### PR TITLE
Torch instance method: amin

### LINKED ISSUE #5889: amin

### PR DESCRIPTION
**Pull request by Dsantra92**
closes #5889

### CODE REVIEW

**Review by simonetgordon — CHANGES_REQUESTED** [review]
Hi there,

This test is failing, and it should be reproducible locally:

```
    def value_test(
        *,
        ret_np_flat,
        ret_np_from_gt_flat,
        rtol=None,
        atol=1e-6,
        ground_truth_backend="TensorFlow",
    ):
        """Performs a value test for matching the arrays in ret_np_flat and
        ret_from_np_flat.
    
        Parameters
        ----------
        ret_np_flat
            A list (flattened) containing Numpy arrays. Return from the
            framework to test.
        ret_np_from_gt_flat
            A list (flattened) containing Numpy arrays. Return from the ground
            truth framework.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the value test passes, else marks the test as failed.
        """
        assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
    
        if type(ret_np_flat) != list:
            ret_np_flat = [ret_np_flat]
        if type(ret_np_from_gt_flat) != list:
            ret_np_from_gt_flat = [ret_np_from_gt_flat]
>       assert len(ret_np_flat) == len(ret_np_from_gt_flat), (
            "len(ret_np_flat) != len(ret_np_from_gt_flat):\n\n"
            "ret_np_flat:\n\n{}\n\nret_np_from_gt_flat:\n\n{}".format(
                ret_np_flat, ret_np_from_gt_flat
            )
        )
E       AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
E       
E       ret_np_flat:
E       
E       []
E       
E       ret_np_from_gt_flat:
E       
E       [array(0, dtype=uint8)]
```

**Comment by Dsantra92** [comment]
Hi @simonetgordon, I faced a similar issue [here](https://github.com/unifyai/ivy/issues/4896#issuecomment-1260174622_) where we concluded that it's not in the scope of my pr.

**Comment by simonetgordon** [comment]
> Hi @simonetgordon, I faced a similar issue [here](https://github.com/unifyai/ivy/issues/4896#issuecomment-1260174622_) where we concluded that it's not in the scope of my pr.

Hmm, can you try adding `@to_ivy_arrays_and_back` to the function def?

**Comment by Dsantra92** [comment]
The Tensor amin function calls the reduction_ops amin function which already has `@to_ivy_array_and_back`. So it causes an error: 
```
args = ((array(0, dtype=int16),), <function _from_torch_frontend_tensor_to_ivy_array at 0x7ff43a4c3ee0>)
kwargs = {'include_derived': {<class 'tuple'>: True, <class 'list'>: False, <class 'dict'>: False}}

    @functools.wraps(fn)
    def new_fn(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
            return fn(*args, **kwargs)
        except (IndexError, ValueError) as e:
            if ivy.get_exception_trace_mode():
                raise ivy.exceptions.IvyError(fn.__name__, str(e))
            else:
                raise ivy.exceptions.IvyError(fn.__name__, str(e)) from None
        except Exception as e:
            if ivy.get_exception_trace_mode():
>               raise ivy.exceptions.IvyBackendException(fn.__name__, str(e))
E               ivy.exceptions.IvyBackendException: numpy: nested_map: numpy: nested_map: input must be Ivy Torch Tensor

ivy/exceptions.py:65: IvyBackendException
```

**Comment by simonetgordon** [comment]
Hi @Dsantra92, thanks for unpacking this. Indeed it looks like an issue on our end. I will look into it further and get back to you.

**Pull request merged**
