### PR TITLE
Add pad paddle frontend nn common.py

### LINKED ISSUE #19342: pad

### PR DESCRIPTION
**Pull request by NripeshN**
Close #19342

### CODE REVIEW

**Comment by NripeshN** [comment]
add_frontend_checklist

**Comment by NripeshN** [comment]
> Hi @NripeshN can you try resolving the merge conflicts?

Hi, Merge conflicts have been resolved now

**Comment by NripeshN** [comment]
> @NripeshN Can you go through and resolve the test errors that you are seeing in `intelligent-tests-pr / run_tests (1) (pull_request) ` ? Thanks

@RickSanchezStoic Could you please review the test now? It's giving some module not found error and I'm not sure how to fix it.

**Comment by RickSanchezStoic** [comment]
@CatB1t Any ideas why this import error is occurring?

**Comment by NripeshN** [comment]
> @CatB1t Any ideas why this import error is occurring? Meanwhile, @NripeshN can you try updating your fork and getting the latest changes from master?

Hi, merging with upstream fixed the previous error. Now I am getting the following error
ivy.utils.exceptions.IvyBackendException: paddle: pad: cannot unpack non-iterable int object
Any idea on how to fix it?

**Comment by RickSanchezStoic** [comment]
Hey Nripesh, can you fix the merge conflicts?

**Comment by RickSanchezStoic** [comment]
Hey @NripeshN the function is missing an argument  `data_format='NCHW'` the errors seem to be related to that.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
