### PR TITLE
Added implementation and tests for floor_ instance method in PyTorch Frontend

### LINKED ISSUE #17015: floor_

### PR DESCRIPTION
**Pull request by MaiElBaradei**
Close #17015

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by fabriziocacicia — CHANGES_REQUESTED** [review]
The `lint / Check formatting / check-formatting` check is failing. Try to understand why and come up with a solution.

Feel free to ask if are stuck.

**Comment by fabriziocacicia** [comment]
@MaiElBaradei I think you are trying to fix the `lint / Check formatting / check-formatting` manually. That's not the issue you should solve.
Go back to the Setting Up page and try to spot what step you missed. It is a very important step to perform if you want to contribute to `ivy` codebase.
Also, by fixing that step you won't have to worry anymore about linting errors.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by fabriziocacicia** [comment]
@MaiElBaradei can you please merge the changes with master and solve the conflicts so that I can review your PR? thanks 😃

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
