### PR TITLE
Reformatted sigmoid activation

### PR DESCRIPTION
**Pull request by Erij97**

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Erij97 great work. Could you exclude the idea files from your PR. It should be ready to merge soon... : )

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hmmm. I think you might have deleted the idea folder and its showing 89 files changed now.  No worries. Could you revert you last commit and ask for my review. I will try fixing it. Hope it's not too much troube....thnx : )

**Comment by Erij97** [comment]
> Hmmm. I think you might have deleted the idea folder and its showing 89 files changed now. No worries. Could you revert your last commit and ask for my review. I will try fixing it. Hope it's not too much troube....thnx : )

Hello, I'm sorry for this inconvenience and thank you so much for your reviews. I did revert the last commit. If this doesn't work I will try to fix it.

**Comment by Ishticode** [comment]
> Hello, I'm sorry for this inconvenience and thank you so much for your reviews. I did revert the last commit. If this doesn't work I will try to fix it. 

Hi. No Need to apologise. You're doing great. You can leave the PR as is now and hopefully I will be able to get it merged in the morning after a small edit. Thnx a lot 🙂

**Comment by Erij97** [comment]
> > Hello, I'm sorry for this inconvenience and thank you so much for your reviews. I did revert the last commit. If this doesn't work I will try to fix it.
> 
> Hi. No Need to apologise. You're doing great. You can leave the PR as is now and hopefully I will be able to get it merged in the morning after a small edit. Thnx a lot 🙂

Ok, Thank you so much for your assistance. 🙂

**Review by Ishticode — APPROVED** [review]
Looking good now. I will go ahead and merge it now. Thnx for the contribution 🙂

**Pull request merged**
