### PR TITLE
Add nansum

### LINKED ISSUE #22513: nansum
- [ ] #15115

### PR DESCRIPTION
**Pull request by Bhargav4223**
# PR Description 
Adding nansum instance method.

## Related Issue 

Close #22513

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Bhargav4223** [comment]
Hey, Can you suggest the required changes for the failing checks ?

**Comment by KareemMAX** [comment]
ivy-gardener

**Comment by KareemMAX** [comment]
Hey @Bhargav4223, I've called for `ivy-gardener` which should fix the lint error you are having automatically.

To make sure this doesn't happen again you may look into [how to install `pre-commit`](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit), and our [formatting deepdive](https://unify.ai/docs/ivy/overview/deep_dive/formatting.html).

[Context](https://discord.com/channels/799879767196958751/1028266706436624456/1148255022417715260)

**Comment by Bhargav4223** [comment]
Hey @zhumakhan can you help me review this PR and suggest some required changes ?

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hey @Bhargav4223,
Looks like your implementation doesn't match [paddlepaddle's signature](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/Tensor_en.html#:~:text=Computes%20the%20sum%20of%20tensor%20elements%20over%20the%20given%20axis%2C%20treating%20Not%20a%20Numbers%20(NaNs)%20as%20zero.). We can't move further with the PR without fixing that issue

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
