### PR TITLE
new activation function (tanh) has been added

### PR DESCRIPTION
**Pull request by roostamovic**
I added a new activation function tanh() to all the required files such as NumPy, PyTorch, TensorFlow, Jax and etc

### CODE REVIEW

**Comment by JerryGCDing** [comment]
Hi @roostamovic, apologize for the late response. Is there a linked issue to this PR?

**Comment by roostamovic** [comment]
I was unable to link issue to this PR, but issue is available in https://github.com/unifyai/ivy/issues/5446

**Comment by roostamovic** [comment]
A staff of you solved this issue after my publishment

**Comment by djl11** [comment]
Hi @roostamovic, this function is already added elsewhere in the code, and so it is not needed. Thanks for the effort anyway! Please feel free to select one of the [open tasks](https://lets-unify.ai/ivy/contributing/4_open_tasks.html) instead if you would like to contribute :)

**Pull request closed without merging**
