### PR TITLE
added broadcast_tensors from

### LINKED ISSUE #24140: broadcast_tensors

### PR DESCRIPTION
**Pull request by odunola499**
# PR Description

## Related Issue

Fixes #24140 

## Checklist

- [x]  Did you add a function?

- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials:

https://twitter.com/Jenrola_odun

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by odunola499** [comment]
Hello!
i have successfully linked the PR to the issue i created earlier

**Comment by odunola499** [comment]
hello @rishabgit  please can you help check out my code plus the tests i wrote. i cannot seem to get the tests to pass. I am guessing the tests isnt generating the right data for the functions. please help

**Comment by odunola499** [comment]
hiii @rishabgit please can you check my PR

**Pull request closed without merging**
