### PR TITLE
rectify `check_shape`

### PR DESCRIPTION
**Pull request by adityagandhamal**
While working on https://github.com/unifyai/ivy/pull/20160, found that the expression for checking the inequality in shapes wasn't working as expected. The function in the subject does not return an error message (while it should) for arrays differing in shape.

### CODE REVIEW

**Comment by adityagandhamal** [comment]
To reproduce:
```
>>> print(ivy.utils.assertions.check_shape(ivy.array([1]), ivy.array([2, 3])))
>>> None
```

Expected Behaviour:

```
>>> print(ivy.utils.assertions.check_shape(ivy.array([1]), ivy.array([2, 3])))
Traceback (most recent call last):
  File "demo.py", line 74, in <module>
    print(ivy.utils.assertions.check_shape(ivy.array([1]), ivy.array([2, 3])))
  File "/home/adubuntu/ivy/ivy/ivy/utils/assertions.py", line 174, in check_shape
    raise ivy.utils.exceptions.IvyException(message)
ivy.utils.exceptions.IvyException: ivy.array([1]) and ivy.array([2, 3]) must have the same shape (ivy.Shape(1,) vs ivy.Shape(2,))

```

**Comment by adityagandhamal** [comment]
This is mainly because `ivy.shape(x1) != ivy.shape(x2)` evaluates a comparison between the shapes `ivy.Shape(1,)` and `ivy.Shape(2,)`  for x1 and x2 respectively, whereas it has to be evaluated elementwise as such `(1,)` and `(2,)`

**Comment by V-G-spec** [comment]
Hey @adityagandhamal apologies for the mild ignorance. But do you need my input on anything here? Seems you have figured it out. 
If that's the case, can you ensure the failing tests don't originate from your changes. Also, can you please share the screenshot of tests passing on your local machine in this case?

**Comment by adityagandhamal** [comment]
> can you ensure the failing tests don't originate from your changes. Also, can you please share the screenshot of tests passing on your local machine in this case?

Hey @V-G-spec, I can confirm that the failing tests do not originate from my changes and yes the test cases are passing locally.

Screenshot (1387)

**Comment by adityagandhamal** [comment]
Once this is merged, https://github.com/unifyai/ivy/pull/20160 can be ready for a review.

**Comment by V-G-spec** [comment]
Understood. Just took a look at your changes and other PR you had linked. Sorry for wasting your time on checking the logs

**Pull request merged**
