### PR TITLE
reformatted trunc #2264

### PR DESCRIPTION
**Pull request by azazrashid**

### CODE REVIEW

**Comment by sherry30** [comment]
Hi,

Just leave a comment here whenever you're done making changes, so I'll know its ready for a review 😃 

Also feel free to ask any question if you have, I'd be happy to help you out.

Thanks.

**Comment by azazrashid** [comment]
Hi, Can you tell me a little about the changes that need to be made? Thanks.

**Comment by sherry30** [comment]
Sure,

So your functional examples look good, you need to add following changes:

1. Add array instance method example in `ivy/array/elementwise.py`.
2. Add container instance method example in `ivy/container/elementwise.py`.
3. Add an example for static container function in `ivy/container/elementwise.py`.

All of these requirements are listed [here](https://github.com/unifyai/ivy/blob/48069d3a774e279eec2a4fb85b7ace69a8925291/docs/partial_source/deep_dive/13_docstring_examples.rst) in great detail. Let me know if you have anymore questions.

Thanks

**Comment by sherry30** [comment]
Hi,

closing this due to inactivity, you can reopen this PR whenever you want if the function has not been deallocated from you.

Thanks

**Pull request closed without merging**
