### PR TITLE
atan adhering to Array API Standard.

### PR DESCRIPTION
**Pull request by Darshan-H-E**

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Please could you ensure there are no changes to the .idea files in your commit. Also could you implement `atan` for the torch backend also 🙂

**Comment by Darshan-H-E** [comment]
I've resolved all the conflicts and it passes all the tests now. Please
review the PR

**Comment by mattbarrett98** [comment]
You've closed the PR, maybe by accident?

**Comment by Darshan-H-E** [comment]
Yeah by mistake I closed the first PR.

**Comment by mattbarrett98** [comment]
Hi if you look under 'files changed', there are changes to a number of .idea files, you need to ensure that you haven't made any changes to these files. Thanks 🙂

**Comment by Darshan-H-E** [comment]
So should I make changes again and resolve the conflicts in this PR and close the latest one?

**Comment by Darshan-H-E** [comment]
> Hi if you look under 'files changed', there are changes to a number of .idea files, you need to ensure that you haven't made any changes to these files. Thanks 🙂
Yeah I apologize for making changes in the .idea files. 
https://github.com/unifyai/ivy/pull/646 . In this pull request I have made sure that I haven't done any changes to the above mentioned files. And it has conflicts with the master.

**Comment by mattbarrett98** [comment]
Apologies I didn't realise you'd made another PR, I'll check it out now!

**Pull request closed without merging**
