### PR TITLE
gather_nd #23326

### LINKED ISSUE #23326: gather_nd

### PR DESCRIPTION
**Pull request by so-dipe**
# PR Description
I wrote the frontend for gather_nd for paddle. I noticed that all the other functions had no test written for them so I assumed one wasn't necessary.

## Related Issue

Close #23326

## Checklist

- [ Yes] Did you add a function?
- [ ] Did you add the tests?
- [ Yes] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by saeedashrraf** [comment]
Hello @so-dipe ,

It seems like the function you picked is already assigned to another person who opened an issue for it. This means that they are working on writing the code for that function. Could you please choose a different function that is not taken by anyone else? I appreciate your cooperation and I hope this is clear. Thanks!

**Comment by so-dipe** [comment]
Hi, sorry for the confusion. I opened the issue but I forgot how to link the issue to the PR. But I think I fixed that. Thanks.

**Comment by saeedashrraf** [comment]
Hello @so-dipe , Thank you so much for your contribution. As per the [contributors guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis), you should also add the tests to make sure the implemented function works correctly as shown. This is explained in more details [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html). You should also make sure the function passes the tests successfully. Let me know if you have any questions and thanks again!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
