### PR TITLE
Implement max_unpool2d

### LINKED ISSUE #19761: max_unpool2d

### LINKED ISSUE #21762: max_unpool2d
#3856

### PR DESCRIPTION
**Pull request by weronikazak**
Close #19761 
Close #21762

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by weronikazak** [comment]
ivy-gardener

**Comment by weronikazak** [comment]
The lint errors aren't a part of my code and I can't seem to get rid of them :/

**Comment by theRealBird** [comment]
Hi @weronikazak,
Thank you for contributing to Ivy!
For future contributions, please remember to correctly link your PR with the open issue, as explained in the contributing guide. I will do it for you this time :) 
Close #19761 
Your PR looks great to me! It does not introduce any new failures. The linter-errors are on code which you did not write, so don't worry about those! 
I will take a closer look once more before merging it. Thanks!

**Comment by theRealBird** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

For more details, refer to the comment left by the bot here.

**Comment by weronikazak** [comment]
> > If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> > For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> > Thank you 🤗
> 
> For more details, refer to the comment left by the bot here.

Ah, my bad! Sorry, corrected it now.

**Comment by theRealBird** [comment]
Hi @weronikazak, I see that you have implemented both the frontend and the backend for `max_unpool2d`. Can you please create a new issue and link it to this open task https://github.com/unifyai/ivy/issues/3856 which is asking for an implementation of `max_unpool2d` in the ivy backend?
Once the issue is created, please link it in the description of this PR.
This will help us keep track of what has been implemented and what's missing!
Thanks - feel free to ask any questions

**Comment by weronikazak** [comment]
> Hi @weronikazak, I see that you have implemented both the frontend and the backend for `max_unpool2d`. Can you please create a new issue and link it to this open task #3856 which is asking for an implementation of `max_unpool2d` in the ivy backend? Once the issue is created, please link it in the description of this PR. This will help us keep track of what has been implemented and what's missing! Thanks - feel free to ask any questions

Done!

**Comment by theRealBird** [comment]
Great! Merging now

**Comment by theRealBird** [comment]
Hi @weronikazak,
I accidentally merged your PR without checking whether you the function was implemented for every back-end or not. This one is on me! My sincerest apologies. 

In order for us to close #21762, Max Pool will need to be implemented in all 5 frameworks as is mentioned in the description.

Also, don't worry! Incase you do not have these changes saved locally at the moment, you can always cherry-pick these commits and create a new PR.

I understand that this seemingly simple frontend function implementation is getting quite lengthy and complicated now. Thank you so much for your patience!

**Comment by theRealBird** [comment]
Sadly, I won't be able to open this PR again. You will have to create a new one. Please mention me on the new one so that I can quickly assign it to myself and review it. 
Also, do not feel compelled to work on this issue. You can take up a new one if you wish. Thanks again!

**Pull request merged**
