### PR TITLE
Numpy frontend prod

### PR DESCRIPTION
**Pull request by sergio-verduzco**

### CODE REVIEW

**Comment by suvadityamuk** [comment]
Hi, @sergio-verduzco!

Thank you for your contribution! 

Please take some time to address comments on the PR!

Also, it seems the test you have written for this function does not pass. Do you mind taking another look at it and seeing if it could be repaired?
Along with that, it seems that there is a [linting error here](https://github.com/unifyai/ivy/actions/runs/4330177927/jobs/7561233269#step:5:32). Do you mind using the [pre-commit hook](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit) to allow for linting the commits? :slightly_smiling_face:

**Comment by sergio-verduzco** [comment]
Thank you for your advice @suvadityamuk !
Here's another try at a good implementation of the Numpy `prod` instance method.
This version is simpler, and all tests pass, except for one case where the Ivy API `prod` (which I use for the instance method) fails.
Also, I am currently using only the `True` value for the `where argument; otherwise I get an error that I can't reproduce when running the falsifying example. I will continue looking into that, but if you happen to know how to fix this, I would be really grateful.

**Comment by suvadityamuk** [comment]
Hi, @sergio-verduzco! Thanks for bringing it back, and apologies for the delay, been a bit swamped! :sweat_smile: 

It seems that your test still doesn't pass for that one specific function, while there seems to still be a [linting error here](https://github.com/unifyai/ivy/actions/runs/4371026463/jobs/7646510526#step:5:27).

Do you mind expanding further on this error and the test case? If it seems to be important, you can try making a PR for that as well. 

Thanks again! :smile:

**Comment by sergio-verduzco** [comment]
Hey @suvadityamuk !
I am testing this in the Docker environment within VSCode. In a terminal, the test for the Numpy frontend `prod` method 
`pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_sums_products_differences.py::test_numpy_prod`

returns this message:

`FAILED ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_sums_products_differences.py::test_numpy_prod[cpu-ivy.functional.backends.tensorflow-False-False] - ivy.utils.exceptions.IvyBackendException: tensorflow: concat: {{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Dimension 0 in both shapes must be equal: shape[0] = [1,1] vs. shape[1] = [2,2] [Op:ConcatV2] name: concat`

Two other error messages appear about 50% of the time:
`FAILED ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_prod[cpu-ivy.functional.backends.torch-False-False] - ivy.utils.exceptions.IvyBackendException: torch: prod: "prod_cpu" not implemented for 'Half'`

`FAILED ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_prod[cpu-ivy.functional.backends.jax-False-False] - AssertionError:  the results from backend jax and ground truth framework numpy do not match`

These same errors are displayed when I test my own instance method as
`pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_prod`

Here is a minimal example to reproduce the TensorFlow error:
```
import ivy.functional.frontends.numpy as ivy_np
ivy.set_backend('tensorflow')

a =  ivy_np.array([[0, 0], [0, 0]], dtype='uint16')
prod = ivy_np.prod(a, axis=-1, dtype='uint16', keepdims=False)
```
The error does not appear with `axis=0` or `axis=1`. A little digging suggests that the error is on handling of the `initial` argument in the frontend `prod`. Is this important?

**Comment by suvadityamuk** [comment]
Hi, @sergio-verduzco!

Thank you so much for the resolution of the errors. Is it possible for you to let me know where that problem is? I'll quickly fix, test and push it, which should lead to your tests passing :smile: 

Once the CI is green, we can do a quick sprint and get this merged!

**Comment by sergio-verduzco** [comment]
Hello @suvadityamuk. Sorry, this message slipped under the radar.

Regarding the error involving TensorFlow and `concat`, I made a PR, and it got merged 5 days ago. That error is gone :)

As I commented before, there are two more errors in the frontend `prod` that propagate to the instance method. These errors appear occasionally on the tests. I still haven't figured out where those two come from.

**Comment by suvadityamuk** [comment]
Hi, @sergio-verduzco!

It seems, due to the `git push --force`, the commit hashes have changed, leading to this PR not being merge-able. Do you mind making a new PR with the changes you introduced, on a fresh fork?
Sorry for the inconvenience! :slightly_smiling_face:

**Comment by sergio-verduzco** [comment]
Hello @suvadityamuk.
While making a new PR I noticed that someone else had also implemented the `prod` method. A quick search revealed [this PR](https://github.com/unifyai/ivy/pull/13044).

Somehow, after the `git push --force` the issue got reopened and someone else implemented the method.

What is the procedure at this point?

**Pull request closed without merging**
