### PR TITLE
refactor: remove infer_device and rename handle_device_shifting decorator

### PR DESCRIPTION
**Pull request by ShreyanshBardia**
# PR Description

## Related Issue

Close [task](https://trello.com/c/9wR0CDCh/2700-remove-inferdevice-and-rename-handledeviceshifting-decorator)

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by vedpatwardhan — COMMENTED** [review]
Looks good to me on a high level, but I'll leave this with @sherry30 to review as he's the author of the task. Thanks @ShreyanshBardia @sherry30 😄

**Review by sherry30 — APPROVED** [review]
Hi Shreyansh,
can you run the following tests and make sure its working fine on your PR.
```
# testing device argument ##full_like ##arange
import ivy
# ivy.set_backend("paddle")
# ivy.set_backend("tensorflow")
# ivy.set_backend("jax")
ivy.set_backend("torch")
# ivy.set_backend("numpy")

ivy.set_soft_device_mode(False)
ivy.set_default_device("cpu")
x = ivy.array([1, 2, 3], device="cpu")
gpu_dev = "gpu:0"

# device is passed with arrays ## device
y = ivy.full_like(x, 3, device=gpu_dev)
print(y.device)

# device is passed without arrays ##device
y = ivy.arange(0, 10, device=gpu_dev)
print(y.device)

# device is not passed with arrays ##array dev
y = ivy.full_like(x, 3)
print(y.device)

# device is not passed without arryas ##default
y = ivy.arange(0, 10)
print(y.device)


# testing device argument ##full_like ##arange # soft_device mode True

import ivy
# ivy.set_backend("paddle")
# ivy.set_backend("tensorflow")
# ivy.set_backend("jax")
ivy.set_backend("torch")
# ivy.set_backend("numpy")

ivy.set_soft_device_mode(True)
ivy.set_default_device("gpu:0")
x = ivy.array([1, 2, 3], device="cpu")
cpu_dev = "cpu"

# device is passed with arrays ## device
y = ivy.full_like(x, 3, device=cpu_dev)
print(y.device)

# device is passed without arrays ##device
y = ivy.arange(0, 10, device=cpu_dev)
print(y.device)

# device is not passed with arrays ##default
y = ivy.full_like(x, 3)
print(y.device)

# device is not passed without arryas ##default
y = ivy.arange(0, 10)
print(y.device)
```
If it works fine on these then its good to merge
Another thing we have to make sure.
In all the backend functions, the device argument is not being used anywhere (for functions that accept a device argument).
torch is an exception of this.
Let me know if you have any questions

**Comment by ShreyanshBardia** [comment]
The following code snippet seems to be generating error

```
>>> import ivy
>>> ivy.set_backend("torch")
>>> ivy.set_soft_device_mode(False)
>>> ivy.set_default_device("cpu")
>>> x = ivy.array([1, 2, 3], device="cpu")
>>> gpu_dev = "gpu:0"
>>> # device is passed with arrays ## device
>>> y = ivy.full_like(x, 3, device=gpu_dev)
<traceback object at 0x7fe78cf1ff40>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 1560, in _handle_backend_invalid
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 969, in _handle_nestable
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 417, in _handle_array_like_without_promotion
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 861, in _handle_out_argument
    return fn(*args, out=out, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 457, in _inputs_to_native_arrays
    return fn(*new_args, **new_kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 563, in _outputs_to_ivy_arrays
    ret = fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 372, in _handle_array_function
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 771, in _infer_dtype
    return fn(*args, dtype=dtype, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 815, in _handle_device
    with ivy.DefaultDevice(ivy.default_device(dst_dev)):
  File "/home/shreyansh/Documents/ivy/ivy/functional/ivy/device.py", line 136, in __exit__
    raise exc_val
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 816, in _handle_device
    return ivy.handle_soft_device_variable(*args, fn=fn, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/functional/backends/torch/device.py", line 117, in handle_soft_device_variable
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/functional/backends/torch/creation.py", line 270, in full_like
    return torch.full_like(x, fill_value, dtype=dtype, device=device)
RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: gpu

```

**Comment by ShreyanshBardia** [comment]
```
 y = ivy.full_like(x, 3)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 1560, in _handle_backend_invalid
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 969, in _handle_nestable
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 417, in _handle_array_like_without_promotion
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 861, in _handle_out_argument
    return fn(*args, out=out, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 457, in _inputs_to_native_arrays
    return fn(*new_args, **new_kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 563, in _outputs_to_ivy_arrays
    ret = fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 372, in _handle_array_function
    return fn(*args, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 771, in _infer_dtype
    return fn(*args, dtype=dtype, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 815, in _handle_device
    with ivy.DefaultDevice(ivy.default_device(dst_dev)):
  File "/home/shreyansh/Documents/ivy/ivy/functional/ivy/device.py", line 136, in __exit__
    raise exc_val
  File "/home/shreyansh/Documents/ivy/ivy/func_wrapper.py", line 816, in _handle_device
    return ivy.handle_soft_device_variable(*args, fn=fn, **kwargs)
  File "/home/shreyansh/Documents/ivy/ivy/functional/backends/torch/device.py", line 117, in handle_soft_device_variable
    return fn(*args, **kwargs)
TypeError: full_like() missing 1 required keyword-only argument: 'device'


```

**Comment by ShreyanshBardia** [comment]
Can you review my last commit @sherry30, I think this should solve the issue.

**Comment by ShreyanshBardia** [comment]
I don't understand this statement of yours
`
Another thing we have to make sure.
In all the backend functions, the device argument is not being used anywhere (for functions that accept a device argument).
`

Do you mean we shouldn't be passing `device` through kwargs also? Because this is what is happening currently which is generating error because in `creation` functions `device` is a required keyword argument

**Comment by vedpatwardhan** [comment]
> No what I meant was, the functions will still have the `device` argument in the backend, but it will be unused in all the backends. Since we removed manual device shifting, it shouldn't be used anywhere in the backend functions with torch backend as an exception.
> 
> About the other problem, yea I guess we can give it a default value of `None` in all the backend functions. because there's no need to pass a device argument to them everytime since `infer_device` is removed. What do you think @vedpatwardhan

I'm not completely sure if I understand this, but do you mean given that we've got the context manager working with the device shifting decorator we wouldn't need to pass the `device` argument to creation functions in the backends for e.g.? Certainly if those functions also operate on the correct device through the context manager, we should consider not using the `device` argument in the implementation of creation functions either, but there were a few corner cases right? Do they play a role here?
Thanks @sherry30 😄

**Comment by sherry30** [comment]
Yep that's what I meant, the corner cases are in torch, but we can still pass in the default value of `device` as `None` just for consistency. The value of device will be passed by the `handle_soft_device_variable` in the torch backend.

**Comment by vedpatwardhan** [comment]
sounds good! As long as the op for functions using `infer_device` currently is executed on the expected device, this approach works for me. Thanks for clarifying @sherry30 😄

**Comment by ShreyanshBardia** [comment]
@sherry30 should I update default values to `None` then?

**Comment by sherry30** [comment]
Yes, you can set them as `None` by default @ShreyanshBardia

**Comment by ShreyanshBardia** [comment]
@sherry30 can you take a look now

**Review by sherry30 — APPROVED** [review]
lgtm!
Lets get one final review from @vedpatwardhan before merging

Thanks

**Review by vedpatwardhan — APPROVED** [review]
I haven't one through the code line by line but seems good to merge, thanks @ShreyanshBardia @sherry30 😄

**Pull request merged**
