### PR TITLE
Added floor to paddle.tensor.math frontend and added related tests

### PR DESCRIPTION
**Pull request by xhr0no**

### CODE REVIEW

**Comment by xhr0no** [comment]
Closes #16083

**Comment by hmahmood24** [comment]
Everything looks good to merge. Thanks @xhr0no! 🚀

**Comment by xhr0no** [comment]
> Hey @xhr0no. Everything looks good to merge. Could you just resolve the merge conflicts so we can merge the PR? Thanks! 😃

Done. Thanks

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @xhr0no. There are some [lint/formatting](https://github.com/unifyai/ivy/actions/runs/5158624262/jobs/9292518362?pr=16130#step:5:104) issues after the merge. Can you kindly resolve those? Please use [pre-commit](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit) to resolve your linting issues and make your code adhere to the coding practices set at Ivy. Kindly ask for a re-review once done. Thanks! :)

**Comment by xhr0no** [comment]
Sorry my mistake, i didn't realise that github's code editor to resolve conflicts didn't run any of the linting functions

**Comment by xhr0no** [comment]
@hmahmood24 mind reviewing the changes? Thanks

**Review by hmahmood24 — APPROVED** [review]

**Comment by hmahmood24** [comment]
Seems good to merge now. Thanks a lot @xhr0no! 😄

**Pull request merged**
