### PR TITLE
feat: added avg_pool2d to tensorflow frontend

### LINKED ISSUE #22783: avg_pool2d

### PR DESCRIPTION
**Pull request by adityadeshmukh369**
# PR Description
Fixes #22783
- Added avg_pool2d function to tensorflow frontend.

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by adityadeshmukh369** [comment]
I have updated the issue number.

**Comment by adityadeshmukh369** [comment]
@nathzi1505 can you review my PR and suggest the changes pls.

**Comment by nathzi1505** [comment]
Looks good. Can you please fix the linting issues for me?

**Comment by adityadeshmukh369** [comment]
@nathzi1505 I am new to open source can you guide me on resolving the linting issues ?

**Comment by adityadeshmukh369** [comment]
@nathzi1505 can you review the changes?

**Pull request merged**
