### PR TITLE
Add jax frontend packbits function and test

### LINKED ISSUE #17711: packbits

### PR DESCRIPTION
**Pull request by borangoher**
Close #17711

### CODE REVIEW

**Comment by MuhammadSaeedBatikh** [comment]
Hi @borangoher, thanks for the PR.
When tested locally, I get the following exceptions:
1- at `x = ivy.swapaxes(x, axis, -1)`
`numpy.AxisError: axis1: axis 0 is out of bounds for array of dimension 0`
Could you please add proper checks for such corner cases. 
Also, the test function needs to change accordingly:
```
dtype_and_x=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("valid"),
        min_num_dims=1,
        min_dim_size=1,
    ),
```
It should look something like this: `tuple(x.shape[:-1] + [x.shape[-1] // 8, 8])`.

2- at `bits = ivy.expand_dims(bits, tuple(range(x.ndim - 1)))`
`TypeError: expand_dims() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given`
Please add `axis` as a keyword:
`bits = ivy.expand_dims(bits, axis=tuple(range(x.ndim - 1)))`

3- I'm not sure about this line `ivy.reshape(x, -1)`. In addition to the exception raised, it seems like a flatten operation with no assignment. Maybe change it to  `x = ivy.flatten(x)`?

4- at `x = x.reshape(x.shape[:-1] + (x.shape[-1] // 8, 8))`
`TypeError: can only concatenate list (not "tuple") to list`
It needs to be `tuple(x.shape[:-1] + [x.shape[-1] // 8, 8])` 

P.S.
Please make sure that tests pass locally. Also, the tests need to be more exhaustive and include the rest of the arguments, namely; `axis`, and  `bitorder`.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by borangoher** [comment]
Hey, @MuhammadSaeedBatikh , can you review again please?

**Comment by MuhammadSaeedBatikh** [comment]
Hi @borangoher, thanks for your modifications.
-There's a missing reshape function; it should be `x = ivy.reshape(x, list(x.shape[:-1]) + [x.shape[-1] // 8, 8])` instead of ` x = tuple(x.shape[:-1] + [x.shape[-1] // 8, 8])`.

-When running the tests, I get `TypeError: packbits() got an unexpected keyword argument 'x'`. Please change the signature of `packbits` to `packbits(x, /, *, axis=None, bitorder="big")` similar to ivy functions.

-I also encountered the following error:
```
at      packed = (x << bits).sum(-1).astype("uint8")
E       TypeError: sum() takes 1 positional argument but 2 were given
```
Notice that `.sum(-1)` is calling `ivy.sum` which has the signature:
```
def sum(
    x: Union[ivy.Array, ivy.NativeArray],
    /,
    *,
    axis: Optional[Union[int, Sequence[int]]] = None,
    ....
 ```

Therefore, axis has to be passed as a keyword argument: `.sum(axis=-1)`

More importantly, there's a mismatch between ground-truth returned shape and the current implementation.
```
E               AssertionError: returned shape = (1, 8), ground-truth returned shape = (1, 1)
E               Falsifying example: test_jax_numpy_packbits(
E                   dtype_x_axis=(['int16'], [array([[0]], dtype=int16)], 0),
E                   bitorder='big',
``` 
The following simple example proves the case:
```
import ivy, jax.numpy as jnp, numpy as np
import ivy.functional.frontends.jax as ijax
a = ivy.array([[[1,0,1],
               [0,1,0]],
              [[1,1,0],
               [0,0,1]]])
print('numpy:',np.packbits(a.to_numpy(), axis=-1))
print('jax:',jnp.packbits(a.to_numpy(), axis=-1))
print('ivy:', ijax.numpy.packbits(a, axis=-1))
```
produces the following output:
```
numpy: [[[160]
  [ 64]]
 [[192]
  [ 32]]]
jax: [[[160]
  [ 64]]
 [[192]
  [ 32]]]
ivy: ivy.frontends.jax.DeviceArray([[
       [160],
        [ 64],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],
       [[192],
        [ 32],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],
       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],
       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],
       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],
       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],
       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]]], dtype=uint8)

```
My guess is there's a problem with the padding :
```
    if remainder:
        pad_config = [(0, 8 - remainder)]
        x = ivy.zero_pad(x, pad_config)
```

**Comment by MuhammadSaeedBatikh** [comment]
Hi @borangoher, thanks for your modifications. All tests now pass. 
Yes, a helper function is OK. However, it needs to be internal/private (starts with underscore) and placed at the begging of the file. So maybe rename the helper method to `_packbits_nested_list_padding` to indicate why it's there and place it at the beginning of the file (i.e. after import statements: `from ivy.utils.exceptions import IvyNotImplementedException`)
Other than that, everything lgtm.

**Comment by borangoher** [comment]
Hi @MuhammadSaeedBatikh. Thanks for the review! I have modified the helper function according to your comments, I think it should be all OK now.

**Comment by MuhammadSaeedBatikh** [comment]
lgtm.

**Pull request merged**
