### PR TITLE
Linear algebra function lu_solve

### PR DESCRIPTION
**Pull request by KartikeyDubeyKD**

### CODE REVIEW

**Comment by KartikeyDubeyKD** [comment]
#14898

**Comment by Ookamice** [comment]
Hiya the code looks good, but there's some failing tests with `ModuleNotFoundError: No module named 'ivy.functional.frontends.ivy`.  I believe this could be an issue with out github intelligent tests rather than an issue with your code.

Let me know if your tests pass locally and I'll try the same and get it merged for you! 😊

**Comment by KartikeyDubeyKD** [comment]
ok sir

**Comment by KartikeyDubeyKD** [comment]
I'm not getting this error locally, Sir can you please check it once thanks for the review.

**Comment by Ookamice** [comment]
@KartikeyDubeyKD 

Just had a more detailed look into the code base, I would recommend you to follow the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) instead in the event that a `ivy.<func_name>` is missing rather than try to add you own.

So far, you have only added the frontend implementation of lu_solve and missing all the backend of it for every framework that ivy supports. This is a pretty daunting task!

Let me know if you're still willing to continue with this by writing a composite function for ivy.lu_solve instead or pursue a different task ☺

**Comment by KartikeyDubeyKD** [comment]
Thank you for checking, sir. I am confident that I can complete this function, and I have already opened a PR. I will merge it, sir.

**Comment by Ookamice** [comment]
Hiya, 👋

It's great that you're enthusiastic and willing to give it a go. However, I would highly recommend following the steps in the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) which will help Ivy's organisation of tasks a lot!

You can feel free to work on implementing ivy.lu_solve once your issue gets approved. 😃 

Let me know if you have any questions. Thank you!

**Comment by KartikeyDubeyKD** [comment]
got it

**Comment by KartikeyDubeyKD** [comment]
First, I have to create the new issue name lu_solve right?

**Comment by Ookamice** [comment]
@KartikeyDubeyKD Yes, and please add the corresponding labels as according to the contributor's guide!👍

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
