### PR TITLE
logit fixed

### LINKED ISSUE #17362: logit

### PR DESCRIPTION
**Pull request by shivam-151197**
Close #17362

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
Hi @shivam-151197 can you please resolve the merge conflicts here? Thanks!

**Comment by shivam-151197** [comment]
@RickSanchezStoic While I was solving the the issue I tried to make commit pre-commit informed that logit function is already there. I created the issue and issue is still open. How that is possible.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @shivam-151197 

This function is already implemented in the frontends here https://github.com/unifyai/ivy/blob/628b8d91701e22033f1e9973bef8e5e575b3ad48/ivy/functional/frontends/paddle/tensor/math.py#L296

**Comment by shivam-151197** [comment]
@hirwa-nshuti when I started this issue it wasn't implemented at all. It's been more 10 days.Since I opened this issue.

**Comment by hirwa-nshuti** [comment]
Hey @shivam-151197 

We are sorry for the inconvenience caused, this is an error at our end we didn't notice duplicity of the subtasks, you can still submit this PR as code challenge, also feel free to work on other open tasks😊

Thanks again for being patient🤞

**Pull request closed without merging**
