### PR TITLE
solve-paddle-frontend

### LINKED ISSUE #17006: solve

### PR DESCRIPTION
**Pull request by selvaraj-sembulingam**
Close #17006

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by aparajith21** [comment]
Hey, thanks for contributing, all LGTM, but please comment `add_frontend_checklist` and edit and confirm with the checklist please, thanks!

**Comment by selvaraj-sembulingam** [comment]
add_frontend_checklist

**Comment by aparajith21** [comment]
LGTM! Thanks for contributing!

**Pull request merged**
