### PR TITLE
Torch take

### LINKED ISSUE #14249: take

### PR DESCRIPTION
**Pull request by Plutone11011**
Close #14249

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Plutone11011** [comment]
@YushaArif99 could you give it a look?

**Comment by YushaArif99** [comment]
Hi @Plutone11011 

I'll be reviewing this PR shortly. Apologies for the delay though. Was quite swamped with work last week and so reviewing this PR totally slipped under my radar. 

Thanks for your patience! 😄

**Review by YushaArif99 — COMMENTED** [review]
Hi @Plutone11011 

The PR looks good overall. The CI tests though don't seem to be running the tests for `torch.take` for some reason 😅. Could you kindly verify that the tests are passing on your local setup? I'll also be trying to manually run the tests on codespaces. Once all the tests are passed, we can then merge this PR.

**Comment by Plutone11011** [comment]
> Hi @Plutone11011
> 
> The PR looks good overall. The CI tests though don't seem to be running the tests for `torch.take` for some reason 😅. Could you kindly verify that the tests are passing on your local setup? I'll also be trying to manually run the tests on codespaces. Once all the tests are passed, we can then merge this PR.

Hi, I've run the tests locally and they pass

**Review by YushaArif99 — APPROVED** [review]

**Pull request merged**
