### PR TITLE
ci: improve the comment message

### PR DESCRIPTION
**Pull request by a0m0rajab**
# PR Description

this PR introduces a message to show for contributors when they open a PR that provides them the content of the CI errors.

### CODE REVIEW

**Review by vedpatwardhan — COMMENTED** [review]
Hey @a0m0rajab, thanks for creating the PR! Is there a way we could test this out before merging? Just wanted to have a look at the formatting of the final message 😄

**Comment by a0m0rajab** [comment]
@vedpatwardhan thanks, here is a simple example that I made before: https://github.com/unifyai/ivy_test_lint/pull/11 
for this one what we will have is the message printed in the action copied to the PR

**Comment by a0m0rajab** [comment]
This would be the expected messages: 

# On new failures: 
Thank you for this PR, here is the CI results: 

-------------
This PR introduces the following new failing tests:
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_ilshift__,numpy
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_ilshift__,jax
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_ilshift__,tensorflow
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_ilshift__,paddle
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_ilshift__,torch
ivy_tests/test_ivy/test_functional/test_core/test_nest.py::test_insert_into_nest_at_indices,numpy
ivy_tests/test_ivy/test_functional/test_core/test_nest.py::test_insert_into_nest_at_indices,jax
ivy_tests/test_ivy/test_functional/test_core/test_nest.py::test_insert_into_nest_at_indices,tensorflow
ivy_tests/test_ivy/test_functional/test_core/test_nest.py::test_insert_into_nest_at_indices,torch
ivy_tests/test_ivy/test_functional/test_core/test_nest.py::test_insert_into_nest_at_indices,paddle

# Without new failures: 
Thank you for this PR, here is the CI results: 

-------------
this PR does not introduce any new test failures! Yippee!

**Comment by a0m0rajab** [comment]
Side note this is an initial iteration, we should add emojis and make the message more user friendly later.

**Comment by vedpatwardhan** [comment]
Yeah sounds good! I think we can make the message a bit more but I'll leave it with you and @KareemMAX to decide how the message should look like 😄

**Comment by a0m0rajab** [comment]
Internal notes: 
@guillesanbri asked to change the message to more formal one. 
@KareemMAX suggested to improve the message later. 

Merging this as first iteration.

**Pull request merged**
