### PR TITLE
Add random.multinomial to Paddle Backend

### LINKED ISSUE #17424: multinomial

### PR DESCRIPTION
**Pull request by mohame54**
close #17424

### CODE REVIEW

**Comment by mohame54** [comment]
@MahmoudAshraf97  I am ready for the interview

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
why not use this directly?
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/multinomial_en.html#multinomial

**Comment by mohame54** [comment]
> why not use this directly? https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/multinomial_en.html#multinomial

Oh sorry, when I searched I didn't find it i will change it at once.

**Review by MahmoudAshraf97 — APPROVED** [review]
Great Work @mohame54

**Pull request merged**
