### PR TITLE
Softsign operation is Added.

### PR DESCRIPTION
**Pull request by galaxygummybear**
Pull request for issue #22161

Good day! I have added the Softsign operation, but unfortunately, the test doesn't pass. I received an AttributeError. I believe this might be due to some internal errors. Could someone from the Ivy Team please check this?

### CODE REVIEW

**Comment by galaxygummybear** [comment]
Hi, it seems like there's no conflict with the upstream branch. Could someone please double-check this and merge it if there are no issues? Thank you.

**Comment by AlexandraPosta** [comment]
Hello @galaxygummybear, please have a look at the raw logs where tests are failing:
AttributeError: module 'ivy.functional.backends.paddle' has no attribute 'softsign'
AttributeError: module 'ivy.functional.backends.tensorflow' has no attribute 'softsign'
etc.

**Comment by galaxygummybear** [comment]
> Hello @galaxygummybear, please have a look at the raw logs where tests are failing: AttributeError: module 'ivy.functional.backends.paddle' has no attribute 'softsign' AttributeError: module 'ivy.functional.backends.tensorflow' has no attribute 'softsign' etc.

How do I fix this? All the backends are failing as well. Same thing, AttributeError. The softsign function is basically just this:
```
def softsign(x):
    return x/(abs(x)+1)
```

Should i go and implement this in all the backends. I'm worried I might break something.

**Comment by AlexandraPosta** [comment]
Hello @galaxygummybear, you do not need to implement it in all the backends, you can create a composition of ivy functions. This: ```return x/(abs(x)+1)``` is really good, convert it to ivy functions and push your changes.

**Pull request closed without merging**
