### PR TITLE
Added Ravel instance method to Jax Frontend

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Close #15387

**Comment by RakshitKumar04** [comment]
Hey @Fayad-Alman please review my PR.

**Comment by RakshitKumar04** [comment]
Hey, @Fayad-Alman I have resolved the conflicts, Please review the PR.

**Review by Fayad-Alman — APPROVED** [review]
The changes look good, I fixed some lint issues and found that the paddle test doesn't pass, but for now we should be good to merge this. Good work!

**Pull request merged**
