### PR TITLE
Add ```paddle.tensor.linalg.dot``` Linear Algebra Functions to Paddle Frontend

### LINKED ISSUE #16133: dot

### PR DESCRIPTION
**Pull request by benkimz**
Close #16133

### CODE REVIEW

**Comment by Daniel4078** [comment]
hello, please do't forget there is a checklist for this kind of tasks, look at the description of the label I set for some info.

**Comment by benkimz** [comment]
> hello, please do't forget there is a checklist for this kind of tasks, look at the description of the label I set for some info.

You mean the tests?

**Comment by Daniel4078** [comment]
> add_frontend_checklist

I mean this `add_frontend_checklist` just incase, and well done for the tests, thanks!

**Comment by benkimz** [comment]
> > add_frontend_checklist
> 
> I mean this `add_frontend_checklist` just incase, and well done for the tests, thanks!

I made the changes. I hope I did it right. 
Thanks you!

**Pull request closed without merging**
