### PR TITLE
Added first 3 pytorch frontend gradient managing functions

### LINKED ISSUE #12883: no_grad

### LINKED ISSUE #12884: enable_grad

### LINKED ISSUE #12885: set_grad_enabled

### PR DESCRIPTION
**Pull request by cmvcordova**
Close #12883
Close #12884 
Close #12885

Unsure if just checking for the existence of the `with_grads_stack` global list is enough to add the other 3 gradient managing functions (is_grad_enabled, inference_mode, is_inference_mode_enabled). Added the skeleton in a comment to address the former once these issues are cleared up.

### CODE REVIEW

**Comment by cmvcordova** [comment]
Also just noticed #12885 is missing assigning the mode variable to with_grads within the function, will fix in next commit

**Comment by cmvcordova** [comment]
New PR potentially:

Close #12955 
Close #12956 
Close #12957 

Comments to follow

**Comment by cmvcordova** [comment]
Implemented methods with the use of Ivy's built-in [GradientTracking](https://lets-unify.ai/ivy/docs/functional/ivy/ivy.functional.ivy.gradients.html#ivy.functional.ivy.gradients.GradientTracking) context manager:

This was done with the rationale of being able to use

1.  no_grad()
2. enable_grad()
3. set_grad_enabled()
4. inference_mode()

in the `with no_grad():` fashion Pytorch usually does.

Few caveats:

Drawing from the following link,
https://discuss.pytorch.org/t/pytorch-torch-no-grad-vs-torch-inference-mode/134099

Inference mode vs no_grad in pytorch have differences in performance, due to inference mode disabling view tracking and version counter bumps. As implemented here, 'Inference mode' is just a boolean mask that will allow the user to set the former flag without computing a gradient, but is equivalent to no_grad in function. Further clarification on Ivy's internal workings would help me address if these optimizations can be found anywhere and/or are desirable within the provided context managers.

Finally, both `is_grad_enabled` and `is_inference_mode_enabled` just use `ivy.with_grads()` under the hood and provides a similar check.

**Comment by zhumakhan** [comment]
Hey, thanks for your PR!
Could you please fix these lint issues with pre-commit given in Ivy repo?
Frontend functions should have equivalent counterpart in ivy functional API like in `is_grad_enabled`.
Refer to https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/gradients.py
Also issues seems to have no description, could you please add some?

**Comment by zhumakhan** [comment]
Anyway, let me look more closer,
Seems like it is not that trivial

**Comment by cmvcordova** [comment]
Hello, thanks for the follow-up!

After a discord conversation in the frontends/#torch channel in the Ivy server, there's apparently some work that needs to be done w.r.t the gradients for this to get cleared. Not entirely sure how to proceed, so I remain open to further comments.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
