### PR TITLE
Docs folder in ivy_tests

### LINKED ISSUE #19362: [Feature Request]: Add Docs folder to each folder
Here is  why the documentation is helpful:

1. Problem:

- The current open source project does not have any documentation that explains the purpose of each file. This makes it difficult for new contributors to understand the project and how to contribute.

2.  Solution:

- I propose adding a Docs folder as a subfolder in each folder. This folder would contain documentation that explains the purpose of each file, why the file is used, and its function. This would make it much easier for new contributors to understand the project and how to contribute.

3. Alternatives:

- One alternative would be to add the documentation to the README file. However, this would make the README file very long and difficult to read. Another alternative would be to create a separate documentation website. However, this would require more work and maintenance.

4. Additional context:

- I believe that adding documentation would be a valuable addition to the open source project. It would make it easier for new contributors to get started and would help to improve the overall quality of the project.

I hope this helps  to the upcomming contributors !

### PR DESCRIPTION
**Pull request by shephinphilip**
Fixed #19362

### CODE REVIEW

**Comment by shephinphilip** [comment]
@DragosStoican 
I am new to this project and trying to understand the project , so when I created Pull request , The PR is getting failed , Some issues with .yml files , Could you please tell me what to do to make the PR to successfully merge .

**Review by shephinphilip — COMMENTED** [review]
Problem with .yml file , could you please , tell me what to do ?

**Comment by DragosStoican** [comment]
Hi @shephinphilip . First of all, thank you for your contribution! We really appreciate your suggested feature request!

However, I am afraid this is not something we want to add to our codebase. The reason is that our docs [here] (https://unify.ai/docs/ivy/) cover most of the information you've suggested, and such a detailed description of what each file contains is not really needed.

I encourage you to take a look at our open tasks [here] (https://unify.ai/docs/ivy/overview/contributing/open_tasks.html) and follow the instructions there to contribute. Take a look and see if anything looks interesting to you!

**Comment by shephinphilip** [comment]
@DragosStoican  Thank you for your response , I am closing the PR now .

**Pull request closed without merging**
