### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Boldcodes**
- [ ] #1777

### CODE REVIEW

**Review by chie2727 — CHANGES_REQUESTED** [review]
Hi @Boldcodes ,
The task is to make changes directly to the `device` submodule rather than creating a newly made file.

https://github.com/unifyai/ivy/blob/87c2ce35c6a3cf79a57bf17d48156b3d003c5c7e/ivy/functional/ivy/device.py#L405

**Comment by Boldcodes** [comment]
Hi @chie2727, how do I get into the Device submodule to make the changes?

**Comment by chie2727** [comment]
@Boldcodes You can make a fork of unifyai/ivy to your account then clone the fork to your local PC folder.

**Comment by Boldcodes** [comment]
Hi @chie2727,
I have made changes to the device submodule. Do I have to create a new pull request

**Pull request closed without merging**
