### PR TITLE
feat: added histogram to numpy frontend

### LINKED ISSUE #23149: histogram

### PR DESCRIPTION
**Pull request by dbisina**
# PR Description

## Related Issue

Close #23149

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials:

https://twitter.com/DanielBisina

### CODE REVIEW

**Comment by lyon98-dbios** [comment]
@ivy-leaves

**Comment by lyon98-dbios** [comment]
@saeedashrraf

**Comment by lyon98-dbios** [comment]
@saeedashrraf  please can i get a review?

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @lyon98-dbios, Thank you for your contribution and sorry for the delay. It seems like the tests are still failing for the function you implemented. Specifically, this is the falsifying example [here](https://github.com/unifyai/ivy/actions/runs/6304768459/job/17117226007?pr=26090#step:3:46). Can you take a look into why it is failing and attempt to fix it ? Let me know if you have any questions. Thanks again!

**Comment by lyon98-dbios** [comment]
@saeedashrraf Thank you for the reply. But in the PR guideline it says run-test-(1) can be ignored

**Comment by saeedashrraf** [comment]
The failure linked is not related to the run-test-(1). It is related to a specific input that returns different results when run through numpy and tensorflow backends. Each backend, returns a different result in this case as shown [here](https://github.com/unifyai/ivy/actions/runs/6304768459/job/17117226007?pr=26090#step:3:46). I hope this clarifies it. Thanks!

**Comment by lyon98-dbios** [comment]
@saeedashrraf

**Comment by lyon98-dbios** [comment]
@saeedashrraf  ... please can you further review this?

**Comment by NripeshN** [comment]
Hey @dbisina,
Your tests still seem to be failing

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
