### PR TITLE
Added apply_over_axes

### PR DESCRIPTION
**Pull request by asparius**

### CODE REVIEW

**Comment by asparius** [comment]
Hi @Aarsh2001, could you tell me why formatting fails since there is no info in test log?

**Comment by Aarsh2001** [comment]
Hey @asparius apologies for the delayed response, can you please tag the issue_number which this PR aims to resolve, thanks 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Aarsh2001** [comment]
Feel free to re-open once you're done with your changes, thanks

**Comment by asparius** [comment]
> Hey @asparius apologies for the delayed response, can you please tag the issue_number which this PR aims to resolve, thanks 🙂

https://github.com/unifyai/ivy/issues/15351

**Pull request closed without merging**
