### PR TITLE
reformat split_factor #1345

### PR DESCRIPTION
**Pull request by haadfida**
This pull request resolves the issue https://github.com/unifyai/ivy/issues/1345

### CODE REVIEW

**Comment by haadfida** [comment]
Hi @saeedashrraf, I have formatted my examples based on the contributors guide. Please take a look when available. 
Thanks.

**Review by saeedashrraf — COMMENTED** [review]
Hello @haadfida , is there a reason as to why you changed the implementation of the function [here](https://github.com/unifyai/ivy/pull/1411/files#diff-ca7db18115e5b52f90e231d41fae2418e12b8598b43cb7bb23ab9448d4d13af8R592) ?

**Comment by haadfida** [comment]
Hello @saeedashrraf, I refactored it using the dictionary [setdefault()](https://docs.python.org/3/library/stdtypes.html#dict.setdefault) method. Please let me know if this isn't required, and I will revert it right away.

**Comment by haadfida** [comment]
Hi, I have added type hints as provided in the documentation. Thanks again.

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Can you also add the type hint for the device variable ?

**Comment by haadfida** [comment]
Hi @saeedashrraf, I have added type hints to the device parameter. Please take a look when available, thanks.

**Review by saeedashrraf — APPROVED** [review]

**Comment by saeedashrraf** [comment]
This looks good. Thank you for your effort @haadfida

**Pull request merged**
