### PR TITLE
Implement reciprocal in ivy core and add to jax.lax frontend

### LINKED ISSUE #2873: Reciprocal function missing in Ivy Functional API
It appears as though an element-wise function, 'reciprocal', is missing from the Ivy Functional API.
I believe that it should have been implemented in the [elementwise.py](https://github.com/unifyai/ivy/blob/f2d2e225e1df4fe6ca2110dcc2ef5b0f5a14a20d/ivy/functional/ivy/elementwise.py) sub-module, however that does not seem to be the case. 
It has not been implemented in another sub-module either, to the best of my knowledge. 
Is this an intentional omission? If not, may I go ahead and create a pull request fixing the same?

### PR DESCRIPTION
**Pull request by TheMonocledHamster**
Resolves #2873 and #2869

Hi! 
I hope my implementation of the function meets the requirements. 
I look forward to iteratively improving the solution if necessary.
Cheers!

### CODE REVIEW

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
I only manage to find one thing to change currently, that is this formatting error:
ivy/functional/backends/tensorflow/elementwise.py:529:72: E502 the backslash is redundant between brackets
It is amazing that all other relative tests passes. Thank you.

**Comment by TheMonocledHamster** [comment]
Thanks for the kind words!
I've made the requested changes, kindly re-review and let me know if there's any other improvement required.
Cheers!

**Review by Daniel4078 — COMMENTED** [review]
Well, now there is only one assertion error happening in the test that found the ground truth return of array(True) is not the same with current output array(False). Which confuses me as reciprocal suppose to take in array of numbers and calcuate x^-1 on each of them and how does True and False get in to the test?
By the way, other test that reguard jax as front end uses this:
dtype_and_x=helpers.dtype_and_values(
        available_dtypes=list(
            set(ivy_jax.valid_float_dtypes).intersection(set(ivy_np.valid_float_dtypes))
        )
    ) 
to generate values while the value you generate only have dtypes from ivy.valid_float_dtypes.

**Comment by TheMonocledHamster** [comment]
> Well, now there is only one assertion error happening in the test that found the ground truth return of array(True) is not the same with current output array(False). Which confuses me as reciprocal suppose to take in array of numbers and calcuate x^-1 on each of them and how does True and False get in to the test? By the way, other test that reguard jax as front end uses this: dtype_and_x=helpers.dtype_and_values( available_dtypes=list( set(ivy_jax.valid_float_dtypes).intersection(set(ivy_np.valid_float_dtypes)) ) ) to generate values while the value you generate only have dtypes from ivy.

The failing test (due to the assertion error) is from the test_jax_lax_ge function, which had been merged into the repo before I made my PR. I'll try to look into it, however I haven't made any changes to the function in question, and I'm not sure if I ought make any within this PR? What do you think would be the best way forward for now?

As for the dtypes, ivy.valid_float_dtypes is a superset of ivy_jax.valid_float_dtypes and ivy_np.valid_float_dtypes (to the best of my knowledge). Of course, considering that the test is specifically for a jax frontend, it might have been a better choice to go with an intersection of ivy_jax and ivy_np.  I will make this change in the immediate next commit.

I feel that it would be appropriate to hold off on making any changes to the function that is throwing the assertion error, for now, as that has to do with the ge function and not the reciprocal function, so it would perhaps be out of place in this PR. Perhaps a separate PR to fix that would be more appropriate? What do you think?

**Comment by Daniel4078** [comment]
Oh, then I must made a mistake and got the name of that test wrong. Well, then you only need to try fix the conflit in these files:
ivy/functional/frontends/jax/lax/operators.py
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
Then I will have a final look at the status of the tests and if they passes, I think the pull request is good to be merged. Thank you.

**Comment by TheMonocledHamster** [comment]
Thanks for your patience and for the extraordinarily quick responses!
It has been a pleasure collaborating on this PR with you!!

**Review by Daniel4078 — APPROVED** [review]
I think there is no errors with your code and this pull request can be merged. Thank you.

**Pull request merged**
