### PR TITLE
Add ELU function to Paddle's activations

### LINKED ISSUE #15982: elu

### PR DESCRIPTION
**Pull request by Nordiniv**
closes #15982

### CODE REVIEW

**Comment by Nordiniv** [comment]
Hi @jkeane508 ! I think this is good to go, sorry for the hassle...

**Comment by Nordiniv** [comment]
Hi again @MahmoudAshraf97 ! I hope it meets your requirements now...

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hi, `elu` doesn't exist in the functional framework so you'll have to add it in all backends in addition to array and container methods

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
