### PR TITLE
result_type #10106

### PR DESCRIPTION
**Pull request by Ahmadmalj**

### CODE REVIEW

**Comment by Ahmadmalj** [comment]
Can you give any explanations for the mistakes?

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @Ahmadmalj 

The guidelines are mentioned in the subtask (https://github.com/unifyai/ivy/issues/780) as well as the Deep Dive (https://lets-unify.ai/ivy/contributing/open_tasks.html#function-formatting).

The task is to basically ensure that `ivy.result_type()` and `<ivy_backend>.result_type()` follow the format as defined in the Deep Dive link above. In most cases, this involves, ensuring that the functions have the correct type hints, and have proper docstrings along with docstring examples. This format should also hold for the methods in `Ivy.Array` and `Ivy.Container` instance methods.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
