### PR TITLE
added atan function

### LINKED ISSUE #15853: atan

### PR DESCRIPTION
**Pull request by whatzittoya**
Close #15853

### CODE REVIEW

**Comment by whatzittoya** [comment]
Hi @KareemMAX,

I am new here, kindly need your advise about the failing checks. I failed to understand what the details mean.

**Comment by KareemMAX** [comment]
add_frontend_checklist

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hi @whatzittoya,
Looks like you have a lot of unrelated changes, sadly I can't merge the PR like that. Can you please revert those changes before we proceed?

**Comment by whatzittoya** [comment]
Hi @KareemMAX,

I it's because I reformated the code using black to avoid linting errors. It makes the whole file got modified. Could you share tips to avoid linting errors?

**Comment by KareemMAX** [comment]
@whatzittoya 

I'm not thinking that's the case, as black always work as a cron job in the repo, there can't be a linting error with that magnitude. Maybe revert your changes and paste your code again

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
