### PR TITLE
add reshape frontends.torch

### PR DESCRIPTION
**Pull request by PatternFinder**
link to issue: #2636

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @PatternFinder 
Thank you for the PR. Would you be able to resolve the merge conflict? perhaps it might just require fetch and merge. Let me know if it poses any difficulty and request my review when done. I think should be able to merge soon after. Thank you😊

**Comment by PatternFinder** [comment]
> Hi @PatternFinder Thank you for the PR. Would you be able to resolve the merge conflict? perhaps it might just require fetch and merge. Let me know if it poses any difficulty and request my review when done. I think should be able to merge soon after. Thank you😊

Hi, @Ishticode ah yes, it conflicted with other my PRs that was merged. The conflict should be resolved now :) I'm ready for another look, thanks :)

**Review by Ishticode — APPROVED** [review]
Looks good @PatternFinder 
torch frontend test failing seem to be based on some other functions so nws for that.
I will get it merged now. Thanks for your contribution.😊

**Comment by PatternFinder** [comment]
> Looks good @PatternFinder torch frontend test failing seem to be based on some other functions so nws for that. I will get it merged now. Thanks for your contribution.😊

Thank you for taking a look :) See you in other PRs :)

**Pull request merged**
