### PR TITLE
softmax function and tests for paddle frontend

### LINKED ISSUE #19092: softmax

### PR DESCRIPTION
**Pull request by huzi6181**
close #19092

### CODE REVIEW

**Comment by huzi6181** [comment]
The failing test is for test_paddle_silu

**Comment by huzi6181** [comment]
@Ishticode please review

**Comment by huzi6181** [comment]
@ivy-leaves no one is reviewing this PR

**Comment by huzi6181** [comment]
@Ishticode please review the PR

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @huzi6181 
Thanks for the PR.
I had tried to push some changes but I am unable to push onto ur fork for some reason. And then the testing pipeline has changed. Could you update and add `backend_fw` arg like in other frontend tests. Also paddle support float16 and bfloat16 for softmax as in the docs so that should be added to supported dtypes also. All else is good and should be soon merged after these updates.

**Comment by huzi6181** [comment]
@Ishticode thank you for the review, ill make these changes and update the PR

**Comment by huzi6181** [comment]
Sorry for the delay, I contracted covid, ill update this first thing tomorrow.

**Comment by huzi6181** [comment]
@Ishticode by the time i finished the changes, the main repo is 533 commits ahead, my fork is 533 commits behind, i created a branch in my fork for this pull request. how to i bring my fork up to date without messing up the changes ive made

**Review by Ishticode — CHANGES_REQUESTED** [review]
Could you resolve the conflicts and push the changes when possible? This PR has been inactive and will be labelled stale soon.

**Pull request closed without merging**
