### PR TITLE
add round to jax

### PR DESCRIPTION
**Pull request by PatricYan**
- [ ] #3113 
- add round to jax

### CODE REVIEW

**Comment by PatricYan** [comment]
@ivy-seed what's the meaning of the **next release**?

**Comment by PatricYan** [comment]
Hi @mattbarrett98 , would you like to make a review for the PR?

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
I believe `round` can take any numeric data type, but you are only testing against floats currently. Also, torch's `round` doesn't support `float16` which you should indicate with an `unsupported_dtypes` attribute similar to other functions in the operators file 🙂

**Comment by PatricYan** [comment]
> I believe `round` can take any numeric data type, but you are only testing against floats currently. Also, torch's `round` doesn't support `float16` which you should indicate with an `unsupported_dtypes` attribute similar to other functions in the operators file 🙂

Hi @mattbarrett98 ,  I have tested the round by type int8, it is not supported.
```
TypeError: round does not accept dtype int8. Accepted dtypes are subtypes of floating.
```

**Review by mattbarrett98 — COMMENTED** [review]
Which backend are you using to obtain this error? torch?

**Comment by PatricYan** [comment]
> Which backend are you using to obtain this error? torch? Could you share the code 🙂

command 
```
Launching pytest with arguments --backend jax test_jax_lax_operators.py::test_jax_lax_round --no-header --no-summary -q in ~/GitHub/ivy/ivy_tests/test_ivy/test_frontends/test_jax

```

**Comment by PatricYan** [comment]
> import jax.numpy as jnp
> >>> jnp.round(jnp.array(1, dtype="int8"))
> DeviceArray(1, dtype=int8)

after debugging by steps, it seems the error comes from 
```
frontend_ret = frontend_fw.__dict__[fn_tree](*args_frontend, **kwargs_frontend)
```

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Just leave it as floats only for now then. You still need to make the changes related to an unsupported_dtype attribute however

**Comment by PatricYan** [comment]
> Just leave it as floats only for now then. You still need to make the changes related to an unsupported_dtype attribute however

Hi @mattbarrett98 , you mean to add the **int8, int32 ...** to the unsupported type?

**Review by mattbarrett98 — COMMENTED** [review]
No, as I said before its torch which doesn't support `float16` which you should indicate in the attribute.

**Comment by PatricYan** [comment]
> float16

done

**Comment by PatricYan** [comment]
> No, as I said before its torch which doesn't support `float16` which you should indicate in the attribute.

Hi @mattbarrett98 , I have resolved it by adding the unsupported type **float16**

**Review by mattbarrett98 — APPROVED** [review]
Thank you 🙂

**Pull request merged**
