### PR TITLE
Reformatted multi_head_attention

### PR DESCRIPTION
**Pull request by Sam-Armstrong**
#6664

### CODE REVIEW

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @Sam-Armstrong The return type can still be ivy.NativeArray. Can you please check the documentation here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting. Thanks.

**Comment by Sam-Armstrong** [comment]
@RashulChutani Thanks for catching that mistake, I misread the documentation. I've updated the pull request.

**Comment by RashulChutani** [comment]
Sure, I will review it soon.

**Comment by Sam-Armstrong** [comment]
@RashulChutani Would you be able to review this soon please? Just don't want my issue to get cancelled. Thanks :)

**Comment by RashulChutani** [comment]
Hi @Sam-Armstrong Sure. I will do that soon

**Review by RashulChutani — APPROVED** [review]
Hi @Sam-Armstrong Looks good to me now.

**Pull request merged**
