### PR TITLE
reformatting gelu

### PR DESCRIPTION
**Pull request by AduGyamfi-David**
refactored ivy.gelu function corresponding to #784 from #754

### CODE REVIEW

**Comment by AduGyamfi-David** [comment]
First pull-request failed due to 1 failed test in ivy/ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py::test_remainder[__imod__(x1, x2)]. Made new commit

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi, can you revert your changes in creation.py in torch backend, torch.Tensor does not need to be reformatted to just 'Tensor' and same with torch.device.
Also helpers.assert_docstring_examples_run has been renamed to helpers.docstring_examples_run. so can you kindly fix that in test_activations.py. the rest looks good, I'll merge your PR as soon as you make these changes 👍

**Comment by AduGyamfi-David** [comment]
> Hi, can you revert your changes in creation.py in torch backend, torch.Tensor does not need to be reformatted to just 'Tensor' and same with torch.device. Also helpers.assert_docstring_examples_run has been renamed to helpers.docstring_examples_run. so can you kindly fix that in test_activations.py. the rest looks good, I'll merge your PR as soon as you make these changes 👍

OK, will do!

**Comment by AduGyamfi-David** [comment]
Changes made. currently running checks

**Comment by AduGyamfi-David** [comment]
@sherry30 still waiting on a review, let me know when you can get review it, thanks!

**Review by sherry30 — CHANGES_REQUESTED** [review]
For some reason your PR is detecting changes in 364 files (its showing that these are empty files), i would suggest to update your forked repo then clone it locally and then copy paste the changes you made in that cloned repo, then make a commit, your PR should only be detecting the changed files

**Comment by AduGyamfi-David** [comment]
> For some reason your PR is detecting changes in 364 files (its showing that these are empty files), i would suggest to update your forked repo then clone it locally and then copy paste the changes you made in that cloned repo, then make a commit, your PR should only be detecting the changed files

Hi, unfortunately these changes are due to a file permissions change that I made, as VSCode wasn't letting me save files and I couldn't figure out why (I am unable to set up a dev environment in pycharm). Instead, I will set up a new pull request with the correct changes, and mention it here (I wont delete this one until you've seen the new one).

**Pull request closed without merging**
