### PR TITLE
median in torch

### LINKED ISSUE #11333: median

### PR DESCRIPTION
**Pull request by dpshekhawat**
Closes #11333 

> Due to recent forced push had to close PR #11336 and create this new PR.

### CODE REVIEW

**Comment by dpshekhawat** [comment]
with recent changes the following errors are faced:

1. for numpy backend -
```
AssertionError: The length of results from backend numpy and ground truth framework torch does not match

ret_np_flat:
[array(-1.)]

ret_np_from_gt_flat:
[array(-1.), array(0)]
```
2. for jax backend -
```
AssertionError: The length of results from backend jax and ground truth framework torch does not match

ret_np_flat:
[array(-1.)]

ret_np_from_gt_flat:
[array(-1.), array(0)]
```
3. for tensorflow backend -
```
AssertionError: The length of results from backend tensorflow and ground truth framework torch does not match

ret_np_flat:
[array(-1.)]

ret_np_from_gt_flat:
[array(-1.), array(0)]
```
4. for torch backend
```
AssertionError: The length of results from backend torch and ground truth framework torch does not match

ret_np_flat:
[array(-1.)]

ret_np_from_gt_flat:
[array(-1.), array(0)]
```

**Comment by dpshekhawat** [comment]
Hi @kurshakuz 
As you can see from the above comment, the ground truth framework (torch) is giving a list of median values and respective indices due to which the test is failing, since then I am trying to find out the way to manipulate the ground truth framework (torch) to return only the values.
If you could direct me to where to implement the above case of manipulating the output, I would highly appreciate it. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by kurshakuz** [comment]
> Hi @kurshakuz As you can see from the above comment, the ground truth framework (torch) is giving a list of median values and respective indices due to which the test is failing, since then I am trying to find out the way to manipulate the ground truth framework (torch) to return only the values. If you could direct me to where to implement the above case of manipulating the output, I would highly appreciate it. Thanks!

Hey! You are not supposed the change the values produced by the ground truth implementation. Goal of Ivy is to serve as an abstraction over the frameworks and replicate the expected behavior, therefore you only need to modify the Ivy implementaion st it follows the same structure as ground gruth values. 🙂

**Comment by dpshekhawat** [comment]
@kurshakuz I really appreciate your feedback. But I think I am having a little trouble in understanding to fix this `ret_np_flat`
 are you suggesting working on this [backend-torch-exp-stat-median](https://github.com/unifyai/ivy/blob/2a77530fc6534db9d330900289d226517190d986/ivy/functional/backends/torch/experimental/statistical.py#L11) implementation and similarly for every other backend implementation of median. 
I was wondering if you could help me clarify it?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by dpshekhawat** [comment]
working on it.

**Comment by dpshekhawat** [comment]
hey @kurshakuz I believe the PR is ready to be merged, let me know if you have any feedback.

Also just wanted to quickly mention that I noticed the median reduction ops test method isn't currently being tested for float dtypes [ref](https://github.com/unifyai/ivy/blob/ded443f1b3bdd7158f90e06fdd4414d5d3fff1b8/ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py#L342) I'm not sure if this is intentional, but I wanted to bring it to your attention in case it was overlooked.

**Review by kurshakuz — APPROVED** [review]
LGTM! Thanks @dpshekhawat

**Pull request merged**
