### PR TITLE
added paddle.nanmean function frontend and test for it

### LINKED ISSUE #22885: nanmean

### PR DESCRIPTION
**Pull request by sabre-code**
# PR Description
Added paddle.nanmean function and test for it.

## Related Issue

Close #22885

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials:
discord - Sulaiman

### CODE REVIEW

**Comment by sabre-code** [comment]
@tomatillos can you please review the PR and merge if things are fine

**Comment by sabre-code** [comment]
@tomatillos hello can you please review the PR?

**Comment by tomatillos** [comment]
Hi, looks good so far. Could you ensure that the test function is testing for NaN values too, otherwise we aren't properly testing the function for values it might encounter. You should be able to find examples of this in the other nan test functions in the file

**Comment by sabre-code** [comment]
> Hi, looks good so far. Could you ensure that the test function is testing for NaN values too, otherwise we aren't properly testing the function for values it might encounter. You should be able to find examples of this in the other nan test functions in the file 

Yeah you are absolutely correct 😄. Will get back to you shortly.

**Comment by sabre-code** [comment]
@tomatillos 
image
the test fail randomly on one or 2 of the backends. Please see the attached screenshot. the difference between the output from function is negligible. (due to difference in precision probably). I am sure this is not because of testing for Nan value. I face this error earlier for other function. and the failing of test for this reason is random. sometime all pass sometime one or 2 fail for same reason. Any suggestions?

**Comment by tomatillos** [comment]
Does the same thing happen with `test_paddle_nansum`?

**Comment by sabre-code** [comment]
> Does the same thing happen with `test_paddle_nansum`?

image
I made changes to rtol and atol. now all test pass. and also added allow_nan to use nan values for testing.

**Comment by tomatillos** [comment]
Thanks for this :)

**Pull request merged**
