### PR TITLE
Update tan in mxnet backend

### PR DESCRIPTION
**Pull request by AymenSe**
Update the tan function in mxnet by removing lambda and define the function using def.

### CODE REVIEW

**Comment by AymenSe** [comment]
@djl11 Could you please review my changes?

**Comment by AymenSe** [comment]
Fixing issue #2130

**Comment by AymenSe** [comment]
@abdrahmandiab Could you please review my PR?

**Comment by AymenSe** [comment]
@ivy-seed @djl11 @1Doomdie1 please someone review my PR! I think @abdrahmandiab is not available these days.

**Comment by abdrahmandiab** [comment]
Hi @AymenSe,
Sorry it took me a bit long to reply, I had to confirm something regarding this PR and that took some time. 😅

It appears this function should not have been open to applicants in the first place since the formatting for it is pretty much done. That is not your fault however, and we'll of course accept this anyway so you can get ahead with your application! 

However, while checking through the 'tan' function formatting myself, I found a small error [here](https://github.com/unifyai/ivy/blob/123f60bbd52356bd61f53078f3178233205e00ff/ivy/container/elementwise.py#L6158). This should say 'a container containing' rather than 'an array containing'. Please update this, and I will Merge your PR right after. :)

Thank you!

**Comment by AymenSe** [comment]
Hi, @abdrahmandiab Thank you so much for your help.

**Comment by abdrahmandiab** [comment]
> Hi, @abdrahmandiab Thank you so much for your help.

Anytime! :)

**Pull request merged**
