### PR TITLE
xlogy_

### LINKED ISSUE #21868: xlogy_
Todo list: #3612

### PR DESCRIPTION
**Pull request by NiteshK84**
# PR Description 
adds xlogy_ function to torch frontend

## Related Issue 

Close #21868

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Pchatain** [comment]
Hi @NiteshK84 nice work! Do you happen to know why the lint check formatting is failing? I can't immediately tell from looking at the code.

**Comment by NiteshK84** [comment]
@Pchatain, yeah because at line 1889 chrome_npM1Dnb6ij
we are redefining the ne function again after aliasing it with not_equal function defined at line 489
chrome_JdZ48uVU3i

**Comment by NiteshK84** [comment]
i think we should remove the redefinition of ne from here
chrome_Qa5kXLewOT

**Comment by NiteshK84** [comment]
but anyways this code has is unrelated with that issue and is ready to merge.
thanks😊

**Comment by aparajith21** [comment]
Failures seem unrelated, LGTM, thanks for contributing!

**Pull request merged**
