### PR TITLE
Fixed : Added  Code_Of_Conduct.md file.

### LINKED ISSUE #27167: [Feature Request]: <Adding Code_Of_Conduct File to repository>
[code of condt importance.txt](https://github.com/unifyai/ivy/files/13197876/code.of.condt.importance.txt)

### PR DESCRIPTION
**Pull request by Kalyanimhala**
Fixed #27167
Added code of conduct for Repository.
@aadya940 @vedpatwardhan   kindly review it and merged the PR. Thank You!

### CODE REVIEW

**Comment by vedpatwardhan** [comment]
I think @sreegandh804 would be the best person to review this PR, thanks @Kalyanimhala 😄

**Comment by sreegandh804** [comment]
> I think @sreegandh804 would be the best person to review this PR, thanks @Kalyanimhala 😄

Apologies for the delayed response, @vedpatwardhan and @Kalyanimhala. 
The PR looks good to me and since it draws from the [Contributor Covenant](https://www.contributor-covenant.org/), I recommend you to attribute credits to the applicable references from the website. Also, please mention any other sources that have inspired you in compiling this information. Let’s follow the example of Hugging Face, which you can find here: https://github.com/huggingface/transformers/blob/main/CODE_OF_CONDUCT.md.

**Review by sreegandh804 — COMMENTED** [review]
Apologies for the delayed response, @vedpatwardhan and @Kalyanimhala. 
The PR looks good to me and since it draws from the [Contributor Covenant](https://www.contributor-covenant.org/), I recommend you to attribute credits to the applicable references from the website. Also, please mention any other sources that have inspired you in compiling this information. Let’s follow the example of Hugging Face, which you can find [here](https://github.com/huggingface/transformers/blob/main/CODE_OF_CONDUCT.md).

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
