### PR TITLE
Append

### PR DESCRIPTION
**Pull request by shireenchand**
Frontend and test for numpy append

### CODE REVIEW

**Comment by shireenchand** [comment]
Hi @V-G-spec can you please review this PR. Thanks!

**Comment by V-G-spec** [comment]
Same comment as on the other PR 😅

**Comment by shireenchand** [comment]
Close #10646

**Comment by aditya-hari** [comment]
Hey, thanks for the contributions. Unfortunately the format of this PR isn't quite right. [This](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues) page in the documentation should clear it up. The TL;DR of it is that you first need to create an issue with the name of the function as the title, comment that issue number on the ToDo list issue, and then open a PR which links to the issue.     
Same applies for all the other PRs you have opened as well. There are some other issues with some of the PRs, but I believe it will be better to address them in the correctly formatted PRs.

**Comment by aditya-hari** [comment]
In the meanwhile, this PR and few others have a common issue of using numpy directly to implement the frontends. That's not quite right, as you're supposed to use Ivy functions to implement these functions. The [frontends guide](https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html) should help you out here.

**Comment by shireenchand** [comment]
> This

Hi @aditya-hari, I have created this issue with the name of the function as the title, commented that issue number on the ToDo list issue, and then opened a PR which links to the issue. You can see the screenshot below
Screenshot 2023-02-26 at 8 51 33 AM

**Pull request closed without merging**
