### PR TITLE
first implementation of stft

### LINKED ISSUE #26569: stft

### PR DESCRIPTION
**Pull request by Ahmed-5**
Refs: #26569

# PR Description

## Related Issue

Close #26569

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing? 
- [x] Did pre-commit not fail on any check? 
- [x] Did you follow the steps we provided? 

### Socials

@am5ai

### CODE REVIEW

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @Ahmed-5, thanks for creating this PR. Could you please look into [ivy.stft](https://unify.ai/docs/ivy/docs/functional/ivy/experimental/layers/ivy.functional.ivy.experimental.layers.stft.html#stft) function and see if it can be used to implement the torch frontend `stft` function? Once you're done, please write a test for the function as well and make sure all the tests are passing locally first. Happy to help out here incase you run into any problems.

**Comment by Ahmed-5** [comment]
Ok I will the test, and improve the similarity of behaviour of the function to that of torch.stft

**Comment by Ishticode** [comment]
Any updates on the missing test @Ahmed-5 and the changes requested by @hello-fri-end

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ishticode** [comment]
Closing this as labelled stale for over a week.

**Pull request closed without merging**
