### PR TITLE
Index append update

### PR DESCRIPTION
**Pull request by VedPatwardhan**
The index_append.rst file has been updated to include the link to the documentation building pipeline page in the sidenav.

### CODE REVIEW

**Review by djl11 — CHANGES_REQUESTED** [review]
Hey Ved, small change, could we rename this file to `building_the_docs.rst`? Will then get it merged once both are updated. Thanks!

**Comment by VedPatwardhan** [comment]
Sure @djl11 , I'll do it right away.

**Comment by VedPatwardhan** [comment]
Done.

**Review by djl11 — APPROVED** [review]
lgtm!

**Pull request merged**
