### PR TITLE
pr_for_empty

### PR DESCRIPTION
**Pull request by rishishounak**
#344

### CODE REVIEW

**Comment by rishishounak** [comment]
@djl11 please tell if I have done this right. Do I need to make further changes?

**Review by 1Doomdie1 — CHANGES_REQUESTED** [review]
Hey, thank you for contributing. Please remove all contents from the commit which is not related to empty (for example everything in .idea)

**Comment by rishishounak** [comment]
I deleted the files and uploaded the files present in the main ivy repository. It shows file changed but I think all content of ivy.iml and misc.xml is the same please check and if possible resolve. @1Doomdie1

**Comment by 1Doomdie1** [comment]
Thanks for the changes. One last thing you need to do is uncomment #empty from this file https://github.com/rishishounak/ivy/blob/master/ivy_tests/array_api_methods_to_test/creation_functions.txt

Request a "re-request review" for your changes. :D

**Review by 1Doomdie1 — APPROVED** [review]
Looks great, thanks!

**Review by djl11 — CHANGES_REQUESTED** [review]
All looks good! Although I am still seeing some files in .idea left over in the files changed tab, when aggregating all commits. You could either rebase your fork, or a hacky approach would be to just copy the .idea from master and replace your local .idea and push. I will merge as soon as the .idea files are removed :)

**Comment by rishishounak** [comment]
are some tests being rewritten because when I rebased all the tests started failing and when I reverted back to original form then still all the tests are failing

**Comment by 1Doomdie1** [comment]
Hey rishishounak, thanks for contributing!
At the moment the method ceil is causing some trouble in the test github action.
Please don't mind them!
As long as the tests are passing on your end then you should be fine.

One more important thing!
Next time after you made the changes requested by a ivy team member please request a "Code Review".
I've requested one for you now but please keep this in mind!
If you fail to do so the PR will remain unchecked and will be closed automatically!

**Comment by rishishounak** [comment]
@djl11 I tried deleting the files and uploading the files present in the main ivy repo inside the .idea folder. But still it shows up in the files changed section. Also I rebased the fork and then the tests started to fail so I reverted back to the original commit. Please suggest what I should do.

**Comment by rishishounak** [comment]
the tests are still failing even when I reverted back to the version where the tests were passing

**Comment by rishishounak** [comment]
I guess the test files have been changed @djl11

**Comment by djl11** [comment]
> @djl11 I tried deleting the files and uploading the files present in the main ivy repo inside the .idea folder. But still it shows up in the files changed section. Also I rebased the fork and then the tests started to fail so I reverted back to the original commit. Please suggest what I should do.

Hmm yes I see, they are identical. Bizarre that git cannot detect that there is no change. Let's see what happens when it's squashed and merged.

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
