### PR TITLE
zero_pad

### PR DESCRIPTION
**Pull request by ashioyajotham**
#810

### CODE REVIEW

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hi @ashioyajotham,

In order to merge this PR, we need to remove changes not relevant to this issue.

Thanks,
James

**Comment by ashioyajotham** [comment]
> Hi @ashioyajotham,
> 
> In order to merge this PR, we need to remove changes not relevant to this issue.
> 
> Thanks, James
Hello James,

Could you expound further
Thanks, Victor.

**Comment by jkeane508** [comment]
> > Hi @ashioyajotham,
> > In order to merge this PR, we need to remove changes not relevant to this issue.
> > Thanks, James
> 
> Hello @jkeane508,
> 
> Could you expound further? Thanks, Victor.

Sure, 

Currently, there are changes to 2,951 files in this PR. We can't merge this as it likely changes important files in the repo. I recommend rebasing your fork with the latest repo version and adding your implementation back in.

Feel free to ask any further questions :)

**Comment by ashioyajotham** [comment]
> > > Hi @ashioyajotham,
> > > In order to merge this PR, we need to remove changes not relevant to this issue.
> > > Thanks, James
> > 
> > 
> > Hello @jkeane508,
> > Could you expound further? Thanks, Victor.
> 
> Sure,
> 
> Currently, there are changes to 2,951 files in this PR. We can't merge this as it likely changes important files in the repo. I recommend rebasing your fork with the latest repo version and adding your implementation back in.
> 
> Feel free to ask any further questions :)

Aahh, I get it now. On it.

**Comment by ashioyajotham** [comment]
> > > > Hi @ashioyajotham,
> > > > In order to merge this PR, we need to remove changes not relevant to this issue.
> > > > Thanks, James
> > > 
> > > 
> > > Hello @jkeane508,
> > > Could you expound further? Thanks, Victor.
> > 
> > 
> > Sure,
> > Currently, there are changes to 2,951 files in this PR. We can't merge this as it likely changes important files in the repo. I recommend rebasing your fork with the latest repo version and adding your implementation back in.
> > Feel free to ask any further questions :)
> 
> Aahh, I get it now. On it.

Hello @jkeane508,
I have rebased it :)

**Comment by jkeane508** [comment]
> > > > > Hi @ashioyajotham,
> > > > > In order to merge this PR, we need to remove changes not relevant to this issue.
> > > > > Thanks, James
> > > > 
> > > > 
> > > > Hello @jkeane508,
> > > > Could you expound further? Thanks, Victor.
> > > 
> > > 
> > > Sure,
> > > Currently, there are changes to 2,951 files in this PR. We can't merge this as it likely changes important files in the repo. I recommend rebasing your fork with the latest repo version and adding your implementation back in.
> > > Feel free to ask any further questions :)
> > 
> > 
> > Aahh, I get it now. On it.
> 
> Hello @jkeane508, I have rebased it :)

Hi @ashioyajotham,

Looking at the changes [here](https://github.com/unifyai/ivy/pull/14790/files), there are still changes to over 2000 files.

**Pull request closed without merging**
