### PR TITLE
feat: implementation of PyTorch pad function

### LINKED ISSUE #23499: pad
https://github.com/unifyai/ivy/issues/22862

### PR DESCRIPTION
**Pull request by tbeetech**
# PR Description

## Related Issue

Close #23499

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by tbeetech** [comment]
@aparajith21 please is my pull request okay for merge now thanks !

**Comment by tbeetech** [comment]
I have changed the pull request description to refer to a my issue number.

**Comment by tbeetech** [comment]
image

**Comment by aparajith21** [comment]
Thanks for contributing, but the pad function actually already exists, and this issue doesn't seem to be linked to a todo list issue from Ivy, so please close this one and choose another open task, and request review once that's done, we will do so!

**Comment by tbeetech** [comment]
@aparajith21 no the pad function for PyTorch as not been implemented this is the only implementations in Ivy/functional/backend/creation.py https://github.com/unifyai/ivy/blob/main/ivy/functional/backends/torch/creation.py

**Comment by tbeetech** [comment]
@aparajith21 please revert on time thank you

**Comment by aparajith21** [comment]
The pad function does indeed have an implementation in Ivy [here](https://github.com/unifyai/ivy/blob/84e68676008334ac217ef1f5f243af715bbc03f1/ivy/functional/ivy/experimental/manipulation.py#L1032) which is what is used currently. Please pick an open task from a TODO list by us instead.

**Comment by tbeetech** [comment]
okay thanks i will create a new pull request right away thanks a lot for the clarifications

**Pull request closed without merging**
