### PR TITLE
add argmax instance method to jax frontend

### LINKED ISSUE #13629: argmax

### PR DESCRIPTION
**Pull request by rodlaf**
Closes #13629

### CODE REVIEW

**Comment by rodlaf** [comment]
Hi @AnnaTz , I implemented this instance function for the JAX DeviceArray class and I am getting errors unrelated to my addition (e.g., in the torch backend). Please let me know if there is anything I am doing wrong here that I can work on

**Comment by AnnaTz** [comment]
> Hi @AnnaTz , I implemented this instance function for the JAX DeviceArray class and I am getting errors unrelated to my addition (e.g., in the torch backend). Please let me know if there is anything I am doing wrong here that I can work on

There are errors in `run_tests_1` that are related to your addition. Specifically I see this "TypeError: test_frontend_method() missing 1 required keyword-only argument: 'frontend_method_data'".

**Comment by rodlaf** [comment]
> > Hi @AnnaTz , I implemented this instance function for the JAX DeviceArray class and I am getting errors unrelated to my addition (e.g., in the torch backend). Please let me know if there is anything I am doing wrong here that I can work on
> 
> There are errors in `run_tests_1` that are related to your addition. Specifically I see this "TypeError: test_frontend_method() missing 1 required keyword-only argument: 'frontend_method_data'".

Thank you, I have fixed this issue. It is currently passing all tests except those related to the Paddle and Torch backends. I see there is some discussion on this in the relevant Discord channel; can this PR still be merged without these passing?

**Comment by AnnaTz** [comment]
@rodlaf The method you added is passing its test, so the PR is ready to be merged! No need to worry about the other errors.

**Pull request merged**
