### PR TITLE
negative function implementation

### PR DESCRIPTION
**Pull request by UditArora2000**
This PR implements the `negative` function into the `ivy` framework.
Tested via the following function on all frameworks except `mxnet`

```
@pytest.mark.parametrize("dtype", ivy.all_dtype_strs)
@pytest.mark.parametrize("shape", ivy_tests.test_shapes)
def test_negative(dtype, shape):
    if ivy.invalid_dtype(dtype):
        pytest.skip()
    x = ivy.cast(ivy.random_uniform(0, 10, shape), type)
    out = ivy.negative(x)
    assert out.dtype == x.dtype
    assert out.shape == x.shape
```

- 292 cases passed
- 92 cases skipped
- 3 cases warning

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by UditArora2000** [comment]
Sir, I feel that you should have "write" access. On the right-hand side below "2 participants," the checkbox is already checked.
Please let me know if I missed anything! I would be happy to help in any way possible 😃

Capture

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Review by djl11 — CHANGES_REQUESTED** [review]
Please reformat the code as describe in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/), and also as explained in this [YouTube series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl).

**Comment by UditArora2000** [comment]
@djl11 Hi sir! I have made the necessary changes in accordance with the contributor guide. Please let me know any other changes I need to make. I would be happy to help 🙂

**Comment by UditArora2000** [comment]
@djl11 Hi sir! I have made the necessary changes in accordance with the contributor guide. Please let me know any other changes I need to make. I would be happy to help 🙂

**Comment by UditArora2000** [comment]
@djl11 I am awaiting a review for this pull request. Please have a look. Thanks!

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Thanks for the pull request! Please could you remove the typing information from the docstring in the ivy/functional/ivy/array_api/elementwise_functions.py file. 

Could you also go to ivy_tests/array_api_methods_to_test/elementwise_functions.txt and uncomment your function negative, so that the tests run 🙂

**Comment by UditArora2000** [comment]
Sir, I have done the changes. 🙂
Kindly do let me know how I can help further!!

**Comment by mattbarrett98** [comment]
Those failures are unrelated to your PR so don't worry. Everything looks good and we'll just await final confirmation from @djl11 before merging your changes. Thanks 🙂

**Review by djl11 — CHANGES_REQUESTED** [review]
Looks great! Could you please un-comment the MXNet implementation. I know we are not testing for this currently, but if you've gone through the effort to implement it then there's no need to comment it out. Even if it fails for MXNet currently this is still fine. We'll add tests for this at a later stage, and then re-address all methods. Once this is uncommented (or removed), then this PR is good-to-go!

**Review by mattbarrett98 — APPROVED** [review]

**Comment by djl11** [comment]
Thanks!

**Comment by UditArora2000** [comment]
Happy to help!

**Comment by UditArora2000** [comment]
Sir
Would be really helpful if you could share when the next phase of the
internship will start?
Thanks and Regards
Udit Arora

**Pull request merged**
