### PR TITLE
Fixes for test_extensions.py file

### PR DESCRIPTION
**Pull request by vaatsalya123**
Made some basic fixes for better production use.

### CODE REVIEW

**Comment by JamieLine** [comment]
Looks good other than the linting error, once that's fixed it'll be good to merge!

**Comment by JamieLine** [comment]
Hi, there's a "repeated keyword argument" error on line 203, I think in a merge a line got added in that isn't meant to be there. The rest looks good though!

**Comment by JamieLine** [comment]
Hi! I've just run the tests locally, all seems fine in the `vorbis_window` test, but the `flatten` test is failing because of an `int object is not subscriptable` error. There should be a flag in `helpers.get_axis` to ensure that the output is a tuple, but I don't know enough about what the test is doing to know if this is the best fix. It shouldn't be too difficult to fix though. If you have any questions or comments please let me know!

**Comment by vaatsalya123** [comment]
Hey my bad I accidentally for test purposes removed force_tuple method should be fixed now thanks (:

**Comment by JamieLine** [comment]
No worries! I'll merge it now!

**Pull request merged**
