### PR TITLE
[feature] -> Add Reduction ops(median) to PyTorch frontend

### PR DESCRIPTION
**Pull request by jatinS-dev**

### CODE REVIEW

**Comment by jatinS-dev** [comment]
@zaeemansari70 any feedback of this PR?

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hey @jatinS-dev ! 
Thank you so much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Your tests are passing, kindly fix the lint errors so we can merge your PR! 🙂

Do let me know if you have any other questions!
Thanks!

**Comment by jatinS-dev** [comment]
I've fixed the linting error in reduction file, but in test_reduction it is showing like 
i) ./test_reduction_ops.py:733:1: W391 blank line at end of file
but when I remove it, it shows 
ii) ./test_reduction_ops.py:732:6: W292 no newline at end of file
Its kind of deadlock for me while fixing the coding style, 
@zaeemansari70 any suggestions?

**Comment by jatinS-dev** [comment]
@zaeemansari70 done with the formatting. The other formatting error in test_reduction is unable to solve by the pre-commit

**Pull request closed without merging**
