### PR TITLE
average

### LINKED ISSUE #10185: average

### PR DESCRIPTION
**Pull request by hodanik**
Close #10185

### CODE REVIEW

**Comment by hodanik** [comment]
Dear @zaeemansari70, This new PR includes the tensorflow and torch average functions as you requested. thanks for the review. 🙂

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi @hodanik ,
Thanks for adding the missing backends. :slightly_smiling_face: 
Please add the test in the experimental statistical file so I can review your PR properly.

Do let me know if you have any other questions.
Thanks! :slightly_smiling_face:

**Comment by hodanik** [comment]
Hi @zaeemansari70, thanks for the comment. I added the test part but unfortunately they are not passed. Could you please take a look? I also added the missed part of the container. 
BR

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi @hodanik ,
Please request a review when the tests are either passing or if you have a specific question and you are having trouble in solving something specific. :slightly_smiling_face: 
Happy to answer any question!

Also can you please resolve the conflicts too? :slightly_smiling_face: 
Do let me know if you have any questions, Thanks :slightly_smiling_face:

**Comment by hodanik** [comment]
Hi @fspyridakos, not sure if I should ask this question from you, but hope you could please help. I get errors while running the updated IVY code, while all parts were working fine before the update. should I some how update the ivy-test separately? because the errors of all parts are because of pytest fails.  
For example, This is the error I get when running the main directory of IVY: 

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/local/lib/python3.8/dist-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
ivy_tests/test_array_api/conftest.py:7: in <module>
    from array_api_tests import _array_module as xp
ivy_tests/test_array_api/array_api_tests/__init__.py:6: in <module>
    from ._array_module import mod as _xp
ivy_tests/test_array_api/array_api_tests/_array_module.py:27: in <module>
    raise RuntimeError("No array module specified. Either edit _array_module.py or set the ARRAY_API_TESTS_MODULE environment variable")
E   RuntimeError: No array module specified. Either edit _array_module.py or set the ARRAY_API_TESTS_MODULE environment variable
=========================== short test summary info ============================
ERROR  - RuntimeError: No array module specified. Either edit _array_module.p...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 4.10s ===============================

Process finished with exit code 2

**Comment by hodanik** [comment]
Hi @zaeemansari70, I wonder if I should ask the following question as a review request. But I hope you could please help. 
could you please help about the new updates? I synced my  forked branch with the updated origin ivy. But when I run this new version I get several errors in each modules. while they all was working fine before the updates. 
Should I somehow update the ivy-test separately? Because the errors of all parts are caused by pytest fails.

**1. For example, This is the error I get when running the main directory of IVY:**

            ==================================== ERRORS ====================================
            ________________________ ERROR collecting test session _________________________
            /usr/lib/python3.8/importlib/__init__.py:127: in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
          <frozen importlib._bootstrap>:1014: in _gcd_import
             ???
         <frozen importlib._bootstrap>:991: in _find_and_load
             ???
         <frozen importlib._bootstrap>:975: in _find_and_load_unlocked
             ???
        <frozen importlib._bootstrap>:671: in _load_unlocked
            ???
         /usr/local/lib/python3.8/dist-packages/_pytest/assertion/rewrite.py:168: in exec_module
         exec(co, module.__dict__)
        ivy_tests/test_array_api/conftest.py:7: in <module>
         from array_api_tests import _array_module as xp
        ivy_tests/test_array_api/array_api_tests/__init__.py:6: in <module>
        from ._array_module import mod as _xp
       ivy_tests/test_array_api/array_api_tests/_array_module.py:27: in <module>
          raise RuntimeError("No array module specified. Either edit _array_module.py or set the 
       ARRAY_API_TESTS_MODULE environment variable")
        E   RuntimeError: No array module specified. Either edit _array_module.py or set the ARRAY_API_TESTS_MODULE 
       environment variable
        =========================== short test summary info ============================
      ERROR  - RuntimeError: No array module specified. Either edit _array_module.p...
          !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
         =============================== 1 error in 5.33s ===============================

         Process finished with exit code 2


**2. For example by running: backends/jax/experimental/statistical.py.** 
       The error: ModuleNotFoundError: No module named 'ivy' . 2. Another example: Launching pytest with arguments
        /ivy/ in 
        /ivy. The error: RuntimeError: No array module specified. Either edit _array_module.py or set the 
        ARRAY_API_TESTS_MODULE environment variable
**3. Another example: container/experimental/statistical.py.** 
       The error:  x.median(axis=0)
        NameError: name 'x' is not defined    

Could you please help to find the reason?

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Your PR shows 44 files changed after the sync, Kindly try fixing it that it shows only your respective files which are committed so I can review the PR. :slightly_smiling_face:

**Comment by zaeemansari70** [comment]
Take a look at this announcement, I hope this resolves it :slightly_smiling_face: 
https://discordapp.com/channels/799879767196958751/983684937712558080/1080080255387189318

**Comment by zaeemansari70** [comment]
Closing due to inactivity for more than 2 months :slightly_smiling_face:

**Pull request closed without merging**
