### PR TITLE
Added arccosh to frontend and added testing

### LINKED ISSUE #16582: arccosh

### PR DESCRIPTION
**Pull request by h-aze**
Close #16582

### CODE REVIEW

**Review by khushi-411 — COMMENTED** [review]
Hi @h-aze! Thanks for the PR. Your implementation looks good to me, but there are failures. Some of them are flaky. Could you please update the branch and take a look at them? Feel free to ping me if you need any help. Thanks!

**Comment by h-aze** [comment]
Hi @khushi-411, I have updated my branch a few times now but some of the "intelligent-tests-pr" are failing, a different number each time!, they don't give any informative information on why exactly they are failing. Do you have any pointers on what could be wrong? Thank you!

**Comment by khushi-411** [comment]
Thanks for reaching out, @h-aze! The the majority of test failures are not related to the PR.
> "intelligent-tests-pr" are failing, a different number each time!, they don't give any informative information on why exactly they are failing. Do you have any pointers on what could be wrong? Thank you!

Sure, you could check the failures in `Determine and Run Tests` part. Thanks!

**Comment by khushi-411** [comment]
Gentle ping! Could you please rebase the PR?

**Pull request closed without merging**
