### PR TITLE
Adjusted the Image Contrast 

### LINKED ISSUE #22205: adjust_contrast

### PR DESCRIPTION
**Pull request by ahmad-zayab**
Close #22205

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by D0m-inic** [comment]
Hi, please refer to our docs https://unify.ai/docs/ivy/overview/contributing.html on contributing to ivy.

You'll need to find an open task: https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#open-tasks

And go through the protocol of creating an issue for the task and linking the pull request.

As for your problems with your GitHub accounts, I would suggest forking the repo on the correct account and copying the changes across 👍

**Comment by ahmad-zayab** [comment]
> Hi, please refer to our docs https://unify.ai/docs/ivy/overview/contributing.html on contributing to ivy.
> 
> You'll need to find an open task: https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#open-tasks
> 
> And go through the protocol of creating an issue for the task and linking the pull request.
> 
> As for your problems with your GitHub accounts, I would suggest forking the repo on the correct account and copying the changes across 👍 . Feel free to close your current pull request and reopen it with the correct account if necessary.

I did the changes you ask for kindly review it again

**Comment by D0m-inic** [comment]
Please refer to the docs, you need to find an issue on the todo list, claim the issue and then link it to this PR

**Comment by ahmad-zayab** [comment]
> _ No description provided. _

Close #22205

**Comment by D0m-inic** [comment]
Hi, why did you remove the hflip implementation and test?
Could you add it back 😃

**Comment by ahmad-zayab** [comment]
@D0m-inic kindly see what's the issue here guide me to solve this

**Comment by D0m-inic** [comment]
Hi, you're still removing the implementation of the `hflip` test and you've got your `adjust_contrast` function duplicated.

**Comment by ahmad-zayab** [comment]
@D0m-inic kindly review it now.

**Comment by D0m-inic** [comment]
Hi, you're still overwriting the `test_paddle_vflip` function and removing the comments for the title of the main and helpers. Make sure you're merging your branch correctly with master 👍

**Comment by ahmad-zayab** [comment]
@D0m-inic kindly review it now

**Comment by D0m-inic** [comment]
You are modifying the  `test_paddle_to_tensor` test, which doesnt seem to be necessary 👍 . Also please add back the Helpers and Main headers which you have removed

**Comment by ahmad-zayab** [comment]
@D0m-inic Is it right now? Kindly check it.

**Comment by Aarsh2001** [comment]
Hey @ahmad-zayab closing this PR due to inactivity, feel free to reopen once you're done with your changes 🙂

**Comment by ahmad-zayab** [comment]
@Aarsh2001 how can I reopen this?

**Comment by ZoeCD** [comment]
Hey, here is a list of things I noticed you need to add/change to your PR:

- [ ] Change the name of the PR to follow the conventional title rules
- [ ] Add back the Helpers and Main headers
- [ ] Check your test is passing (The workflows are running for me now, so I can't see the results yet)
- [ ] Check you're not adding new formatting errors

I already linked the new issue you created to the PR. Also, you can read the docs [here](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#pull-requests) to learn more about contributing and creating your PR. We appreciate your patience!

**Comment by ahmad-zayab** [comment]
@ZoeCD kindly check it

**Comment by ahmad-zayab** [comment]
@Aarsh2001 kindly check it now.

**Review by Aarsh2001 — CHANGES_REQUESTED** [review]
Hey @ahmad-zayab kindly fix the failing tests ? I tried running your code on my machine, it seems to fail for all backends. Can you recheck the `supported_dtypes` and your implementation for the function, thanks !

**Comment by ahmad-zayab** [comment]
@Aarsh2001  kindly guide me on how to solve this error Check Semantic and welcome new contributors / PR Compliance Checks (pull_request_target) waiting for your reply.

**Comment by ahmad-zayab** [comment]
@Aarsh2001 kindly review it

**Comment by NiteshK84** [comment]
Hi @ahmad-zayab, all the backend tests are failing,
image
please run the test in your local env, go through the error messages which are printed above the result and try to analyse and fix your implementation of func and test, it might resolve your failures.
and let me know once it is done.
Thanks😊

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
