### PR TITLE
added zeta

### LINKED ISSUE #14156: zeta

### PR DESCRIPTION
**Pull request by piyushgit011**
closes #14156

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by piyushgit011** [comment]
hey @KareemMAX can you look into this?

**Comment by Ookamice** [comment]
@piyushgit011 
Sorry for taking so long to review your PR. Could you please write the unit test for the function you've added as well please. More detail can be found in the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing.html).

Let me know if you have any other concerns or questions! 👀

**Comment by Ookamice** [comment]
@piyushgit011 

Hiya, the intelligent test work by analysing what you have modified, how it relates to other parts of the codebase, and running the  relevant unit tests for all the functions. Since a unit test does not exist for zeta, it will not perform any tests on the function you have written. Please have a read of the  [frontend section of the contributor's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis). 😄

**Comment by piyushgit011** [comment]
hey , i think it's already implemented by some another one , thanks for help #14125

**Pull request closed without merging**
