### PR TITLE
ivy.ones formatted and small fix done about mxnet

### PR DESCRIPTION
**Pull request by alierenak**
All backends are formatted. Except mxnet all backend tests are passed.

About mxnet,

`mx.nd.ones()` (as well as `full()` and `zeros()`) not accept empty lists or zero as an input. So in generic functions there is a check for it however it fails on integer input. So we need to check for 2 things additionally;

1. If shape is integer --> call `mx.nd.ones`
2. if shape is 0 --> call `_1_dim_array_to_flat_array`

Indeed we can convert integer to 1D array (1 -> [1]) before if statement to solve this situation. So I added new line to mxnet for this purpose.

```python
# noinspection PyShadowingNames
def ones(shape: Union[int, Tuple[int, ...]],
         dtype: Optional[mx.nd.dtype] = 'float32',
         device: Optional[str] = None) \
        -> mx.ndarray.ndarray.NDArray:
    cont = _mxnet_init_context(default_device(device))

    # shape = 1 -> len(1) -> Error
    # also we accept integer inputs in according to Array API. So I added new check here (shape==0). (Also to ivy.full which is already implemented)
    if len(shape) == 0 or 0 in shape: 
        return _1_dim_array_to_flat_array(mx.nd.ones((1,), ctx=cont).astype(dtype))
    return mx.nd.ones(shape, ctx=cont).astype(dtype)
```

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by alierenak** [comment]
Thanks for the quick reply.

Actually, I already gave permission to maintainers. It said "users with write access to unifyai/ivy can add new commits to your master branch." Could you please try again?

**Comment by djl11** [comment]
> Thanks for the quick reply.
> 
> Actually, I already gave permission to maintainers. It said "users with write access to unifyai/ivy can add new commits to your master branch." Could you please try again?

Yes you're right, thanks!

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Comment by alierenak** [comment]
- [X] All methods should be defined with def func_name explicitly, no lambdas or direct binding.
- [X] All Ivy methods should have type-hints and doc strings
- [X] All backend methods should have type-hints, but no doc strings.
- [X] All Array API methods should be moved to the correct sub-modules and files.

All of them is already done. I pushed small fix about backends functions. Thanks

**Comment by alierenak** [comment]
Hi @djl11,

I fixed circular import issue; however still test_ivy check failed. I guess, error is not about my PR. If you don't think so, I would be happy if you can guide me to find the problem. Thanks

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
