### PR TITLE
Feature/add frontend function paddle tensor nanmedian

### LINKED ISSUE #22511: nanmedian
- [ ] #15115

### PR DESCRIPTION
**Pull request by AliTarekk**
Close #22511

### CODE REVIEW

**Comment by AliTarekk** [comment]
@rishabgit kindly review my PR

**Comment by AliTarekk** [comment]
@rishabgit Kindly review my PR after modification. Thanks!

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi @AliTarekk, thanks for looking into this. Your issue wasn't correctly commented on the ToDo list, so I've manually made the entry, in the future, please use the syntax as mentioned in our [docs](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) 😅 

I've removed the incorrect expected return from `dtype_and_x` but tests are failing due to incorrect dtype usage, could you please look into it? Feel free to request for review afterward. Thanks! 😄

**Comment by rishabgit** [comment]
This PR has been closed because it has been stale for more than 7 days with no activity.

**Pull request closed without merging**
