### PR TITLE
Index select torch

### PR DESCRIPTION
**Pull request by kurshakuz**
Closes https://github.com/unifyai/ivy/issues/6878

### CODE REVIEW

**Comment by kurshakuz** [comment]
@ZoeCD can you check if I made the test correctly? The implementation is correct, but I am not sure if I need to expand the hypothesis space somehow.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ZoeCD** [comment]
Hi! Sorry for the late response, I didn't notice you asked me a question. It looks good to me! But what do you mean by "expanding the hypothesis space"? Also, now there are some branch conflicts to solve before merging

**Comment by kurshakuz** [comment]
Can't test right now due to recent refactoring, merging for now

**Pull request merged**
