### PR TITLE
Add resize to transforms.py

### LINKED ISSUE #22633: resize
- [ ] #15046

### PR DESCRIPTION
**Pull request by alec-kr**
This PR adds the `resize` function to the existing codebase in transforms.py.

## Related Issue

Closes #22633

### CODE REVIEW

**Comment by AlexandraPosta** [comment]
Hello @alec-kr, please solve your merge conflicts and I will review it right after.

**Comment by alec-kr** [comment]
@AlexandraPosta Merge conflicts have now been resolved.

**Comment by AlexandraPosta** [comment]
Hello @alec-kr! Thank you for that.

I have just noticed that you have not reference the issue properly. Please check [our documentation](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) and change the comment that you left [here](https://github.com/unifyai/ivy/issues/15046). Currently, in the task list, your function is not referenced as open, so a different contributor can take it over.

In terms of the function implementation, by looking at the raw log, you get this error: ```AttributeError: module 'ivy.functional.backends.torch' has no attribute 'resize'```. Normally, the process needed to change the size of the given is called interpolation. At ivy, we have a [backend function dedicated for interpolation](https://unify.ai/docs/ivy/docs/functional/ivy/experimental/layers/ivy.functional.ivy.experimental.layers.interpolate.html) that I would suggest you to use.

**Comment by AlexandraPosta** [comment]
Hello @dhruvsaxena11, just checking whether you are still working on the PR. :zap:

**Pull request closed without merging**
