### PR TITLE
[feature] -> Add Reduction Ops to PyTorch frontend

### PR DESCRIPTION
**Pull request by jatinS-dev**
Closes https://github.com/unifyai/ivy/issues/10886

### CODE REVIEW

**Comment by jatinS-dev** [comment]
With reference to PR https://github.com/unifyai/ivy/pull/10901
Closed the issue https://github.com/unifyai/ivy/issues/10886

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @jatinS-dev ! Your implementation is throwing following error:
```
================================================================ 1 warning, 1 error in 3.57s ================================================================
ERROR: not found: /workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py::test_torch_median
(no name '/workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py::test_torch_median' in any of [<Module test_reduction_ops.py>])
```

**Comment by jatinS-dev** [comment]
@kurshakuz can you check now?

**Comment by jatinS-dev** [comment]
@kurshakuz can you give an idea what could be the problem over here?

**Pull request closed without merging**
