### PR TITLE
feat: add serialize to tf frontend with the test

### LINKED ISSUE #25772: serialize

### PR DESCRIPTION
**Pull request by abdul-rehman18**
# PR Description
Added a serialize function in TensorFlow front end

## Related Issue

Close #25772 

<!--
Please mark your PR as a draft if you realise after the fact that your tests are not passing or
that your pre-commit check has some failures.

Here are some relevant resources regarding tests and pre-commit:

https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html
https://unify.ai/docs/ivy/overview/deep_dive/formatting.html#pre-commit

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Hi @abdul-rehman18 thank you for your first contribution, can you fix the title?

**Comment by abdul-rehman18** [comment]
Hi @a0m0rajab 
For sure I can fix it but could you explain a bit

**Comment by a0m0rajab** [comment]
@abdul-rehman18 thanks, the action bot explained it in details: 
https://github.com/unifyai/ivy/pull/25790#pullrequestreview-1637504074

TL:DR; you need to follow **feat: description** style

**Comment by abdul-rehman18** [comment]
@a0m0rajab 
Sir are you reviewing my pr?

**Comment by Ishticode** [comment]
closing this as it looks like a duplicate of https://github.com/unifyai/ivy/pull/23432

**Pull request closed without merging**
