### PR TITLE
add docstrings of optimizer_update function

### LINKED ISSUE #1833: optimizer_update

### PR DESCRIPTION
**Pull request by yugaljain1999**
fixes #1833

### CODE REVIEW

**Comment by yugaljain1999** [comment]
@RashulChutani @djl11 Can you pls review this PR?

**Review by RashulChutani — COMMENTED** [review]
Hi @yugaljain1999, The added docstring looks good. Can you also make the required changes for the corresponding Ivy container and Array Functions as mentioned here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting. Thanks

**Comment by yugaljain1999** [comment]
Hi @RashulChutani , I have already added container functions and @djl11 told me there is no need to add native array examples as it makes it complex. You can view this closed PR where he suggest me this. #1834 

And I did above changes exactly as per daniel review. You can view that closed PR for more info.

Hope you are getting me.
Thanks

**Comment by RashulChutani** [comment]
Sure. Thanks for clarifying. Please ensure that docstrings tests pass. I
will just have a final review and then merge the same.

**Comment by yugaljain1999** [comment]
@RashulChutani Docstrings passes successfully. You can merge this PR.
Thanks

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Oh, I see the function as failing in the test-docstring Workflow. Can you please check once?

**Comment by yugaljain1999** [comment]
@RashulChutani I just checked those docstrings test but that's failing because of another function not this optimizer_update function as you can see here.
image
image
image


Hope it's clear to you now. Now you can merge this PR.
Thanks

**Comment by RashulChutani** [comment]
Sure. That's awesome. I think I saw your function in the error log there. No worries though. I will have a look again in the test-docstring logs and let you know. Anyways, Great Work!

**Pull request merged**
