### PR TITLE
Deep dive update: Remove all mentions of container static methods as they’re private now

### PR DESCRIPTION
**Pull request by Daniel4078**

### CODE REVIEW

**Comment by Daniel4078** [comment]
What kind of lable should I use for this and what issue should I link the pull request to? This task can be found here: https://docs.google.com/document/d/1U4g-z7wdn-oaArmWbIMuH0aG7RT-0lyvpdO8wbHjK9A

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
Hey @Daniel4078, thanks for making the changes! There seem to be a few other files with mentions of container static methods such as `contributing/open_tasks.rst`, `deep_dive/containers.rst, function_types.rst, function_wrapping.rst`, could you please remove those as well? I'd suggest running a search in the `docs` folder at the end to ensure we remove all occurrences. Thanks again 😄👍

**Comment by Daniel4078** [comment]
@vedpatwardhan Some of the reference to container static functions are API static functions that calls the corrisponding ones under the hood. Should I remove this kind of indirect reference?

**Comment by vedpatwardhan** [comment]
> @vedpatwardhan Some of the reference to container static functions are API static functions that calls the corrisponding ones under the hood. Should I remove this kind of indirect reference?

Hey @Daniel4078 I couldn't actually understand that 😅
Could you please share an example where that's the case? Thanks 😄

**Comment by Daniel4078** [comment]
"Under the hood, the :class:`ivy.Container` API static methods are called when :class:`ivy.Container` instances are passed in as inputs to functions in the functional API." So this line in the  deep_dive/function_types.rst, it does not mention container static methods directly. also "In such cases, the function in the functional API defers to this static [:class:`ivy.Container`](https://github.com/Daniel4078/ivy/blob/Remove-all-mentions-of-container-static-methods-in-docstring-part-of-deepdive/docs/overview/deep_dive/containers.rst#id19) implementation. Under the hood, [ivy.Container.cont_multi_map_in_function](https://github.com/unifyai/ivy/blob/b725ed10bca15f6f10a0e5154af10231ca842da2/ivy/container/base.py#L162) enables us to pass in arbitrary combinations of containers and non-containers, and perform the correct mapping across the leaves. Internally, [:meth:`ivy.Container.cont_multi_map_in_function`](https://github.com/Daniel4078/ivy/blob/Remove-all-mentions-of-container-static-methods-in-docstring-part-of-deepdive/docs/overview/deep_dive/containers.rst#id21) calls [`ivy.Container.multi_map`_](https://github.com/Daniel4078/ivy/blob/Remove-all-mentions-of-container-static-methods-in-docstring-part-of-deepdive/docs/overview/deep_dive/containers.rst#id114). In cases where there are no containers passed, [ivy.Container.cont_multi_map_in_function](https://github.com/unifyai/ivy/blob/b725ed10bca15f6f10a0e5154af10231ca842da2/ivy/container/base.py#L162) will simply call the function once on the non-container arguments provided.

A few examples of [:class:`ivy.Container`](https://github.com/Daniel4078/ivy/blob/Remove-all-mentions-of-container-static-methods-in-docstring-part-of-deepdive/docs/overview/deep_dive/containers.rst#id23) API static methods are [ivy.Container.static_add](https://github.com/unifyai/ivy/blob/b725ed10bca15f6f10a0e5154af10231ca842da2/ivy/container/elementwise.py#L324), [ivy.Container.static_tan](https://github.com/unifyai/ivy/blob/b725ed10bca15f6f10a0e5154af10231ca842da2/ivy/container/elementwise.py#L7285) and [ivy.Container.static_roll](https://github.com/unifyai/ivy/blob/b725ed10bca15f6f10a0e5154af10231ca842da2/ivy/container/manipulation.py#L835)." in deep_dive/containers.rst.

**Review by vedpatwardhan — COMMENTED** [review]
> "Under the hood, the :class:`ivy.Container` API static methods are called when :class:`ivy.Container` instances are passed in as inputs to functions in the functional API." So this line in the deep_dive/function_types.rst, it does not mention container static methods directly. Also "Under the hood, every instance method calls the corresponding static method. For example, [ivy.Container.add](https://github.com/unifyai/ivy/blob/8d1eef71522be7f98b601e5f97bb2c54142795b3/ivy/container/elementwise.py#L92) calls [:meth:`ivy.Container.static_add`](https://github.com/Daniel4078/ivy/blob/Remove-all-mentions-of-container-static-methods-in-docstring-part-of-deepdive/docs/overview/deep_dive/containers.rst#id40), [ivy.Container.tan](https://github.com/unifyai/ivy/blob/b725ed10bca15f6f10a0e5154af10231ca842da2/ivy/container/elementwise.py#L7347) calls [:meth:`ivy.Container.static_tan`](https://github.com/Daniel4078/ivy/blob/Remove-all-mentions-of-container-static-methods-in-docstring-part-of-deepdive/docs/overview/deep_dive/containers.rst#id42), and [ivy.Container.roll](https://github.com/unifyai/ivy/blob/b725ed10bca15f6f10a0e5154af10231ca842da2/ivy/container/manipulation.py#L927) calls [:meth:`ivy.Container.static_roll`](https://github.com/Daniel4078/ivy/blob/Remove-all-mentions-of-container-static-methods-in-docstring-part-of-deepdive/docs/overview/deep_dive/containers.rst#id44)." in deep_dive/containers.rst.

Hey @Daniel4078, thanks for elaborating! I think we should get rid of both these usages, because if the container static methods are private, there isn't really any benefit of mentioning that they're being called under the hood in the docs. Of course, with the second example, we'd have to remove that mention simply because `ivy.Container.static_add` doesn't exist anymore. Hope that makes sense 😄

**Comment by Daniel4078** [comment]
ivy-gardener

**Comment by Daniel4078** [comment]
Is API static methods also needed to be removed? I though they are not container static methods. @vedpatwardhan

**Comment by vedpatwardhan** [comment]
> Is API static methods also needed to be removed? I though they are not container static methods. @vedpatwardhan

Actually the container static methods are the only static methods in the API 😅

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Feel free to merge, thanks @Daniel4078 😄

**Pull request merged**
