### PR TITLE
jax.numpy floor function

### PR DESCRIPTION
**Pull request by ema-alb**
- Added floor function
- Re-ordered name_space_functions.py functions alphabetically
- Added test

### CODE REVIEW

**Comment by ogbanugot** [comment]
Hey @ema-alb the PR looks good however, is it possible to create issues (if they don't exist already) for the corresponding functions listed here https://github.com/unifyai/ivy/issues/4612 so that we can link them to this PR. You may want to check out this guide [here](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis) for any clarifications on creating the issues.

**Comment by ema-alb** [comment]
Close #5691

**Comment by ema-alb** [comment]
> Hey @ema-alb the PR looks good however, is it possible to create issues (if they don't exist already) for the corresponding functions listed here #4612 so that we can link them to this PR. You may want to check out this guide [here](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis) for any clarifications on creating the issues. Just for clarification, you should comment `Close #<issue-number>` here on this PR for all the corresponding issues.

Hey @ogbanugot, please let me know if the way I commented works. I had previously created the issue (#5691), but I thought I had to comment with `Close #issue_number` only after you validated my commit.

**Comment by ogbanugot** [comment]
Hi @ema-alb , the way you commented is fine, however, I noticed that your PR has implementations for other functions as well (`arctan`, `arctan2`, `sin`, `sinh`, `cos`, `cosh`). Although it's advised that you work on only one function per PR, if you wish to contribute all these functions then you'll need to create issues (if they aren't created already) and then comment `Close #<issue-number>` for them as well.

**Comment by ema-alb** [comment]
Though it seems like I "worked" on that as well, in reality what I did was just to reorder all the functions to match the order they have on the jax docs.
Would it still be needed to comment on each specific issue for this minor change?

**Comment by ogbanugot** [comment]
Oh I see! In that case, no need, I'll go ahead and approve this now.

**Review by ogbanugot — APPROVED** [review]

**Comment by ema-alb** [comment]
Next time I'll try to be more specific with my commits: I'll commit each individual step (adding the function only, then reordering, then implementation of the tests) to make it more clear :)
Thank you

**Pull request merged**
