### PR TITLE
Add normal to Torch frontend

### LINKED ISSUE #13365: normal

### PR DESCRIPTION
**Pull request by adityagandhamal**
Close #13365
Implemented and tested the random sampling function `normal` in Torch frontend

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hey @adityagandhamal, can you resolve the merge conflicts please?
Thanks!

**Comment by adityagandhamal** [comment]
hey @V-G-spec, the merge conflicts have been resolved, and also to confirm, the linter issues do not pertain to my code. Thanks!

**Comment by adityagandhamal** [comment]
Hey @V-G-spec, I had to resolve the merge conflicts again. And also to mention, the failing test cases are due to other parts of the code and not related to my implementation

**Comment by V-G-spec** [comment]
Everything looks great, can you tell me why you have only taken floats here?

**Comment by adityagandhamal** [comment]
Is there any possibility to extend this to have a superset behavior by considering other dtypes?

**Comment by V-G-spec** [comment]
No, this is fine. Can you quickly revert a small change you made in the test file? You removed a new line and added newline with tab. Won't make difference to the codebase, but better to keeps things clean

**Comment by adityagandhamal** [comment]
hey @V-G-spec, I've done the changes as suggested. Please have a look. 
Thanks!

**Pull request merged**
