### PR TITLE
Permutation method for jax frontend

### LINKED ISSUE #14840: permutation

### PR DESCRIPTION
**Pull request by iammarco11**
Closes #14840

### CODE REVIEW

**Comment by iammarco11** [comment]
Hi @Ookamice, please review and let me know if any changes are required. Thanks!

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hiya, mostly looks good but a few changes need to be made please. 👍

1) please could you use [`ivy.take_along_axis()`](https://unify.ai/docs/v1.1.9/ivy/docs/functional/ivy/experimental/manipulation/ivy.functional.ivy.experimental.manipulation.take_along_axis.html) instead of importing and using ivy's numpy frontend.

2) please see [`jax.random.permutation`](https://jax.readthedocs.io/en/latest/_autosummary/jax.random.permutation.html) and implement the `independent` flag. The function declaration should match the function being implemented so it would also be great if you could remove the `dtype` flag.

Let me know if you have any other questions!

**Comment by iammarco11** [comment]
Hey @Ookamice, thanks for the speedy review :)

**Comment by Ookamice** [comment]
@iammarco11 
> I added the dtype flag because it was required for the test method. Right now the test fails returning an error related to it. Could you review it again.

Is that so? 😅 Then that suggestion is a mistake on my part, could you add it back in so the tests pass please? After that, it should be all good!

**Comment by iammarco11** [comment]
Hi @Ookamice 
Test 3 is failing with this output.
```
     from jaxlib.xla_extension import Buffer
E   ImportError: cannot import name 'Buffer' from 'jaxlib.xla_extension' (/opt/fw/jax/jaxlib/xla_extension.so)
```

This is not due to the change I made since I checked it with the first commit on which you reviewed which passed all the test cases but pushed it couple of minutes back which failed. Right now this PR has all the changes you suggested. Please share your inputs. Thanks :)

**Comment by Ookamice** [comment]
@iammarco11 

Hiya, I've checked the CI tests and they don't appear to be running your newly created test test_jax_permutation and the reported errors are with test_jax_randint so it's not something you have to worry about fixing.

I've opened up a codespace using your changes and ran `python3 -m pytest ivy_tests/test_ivy/test_frontends/test_jax/test_jax_random.py::test_jax_permutation  --backend 'all' -rxXs` but there are some errors. Please let me know if the tests pass on your end or not!

**Comment by Ookamice** [comment]
Main issue is with `framework = None` I believe @iammarco11 

I'm not quite sure so I did some searching on the Ivy [discord]((https://www.discord.com/channels/799879767196958751/982738436383445073/1090305719003258990)) and I gathered it could be due to some of the backends not being installed properly? I think I have resolved this in the codespace by installing the requirements but I have ran into another issue with `ImportError: cannot import name 'Buffer' from 'jaxlib.xla_extension'` which means the test can't be ran.

Let me know if you have any ideas to resolve it! I'll raise it with the team in the mean time

**Comment by Ookamice** [comment]
@iammarco11, I have resolved the issues with jax framework by pip3 installing an older version of jax (`jax==0.4.8` and `jaxlib==0.4.7`). However, the tests are still failing but it should be easier to troubleshoot now.

Let me know if you have any other concerns or if the issues are still cropping up for you! 💪

**Comment by iammarco11** [comment]
Hey @Ookamice,

I did some more fixes.

```
FAILED ivy_tests/test_ivy/test_frontends/test_jax/test_jax_random.py::test_jax_permutation[cpu-ivy.functional.backends.jax-False-False] - ivy.utils.exceptions.IvyBackendException: jax: shuffle: shuffle() got some positional-only arguments passed as keyword arguments: 'x'
```

I realized that the above error points that the shuffle method numpy and `jax.random.permutation` is expecting has one more argument called axis passed. More about it [here](https://jax.readthedocs.io/en/latest/_autosummary/jax.random.shuffle.html)

**Comment by Ookamice** [comment]
Hiya @iammarco11 
> But our current backend wrapper does not take axis as an argument

From my understanding, Ivy functions aim for superset behaviour so this is a great issue you have spotted. I'd suggest opening an issue as according to the [contributer's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) detailing `ivy.shuffle` to support the `axis` flag akin to `jax.random.shuffle` and a member of our team will get to it! 👍

**Comment by iammarco11** [comment]
@Ookamice would this PR be too big if I do the backend changes myself?

**Comment by Ookamice** [comment]
> @Ookamice would this PR be too big if I do the backend changes myself? Since it is just one argument and the testing would not be a big challenge.

Go for it!! 🚀🚀

**Comment by iammarco11** [comment]
@Ookamice sorry might be a basic question since I did not research the documentation much :P But say I have to test `test_shuffle` which is a backend function. is there anyway to that like this
> `python3 -m pytest ivy_tests/test_ivy/test_frontends/test_jax/test_jax_random.py::test_jax_permutation  --backend 'all' -rxXs`

**Comment by iammarco11** [comment]
@Ookamice great news is that the tests for jax frontend permutation passes. But the `test_tensorflow_shuffle` is failing. I am not sure though why it fails. Looking to hear your inputs on it. Thank you!

**Comment by Ookamice** [comment]
@iammarco11 

Awesome work you're doing here! I'm really not sure because my experience with backend developement is lacking. Could I ask you to check if the tensorflow test passed before you made the changes? I know that whilst Ivy tries for superset behavior, sometimes there are weird edgecases where backends have conflicting behaviour and we have to compromise and pick the most frequent one.

Thank you!

**Comment by iammarco11** [comment]
@Ookamice 
I tested the `test_tensorflow_shuffle` using `python3 -m pytest ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle  --backend 'all'` in a codespace

```
framework = None, kind = 'valid'

    def _get_fn_dtypes(framework, kind="valid"):
>       return test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[framework.backend][
            test_globals.CURRENT_DEVICE_STRIPPED
        ][kind]
E       AttributeError: 'NoneType' object has no attribute 'backend'
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.75.2', b'AA==') as a decorator on your test case

ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:35: AttributeError
=================================================================== short test summary info ===================================================================
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle[cpu-ivy.functional.backends.numpy-False-False] - AttributeError: 'NoneType' object has no attribute 'backend'
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle[cpu-ivy.functional.backends.jax-False-False] - AttributeError: 'NoneType' object has no attribute 'backend'
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle[cpu-ivy.functional.backends.torch-False-False] - AttributeError: 'NoneType' object has no attribute 'backend'
```

Not sure how to proceed further lol. Error similar like the previous `jaxlib` one. Anyway the CI has a different error thrown.

**Comment by Ookamice** [comment]
@iammarco11 

Hiya, this error is due to an update with jax and jaxlib that broke our systems a little. Please do 'pip3 install jax=0.4.8` and `pip3 install jaxlib=0.4.7` to resolve this. In the meantime, I'll check if there's any internal notes about tensorflow shuffle!

**Comment by iammarco11** [comment]
@Ookamice hey
yeah I solved the jax error long back with your fix, let me know if there is a similar fix for tensorflow

**Comment by Ookamice** [comment]
I'lllook into it :)

**Comment by Ookamice** [comment]
@iammarco11 
It looks like all Tensorflow tests have this attributeError which I think is similar to what happened with Jax. Tried to downgrade it but it still didn't work. Looked around and no solutions present yet

Let me know if it passes all the other tests. If it does, I'll give a manual sanity check over the TensorFlow test changes and get it merged for you! 🚀🚀

**Comment by iammarco11** [comment]
@Ookamice 

Currently I have reformatted the commits messages and corrected the lint formatting as well.

> Let me know if it passes all the other tests. If it does, I'll give a manual sanity check over the TensorFlow test changes and get it merged for you! 🚀🚀

It passes all the other tests(`test_jax_permutation` and `test_shuffle`). Thank you so much for the guidance and speedy reviews :)

**Comment by iammarco11** [comment]
@Ookamice 

> The change you made to ivy.shuffle to support axis passes all the backend tests apart from tensorflow's
Yes
> text_jax_permutation works for all backends apart from tensorflow's
Yes, tensorflow passes as well

**Comment by Ookamice** [comment]
@iammarco11 

One last thing just before I get this merged, I've noticed that all the test cases only test for axis=0; could you test this for other values too? Other than that, everything looks good!!

**Comment by iammarco11** [comment]
@Ookamice 

Updated according to your suggestion 

Currently, same as before the following test cases are failing.
```

Run find . -name "new_failures_*.txt" -exec cat {} + > combined_failures.txt
This PR introduces the following new failing tests:
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,numpy
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,jax
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,tensorflow
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,torch
```

**Comment by Ookamice** [comment]
@iammarco11 
Hiya, I'm slightly concerned if setting the min and max value of axis to 0 in the tests is truly robust or not.

Let me know your thoughts on this matter! 👍

**Comment by iammarco11** [comment]
Hi @Ookamice 

> Hiya, I'm slightly concerned if setting the min and max value of axis to 0 in the tests is truly robust or not.

Sorry that was a careless mistake from my side, thanks for pointing it out. I have updated the test. Let me know if there is anything else to add.

Same results still now
```
Run find . -name "new_failures_*.txt" -exec cat {} + > combined_failures.txt
This PR introduces the following new failing tests:
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,numpy
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,jax
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,tensorflow
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_shuffle,torch
```

**Comment by Ookamice** [comment]
Thanks for this PR! Just added some small changes but I think you've gotten it into a good state to be merged💪

Just stating a few observations for future reference:
- test_jax_permutation
    -  passed numpy and jax backend tests
    -  tensorflow backend test didn't run when using --backend 'all'
    -  pytorch `uint32 is not supported` error along with most other functions in `test_jax_random`

-test_shuffle
    - axis only tested for axis=0 due to ivy testing dimension 
    - backend 'all' only tested numpy and jax backend (all passed)

-additional changes: deprecated jax.random.suhuffle with jax.random.permutation with independence = True

**Comment by iammarco11** [comment]
@Ookamice Thank you so much for helping me out and pointing some to do work. Let me know if I have to add something from my side.

**Pull request merged**
