### PR TITLE
square_error_cost

### PR DESCRIPTION
**Pull request by HamzaRamzan65**

### CODE REVIEW

**Comment by HamzaRamzan65** [comment]
Hi, I am unable to identify the conflict.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by HamzaRamzan65** [comment]
Kindly tell me the reasons of my test failings.

**Comment by HamzaRamzan65** [comment]
@Aarsh2001

**Comment by HamzaRamzan65** [comment]
@hirwa-nshuti Kindly review it.

**Comment by HamzaRamzan65** [comment]
@KareemMAX Kindly review it

**Comment by KareemMAX** [comment]
Hey @HamzaRamzan65,
Sadly I'll close your PR in the meantime, as it has been stale for a very long time. Feel free to reopen the PR if you would like to continue working on it

**Pull request closed without merging**
