### PR TITLE
Double_sided_maxwell

### PR DESCRIPTION
**Pull request by stalemate1**

### CODE REVIEW

**Comment by Ookamice** [comment]
@stalemate1 
Hiya, it seems like the tests you have written aren't passing. You can run them locally with the command line using `python -m pytest  "ivy_tests/test_ivy/test_frontends/test_jax/test_random.py::test_jax_double_sided_maxwell"`. Please note that the xfail declorator means it will show up as passing even though it isn't strictly true. The reason why it is added is because there is a known issue for torch and paddle abckends with uint types for jax key. This means that if the tests manage to pass for the other backends, it would be sufficient to be merged! 😄

**Comment by stalemate1** [comment]
@Ookamice 
Hello, sorry for the delay. I finally realised double_sidded_maxwell function was just a "normal distribution function" few days ago when I was going through the basics for probability. Finally, this function is passing all the tests for all backends except for paddle and pytorch backend.  

I don't know why there are still 13 failing check here though. Could you please help me understand how to understand what failing checks to be neglected and which are the once that I have to focus on.

Thankyou!

**Comment by Ookamice** [comment]
@stalemate1 
I'm glad to see that you're making progress. Please could you first change the test helpers to `available_dtypes=helpers.get_dtypes("valid"),` as you should include all the unsupported dtypes in the frontend instead.

Also, I've ran your tests a few times over command line manually and it seems like the results are different everytime I run it with the best case being 3/5 tests passing and the worst being 0/5 tests passing. Most issues comes from `RuntimeWarning: overflow encountered in divide` which propogates into `RuntimeWarning: invalid value encountered in multiply`.

PS: The intelligent-tests-pr isn't too reliable and I would suggest manually running the tests as I have done. This is because there are still a lot of bugs in the main ivy repo so even if your code doesn't introduce any additional issues, it will still report it as failed.

**Comment by stalemate1** [comment]
When I change to` available_dtypes=helpers.get_dtypes("valid")`  I am encountering this error `TypeError: JAX encountered invalid PRNG key data: expected key_data.dtype = uint32; got dtype=int64`

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by stalemate1** [comment]
@Ookamice Sorry, I might have done some mistake while pushing my file. There were too many changes that were reflected in the files that I uploaded in this PR. Since for some reason I couldn't revert commit I open a new branch and tried uploaded the changes there. Here is the PR number #21264

**Pull request closed without merging**
