### PR TITLE
Added determinant method

### PR DESCRIPTION
**Pull request by DhruvaBhardwaj404**
[issue 110](#110)

### CODE REVIEW

**Comment by oliverxue20** [comment]
Please delete .gitignore file and then re-upload

**Comment by DhruvaBhardwaj404** [comment]
I have deleted the changes from .gitignore file.  Any other changes?

**Review by HotzingTone — CHANGES_REQUESTED** [review]
Hi, please move the code to linear_algebra.py, no need to create new files for extensions.
Also, the docstring should be consistent with what's on the API Standard website.
And, det for backends needs only one argument, as ivy.det does.
Thanks!

**Comment by DhruvaBhardwaj404** [comment]
Hi, actually the files were not created by me,it were present in the earlier commits and since the Array API documents has put `det()` method under extension , I have put in under the existing algebra extension file. So should I now move it under the algebra file?

**Comment by HotzingTone** [comment]
> Hi, actually the files were not created by me,it were present in the earlier commits and since the Array API documents has put `det()` method under extension , I have put in under the existing algebra extension file. So should I now move it under the algebra file?

Yes please do :)
Sorry for the confusion.

**Review by HotzingTone — CHANGES_REQUESTED** [review]
Once the code is in the right place and all tests pass, we'll merge the branch :)

**Comment by DhruvaBhardwaj404** [comment]
I have made the asked changes, Please do let me know it something more is required.

**Review by HotzingTone — CHANGES_REQUESTED** [review]
* Hi, it would be nice to have docstring consistent with the standard documentation https://data-apis.org/array-api/latest/extensions/generated/signatures.linalg.det.html
* Also, for torch backend's signature, it's better to use "x" as the argument name.
* Would you also please resolve all conflicts before commit?
Thanks a lot!

**Comment by DhruvaBhardwaj404** [comment]
I have made the asked changes and also have resolved all the conflicts. Please let me know ifs there's anything more!

**Comment by DhruvaBhardwaj404** [comment]
@HotzingTone, waiting for the review!

**Review by HotzingTone — COMMENTED** [review]
Thanks for your work!
The code looks fine, but the JAX test hasn't passed because of an error from diagonal.
Passing review to @djl11

**Review by djl11 — CHANGES_REQUESTED** [review]
Please uncomment the det method in the correct file in `ivy_tests/array_api_methods_to_test` (by removing the #), and then we can see if the tests are passsing :)

**Comment by 1Doomdie1** [comment]
[BOT MSG] This PR is being closed because there was no activity on this PR in the last 7 days, and you have not requested a code review from us. Please check our policy on the closing of PRs which are linked to ToDo list issues [here](https://lets-unify.ai/ivy/contributing.html#todo-list-issues).

**Review by HotzingTone — APPROVED** [review]
Conflicts resolved, passing review to @djl11 . Thanks!

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
