### PR TITLE
refactor matrix_transpose Issue #5952

### PR DESCRIPTION
**Pull request by AwkNinja**

### CODE REVIEW

**Comment by AwkNinja** [comment]
Close #5954

**Comment by AwkNinja** [comment]
I will fix the docstring errors I need to updated the docker image so I can run these tests locally and then submit.

**Comment by AwkNinja** [comment]
Hi @JerryGCDing I am done with the changes please review and let me know if I should update anything.

**Comment by JerryGCDing** [comment]
Hi @AwkNinja, thanks for contributing to Ivy 😃! Everything else on your PR looks perfect, can you link the PR to its corresponding issue in the `Development` section on the right? I'll then go ahead and merge it.

**Comment by AwkNinja** [comment]
Close #5952

**Pull request merged**
