### PR TITLE
add jax cummin function and tests

### LINKED ISSUE #4309: cummin

### PR DESCRIPTION
**Pull request by Dsantra92**
Close #4309

### CODE REVIEW

**Review by CatB1t — CHANGES_REQUESTED** [review]
Hello @Dsantra92 currently Ivy doesn't have the function `cummin`, you should implement this function compositionally using Ivy functions, read more here: https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html#temporary-compositions
Thanks!

**Comment by Dsantra92** [comment]
I should add the `ivy.cumsum` function in a different pr, right?

**Review by CatB1t — CHANGES_REQUESTED** [review]
Hello @Dsantra92, Yes, the extension to the functional API should be done in a seperate PR, you could refer here for more details: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#ivy-api-extensions , the function should be implemented for each backend. Although I'd recommend implementing it compositionally for JAX frontend, as it seems the function to be only specific to `torch` and `JAX`.

**Comment by Dsantra92** [comment]
I don't think `cummin` can/should be implemented by composition as it is cumulative functions are wrappers around super-optimized C++ functions. So complex compositions for such functions might not be optimal. I might just go for a different issue. Thanks for your time!

**Pull request closed without merging**
