### PR TITLE
reformat seed

### PR DESCRIPTION
**Pull request by MrZilinXiao**
https://github.com/unifyai/ivy/issues/1079

### CODE REVIEW

**Comment by MrZilinXiao** [comment]
@bicycleman15 Hi. Pop it up in case it gets drowned in your mainbox.

**Comment by bicycleman15** [comment]
Hey @MrZilinXiao, thanks for your contribution. There are some formatting errors, could you fix those ?
Rest LGTM 👍

**Comment by MrZilinXiao** [comment]
> Hey @MrZilinXiao, thanks for your contribution. There are some formatting errors, could you fix those ? Rest LGTM 👍

Formatting problem solved. Sorry for the inconvenience brought.

**Comment by bicycleman15** [comment]
I think there are some merge conflicts, could you please resolve those as well ? 🙂

**Comment by MrZilinXiao** [comment]
Resolved🤗

**Review by bicycleman15 — APPROVED** [review]

**Pull request merged**
