### PR TITLE
Refactor torch frontend functions and their tests

### PR DESCRIPTION
**Pull request by mohame54**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MuhammadSaeedBatikh** [comment]
Hi @mohame54, thanks for the PR.

I think this is too complex a task to be fixed in a single PR. You seem to have refactored six different pooling functions along with their tests; namely: `max_pool1d`, `lp_pool1d`, `lp_pool2d`, `avg_pool1d`, `avg_pool2d`, and `avg_pool3d`. I think it's best if you split and group them by category, one PR per category, maybe?
For example. a single PR for refactoring both `lp_pool1d` and `lp_pool2d`. This would make it easier to follow and review. Case in point, you have the following lines in `lp_pool1d`:
```
if stride is None:
     kernel_size = stride
```
It should be the reverse (`stride = kernel_size`). Simpler and granular PRs would make it easier to spot such mistakes.

**Comment by mohame54** [comment]
> Hi @mohame54, thanks for the PR.
> 
> I think this is too complex a task to be fixed in a single PR. You seem to have refactored six different pooling functions along with their tests; namely: `max_pool1d`, `lp_pool1d`, `lp_pool2d`, `avg_pool1d`, `avg_pool2d`, and `avg_pool3d`. I think it's best if you split and group them by category, one PR per category, maybe? For example. a single PR for refactoring both `lp_pool1d` and `lp_pool2d`. This would make it easier to follow and review. Case in point, you have the following lines in `lp_pool1d`:
> 
> ```
> if stride is None:
>      kernel_size = stride
> ```
> 
> It should be the reverse (`stride = kernel_size`). Simpler and granular PRs would make it easier to spot such mistakes.

Yeah I forgot about it thanks very much for notifying me .

**Comment by mohame54** [comment]
@MuhammadSaeedBatikh I spited the work as you suggested

**Comment by MuhammadSaeedBatikh** [comment]
Awesome! Could you post links to the newly created PRs here before I close this one? Thanks

**Comment by mohame54** [comment]
okay no problem.

**Pull request closed without merging**
