### PR TITLE
Reformat used_mem_on_dev

### LINKED ISSUE #3986: used_mem_on_dev

### PR DESCRIPTION
**Pull request by pdpino**
Fixes #3986

### CODE REVIEW

**Comment by pdpino** [comment]
add_reformatting_checklist_device

**Comment by sreegandh804** [comment]
Hey @pdpino , could you add the relevant backend functions if there are any? 🙂

**Comment by pdpino** [comment]
Hi @sreegandh804, thanks for reviewing this!

As far as I can tell, there are no backend functions relevant to this method. Maybe `clear_mem_on_dev()`? but I would say that should be addressed in a separated issue (as listed in #814)

Am I missing something?

**Comment by pdpino** [comment]
Related `used_mem_on_dev` comment:

`psutil.Process(...).memory_info().rss` is returned in bytes ([docs here](https://psutil.readthedocs.io/en/latest/index.html?highlight=memory_info#psutil.Process.memory_info)), not in GB (i.e. is missing a `/ 1e9`).
I could add this fix right away if that's ok, or open a different PR

**Comment by sreegandh804** [comment]
Hey @pdpino , The PR looks good to me!, I'll get it merged right away, Regarding the other issue I would suggest you make separate PR 🙂

**Pull request merged**
