### PR TITLE
 torch frontend asinh and asinh_ instance method

### PR DESCRIPTION
**Pull request by raghuveerbhat**

### CODE REVIEW

**Comment by raghuveerbhat** [comment]
close #5723

**Comment by raghuveerbhat** [comment]
Hi @Nightcrab , there are couple of lint issues which are unrelated to my changes. Hope I can ignore:)

With respect to failing test case for `asinh_` (and couple of other functions unrelated to my changes), I've found some change done in this commit [96f0cac](https://github.com/unifyai/ivy/commit/96f0cac30f6e881baad155a503cabda2b08d3e50) which might be causing the issue. The problematic code is [this line](https://github.com/jkeane508/ivy/blob/780b368536cc8013c4cb9b5d9a3b812b7825cb3d/ivy/functional/frontends/torch/creation_ops.py#L192). I think this function name aliasing might not be needed. I tested by removing that line in my local system, and the test cases for `test_creation_ops` and `test_tensor` pass.

Since I'm new contributor to the ivy project, I wanted to get your opinion on this. Also, if it is indeed a bug, should I raise new issue and fix it in this pull request or can I fix it without raising the new issue. Sorry for bothering you with many questions.

**Comment by Nightcrab** [comment]
Removing that line is fine, since the `tensor` function is provided in `Tensor.py` in a more correct manner. To keep repo structure consistent, I would move that alias out of `Tensor.py` and into `creation_ops.py` but that's outside of the scope of this PR.

**Review by Nightcrab — COMMENTED** [review]
merged since everything looks fine + tests pass

**Pull request merged**
