### PR TITLE
Implementation and testing of nanmean for the jax frontend

### PR DESCRIPTION
**Pull request by AhmedMahmoud03214**

### CODE REVIEW

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing! Please also add a test for this function in it's corresponding test file, you can find it in the `ivy_tests/test_ivy/test_frontends/test_jax/...` folder

Also, another side point, please change the name of this PR to be the name of the function you're working on and please mention your created issue in the description/comment! Thank you!

**Comment by AhmedMahmoud03214** [comment]
> AhmedMahmoud03214

According to The received PDF that explains the open-source coding challenge, a new PR #12094 has been opened
would you please review this PR #12094
thank you
Ahmed Ibrahim (AhmedMahmoud03214)

**Comment by AhmedMahmoud03214** [comment]
> Hey! Thanks for contributing! Please also add a test for this function in it's corresponding test file, you can find it in the `ivy_tests/test_ivy/test_frontends/test_jax/...` folder
> 
> Also, another side point, please change the name of this PR to be the name of the function you're working on and please mention your created issue in the description/comment! Thank you!

I have done the required changes.

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey there! It seems that the changes are not reflected in this PR and that the `nanstd` function has been removed instead, could you please double check and rearrange the PR if necessary? also, please don't push any changes related to the `.idea` folder! Thanks a lot!

**Pull request closed without merging**
