### PR TITLE
nextafter

### PR DESCRIPTION
**Pull request by shireenchand**
Added frontend and test for numpy nextafter

### CODE REVIEW

**Comment by shireenchand** [comment]
#13077

**Comment by aditya-hari** [comment]
Hey, unfortunately the tests are failing  

>RuntimeError: "nextafter_cpu" not implemented for 'Half' 
 
Just need to handle that

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by zhumakhan** [comment]
Hi, thanks for you PR, could you please remove unused imports. Rest seems good to me. There is error related to torch backend's nextafter with float16, but that should be a separate issue.

**Comment by shireenchand** [comment]
Hi @zhumakhan, I have removed the unused imports. Please do let me know if there are any other issues!

**Pull request merged**
