### PR TITLE
Implemented `floordiv` functionality for TensorFlow frontend.

### PR DESCRIPTION
**Pull request by edith007**
Close https://github.com/unifyai/ivy/issues/13866

### CODE REVIEW

**Comment by edith007** [comment]
@YushaArif99 Let me know if there are any suggestions or changes required ? 🙇🏻

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by edith007** [comment]
@YushaArif99 can you please take a look at this PR whenever time permits. 🙇🏻

**Pull request closed without merging**
