### PR TITLE
added adaptive_max_pool1d to frontend and ivy experimental

### LINKED ISSUE #22238: adaptive_max_pool1d
I will add adaptive_max_pool1d in Pytorch Frontend

### PR DESCRIPTION
**Pull request by sherySSH**
# PR Description 

## Related Issue 

Close #22238 

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by arshPratap** [comment]
Hi @sherySSH 
I have already pushed a PR for this here #22542

**Comment by arshPratap** [comment]
I would love to work on this issue

**Comment by bipinKrishnan** [comment]
@sherySSH Usually you shouldn't make frontend and ivy framework related changes in a single PR, those should be made as a separate PRs to keep things simple and clean.

As @arshPratap mentioned, he had already made a PR on adding this function to ivy last week. Since his PR was created first, he would be continuing the work on adding the function to ivy. You could then make use of this function in the torch frontend you are working on. Again, sorry for the trouble and thanks for the contribution @sherySSH 🙂 .

**Comment by sherySSH** [comment]
Ok noted. Since frontend was dependent on ivy implementation therefore I thought maybe both of these will go under 1 PR. Thanks for making it clear though, I will keep it under consideration next time.

As soon as, @arshPratap adds function in ivy then I will use it in frontend to complete my sub-task.

Cheers!

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @sherySSH 
Sorry for delays on our end. I will take over the PR and get the other PR mentioned above merged and then get this merged hopefully. The first one implement adaptive 1d max pool in ivy and this PR uses it to impment it in the frontend.
So could you remove the logic from ivy experimental layers as this will just conflict with the updates from the other PR.
Let me know if anything is unclear. Thnx a lot :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
