### PR TITLE
Added torch `hinge_embedding_loss`

### PR DESCRIPTION
**Pull request by ZiadAmerr**
Closes https://github.com/unifyai/ivy/issues/7673

### CODE REVIEW

**Comment by ZiadAmerr** [comment]
- #7673

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @ZiadAmerr! Your test implementation is currently failing for:
```
E       TypeError: hinge_embedding_loss() got multiple values for argument 'size_average'
```

Can you please resolve it and let me know once you are done for a second round of review? Thanks!

**Comment by ZiadAmerr** [comment]
Hey @kurshakuz, I never stumbled upon this error, and to make sure, I `git pull --force` the branch and ran the test, and got the AssertionError not the TypeError

**Comment by ZiadAmerr** [comment]
Hi @kurshakuz, the tests are passing now. :)

**Comment by ZiadAmerr** [comment]
You can also find the output of torch's native `hinge_embedding_loss` for various values in [this](https://docs.google.com/spreadsheets/d/1hPFTKzpglGtQkzsTRmwnHGKFPTMEk-UvJLdLMCFrK58/edit#gid=1630002989) sheet. This would be relevant to anyone reviewing the behavior of `HingeEmbeddingLoss` later on; as torch's docs don't thoroughly cover the behavior of it.

**Review by kurshakuz — COMMENTED** [review]
Hey Ziad, this is looking good to me, but can you just make a small nitpick fix? Thanks!

**Comment by ZiadAmerr** [comment]
Done :)

**Pull request closed without merging**
