### PR TITLE
Function arguments and docstrings for tanh #1627

### PR DESCRIPTION
**Pull request by ntoane**
- [ ] #1627

### CODE REVIEW

**Comment by sherry30** [comment]
Hi,

Do you want me to review your PR or are you still working on it?
If you're still working on it then let me know when you want me to review it by leaving a comment here 😄

**Comment by ntoane** [comment]
Hi Sherry,

Please review my PR, I am done working on it.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Some changes are required:
1. Make sure you don't make changes to any other other function beside tanh, currently your PR is detecting changes in a lot of other functions in elementise.py.
2.  You have to write examples of tanh under their appropriate files, for instance, example of passing input as ivy.array under ivy.tanh in ivy/functional/ivy/elementwise.py.

Some more changes are required like, creating a static method for tanh under container file. You can view all of these requirements [here](https://github.com/unifyai/ivy/blob/479e75ba53b8347db512445bf39f351b3f83609a/docs/partial_source/deep_dive/11_docstring_examples.rst). tan function has been used as an example in this document so you can use that as a reference to complete tanh function.

Let me know if you need help with anything or have any questions, I'd be happy to answer.

**Comment by ntoane** [comment]
Just to make sure that I understand where I should make changes, to do a Reformat elementwise Issue it was said that we make chamges both Ivy API (ivy/functional/ivy/elementwise.py) and Backend API (ivy/functional/backends/backend_name/elementwise.py). That means for each of the four backend names and Ivy API elementwise file, I locate the tanh function and make neccessary updates.
Please tell me if I misunderstood anything regarding this.

With the understanding above (asuming it's correct), for backend API I only made changes to function arguments and for Ivy API I updated with docstring and examples. I am using PyCharm, I don't know if it reformatted some functions if they appear to be changed on the PR.

Please let me know if I am following the right procedures before I continue because I already made use of docstring and  examples and I don't really understand how to make changes.
Please also advice how to go about this one: now that I made commits to my forked repo and linked with PR, how do I revert them back if I want to start from scratch.

Please bear with me, it is my first time to contribute.

**Comment by sherry30** [comment]
No problem, It's completely fine.

Yup, your understanding is pretty much correct. In the backend functions you just have to fix the functional arguments and add any missing type hints and for ivy API, you have to add docstring examples. In addition to that you also have to add docstring example for container instance method in ivy/container/elementwise.py under tanh function ([here](https://github.com/unifyai/ivy/blob/189aa436651d7560b836ccfa47a06f4cd63ebfd2/ivy/container/elementwise.py#L1384) is an example of tan function) and also add docstring example for array instance method in ivy/array/elementwise.py under tanh (tan [example](https://github.com/unifyai/ivy/blob/189aa436651d7560b836ccfa47a06f4cd63ebfd2/ivy/array/elementwise.py#L285)). In ivy/container/elementwise.py, `static_tanh` function hasn't been implemented so you'll also have to implement that similar to how static_tan has been implemented [here](https://github.com/unifyai/ivy/blob/189aa436651d7560b836ccfa47a06f4cd63ebfd2/ivy/container/elementwise.py#L1338)
This task was changed a bit recently that's why there are some additional things to do.

If you have added any docstring examples in ivy API then for some reason they aren't showing up on your PR, maybe you can try to make another commit ensuring that ivy/functional/ivy/elementwise.py is checked on the left hand panel while you're making a commit on pycharm. and yes, it seems like pycharm has reformatted your file that's why its showing changes to other functions. 

As for reverting a commit you can run these commands:
`git checkout tanh_branch`
`git revert HEAD^`
`git push origin tanh_branch -f`

this will revert your latest commit on your `tanh_branch` branch and also on your PR.

Let me know if you have any other question,
Thanks

**Comment by ntoane** [comment]
Hi,
I am done making the requested changes, please review them.
Please note that after creating static_tanh method I had to modify the return statement of tanh method in the Container, I am not sure if this was necessary.
Also, advice on how to run tests, e.g. to test static_tanh method that it works as expected.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

modifying the return statement of tanh in container looks good, just a few more chanegs are required:

1. your `ivy/functional/backends/torch/elementwise.py` file seems to be reformatted and its detecting changes in a lot of other functions, can you kindly revert those changes.
2. Whenever you use ivy.container as an input and you're adding array a and b in it, can you put b on the next line and use `\` separator. This just makes the code more readable.
3. Currently your docstring test for tanh seems to be failing, can you look into that and try to fix it. You can ask for help if you need any.

As for running the test, You can go to `ivy_test/test_ivy/test_functional/test_core/test_elementwise.py` and from there you can run the `test_tanh` method to see if the implementation is correct. 

If you want to run docstring test, you can go to `ivy_tests/test_docstrings.py` and run the `test_docstrings` method from there

Thanks!

**Comment by ntoane** [comment]
I have made the requested changes. However, it seems I still have issues with test-docstrings. I run the docstring test as you advised and it passed on my machine.
Please review and assist with failing the docstring test.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

So you're local test were passing because your branch wasn't up to date with master so `assert_success` line was missing in your test_docstring. The CI is updated with master that's why it was failing. I've updated your branch so it should be failing locally now as well.
It seems to be failing because your output is a bit off, I tried these examples separately in a test file and I'm getting the same answer suggested by the CI tests and different from your examples just a bit (difference of decimals like I'm getting `1.` instead of `0.999`). Maybe you can run these examples again in a separate test file and see what the outputs are and replace yours if they're different.

One more thing, you can remove `Instance Method Examples` from `ivy/functional/ivy/elementwise.py`, since you've already added these examples in array and container folder.

Thanks.

**Review by sherry30 — APPROVED** [review]
Looks perfect, Thanks for the contribution 😃 

Maybe there is something wrong with the environment. You can try to create a test.py file under the main ivy folder and test things out there, `import ivy` should work in that file.

**Comment by ntoane** [comment]
Thank you so much. It was a great experience working on this task and I hope to contribute further to this project.

**Pull request merged**
