### PR TITLE
Choose

### PR DESCRIPTION
**Pull request by simonebonato**
Close https://github.com/unifyai/ivy/issues/17641

### CODE REVIEW

**Comment by simonebonato** [comment]
Hi, I have created the function and I hope it is correct. Now I would like to write the test for it but I don't know how, any help appreciated.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by simonebonato** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

I think I have just done it, confirm me if you can :)

**Comment by simonebonato** [comment]
I need help with testing, I have no idea how to create them and also run the existing ones locally...

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @simonebonato 

The implementation looks good overall. Could you kindly also add a test for this in the corresponding frontend test file. Thanks 🙂

**Comment by simonebonato** [comment]
@YushaArif99 I would love to, I am having some troubles with the tests.
I don't understand why I get this error when I try to run the tests in Pycharm, even though I didn't do any changes to the tests.

image

**Pull request closed without merging**
