### PR TITLE
Fixes sequence of wrapper decorators for ivy functions

### PR DESCRIPTION
**Pull request by usama-baloch**
Rearranged the decorators of Ivy functions according to the given ground truth (list of decorators given in func_wrapper file in Ivy)

### CODE REVIEW

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hey @usama-baloch, thanks for making the changes, if you see the ground truth sequence in [`func_wrappers.py`](https://github.com/unifyai/ivy/blob/960ee36810ce9ea94bd0d3341fc3867dca0df726/ivy/func_wrapper.py#L14) and the way they're wrapped in the [`_wrap_function`](https://github.com/unifyai/ivy/blob/960ee36810ce9ea94bd0d3341fc3867dca0df726/ivy/func_wrapper.py#L733), the first wrapper in the ground truth sequence is actually the innermost wrapper and the last one is the outermost wrapper, could you please update the sequence of decorators to take that into account (I suppose you'll just have to reverse the sequence of decorators you've arranged currently)? Thanks 🙂

**Comment by usama-baloch** [comment]
Hey @VedPatwardhan, Sorry for the above mess that I created yesterday 😅, I have made amends and it is good to go now, it works just fine :)

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Sounds great, thanks for making the changes @usama-baloch! Could you please also go through the functions in the experimental API in a similar manner? Thanks 🙂

**Comment by usama-baloch** [comment]
I have updated the files of the experimental directory. Now you can check it out

**Review by VedPatwardhan — APPROVED** [review]
lgtm! Feel free to merge the PR, thanks @usama-baloch @YushaArif99 🙂

**Pull request merged**
