### PR TITLE
Add Pointwise ops to PyTorch Frontend atanh #3058

### PR DESCRIPTION
**Pull request by Emperor-WS**
Hello,
The code is ready to be merged I guess. 
if there is anything else you want me to add or edit tell me.
Best regards.

### CODE REVIEW

**Comment by Emperor-WS** [comment]
Greetings @sherry30 ,
I checked the error files and it seems that it doesnt have anything to do with my code, if it does kindly let me know.
Thanks in advance.

**Comment by Emperor-WS** [comment]
Hello again @sherry30 , the branch had some conflicts with the base branch and i resolved them if there is anything i need to edit  kindly let me know.
Thanks in advance.

**Comment by Emperor-WS** [comment]
@sherry30 Solved some more conflicts and i checked the error logs again and everything seems to be working just fine i think the code is ready to be merged.
Thanks in advance.

**Comment by Emperor-WS** [comment]
@sherry30 is everything good to go?

**Review by sherry30 — APPROVED** [review]
Looks good 👍 

Thanks for the contribution

**Pull request merged**
