### PR TITLE
Add corrcoef to Numpy frontend Statistics

### PR DESCRIPTION
**Pull request by Zain-Bajwa**
corrcoef #12747

### CODE REVIEW

**Comment by ZoeCD** [comment]
> corrcoef() needs two arrays with the same dimension and the maximum dimensions are 2. I am unable to find a parameter that provides two arrays with the same dimension. Following error occur due this issue:

What you can do is to use the Ivy helper `get_shape()` and then use that in the parameter `shape` of `dtype_and_values`

> The ivy.corrcoef() does not handle the other data types except float.
Is this happening with all the backends or just for numpy?

**Comment by Zain-Bajwa** [comment]
> What you can do is to use the Ivy helper `get_shape()` and then use that in the parameter `shape` of `dtype_and_values`

I added the shape parameter below. But still, two arrays of the same shape are not being generated.
```
@handle_frontend_test(
    fn_tree="numpy.corrcoef",
    dtype=helpers.get_dtypes("float", full=False, none=True),
    dtype_and_x=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("float"),
        num_arrays=2,
        shared_dtype=True,
        shape=helpers.get_shape(
            min_num_dims=1,
            max_num_dims=2,
        )
    ),
    test_with_out=st.just(False),
    rowvar=st.booleans(),
)
```
**Error:**
```
test_averages_and_variances.py:386: in test_numpy_corrcoef
    np_frontend_helpers.test_frontend_function(
../helpers.py:166: in test_frontend_function
    helpers.test_frontend_function(*args, **kwargs)
../../../helpers/function_testing.py:836: in test_frontend_function
    value_test(
../../../helpers/assertions.py:122: in value_test
    assert_all_close(
../../../helpers/assertions.py:53: in assert_all_close
    assert np.allclose(
<__array_function__ internals>:200: in allclose
    ???
/home/zain/Virtual_environmets/ivy_dev/lib/python3.8/site-packages/numpy/core/numeric.py:2270: in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
<__array_function__ internals>:200: in isclose
    ???
/home/zain/Virtual_environmets/ivy_dev/lib/python3.8/site-packages/numpy/core/numeric.py:2380: in isclose
    return within_tol(x, y, atol, rtol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., ...   [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])
y = array([[0., 0.],
       [0., 0.]]), atol = 1e-06, rtol = 1e-05

    def within_tol(x, y, atol, rtol):
        with errstate(invalid='ignore'), _no_nep50_warning():
>           return less_equal(abs(x-y), atol + rtol * abs(y))
E           ValueError: operands could not be broadcast together with shapes (8,8) (2,2) 
E           Falsifying example: test_numpy_corrcoef(
E               dtype=['float64'],
E               dtype_and_x=(['float64', 'float64'], [array([[-1.],
E                        [-1.],
E                        [-1.],
E                        [-1.]]), array([[-1.],
E                        [-1.],
E                        [-1.],
E                        [-1.]])]),
E               rowvar=False,
E               fn_tree='ivy.functional.frontends.numpy.corrcoef',
E               test_flags=FrontendFunctionTestFlags(
E                   num_positional_args=3,
E                   with_out=False,
E                   inplace=False,
E                   as_variable=[False],
E                   native_arrays=[False],
E               ),
E               frontend='numpy',
E               on_device='cpu',
E           )
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2BgZGBmZAADKAWmacBmZgAABbEAGQ==') as a decorator on your test case

/home/zain/Virtual_environmets/ivy_dev/lib/python3.8/site-packages/numpy/core/numeric.py:2361: ValueError
```
> Is this happening with all the backends or just for numpy?

I checked all other backends and it is only happening for `Numpy`

**Comment by ZoeCD** [comment]
> I added the shape parameter below. But still, two arrays of the same shape are not being generated.
Hmmm, try with:

```
        min_num_dims=2,
        max_num_dims=2,
        min_dim_size=3,
        max_dim_size=3,
```

**Comment by Zain-Bajwa** [comment]
> 
> Hmmm, try with:
> 
> ```
>         min_num_dims=2,
>         max_num_dims=2,
>         min_dim_size=3,
>         max_dim_size=3,
> ```
I don't know how but it is working now and all tests are passed related to my issue.
And I also tried your suggestions, It is also working fine.
```
@handle_frontend_test(
    fn_tree="numpy.corrcoef",
    dtype=helpers.get_dtypes("float", full=False, none=True),
    dtype_and_x=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("float"),
        num_arrays=2,
        min_num_dims=1,
        max_num_dims=2,
        shared_dtype=True,
    ),
    test_with_out=st.just(False),
    rowvar=st.booleans(),
)
```

**Comment by Zain-Bajwa** [comment]
> > Hmmm, try with:
> > ```
> >         min_num_dims=2,
> >         max_num_dims=2,
> >         min_dim_size=3,
> >         max_dim_size=3,
> > ```
> 
> I don't know how but it is working now and all tests are passed related to my issue. And I also tried your suggestions, It is also working fine.
> 
> ```
> @handle_frontend_test(
>     fn_tree="numpy.corrcoef",
>     dtype=helpers.get_dtypes("float", full=False, none=True),
>     dtype_and_x=helpers.dtype_and_values(
>         available_dtypes=helpers.get_dtypes("float"),
>         num_arrays=2,
>         min_num_dims=1,
>         max_num_dims=2,
>         shared_dtype=True,
>     ),
>     test_with_out=st.just(False),
>     rowvar=st.booleans(),
> )
> ```

@ZoeCD please look into this issue.
What should I do next?

**Comment by ZoeCD** [comment]
Hello, sorry for the late response. There is a new error popping up, could you please check it? `tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat`

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
