### PR TITLE
Add scatter_nd paddle frontend manipulation

### LINKED ISSUE #19234: scatter_nd

### PR DESCRIPTION
**Pull request by NripeshN**
Close #19234

### CODE REVIEW

**Comment by NripeshN** [comment]
add_frontend_checklist

**Comment by MuhammadSaeedBatikh** [comment]
Hi @NripeshN, thanks for the PR.
I don't think this ivy `scatter_nd` implementation matches `paddle.scatter_nd`. 
- the function signature needs to be changed to `scatter_nd(index, updates, shape, name=None)`. [See here.](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/scatter_nd_en.html)

- Make sure that `test_paddle_scatter_nd` includes appropriate tests for `index`, `updates`, and `shape`. You may take a look at `test_scatter_nd` in `../test_ivy/test_functional/test_core/test_general.py`
- Please make sure that all tests pass locally.

**Comment by NripeshN** [comment]
> Hi @NripeshN, thanks for the PR. I don't think this ivy `scatter_nd` implementation matches `paddle.scatter_nd`.
> 
> * the function signature needs to be changed to `scatter_nd(index, updates, shape, name=None)`. [See here.](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/scatter_nd_en.html)
> * Make sure that `test_paddle_scatter_nd` includes appropriate tests for `index`, `updates`, and `shape`. You may take a look at `test_scatter_nd` in `../test_ivy/test_functional/test_core/test_general.py`
> * Please make sure that all tests pass locally.

Hi @MuhammadSaeedBatikh,
I have changed the test and function.
I am getting the following error.
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_manipulation.py::test_scatter_nd[cpu-ivy.functional.backends.numpy-False-False] - TypeError: i is not a valid data type that can be generated, only integers, floats and booleans are allowed.

**Comment by MuhammadSaeedBatikh** [comment]
Hi @NripeshN, I see you're still fixing failed tests. Please let me know when it's ready for review.

**Comment by NripeshN** [comment]
Hi @MuhammadSaeedBatikh, The error i am getting is not related to this PR.

**Comment by MuhammadSaeedBatikh** [comment]
Hi @NripeshN, some of the exceptions seem to be related to the issue:
```
ValueError: (InvalidArgument) Updates has wrong shape. The shape of Updates and Input(Updates) should be same, but received the shape of Updates is 2, the shape of Input(Updates) is 1.
[Hint: Expected r_updates_dims.size() == updates_dims_size, but received r_updates_dims.size():2 != updates_dims_size:1.] (at /paddle/paddle/phi/infermeta/ternary.cc:1147)
           
E           Falsifying example: test_paddle_scatter_nd(
E               x=(['int32', 'int32', 'int32'],
E                array([[0]], dtype=int32),
E                array([[0]]),
E                array([0], dtype=int32)),
E               fn_tree='ivy.functional.frontends.paddle.scatter_nd',
E               test_flags=FrontendFunctionTestFlags(
E                   num_positional_args=0,
E                   with_out=False,
E                   inplace=False,
E                   as_variable=[False],
E                   native_arrays=[False],
E                   generate_frontend_arrays=False,
E               ),
E               backend_fw='paddle',
E               on_device='cpu',
E               frontend='paddle',
E           )
```

**Pull request closed without merging**
