### PR TITLE
Added l1_l2 frontend

### PR DESCRIPTION
**Pull request by ahlag**
Signed-off-by: Chang Yong Lik <theeahlag@gmail.com>

## Description
- Added l1_l2

Resolves https://github.com/unifyai/ivy/issues/2348

## How was this patch tested?
TBD

## Does this PR introduce any user-facing changes?
Allows users to run l1_l2 from Tensorflow

### CODE REVIEW

**Comment by ahlag** [comment]
@abdrahmandiab 
Hi, would love to have some feedbacks for L1L2 regularizers.

**Comment by juliagsy** [comment]
Hey there! Thanks a lot for this feature! We'll be looking into feature extensions after our next release soon!

**Comment by ahlag** [comment]
@juliagsy 
Hey thank you for your reply.
Should we keep this PR in WIP

**Comment by ahlag** [comment]
Discussed in another separate discussion. Refer: https://github.com/unifyai/ivy/discussions/2051#discussioncomment-3280274

**Comment by abdrahmandiab** [comment]
Hi @ahlag, 
Really sorry for the inconvenience and confusion! 
The issue solved in this PR is indeed part of the current applicant task list, and therefore it should not have the "Next Release" label. However, it appears this function will require some special attention since it doesn't have a very generalizable return type across backends, therefore it is tricky to handle the frontend implementation for. Definitely a mistake on our part, and we will update the description for it soon.

For the time being and to speed up your application, could you attempt to solve another issue from the ToDo labeled ones? 😅

Apologies for the confusion again, and thank you so much!
Please let me know if you have any questions.

**Comment by ahlag** [comment]
Hi @abdrahmandiab,

Thank you so much for your reply! I will hold up the test for now and focus on other tasks. Really thank you!

**Pull request closed without merging**
