### PR TITLE
Extend the access to Unify API key to all of our users

### PR DESCRIPTION
**Pull request by kurshakuz**

### CODE REVIEW

**Review by guillesanbri — APPROVED** [review]
lgtm!

**Comment by Sai-Suraj-27** [comment]
Hey @kurshakuz, @guillesanbri. I think similar changes need to be done [here](https://unify.ai/docs/ivy/overview/get_started.html#ivy-s-tracer-and-transpiler) also.
https://github.com/unifyai/ivy/blob/a395c0a565f4f02a81393e67f715333dc63d5f1c/docs/overview/get_started.rst?plain=1#L62-L64

**Comment by guillesanbri** [comment]
> Hey @kurshakuz, @guillesanbri. I think similar changes need to be done [here](https://unify.ai/docs/ivy/overview/get_started.html#ivy-s-tracer-and-transpiler) also.
> 
> https://github.com/unifyai/ivy/blob/a395c0a565f4f02a81393e67f715333dc63d5f1c/docs/overview/get_started.rst?plain=1#L62-L64

Indeed, very good catch, thanks!

**Comment by guillesanbri** [comment]
fixed in https://github.com/unifyai/ivy/pull/27749

**Pull request merged**
