### PR TITLE
Add tie_in to jax frontend api with test

### LINKED ISSUE #20991: tie_in

### PR DESCRIPTION
**Pull request by Sjsingh101**
closes #20991

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @Sjsingh101 ! Can you sync this branch with master and resolve the merge-conflict? This should also fix the failing tests on the CI :)

**Comment by Sjsingh101** [comment]
Hi @hello-fri-end, I have synced the branch. All the failing testcases are unrelated to `tie_in`.

**Review by hello-fri-end — APPROVED** [review]
LGTM! :rocket:

**Pull request merged**
