### PR TITLE
added examples to negative func

### PR DESCRIPTION
**Pull request by sondertg**

### CODE REVIEW

**Comment by sondertg** [comment]
add_reformatting_checklist_elementwise

**Comment by sondertg** [comment]
close #7245

**Comment by sondertg** [comment]
Failed tests:
1 --- 1 failed
`from run-array-api-tests (tensorflow, linalg) `
```
test_linalg.py::test_matrix_rank`
```
2 --- 1 failed
`from run-array-api-tests (torch, creation_functions) `
```
test_creation_functions.py::test_linspace`
```
3 --- 1 failed
`from run-nightly-tests(tensorflow, elementwise) `
```
test_elementwise.py::test_trunc_divide
```
4 --- 5 failed
`from run-nightly-tests(jax, elementwise) `
```
test_elementwise.py::test_cosh 
test_elementwise.py::test_log
test_elementwise.py::test_remainder
test_elementwise.py::test_reciprocal
test_elementwise.py::test_trunc_divide
```

5 --- 2 failed
`from run-nightly-tests(torch, elementwise)`
```
test_elementwise.py::test_floor_divide
test_elementwise.py::test_remainder
```
6 --- 1 failed
`from run-nightly-tests(numpy, elementwise)`
```
test_elementwise.py::test_trunc_divide
```
7th failure comes from format checking, related to to variable named as 'l' in lambda func used at 
ivy_tests/test_ivy/test_functional/test_core/test_general.py:654:29: and E741 error code. I can fix this easily.

I searched all logs for 'negative', 'neg' and '__neg__' , couldn't find any failure of tests related to elementwise negative

For docstrings, elements of arrays return multiple decimals (more than input elements have)  when input elements are float. I think this is because they are close to transcendental numbers. I am open for suggestion to solve it if docstring tests fails.

**Comment by sondertg** [comment]
> Failed tests: 1 --- 1 failed `from run-array-api-tests (tensorflow, linalg) `
> 
> ```
> test_linalg.py::test_matrix_rank`
> ```
> 
> 2 --- 1 failed `from run-array-api-tests (torch, creation_functions) `
> 
> ```
> test_creation_functions.py::test_linspace`
> ```
> 
> 3 --- 1 failed `from run-nightly-tests(tensorflow, elementwise) `
> 
> ```
> test_elementwise.py::test_trunc_divide
> ```
> 
> 4 --- 5 failed `from run-nightly-tests(jax, elementwise) `
> 
> ```
> test_elementwise.py::test_cosh 
> test_elementwise.py::test_log
> test_elementwise.py::test_remainder
> test_elementwise.py::test_reciprocal
> test_elementwise.py::test_trunc_divide
> ```
> 
> 5 --- 2 failed `from run-nightly-tests(torch, elementwise)`
> 
> ```
> test_elementwise.py::test_floor_divide
> test_elementwise.py::test_remainder
> ```
> 
> 6 --- 1 failed `from run-nightly-tests(numpy, elementwise)`
> 
> ```
> test_elementwise.py::test_trunc_divide
> ```
> 
> 7th failure comes from format checking, related to to variable named as 'l' in lambda func used at ivy_tests/test_ivy/test_functional/test_core/test_general.py:654:29: and E741 error code. I can fix this easily.
> 
> I searched all logs for 'negative', 'neg' and '**neg**' , couldn't find any failure of tests related to elementwise negative
> 
> For docstrings, elements of arrays return multiple decimals (more than input elements have) when input elements are float. I think this is because they are close to transcendental numbers. I am open for suggestion to solve it if docstring tests fails.

I fixed issue related to formatting check and new failed tests occured due to merging behind commits but none related to backend elementwise negative.
Failed Tests:
from array-api-tests(tensorflow, linalg) > test_linalg.py::test_matrix_rank

from nightly-tests(tensorflow, general): 25 failed and no 'negative' or '__neg__'' mentioned in logs.

from nightly-tests(tensorflow, elementwise): test_elementwise.py::test_trunc_divide failed (1 failed).

from nightly-tests(jax, general): 26 failed and  no 'negative' or '__neg__'' mentioned in logs.

from nightly-tests(jax, elementwise): 7 failed and no 'negative' or '__neg__'' mentioned in logs.

from nightly-tests(torch, general): 25 failed and no 'negative' or '__neg__'' mentioned in logs.

from nightly-tests(torch, elementwise): 2 failed and no 'negative' or '__neg__'' mentioned in logs.

from array-api-tests(torch, creation_functions): test_creation_functions.py::test_linspace (1 failed).

from nightly-tests(numpy, general): 25 failed and no 'negative' or '__neg__'' mentioned in logs.

from nightly-tests(numpy, elementwise): test_elementwise.py::test_trunc_divide (1 failed).

None of those tests related to negative function. 

Nine tests skipped which six of them testing frontend. Two of them seems related to docs and if any problem there I can try to fix. I am open to guidance. Thanks

**Comment by ukj02** [comment]
LGTM!

**Pull request merged**
