### PR TITLE
BlackmanWindow #19480

### PR DESCRIPTION
**Pull request by hakymulla**
https://github.com/unifyai/ivy/issues/19480

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by hakymulla** [comment]
can someone please review my PR

**Comment by jieunboy0516** [comment]
ivy-gardener

**Comment by jieunboy0516** [comment]
Hi @hakymulla, thanks a lot for your PR, and I am sorry for the late response. 

Could you please resolve the issue of `TypeError: test_function() missing 1 required keyword-only argument: 'backend_to_test'`  for the test `test_blackman_window` ? Furthermore, please follow the pre-commit guide in [https://unify.ai/docs/ivy/overview/contributing/setting_up.html](this doc) so that the linter check passes!

thanks again for your contribution to ivy!

**Comment by hakymulla** [comment]
> Hi @hakymulla, thanks a lot for your PR, and I am sorry for the late response.
> 
> Could you please resolve the issue of `TypeError: test_function() missing 1 required keyword-only argument: 'backend_to_test'` for the test `test_blackman_window` ? Furthermore, please follow the pre-commit guide in https://unify.ai/docs/ivy/overview/contributing/setting_up.html so that the linter check passes!
> 
> thanks again for your contribution to ivy!

Done

**Comment by jieunboy0516** [comment]
thanks @hakymulla

**Pull request merged**
