### PR TITLE
Add quantile function

### PR DESCRIPTION
**Pull request by arananDev**
testing order statistics still outputs the following error

`@handle_frontend_test(
     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arana\Documents\venvs\ivy_dev\Lib\site-packages\ivy_tests\test_ivy\helpers\testing_helpers.py", line 383, in test_wrapper
    callable_fn, fn_name, fn_mod = _import_fn(fn_tree)
                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arana\Documents\venvs\ivy_dev\Lib\site-packages\ivy_tests\test_ivy\helpers\testing_helpers.py", line 152, in _import_fn
    callable_fn = mod.__dict__[fn_name]
                  ~~~~~~~~~~~~^^^^^^^^^

    @handle_frontend_test(
     ^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\arana\Documents\venvs\ivy_dev\Lib\site-packages\ivy_tests\test_ivy\helpers\testing_helpers.py", line 383, in test_wrapper
    callable_fn, fn_name, fn_mod = _import_fn(fn_tree)
                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arana\Documents\venvs\ivy_dev\Lib\site-packages\ivy_tests\test_ivy\helpers\testing_helpers.py", line 152, in _import_fn
    callable_fn = mod.__dict__[fn_name]
                  ~~~~~~~~~~~~^^^^^^^^^`

### CODE REVIEW

**Review by CatB1t — COMMENTED** [review]
Hello @arananDev, can you please implement the test function and push it? I'll be happy to have a look (: Thanks!

**Comment by arananDev** [comment]
@CatB1t Sorry! Forgot to add it, will do it now

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
