### PR TITLE
Fixed(Docstring) in Compiler, Added invert_permutarion to tensorflow frontend math.py

### LINKED ISSUE #22939: invert_permutation

### PR DESCRIPTION
**Pull request by lyon98-dbios**
Fixed Docstring in compiler for unify And added invert_permutation to the math function

The docstring for the unify function in the compiler was on the Todo, I didn't quite see any issue opened up for it but decided to handle it either way

added invert_permutation function at ivy/functional/frontends/tensorflow/math.py

## Related Issue

Close #22939

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials:

https://twitter.com/DanielBisina.

@Mr-Niraj-Kulkarni

### CODE REVIEW

**Comment by lyon98-dbios** [comment]
@Mr-Niraj-Kulkarni

**Comment by Mr-Niraj-Kulkarni** [comment]
Hey, your tests are failing and there are lint error. Can you please fix both please. Thanks

**Comment by Mr-Niraj-Kulkarni** [comment]
Please don't add the doc string fix for the compiler file in this PR please remove it.

**Comment by lyon98-dbios** [comment]
Alright sir. Will get them fixedSent from my iPhoneOn 14 Sep 2023, at 09:47, Niraj Rajendra Kulkarni ***@***.***> wrote:﻿
Please don't add the doc string fix for the compiler file in this PR please remove it.

**Comment by losmi247** [comment]
Why are you taking an already open issue that already has a PR that fixes it (mine)

**Pull request closed without merging**
