### PR TITLE
Added average numpy frontend

### PR DESCRIPTION
**Pull request by shireenchand**
Added to averages_and_variances.py and added test to test_averages_and_variances.py

This is the issue number https://github.com/unifyai/ivy/issues/6739

### CODE REVIEW

**Comment by shireenchand** [comment]
@MarShaikh can you please check this one? Thankss!

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Everything else looks good, but could you remove the `.DS_Store` files? Thanks, after that it will be ready to merge!

**Comment by shireenchand** [comment]
Hi @MarShaikh, I have removed the .DS_Store files. Please do check and let me know.
Thanks!

**Comment by shireenchand** [comment]
Hi @MarShaikh can you check the changes made.
Thanks!!

**Comment by shireenchand** [comment]
@MarShaikh can you review the PR please. Thanks!

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi, thanks for removing the files. Could you also fix the merge conflicts? I'll give this PR high priority so as soon as you're done, request a review and I'll merge it. Thanks! 🙂

**Comment by shireenchand** [comment]
Hi @MarShaikh, I have resolved the merge conflicts as well. Can you check and let me know if there are any other changes to be done.
Thanks!!

**Comment by shireenchand** [comment]
@MarShaikh can you please review the PR
Thanks!

**Comment by shireenchand** [comment]
@MarShaikh can you please review the PR. All the changes have been made.

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi, sorry, I took a look at your current changes again in the `test_averages_and_variances.py` and noticed that you replaced the `handle_frontend_test` decorator with `handle_cmd_line_args` decorator and `given` decorator. This was how we initially wrote our tests, but have since changed so could you revert the changes back to using `handle_frontend_test` decorator? Thanks!

**Pull request closed without merging**
