### PR TITLE
feature: add baddbmm_ to torch

### LINKED ISSUE #20970: baddbmm_
Related to: https://github.com/unifyai/ivy/issues/3612

### PR DESCRIPTION
**Pull request by RawaaRajab**
close #20970

@Ishticode can you review it please? I unintentionally closed the other PR.
Thank you

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by paulaehab** [comment]
Hi @RawaaRajab Nice work 😄 solve conflicts and I will merge it for you.

**Comment by RawaaRajab** [comment]
@paulaehab thank you for your review, I solved the conflicts and used pre-commit formatting.

**Comment by paulaehab** [comment]
Hey @RawaaRajab  there are 2 edits in 2 different files (reduction_ops in torch ) please remove this edit to accept the PR

**Comment by RawaaRajab** [comment]
hey @paulaehab removed the edits, is there anything else to do ?

**Comment by paulaehab** [comment]
> 

nice work, thanks for contributing 😄 I will merge it.

**Pull request merged**
