### PR TITLE
feat: Added sqrtm Linear Algebra function for TensorFlow frontend. Close #26526.

### LINKED ISSUE #26526: sqrtm
Add Linear Algebra functions for TensorFlow frontend

### PR DESCRIPTION
**Pull request by Juligee**
# PR Description
Adding the sqrtm Linear Algebra function for TensorFlow frontend to Ivy file

## Related Issue
New issue number #26526 was created for sqrtm function from issues list - #1546

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Juligee** [comment]
Dear @nathzi1505, 

Please, I would like to have a link for testing frontends in Ivy.

Thank you.

**Comment by Sam-Armstrong** [comment]
@Juligee this is the doc for testing frontends btw https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html

**Comment by Juligee** [comment]
Good day @Sam-Armstrong,

I am very thankful for the link for Ivy testing. I am so interested to know how to test with the different frontends and make the expected outcomes passing. I will learn more from the ivy document. Please, if I have problems with test set-up, I will tag you for some assistance.

I see that this PR is closed, could l move on to the next issues, assuming this PR is merged?

Thank you.

**Comment by Juligee** [comment]
> @Juligee looks like this issue is already being worked on #25864, so I'm going to close this PR. Feel free to open a new issue on any todo list task which isn't currently being worked on :)

Good day @Sam-Armstrong, 

Okay, as at the time I started working on the issue it was opened without a check mark. Might be someone completed it before me. Okay, I will start a new issue. 

Thank you.

**Pull request closed without merging**
