### PR TITLE
added numpy.extract implementation

### LINKED ISSUE #10661: extract

### PR DESCRIPTION
**Pull request by Nuno-Ferreira**
closes #10661

### CODE REVIEW

**Comment by Nuno-Ferreira** [comment]
Hi @V-G-spec! 
Whenever I run this locally I keep getting an assertion error which I don't really know how to solve could you give me some help or advice?
Here is the error:
`FAILED ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py::test_numpy_extract[cpu-ivy.functional.backends.numpy-False-False] - AssertionError: the ground truth framework numpy returned a float16 datatype while the backend numpy returned a float64 datatype
FAILED ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py::test_numpy_extract[cpu-ivy.functional.backends.jax-False-False] - AssertionError: the ground truth framework numpy returned a float16 datatype while the backend jax returned a float64 datatype
FAILED ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py::test_numpy_extract[cpu-ivy.functional.backends.tensorflow-False-False] - AssertionError: the ground truth framework numpy returned a float16 datatype while the backend tensorflow returned a float64 datatype
FAILED ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py::test_numpy_extract[cpu-ivy.functional.backends.torch-False-False] - AssertionError: the ground truth framework numpy returned a float16 datatype while the backend torch returned a float64 datatype`

**Comment by V-G-spec** [comment]
Hey @Nuno-Ferreira, thanks for your contribution and sorry about the delay in response. Can you quickly go through the failing tests? Just keep in mind that sometimes tests fail because of other files to. So ensure that first before spending time on fixes
Thanks!

**Comment by Nuno-Ferreira** [comment]
Hey @V-G-spec , I have had a look and I don’t think it is another file, since when I test locally I only test my function `test_searching.py::test_numpy_extract` and it's still with the same error it just changes the types it gets like the numpy frontend gets complex128 and the backend gets float32.

Is there anything else that you could think could be the problem?

Thank you for the help!

**Comment by V-G-spec** [comment]
I believe the problem might be with the test function. You should use an exhaustive set of inputs for it. Check out the deep dive for more information on this. It may be that due to sampling, sometimes your function fails for one reason, sometimes for some other and as I can see right now, it shows all tests are passing. 
Best to have a robust test function.
Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Nuno-Ferreira** [comment]
Ok I will have a look at it. Thank you!!

**Comment by V-G-spec** [comment]
👍🏼

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
