### PR TITLE
Added new_zeros instance method to PyTorch frontend #5733

### PR DESCRIPTION
**Pull request by kivimike**
I have implemented the method but I'm currently struggling with writing a working test. I've used the new_ones method as a reference and found that the test for that method was not working properly (it was generating a tensor filled with floats). I've figered out how to set a specific value (in my case its zero), how to create a strategy that uses shapes from a given range, but I don't know understand how create identical shapes for both: the test tensor and for the method input. I've tried to use st.shared, but in this case it still doesn't really generate the same shape for both cases.

### CODE REVIEW

**Comment by ogbanugot** [comment]
Hey @kivimike great work so far, can you kindly resolve the conflicts? Also, I'll link this to the corresponding issue, but in the future, you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)”. Once this is done, I'll take a closer look at the issue you are having and see if I can help. Thanks!

**Comment by ogbanugot** [comment]
Close #5733

**Comment by kivimike** [comment]
> Hey @kivimike great work so far, can you kindly resolve the conflicts? Also, I'll link this to the corresponding issue, but in the future, you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues). Once this is done, I'll take a closer look at the issue you are having and see if I can help. Thanks!

Could you review my code? I think I resolved the conflicts.

**Comment by kivimike** [comment]
Close - [] #5799

**Comment by ogbanugot** [comment]
Hey @kivimike, the PR looks good but I don't think the test is passing (I ran it locally). Kindly confirm please.

**Comment by kivimike** [comment]
> Hey @kivimike, the PR looks good but I don't think the test is passing (I ran it locally). Kindly confirm please.
I haven't fixed the test yet because I still have the same issue as I wrote above. I've only resolved conflicts with the main branch. Please have a look at my previous comment.

**Comment by ogbanugot** [comment]
Okay, seen! You might want to use a composite strategy i.e `st.composite` to create your inputs that way you can have more control over the shapes. In anycase, I don't think the PR is the best place to ask for help though if you are having issues. Feel free to ask a question on our [discord](https://discord.com/invite/G4aR9Q7DTN), that way you can have a better discussion about the issues you are facing.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
