### PR TITLE
 categorical_crossentropy #5027 

### LINKED ISSUE #5027: categorical_crossentropy

### PR DESCRIPTION
**Pull request by MutugiD**

### CODE REVIEW

**Comment by aryans1204** [comment]
#5027

**Comment by MutugiD** [comment]
Cannot pinpoint the 2 issues. @aryans1204 mind having a look?

**Comment by MutugiD** [comment]
Locally, all tests pass. 
I cannot pinpoint the 2 issues. @aryans1204 mind having a look?

**Comment by aryans1204** [comment]
please work on the previous review I've given first. Remove the type hints from the functional arguments, since those are not required in frontend tasks, and the lint formatting tests should pass. Additionally, you mentioned all tests pass locally. Which tests have you ran locally and could you attach a screenshot?

**Review by MutugiD — COMMENTED** [review]
Removed type hints and fixed lint formatting

**Comment by aryans1204** [comment]
Hi there are conflicts in your file metrics.py and test_metrics.py files compared to the Ivy master branch. Please resolve thos e first, and then this looks ready to merge.

**Comment by aryans1204** [comment]
Hi, your lint tests aren't passing specifically because your function formatting is inconsistent with Ivy standard.

**Comment by MutugiD** [comment]
@aryans1204 There seems to be a lint formatting problem with unrelated file - ivy/functional/backends/jax/extensions/random.py

**Comment by aryans1204** [comment]
> @aryans1204 There seems to be a lint formatting problem with unrelated file - ivy/functional/backends/jax/extensions/random.py

yup those are not to worry about. 


LGTM 🚀

**Pull request merged**
