### PR TITLE
docs: correct typo in README

### PR DESCRIPTION
**Pull request by adityadeshmukh369**
# PR Description 

## Related Issue 

Close #

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by theRealBird** [comment]
@adityadeshmukh369 Thanks for contributing to Ivy. 
Could you append the part where it says `at the time of writing` to your changes? I think it's a helpful statement

**Comment by adityadeshmukh369** [comment]
I have appended it. Please check for any changes.

**Comment by adityadeshmukh369** [comment]
@theRealBird can you review the changes pls.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
