### PR TITLE
adding reformat permute_dims manipulation function

### LINKED ISSUE #1809: permute_dims

### PR DESCRIPTION
**Pull request by yugaljain1999**
Fixes #1809

### CODE REVIEW

**Comment by yugaljain1999** [comment]
@RashulChutani Can you please review this PR?
Thanks

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Please reformat the docstrings to add a space between arguments. For example:
x = ivy.array([[1,2,3],[4,5,6]]) should be x = ivy.array([[1,2,3], [4,5,6]])

**Comment by yugaljain1999** [comment]
@RashulChutani Just fixed that.
Can you now merge it?

**Comment by yugaljain1999** [comment]
@RashulChutani @djl11 Can you pls review this PR?
Thanks

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @yugaljain1999, The added docstring looks good. Can you also make the required changes for the corresponding Ivy container and Array Functions as mentioned here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting. Thanks

**Comment by yugaljain1999** [comment]
@RashulChutani Can you merge this PR too? As reason is same as explained here. https://github.com/unifyai/ivy/pull/2222

**Comment by yugaljain1999** [comment]
@RashulChutani Can u review and merge this PR too.
Thanks

**Comment by ZoeCD** [comment]
Hi @yugaljain1999! Could you please review the docstring errors?

**Comment by yugaljain1999** [comment]
Hi @ZoeCD , As you can see in this screenshot., there is issue in test cases of is_int_dtype and this permute_dims has nothing to do with that. That's why I can't update anything in docstring.
image


Hope you are getting me. Looking forward to your review and merge this PR.
Thanks

**Comment by ZoeCD** [comment]
You are right. Thanks for the clarification! To make reviewing formatting PRs easier, we have a checklist now. Could you please follow the steps that are [here](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#formatting-checklist)? Thanks!

**Comment by yugaljain1999** [comment]
add_reformatting_checklist_manipulation

**Comment by yugaljain1999** [comment]
Hey @ZoeCD , Can you look at checklist now? I don't know why it's showing wrong for each check.. Can you pls clarify what's wrong with these checks because I did changes as per Daniel requested?
Thanks

**Comment by ZoeCD** [comment]
You have to modify each to-do according to the legend  🙂

**Comment by yugaljain1999** [comment]
Hey @ZoeCD Can you pls help me to resolve conflicts as when I committed on this PR last time , there wasn't any conflicts but suddenly now it's showing conflicts.
Can you pls take a look at it once in deep?
Thanks

**Comment by yugaljain1999** [comment]
add_reformatting_checklist_manipulation

**Pull request merged**
