### PR TITLE
Fix jax.nn.one_hot frontend test

### LINKED ISSUE #8691: Fix jax_nn_activations.test_jax_nn_one_hot
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5461165256/jobs/9938860654"></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5461165256/jobs/9938860654"></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5461165256/jobs/9938860654"></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5461165256/jobs/9938860654"></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5478319447"></a>

### PR DESCRIPTION
**Pull request by hello-fri-end**
Close #8691.

### CODE REVIEW

**Comment by hello-fri-end** [comment]
> Hey, thank you for your contribution! Can you take a look at the errors, please? Thanks!

Hey @V-G-spec, these errors are unrelated to my PR. The tests for `jax.nn.one_hot` are passing now.

**Comment by hello-fri-end** [comment]
Hey @V-G-spec, can we merge this please?

**Comment by hello-fri-end** [comment]
> Hi @hello-fri-end! Sorry for the delay in response. I am skeptical of how your change fixes the issue raised. Can you kindly explain to me why you have made the specific change? I know it is not a requirement, but it will help me assess your PR better. Thanks!

The only allowable datatype for the `indices` argument should be integer. With `numeric` even floats were generated which were causing the test to fail.

**Comment by V-G-spec** [comment]
Ah, I didn't know back then that you were part of the team and this wasn't for application. That's why I was getting a little intensive to make sure the contribution is significant 😅

**Pull request merged**
