### PR TITLE
feat: added elu_ activation function and test for PaddlePaddle frontend

### LINKED ISSUE #18944: elu_

### PR DESCRIPTION
**Pull request by sachelsout**
Close #18944

### CODE REVIEW

**Comment by sachelsout** [comment]
All the test cases passing locally for elu_ activation function of PaddlePaddle Frontend !
Thank you.

image

**Comment by sachelsout** [comment]
Hi @MuhammadSaeedBatikh , could you please review my PR ? 😃

**Comment by MuhammadSaeedBatikh** [comment]
Hi @sachelsout, thanks for the PR.
Please make the following changes.

- The name of [the original function ](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/elu_en.html) is `elu` and not `elu_` . Please change the function name in test module to `test_paddle_elu` and set `fn_tree` to `paddle.nn.functional.elu`

- `_elu_with_inplace` method is unnecessary; it could be simply implemented as such: 
```
def elu(
        x,
        /,
        *,
        alpha=1.0,
        name=None,
):
    return ivy.elu(x, alpha=alpha)
```
- Increase the range of alpha's `max_value` in `handle_frontend_test`: `alpha=helpers.floats(min_value=0, max_value=3, exclude_min=True)` 

Otherwise, lgtm.

**Comment by sachelsout** [comment]
Hi @MuhammadSaeedBatikh , thank you for the brief reply.

- I am working on elu_ activation function, not elu (someone else is working on elu). elu and elu_ are separate issues as seen in the below screenshot attached.
image
- The name of the original function is elu_. Check this out - https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/elu__en.html
image

- `_elu_with_inplace` method is indeed necessary for elu_ to work as inplace argument comes in handy for elu_ method definition.
- Alpha value ranges between 0 to 1. It wouldn't be greater than 1. May I know, why we should increase the alpha value then in test cases? 😕

**Comment by MuhammadSaeedBatikh** [comment]
Hi @sachelsout, thanks for your explanation. Indeed, it's a similar function with underscore. 
Regarding the second point; I don't see any inplace update here:
```
def _elu_with_inplace(x, alpha=1.0, inplace=False):
    return ivy.elu(x, alpha=alpha)
```
The `inplace` argument is not used. Furthermore, an inplace update is a simple enough operation that I don't think it requires a separate helper function; similar to what you did with [`relu_`](https://github.com/unifyai/ivy/issues/16343):
```
def relu_(x, name=None):
    ret = ivy.relu(x)
    ivy.inplace_update(x, ret)
    return x
```

Regarding the range of alpha; generally, tests need to be exhaustive in order to illustrate function's behavior when encountering corner cases. In this case, `alpha>1` is perfectly fine. See [ the assertion line](https://github.com/PaddlePaddle/Paddle/blob/release/2.5/python/paddle/nn/functional/activation.py#L136) in paddle's implementation of `elu_`. It checks if `alpha>=0`

**Comment by sachelsout** [comment]
Hi @MuhammadSaeedBatikh , thank you for the brief explanation ! I followed same steps for elu_ which I did for relu_ but I get AssertionError for all the backends.

**Comment by MuhammadSaeedBatikh** [comment]
> Hi @MuhammadSaeedBatikh , thank you for the brief explanation ! I followed same steps for elu_ which I did for relu_ but I get AssertionError for all the backends.
> 
> Is it necessary to do inplace update for the output tensor of elu_?

Hi @sachelsout, yes, I think it's necessary to have inplace update for `elu_` as it's the only thing distinguishing it from regular `elu`. Could you post the log of the exception you're getting here. Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by sachelsout** [comment]
Hi @MuhammadSaeedBatikh , apologies for the delay ! Here are the logs - 

(multienv) @sachelsout ➜ /workspaces/ivy (paddle_elu_) $ python3 -m pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_
Use Database in ReadOnly Mode with local caching !
===================================================================== test session starts =====================================================================
platform linux -- Python 3.10.0, pytest-7.4.0, pluggy-1.2.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-3.7.1, metadata-3.0.0, hypothesis-6.82.3, json-report-1.5.0
collected 5 items                                                                                                                                             

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py FFFFF                                                          [100%]

========================================================================== FAILURES ===========================================================================
___________________________________________________________ test_paddle_elu_[cpu-numpy-False-False] ___________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.nn.functional.elu_",
        dtype_and_input=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
        ),
        alpha=helpers.floats(min_value=0, max_value=1, exclude_min=True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:789: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:806: in test_paddle_elu_
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:833: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:141: in value_test
    assert_all_close(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ret_np = array(-0.31606028), ret_from_gt_np = array(-0.13549225), backend = 'numpy', rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'paddle'

    def assert_all_close(
        ret_np,
        ret_from_gt_np,
        backend: str,
        rtol=1e-05,
        atol=1e-08,
        ground_truth_backend="TensorFlow",
    ):
        """
        Match the ret_np and ret_from_gt_np inputs element-by-element to ensure that they
        are the same.
    
        Parameters
        ----------
        ret_np
            Return from the framework to test. Ivy Container or Numpy Array.
        ret_from_gt_np
            Return from the ground truth framework. Ivy Container or Numpy Array.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the test passes, else marks the test as failed.
        """
        ret_dtype = str(ret_np.dtype)
        ret_from_gt_dtype = str(ret_from_gt_np.dtype).replace("longlong", "int64")
        assert (
            ret_dtype == ret_from_gt_dtype
        ), (
            "the ground truth framework {} returned a {} datatype while "
            "the backend {} returned a {} datatype".format(
                ground_truth_backend,
                ret_from_gt_dtype,
                backend,
                ret_dtype,
            )
        )
        # TODO eanble
        # if ivy.is_ivy_container(ret_np) and ivy.is_ivy_container(ret_from_gt_np):
        #     ivy.Container.cont_multi_map(assert_all_close, [ret_np, ret_from_gt_np])
        # else:
        if ret_np.dtype == "bfloat16" or ret_from_gt_np.dtype == "bfloat16":
            ret_np = ret_np.astype("float64")
            ret_from_gt_np = ret_from_gt_np.astype("float64")
>       assert np.allclose(
            np.nan_to_num(ret_np), np.nan_to_num(ret_from_gt_np), rtol=rtol, atol=atol
        ), (
            f" the results from backend {backend} "
            f"and ground truth framework {ground_truth_backend} "
            f"do not match\n {ret_np}!={ret_from_gt_np} \n\n"
        )
E       AssertionError:  the results from backend numpy and ground truth framework paddle do not match
E        -0.31606027941427883!=-0.13549224789223768 
E       
E       
E       Falsifying example: test_paddle_elu_(
E           on_device='cpu',
E           backend_fw='numpy',
E           frontend='paddle',
E           dtype_and_input=(['float64'], [array(-1.)]),
E           alpha=0.5,
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E           fn_tree='ivy.functional.frontends.paddle.nn.functional.elu_',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.3', b'AXicY2AAAkYGCADTBxiQAAAKCwDD') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:62: AssertionError
____________________________________________________________ test_paddle_elu_[cpu-jax-False-False] ____________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.nn.functional.elu_",
        dtype_and_input=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
        ),
        alpha=helpers.floats(min_value=0, max_value=1, exclude_min=True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:789: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:806: in test_paddle_elu_
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:833: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:141: in value_test
    assert_all_close(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ret_np = array(-0.31606028), ret_from_gt_np = array(-0.13549225), backend = 'jax', rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'paddle'

    def assert_all_close(
        ret_np,
        ret_from_gt_np,
        backend: str,
        rtol=1e-05,
        atol=1e-08,
        ground_truth_backend="TensorFlow",
    ):
        """
        Match the ret_np and ret_from_gt_np inputs element-by-element to ensure that they
        are the same.
    
        Parameters
        ----------
        ret_np
            Return from the framework to test. Ivy Container or Numpy Array.
        ret_from_gt_np
            Return from the ground truth framework. Ivy Container or Numpy Array.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the test passes, else marks the test as failed.
        """
        ret_dtype = str(ret_np.dtype)
        ret_from_gt_dtype = str(ret_from_gt_np.dtype).replace("longlong", "int64")
        assert (
            ret_dtype == ret_from_gt_dtype
        ), (
            "the ground truth framework {} returned a {} datatype while "
            "the backend {} returned a {} datatype".format(
                ground_truth_backend,
                ret_from_gt_dtype,
                backend,
                ret_dtype,
            )
        )
        # TODO eanble
        # if ivy.is_ivy_container(ret_np) and ivy.is_ivy_container(ret_from_gt_np):
        #     ivy.Container.cont_multi_map(assert_all_close, [ret_np, ret_from_gt_np])
        # else:
        if ret_np.dtype == "bfloat16" or ret_from_gt_np.dtype == "bfloat16":
            ret_np = ret_np.astype("float64")
            ret_from_gt_np = ret_from_gt_np.astype("float64")
>       assert np.allclose(
            np.nan_to_num(ret_np), np.nan_to_num(ret_from_gt_np), rtol=rtol, atol=atol
        ), (
            f" the results from backend {backend} "
            f"and ground truth framework {ground_truth_backend} "
            f"do not match\n {ret_np}!={ret_from_gt_np} \n\n"
        )
E       AssertionError:  the results from backend jax and ground truth framework paddle do not match
E        -0.31606027941427883!=-0.13549224789223768 
E       
E       
E       Falsifying example: test_paddle_elu_(
E           on_device='cpu',
E           backend_fw='jax',
E           frontend='paddle',
E           dtype_and_input=(['float64'], [array(-1.)]),
E           alpha=0.5,
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E           fn_tree='ivy.functional.frontends.paddle.nn.functional.elu_',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.3', b'AXicY2AAAkYGCADTBxiQAQAKzgDD') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:62: AssertionError
________________________________________________________ test_paddle_elu_[cpu-tensorflow-False-False] _________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.nn.functional.elu_",
        dtype_and_input=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
        ),
        alpha=helpers.floats(min_value=0, max_value=1, exclude_min=True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:789: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:806: in test_paddle_elu_
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:833: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:141: in value_test
    assert_all_close(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ret_np = array(-0.31606028), ret_from_gt_np = array(-0.13549225), backend = 'tensorflow', rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'paddle'

    def assert_all_close(
        ret_np,
        ret_from_gt_np,
        backend: str,
        rtol=1e-05,
        atol=1e-08,
        ground_truth_backend="TensorFlow",
    ):
        """
        Match the ret_np and ret_from_gt_np inputs element-by-element to ensure that they
        are the same.
    
        Parameters
        ----------
        ret_np
            Return from the framework to test. Ivy Container or Numpy Array.
        ret_from_gt_np
            Return from the ground truth framework. Ivy Container or Numpy Array.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the test passes, else marks the test as failed.
        """
        ret_dtype = str(ret_np.dtype)
        ret_from_gt_dtype = str(ret_from_gt_np.dtype).replace("longlong", "int64")
        assert (
            ret_dtype == ret_from_gt_dtype
        ), (
            "the ground truth framework {} returned a {} datatype while "
            "the backend {} returned a {} datatype".format(
                ground_truth_backend,
                ret_from_gt_dtype,
                backend,
                ret_dtype,
            )
        )
        # TODO eanble
        # if ivy.is_ivy_container(ret_np) and ivy.is_ivy_container(ret_from_gt_np):
        #     ivy.Container.cont_multi_map(assert_all_close, [ret_np, ret_from_gt_np])
        # else:
        if ret_np.dtype == "bfloat16" or ret_from_gt_np.dtype == "bfloat16":
            ret_np = ret_np.astype("float64")
            ret_from_gt_np = ret_from_gt_np.astype("float64")
>       assert np.allclose(
            np.nan_to_num(ret_np), np.nan_to_num(ret_from_gt_np), rtol=rtol, atol=atol
        ), (
            f" the results from backend {backend} "
            f"and ground truth framework {ground_truth_backend} "
            f"do not match\n {ret_np}!={ret_from_gt_np} \n\n"
        )
E       AssertionError:  the results from backend tensorflow and ground truth framework paddle do not match
E        -0.31606027941427883!=-0.13549224789223768 
E       
E       
E       Falsifying example: test_paddle_elu_(
E           on_device='cpu',
E           backend_fw='tensorflow',
E           frontend='paddle',
E           dtype_and_input=(['float64'], [array(-1.)]),
E           alpha=0.5,
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E           fn_tree='ivy.functional.frontends.paddle.nn.functional.elu_',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.3', b'AXicY2AAAkYGCADTBxiQAQAKzgDD') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:62: AssertionError
___________________________________________________________ test_paddle_elu_[cpu-torch-False-False] ___________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.nn.functional.elu_",
        dtype_and_input=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
        ),
        alpha=helpers.floats(min_value=0, max_value=1, exclude_min=True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:789: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:806: in test_paddle_elu_
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:833: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:141: in value_test
    assert_all_close(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ret_np = array(-0.31606028), ret_from_gt_np = array(-0.13549225), backend = 'torch', rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'paddle'

    def assert_all_close(
        ret_np,
        ret_from_gt_np,
        backend: str,
        rtol=1e-05,
        atol=1e-08,
        ground_truth_backend="TensorFlow",
    ):
        """
        Match the ret_np and ret_from_gt_np inputs element-by-element to ensure that they
        are the same.
    
        Parameters
        ----------
        ret_np
            Return from the framework to test. Ivy Container or Numpy Array.
        ret_from_gt_np
            Return from the ground truth framework. Ivy Container or Numpy Array.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the test passes, else marks the test as failed.
        """
        ret_dtype = str(ret_np.dtype)
        ret_from_gt_dtype = str(ret_from_gt_np.dtype).replace("longlong", "int64")
        assert (
            ret_dtype == ret_from_gt_dtype
        ), (
            "the ground truth framework {} returned a {} datatype while "
            "the backend {} returned a {} datatype".format(
                ground_truth_backend,
                ret_from_gt_dtype,
                backend,
                ret_dtype,
            )
        )
        # TODO eanble
        # if ivy.is_ivy_container(ret_np) and ivy.is_ivy_container(ret_from_gt_np):
        #     ivy.Container.cont_multi_map(assert_all_close, [ret_np, ret_from_gt_np])
        # else:
        if ret_np.dtype == "bfloat16" or ret_from_gt_np.dtype == "bfloat16":
            ret_np = ret_np.astype("float64")
            ret_from_gt_np = ret_from_gt_np.astype("float64")
>       assert np.allclose(
            np.nan_to_num(ret_np), np.nan_to_num(ret_from_gt_np), rtol=rtol, atol=atol
        ), (
            f" the results from backend {backend} "
            f"and ground truth framework {ground_truth_backend} "
            f"do not match\n {ret_np}!={ret_from_gt_np} \n\n"
        )
E       AssertionError:  the results from backend torch and ground truth framework paddle do not match
E        -0.31606027941427883!=-0.13549224789223768 
E       
E       
E       Falsifying example: test_paddle_elu_(
E           on_device='cpu',
E           backend_fw='torch',
E           frontend='paddle',
E           dtype_and_input=(['float64'], [array(-1.)]),
E           alpha=0.5,
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E           fn_tree='ivy.functional.frontends.paddle.nn.functional.elu_',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.3', b'AXicY2AAAkYGCADTBxiQAQAKzgDD') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:62: AssertionError
__________________________________________________________ test_paddle_elu_[cpu-paddle-False-False] ___________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.nn.functional.elu_",
        dtype_and_input=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
        ),
        alpha=helpers.floats(min_value=0, max_value=1, exclude_min=True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:789: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py:806: in test_paddle_elu_
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:833: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:141: in value_test
    assert_all_close(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ret_np = array(-0.31606028), ret_from_gt_np = array(-0.13549225), backend = 'paddle', rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'paddle'

    def assert_all_close(
        ret_np,
        ret_from_gt_np,
        backend: str,
        rtol=1e-05,
        atol=1e-08,
        ground_truth_backend="TensorFlow",
    ):
        """
        Match the ret_np and ret_from_gt_np inputs element-by-element to ensure that they
        are the same.
    
        Parameters
        ----------
        ret_np
            Return from the framework to test. Ivy Container or Numpy Array.
        ret_from_gt_np
            Return from the ground truth framework. Ivy Container or Numpy Array.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the test passes, else marks the test as failed.
        """
        ret_dtype = str(ret_np.dtype)
        ret_from_gt_dtype = str(ret_from_gt_np.dtype).replace("longlong", "int64")
        assert (
            ret_dtype == ret_from_gt_dtype
        ), (
            "the ground truth framework {} returned a {} datatype while "
            "the backend {} returned a {} datatype".format(
                ground_truth_backend,
                ret_from_gt_dtype,
                backend,
                ret_dtype,
            )
        )
        # TODO eanble
        # if ivy.is_ivy_container(ret_np) and ivy.is_ivy_container(ret_from_gt_np):
        #     ivy.Container.cont_multi_map(assert_all_close, [ret_np, ret_from_gt_np])
        # else:
        if ret_np.dtype == "bfloat16" or ret_from_gt_np.dtype == "bfloat16":
            ret_np = ret_np.astype("float64")
            ret_from_gt_np = ret_from_gt_np.astype("float64")
>       assert np.allclose(
            np.nan_to_num(ret_np), np.nan_to_num(ret_from_gt_np), rtol=rtol, atol=atol
        ), (
            f" the results from backend {backend} "
            f"and ground truth framework {ground_truth_backend} "
            f"do not match\n {ret_np}!={ret_from_gt_np} \n\n"
        )
E       AssertionError:  the results from backend paddle and ground truth framework paddle do not match
E        -0.31606027941427883!=-0.13549224789223768 
E       
E       
E       Falsifying example: test_paddle_elu_(
E           on_device='cpu',
E           backend_fw='paddle',
E           frontend='paddle',
E           dtype_and_input=(['float64'], [array(-1.)]),
E           alpha=0.5,
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E           fn_tree='ivy.functional.frontends.paddle.nn.functional.elu_',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.3', b'AXicY2AAAkYGCADTBxiQAQAKzgDD') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:62: AssertionError
====================================================================== warnings summary =======================================================================
../../opt/fw/tensorflow/_distutils_hack/__init__.py:18
  /opt/fw/tensorflow/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
    warnings.warn(

../../opt/fw/tensorflow/_distutils_hack/__init__.py:33
  /opt/fw/tensorflow/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")

../../opt/fw/tensorflow/setuptools/sandbox.py:13
  /opt/fw/tensorflow/setuptools/sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../../opt/fw/tensorflow/pkg_resources/__init__.py:2871
  /opt/fw/tensorflow/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
  /workspaces/ivy/ivy/functional/backends/numpy/experimental/activations.py:91: RuntimeWarning: overflow encountered in expm1
    ret = np.where(x > 0, x, np.multiply(alpha, np.expm1(x))).astype(x.dtype)

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False]
  /workspaces/ivy/ivy/functional/backends/numpy/experimental/activations.py:91: RuntimeWarning: invalid value encountered in multiply
    ret = np.where(x > 0, x, np.multiply(alpha, np.expm1(x))).astype(x.dtype)

ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py: 18 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1035: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================================= 0.0% of 5 passed ========================================================================================================================================= short test summary info ===================================================================
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-numpy-False-False] - AssertionError:  the results from backend numpy and ground truth framework paddle do not match
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-jax-False-False] - AssertionError:  the results from backend jax and ground truth framework paddle do not match
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-tensorflow-False-False] - AssertionError:  the results from backend tensorflow and ground truth framework paddle do not match
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-torch-False-False] - AssertionError:  the results from backend torch and ground truth framework paddle do not match
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_activation.py::test_paddle_elu_[cpu-paddle-False-False] - AssertionError:  the results from backend paddle and ground truth framework paddle do not match
=============================================================== 5 failed, 32 warnings in 32.71s ===============================================================
(multienv) @sachelsout ➜ /workspaces/ivy (paddle_elu_) $

**Comment by sachelsout** [comment]
@MuhammadSaeedBatikh , I've updated the code and resolved merge conflicts as well. All the tests are failing due to Assertion Error. Could you please let me know what I can do ? I've defined the elu_ function as mentioned.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @sachelsout 
We apologise for the late reply due to changes in PR review policies.
Thank you very much for the PR.
The tests on the PR still fail.
```
E   AssertionError:  the results from backend torch and ground truth framework paddle do not match
159
E    -1.0!=-0.31606027483940125 
160
E   
161
E   
162
E   Falsifying example: test_paddle_elu_(
163
E       on_device='cpu',
164
E       backend_fw='torch',
165
E       frontend='paddle',
166
E       dtype_and_input=(['float32'], [array(-1., dtype=float32)]),
167
E       alpha=0.5,  # or any other generated value
168
E       fn_tree='ivy.functional.frontends.paddle.nn.functional.elu_',
169
E       test_flags=FrontendFunctionTestFlags(
170
E           num_positional_args=1,
171
E           with_out=False,
172
E           with_copy=False,
173
E           inplace=False,
174
E           as_variable=[True],
175
E           native_arrays=[False],
176
E           test_trace=False,
177
E           generate_frontend_arrays=False,
178
E           transpile=False,
179
E           precision_mode=False,
180
E       ),
181
E   )
```
you can see this in the test logs @  https://github.com/unifyai/ivy/actions/runs/7310033443/job/19918258100?pr=18945
under the section Determine and Run Tests.
Let me know if anything is unclear. Thnx :)

**Comment by Ishticode** [comment]
Closing this due to inactivity. Please feel free to reopen

**Pull request closed without merging**
