### PR TITLE
reformat dev_dist_array

### PR DESCRIPTION
**Pull request by rjsun06**

### CODE REVIEW

**Comment by rjsun06** [comment]
#1979

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi, The reformatting looks good. Can you please add a link to the original issue from which you took this function into this PR itself so that it is automatically closed when I merge it?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
