### PR TITLE
Added count_nonzero to paddle_frontend

### LINKED ISSUE #23118: count_nonzero

### PR DESCRIPTION
**Pull request by AryanSharma21**
close #23118

Local env Function test result:

Screenshot 2023-09-07 at 10 26 52 AM

Local env lint formatting test:

Screenshot 2023-09-08 at 8 58 35 PM

### CODE REVIEW

**Comment by AryanSharma21** [comment]
Please review here @danielmunioz

**Review by Daniel4078 — APPROVED** [review]
Looks good to me

**Comment by danielmunioz** [comment]
Hey @AryanSharma21! Thanks for contributing!

Yeah the tests seem to be passing locally no problem there, however it seems that the function arguments are a bit different from the ones used on the [original implementation](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/count_nonzero_en.html) could you please modify the arguments so that they match the original ones?

Other than that the PR looks in good shape!
Thanks! :)

**Comment by AryanSharma21** [comment]
Hello @danielmunioz , thanks for pointing this out. I have removed the dtype argument here and re-tested, Is there anything else that needs to be fixed please let me know.

**Comment by danielmunioz** [comment]
Hey! @AryanSharma21! Yeah It looks good now, just a minor extra letter on `keepdims`, paddle uses `keepdim` instead, but no worries, I'll take care of that little thing!

Other than that, the PR looks good to me!
Merging now! 🚀 

Thanks for contributing :)

**Pull request merged**
