### PR TITLE
Update linear_algebra.py

### PR DESCRIPTION
**Pull request by yluoc**
update solve_triangular in ivy/functional/ivy/experimental/linear_algebra.py

Close https://github.com/unifyai/ivy/issues/3856

### CODE REVIEW

**Comment by yluoc** [comment]
update solve_triangular in [ivy/functional/ivy/experimental/linear_algebra.py]

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by yluoc** [comment]
Close #3856

**Comment by kgmann** [comment]
Hey @yluoc thanks for your contribution, but your work is incomplete. You have to implement the function in ivy's functional API and for each backend, and test. Please take a look at this https://lets-unify.ai/docs/ivy/overview/contributing/open_tasks.html#ivy-experimental-api and let me know if you have any other question. You can also take a look at how some of the functions have been implemented [here](https://github.com/unifyai/ivy/issues/3856) to have a better idea of what to do.

**Comment by kgmann** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you hugs

Also @yluoc please follow the guidelines to create an issue and link the PR to it.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by danielmunioz** [comment]
Closing due to inactivity, as it's been more than 2 weeks without changes

**Pull request closed without merging**
