### PR TITLE
Reformatted bitwise_or

### LINKED ISSUE #1911: bitwise_or

### PR DESCRIPTION
**Pull request by RitikRawat**
Changes:

Added/updated docstrings in bitwise_or(), +examples
Added ivy.Container static of ivy.bitwise_or()
Removed lambda in return
Thanks!

closes #1911

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

The changes look good, but Functional examples also need to be added in `ivy/functional/ivy/elementwise.py`. You can see this requirement [here](https://github.com/unifyai/ivy/blob/06c3ba2152f21ac6fa48261a37e05f6941f127c0/docs/partial_source/deep_dive/12_docstring_examples.rst) in point 1 to 5.

Let me know if you have any question, I'd be happy to answer.
Thanks

**Comment by RitikRawat** [comment]
@sherry30 
Hey,
I did the requested changes.
Please review whenever you can.
Thanks!

**Comment by sherry30** [comment]
Hi,

test_docstring seems to be failing for bitwise_or, can you try to fix these errors. If you can't you can ask for help, I'd be happy to answer any questions. You can run this test locally from `ivy_tests/test_docstrings.py` and see the output on received on run.

Thanks

**Comment by RitikRawat** [comment]
> Hi,
> 
> test_docstring seems to be failing for bitwise_or, can you try to fix these errors. If you can't you can ask for help, I'd be happy to answer any questions. You can run this test locally from `ivy_tests/test_docstrings.py` and see the output on received on run.
> 
> Thanks

Hey,
The test is failing due to some issue with int32 dtype (I have seen other PRs from people that have fixed it). I looked for issues with the bitwise_or function specifically, and didn't find anything.
Thanks.

**Comment by RitikRawat** [comment]
> Hi,
> 
> test_docstring seems to be failing for bitwise_or, can you try to fix these errors. If you can't you can ask for help, I'd be happy to answer any questions. You can run this test locally from `ivy_tests/test_docstrings.py` and see the output on received on run.
> 
> Thanks

Hey, Fixed the issue.
the docstring test is still failing though, because of some issue with the int32 dtype. I just fixed the issue with the bitwise_or function.
Thanks

**Comment by RitikRawat** [comment]
@sherry30 please review the changes.

**Pull request merged**
