### PR TITLE
#16065 - Implements eigh_tridiagonal in TensorFlow front end

### LINKED ISSUE #16065: eigh_tridiagonal

### PR DESCRIPTION
**Pull request by fractalis**
Close #16065

### CODE REVIEW

**Comment by KareemMAX** [comment]
add_frontend_checklist

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hi @fractalis,

Great work, I've some comments on your code. Also you didn't complete our required guidelines which you can see in the checklist I added.

Please feel free to request a review once you finish your changes

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
