### PR TITLE
Cosine function added to Numpy frontend trigonomertic_functions

### LINKED ISSUE #23545: cos

### PR DESCRIPTION
**Pull request by Sol1man**
# PR Description
 Feat: implemented cosine function in numpy frontend

## Related issue

Close #23545

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Sol1man** [comment]
I edited it
I added “Close #issue number” at the description, but it failed in Semantic check

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sol1man** [comment]
Can you send me copy of pr template?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by Fayad-Alman — CHANGES_REQUESTED** [review]
Hi @Sol1man, this looks good so far, just one quick change:

**Pull request closed without merging**
