### PR TITLE
Improving Function Arguments

### PR DESCRIPTION
**Pull request by mobley-trent**
This PR adds default arguments to convolution functions as well as their corresponding stateful classes.

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hello, please change the arguments in all backends if the implementation is not compositional

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
can you please update the documentation to reflect the new defaults?

**Comment by mobley-trent** [comment]
@KareemMAX what do you think of these changes so far ?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
