### PR TITLE
Added torch frontend function diagflat

### LINKED ISSUE #22094: diagflat

### PR DESCRIPTION
**Pull request by Darshan-H-E**
closes #22094

### CODE REVIEW

**Comment by Darshan-H-E** [comment]
Hi @paulaehab, could you please look into this PR?
Thank you

**Comment by paulaehab** [comment]
Hi @Darshan-H-E 
first sorry for late reply, nice work and thanks for contributing 😄 just solve these conflicts and I will merge it.

**Comment by Darshan-H-E** [comment]
Hi @paulaehab, I have resolved the conflicts.

**Comment by paulaehab** [comment]
Hi @Darshan-H-E Nice work, thanks for contributing 😄

**Pull request merged**
