### PR TITLE
Logit added

### LINKED ISSUE #17362: logit

### PR DESCRIPTION
**Pull request by shivam-151197**
Close #17362

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by satakshigarg** [comment]
Hey @shivam-151197 , thanks a lot for the PR. I have to mention some points though:

- There are some tests that your PR is failing. Kindly look into those [here](https://github.com/unifyai/ivy/actions/runs/5275576030/jobs/9541202739?pr=16737) and fix them. 
- I'm guessing you haven't installed pre-commit since it automatically runs all these checks whenever you commit your code and push it. I suggest you [set up](https://lets-unify.ai/ivy/overview/contributing/setting_up.html#pre-commit) pre-commit in your local environment and [run](https://lets-unify.ai/ivy/overview/deep_dive/formatting.html#pre-commit-hook) these linting and formatting checks because otherwise the CI tests will fail every time you submit a PR that has linting and formatting issues.
- Besides you have been advised earlier to link the issue to the PR description [here](https://github.com/unifyai/ivy/pull/16737#issuecomment-1597605527) and have been shared a guide. Please ensure that your PR follows the guide.
- I'm guessing you didn't run the tests locally because pytest would have thrown an error. Kindly always make sure that you run all your tests locally and ensure that they pass for ALL backends because otherwise the CI tests will fail when you submit a PR.
When you've done all these changes and verified that the tests are passing, feel free to ask for a re-review from me 🙂

Good luck!

**Comment by shivam-151197** [comment]
@satakshigarg I have created a new PR for the issue #17362. Kindly Review #17787. I have considered all your suggestions.

**Pull request closed without merging**
