### PR TITLE
feat: add segment_sum function to Ivy TensorFlow frontend

### LINKED ISSUE #27220: segment_sum

### PR DESCRIPTION
**Pull request by pixel3user**
# add segment_sum function to Ivy TensorFlow frontend under math 

## 27220

Closes #27220

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Review by he11owthere — CHANGES_REQUESTED** [review]
Hey, nice work but it seems like you are testing only for `int32` inputs. You can find all the available data types here: https://www.tensorflow.org/api_docs/python/tf/math/segment_sum

Make sure to add `with_supported_dtypes` / `with_unsupported_dtypes` decorator above your function and add each data type accordingly. Thanks!

**Comment by pixel3user** [comment]
Hi, i have added `with_unsupported_dtypes` decorator in the frontend function. For the test cases i tried `data=helpers.array_values(dtype=helpers.get_dtypes(), shape=(5, 6)),` all the valid dtypes but i am getting `AssertionError` 
for the dtypes. Also take a look at `input_dtypes` under `helpers.test_frontend_function`.

**Comment by pixel3user** [comment]
I have added test cases for all dtypes and with_unsupported_dtype decorator for the frontend funciton. I get to find out that paddle does not support int8 and throwing a RuntimeError. `RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), int8) of kernel 'slice' is not registered. Selected wrong DataType 'int8'. Paddle support following DataTypes: int64, float64, complex128, float32, complex64, int32, uint8, bfloat16, bool.` The test runs are passing 5/5 mostly but sometime throw RuntimeError in paddle backend.

**Review by he11owthere — COMMENTED** [review]
Hey @pixel3user, nice changes! But as mentioned earlier, you also need to test the `segment_ids` for `int64` data type as written in the official TensorFlow documentation.

image

Also, could you please resolve the linter issues? I can definitely merge after that. Thanks!

**Comment by he11owthere** [comment]
> @he11owthere I have added test cases for all dtypes and with_unsupported_dtype decorator for the frontend funciton. I get to find out that paddle does not support int8 and throwing a RuntimeError. `RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), int8) of kernel 'slice' is not registered. Selected wrong DataType 'int8'. Paddle support following DataTypes: int64, float64, complex128, float32, complex64, int32, uint8, bfloat16, bool.` The test runs are passing 5/5 mostly but sometime throw RuntimeError in paddle backend.

Then you should add `int8` inside `with_unsupported_dtypes` decorator. Tests are failing for paddle on the CI: 
https://github.com/unifyai/ivy/actions/runs/7174426309/job/19536724302?pr=27459#step:6:14

**Comment by pixel3user** [comment]
Hi @he11owthere, the ivy-lint are passing on my end and i have added int8 to `with_unsupported_dtypes`. Also take a look at segment_ids dtype generation, as i have added test cases for all integers. In the end, i just realize that i am pushing the changes from the main branch. If that's not possible kindly let me know.

**Comment by he11owthere** [comment]
> Hi @he11owthere, the ivy-lint are passing on my end and i have added int8 to `with_unsupported_dtypes`. Also take a look at segment_ids dtype generation, as i have added test cases for all integers. In the end, i just realize that i am pushing the changes from the main branch. If that's not possible kindly let me know.

Linting issues have been resolved but I see new failures on the CI related to Paddle and JAX backend:
https://github.com/unifyai/ivy/actions/runs/7226170206/job/19691915892?pr=27459#step:6:28

Maybe try limiting the data types because it seems like majority of them are not supported by other backends.

**Comment by pixel3user** [comment]
I have removed the failing dtypes, now paddle and jax backend are running great.

**Review by he11owthere — APPROVED** [review]

**Review by he11owthere — APPROVED** [review]
LGTM!

**Pull request merged**
