### PR TITLE
implemented the nanmedian along with test cases

### LINKED ISSUE #19354: nanmedian

### PR DESCRIPTION
**Pull request by supreer**
Implemented the nanmedian end-to-end functionality along with all passed test cases fixes #19354

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @supreer ! Thanks for creating this PR. Would you please revert all the changes you made to the files inside the .idea folder - you shouldn't push any changes you make to these files. Feel free to request another review when you're done with the changes.

**Comment by supreer** [comment]
I have reverted the changes @hello-fri-end

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @supreer ! Could you please also undo the changes inside `.idea/runConfigurations/_template__of_py_test.xml` and `.idea/vcs.xml`. Feel free to request another review when you are done. Thanks

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Kindly un-commit your changes from the `.idea` folder thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
