### PR TITLE
Updated docstrings in set, random, and manipulation submodules

### PR DESCRIPTION
**Pull request by Archymade**
I've made docstrings for the following functions in the frontend:
1. unique_all (set)
2. unique_counts (set)
3. random_normal (random)
4. randint (random)
5. shuffle (random)
6. multinomial (random)
7. squeeze (manipulation)
8. flip (manipulation)
9. permute_dims (manipulation)
10. concat (manipulation)
11. split (manipulation)

### CODE REVIEW

**Comment by VedPatwardhan** [comment]
Hey, @Archymade, the tests seem to be failing because of an issue with the parameters, could you please try to resolve it? Thank you!

**Comment by Archymade** [comment]
> Hey, @Archymade, the tests seem to be failing because of an issue with the parameters, could you please try to resolve it? Thank you!

I'm on it!

**Comment by Archymade** [comment]
Sorry, had to clean it out. Too many updates at once.

**Comment by VedPatwardhan** [comment]
Yeah, no problem!

**Pull request closed without merging**
