### PR TITLE
added paddle.median frontend function with its test

### LINKED ISSUE #16639: median

### PR DESCRIPTION
**Pull request by Mghrabi**
Close #16639 in #15115

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Mghrabi** [comment]
Review please @DragosStoican, thanks

**Comment by DragosStoican** [comment]
Hey @Mghrabi , can you make sure that the only modifications are to the function and the test for the function? There are a lot of changes in array_api_testing that shouldn't be there! Please remove those changes and then I'll quickly have another look! Thanks for your contribution!

**Comment by Mghrabi** [comment]
Yeah, my bad

**Comment by Mghrabi** [comment]
Done @DragosStoican

**Comment by Mghrabi** [comment]
@DragosStoican When I made the changes the first time I directly checked if the PR introduced any new failures in GitHub actions and it didn't, and I thought that to be enough, but I turned out to be wrong :( , thanks for pointing that out.

Anyway, I made the required changes and everything should be fine from the frontend side, the only issue is with backends (except Tensorflow) since the test fails with (Returning the wrong data type), which is completely a backend issue. When I fixed them locally all tests passed for `test_paddle_median` which verifies the frontend is implemented correctly.

For example with the case of `numpy` for `median` func in `ivy/functional/backends/numpy/experimental/statistical.py` if we changed the following section 
``` 
...
    if input.dtype in [np.uint64, np.int64, np.float64]:
        return ret.astype(np.float64)
    elif input.dtype in [np.float16]:
        return ret.astype(input.dtype)
    else:
        return ret.astype(np.float32)
```
to:
```
...
 if input.dtype in [np.float64]:
        return ret.astype(np.float64)
 else:
        return ret.astype(np.float32)
```
this will pass the test for `numpy` backend, it simply makes numpy median function returns `float32` for all input data types except for `float64` which should be returned as it is according to docs [here](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/median_en.html), This will make the test (`test_paddle_median`) to pass for `numpy` backend as mentioned, and the other tests will pass as well if the required changes made for each backend. 

Sorry for this long comment but this should verify the frontend function & its test are implemented as needed.

Note: the change I made for the `numpy` backend median function is not real fix for the returned type issue, it just fixes it for a single case (`paddle.median`).

**Comment by Mghrabi** [comment]
Please let me know if something is not correct, thanks in advance

**Comment by DragosStoican** [comment]
Hi @Mghrabi ! Sorry for the slow response I was away for the last few days!

I understand what you mean with the failing tests. However, with the changes you suggested for `numpy.meadian`, you would be introducing failing tests in other frontends. I tested your implementation and it causes a new failure in the `jax` frontend. In this scenario changing the backend function is not the correct thing to do, unless you notice a clear mistake (which I don't think is the case here).

Since `ivy.median` doesn't function in the correct way for the paddle frontend, I would suggest you add some logic in the frontend function to deal with the input dtypes such that the returned values are of the correct dtype. I think with a few type checks and casts inside the frontend function you can get `paddle.median` to work as expected and get all the tests passing!

Let me know how it goes!

**Comment by Mghrabi** [comment]
@DragosStoican take your time, thanks for your valuable time.
I made the changes and all tests are passing and squashed the commits into one

btw when I made the changes for the backend, I was aware that they will make other frontends fail, the changes were just for demonstration purposes that the backend could be the source of the problem and they weren't the solution at all that's why I left a **Note** above. Thanks again for your time

**Pull request merged**
