### PR TITLE
sinh adhering to Array API Standard

### PR DESCRIPTION
**Pull request by zby-zy**

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
It looks like your sinh function in the ivy/functional/ivy/array_api/elementwise_functions.py file is indented, which is causing tests to fail, could you amend this. Also could you make sure you have checked the box "Allow edits from maintainers". Thanks 🙂

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Please could you add appropriate spacing in sinh's docstring to make it more readable. Or if you allow edits by maintainers I can just do it. Thanks 🙂

**Review by mattbarrett98 — APPROVED** [review]
Everything looks good thanks for your contribution 🙂 We’ll just get confirmation off @djl11 before merging your changes.

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
