### PR TITLE
index_add

### LINKED ISSUE #26392: index_add
index_add function

### PR DESCRIPTION
**Pull request by imsoumya18**
# PR Description
index_add method in Paddla FrontEnd

## Related Issue
index_add #26392

Close #26392

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials
[Twitter](https://twitter.com/imsoumya184)

### CODE REVIEW

**Review by HaiderSultanArc — CHANGES_REQUESTED** [review]
Can you merge upstream/main into your branch please? 😄

**Comment by imsoumya18** [comment]
@HaiderSultanArc I have merged, have a look now

**Review by HaiderSultanArc — CHANGES_REQUESTED** [review]
All of your tests are failing 🤔 . Can you have a look at your implementation?
image

**Review by HaiderSultanArc — COMMENTED** [review]
Can you merge with upstream/main again? The issue of CI should be fixed now.

**Comment by imsoumya18** [comment]
> Can you merge with upstream/main again? The issue of CI should be fixed now.

I have merged the main. But, I need to make some modifications to the test. Also, I have something to say to you about this frontend function. I shall DM u on Discord.

**Comment by imsoumya18** [comment]
@HaiderSultanArc all the tests are passing now but, please don't merge it now until I add this to Ivy Functional API and here replace the code with calling `ivy.index_add` API as I have told you on Discord.

**Comment by NiteshK84** [comment]
Hi @imsoumya18, if you PR is ready, you can let me know for the review.

**Comment by NiteshK84** [comment]
Hi @imsoumya18,
test cases for torch and paddle backends are failing, can you please look into it,
image
image

**Comment by imsoumya18** [comment]
@NiteshK84 it is now passing all tests

**Comment by NiteshK84** [comment]
Hi @imsoumya18,
image
LGTM!

**Comment by NiteshK84** [comment]
not sure why a lot of tests are failing in CI.

**Comment by NiteshK84** [comment]
Adds paddle frontend function index_add.

**Pull request merged**
