### PR TITLE
Adds constant_initializer to Tensorflow frontend

### LINKED ISSUE #21611: constant_initializer

### PR DESCRIPTION
**Pull request by MaxFrax**
Close #21611

### CODE REVIEW

**Comment by MaxFrax** [comment]
This pull request replaces https://github.com/unifyai/ivy/pull/21733
It's the same edits, without some git submodule mess that I did.

@OmarJabri7 I think we should pick the conversation up from here.

Unfortunately my tests are still not running.
In attachment, you can find `pytest ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_constant_initializer` output.
I get the error `TypeError: Constant.__init__() got an unexpected keyword argument 'dtype'` however I cannot figure out how to fix it.

[pytest_out.txt](https://github.com/unifyai/ivy/files/12469534/pytest_out.txt)

**Comment by OmarJabri7** [comment]
Hey @MaxFrax , I see you need to add:
if dtype is not None:
        return EagerTensor(ivy.astype(value, dtype))
to your constant_initializer fn, try that and let me know :D

**Comment by OmarJabri7** [comment]
Hey @MaxFrax , did you get anything working? ore any success with this?

**Comment by MaxFrax** [comment]
@OmarJabri7 Hey, the short answer is no! Now I'll explain what's going on and what I tried.

The error happens while running my test `test_tensorflow_constant_initializer`, at line 879 in function_testing.py
```
>       frontend_ret = frontend_fw.__dict__[gt_fn_name](*args_frontend, **kwargs_frontend)
E       TypeError: Constant.__init__() got an unexpected keyword argument 'dtype'
```

As far as I understand, `frontend_fw` is the tensorflow frontend module that gets imported on line 878.
If I inspect the keys I find that:
- The key `constant`, the function I am using as reference, is correctly equal to `<function constant at 0x7f13954ed5a0>`
- The key of my function `constant_initializer` is equal to `<class 'tensorflow.python.ops.init_ops_v2.Constant'>`

This looks weird, and maybe there's a name clash to resolve.
Following this theory, I tried to rename my function from `constant_initializer` to `randomname` so to understand if the name clash is the issue.

My test in `test_general_functions.py` became:
```
# randomname
@handle_frontend_test(
    fn_tree="tensorflow.randomname",
    all_args=_x_cast_dtype_shape(),
    test_with_out=st.just(False),
)
def test_tensorflow_randomname(
    *,
    all_args,
    on_device,
    backend_fw,
    fn_tree,
    frontend,
    test_flags,
):
    x_dtype, x, cast_dtype, to_shape = all_args
    helpers.test_frontend_function(
        input_dtypes=x_dtype,
        frontend=frontend,
        test_flags=test_flags,
        backend_to_test=backend_fw,
        fn_tree=fn_tree,
        on_device=on_device,
        value=x[0].tolist() if x[0].ndim > 0 else x[0].item(),
        dtype=cast_dtype,
        shape=to_shape,
    )
```

And the actual function in `general_functions.py`:
```
@handle_tf_dtype
def randomname(value, dtype=None, shape=None, name=None):
    #return EagerTensor(value)
    return constant(value, dtype, shape, name)
```

When I run the test I get:
```
>       frontend_ret = frontend_fw.__dict__[gt_fn_name](*args_frontend, **kwargs_frontend)
E       KeyError: 'randomname'
```

If I inspect `frontend_fw` there's constant correctly, but not randomname.

`ivy.functional.frontends.tensorflow.__init.py__` import all general functions, so I cannot understand why mine is missing.

Any ideas?

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @MaxFrax 
Thanks for the PR.
The constant initializer is not a EagerTensor but a constructor (class) that has a `__call__` method. So it takes a val and returns a constructor. This constructor (tf_init in the snippet below) can then be a given any shape or dtype and it wil turn that value into a tensor of that dtype and shape. 
Screenshot from 2024-02-29 10-23-59
Please let me know if something is unclear and pls make changes based on this and request a review when ready. Hope that helps :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
