### PR TITLE
Adds: torch frontend and backend support for Householder Product

### LINKED ISSUE #14971: householder_product

### PR DESCRIPTION
**Pull request by divyanshugit**
closes #14971

### CODE REVIEW

**Comment by Infrared1029** [comment]
Hey @divyanshugit, if a new function is introduced in the backends, it should be added to all backends, you should probably create two PRs, one for adding the function across the backends, and one for adding the frontend torch function.

**Comment by divyanshugit** [comment]
@Infrared1029 makes sense. I'll create another PR where I'll add the backend for all the other frameworks except torch. Would that be fine?

**Comment by Infrared1029** [comment]
> @Infrared1029 makes sense. I'll create another PR where I'll add the backend for all the other frameworks except torch. Would that be fine?

It would be better to have a designated PR for all the backend stuff, and another one for the frontend stuff, so two PRs:
PR -1- : Implements all the backend implementations of householder product on all frameworks and the associated test.
PR -2-: Implements the torch frontend function for householder products and the associated test. 

you should start with the first PR, you can modify the current PR to do that, revert the frontend implementation, and add the rest of the backend implementations.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
