### PR TITLE
`random` submodule fix

### PR DESCRIPTION
**Pull request by juliagsy**
a side note:
- as randomised values are returned, arrays are tested either on their range or types

one quick question on `multinomial`:
- as `probs` is the only array typed argument, and it is optional, should this method have array/container instances? I didn't implement them yet

please let me know if anything should be changed or improved! thanks!

### CODE REVIEW

**Review by djl11 — CHANGES_REQUESTED** [review]
great question with `multinomial`, I hadn't thought about this case. But yes, I think we should add it, with `self` occupying the `probs` argument in both cases. Thanks for checking!

**Comment by juliagsy** [comment]
Thanks for the review! I've added the instance methods accordingly! Requesting another review just in case there's other changes needed! Thank you!

**Review by djl11 — CHANGES_REQUESTED** [review]
`test_multinomial` should make use of `test_function` helper, currently we have the old legacy unit test implementation still in place.

**Review by djl11 — APPROVED** [review]
lgtm!

**Pull request merged**
