### PR TITLE
conj #12400 : Added conj function to numpy frontend

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Close #12400

**Comment by sreegandh804** [comment]
Hey @RakshitKumar04 ,
You seemed to have opened 4 issues(https://github.com/unifyai/ivy/issues/created_by/RakshitKumar04) for various functions at around the same time, you are only allowed to have 3 issues open at any time 😅 , you would need to get one of those PRs merged before you open another issue, and also could you please check the comment format for the issues here: https://github.com/unifyai/ivy/issues/1525 
Feel free to refer to the contributor's guide here [https://lets-unify.ai/ivy/contributing/the_basics.html#todo-list-issues]
Let me know if you have any further questions 😄

**Comment by RakshitKumar04** [comment]
> Hey @RakshitKumar04 , You seemed to have opened 4 issues(https://github.com/unifyai/ivy/issues/created_by/RakshitKumar04) for various functions at around the same time, you are only allowed to have 3 issues open at any time 😅 , you would need to get one of those PRs merged before you open another issue, and also could you please check the comment format for the issues here: #1525 Feel free to refer to the contributor's guide here [https://lets-unify.ai/ivy/contributing/the_basics.html#todo-list-issues] Let me know if you have any further questions 😄

Sorry for this, I know that I should raise only three issues at a time. Actually, the modf issue is not getting connected to the to-do list, so I thought there is something wrong with it hence I raised the fourth one.
Can you please guide which issues among conj #12404 or modf #12086 I should close?

**Comment by RakshitKumar04** [comment]
hey @Infrared1029 can you please help me in solving the intelligent-tests-pr error.

**Comment by RakshitKumar04** [comment]
Hey @Infrared1029 can you please review my PR.

**Pull request closed without merging**
