### PR TITLE
#16753 added bitwise_or method to paddle frontend

### LINKED ISSUE #16753: bitwise_or

### PR DESCRIPTION
**Pull request by mohithsarma**
close #16753

### CODE REVIEW

**Comment by mohithsarma** [comment]
Hi, The test is not successful in this 
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py::test_paddle_cumprod,tensorflow
This seems to be for a different method than what I added.

**Comment by aparajith21** [comment]
Hi! Thanks for contributing, could you please comment `add_frontend_checklist` and tick off the items there.

**Comment by mohithsarma** [comment]
add_frontend_checklist

**Comment by mohithsarma** [comment]
hey @aparajith21 i have checked the checklist.  let me know if there is any thing else thanks.

**Comment by aparajith21** [comment]
LGTM! Thanks for contributing!

**Pull request merged**
