### PR TITLE
frontends.tensorflow.convolution: initial commit

### LINKED ISSUE #7789: tensorflow.nn.convolution

### PR DESCRIPTION
**Pull request by hmahmood24**
Close #7789

Initiating this PR to prevent the attached issue from getting stale. The frontend tests for `frontends.functional.tensorflow.nn.convolution` are failing right now. However, I'll be working on resolving them within the next few days to get this PR merged as soon as possible. Apologies for any inconvenience,

### CODE REVIEW

**Comment by hmahmood24** [comment]
Hi @V-G-spec,

I have resolved the tests for `frontends.tensorflow.nn.convolution` now. Can you please review my PR :) Apologies for the delay and thanks for the patience.

**Comment by V-G-spec** [comment]
Thanks for your contribution @hmahmood24. However, there are still multiple test cases that aren't passing. Can you please look into those?

**Comment by hmahmood24** [comment]
Hi @V-G-spec,

I have gone through the test logs and there seems to be just one test case that failed for `tensorflow.nn.convolution` with a `jax` backend as shown below (The rest of the test logs don't concern my contribution):

image

In order to reproduce this I added `@reproduce_failure('6.55.0', b'AXicY2DABg5QzGQAALIZBIE=')` and ran the tests with a `jax` backend but the tests passed on my local machine without reproducing any errors as shown below:

image

**Comment by V-G-spec** [comment]
Sorry for the delay in response. Thank you for pointing out this issue to us. I will raise this internally. For now, you can try calling the tested function given the arguments of the failing example, and then debugging the function until this call returns the same result as the original framework. You can do so by overwriting the arguments that `@handle_test` passes to the test function

**Comment by hmahmood24** [comment]
Hi @V-G-spec,

Here you go:

image

The test passes as pointed out earlier as well, even after overwriting with the falsifying example explicitly. 🙂 I don't think the issue is with my function. The bug is somewhere with Hypothesis itself. Waiting for your review to move forward with this PR now.

**Comment by fspyridakos** [comment]
The error seems to be showing up in other tests in this module, most likely a systematic problem, I'll take a look into it eventually. Otherwise great PR! I'll go ahead and merge. Thanks for the contribution!

**Pull request merged**
