### PR TITLE
Add branch protection

### PR DESCRIPTION
**Pull request by sladyn98**
This PR introduces  a pre-receive hook designed  to enforce commit authorship rules. It checks every incoming commit in a push operation to see if the author matches the specified user ("vedpatwardhan"). If a commit is found authored by a different user, it rejects the entire push and outputs an error message specifying the unauthorized commit and its author. This ensures that only commits authored by the specified user are accepted in the push.

Steps to get this to run

- In the GitHub Enterprise web interface, go to your repository, click on "Settings", then click on "Pre-receive hooks".
-  Click on "New pre-receive hook".
- In the "Name" field, enter a name for the hook. In the "Script" field, paste the contents of the pre-receive file. In the "Enforcement" section, select whether you want the hook to be enforced or non-enforced.
-  Click "Create".

### CODE REVIEW

**Comment by sladyn98** [comment]
@Daniel4078

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
I think we could explore if there's a way to add a `pre-receive` hook to handle this instead, based on the suggestion [here](https://stackoverflow.com/a/72133698). 
Thanks for looking into this @sladyn98 💪

**Review by vedpatwardhan — COMMENTED** [review]
Hey @sladyn98, thanks for looking into the changes required for adding a `pre-receive` hook 🚀 
However the hook you're adding would restrict everyone except one from commiting to master altogether 😅
The goal of our `pre-receive` hook is to only restrict branch creation on the main repo for everyone else for now. Happy to clarify further if required 🙂

**Comment by sladyn98** [comment]
I see, thanks for the clarification. However, there's an inherent difficulty in Git because branches themselves don't contain information about who created them. A branch is just a lightweight movable pointer to a commit.We can use GitHub's protected branches feature. We can protect the main branch, and then specify who is allowed to push to it.

**Comment by vedpatwardhan** [comment]
> @vedpatwardhan I see, thanks for the clarification. However, there's an inherent difficulty in Git because branches themselves don't contain information about who created them. A branch is just a lightweight movable pointer to a commit.We can use GitHub's protected branches feature. We can protect the main branch, and then specify who is allowed to push to it, for that I would need extra permissions.

Hey @sladyn98, thanks for diving into this further! However, I don't think we should add protections to the main branch, the idea is simply to have a workflow to avoid cluttering the main repo with too many branches 😅
Also, I think there could be some way to retrieve the author of a particular branch, given that the same is displayed on the [branches page](https://github.com/unifyai/ivy/branches) too 😄

**Comment by sladyn98** [comment]
Thanks @vedpatwardhan for the suggestions. I understand your concerns, but as previously mentioned, in Git, a branch is merely a pointer to a specific commit and it doesn't carry information about who created it. The information you see on GitHub's branch page (i.e., "Your branches"/"Active branches") does not actually represent the creator of the branch. It represents the author of the latest commit on that branch.

**Comment by vedpatwardhan** [comment]
> Thanks @vedpatwardhan for the suggestions. I understand your concerns, but as previously mentioned, in Git, a branch is merely a pointer to a specific commit and it doesn't carry information about who created it. The information you see on GitHub's branch page (i.e., "Your branches"/"Active branches") does not actually represent the creator of the branch. It represents the author of the latest commit on that branch.

Yeah you're right, it specifies the person with the last commit instead of the author, sorry about that! 
ig in that case, the only way to deal with this is to disable commits to all other branch names other than the ones already created using an appropriate branch name pattern, and then having to update the rule everytime a new branch is created to allow commits to that branch. 
Happy to know your thoughts if there are other simpler solutions to deal with this, because what I'm suggesting is certainly infeasible 😅
Thanks for putting in the efforts @sladyn98 😄💪

**Comment by sladyn98** [comment]
Hey @vedpatwardhan thanks for the feedback, the method you're suggesting can work but it's not very easy. First, it requires a lot of work to keep changing the rules every time a new branch pops up, especially for projects that are always creating new branches. Second, people make mistakes, and even a small error in updating these rules could either block a branch we need or allow one we don't want.

**Comment by vedpatwardhan** [comment]
> Hey @vedpatwardhan thanks for the feedback, the method you're suggesting can work but it's not very easy. First, it requires a lot of work to keep changing the rules every time a new branch pops up, especially for projects that are always creating new branches. Second, people make mistakes, and even a small error in updating these rules could either block a branch we need or allow one we don't want.

Hey @sladyn98, yeah exactly! I can't really think of another approach atm for the reasons we've discussed above, probably @RashulChutani could help out here. Thanks 😄

**Comment by vedpatwardhan** [comment]
> Hey @sladyn98, If I remember correctly in our last attempt in this enforcement, our issue was that we don't have GitHub enterprise subscription (correct me if I'm wrong on that @vedpatwardhan). Other than that, what rules are we looking to enforce? I presume linting rules for now right?

Actually the goal then was different (ig it was about not allowing direct commits to files with codeowners), this time we just want to restrict branch creation on the repo, to avoid cluttering it too much 😅

**Comment by KareemMAX** [comment]
> Actually the goal then was different (ig it was about not allowing direct commits to files with codeowners), this time we just want to restrict branch creation on the repo, to avoid cluttering it too much 😅

Makes sense @vedpatwardhan, first of all really sorry for the late reply.

I'm not really aware how to code will function, but I would say we work for now on a private repo (which @sladyn98 can get admin access on to fully control that repo). If the tests proved successful we can deploy it here.

**Comment by vedpatwardhan** [comment]
> > Actually the goal then was different (ig it was about not allowing direct commits to files with codeowners), this time we just want to restrict branch creation on the repo, to avoid cluttering it too much 😅
> 
> Makes sense @vedpatwardhan, first of all really sorry for the late reply.
> 
> I'm not really aware how to code will function, but I would say we work for now on a private repo (which @sladyn98 can get admin access on to fully control that repo). If the tests proved successful we can deploy it here.

Sounds good to me, feel free to make a start with the private repo. Thanks @KareemMAX @sladyn98 😄

**Comment by sladyn98** [comment]
Let me know I could start with the private repo, would love to start on it.

**Comment by KareemMAX** [comment]
> Let me know I could start with the private repo, would love to start on it.

Yes please, feel free to share the results with me and Ved. And it would be better if it was a unifyai repo instead of creating a personal one so you have access to our GitHub enterprise plan

**Comment by sladyn98** [comment]
@KareemMAX From whom do I get access for this

**Comment by KareemMAX** [comment]
@sladyn98 I guess you already have access to create new repos

**Comment by KareemMAX** [comment]
@sladyn98 I guess you already have access to create new repos

**Comment by vedpatwardhan** [comment]
let me know the name of the repo, I'll create it and share it with you guys, thanks @sladyn98 @KareemMAX 😄

**Comment by sladyn98** [comment]
@KareemMAX @vedpatwardhan https://github.com/unifyai/test-branch-protection Created a repo and added branch protection action. Do let me know what you guys think

**Comment by vedpatwardhan** [comment]
Thanks for getting this done @sladyn98, looks great to me. Let's see what @KareemMAX thinks (ofc I couldn't test it out if others aren't allowed to create branches on that repo but ig you've done that already) 😄🚀

**Comment by KareemMAX** [comment]
Hey @sladyn98, I guess you didn't give me access to the repo. Do you mind giving me and @vedpatwardhan Admin access to test things out?

**Comment by vedpatwardhan** [comment]
> Hey @sladyn98, I guess you didn't give me access to the repo. Do you mind giving me and @vedpatwardhan Admin access to test things out?

Ah yeah makes sense! I already have access, @sladyn98 could you please add @KareemMAX? Thanks 😄

**Comment by KareemMAX** [comment]
Also @vedpatwardhan, can you try creating a new branch from your side? Just to confirm that you are excluded from the protection rule

**Comment by vedpatwardhan** [comment]
> Also @vedpatwardhan, can you try creating a new branch from your side? Just to confirm that you are excluded from the protection rule

yep, just managed to create a `test_branch` on the repo, seems to work perfectly 😄

**Comment by sladyn98** [comment]
@vedpatwardhan @KareemMAX Given permission

**Comment by sladyn98** [comment]
@KareemMAX The action just fails the PR it does not, stop you from merging

**Comment by KareemMAX** [comment]
> @KareemMAX The action just fails the PR it does not, stop you from merging

I guess I got confused here, wasn't the goal of this hook it to prevent creation of new branchs? @vedpatwardhan @sladyn98

**Comment by vedpatwardhan** [comment]
> > @KareemMAX The action just fails the PR it does not, stop you from merging
> 
> I guess I got confused here, wasn't the goal of this hook it to prevent creation of new branchs? @vedpatwardhan @sladyn98

Yep the initial goal was to prevent creation of new branches on the `ivy` repo except for a few users to avoid clutter, but I'd suggest going through the conversation in the PR, probably there's some issues where you could help out. Thanks @KareemMAX 😄

**Comment by KareemMAX** [comment]
@vedpatwardhan I guess I need to do that, replying one reply a day is not helping 😅. Just to confirm, is that still the intent of this PR? 

And @sladyn98 can you message me privately when can we meet? (Maybe in UTC)

**Comment by sladyn98** [comment]
@KareemMAX Messaged. Do let me know if you any help in getting this PR over the line

**Comment by KareemMAX** [comment]
Hey @sladyn98,
Sadly I'll be closing this PR as it has been stale for a very long time. Feel free to reopen it if you wish to continue working on it.

cc: @vedpatwardhan

**Pull request closed without merging**
