### PR TITLE
logical_not

### LINKED ISSUE #14093: logical_not

### PR DESCRIPTION
**Pull request by Emanuele-n**
closed #14093

### CODE REVIEW

**Comment by Emanuele-n** [comment]
Hi @YushaArif99, I see that recently all the new functions are getting the error on "lint / check-formatting", does this mean that mine is ok as well?
Please let me know if there is something else I have to modify, thank you

**Comment by Emanuele-n** [comment]
@YushaArif99 any news?

**Review by YushaArif99 — APPROVED** [review]

**Comment by YushaArif99** [comment]
Hi @Emanuele-n.

Extremely sorry for the late review. I was quite swamped with work recently due and thus reviewing this PR totally slipped under my radar. No need to worry about linting errors. 
The changes look good to me and I'll therefore be merging this PR. Thanks, a lot for the contribution! 🙂

**Comment by Emanuele-n** [comment]
No worries! Thanks a lot for the merge! @YushaArif99

**Pull request merged**
