### PR TITLE
added lognormal and logistic function to numpy frontend

### PR DESCRIPTION
**Pull request by ratulMahjabin**

### CODE REVIEW

**Comment by ratulMahjabin** [comment]
close #14586

**Comment by ratulMahjabin** [comment]
close #14589

**Comment by valeriocost** [comment]
Hi @ratulMahjabin, I'm not sure if tests for your functions are failing. Are you able to run the test locally? What is the output? Thanks

**Comment by ratulMahjabin** [comment]
> Hi @ratulMahjabin, I'm not sure if tests for your functions are failing. Are you able to run the test locally? What is the output? Thanks

Hello @valeriocost test for `lognormal` is passing but the test for logistic is failing. I tried to debug test for logistic with different parameters. I have attached ss for the reference.

image
image

**Comment by ratulMahjabin** [comment]
@valeriocost 
output for test for `logistic`:

`AssertionError:  the results from backend numpy and ground truth framework numpy do not match
E            [[0.19587791 0.92072284]
E            [0.41699258 0.1800173 ]]!=[[-0.30778782  0.60103959]
E            [-0.25096005  2.10898075]] `

**Review by ratulMahjabin — COMMENTED** [review]
- lognormal function + test works fine
- logistic test fails.

please review the codes and provide suggestion

**Pull request closed without merging**
