### PR TITLE
add gamma implementation to paddle backend

### LINKED ISSUE #19079: gamma

### PR DESCRIPTION
**Pull request by gabryellesoares**
close #19079

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by gabryellesoares** [comment]
@MahmoudAshraf97 could you please review this pr?

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
Hi @gabryellesoares 
can you please have a look, why tests are failing. let me know if they are passing locally.
Thanks!

**Comment by gabryellesoares** [comment]
@abdulasiraj i saw that some tests are failing on master, so I didn't know if the failing tests are because of my changes. How do I check this?

**Comment by abdulasiraj** [comment]
Let me check it for you.

**Comment by abdulasiraj** [comment]
Please update your branch with current master branch, than it's to review.

**Comment by gabryellesoares** [comment]
@abdulasiraj i did it

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
Hi @gabryellesoares 
The functions you're using from Ivy doesn't exists. Please implement it in some other way 
```
E   ivy.utils.exceptions.IvyAttributeError: paddle: gamma: module 'ivy.functional.backends.paddle.random' has no attribute 'gamma'
E   Falsifying example: test_numpy_gamma(
E       frontend='numpy',
E       on_device='cpu',
E       input_dtypes=['float16'],
E       shape=1.0,
E       scale=1.0,
E       size=(2, 2),
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=0,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=False,
E       ),
E       fn_tree='ivy.functional.frontends.numpy.random.gamma',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.0', b'AXicY2CAA0ZMJgAAOQAD') as a decorator on your test case
```

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
