### PR TITLE
updated compress function of jax

### PR DESCRIPTION
**Pull request by ShreyanshBardia**
@AnnaTz can you take a look at this, related to https://github.com/unifyai/ivy/pull/18334#issuecomment-1631990264

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by AnnaTz** [comment]
Hi @Ookamice, this looks good but there are conflicts. Kindly resolve those so we can merge.

**Comment by Ookamice** [comment]
@ShreyanshBardia 
Hiya, I'm a little lost in your braches and forks 😅 
If you could help resolve the conflicts, that would be great 🚀

**Comment by AnnaTz** [comment]
Web "Resolve conflicts" doesn't work when the conflicts are complex, so you have to do this manually.
1. Go to your master on github and click `Sync fork`
2. Using the command line on you master do `git pull`
3. Checkout to your branch jax-numpy-compress and do `git merge master`
4. If you get conflicts, resolve them manually

**Comment by ShreyanshBardia** [comment]
Hi, thanks for the guide! I hope this is fine now.

**Comment by Ookamice** [comment]
Awesome! 👍

**Pull request merged**
