### PR TITLE
Add MatrixSolve to raw_ops

### LINKED ISSUE #5474: MatrixSolve

### PR DESCRIPTION
**Pull request by KareemMAX**
Close #5474
Based on #6243

### CODE REVIEW

**Comment by CatB1t** [comment]
Hello @KareemMAX, can you address one task per PR please? seems like you've added multiple changes other than `MatrixSolve`.

**Comment by KareemMAX** [comment]
Yup, I wrote that it's based on https://github.com/unifyai/ivy/pull/6243. So it still shows its diff. Once you merge https://github.com/unifyai/ivy/pull/6243 it will be one change

**Comment by CatB1t** [comment]
Aha okay, I'll get #6243 reviewed later today!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
