### PR TITLE
EHN: asin added in paddle.tensor.tensor.Tensor class, from issue asin #16043  and form list of function #15115

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
I have added asin function it might conflict with PR #16040

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@MuhammadNizamani I think it would be unsupported dtypes.

**Comment by MuhammadNizamani** [comment]
@soma2000-lang I was bit confuse about it so I checked file `paddle.tensor.tensor.math.py `  it has same method and it was using supported so I followed it because it was marge in main branch. Can you explain why it should unsupported in `paddle.tensor.tensor.Tensor`  but not in `paddle.tensor.tensor.Tensor`? 
Thanks for review.

**Comment by soma2000-lang** [comment]
@MuhammadNizamani thanks for pointing out ,I will look into this,there might be some mistake. I think can you modify that to unsupported dtypes ?

**Comment by MuhammadNizamani** [comment]
@soma2000-lang  I will modify this to unsupported dtypes. just so know sqrt, log_softmax and asin these are the method that uses supported in `paddle.tensor.tensor.math.py`.

**Comment by soma2000-lang** [comment]
@MuhammadNizamani thanks for pointing out .After digging into this I found out that it will be supported only.I will be merging this.
Thanks for contributing😊

**Pull request merged**
