### PR TITLE
Added reciprocal_ method in the PyTorch frontend

### PR DESCRIPTION
**Pull request by he11owthere**
closes https://github.com/unifyai/ivy/issues/22035

image

### CODE REVIEW

**Comment by he11owthere** [comment]
@Ookamice please remove "bfloat16" from the `with_supported_dtypes` decorator before running the tests until the issue with `ivy.Array.repr` method has been fixed as mentioned by Ved in https://github.com/unifyai/ivy/pull/21447. Thank you! 🙂

**Comment by Ookamice** [comment]
@he11owthere 
Hiya, thanks for the PR. From reading the PyTorch documentation, it appears that integer types should also be supported for [reciprocal](https://pytorch.org/docs/stable/generated/torch.reciprocal.html). Please could you add these to the function decorator

**Comment by he11owthere** [comment]
@Ookamice, I've noticed that PyTorch's `reciprocal` method doesn't seem to support integers, contrary to what's stated in the documentation. When I provide integer inputs, I encounter an error message: `result type Float can't be cast to the desired output type Int.` If there's something I'm missing or if there's a recommended approach to handle this, I'd greatly appreciate your insights. Thank you for your time and assistance!

**Comment by Ookamice** [comment]
@he11owthere 
No worries then, I suspect this is more to do with Ivy's wrapping where there is some implicit conversion of the output back to the input dtype. Hence why the error is about going from float to int.

**Pull request merged**
