### PR TITLE
boolean_mask #9684

### PR DESCRIPTION
**Pull request by abhisharsinha**
Added `boolean_mask` function in tensorflow frontend general_functions.  #9684

### CODE REVIEW

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Just need to resolve conflicts with this PR, implementation looks good just need to check through test logs after conflicts have been resolved :)

**Comment by abhisharsinha** [comment]
Hi @jkeane508, thanks for reviewing, I've resolved the conflict. Please have a look.

**Review by jkeane508 — COMMENTED** [review]
Just re-running tests, will check back when they've finished :)

**Review by jkeane508 — APPROVED** [review]
Looks good to me, once you get a chance to resolve conflicts will go ahead and merge :)

Thanks!

**Pull request merged**
