### PR TITLE
add adaptive_max_pool1d#20213

### PR DESCRIPTION
**Pull request by nyomangedar**
https://github.com/unifyai/ivy/issues/20213

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by nyomangedar** [comment]
@MahmoudAshraf97 hi I don't really get it with the error in the check formatting step, can you help me solve the issue?

**Review by AryanSharma21 — COMMENTED** [review]
Hello @nyomangedar , as you have added the implementation , please also add the corresponding test function to test and complete this PR

**Comment by nyomangedar** [comment]
Thank you for the response @AryanSharma21, is there any guidelines that I can follow to create the test?

**Comment by AryanSharma21** [comment]
Yes @nyomangedar , you can read about the test cases in the documentations itself 

https://unify.ai/docs/ivy/docs/ivy_tests.test_ivy.helpers.html 

Also you can ask the team in discord channel as well. Feel free to ask question if you need help thanks !

**Comment by AryanSharma21** [comment]
Hello  @nyomangedar , I see in the implementation you have returned avg pool instead of max pool but it is a completely different function. 
You can read about functions in the documentations 
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/avg_pool1d_en.html

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/MaxPool1D_en.html#:~:text=MaxPool1D%C2%B6&text=This%20operation%20applies%201D%20max,the%20length%20of%20the%20feature.

Also , in the test case you should use valid data types instead of float to make sure that you don't get any error related to data types.

**Comment by nyomangedar** [comment]
> Hello @nyomangedar , I see in the implementation you have returned avg pool instead of max pool but it is a completely different function. You can read about functions in the documentations https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/avg_pool1d_en.html
> 
> https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/MaxPool1D_en.html#:~:text=MaxPool1D%C2%B6&text=This%20operation%20applies%201D%20max,the%20length%20of%20the%20feature.
> 
> Also , in the test case you should use valid data types instead of float to make sure that you don't get any error related to data types.

Hi @AryanSharma21, sorry if there any mistakes as stated in the title of the issue that I raised,  I think what I should implement is the adaptive max pool 1d function(https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/AdaptiveMaxPool1D_en.html#adaptivemaxpool1d) instead of max pool 1d that you mentioned above. CMIIW.

For the data types is it better for me to use the helpers.arrays_for_pooling function?

Thank you!

**Comment by AlexandraPosta** [comment]
Hello @nyomangedar! Great work so far! Would you be able to check your missing keyword-only arguments in the test file? 

```
TypeError: test_frontend_function() missing 2 required keyword-only arguments: 'input_dtypes' and 'backend_to_test'
```

**Comment by AlexandraPosta** [comment]
Hello @nyomangedar! Did you get a chance to look at those missing arguments?

**Pull request closed without merging**
