### PR TITLE
Add identity function to tensor flow frontend

### LINKED ISSUE #7605: identity

### PR DESCRIPTION
**Pull request by DPLATA**
Close #7605

### CODE REVIEW

**Comment by DPLATA** [comment]
This PR will introduce identity function General Functions of TensorFlow frontend and add the correspondent alias in RawOps.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by DPLATA** [comment]
@Ishticode putting up this comment because PR went stale. Kindly review this PR please

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @DPLATA 
Thank you so much for this PR. Terribly sorry for the delay as I was mostly off for this past week and this clearly went under the radar.

Your PR looks great and nearly ready to be merged. Could you resolve the minor conflict and check to see if you can fix the import error in raw_ops that is leading to failure for `test_trensorflow_identity`.

I will keep your PR on highest priority and try to merge asap. Feel free to ask a question if something doesn't make sense above. Thanks 🙂.

**Comment by DPLATA** [comment]
@Ishticode I updated the P please let me know if circular import error and merge conflict were resolved as expected.

**Review by Ishticode — APPROVED** [review]
Looking great @DPLATA 
The CI just cancels the test so i've checked locally and the test for identity as well as the raw ops Identity both pass. There was a minor conflict again which i resolved anyway.

I will get this merged. Thanks a lot for your contribution. 🙂

**Comment by DPLATA** [comment]
Thank you for reviewing @Ishticode !

**Pull request merged**
