### PR TITLE
softplus commit

### PR DESCRIPTION
**Pull request by luizgubarichello**
Close https://github.com/unifyai/ivy/issues/15949

### CODE REVIEW

**Comment by luizgubarichello** [comment]
Close #15949

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
please use `ivy.softplus`
and write the tests for the function

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
