### PR TITLE
Pytorch Frontend: log

### PR DESCRIPTION
**Pull request by gary30404**
This PR adds the log function to the Pytorch Frontend, related to the issue #2582.

### CODE REVIEW

**Comment by Auxia** [comment]
Hi @gary30404! Thanks for contributing to Ivy 😄 
I see that the lint checks are failing. I'd like to know if you have installed the [pre-commit](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit) hook. This will reformat the the code at the time of committing to fix lint errors, or atleast help you fix the more complicated ones.

If you have any questions that are not covered by the contributing guide then please let me know!

**Comment by gary30404** [comment]
Hi, @Auxia 
Thanks for the reminder. I've followed the link and finished the checks. Is the current status accepted?

**Comment by Auxia** [comment]
I think you may have committed more files than the ones you were meaning to. There are some files which are not relevant to your task. I would suggest reseting the commit and pushing only the files you have made edit to concerning the task.

Additionally, the numpy and tensorflow tests are failing. You might want to check if your test function has any bugs.

**Comment by gary30404** [comment]
Hi, @Auxia 
Thanks for the suggestion. I've updated the codes and committed new version. Some of the checks (Numpy) still failed but I did not modify from the origin.

**Comment by Auxia** [comment]
Everything seems to be fine except for the fact that you have removed the test function for `cos`. I would request you to put the `test_cos` function  back in and then we should be good to merge.

**Pull request closed without merging**
