### PR TITLE
nanmean implementation and test for jax frontend

### LINKED ISSUE #11739: nanmean

### PR DESCRIPTION
**Pull request by Lexticc**
close #11739

### CODE REVIEW

**Comment by Lexticc** [comment]
this pr is continuation of pr  #11972 reviewed by @Infrared1029 . would you please assign yourself to it to continue what we started in pr  #11972 with @Infrared1029

**Comment by Lexticc** [comment]
@Infrared1029 , I have changed the code  handling where argument
the new concept of where handling is to convert all elements of array a that are not included in the calculation of the mean to nan before passing array a to nanmean function and in this way only selected elements in where arguments would be included in the calculation of the mean

**Comment by Lexticc** [comment]
@Infrared1029 , if you want you can see the old code before the changes in #11822

thank you

**Comment by Lexticc** [comment]
@Infrared1029 , the pr showed conflict that needed to be resolved. I did my best to resolve it and I hope I did it right this time 

thank you for you patience with me

**Comment by Lexticc** [comment]
@Infrared1029 , today new conflicts arised again for the second time since I opened this PR, my part of the code is perfectly resolved ok but other contributors part of the code i just rearranged it as  it was marked in the files to be resolved 
I hope I did this right
Please I am waiting for your comments

**Comment by Infrared1029** [comment]
sorry for the late response as lots of PR are being submitted lately, i'll take a look now.

**Comment by Infrared1029** [comment]
The tests seem to fail @Lexticc, with a quick look, I can see the inclusion of the `out` argument in the test, it is important to note that jax does not support the `out` argument, it is just an artifact of copying numpy's docstrings and api, but it should not be used. There could be other issues, make sure the tests are passing, if the tests still fail, try to resolve the issues, if you still can't, let me know and I will look into it!

**Comment by Infrared1029** [comment]
Also a side note, the test function should be named `test_jax_numpy_nanmean`

**Pull request closed without merging**
