### PR TITLE
added dropout3d function and test for PaddlePaddle frontend

### LINKED ISSUE #18182: dropout3d

### PR DESCRIPTION
**Pull request by sachelsout**
Close #18182

### CODE REVIEW

**Comment by sachelsout** [comment]
All the test cases passing locally for dropout3d function !! 😄 

image

**Comment by sachelsout** [comment]
Hi @danielmunioz , could you please review my PR ? 😃

**Comment by danielmunioz** [comment]
Hey! @sachelsout! Thanks for contributing!!

Similar to the other one, The PR looks good but the tests seems to be failing on numpy, torch and paddle backends, locally at least 🤔, could you please fix the merge conflicts and confirm if the tests are passing again?

Thanks!

**Comment by sachelsout** [comment]
> Hey! @sachelsout! Thanks for contributing!!
> 
> The PR looks good but the tests seems to be failing on numpy, torch and paddle backends, locally at least 🤔, could you please fix the merge conflicts and confirm if the tests are passing again?
> 
> Thanks!

Hi @danielmunioz , I fixed the merge conflicts but after merging the base branch into my branch, the tests are failing, as you have mentioned. But the tests were passing successfully before, as seen in the screenshot I've uploaded.

I've followed the official PaddlePaddle docs for implementing dropout3d function and relevant test function. The tests are failing due to AssertionError, but I've written correct code for dropout3d.

Could you please guide me where am I going wrong. My guess is, there might have been some changes in the backend of these frameworks, which is leading to this error.

**Comment by danielmunioz** [comment]
Hey @sachelsout, it seems that there are still some merge errors popping up, and yeah the paddle test seems to be failing due to an assertion error, the results from the paddle library do not match with the results of the frontend implementation, the other but the other ones seem to be an hypothesis error, I'll take a look at those, and I'll get back to you, could you check the assertion one (find what's different) and the merge error please?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by sachelsout** [comment]
Hi @danielmunioz , apologies for the delay ! I resolved merge conflicts, updated the paddle to 2.5.1 in function definition for dropout3d, made relevant changes in the test function as well. All the test cases are passing locally.

image

**Comment by danielmunioz** [comment]
Hey @sachelsout! Thanks for fixing the issues!

Yeah, all test seem to be passing locally
LGTM, Merging now!

Thanks for contributing!

**Comment by sachelsout** [comment]
Hi @danielmunioz , thank you for your guidance and review throughout the issue !! ❤️

**Pull request merged**
