### PR TITLE
Reformat float_img_to_uint8_img

### PR DESCRIPTION
**Pull request by varsharoshan**
#867 
Passed all tests

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Thanks for making the changes 🙂 Could you take a deeper look at your example, the one you gave produces failures

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Again, you need to give some more thought to your example. The issue wasn't the `ivy.array` part, it's that if you try and run the code you've given, it fails.

**Comment by mattbarrett98** [comment]
In particular, it is failing for NumPy and jax. Also, the output when running the code with torch is `ivy.array([[  0,   0,   0,   0],
       [  0,   0,   0,  63],
       [156, 196,   0,  63],
       [  0,   0, 128,  63]])`. You can run your examples on your machine to verify that they are actually doing what you think they are.

**Comment by juliagsy** [comment]
Hey there! As this PR is inactive for more than 7 days, it will be closed in 24 hours if there are no further response. Thank you!

**Comment by juliagsy** [comment]
Closing due to inactivity

**Pull request closed without merging**
