### PR TITLE
"Add 'create_rng_state' function for random number generation"

### LINKED ISSUE #19567: create_rng_state

### PR DESCRIPTION
**Pull request by EllCoe**
Close #19567 

This pull request adds the 'create_rng_state' function to Ivy's TensorFlow frontend, allowing users to create an RNG state from an integer seed. The RNG state is represented as a 1-D Ivy array with the seed value and a fixed second element set to 0.

This addition enhances the library's functionality, providing users with a convenient method for managing RNG states during random number generation.

Your feedback and suggestions for improvement are welcome.

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by theRealBird — CHANGES_REQUESTED** [review]
Hi @EllCoe, thank you so much for contributing to Ivy!

For the create_rng state function's current implementation, currently we are not incorporating the `algorithm` kwarg in our results. If I am not wrong TF supports Philox and Threefry. 

I suggest we explore ways to incorporate this as well. Thanks!

**Comment by EllCoe** [comment]
Hi @theRealBird, Thank you for the insightful review and suggestions. I've incorporated the Philox and Threefry algorithms into the create_rng_state function as you recommended. Please have a look, and let me know if there are any further adjustments or improvements needed.

Thanks again for guiding me through this!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by bipinKrishnan** [comment]
Hey @EllCoe, since this is a new function that is being added, you should include a test case for this.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
