### PR TITLE
Added trunc and fix instance method to torch frontend

### LINKED ISSUE #14302: trunc

### LINKED ISSUE #14303: trunc_

### LINKED ISSUE #14304: fix

### LINKED ISSUE #14305: fix_

### PR DESCRIPTION
**Pull request by binh234**
close #14302 
close #14303
close #14304
close #14305

### CODE REVIEW

**Comment by binh234** [comment]
@RickSanchezStoic can you take a look at this

**Comment by RickSanchezStoic** [comment]
@RashulChutani seems like the tests aren't picking up. Will they need to re-create the pr? Thanks!

**Comment by RashulChutani** [comment]
Hi @RickSanchezStoic Yeah I am checking this. I will let you know ASAP. Thanks

**Comment by RashulChutani** [comment]
Hi @RickSanchezStoic, Yes, the tests are not being picked due to the paddle issue, that Ved solved after the PR was created. Hence, the contributor will have to create a new PR. Thanks.

**Pull request closed without merging**
