### PR TITLE
Closes Bessel_i0 for tf.frontend.math

### LINKED ISSUE #21111: Bessel_i0

### PR DESCRIPTION
**Pull request by Enigmafiend**
Close #21111

### CODE REVIEW

**Comment by Enigmafiend** [comment]
ivy-gardener

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @Enigmafiend 

Apologies for the delay in the review. Have been quite swamped with work recently and havent had the time to review any PRs 😓 


Regarding the PR itself, the tests for `bessel_i0` are failing for the `JAX` backend with a `KeyError: cpu` [here](https://github.com/unifyai/ivy/actions/runs/5721440642/job/15503034091?pr=21122#step:3:1999).
Could you kindly look into it and try resolving it? Also, could you kindly resolve the merge conflicts? 
Feel free to ping me once the tests are all passing. Thanks! 🙂

**Comment by YushaArif99** [comment]
Any updates on this PR @Enigmafiend 🙂?

**Comment by Enigmafiend** [comment]
> Any updates on this PR @Enigmafiend 🙂?

Yes the test faliure seems to be a bug on the ivy test side as the code seems to behave normally and as expected when run manually

**Comment by Enigmafiend** [comment]
again a trivial conflict, could you resolve this manually

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @Enigmafiend 

Seems like you have made quite a lot of unwanted changes as a result of resolving the merge conflicts 😅.

Kindly revert back the commits that resulted in these changes (using `git revert <commit hash>`. This will generate a new commit that reverts the changes of the <commit hash> commit. You can then do the usual `git add` -> `git commit` -> `git push` to push this new commit to the PR. 

As for the merge conflicts, you can manually resolve the conflicts using the following steps:
- simply copy and paste your changes into a separate .txt file. 
- Then copy over the changes from the main branch (for that given file). 
- Once that's done, you can then append your changes at the bottom

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
