### PR TITLE
Added jax_numpy_zeros and test.

### LINKED ISSUE #5630: zeros

### PR DESCRIPTION
**Pull request by samuelbido**
resolves #5630

### CODE REVIEW

**Comment by JerryGCDing** [comment]
Hi @samuelbido, thank you for contributing to Ivy😃! Can you refactor the test to utilize the `with_out` and `as_variable` arguments returned by the `@given` decorator, the example can be found on `test_jax_numpy_namespace_functions.py - LINE 922`. Anything else in your PR looks perfectly fine!

**Comment by samuelbido** [comment]
The requested changes are pushed.

**Comment by JerryGCDing** [comment]
Great! Can you link the PR to its corresponding issue in the `Development` tab on the right, then I'll go ahead and merge it 🎉

**Comment by samuelbido** [comment]
Linked!

**Pull request merged**
