### PR TITLE
Tanhshrink

### LINKED ISSUE #23689: tanhshrink

### PR DESCRIPTION
**Pull request by samthakur587**
# Implementation of tanhshrink to ivy experimental.

## in this i have taken the reference from pytorch to implement the tanhshrink. which is defined as f(x) = x - tanh(x). and its passing all test with 100 example in all backend. 

image

Close #23689

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by samthakur587** [comment]
Hi! @jieunboy0516 i have checked everything is good passing all the test and can check and merge it. So i can move forward to the next task. 🚀 

thanks 
sam

**Comment by Aaryan562** [comment]
@samthakur587 Hey I have one doubt, the docstring in ivy/data_classes/array/experimental/activations.py, you defined it yourself in your own words or you copied from somewhere??

**Comment by samthakur587** [comment]
> @samthakur587 Hey I have one doubt, the docstring in ivy/data_classes/array/experimental/activations.py, you defined it yourself in your own words or you copied from somewhere??

Not all from my self but i have taken the same format as in the existing function any modified according to the my function with the Example i have tested on my own. you can take the any example you want but the input , outout , and the parameter should be included in the docstring. if any thing you made wrong don't worry your review give the instruction what should you add according to your function.

Thanks

**Comment by Aaryan562** [comment]
> > @samthakur587 Hey I have one doubt, the docstring in ivy/data_classes/array/experimental/activations.py, you defined it yourself in your own words or you copied from somewhere??
> 
> Not all from my self but i have taken the same format as in the existing function any modified according to the my function with the Example i have tested on my own. you can take the any example you want but the input , outout , and the parameter should be included in the docstring. if any thing you made wrong don't worry your review give the instruction what should you add according to your function.
> 
> Thanks
Okay understood, but what if I want to implement nanmin function given in https://github.com/unifyai/ivy/issues/3856 but however there is no ivy.nanmin exists and also there is no documentation of nanmin in Ivy docs. So how to go about implementing it? How would I get to know how that function works!

**Comment by Aaryan562** [comment]
@samthakur587

**Comment by jieunboy0516** [comment]
Hi @samthakur587 , sorry for the late reply.  Your code looks good! Thanks a lot for your contribution!

**Pull request merged**
