### PR TITLE
Added paddle.tensor.linalg dist

### LINKED ISSUE #19355: dist

### PR DESCRIPTION
**Pull request by Ashwani132003**
Close #19355

### CODE REVIEW

**Comment by MuhammadSaeedBatikh** [comment]
Hi @Ashwani132003, thanks for the PR.

There's a mismatch between your implementation's returned shape and ground-truth returned shape for all backends.
```
E               AssertionError: returned shape = (), ground-truth returned shape = (1,)
E               Falsifying example: test_paddle_dist(
E                   dtype_and_input=(['float32', 'float32'],
E                    [array(-1., dtype=float32), array(-1., dtype=float32)]),
E                   p=1.0,
E                   test_flags=FrontendFunctionTestFlags(
E                       num_positional_args=0,
E                       with_out=False,
E                       inplace=False,
E                       as_variable=[False],
E                       native_arrays=[False],
E                       generate_frontend_arrays=False,
E                   ),
E                   fn_tree='ivy.functional.frontends.paddle.dist',
E                   on_device='cpu',
E                   frontend='paddle',
E               )
E               
```
It seems `paddle.dist` always returns `shape=[1]`, while `ivy.vector_norm` returns a scalar as shown by the following example:
```
import paddle
x = paddle.to_tensor([-1.0])
y = paddle.to_tensor([1.0])
print(paddle.dist(x,y,2).shape)
>>> [1]
```

You may change it to the following:
```
def dist(x, y, p=2):
    ret = ivy.vector_norm(ivy.subtract(x, y), ord=p)
    return ivy.reshape(ret, (1,))
```

**Comment by Ashwani132003** [comment]
> Hi @Ashwani132003, thanks for the PR.
> 
> There's a mismatch between your implementation's returned shape and ground-truth returned shape for all backends.
> 
> ```
> E               AssertionError: returned shape = (), ground-truth returned shape = (1,)
> E               Falsifying example: test_paddle_dist(
> E                   dtype_and_input=(['float32', 'float32'],
> E                    [array(-1., dtype=float32), array(-1., dtype=float32)]),
> E                   p=1.0,
> E                   test_flags=FrontendFunctionTestFlags(
> E                       num_positional_args=0,
> E                       with_out=False,
> E                       inplace=False,
> E                       as_variable=[False],
> E                       native_arrays=[False],
> E                       generate_frontend_arrays=False,
> E                   ),
> E                   fn_tree='ivy.functional.frontends.paddle.dist',
> E                   on_device='cpu',
> E                   frontend='paddle',
> E               )
> E               
> ```
> 
> It seems `paddle.dist` always returns `shape=[1]`, while `ivy.vector_norm` returns a scalar as shown by the following example:
> 
> ```
> import paddle
> x = paddle.to_tensor([-1.0])
> y = paddle.to_tensor([1.0])
> print(paddle.dist(x,y,2).shape)
> >>> [1]
> ```
> 
> You may change it to the following:
> 
> ```
> def dist(x, y, p=2):
>     ret = ivy.vector_norm(ivy.subtract(x, y), ord=p)
>     return ivy.reshape(ret, (1,))
> ```

Hi sir, on doing the changes you mentioned i got this error: 
image

**Comment by MuhammadSaeedBatikh** [comment]
This is odd!
 
I got the exact opposite:
with reshape:
image

and without reshape:
image

Let's apply the modifications and see if there are any relevant failing github checks to decide on which version to merge.

**Comment by MuhammadSaeedBatikh** [comment]
The checks match your version. It's now raising mismatched shape exception.

**Comment by Ashwani132003** [comment]
> The checks match your version. It's now raising mismatched shape exception.

So, is there anything to be done from my side to fix this? If not can you please merge this pr.

**Comment by MuhammadSaeedBatikh** [comment]
> > The checks match your version. It's now raising mismatched shape exception.
> 
> So, is there anything to be done from my side to fix this? If not can you please merge this pr.

Yes, we need to revert back to the version without `reshape` (your version ) which seems to pass all checks + local tests. Sorry for this inconvenience.

**Comment by Ashwani132003** [comment]
> > > The checks match your version. It's now raising mismatched shape exception.
> > 
> > 
> > So, is there anything to be done from my side to fix this? If not can you please merge this pr.
> 
> Yes, we need to revert back to the version without `reshape` (your version ) which seems to pass all checks + local tests; then it should be ready for merge. Sorry for this inconvenience.

Done modifications as you said, please merge it, Thanks .

**Pull request merged**
