### PR TITLE
Added frontend tensorflow zeros function

### LINKED ISSUE #6951: zeros

### PR DESCRIPTION
**Pull request by AhmedMousa-ag**
This PR closes #6951

### CODE REVIEW

**Comment by CerberusLatrans** [comment]
Hi @AhmedMousa-ag thanks for the PR!

For your test, just make sure that the shape param can be "A list of integers, a tuple of integers, or a 1-D Tensor of type int32" (from tf.zeros docs) instead of just a tuple.

Let me know if you have any questions. Thanks!

**Comment by AhmedMousa-ag** [comment]
Hi @CerberusLatrans changed it to produce random shapes, waiting for your review.

**Comment by CerberusLatrans** [comment]
I meant generating lists and 1-D lists as input too (in addition to tuples). get_shape only produces tuples.

**Comment by AhmedMousa-ag** [comment]
@CerberusLatrans Thank you for clarifying, I changed it to produce dtype_and_values as I understand it produces arrays and tensors of random shapes which includes tuples, lists, and tensors as well.

**Comment by CerberusLatrans** [comment]
dtype_and_values only produces arrays to my knowledge (https://github.com/unifyai/ivy/blob/d666a0fbe0106570402ed86fd87858c3f5754bb3/ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py#L83). Since ivy converts tensors to ivy arrays, it is fine to just produce arrays and tuples. You can do this with hypothesis strategies (st.tuples). Thanks.

**Comment by AhmedMousa-ag** [comment]
@CerberusLatrans Thank you for clearifing, I did changed it, and apparently you've done major changes to ivy that you now use @handle_frontend_test, and that produced a lot of errors across the package that isn't related to me 😕

**Comment by CerberusLatrans** [comment]
Hi @AhmedMousa-ag yes, there have been some major refactors to the frontend tests (and testing in general), so don't worry about that. Just one thing: I meant to use both st.tuples (or get_shape) and st.lists to generate both types. Thanks!

**Pull request closed without merging**
