### PR TITLE
Added AdaptiveAvgPool3D

### PR DESCRIPTION
**Pull request by shubham1206agra**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by shubham1206agra** [comment]
@RickSanchezStoic Please review this PR.
I need this PR to open another PR.

**Comment by RickSanchezStoic** [comment]
Hi @RashulChutani the tests don't seem to be picking up, seems like an issue with the runner.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @shubham1206agra 

I tried to run your tests locally and I'm getting the following failure
`E   hypothesis.errors.FailedHealthCheck: The smallest natural example for your test is extremely large. This makes it difficult for Hypothesis to generate good examples, especially when trying to reduce failing ones at the end. Consider reducing the size of your data if it is of a fixed size. You could also fix this by improving how your data shrinks (see https://hypothesis.readthedocs.io/en/latest/data.html#shrinking for details), or by introducing default values inside your strategy. e.g. could you replace some arguments with their defaults by using one_of(none(), some_complex_strategy)?
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.large_base_example to the suppress_health_check settings for this test.`

Would you look into this🙂

**Comment by shubham1206agra** [comment]
> Hey @shubham1206agra
> 
> I tried to run your tests locally and I'm getting the following failure `E hypothesis.errors.FailedHealthCheck: The smallest natural example for your test is extremely large. This makes it difficult for Hypothesis to generate good examples, especially when trying to reduce failing ones at the end. Consider reducing the size of your data if it is of a fixed size. You could also fix this by improving how your data shrinks (see https://hypothesis.readthedocs.io/en/latest/data.html#shrinking for details), or by introducing default values inside your strategy. e.g. could you replace some arguments with their defaults by using one_of(none(), some_complex_strategy)? E See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.large_base_example to the suppress_health_check settings for this test.`
> 
> Would you look into this🙂

Can you tell me which command have you run?

**Comment by hirwa-nshuti** [comment]
> > Hey @shubham1206agra
> > I tried to run your tests locally and I'm getting the following failure `E hypothesis.errors.FailedHealthCheck: The smallest natural example for your test is extremely large. This makes it difficult for Hypothesis to generate good examples, especially when trying to reduce failing ones at the end. Consider reducing the size of your data if it is of a fixed size. You could also fix this by improving how your data shrinks (see https://hypothesis.readthedocs.io/en/latest/data.html#shrinking for details), or by introducing default values inside your strategy. e.g. could you replace some arguments with their defaults by using one_of(none(), some_complex_strategy)? E See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.large_base_example to the suppress_health_check settings for this test.`
> > Would you look into this🙂
> 
> Can you tell me which command have you run?
`pytest -v ivy_test/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_adaptive_avg_pool3d`

**Comment by shubham1206agra** [comment]
@hirwa-nshuti Now test should be working. But looks like avg_pool tests are failing.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Try updating with the latest master branch changes to run CI checks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @shubham1206agra 

Would you resolve the merge conflicts, for me to be able to run the tests locally, I'll then continue the review process

**Comment by shubham1206agra** [comment]
@hirwa-nshuti Can you quickly test now?

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
There are also some merge conflicts would resolve them😂
Sorry for responding late🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
