### PR TITLE
index_add

### LINKED ISSUE #13951: index_add

### PR DESCRIPTION
**Pull request by kkaracam**
Close #13951

### CODE REVIEW

**Comment by kkaracam** [comment]
Hi @hmahmood24, can I get a review on this?

**Comment by hmahmood24** [comment]
Hey @kkaracam, 

Apologies for the delay on my end. Everything looks good to me. The test, however, seems to fail for the `jax` backend as seen [here](https://github.com/unifyai/ivy/actions/runs/4668048385/jobs/8264596326?pr=13999#step:3:243). Can you kindly look into the failing example and try to fix it? Thanks so much for your patience! 😃

**Comment by kkaracam** [comment]
Thanks for the feedback @hmahmood24. I just synced the branch with no additions to the implementation, and now the tests pass. I believe the issue is caused by instabilities in float operations and how different backends handle it. But I am not certain what the case actually is.

**Comment by hmahmood24** [comment]
Hey @kkaracam, thanks so much! I think your suggestion makes sense. 👍🏼 I manually verified this and it doesn't break any existing functionality. The only possible reason why this is happening is probably because of some precision loss in the `ivy.add` function for certain high precision inputs causing the output to rollover in certain cases. 

Please feel free to make the change to [this](https://github.com/unifyai/ivy/blob/7a8fc1ea4eca6d061ae7a3efd1814518d4a6016f/ivy/functional/frontends/torch/indexing_slicing_joining_mutating_ops.py#L312) line and verify whether your method as well as that function pass the tests for all backends. Kindly tag me or request for a re-review from me once you're done. Thanks! 😃

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @kkaracam, thanks so much! I think your suggestion makes sense. 👍🏼 I manually verified this and it doesn't break any existing functionality. The only possible reason why this is happening is probably because of some precision loss in the ivy.add function for certain high precision inputs causing the output to rollover in certain cases.

Please feel free to make the change to [this](https://github.com/unifyai/ivy/blob/7a8fc1ea4eca6d061ae7a3efd1814518d4a6016f/ivy/functional/frontends/torch/indexing_slicing_joining_mutating_ops.py#L312) line and verify whether your method as well as that function pass the tests for all backends. Kindly tag me or request for a re-review from me once you're done. Thanks! 😃

**Comment by kkaracam** [comment]
Hi again @hmahmood24 

Thanks for the explanation. I have made the discussed changes.

**Comment by hmahmood24** [comment]
Hey @kkaracam, thank you for an amazing contribution! Looks good to merge now 🚀

**Comment by kkaracam** [comment]
Thank you for your attention and help!

**Pull request merged**
