### PR TITLE
Fixed the formatting issue

### PR DESCRIPTION
**Pull request by mayankcs**
Fixed the formatting issue in the multiply method in the tensorflow frontend as per addressed by @ankitdsi2010

### CODE REVIEW

**Comment by mayankcs** [comment]
@Aarsh2001 can you please help me out in understanding these two checks that results failed. so that I can fix them quickly.

**Comment by Aarsh2001** [comment]
Hi @mayankcs, kindly add the tests in the `test_ivy/test_frontends/test_tensorflow` directory as well. This is a part of the task as mentioned [here](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis)

**Comment by Aarsh2001** [comment]
Hi @mayankcs, kindly fix the merge conflicts, rest the PR is good to go, thanks🙂.

**Comment by mayankcs** [comment]
> Hi @mayankcs, kindly fix the merge conflicts, rest the PR is good to go, thanks🙂.

Hello @Aarsh2001, just solved the merge conflict! Kindly check it once. Thanks.

**Pull request merged**
