### PR TITLE
Implement `polygamma` math functionality for TensorFlow frontend

### PR DESCRIPTION
**Pull request by edith007**
Close https://github.com/unifyai/ivy/issues/14177

### CODE REVIEW

**Review by ndurumo254 — CHANGES_REQUESTED** [review]
Hello @edith007, thanks for your contribution, the implementation looks good but before we proceed fix the unit tests. Once they pass will merge your PR. Thanks

**Comment by edith007** [comment]
Hi @ndurumo254 👋🏻 
We are getting `AttributeError: module 'ivy.functional.backends.torch' has no attribute 'polygamma'` Is there is no backend implementation for `polygamma`??

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ndurumo254** [comment]
> Hi @ndurumo254 👋🏻 We are getting `AttributeError: module 'ivy.functional.backends.torch' has no attribute 'polygamma'` Is there is no backend implementation for `polygamma`??

Hi @edith007 polygamma is a compositional function,  this is the reason as to why you are getting the error. you can get some insight about the function here  https://lets-unify.ai/docs/ivy/overview/deep_dive/function_types.html#

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
