### PR TITLE
Add ```paddle.tensor.manipulation.tensordot``` Manipulation Functions to Paddle Frontend

### LINKED ISSUE #17207: tensordot

### PR DESCRIPTION
**Pull request by benkimz**
Close #17207

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Actually 1 thing I missed 😅 
`tensordot` also takes `axes` as an argument.
You can check it out [here](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/tensordot_en.html)
Can you also add this and also test this argument.

Thanks

**Comment by benkimz** [comment]
> Actually 1 thing I missed 😅 `tensordot` also takes `axes` as an argument. You can check it out [here](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/tensordot_en.html) Can you also add this and also test this argument.
> 
> Thanks

I have included the axes argument. 
Thank you! 😊

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Thanks for the changes 😄.
One thing that's causing the tests to fail is that `heleprs.dtype_and_values` doesn't produce a value for `axis`, you will have to use `helpers.dtype_values_axis` to generate an axis along with an array. You can check out any other function which has an axis argument for reference how to use this helper function. Hope this makes sense.

Thanks

**Comment by benkimz** [comment]
> Hi,
> 
> Thanks for the changes 😄. One thing that's causing the tests to fail is that `heleprs.dtype_and_values` doesn't produce a value for `axis`, you will have to use `helpers.dtype_values_axis` to generate an axis along with an array. You can check out any other function which has an axis argument for reference how to use this helper function. Hope this makes sense.
> 
> Thanks

All the tests are now passed. 
Thank you!

**Pull request closed without merging**
