### PR TITLE
added asin and arcsin to torch frontend and tested

### LINKED ISSUE #5812: asin

### LINKED ISSUE #5814: arcsin

### PR DESCRIPTION
**Pull request by TAUIL-Abd-Elilah**
Close #5812
Close #5814

### CODE REVIEW

**Comment by aryans1204** [comment]
Hello,

Since this is a PyTorch frontend task can you get the tests you've written passing for the torch frontend?

**Comment by TAUIL-Abd-Elilah** [comment]
This is what I got. And it's the same issue in other functions like test_torch_instance_sin

image

**Comment by TAUIL-Abd-Elilah** [comment]
This is the errors that I got (which are by the way the same as existing functions like test_torch_instance_sin):

`/usr/bin/python3 /opt/.pycharm_helpers/pycharm/_jb_pytest_runner.py --target test_tensor.py::test_torch_instance_asin -- --backend=all 
Testing started at 23:56 ...
Launching pytest with arguments --backend=all test_tensor.py::test_torch_instance_asin --no-header --no-summary -q in /ivy/ivy_tests/test_ivy/test_frontends/test_torch

============================= test session starts ==============================
collecting ... collected 4 items

test_tensor.py::test_torch_instance_asin[cpu-ivy.functional.backends.numpy-False-False-numpy] <- ivy_tests/test_ivy/helpers/testing_helpers.py FAILED [ 25%]
ivy_tests/test_ivy/helpers/testing_helpers.py:182 (test_torch_instance_asin[cpu-ivy.functional.backends.numpy-False-False-numpy])
get_command_line_flags = {'as_variable': None, 'container': None, 'instance_method': None, 'native_array': None, ...}
device = 'cpu'
f = <module 'ivy.functional.backends.numpy' from '/ivy/ivy/functional/backends/numpy/__init__.py'>
fw = 'numpy', fixt_frontend_str = 'torch', args = (), kwargs = {}

    @given(data=st.data())
>   @settings(max_examples=1)

../../helpers/testing_helpers.py:184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../helpers/testing_helpers.py:226: in new_fn
    return test_fn(*args, **kwargs)
test_tensor.py:34: in test_torch_instance_asin
    @given(
test_tensor.py:46: in test_torch_instance_asin
    helpers.test_frontend_method(
../../helpers/function_testing.py:1382: in test_frontend_method
    value_test(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def value_test(
        *,
        ret_np_flat,
        ret_np_from_gt_flat,
        rtol=None,
        atol=1e-6,
        ground_truth_backend="TensorFlow",
    ):
        """Performs a value test for matching the arrays in ret_np_flat and
        ret_from_np_flat.
    
        Parameters
        ----------
        ret_np_flat
            A list (flattened) containing Numpy arrays. Return from the
            framework to test.
        ret_np_from_gt_flat
            A list (flattened) containing Numpy arrays. Return from the ground
            truth framework.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the value test passes, else marks the test as failed.
        """
        assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
    
        if type(ret_np_flat) != list:
            ret_np_flat = [ret_np_flat]
        if type(ret_np_from_gt_flat) != list:
            ret_np_from_gt_flat = [ret_np_from_gt_flat]
>       assert len(ret_np_flat) == len(ret_np_from_gt_flat), (
            "len(ret_np_flat) != len(ret_np_from_gt_flat):\n\n"
            "ret_np_flat:\n\n{}\n\nret_np_from_gt_flat:\n\n{}".format(
                ret_np_flat, ret_np_from_gt_flat
            )
        )
E       AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
E       
E       ret_np_flat:
E       
E       []
E       
E       ret_np_from_gt_flat:
E       
E       [array(-1.57079633)]

../../helpers/assertions.py:103: AssertionError
FAILED [ 50%]
ivy_tests/test_ivy/helpers/testing_helpers.py:182 (test_torch_instance_asin[cpu-ivy.functional.backends.jax-False-False-jax])
get_command_line_flags = {'as_variable': None, 'container': None, 'instance_method': None, 'native_array': None, ...}
device = 'cpu'
f = <module 'ivy.functional.backends.jax' from '/ivy/ivy/functional/backends/jax/__init__.py'>
fw = 'jax', fixt_frontend_str = 'torch', args = (), kwargs = {}

    @given(data=st.data())
>   @settings(max_examples=1)

../../helpers/testing_helpers.py:184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../helpers/testing_helpers.py:226: in new_fn
    return test_fn(*args, **kwargs)
test_tensor.py:34: in test_torch_instance_asin
    @given(
test_tensor.py:46: in test_torch_instance_asin
    helpers.test_frontend_method(
../../helpers/function_testing.py:1382: in test_frontend_method
    value_test(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def value_test(
        *,
        ret_np_flat,
        ret_np_from_gt_flat,
        rtol=None,
        atol=1e-6,
        ground_truth_backend="TensorFlow",
    ):
        """Performs a value test for matching the arrays in ret_np_flat and
        ret_from_np_flat.
    
        Parameters
        ----------
        ret_np_flat
            A list (flattened) containing Numpy arrays. Return from the
            framework to test.
        ret_np_from_gt_flat
            A list (flattened) containing Numpy arrays. Return from the ground
            truth framework.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the value test passes, else marks the test as failed.
        """
        assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
    
        if type(ret_np_flat) != list:
            ret_np_flat = [ret_np_flat]
        if type(ret_np_from_gt_flat) != list:
            ret_np_from_gt_flat = [ret_np_from_gt_flat]
>       assert len(ret_np_flat) == len(ret_np_from_gt_flat), (
            "len(ret_np_flat) != len(ret_np_from_gt_flat):\n\n"
            "ret_np_flat:\n\n{}\n\nret_np_from_gt_flat:\n\n{}".format(
                ret_np_flat, ret_np_from_gt_flat
            )
        )
E       AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
E       
E       ret_np_flat:
E       
E       []
E       
E       ret_np_from_gt_flat:
E       
E       [array(-1.57079633)]

../../helpers/assertions.py:103: AssertionError
FAILED [ 75%]2022-10-21 22:56:59.002291: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-10-21 22:56:59.002379: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)

ivy_tests/test_ivy/helpers/testing_helpers.py:182 (test_torch_instance_asin[cpu-ivy.functional.backends.tensorflow-False-False-tensorflow])
get_command_line_flags = {'as_variable': None, 'container': None, 'instance_method': None, 'native_array': None, ...}
device = 'cpu'
f = <module 'ivy.functional.backends.tensorflow' from '/ivy/ivy/functional/backends/tensorflow/__init__.py'>
fw = 'tensorflow', fixt_frontend_str = 'torch', args = (), kwargs = {}

    @given(data=st.data())
>   @settings(max_examples=1)

../../helpers/testing_helpers.py:184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../helpers/testing_helpers.py:226: in new_fn
    return test_fn(*args, **kwargs)
test_tensor.py:34: in test_torch_instance_asin
    @given(
test_tensor.py:46: in test_torch_instance_asin
    helpers.test_frontend_method(
../../helpers/function_testing.py:1382: in test_frontend_method
    value_test(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def value_test(
        *,
        ret_np_flat,
        ret_np_from_gt_flat,
        rtol=None,
        atol=1e-6,
        ground_truth_backend="TensorFlow",
    ):
        """Performs a value test for matching the arrays in ret_np_flat and
        ret_from_np_flat.
    
        Parameters
        ----------
        ret_np_flat
            A list (flattened) containing Numpy arrays. Return from the
            framework to test.
        ret_np_from_gt_flat
            A list (flattened) containing Numpy arrays. Return from the ground
            truth framework.
        rtol
            Relative Tolerance Value.
        atol
            Absolute Tolerance Value.
        ground_truth_backend
            Ground Truth Backend Framework.
    
        Returns
        -------
        None if the value test passes, else marks the test as failed.
        """
        assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
    
        if type(ret_np_flat) != list:
            ret_np_flat = [ret_np_flat]
        if type(ret_np_from_gt_flat) != list:
            ret_np_from_gt_flat = [ret_np_from_gt_flat]
>       assert len(ret_np_flat) == len(ret_np_from_gt_flat), (
            "len(ret_np_flat) != len(ret_np_from_gt_flat):\n\n"
            "ret_np_flat:\n\n{}\n\nret_np_from_gt_flat:\n\n{}".format(
                ret_np_flat, ret_np_from_gt_flat
            )
        )
E       AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
E       
E       ret_np_flat:
E       
E       []
E       
E       ret_np_from_gt_flat:
E       
E       [array(-1.57079633)]

../../helpers/assertions.py:103: AssertionError
FAILED [100%]
ivy_tests/test_ivy/helpers/testing_helpers.py:182 (test_torch_instance_asin[cpu-ivy.functional.backends.torch-False-False-torch])
get_command_line_flags = {'as_variable': None, 'container': None, 'instance_method': None, 'native_array': None, ...}
device = 'cpu'
f = <module 'ivy.functional.backends.torch' from '/ivy/ivy/functional/backends/torch/__init__.py'>
fw = 'torch', fixt_frontend_str = 'torch', args = (), kwargs = {}

    @given(data=st.data())
>   @settings(max_examples=1)

../../helpers/testing_helpers.py:184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../helpers/testing_helpers.py:226: in new_fn
    return test_fn(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

as_variable = [False], native_array = [False]

    @handle_cmd_line_args
>   @given(
        dtype_and_x=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("float"),
            allow_inf=False,
        ),
    )
E   hypothesis.errors.MultipleFailures: Hypothesis found 2 distinct failures.

test_tensor.py:34: MultipleFailures


























test_tensor.py::test_torch_instance_asin[cpu-ivy.functional.backends.jax-False-False-jax] <- ivy_tests/test_ivy/helpers/testing_helpers.py 
test_tensor.py::test_torch_instance_asin[cpu-ivy.functional.backends.tensorflow-False-False-tensorflow] <- ivy_tests/test_ivy/helpers/testing_helpers.py 
test_tensor.py::test_torch_instance_asin[cpu-ivy.functional.backends.torch-False-False-torch] <- ivy_tests/test_ivy/helpers/testing_helpers.py 

======================= 4 failed, 130 warnings in 35.29s =======================

Process finished with exit code 1`

**Comment by aryans1204** [comment]
Hi, are you running the tests on the Ivy Docker container? Because the CUDA error shouldn't be there if you have CUDA and cuDNN correctly installed on your system, or more preferably you're using the Ivy Docker image.

**Comment by TAUIL-Abd-Elilah** [comment]
Yes, I do run the code with the Ivy Docker container
image

**Comment by aryans1204** [comment]
As such, the test_frontend_methods function is currently not working, so you don't have to pass the tests for now, and this can be merged. 

LGTM!

**Comment by TAUIL-Abd-Elilah** [comment]
Thanks @aryans1204

**Pull request merged**
