### PR TITLE
feat: Added lgamma to tensorflow frontend

### LINKED ISSUE #25893: lgamma

### PR DESCRIPTION
**Pull request by Lordsedion**
# PR Description

Close #25893 

## Checklist

- [ Yes] Did you add a function?
- [ Yes] Did you add the tests?
- [ Yes] Did you run your tests and are your tests passing?
- [ No] Did pre-commit not fail on any check?
- [ Yes] Did you follow the steps we provided?

### Socials:
twitter.com/lordseidon_

### CODE REVIEW

**Comment by Lordsedion** [comment]
Good day, @Aarsh2001 Can you kindly please review my PR?
Thank you.

**Comment by Lordsedion** [comment]
Good day, Mr @Aarsh2001 Can you kindly please review my PR?
Thank you.

**Review by Aarsh2001 — COMMENTED** [review]
Hey @Lordsedion, are all tests passing for you locally ? Here on the CI i noticed that the test for your function is failing for the Jax backend.

**Comment by Lordsedion** [comment]
> Hey @Lordsedion, are all tests passing for you locally ? Here on the CI i noticed that the test for your function is failing for the Jax backend.

Yes. All tests were passing locally before I made a commit.

**Pull request closed without merging**
