### PR TITLE
add identity function creation for jax numpy

### LINKED ISSUE #9220: identity

### PR DESCRIPTION
**Pull request by SaitejaUtpala**
closes #9220

### CODE REVIEW

**Comment by SaitejaUtpala** [comment]
@ahmedo42, I have run the test locally, failed test is unrelated to the changes.

**Comment by SaitejaUtpala** [comment]
@ahmedo42 any update ? Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @SaitejaUtpala 
Thanks for contributing to ivy😊
Here are a few suggested changes that are needed🙂
After that, it'll be good to be merged.
Thanks and happy coding✌

**Pull request closed without merging**
