### PR TITLE
Positive function for Numpy Frontend

### PR DESCRIPTION
**Pull request by deepanshug4**

### CODE REVIEW

**Comment by deepanshug4** [comment]
This PR is for issue #3841. I couldn't assign this in the Development section, so I thought it would be better to just comment the issue number.

**Comment by MrZilinXiao** [comment]
Hi @deepanshug4. Thanks for your contribution. But would you mind checking the test failures relating to your commits here? https://github.com/unifyai/ivy/runs/8107959439?check_suite_focus=true#step:6:4853
It seems you gave the wrong type for `input_dtype `, which is causing `TypeError: can only concatenate str (not "list") to str`.

**Comment by deepanshug4** [comment]
Hi @MrZilinXiao, Thanks for the review I have fixed that part. Can you please check it out and give reviews about the same.

**Review by MrZilinXiao — APPROVED** [review]
Great! No more failures!

**Pull request merged**
