### PR TITLE
Adds constant_initializer to Tensorflow frontend

### LINKED ISSUE #21611: constant_initializer

### PR DESCRIPTION
**Pull request by MaxFrax**
Close #21611

### CODE REVIEW

**Comment by MaxFrax** [comment]
As per Tensorflow [source code](https://github.com/tensorflow/tensorflow/blob/e3303d912751b9fe5d9785d28ef258a142095cc0/tensorflow/python/ops/init_ops.py#L1665) the function works as an alias to `constant`.
In particular, `constant_initializer` works with just the value argument, as per [documentation](https://www.tensorflow.org/api_docs/python/tf/constant_initializer)

Please note that the test fails due to #20982 .
To run the test `python3 -m pytest -x /ivy_tests/test_ivy/test_frontends/test_tensorflow /test_general_functions.py::test_constant_initializer`

**Comment by OmarJabri7** [comment]
Hello @MaxFrax ,
it seems that your tests are failing on all frameworks:
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_constant_initializer,jax
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_constant_initializer,torch
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_constant_initializer,tensorflow
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_constant_initializer,numpy
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_constant_initializer,paddle

Could you kindly check these test again and commit your changes?

**Comment by MaxFrax** [comment]
> Hello @MaxFrax ,
> Let me check based on the bug reported, what we can do in this scenario

Thank you @OmarJabri7 ! Let me know!
PS sorry for the pr closed and then reopened, I was trying to rename my branch from master to main

**Comment by OmarJabri7** [comment]
Hey There @MaxFrax , the bug is okay, however it seems you have done a lot of changes to the folder test_array_api, please can you revert these changes to the system files?

**Comment by MaxFrax** [comment]
> Hey There @MaxFrax , the bug is okay, however it seems you have done a lot of changes to the folder test_array_api, please can you revert these changes to the system files?

I was unable to revert those changes. Git submodules still defeats me sometimes.
I created a new PR from a clean branch. I hope it is actually the fastest way to move forward.
Here it is https://github.com/unifyai/ivy/pull/22760

**Pull request closed without merging**
