### PR TITLE
Update typo in docs, building blocks section

### PR DESCRIPTION
**Pull request by MariaGamal**

### CODE REVIEW

**Review by Ishticode — APPROVED** [review]
Good spot. Thanks for this @MariaGamal.🙂.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Although, I would say its best to change all `f` references to `backend` the way it is currently in ivy master on [this line](https://github.com/unifyai/ivy/blob/633c481ce6338d3aeeef6b24a204d8e0bb88f3c7/ivy/backend_handler.py#L225). Could you also add the typehint of `str`. The rest should remain as is. Could you perhaps update this and request a review and I will get this merged. 🙂

**Review by Ishticode — APPROVED** [review]
Looks all good. Thanks for this contribution @MariaGamal mergning now.

**Comment by MariaGamal** [comment]
> Looks all good. Thanks for this contribution @MariaGamal mergning now.

Thank you! @Ishticode

**Pull request merged**
