### PR TITLE
implementation and tests for is_meta for PyTorch Frontend

### LINKED ISSUE #16671: is_meta

### PR DESCRIPTION
**Pull request by MohammedAbdulaziz**
Close #16671

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @MohammedAbdulaziz 
Firstly, Thank you for the PR. The idea of the implementaion is correct. There is some mistakes which should be caught when u run the test.
1. You should pass the meta_tensor in using `init_all_as_kwargs_np`. Look at other tests to get examples.
2. The test_frontend_method has no paramter `expected_output=True` that is being passed in. You can manually test the values by setting `test_values=False` and obtaitning the results and commparing them manually. something like
` ret == frontend_ret == True` where ret, and frontend_ret are return by test_frontend_function when test_value is set to False.
Please let know if you have any questions and request my review when you are done. Thanks 
🙂

**Comment by MohammedAbdulaziz** [comment]
@Ishticode am I on the right track with this? the checks are more successful this time, but i'm not sure why some of them are failing

**Comment by MohammedAbdulaziz** [comment]
@Ishticode have you had the time to re-review?

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @MohammedAbdulaziz 
Running the tests gives `fixture 'frontend_method_data' not found`.
The `meta_tensor` and `data_tensor` that is being generated should be generated under handle_frontend_method rather than creating one manually. Please check similar tests. Let me know if something is unclear 🙂

**Comment by MohammedAbdulaziz** [comment]
@Ishticode can you please explain further how i can generate the tensors in handle_frontend_method? i have been checking similar tests for sometime and i'm not getting anywhere, i would really appreciate it if you would guide through it

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi.
So looking at the test blelow like `test_torch_instance_movedim` for example, you can use the  `helpers.dtype_and_values` function

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
