### PR TITLE
Updated torch backend implementation of randint to handle high and low as tensors 

### LINKED ISSUE #10434: Fix random.test_randint
|   |   |
|---|---|
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5655028157/job/15319282793"></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5655028157/job/15319282793"></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5655028157/job/15319282793"></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5655028157/job/15319282793"></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5655028157/job/15319282793"></a>

### PR DESCRIPTION
**Pull request by hello-fri-end**
close #10434.

`torch.randint` does not natively support `high` and `low` as tensors. I updated the backend implementation to add support for the same.

### CODE REVIEW

**Comment by hello-fri-end** [comment]
Hi @CatB1t! There's still one problem in the torch backend implementation. If `shape` is different from `shape(high)` & `shape(low)`, we should return broadcast the result to `shape` if the shape of the result is broadcastable and throw an error otherwise.  Here's an example in NumPy that should make this point clear:

```python
>>> high
array([[2, 3],
       [4, 5]])
>>> low
array([[1, 2],
       [3, 4]])
>>> np.random.randint(low,high)
array([[1, 2],
       [3, 4]])
>>> np.random.randint(low, high, size=(1,2))
array([[1, 2]])
>>> np.random.randint(low, high, size=(2,1))
array([[1],
       [2]])
>>> np.random.randint(low, high, size=(2, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1262, in numpy.random._bounded_integers._rand_int64
  File "_bounded_integers.pyx", line 697, in numpy.random._bounded_integers._rand_int64_broadcast
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 2) and arg 2 with shape (2, 3).

```

Our implementation will give an error in cases 2 and 3 ( cannot reshape an array of size 4 to (1,2) & (2,1) respectively). How should I update the function to handle this behavior?

**Comment by hello-fri-end** [comment]
> Hi @CatB1t! There's still one problem in the torch backend implementation. If `shape` is different from `shape(high)` & `shape(low)`, we should unbroadcast (not sure what the correct name for the opposite of broadcasting is :D) the result to `shape` if the shape of the result is unbroadcast compatible and throw an error otherwise. Here's an example in NumPy that should make this point clear:
> 
> ```python
> >>> high
> array([[2, 3],
>        [4, 5]])
> >>> low
> array([[1, 2],
>        [3, 4]])
> >>> np.random.randint(low,high)
> array([[1, 2],
>        [3, 4]])
> >>> np.random.randint(low, high, size=(1,2))
> array([[1, 2]])
> >>> np.random.randint(low, high, size=(2,1))
> array([[1],
>        [2]])
> >>> np.random.randint(low, high, size=(2, 3))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
>   File "_bounded_integers.pyx", line 1262, in numpy.random._bounded_integers._rand_int64
>   File "_bounded_integers.pyx", line 697, in numpy.random._bounded_integers._rand_int64_broadcast
>   File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
> ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 2) and arg 2 with shape (2, 3).
> ```
> 
> Our implementation will give an error in cases 2 and 3 ( cannot reshape an array of size 4 to (1,2) & (2,1) respectively). How should I update the function to handle this behavior?

Hey @CatB1t! I figured out how to handle the broadcasting issue. Here's a summary of the changes I made:

`_check_bounds_and_get_shape` helper
- We'll first broadcast `low`, `high` and `shape` ( with `ivy.ones` as a dummy array) to a common shape.
- Next, we'll get the indices (`_get_indices` function) for `low` and `high` to match the `shape` tuple if it's specified.
- In the torch backend, we'll flatten the `low` and `high` arrays to generate individual values and then concatenate them ( finally the result will be reshaped to match `shape`).

In the tests:

- Updated the `gen_randint_data` helper to generate a mutually broadcastable shape for `low`, `high` and `shape`.
- The value test was incorrect. Updated it with the same broadcasting logic as above. 

There's still one problem with the test which I'm unable to figure out.
```python
  assert ivy.all(ret[0] >= low[0]) and ivy.all(ret[0] < high[0])
    assert ivy.all(ret_gt[0] >= low[0]) and ivy.all(ret_gt[0] < high[0])
```
These two assertions fail with very weird errors.
Torch: ` ivy.exceptions.IvyBackendException: torch: default_dtype: torch: is_complex_dtype: torch: as_ivy_dtype: True`
Jax: `ivy.exceptions.IvyBackendException: jax: default_dtype: jax: is_complex_dtype: jax: as_ivy_dtype: True`
Tensorflow: `ivy.exceptions.IvyBackendException: tensorflow: default_dtype: tensorflow: default_float_dtype: local variable 'ret' referenced before assignment`

There is no error for NumPy. I checked the values with the debugger and it seems to be a problem with `ivy.all()` function ( The conditions inside always evaluate to True). Did I miss anything in the test which is causing this problem or is this a known issue with `ivy.all()`? 

CC: @VedPatwardhan Can you also take a took at this please?

**Comment by VedPatwardhan** [comment]
> > Hi @CatB1t! There's still one problem in the torch backend implementation. If `shape` is different from `shape(high)` & `shape(low)`, we should unbroadcast (not sure what the correct name for the opposite of broadcasting is :D) the result to `shape` if the shape of the result is unbroadcast compatible and throw an error otherwise. Here's an example in NumPy that should make this point clear:
> > ```python
> > >>> high
> > array([[2, 3],
> >        [4, 5]])
> > >>> low
> > array([[1, 2],
> >        [3, 4]])
> > >>> np.random.randint(low,high)
> > array([[1, 2],
> >        [3, 4]])
> > >>> np.random.randint(low, high, size=(1,2))
> > array([[1, 2]])
> > >>> np.random.randint(low, high, size=(2,1))
> > array([[1],
> >        [2]])
> > >>> np.random.randint(low, high, size=(2, 3))
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
> >   File "_bounded_integers.pyx", line 1262, in numpy.random._bounded_integers._rand_int64
> >   File "_bounded_integers.pyx", line 697, in numpy.random._bounded_integers._rand_int64_broadcast
> >   File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
> > ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 2) and arg 2 with shape (2, 3).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Our implementation will give an error in cases 2 and 3 ( cannot reshape an array of size 4 to (1,2) & (2,1) respectively). How should I update the function to handle this behavior?
> 
> Hey @CatB1t! I figured out how to handle the broadcasting issue. Here's a summary of the changes I made:
> 
> `_check_bounds_and_get_shape` helper
> 
> * We'll first broadcast `low`, `high` and `shape` ( if it's specified) to a common shape.
> * Next, we'll get the indices (`_get_indices` function) for `low` and `high` to match the `shape` tuple if it's specified.
> * In the torch backend, we'll flatten the `low` and `high` arrays to generate individual values and then concatenate them ( finally the result will be reshaped to match `shape`).
> 
> In the tests:
> 
> * Updated the `gen_randint_data` helper to generate a mutually broadcastable shape for `low`, `high` and `shape`.
> * The value test was incorrect. Updated it with the same broadcasting logic as above.
> 
> There's still one problem with the test which I'm unable to figure out.
> 
> ```python
>   assert ivy.all(ret[0] >= low[0]) and ivy.all(ret[0] < high[0])
>     assert ivy.all(ret_gt[0] >= low[0]) and ivy.all(ret_gt[0] < high[0])
> ```
> 
> These two assertions fail with very weird errors. Torch: ` ivy.exceptions.IvyBackendException: torch: default_dtype: torch: is_complex_dtype: torch: as_ivy_dtype: True` Jax: `ivy.exceptions.IvyBackendException: jax: default_dtype: jax: is_complex_dtype: jax: as_ivy_dtype: True` Tensorflow: `ivy.exceptions.IvyBackendException: tensorflow: default_dtype: tensorflow: default_float_dtype: local variable 'ret' referenced before assignment`
> 
> There is no error for NumPy. I checked the values with the debugger and it seems to be a problem with `ivy.all()` function ( The conditions inside always evaluate to True). Did I miss anything in the test which is causing this problem or is this a known issue with `ivy.all()`?
> 
> CC: @VedPatwardhan Can you also take a took at this please?

Hey @hello-fri-end, actually the change to the `randint` torch backend implementation was incorrectly made in [this](https://github.com/unifyai/ivy/commit/e350652599d1b5fbc42e8d0af55c1de1b8945095) commit last week. As you said, this implementation didn't support `low` and `high` to be `Tensor`, which failed the ivy tests. However, this is something we had previously fixed a few months ago with the help of the [`rand`](https://github.com/unifyai/ivy/commit/fd5c0f2e83d05d249f98f4786152a18909546eaa#diff-d95f1c2c6ec619d420bd290d3456b562eebcabe0b1a0b6907ca2efa36b1ec633R93) function which I've [reverted](https://github.com/unifyai/ivy/commit/cbf614a67ed62bb85534e236395c4a27bffc04ae) the implementation to, and it starts working. This helps avoid the need for additional broadcasting in the helpers and is also supposed to be more efficient. 
If you think there can be improvements to that implementation, feel free to contribute! Thanks 🙂

**Comment by hello-fri-end** [comment]
> > > Hi @CatB1t! There's still one problem in the torch backend implementation. If `shape` is different from `shape(high)` & `shape(low)`, we should unbroadcast (not sure what the correct name for the opposite of broadcasting is :D) the result to `shape` if the shape of the result is unbroadcast compatible and throw an error otherwise. Here's an example in NumPy that should make this point clear:
> > > ```python
> > > >>> high
> > > array([[2, 3],
> > >        [4, 5]])
> > > >>> low
> > > array([[1, 2],
> > >        [3, 4]])
> > > >>> np.random.randint(low,high)
> > > array([[1, 2],
> > >        [3, 4]])
> > > >>> np.random.randint(low, high, size=(1,2))
> > > array([[1, 2]])
> > > >>> np.random.randint(low, high, size=(2,1))
> > > array([[1],
> > >        [2]])
> > > >>> np.random.randint(low, high, size=(2, 3))
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
> > >   File "_bounded_integers.pyx", line 1262, in numpy.random._bounded_integers._rand_int64
> > >   File "_bounded_integers.pyx", line 697, in numpy.random._bounded_integers._rand_int64_broadcast
> > >   File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
> > > ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 2) and arg 2 with shape (2, 3).
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Our implementation will give an error in cases 2 and 3 ( cannot reshape an array of size 4 to (1,2) & (2,1) respectively). How should I update the function to handle this behavior?
> > 
> > 
> > Hey @CatB1t! I figured out how to handle the broadcasting issue. Here's a summary of the changes I made:
> > `_check_bounds_and_get_shape` helper
> > 
> > * We'll first broadcast `low`, `high` and `shape` ( if it's specified) to a common shape.
> > * Next, we'll get the indices (`_get_indices` function) for `low` and `high` to match the `shape` tuple if it's specified.
> > * In the torch backend, we'll flatten the `low` and `high` arrays to generate individual values and then concatenate them ( finally the result will be reshaped to match `shape`).
> > 
> > In the tests:
> > 
> > * Updated the `gen_randint_data` helper to generate a mutually broadcastable shape for `low`, `high` and `shape`.
> > * The value test was incorrect. Updated it with the same broadcasting logic as above.
> > 
> > There's still one problem with the test which I'm unable to figure out.
> > ```python
> >   assert ivy.all(ret[0] >= low[0]) and ivy.all(ret[0] < high[0])
> >     assert ivy.all(ret_gt[0] >= low[0]) and ivy.all(ret_gt[0] < high[0])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These two assertions fail with very weird errors. Torch: ` ivy.exceptions.IvyBackendException: torch: default_dtype: torch: is_complex_dtype: torch: as_ivy_dtype: True` Jax: `ivy.exceptions.IvyBackendException: jax: default_dtype: jax: is_complex_dtype: jax: as_ivy_dtype: True` Tensorflow: `ivy.exceptions.IvyBackendException: tensorflow: default_dtype: tensorflow: default_float_dtype: local variable 'ret' referenced before assignment`
> > There is no error for NumPy. I checked the values with the debugger and it seems to be a problem with `ivy.all()` function ( The conditions inside always evaluate to True). Did I miss anything in the test which is causing this problem or is this a known issue with `ivy.all()`?
> > CC: @VedPatwardhan Can you also take a took at this please?
> 
> Hey @hello-fri-end, actually the change to the `randint` torch backend implementation was incorrectly made in [this](https://github.com/unifyai/ivy/commit/e350652599d1b5fbc42e8d0af55c1de1b8945095) commit last week. As you said, this implementation didn't support `low` and `high` to be `Tensor`, which failed the ivy tests. However, this is something we had previously fixed a few months ago with the help of the [`rand`](https://github.com/unifyai/ivy/commit/fd5c0f2e83d05d249f98f4786152a18909546eaa#diff-d95f1c2c6ec619d420bd290d3456b562eebcabe0b1a0b6907ca2efa36b1ec633R93) function which I've [reverted](https://github.com/unifyai/ivy/commit/cbf614a67ed62bb85534e236395c4a27bffc04ae) the implementation to, and it starts working. This helps avoid the need for additional broadcasting in the helpers and is also supposed to be more efficient. If you think there can be improvements to that implementation, feel free to contribute! Thanks 🙂

Thanks for looking into this. I agree that using the `rand` function makes it more efficient - also makes sense to keep the unit test simple. I'll close this PR. Thanks again :)

**Pull request closed without merging**
