### PR TITLE
 adding square error cost function to loss functions

### LINKED ISSUE #22219: square_error_cost

### PR DESCRIPTION
**Pull request by elestelib**
closes #22219

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Can you resolve the merge conflicts.
I'll merge your PR as soon as you do.

Thanks

**Comment by elestelib** [comment]
Done, please let me know , if all is in order

**Comment by sherry30** [comment]
ivy-gardener

**Review by sherry30 — APPROVED** [review]
lgtm!

**Pull request merged**
