### PR TITLE
adding  arctan2_

### PR DESCRIPTION
**Pull request by soma2000-lang**
close arctan2_ #10493

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hey @soma2000-lang! Can you address the failing tests? Thanks!

**Comment by soma2000-lang** [comment]
@V-G-spec  the lint check failures are not due to my changes.It has passed locally. 
I cannot make out why the intelligent pr test  has failed.It would be great if you can help me there.

**Comment by soma2000-lang** [comment]
@V-G-spec just a friendly reminder.

**Comment by V-G-spec** [comment]
Looks good

**Pull request merged**
