### PR TITLE
Adding 'keep_input_dtype' flag to 'inplace_update'

### PR DESCRIPTION
**Pull request by danielmunioz**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ZoeCD** [comment]
@danielmunioz please ping me once you're happy with the PR and it's ready to merge!

**Comment by danielmunioz** [comment]
Hi @ZoeCD, sorry it took a while, but I still need to add a couple of details to the pr before it can be merged, I'll finish them this week!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
