### PR TITLE
astype #7356

### PR DESCRIPTION
**Pull request by codeamic**

### CODE REVIEW

**Comment by codeamic** [comment]
close #7356

**Comment by agniiyer** [comment]
Hey the test here isn't passing. Can you take another look? :)

**Comment by codeamic** [comment]
ok, i will

**Comment by agniiyer** [comment]
Hey the test is still not passing. Have you checked the logs? Click Details next to `test-frontend-numpy / run-nightly-tests (pull_request)`.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
