### PR TITLE
Tesnorflow frontend - create_rng_state

### LINKED ISSUE #15356: create_rng_state

### PR DESCRIPTION
**Pull request by dp846**
Close #15356

### CODE REVIEW

**Comment by dp846** [comment]
Hi there! I'm new here and working on this pull request as my first for the ML placement position. I have gone through the layout of similar PRs made for similar functions and have made these changes. Could you please give me some pointers on what I should do? Thanks a lot!

**Comment by satakshigarg** [comment]
> Hi there! I'm new here and working on this pull request as my first for the ML placement position. I have gone through the layout of similar PRs made for similar functions and have made these changes. Could you please give me some pointers on what I should do? Thanks a lot!

Hi @dp846 
Thanks for your contribution and your interest in joining our organisation !!

However, there are some lint and formatting checks that are failing. I guess you haven't installed pre-commit yet. I suggest you [set up](https://lets-unify.ai/ivy/overview/contributing/setting_up.html#pre-commit) pre-commit in your local environment and [run](https://lets-unify.ai/ivy/overview/deep_dive/formatting.html#pre-commit-hook) these lint and formatting checks.
Besides, please try running your tests locally, where pytest will show failed tests on your local system itself. Kindly always make sure that you run all your tests locally and ensure that they pass for ALL backends because otherwise the CI tests will fail when you submit a PR.
When you've done all these changes and verified that the tests are passing, feel free to ping me for a review.

Good luck!

**Comment by dp846** [comment]
Thanks for the feedback @satakshigarg - I have closed this PR for now, I am swamped with exams and stuff at the moment so my focus is on that. If this task can be reassigned to others that would be great, I don't want to be holding onto a task that others could get to work on :)

Thanks for the help!

**Comment by satakshigarg** [comment]
No issues @dp846. All the best for your exams !!

**Pull request closed without merging**
