### PR TITLE
fix implementation (experimental)

### PR DESCRIPTION
**Pull request by umer200**

### CODE REVIEW

**Comment by umer200** [comment]
@MahmoudAshraf97 please review

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
please add the unsupported dtypes and devices handler, also try to use the equivalent ivy functions which support more dtypes under `ivy.ArrayMode(False)`
please request another review after the function is passing the tests

**Comment by umer200** [comment]
> please add the unsupported dtypes and devices handler, also try to use the equivalent ivy functions which support more dtypes under `ivy.ArrayMode(False)`
> please request another review after the function is passing the tests

I'm looking into that and will make the changes to cater with the requirements.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by umer200** [comment]
Working on the changes requested for the PR

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
