### PR TITLE
feat: add union1d() for jax frontend

### LINKED ISSUE #23328: union1d

### PR DESCRIPTION
**Pull request by stalemate1**
# PR Description

## Related Issue

Close #23328 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by stalemate1** [comment]
@Ookamice Could you please help me understand why all my functions that I write are running into this error

fun_name = 'union1d'
args = ([Array([-1.], dtype=float32), Array([-1.], dtype=float32)], [Array([-1.], dtype=float32), Array([-1.], dtype=float32)])
pos = 0, arg = [Array([-1.], dtype=float32), Array([-1.], dtype=float32)]
msg = '{} requires ndarray or scalar arguments, got {} at position {}.'

    def check_arraylike(fun_name: str, *args: Any):
      """Check if all args fit JAX's definition of arraylike."""
      assert isinstance(fun_name, str), f"fun_name must be a string. Got {fun_name}"
      if any(not _arraylike(arg) for arg in args):
        pos, arg = next((i, arg) for i, arg in enumerate(args)
                        if not _arraylike(arg))
        msg = "{} requires ndarray or scalar arguments, got {} at position {}."
>       raise TypeError(msg.format(fun_name, type(arg), pos))
E       TypeError: union1d requires ndarray or scalar arguments, got <class 'list'> at position 0.
E       Falsifying example: test_jax_union1d(
E           on_device='cpu',
E           frontend='jax',
E           backend_fw='numpy',
E           dtype_and_x=(['float32', 'float32'],
E            [array([-1.], dtype=float32), array([-1.], dtype=float32)]),
E           size=0,
E           fill_value=0,
E           fn_tree='ivy.functional.frontends.jax.numpy.union1d',
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=0,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.3', b'AXicY2AAAUYGBjiNzAYBAABqAAU=') as a decorator on your test case

**Comment by stalemate1** [comment]
First of all, thanks a lot for such an elegant review. I did make quite a few changes. Now tests are passing for all the back-ends.  However, instead of `valid` I used `numeric` because I was always running into error due to `bool` dtype.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,
its currently failing for the numpy and tensorflow backend with `AssertionError: returned dtype = float32, ground-truth returned dtype = float16`
Can you look into it?
The rest looks good

Thanks

**Comment by stalemate1** [comment]
@sherry30 I have trouble understanding how to fix such errors could you please help me understand how to fix such errors.

**Comment by sherry30** [comment]
Generally the dtype errors can be resolved by just type casting to the correct dtype in the function (which usually the dtype of the input array). But I would suggest debugging this function on the inputs it is failing on to make sure that its not some problem in the backends and is a problem in the frontend

**Comment by stalemate1** [comment]
Hello @sherry30 there is a problem with type promotions. Every time I `concat` two arrays there are 3 cases

1) If one of the dtypes is `float16 `and the other one is either `int16` and above or `uint16` or above the output dtype is `float32`.
2) If one of the dtypes is `float32 `and the other one is either `int32` and above or `uint32` or above the output dtype is `float64`.
3) Similarly with `complex dtypes`

Should I fix all of these? or just pass Integer or Floating point value in the `ivy_test` because there is no problem with type promotions in any other cases.

**Comment by stalemate1** [comment]
Does this mean that the problem is in the backend or is it in the frontend

**Review by sherry30 — CHANGES_REQUESTED** [review]
In the backend, we use ivy promotion table to determine which dtype it should be.
Is the promotion in this function done through numpy's promotion table?
if so then you can use `promote_numpy_dtypes` in the frontend and that should work.

Thanks

**Comment by stalemate1** [comment]
Using `promote_numpy_dtypes` didn't help.

**Comment by stalemate1** [comment]
Hello @hirwa-nshuti could you please help me merge this function it has been here since a month.

**Comment by joaozenobio** [comment]
Hi @stalemate1! Thank for the PR, please pin when you need a review :smile:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
