### PR TITLE
Add examples to positive func in elementwise

### PR DESCRIPTION
**Pull request by sladyn98**
This pull request adds examples to positive func in reformatting elementwise.

Closes: https://github.com/unifyai/ivy/issues/6668

### CODE REVIEW

**Comment by sladyn98** [comment]
add_reformatting_checklist_elementwise

**Comment by Daniel4078** [comment]
> LEGEND
Oh!, I did not notice it because you did not change the legend of the reformatting task checklist. Let me have a look, thank you.

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
First, please fix these two formatting errors :
ivy/array/elementwise.py:1697 in public method `positive`:
        D412: No blank lines allowed between a section header and its content ('Examples')
ivy/container/elementwise.py:5672 in public method `positive`:
        D412: No blank lines allowed between a section header and its content ('Examples')
secondly, I suspect one of the examples you add need to be fixed as it does not show what will happen correctly, but I am not certain about this as the error log is jumbled.

**Review by Daniel4078 — APPROVED** [review]
I think you are good to go now. Thank you.

**Pull request merged**
