### PR TITLE
`numpy.roots` frontend function

### LINKED ISSUE #22147: numpy.roots

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #22147

### CODE REVIEW

**Review by AryanSharma21 — COMMENTED** [review]
Hey, @mobley-trent , I was going through the test logs, I realized that the function implemented here does not pass the test mainly because of `data type` 

except for TensorFlow backend shows irregularity in the output values such as

`E   AssertionError:  the results from backend tensorflow and ground truth framework numpy do not match
E    [-1.+0.j  0.+0.j]!=[-0.5+8388608.j -0.5-8388608.j] `

otherwise the test for other backends show that the ground truth function returns 
`float32` whereas function returns `complex64` 

I would like to be a part of this discussion further as well. Thanks

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hello please check the suggestions and make sure the tests are passing

**Comment by MahmoudAshraf97** [comment]
https://w2g.tv/en/room/?access_key=tllndoatr0208jwh8gxxxh

**Comment by MahmoudAshraf97** [comment]
Hello, are you still working on this?

**Comment by mobley-trent** [comment]
@MahmoudAshraf97 I'm trying to figure out how to map the correct dtype to the output according to the inputs

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
