### PR TITLE
fixing out of bound indexing errors in ivy.array

### LINKED ISSUE #19744: [Bug]: Indexing error in ivy.array
### Bug Explanation

Error is raised when endpoint is larger than len of dim. 

cc @AnnaTz 

### Steps to Reproduce Bug

```
>>> import ivy
>>> ivy.array([1,2,3])[:5]
<traceback object at 0x7f8e310bfe80>
Traceback (most recent call last): #relevant error stack
IndexError: index 3 is out of bounds for axis 0 with size 3 
```

### Environment

Colab, Ubuntu 

### Ivy Version

The issue exists in the current Github repo and not i released version of ivy

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

_No response_

### PR DESCRIPTION
**Pull request by ShreyanshBardia**
I am still testing this, but this should ideally close #19744.
@sagewhocodes would you mind taking a look

### CODE REVIEW

**Comment by sagewhocodes** [comment]
Could you please remove the print statements from the code?

**Comment by ShreyanshBardia** [comment]
@sagewhocodes done

**Comment by sagewhocodes** [comment]
Great!, I've requested a review from Anna.

**Comment by ShreyanshBardia** [comment]
@AnnaTz this looks fine to me now, can you please review this once?

**Comment by theRealBird** [comment]
@sagewhocodes assigning this PR to you as you have already reviewed it. Not sure how I was introduced here haha. 
Thanks!

**Comment by AnnaTz** [comment]
Hi @ShreyanshBardia, I already pushed a fixed for this issue on Friday! 
This was reported to me by @sagewhocodes and I told them I would make sure to fix it. I didn't expect someone else to work on this at the same time. Sorry to have bypassed your work!

**Comment by AnnaTz** [comment]
> Hi @AnnaTz, thanks for looking into the issue. I checked the update but it seems some bugs still exist. Below is an example
> 
> ```
> import ivy
> ivy.array([1,2,3])[5:]
> ```

This works fine on my end.

**Comment by ShreyanshBardia** [comment]
Yes I did, here's a colab [link](https://colab.research.google.com/drive/1t_B1Ms_jDdT743c1Fb44CALpd0iNjS0i?usp=sharing) to reproduce

**Comment by AnnaTz** [comment]
> Yes I did, here's a colab [link](https://colab.research.google.com/drive/1t_B1Ms_jDdT743c1Fb44CALpd0iNjS0i?usp=sharing) to reproduce @AnnaTz I think the following line is causing the issue
> 
> ```
> q_i = (ivy.array(q_i)
>           if len(q_i) or start == stop or idx.stop is not None
>           else ivy.arange(0, s, 1)
>       )
> ```

It runs in the link as well.
image

**Comment by AnnaTz** [comment]
Oh now I see what you mean. Yeah I'll look into that as well. The line you pointed out was needed to handle some other cases but it will probably need to be modified. Thanks for flagging this!

**Comment by ShreyanshBardia** [comment]
Yes it does run, but it is not the correct behaviour, that's what I meant. Sorry for the confusion.
```
import numpy as np
np.array([1,2,3])[4:]
Out[31]: array([], dtype=int64)
```

**Comment by ShreyanshBardia** [comment]
@AnnaTz I think the logic leaves out some edge cases too.

```
ivy.array([1,2,3])[-10::-1]
Out[38]: ivy.array([1])
np.array([1,2,3])[-10::-1]
Out[39]: array([], dtype=int64)
```

**Comment by AnnaTz** [comment]
These are fairly easy to fix, but I don't understand why they are not being caught by the test.

**Comment by AnnaTz** [comment]
The cases you flagged should also be working now.

**Comment by sagewhocodes** [comment]
@ShreyanshBardia can you close this PR if the request changes have been done?

**Comment by ShreyanshBardia** [comment]
Thanks for the prompt solution!
@AnnaTz @sagewhocodes

**Pull request closed without merging**
