### PR TITLE
to_grayscale

### LINKED ISSUE #21984: to_grayscale

### PR DESCRIPTION
**Pull request by rohinish404**
closes #21984

### CODE REVIEW

**Review by sondertg — COMMENTED** [review]
Thanks for you great effor! However, from the CI results, I see that the test function you wrote is failing. Could you please make it to pass tests. If you get stuck, I can check in detail when I have some time. ( in three-four days)

**Comment by rohinish404** [comment]
Yeah i was having difficulty writing test function. Could you suggest what changes should i make in test function.

**Comment by ozogxyz** [comment]
@rohinish404 @sondertg  You can use the `_chw_image_shape_helper()` helper function that I wrote to pass intended shape.

**Comment by rohinish404** [comment]
@sondertg are you free now? Can you suggest the changes i should make in test function?

**Pull request closed without merging**
