### PR TITLE
Adding mathematical function to ivy frontend 

### LINKED ISSUE #17726: Numpy Frontend ToDo
#17726

### PR DESCRIPTION
**Pull request by roshandhanasekaran**
close #17726

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by roshandhanasekaran** [comment]
Will do that !

Kind regards
Roshan

**Comment by roshandhanasekaran** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

I believe I've successfully linked my issue as requested. Please let me know if there are any additional changes that need to be made.

**Comment by roshandhanasekaran** [comment]
hi, i have made the changes in the .idea folder files please check :)

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
The `.idea`  changes in your PR are still being shown, kindly remove any changes you made in that folder, thanks :slightly_smiling_face:

**Comment by roshandhanasekaran** [comment]
> The `.idea` changes in your PR are still being shown, kindly remove any changes you made in that folder, thanks 🙂

 I've made the changes you requested. Now, there are only two files with modifications, and the .idea files have been excluded.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
