### PR TITLE
Added log10 to ivy paddle frontend (#16507)

### PR DESCRIPTION
**Pull request by JagjeetSunghera**
#16507 completed

### CODE REVIEW

**Comment by JagjeetSunghera** [comment]
dear @Ookamice, please review my PR, i think there is some issue with run_test(1). all PRs are suffering from it.

**Review by JagjeetSunghera — COMMENTED** [review]
looks ok

**Comment by Ookamice** [comment]
@JagjeetSunghera 
Hiya, thank you for your contributions. From an initial look, the logic appears to be perfect. I'll run your testcase in a github codespace due to the intelligent-test-pr's bugs. I'll let you know the result! 🚀

**Comment by Ookamice** [comment]
Ran the test and they all passed except for jax but I believe it has to do with ivy.log10's backend implementation and not your frontend logic. Thank you for your work!! 😄

**Pull request merged**
