### PR TITLE
feat: Add tensorflow Gather nd raw ops

### LINKED ISSUE #27443: GatherNd

### PR DESCRIPTION
**Pull request by TalhaKhalil**
# PR Description

## Related Issue

Closes #27443

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by TalhaKhalil** [comment]
Hi @vedpatwardhan 

I have been working on this issue with @he11owthere and @NripeshN 
All the test cases are passing on my local. 

But while I was working with @he11owthere I had issues where some of the test cases passed and some didn't so he consulted me with the fix I've made in this PR.

Pls @vedpatwardhan look into this solution and let me know if there are any changes that needs to be made.

**Comment by vedpatwardhan** [comment]
Hey @TalhaKhalil, thanks for creating the PR, I'll leave this with @Ishticode to review as it's related to gather 😄

**Comment by TalhaKhalil** [comment]
Hi @vedpatwardhan @Ishticode could you please provide me with any updates regarding the PR.

**Review by Ishticode — APPROVED** [review]
hi @TalhaKhalil 
Thank you very much for the PR. I have ran the tests locally with over 500 examples and they pass. I made a minor update to the function signature. Will merge now. Thanks for contributing :)

**Pull request merged**
