### PR TITLE
feat: add paddle tolist

### LINKED ISSUE #23649: tolist

### PR DESCRIPTION
**Pull request by Anteemony**
# PR Description

## Related Issue

Close #23649

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Anteemony** [comment]
Hello, I believe the errors come from `helpers.test_frontend_function` during the tests.
Paddle.tolist returns a python list or number and not an array. So array operations will not work on it
The test pass when I add `test_values=False`  to helpers.test_frontend_function` in the test file.
Checking the frontend function manually also gives expected results.
Should I go ahead with this solution?

**Comment by Anteemony** [comment]
Hello @Daniel4078 please could you leave a review. I don’t know why

**Comment by Anteemony** [comment]
Daniel could you please guide me on what’s happening? I don’t know why it’s causing failed tests

**Comment by Daniel4078** [comment]
Sorry for the delay, I just wake up. Will check it out now.

**Comment by Daniel4078** [comment]
I did not see any tolist tests failing on my end though? Can you give some more context about the problem you faced?

**Comment by Anteemony** [comment]
I used to get an Assertion error before with the info that the data types and array sizes do not match. 
But I reran the tests today and I'm getting a different error on my codespace.

**Comment by Anteemony** [comment]
image

I wonder if this has anything to do with my setup. And sorry for the late reply on my end too @Daniel4078

**Review by Daniel4078 — APPROVED** [review]
Looks good to me now with no relavent tests failing in the checks

**Pull request merged**
