### PR TITLE
added numpy.random.wald function

### LINKED ISSUE #22338: wald
numpy.random frontend function wald

### PR DESCRIPTION
**Pull request by VedantPol**
Closes #22338
added numpy.random.wald function along with test

### CODE REVIEW

**Comment by VedantPol** [comment]
#22338

**Comment by yopknopixx** [comment]
@VedantPol Please include the open issue in the PR description.
I see a lot of tests failing related to Numpy front-end. Can you verify that those are not caused by the changes you made?

**Comment by VedantPol** [comment]
hey @yopknopixx ,
Updated the PR description to link the issue.
Thanks

**Comment by yopknopixx** [comment]
@VedantPol In order to verify, can you run the failing tests on the base from `unify:main` before your commits? Thanks!

**Comment by VedantPol** [comment]
@yopknopixx updated the head of my branch to unify:main  at this moment which is `commit hash 01cc6704dbf5eaa97744d446947ee4703bd2f173` we can compare the unify: main and my PR  branch to see the test that is failing in my case and the main branch.

**Comment by VedantPol** [comment]
Same test cases are failing when compared to latest commit on main branch  https://github.com/unifyai/ivy/actions/runs/5960261928/job/16167275847 
indicating my changes did not affect the already failing test cases Thanks

**Comment by yopknopixx** [comment]
@VedantPol Thank you for contributing! Merging.

**Pull request merged**
