### PR TITLE
Add Instance Methods to PyTorch Frontend #3612 - sinc #21142

### LINKED ISSUE #21142: sinc

### PR DESCRIPTION
**Pull request by alexkoziell**
Close #21142

### CODE REVIEW

**Comment by theRealBird** [comment]
Hi @alexkoziell 
Thank you for your patience and for contributing to Ivy. Great work on the PR, looks good to me! 
Before it can be merged, could you please resolve the merge conflicts? 
Thanks!

**Comment by alexkoziell** [comment]
@theRealBird Have fixed the merge conflicts! Please may you double-check everything is still working?

**Comment by theRealBird** [comment]
Hi @alexkoziell,
Everything looks great! I was OOO yesterday so could not merge your PR in time, can you please remove the conflicts once more? Thanks!

**Comment by alexkoziell** [comment]
@theRealBird Updated again!

**Comment by theRealBird** [comment]
Hi @alexkoziell,
Thanks for resolving the conflicts. At the moment on the tests dashboard, I see a lot of new failures being introduced via this PR, but none seem to be related to your change. Things look good to me. Thanks!

**Pull request merged**
