### PR TITLE
Torch pow

### PR DESCRIPTION
**Pull request by kurshakuz**
Closes https://github.com/unifyai/ivy/issues/10080

### CODE REVIEW

**Comment by kurshakuz** [comment]
Depends on https://github.com/unifyai/ivy/issues/9988 to be fixed

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ZoeCD** [comment]
> Depends on #9988 to be fixed

Hi! I saw the issue is resolved. Do you want me to review and merge this PR?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
