### PR TITLE
add round function

### PR DESCRIPTION
**Pull request by mazy06000**
#3809

### CODE REVIEW

**Comment by mazy06000** [comment]
Hello @johanjino, I updated my code adding unsupported dtypes for torch and tensorflow.

The round function is compatible with all numeric types, but I got this error for int8 and in16:

    def raise_from_not_ok_status(e, name):
      e.message += (" name: " + name if name is not None else "")
>     raise core._status_to_exception(e) from None  # pylint: disable=protected-access
E     tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Round}} = Round[T=DT_INT8]
E     All kernels registered for op Round:
E       device='GPU'; T in [DT_INT64]
E       device='GPU'; T in [DT_INT32]
E       device='GPU'; T in [DT_DOUBLE]
E       device='GPU'; T in [DT_FLOAT]
E       device='GPU'; T in [DT_HALF]
E       device='CPU'; T in [DT_INT64]
E       device='CPU'; T in [DT_INT32]
E       device='CPU'; T in [DT_DOUBLE]
E       device='CPU'; T in [DT_FLOAT]
E       device='CPU'; T in [DT_HALF]
E      [Op:Round]

So, at the moment only float are using.

Let me know what do you think. Thank you!

**Comment by johanjino** [comment]
Hey @mazy06000, we do not need to redefine the `ivy.round` in the Ivy functional API because it already exists. You can use that round function to implement your frontend.

Also, please make sure that no other files are edited or changed. Some xml and iml files seems to be altered, probably due to local testing, make sure this is not changed in the PR.

**Comment by johanjino** [comment]
Ill take a look at the compatibility with `int` datatypes once these are fixed 😀

**Comment by mazy06000** [comment]
Hi @johanjino, you're right, I didnt see that the round function already exist. So, I removed the round function that I added in Ivy functional API, and I restored xml and iml files like before.

**Comment by johanjino** [comment]
@mazy06000 , I apologize for the delay, a huge backlog caused this.

The tests seem to be perfect. I think its all ready to be merged. But could you remove the `iml` file. Not sure how this change crept in. If you had removed it before it must be a mistake from our side, I apologize if thats the case as well 🙂

**Comment by shadmeoli** [comment]
#3810

**Pull request closed without merging**
