### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Lancelot03**

### CODE REVIEW

**Comment by kimbring2** [comment]
@Lancelot03 Hello, you need to write a frontend function in [functions.py](https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/tensorflow/functions.py) of Tensorflow frontend. 

Additionally, you need to make a test code for that under [test_tf_functions.py](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tf_functions.py) file.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Please follow @kimbring2's remarks. Thanks.

**Comment by Lancelot03** [comment]
@kimbring2  thanks for the help, please review the changes.

**Comment by kimbring2** [comment]
@Lancelot03 Ok, I am checking it

**Comment by Lancelot03** [comment]
@kimbring2  should I make another pr

**Comment by kimbring2** [comment]
@Lancelot03 Yes, it seems like it is too late. I will update it soon myself. Please open another commit.

**Pull request closed without merging**
