### PR TITLE
Implemented lu for jax

### LINKED ISSUE #18210: lu

### PR DESCRIPTION
**Pull request by moezAhmad**
close #18210

### CODE REVIEW

**Comment by moezAhmad** [comment]
@zaeemansari70 Thank you for reviewing my pr.
Apologies for the inconvenience. I was waiting for your reply to guide me what should I do as I could not find any backend implementation for lu_factor due to which function gives exceptions when it is executed so even if test cases are correct they will eventually fail

**Review by zaeemansari70 — COMMENTED** [review]
Hi @moezAhmad 

This is just a dummy call as we do not have a `lu_factor()` backend.
You can either make a PR and add it in the backend first or either you can implement this compositionally using ivy functions :slightly_smiling_face:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
