### PR TITLE
add reduce method to wrapped functions

### PR DESCRIPTION
**Pull request by Abdelrhman-Hosny**
### Problem

When a `ufunc` was wrapped using `_wrap_method`, some of the attributes it had couldn't be accessed

e.g. you can access `ufunc.reduce` however, `_wrapped_ufunc.reduce` didn't exist, therefore when `_wrapped_ufunc` was passed as a parameter to numpy's `-wrap_reduction` method the following error occurred and caused 120 of the 124 tests to fail

After the addition of the reduce wrapper, here are the results

The remaining 4 errors are from a type error from `ivy.pinv` which is the only one not currently working unlike before when all of them weren't.

### CODE REVIEW

**Comment by Abdelrhman-Hosny** [comment]
This also fixed some of the tests in `test_math.py`.

Not really fix as much as uncover a new problem which is 0-D arrays in numpy (e.g. x.shape = (3,)) return `False` when passed through `ivy.is_array`

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by Abdelrhman-Hosny** [comment]
> Thanks a lot for the PR!
> 
> I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? slightly_smiling_face

I've rebased this PR such that `git diff master` only shows the line I added as output

e.g.

```
git diff master

diff --git a/ivy/func_wrapper.py b/ivy/func_wrapper.py
index f71f5c880..d81cf47a7 100644
--- a/ivy/func_wrapper.py
+++ b/ivy/func_wrapper.py
@@ -56,6 +56,8 @@ def _wrap_method(fn):
         _method_wrapped.__name__ = fn.__name__
     _method_wrapped.wrapped = True
     _method_wrapped.inner_fn = fn
+    _method_wrapped.reduce = fn.reduce
+
     return _method_wrapped
```

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Review by djl11 — CHANGES_REQUESTED** [review]
The code you are modifying is part of a very general function for wrapping any method. This change will cause errors when the wrapped method does not have a reduce attribute. Could you please instead add `_method_wrapped.__dict__ = dict(**_method_wrapped.__dict__, **fn.__dict__)` or something similar, which copies over any extra attributes of the wrapped method? I'm not sure this will exactly work, but something similar will work. Alternatively, for now you could explicitly check if the inner functions has attribute `reduce` with hasattr(fn, 'reduce')`

**Comment by Abdelrhman-Hosny** [comment]
already added as a part of #143

**Pull request closed without merging**
