### PR TITLE
implemented tensorflow frontend linalg qr

### LINKED ISSUE #19009: qr

### PR DESCRIPTION
**Pull request by OmarAnwar19**
Close #19009

### CODE REVIEW

**Comment by OmarAnwar19** [comment]
- Working on fixing the failing test, just having some issues running pytest on M1 Mac.

**Comment by tomatillos** [comment]
Hi, did you get this fixed?

**Comment by OmarAnwar19** [comment]
> Hi, did you get this fixed?

Hey, sorry, I'll try to get it done this weekend. I'm still having issues with getting the dev environment working on M1 Mac

**Comment by OmarAnwar19** [comment]
@tomatillos Hey, I think I'm finished with this PR. The checks failing aren't related to anything, just some git stuff. The function itself and its test are working as intended. Let me know what you think.

**Comment by tomatillos** [comment]
LGTM, thanks!

**Pull request merged**
