### PR TITLE
Adds insert()

### LINKED ISSUE #18168: insert

### PR DESCRIPTION
**Pull request by aryanxk02**
fixes #18168

### CODE REVIEW

**Comment by aryanxk02** [comment]
Hello @kurshakuz, any follow up on how do I resolve the tests?

**Comment by aryanxk02** [comment]
> Hello @kurshakuz, any follow up on how do I resolve the tests?
> 
> 

Hi @kurshakuz, please suggest changes 🙂

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! 

Please resolve that issue:

```
E       TypeError: insert() got an unexpected keyword argument 'array'
```

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
