### PR TITLE
Reformatting docstring for unique_inverse

### PR DESCRIPTION
**Pull request by Arkhymadhe**

### CODE REVIEW

**Review by chie2727 — CHANGES_REQUESTED** [review]
Hi @Archymade , the examples are looking good so far.

First off there are two changes you need to make:

1. Update the URL at line 272 with the correct one for your function, then keep this URL on just one line and then add `#noqa` at the end.
2. Include linespaces after every single example's output.

**Review by chie2727 — CHANGES_REQUESTED** [review]
Hi @Archymade , just a couple more changes to make:

- [ ] 1. Remove the commits to `test_array_api` from this PR
- [ ] 2. The `ivy.random_normal()` examples are not using `ivy.array()` as an input so please remove these examples.
- [ ] 3. Include a functional example that uses `ivy.Container` as an input.
For example: https://github.com/unifyai/ivy/blob/7b741439dc15db949a27d6deb530c3f17dc49e41/ivy/functional/ivy/elementwise.py#L246
(Refer to the Docstring Guide for more details!)
https://github.com/unifyai/ivy/blob/master/docs/partial_source/deep_dive/11_docstring_examples.rst
- [ ] 4. Re-write line 183 as `Using :code:'ivy.Array' instance method:`
- [ ] 5. Under `Instance Method Examples` include one `ivy.Container instance method` example.

**Comment by Archymade** [comment]
Got it👍

**Comment by chie2727** [comment]
Hi @Archymade , please let me know when you have finished making the changes!

**Comment by Archymade** [comment]
> Hi @Archymade , please let me know when you have finished making the changes!

No problem! Sorry I haven't been working on it seriously.  My PC  got bad. Just got a new one.

**Comment by Archymade** [comment]
@chie2727 Is it me or are there a lot more tests than before?

**Comment by chie2727** [comment]
Hi @Archymade , thanks for the reply.
Don't worry about the increased number of tests! It's only `test-docstrings` that you need to check and make sure is passing!

**Comment by Arkhymadhe** [comment]
I think I've got the hang of it. The only issue now is the Container examples. I can't seem to get them to work, because I can't run the tests on my local machine. Don't know why. Can you help with that?

**Comment by chie2727** [comment]
Hi @Arkhymadhe , ivy.Container inputs should be working fine with random_normal.
You might run into issues with ivy.Container instance methods however. If this happens to be the case let me know!

clip_8

**Review by chie2727 — CHANGES_REQUESTED** [review]
.

**Comment by chie2727** [comment]
Hi @Arkhymadhe , let me know if you're still working on this task otherwise I'll need to close this PR for inactivity.

**Comment by Arkhymadhe** [comment]
Sorry, I haven't been available to work on the project. Stuff came up in real life. Is the task still available to work on?

**Pull request closed without merging**
