### PR TITLE
Reformat linear_algebra (Outer method): Decorate outer methods for all backends

### PR DESCRIPTION
**Pull request by AlyMuhammadAly**

### CODE REVIEW

**Comment by DragosStoican** [comment]
Hi @AlyMuhammadAly Can you link this to the corresponding issue? You should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues) . Thanks! 😁

**Comment by AlyMuhammadAly** [comment]
It's already linked. I needed to follow the format but I left the link of this PR down in the [issue](https://github.com/unifyai/ivy/issues/792#issuecomment-1317895639) comment section

**Comment by DragosStoican** [comment]
Hi @AlyMuhammadAly , the instructions says `Create a new issue with the title being just the name of the sub-task you would like to work on.`, in your case that means creating a new issue with the name "outer".

Then on the ToDo list you add a comment with the `outer` issue you just created. This is to ensure that the ToDo list stays up to date and people can see what piece of work you've picked up. 

Then we can link this PR to the `outer` issue. 😁

**Comment by AlyMuhammadAly** [comment]
This PR should resolve #7108

**Comment by DragosStoican** [comment]
Hi Aly, as the open tasks indicates, the updates to the function should be applied for the:

1. ivy API
2. all backend APIs
3. container static methods
4. array instance methods
5. container instance methods
6. array operators
7. array reverse operators
8. container operators
9. container reverse operators

I can see you've applied the changes to all the backend API, but the array instance method, the container static method and the container instance method still need to have their docstrings updated. Could you look at updating those?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by AlyMuhammadAly** [comment]
I'd like to continue working on this PR

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by AlyMuhammadAly** [comment]
> I'd like to continue working on this PR

I'd like to continue working on this PR

**Comment by AlyMuhammadAly** [comment]
I'm going to continue working on this PR in Jan 23 if thats fine with you. @DragosStoican Could you please confirm?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
