### PR TITLE
Merge pull request #1 from unifyai/master

### PR DESCRIPTION
**Pull request by ArpitKhandelwal-developer**
Add ceil _Mathematical Functions to Paddle Frontend

### CODE REVIEW

**Review by ArpitKhandelwal-developer — COMMENTED** [review]
Added ceil_ function

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ArpitKhandelwal-developer** [comment]
@MahmoudAshraf97 Sir how to merge this?

**Comment by ArpitKhandelwal-developer** [comment]
@kurshakuz @MahmoudAshraf97 Please check now

**Comment by MahmoudAshraf97** [comment]
Hello, you are trying to add a frontend function but you added it in the backend, please note that frontend functions only use ivy functions not the native functions

**Pull request closed without merging**
