### PR TITLE
Reformatted map_nest_at_index

### LINKED ISSUE #5848: map_nest_at_index
Reformat nest #793

### PR DESCRIPTION
**Pull request by roo-afk**
Close #5848

### CODE REVIEW

**Comment by JerryGCDing** [comment]
Hi @roo-afk, thank you for contributing to Ivy 😃! Can you fix the issues in the failing `lint` and `test-docstrings` associated with the PR?

**Comment by roo-afk** [comment]
Yes, I'll go ahead and address those tests.

**Comment by roo-afk** [comment]
@JerryGCDing, I fixed the lint and docstring errors in nest.py. Currently, the failing tests are coming from other files.

**Comment by JerryGCDing** [comment]
Looks perfect, I'll go ahead and merge it.

**Pull request merged**
