### PR TITLE
Review SVD function (Linear Algebra) implementation

### PR DESCRIPTION
**Pull request by nnitiwe-dev**

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by nnitiwe-dev** [comment]
Okay, @djl11 I sent an invite to you which gives you direct access to my Forked Repository. Does this solve the access issue?

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

**Comment by nnitiwe-dev** [comment]
> * All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
> * All Ivy methods should have type-hints and doc strings
> * All backend methods should have type-hints, but no doc strings.
> * All Array API methods should be moved to the correct sub-modules and files.

Hi, @djl11  I have updated my pull request to meet the listed Guidelines. Initially, my **Backend** PR met the following:
- Defined with def func_name explicitly, no lambdas or direct binding.
- All Array API methods should be moved to the correct sub-modules and files.

The updated PR corrected the following:
- All backend methods should have type-hints, but no docstrings.

Kindly review for correctness.

**Review by djl11 — CHANGES_REQUESTED** [review]
The unit tests for test_svd seem to be failing in CI. Were you able to get the tests passing locally?

**Comment by nnitiwe-dev** [comment]
> Details

Hi @djl11 ,
I have tried running it locally. It keeps flagging `np.bool` error under `mxnet`.

**Review by djl11 — CHANGES_REQUESTED** [review]
The unit tests are still failing in CI, could you update so the unit tests for test_svd in test_ivy/tesy_arry_api all pass locally?

**Comment by nnitiwe-dev** [comment]
Hi @djl11  I cant seem to find what I am getting wrong.  I however have updated the functions from:
 ```svd(x:Union[_ivy.Array],full_matrices: bool = True) -> Union[_ivy.Array, Tuple[_ivy.Array]]:```
to
```svd(x:Union[_ivy.Array,_ivy.NativeArray],full_matrices: bool = True) -> Union[_ivy.Array, Tuple[_ivy.Array,...]]:```

I don't know if this will possibly fix it.

**Review by djl11 — CHANGES_REQUESTED** [review]
Your implementation is in the wrong location, please remove from core and move to the correct file in array_api subfolder. Check out contributor guide for more info (https://lets-unify.ai/ivy/contributing.html)

**Comment by nnitiwe-dev** [comment]
Hi, @djl11  I have moved the functions to the appropriate subfolder and have fixed the initial bugs I flagged on Discord.

**Review by 1Doomdie1 — APPROVED** [review]
Hey, thank you for contributing!
The changes look good to me. 
I will mention Dan to have a look as well before merging.

**Review by 1Doomdie1 — CHANGES_REQUESTED** [review]
Hey, thank you for contributing!
The changes look good to me. 
One more thing you need to do is resolve the conflicts. 

Once you have done that, request another Code Review and we will take a look

**Comment by nnitiwe-dev** [comment]
Hi, @1Doomdie1  I have resolved the conflicts. Thanks for your response.

**Review by djl11 — APPROVED** [review]
Not sure why the tests didn't run on this PR, but I just ran them all locally and they are working fine. Thanks!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
