### PR TITLE
added jax.numpy.pad function

### PR DESCRIPTION
**Pull request by x0axz**
Close https://github.com/unifyai/ivy/issues/11779

### CODE REVIEW

**Comment by x0axz** [comment]
@nathzi1505 Please review this commit.

**Comment by x0axz** [comment]
@nathzi1505 please review this.

**Comment by nathzi1505** [comment]
Hi @x0axz, 
Thanks for the commit. 
Can you please review the conflicts that are being pointed out?

**Comment by x0axz** [comment]
@nathzi1505 Resolved the conflicts.

**Comment by x0axz** [comment]
@nathzi1505 Please review this PR.

**Comment by x0axz** [comment]
Closed because there was a force push in Ivy's codebase that created too many conflicts, so I closed this PR and opened a new PR: https://github.com/unifyai/ivy/pull/12799

**Pull request closed without merging**
