### PR TITLE
reformat multinomial

### PR DESCRIPTION
**Pull request by civanakbas**
#1084

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
hi @civanakbas. Thanks for the PR. Could you kindly make the changes required mentioned under the test-numpy-style-docstrings below. Let me know if something is unclear. : )

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @civanakbas . It looks good but could you kindly add more examples based on the different arguments of multinomial function. Check our the [guide here](https://lets-unify.ai/ivy/contributing/6_docstring_examples.html). Let me know if anything is unclear : )

**Comment by civanakbas** [comment]
Hi @Ishticode. I added more examples. I believe the examples covers the function well. Let me know if I missed any and/or should add more.

Also some checks seem to be failing but I don't think they are related to my commit. Let me know if they are in any way.

**Review by Ishticode — APPROVED** [review]
Looking great.  I will go ahead and merge this. Thanks for the contribution @civanakbas : ).

**Pull request merged**
