### PR TITLE
added  acos to the  paddle.tensor.math Mathematical Functions

### PR DESCRIPTION
**Pull request by raj921**

### CODE REVIEW

**Comment by raj921** [comment]
close #15396

**Review by juliagsy — COMMENTED** [review]
Hello! Thanks for the great work! The code and tests status look good to me, but there are merge conflicts at the moment, could you please resolve them and we could get it merged if the test status remains green! Thanks a lot!

**Comment by raj921** [comment]
hey @juliagsy thank you review my pr  I fixed the conflict  all tests are passed

**Review by juliagsy — APPROVED** [review]
Thanks for contributing!

**Comment by raj921** [comment]
Thanks for merging

**Pull request merged**
