### PR TITLE
frontend.jax.numpy.logic.fromfunction

### LINKED ISSUE #11995: fromfunction
Working on (#8431-> #17806)

### PR DESCRIPTION
**Pull request by Sarvesh-Kesharwani**
Closes #11995

### CODE REVIEW

**Comment by hirwa-nshuti** [comment]
Hey @Sarvesh-Kesharwani 
Would you elaborate more on this so I can help out?
If possible provide use case examples 😊

Thanks

**Comment by Sarvesh-Kesharwani** [comment]
Hey @hirwa-nshuti 
I researched, found and implemented the main functionality of the fromfunction()
now one handling one parameter is remaining ie, "like"
Code_gy6H8AEf7H

i studied it but couldn't understand its usecase,
could you please give me a hint how do i understand this parameter?


thank you

**Comment by hirwa-nshuti** [comment]
Hey I looked into the numpy version of the function,
You can follow the examples they showed to understand what it does: https://numpy.org/doc/stable/reference/generated/numpy.fromfunction.html#numpy.fromfunction

**Comment by hirwa-nshuti** [comment]
Well if the function is more complex and hard to understand I would recommend you take on another task.
We might work on this one later in the future😊

**Comment by sreegandh804** [comment]
Hey @Sarvesh-Kesharwani , 
Please refer to the comment I made on this issue (https://github.com/unifyai/ivy/issues/12379) 🙂.
Thank You.

**Comment by hirwa-nshuti** [comment]
Hey @Sarvesh-Kesharwani 

Would you copy your changes to a new PR as the recent changes to the repo introduced many conflicts to your PR.
Feel free to tag me there😊
After that you can close this PR

Thanks

**Comment by hirwa-nshuti** [comment]
Hey this PR is conflicted I am going to close it for now feel free to open another one

**Pull request closed without merging**
