### PR TITLE
Added embedding in sparse function module for torch frontend

### PR DESCRIPTION
**Pull request by ukj02**

### CODE REVIEW

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Hello, I found that there are some formatting errors in your code:
ivy/functional/frontends/torch/sparse_functions.py:5:89: E501 line too long (117 > 88 characters)
ivy/functional/frontends/torch/sparse_functions.py:6:89: E501 line too long (113 > 88 characters)
ivy_tests/test_ivy/test_frontends/test_torch/test_sparse_functions.py:3:1: F401 'hypothesis.strategies as st' imported but unused
ivy_tests/test_ivy/test_frontends/test_torch/test_sparse_functions.py:46:6: W292 no newline at end of file
I suspect there may be more actural bugs and I will comment on them when I found them.
By the way, is this pull request related to any issues? Thank you.

**Comment by ukj02** [comment]
> Hello, I found that there are some formatting errors in your code: ivy/functional/frontends/torch/sparse_functions.py:5:89: E501 line too long (117 > 88 characters) ivy/functional/frontends/torch/sparse_functions.py:6:89: E501 line too long (113 > 88 characters) ivy_tests/test_ivy/test_frontends/test_torch/test_sparse_functions.py:3:1: F401 'hypothesis.strategies as st' imported but unused ivy_tests/test_ivy/test_frontends/test_torch/test_sparse_functions.py:46:6: W292 no newline at end of file I suspect there may be more actural bugs and I will comment on them when I found them. By the way, is this pull request related to any issues? Thank you.

Yes this is related to this issue https://github.com/unifyai/ivy/issues/3215

**Comment by Daniel4078** [comment]
One of the ivy team has just pushed an update to fix bfloat16 issue for torch backend for frontend tests, please make sure that you are testing for bfloat16 by using ivy.valid_float_dtypes or whatever proper ivy.valid_ dtypes, also make sure that implemented functions doesn't have unnecessary .unsupported_dtypes = {"torch": ("bfloat16",)} as this was used to make the test falsely pass.

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Please try and resolve the conflict with the main branch before pull from the main branch for the update to torch test, check my comment for more details. Thank you.

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Firstly, you are not supposed to leave those special lines( like <<<< HEAD) in your code.
Secondly, I found some formatting errors:
ivy/functional/frontends/torch/sparse_functions.py:8:1: E999 SyntaxError: invalid syntax
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py:75:1: W391 blank line at end of file
ivy_tests/test_ivy/test_frontends/test_torch/test_sparse_functions.py:7:1: F401 'ivy.functional.backends.numpy as ivy_np' imported but unused
ivy_tests/test_ivy/test_frontends/test_torch/test_sparse_functions.py:80:6: W292 no newline at end of file
Please fix these errors, thank you.

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
According to the test, there are two errors that you need to fix:
first, module 'ivy.functional.backends.torch' has no attribute 'embedding'. So there is no such function as ivy.embedding. In this case, you can convert your existing GitHub issue to request for the function to be added to Ivy. Meanwhile, you can select another frontend function to work on from the ToDo list or try to implement the function in a compositional way. If you’re stuck on a function which requires complex compositions, you’re allowed to reselect a function too!
second, embedding() got an unexpected keyword argument 'tensors' in your test. And it seems lik your test does not feed the correct arguments embedding need at all.
Thank you.

**Comment by ukj02** [comment]
> According to the test, there are two errors that you need to fix: first, module 'ivy.functional.backends.torch' has no attribute 'embedding'. So there is no such function as ivy.embedding. In this case, you can convert your existing GitHub issue to request for the function to be added to Ivy. Meanwhile, you can select another frontend function to work on from the ToDo list or try to implement the function in a compositional way. If you’re stuck on a function which requires complex compositions, you’re allowed to reselect a function too! second, embedding() got an unexpected keyword argument 'tensors' in your test. And it seems lik your test does not feed the correct arguments embedding need at all. Thank you.

So should I close this pull request?

**Comment by Daniel4078** [comment]
> > According to the test, there are two errors that you need to fix: first, module 'ivy.functional.backends.torch' has no attribute 'embedding'. So there is no such function as ivy.embedding. In this case, you can convert your existing GitHub issue to request for the function to be added to Ivy. Meanwhile, you can select another frontend function to work on from the ToDo list or try to implement the function in a compositional way. If you’re stuck on a function which requires complex compositions, you’re allowed to reselect a function too! second, embedding() got an unexpected keyword argument 'tensors' in your test. And it seems lik your test does not feed the correct arguments embedding need at all. Thank you.
> 
> So should I close this pull request?

You can check this piece of Deep dive guide(https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html#temporary-compositions) to help you decide what you may do.

**Comment by ukj02** [comment]
> > > According to the test, there are two errors that you need to fix: first, module 'ivy.functional.backends.torch' has no attribute 'embedding'. So there is no such function as ivy.embedding. In this case, you can convert your existing GitHub issue to request for the function to be added to Ivy. Meanwhile, you can select another frontend function to work on from the ToDo list or try to implement the function in a compositional way. If you’re stuck on a function which requires complex compositions, you’re allowed to reselect a function too! second, embedding() got an unexpected keyword argument 'tensors' in your test. And it seems lik your test does not feed the correct arguments embedding need at all. Thank you.
> > 
> > 
> > So should I close this pull request?
> 
> You can check this piece of Deep dive guide(https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html#temporary-compositions) to help you decide what you may do.

I think you have to add the ToDo label since I cannot do that.

**Comment by Daniel4078** [comment]
Do you mean adding a ToDo label for the issue this pull request is linked to right?

**Comment by ukj02** [comment]
Yes

**Comment by ukj02** [comment]
Like this issue https://github.com/unifyai/ivy/issues/2873

**Comment by Daniel4078** [comment]
Done

**Comment by Daniel4078** [comment]
If you think doing a compositional implementation of this is too hard, you can always leave this and choose another function to work on.

**Comment by Daniel4078** [comment]
If you do not want to try and implement the frontend function compositionally, then you can remove the Sub_Task label from the sub-task issue, rename the issue to ivy.<func_name>, add the Extension and Next Release labels, and then simply choose another frontend function to work on, leaving this original issue open. This issue will also still show up as open in the original ToDo list, helpfully preventing others from working on this problematic frontend function, which depends on the unimplemented ivy.<func_name>.

**Comment by Daniel4078** [comment]
If you want to leave this task and try another function, please tell me so I can help you do those changes to the relative issue and close this pull request. Thank you.

**Comment by ukj02** [comment]
> If you want to leave this task and try another function, please tell me so I can help you do those changes to the relative issue and close this pull request. Thank you.

Yeah I will choose another task. I have chosen this task https://github.com/unifyai/ivy/issues/3431.

**Pull request closed without merging**
