### PR TITLE
Added matrix_rank function to jax.numpy.linalg 

### PR DESCRIPTION
**Pull request by ukj02**
I was having a bit of trouble implementing the tests.

### CODE REVIEW

**Comment by modanesh** [comment]
Hey @ukj02 🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues).

**Comment by modanesh** [comment]
As I went through the changes, it appears that there're some unnecessary changes specifically regarding the spacing made to `custom_gradient_operators.py` and `test_jax_lax_custom_gradient_operators.py` and `test_jax_numpy_linalg.py`. Could you revert them back?
Also, there're lint check failures. Please take a look at them and resolve issues.
For the `test-frontend-jax`, according to the logs this is the error for why it's failing: `TypeError: matrix_rank() got an unexpected keyword argument 'a'`. Could you find an answer to it?

**Comment by ukj02** [comment]
Hi I made a few changes and am now getting the error "AssertionError: the return with a jax backend produced data type of int64, while the return with a numpy backend returned a data type of float32."

**Comment by modanesh** [comment]
You don't need to worry about that error. It is due to a problem with the backend implementation that will be fixed soon. Besides that, could you take a look at the lint test logs and do necessary changes?
As mentioned in my previous comment, it appears that there're some unnecessary changes specifically regarding the spacing made to custom_gradient_operators.py and test_jax_lax_custom_gradient_operators.py and test_jax_numpy_linalg.py. Could you revert them back?
Thanks!

**Comment by ukj02** [comment]
I have got the lint test passing and reverted the changes.

**Pull request merged**
