### PR TITLE
Add reduce_sum function to TensorFlow frontend  #3277

### PR DESCRIPTION
**Pull request by JonaOmara**

### CODE REVIEW

**Comment by JonaOmara** [comment]
@MarShaikh , please fix time and review my PR

**Comment by kimbring2** [comment]
@JonaOmara It seems like somebody already added the reduce_sum function.

**Comment by JonaOmara** [comment]
@kimbring2, I don't know why this happened but I created the issue first  to add the reduce_ sum function as it was an open task but then it was assigned to another person  @ankitdsi2010 after I made my pull request and later my issue was closed. So what should I do now?

**Comment by MarShaikh** [comment]
> @kimbring2, I don't know why this happened but I created the issue first to add the reduce_ sum function as it was an open task but then it was assigned to another person @ankitdsi2010 after I made my pull request and later my issue was closed. So what should I do now?

Hey @JonaOmara, sorry for the confusion. It seems like the task was already done before you made the first commits but after you started the issue but one of our team members. Going forward, we will keep this in mind, but I suggest you to please pick another function, I'm sure it won't take you more than 30mins to complete since you already know what to do. Please also don't forget to comment the issue name in your PR as well as it will avoid this type of mistake in the future! Again, sorry for this. We'll set up better protocols to avoid this from happening in the future.

**Comment by JonaOmara** [comment]
@MarShaikh , thanks for the clarification, I hope this doesn't happen again because the added code is exactly the same code I added but let me work on another task as you suggested. Thanks!

**Pull request closed without merging**
