### PR TITLE
Add Numpy Frontend maximum

### LINKED ISSUE #3505: maximum
Implement Numpy's maximum function. One of the tasks present in https://github.com/unifyai/ivy/issues/1525

### PR DESCRIPTION
**Pull request by aryanxk02**
This PR fixes #3505

### CODE REVIEW

**Comment by MrZilinXiao** [comment]
Hi, did you notice that there is a unit test exception here that is triggered by `test_numpy_maximum`?
https://github.com/unifyai/ivy/runs/7988276520?check_suite_focus=true#step:4:4997

**Comment by aryanxk02** [comment]
Hello @MrZilinXiao can you help me with the tests ? What can I do exactly so the PR passes the tests?

**Comment by MrZilinXiao** [comment]
The assertion tells that `with the sequence length being equal to the number of arrays in the arguments.`, meaning the hypothesis is generating an array and corresponding bool flag with different lengths. https://github.com/unifyai/ivy/runs/7988276520?check_suite_focus=true#step:4:5010

**Comment by MrZilinXiao** [comment]
Hi, @aryanxk02. Because it has been 28 days since your last activity on this PR, I am now closing it. Feel free to reopen it if you still wanna work on it.

**Pull request closed without merging**
