### PR TITLE
this is my first commit in fmin

### PR DESCRIPTION
**Pull request by mohansharma077**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by AryanSharma21 — COMMENTED** [review]
Hello @mohansharma077, The changes that you have made, Is there any open issue for the same  ? If yes, please link the open issues in the description of your pull request.

**Comment by a0m0rajab** [comment]
Related issue: https://github.com/unifyai/ivy/issues/20937

**Comment by mohansharma077** [comment]
@ivy-leaves check the issue zeros_initializer #20947

**Comment by mohansharma077** [comment]
i want to make a new pull request  for #20947 , but the previous  commit is submitted everytime, how can  send  only the second pull request.

**Comment by a0m0rajab** [comment]
You need to create a new branch to do that check this for datils: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches

**Pull request closed without merging**
