### PR TITLE
Close #14948

### LINKED ISSUE #14948: put

### PR DESCRIPTION
**Pull request by utkarsh-shrivastav77**
Added the features  put #14948

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by utkarsh-shrivastav77** [comment]
Sir I am working on this issue https://github.com/unifyai/ivy/issues/14948 and this is my frist contribution so please guide me

**Comment by utkarsh-shrivastav77** [comment]
Close https://github.com/unifyai/ivy/issues/14948

**Review by AryanSharma21 — COMMENTED** [review]
Hey, @utkarsh-shrivastav77 , you should edit the `description` of the PR, make it 
`close #issue_number` . This will associate the pull request with the created issue correctly.

**Comment by utkarsh-shrivastav77** [comment]
Sir I have updated

**Comment by AryanSharma21** [comment]
@utkarsh-shrivastav77 , I am just a fellow contributor just like you 😊 I am no sir... 
Besides what I tried to convey is that you have to write close #issue_number in the Description where you have written 'added the feature put' and not in comments. Thanks

**Pull request closed without merging**
