### PR TITLE
Paddle creation clone

### LINKED ISSUE #19201: clone

### PR DESCRIPTION
**Pull request by Kalachuchis**
Close #19201

### CODE REVIEW

**Comment by Kalachuchis** [comment]
Hi @RickSanchezStoic. I made some fixes. Requesting for a review. Thanks!

**Comment by RickSanchezStoic** [comment]
Hi @Kalachuchis  There are some errors occurring related to the test suite. Try updating your fork and have the latest changes from master.

**Comment by Kalachuchis** [comment]
Updated my fork.. but having trouble with tests. I tried checking the output for ivy.copy_array() and it was the same with the input for paddle.clone but still had AssertionError. help would be appreciated. here is the output of one test
```
____________________________________________________________________ test_paddle_clone[cpu-paddle-False-False] ____________________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.clone",
        dtype_and_x=helpers.dtype_and_values(available_dtypes=helpers.get_dtypes("valid")),
        test_with_out=st.just(False),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:562: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:576: in test_paddle_clone
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:837: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:118: in value_test
    assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

values = [[array(0, dtype=uint8)], [array([0], dtype=uint8)]], this_key_chain = None

    def assert_same_type_and_shape(values, this_key_chain=None):
        x_, y_ = values
        for x, y in zip(x_, y_):
            if isinstance(x, np.ndarray):
                x_d = str(x.dtype).replace("longlong", "int64")
                y_d = str(y.dtype).replace("longlong", "int64")
>               assert (
                    x.shape == y.shape
                ), "returned shape = {}, ground-truth returned shape = {}".format(
                    x.shape, y.shape
                )
E               AssertionError: returned shape = (), ground-truth returned shape = (1,)
E               Falsifying example: test_paddle_clone(
E                   on_device='cpu',
E                   frontend='paddle',
E                   backend_fw='paddle',
E                   dtype_and_x=(['uint8'], [array(0, dtype=uint8)]),
E                   test_flags=FrontendFunctionTestFlags(
E                       num_positional_args=0,
E                       with_out=False,
E                       inplace=False,
E                       as_variable=[False],
E                       native_arrays=[False],
E                       generate_frontend_arrays=False,
E                   ),
E                   fn_tree='ivy.functional.frontends.paddle.clone',
E               )
E               
E               You can reproduce this example by temporarily adding @reproduce_failure('6.82.0', b'AAYAAAAAAAAAAA==') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:77: AssertionError
------------------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------------------
ivy.array(0)
uint8
ivy.array(0)
ivy.array(115)
int8
ivy.array(115)
ivy.array(115)
int8
ivy.array(115)
ivy.array(0)
uint8
ivy.array(0)
ivy.array(0)
uint8
ivy.array(0)
------------------------------------------------------------------------------ Captured stderr call -------------------------------------------------------------------------------
I0725 09:03:13.541280 12964 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0725 09:03:14.520161 12964 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0725 09:03:15.691062 12964 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0725 09:03:16.538931 12964 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0725 09:03:17.788709 12964 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
```

**Comment by Kalachuchis** [comment]
test results
```
Use Database in ReadOnly Mode with local caching !
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.10.0, pytest-7.4.0, pluggy-1.2.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-3.7.1, json-report-1.5.0, hypothesis-6.82.4, metadata-3.0.0
collected 5 items                                                                                                                                                                 

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py .....                                                                                            [100%]

================================================================================ warnings summary =================================================================================
ivy/data_classes/container/base.py:1396
  /workspaces/ivy/ivy/data_classes/container/base.py:1396: DeprecationWarning: invalid escape sequence '\.'
    flat_keys = re.split("/|\.", key_chain)  # noqa

../../opt/fw/tensorflow/_distutils_hack/__init__.py:18
  /opt/fw/tensorflow/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
    warnings.warn(

../../opt/fw/tensorflow/_distutils_hack/__init__.py:33
  /opt/fw/tensorflow/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")

../../opt/fw/tensorflow/setuptools/sandbox.py:13
  /opt/fw/tensorflow/setuptools/sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../../opt/fw/tensorflow/pkg_resources/__init__.py:2871
  /opt/fw/tensorflow/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py: 50 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1035: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================ 100.0% of 5 passed =================================================================================================================================================== 5 passed, 55 warnings in 88.99s (0:01:28) ====================================================================

```

**Comment by Kalachuchis** [comment]
fixed conflicts. please review @RickSanchezStoic

**Pull request closed without merging**
