### PR TITLE
fix: use of ivy.Shape in conditions

### PR DESCRIPTION
**Pull request by mattbarrett98**
fixing the `__bool__` method of `ivy.Shape`. problem is lists/tuples don't have a `__bool__` method, instead we need to call `bool()` on them for it to work. this breaks the use of an `ivy.Shape` object in conditions, and added a test which shows what this fixes @vedpatwardhan

### CODE REVIEW

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Feel free to merge, thanks @mattbarrett98 😄

**Comment by mattbarrett98** [comment]
@vedpatwardhan there is a recent pr from @fnhirwa on the same method: https://github.com/unifyai/ivy/commit/9789ea5392d9585d65acfa308a9907fb50a120d5.  I've overridden with my change as I don't believe this was the right fix. The method now tries to extract the first element out of the shape, and check the truth value of this element, which i don't think is quite right.

I think it would coincidentally give the right answer most of the time, but one example where it fails is the shape of a 0 dimensional array would be `ivy.Shape(())` ie an empty tuple. Trying to extract the 0th element from this would fail.

**Comment by fnhirwa** [comment]
> @vedpatwardhan there is a recent pr from @fnhirwa on the same method: [9789ea5](https://github.com/unifyai/ivy/commit/9789ea5392d9585d65acfa308a9907fb50a120d5). I've overridden with my change as I don't believe this was the right fix. The method now tries to extract the first element out of the shape, and check the truth value of this element, which i don't think is quite right.
> 
> I think it would coincidentally give the right answer most of the time, but one example where it fails is the shape of a 0 dimensional array would be `ivy.Shape(())` ie an empty tuple. Trying to extract the 0th element from this would fail.

Hey @mattbarrett98 this makes sense, I'm going to revert this commit🤞

**Comment by vedpatwardhan** [comment]
> @vedpatwardhan there is a recent pr from @fnhirwa on the same method: [9789ea5](https://github.com/unifyai/ivy/commit/9789ea5392d9585d65acfa308a9907fb50a120d5). I've overridden with my change as I don't believe this was the right fix. The method now tries to extract the first element out of the shape, and check the truth value of this element, which i don't think is quite right.
> 
> I think it would coincidentally give the right answer most of the time, but one example where it fails is the shape of a 0 dimensional array would be `ivy.Shape(())` ie an empty tuple. Trying to extract the 0th element from this would fail.

Yeah makes sense, thanks for pointing that out @mattbarrett98 😄

**Pull request merged**
