### PR TITLE
feat(ci): enable `pip` cache in CI

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Changes made by this PR can be summarized as follows:

- Use an updated version of `actions/setup-python` so as to allow the caching of `pip`.

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by SauravMaheshkar** [comment]
Request for Review @kurshakuz

**Comment by kurshakuz** [comment]
Hey @RashulChutani what do you think about this PR? Do we need that to be merged?

**Comment by SauravMaheshkar** [comment]
Request for Review @RashulChutani

**Comment by RashulChutani** [comment]
Hi @SauravMaheshkar We don't need to cache the contents of pip, as we use a Large Docker Image with all the packages, pre-installed. Thanks.

**Pull request closed without merging**
