### PR TITLE
empty_strided #18298

### PR DESCRIPTION
**Pull request by Aayush146**
#18298

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Aayush146** [comment]
@hello-fri-end, hope you are doing well. I wanted to know if you were able to review my pull request?

**Comment by Aayush146** [comment]
@Aarsh2001 Hope you are doing alright, is it possible to know if my code has been reviewed?

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Kindly remove all the changes you made in the `.idea` folder.
Thanks!

**Comment by Aayush146** [comment]
@zaeemansari70 Thanks for your response. should I close this pull request and create a new one for you to review?

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @Aayush146 ! Thanks for creating this PR! Could you please revert the changes you have made to the files inside the `.idea` folder?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
