### PR TITLE
please check the update ndarray.py

### PR DESCRIPTION
**Pull request by varshithamanasa**

### CODE REVIEW

**Review by CheezBallzPi — CHANGES_REQUESTED** [review]
Your tests aren't passing yet.

**Comment by CheezBallzPi** [comment]
Take a look at the `test-frontend-numpy` check and the [Deep Dive](https://lets-unify.ai/ivy/deep_dive/ivy_frontends_tests.html) for guidance.

**Review by varshithamanasa — COMMENTED** [review]
where am I going wrong?

**Comment by varshithamanasa** [comment]
> Your tests aren't passing yet.

why, could you please tell me where I am going wrong, I might need help to resolve this. My instance method is correct but why are the test cases not passing

**Comment by CheezBallzPi** [comment]
If you check the logs you can see the problem with the test. Here it is:
```
E       TypeError: test_frontend_method() got an unexpected keyword argument 'input_dtype_init'
```

You can manually run the frontend test on your own machine to test it out, too. That way you can check your code without waiting for the tests here to run.

**Comment by CheezBallzPi** [comment]
Are you still working on this PR? Let me know if you have any questions.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
