### PR TITLE
modified exp

### PR DESCRIPTION
**Pull request by jashdalvi**

### CODE REVIEW

**Comment by jashdalvi** [comment]
I have reformatted the ivy.exp function. It would be helpful if someone could review this!!

**Review by HotzingTone — COMMENTED** [review]
Hi, please add back the exp function deleted from mxnet backend. Thanks!

**Comment by jashdalvi** [comment]
@HotzingTone I have just changed the exp function but it is failing on some tests. Any help would be appreciated!!

**Comment by jashdalvi** [comment]
@HotzingTone I have solved the above issue. The problem was related to the environment I was working in and not with the actual code.

**Review by HotzingTone — APPROVED** [review]
I resolved the conflicts and now merging to main. Thanks for your work!

**Pull request merged**
