### PR TITLE
Reformat matrix_power #7488

### LINKED ISSUE #7488: matrix_power

### PR DESCRIPTION
**Pull request by Timotheevin**
Close #7488

### CODE REVIEW

**Comment by Timotheevin** [comment]
For some reason checks are not successful but I don't really get why.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by aditya-pola** [comment]
This somehow slipped under my radar, my apologies! I will be reviewing this ASAP and get back to you.

**Comment by Timotheevin** [comment]
I was about to send a message on the discord channel but if you are on it that's ok, thanks !

**Comment by aditya-pola** [comment]
This looks good to me! Merging...

**Pull request merged**
