### PR TITLE
Implemented cummax on torch frontend

### LINKED ISSUE #12998: cummax

### PR DESCRIPTION
**Pull request by tvsharish**
I have implemented cummax on torch frontend . I have also created testing function ```test_torch_cummax``` function on torch frontend. This will closes #12998 which is subtask of #3612 .

### CODE REVIEW

**Comment by MahmoudAshraf97** [comment]
Please remove all unrelated formatting changes before we can review the PR

**Comment by tvsharish** [comment]
Hi, I have checkedin only the changes in torch frontend and test_torch_cummax.

**Comment by tvsharish** [comment]
Hi @MahmoudAshraf97 , can you review this PR.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey would you add only changes made to the cummax function in the unit tests file😊

**Comment by tvsharish** [comment]
> Hey would you add only changes made to the cummax function in the unit tests fileblush
Hi, Where could I find unit test files.

**Comment by tvsharish** [comment]
Hi @hirwa-nshuti , Where could I find unit test files.

**Comment by MahmoudAshraf97** [comment]
> Hi @hirwa-nshuti , Where could I find unit test files.

`ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py`

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
