### PR TITLE
Add erf to torch tensor

### LINKED ISSUE #16257: erf

### PR DESCRIPTION
**Pull request by G544**
close  #16257

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hey @G544 thanks a lot for your contribution! Can you quickly take a look at the failing tests?

**Comment by G544** [comment]
Hey @V-G-spec thanks for the review. It looks like fails are not related to my changes.
It seems like run_tests(1) exited unexpectedly. 
```
Status: Downloaded newer image for unifyai/ivy:latest
Error: The operation was canceled.
``` 
In run_tests(56) fail is related to function test_torch_instance_new_zeros. and it passed locally. 

```
__ test_torch_instance_new_zeros[cpu-ivy.functional.backends.jax-False-False] __
ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py:660: in test_torch_instance_new_zeros
    class_tree=CLASS_TREE,
ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:490: in dtype_and_values
    available_dtypes = draw(available_dtypes)
/opt/miniconda/envs/multienv/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw
    return strategy.do_draw(self)
/opt/miniconda/envs/multienv/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1558: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:173: in get_dtypes
    valid_dtypes = set(retrieval_fn(test_globals.CURRENT_BACKEND(), kind))
ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:35: in _get_fn_dtypes
    return test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[framework.backend][
E   KeyError: 'cpu'
``` 

And in formatting check there are no errors related to files changed in this pr

**Comment by V-G-spec** [comment]
Hey, there are 49 failing tests. Are you sure they are not arising from your changes? Do they pass locally for you?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by G544** [comment]
Hey!
Yes, I am sure they are not related. 
Today another conflict occurred and as you see there are only  formatting check failing. Formatting check is related to my code (extra spaces). But as I understand formatting  issue fixed automatically, as I can see diff in formatting check logs

```
--- a/ivy/functional/frontends/torch/tensor.py
+++ b/ivy/functional/frontends/torch/tensor.py
@@ -405,7 +405,7 @@ class Tensor:
     @with_unsupported_dtypes({"2.0.1 and below": ("float16", "complex")}, "torch")
     def erf(self):
         return torch_frontend.erf(self)
-      
+
     def new_zeros(self, *size, dtype=None, device=None, requires_grad=False):
         if isinstance(size[0], tuple):
             return torch_frontend.zeros(
Error: Process completed with exit code 1.
```

**Comment by G544** [comment]
Hey @V-G-spec!
Today another merge conflict occured. Now it is 2 falling test and both are not related to my code.

From run_tests(1)

```
=========================== short test summary info ============================
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_paddle_fft.py::test_paddle_fft[cpu-ivy.functional.backends.numpy-False-False]
============================== 1 failed in 0.67s ===============================
Error: Process completed with exit code 1
``` 

from formatting check
```
@@ -628,7 +628,8 @@ from ivy.functional.frontends.numpy.mathematical_functions.extrema_finding impor
 )
 
 from ivy.functional.frontends.numpy.mathematical_functions.floating_point_routines import (  # noqa
-    _nextafter, _spacing,
+    _nextafter,
+    _spacing,
 )
 
 _frontend_array = array
diff --git a/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py b/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
index bde7984..95e4563 100644
--- a/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
+++ b/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
@@ -1062,7 +1062,7 @@ def test_paddle_erf(
         frontend=frontend,
         on_device=on_device,
     )
-    
+
 
 # subtract
 @handle_frontend_method(
Error: Process completed with exit code 1.
```

**Comment by V-G-spec** [comment]
Hey, I confirm that the errors are not due to your files. However, I noticed that your function has only one argument, which is not the case for `torch.special.erf`

**Comment by G544** [comment]
Hey @V-G-spec. I've added arguments. Can you check, please?
7 failling tests again, but I checked and it seems like they are not related to my code.

**Comment by V-G-spec** [comment]
Hi, I do see some tests failing because of your additions (correct me if I'm wrong). Search for `erf` in the logs of the failing tests

**Comment by G544** [comment]
Hey @V-G-spec , I've synced my branch with ivy's master and rerun tests. now there is no failing tests related to erf. 
However, there is a warning in a test related to erf
```
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py::test_paddle_instance_erf[cpu-ivy.functional.backends.numpy-False-False]
  /ivy/ivy/functional/backends/numpy/elementwise.py:799: RuntimeWarning: overflow encountered in multiply
    y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * np.exp(-x * x)
```
but I cannot reproduce it on my local. Also warning relates to paddle, not torch

photo_2023-07-06_11-35-39 — копия


Other failures do not seem to be related to erf at all 
in test 3
```
_ test_torch_instance_pow[cpu-ivy.functional.backends.paddle-False-False] __
ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py:4375: in test_torch_instance_pow
    class_tree=CLASS_TREE,
ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py:4398: in test_torch_instance_pow
    helpers.test_frontend_method(
ivy_tests/test_ivy/helpers/function_testing.py:1542: in test_frontend_method
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:134: in value_test
    assert_all_close(
ivy_tests/test_ivy/helpers/assertions.py:56: in assert_all_close
    assert np.allclose(
E   AssertionError:  the results from backend paddle and ground truth framework torch do not match
E    2!=1 
```

in run_test 96
```
_ test_torch_instance_byte[cpu-ivy.functional.backends.numpy-False-False] __
ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py:5937: in test_torch_instance_byte
    class_tree=CLASS_TREE,
ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py:5953: in test_torch_instance_byte
    helpers.test_frontend_method(
ivy_tests/test_ivy/helpers/function_testing.py:1542: in test_frontend_method
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:134: in value_test
    assert_all_close(
ivy_tests/test_ivy/helpers/assertions.py:56: in assert_all_close
    assert np.allclose(
E   AssertionError:  the results from backend numpy and ground truth framework torch do not match
E    0!=255
```

**Comment by V-G-spec** [comment]
All looks good. Thanks a lot for diving deep into the issue

**Comment by G544** [comment]
Hi @V-G-spec, thanks! 
Can you please advice on the next steps? It looks like I still cannot merge, do we need approve?

**Comment by V-G-spec** [comment]
I was about to merge, but I am seeing something odd (A lot of "co-authored-by" comments) which I'm not sure how we handle. So I'm taking this up internally. Won't be long before I confirm the merge

**Comment by G544** [comment]
Hey @V-G-spec. Thanks! It is probably of the way I synced unify repo into my fork :(  I will wait for reply. May be I ahould create a new fork to solve this problem? I will wait for reply.

**Comment by V-G-spec** [comment]
The reason for the delay was that I saw a lot of "Co-authored-by" comments while trying to merge and was confirming internally if that's okay. Can you please resent your branch to the current master commit and then add your changes again? We reckon that the PR has been wrongly rebased, given that there are only 2 files modified.

**Comment by G544** [comment]
Hey @V-G-spec, I cleaned up the commit history and hopefully there will be no issues with the merge now.
Also I checked failing tests and they are not related to my code

**Pull request merged**
