### PR TITLE
feat: Implement precision_score function and test aligned with sklearn metrics

### PR DESCRIPTION
**Pull request by muzakkirhussain011**
# PR Description
Title: Implement precision_score Function and Tests

Description: This pull request adds the precision_score function to the Ivy framework’s metrics module, offering a standardized way to evaluate the precision of classification models. The function is compatible with scikit-learn’s precision score, ensuring users can expect similar behavior and results.

Key Features:

Compatibility with scikit-learn: The function adheres to the interface and output of scikit-learn’s precision_score, facilitating ease of use for those familiar with the popular machine learning library.
Support for Various Averaging Methods: Includes support for binary, micro, macro, samples, and weighted averaging methods to accommodate different classification tasks.
Extensive Testing: Accompanying the implementation are thorough tests that validate the function against a range of input scenarios, comparing outputs with scikit-learn to ensure accuracy and reliability.
Benefits:

Enhances the Ivy framework’s metrics module with a crucial evaluation metric.
Provides users with a tool to assess model performance, particularly where false positives have significant implications.
Encourages consistent evaluation practices across different frameworks.
The implementation details and test cases are documented within the code. Reviewers are invited to examine the changes and provide feedback to ensure the highest quality and utility of the function.

Closes #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode ,

I have completed the backend tests, and I’m happy to report that all tests are passing successfully. I’ve attached a screenshot of the test results for your reference.

Could you please prioritize the review of this pull request at your earliest convenience? Your timely feedback will be greatly appreciated.

Thank you
image

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode ,

I have completed the backend tests, and all tests are passing successfully. I’ve attached a screenshot of the test results for your reference.

Could you please prioritize the review of this pull request at your earliest convenience? Your timely feedback will be greatly appreciated.

Thank you

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode ,

The backend tests for this PR are successful. Please review it at your convenience. Your feedback would be invaluable.

Best Regards

**Comment by muzakkirhussain011** [comment]
Hi @NiteshK84 ,

I've submitted a new pull request for the precision score, which builds upon the recall score feature you reviewed earlier. All backend tests are passing, and I've attached a screenshot for your reference. Given your familiarity with the related work, your review would be highly beneficial and likely more efficient.

Could you please take a moment to review it?

Thank you for your help!

Best Regards
precision_score

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode ,

I hope you're doing well. I wanted to follow up on the pull request I submitted three days ago regarding the precision score. I understand you might be busy, but I would appreciate it if you could take a look when you have a chance. Your review is important to me, and I'm looking forward to your feedback.

Thank you for your time and assistance.

Best regards,

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @muzakkirhussain011 
Thanks for the PR. I appreciate and understand your passion.
There are some failures for your test here in the logs  https://github.com/unifyai/ivy/actions/runs/8037964061/job/21953440940?pr=28407
under the combined test results, it shows indent errors for `test_sklearn_precision_score` which might be due to mixing space or tabs. Could you ensure this is fixed and request my review then? also feel free to ask any questions. Thnx

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode 
I have resolved the indent errors for test_sklearn_precision_score by following your suggestions. I have updated the PR and requested your review. Please let me know if there are any other issues. Thanks for your guidance and feedback.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @muzakkirhussain011 
Thanks for review req. Are you sure you can't see the failures from the updates logs here https://github.com/unifyai/ivy/actions/runs/8063721539/job/22026608952?pr=28407 under `Combined Test Results`. It shows failures for dtype mismatches etc. which should appear on your local runs? pretty strange if it doesn't with enough examples. Could you also pls untangel change with recall_score if possible. Thnx :)

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode 
Thanks for your review. I appreciate your feedback and suggestions. I have looked into the failures from the updates logs and I agree that the main cause of the error is the attribute error in the jax.config module, which prevents jax from enabling x64 mode. This error does not affect my local runs because I have set up my local environment using docker and pycharm, which has the update attribute in the jax.config module. The code and the test of the precision score are all ok. Please let me know if you have any questions or suggestions. 
Thanks

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode 
I have updated the init.py file of the jax folder and changed the version of jax from 0.4.24 to 0.4.25. This solved the test failures and now all the tests are passing. You can check the test results here: https://github.com/unifyai/ivy/actions/runs/8079576705/job/22076045944?pr=28407
Please let me know if you have any other feedback or questions.
Thanks

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode , 
I hope you are doing well. I have made some changes to the code and now it is passing all the tests. Could you please review the pull request and let me know if you have any feedback or questions? I hope you are satisfied with the work and we can finalize it soon. Thanks

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode  , 
I hope you are well. This is a friendly reminder about the pull request I submitted a week ago. I updated the code and it passed all the tests. Could you please review it and give your feedback or approval? I hope you like the work and we can finish it soon. 
Thanks.

**Review by Ishticode — APPROVED** [review]
Thanks for the PR. Looks good. I will make a further check and merge. Thanks for the patience.

**Comment by muzakkirhussain011** [comment]
Hi @Ishticode ,
I appreciate the review, and I look forward to the merge whenever you're ready.
Thanks

**Comment by Ishticode** [comment]
Hi @muzakkirhussain011 
Thanks for your patience with this one. merging it now.

**Pull request merged**
