### PR TITLE
initialize frontend api for Take function

### PR DESCRIPTION
**Pull request by mahmoudelnazer**
#19811

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by KareemMAX** [comment]
@YushaArif99 @mahmoudelnazer be aware that this might be a duplicate of https://github.com/unifyai/ivy/pull/18943

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Kindly un-commit your changes from the `.idea` folder thanks!

**Comment by YushaArif99** [comment]
Hi @mahmoudelnazer 

I am closing this PR due to it being inactive for more than 3 weeks. Feel free to work on other open tasks 🙂

**Pull request closed without merging**
