### PR TITLE
23051 exponential

### LINKED ISSUE #23051: exponential

### PR DESCRIPTION
**Pull request by Prady0**
# PR Description

This PR is about adding an exponential function and its test case 

## Related Issue

No related issue

Close #23051

## Checklist

- [ Yes] Did you add a function?
- [ Yes] Did you add the tests?
- [ Yes] Did you follow the steps we provided?

### Socials:

None

### CODE REVIEW

**Comment by mobley-trent** [comment]
Hello @Prady0 thanks for the PR 🙂 
Please pick a single function for your contribution. This makes it easier to make reviews.
Here are the [contribution guidelines](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html)

**Comment by Prady0** [comment]
Hi @mobley-trent, I’ve added only a single function (that is exponential) and the test case for the same function.

**Comment by mobley-trent** [comment]
@Prady0 that's strange, your PR is showing changes made to several files. 
Please revert them to their original state and also fix the conflicts so that I can see the tests on the CI 🙂

**Comment by Prady0** [comment]
Hello @mobley-trent ,

I've thoroughly investigated the excessive function additions in the pull request (PR) and determined that they stem from the pre-commit checks we run before creating the PR. You can verify that in the commits tab. The initial two commits are mine, while the third commit is the result of an automated pre-commit check that's required for PR creation. I hope this clarifies the situation, and I look forward to having my PR merged promptly. Please let me know if there are any additional details you require.

Thank you.

**Comment by Prady0** [comment]
Hi @mobley-trent, I have removed the pre-checks commit from my PR and now there are only 2 files visible in the files changes tab. You can check them and let me know if everything seems fine. Talk to you soon.

**Review by mobley-trent — CHANGES_REQUESTED** [review]
Hi @Prady0 your PR looks great 🚀 
Please remove the second `exponential` function at the end of the file if it is not needed.
You also need to refactor the tests and add strategies for some of the arguments.
Make sure pre-commit is active 🙂

**Review by mobley-trent — APPROVED** [review]
lgtm 🚀 
merging right away 😄

**Pull request merged**
