### PR TITLE
Add negative to numpy frontend math functions

### PR DESCRIPTION
**Pull request by JonaOmara**
- [x] #3914

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
Hi @JonaOmara can you please fix the lint issues?

**Comment by JonaOmara** [comment]
@RickSanchezStoic , could you please help me point out where that error is?

**Comment by RickSanchezStoic** [comment]
I would suggest you to go through this guide for a better understanding https://lets-unify.ai/ivy/contributing/1_the_basics.html#the-basics

**Comment by JonaOmara** [comment]
@RickSanchezStoic , I don't seem to find anything  on that page talking about a lint error, do you mind elaborating more on the lint error you talked about so that I correct it please.

**Comment by JonaOmara** [comment]
@RickSanchezStoic , I've made some changes to the PR

**Pull request closed without merging**
