### PR TITLE
mae layer

### PR DESCRIPTION
**Pull request by Jordan-Madden**
#4668

### CODE REVIEW

**Comment by ahmedo42** [comment]
Hi @Jordan-Madden thanks for the contribution!!, due to the changes in the TensorFlow API, we moved this function from the layers submodule (kindly recheck the TODO issue), and the `mean_absloute_error` metric is already implemented in `metrics.py` if you'd like you can simply add a one-liner binding to it and then we can merge, or you can work on another function if you'd prefer that.

**Comment by Jordan-Madden** [comment]
Hi @ahmedo42 thanks for the update. I was sure I saw it requested in the TODo issue, must have been my mistake. I'll try to add the binding to it

**Comment by Jordan-Madden** [comment]
I added the binding to the function. Can you let me know if it is ok please.

**Comment by Jordan-Madden** [comment]
Alright thank you. Changes made to the code.

**Comment by ahmedo42** [comment]
@Jordan-Madden we can merge as soon as the lint check passes

**Comment by ahmedo42** [comment]
LGTM! @Jordan-Madden

**Pull request merged**
