### PR TITLE
Reformat einops_repeat

### LINKED ISSUE #10824: einops_repeat

### PR DESCRIPTION
**Pull request by rishabgit**
Close #10824

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hey @rishabgit. Can you take a look at the failing tests please?
Thanks!

**Comment by rishabgit** [comment]
> Hey @rishabgit. Can you take a look at the failing tests please? Thanks!

I'm not too sure, but it looks like the failing tests aren't related to edits I made?

**Comment by V-G-spec** [comment]
Yep, that happens a lot of times, and I was expecting that. Just wanted you to check and go through the logs once.
Can you resolve the conflicts too?

**Comment by rishabgit** [comment]
@V-G-spec Resolved the conflicts.

**Comment by rishabgit** [comment]
@V-G-spec quick reminder

**Comment by hirwa-nshuti** [comment]
Hey @rishabgit 
Thanks for contributing to ivy🤗

There was a large update to the repository which introduced many conflicts.
Would you copy your changes to a new PR😊 and close this one?

Feel free to tag me I'll give it a review🙂
Thanks

**Pull request closed without merging**
