### PR TITLE
 Add is_nan 

### PR DESCRIPTION
**Pull request by mixmore**
Add (is_nan) math function to functional-frontends-tensorflow-math.py
and also add the test 
https://www.tensorflow.org/api_docs/python/tf/math/is_nan
Main---""https://github.com/unifyai/ivy/issues/1545""
[ is_nan] #11525

### CODE REVIEW

**Comment by mixmore** [comment]
This is my first addition. I hope I did things right. Please I am waiting for feedback to know about my mistakes to correct them.
Thanks in advance

**Comment by mixmore** [comment]
[ is_nan] #11525

**Comment by fspyridakos** [comment]
Thanks for your contribution! Looks good to me

**Comment by mixmore** [comment]
@fspyridakos Thank you very much for your feedback

**Pull request merged**
