### PR TITLE
Torch Frontend - inner

### LINKED ISSUE #9901: inner

### PR DESCRIPTION
**Pull request by tomislavrekic**
Close #9901

### CODE REVIEW

**Comment by tomislavrekic** [comment]
#9901

**Comment by aditya-hari** [comment]
Hey! Thanks for the contribution, but the test seem to be failing. Please look at the other tests for reference of how to write the test for inner

**Comment by tomislavrekic** [comment]
I've downloaded the error logs from nightly tests and when search for "inner" I don't see anything related to the code I wrote. A lot of errors come from other test functions which haven't updated for the 'as_variable' change. 

I ran the tests locally successfully.

I am sorry but could you at least point me in the right direction? Thank you

**Comment by aditya-hari** [comment]
Sorry, seems like I got something wrong. The tests are indeed passing. LGTM, I'll go ahead and merge this!

**Pull request merged**
