### PR TITLE
asarray function

### PR DESCRIPTION
**Pull request by bethelhall**
- [ ] #513

### CODE REVIEW

**Comment by bethelhall** [comment]
- [ ] Code refactored

**Comment by bethelhall** [comment]
- [ ] Code refactored

**Review by saeedashrraf — COMMENTED** [review]
Hello @bethelhall , thank you for your effort but it seems like you are addressing an issue which is already assigned to someone else. Unfortunately, I will have to close this pull request because of that. You're very welcome to select a different issue that is not assigned to anyone to work on.

**Comment by bethelhall** [comment]
> Hello @bethelhall , thank you for your effort but it seems like you are addressing an issue which is already assigned to someone else. Unfortunately, I will have to close this pull request because of that. You're very welcome to select a different issue that is not assigned to anyone to work on.

> Hello @saeedashrraf, thank you for your comments. But the issue is still open while my PR is pending. Why can't you review my PR?

**Pull request closed without merging**
