### PR TITLE
gelu added to jax frontend 

### PR DESCRIPTION
**Pull request by VikramxD**

### CODE REVIEW

**Comment by VikramxD** [comment]
pr for #2936 , belonging to the todolist issue #1515
1. implemented gelu activation function in ivy/functional/frontends/jax/nn/non_linear_activations.py 
2. Added tests for gelu activation in  ivy/functional/frontends/jax/nn/non_linear_activations.py
3.  corrected parameter fn_name to fn_tree in the function helpers.test_frontend_function  in ivy_tests/test_ivy/test_frontends/test_jax/test_activations.py

**Comment by Daniel4078** [comment]
Hello, can you tell me why you use fn_tree as the parameter name instead of fn_name while there is no such parameter for helpers.test_frontend_function? Thank you.

**Comment by VikramxD** [comment]
> Hello, can you tell me why you use fn_tree as the parameter name instead of fn_name while there is no such parameter for helpers.test_frontend_function? Thank you.

This was in references to changes made in the pr #2903 , fn_name has been changed to fn_tree , if we run the test frontend function without changing the name it throws the error of missing argument fn_tree

**Comment by Daniel4078** [comment]
> > Hello, can you tell me why you use fn_tree as the parameter name instead of fn_name while there is no such parameter for helpers.test_frontend_function? Thank you.
> 
> This was in reference to changes made in the pr #2903 , fn_name has been changed to fn_tree , if we run the test frontend function without changing the name it throws the error of missing argument fn_tree , if you refer the failed frontend tests made in this pr , the main reason they are failing is because they are following the old fn_name parameter , hence the error thrown : TypeError: test_frontend_function() missing 1 required keyword-only argument: 'fn_tree'

Thank you for your explaination as I just found that the branch I mainly working on has an outdated version of helpers.py.

**Comment by VikramxD** [comment]
> > > Hello, can you tell me why you use fn_tree as the parameter name instead of fn_name while there is no such parameter for helpers.test_frontend_function? Thank you.
> > 
> > 
> > This was in reference to changes made in the pr #2903 , fn_name has been changed to fn_tree , if we run the test frontend function without changing the name it throws the error of missing argument fn_tree , if you refer the failed frontend tests made in this pr , the main reason they are failing is because they are following the old fn_name parameter , hence the error thrown : TypeError: test_frontend_function() missing 1 required keyword-only argument: 'fn_tree'
> 
> Thank you for your explaination as I just found that the branch I mainly working on has an outdated version of helpers.py.

No issues it failed for me too i was able to work on a local working fix in helpers.py's nest.py function but found out that @JLU-Neal had already patched it so i just changed the tests accordingly.

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
I suppose that the as_variable_flags and native_array_flags should not be generated randomly but I am not sure now.
Also, ivy.gelu has a optional out argument that your front_end wrapper and test ignored.

**Comment by VikramxD** [comment]
> I suppose that the as_variable_flags and native_array_flags should not be generated randomly but I am not sure now.
> Also, ivy.gelu has a optional out argument that your front_end wrapper and test ignored.

the frontend test and the implementation has been done according to the jax implementation of the gelu function (https://jax.readthedocs.io/en/latest/_autosummary/jax.nn.gelu.html) which is why the function is not following the optional out argument in frontend function and test  , as for the as_variable_flags and native_array_flags in the helpers.test_frontend_function if we fix those tests wouldn't that hurt the testing because the generated data would be limiting to the fixed cases we assert

**Review by Daniel4078 — APPROVED** [review]
Then I think there is nothing wrong here.

**Pull request merged**
