### PR TITLE
Update math.py

### PR DESCRIPTION
**Pull request by Fayad-Alman**
Fixed is_strictly_increasing function:
- Replaced final return statement with for loop to check for strictly increasing array
- Final return statement set to return True

### CODE REVIEW

**Comment by Fayad-Alman** [comment]
Issue:
#9356

**Comment by jkeane508** [comment]
Hey, thanks for submitting this PR

Seems as though the tests didn't run properly :(

Will check up once they have finished!

Thanks

**Comment by Fayad-Alman** [comment]
Hi @jkeane508 
Mind taking another look at the changes?

**Review by jkeane508 — CHANGES_REQUESTED** [review]
From the test results seems to be a syntax error with your implementation. Moreover, for this task you should also write a test for this function in the relevant file :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
