### PR TITLE
Implement eigvalsh function to conform to Array API Standards

### PR DESCRIPTION
**Pull request by juaolobo**
Implement eigvalsh (#434) function for ivy and all backends. Regular tests are failing due to the triu function not being implemented.

### CODE REVIEW

**Review by 1Doomdie1 — CHANGES_REQUESTED** [review]
Hey! Thank you for contributing to Ivy!
As you pointed out this method depends on other functions so you can either create another issue and implement it your self or hang tight until someone implement's it.
I flagged this PR as "Depends on another method" so it will not be closed automatically in the future.

One small think I would like you to do is uncomment the name of the function you are working on from ivy_tests/array_api_methods_to_test/elementwise_functions.txt

Thank you!

**Comment by juaolobo** [comment]
> Hey! Thank you for contributing to Ivy! As you pointed out this method depends on other functions so you can either create another issue and implement it your self or hang tight until someone implement's it. I flagged this PR as "Depends on another method" so it will not be closed automatically in the future.
> 
> One small think I would like you to do is uncomment the name of the function you are working on from ivy_tests/array_api_methods_to_test/elementwise_functions.txt
> 
> Thank you!

Ok, I think the triu function has already been implemented here #545, so I'll wait until the PR is accepted. I uncommented eigvalsh from ivy_tests/array_api_methods_to_test/linear_algebra.txt.

**Review by HotzingTone — CHANGES_REQUESTED** [review]
All conflicts now resolved, but tests haven't passed.

**Comment by juaolobo** [comment]
Yeah, it seems the function also depends on the mT attribute which is being implemented.

**Comment by HotzingTone** [comment]
eigvalsh has been well implemented, though tests failed due to another function. PR now merged.

**Pull request merged**
