### PR TITLE
 Add Manipulation Functions to Paddle Backend

### PR DESCRIPTION
**Pull request by chinonsoonodi**
The PR aim is to add scatter_flat function to general in paddle backend
issue #14006

### CODE REVIEW

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
please remove any changes other than scatter flat

**Comment by chinonsoonodi** [comment]
> please remove any changes other than scatter flat

Done

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Reduction is meant to operate on the updated indices only not the whole array

**Comment by chinonsoonodi** [comment]
> Reduction is meant to operate on the updated indices only not the whole array

Updated

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
reduction is meant to be between the old values and the new values on elementwise basis, also when concatinating shapes, make sure that they are both tuples or lists. you must use paddle scatter or an equivalent function because the current implementation doesn't work with tensors that have gradients enabled

**Pull request closed without merging**
