### PR TITLE
Fix jax_devicearray_at test

### PR DESCRIPTION
**Pull request by hello-fri-end**

### CODE REVIEW

**Comment by jkeane508** [comment]
Hi,

Thanks for opening up this PR :)

Can you please reference what issue this closes?

Happy Coding!

**Comment by hello-fri-end** [comment]
> Hi,
> 
> Thanks for opening up this PR :)
> 
> Can you please reference what issue this closes?
> 
> Happy Coding!

Hi, I couldn't find the issue for this failing test in #7978. Should I open up a new one first?

**Comment by jkeane508** [comment]
> > Hi,
> > Thanks for opening up this PR :)
> > Can you please reference what issue this closes?
> > Happy Coding!
> 
> Hi, I couldn't find the issue for this failing test in #7978. Should I open up a new one first?

No worries, I went ahead and found it and linked it for you!

**Review by jkeane508 — APPROVED** [review]
LGTM :)

**Comment by jkeane508** [comment]
Co-authored-by: jkeane508 <jameskeane508@gmail.com>

**Comment by hello-fri-end** [comment]
> > > Hi,
> > > Thanks for opening up this PR :)
> > > Can you please reference what issue this closes?
> > > Happy Coding!
> > 
> > 
> > Hi, I couldn't find the issue for this failing test in #7978. Should I open up a new one first?
> 
> No worries, I went ahead and found it and linked it for you!

Thanks :) Can we merge this now?

**Comment by jkeane508** [comment]
> 

Oh my bad I was meant to merge it ahaha

**Comment by hello-fri-end** [comment]
> > 
> 
> Oh my bad I was meant to merge it ahaha

No problem, thanks! 😄

**Pull request merged**
