### PR TITLE
Adding `with_backend` cache to `ivy.Module`

### PR DESCRIPTION
**Pull request by danielmunioz**

### CODE REVIEW

**Review by vedpatwardhan — APPROVED** [review]
lgtm! We can get it merged once @mattbarrett98 has verified the same, thanks @danielmunioz 😄

**Review by mattbarrett98 — COMMENTED** [review]
module tests are working fine, though they still seem to be a lot slower than they used to be so don't know how much this will help

**Comment by vedpatwardhan** [comment]
@danielmunioz, could you please also use the caching argument for `with_backend` in the `ivy.Module.__init__`? Probably that would speed up the tests further. Thanks for pointing that out @mattbarrett98 😄

**Comment by danielmunioz** [comment]
@vedpatwardhan, it's already on the __init__, did you mean adding it to the __call__?

**Comment by danielmunioz** [comment]
@mattbarrett98, could you please verify it again please?

**Comment by vedpatwardhan** [comment]
> @vedpatwardhan, it's already on the **init**, but I'm trying adding it to the **call** as well

Ah yeah sorry, I meant we use caching for both the usages of `with_backend`. Thanks for updating that @danielmunioz 😄

**Pull request merged**
