### PR TITLE
Added truncatemod tensorflow frontend function

### LINKED ISSUE #16290: truncatemod

### PR DESCRIPTION
**Pull request by Konyancha1**
Close #16290

### CODE REVIEW

**Comment by Konyancha1** [comment]
Hello @paulaehab, kindly review this PR

Thanks

**Comment by paulaehab** [comment]
Hi @Konyancha1, as I can see after your edits (tensorflow,numpy,jax) don't support unit8 dtype so check supported dtypes for this function to solve this error.

**Comment by paulaehab** [comment]
Hi @Konyancha1  are you finish the edits and want review or you still working on it ? if you didn't finish could you please request changes after you finished

**Comment by Konyancha1** [comment]
Hello @paulaehab , I am finished with edits. Kindly please review

**Comment by paulaehab** [comment]
Hi @Konyancha1  nice work it looks great for me just include the unsupported dtyeps instead of supported dtypes 
@with_unsupported_dtypes({"2.12.0 and below": ("int16", "int8","uint8"," uint16")}, "tensorflow") and I will merge it

**Comment by paulaehab** [comment]
Hi @Konyancha1  lgtm Thanks for contributing, I will merge it.🥳

**Pull request merged**
