### PR TITLE
Added Docstrings and Examples to argsort function

### PR DESCRIPTION
**Pull request by ukj02**

### CODE REVIEW

**Comment by modanesh** [comment]
Thanks for your contribution :)

There are a few things that needs to be addressed. 
1- Could you please apply your changes to the master HEAD version? It seems that you've modified an old version which doesn't have the latest commits.
2- Could you add docstrings and examples to relevant functions in this file `ivy/container/sorting.py`?

Thanks.

**Comment by ukj02** [comment]
> Thanks for your contribution :)
> 
> There are a few things that needs to be addressed. 1- Could you please apply your changes to the master HEAD version? It seems that you've modified an old version which doesn't have the latest commits. 2- Could you add docstrings and examples to relevant functions in this file `ivy/container/sorting.py`?
> 
> Thanks.

Hi, for some reason when I updated my forked version it closed this pull request. I have made the changes now how can I get you to review them. Do I need to make a new pull request?

**Comment by ukj02** [comment]
Hi, I was trying to update my forked version this repository and in the process I by mistake deleted what I had committed. It also closed this pull request. Now I have made the changes in my forked version and now want to review them. Can you reopen this pull request or do I need to create a new pull request?

**Comment by modanesh** [comment]
As you already have opened another PR (#2510), I'm going to keep this one closed. You can follow the relevant task in the new PR. Thanks.

**Pull request closed without merging**
