### PR TITLE
fix: Updated set.py

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
#23539

### CODE REVIEW

**Comment by jaskiratsingh2000** [comment]
@Nightcrab @Daniel4078 
`axis`
It specifies the dimension of x along which the unique elements will be computed.
Explanation:

- If axis is None (the default), the unique elements of the flattened array x are returned. In other words, the function will consider x as a 1D array regardless of its actual shape.
- If axis is an integer, then the unique elements are computed along the specified dimension. This means if x is a 2D array (like a matrix) and axis=0, then the function will find unique rows, and if axis=1, it will find unique columns.

`by_value`
Determines the order in which unique elements are returned.

Explanation:

- If by_value is True (the default), the unique elements are sorted by their value.
- If by_value is False, the unique elements will be sorted in the same order that they occur in x. This means the order of appearance in the original x array is preserved for the unique elements in the output.

**Comment by adlub** [comment]
Hi @jaskiratsingh2000, I submitted a pull request for this issue about 9 hours ago and our commits seem to be identical. Are you able to see this? Thanks

**Comment by jaskiratsingh2000** [comment]
Some of its tests were failing and identically I figured out this can be done towards formatting

**Comment by Ookamice** [comment]
@jaskiratsingh2000 
I believe Nightcrab's point is that `axis` and `by_value` is currently not being used in the function. How the ivy API works is that it calls the respective backend implementation of the ivy function with `ivy.current_backend()..unique_inverse(x)` so even if you have updated  `axis` and `by_value` in the function declaration, it will have no effect unless you've also altered every backend.

Also @adlub makes a great point here. I see that the issue you have linked was opened by him originally. Please could you find another open issue to do as I wil lbe closing this.

**Comment by adlub** [comment]
Thanks @Ookamice. @jaskiratsingh2000, I suggest we move to my pull request page and we can discuss your suggested changes.

**Pull request closed without merging**
