### PR TITLE
reformat slogdet

### PR DESCRIPTION
**Pull request by sondertg**

### CODE REVIEW

**Comment by sondertg** [comment]
add_reformatting_checklist_linalg

**Comment by sondertg** [comment]
close #7401

**Comment by sondertg** [comment]
close #7401

**Comment by sondertg** [comment]
Hi, do I need to include out argument? This function doesn't return any array, I checked docs multiple times but couldn't decide. When I try to add out argument, ivy.slogdet function returns a tuple since this function works like that. It doesn't return any array that's why I came to the conclusion I shouldn't add out argument.
 
Rather than that, I checked all failed tests, none of them related to slogdet. In case if it helps, I list them in below.

Failed tests according to automated github tests.
nightly-tests(numpy, elementwise):
test_trunc_divide

nightly-tests(torch, elementwise):
test_floor_divide
test_remainder
test_rad2deg

nightly-tests(jax, elementwise):
test_trunc_divide
test_rad2deg
test_remainder
test_expm1

nightly-tests(tensorflow, elementwise):
test_trunc_divide
test_rad2deg

array-api-tests(numpy, linalg):
test_matrix_rank

array-api-tests(tensorflow, linalg):
test_inv - As...
test_matrix_rank

array-api-tests(torch, creation_functions):
test_linspace

**Comment by sondertg** [comment]
> Hi, do I need to include out argument? This function doesn't return any array, I checked docs multiple times but couldn't decide. When I try to add out argument, ivy.slogdet function returns a tuple since this function works like that. It doesn't return any array that's why I came to the conclusion I shouldn't add out argument.
> 
> Rather than that, I checked all failed tests, none of them related to slogdet. In case if it helps, I listed them in below.
> 
> Failed tests according to automated github tests. nightly-tests(numpy, elementwise): test_trunc_divide
> 
> nightly-tests(torch, elementwise): test_floor_divide test_remainder test_rad2deg
> 
> nightly-tests(jax, elementwise): test_trunc_divide test_rad2deg test_remainder test_expm1
> 
> nightly-tests(tensorflow, elementwise): test_trunc_divide test_rad2deg
> 
> array-api-tests(numpy, linalg): test_matrix_rank
> 
> array-api-tests(tensorflow, linalg): test_inv - As... test_matrix_rank
> 
> array-api-tests(torch, creation_functions): test_linspace

Checked recently updated doc tests, fixed slogdet related issues. 

Checked all failed tests, some came from recently implied tests which is not related to slogdet reformating. In case I missed anything, I am open for advice.

**Comment by sondertg** [comment]
#7566 fixed lint issues on this pull request.

**Review by zaeemansari70 — APPROVED** [review]
Hey! 
Thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Your changes looks good to be merged!
I hope you enjoyed contributing to Ivy, looking forward to your contributions in the future too 🙂
Thanks!

**Pull request merged**
