### PR TITLE
added torch_reciprocal

### LINKED ISSUE #6513: reciprocal

### PR DESCRIPTION
**Pull request by dovaaa**
Close #6513

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by dovaaa** [comment]
@Aarsh2001

**Comment by Aarsh2001** [comment]
Hey @dovaaa, apologies for the late response. The PR looks good. Can you fix the merge conflicts? and I'll merge it right away.

**Comment by dovaaa** [comment]
> Hey @dovaaa, apologies for the late response. The PR looks good. Can you fix the merge conflicts? and I'll merge it right away.

Fixed the conflicts!

**Pull request merged**
