### PR TITLE
added softsign

### LINKED ISSUE #14134: softsign

### PR DESCRIPTION
**Pull request by piyushgit011**
close #14134

### CODE REVIEW

**Comment by piyushgit011** [comment]
hey @fspyridakos tests are failing as softsign is not implemented in the backend of ivy tensorflow , so i think you can merge this and i will add backend function in the different pr.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by piyushgit011** [comment]
Hey @suvadityamuk can you take a look on errors

**Comment by Ookamice** [comment]
Hiya, thank you for your contributions and sorry it took so long to review your PR

I'm checking the tests and it seems that ivy.softsign part of our frameworks. Please consult the [contributer's guide](https://unify.ai/docs/ivy/overview/contributing.html) for when `ivy.<func_name>` is missing. In summary, there are two options:
1) Create an issue detailing that ivy.softsign should be added with the appropriate issue labels and a member of our team will work on it (or alternatively, you can give it a shot!)
2) Compose ivy,softsign as a composite function using existing ivy functions.

Let me know if you need any more help or if you got any questions for me! 😸

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
