### PR TITLE
Create test_jax_numpy_functions.py

### PR DESCRIPTION
**Pull request by devsugun**
jax.numpy package

### CODE REVIEW

**Comment by devsugun** [comment]
new numpy function

**Comment by devsugun** [comment]
jax.lax_oparator

elementswise implemented #subtract #cos #concat #noinspection DuplicatedCode

**Comment by devsugun** [comment]
element wise operators #divide #cos #concat

**Comment by JLU-Neal** [comment]
Hey @devsugun, I am a little bit confused about why you have created two new files instead of adding test functions to the existing ones.

**Comment by devsugun** [comment]
Sorry for the late response am sure I didn't get the instructions clearly.
I would go back and make some amendment to it correct the mistakes before
the weekend.

Thank you

**Pull request closed without merging**
