### PR TITLE
reformat multi_head_attention (issue #1366)

### PR DESCRIPTION
**Pull request by vinesmsuic**

### CODE REVIEW

**Comment by vinesmsuic** [comment]
#1366

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi, the changes in ivy.layers look good. Though you would also need to add an out argument to the function as well as some examples to the multi_head_attention function. You can find more information [here](https://github.com/unifyai/ivy/blob/75b415dcbdc316e95f75b92f83dc31d38c7d1271/docs/partial_source/deep_dive/11_docstring_examples.rst).
Thanks.

**Comment by vinesmsuic** [comment]
Hi, I am trying to create an example but I am stuck in an error that seems to be associated with `ivy\torch\core\general.py` because the `kv` cannot split.
```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-5d10db0bc484> in <module>
      1 x = ivy.array([[[0.2, 1.], [2.2, 3.],[4.4, 5.6],[7.1, 4.2]]])
----> 2 result = ivy.multi_head_attention(x, scale=1, num_heads=2)
      3 print(result)

c:\Users\vinesmsuic\anaconda3\lib\site-packages\ivy\neural_net_functional\layers.py in multi_head_attention(x, scale, num_heads, context, mask, to_q_fn, to_kv_fn, to_out_fn, to_q_v, to_kv_v, to_out_v)
    153         k, v = kv
    154     else:
--> 155         k, v = ivy.split(kv, 2, -1)
    156 
    157     # BS x H x Q x F,  BS x H x K x F,  BS x H x K x F

c:\Users\vinesmsuic\anaconda3\lib\site-packages\ivy\torch\core\general.py in split(x, num_or_size_splits, axis, with_remainder)
    273 def split(x, num_or_size_splits: Optional[Union[int, List[int]]] = None, axis: int = 0, with_remainder: bool = False)\
    274         -> List[_torch.Tensor]:
--> 275     if x.shape == ():
    276         if num_or_size_splits is not None and num_or_size_splits != 1:
    277             raise Exception('input array had no shape, but num_sections specified was {}'.format(num_or_size_splits))

AttributeError: 'list' object has no attribute 'shape'
```

**Comment by MarShaikh** [comment]
> 

Thanks for pointing this out, this looks like a bug. The split function should be receiving an array but instead is receiving a list. Need to work this out.

**Comment by MarShaikh** [comment]
> ```shell
> x = ivy.native_array([0, 1, 2])
> ```

This looks weird, how are you getting this error again?

**Comment by MarShaikh** [comment]
> I also countered error when creating `Native_Array`. I noticed multiple persons reported this in the discord server but there is no solution yet.
> 
> ```shell
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-6-c3e896ceaa3d> in <module>
> ----> 1 x = ivy.native_array([0, 1, 2])
>       2 x2 = ivy.Container(a=ivy.array([0., 1., 2.]), b=ivy.array([3., 4., 5.]))
> 
> AttributeError: module 'ivy.torch' has no attribute 'native_array'
> ```

This looks weird, how are you getting this error again?

**Comment by vinesmsuic** [comment]
Environment : Windows 10
Installed Ivy through `pip install ivy-core`

Python file `ivy-create.py`
```python
import ivy

ivy.set_framework('torch')  # change to any framework!

first = ivy.array([[[0.2, 1.], [2.2, 3.],[4.4, 5.6]]])
print(first)

second = ivy.Container(w=ivy.array([0., 1., 2.]), b=ivy.array([3., 4., 5.]))
print(second)

third = ivy.native_array([0, 1, 2])
print(third)
```

Output of python file:
```shell
tensor([[[0.2000, 1.0000],
         [2.2000, 3.0000],
         [4.4000, 5.6000]]])
{
    b: tensor([3., 4., 5.]),
    w: tensor([0., 1., 2.])
}
Traceback (most recent call last):
  File ".\ivy-create.py", line 11, in <module>
    third = ivy.native_array([0, 1, 2])
AttributeError: module 'ivy.torch' has no attribute 'native_array'
```

**Comment by MarShaikh** [comment]
> Environment : Windows 10 Installed Ivy through `pip install ivy-core`
> 
> My python file `ivy-create.py`
> 
> ```python
> import ivy
> 
> ivy.set_framework('torch')  # change to any framework!
> 
> first = ivy.array([[[0.2, 1.], [2.2, 3.],[4.4, 5.6]]])
> print(first)
> 
> second = ivy.Container(w=ivy.array([0., 1., 2.]), b=ivy.array([3., 4., 5.]))
> print(second)
> 
> third = ivy.native_array([0, 1, 2])
> print(third)
> ```
> 
> Output of python file:
> 
> ```shell
> tensor([[[0.2000, 1.0000],
>          [2.2000, 3.0000],
>          [4.4000, 5.6000]]])
> {
>     b: tensor([3., 4., 5.]),
>     w: tensor([0., 1., 2.])
> }
> Traceback (most recent call last):
>   File ".\ivy-create.py", line 11, in <module>
>     third = ivy.native_array([0, 1, 2])
> AttributeError: module 'ivy.torch' has no attribute 'native_array'
> ```

Ah okay, I can see where the issue could be. If you've seen the contributor guide, it is recommended to use the latest fork of the repo because we have changed a lot of stuff and it is then easier to debug issues like these. The error you mention does not occur when I try it with my fork.

**Comment by vinesmsuic** [comment]
> > 
> 
> Thanks for pointing this out, this looks like a bug. The split function should be receiving an array but instead is receiving a list. I need to look into this.

Hi, May I know if this has been solved?

**Comment by MarShaikh** [comment]
> > > 
> > 
> > 
> > Thanks for pointing this out, this looks like a bug. The split function should be receiving an array but instead is receiving a list. I need to look into this.
> 
> Hi, May I know if this has been solved?

Hi, sorry for the delay! The issue has been resolved. Let me know if you have any other problem.

**Comment by vinesmsuic** [comment]
Hi @MarShaikh I am a bit stuck in the parameters `to_q_fn`, `to_kv_fn` and `to_out_fn`. I think those parameters are expected to be `ivy.Linear` but I couldn't get it to work. The error is associated to `ivy/functional/ivy/manipulation.py` so I am not sure if this is a bug and I miss inputting something. It would be great if you could help me have a look at it.

```python
x = ivy.random_normal(shape=(1, 2, 4))
context = ivy.random_normal(shape=(1, 2, 4))
mask = ivy.random_normal(shape=(1, 2, 2))
linear_q = ivy.Linear(2, 2)
linear_kv = ivy.Linear(2, 2)
linear_out = ivy.Linear(2, 2)

result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask, to_q_fn=linear_q, to_kv_fn=linear_kv, to_out_fn=linear_out, to_q_v=None, to_kv_v=None, to_out_v=None)
print(result.shape)
```

Error log:

```python
Traceback (most recent call last):
  File "C:\Users\vinesmsuic\Downloads\Temp\ivy-test.py", line 10, in <module>
    result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask, to_q_fn=linear_q, to_kv_fn=linear_kv, to_out_fn=linear_out, to_q_v=None, to_kv_v=None, to_out_v=None)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 229, in new_fn
    ret = fn(*args, **kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 173, in new_fn
    return fn(*native_args, **native_kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\functional\ivy\layers.py", line 412, in multi_head_attention
    q = to_q_fn(x, v=to_q_v) if ivy.exists(to_q_fn) else x
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\module.py", line 659, in __call__
    ret = self._call(*args, v=v, with_grads=with_grads, **kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\module.py", line 388, in _call
    return self._forward_with_tracking(*args, **kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\module.py", line 348, in _forward_with_tracking
    ret = self._forward(*args, **kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\layers.py", line 104, in _forward
    return ivy.linear(inputs, self.v.w, self.v.b if self._with_bias else None)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 229, in new_fn
    ret = fn(*args, **kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 173, in new_fn
    return fn(*native_args, **native_kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\functional\ivy\layers.py", line 53, in linear
    ivy.reshape(
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 229, in new_fn
    ret = fn(*args, **kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 173, in new_fn
    return fn(*native_args, **native_kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 349, in new_fn
    return fn(*args, **kwargs)
  File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\functional\ivy\manipulation.py", line 570, in reshape
    return _cur_backend(x).reshape(x, shape, copy, out=out)
TypeError: reshape() got an unexpected keyword argument 'out'
```


Removing the fns:
```python
x = ivy.random_normal(shape=(1, 2, 4))
context = ivy.random_normal(shape=(1, 2, 4))
mask = ivy.random_normal(shape=(1, 2, 2))

result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask)
print(result.shape)
```
Output:
```
(1, 2, 2)
```

**Comment by MarShaikh** [comment]
> Hi @MarShaikh I am a bit stuck in providing examples with the parameters `to_q_fn`, `to_kv_fn` and `to_out_fn`. I think those parameters are expected to be `ivy.Linear` but I couldn't get it to work. The error is associated to `ivy/functional/ivy/manipulation.py` so I am not sure if this is a bug or I did something wrong. It would be great if you could help me have a look at it.
> 
> ```python
> x = ivy.random_normal(shape=(1, 2, 4))
> context = ivy.random_normal(shape=(1, 2, 4))
> mask = ivy.random_normal(shape=(1, 2, 2))
> linear_q = ivy.Linear(2, 2)
> linear_kv = ivy.Linear(2, 2)
> linear_out = ivy.Linear(2, 2)
> 
> result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask, to_q_fn=linear_q, to_kv_fn=linear_kv, to_out_fn=linear_out, to_q_v=None, to_kv_v=None, to_out_v=None)
> print(result.shape)
> ```
> 
> Error log:
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Users\vinesmsuic\Downloads\Temp\ivy-test.py", line 10, in <module>
>     result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask, to_q_fn=linear_q, to_kv_fn=linear_kv, to_out_fn=linear_out, to_q_v=None, to_kv_v=None, to_out_v=None)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 229, in new_fn
>     ret = fn(*args, **kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 173, in new_fn
>     return fn(*native_args, **native_kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\functional\ivy\layers.py", line 412, in multi_head_attention
>     q = to_q_fn(x, v=to_q_v) if ivy.exists(to_q_fn) else x
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\module.py", line 659, in __call__
>     ret = self._call(*args, v=v, with_grads=with_grads, **kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\module.py", line 388, in _call
>     return self._forward_with_tracking(*args, **kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\module.py", line 348, in _forward_with_tracking
>     ret = self._forward(*args, **kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\stateful\layers.py", line 104, in _forward
>     return ivy.linear(inputs, self.v.w, self.v.b if self._with_bias else None)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 229, in new_fn
>     ret = fn(*args, **kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 173, in new_fn
>     return fn(*native_args, **native_kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\functional\ivy\layers.py", line 53, in linear
>     ivy.reshape(
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 229, in new_fn
>     ret = fn(*args, **kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 173, in new_fn
>     return fn(*native_args, **native_kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py", line 349, in new_fn
>     return fn(*args, **kwargs)
>   File "C:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\functional\ivy\manipulation.py", line 570, in reshape
>     return _cur_backend(x).reshape(x, shape, copy, out=out)
> TypeError: reshape() got an unexpected keyword argument 'out'
> ```
> 
> Removing the fns:
> 
> ```python
> x = ivy.random_normal(shape=(1, 2, 4))
> context = ivy.random_normal(shape=(1, 2, 4))
> mask = ivy.random_normal(shape=(1, 2, 2))
> 
> result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask)
> print(result.shape)
> ```
> 
> Output:
> 
> ```
> (1, 2, 2)
> ```

Hi, I've been trying to reproduce your error but I cannot. It looks like it might have been fixed, because there is another error related to shapes. Please have a look. Thanks.

**Comment by vinesmsuic** [comment]
@MarShaikh Sorry for the late update, the examples have been added.

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Can you remove the instance method examples? As: 
1. It doesn't make sense to add instance method example for this type of functon. 
2. The instance method example are not correct. 
Other than that, everything else looks good!

**Comment by MarShaikh** [comment]
> @MarShaikh Just removed the instance method example.

Thanks for a lot for the changes. I see that there are some issues with your code and that the test-docstrings is failing because of it. Could you please take a look? If you can, if it isn't causing any errors, add a container example to the docstrings? So sorry for not mentioning earlier!

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Thanks for a lot for the changes. I see that there are some issues with your code and that the test-docstrings is failing because of it. Could you please take a look? If you can, if it isn't causing any errors, add a container example to the docstrings? So sorry for not mentioning earlier!

**Comment by vinesmsuic** [comment]
> Thanks for a lot for the changes. I see that there are some issues with your code and that the test-docstrings is failing because of it. Could you please take a look? If you can, if it isn't causing any errors, add a container example to the docstrings? So sorry for not mentioning earlier!

Hey @MarShaikh  , I encountered some errors and I could not run MHA when using `ivy.Container`. Can you please have a look if I missed something?

Experiment 1:
```python
x = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)), b=ivy.random_normal(shape=(1, 4, 4)))
context = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)), b=ivy.random_normal(shape=(1, 4, 4)))
mask = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)), b=ivy.random_normal(shape=(1, 4, 4)))

linear_q = ivy.Linear(4, 4)
linear_kv = ivy.Linear(4, 4)
linear_out = ivy.Linear(2, 2)

result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask, to_q_fn=linear_q, to_kv_fn=linear_kv, to_out_fn=linear_out, to_q_v=None, to_kv_v=None, to_out_v=None)
print(result.shape)
print(result)
```
Error log:
```shell
RuntimeError                              Traceback (most recent call last)
     linear_kv = ivy.Linear(4, 4)
     linear_out = ivy.Linear(2, 2)
---> result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask, to_q_fn=linear_q, to_kv_fn=linear_kv, to_out_fn=linear_out, to_q_v=None, to_kv_v=None, to_out_v=None)
     print(result.shape)
     print(result)

File c:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py:147, in outputs_to_ivy_arrays.<locals>.new_fn(*args, **kwargs)
    130 """
    131 Calls the function, and then converts all `ivy.NativeArray` instances in
    132 the function return into `ivy.Array` instances.
   (...)
    144     The return of the function, with native arrays as ivy arrays.
    145 """
    146 # call unmodified function
--> 147 ret = fn(*args, **kwargs)
    148 # convert all arrays in the return to `ivy.Array` instances
    149 return ivy.to_ivy(ret, nested=True, include_derived={tuple: True})

File c:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py:87, in inputs_to_native_arrays.<locals>.new_fn(*args, **kwargs)
     83 # convert all arrays in the inputs to ivy.NativeArray instances
     84 native_args, native_kwargs = ivy.args_to_native(
     85     *args, **kwargs, include_derived={tuple: True}
...
     49             if backend.is_appropriate_type(tensor):
     50                 return backend
---> 52 raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))

RuntimeError: Tensor type unknown to einops <class 'str'>
```

Experiment 2:
```python
x = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)))
context = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)))
mask = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)))

linear_q = ivy.Linear(4, 4)
linear_kv = ivy.Linear(4, 4)
linear_out = ivy.Linear(2, 2)

result = ivy.multi_head_attention(x, scale=1, num_heads=2, context=context, mask=mask, to_q_fn=linear_q, to_kv_fn=linear_kv, to_out_fn=linear_out, to_q_v=None, to_kv_v=None, to_out_v=None)
print(result.shape)
print(result)
```
Error log:
```shell
ValueError                                Traceback (most recent call last)
File c:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py:147, in outputs_to_ivy_arrays.<locals>.new_fn(*args, **kwargs)
    130 """
    131 Calls the function, and then converts all `ivy.NativeArray` instances in
    132 the function return into `ivy.Array` instances.
   (...)
    144     The return of the function, with native arrays as ivy arrays.
    145 """
    146 # call unmodified function
--> 147 ret = fn(*args, **kwargs)
    148 # convert all arrays in the return to `ivy.Array` instances
    149 return ivy.to_ivy(ret, nested=True, include_derived={tuple: True})

File c:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py:87, in inputs_to_native_arrays.<locals>.new_fn(*args, **kwargs)
     83 # convert all arrays in the inputs to ivy.NativeArray instances
     84 native_args, native_kwargs = ivy.args_to_native(
     85     *args, **kwargs, include_derived={tuple: True}
...
    433     lambda t: ivy.einops_rearrange(t, "... n (h f) -> ... h n f", h=num_heads),
    434     (q, k, v),
    435 )

ValueError: not enough values to unpack (expected 2, got 1)
```

Experiment 3:
```python
x = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)))
context = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)))
mask = ivy.Container(a=ivy.random_normal(shape=(1, 4, 4)))

result = ivy.multi_head_attention(x, scale=1, num_heads=2)
print(result.shape)
print(result)
```
Experiment 3:
```shell
AttributeError                            Traceback (most recent call last)
File c:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py:147, in outputs_to_ivy_arrays.<locals>.new_fn(*args, **kwargs)
    130 """
    131 Calls the function, and then converts all `ivy.NativeArray` instances in
    132 the function return into `ivy.Array` instances.
   (...)
    144     The return of the function, with native arrays as ivy arrays.
    145 """
    146 # call unmodified function
--> 147 ret = fn(*args, **kwargs)
    148 # convert all arrays in the return to `ivy.Array` instances
    149 return ivy.to_ivy(ret, nested=True, include_derived={tuple: True})

File c:\Users\vinesmsuic\anaconda3\envs\ivy\lib\site-packages\ivy\func_wrapper.py:87, in inputs_to_native_arrays.<locals>.new_fn(*args, **kwargs)
     83 # convert all arrays in the inputs to ivy.NativeArray instances
     84 native_args, native_kwargs = ivy.args_to_native(
     85     *args, **kwargs, include_derived={tuple: True}
...
    132                     num_or_size_splits
    133                 )
    134             )

AttributeError: 'list' object has no attribute 'shape'
```

**Comment by MarShaikh** [comment]
> 

So sorry for the delay in making this review. I tried to resolve the issue with containers and multihead attention head as well. It seems like there are some issues we would need to work on. I'll leave the PR open for now and we can come back to this after we resolved those issues. Thanks so much for these updates!

**Comment by vinesmsuic** [comment]
> > 
> 
> So sorry for the delay in making this review. I tried to resolve the issue with containers and multihead attention head as well. It seems like there are some issues we would need to work on. I'll leave the PR open for now and we can come back to this after we resolved those issues. Thanks so much for these updates!

It's okay! Hope the issues could be fixed soon.

**Comment by vinesmsuic** [comment]
@MarShaikh hi may I know why is it closed?

**Pull request closed without merging**
