### PR TITLE
Add adjust_hue function to paddle.vision.transforms

### LINKED ISSUE #21317: adjust_hue

### PR DESCRIPTION
**Pull request by ozogxyz**
Close #21317

### CODE REVIEW

**Comment by ozogxyz** [comment]
@sagewhocodes Could you take a look at this whenever you have time? It's for the internship challenge.

**Comment by sagewhocodes** [comment]
ivy-gardener

**Comment by ozogxyz** [comment]
I didn't quite understand

**Comment by sagewhocodes** [comment]
@ozogxyz that's just the `ivy-gardener` which lints the code so that it can be ready to get merged after the PR. Will review it soon 😄

**Comment by ozogxyz** [comment]
Ah ok, let's close this soon so I can move on to other transformations😀

**Comment by sagewhocodes** [comment]
>@with_supported_dtypes({"2.5.1 and below": ("float32", "float64")}, "paddle")
@ozogxyz any particular reason on limited the dtypes to `float32 & float64` ?
The example here uses `uint8` so the frontend function should Ideally work with all `numeric` types?

Also the tests for the torch backend are failing with `rtol=1e-3` and `atol=1e-3` , could you please look into it?

**Comment by sagewhocodes** [comment]
Great find @ozogxyz ! Could you include this behaviour in your frontend implementation? Ideally all frontend functions should map 1:1 to their framework counterparts, which means we should support `uint8` too 😄

**Comment by ozogxyz** [comment]
@sagewhocodes When I add `int32` to 

`@with_supported_dtypes({"2.5.1 and below": ("float32", "float64", "uint8", "int32")}, "paddle")`

the `stack` function throws this error.

**Comment by ozogxyz** [comment]
@sagewhocodes Yes, so that's why I used `@with_supported_dtypes({"2.5.1 and below": ("float32", "float64", "uint8")}, "paddle")`. 

Then only remaining issue is tolerance, right?

**Comment by sagewhocodes** [comment]
Actually
PIL doesn't seem to work well with `int32` arrays but np.arrays work fine with `int32` and the rest of the data types. 
The ideal way to figure out what data types to test on is by referring to docs or manually testing out the desired function on all of the datatypes.

**Comment by sagewhocodes** [comment]
I don't really think having `int32` as a valid input would actually benefit the function in any way considering the images have limited numerical range by design, feel free to omit this data type in your decorator 😄

**Comment by ozogxyz** [comment]
@sagewhocodes Why is Combined Test Results not showing this function?

**Comment by sagewhocodes** [comment]
This was the same issue with me when I was checking the CI, could you run the tests locally with `pytest -v <test_file_path.py>::<test_name>` and see if those tests pass?

I'll ask the CI team regarding this, Thanks!

**Comment by ozogxyz** [comment]
@sagewhocodes 
Screenshot 2023-08-14 at 12 39 39

Passing locally. Ignore paddle skipping for now, that's another issue raised on Discord, that test passes on CI normally😄

**Comment by sagewhocodes** [comment]
LGTM, Awesome work @ozogxyz !

**Comment by ozogxyz** [comment]
@sagewhocodes Thank you for your help:)

**Pull request merged**
