### PR TITLE
Added-embedding_lookup

### PR DESCRIPTION
**Pull request by sdanishka**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by suvadityamuk** [comment]
Hello, @sdanishka!

Thank you so much for your contribution to Ivy :grin:, and apologies for the delays.

It seems you may have to make a new PR, as you may know that we recently had a `git push --force` that changed the commit histories of repositories (the reason why you see so many different file changes). A possible solution to repairing this PR itself can also be found in this [very detailed explanation from Dan on our Discord server](https://discord.com/channels/799879767196958751/983684937712558080/1080080255387189318). Please feel free to go through that to update your PR, and ping me once, I shall be happy to review then! 

Thanks again! :slightly_smiling_face:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
