### PR TITLE
adding instance method __ilshift__ for numpy frontend

### LINKED ISSUE #16556: __ilshift__

### PR DESCRIPTION
**Pull request by redorblueorred**
Close #16556

### CODE REVIEW

**Comment by redorblueorred** [comment]
Hi @Infrared1029 could u review this, needed some feedback

**Comment by Infrared1029** [comment]
Hello @redorblueorred, very sorry for the late reply, can you fix the merge conflict? ill take a look right away after that!

**Comment by redorblueorred** [comment]
Hi @Infrared1029, fixed the merge conflicts, have a look.

**Comment by Infrared1029** [comment]
can we revert the array api changes? updates should be done in the ndarray and test files only.

**Comment by redorblueorred** [comment]
I have removed the array api changes

**Comment by redorblueorred** [comment]
Hi @Infrared1029, could u merge the changes.

**Comment by Infrared1029** [comment]
woops, was out of office for a few days, this completely slipped under my radar, will check it right away and merge if everything looks good!

**Comment by Infrared1029** [comment]
Hey, @redorblueorred taking a closer look, I'd suggest you first create a PR that implements the frontend function `np.left_shift`, and then use that in the method `__ilshift__` by returning `np_frontend.left_shift(self, value)`, the current implementation is flawed because `ivy.bitwise_left_shift` only works with `ivy.Arrays`, while the value argument could be a `numpy.frontend.ndarray`, this can be obviously handled by some conditions but that would convolute the function for no reason, a cleaner solution would be, as described above, to implement the frontend method for bitwise left shifting and using that.

(the same issue is with `__rshift__` which ill be flagging to the team internally)

**Comment by redorblueorred** [comment]
Hi @Infrared1029, for class ndarray (in ivy), self.ivy_array would always be of type ivy.Array. Is this understanding correct?

**Comment by Infrared1029** [comment]
> Hi @Infrared1029, for class ndarray (in ivy), self.ivy_array would always be of type ivy.Array. Is this understanding correct?

that is correct, however, we expect the function to work with ivy arrays, native arrays, and frontend arrays as well, this is automatically handled if we use the frontend functions instead of ivy directly (specifically the frontend array part).

**Comment by redorblueorred** [comment]
Hi @Infrared1029, I have tried to create some example usage for instance method __ilshift__ (for class ivy.frontends.numpy.ndarray).


import ivy.functional.frontends.numpy as np_frontend

## using the method __ilshift__

arr1 = np_frontend.array([2, 4])
>> print(arr1)
ivy.frontends.numpy.ndarray([2, 4])


res1 = arr1.__ilshift__(2)
>> print(res1)
ivy.frontends.numpy.ndarray([ 8, 16])


## arr1 is also updated
>> print(arr1)
ivy.frontends.numpy.ndarray([ 8, 16])



## using the related operator <<=

arr2 = np_frontend.array([2, 4])
>> print(arr2)
ivy.frontends.numpy.ndarray([2, 4])


arr2 <<= 2
>> print(arr2)
ivy.frontends.numpy.ndarray([ 8, 16])


Could you help me in getting similar examples for other array types : ivy arrays and native arrays, so I can understand their usage with this instance method ( ivy.frontends.numpy.ndarray.__ilshift__).

**Comment by Infrared1029** [comment]
```python
import numpy as np
import ivy.functional.frontends.numpy as ivy_np

a = np.array([1,2,3])
a <= np.array([1,1,1]) # a is now array([2, 4, 6])


b = ivy_np.array([1,2,3])
b <= ivy_np.array([1,1,1]) # fails

```

**Comment by redorblueorred** [comment]
Hi, @Infrared1029 , I am working on the function "np_left_shift" in this branch: 
https://github.com/redorblueorred/ivy/tree/branch_np_lshift

Could you point me to the ToDo list for this function, so I can update?

**Pull request closed without merging**
