### PR TITLE
Fix Frontend Failing Test: paddle - comparison.numpy.greater_equal

### PR DESCRIPTION
**Pull request by ZJay07**
# PR Description
Error thrown due to complex comparison, `paddle` does not support complex for `greater equal` not sure why the function was trying to do so, removing the comparison works, but not sure if it was essential to make a "`complex` acceptable" `paddle.greater_equal`

ref: https://www.paddlepaddle.org.cn/documentation/docs/en/2.2/api/paddle/greater_equal_en.html#greater-equal

## Related Issue

Close https://github.com/unifyai/ivy/issues/28700

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Review by Ishticode — COMMENTED** [review]
I think this was based on our goal to superset the functions. So our backends are as comprehensive as possible. I think numpy support complex comparison so perhaps its trying to copy that. 
image

Could you possibly check that out if it matches with np. Thank you very much :)

**Comment by ZJay07** [comment]
Similar fix to https://github.com/unifyai/ivy/pull/28688

**Comment by Ishticode** [comment]
> Similar fix to #28688

Thanks. Similar to #28688 I would say supported dtypes can be extended here too like int8. But I can leave that for another PR. As you changes here don't touch the suppported dtypes decorators etc. As opposed to #28688.

**Review by Ishticode — APPROVED** [review]
Thanks @ZJay07 for the effort put into this fix :)

**Pull request merged**
