### PR TITLE
EHN: added less_than method in paddle tensor.py

### LINKED ISSUE #17853: less_than
Adding less_than function paddle.tensor.tensor.py

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
Closed #17853

### CODE REVIEW

**Comment by KareemMAX** [comment]
Hey @MuhammadNizamani 

To streamline the review process a little bit. Do you mind adding a comment and in it "add_frontend_checklist" (without double quotes nor newlines)? Our automation will convert your comment into a checklist where you can fill which points you have completed, then I'll start our review process

**Comment by MuhammadNizamani** [comment]
add_frontend_checklist

**Comment by MuhammadNizamani** [comment]
@KareemMAX I have add some so checks on it?

**Review by KareemMAX — APPROVED** [review]
LGTM! Thanks for your contribution @MuhammadNizamani

**Pull request merged**
