### PR TITLE
Add maxwell to Jax random frontend

### LINKED ISSUE #14881: maxwell

### PR DESCRIPTION
**Pull request by iammarco11**
closes #14881

### CODE REVIEW

**Comment by iammarco11** [comment]
@ZoeCD looking forward to hearing your inputs and thoughts on this addition :)

**Comment by iammarco11** [comment]
@ZoeCD could you please review this? Thank you.

**Comment by ZoeCD** [comment]
Hello! My apologies for the late response. The test is failing for Torch, but it seems to be a common problem for these functions. Please just add `# TODO Update the test by fixing the uint32 unsupported problem` before the test

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by stalemate1** [comment]
Hello @iammarco11 I am working on double_sided_maxwell for which I would like to use your Maxwell() code. Please let me know if it is okay.

**Pull request closed without merging**
