### PR TITLE
Added less_than function and test to Paddle frontend

### PR DESCRIPTION
**Pull request by a1701s**

### CODE REVIEW

**Comment by a1701s** [comment]
#15115 added less_than function

**Review by Aarsh2001 — CHANGES_REQUESTED** [review]
Hi @a1701s, you are supposed to add these functions as instance methods in the `paddle/tensor/tensor.py` class. Also, there doesn't exist any `ivy.less_than` function in the functional API. Please make the suggested changes, and re-request a review from me, thanks 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Aarsh2001** [comment]
Feel free to reopen once you're done with your changes thanks

**Pull request closed without merging**
