### PR TITLE
add docstrings of stop_gradient function

### LINKED ISSUE #2241: stop_gradient

### PR DESCRIPTION
**Pull request by yugaljain1999**
fixes #2241

### CODE REVIEW

**Comment by yugaljain1999** [comment]
@RashulChutani Can u pls review this PR?

**Review by RashulChutani — COMMENTED** [review]
@yugaljain1999 Sure.

**Review by RashulChutani — COMMENTED** [review]
@yugaljain1999 The added docstring looks good. Can you also make the required changes for the corresponding Ivy container and Array Functions as mentioned here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting. Thanks

**Comment by yugaljain1999** [comment]
@RashulChutani Can you merge this PR too? As reason is same as explained here. #2222

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @yugaljain1999, Can you please make the docstrings test pass for the stop_gradient function?

**Comment by yugaljain1999** [comment]
@RashulChutani I just checked those docstrings test but that's failing because of another function not this optimizer_update function as you can see here.
image
image
image


Hope it's clear to you now. Now you can merge this PR.
Thanks

**Comment by yugaljain1999** [comment]
@RashulChutani I just updated docstrings for this function. You can review and merge PR .
Thanks

**Pull request merged**
