### PR TITLE
operator functions numeric support for numpy

### PR DESCRIPTION
**Pull request by juliagsy**
operator functions with numeric support added: 
- add, subtract, divide, floor_divide, multiply, remainder, pow
- positive, negative, abs
- less, less_equal, greater, greater_equal, equal, not_equal
- bitwise => and, or, xor, invert, left_shift, right_shift

Feel free to let me know if I left out any other operator functions! Thank you!!

### CODE REVIEW

**Comment by juliagsy** [comment]
Changes done according to review in PR #1448 

The last PR is a bit messy, so I opened a new PR and update the support by backend/framework. Functions changed are stated in the description! Thanks!

**Review by mattbarrett98 — COMMENTED** [review]
Hey, just thought I’d add that the out argument and the return type should just be np.ndarray. This is because numpy’s out argument only works with numpy arrays, and the decorator on these functions ensures the output is always a numpy array (never a float, bool etc)

**Comment by juliagsy** [comment]
Hey @mattbarrett98 thanks for pointing that out! I added that because of some clarifications mentioned in this discussion (https://github.com/unifyai/ivy/discussions/1320)

If that's a issue, I'll make a fix! Thank you!

**Comment by mattbarrett98** [comment]
The `out` argument definitely can't accept anything other than np.ndarrays so you can remove this. Maybe we can wait for confirmation from Dan about the returns being numbers, I think this discussion was before I added the decorator which calls `np.asarray` on the return if it isn't an `np.ndarray` already.

**Review by djl11 — CHANGES_REQUESTED** [review]
Yes, given that we've recently decided to return arrays in cases where numbers are passed in the input, then perhaps parts of this PR are incorrect. Could you remove any changes which cause numbers to be returned, and keep any changes you think are still relevant even with this updated decision of desired behaviour, and then I'll review again. Otherwise, feel free to close if you deem that all of these changes are no longer relevant.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hey I just wrote a function `_cast_for_binary_op`, which implements the logic we want, could you add this to the relevant functions (I've done it for `add`). This way we aren't repeating the same logic in many functions. 

Also, I think the bitwise functions can take both `int` and `bool`.

**Comment by juliagsy** [comment]
@mattbarrett98 Will update them now! And you're right, almost missed out bool, thanks a lot!

**Review by mattbarrett98 — COMMENTED** [review]
Just noticed you forgot to edit `atan2` (it's near the bottom of the file). After this change though I think I'm happy and we'll just wait for Dan's confirmation.

**Review by djl11 — APPROVED** [review]
lgtm!

**Pull request merged**
