### PR TITLE
fix: failing test for sin 

### PR DESCRIPTION
**Pull request by Aaryan562**
failing test for sin (shared priority task) #12656

### CODE REVIEW

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @Aaryan562, thanks a lot for looking into this failing test. Could you please link [this](https://github.com/unifyai/ivy/issues/12656) issue in the PR title. Also, I'm not sure if I follow why we shouldn't be testing for gradients in this function, could you please explain why it is necessary to set `test_gradients` as `False` in this?

**Comment by Aaryan562** [comment]
> Hey @Aaryan562, thanks a lot for looking into this failing test. Could you please link [this](https://github.com/unifyai/ivy/issues/12656) issue in the PR title. Also, I'm not sure if I follow why we shouldn't be testing for gradients in this function, could you please explain why it is necessary to set `test_gradients` as `False` in this?

```
ivy.utils.exceptions.IvyBackendException: paddle: mean: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), float16) of kernel `mean` is not registered. Selected wrong DataType `float16`. Paddle support following DataTypes: float64, complex128, float32, complex64, bool.
E         [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:199)
```
@hello-fri-end Basically when `paddle` was taking `float16` dtype and  `test_gradients` flag was set to `True` it gave the above error. So in my latest commit I have focused on that but I am not quite sure why is error for this condition. Maybe your inputs could help.

**Comment by Aaryan562** [comment]
@vedpatwardhan Since @hello-fri-end would be inactive this week, could you pls review my PR

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Feel free to merge, thanks @Aaryan562 😄

**Pull request merged**
