### PR TITLE
added cos function in jax frontend

### PR DESCRIPTION
**Pull request by emekaokoli19**

### CODE REVIEW

**Comment by emekaokoli19** [comment]
#3481

**Comment by emekaokoli19** [comment]
[#3481 ](url)

**Comment by emekaokoli19** [comment]
[#3481 ](#3481 )

**Review by JonathanYang-yzh — CHANGES_REQUESTED** [review]
Hello, thank you for the commits! Could you please remove changes to the IDE configuration? Please let me know when you are done.

**Comment by emekaokoli19** [comment]
> Hello, thank you for the commits! Could you please remove changes to the IDE configuration? Please let me know when you are done.

Hi, I've tried to remove it but I think I made it worse, can I add the .idea folder to gitignore? or is there a way you can ignore those files

**Comment by emekaokoli19** [comment]
> Hello, thank you for the commits! Could you please remove changes to the IDE configuration? Please let me know when you are done.

I have removed the changes made in the .idea files, they are now the same with the o

**Comment by emekaokoli19** [comment]
> Hello, thank you for the commits! Could you please remove changes to the IDE configuration? Please let me know when you are done.

I have removed the changes made in the .idea files, they are now the same with the original files.

**Review by JonathanYang-yzh — APPROVED** [review]

**Pull request merged**
