### PR TITLE
Torch reduction_ops count_nonzero

### LINKED ISSUE #5902: count_nonzero

### PR DESCRIPTION
**Pull request by Dsantra92**
Closes  #5902

### CODE REVIEW

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey :)

Seems tests didn't run properly, can give a full review when they finish up. In the mean time there seems to be some formatting errors in the files you have edited in this PR. You can install a pre-commit hook to prevent these, instructions are [here](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit).

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey, seems to be that the relevant test for this function is failing. This would need to be passing before we can go ahead and merge :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
