### PR TITLE
multinomial function is added for numpy

### PR DESCRIPTION
**Pull request by eldorabdukhamidov**

### CODE REVIEW

**Comment by eldorabdukhamidov** [comment]
Close #4728

**Comment by eldorabdukhamidov** [comment]
Hi @MrZilinXiao. Can you help to merge the change?

**Comment by MrZilinXiao** [comment]
Hi @eldorabdukhamidov. Thanks for your contribution, and sorry for my late reply (was taking some leave). 
a) would you mind moving modification towards `setup.py` out of this PR? We want to make sure each PR serves its own purpose rather than a mixture.
b) I noticed the tests are not passing for `test_numpy_multinomial` here: https://github.com/unifyai/ivy/actions/runs/3164137718/jobs/5152217095#step:6:111164.

**Comment by eldorabdukhamidov** [comment]
> Hi @eldorabdukhamidov. Thanks for your contribution, and sorry for my late reply (was taking some leave). a) would you mind moving modification towards `setup.py` out of this PR? We want to make sure each PR serves its own purpose rather than a mixture. b) I noticed the tests are not passing for `test_numpy_multinomial` here: https://github.com/unifyai/ivy/actions/runs/3164137718/jobs/5152217095#step:6:111164.

Thank you for your reply. I will remove unnecessary files. Last time, I opened another PR for the same task and it passed all the test cases. For some reason, the code base was updated and I had to create a new PR. I am using the same code for the task, however, it is showing an error. In my local computer, it is passing all the test cases without any issues. Can you help find the issue?

**Comment by eldorabdukhamidov** [comment]
@MrZilinXiao I have a question. If you look at the issue description, it says that the function is receiving an unexpected keyword. However, I am not passing any keyword with the name.

```
>       ins_gt = frontend_class(*args_constructor_frontend, **kwargs_constructor_frontend)
E       TypeError: array() got an unexpected keyword argument 'data'

ivy_tests/test_ivy/helpers/function_testing.py:1306: TypeError
__ test_numpy_multinomial[cpu-ivy.functional.backends.numpy-True-False-numpy] __
```

**Comment by MrZilinXiao** [comment]
Hi @eldorabdukhamidov. Yes, you are right; I don't think this unexpected keyword `data` comes from your commit. Would you mind enabling debugging for this specific test and using `step into` to see the call stack? I believe this will help you diagnose the problem. I will put this on my todo list once I finish some urgent jobs.

**Comment by abdrahmandiab** [comment]
Hi @eldorabdukhamidov,
as Zilin has left our team for the time being, I am going to be handling the process of reviewing this PR from now on! To catch me up to speed, could you please reply back with a little summary of what is left to be done/ progress so far?

Thanks! and looking forward to working with you!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
