### PR TITLE
element wise abs implementation

### PR DESCRIPTION
**Pull request by sounritesh**
Pull request for issue #506 

All tests pass for element-wise abs implementation.
Looking forward to seeing this merged in the project.

### CODE REVIEW

**Comment by sounritesh** [comment]
Seems to be some issue with my local setup, all tests pass on the cloud.
This request is good to go from my side.
Looking forward to seeing it merged with the project.

Thank you!

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @sounritesh , thank you for your efforts. can you remove the .idea files. Also, can you add the implementation to the jax backend module ? Can you also uncomment the corresponding test for abs from "ivy_tests\array_api_methods_to_test\elementwise_functions.txt"?

**Comment by sounritesh** [comment]
Hello @saeedashrraf , I have made the requested changes, thanks for the feedback!

**Review by saeedashrraf — APPROVED** [review]

**Comment by saeedashrraf** [comment]
Hi @sounritesh , thank you for your efforts :)

**Pull request merged**
