### PR TITLE
feat: add lrn ops nn layer function support to mindspore

### LINKED ISSUE #21047: lan

### PR DESCRIPTION
**Pull request by sushmanthreddy**
close #21047

### CODE REVIEW

**Comment by sushmanthreddy** [comment]
@RickSanchezStoic can u pls review the pr and pls  let me knew any changes are needed?

**Comment by RickSanchezStoic** [comment]
@sushmanthreddy your entire test is commented out, can you please update that ? Thanks!

**Comment by sushmanthreddy** [comment]
@RickSanchezStoic was commented out for a cause... 
There is no mindspore framework support at ivy.. 
That is the reason we  have commented out the whole code... For not making any complexity

**Comment by sushmanthreddy** [comment]
@RickSanchezStoic once plss review th pull request

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @sushmanthreddy 

Would you remove the changes that you added to the `test_array_api` submodule.

**Comment by sushmanthreddy** [comment]
@hirwa-nshuti those are merge conflicts... i havent added anything..to it

**Comment by hirwa-nshuti** [comment]
> @hirwa-nshuti those are merge conflicts... i havent added anything..to it

We have updated the array API submodule with the latest changes and your PR is referring to old version of the submodule

**Comment by sushmanthreddy** [comment]
@hirwa-nshuti if u dont mind how to change that now??can u pls help me with that??

**Comment by sushmanthreddy** [comment]
@hirwa-nshuti I have followed ur implementation as mentioned but no changes are coming following commands
can u pls elaborate it clearly??

**Comment by sushmanthreddy** [comment]
@hirwa-nshuti the file has been removed..can u plss review once ..

**Comment by joaozenobio** [comment]
Hi @sushmanthreddy! Sorry for the delay on an response to your PR. I'll  be reviweing it for you now. Any questions you may have just pin me here :smile: I have a task and a question for you:

* Please, resolve the conflicts of your PR.
* Correct me if I am wrong. On your function:

output[b, r, c, d] /= ivy.pow(bias + alpha * ivy.sum(patch * patch), beta)

didn't you miss dividing alpha by n (depth diameter)?

Screenshot from 2024-01-22 23-08-18

I am going to look into your tests while I wait for your answer.

**Comment by sushmanthreddy** [comment]
@joaozenobio I don't have the laptop ,where ivy has been setup. @JyothiSwaroopReddy07 can u take this pull request and make required changes
?

**Comment by joaozenobio** [comment]
Hi @sushmanthreddy ! Please, when you make the corrections execute the example that can be found in the [mindspore lrn [
documentation page](https://www.mindspore.cn/docs/en/r2.0/api_python/ops/mindspore.ops.LRN.html#mindspore.ops.LRN).

x = Tensor(np.array([[[[0.1], [0.2]],
                      [[0.3], [0.4]]]]), mindspore.float32)
lrn = ops.LRN()
output = lrn(x)
print(output)

And check your implementation with this unit test. :smile:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
