### PR TITLE
feat: added hfft function to jax frontend

### LINKED ISSUE #26088: hfft

### PR DESCRIPTION
**Pull request by UggoPrince**
# PR Description

added hfft function in the fft.py file in numpy folder in jax frontend

## Related Issue

Close #26088

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by tomatillos** [comment]
Hey, great start. The tests for hfft aren't passing, so maybe need to start there :) Also we don't need the docstring (as helpful as it is)!

**Comment by UggoPrince** [comment]
> Hey, great start. The tests for hfft aren't passing, so maybe need to start there :) Also we don't need the docstring (as helpful as it is)!

Thank you. I will check on the test.
Please what docstring are you referring to?

**Comment by UggoPrince** [comment]
@tomatillos All the tests are now passing. Please review again.

**Comment by UggoPrince** [comment]
> Hey, great start. The tests for hfft aren't passing, so maybe need to start there :) Also we don't need the docstring (as helpful as it is)!

@tomatillos tests are now passing. Please review again.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @UggoPrince 
Thanks for the PR and sorry for the delays.
Few things to consider.
Firstly, pls remove the additonal file `::test_jax_numpy_hfft` with failure logs. Secondly, pls ensure the test runs the correct function. 
Secondly, This test is meant for hfft (hermitian) but the fn tree is passing ifft (inverse). So even if it passes it passes for the wrong function. Let me know if something is unclear and once you are fixed please request a review :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ishticode** [comment]
Closing this due to inactivity for over 3 weeks after changes were requested. Please feel free to reopen if you would like to continue working on this. Thank you :)

**Pull request closed without merging**
