### PR TITLE
not_equal

### PR DESCRIPTION
**Pull request by davidlee1102**

### CODE REVIEW

**Review by chie2727 — APPROVED** [review]
Hi @davidlee1102 , thanks for making the new PR.
I'll merge your changes in now!

**Comment by hirwa-nshuti** [comment]
Hello @chie2727 I don't know if it's just me facing this issue but seems like these changes are failing docstrings tests some docstring outputs are not equal and it is raising errors for my PR which was working well last night.

Example here : 
`>>> x1 = ivy.array([1, -1, 1, -1])
>>> x2 = ivy.array([0, -1, 1, 0])
>>> y = ivy.not_equal(x1, x2, out=x1)
`
Output is showing: `ivy.array([1.,1.,1.,1.])` in Docstring as it would be `ivy.array([1, 0, 0, 1])` if I am right.

Thanks

**Comment by davidlee1102** [comment]
Hi @hirwa-nshuti  and @chie2727 ,
Let me check it and create new brand for fixing this problem,
Thank you
David

**Comment by davidlee1102** [comment]
Hi @chie2727 ,
I have fixed some error that existed on this PR, and also created new PR for merging
Here is a new PR: 
- [ ]  https://github.com/unifyai/ivy/pull/1789
Hope that you can check and start to merge it again
Also thank for @hirwa-nshuti who have found some errors on my PR
Thank you,
David

**Pull request merged**
