### PR TITLE
conv3d_transpose #1793

### PR DESCRIPTION
**Pull request by DankGunther**

### CODE REVIEW

**Comment by sreegandh804** [comment]
Hi @DankGunther , I just wanted to point out a few things:
1. You have added layers.py .For the open source coding challenge , applicants are not expected to add any new files to the repository. 
2. Your task is to just edit the files in the IVY API and Backend APIs, I do not see the required changes made to these files,
Hence I would suggest you read through the description of the task again and make another commit. 🙂

**Comment by DankGunther** [comment]
> Hi @DankGunther , I just wanted to point out a few things:
> 
> 1. You have added an extra layers.py file with your commit .For the open source coding challenge , applicants don't have to add any new files to the repository at all.
> 2. Your task is to just edit the files in the IVY API and Backend APIs, I do not see the required changes made to these files,
>    Hence I would suggest you read through the description of the task again and make another commit. 🙂

Okay
Thank you Sree. Just one question though( I think I misunderstood something)
What files am I supposed to make these changes in( it's a bit difficult for me to understand)
Maybe you could send a link to them and I'll get it done right away

**Comment by DankGunther** [comment]
In the backends do I need to make changes for all these: (Jax, mxnet, numpy, tensor flow and torch) in their respective layers.py files ?

**Comment by sreegandh804** [comment]
Hi @DankGunther , I would suggest you go though the deep dive section(https://lets-unify.ai/ivy/deep_dive.html) and open task(https://lets-unify.ai/ivy/contributing/4_open_tasks.html) section in the docs, which i think could be helpful references for you to understand the task better 🙂 .

**Comment by DankGunther** [comment]
Thank you @sreegandh804 for your response, I will go through the documentation again and make changes. If I have any doubts I will reach out to you

**Comment by DankGunther** [comment]
I just committed file changes for ivy.functional.backends.jax.layers @sreegandh804

**Pull request closed without merging**
