### PR TITLE
refactor: removed lambda function and added type hints.

### PR DESCRIPTION
**Pull request by yickysan**
refactor: removed lambda function and added type hints.

# PR Description
Changed the  `_shape_to_native` function. I added type hints to the function and also removed the lambda function for a defined function using the `def` keyword.

## Related Issue
#790 Reformat creation

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by omsai11** [comment]
How to allow test cases to check only the particular part of changes.

**Review by sherry30 — APPROVED** [review]
lgtm!
can you resolve the merge conflict, I'll merge it after that

**Comment by yickysan** [comment]
> lgtm! can you resolve the merge conflict, I'll merge it after that

Alright I'll do just that. Thank you very much.

**Comment by yickysan** [comment]
@sherry30 Hello, I haven't got a reply from you since the last time. I'm wondering if there is a problem?

**Comment by sherry30** [comment]
Sorry, for the late response. Everything looks good

**Pull request merged**
