### PR TITLE
added corrcoef to torch frontend and nanquantile to numpy frontend

### PR DESCRIPTION
**Pull request by Jayanth941**
close https://github.com/unifyai/ivy/issues/13761
close https://github.com/unifyai/ivy/issues/13834

### CODE REVIEW

**Comment by zhumakhan** [comment]
Hi thanks for you PR! Could you please attach this PR corresponding issue by commenting with issue number?

**Comment by Jayanth941** [comment]
#13761
#13834

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by zhumakhan** [comment]
Hi, thanks for your PR!
Could you please remove *sign* numpy frontend functions since it is not attached to issues addressed?

**Comment by Jayanth941** [comment]
What does this mean "intelligent-tests-pr / run_tests_1 (pull_request)",

**Comment by zhumakhan** [comment]
Also, I  noticed you used numpy directly for ivy's numpy frontend, Ivy's methods should be used instread as described in the docs: https://lets-unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
