### PR TITLE
bitwise_xor adhering to Array API Standard

### PR DESCRIPTION
**Pull request by sohil-hub**

### CODE REVIEW

**Comment by sohil-hub** [comment]
@djl11 can you please review the PR.
There might be some issues with the docker cloud, the tests fail every time.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hi, please could you ensure that you haven't made any changes to any of the .idea files. Don't worry about the docker failures we are working on fixing these 🙂

**Comment by sohil-hub** [comment]
Hi @mattbarrett98,
I have not made any change to .idea. I only added the **bitwise_xor** function wherever it was required. But when went to the **File Changes** tab which is on top of the pull request, it shows some changes to .idea. I don't know why?

**Comment by mattbarrett98** [comment]
Your IDE may have added them automatically. Please could you remove any changes to these files 🙂

**Comment by sohil-hub** [comment]
I will do it

**Comment by mattbarrett98** [comment]
Thank you. Yes I did, this was to get the tests passing for `__xor__`. I'm looking into the tensorflow failure now

**Comment by sohil-hub** [comment]
Please let me know if you something which I can help you in.

**Comment by mattbarrett98** [comment]
Thanks for contributing!

**Comment by sohil-hub** [comment]
@mattbarrett98 should not we also change the **bitwise_and** and **bitwise_invert**? 

image

**Comment by mattbarrett98** [comment]
No, you made an issue for bitwise_xor, so this is the only function that needed to be implemented.

**Comment by sohil-hub** [comment]
should not we also change the *bitwise_and* and *bitwise_invert?* [image:
image.png]

**Pull request merged**
