### PR TITLE
Added frontend for mindspore.ops.mish

### LINKED ISSUE #21276: mish
mindspore.ops.mish
(frontend)

### PR DESCRIPTION
**Pull request by jindalai**
Close #21276

### CODE REVIEW

**Comment by yashj8** [comment]
Lint is failling at line 105 of tests file. It is not part of my code (mish)

**Comment by yashj8** [comment]
Hello @zaeemansari70 ! Just a small reminder that I am waiting for your review 😄

**Review by zaeemansari70 — COMMENTED** [review]
Unfortunately, this cannot be reviewed as the tests for Mindspore are not up and running for now.
Will review this once we have the pipeline setup soon.
Sorry for the inconvenience. Thanks for waiting 🙂

**Comment by yashj8** [comment]
@zaeemansari70 
I've had one mindspore [PR](https://github.com/unifyai/ivy/pull/21275) of mine merged recentyl


AFAIK other PRs are also being [merged](https://github.com/unifyai/ivy/pulls?q=is%3Apr+is%3Aclosed+mindspore)

**Review by zaeemansari70 — COMMENTED** [review]
Hey @AnnaTz, this PR has been help back due to the mindspore frontend tests not being functional. Due let us know if there is an update to this.

Thanks@ :slightly_smiling_face:

**Comment by AnnaTz** [comment]
> Hey @AnnaTz, this PR has been help back due to the mindspore frontend tests not being functional. Due let us know if there is an update to this.
> 
> Thanks@ 🙂

Hey @zaeemansari70, setting up the testing for mindspore has been on very low priority so it is still pending. The mindspore ToDo lists have been converted to internal so that no more unchecked PRs get merged, but I see this one was created just before we closed the lists. I would suggest merging this now to not leave @yashj8 waiting longer.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
