### PR TITLE
Added torch.trapezoid frontend and tested

### LINKED ISSUE #11898: trapezoid

### PR DESCRIPTION
**Pull request by Illia-tsar**
Close #11898

### CODE REVIEW

**Comment by Illia-tsar** [comment]
@V-G-spec Could you please review my PR?

**Comment by V-G-spec** [comment]
Thanks for your contribution @Illia-tsar! It's perfect, merging it :)

**Comment by V-G-spec** [comment]
Hey, can you make this PR again? I believe there was some issue with the intelligent tests

**Comment by Illia-tsar** [comment]
That's strange because everything worked just fine, but ok, I'll do it.

**Comment by Illia-tsar** [comment]
Hey @V-G-spec , here's new PR - https://github.com/unifyai/ivy/pull/12358

**Pull request merged**
