### PR TITLE
Add searchsorted function (issue: searchsorted #2355)

### PR DESCRIPTION
**Pull request by drhuazhao**
- Add searchsorted function to ivy/array/sorting
- Add searchsorted function to ivy/container/sorting
- Add searchsorted function to ivy/functional/backends/(jax; mxnet; numpy; tensorflow; torch)
- Add searchsorted function to ivy/functional/ivy
To solve the issue:  #2355.

### CODE REVIEW

**Comment by Oxbeefbabe** [comment]
Thanks for the contribution! Just checking, are you an intern applicant doing the coding challenge?

**Comment by DrHuaZhao** [comment]
> Thanks for the contribution! Just checking, are you an intern applicant doing the coding challenge?

Thank you for the reply! Yes, I am the intern applicant!

**Comment by Oxbeefbabe** [comment]
Ok! Can you please check the lint / check-formatting (pull_request) tests and fix any lint errors you see? It seems your changes have raised a few lint errors.

**Comment by DrHuaZhao** [comment]
> Ok! Can you please check the lint / check-formatting (pull_request) tests and fix any lint errors you see? It seems your changes have raised a few lint errors.

Thank you for mentioning it! I have changed the lint errors.

**Comment by Oxbeefbabe** [comment]
Ok! One more quick thing I see is that some of the docstring tests are failing. This seems to be because in ivy/container/sorting.py, in the type hints, you have used a lowercase c for ivy.Container. You should use an uppercase C when referring to ivy.Container.

**Comment by Oxbeefbabe** [comment]
There are still some docstring tests failing. Can you check your changes to make sure any docstrings you have written are correct?

**Comment by drhuazhao** [comment]
> There are still some docstring tests failing. Can you check your changes to make sure any docstrings you have written are correct?

Do the fails in 'test docstings' mean that the output of the searchsorted function in four backends is incorrect? Can you please give an example of it? Thank you!

**Comment by Oxbeefbabe** [comment]
Hi @drhuazhao, I see you are having trouble with the docstrings. Keep in mind that you don't have to push every time you want to test the docstrings. You can use this guide (https://docs.python.org/3/library/doctest.html) to test the docstrings on your local machine instead. Just make sure you remove any supporting code before pushing.

**Comment by drhuazhao** [comment]
> Hi @drhuazhao, I see you are having trouble with the docstrings. Keep in mind that you don't have to push every time you want to test the docstrings. You can use this guide (https://docs.python.org/3/library/doctest.html) to test the docstrings on your local machine instead. Just make sure you remove any supporting code before pushing.

Ok, Thank you! Will do!

**Comment by drhuazhao** [comment]
Does any know why the checking of code is not working now? Thanks!

**Comment by drhuazhao** [comment]
Hi @Oxbeefbabe, is it ok now? Thank you!

**Comment by Oxbeefbabe** [comment]
Looks great! Thanks a ton, merging your work now :)

**Pull request merged**
