### PR TITLE
Updated docstring

### PR DESCRIPTION
**Pull request by chetna-mittal**
Unique_values #11715

### CODE REVIEW

**Comment by chetna-mittal** [comment]
Please let me know if there are any suggestions or changes needed?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by hirwa-nshuti** [comment]
Hey @chetna-mittal 

There have been major updates in the repository which made your changes conflict with the current repository status.
Would you copy the changes from this PR and open a new one adding them there😊

Feel free to ask for help if you need any🙂

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @chetna-mittal! As mentioned by @hirwa-nshuti, please resolve the conflicts either my force merging your branch or by simply copy pasting your fixes to a new branch. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
