### PR TITLE
Added data_type_functions

### PR DESCRIPTION
**Pull request by buriihenry**
This function rolls (circular shifts) the elements of an array along specified axes.

### CODE REVIEW

**Comment by danielmunioz** [comment]
Hey @buriihenry! Thanks for your interest in contributing to Ivy! 

I was wondering why should we add `roll` to the `data_type_functions` methods list? as far as I know `roll` belongs to `manipulation_functions`? Is there any particular reason you may have in mind to add `roll` to `data_type_functions`?

**Comment by buriihenry** [comment]
Hi @danielmunioz  While the roll function might be more commonly associated with array manipulation, it could have a functional similarity or usage pattern that aligns with the data type functions.  due to this, the roll operation is related to data transformation that is closely tied to specific data types or type conversions.

**Comment by danielmunioz** [comment]
I'm sorry maybe I'm missing something but I cannot see how is roll related to data type manipulation? If you check the [Data Type Functions](https://data-apis.org/array-api/2022.12/API_specification/data_type_functions.html) section of the Array API specification, the functions there directly interact with array data types, while [roll](https://data-apis.org/array-api/2021.12/API_specification/generated/array_api.roll.html) interacts mostly with the array itself

Also the file you are modifying is there to make sure we run those tests, if we were to update the location of a function it'd need to be across the whole repo

**Comment by hirwa-nshuti** [comment]
Hey @buriihenry 
Thanks for the PR😊
It is a good suggestion that we add this function to the methods to test in array API, however the function belongs to `manipulation` functions from the array API specifications https://data-apis.org/array-api/latest/API_specification/manipulation_functions.html and it is already added to our array API test suite here https://github.com/unifyai/ivy/blob/564eb98f4cc591f63049b7297072bfe7a0a973cc/ivy_tests/array_api_testing/array_api_methods_to_test/manipulation_functions.txt#L6

I'd suggest you go through our contribution guidelines to see open tasks https://unify.ai/docs/ivy/overview/contributing.html 

Meanwhile, I'm closing this item🙂

Thanks

**Pull request closed without merging**
