### PR TITLE
feat: added histogram statistic function to numpy frontend

### LINKED ISSUE #23149: histogram

### PR DESCRIPTION
**Pull request by JamesMbeti**
# PR Description
I added the histogram function to the statistics function in numpy frontend

## Related Issue
I got an issue while testing the function through ivy but while testing by myself the function works correctly as the np.histogram method. Also the ivy.histogram method from what I saw it isn't giving the correct output.

Close #23149

## Checklist

- [x] Did you add a function? I added the histogram function
- [x] Did you add the tests? I added but the test function doesn't work correctly
- [x] Did you follow the steps we provided? Yes I did follow all the steps

### Socials:
Twitter: @JamesMbeti

### CODE REVIEW

**Comment by JamesMbeti** [comment]
The Ivy tests or this failed test on GitHub? I had seen on the GitHub guidelines that they said I can ignore the run_tests (1), run_tests (2), … jobs, and only look at the display_test_results job.

**Comment by tomatillos** [comment]
Yep, and in `display_test_failures` -> `new_failures_introduced` lists the this test function as failing.

**Comment by JamesMbeti** [comment]
Can it be merged if I remove the test function as the code is running as the numpy function from my tests? I think the errors are from the ivy tests.

**Comment by tomatillos** [comment]
No, we would need the tests to be included + passing before merging. Thanks

**Comment by JamesMbeti** [comment]
Okay. Working on it. Thank you.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
