### PR TITLE
Added Norm Function

### PR DESCRIPTION
**Pull request by avi-thakur-0812**
add_frontend_checklist_linear-algebra

### CODE REVIEW

**Review by zaeemansari70 — COMMENTED** [review]
Kindly do let me know when you are done with your implementation by commenting on the PR so I can review it. :+1:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by avi-thakur-0812** [comment]
Close 

> Kindly do let me know when you are done with your implementation by commenting on the PR so I can review it. 👍

Hey! Could you please take a look, and recommend changes, if necessary.

**Comment by avi-thakur-0812** [comment]
Close #17223

**Pull request closed without merging**
