### PR TITLE
feat: bilinear function defined

### LINKED ISSUE #21366: bilinear

### PR DESCRIPTION
**Pull request by Sanjay8602**
This template will help you to have a meaningful PR, please follow it and do not leave it blank.
-->

# PR Description

## Related Issue

Closes #21366 

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Review by Sanjay8602 — COMMENTED** [review]
Two files updated: 
1. ivy/functional/frontends/paddle/nn/functional/common.py
2. ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_common.py

**Comment by Sanjay8602** [comment]
please review this PR please @joaozenobio

**Comment by samthakur587** [comment]
Hii @Sanjay8602 can you please remove the changes that are not related to this PR.

**Comment by samthakur587** [comment]
I think your problem will solve if you do reset your branch head on this commit hash 7c564ec19bbdb2b7c021c1ed42f8231db3d1a801   this is your first commit.

**Comment by Sanjay8602** [comment]
> I think your problem will solve if you do reset your branch head on this commit hash [7c564ec](https://github.com/unifyai/ivy/commit/7c564ec19bbdb2b7c021c1ed42f8231db3d1a801) this is your first commit.

please help me how to do this type of changes please

**Pull request closed without merging**
