### PR TITLE
Added acosh_ instance method and test method to pytorch frontend

### PR DESCRIPTION
**Pull request by usama-baloch**

### CODE REVIEW

**Comment by vaatsalya123** [comment]
Hey @usama-baloch thanks for contributing , though before I can start reviewing your PR  I noticed that you have committed .idea folder  to your list of changes could you remove that first please thanks.

**Comment by usama-baloch** [comment]
I'm sorry for the late response @ vaatsalya123, I just removed the commits of .idea folder file and updated the tesnor.py and test_tensor.py files, Now you can check it 🌝

**Comment by vaatsalya123** [comment]
Hi @usama-baloch  really sorry for the delayed response , So I was just going through your PR but I can't really understand why you are removing so much code for adding the acosh instance method.Could you give me a wider scope on why you are removing over 270 lines of code that mostly look's valid , thanks!

**Comment by usama-baloch** [comment]
Hi @vaatsalya123,  I also clearly don't know why they had been removed after adding acosh_ function, but I think the main reason is that I got merge conflicts when I added the function acosh_, and between the process of resolving merge conflicts, this problem happened. So now I checked the removed lines and added them again and Now there are no merge conflicts and it looks good but you can check it from your side and then tell me. Thank you! 🌝

**Comment by vaatsalya123** [comment]
lgtm!

**Pull request merged**
