### PR TITLE
added numpy.ndarray.astype

### LINKED ISSUE #9596: astype

### PR DESCRIPTION
**Pull request by mustafa1adel**
closes #9596

### CODE REVIEW

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @mustafa1adel ! Can you please add the testing function as well?

**Comment by kurshakuz** [comment]
Can you also link an issue that is attached to that PR and to a point in a ToDo list?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by kurshakuz** [comment]
Hey @mustafa1adel! I have tested your implementation locally and it fails for all 4 cases. Please check your implementation. The error I get is below:

```
E       TypeError: astype() missing 1 required positional argument: 'dtype'
E       Falsifying example: test_numpy_instance_astype(
```

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @mustafa1adel! I have tested your implementation locally and it fails for all 4 cases. Please check your implementation. The error I get is below:
```
E       TypeError: astype() missing 1 required positional argument: 'dtype'
E       Falsifying example: test_numpy_instance_astype(
```

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
