### PR TITLE
Cumprod function ivy

### PR DESCRIPTION
**Pull request by Tristan1649**
Hi @AnnaTz this is add function issue #11855

### CODE REVIEW

**Comment by Tristan1649** [comment]
Hi @AnnaTz can you pls review PR #12175?

**Comment by AnnaTz** [comment]
> Hi @AnnaTz can you pls review PR #12175?

Hi @Tristan1649, the assignee of your PR @agniiyer will be reviewing asap.

**Comment by Tristan1649** [comment]
Hi, @agniiyer can you please ckeck my PR?

@AnnaTz  thank you for respond.

**Comment by Tristan1649** [comment]
@agniiyer here is one function cumprod_numpy. If everything ok. I can add other finctions: Jax, Tf, Pytorch

**Comment by Tristan1649** [comment]
> > Hi @AnnaTz can you pls review PR #12175?
> 
> Hi @Tristan1649, the assignee of your PR @agniiyer will be reviewing asap.

Sill penging review

**Comment by hirwa-nshuti** [comment]
Hey @Tristan1649

**Pull request closed without merging**
