### PR TITLE
feat: add interpolate function and test 

### LINKED ISSUE #26133: interpolate

### PR DESCRIPTION
**Pull request by rfatihors**
# feat: add interpolate function and test 

## Related Issue
Add Layers to Paddle Backend
#10696
add interpolate function and test 

Close #26133 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by danielmunioz** [comment]
Hey @rfatihors! Thanks for contributing! 🚀 

Looks like the test for your function is missing, also it seems you're implementing it on the regular paddle backend? This one is an Experimental Function, as such it needs to be placed on the `experimental` paddle folder! 
Please take a look at the [Experimental Functions Guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#ivy-experimental-api) for more info on how to align your implementation with Ivy!

If you have any questions whatsoever please don't hesitate to ask!
Thanks :)

**Comment by rfatihors** [comment]
Hi Daniel, I will add it to the experimental paddle folder as you said. But I could not find how to add test. I guess I ran the right tests but could not implement them. danielmunioz ***@***.***> şunları yazdı (1 Eki 2023 19:56):﻿
Hey @rfatihors! Thanks for contributing! 🚀
Looks like the test for your function is missing, also it seems you're implementing it on the regular paddle backend? This one is an Experimental Function, as such it needs to be placed on the experimental paddle folder!
Please take a look at the Experimental Functions Guide for more info on how to align your implementation with Ivy!
If you have any questions whatsoever please don't hesitate to ask!
Thanks :)

**Comment by rfatihors** [comment]
Hi, I made the changes that were requested. Please,  kindly take a look and re-review.

**Comment by danielmunioz** [comment]
Hey @rfatihors! 

Yeah some of the changes look good! however it seems that you are introducing changes to the `.idea` folder, could you please remove those?
As well as a new `Tensor` class being added to the `paddle/__init__.py` file? May I ask why did you add that? As per ivy rules, the PR should only contain changes related to the issue at hand, so could you please remove that new class?.

Thanks!

**Comment by rfatihors** [comment]
Hi again, I reverted the changes that you mentioned. At late night, I was trying the understand the structure and if I could see the variables for a better understanding of the whole of tests. Then, I guess in the morning forgot to delete, sorry.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
