### PR TITLE
Lstsq

### LINKED ISSUE #26699: lstsq

### PR DESCRIPTION
**Pull request by shruzki**
# PR Description

WIP - TODO
- Have to complete tensorflow implementation that works using SVD instead of default method.
- Have to add examples in docstring

## Related Issue

Closes #26699

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by JPGoodale** [comment]
Hi @shruzki, are you finished with your changes to this PR? If so, please mark it as ready for review, thanks.

**Comment by shruzki** [comment]
@JPGoodale will do today

**Comment by Ishticode** [comment]
any updates on this draft?

**Comment by Ishticode** [comment]
Closing this due to lack of activity for over 5 months. Please reopen if you would like to continue work. Thank you :)

**Pull request closed without merging**
