### PR TITLE
L1 loss in paddle FrontEnd (#16455)

### PR DESCRIPTION
**Pull request by RohitPawar2406**
closes https://github.com/unifyai/ivy/issues/16455

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @RohitPawar2406 

The changes looks nice, would you add the `#issue_number` in the first comment of the PR to link this item with the subtask

**Comment by RohitPawar2406** [comment]
#16455

**Comment by RohitPawar2406** [comment]
@hirwa-nshuti, sorry for late response, Could you merge following PR.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Resolve the merge conflicts for CI check and merging

**Comment by RohitPawar2406** [comment]
> Resolve the merge conflicts for CI check and merging

Should I pull and merge conflicts and then push the code ? @hirwa-nshuti

**Pull request closed without merging**
