### PR TITLE
Add test naming convention script

### PR DESCRIPTION
**Pull request by sladyn98**
This PR adds the test_naming_convention.py script to ivy so that it can be integrated with our workflow bot

### CODE REVIEW

**Comment by sladyn98** [comment]
@KareemMAX

**Comment by KareemMAX** [comment]
@sladyn98 I'm a bit confused why do we want this script to be here

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
