### PR TITLE
corrcoef

### PR DESCRIPTION
**Pull request by UnwillingCrab85**

### CODE REVIEW

**Review by juliagsy — COMMENTED** [review]
Hey there! Thanks for contributing! Just to check a few things before I can actually review the changes, did you have an issue created, and is this function for the frontend of which framework, or are you working on adding an Ivy API to the backends? Thanks!

**Comment by UnwillingCrab85** [comment]
Hi, yes my issue  number is: #17510 and I am adding the statistical function to Paddle Backend on statistical.py. Sorry if this isn´t correct, im trying to learn :)

**Comment by juliagsy** [comment]
@UnwillingCrab85  ahh I see! You should be adding the function to the paddle file instead of the numpy file. But I've just double checked the function and it's actually already present in ivy master, I've checked the entry in the todo list to complete now! Apologies for any inconvenience but would you mind to pick another available function to work on? Thanks a lot!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
