### PR TITLE
Add General Functions (zeros_initializer) to TensorFlow frontend 

### LINKED ISSUE #9425: zeros_initializer

### PR DESCRIPTION
**Pull request by ream-kh**
resolves #9425

### CODE REVIEW

**Comment by ream-kh** [comment]
Hello @Ishticode can you please give me a review for my pull request

**Comment by ream-kh** [comment]
@Ishticode could you please help me with by giving me a review for this pull request?

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @ream-kh 
Sorry for the delay although 3-4 days are normal especially considering weekends so no need for any worries. I will review the PR now 🙂.

Thank you so much for the PR. 

There are several thing to take care of. There is no `zero_initializer` function in Ivy. So the call `ivy.zero_initializer` won't work here. To get the desired behaviour you might need  a composition of other ivy functions. Please check the documentation on lets-unify.ai to look up functions. 
If you believe the compostion is too complex then we can figure other steps such as a feature request to add ivy.zeros_initializer funtion in Ivy's functional API and meanwhile you will be welcome to work on any function.

Secondly, I think according to tensorflow's api for this function requires that it also handle **kw which perhps can be added to the function parameters and the `name` argument will be part of that if it is an argument.

Let me know if something is unclear and feel free to tag a question or request a review when you think its ready for review.

Thanks again.🙂

**Comment by ream-kh** [comment]
Hi @Ishticode thank you for the review.
Can I change the function I am working on to one found in Ivy of I have to complete working on zero_initializer function

**Comment by Ishticode** [comment]
@ream-kh 
You can work on another function if you want. You can keep this open for over a week too, At anytime you can have three issues assigned to yourself to work on any of the functions. So please feel free to choose another function and keep this open too if you like. Does that help?

**Comment by ream-kh** [comment]
@Ishticode 
Yes than you. I will work on another function and leave this open too to work it after that.

**Pull request closed without merging**
