### PR TITLE
feat: Added expand_as instance method to paddle frontend

### LINKED ISSUE #26859: expand_as

### PR DESCRIPTION
**Pull request by m571adil**
feat: Added expand_as instance method to paddle frontend

#26859 

Close #26859

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by m571adil** [comment]
Hi @kgmann can you please review.

**Review by Sam-Armstrong — CHANGES_REQUESTED** [review]
Hey @m571adil, sorry for the slow review on this. 

expand_as doesn't exist yet in the paddle frontend, so you can't use `paddle_frontend.expand_as`. So you could either implement that function yourself, or just implement the same logic in this function using ivy functions. Hope that makes sense!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ishticode** [comment]
Thank you very much for the PR. Closing this due to lack of activity with changes requested remaining unresolved for over 6 months. Please feel free to reopen if you would like to continue working on this. :)

**Pull request closed without merging**
