### PR TITLE
added greater_equal function to tf frontend

### PR DESCRIPTION
**Pull request by Sooryak12**
This pull request fixed the following issue :
*  Fixes issue  #13651 #13653 by adding greater_equal_function to tf frontend

### CODE REVIEW

**Comment by Daniel4078** [comment]
Hello, the pull request you mensioned is not merged yet and was just created 6 hours ago, thus still a work in progress. You do not need to fix the problem in other's pull request as they are currently working on it and no change has been done to the main branch. You may state your suggestions about what and how to fix in their pull request but not effectively try to finish someone else's task that they are still working on.

**Comment by Sooryak12** [comment]
Thank you Daniel ! I'm new to this so I was not aware of it .

**Comment by Mohamed-dewidar** [comment]
what is the problem with my pull request, can u help me?

**Comment by Sooryak12** [comment]
> what is the problem with my pull request, can u help me? @Sooryak12

Hey @Mohamed-dewidar  , There is nothing with your pull request . I tried to work on the issue you created ,by myself without knowing that you will be working on it. If you face any issues in your commit , you can check my changes in the code for this issue , that might help you.

**Pull request closed without merging**
