### PR TITLE
implimentation of degrees

### PR DESCRIPTION
**Pull request by ndurumo254**

### CODE REVIEW

**Comment by ndurumo254** [comment]
7413

**Comment by ndurumo254** [comment]
#7413

**Comment by ndurumo254** [comment]
hey @fspyridakos . getting some challenges of pushing the corrected syntax error referenced by ivy_tests/test_ivy/test_frontends/test_numpy/test_logic/test_array_contents.py:159:1: E999 SyntaxError: invalid syntax
how can I go about it?

**Comment by fspyridakos** [comment]
Hi 😊
Thanks for making a contribution!

deg2rad happens to already be implemented but I see you added handling for the `dtype` parameter in line 145 and 146 of `trigonometric_functions`  which is something that should be included in the function. Otherwise all your other changes aren't necessary so please revert them, including the changes to the test as the tests have a general problem we're actively trying to resolve.

**Comment by ndurumo254** [comment]
> Hi 😊 Thanks for making a contribution!
> 
> deg2rad happens to already be implemented but I see you added handling for the `dtype` parameter in line 145 and 146 of `trigonometric_functions` which is something that should be included in the function. Otherwise all your other changes aren't necessary so please revert them, including the changes to the test as the tests have a general problem we're actively trying to resolve.

thanks for the review. so it seems there are some open issues from the to-do list that are already implemented.

**Comment by fspyridakos** [comment]
Yes, we try to stick to the policy of making issues for everything and closing them after they are implemented but some members end up implementing some functions without going through this process. We try checking these funcitons off in the ToDo anyway but I do agree that it's not as obvious without the closed issue label.

**Comment by ndurumo254** [comment]
#7477

**Comment by ndurumo254** [comment]
hello there.
am getting some errors from different contribution files. Is it advisable for me to change  files from different contribution
Thanks with regards.

**Comment by ndurumo254** [comment]
> Yes, we try to stick to the policy of making issues for everything and closing them after they are implemented but some members end up implementing some functions without going through this process. We try checking these funcitons off in the ToDo anyway but I do agree that it's not as obvious without the closed issue label.

ok. understood. and can that lines 145 and 146 qualify to be part of the contribution😊

**Comment by ndurumo254** [comment]
https://github.com/unifyai/ivy/issues/7477

**Pull request closed without merging**
