### PR TITLE
lstsq function added on paddle

### LINKED ISSUE #18159: lstsq function on paddle
Hi there!
I will be working on implementing the lstq linear algebra function in the Paddle front end.

Based on the task list, it looks like this function does not yet have a RawOps implementation, so I will create a new implementation in the linear_algebra.py file. I will also ensure that any additional parameters are included and properly documented.

I will keep everyone updated on my progress and will create a pull request as soon as I have a partial or full solution. If anyone has any questions or suggestions, please feel free to reach out to me.

Looking forward to contributing to the project!

### PR DESCRIPTION
**Pull request by Risi-droid**
close #18159

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
please remove all unrelated files from the PR before reviewing

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Kindly uncommit your changes to the `.idea` folder.
Thanks!

**Comment by MahmoudAshraf97** [comment]
Hi, I checked your issue and noticed that you are trying to implement a frontend function, so please check the contributors guide in the documentation

**Pull request closed without merging**
