### PR TITLE
Update general_functions.py

### PR DESCRIPTION
**Pull request by m-gopichand**
Added  negative indexing

### CODE REVIEW

**Comment by rishabgit** [comment]
Hey @AnnaTz, adding you here because you've worked on this before, and I'm not too sure how to proceed 😅

**Review by AnnaTz — CHANGES_REQUESTED** [review]
Hi @m-gopichand, 
To make sure the added negative indices support works correctly you will also need to update the test of the function.
Also, I'm pretty sure that changing `py_slice` to `slice` will cause an infinite loop, as `slice` here is a tensorflow function that uses `strided_slice` in itself. Please always run the function's test locally while making changes.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by m-gopichand** [comment]
Hi @AnnaTz, Thank you for the feedback I will update it

**Pull request closed without merging**
