### PR TITLE
add transpose, swapaxes, swapdims

### PR DESCRIPTION
**Pull request by PatternFinder**
to frontends.torch.indexing_slicing_joining_mutating_ops

link to issue: #2691

### CODE REVIEW

**Comment by saeedashrraf** [comment]
Hello @PatternFinder, I have left you a review, requesting some changes to your previous PR https://github.com/unifyai/ivy/pull/2648#issuecomment-1207139396. Those same requests apply to this PR as well. Please refrain from creating any new PRs before addressing those changes. 
Thank you for your effort!

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @PatternFinder, I have left you a review, requesting some changes to your previous PR https://github.com/unifyai/ivy/pull/2648#issuecomment-1207139396. Those same requests apply to this PR as well. Please refrain from creating any new PRs before addressing those changes. 
Thank you for your effort!

**Comment by PatternFinder** [comment]
> Hello @PatternFinder, I have left you a review, requesting some changes to your previous PR [#2648 (comment)](https://github.com/unifyai/ivy/pull/2648#issuecomment-1207139396). Those same requests apply to this PR as well. Please refrain from creating any new PRs before addressing those changes. Thank you for your effort!

understood. I will split up these alias and file them under separate issues then

**Comment by PatternFinder** [comment]
closing, then split up submits individually under different PRs

**Pull request closed without merging**
