### PR TITLE
Add diff mathematical function to Paddle frontend

### LINKED ISSUE #18233: diff

### PR DESCRIPTION
**Pull request by remenraj**
Close #18233

### CODE REVIEW

**Comment by sondertg** [comment]
Hi @remenraj , tests are failing for `diff`. Also, you need to create another PR for different functions(For `trunc` in this case). Please kindly check documentation. :)
https://unify.ai/docs/ivy/overview/contributing/the_basics.html#the-basics
https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#open-tasks

**Comment by remenraj** [comment]
> Hi @remenraj , tests are failing for `diff`. Also, you need to create another PR for different functions(For `trunc` in this case). Please kindly check documentation. :) https://unify.ai/docs/ivy/overview/contributing/the_basics.html#the-basics https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#open-tasks

Thank you @sondertg for the feedback and reviewing my pull request. I want to clarify that my changes were unrelated to the 'trunc' function, and I didn't work on it in this pull request.  I apologize for the confusion caused by fixing the merge conflict. I am actively working on fixing the failing tests and will update the pull request accordingly.

**Comment by jshepherd01** [comment]
Hi @remenraj, your tests still seem to be failing by the look of it. You'll need to update the version number for paddle, and I think your test is missing the `backend_to_test` parameter. Take a look at the other code in those files or at the deep dives on the website to see how its done. Good luck with it :)

**Comment by remenraj** [comment]
> Hi @remenraj, your tests still seem to be failing by the look of it. You'll need to update the version number for paddle, and I think your test is missing the `backend_to_test` parameter. Take a look at the other code in those files or at the deep dives on the website to see how its done. Good luck with it :)

Thank you, @jshepherd01! I'll update the Paddle version number, add the `backend_to_test` parameter, and work on the failing tests. I truly appreciate your help! :)

**Comment by remenraj** [comment]
Hi @jshepherd01, I noticed that when I pushed the changes to the pull request, the checks are showing 7 failing checks. Locally, when i ran this code 'python -m pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py::test_paddle_diff`,  all tests passed successfully. Can you please review the failing checks and provide your insights? Your assistance would be greatly appreciated! Thank you!

**Comment by jshepherd01** [comment]
Hi @remenraj, don't worry too much about the failed checks in GitHub actions. Basically it automatically runs tests from various parts of the repository, and some (probably most) of them will be ones unrelated to your code. The best thing to do is check the error messages and see if the results are related to your function in any way, but it doesn't look like they are so that's fine, you're all good :)

**Comment by remenraj** [comment]
> Hi @remenraj, don't worry too much about the failed checks in GitHub actions. Basically it automatically runs tests from various parts of the repository, and some (probably most) of them will be ones unrelated to your code. The best thing to do is check the error messages and see if the results are related to your function in any way, but it doesn't look like they are so that's fine, you're all good :)

Thanks for clarifying, @jshepherd01! Your support is really helpful :)

**Pull request merged**
