### PR TITLE
Conv1d_transpose

### LINKED ISSUE #17147: conv1d_transpose

### PR DESCRIPTION
**Pull request by VaishnaviMudaliar**
Closes #17147

Since my previous PR(#17214) was causing conflicts , i made a new PR by committing the changes to a new branch.

### CODE REVIEW

**Comment by Daniel4078** [comment]
ivy-gardener

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Hello, why I can't see a test for the function you implemented?

**Comment by VaishnaviMudaliar** [comment]
Well, I did not change anything in the test files

**Comment by VaishnaviMudaliar** [comment]
I am extremely sorry , i had mentioned the wrong function name in the PR , I have corrected it now

**Pull request closed without merging**
