### PR TITLE
set_split_factor

### PR DESCRIPTION
**Pull request by tamukagate**

### CODE REVIEW

**Comment by tamukagate** [comment]
#6957

**Comment by tamukagate** [comment]
add_reformatting_checklist_device

**Comment by JamieLine** [comment]
Hi! Thanks for the PR!

I see the bot has added in the checklist, once you have either filled out everything on the checklist or would like some assistance in doing so, please add a comment to this PR seperately to the checklist. I'm not sure how my alerts will work with editing the checklist but adding a new comment will definitely bring it to my attention.

**Comment by tamukagate** [comment]
Close #6957

**Pull request merged**
