### PR TITLE
lexsort function implementation

### PR DESCRIPTION
**Pull request by nadidebeyza**
- [x] #7126

### CODE REVIEW

**Comment by ahmedo42** [comment]
Hi @nadidebeyza, Thanks for your contribution! 
 since you're implementing a NumPy frontend function, you can either: 
 - implement only the frontend compositionally without adding an experimental API function
 - implement the experimental API including all the backends and if you'd like, add the frontend function in a separate PR

**Comment by nadidebeyza** [comment]
> 

Hi @ahmedo42, I would like to implement the experimental API including all the backends. Can you explain the task a little more? I understand that I will implement the lexsort function also under the title of the task in IVY Experimental API, am I right?

**Comment by ahmedo42** [comment]
@nadidebeyza kindly read through this [section](https://lets-unify.ai/ivy/contributing/open_tasks.html#ivy-experimental-api)

**Comment by hirwa-nshuti** [comment]
Hey @nadidebeyza 
This function was late added to the functional API via https://github.com/unifyai/ivy/pull/10160 as it was urgently needed we are sorry for the inconvenience🙂

Feel free to take on another open task for contribution and to close this PR if satisfied with the explanation above😊

Thanks and happy coding🤗

**Pull request closed without merging**
