### PR TITLE
nextafter Pytorch Frontend implementation

### LINKED ISSUE #9670: nextafter

### PR DESCRIPTION
**Pull request by EPalmer14**
Close #9670

Could not get tests to run. I am getting some kind of internal error when trying to test on just --backend torch.

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by agniiyer** [comment]
Hey apologies for the delay! Can you remove the changes to the .idea folder here?

**Comment by EPalmer14** [comment]
> Hey apologies for the delay! Can you remove the changes to the .idea folder here?

Yes! Sorry, I meant to unclick the changes to the .idea folder and when I realized I forgot I wasn't sure if it would affect the files or not. It should be fixed now.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by agniiyer** [comment]
Hey the tests are still not passing. Can you check again?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
