### PR TITLE
Add pytorch multi_margin_loss function for ivy frontend api

### PR DESCRIPTION
**Pull request by dorltcheng**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @dorltcheng 
Thank you for the PR and sorry for the late reply here. 
Could you link the issue for this PR? if you are unsure please check the guide on [TODO list issue and open tasks](https://lets-unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues). Feel free to request a review when done. Thank you very much.🙂

**Comment by dorltcheng** [comment]
- [] #14031

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
