### PR TITLE
Added truncatediv tensorflow frontend function

### PR DESCRIPTION
**Pull request by Konyancha1**

### CODE REVIEW

**Comment by Konyancha1** [comment]
Hello @paulaehab, could you kindly review

Thanks

**Comment by paulaehab** [comment]
Hi @Konyancha1 Nice work 🥳  just add factory safety to the test function this will help in passing all tests after it I will merge the PR thanks.

**Comment by paulaehab** [comment]
Hey @Konyancha1  🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained here: (https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues)

**Comment by paulaehab** [comment]
Hi @Konyancha1  I am sorry for being late this PR  just  slipped under my radar!
Sorry again because  but there is another one who already take the same function https://github.com/unifyai/ivy/issues/16200 ,this conflict happen because when you created the issue you didn't follow the instructions of Contributors which you should create issue with the function name then leave a comment in the Todolist with this issue number you can find instructions here . (https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues). so I will close this PR and you can choose any another function.

**Comment by Konyancha1** [comment]
Hi @paulaehab, thanks for the heads up. I will make sure to do this on implementing the next function to avoid conflict. This was totally my bad

**Comment by paulaehab** [comment]
@Konyancha1 I will close this PR and after you choose another function create new one

**Pull request closed without merging**
