### PR TITLE
Updated nested_map to support shallow for ivy.Array input using inplace_update instead of an additional check with lists

### PR DESCRIPTION
**Pull request by vedpatwardhan**
These changes have reverted a bug introduced in [this](https://github.com/unifyai/ivy/commit/882edce20d12930e972bc94089411c223691d38a) commit where we checked for `ivy.Container`, which isn't required as it's a derived `dict`. Just requested your reviewed @guillesanbri and @sherry30, as I also moved the `ivy.inplace_update` to the end of the function to also fix the issue mentioned in [this](https://trello.com/c/p2SF9luG/1487-fix-ivynestedmap-not-working-with-in-place-updates) card, which was in fact the objective of the commit link I shared above. 
Let me know if you thinkthere's any issues which could arise because of these changes, thanks 🙂

### CODE REVIEW

**Review by guillesanbri — COMMENTED** [review]
I'm afraid that it seems to break the graph compiler :sweat_smile:

**Comment by VedPatwardhan** [comment]
> I'm afraid that it seems to break the graph compiler 😅 , not sure why but I'm assuming that the id of arrays are not being preserved as expected, if this is high priority we can get someone with access to the gc to look into it, otherwise I can look into it in a couple of days but I want to finish a few things first

Hey @guillesanbri, thanks for looking into the PR. I wonder if it may be needed to add another flag for determining whether the user would like to inplace update the arrays in the input nest. Then users could select whether they'd like to inplace update the input nest using the `shallow` argument (where the leaves wouldn't be inplace updated) and then use the `inplace` argument (or some other name) to inplace update the arrays at the leaves of that nest. 
But I'm curious to know what you think about this, because the reason it may break the compiler if because if the new values after `nested_map` aren't broadcastable to the old arrays, then inplace update fails the assertion. 
I think we can go forward with whatever you think works best. Thanks 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by VedPatwardhan** [comment]
<any comment>

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by VedPatwardhan** [comment]
<another comment>

**Comment by guillesanbri** [comment]
Probably a side effect of a change that has been made in the gc in the last few days, but all tests seems to be working fine now. Feel free to merge this if it's ready. Nonetheless, if we are going to add the `inplace` param to `nested_map` I think it would be good to include it as well in every nested function and ensure that the signature of every one of them follows the same pattern / has the same features :+1:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by VedPatwardhan** [comment]
<comment>

**Comment by VedPatwardhan** [comment]
> Probably a side effect of a change that has been made in the gc in the last few days, but all tests seems to be working fine now. Feel free to merge this if it's ready. Nonetheless, if we are going to add the `inplace` param to `nested_map` I think it would be good to include it as well in every nested function and ensure that the signature of every one of them follows the same pattern / has the same features 👍

Sure, I'll add the `inplace` argument to the other `nest` functions too in a few days, thanks for pointing it out @guillesanbri 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by vedpatwardhan** [comment]
I don't fully remember what the goal was here, but given that there aren't any test failures because of this, and given that native inplace updates aren't consistent across backends anyway, I think we can hold this off for now and look back at it if required later. Thanks guys!

**Pull request closed without merging**
