### PR TITLE
Reformat linear 

### LINKED ISSUE #4769: linear

### PR DESCRIPTION
**Pull request by randomstate42**
fixes #4769

### CODE REVIEW

**Comment by randomstate42** [comment]
add_reformatting_checklist_layers

**Comment by randomstate42** [comment]
#4769

**Comment by randomstate42** [comment]
Close #4769

**Comment by randomstate42** [comment]
https://github.com/sharique1006 please review

**Comment by randomstate42** [comment]
@sharique1006 could you please review

**Comment by randomstate42** [comment]
@ivy-leaves @ivy-seed  @sharique1006  can someone review this PR please

**Comment by randomstate42** [comment]
Hi @sharique1006, I think I accidently added the file to the commit. I tried to revert the commit but it kept returning conflict errors so I ended up deleting the file from the commit. Thanks

**Comment by sharique1006** [comment]
Your commit still shows `test_array_api` submodule deleted, these changes should not be reflected here. Only the changes in the first 3 files.

**Comment by randomstate42** [comment]
Hi @sharique1006 , I managed to  revert the commit after unstaging the file from staging area. Only the target file are changed now :ok_hand: .
Thanks

**Comment by randomstate42** [comment]
@sharique1006 ready for review🙂

**Comment by sharique1006** [comment]
lgtm. Cheers!

**Pull request merged**
