### PR TITLE
update selu for stateful api - Close #19808

### LINKED ISSUE #19808: SeLU

### PR DESCRIPTION
**Pull request by guodh321**
closes #19808

### CODE REVIEW

**Comment by guodh321** [comment]
Close #19808 please

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Hello, you should add a test for your funciton in here (https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_stateful/test_activations.py).

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Found one failure for your tests, please have a look: 
E   AssertionError:  the results from backend jax and ground truth framework tensorflow do not match
E    [[1.75809934]]!=[[1.05070099]] 
E   
E   
E   Falsifying example: test_selu(
E       on_device='cpu',
E       dtype_and_x=(['float64'], [array([[-4.28801959e-17]])]),
E       method_name='__call__',
E       ground_truth_backend='tensorflow',
E       init_flags=InitMethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E       ),
E       test_gradients=True,
E       class_name='SeLU',
E       method_flags=MethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E           container_flags=[False],
E       ),
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.0', b'AXicY2JkYAAiEGA8nACmLjLAAAAbxgH7') as a decorator on your test case

**Comment by Daniel4078** [comment]
E   AssertionError:  the results from backend torch and ground truth framework tensorflow do not match
E    [[1.75809934]]!=[[1.05070099]] 
E   
E   
E   Falsifying example: test_selu(
E       on_device='cpu',
E       dtype_and_x=(['float64'], [array([[-2.77555756e-17]])]),
E       init_flags=InitMethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E       ),
E       test_gradients=True,
E       class_name='SeLU',
E       method_name='__call__',
E       method_flags=MethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E           container_flags=[False],
E       ),
E       ground_truth_backend='tensorflow',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.0', b'AXicY2RkYAAiEGA8nMCACgATdAEo') as a decorator on your test case

**Comment by Daniel4078** [comment]
I do not know the cause of this error, but maybe it is from the backend implementation. Please check if my guess is correct, and if so, then your code will be merged. Thanks

**Comment by guodh321** [comment]
Hi @Daniel4078 , I think you are right that the error came from the backend implementation. Please help merge if possible, thanks.

**Pull request merged**
