### PR TITLE
Updated the function arguments and type hints, added correct docstrin…

### PR DESCRIPTION
**Pull request by Phindulo60**
1. Update the function arguments and type hints.
2. Added the correct docstrings
3. Added thorough docstring examples

### CODE REVIEW

**Comment by MuhammadSaeedBatikh** [comment]
Hi @Phindulo60, Thanks for the PR.
Please make sure not include other unrelated files such as vsc.xml and ivy.iml with your PR.

**Comment by Phindulo60** [comment]
Hi @MuhammadSaeedBatikh , thank you and I will do so, and should I remove those files from the current commit?

**Comment by MuhammadSaeedBatikh** [comment]
> Hi @MuhammadSaeedBatikh , thank you and I will do so, and should I remove those files from the current commit?

 yes please.

**Comment by Phindulo60** [comment]
Hi @MuhammadSaeedBatikh , I have just removed those files, please check

**Comment by MuhammadSaeedBatikh** [comment]
Hi @Phindulo60, sorry for the late response. 
You removed them but they're still included in git. As you can see, there're still conflicting files.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
