### PR TITLE
Instance Methods to PyTorch Frontend - bitwise_xor_

### LINKED ISSUE #13092: bitwise_xor_

### PR DESCRIPTION
**Pull request by jatinS-dev**
Closes #13092

### CODE REVIEW

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @jatinS-dev! There seems to be a minor Assertion error that needs to be fixed, otherwise looks good to me :)

```
E       AssertionError: the ground truth framework torch returned a int8 datatype while the backend jax returned a int16 datatype
```

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hi! This is already looking good, but please fix that last error:
```
E       AssertionError: the ground truth framework torch returned a int8 datatype while the backend jax returned a int16 datatype
E       Falsifying example: test_torch_instance_bitwise_xor_(
E           dtype_and_x=(['int8', 'int16'],
E            [array(0, dtype=int8), array(0, dtype=int16)]),
E           init_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           method_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.torch' from '/workspaces/ivy/ivy/functional/frontends/torch/__init__.py'>, framework_init_module=<module 'torch' from '/usr/local/lib/python3.8/dist-packages/torch/__init__.py'>, init_name='tensor', method_name='bitwise_xor_'),
E           frontend='torch',
E           on_device='cpu',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2RkQAMAADUAAw==') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:38: AssertionError
```
Let me know once you are done 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
