### PR TITLE
add softplus to PyTorch frontend

### PR DESCRIPTION
**Pull request by ashmitkx**
#3007

### CODE REVIEW

**Review by MarShaikh — CHANGES_REQUESTED** [review]
I had a look at your code. It looks good to me, but the test_frontend check in the CI is failing. Please get it to pass and I'll have a look again. Thanks.

**Comment by ashmitkx** [comment]
Hey. Thanks so much for reviewing my code, I had been waiting for long.

I'm actually not sure why [the error](https://github.com/unifyai/ivy/runs/7836851475?check_suite_focus=true#step:4:605) is happening. Do you have any clue as to why `AssertionError: -0.0 != inf` is being thrown?

**Comment by MarShaikh** [comment]
> Hey. Thanks so much for reviewing my code, I had been waiting for long.
> 
> I'm actually not sure why [the error](https://github.com/unifyai/ivy/runs/7836851475?check_suite_focus=true#step:4:605) is happening. Do you have any clue as to why `AssertionError: -0.0 != inf` is being thrown?

Sorry for the delay! I'm assuming the error is being thrown due to `tf` returning `inf` for a specific value of `x` whereas `torch` returns `-0.0` for that value. I think a fix would be to limit the range of values being tested, but I recommend just diving deeper in both the `torch`'s `softplus` function and `tf` `softplus` and finding the cause.

**Comment by ashmitkx** [comment]
Alright, I'll have a look and let you know.

**Comment by ashmitkx** [comment]
Hey @MarShaikh, I'm currently having trouble debugging the issue.\
I tried stepping through the testing function, but couldn't exactly understand what is happening with the input.

Do you have any tips on how I can better trace the issue in the code?

**Comment by MarShaikh** [comment]
> Hey @MarShaikh, I'm currently having trouble debugging the issue. I tried stepping through the testing function, but couldn't exactly understand what is happening with the input.
> 
> Do you have any tips on how I can better trace the issue in the code?

It seems like the outputs you get from the Tensorflow and the output you get from the function itself are different. I would suggest using the failure input as shown in the error stack, you try to test the `softplus` function with different backends! It is possible that you might need to change the limits of your inputs as one of the outputs was `-inf`, maybe also read tf documentation.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
