### PR TITLE
add set(intersection) function

### LINKED ISSUE #4054: add ivy.intersection (set-version) function
Add Set functions for TensorFlow frontend #1558

### PR DESCRIPTION
**Pull request by deepanshug4**
close #4054

### CODE REVIEW

**Review by Unevilicorn — CHANGES_REQUESTED** [review]
Hey there. The test for intersection is not passing, could you get this fixed, Thanks.

**Comment by deepanshug4** [comment]
Hey @Unevilicorn, I'm not sure which tests are failing also the ivy implementation for the intersection method is not there for reference #3195.
So, if you could please look into that!
Also, I'm seeing a lot of tests so if you could please tell me which test cases are failing then I'll try to solve them as well.

**Comment by Unevilicorn** [comment]
Hey, I looked a bit deeper into this function and others within the todo list. I believe the best case of action is either try implementing this using existing ivy functions or as the [docs](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis) suggested, convert your existing GitHub issue to request for the function, and  choose another function to work on.

As for where you can see the tests, it's in `checks` -> `test-frontend-tensorflow` -> `run-nightly-tests` -> `Run frontend tests` -> your test function, if it's not there, then there isn't an error with your function

**Comment by deepanshug4** [comment]
Hi @Unevilicorn, thanks for your suggestion I will see if I can come up with a composite implementation of this method. Till then, I will mark this as the "pending ivy method" as mentioned in the docs. Also, I'll look into the tests the way you described it. Thanks.

**Comment by Unevilicorn** [comment]
Hi, just request another review from me if you manage to implement this so I can get it reviewed ASAP, otherwise you can just close this PR and move on to something else.

**Pull request closed without merging**
