### PR TITLE
from_dlpack adhering to Array API Standard

### PR DESCRIPTION
**Pull request by hieultp**
Solve #727

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Looks good 🙂Just one small change, could you define the functions using ‘def’ rather than lambda functions, thanks!

**Comment by hieultp** [comment]
Hi @mattbarrett98, I have converted all the lambda functions to the normal ones. Could you have a look at this again?
Also, some tests for Pytorch fail for the "test_cross" and "test_matmul". I don't know why it failed. Did my changes cause some conflicts?

**Review by mattbarrett98 — COMMENTED** [review]
Great thanks! No these failures are unrelated to your changes don't worry 🙂

**Comment by mattbarrett98** [comment]
Thanks for contributing!

**Pull request merged**
