### PR TITLE
added flatten function to paddle.tensor.manipulation

### PR DESCRIPTION
**Pull request by spidy1996**
added flatten function to paddle.tensor.manipulation - first pull request

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by spidy1996** [comment]
@MuhammadSaeedBatikh Can you please review it, it's been 3 days?

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @spidy1996 
Thanks for the PR😊
Would you also add unit test for the implemented function?

Thanks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
