### PR TITLE
Adden instance method Mean to Jax frontend

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Close #14170

**Comment by RakshitKumar04** [comment]
Close #14170

**Comment by RakshitKumar04** [comment]
Hey, @valeriocost the implementation passed 4 out of 5 tests when ran locally. The fifth test is failing may be due to the `where` argument that has not been initialized and used in the test function but when I do so all 5 tests get failed.

Please guide me on how to declare and initialize the `where` argument in the test function.

**Comment by valeriocost** [comment]
Hi @RakshitKumar04, you should probably take a look here https://lets-unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html where we explained how to write frontends tests. Thanks 😄

**Comment by RakshitKumar04** [comment]
Hey, @valeriocost can you please review my PR.

**Comment by valeriocost** [comment]
@RakshitKumar04 try to rebase with master first because a lot tests are failing and are not related to your PR, thanks 😄

**Comment by RakshitKumar04** [comment]
hey @valeriocost I have rebased it, is it fine now?

**Comment by RakshitKumar04** [comment]
Hey, @valeriocost Please review my PR.

**Comment by RakshitKumar04** [comment]
Hey @valeriocost please review the PR.

**Comment by valeriocost** [comment]
LGTM, ready to merge 👍🏼

**Pull request merged**
