### PR TITLE
Added Multi Dot

### LINKED ISSUE #19403: multi_dot

### PR DESCRIPTION
**Pull request by avi-thakur-0812**
Close #19403

### CODE REVIEW

**Comment by avi-thakur-0812** [comment]
@Mr-Niraj-Kulkarni Hey! Could you tell me why some tests seem to be failing, thanks!

**Comment by avi-thakur-0812** [comment]
@Mr-Niraj-Kulkarni  Hey, it's been a week, could you please tell me the changes that I need to make.

**Comment by Mr-Niraj-Kulkarni** [comment]
> @Mr-Niraj-Kulkarni Hey, it's been a week, could you please tell me the changes I need to make?

Hey Avi, Sorry I missed your comment. I will look at it and return to you by tomorrow's EOD.

**Comment by Mr-Niraj-Kulkarni** [comment]
Hey @avi-thakur-0812, I don't see the multi-dot method added. I think you have not committed that code.

**Comment by avi-thakur-0812** [comment]
> Hey @avi-thakur-0812, I don't see the multi-dot method added. I think you have not committed that code.

When I made the PR, there already was a multi-dot method, but no tests, so I added the necessary tests. But now, it seems like the multi-dot method has been removed.

So, should I close this, and make a new PR, with the method added?

**Comment by Mr-Niraj-Kulkarni** [comment]
> > Hey @avi-thakur-0812, I don't see the multi-dot method added. I think you have not committed that code.
> 
> When I made the PR, there already was a multi-dot method, but no tests, so I added the necessary tests. But now, it seems like the multi-dot method has been removed.
> 
> So, should I close this, and make a new PR? I already have the code for the method.

Yes Please. Thank you.

**Pull request closed without merging**
