### PR TITLE
Fix array inplace testing

### PR DESCRIPTION
**Pull request by xoiga123**
They're failing because torch doesn't allow `inplace` with gradient enabled tensors.

### CODE REVIEW

**Review by CatB1t — CHANGES_REQUESTED** [review]
If they're failing only for torch, we can create a custom strategy to not generate `as_variable` flags for torch specifically, also it may be worth getting in touch with @VedPatwardhan regarding that issue, could be something to have a workaround in the backend.

**Comment by VedPatwardhan** [comment]
Hey guys, there's quite a few functions in our API where the `torch` backend implementation supports inplace updates natively and we've been testing with the `as_variable` flag for quite a few months and the tests have been passing, I think it could be one of 2 possibilities,
1. We were already handling this in the test helpers and the handling may have been lost in a recent commit.
2. It's a problem with newer versions of `torch` (which is unlikely as I have remember seeing an error for this in the past).
In either case, I think we should be handling this in the tests itself, where `as_variable` should be set to `False` if `with_out=True` as we were doing before as far as I remember.

Thanks for looking into this @xoiga123 and @CatB1t 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
