### PR TITLE
fixed expm1 method in the PyTorch frontend

### PR DESCRIPTION
**Pull request by he11owthere**
closes https://github.com/unifyai/ivy/issues/20784

image

### CODE REVIEW

**Comment by he11owthere** [comment]
Hi @Infrared1029, could you please take a look at this? Thank you! :blush:

**Comment by he11owthere** [comment]
@Infrared1029 Please add 'bfloat16' in the `with_unsupported_dtypes` decorator before running the tests until the issue with `ivy.Array.repr` method has been resolved as mentioned by Ved in https://github.com/unifyai/ivy/pull/21447. Thank you! 🙂

**Comment by he11owthere** [comment]
@illia-bab, would you mind reviewing my pull request? It has already been more than 2 weeks; I would be really thankful to you.
Your insights would be highly appreciated. Thanks! 😊

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by he11owthere** [comment]
> This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

*

**Pull request merged**
