### PR TITLE
add function inv_ex operation to PyTorch frontend - test passed

### PR DESCRIPTION
**Pull request by MrZhangKY**

### CODE REVIEW

**Comment by MrZhangKY** [comment]
https://github.com/unifyai/ivy/issues/7920

**Comment by MrZhangKY** [comment]
@karalleyna Do you think it can be merged now?

**Comment by karalleyna** [comment]
Hi @MrZhangKY,

Could you reformat the files you have implemented, please? You can see the that the test for formatting fails and hence you may want to format ` ivy/functional/frontends/torch/linalg.py` so that we can see whether your test for `inv_ex` works properly. :)

**Comment by MrZhangKY** [comment]
Hi @karalleyna 
I reformat the files I have implemented.

**Comment by karalleyna** [comment]
Thank you for your contribution. :) It looks good to me.

**Comment by MrZhangKY** [comment]
Thank you! 😄 @karalleyna

**Pull request merged**
