### PR TITLE
empirical_covariance implementation (sklearn)

### LINKED ISSUE #22904: empirical_covariance

### PR DESCRIPTION
**Pull request by Anubhav-Goyal01**
Closes #22904

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Almost there. I've fixed the "0 not equal 1" issue. which was due to too many or too less dimensions. The sklearn docs specify 2 dimensional input as you might have seen.

There are dtype mismatches still. This mean our test detect the output to have a different dtype when function is called from our sklearn frontend compard against that of the native sklearn front. Ive fixed somewhat. but best maybe you give it a go. Run the test and look at the input to out put dtypes.
An error message like
`AssertionError: returned dtype = float16, ground-truth returned dtype = float64`
means that our frontend sklearn is returning float16 while native sklearn is return float64 for the same input.
The input data can be seen under `Falsifying example ......`
you can also experiment by playing around with native sklearn (`from sklearn.convariance import ...`) or our frontend sklearn ("from ivy.functional.frontends.sklearn.covariance import ..."

Don't hesitate to reach out with questions ☺️

**Comment by Anubhav-Goyal01** [comment]
Hi @Ishticode, thanks for the feedback, I have made a new commit trying to fix those issues

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Anubhav-Goyal01 
It seems like the `test_sklearn_empirical_convariance` has failed due to int8 not being supported by dot function. check the logs for `test_sklearn_empirical_convariance here`

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
