### PR TITLE
feature_alpha_dropout

### LINKED ISSUE #21634: feature_alpha_dropout

### PR DESCRIPTION
**Pull request by FraBomba6**
Close #21634

### CODE REVIEW

**Comment by FraBomba6** [comment]
**Note**
`alpha_dropout` was added by me [here](https://github.com/unifyai/ivy/pull/21712) but the computation of the function was wrong so I fixed it with the first commit, then added `feature_alpha_dropout`

**Comment by RickSanchezStoic** [comment]
Hi @FraBomba6 can you checkout the error logs in `intelligent-tests-pr / run_tests (1) (pull_request)` and  try fixing them ?

**Comment by FraBomba6** [comment]
@RickSanchezStoic I was generating a wrong sized input for the test to run  `intelligent-tests-pr / run_tests (1) (pull_request)`
Now some errors are still present but regarding types conversions between frameworks I guess

**Comment by FraBomba6** [comment]
@RickSanchezStoic could you please check out this PR?

**Comment by FraBomba6** [comment]
@RickSanchezStoic this PR is still pending

**Pull request closed without merging**
