### PR TITLE
Reformat index_nest

### PR DESCRIPTION
**Pull request by JerryGCDing**
#1820

### CODE REVIEW

**Comment by JerryGCDing** [comment]
I'm a bit confused about how the tests on docstring examples work and why it seems one of my examples using the Iterable type failed the test.

**Comment by JerryGCDing** [comment]
Hello @djl11, can you help me with my quick question? I should be able to fix it real soon. Thanks!

**Comment by sreegandh804** [comment]
Hi there,
The docstring tests simply execute the examples you've written . 
You should be able to test the examples you've written by creating a new .py file,  import ivy and write down the example you want to add as an example and run the file(If there is a more efficient method use that by all means,  this is just a suggestion 🙂 ),  I think this should help you debug what's causing that error.

**Comment by JerryGCDing** [comment]
Thank you for the suggestion! And can you give me some hints on why the check-formatting test is failing?

**Comment by sreegandh804** [comment]
Hi @JerryGCDing , 
The lint check are failure are not caused by any of the changes you've made, so nothing to worry about, they are related to unused variable in the helpers file.

**Comment by sreegandh804** [comment]
hey @JerryGCDing , 
Can you just undo the changes to gitignore, I'll get it merged right away 🙂

**Comment by JerryGCDing** [comment]
Just fixed it 🙂 @sreegandh804

**Pull request merged**
