### PR TITLE
maxpool2d

### PR DESCRIPTION
**Pull request by VikramxD**

### CODE REVIEW

**Comment by VikramxD** [comment]
@Ishticode can you please review this pr

**Comment by Ishticode** [comment]
Hi @VikramxD Thank you for the PR.
Currentl test_frontend_tensorflow is failing on your PR. Could you get it passing for your implementation and rerequest my review when done. Meanwhile feel free to ask for any question 😊

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @VikramxD Thank you for the PR.
Currentl `test_frontend_tensorflow` is failing on maxpool2d fromm your PR. Could you get it passing for your implementation and rerequest my review when done. Meanwhile feel free to ask for any question 😊

**Comment by VikramxD** [comment]
@Ishticode it seems the function itself is not implemented under ivy layers could you tell how to proceed with this ?

**Comment by Ishticode** [comment]
> @Ishticode it seems the function itself is not implemented under ivy layers could you tell how to proceed with this ?

Hi. Yh thats a bit of an issue. Your implementation seemed fine. A lot of times functions can be composed from others but it can be a bit of work sometimes.

You can leave this PR open for now and I will see tonight if I can get something done for maxpool2d in the backends. Meanwhile you are free to take on another function if you like and afterwards we can perhaps merge this PR also. Is that ok for you?

**Comment by VikramxD** [comment]
Yeah sure lets work it out together is there anything i can do to help in the backend implementations @Ishticode ?

**Pull request closed without merging**
