### PR TITLE
added binarizer to experimental api

### LINKED ISSUE #9957: Binarizer

### PR DESCRIPTION
**Pull request by aymuos15**
close #9957

### CODE REVIEW

**Comment by aymuos15** [comment]
Hi @agniiyer. Could you please review this request? thank you.

**Comment by aymuos15** [comment]
Hi @agniiyer. Just getting back to this. Could you please review this request? Thank you.

**Comment by agniiyer** [comment]
Hey apologies for the delay! Nicely done :)

**Comment by aymuos15** [comment]
Thank you so much!

**Pull request merged**
