### PR TITLE
Added instance method __lshift__ for numpy

### LINKED ISSUE #19478: __lshift__

### PR DESCRIPTION
**Pull request by Kappuccino111**
Close #19478

### CODE REVIEW

**Comment by Kappuccino111** [comment]
Hey @JPGoodale, could you please review the above PR and let me know if there are any changes needed?

**Comment by Kappuccino111** [comment]
Hey @JPGoodale, could you please review the above PR and let me know if there are any changes needed?

**Comment by Kappuccino111** [comment]
Hey @JPGoodale, I have updated the test function as required. Could you please review it? 

I have also attached a screenshot showing the tests passing.
test_pass

**Comment by Kappuccino111** [comment]
Hi @JPGoodale , any updates on the above ?

**Comment by JPGoodale** [comment]
Merged. Thank you for your contribution.

**Pull request merged**
