### PR TITLE
added context manager to refactor the way we apply decorators to redu…

### PR DESCRIPTION
**Pull request by mosesdaudu001**
…ce redundancy

### CODE REVIEW

**Review by vedpatwardhan — COMMENTED** [review]
Hey @mosesdaudu001, thanks for diving into this, certainly a useful approach to reduce redundancy. However, going through the file I'm realizing that we might be trading off with the readability quite a lot by doing this, and probably clearly specified decorators per function might be desirable by users as we end up with 7k lines of code in some files. 
Sorry for not letting you know earlier, even I'm realizing it now 😅

**Comment by mosesdaudu001** [comment]
No worries @vedpatwardhan 
I'm always happy to help in whatever way I can

**Comment by ZiadAmerr** [comment]
Hey @vedpatwardhan, I have talked about this with Yasser, and he suggested creating a new decorator that just applies the decorators using a list of them, instead of using a context manager, lmk what you think and maybe I could provide a preliminary example to it

**Comment by vedpatwardhan** [comment]
> Hey @vedpatwardhan, I have talked about this with Yasser, and he suggested creating a new decorator that just applies the decorators using a list of them, instead of using a context manager, lmk what you think and maybe I could provide a preliminary example to it

That's a good approach as well, as long as we don't hurt the readability of the code too much which is a challenge with the current approach. Happy to know more about what you plan on doing @ZiadAmerr @Infrared1029. Thanks 😄

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
