### PR TITLE
added descriptions and examples for dropout function.

### PR DESCRIPTION
**Pull request by htinaunglu**
Pull request for issue #8980
Description and Examples added.

### CODE REVIEW

**Comment by nassimberrada** [comment]
Hi @htinaunglu, thank you for your contribution ! The examples and description look good to me, could you also add examples for the container class, as well as array instance method and container instance method ? Thanks !

**Comment by htinaunglu** [comment]
hello @nassimberrada , I have added examples for container class, I am a little confuse with the `instance method` and checked other's commits, may I please get more clear instruction on that part? thanks!

**Comment by nassimberrada** [comment]
Hi @htinaunglu , your container examples look good thanks for the addition ! 

As far as array instance method and container instance method examples are concerned it's basically the same structure with the exception that the function is passed on the input as `x.dropout(arguments)` instead of `ivy.dropout(x, arguments)` the rest is identical to the examples you wrote. Hope that clarifies things a bit, let me know otherwise ! 

Also, before writing the instance method examples could you add the following lines as a header
```
Instance Method Examples
------------------------
``` 
similar to the `Examples` line that precedes the examples you wrote ? Thanks !

**Comment by htinaunglu** [comment]
hello @nassimberrada , could you please check my last commit. Thank you!!

**Comment by nassimberrada** [comment]
Hi @htinaunglu, looks great could you just remove the extra indenting for some of the `With ...` lines in the instance method examples ? Let me know when that's done and i'll be able to merge your PR. Thanks !

**Comment by htinaunglu** [comment]
Hello @nassimberrada , could you please check my last commit and able to merge? Thank you!

**Comment by nassimberrada** [comment]
Looking good, merging. Thank you for your contribution !

**Pull request merged**
