### PR TITLE
PR for random_crop

### PR DESCRIPTION
**Pull request by sowmen**
#1041

### CODE REVIEW

**Comment by sowmen** [comment]
@RashulChutani Can I get a code review for the PR?

**Comment by RashulChutani** [comment]
@sowmen You are not supposed to separate the implementation of random_crop into separate backends, as it is a compositional function. Please check out the "function types" in the contributor guidelines. Thanks.

**Comment by juliagsy** [comment]
Hey there! As this PR is inactive for more than 7 days, it will be closed in 24 hours if there are no further response. Thank you!

**Comment by juliagsy** [comment]
Closing due to inactivity

**Pull request closed without merging**
