### PR TITLE
adding tanh activation function to tensorflow frontend

### PR DESCRIPTION
**Pull request by anaghazachariah**

### CODE REVIEW

**Comment by anaghazachariah** [comment]
@aditya-pola Can you tell me whats going wrong?

**Comment by AlphaPro06** [comment]
If you take a look at the feedback from lint, it looks like you are missing one blank line in line 81 in your test_activations.py file. You can add an empty line in that line.

**Comment by anaghazachariah** [comment]
I corrected @AlphaPro06

**Comment by anaghazachariah** [comment]
Can you merge if everything is okay?

**Comment by anaghazachariah** [comment]
@AlphaPro06  @aditya-pola any updates?

**Comment by anaghazachariah** [comment]
@aditya-pola  please respond

**Comment by anaghazachariah** [comment]
@aditya-pola I have raise this pull request 4 days ago.There is no update from your part.Now someone else committed .I am closing this request.

**Comment by aditya-pola** [comment]
Hello @anaghazachariah, please find instructions in this [link](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues) (especially point d) on the initial steps to making a PR. The ToDO List issues instructions ensure a smooth workflow with minimal conflicts. One way it does that is by asking the contributor to mark an issue as being worked on by commenting `- [ ] #Issue_number` so that other users know which functions are already being worked on. Our approach to contributions is making it non-competitive and we expect new contributors to not work on issues that have already been marked as being worked on. 
We hope you intend to contribute to Ivy in the future, in which case please follow the guidelines set up by the link provided above. If you make another PR please understand that it takes reviewers upto a week for them to engage in the PR.

**Pull request closed without merging**
