### PR TITLE
Reformat elementwise maximum

### LINKED ISSUE #1749: maximum

### PR DESCRIPTION
**Pull request by SaadHasib**
Closes #1749

### CODE REVIEW

**Comment by simonetgordon** [comment]
Hi,

Thanks for the contribution!

The docstring test is failing for this function. Please check the output of `Details` -> `Run Docstring Test` for more details on the failure.

Simone

**Comment by SaadHasib** [comment]
Fixed the output data types in the doc strings.

All tests are passing.

**Comment by simonetgordon** [comment]
Hi Saad,

You are missing a static container method as per point 8 in the [contributor guide](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html#docstring-examples). Please ensure you have not missed any other category of example.

Thanks!

Simone

**Comment by simonetgordon** [comment]
Hi Saad, 

Ah I see, I assumed they would be. No, you can leave them for now and I can get his PR merged. Thanks for the contribution!

Kind Regards, 

Simone

**Pull request merged**
