### PR TITLE
feat: Updated `paddle` version mapping form `2.5.2` to `2.6.0`

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
[New version of PaddlePaddle](https://github.com/PaddlePaddle/Paddle/releases/tag/v2.6.0) is released. So, I have updated the version from `2.5.2` to `2.6.0`.

## Related Issue
Closes #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Review by KareemMAX — COMMENTED** [review]
I know you only changed paddle related functions, but @vedpatwardhan can you check that this PR didn't introduce new errors?

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Feel free to merge @KareemMAX, thanks @Sai-Suraj-27 😄

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Can you merge the conflicts real quick? @Sai-Suraj-27

**Comment by Sai-Suraj-27** [comment]
> Can you merge the conflicts real quick? @Sai-Suraj-27

Done @KareemMAX. Please check now. 👍🏻

**Pull request merged**
