### PR TITLE
lcm_

### LINKED ISSUE #21625: lcm_
Todo list: #3612

### PR DESCRIPTION
**Pull request by NiteshK84**
Closes #21625

### CODE REVIEW

**Comment by NiteshK84** [comment]
image
image

**Comment by theRealBird** [comment]
Thank you for your contribution to Ivy!

**Comment by NiteshK84** [comment]
Hi @theRealBird,
I have fixed the conflicts, 
please feel free to merge it.
thanks.

**Comment by theRealBird** [comment]
@NiteshK84 Thanks for resolving the conflicts Nitesh. For some reason, your PR is introducing a lot of new failures (unrelated to your changes). Seems like there is a bug with the CI testing but could you please take a look once too? Thanks!

**Comment by NiteshK84** [comment]
Hey @theRealBird, the branch was falling behind the test_array_api submodule update, which was not getting fixed with just the rebase, so i had no other option other than creating a new branch from main again,

if you have any better solution please leave here,
thanks

new branch->  #21626

**Comment by theRealBird** [comment]
image
Hi @NiteshK84,
Thanks for the great work on the PR. Yes you are not required to fix anything that you did not write. 
I see some failures of LCM too, could you please take a look. Thanks!

**Comment by NiteshK84** [comment]
Hey @theRealBird, i fixed all the failures,
its ready to review now,
Thanks

**Pull request closed without merging**
