### PR TITLE
inplace_decrement #3791

### PR DESCRIPTION
**Pull request by aryans1204**
…d all lambda bindings, updated type hints

### CODE REVIEW

**Comment by aryans1204** [comment]
add_reformatting_checklist_general

**Comment by aryans1204** [comment]
awaiting review from @rush2406

**Comment by aryans1204** [comment]
to do list issue #3791

**Review by CatB1t — CHANGES_REQUESTED** [review]
Hello @aryans1204, Please make changes that address only one function, `inplace_decrement`. 
Also we should be adding docstring examples to this function here: https://github.com/unifyai/ivy/blob/8c677baa152cf8f91534b8118e89b492dd6a01d8/ivy/functional/ivy/general.py#L2763

**Comment by aryans1204** [comment]
Hi,

From the Deep Dive, I had believed that while working on function reformatting issues, we had to fix all lambda bindings and type hints for the five backends. So do you want me to remove the type hints and lambda bindings I fixed for other functions other than inplace_decrement?

**Comment by CatB1t** [comment]
Hello @aryans1204, exactly, the task should only update 1 function at a time, you should only do changes related to the function `inplace_decrement`.

**Pull request closed without merging**
