### PR TITLE
Update is_non_decreasing in math.py

### PR DESCRIPTION
**Pull request by Fayad-Alman**
Modified is_non_decreasing function:
- Changed comparison to remove 2-D array
- ivy.all comparison now excludes final comparison of last element to first element

### CODE REVIEW

**Comment by Fayad-Alman** [comment]
#10121

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @Fayad-Alman.

Apologies for the late response. I was swamped with work last week and so reviewing this PR totally slipped under my radar 😅 

With regards, to the changes you've made, I have noticed that some of the intelligent tests are still failing for `test_tensorflow_is_non_decreasing` (https://github.com/unifyai/ivy/actions/runs/4100990413/jobs/7072341289). Could you kindly fix those and re-request a review? Thanks! 😃

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
