### PR TITLE
ENH: adding in elemenetwise Erfinv

### LINKED ISSUE #17011: erfinv
I am going to erfinv in elementwise.py from https://github.com/unifyai/ivy/issues/3856 this function must be in elementwise so I can erfinv in paddle.tesnor.tensor.Tensor .

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
I am adding erfinv in elementwise.py from issue Closed #17011

### CODE REVIEW

**Comment by sagewhocodes** [comment]
Hello MuhammadNizamani, I've added the comments on the corresponding issue #16720

**Comment by MuhammadNizamani** [comment]
@sagewhocodes  Anna has cleased this issue for this PR so What am I suppose to do with PR?

**Comment by sagewhocodes** [comment]
@MuhammadNizamani As anna said, you should open a new issue with the Sub task template and comment the issue number on #3856  . You can then reference this PR in your newly created issue 😄

**Comment by MuhammadNizamani** [comment]
> @MuhammadNizamani As anna said, you should open a new issue with the Sub task template and comment the issue number on #3856 . You can then reference this PR in your newly created issue smile

what should I label the issue that I will create for this PR?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MuhammadNizamani** [comment]
@sagewhocodes  sir could you review this PR please

**Comment by sagewhocodes** [comment]
Hello @MuhammadNizamani , i see you're missing the test for the added function.
Please refer to [Ivy tests doc](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html) to know more

**Comment by sagewhocodes** [comment]
@MuhammadNizamani could you check why your test gets terminated without running?

**Comment by MuhammadNizamani** [comment]
> @MuhammadNizamani could you check why your test gets terminated without running?

i am on it.

**Comment by MuhammadNizamani** [comment]
@sagewhocodes Just so you in the test file most of the test function don't run properly, there is some expection. I have mention some of the team member on discord on reply me.

**Comment by MuhammadNizamani** [comment]
@sagewhocodes Could you please provide details about the error you encountered when running the test?  I ran the test for this function three times on your laptop, and each time it crashed my laptop.

**Comment by sagewhocodes** [comment]
@MuhammadNizamani this issue is happening because `erfinv` function is not present in any of the backends that ivy supports. You should implement `erfinv` in each of the backends and then retry running the tests.
Please ensure the individual function implementations have correct arguments and follow the superset behaviour.

**Comment by MuhammadNizamani** [comment]
@sagewhocodes  sir i should implement  `erfinv` in elementwise.py in back-end of API

**Comment by MuhammadNizamani** [comment]
> @MuhammadNizamani this issue is happening because `erfinv` function is not present in any of the backends that ivy supports. You should implement `erfinv` in each of the backends and then retry running the tests. Please ensure the individual function implementations have correct arguments and follow the superset behaviour.

@sagewhocodes can you point me to the docs where i find about implemetation of backend function

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
