### PR TITLE
 Hfft frontend numpy

### PR DESCRIPTION
**Pull request by jashdalvi**
I have added some basic code, which is currently not working since there is no hfft or irfft in ivy backend. Should I wait for these functions to be added in the backend or should I try to write it from scratch? @ZoeCD

### CODE REVIEW

**Comment by jashdalvi** [comment]
Close #14241

**Comment by ZoeCD** [comment]
Hi! You can implement this either using other Ivy functions, or, if it's a function that's needed for various frameworks, you can create an issue to add the Ivy implementation to our API and work on something else. You can read more about it [here](https://lets-unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) 🙂

**Comment by jashdalvi** [comment]
I think all the fft functions will surely be needed across all frontends and implementing it compositionally based on other ivy functions would not be trivial. I will create an issue as you suggested. Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
