### PR TITLE
Update inv() #443 to conform to Array API Standard

### PR DESCRIPTION
**Pull request by SayanJerr**

### CODE REVIEW

**Comment by SayanJerr** [comment]
Tensorflow seems to have a problem with the Eagle tensor and Jaxx.........

**Comment by SayanJerr** [comment]
As for jax
@pytest.mark.xp_extension('linalg')
>   @given(x=invertible_matrices())
E   hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 8 valid examples in 1.01 seconds (0 invalid ones and 2 exceeded maximum size). Try decreasing size of the data you're generating (with e.g. max_size or max_leaves parameters).
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.

ivy/ivy_tests/test_array_api/array_api_tests/test_linalg.py:268: FailedHealthCheck
---------------------------------- Hypothesis ----------------------------------
You can add @seed(33797418062777158039021[211](https://github.com/unifyai/ivy/runs/5727981121?check_suite_focus=true#step:3:211)0029121429640) to this test or run pytest with --hypothesis-seed=337974180627771580390[212](https://github.com/unifyai/ivy/runs/5727981121?check_suite_focus=true#step:3:212)1100291[214](https://github.com/unifyai/ivy/runs/5727981121?check_suite_focus=true#step:3:214)29640 to reproduce this failure.
=============================== warnings summary ===============================
ivy/ivy/container.py:852
  /ivy/ivy/container.py:852: DeprecationWarning: invalid escape sequence \.
    flat_keys = re.split('/|\.', key_chain)

ivy/ivy/functional/ivy/linear_algebra.py:55
  /ivy/ivy/functional/ivy/linear_algebra.py:55: DeprecationWarning: invalid escape sequence \*
    """

ivy/ivy/functional/ivy/linear_algebra.py:442
  /ivy/ivy/functional/ivy/linear_algebra.py:442: DeprecationWarning: invalid escape sequence \m
    """

ivy/ivy/functional/backends/numpy/elementwise.py:3
  /ivy/ivy/functional/backends/numpy/elementwise.py:3: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
    import numpy.array_api as npa

usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19
  /usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

ivy/ivy/functional/backends/jax/old/general.py:12
  /ivy/ivy/functional/backends/jax/old/general.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Iterable

ivy/ivy/framework_handler.py:116
  /ivy/ivy/framework_handler.py:116: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    if isinstance(specific_v, collections.Hashable):

usr/local/lib/python3.8/dist-packages/hypothesis/extra/array_api.py:778
  /usr/local/lib/python3.8/dist-packages/hypothesis/extra/array_api.py:778: HypothesisWarning: Could not determine whether module ivy.functional.backends.jax is an Array API library
    warn(

ivy/ivy_tests/test_array_api/array-api/spec/API_specification/signatures/creation_functions.py:32
  /ivy/ivy_tests/test_array_api/array-api/spec/API_specification/signatures/creation_functions.py:32: DeprecationWarning: invalid escape sequence \s
    """

ivy/ivy_tests/test_array_api/array-api/spec/API_specification/signatures/linalg.py:447
  /ivy/ivy_tests/test_array_api/array-api/spec/API_specification/signatures/linalg.py:447: DeprecationWarning: invalid escape sequence \*
    """

ivy/ivy_tests/test_array_api/array-api/spec/API_specification/signatures/elementwise_functions.py:601
  /ivy/ivy_tests/test_array_api/array-api/spec/API_specification/signatures/elementwise_functions.py:601: DeprecationWarning: invalid escape sequence \s
    """

ivy_tests/test_array_api/array_api_tests/test_sorting_functions.py::test_sort
ivy_tests/test_array_api/array_api_tests/test_sorting_functions.py::test_sort
ivy_tests/test_array_api/array_api_tests/test_sorting_functions.py::test_sort
ivy_tests/test_array_api/array_api_tests/test_sorting_functions.py::test_sort
  /usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py:3828: UserWarning: 'kind' argument to sort is ignored.
    warnings.warn("'kind' argument to sort is ignored.")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ivy/ivy_tests/test_array_api/array_api_tests/test_linalg.py::test_inv
=== 1 failed, 106 passed, 4053 deselected, 15 warnings in 430.73s (0:07:10) ====
Error: Process completed with exit code 1.

**Review by SayanJerr — COMMENTED** [review]
@saeedashrraf

**Review by SayanJerr — COMMENTED** [review]
@saeedashrraf
Done

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
