### PR TITLE
Fixes broken links in ivy docs

### PR DESCRIPTION
**Pull request by Sarvesh-Kesharwani**
- [x] which of these files (https://github.com/data-apis/array-api/tree/main/spec/2022.12/API_specification) should be referenced here --> 
chrome_xtpUeyCdFM
https://unify.ai/docs/ivy/overview/deep_dive/docstrings.html

for now i have replaced theme with "https://github.com/data-apis/array-api/blob/main/spec/2022.12/API_specification/function_and_method_signatures.rst"

- [ ] This one link is not responding : https://ivy-dynamical-dashboards.onrender.com

### CODE REVIEW

**Comment by Sarvesh-Kesharwani** [comment]
Hi Haris, this PR closes one of the Trello task https://trello.com/c/MF7z5MAa/2192-fixing-broken-links-in-the-docs?search_id=55f85ce5-f527-4b83-bb0e-d65138010dca.

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi @Saransh-28 

Requested a few changes :slightly_smiling_face: 

Thanks!

**Comment by Sarvesh-Kesharwani** [comment]
> Hi @Saransh-28
> 
> Requested a few changes 🙂
> 
> Thanks!

Hey @zaeemansari70, I have addressed all the highlighted corrections as per your review. Thank you for your feedback.

**Comment by zaeemansari70** [comment]
@Sarvesh-Kesharwani 
Sorry, My bad, just updated it :slightly_smiling_face:

**Pull request merged**
