### PR TITLE
Tensorflow frontend - unsorted segment sum function added

### PR DESCRIPTION
**Pull request by adityarajsahu**
**Adding unsorted_segment_sum function to TensorFlow frontend**
Here is the link to the [issue](https://github.com/unifyai/ivy/issues/1545).

Computes the sum along segments of an array.

ivy.unsorted_segment_sum(
    data, segment_ids, num_segments, name=None
)

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by adityarajsahu** [comment]
@Ishticode the failing checks belong to some other test functions that are not related to unsorted_segment_sum function. Can you please check the pull request?

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @adityarajsahu 
Thank you very much for the PR.
Almost there. It seems the test for the numpy is failing locally with error `E       TypeError: 'Array' object cannot be interpreted as an integer`. Have you seen this error?

**Comment by adityarajsahu** [comment]
> TypeError: 'Array' object cannot be interpreted as an integer

@Ishticode yes i checked it. 
`shape = (ivy.array(2), 6)`
i am getting this as shape of the output array. Can't figure out why. Please help

**Review by Ishticode — APPROVED** [review]
The issue above had persisted which I have fixed now. It was simple because and array was being passed down to the ivy.zeros functins. Good to merge now.  Thank you very much @adityarajsahu for your contribution 😊

**Comment by adityarajsahu** [comment]
@Ishticode Thanks for your help.

**Pull request merged**
