### PR TITLE
Adding nansum statistical function and test#13710

### PR DESCRIPTION
**Pull request by curi-adi**
Creating this PR for the issue for https://github.com/unifyai/ivy/issues/13710

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by curi-adi** [comment]
Creating this PR for the issue for https://github.com/unifyai/ivy/issues/13710

**Comment by bipinKrishnan** [comment]
Hey @curi-adi , you should always add "Close<issue_id>" in your comment to automatically link your issue with the PR. I'll do this manually for now. Also since you are directly working on your master branch, I don't have push access. So, please fix the merge conflicts from your side. Thanks :slightly_smiling_face:

**Comment by bipinKrishnan** [comment]
Also, its better if you install pre-commit in your system and lint the code before making a push.

**Comment by bipinKrishnan** [comment]
ivy-gardener

**Comment by curi-adi** [comment]
@bipinKrishnan, thank you so very much for taking out time to review my PR, and also going ahead and filling up the missing stops. My apologies for missing out those, although inadvertently. I will take care of the steps in future PR's.

currently working on fixing conflicts

**Comment by bipinKrishnan** [comment]
Hey @curi-adi , since you are dierclty working on the master of your fork, I may not have push access. So can you please fix the conflicts and push the changes?

**Comment by curi-adi** [comment]
> Hey @curi-adi , since you are dierclty working on the master of your fork, I may not have push access. So can you please fix the conflicts and push the changes?

Hey @bipinKrishnan  I am currently checking how to resolve the conflicts as I am not that familiar with git's resolve conflicts, thanks

**Pull request closed without merging**
