### PR TITLE
added gumbel_softmax paddle 

### LINKED ISSUE #19381: gumbel_softmax

### PR DESCRIPTION
**Pull request by smitkalathiya**
added gumbel_softmax at paddle.nn.functional.activation

close #19381

### CODE REVIEW

**Review by AryanSharma21 — COMMENTED** [review]
implementation seems ok. Can you provide the screenshot of the test running in local environment. Just to see if test passes locally

**Comment by smitkalathiya** [comment]
ya about that when I am adding the test environment it shows error.

**Comment by AryanSharma21** [comment]
You can run the tests manually using the pytest command in the terminal 
use
pytest -v <path of test> -k <test function name>
it should run

**Comment by smitkalathiya** [comment]
let me try and reach you again.

**Comment by smitkalathiya** [comment]
from all the failing run_tests test number 8 is not mine.
please review it and address me the changes.

**Review by AryanSharma21 — COMMENTED** [review]
Please run test in local environment and provide screenshot of the result .

**Comment by smitkalathiya** [comment]
@AryanSharma21  can I reach you on discord?

**Comment by AryanSharma21** [comment]
Ofcourse , Drop your id I'll connect

**Pull request closed without merging**
