### PR TITLE
Add bytes function to numpy frontend (#16360)

### LINKED ISSUE #16360: bytes

### PR DESCRIPTION
**Pull request by VinuUD**
Added `random.bytes` function to `numpy` frontend with Ivy compositions. (closes #16360)

### CODE REVIEW

**Comment by VinuUD** [comment]
Hi team! 

I have implemented the function `bytes` to simulate the functionality of `numpy.random.bytes`.

I would appreciate some help in writing the tests for this function. I believe the following should be tested:

1. **Length of the Output:** The output byte string should match the length specified in the input.
2. **Type of the Output:** The output should be of type `bytes`.
3. **Randomness:** Check whether the ouput bytes are indeed bytes are indeed random.

If anyone can assist on how to test these aspects or if there are that need to be tested, I would greatly appreciate the input.

Thank you.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by VinuUD** [comment]
> Hi team!
> 
> I have implemented the function `bytes` to simulate the functionality of `numpy.random.bytes`.
> 
> I would appreciate some help in writing the tests for this function. I believe the following should be tested:
> 
> 1. **Length of the Output:** The output byte string should match the length specified in the input.
> 2. **Type of the Output:** The output should be of type `bytes`.
> 3. **Randomness:** Check whether the ouput bytes are indeed bytes are indeed random.
> 
> If anyone can assist on how to test these aspects or if there are that need to be tested, I would greatly appreciate the input.
> 
> Thank you.

@suvadityamuk can you take a look at this when you have some free time?
Thank you.

**Comment by Daniel4078** [comment]
> Hi team!
> 
> I have implemented the function `bytes` to simulate the functionality of `numpy.random.bytes`.
> 
> I would appreciate some help in writing the tests for this function. I believe the following should be tested:
> 
> 1. **Length of the Output:** The output byte string should match the length specified in the input.
> 2. **Type of the Output:** The output should be of type `bytes`.
> 3. **Randomness:** Check whether the ouput bytes are indeed bytes are indeed random.
> 
> If anyone can assist on how to test these aspects or if there are that need to be tested, I would greatly appreciate the input.
> 
> Thank you.

Sorry for the delay as the previous reviewer is not available at the moment. In short, you need to write a test function like the other pull requests linked in the TODO list this task is from. You can find other info about how to write our test in the [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) and our [Deep Dive document](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html).

**Pull request closed without merging**
