### PR TITLE
Add ldexp to torch frontend api with test

### LINKED ISSUE #21874: ldexp

### PR DESCRIPTION
**Pull request by Sjsingh101**
closes #21874

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
Nice effort

**Review by hello-fri-end — APPROVED** [review]
LGTM!

**Review by Akshat111111 — COMMENTED** [review]
Have completed

**Review by Akshat111111 — COMMENTED** [review]
The function is efficient

**Pull request merged**
