### PR TITLE
#12400 Added conj to ivy frontend

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Close #12400

**Comment by RakshitKumar04** [comment]
Hey, @danielmunioz please review my PR.

**Comment by RakshitKumar04** [comment]
Hey, @danielmunioz can you please take a look at the PR

**Comment by danielmunioz** [comment]
Hey @RakshitKumar04! Thanks for the contribution!, the tests for your function seem to be failing, locally at least, could you please take a look at that?, Also the function seems to be missing the `out` parameter, the frontend function itself should resemble the original [framework function](https://numpy.org/doc/stable/reference/generated/numpy.conj.html) as much as possible. Also, there seem to be some lint issues particularly on the test, could you please take a loot at those?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by RakshitKumar04** [comment]
.

**Comment by RakshitKumar04** [comment]
Hey, @danielmunioz Can you please guide me on how do I resolve these errors

**E   TypeError: can't convert complex to float**
E   Falsifying example: test_numpy_conj(
E       dtypes_values_casting=(['complex64'],
E        [array(-1.-1.j, dtype=complex64)],
E        'no',
E        None),
E       where=[array(False)],
E       fn_tree='ivy.functional.frontends.numpy.conj',
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=1,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=True,
E       ),
E       frontend='numpy',
E       on_device='cpu',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.71.0', b'AXicY2AAAUYGBjiNzAaSAABmAAY=') as a decorator on your test case

**E   IndexError: list index out of range**
E   Falsifying example: test_numpy_conj(
E       dtypes_values_casting=(['complex128'], [array(-1.-1.j)], 'no', None),
E       where=[array(False)],
E       fn_tree='ivy.functional.frontends.numpy.conj',
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=1,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=True,
E       ),
E       frontend='numpy',
E       on_device='cpu',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.71.0', b'AXicY2AAAUYGBjiNzAaSAABmAAY=') as a decorator on your test case

**E   RuntimeError: value cannot be converted to type double without overflow**
E   Falsifying example: test_numpy_conj(
E       dtypes_values_casting=(['complex128'], [array(-1.-1.j)], 'no', None),
E       where=[array(False)],
E       fn_tree='ivy.functional.frontends.numpy.conj',
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=1,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=True,
E       ),
E       frontend='numpy',
E       on_device='cpu',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.71.0', b'AXicY2AAAUYGBjiNzAaSAABmAAY=') as a decorator on your test case

**Comment by RakshitKumar04** [comment]
Hey @danielmunioz can you please guide me on how to resolve this error
E   hypothesis.errors.InvalidArgument: test_numpy_conj() got an unexpected keyword argument 'dtype_and_x', from `dtype_and_x=dtype_and_values(available_dtypes=get_dtypes(kind='real_and_complex'))` in @given

**Pull request merged**
