### PR TITLE
feat: Paddle Frontend special method __pow__

### LINKED ISSUE #27246: __pow__

### PR DESCRIPTION
**Pull request by Mac16661**
Closes #27246

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by NripeshN** [comment]
Hey @Mac16661 
Are your tests passing locally?
`pytest -v ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor__pow__`

**Comment by Mac16661** [comment]
Im facing an issue in my local machine

image

this is the err I am getting. I don't know how to fix it. I need help regarding that .

**Comment by Mac16661** [comment]
But it should pass because I didn't implement it. I used  UT of pow function. This UT should work for __pow__ function right?

**Comment by NripeshN** [comment]
> Im facing an issue in my local machine
> 
> image
> 
> this is the err I am getting. I don't know how to fix it. I need help regarding that .

Have you tried running pytest before with any other function?
pytest -v <file_path>:<file_name>

**Comment by NripeshN** [comment]
> But it should pass because I didn't implement it. I used UT of pow function. This UT should work for _ _pow_ _ function right?

Looks like the test is failing though
https://github.com/unifyai/ivy/actions/runs/6915160423/job/18814117734?pr=27320#step:6:29

**Comment by Mac16661** [comment]
Okay, I have checked the methods in torch frontend. The problem is __pow__  method in torch expects a vector and a number , but for paddle as well as TensorFlow __pow__  method expects 2 vectors.

**Comment by Mac16661** [comment]
Torch implementation 
```
@with_unsupported_dtypes({"2.1.0 and below": ("bfloat16",)}, "torch")
    def __pow__(self, exponent):
        return self.pow(exponent)
```
tensorflow implementation 

```
def __pow__(self, y, name="pow"):
        return tf_frontend.math.pow(x=self, y=y, name=name)
```

My implementation in paddle frontend

```
@with_unsupported_dtypes({"2.5.1 and below": ("float16", "bfloat16")}, "paddle")
    def __pow__(self, y, name=None):
        return paddle_frontend.pow(self, y)
```

**Comment by NripeshN** [comment]
[aibenStunner](https://github.com/aibenStunner)
Could you please take a look at this PR

**Comment by NripeshN** [comment]
Hey @Mac16661,
Unfortunately, I cannot merge this PR as the tests are not passing. Sorry!

**Pull request closed without merging**
