### PR TITLE
Mihaelayounas work on slice general function

### PR DESCRIPTION
**Pull request by mihayounas**

### CODE REVIEW

**Comment by mihayounas** [comment]
Hi Zoe, while I am waiting for your feedback please consider a simple version 👍🏻 
def slice(input_, begin, size, name=None):
    return ivy.slice(input_, begin, size).Please keep in mind that I am trying to understand it and the other version seemed better.

**Comment by ZoeCD** [comment]
Hi! Currently, there is no `ivy.slice` implementation. So, you can try to implement it as a composition of other Ivy functions, or move on to another frontend function. For more detailed instructions, please read our fronted API guide [here](https://lets-unify.ai/ivy/contributing/open_tasks.html#frontend-apis). Also, for each function added, a test function is needed. For more information about contributing, you can read our [docs](https://lets-unify.ai/ivy/contributing.html) or watch our [YouTube series](https://www.youtube.com/playlist?list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG) 🙂

**Comment by mihayounas** [comment]
Hi Zoe, thank you will have a look into this .Thank you for claifying .

**Comment by mihayounas** [comment]
Hi Zoe, do you think that implementing slice in the clip_by_value function would be ok?it seems to me that are similar in functionality?Or it's best to make a new function and test it on ivy.array.slice?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by mihayounas** [comment]
Hello I am still working on it but I have issues with testing it, I am trying with PyCharm but I am getting installation error so I did not commit the changes because I could not test it.Apologies for this I am reinstalling it today hoping to test it before committing .

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
