### PR TITLE
Added functions for SequenceLength

### LINKED ISSUE #23664: SequenceLength

### PR DESCRIPTION
**Pull request by DaveOkpare**
Closes #23664

### CODE REVIEW

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hey @DaveOkpare,
Seems like your code is missing an implementation for the different backends, please follow [this guide](https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html).

**Comment by DaveOkpare** [comment]
> Hey @DaveOkpare,
> Seems like your code is missing an implementation for the different backends, please follow [this guide](https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html).

Alright, I'm on it. Thanks for the tip!

**Comment by KareemMAX** [comment]
> Alright, I'm on it. Thanks for the tip!

Cool @DaveOkpare, please request a review from me once you finish

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
