### PR TITLE
fix: Fix Ivy Failing Test: paddle - elementwise.divide

### LINKED ISSUE #28069: Fix Ivy Failing Test: paddle - elementwise.divide

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
# PR Description
The elementwise divide were failing in paddle because angle  function used by paddle divide function and the angle function does not work in integers so to solve this I remove int32 and int64 from elementwise.divide in paddle backend.
all local tests are passing.
elementwise divide

## Related Issue

Closes #28069

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by samthakur587** [comment]
jsut remove astype from paddle backend. and add these constrain to test function. 
test_gradients=st.just(False),
helpers.get_dtypes("numeric",full=False),

**Comment by MuhammadNizamani** [comment]
@samthakur587  sir can you e

> jsut remove astype from paddle backend. and add these constrain to test function. test_gradients=st.just(False), helpers.get_dtypes("numeric",full=False),

could you elaborate how this solution works please it would great help .
btw thanks sir for your kind reply 🙏🤗

**Comment by MuhammadNizamani** [comment]
@samthakur587  Thanks a lot your suggestion worked and all test are passing 
new paddle elementwise divide

**Comment by samthakur587** [comment]
> > jsut remove astype from paddle backend. and add these constrain to test function. test_gradients=st.just(False), helpers.get_dtypes("numeric",full=False),
> 
> @samthakur587 sir could you elaborate how this solution works please it would great help . btw thanks sir for your kind reply 🙏🤗

LGTM! but as of now the paddle.divide has bug for the int dtype so we are using x1/x2 but if this bug get resolved then we can change it to the paddle.divide .

**Pull request merged**
