### PR TITLE
Adding arccosh to torch frontend

### LINKED ISSUE #14131: arccosh

### PR DESCRIPTION
**Pull request by vtsamit**
Close #14131

### CODE REVIEW

**Comment by zhumakhan** [comment]
Hi @vtsamit , thanks for you PR! Could you also please add arccosh_ function similar to this one: https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/torch/tensor.py#L160?

**Comment by vtsamit** [comment]
Yes sir. I have already added arccosh_ too but in another PR (#14139). Should I add both the functions in the same PR?

**Comment by zhumakhan** [comment]
Great! Yes could you please add it to this PR?

**Comment by zhumakhan** [comment]
Also, tests of arccosh are failing because on_device argument was not passed: TypeError: test_frontend_method() missing 1 required keyword-only argument: 'on_device'
Could you please fix that, rest seems valid to me

Thanks

**Comment by vtsamit** [comment]
Yes sir, I have made the changes. Thank You.

**Pull request merged**
