### PR TITLE
Added Trace method in Paddle Frontend

### LINKED ISSUE #22555: trace

### PR DESCRIPTION
**Pull request by Aaryan562**
Close #22555

### CODE REVIEW

**Comment by Aaryan562** [comment]
Hey @theRealBird could you please review my PR! Thanks

**Comment by theRealBird** [comment]
Hi @Aaryan562, thanks for contributing to Ivy. Functionally your PR looks good to me :)
There are a bunch of formatting errors in your code as pointed out in the lint check. Please fix them. Thanks!

**Comment by Aaryan562** [comment]
@theRealBird I have no idea how to fix that black lint error. Anyways my previous PR also had this but it got merged as my all local test cases were passing. Also other lint checks are passing its just black which I am not able to figure out.

**Comment by Aaryan562** [comment]
Ig I did something wrong let me close this PR and create another one

**Pull request closed without merging**
