### PR TITLE
added heaviside function to torch frontends.

### PR DESCRIPTION
**Pull request by elreweidy**
#9803

### CODE REVIEW

**Comment by vaatsalya123** [comment]
Hey @elreweidy first of all thanks for making the PR , Just had a look and mostly the PR look's good to me just a few changes needed related to formatting and failing test which should be resolved:

1.)Please resolve the failing test locally to see if your implementation is correct ( I tested the implementation locally and it is failing so please have a look at that)

2.)Please resolve the lint test failures that could be fixed like add a new line at the end of the file.

Once these issues are fixed we can merge this PR (:

**Comment by elreweidy** [comment]
Hello @vaatsalya123, you are welcome :) 
Regardless of the lint test failure which I will resolve shortly. I don't get any failing tests locally ( running docker on VScode ).
can you please hint to me what could be this error: "fixture 'as_variable' not found"

**Comment by elreweidy** [comment]
Close #9803 
Please let me know if there are any other modifications needed.

**Comment by vaatsalya123** [comment]
lgtm!

**Pull request merged**
