### PR TITLE
Add Signal functions for TensorFlow frontend tensorflow.dct

### PR DESCRIPTION
**Pull request by MuokaPWambua**
### Issue 
- [ ] missing ivy.dct

### CODE REVIEW

**Comment by ogbanugot** [comment]
Hey @MuokaPWambua, can you please add a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues), where `issue_number` is the corresponding issue for this function.

**Comment by ogbanugot** [comment]
Hey @MuokaPWambua , kindly confirm the number of files you have committed. It appears while merging the upstream master branch, a lot of files have been included in your commit. In any case I think you should have only two files committed `ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py` and 
`ivy/functional/frontends/tensorflow/signal.py`. You'll have clean up the number of files you have committed in order to get this merged. Thanks for effort!

**Comment by MuokaPWambua** [comment]
Close  #6003

**Comment by MuokaPWambua** [comment]
> Hey @MuokaPWambua , kindly confirm the number of files you have committed. It appears while merging the upstream master branch, a lot of files have been included in your commit. In any case I think you should have only two files committed `ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py` and `ivy/functional/frontends/tensorflow/signal.py`. You'll have clean up the number of files you have committed in order to get this merged. Thanks for effort!

Hi @ogbanugot, am having problems trying to track the .idea folder in .gitignore file, any suggestion

**Comment by MuokaPWambua** [comment]
i reverted my branch to clear the numbers of files

**Review by ogbanugot — CHANGES_REQUESTED** [review]
Hey @MuokaPWambua , great work cleaning up the files, almost there! However, you have committed changes to files within the `test_array_api` submodule which is not in our scope as this is a separate git repository for the array API standard. I'll suggest removing `test_array_api` from your commit and push again. Also can you please take a look at `ivy/functional/backends/jax/gradients.py`, `ivy/functional/backends/torch/gradients.py` and `ivy/functional/backends/tensorflow/gradients.py`, did you add those lines? If you did I'm not sure why but if not then they shouldn't be there. You'll have to remove those lines and push. Again, you should have only two files with changes as explained earlier. Thanks!

**Comment by MuokaPWambua** [comment]
hi @ogbanugot, have been having problems trying with my push all my PR keep getting updated with unchanged files, have switched to another branch that has made a new PR

> Hey @MuokaPWambua , great work cleaning up the files, almost there! However, you have committed changes to files within the `test_array_api` submodule which is not in our scope as this is a separate git repository for the array API standard. I'll suggest removing `test_array_api` from your commit and push again. Also can you please take a look at `ivy/functional/backends/jax/gradients.py`, `ivy/functional/backends/torch/gradients.py` and `ivy/functional/backends/tensorflow/gradients.py`, did you add those lines? If you did I'm not sure why but if not then they shouldn't be there. You'll have to remove those lines and push. Again, you should have only two files with changes as explained earlier. Thanks!

**Pull request closed without merging**
