### PR TITLE
Examples were added to svdvals().

### LINKED ISSUE #1255: svdvals
Reformat svdvals #1258

### PR DESCRIPTION
**Pull request by karlschwarz**
This pull request fixes #1255 

- Examples were added to svdvals() function in linear_algebra.
- This PR is the same as #1258 which is accidently closed when we are trying to change the base branch to a different branch other than master ([solution](https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch/26986320#26986320)).

Thanks for the review.

### CODE REVIEW

**Comment by chie2727** [comment]
Hi @karlschwarz, thanks for making a new PR.

@MarShaikh I've just assigned you as it seems you were reviewing @karlschwarz 's previous PR.

**Comment by karlschwarz** [comment]
@chie2727 Sure, thanks for your help!

**Comment by MarShaikh** [comment]
@karlschwarz, have you tried [this](https://stackoverflow.com/a/45286781) solution? I'm sorry but your branch is 808 commits behind the main branch and I am not able to view the new diff between your commit and the new changes in the main branch. Let me know if you come across any roadblocks!

**Comment by karlschwarz** [comment]
@MarShaikh Sure, this time I will try to solve this problem following the rebase method as soon as possible.

**Comment by MarShaikh** [comment]
> Hi @MarShaikh, I used the rebase method and can you review my PR again? Please let me know if there is anything that needs to be updated. Thanks!

Can you make sure that the test-docstrings passes without error? The function you edited seems to be causing a problem.

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Can you make sure that the test-docstrings passes without error? The function you edited seems to be causing a problem.

**Comment by karlschwarz** [comment]
@MarShaikh Okay, the codes are updated and all the checks have passed. Can you review it again? Thanks.

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Could you remove the changes to test_array_api file. We shouldn't be making any changes to that repo. Plus, if you could an example of array instance method to svdvals, as there is an instance of svdvals also present in `ivy/array`. Then it would be ready to merge. Thanks!

**Comment by karlschwarz** [comment]
Yes. The change to test_array_api file is removed and also the instance examples are added. @MarShaikh

**Review by MarShaikh — APPROVED** [review]
Thanks for the update! Everything else looks perfect!

**Comment by karlschwarz** [comment]
Thanks for your review and help! @MarShaikh 

> Thanks for the update! Everything else looks perfect!

**Pull request merged**
