### PR TITLE
added stateless_categorical

### PR DESCRIPTION
**Pull request by arham-kk**
Close https://github.com/unifyai/ivy/issues/17747

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey,

For this task you need to write a test in ivy_tests so that we can check everything is working properly :)

Thanks

**Comment by arham-kk** [comment]
I've added the test in ivy_tests.

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey,

So we need to get your test passing before merging so that we are sure that the implementation is correct. I checked the logs and it seems that your test is failing [here](https://github.com/unifyai/ivy/actions/runs/5685452101/job/15410355145?pr=20860#step:3:1477).

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey, PR is doing well but it looks like tests are still failing. Just need to get them passing so we can merge :)

**Pull request closed without merging**
