### PR TITLE
implement jax.lax.scan and test

### PR DESCRIPTION
**Pull request by Ahmed-abdelgalil**
scan https://github.com/unifyai/ivy/issues/21115

### CODE REVIEW

**Comment by Ahmed-abdelgalil** [comment]
scan #21115

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Ahmed-abdelgalil** [comment]
Hi @Ishticode i hope you're well can you please review my PR.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Ahmed-abdelgalil 
Thank you very much for the PR. Please try to run the tests locally as the current ones clearly fail due to mismatching parameters. For example, `x` is being passed as an argument to `test_frontend_function` while scan does not take x. In addition several other parameters have no value passed. 
Feel free to check [deep dive on frontend tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html).

**Pull request closed without merging**
