### PR TITLE
added atanh tensor instance method and test to PaddlePaddle frontend

### LINKED ISSUE #15908: atanh

### PR DESCRIPTION
**Pull request by sachelsout**
Close #15908

### CODE REVIEW

**Comment by sachelsout** [comment]
Hello @zhumakhan , could you please review my PR ?

**Comment by sachelsout** [comment]
Hello @zhumakhan , could you please review my PR ?

**Comment by zhumakhan** [comment]
Hi, thanks for you PR! It seems you've also added `amax` method, could you please remove that? Also please resolve the conflicts. Probably then we can merge it.
Thanks!

**Comment by sachelsout** [comment]
> Hi, thanks for you PR! It seems you've also added `amax` method, could you please remove that? Also please resolve the conflicts. Probably then we can merge it. Thanks!

Sure @zhumakhan , I'll do the required changes right away !! 😃

**Comment by sachelsout** [comment]
Hi @zhumakhan , could you please review my PR ?

**Comment by sachelsout** [comment]
@zhumakhan , I tried to resolve merge conflicts and ran tests locally to which I am getting error as mentioned below 👇 
image
This cpu 'keyerror' is observed in most of the functions already implemented in different directories. Same issue was faced earlier for jax framework and the issue was resolved from Ivy's end.
So let's wait to get this resolved and then I'll resolve merge conflicts !! 😃

**Comment by sachelsout** [comment]
Hi @zhumakhan , I made some changes  in the code (updated paddle version to 2.5.0 in tensor.py function) and the test cases are passing now for atanh function ! 😃 
Update - I tried running the test cases again and it is failing for tensorflow backend, other tests are passing.
Could you please let me know what I can do to resolve this issue. Thank You !!

Here is the error screenshot - 
image

**Comment by sachelsout** [comment]
@zhumakhan , Quick update !!
After I resolved merge conflicts, I tried running test cases and all the test cases are passing now. 😄 
image

**Comment by sachelsout** [comment]
Hi @zhumakhan , could you please review my PR ? 😃

**Pull request merged**
