### PR TITLE
Added modf function in jax numpy frontend

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Close #14522

**Comment by valeriocost** [comment]
Hi @RakshitKumar04, the test is failing due to `AssertionError: the ground truth framework jax returned a float32 datatype while the backend torch returned a int8 datatype`. Does it pass locally for you?

**Comment by valeriocost** [comment]
sounds good! update here when we are ready to merge the PR then 😄

**Comment by RakshitKumar04** [comment]
@valeriocost I think we are good to go. 
LInk to numpy.modf PR : https://github.com/unifyai/ivy/pull/11680
U can check here. It got merged.

**Comment by RakshitKumar04** [comment]
Hey, @valeriocost I think the PR is ready to merge because I faced the same `AssertionError: the ground truth framework jax returned a float32 datatype while the backend numpy returned a int16 datatype` while implementing modf in NumPy frontend. The casting error seems to be in the testing side of ivy.

If I am wrong, can you please guide me on how do I resolve the error.

**Comment by valeriocost** [comment]
merging 👍🏼

**Pull request merged**
