### PR TITLE
weighted_moments

### LINKED ISSUE #15974: weighted_moments

### PR DESCRIPTION
**Pull request by usayrimrehman**
- Close #15974

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Can you revert the changes to .idea files. 
Also I noticed you haven't added the test function yet. You can ask me for a review whenever you think the PR is ready. 😄 

Thanks

**Comment by usayrimrehman** [comment]
Hey,

I'll revert the changes made to the .idea files. As for the test function, the issue I've been working on only asks for a frontend function implementation, and doesn't mention anything about implementing a test function.
Can you brief me a little about what you're looking for.

Thank you.

**Comment by usayrimrehman** [comment]
@sherry30

**Comment by sherry30** [comment]
Hi,

Writing a test for a frontend function is a must otherwise we won't know if its working as expected.
You have to use hypothesis for generating data. It is explained in great detail in the docs [here](https://github.com/unifyai/ivy/blob/2575844a75b1b748c7a972e8a977d43f0f39f831/docs/overview/deep_dive/ivy_frontends_tests.rst).
Also feel free to ask me any question if you get stuck 😄 

Thanks

**Pull request closed without merging**
