### PR TITLE
feat: added a the numpy instance method choose

### PR DESCRIPTION
**Pull request by manny-uncharted**
# PR Description
feat: added the numpy instance method: 

#23331 

Close #

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials:

[Twitter](https://twitter.com/manny_uncharted)

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by OriginCoding** [comment]
hello i am already working on this issue my PR is #23335

**Comment by manny-uncharted** [comment]
@OriginCoding that's no issue, I could pick up another task to work on

**Comment by OriginCoding** [comment]
I will inform you if it's not merged

**Pull request closed without merging**
