### PR TITLE
fixed: Bugs1

### PR DESCRIPTION
**Pull request by xPushpeshx**
tried to implement interpolate from #10696 (Experimental)
fixes issue #22033 

gathered info form -https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/interpolate_en.html#interpolate

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by AnnaTz — CHANGES_REQUESTED** [review]
Hi @xPushpeshx, currently the paddle backend test is failing as seen in the CI checks. Have you tried running the test locally? You will need to do that to debug the errors.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
