### PR TITLE
Update indexing_like_operations.py

### PR DESCRIPTION
**Pull request by robertsn808**
take #5913

### CODE REVIEW

**Comment by robertsn808** [comment]
I'm not quite sure on how to resolve this

**Comment by ogbanugot** [comment]
Hey @robertsn808 can you please add a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

**Comment by ogbanugot** [comment]
So as for the tests, you might want to take some time to go through the docs on how to write frontend tests [here](https://lets-unify.ai/ivy/deep_dive/ivy_frontends_tests.html). It's actually quite easy to follow and you can check out the tests written for already existing functions in the codebase. You can try to learn from examples and implement yours. However, if you have any follow-up questions, I'll advice you to ask a question on our [discord](https://discord.com/invite/G4aR9Q7DTN). Thanks for the effort!

**Comment by ogbanugot** [comment]
Once, you have written your test you can simply run it using the command `python3 -m pytest ivy_tests/test_ivy/path/to/test_file.py --backend 'all'`

**Comment by robertsn808** [comment]
close #5913

**Pull request closed without merging**
