### PR TITLE
initial changes to add tf.foldl to ivy's tensorflow frontend

### LINKED ISSUE #6931: [ToDo List]: Add General Functions to TensorFlow frontend
### Description

Add General Functions to TensorFlow frontend

### Task List

- [ ] sort
- [ ] argsort
- [ ] full
- [ ] ones
- [ ] zeros

### LINKED ISSUE #14972: foldl

### PR DESCRIPTION
**Pull request by FourFortyFour**
Close #14972

### CODE REVIEW

**Comment by FourFortyFour** [comment]
Hi, I am really looking for feedback about this PR. Specifically concerning the way I structured the code and if I am understanding the structure correctly. I will commit the tests soon, as I am still trying to figure out running testing, and the examples in `ivy/functional/ivy/general.py` will also be added promptly.

**Comment by zhumakhan** [comment]
Hi, thanks for you PR!
This task requires to implement frontend functions and its tests only. But, since backend for `foldl` does not exist, we need to have backend first. You can implement backend for foldl as a composition of other ivy functions OR separately for each backend in a separate pull request

**Comment by FourFortyFour** [comment]
Hi @zhumakhan, thank you for your feedback I will update the PR ASAP and shift my focus towards implementing the backend it for it as it seems #15376 has written the frontend tests for foldl and added the function to general_functions.py in the tf frontend. I'll keep an eye on that PR just incase and update mines as mentioned.

**Comment by FourFortyFour** [comment]
Hello again @zhumakhan, if you could take a look at [these](https://github.com/unifyai/ivy/compare/master...FourFortyFour:ivy:foldlbackend) changes in my forked branch where `foldl` is implemented using `reduce`. By "we need to have the backend for it first" would that mean transferring that implementation to /ivy/functional/ivy or /ivy/functional/backends/tensorflow and then just calling `ivy.foldl()` from the tensorflow frontend? I am unclear about your comments. Furthermore, I have implemented foldl using ivy functions as well but am not sure what to do with the implementation.

**Pull request closed without merging**
