### PR TITLE
add sinh to jax

### PR DESCRIPTION
**Pull request by PatricYan**
- [ ] #3086 
- add sinh to jax
- add test case

### CODE REVIEW

**Comment by PatricYan** [comment]
Hi @chie2727 , would you like to make a review for the PR?

**Comment by kimbring2** [comment]
@PatricYan Thank you for all 3 contributions. Everything looks file.

**Comment by kimbring2** [comment]
@PatricYan It seems like that previous merging triggers the conflict again

**Comment by PatricYan** [comment]
> @PatricYan It seems like that previous merging triggers the conflict again. I just fix it. Thank you for your all 3 contribution.

Ok, thank you fix the conflict,

**Comment by PatricYan** [comment]
Hi @kimbring2 , I want to discuss some questions, can I send a message to you by discord or email?

**Comment by kimbring2** [comment]
@PatricYan Yes, please send me a message on Discord (: 

My id is kimbring2#8163.

**Comment by PatricYan** [comment]
> kimbring2#8163
@kimbring2 I have sent message to you by discord

**Pull request merged**
