### PR TITLE
multinomial function is added for numpy

### PR DESCRIPTION
**Pull request by eldorabdukhamidov**

### CODE REVIEW

**Comment by ZoeCD** [comment]
Hi! Thank you for your contribution!  😊

It seems there are a couple of errors. Could you please take a look at them?

There is a `value error` happening for backends PyTorch, NumPy, and Jax. And using TensorFlow, an `InvalidArgumentError` is being raised. You can see more information about those errors in the details section of the `test frontend NumPy`.

I recommend using `ctrl + F` to find the errors quickly. 

I think the frontend implementation is correct, so maybe there is some issue with how you generate the test data.

**Comment by eldorabdukhamidov** [comment]
Close #4728

**Comment by eldorabdukhamidov** [comment]
@ZoeCD Please have a look at the PR. I think it passed the necessary checks

**Comment by ZoeCD** [comment]
Hello. Could you please update your fork to have the most recent upstream changes? It would make it easier for you and me to review your contribution. Now it looks like there are a lot of unrelated changes to your issue in this PR. I would appreciate it a lot 😄

**Comment by eldorabdukhamidov** [comment]
Hi @ZoeCD. I have some issues with the branch, which ended up being closed. I pushed the change into another PR. Sorry for the inconvenience.

**Pull request closed without merging**
