### PR TITLE
added min

### LINKED ISSUE #5826: min

### PR DESCRIPTION
**Pull request by Viditagarwal7479**
Close #5826

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by abdrahmandiab** [comment]
Hi @Viditagarwal7479 , it seems this PR has been open for quite a while, and you have not yet requested for it to be reviewed. Are you still actively working on this? or did you maybe just miss that step? 😅

**Comment by Viditagarwal7479** [comment]
> Hi @Viditagarwal7479 , it seems this PR has been open for quite a while, and you have not yet requested for it to be reviewed. Are you still actively working on this? or did you maybe just miss that step? sweat_smile

Hey @abdrahmandiab, the option to request to review only comes when the assigned gives feedback upon which I can improve. Due to excessive notification from GitHub regarding failing on tests was coming I had stopped looking at mails from GitHub so was unware of the first comment made 4 days ago.
Thanks
Vidit Agarwal

**Comment by Viditagarwal7479** [comment]
Hey @abdrahmandiab ,
I have resolved the merge conflicts. Could you kindly review it?
Thanks
Vidit Agarwal

**Comment by abdrahmandiab** [comment]
Hey @Viditagarwal7479, 
Apologies for the late review, and thank you so much for your work! 
As the instance method tests are currently being skipped due to some maintenance from our side, we'll be merging the PR and you can move ahead with your application!

Thank you, and good luck!

**Pull request merged**
