### PR TITLE
feat: add torch.combinations to torch frontend

### LINKED ISSUE #23508: combinations

### PR DESCRIPTION
**Pull request by CanKeles5**
# PR Description

## Related Issue

Close #23508

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by RickSanchezStoic** [comment]
@CanKeles5 kindly go through the `intelligent-tests-pr / run_tests (1) (pull_request) ` and resolve the failures occurring in the    test_torch_combinations

**Comment by CanKeles5** [comment]
@RickSanchezStoic Hi. I think the issue is fixed now. Sorry for the late update.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
