### PR TITLE
Jax numpy size

### PR DESCRIPTION
**Pull request by VictorOdede**

### CODE REVIEW

**Comment by VictorOdede** [comment]
Close #14769

**Comment by vaatsalya123** [comment]
Hey @VictorOdede  ,Even though the implementation seems correct for the function the testing logic seems super simple , I would suggest you make the test code a bit more rigors so we can properly test this function, Thanks!

**Comment by VictorOdede** [comment]
Thanks @vaatsalya123. What approach would you suggest to make the tests more rigorous?

**Comment by vaatsalya123** [comment]
This looks fine @VictorOdede will merge , Thanks alot!

**Pull request merged**
