### PR TITLE
Pytorch Frontend: is_tensor function

### PR DESCRIPTION
**Pull request by Avinashpathapati**
This PR adds the is_tensor function to the Pytorch Frontend, related to the issue https://github.com/unifyai/ivy/issues/2865.

This is one of sub-tasks https://github.com/unifyai/ivy/issues/7

### CODE REVIEW

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Took a look at the code, for the backends, it is best to not include `is_tensor` for all the backends as Ivy already supports `is_array` function that will check for all the functions. Would recommend removing all the function instances from the backends as well as Ivy and just replacing the call in func `is_tensor` with `ivy.is_array` instead of `ivy.is_tensor`. Thanks, request for a review and I'll take a look again!

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Sorry for the delayed review. Could you fix the error in the `test-frontends-torch`? As well as fix the lint error. Would recommend using `pre-commit`(you can find more info in our docs) to fix linting errors! Thanks.

**Comment by Avinashpathapati** [comment]
@MarShaikh this is a gentle reminder for reviewing the PR as I made the requested changes.

**Review by MarShaikh — APPROVED** [review]
LGTM!

**Pull request merged**
