### PR TITLE
Implementation of `ivy.std` function & integration testing

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Hello,
This PR aims to implement the `ivy.std` functionality along with some basic integration testing. According to my knowledge, all instances of `reduce_std` have been changed to `std`. 
Implements #98 

Thanks 😄

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by DhruvSondhi** [comment]
Hello @djl11,
I have given you the rights for editing this PR. I could also `rebase` the PR if needed 😄

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Review by djl11 — CHANGES_REQUESTED** [review]
Please reformat the code as describe in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/), and also as explained in this [YouTube series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl).

**Comment by DhruvSondhi** [comment]
Hello @djl11,
I am running late a bit on my todo list. I will surely do the needful with this PR & get it ready for merging. Please bear with me at the moment 😅

**Comment by DhruvSondhi** [comment]
Hey @djl11, It seems so that my PR adheres to the code formatting standards for **Ivy**. Please do let me know if something else needs to be done to make this PR upto the mark 🤔

**Comment by 1Doomdie1** [comment]
This PR is being closed because there was no activity on this PR in the last 7 days, and you have not requested a code review from us. Please check our policy on the closing of PRs which are linked to ToDo list issues [here](https://lets-unify.ai/ivy/contributing.html#todo-list-issues), please reach out on discord if you believe this issue has been closed mistakenly, and we’d be very happy to help 🙂

**Comment by DhruvSondhi** [comment]
Can you please review this change? I was expecting an answer from @djl11 for moving forward. I assume I have implemented the correct method with the right code formatting.

**Comment by 1Doomdie1** [comment]
@DhruvSondhi We've reopen the PR and Issue. We apologies for any inconvenience created.
Going forward can you please request a code review  from the assigned member?
Thank you!

**Review by djl11 — CHANGES_REQUESTED** [review]
Hi! Yes very sorry for the confusion caused. Please could you fix the conflicts and then un-comment the std method under ivy_tests/array_api_methods_to_test?

Also, the method will need to be in the file ivy/functional/ivy/statistical.py and the same goes for each backend method.

Once these changes are added, please request another review and I'll take a look :)
Thanks!

**Pull request closed without merging**
