### PR TITLE
expm1 Adhering to Array API Standards

### PR DESCRIPTION
**Pull request by tayoshittu**

### CODE REVIEW

**Comment by tayoshittu** [comment]
hi, i managed to do as you asked, but im still failing one test the "run nightly tests" after i re-ran my updated files. Please how do i proceed? thank you for your help

**Comment by Ishticode** [comment]
> hi, i managed to do as you asked, but im still failing one test the "run nightly tests" after i re-ran my updated files. Please how do i proceed? thank you for your help

Hi great work : ). The failure in nightly tests was not caused by your function. Will be merging soon.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @tayoshittu.  It turns out you had forgotten to uncomment your function for tests - which I have done now anyway. Now the tests show that you somehow forgotten to implement the function in the numpy backend therefore numpy test is failing. Adding this should solve this. Rest is fine : )

**Review by Ishticode — APPROVED** [review]
Great

**Pull request merged**
