### PR TITLE
Grammatical errors in tests

### LINKED ISSUE #9178: Grammatical errors in ivy_tests.rst

### PR DESCRIPTION
**Pull request by jaygala223**
Fixes #9178 

Fixed minor grammatical errors I found in "ivy_tests.rst" while referring to the docs

### CODE REVIEW

**Comment by jaygala223** [comment]
Hello @WilliamHirst, some of the checks are failing on files that I haven't edited in this commit. Please advise on the next steps

**Comment by WilliamHirst** [comment]
Hi Jay,
Thanks for finding the grammatical errors!

It seems as though you are additionally pushing the commit for a FE-function. Can you remove this commit and only push the grammatical fixes?
Thanks, William

**Comment by jaygala223** [comment]
Yes, I did that by mistake. I will push the grammatical fixes in a bit

**Comment by jaygala223** [comment]
is the last commit good? or should I create another PR by closing this one?

**Comment by WilliamHirst** [comment]
So currently the other changes are still connected to this PR. You can either create another PR, or just revert (or simply delete) the changes made to the other files.

**Comment by jaygala223** [comment]
I created another PR #9198  
Will close this PR now

**Pull request closed without merging**
