### PR TITLE
Paddle paddle

### PR DESCRIPTION
**Pull request by mosesdaudu001**
added statistical function quantile to the backend experimental paddlepaddle.

### CODE REVIEW

**Comment by MahmoudAshraf97** [comment]
please in the next PRs write the issue number so we can track it, for example: closes #10932

**Comment by mosesdaudu001** [comment]
> please in the next PRs write the issue number so we can track it, for example: closes #10932

okay, I will do that for next PRs. Sorry for the mixup

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
please do not change the function arguments as they are standard across all backends, also find a method to implement interpolation argument since paddle doesn't natively support it

**Comment by mosesdaudu001** [comment]
Hello Mahmoud, I am a little bit confused as to how I should proceed. All other backends natively support the interpolation argument except paddle. Do I add the interpolation argument to the backends.paddle.experimental.statistical quantile function, which would mean tampering with the function arguments? pls how do I proceed.

**Pull request closed without merging**
