### PR TITLE
Refactoring data classes to `data_classes` submodule

### PR DESCRIPTION
**Pull request by KareemMAX**

### CODE REVIEW

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hey @KareemMAX, we should be refactoring to `data_classes` instead of `array_classes`. Thanks 🙂

**Comment by KareemMAX** [comment]
@VedPatwardhan I have renamed the submodule, please take a look whenever you can ❤

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Great, thanks for making the changes @KareemMAX, could you please also move `nested_array` inside `data_classes` (Given that it's a data class as well)? Thanks 🙂

**Comment by KareemMAX** [comment]
@VedPatwardhan I talked with @sherry30 about that, he asked me not to as he still have work to do regarding the `nested_array`, I coordinated with @saeedashrraf to split refactoring the `nested_array` to another trello task

**Review by VedPatwardhan — APPROVED** [review]
lgtm! I'll merge the PR now, thanks @KareemMAX and @CatB1t 🙂

**Pull request merged**
