### PR TITLE
feat: added cholesky_solve function to paddle tensor class

### LINKED ISSUE #26270: cholesky_solve

### PR DESCRIPTION
**Pull request by arshPratap**
# PR Description
Added cholesky_solve function to paddle tensor class

## Related Issue

Close #26270 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by arshPratap** [comment]
Hi @bipinKrishnan .. could you take a look ?

**Comment by arshPratap** [comment]
@bipinKrishnan could you take a look ?

**Comment by bipinKrishnan** [comment]
Hey @arshPratap, thanks for the contribution. Seems like the CI didn't pick up the new test you've added. Can you try rebasing on top of the main branch?

**Comment by arshPratap** [comment]
> Hey @arshPratap, thanks for the contribution. Seems like the CI didn't pick up the new test you've added. Can you try rebasing on top of the main branch?

Hey @bipinKrishnan .. have rebased the code..but the CI is not picking up the test

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @arshPratap 
Could you pls resolve conflicts and we will see whether ci will pickup on the test. Thanks

**Comment by Ishticode** [comment]
ive resolved the conflicts anyway. lets wait on ci

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
