### PR TITLE
addr_

### LINKED ISSUE #15859: addr_

### PR DESCRIPTION
**Pull request by a00ayad00**
Close #15859

### CODE REVIEW

**Comment by a00ayad00** [comment]
Hey @nathzi1505 
I had an error on my local test bellow and I can't understand it !!

ImportError while loading conftest 'C:\Users\EL-Huda\ivy\ivy_tests\test_ivy\conftest.py'.
ivy_tests\test_ivy\__init__.py:1: in <module>
    from .. import config
E   ImportError: cannot import name 'config' from 'ivy_tests' (C:\Users\EL-Huda\ivy\ivy_tests\__init__.py)

help me !

**Comment by nathzi1505** [comment]
Hi @a00ayad00, not quite sure about Windows system tbh.
Can you take a clean clone of the repository and try again?

**Comment by a00ayad00** [comment]
@nathzi1505 I already did that and I start from the beginning, but the same problem happens.

**Comment by nathzi1505** [comment]
Not quite sure how I can help. There seems to be a problem with the imports.
@Ishticode can you look at this problem as I understand your main system is Windows based?

**Comment by a00ayad00** [comment]
@nathzi1505 But the main issue is that I don't understand where are the error cuz I just implemented the same function that was merged already. Do you understand me ?!

**Comment by a00ayad00** [comment]
> Hi @a00ayad00, not quite sure about Windows system tbh. Can you take a clean clone of the repository and try again?

@nathzi1505 I already did that and I start from the beginning, but the same problem happens.

**Comment by a00ayad00** [comment]
> > Hi @a00ayad00, not quite sure about Windows system tbh. Can you take a clean clone of the repository and try again?
> 
> @nathzi1505 I already did that and I start from the beginning, but the same problem happens.

@nathzi1505 But the main issue is that I don't understand where are the error cuz I just implemented the same function that was merged already. Do you understand me ?!

**Comment by a00ayad00** [comment]
> Not quite sure how I can help. There seems to be a problem with the imports. @Ishticode can you look at this problem as I understand your main system is Windows based?

Yes, windows 11.
But I implemented many function successfully and I don't know what happened this time !!

**Comment by Ishticode** [comment]
> Not quite sure how I can help. There seems to be a problem with the imports. @Ishticode can you look at this problem as I understand your main system is Windows based?

Hi @nathzi1505 
Ive been on linux for a while now so not sure i could help much with windows related issue. I can take a look anyways perhaps tomorrow.

**Review by Ishticode — APPROVED** [review]
I've made a push and fixed the test. The config related test is specific to you local setup @a00ayad00
I have updated the sig according to https://pytorch.org/docs/stable/generated/torch.Tensor.addr_.html and ensured test is passing. Previously kw args were being passed which the method did not even have. 
LGTM but @nathzi1505 Feel free to merge when you think everythings in order.
Thanks.

**Comment by a00ayad00** [comment]
> I've made a push and fixed the test. The config related test is specific to you local setup @a00ayad00 I have updated the sig according to https://pytorch.org/docs/stable/generated/torch.Tensor.addr_.html and ensured test is passing. Previously kw args were being passed which the method did not even have.
> 
> LGTM but @nathzi1505 Feel free to merge when you think everythings in order. Thanks.

But I just implemented that like the other functions, they didn't pass the kws at all !!!
Maybe there is, all the functions I saw didn't pass their kws !! 

But any way, I would like to thank you very much @Ishticode 💚❤️🌹

**Comment by a00ayad00** [comment]
You can merge that too cuz you are assigned to me too @Ishticode 
Anyone who see this comment before the other, you can merge the commit 😅 @nathzi1505

**Pull request merged**
