### PR TITLE
Add: one_hot + tests

### PR DESCRIPTION
**Pull request by Kranium2002**
Completed sub task in #6931

Added one_hot in general_function.py with following tasks:

-   Written test for one_hot in test_general_function.py 
-  Written function for one_hot

Function tree: tensorflow.one_hot

### CODE REVIEW

**Comment by Kranium2002** [comment]
@vaatsalya123 can you help me with some tests as tests for tensorflow, jax and numpy are failing because they don't support certain datatypes.

Error: tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'TI' of uint64 is not in the list of allowed values: uint8, int32, int64

This same error is there for all three. This is a backend error, please advise on what steps to take.

**Comment by Kranium2002** [comment]
All test cases passed

**Comment by vaatsalya123** [comment]
Hey @Kranium2002 first of all thanks for making the PR and sorry for the delayed response , Just had a look through your PR and mostly look's good to me just wanted to confirm are the issues you were facing resolved or are you still facing the issue? If the issues is no longer there the rest of the PR look's good!

**Comment by Kranium2002** [comment]
Hi, there are no current issues from my side. My code is passing all the tests which I have written. Some GitHub actions are failing due to someone else's code.

**Comment by vaatsalya123** [comment]
lgtm!

**Pull request merged**
