### PR TITLE
Argpartition to sort.py

### LINKED ISSUE #20880: argpartition

### PR DESCRIPTION
**Pull request by JoshOlam**
Close #20880

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by pillarxyz** [comment]
you need to also write the test associated with the frontend function and make sure the test passes

**Review by AryanSharma21 — COMMENTED** [review]
Hey,  @JoshOlam , while you have done the function implementation, you should also add the test for this particular function in the corresponding test file.

/workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_sorting.py

so that you can check if the function is working properly . .

**Comment by JoshOlam** [comment]
> Hey, @JoshOlam , while you have done the function implementation, you should also add the test for this particular function in the corresponding test file.
> 
> /workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_sorting.py
> 
> so that you can check if the function is working properly . .

Sure, @AryanSharma21 . I have only started working on the API and will add the test once I'm done with the implementation.

Thanks.

**Pull request closed without merging**
