### PR TITLE
abs tensorflow

### LINKED ISSUE #4662: abs

### PR DESCRIPTION
**Pull request by Aditya-Komaravolu**
Close #4662

### CODE REVIEW

**Comment by Aditya-Komaravolu** [comment]
Closes #4662

**Comment by Aditya-Komaravolu** [comment]
@RashulChutani can you please review the code?

**Comment by RashulChutani** [comment]
Hi @Aditya-Komaravolu I will do that soon.

**Comment by Aditya-Komaravolu** [comment]
> Hi @Aditya-Komaravolu I will do that soon.

Thank you so much! I have one doubt brother. I didn't understand why the frontend test failed, I checked logs, and I didn't find an error related to `abs` function.

**Comment by Aditya-Komaravolu** [comment]
@RashulChutani, as per a small discussion with James today, I have also added the instance of the method in the Tensor class. If you don't mind, by when can I expect a review from your end? So that we can fix things and hopefully merge the PR.

**Comment by RashulChutani** [comment]
Hi @Aditya-Komaravolu, It usually takes us 2-3 days, but I will try my best to do it ASAP.

**Comment by Aditya-Komaravolu** [comment]
> Hi @Aditya-Komaravolu, It usually takes us 2-3 days, but I will try my best to do it ASAP. 

Sure brother! Will be definitely waiting for your review😃.

**Comment by Aditya-Komaravolu** [comment]
> Hi @Aditya-Komaravolu, It usually takes us 2-3 days, but I will try my best to do it ASAP. 

Sure brother! Will be definitely waiting for your review😃.

**Comment by Aditya-Komaravolu** [comment]
> Hi @Aditya-Komaravolu, It usually takes us 2-3 days, but I will try my best to do it ASAP. 

Sure brother! Will be definitely waiting for your review😃.

**Comment by Aditya-Komaravolu** [comment]
@RashulChutani I have made changes to the test functions and they ran perfectly in local testing. Could you please review them?

**Comment by RashulChutani** [comment]
@Aditya-Komaravolu Please also check that the CI Tests Pass.

**Comment by Aditya-Komaravolu** [comment]
> @Aditya-Komaravolu Please also check that the CI Tests Pass.

Yep, the test cases passed for my both test functions as stated here:
screenshot_1

screenshot_2

**Comment by RashulChutani** [comment]
Sure. I will review soon. Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
