### PR TITLE
Add local_response_normalization for TensorFlow frontend (#6704)

### PR DESCRIPTION
**Pull request by mohamedehab0999**

### CODE REVIEW

**Comment by Aarsh2001** [comment]
Hi @mohamedehab0999, have you tried running the test for this function locally?

**Comment by mohamedehab0999** [comment]
Yes, the Test Passed [100%]

**Comment by Aarsh2001** [comment]
Can you try reproducing the failures on the CI in your local machine? Just add the decorator `reproduce_failure` in the test. Information on the failures is available in the logs. Meanwhile I'll check the test logs as well, thanks 🙂

**Comment by Aarsh2001** [comment]
Hey @mohamedehab0999, we just had a refactor inside the testing suite. Can you please pull the latest changes and add the `handle_frontend_test` decorator instead of `handle_cmd_line_args`, as implemented for the other functions.

**Comment by mohamedehab0999** [comment]
1. When i try reproducing the failures earlier, `The shape of the test data has changed in some way from where this blob was defined` message appears and i see that the generated array was 2-D not 4-D as the function need.
2. The new decorator `handle_frontend_test` raises a failer in both GitHub and local machine

**Comment by mohamedehab0999** [comment]
I committed my latest changes and modified the decorator on the test file to be `handle_frontend_test` instead of `handle_cmd_line_args`.

**Comment by mohamedehab0999** [comment]
Close #6765

**Comment by Aarsh2001** [comment]
Hey @mohamedehab0999 , fn_tree should be `fn_tree="tensorflow.nn.local_response_normalization"`, the tests should then pass hopefully.

**Comment by mohamedehab0999** [comment]
Done @Aarsh2001

**Comment by Aarsh2001** [comment]
Add `fn_tree` as a keyword argument in the test function

**Comment by mohamedehab0999** [comment]
`ivy.pow` was running normally when testing on my local machine with the old decorator. I think this error might cause because of version changes on NumPy or TensorFlow.

**Comment by Aarsh2001** [comment]
The test are passing for the function now, thanks for your contribution @mohamedehab0999 🙂

**Comment by mohamedehab0999** [comment]
Thanks @Aarsh2001,  I just Fixed lint formatting for the function and asking you for a merge.

**Comment by mohamedehab0999** [comment]
Thanks ! 🙂

**Pull request merged**
