### PR TITLE
Fix ground truth backend flag in tests

### PR DESCRIPTION
**Pull request by shubham1206agra**

### CODE REVIEW

**Comment by AnnaTz** [comment]
Hi @shubham1206agra, looks good! Should we merge or are you to make more changes?

**Comment by shubham1206agra** [comment]
> Hi @shubham1206agra, looks good! Should we merge or are you to make more changes?

@AnnaTz Now you can merge

**Comment by shubham1206agra** [comment]
@AnnaTz Can you see other tests which are failing due to incorrect mapping?

**Comment by AnnaTz** [comment]
> @AnnaTz Can you see other tests which are failing due to incorrect mapping?

Can't think of an easy way to get all tests with this failure. Let me know if you would like to look into this more. Otherwise the PR is good.

**Comment by shubham1206agra** [comment]
Just merge this PR. I will put the list of incorrect mapping in another issue

**Pull request merged**
