### PR TITLE
Add isclose for jax frontend 

### LINKED ISSUE #9902: isclose

### PR DESCRIPTION
**Pull request by adityagandhamal**
Close #9902 
Implemented and tested isclose() frontend functionality for jax.numpy

### CODE REVIEW

**Comment by adityagandhamal** [comment]
@vaatsalya123 
Could you please review this?

**Comment by vaatsalya123** [comment]
@adityagandhamal Sorry for the delayed response to to the PR just went through it mostly looks good to me!

Just one quick thing to fix would be to resolve some of the lint failures caused by the PR like adding new lines to to the end of the file.Once these are resolved we can get your PR merged thanks!

**Comment by adityagandhamal** [comment]
Thanks for responding @vaatsalya123 !

I've gone through the code again and tried fixing the linter issues. 
Seems like the new test failures are caused because of some other parts irrespective of mine.
Could you please infer the same?

**Comment by vaatsalya123** [comment]
lgtm!

**Pull request merged**
