### PR TITLE
shortend minkowski funtion

### PR DESCRIPTION
**Pull request by raj921**

### CODE REVIEW

**Comment by raj921** [comment]
#14961

**Comment by RickSanchezStoic** [comment]
@raj921 Can you please try elaborating a bit on what issues this fixes and what exact changes you have made? Thanks!

**Comment by raj921** [comment]
I reduced this code 17 loc to 8 loc  removing extra variables in the last line and directly returning the result and writing and reducing conditional loop in one line to remove extra eilf statement

**Comment by RickSanchezStoic** [comment]
@raj921 seems like you have made too many changes to other files too which were probably not needed. Can you look into that and make sure that only the required file which I believe is `distance.py` gets changed? Thanks!

**Comment by raj921** [comment]
yes i already deleted very file i changed expect distance.py

**Comment by RickSanchezStoic** [comment]
Hey, @raj921 that's not exactly how it works. If you delete those files, they will be deleted from the repo too. What you can do is copy and save the changes that you have made (I guess in `distance.py` ) to somewhere else and then make a fresh clone from ivy and then create a new pr. Make sure that you add only those files that you have made changes to while making a commit. using `git add filename` . Let me know if you have any doubts.

**Pull request closed without merging**
