### PR TITLE
Update torch.test_reduction_ops.test_torch_norm to support the testing of the dtype parameter

### PR DESCRIPTION
**Pull request by fabriziocacicia**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by fabriziocacicia** [comment]
@Aarsh2001 I asked you to review since you was the reviewers of the last PR regarding `test_torch_norm`.

I saw that the `dtype` parameter of `torch.norm` was not tested so I edited the `_get_axis_and_p` to handle the generation of proper values of the `dtype` parameter according to the `torch` docs specifications.

I also edited the decorator of `torch.norm` since in the pytorch docs it's clearly stated that the function accepts only `float` and `complex` values ([see input parameter description](https://pytorch.org/docs/stable/generated/torch.norm.html#torch.norm)), then I replaced the `with_unsupported_dtypes`decoretor with a `with_supported_dtypes` declaring only the correct ones.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Aarsh2001 — APPROVED** [review]
My apologies for the late response, this PR looks good to me 🙂

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request merged**
