### PR TITLE
Cholesky

### PR DESCRIPTION
**Pull request by Eng-Abdelrahman-M**
Remove Cholesky function from core and backends.
Added Cholessky to API array to ivy and backends.

The test fails because it needs the ivy.eye functions, should I work on it too?

### CODE REVIEW

**Review by 1Doomdie1 — APPROVED** [review]
Thank you for contributing.
Everything looks fantastic!
Please standby while Dan will merge this PR

**Comment by djl11** [comment]
Someone is working on eye right now, we will get this merged as soon as the eye PR is accepted!

**Review by djl11 — COMMENTED** [review]
Someone is working on eye right now, we will get this merged as soon as the eye PR is accepted!

**Comment by Eng-Abdelrahman-M** [comment]
I want to fetch upstream and continue working on Cholesky.  It was depending on eye #323 that it has been merged.

**Review by djl11 — CHANGES_REQUESTED** [review]
Could you try and resolve the conflicts? Then we can see if the CI tests are passing :)

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Comment by Eng-Abdelrahman-M** [comment]
Thanks!

**Comment by Eng-Abdelrahman-M** [comment]
Sorry, this [function ](https://github.com/unifyai/ivy/blob/9eadefb62dc710a62fb8dbaded7c40c3df6b6a10/ivy/functional/ivy/linear_algebra.py#L199)needs to be deleted. 
it is implemented [here](https://github.com/unifyai/ivy/blob/9eadefb62dc710a62fb8dbaded7c40c3df6b6a10/ivy/functional/ivy/linear_algebra.py#L369).

**Pull request merged**
