### PR TITLE
Added ifft2 below Add Discrete Fourier Transform functions to Numpy F…

### PR DESCRIPTION
**Pull request by IsaiJimenezTalonia**
…rontend #1532

# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by IsaiJimenezTalonia** [comment]
Open ISSUE: https://github.com/unifyai/ivy/issues/1532

**Comment by bipinKrishnan** [comment]
Hey @IsaiJimenezTalonia , seems like the issue you mentioned in the PR description is the main to-do list. Can you please link the correct issue you raised for the PR by adding "Closes #<issue id>" in your PR description? You could refer to [this section](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) of the docs.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
