### PR TITLE
added paddle frontend cumsum function

### LINKED ISSUE #23092: cumsum

### PR DESCRIPTION
**Pull request by JeffreyJu8**
# PR Description 

## Related Issue 

Close #23092

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by JeffreyJu8** [comment]
close #23092

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by JeffreyJu8** [comment]
All tests related to cumsum has passed.

**Comment by JeffreyJu8** [comment]
For some reason the sub issue is not linked to the main issue #15039. Can somebody take a look?

**Comment by JeffreyJu8** [comment]
It seems like some functions other than mine in this file is having syntax errors

**Pull request closed without merging**
