### PR TITLE
Adding complex dtypes to numeric

### PR DESCRIPTION
**Pull request by Fayad-Alman**
- Adding complex dtype to valid numeric types as complex dtype checking is now complete
- Fixing tests to ensure that complex dtypes are accepted as input

### CODE REVIEW

**Comment by Fayad-Alman** [comment]
@VedPatwardhan Just a heads up that I'll be working on this, I'll let you know when I'm done

**Comment by VedPatwardhan** [comment]
Sounds good! Thanks @Fayad-Alman 🙂

**Comment by VedPatwardhan** [comment]
Could you please add your changes to a branch on your fork rather than creating a branch on the main repo? Just to keep things clean on the main one. Thanks 🙂

**Comment by Fayad-Alman** [comment]
Hi @VedPatwardhan, I've deleted the branch and made a new PR for this task: #12623
I'll let you know when I'm finished

**Pull request closed without merging**
