### PR TITLE
Close #15489

### LINKED ISSUE #15489: asinh

### PR DESCRIPTION
**Pull request by TheGreatShubham**

### CODE REVIEW

**Comment by soma2000-lang** [comment]
Hi @TheGreatShubham thanks for contributing to ivy.Can you please link the issue number?

**Comment by TheGreatShubham** [comment]
Hi @soma2000-lang sorry I am not sure if I know how to do it. can you please walk me through this?

**Comment by soma2000-lang** [comment]
@TheGreatShubham Please follow https://unify.ai/docs/ivy/overview/contributing/the_basics.html#the-basics

**Comment by TheGreatShubham** [comment]
Close #15489

**Pull request closed without merging**
