### PR TITLE
add mean_squared_logarithmic_error

### PR DESCRIPTION
**Pull request by rahulsnkr**
Resolves https://github.com/unifyai/ivy/issues/3083

### CODE REVIEW

**Comment by rahulsnkr** [comment]
@MarShaikh I don't have permission to request a review, so tagging you here instead

**Comment by RickSanchezStoic** [comment]
Hi @rahulsnkr can you try resolving the merge conflicts?

**Comment by rahulsnkr** [comment]
> Hi @rahulsnkr can you try resolving the merge conflicts?

@RickSanchezStoic updated!

**Comment by kimbring2** [comment]
@rahulsnkr Thank you, works well (:

**Pull request merged**
