### PR TITLE
Add bernoulli for jax frontend

### LINKED ISSUE #11083: bernoulli

### PR DESCRIPTION
**Pull request by xingyu-long**
Close #11083

### CODE REVIEW

**Comment by xingyu-long** [comment]
Hi, @WilliamHirst, can you take a look for this PR? thanks

**Comment by WilliamHirst** [comment]
Hi!
Due to some internal work on the Ivy repo, your PR seems to be running into some conflict. To fix this, please follow the instruction made by Dan last week on the Ivy Discord on how to "reset".

If you have any questions, let me know! 😊

**Comment by xingyu-long** [comment]
@WilliamHirst  Thanks for the reminder! Just reset the master with upstream, right now, it should be good to review. Thanks!

**Comment by WilliamHirst** [comment]
Great job!

There seems to be a couple of failing tests related to your commit. Change them out in the "run_tests_1" and lint logs.

Let me know when these are fixed or if you have any questions 😊

**Comment by xingyu-long** [comment]
@WilliamHirst, I have a question about this function, so from jax.random.bernoulli, it will return an Array of Booleans but for the other framework, they return Arrays of Integer (1, or 0). so should I limit this test to jax only?

**Comment by xingyu-long** [comment]
Just rebased with latest branch to resolve conflicts. I will need some time to consult the potential solution in discord channel.

**Comment by WilliamHirst** [comment]
Nice! Let me know when this is done 😊

**Comment by xingyu-long** [comment]
Additional comment for this:
Because this has a dependency on PRNGKey and we will close it for now.

**Pull request closed without merging**
