### PR TITLE
test(PyThorch-frontend): Added the support for testing methods that performs inplace operation by default like `add_`

### PR DESCRIPTION
**Pull request by hirwa-nshuti**
Hey @sherry30 

This PR adds the testing for methods that perform inplace operations directly like `torch.tensor.add_`. The testing is implemented such that we ensure that the instance of the frontend return is the input one updated.

Also on this PR, I made a refactor for alias methods which were redefined instead of being referenced to their aliases.
Thanks

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by sherry30 — CHANGES_REQUESTED** [review]
Looks good.
Can you also update the paddle frontend with this since it also has methods which inplace updates arrays, also updating the docs would be nice stating that we should add `test_inplace=st.just(True)` for frontend methods which inplace updates the array.
Will also request a review from @AnnaTz for the frontend changes.

Thanks Felix

**Review by AnnaTz — APPROVED** [review]
Looks good!

**Pull request merged**
