### PR TITLE
#3345 : Added floor function in numpy frontend

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Hey, @agniiyer can you guide me and help in passing the checks

**Comment by RakshitKumar04** [comment]
Hey, @agniiyer I have updated the code, can you please review my PR.

**Comment by RakshitKumar04** [comment]
hey, @agniiyer please review my PR.

**Comment by RakshitKumar04** [comment]
Close #12085

**Comment by RakshitKumar04** [comment]
Hwy, @agniiyer Please review my PR.

**Comment by agniiyer** [comment]
Hey can you check if the tests are passing again? :)

**Comment by RakshitKumar04** [comment]
> 

Created the new PR. Please review it.
Here is the link too
https://github.com/unifyai/ivy/pull/12948

**Pull request closed without merging**
