### PR TITLE
Adding multiple Pointwise Ops to pytorch frontend

### PR DESCRIPTION
**Pull request by KevinUnadkat**
doing multiple subtask  from Pointwise Ops and adding them to pytorch frontend

### CODE REVIEW

**Comment by KevinUnadkat** [comment]
hy @WilliamHirst 
pls review this file it is mostly ready to merge

**Comment by WilliamHirst** [comment]
Hi Kevin!
The contribution looks great. There just seems to be a formatting error in the test function.

**Comment by KevinUnadkat** [comment]
> Hi Kevin!
> The contribution looks great. There just seems to be a formatting error in the test function.

Ya but the error says there is no new line at the end of the file but actually there is a line

**Comment by WilliamHirst** [comment]
Yes I agree the comment is a bit misleading, but there should not in fact be a new line at the end of the file.

**Comment by WilliamHirst** [comment]
Hi Kevin, 
All functions seem to be implemented correctly and are not failing any test. But, there is a merge conflict related to your commit. Please fix this and we can merge your changes 👍

**Comment by WilliamHirst** [comment]
Additionally you have not linked the PR correctly to the issues. They should be highlighted in the "Development" section on the right side of the PR. Check out the docs on how to do this: https://lets-unify.ai/ivy/contributing/the_basics.html#the-basics

**Pull request closed without merging**
