### PR TITLE
atan

### PR DESCRIPTION
**Pull request by SethiAbhinav**

### CODE REVIEW

**Comment by SethiAbhinav** [comment]
Hi @nathzi1505 I am new to open source, please review the PR and let me know if there are any changes to be made.

**Comment by SethiAbhinav** [comment]
@nathzi1505 You may have missed my PR, please look at it when you are free.

**Comment by nathzi1505** [comment]
Hi @SethiAbhinav, I see there are some merge conflicts. Can you please look at them and resolve.
Thanks :D

**Comment by SethiAbhinav** [comment]
Hi @nathzi1505, I had actually deleted the fork and so lost my branch, and didn't understand how to go ahead with the changes in that case. Could you please refer to #11740 and merge it if it looks good?

**Pull request closed without merging**
