### PR TITLE
make changes to range function to short frontend

### PR DESCRIPTION
**Pull request by 01PrathamS**

### CODE REVIEW

**Comment by satakshigarg** [comment]
Hey @01PrathamS, thanks you for the PR. Your contributions to our organisation mean a lot. 
The PR looks good to me !
Good luck for your future contributions.

**Comment by 01PrathamS** [comment]
hey @satakshigarg if  you don't mind, can you help me to do setup, i tried everything from docs, ask for help in discord multiple times nothing works, i tried with vscode + docker and pycharm + docker for testing.

**Comment by satakshigarg** [comment]
> hey @satakshigarg if you don't mind, can you help me to do setup, i tried everything from docs, ask for help in discord multiple times nothing works, i tried with vscode + docker and pycharm + docker for testing.

Sure @01PrathamS 
Have you tried to [set up](https://lets-unify.ai/ivy/overview/contributing/setting_up.html#pre-commit) pre-commit in your local environment and tried [running](https://lets-unify.ai/ivy/overview/deep_dive/formatting.html#pre-commit-hook) these lint and formatting checks. Please try it, in case you feel stuck anywhere, feel free to ping me.

**Comment by 01PrathamS** [comment]
hey @satakshigarg i tried, but when i setup ivy locally with docker it showing some or the other error, i think i needed your help, i tried both the way as per docs, please look at the screen shot or if you don't mind i can share my screen , thank you for helping me .

Screenshot (2)
Screenshot (3)
Screenshot (4)
Screenshot (5)
Screenshot (6)
Screenshot (7)
Screenshot (8)
Screenshot (9)

**Pull request merged**
