### PR TITLE
is_quantized added to torch.frontend

### LINKED ISSUE #16508: is_quantized

### PR DESCRIPTION
**Pull request by andrewhinh**
Close #16508

### CODE REVIEW

**Comment by andrewhinh** [comment]
add_frontend_checklist_Tensor

**Comment by andrewhinh** [comment]
@khushi-411 How does this look?

**Comment by khushi-411** [comment]
Hi, @andrewhinh! Thanks for the PR. LGTM. But there's a problem with the CI; none of the newly added tests are running. So, I'd like to wait a bit for it.
#### Here's the CI output:
```python
Found matching commit hash in current repository: 823b56698f9eddece90d203b51627416b26a404f
Reference Commit:  823b56698f9eddece90d203b51627416b26a[40](https://github.com/unifyai/ivy/actions/runs/5245772721/jobs/9473688460?pr=16586#step:3:41)4f
----- Determined Tests -----
0
----------------------------
```

**Comment by andrewhinh** [comment]
@khushi-411 All good, thanks!

**Comment by khushi-411** [comment]
Hi, Andrew! Could you please update the branch to check the tests? Thanks!

**Comment by khushi-411** [comment]
I agree, @andrewhinh! Those were base failures. Could you rebase it? I'll merge it, then. Thanks for your patience.

**Comment by andrewhinh** [comment]
@khushi-411 Thanks for the clarification. I rebased it, should be good to go.

**Review by khushi-411 — APPROVED** [review]
LGTM! Thanks for the PR :)

**Pull request merged**
