### PR TITLE
Implement max_unpool2d

### LINKED ISSUE #19761: max_unpool2d

### LINKED ISSUE #21762: max_unpool2d
#3856

### PR DESCRIPTION
**Pull request by weronikazak**
Close #19761
Close #21762

### CODE REVIEW

**Comment by weronikazak** [comment]
@theRealBird

**Comment by theRealBird** [comment]
Hello @weronikazak, great to see you pick this up again! Apologies for the inconvenience. 
Thanks again!

**Comment by theRealBird** [comment]
Sure thing @weronikazak,
Let me know what I can help you out with :)

**Comment by Ishticode** [comment]
Closing due to lack of activity for over 6 months. Although this is marked as draft. Please feel free to reopen if you would like to continue work on this. You would need to add the test for the backends too as well as their corresponding implementation. Caliing current_backend.max_unpool2d would only be possible if there were implemented initially. 
But anyways let us know if you reopen and add these few things. Thank you very much :)

**Pull request closed without merging**
