### PR TITLE
add max to numpy in matrix

### LINKED ISSUE #4589: max

### PR DESCRIPTION
**Pull request by PatricYan**
Close #4589

### CODE REVIEW

**Comment by modanesh** [comment]
Thanks for you contribution. It looks good to me. Could you just please revert back the changes you made to other functions like `any()` in the `methods.py` or changes in the `test_methods.py`?

**Comment by PatricYan** [comment]
> Thanks for you contribution. It looks good to me. Could you just please revert back the changes you made to other functions like `any()` in the `methods.py` or changes in the `test_methods.py`?

done

**Comment by modanesh** [comment]
Thanks. Could you take a look at the logs of `test-frontend-numpy` tests? I see that the `test_numpy_max` is being run with `torch` as backend resulting in test failures.

**Comment by PatricYan** [comment]
> Thanks. Could you take a look at the logs of `test-frontend-numpy` tests? I see that the `test_numpy_max` is being run with `torch` as backend resulting in test failures.

This is numpy's function, why run it in the torch backend?

**Comment by modanesh** [comment]
So basically the outputs of the ground truth and the frontend functions are converted to numpy arrays (regardless of the original framework) and asserted to be the same. From the error logs, I see it throws `ivy.exceptions.IvyBackendException: torch: to_numpy: Expected a pytorch tensor`. So somewhere in the chain there might be a missing decorator to convert arrays between Ivy Arrays and Native Arrays. I would suggest you try debugging one of the examples that are failing (can be found in the logs) and see if that makes it any clearer. For that, what I'd do is to make a simple Python script with that particular case and go step by step to understand what's happening and what's going wrong. Just make sure that you set the backend to Torch.

**Comment by PatricYan** [comment]
in my localhost, test case is ok.

**Pull request closed without merging**
