### PR TITLE
sqrt torch front end 

### PR DESCRIPTION
**Pull request by artykov1511**

### CODE REVIEW

**Comment by artykov1511** [comment]
Close #7745

**Comment by nassimberrada** [comment]
Hi @artykov1511, thank you for your contribution !

I see that you've implemented the frontend function but not the tests. Could you add the testing process in the `ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py` file as well ? Thanks !

**Comment by artykov1511** [comment]
Hey @nassimberrada, could you please check the test Ive written? Thanks in regard.

**Comment by nassimberrada** [comment]
Hi @artykov1511, thanks for working on the tests.
If you take a look at the test-frontend-torch tests you can see that it throws the following error:
```
E   TypeError: handle_frontend_method() missing 3 required keyword-only arguments: 'class_tree', 'init_tree', and 'method_name'
```
Could you add the missing arguments and make any adjustments to correct further errors if any gets thrown ? Thanks !

**Comment by artykov1511** [comment]
Hey @nassimberrada thank you for your feedback. Ive added the features you mentioned above. Can you please take a look?

**Comment by nassimberrada** [comment]
Hi @artykov1511, you're in the right direction but something is still off. 

Looking at your branch i think it may be outdated as some of the previous tests are now written slightly differently on master. I suggest you try to update your branch and see where the differences are so you can integrate them in your implementation (both for the testing and the function itself). 

Once you do and you've corrected possible errors, let me know and i'll review it. Thanks !

**Comment by artykov1511** [comment]
Hey @nassimberrada , I updated my branch and reimplemented both the method and its test looking at other already implemented examples. It still gives errors during testing. I can not understand the reason. Can you please take a look?

**Comment by nassimberrada** [comment]
Hi @artykov1511, this looks good to me, thank you for your contribution !

**Pull request merged**
