### PR TITLE
Added nansum Jax frontend #13710

### PR DESCRIPTION
**Pull request by curi-adi**
Pls review the PR.

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by curi-adi** [comment]
Pls review the PR.

**Comment by curi-adi** [comment]
https://github.com/unifyai/ivy/issues/13710

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by curi-adi** [comment]
This PR is with regard to issue : https://github.com/unifyai/ivy/issues/13710

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hiya, sorry it took this long to review your PR 😓 

Thank you for the contributions but I can't give it a proper review yet. Please could you rewrite the testcase following the format in `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_statistical.py`. I believe the `cumsum` test would be helpful here. Please make sure to include both the test helper decorator as well as the test function itself

Thank you!

**Comment by curi-adi** [comment]
> Hiya, sorry it took this long to review your PR 😓
> 
> Thank you for the contributions but I can't give it a proper review yet. Please could you rewrite the testcase following the format in `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_statistical.py`. Please make sure to include both the test helper decorator as well as the test function itself
> 
> Thank you!

Hi @Ookamice , 

Thank you for taking out time to post your inputs. I have edited the `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_statistical.py` for #nansum function, kindly let me know if the changes I made looks ok.

Thanks,
Aditya

**Comment by Ookamice** [comment]
Hey @curi-adi, could you please resolve the merge conflict so the automatic CI tests will run?

Thank you

**Comment by Ookamice** [comment]
@curi-adi 
Thank you for fixing the merge conflicts but I'm not sure why you made modifications to the median test case. Could you please clarrify?

Thank you

**Comment by Ookamice** [comment]
@curi-adi 
Hiya, please could you only commit changes that are relevant to your PR please. There are some wonderful stackoverflow as well as git tutorials on how to revert changes and you can then re-commit only the changes that are relavant!

**Comment by curi-adi** [comment]
> @curi-adi Hiya, please could you only commit changes that are relevant to your PR please. There are some wonderful stackoverflow as well as writeup tutorials on how to revert changes for git and you can then re-commit only the changes that are relevant!

@Ookamice sure, sincere apologies, again! it was unintentional, I will check the internet how to undo commits and re-commit stuff  related to my PR only.

**Comment by curi-adi** [comment]
> > @curi-adi Hiya, please could you only commit changes that are relevant to your PR please. There are some wonderful stackoverflow as well as writeup tutorials on how to revert changes for git and you can then re-commit only the changes that are relevant!
> 
> @Ookamice sure, sincere apologies, again! it was unintentional, I will check the internet how to undo commits and re-commit stuff related to my PR only.

Closed the pr, SORRY about the trouble

**Pull request closed without merging**
