### PR TITLE
reformat round, add examples

### PR DESCRIPTION
**Pull request by schmij12**
#1337

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
@schmij12 your PR is nearly ready to merge I think. It might be appropriate to just add one example using one of the special cases. Request my review when done.😊.. Thanks

**Review by Ishticode — CHANGES_REQUESTED** [review]
In addition, could you also make sure the round function in the backend is formatted. As in, each argument should be on a newline to help with the readability of typehints. This is in addition to what I requested in the review above. Lmk if somethings unclear.  😊

**Comment by schmij12** [comment]
the new commits should address those things, let me know if there's anything else i should change/add!

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @schmij12 
Sorry for the delay - there were some tests being added/fixed and had to resolve an issue with how `round` should work with the special cases mentioned by Array API standard. For now dw about that. Could you update your fork branch? (Pls don't force push)

**Comment by schmij12** [comment]
okay it should be updated now and my bad about the force pushing!! - i accidentally pushed a commit i didn't mean to, and just reverted back the previous commit. let me know if the PR is alright or if i should make a new pull request!

**Review by Ishticode — APPROVED** [review]
Thankyou for your patience @schmij12. I will merge your PR now.

The failing tests are due to external reasons. I have ran tests locally on your branch (test_docstring) and all passing.

Thanks for your contribution. 😊

**Pull request merged**
