### PR TITLE
added log_sigmoid to paddle frontend

### LINKED ISSUE #19327: log_sigmoid

### PR DESCRIPTION
**Pull request by owais8**
Closes #19327

### CODE REVIEW

**Comment by owais8** [comment]
Please do check my repo as I have ran the tests locally and all of them were passing. Thanks

**Comment by theRealBird** [comment]
ivy-gardener

**Comment by theRealBird** [comment]
Hi @owais8,
Let's see if our linting bot can take care of the failing lint tests, other than that your PR looks good to me! Thanks

**Comment by owais8** [comment]
@theRealBird Sure do let me know in case something needs to be changed. Thanks

**Comment by owais8** [comment]
Hello @theRealBird Any update on my PR since its been 4 days that its opened?  Thanks

**Comment by KareemMAX** [comment]
ivy-gardener

**Comment by owais8** [comment]
Hello @theRealBird Can you please review my PR? Its been 6 days since its opened. Lint errors are also solved by bot. Thanks

**Pull request merged**
