### PR TITLE
multi_dot

### PR DESCRIPTION
**Pull request by shireenchand**
added frontend and test for jax multi_dot function

### CODE REVIEW

**Comment by shireenchand** [comment]
#14218

**Comment by zhumakhan** [comment]
Hi, thanks for your PR!
It seems it has quite a lot of failing tests, could you please first address them?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by zhumakhan** [comment]
Hi again, please make sure that on you local machine *python3 -m pytest ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_linalg.py::test_jax_numpy_multi_dot* is passing all the tests. If *ivy.multi_dot* requires fixes feel free to add commits to this PR that fixes it. 
Currently it is failing almost all of the tests.
Thanks.

**Pull request closed without merging**
