### PR TITLE
Checked squeeze

### PR DESCRIPTION
**Pull request by TudorAndrei**
Solves #210

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by TudorAndrei** [comment]
Edits are allowed. :smile:

**Comment by djl11** [comment]
> Edits are allowed. 😄

Thank you!

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Review by djl11 — CHANGES_REQUESTED** [review]
I was unable to push to your repository for some reason. Could you please update to upstream? There are some important updates to the Array API tests in CI which need updating before I can check the test results for merging.

**Comment by TudorAndrei** [comment]
I have fetched the upstream, to this branch.

**Review by djl11 — CHANGES_REQUESTED** [review]
squeeze should not be in the core submodule when adhering to the Array API standard. Is this PR simply to change the type hints? If that's the case, I would rather wait until someone else updates this method to the Array API standard.

**Comment by TudorAndrei** [comment]
I understand. I will move it accordingly!

**Review by djl11 — CHANGES_REQUESTED** [review]
Seems as though the unit tests are not passing, for torch for example. Could you make sure they are all passing locally and then push.

**Comment by TudorAndrei** [comment]
For all frameworks, except mxnet, all the tests work for the `test_squeeze` function, on my machine.

**Comment by TudorAndrei** [comment]
I now, see the errors, I will work on them.

**Comment by 1Doomdie1** [comment]
This PR is being closed because there was no activity on this PR in the last 7 days, and you have not requested a code review from us. Please check our policy on the closing of PRs which are linked to ToDo list issues [here](https://lets-unify.ai/ivy/contributing.html#todo-list-issues), please reach out on discord if you believe this issue has been closed mistakenly, and we’d be very happy to help 🙂

**Pull request closed without merging**
