### PR TITLE
Unknown_shape function not defined

### LINKED ISSUE #19306: [Bug]: Unknown_shape function not defined
### Bug Explanation

Screenshot (50)

### Steps to Reproduce Bug

- Open the file located at C:\open source\ivy\ivy_init_.py in your preferred text editor or IDE.
-
- Check if there are any import statements or dependencies mentioned at the top of the file. Make sure all the required dependencies are installed.
- Run the code that utilizes the Unknown_shape function.
- If you encounter the error message "Unknown_shape function not defined," follow the next steps.
- Make sure you have the latest version of Ivy installed.
- Check the backend being used (NumPy, TensorFlow, PyTorch, JAX). Ensure that the backend is properly installed and compatible with Ivy.
- Verify the device being used (GPU/CPU/TPU) and ensure it is supported by the backend and Ivy.
- Double-check that all necessary packages and dependencies are installed and up-to-date.
- If the error persists, consider providing additional details such as the specific code snippet that triggers the error and any relevant error messages or traceback information.

- Share the bug report with the Ivy community or the project's GitHub repository, including the information about your environment (VSCode version, Ivy version, backend, and device).

### Environment

- IDE: Visual Studio Code (latest version)
- Ivy Version: latest

### Ivy Version

ivy-core-1.1.10

### Backend

- [X] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

 nvidia-ml-py3-7.352.0

### PR DESCRIPTION
**Pull request by shephinphilip**
Fixed "Unknown_shape not defined " error in ___init__.py file.

close #19306

### CODE REVIEW

**Comment by shephinphilip** [comment]
> @shephinphilip Hiya, im not quite sure what this PR fixes, please could you recheck if you have linked the correct issue number.

sorry for my mistake  regarding with  wrong issue number. , I got an error , which states  "Unknown_shape not defined " . the Unknown_shape  function and calling in  with_rank  function in  ./ ivy / ivy / __init__.py  

I fixed the error by   defined  the unknown_shape function inside the with_rank function.
Screenshot (50)

**Comment by Ookamice** [comment]
@shephinphilip 
Hiya, could you link the correct issue number for this please?

**Comment by shephinphilip** [comment]
> @shephinphilip Hiya, could you link the correct issue number for this please?

#19300

**Comment by Ookamice** [comment]
@shephinphilip 
Could you create a new issue following the bug report template please? Especially with the "steps to reproduce" part as that will help a lot for me to see what the underlying problem is as I have never encountered this particular bug myself.

**Comment by shephinphilip** [comment]
> @shephinphilip Could you create a new issue following the bug report template please? Especially with the "steps to reproduce" part as that will help a lot for me to see what the underlying problem is as I have never encountered this particular bug myself.

#19306

**Comment by Ookamice** [comment]
@shephinphilip 
Am i correct in my understanding that this bug is not a runtime error or an error that is encountered when running a specific function but rather an error due to your IDE's syntax highlighting and its use of PyLance for static checking?

**Pull request closed without merging**
