### PR TITLE
ivy_change_1

### PR DESCRIPTION
**Pull request by TRIPLEMEEN**
I am working on the ndim array attribute. I can't find a the function in the test_array_api/array_api_tests. But I did find a method in the test_array_object python file, that may be addressing it and has a TODO at some step. I have to be honest, I am not sure exactly what to do. It doesn't have similarities with any of the examples you used on the Youtube videos.

### CODE REVIEW

**Review by djl11 — CHANGES_REQUESTED** [review]
Please remove all .idea changes from the commit. The code will need to be modified in the ivy.Array class, located at: https://github.com/unifyai/ivy/blob/master/ivy/array/__init__.py

You should add the property ndim here, and then verify yourself that the attribute behaves as expected for all backend frameworks.

**Comment by 1Doomdie1** [comment]
Hey TRIPLEMEE, thank you for contributing!
Next time after you made the changes requested by a ivy team member please request a "Code Review".
I've requested one for you now but please keep this in mind!
If you fail to do so the PR will remain unchecked and will be closed automatically!

**Comment by TRIPLEMEEN** [comment]
Hi,
I couldn’t seem to figure out what the task wanted me to do, and I asked on
the discord channel but got no help.
I’ve gone through the videos but they don’t reference how to standardize
for attributes.

**Review by djl11 — CHANGES_REQUESTED** [review]
Please see my previous comment:

The code will need to be modified in the ivy.Array class, located at: https://github.com/unifyai/ivy/blob/master/ivy/array/__init__.py

You should add the property ndim here, and then verify yourself that the attribute behaves as expected for all backend frameworks.

**Pull request closed without merging**
