### PR TITLE
Implemented square function in all the backends and also the core ivy

### PR DESCRIPTION
**Pull request by NIkhilbadveli**
48 cases failing out of 384 tests for the issue #130 

Only for Tensorflow there were 2 types of errors:

- **E   tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Square}} = Square[T=DT_INT8]
E   All kernels registered for op Square:
E     device='CPU'; T in [DT_BFLOAT16]
E     device='CPU'; T in [DT_COMPLEX128]
E     device='CPU'; T in [DT_COMPLEX64]
E     device='CPU'; T in [DT_INT64]
E     device='CPU'; T in [DT_INT32]
E     device='CPU'; T in [DT_DOUBLE]
E     device='CPU'; T in [DT_HALF]
E     device='CPU'; T in [DT_FLOAT]
E     device='GPU'; T in [DT_INT64]
E     device='GPU'; T in [DT_DOUBLE]
E     device='GPU'; T in [DT_FLOAT]
E     device='GPU'; T in [DT_HALF]
E     device='GPU'; T in [DT_INT32]
E     device='DEFAULT'; T in [DT_INT32]
E    [Op:Square]

<string>:3: NotFoundError**

- **E   tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of uint64 is not in the list of allowed values: bfloat16, half, float, double, int8, int16, int32, int64, complex64, complex128
E   	; NodeDef: {{node Square}}; Op<name=Square; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]> [Op:Square]

<string>:3: InvalidArgumentError**

For the second one, how should I modify the function for tensorflow backend? Should I check for the compatible data types and return some error or handle it some other way? @djl11 

Also, please suggest how to fix the first error.

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by NIkhilbadveli** [comment]
> Thanks a lot for the PR!
> 
> I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

It was already enabled, Dan. Please check once again.

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

**Review by djl11 — CHANGES_REQUESTED** [review]
Please reformat the code as describe in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/), and also as explained in this [YouTube series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl).

**Comment by 1Doomdie1** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
