### PR TITLE
Adding nanmedain function and test in jax frontend

### PR DESCRIPTION
**Pull request by abdulasiraj**
closes #14213

### CODE REVIEW

**Review by zaeemansari70 — COMMENTED** [review]
Hi @abdulasiraj ,
I've requested some changes on your backend implementation PR for this function :slightly_smiling_face:

**Comment by abdulasiraj** [comment]
> Hi @abdulasiraj , I've requested some changes on your backend implementation PR for this function 🙂

Once you merge my backend PR, this one start passing all tests. I have verified locally but you can check on your behave once the other PR is merged. 
Thanks!

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi @abdulasiraj 
Can you please resolve the conflicts? :slightly_smiling_face:

**Review by zaeemansari70 — APPROVED** [review]
Lgtm!

**Pull request merged**
