### PR TITLE
worked on resample image data

### PR DESCRIPTION
**Pull request by Allaye**
- added annotation 
- cleaned up function docstring
- added sample code of the function

### CODE REVIEW

**Comment by Allaye** [comment]
@VedPatwardhan can you please take a look at this PR for me?

**Review by VedPatwardhan — APPROVED** [review]
Hi @Allaye, thanks for contributing, the PR looks good to me, the issue you've created hasn't been linked to the ToDo list yet, as soon as it gets linked, I'll get it merged. Thanks!

**Comment by Allaye** [comment]
@VedPatwardhan you can please merge now

**Comment by VedPatwardhan** [comment]
yeah sure @Allaye, thanks for contributing!

**Pull request merged**
