### PR TITLE
added examples for pinv

### LINKED ISSUE #1216: pinv

### PR DESCRIPTION
**Pull request by anirudhakulkarni**
fixes #1216

### CODE REVIEW

**Comment by anirudhakulkarni** [comment]
- [ ] #1216

**Comment by anirudhakulkarni** [comment]
fixes #1216

**Comment by bicycleman15** [comment]
Its a good start, but still needs more changes.
Refer to: https://lets-unify.ai/ivy/deep_dive/10_docstrings.html

Regarding the examples:
- functional examples having `ivy.Container` is missing
- instance method of `ivy.Array` is missing

Let me know once above is done 🙂

**Comment by bicycleman15** [comment]
closing this due to inactivity

**Pull request closed without merging**
