### PR TITLE
feat: Add `negative_` method to PyTorch frontend

### LINKED ISSUE #23760: negative_

### PR DESCRIPTION
**Pull request by daspartho**
Close #23760

### CODE REVIEW

**Comment by daspartho** [comment]
2 tests are failing but I don't know what's causing it, could you provide me with some context?

**Comment by daspartho** [comment]
Hey @RickSanchezStoic could you take a look at it, looking forward to any comments!

**Comment by RickSanchezStoic** [comment]
@RashulChutani same issue here, dill not found

**Comment by daspartho** [comment]
hello @RickSanchezStoic any updates on this?

**Comment by daspartho** [comment]
@RickSanchezStoic any updates?

**Review by Ishticode — APPROVED** [review]
Hi @daspartho 
Thank you very much for the PR. Sorry for the delay. Not sure why this wasn't merged earlier. Thank you very much for contributing :)

**Pull request merged**
