### PR TITLE
Add Instance Methods ptp to NumPy Frontend #13696

### PR DESCRIPTION
**Pull request by indrawatideasy**
Subtask https://github.com/unifyai/ivy/issues/13611 for Instance Methods to NumPy Frontend https://github.com/unifyai/ivy/issues/3607
accidentaly closed because of sync to branch

### CODE REVIEW

**Comment by indrawatideasy** [comment]
already reviewed by @hmahmood24 --> [here ](https://github.com/unifyai/ivy/pull/13696)

**Comment by satakshigarg** [comment]
> already reviewed by @hmahmood24 --> [here ](https://github.com/unifyai/ivy/pull/13696)

Thank you @indrawatideasy for reopening your PR! However, I noticed that the suggested changes mentioned in the previous review have not been implemented yet. Please take a look at the linting and formatting checks that your PR is failing and fix them by setting up pre-commit in your local environment. Also, ensure that you run all your tests locally and verify that they pass for ALL backends before submitting a PR.
Thank you for your hard work and dedication to our project. We appreciate your contribution and look forward to seeing the updated changes soon. Feel free to ping us on our Discord for any issues.

**Comment by indrawatideasy** [comment]
Hi @satakshigarg,
I am sorry for add other PR [here](https://github.com/unifyai/ivy/pull/14825) . My pycharm got error, so I made other PR. Already did what @hmahmood24 reviewed and passed on Numpy and Jax backend. Still find out why not working on 2 others background.
Thank you :)

**Comment by satakshigarg** [comment]
> Hi @satakshigarg, I am sorry for add other PR [here](https://github.com/unifyai/ivy/pull/14825) . My pycharm got error, so I made other PR. Already did what @hmahmood24 reviewed and passed on Numpy and Jax backend. Still find out why not working on 2 others background. Thank you :)

Hi @indrawatideasy 
I am closing this PR, since there's a new PR now. Thank you !!

**Pull request closed without merging**
