### PR TITLE
add: instance method `squeeze` to JAX frontend

### LINKED ISSUE #23168: squeeze

### PR DESCRIPTION
**Pull request by gauthamk02**
# PR Description 

Adds instance function for `squeeze` operation in JAX Frontend to fix issue #23168 .
## Related Issue 

Close #23168

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials: 
https://twitter.com/gauthamk02

### CODE REVIEW

**Comment by gauthamk02** [comment]
Hey @Infrared1029, Can you please review the PR?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by gauthamk02** [comment]
I have updated the PR description to link to the issue it fixes, before it was only linked in the related issue.

**Comment by Infrared1029** [comment]
Sorry for the late reply @gauthamk02, PR looks good to me, mering.

**Pull request merged**
