### PR TITLE
affine_grid #18942

### LINKED ISSUE #18942: affine_grid

### PR DESCRIPTION
**Pull request by so-dipe**
Close #18942

### CODE REVIEW

**Comment by hirwa-nshuti** [comment]
add_frontend_checklist

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @so-dipe 

Thanks for the PR 😊
Your changes looks good🙂 however, the tests are only passing for the `Numpy` and `Jax` backends would you look into this disparity?

Thanks

**Comment by so-dipe** [comment]
Hi...

My changes are in line with the affine_grid function in pytorch and they seem to be failing the same tests too. I think there's a general issue with the ivy implementation of some functions used there. I not sure which of the functions is causing the issue, and i didn't bother to check because I didn't think editing it would be in the cope of the issue.

**Comment by so-dipe** [comment]
Hi again @hirwa-nshuti 
I suspect the problem is coming from here `base_grid[:, :, :, 1] = ivy.expand_dims(
                ivy.linspace(-1, 1, H) * (H - 1) / H, axis=-1
            )` numpy and jax handle the casting differently from the other frameworks

**Comment by so-dipe** [comment]
Hello @hirwa-nshuti, I have made some changes and I need you to take a look.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @so-dipe 

Good progress with this item.
Now the failure is remaining with the paddle backend
image

**Comment by so-dipe** [comment]
it's a flaky test error... what am i going to do about that.🤷🏽‍♂️ @hirwa-nshuti

**Comment by so-dipe** [comment]
@hirwa-nshuti This is the issue. My code passes the test but fails it initially, there's nothing I can do about that. It's probably an error caused by another function or something.
Screenshot from 2023-07-19 14-12-05

**Review by hirwa-nshuti — APPROVED** [review]
Looks great!
Going to merge it we will look into the detailed issue😊

**Pull request merged**
