### PR TITLE
Reformat general  queue_timeout #3011 

### LINKED ISSUE #3011: get_queue_timeout

### PR DESCRIPTION
**Pull request by edaehn**
+docs examples

closes #3011

### CODE REVIEW

**Comment by edaehn** [comment]
Dear @juliagsy,

1. DocString test fails related to the queue_timeout

> output for  queue_timeout  on run:  10.0,10.0 
371
output in docs : 15.0,10.0 
372
 10.0  !=  15.0 

However, on my machine:

Screenshot 2022-08-31 at 14 59 23


 
2. Lint test
Lint test fails due to the unrelated to the PR file
ivy/functional/frontends/numpy/sorting_searching_counting/searching.py:21:89: E501 line too long (96 > 88 characters)

3. There is again rate limit error: 
API rate limit exceeded for installation ID 14158673.

Please let me know if I should fix anything related to this PR.

Thank you very much.
Best regards,
Elena

**Comment by juliagsy** [comment]
Hi @edaehn 

I'll look into the issue and let you know asap!

and you may ignore the lint and rate limit!

Thank you!

**Comment by edaehn** [comment]
Hi @juliagsy,

Thank you very much. No worries, have a great day!

**Comment by juliagsy** [comment]
Thanks for contributing!

**Comment by edaehn** [comment]
Hi @juliagsy,

Thank you very much for the merge and the information. 

I see that the function is renamed now to get_queue_timeout. I think that it is correct and corresponds to the set_queue_timeout. I have found that the behavior of get_queue_timeout is quite interesting. I did not change the backend when testing it. Thank you very much for your explanation. I hope that the function will behave more predictably in the production. 

Have a nice day, Elena

**Pull request merged**
