### PR TITLE
Added argmin

### PR DESCRIPTION
**Pull request by varshithamanasa**

### CODE REVIEW

**Review by simonetgordon — CHANGES_REQUESTED** [review]
Hi there, 

Thanks for the contribution!

You are also required to write the unit test for argmin. Please check the frontend guide again for more details.

Kind Regards, 

Simone

**Comment by varshithamanasa** [comment]
changes  requested in ndarray.py or test_ndarray.py

**Review by varshithamanasa — COMMENTED** [review]
updated ndarray.py

**Review by simonetgordon — CHANGES_REQUESTED** [review]
Lint picked up the following errors:

```
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py:11:1: E302 expected 2 blank lines, found 1
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py:47:1: E302 expected 2 blank lines, found 1
ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py:91:1: F[8](https://github.com/unifyai/ivy/actions/runs/3279960740/jobs/5400153967#step:5:9)11 redefinition of unused 'test_numpy_ndarray_argmax' from line 54
```

**Comment by simonetgordon** [comment]
@varshithamanasa Hi there, are you still working on this PR? If not, I will close it.

**Pull request closed without merging**
