### PR TITLE
Linspace Examples added

### PR DESCRIPTION
**Pull request by iamravi1**
- [ ] #6942

### CODE REVIEW

**Comment by meetcshah19** [comment]
Hi @iamravi1, I already added these two days back https://github.com/unifyai/ivy/pull/7554

**Comment by nassimberrada** [comment]
Hi @iamravi1, thanks for your contribution ! It looks like there was an overlap of your issue with that of another contributor, this was caused by a mix of improper issue naming and a duplicate linspace slot in the to-do list. 

In an attempt to accomodate both of you and @meetcshah19, could you wait for meetcshah19 to finish writing their implementation of the array examples, and then you could take over by writing the container static and instance method examples ? 

This way you would both be able to contribute to writing the docstrings for this function and none of you would need to discard their work altogether. Hopefully this works well with you, thanks !

**Comment by nassimberrada** [comment]
Hi @iamravi1, thank you for adding the container example. 

Containers are used to apply the target function over multiple arrays at the same time and not as a dictionary of the function's arguments. Consequently, the example should be written in the following format 
```
> x = ivy.Container(a = ivy.array([....]), b=ivy.array([....]))
> ivy.linspace(x, arg1, arg2)
{
    a: ivy.array([.......]),
    b: ivy.array([.......]),
}
```
With that said, could you make the appropriate changes to your example and also add the container instance method example ? (it should be in the format `x.linspace(...)`
Let me know if something is unclear, thanks !

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by nassimberrada** [comment]
Hi @iamravi1, just dropping a comment to stop your PR from going stale. Also quick notice, you may want to update your branch if you resume your work since the other contributor has implemented the function examples.

**Comment by iamravi1** [comment]
I will update my branch soon

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
