### PR TITLE
feat: torch frontend `cholesky_solve`

### LINKED ISSUE #25882: cholesky_solve
Reserve subtask to work on

### PR DESCRIPTION
**Pull request by bridgekat**
# PR Description

## Related Issue

Close #25882

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by bridgekat** [comment]
Implementation should be complete but unfortunately I am still unable to test. It seems like every single PyTorch frontend test is failing with an infinite recursion now...

**Comment by bridgekat** [comment]
Synced with upstream, CI is not detecting the new test, however I ran it locally (`python -m pytest ivy_tests/test_ivy/test_frontends/test_torch/test_blas_and_lapack_ops.py -k test_torch_cholesky_solve`) and this time it failed due to unsupported dtypes being generated and given to my function (?).

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hello! Thank you for your contribution!

Currently your implementation is failing due to the following error:
```
E       RuntimeError: "triangular_solve_cpu" not implemented for 'Half'
```

Can you please check it and resolve it?

**Comment by bridgekat** [comment]
> Hello! Thank you for your contribution!
> 
> Currently your implementation is failing due to the following error:
> 
> ```
> E       RuntimeError: "triangular_solve_cpu" not implemented for 'Half'
> ```
> 
> Can you please check it and resolve it?

This is exactly the failure I've mentioned (I was guessing if `Half` means `float16`).

**Comment by bridgekat** [comment]
Should be passing now.

**Comment by bridgekat** [comment]
Hello, if no one is going to merge this PR, I will close it in 5 days to stop receiving spam emails on unrelated CI failures...

**Pull request closed without merging**
