### PR TITLE
fix(framework): refactoring as_ivy_dev and as_native_dev in all backends

### PR DESCRIPTION
**Pull request by abdulasiraj**
will also close, #18247

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
Hey @abdulasiraj, thanks for looking into this task, I think we could just use `as_native_dev` inside `as_ivy_dev` to avoid duplicating the fallback logic. 
Happy to know your thoughts 😄

**Comment by abdulasiraj** [comment]
> Hey @abdulasiraj, thanks for looking into this task, I think we could just use `as_native_dev` inside `as_ivy_dev` to avoid duplicating the fallback logic.
> Happy to know your thoughts 😄

Hey @vedpatwardhan,
Thanks for your comment. Actually, I tried this but `as_ivy_dev` and `as_native_dev` has a little bit different logic. Also, both return different devices. so, `as_native_dev` can't be used inside the `as_ivy_dev`.

**Review by vedpatwardhan — COMMENTED** [review]
Thanks for clarifying @abdulasiraj 
I think what we should do in that case is get the common logic between these 2 functions (`as_ivy_dev` and `as_native_dev`) as a private helper which both of these functions would make use of, happy to know what you think 😄

**Comment by abdulasiraj** [comment]
> Thanks for clarifying @abdulasiraj I think what we should do in that case is get the common logic between these 2 functions (`as_ivy_dev` and `as_native_dev`) as a private helper which both of these functions would make use of, happy to know what you think 😄

Yep, It'll be a good solution. let me try!
Thanks!

**Comment by abdulasiraj** [comment]
Hi @vedpatwardhan,
I created the private functions where possible but It's not possible for most of the time!

**Review by vedpatwardhan — COMMENTED** [review]
> Hi @vedpatwardhan, I created the private functions where possible but It's not possible for most of the time!

Actually in your PR, in the `backends/jax/device.py` for e.g., except for the `ivy.Device` calls in `as_ivy_dev`, rest of the code is the same as that in `as_native_dev`. We could avoid this code duplication through a single helper that executes this common functionality 😄

**Review by sladyn98 — COMMENTED** [review]
The creation of ivy.Device object is repeated multiple times. This can be minimized.

**Comment by abdulasiraj** [comment]
Hi @vedpatwardhan,

It's possible to add helper for torch and jax but for paddle it's not yet possible cuz paddle missing some functions. I've raised issue on paddlepaddle repo. 
https://github.com/PaddlePaddle/Paddle/issues/55977

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by vedpatwardhan** [comment]
Hey @abdulasiraj, are you creating a different PR for this issue?

**Comment by vedpatwardhan** [comment]
> > Hey @abdulasiraj, are you creating a different PR for this issue?
> 
> Hey @vedpatwardhan, I was working on some other important tasks on testing side and bot marked this PR as staled so I consider this to close. Due you think we should work on this or do you have someone on framework to work on this?. let me know your thoughts. Thanks :)

Got it! If you're busy with something else, @RickSanchezStoic could you please look into getting this over the line? I think we're done for the most part just a final few changes remaining. Thanks 😄

**Comment by abdulasiraj** [comment]
I'll create new PR for this

**Pull request closed without merging**
