### PR TITLE
added funtionality for __divmod__ (unifyai #13079)

### LINKED ISSUE #13079: __divmod__

### PR DESCRIPTION
**Pull request by AjibolaMatthew1**
Close #13079

### CODE REVIEW

**Comment by AjibolaMatthew1** [comment]
@Fayad-Alman

**Comment by AjibolaMatthew1** [comment]
@Fayad-Alman hello! I'd appreciate if you could kindly help go through my PR.

**Review by Fayad-Alman — CHANGES_REQUESTED** [review]
Hi @AjibolaMatthew1, sorry for the late response!

Everything looks good so far, just one thing. On your forked branch, make sure you update the changes made to the following file:
ivy/functional/frontends/numpy/ndarray/ndarray.py

Once you've updated the file, add the changes you made and send another review so I can see if everything's ready to merge.

Thanks for your contributions!

**Comment by AjibolaMatthew1** [comment]
@Fayad-Alman

**Review by Fayad-Alman — CHANGES_REQUESTED** [review]
Hi @AjibolaMatthew1, apologies for the late response
The tests for the divmod function are failing, and I've been trying to pinpoint the cause of the errors. It seems that the results for the backend are different than the frontend, and that's causing the tests to fail. 
There is no implementation of the divmod function in the backend, so in hindsight this makes sense. However, I'm still unsure if this is the correct solution to this problem. Could you perhaps try to incorporate this change and see what happens?
Appreciate the contribution!

**Comment by AjibolaMatthew1** [comment]
Good evening @Fayad-Alman, hope you are doing good? Kindly help me review my change. Thank you!

**Review by Fayad-Alman — CHANGES_REQUESTED** [review]
Hi @AjibolaMatthew1 
I believe you still need to add the implementation of divmod to the backend. Kindly make this change and request another review.

Many thanks,
Fayad

**Comment by Fayad-Alman** [comment]
@AjibolaMatthew1 This PR and issue has been inactive for quite some time, and your branch is quite outdated, so I'm going to close this PR. If you wish to have your changes reviewed, please create a new PR and request a review. Thank you.

**Pull request closed without merging**
