### PR TITLE
Fixed Ivy can cast

### LINKED ISSUE #19704: [Bug]: ivy.can_cast
### Bug Explanation

 Function always returns True.

### Steps to Reproduce Bug

```
>>> import numpy as np
>>> import ivy
>>> ivy.can_cast(ivy.float64,ivy.int32)
True
>>> np.can_cast(np.float64,np.int32)
False
```

### Environment

Colab

### Ivy Version

v1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

_No response_

### PR DESCRIPTION
**Pull request by shephinphilip**
Close  #19704 

In the modified code, we store the result of ivy.promote_types(from_, to) in a variable called dtype. Then, we check if dtype is equal to to. If they are equal, it means the cast can occur according to the type-promotion rules, and we return True; otherwise, we return False.

This solution ensures that the can_cast function now correctly determines if one data type can be cast to another data type, fixing the bug in the original code.

### CODE REVIEW

**Comment by shephinphilip** [comment]
@ZoeCD ,Hey  , I am creating pull request and every time  Some checks were not successful  ,  could you please tell me why this happens , I gone through the changes that i have made and can't understand it , Would you please guide me on this ?, I would appreciate for your guidance.

**Comment by shephinphilip** [comment]
re-run checks

**Comment by ZoeCD** [comment]
Hello! Sure, I'm here to help you!
First, you don't need to change the .yml file, so you'll need to revert those changes
Second, you don't need to worry about tests unrelated to your commit. If you see a test that is failing, but you did not change anything in the related files, you do not need to solve that. You just need to make sure the test that you created passes for all backends
And finally, to know more about the errors, you need to go to the "Details" section of the intelligent tests and search for the name of your function to find the corresponding section faster.
Let me know if that helps!  😊

**Comment by shephinphilip** [comment]
this issue is resolved so closing this repository

**Pull request closed without merging**
