### PR TITLE
Adding jax_random_orthogonal

### PR DESCRIPTION
**Pull request by stalemate1**

### CODE REVIEW

**Comment by Ookamice** [comment]
@stalemate1 
Hiya, thank you for your contributions. Could you please double check the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing.html) regarding how to open an PR for a frontend function.

Namely, please reference the issue number that this PR relates to and double check that the files in this PR are in the same directory. There shouldn't be a case of creating new files with PRs of this type.

Let me know if you have any other questions or concerns! 😃

**Comment by stalemate1** [comment]
Hello @Ookamice so should I close this PR before I make a new PR as explained in the video. Because right now everytime I am selecting the current branch I am not able to make the new PR from that

**Comment by stalemate1** [comment]
orthogonal #17774

**Comment by stalemate1** [comment]
It is being placed in the appropriate directory (I believe). Also, I have mentioned the issue number in the comment. Should I be worried about anything else before the workflow is approved?

**Comment by Ookamice** [comment]
@stalemate1 
Hiya, please double check that the directory is correct. Currently, as according to the  "files changed" tab of this PR, it is showing that you're trying to add 2 files into the root directory of Ivy. Rather, it should look like you're trying to modify two files in the respective frontend subdirectories.

Let me know if you need further help in this matter. 😸

**Comment by stalemate1** [comment]
@Ookamice , sorry unfortunately whatever I have been updating on git bash is not being reflected on github. Therefore, I copied the entire file and pasted here and that was the problem. Now I have created a new PR Orthogonal #18094. Please let me know if it is fine. 

Thanks a bunch!

**Comment by Ookamice** [comment]
Sounds good 👍 

I'll close this PR for you and good luck on your next PR

**Pull request closed without merging**
