### PR TITLE
feat(docs/api-standards): fix placeholders in api_standards.rst

### PR DESCRIPTION
**Pull request by shephinphilip**
# PR Description

I have addressed issue , which involved correcting placeholders in the documentation located at https://unify.ai/docs/ivy/overview/related_work/api_standards.html.

## Related Issue

Close 

## Checklist

- [x] Corrected the placeholders in the documentation.
- [x] Verified that the content accurately reflects the changes made.
- [x] Checked the documentation for any additional issues or inconsistencies.

### Socials:

N/A

### CODE REVIEW

**Comment by tomatillos** [comment]
Hello, can you make sure you're only editing the files you are intending to change.

**Comment by shephinphilip** [comment]
> Hello, can you make sure you're only editing the files you are intending to change.

 I edited this file 
docs/overview/related_work/api_standards.rst

Error is in 
https://unify.ai/docs/ivy/overview/related_work/api_standards.html.

**Comment by tomatillos** [comment]
OK but the PR is reversing lots of other commits, in 'Files changed' there should only be your file.

**Comment by shephinphilip** [comment]
> OK but the PR is reversing lots of other commits, in 'Files changed' there should only be your file.

what should I do ? Could you please help me on this ?

**Pull request closed without merging**
