### PR TITLE
Implemented `mod` functionality for TensorFlow frontend

### PR DESCRIPTION
**Pull request by edith007**
Close https://github.com/unifyai/ivy/issues/14069

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Sorry for the late review,
`mod` is just an alias of `floormod` in tensorflow, https://www.tensorflow.org/api_docs/python/tf/math/floormod

So you can basically add it like: `mod=floormod` in the frontends. For testing you can add an argument `aliases=['tensorflow.math.mod'],` in the `handle_frontend_test` decorator of `floormod` test function. Hope this helps and let me  know if you have any questions.

Thanks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
