### PR TITLE
Added log_softmax for Mindspore frontend #21254

### LINKED ISSUE #21254: log_softmax

### PR DESCRIPTION
**Pull request by guodh321**
Added log_softmax for Mindspore frontend 
closes #21254
Please merge and close the issue. Thanks.

### CODE REVIEW

**Comment by guodh321** [comment]
And the issue #21254 is a subtask form #14951

**Review by AryanSharma21 — COMMENTED** [review]
Hello, @guodh321 , while you have added the function, you should also implement the test for the same function in the corresponding file. 
Also, you can edit the PR description and write    `close #issue_number`  only . This will link the PR to the issue that you have just created and it will automatically close the issue also whenever the PR gets merged . 
Thanks

**Comment by guodh321** [comment]
> 

Hi, thanks for suggestion. I added the test for this function. Please check, thanks.

**Comment by Daniel4078** [comment]
ivy-gardener

**Comment by AryanSharma21** [comment]
I think you have mistakenly commented out the entire test case .

**Comment by guodh321** [comment]
> 

Hi, the original test case was already commented out. I was also wondering about this. I just followed to comment mine out as well. Is there any changes needed or can be merged? Thanks.

**Comment by AryanSharma21** [comment]
@guodh321 ,  I am not sure what you are actually trying to convey with  `Original Test case` here. As far as I could understand is that every function has a test function used to check if the function is working properly to all the backend frameworks and to run the test here, shouldn't it be commented out ? 
Besides, we can wait for the review from maintainer assigned @Daniel4078 , to understand better.

**Comment by Daniel4078** [comment]
According to what I can see here, all the existing tests for the set of functions are commented out for some reason. I recomment you (@guodh321) to try and uncomment the tests to see if it will cause any problem while I will ask on Ivy's discord channel for other people who know what happened.

**Comment by AryanSharma21** [comment]
In that case, I will be waiting for update from your side sir. :)

**Comment by Daniel4078** [comment]
> In that case, I will be waiting for update from your side sir. :)

During the setup we can't simply install mindspore using pip and it isn't yet added to requirements that's why 🙄

**Comment by Daniel4078** [comment]
By the way, don't forget to resolve merge conflicts.

**Comment by guodh321** [comment]
> By the way, don't forget to resolve merge conflicts.

Conflict solved. Please help merge and close this PR if possible. Thanks.

**Comment by Daniel4078** [comment]
ivy-gardener

**Pull request merged**
