### PR TITLE
approx_max_k(Add Operator functions to Jax Frontend)Close [#21329]

### PR DESCRIPTION
**Pull request by JONAHKYAGABA**
Close [#21329]
A start implementation am requesting for clarity on how to compose this

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Pchatain** [comment]
HI @JONAHKYAGABA thanks for working on this! This looks like a neat function to add and there are several steps to follow. Here are some documents to help guide you when working and hopefully provide clarity. 
https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html 

Also make sure to read - https://unify.ai/docs/ivy/overview/deep_dive/function_types.html#function-types I think this falls under the class of Mixed Functions. Therefore, we should make an Issue to add this in the related backend in case it's not already implemented there in jax.lax. Then in this PR, you need to optionally use your compositional implementation, which upon first glance looks correct, or the future backend specific implementation once that's completed.

https://unify.ai/docs/ivy/overview/contributing/open_tasks.html
It looks like the PR for testing this function was never finished, so you also need to write tests to finish this contribution. https://github.com/unifyai/ivy/pull/13730/files 

I believe based on https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.approx_max_k.html that this function is meant to be an efficient alternative to top_k. So simply calling top_k might be slower. This is why implementing this as a mixed function would be good.

**Comment by JONAHKYAGABA** [comment]
Hi @Pchatain .Thank you for such an igniting and constructive feedback. Let me implement the changes requested .Also the function is not implemented in the back end that is jax.lax .I will make another PR as soon as possible.

**Comment by JONAHKYAGABA** [comment]
Hi @Pchatain this function requires many backend functions and not effficient to be implemented in the frontend only.I will be glad to contribute to its backend first

**Pull request closed without merging**
