### PR TITLE
fix the bug #22842

### PR DESCRIPTION
**Pull request by Aryan8912**
# PR Description 

## Related Issue 

Close https://github.com/unifyai/ivy/issues/22842

## Checklist 

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by paulaehab** [comment]
Hey @Aryan8912  could you please refer to the bug number you try to fix ?

**Comment by Aryan8912** [comment]
the bug number is #22842 @paulaehab

**Comment by KareemMAX** [comment]
Hey @Aryan8912 @paulaehab,
FYI this is a duplicate of https://github.com/unifyai/ivy/pull/26487

**Comment by KareemMAX** [comment]
Also, FYI @paulaehab: I'm flagging this internally, DMing you the conversation.

**Comment by KareemMAX** [comment]
Hey @Aryan8912, sadly I'm closing this PR as it would be better if we fixed this issue internally. Thank you so much for your effort and really sorry about the inconvenience I caused.

Can't wait to see your future contributions 🚀

**Pull request closed without merging**
