### PR TITLE
Numpy.random.f function

### LINKED ISSUE #19511: f
numpy.random.f function

### PR DESCRIPTION
**Pull request by VedantPol**
close #19511

### CODE REVIEW

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
Hi @VedantPol 
Can you look again, why tests are failing. let me know if they are passing locally.
Thanks!

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
./ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py::test_numpy_f[cpu-ivy.functional.backends.numpy-False-False] Failed: [undefined]TypeError: f() takes at least 2 positional arguments (0 given)

**Comment by VedantPol** [comment]
hey @abdulasiraj ,
I ran the test locally multiple times with a modified function but I couldn't understand the root cause of the error. Locally importing the function and running dummy tests also worked. this is the following error log that I received. I hope you could provide me with some insights on the following 
FAILED [ 20%]
ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py:711 (test_numpy_f[cpu-ivy.functional.backends.numpy-False-False])
frontend = 'numpy', on_device = 'cpu'

    @handle_frontend_test(
>       fn_tree="numpy.random.f",
        input_dtypes=helpers.get_dtypes("float", full=False),
        dfn=st.one_of(
            st.floats(
                min_value=0,
                max_value=1000,
                exclude_min=True,
                width=32,
            ),
        ),
        dfd=st.one_of(
            st.floats(
                min_value=0,
                max_value=1000,
                exclude_min=True,
                width=32,
            ),
        ),
        size=helpers.get_shape(allow_none=True),
    )

test_functions.py:713: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_functions.py:743: in test_numpy_f
    helpers.test_frontend_function(
../../../helpers/function_testing.py:784: in test_frontend_function
    raise e
../../../helpers/function_testing.py:769: in test_frontend_function
    frontend_ret = frontend_fw.__dict__[fn_name](*args_frontend, **kwargs_frontend)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: f() takes at least 2 positional arguments (0 given)
E   Falsifying example: test_numpy_f(
E       frontend='numpy',
E       on_device='cpu',
E       input_dtypes=['float16'],
E       dfn=1.0,
E       dfd=1.0,
E       size=None,
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=0,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=False,
E       ),
E       fn_tree='ivy.functional.frontends.numpy.random.f',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.81.1', b'AXicY2CAA0YMJgAANgAD') as a decorator on your test case

mtrand.pyx:1728: TypeError

**Comment by abdulasiraj** [comment]
Please Resolve the conflict, than I'll check what's the problem. Thanks!

**Comment by VedantPol** [comment]
Resolved the merge conflict. Thanks

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
Hi @VedantPol 
There's a problem with your test function. somewhere you're passing positional argument as keyword arguments. It's just the hint, you've to figured it out yourself. 
Thanks!

**Comment by VedantPol** [comment]
Hello @abdulasiraj,

It seems that the @handel_frontend_test decorator was not able to automatically detect the number of positional arguments. However, the issue was resolved by passing them manually (you can see the fix here: https://github.com/unifyai/ivy/pull/19512/files#diff-b1ae859126683b64161eef39c7a554962376081abcb3da77efa63c7a8a0e01fdR821). Thank you for providing the helpful hint.

Currently, all my tests are passing locally, but I am encountering a few failures with GitHub actions checks. I would appreciate your opinion on these matters :)

Screenshot from 2023-07-25 01-07-21

console log of the testcase:
```

/opt/miniconda/envs/multienv/bin/python3 /opt/.pycharm_helpers/pycharm/_jb_pytest_runner.py --target test_functions.py::test_numpy_f 
Testing started at 12:55 am ...
/opt/.pycharm_helpers/pycharm/_jb_pytest_runner.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import iter_entry_points
Launching pytest with arguments test_functions.py::test_numpy_f --no-header --no-summary -q in /opt/project/ivy_tests/test_ivy/test_frontends/test_numpy/test_random

Use Database in ReadOnly Mode with local caching !
============================= test session starts ==============================
collecting ... collected 5 items

test_functions.py::test_numpy_f[cpu-numpy-False-False] 
test_functions.py::test_numpy_f[cpu-jax-False-False] 
test_functions.py::test_numpy_f[cpu-tensorflow-False-False] 
test_functions.py::test_numpy_f[cpu-torch-False-False] 
test_functions.py::test_numpy_f[cpu-paddle-False-False] 

================== 4 passed, 1 skipped, 75 warnings in 21.28s ==================
PASSED            [ 20%]PASSED              [ 40%]PASSED       [ 60%]WARNING:tensorflow:From /opt/fw/tensorflow/tensorflow_probability/python/internal/batched_rejection_sampler.py:102: calling while_loop_v2 (from tensorflow.python.ops.while_loop) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))
PASSED            [ 80%]SKIPPED          [100%]
Skipped: Function not implemented in backend.

Process finished with exit code 0
```

**Comment by abdulasiraj** [comment]
Hi @VedantPol,
can you please resolve the conflicts?
Thanks!

**Comment by VedantPol** [comment]
hey @abdulasiraj ,
I have resolved all the merge conflicts :)

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
Hi @VedantPol 
Thanks for great work. just one quick thing, your function is not detected during the test. can please check why that's the case is?

**Review by abdulasiraj — APPROVED** [review]
LGTM!

**Pull request merged**
