### PR TITLE
Starting pmax #6016 in  parallel_operators.py

### PR DESCRIPTION
**Pull request by Shajeeran**
I add this commit to start doing my contribution in pmax methode of parallel_operators.py

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by agniiyer** [comment]
Hey just following up on this PR! Let me know if you need any guidance :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
