### PR TITLE
Implements the dct function for the frontend which is missing but ticked in the issues tab

### LINKED ISSUE #21436: DCT

### PR DESCRIPTION
**Pull request by Enigmafiend**
Close #21436

### CODE REVIEW

**Comment by Enigmafiend** [comment]
ivy-gardner

**Comment by Enigmafiend** [comment]
ivy-gardener

**Comment by Enigmafiend** [comment]
ivy-gardener

**Comment by satakshigarg** [comment]
Hi @Enigmafiend 
Thanks for contributing !!
However I can see that few tests are failing, could you please make the required changes to make sure that all tests pass. Feel free to ping me once the code is ready for review.

Regards
Satakshi Garg
Screenshot 2023-08-20 at 7 14 25 PM

**Comment by hmahmood24** [comment]
Closing this PR since there has been no activity for more than a week.

**Pull request closed without merging**
