### PR TITLE
einsum

### PR DESCRIPTION
**Pull request by janetwamaitha**

### CODE REVIEW

**Comment by Infrared1029** [comment]
Hi @janetwamaitha! I'm looking into the PR now, there are a few linting errors though, we gotta get those fixed:D! using `pre-commit` as described [here](https://lets-unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit) will make things easier!

**Comment by janetwamaitha** [comment]
#13993

**Comment by janetwamaitha** [comment]
There was an initial error when running the test, which was a Name Error.
Name error

**Comment by Infrared1029** [comment]
Hi @janetwamaitha! you are using `np` even tho `np` is not imported in this file, so the errors make sense! we probably do not need to `np` to generate the arrays as there are helper functions for that like `helpers.dtype_and_values`

**Comment by janetwamaitha** [comment]
Okay, let me give a try.

**Pull request closed without merging**
