### PR TITLE
Add log_loss for Paddle frontend and test

### LINKED ISSUE #18515: log_loss

### PR DESCRIPTION
**Pull request by peterwisu**
Close #18515

### CODE REVIEW

**Comment by tomatillos** [comment]
Thanks! Would you mind getting the lint formatting test to pass? You can see how to setup the pre-commit here: https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit

**Comment by peterwisu** [comment]
> Thanks! Would you mind getting the lint formatting test to pass? You can see how to setup the pre-commit here: https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit

Sure will do it

**Comment by tomatillos** [comment]
Hi, thanks for that, unfortunately it seems like the test is failing for the tensorflow backend. Could you take a look?

**Comment by tomatillos** [comment]
LGTM! Thanks

**Pull request merged**
