### PR TITLE
Added digamma fn

### PR DESCRIPTION
**Pull request by shakirriyaz**
Close https://github.com/unifyai/ivy/issues/21399

### CODE REVIEW

**Comment by shakirriyaz** [comment]
Close #21399

**Comment by ZoeCD** [comment]
Hello! The tests for digamma are not being executed. You need to add the corresponding decorator for it. I also recommend creating a different PR for the igamma test to keep things cleaner. Let me know if you have any questions!

**Comment by ZoeCD** [comment]
Also, you need to resolve the merge conflicts!

**Comment by shakirriyaz** [comment]
@ZoeCD Please review this

**Comment by ZoeCD** [comment]
Could you please update your branch, resolve the merge conflicts and push everything again?

Thanks!

**Comment by shakirriyaz** [comment]
I don't know how this was closed automatically. Can you merge it if it is okay?

**Pull request closed without merging**
