### PR TITLE
index_add

### LINKED ISSUE #13557: index_add

### PR DESCRIPTION
**Pull request by kkaracam**
Close #13557

### CODE REVIEW

**Comment by kkaracam** [comment]
@MahmoudAshraf97 looks like functions other than my implementation are failing. Could you please review?

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Can you please remove all changes that are unrelated to your implementation?

**Comment by kkaracam** [comment]
I have done so in commit [247f06e](https://github.com/unifyai/ivy/pull/13559/commits/247f06e04707744b64e70444bd9d2153f54cb3bd)

**Comment by kkaracam** [comment]
Should be fine now, only lint check is failing

**Pull request merged**
