### PR TITLE
normal

### LINKED ISSUE #22678: normal

### PR DESCRIPTION
**Pull request by Fahreddin487**
# PR Description 

## Related Issue 

Close #22678

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @Fahreddin487, thanks for the PR! Can you please revert any changes you committed to the `array_api_testing` folder? Can you also fix the multiple [lint/formatting issues](https://github.com/unifyai/ivy/actions/runs/6011597134/job/16305305082?pr=22734) with this PR? Thanks! :)

**Comment by Fahreddin487** [comment]
Hi @hmahmood24, I made new changes.

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @Fahreddin487, it seems like the function is failing when tested with the `tensorflow` backend. Can you look into the [failure](https://github.com/unifyai/ivy/actions/runs/6074632949/job/16479106600?pr=22734) and fix it? Thanks!

**Comment by Fahreddin487** [comment]
Seems like this function is already added by another person. I am closing this PR.

**Pull request closed without merging**
