### PR TITLE
histogram function in pytorch frontend

### LINKED ISSUE #21071: histogram
Adding histogram to pytorch frontend

### PR DESCRIPTION
**Pull request by jindalai**
Adds the histogram function along with corresponding test to the pytorch frontend as per issue #21071

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by sagewhocodes** [comment]
Hello @yashj8 , I noticed a couple of issues that I would like you to address before the assigned reviewer reviews your PR.
1. rename your PR to highlight what issue you have worked on? like `histogram function in pytorch frontend` . 
2. write the test for the implemented frontend function, refer [Ivy frontends tests doc](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html) for more details

Thank you for contributing to Ivy 😄

**Comment by yashj8** [comment]
> Hello @yashj8 , I noticed a couple of issues that I would like you to address before the assigned reviewer reviews your PR.
> 
> 1. rename your PR to highlight what issue you have worked on? like `histogram function in pytorch frontend` .
> 2. write the test for the implemented frontend function, refer [Ivy frontends tests doc](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html) for more details
> 
> Thank you for contributing to Ivy 😄

Thanks for the feedback! Made the required changes. Currently working on the test.

**Comment by yashj8** [comment]
I am writing the tests for this and it has multiple [parameters](https://pytorch.org/docs/stable/generated/torch.histogram.html), including one that can be either an int or a tensor (_bins_).
How do I go about writing the data generation part for the test (dtype_and_x = ...)?
Do I create a custom function?
A high-level overview would be highly helpful 😄 
@sagewhocodes @ndurumo254

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by yashj8** [comment]
It is waiting initial review from @ndurumo254 from over a month.

**Comment by NripeshN** [comment]
Hi @jindalai,
Could you please merge this branch with main resolving all the conflicts?

**Pull request closed without merging**
