### PR TITLE
Added paddle.broadcast_tensors frontend to manipulations file

### LINKED ISSUE #24140: broadcast_tensors

### PR DESCRIPTION
**Pull request by odunola499**
# PR Description

## Related Issue

Fixes #24140 

## Checklist

- [x]  Did you add a function?

- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials:

https://twitter.com/Jenrola_odun

### CODE REVIEW

**Comment by AlexandraPosta** [comment]
Hello @odunola499, thank you for your contribution:zap:. Please run your tests locally and let me know if I can help in any way.

**Comment by odunola499** [comment]
hello @AlexandraPosta  for some reason I cannot seem to get the tests to pass. each backend throws off a bunch of different errors.

**Comment by AlexandraPosta** [comment]
Hello @odunola499, good work so far! There are a few points:
- I would have another look at the function definition in the [PaddlePaddle documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/broadcast_tensors_en.html), especially for arguments
- Why do you only return the first element of the output?
- Your testing procedure is not completed, please have another look at our [testing procedure](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html)
- In terms of the input generation. Are you sure you need a custom helper for the input generation? Maybe have a look at the test implementation for broadcast_tensors (broadcast_arrays) in other backends

Hope this is helpful, happy coding :cat:

**Comment by Ishticode** [comment]
Closing this due to inactivity for over 6 months. Please feel free to reopen if you would like to continue working on this. Thank you :)

**Pull request closed without merging**
