### PR TITLE
atanh #18992

### LINKED ISSUE #18992: atanh

### PR DESCRIPTION
**Pull request by UseTheForce007**
closes #18992

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by UseTheForce007** [comment]
Can I get some help with where this is failing?

**Comment by UseTheForce007** [comment]
#18992

**Comment by juliagsy** [comment]
It's working well, thanks for contributing!

**Pull request merged**
