### PR TITLE
Xbouroseu/experimental/idct

### LINKED ISSUE #15761: idct

### PR DESCRIPTION
**Pull request by xbouroseu**
Close #15761

### CODE REVIEW

**Comment by Ookamice** [comment]
@xbouroseu
Hiya, thank you for your contributions! I am having a closer look now and running some tests manually but in the meantime could you revert the changes made to `.pre-commit-config.yaml`

Thank you and let me know if you have any other concerns and questions! 🚀

**Comment by xbouroseu** [comment]
@Ookamice Hello! Thank you for your response! I have reverted the changes. Please let me know if there are any problems!

**Comment by xbouroseu** [comment]
@Ookamice I added it! I also added to test_dct because i saw it was missing there as well. Please let me know if there is anything else!

**Comment by xbouroseu** [comment]
@Ookamice Uhmm there is a helper function which is called `valid_dct` which was implemented by the guy who wrote `dct` and i have kept it for `test_idct` data generation because the data spec is the same. In `valid_dct` there is the line 
```python
axis = draw(helpers.ints(min_value=-dims_len, max_value=dims_len))
```
It has to be there but how can we debug this? Can we poll the value of axis? Also i can't find anywhere in the implementations of `idct` and `test_idct` the restrictions and exceptions which would produce the error you write above. I would like to help if you could share with me the conditions under which i can reproduce the error? Thank you and i am at your disposal!

**Comment by xbouroseu** [comment]
@Ookamice Okay so i'm unable to fully go through with the tests because i get errors related to the torch version which is related to the docker latest-gpu image i'm running from. I would like to help if you could share the conditions under which i can reproduce the error? 

Otherwise i think the error may be in:
```python
dims_len = len(x[0].shape)
axis = draw(helpers.ints(min_value=-dims_len, max_value=dims_len))
```

Which could be:
```python
dims_len = len(x[0].shape)
axis = draw(helpers.ints(min_value=-dims_len, max_value=dims_len)-1)
```

Because in ` axis_dim = x.shape[axis]` axis is used as index of shape but during data generation it can take the value of the shape's length which is out of bounds in 0-index array correct?

**Comment by Ookamice** [comment]
@xbouroseu 
I'm not quite sure why dct is merged as not every PR goes through multiple eyes. I do think your solution sounds promising using `max_value=dims_len-1` for the data generation. I'm also only relying on the intelligent tests so feel free to make changes and see how those tests react (this is a pretty tedious process as those tests take quite a while to run) 😅 

PS:  If your local instance isn't working well, you can try opening a github codespace.

**Comment by xbouroseu** [comment]
@Ookamice Hmm i understand. So i will try to push that minor change and see how it goes? Please don't leave me alone on this xD. About codespaces, yeah i started with that but i immediately abandonded it due to some problems with lack of proper configuration in ivy for proper automatic testing from the IDE, but for manual testing i may use it from now on if it means that i am keeping up with everyone.

**Comment by Ookamice** [comment]
@xbouroseu I do believe there is a way to get testing setup which you can check more details in [here](https://unify.ai/docs/ivy/overview/contributing/setting_up.html) although I just prefer to do small tests via the command line through PyTest. Let me know if you need any help getting a codespace setup and installing the required modules

> So i will try to push that minor change and see how it goes?
That's what I've seen others do for their PRs although ideally a way to test your code before the intelligent test would be good because there is a pretty big delay 😆

**Comment by xbouroseu** [comment]
@Ookamice Okay so i see that it's taking some while to pass the 1st test which hopefully is a good sign! :smiley: . But i would like some help regarding codespaces if that is possible? I have setup and allowed it to initialize and download any vscode extensions that it might need. 
I also ran `pip install requirements/requirements.txt` and completed successfully. However when i tried the same for `requirements/optional.txt` or `requirements/optional_gpu.txt` it fails on package `torch-scatter`. Bypassing that and not installing the package i try to run the command for testing which is: 
```
python -m pytest ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_idct
```
but i get the error :
```
=============================================================================== short test summary info ================================================================================
ERROR ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
============================================================================= 7 warnings, 1 error in 2.29s =============================================================================
ERROR: not found: /workspaces/ivy/ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_idct
(no name '/workspaces/ivy/ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_idct' in any of [<Module test_layers.py>])
```

**Comment by Ookamice** [comment]
@xbouroseu 
Also, just had a look through the error log and it seems to be that a lot of the error it is throwing has to do with the implementation of dct(). I know that the code you have written leverages dct() a lot so I'm not sure if there's an easy fix for you other than rewriting some of the dct() logic too. Unfortunately, codespace debugging has been broken for me since this week so if it is possible, I think it would be super informative if you can run the pytest for dct()!

**Comment by xbouroseu** [comment]
@Ookamice On a second note I remember that many tests are failing even without any commits from my part but only with the latest pull.. So apart from running test_dct can we isolate the failing relevant to this PR only from the intelligent-PR-tests? If not I'll try test_dct and will be waiting for your further input... 😀

**Comment by Ookamice** [comment]
@xbouroseu 
Unfortunately not but I am also not 100% confident in my understanding of how the intelligent-test-prs are decided as I am uninvolved with that team. I just expand the combined testing logs and then use github's log search feature for idct to find the relevant tests.

**Comment by xbouroseu** [comment]
@Ookamice Yeah you are right and we should do that obviously.. Okay so I will try running pytest and searching through the logs as you said but I will also be waiting your assistance 🙏

**Comment by Ookamice** [comment]
@xbouroseu 
Hiya, I bring some good news. After digging around and playing with codespaces, I have addressed the error of Pytests not working. Turns out the error message is super misleading and it is actually a problem with the jax installation. If you `pip3 install jax` as well as `pip3 install jaxlib`, the error about not being able to import test configs disappears.

Let me know if this solution works for you and if not, I'll set up a codespace up on this PR branch to help you with troubleshooting 👍

**Comment by xbouroseu** [comment]
@Ookamice Hey! Thanks for letting me know, it's nice to be able to have a ground truth environment where we all can work on 😀.

Anyway I made some contact with the author of dct and turns out there as some issues unrelated to my PR. The tests fail primarily on numpy, jax, torch due to some backend issues. I changed the numpy implementation to use scipy.fftpack.dct and managed to get tests passing which can also imply that jax, torch implementations would pass because they are  similar. So I'm told that the PR might be eligible for merging but I'm awaiting further confirmation from Jerry (that's the name I was given).

**Comment by xbouroseu** [comment]
@Ookamice Hey! I think i have resolved the conflicts. Please let me know if there is anything else!

**Comment by Ookamice** [comment]
Awesome, thank you for the contributions! 👍

**Pull request merged**
