### PR TITLE
Added trace to jax frontend

### LINKED ISSUE #21027: trace

### PR DESCRIPTION
**Pull request by BrolyDBZ**
close #21027

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by a0m0rajab** [comment]
@BrolyDBZ can you add the related task to the description of the issue with `close #TASK NUMBER`,

Why to do this? 

Cause it will help to auto close the task opened and mark it as done in the list, 
[Ivy Docs](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues)
[GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)


Related to: https://github.com/unifyai/ivy/issues/21027

**Comment by BrolyDBZ** [comment]
Hey @Infrared1029, Please review it and let me know if any changes need to be made.

**Comment by Infrared1029** [comment]
Hi @BrolyDBZ, apologies for the late reply, the tests we write should ideally cover the entire input space, it appears that the test written here only generates 2-D arrays, while the function accepts N-D arrays, the axis1, axis2 and offset can also have their values played around instead of using the default values.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
