### PR TITLE
Add atan2 to torch

### PR DESCRIPTION
**Pull request by ream-kh**
- [ ] #3078

### CODE REVIEW

**Comment by ream-kh** [comment]
I have opened and issue to add divide_no_nan to tensorflow frontend (#3078) and this pull request includes the divide_no_nan implemented function. Can you make a review? Thank you in advance.

**Comment by Auxia** [comment]
Hi @ream-kh, thanks for contributing to Ivy! Unfortunately this pull request cannot be accepted right now as the function that you are working on has not been implemented natively in Ivy or even the specific backend. This will however be implemented in a future release. I will flag this PR and the Issue connected to it as function to be implemented in next release. Hence, I would like if you can convert the original Issue into a request for addition of the function. 

Meanwhile you can work on other functions or request them to be added in a future release. Apologies for the inconvenience.

**Comment by ream-kh** [comment]
Hi @Auxia. How I can know on which functions I can work on?

**Comment by Auxia** [comment]
Generally if a function exists in the ivy framework then you can work on it. [Check in this folder](https://github.com/unifyai/ivy/blob/ce0da78a16018f2d8de52f92a840c907ab7697c9/ivy/functional/ivy)

**Pull request closed without merging**
