### PR TITLE
Paddle random_normal

### LINKED ISSUE #14429: random_normal

### PR DESCRIPTION
**Pull request by Ishaan-Chandak**
close #14429

### CODE REVIEW

**Comment by Ishaan-Chandak** [comment]
Greetings, @MahmoudAshraf97  Please let me know which exact test case for this P.R. is failing so that I can make the necessary adjustments.

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hello, I havent tested it completely but I notice some failure points and they are all related to dtypes, please run the hypothesis tests and the test cases for failure will pe produced

**Comment by Ishaan-Chandak** [comment]
Hii @MahmoudAshraf97 Sorry for the delay but I am not able to code because of some error appearing while I was rebuilding my container in docker. I ll make the changes as soon as possible.
Apologies

**Comment by MahmoudAshraf97** [comment]
Sorry to close this PR but it was implemented already

**Pull request closed without merging**
