### PR TITLE
EHN: adding square in paddle math.py

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
square from issue  #17461

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by xoiga123 — APPROVED** [review]
LGTM! Thank you for contributing :heart:

**Comment by xoiga123** [comment]
@MuhammadNizamani Eh please resolve conflicts, ty

**Comment by MuhammadNizamani** [comment]
On it

**Comment by MuhammadNizamani** [comment]
@xoiga123 merge conflict resolved

**Pull request merged**
