### PR TITLE
Linspace #316

### PR DESCRIPTION
**Pull request by yudhid**
Fixex #316 linspace in creation.py

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
Kindly fix the lint errors

**Comment by RickSanchezStoic** [comment]
@yudhid Can you please update your pr with the requested changes?

**Comment by yudhid** [comment]
@RickSanchezStoic I have update my Pull Request on my ivy fork repository, please kindly to check my work, it's really helpful for me and if there are any mistake, please mention so I could fix it as soon as possible. Thank You.

**Comment by RickSanchezStoic** [comment]
@yudhid I think you have made changes beyond the `linspace` function. You would need to undo these changes and make changes only to the `linspace` function. Let me know if you need any help regarding the same.

**Comment by yudhid** [comment]
@RickSanchezStoic Thank you for your explanation, I have question regarding on ivy function, I have downloaded ivy-core, but there are several function that are not included in it, are there any link to download the function such as ivy.backend_handler? or it should be copy paste one by one into my local python?

I've tried run into my visual studio code, but I always stumble into run this function, its really hard for me to fix the main problem.

**Comment by RickSanchezStoic** [comment]
> @RickSanchezStoic Thank you for your explanation, I have question regarding on ivy function, I have downloaded ivy-core, but there are several function that are not included in it, are there any link to download the function such as ivy.backend_handler? or it should be copy paste one by one into my local python?
> 
> I've tried run into my visual studio code, but I always stumble into run this function, its really hard for me to fix the main problem.

Hi @yudhid the ivy-core is not the latest version of ivy, for you to work on ivy, you should use the ivy repo to work on the latest ivy tasks. Also, seems like you might have to undo all the changes to `[ivy/functional/backends/torch/creation.py]` . Feel free to ask any more questions that you might have.

**Comment by yudhid** [comment]
@RickSanchezStoic Thank you for your information and help, I have clone the latest ivy repo in my local. I will update my PR soon.

**Comment by yudhid** [comment]
@RickSanchezStoic Hai, I have undo my fork repository and update PR on linspace, please kindly to check my work. Thank you.

**Comment by RickSanchezStoic** [comment]
@yudhid you need to update your local fork of ivy. Try running bash ./merge_with_upstream.sh before making any changes and then redo the changes only to the `linspace` function as required. I have updated this for now, but your fork is not updated and so any further change you make will cause conflicts. Let me know if you have any doubts.

**Comment by yudhid** [comment]
@RickSanchezStoic I have updated my local fork of ivy with merge_with_upstream.sh. I have a question about linspace method, why in linspace there are strt or stp command then at last paragraph, there is for strt in start or stp in stop in zip?

**Comment by RickSanchezStoic** [comment]
Hi, @yudhid I would suggest you re-work your branch and update it, and then start working on this function, your branch is way too behind the master and hence so many conflicts.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
