### PR TITLE
Updated creation py

### PR DESCRIPTION
**Pull request by ManasVardhan**
closes https://github.com/unifyai/ivy/issues/13193
added docstring to meshgrid function in creation.py in data_classes

### CODE REVIEW

**Comment by ManasVardhan** [comment]
#13193

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
I think that you are supposed to make changes to the docstring of meshgrid function in ivy/functional/ivy/creation.py, not in other places like in the container folder or set.py. Please move your changes to the correct place. Thanks!

**Comment by ManasVardhan** [comment]
Thank you for the clarification Daniel, I think those two files already have correct docstrings, hence I'll close my PRs. 
These function reformatting issues were still open in the ToDo list. Please mark them completed to avoid any confusion further. 
I'll go and fix other issues. 
Thanks again!

**Comment by Daniel4078** [comment]
> Thank you for the clarification Daniel, I think those two files already have correct docstrings, hence I'll close my PRs. These function reformatting issues were still open in the ToDo list. Please mark them completed to avoid any confusion further. I'll go and fix other issues. Thanks again!

no, the function is still not fully documented as it lacks some other examples like for nestable functions which accept more than one argument, there should also be an example that passes in ivy.Container instances for multiple arguments

**Comment by Daniel4078** [comment]
please refer to this doc: https://lets-unify.ai/ivy/overview/deep_dive/docstring_examples.html here for examples and guidlines about what kinds of examples and other stuffs are needed.

**Comment by ManasVardhan** [comment]
Okay, I'll update the docstring and push again. Thanks.

**Pull request closed without merging**
