### PR TITLE
Numpy Frontend tri, triu

### LINKED ISSUE #11066: triu

### LINKED ISSUE #11070: tri

### PR DESCRIPTION
**Pull request by NouranYoussef**
closes #11070
closes #11066

### CODE REVIEW

**Comment by NouranYoussef** [comment]
closes #11066

**Comment by Daniel4078** [comment]
Sorry for the delay, there seems to be some problem with the automatic CI test, so can you try to update your branch and make a commit to restart the checks? Thank you.

**Comment by NouranYoussef** [comment]
Changes pushed to branch @Daniel4078

**Review by Daniel4078 — APPROVED** [review]
Well, even though the test was canceled due to the fact that someone was trying to fix the problem happened before, but I did not find any problem with the code. Well done.

**Pull request merged**
