### PR TITLE
Adding Missing ONNX Functions

### LINKED ISSUE #14668: STFT

### PR DESCRIPTION
**Pull request by KevinUnadkat**
Closes #14668

### CODE REVIEW

**Comment by KevinUnadkat** [comment]
@Aarsh2001 can u pls review

**Review by Aarsh2001 — CHANGES_REQUESTED** [review]
I recommend implementing these functions in the backends, and suggest reviewing the "Deep Dive" section of the documentation to gain an understanding of how Ivy works. Specifically, please focus on the sections covering `Function Types, Ivy Functional, Backend APIs, Frontend APIs`, and extending support to the `Experimental API`.

Ideally, you should only implement everything compositionally if none of the backends have the specific function. However, since an implementation of `stft` already exists for `Torch, TensorFlow, and Jax`, you should implement this function compositionally in `Numpy` within the `Numpy` backend. Additionally, please search for an implementation for the Paddle backend. Finally, simply return the function inside the `functional API` using the `current_backend(<input>).stft(<arguments>)` method.

You will have a better understanding of the above when you understand how functions work in Ivy. The "Deep Dive" is currently the best resource for this, and feel free to ask any questions in the corresponding Discord channels. 🙂

**Comment by KevinUnadkat** [comment]
hyy @Aarsh2001 i checked for paddle , there exists an implementation of `STFT` in `paddle`

**Comment by KevinUnadkat** [comment]
hyy @Aarsh2001 i checked for paddle , there exists an implementation of `STFT` in `paddle`

**Comment by KevinUnadkat** [comment]
hyy @Aarsh2001 i checked for paddle , there exists an implementation of `STFT` in `paddle`

**Comment by KevinUnadkat** [comment]
hyy @Aarsh2001 made the changes and also checked for paddle , there exists an implementation of `STFT` in `paddle` .

**Review by Aarsh2001 — COMMENTED** [review]
Hey @KevinUnadkat,

It seems like you still don't understand the essence of Ivy, so here's what you need to do:

Create a file called `demo.py` in the main `Ivy` directory.

Execute the following code in the file:

```
import ivy
ivy.set_backend("tensorflow")

x = ivy.random_uniform(shape=(32, 224, 224, 3))
frame_step = (2, 4)
print(ivy.functional.experimental.stft(x, frame_step))
```

Run the above code with different backends - do `ivy.set_backend("torch")`, `ivy.set_backend("jax")`, `ivy.set_backend("paddle")`.

You need to understand backend specific implementations, which the functional API abstracts. You'll understand better when you execute the code above. **Hint - It will  ❌**

Before requesting another review, I suggest you do the following:

1. Go through the Deep Dive sections above (again).
2. Look at how functions are implemented in Ivy. You can take any function, for example, `matmul`.
3. For a clearer understanding, you can also look at my PR from the ONNX word document.
4. Implement a test for your function.
5. Implement static and instance methods in the array and container specific files.
6. Once you're done with the above, create a demo file, and test for all backends like I mentioned above. You should get an output for each.
7. Make sure that the test function you write passes locally.
8. If step 6 fails or you're having difficulty implementing the tests, you can contact me again or request a review on your PR. When you do request a review, make sure you have completed step 5. I won't be reviewing this PR before that.

Best of Luck 🙂

**Comment by KevinUnadkat** [comment]
commenting this to just add some activity

**Comment by KevinUnadkat** [comment]
add comment to add activity

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by KevinUnadkat** [comment]
Still working on this pr

**Comment by KevinUnadkat** [comment]
adding this comment for activity , still working on this task

**Pull request closed without merging**
