### PR TITLE
Added gelu activation function and test to PaddlePaddle frontend

### PR DESCRIPTION
**Pull request by sachelsout**

### CODE REVIEW

**Comment by sachelsout** [comment]
Close #15945

**Comment by sachelsout** [comment]
Hello @Infrared1029 , could you please review my PR ? :)

**Comment by Infrared1029** [comment]
Hey @sachelsout! sorry for the late reply, the test appears to fail, (from the CI, it's probably due to huge values being converted to `inf` by some frameworks), can you make sure all tests are passing? one way to alleviate this issue is to set a safety factor in the test.

**Comment by sachelsout** [comment]
> Hey @sachelsout! sorry for the late reply, the test appears to fail, (from the CI, it's probably due to huge values being converted to `inf` by some frameworks), can you make sure all tests are passing? one way to alleviate this issue is to set a safety factor in the test.

Hello @Infrared1029 , thank you for reviewing the code and suggesting to add safety factor in the test. I ran the tests after making changes, and all the test cases are passing ! :)

**Comment by Infrared1029** [comment]
lgtm! thanks for your contribution @sachelsout! again sorry for the late reply, merging!

**Comment by sachelsout** [comment]
> lgtm! thanks for your contribution @sachelsout! again sorry for the late reply, merging!

It's completely fine ! Have a good day !! :)

**Pull request merged**
