### PR TITLE
Reformat set #794 - unique_values #9390

### PR DESCRIPTION
**Pull request by chkoutsis**

### CODE REVIEW

**Comment by aditya-hari** [comment]
Hey! Is this PR still work in progress?  
 
 And could you please link the issue in the comments? Refer to the contributing guide in case you're unclear how this should be formatted.

**Comment by chkoutsis** [comment]
Hello!

The current results of this PR:  3 failing, 13 skipped, and 110 successful checks

Also, the issue link: https://github.com/unifyai/ivy/issues/9390

**Comment by chkoutsis** [comment]
add_reformatting_checklist_<Reformat set>

**Comment by aditya-hari** [comment]
You haven't actually changed anything in the commit except adding spaces in a few places. Please read the description given in #794 to understand what is required for this, and refer to the other subtasks linked there for examples of what is needed.

**Comment by chkoutsis** [comment]
Thank you for your response and for informing me. 

Actually I created the PR because of the 7-days deadline.

**Comment by aditya-hari** [comment]
No problem :slightly_smiling_face:! The 7 day deadline is only for accepting the Upwork offer, you are free to approach the task at your pace once you've done that.

**Comment by chkoutsis** [comment]
That sounds great! 

Thank you for informing me.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by chkoutsis** [comment]
I would like to continue working on this PR.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by Monsurat-Onabajo** [comment]
can i work on this issue?

**Pull request closed without merging**
