### PR TITLE
tanh #1643

### PR DESCRIPTION
**Pull request by soran-ghaderi**
tanh #1643 - Added to the PyTorch frontend - pointwise_ops.py

### CODE REVIEW

**Comment by soran-ghaderi** [comment]
Hi @bicycleman15,could you please review this pull request?

**Comment by bicycleman15** [comment]
@soran-ghaderi sorry for the late reply. Will get this reviewed asap.
@jiahanxie353 do you mind reviewing this ? got a little too much on my plate currently 😅

**Review by jiahanxie353 — COMMENTED** [review]
Hello, sorry for the late reply.
As ivy is currently focusing on getting all the backends working, we are now putting back the frontends implementations. So I'm afraid any frontend PR will not be able to get integrated for at least one week.
If you would like to continue contributing and would rather not wait, could you please choose a reformat docstring task? You can create a new PR and we will review it asap :)

**Comment by soran-ghaderi** [comment]
At this time I'm not sure if I can make time; so I'd prefer to wait till the next week.

**Comment by jiahanxie353** [comment]
This task is not open yet - but it will be in a few days. I will review the PR once it's open. If you would rather get a faster response, then please create a PR for the reformatting task. Thanks! :)

**Comment by jiahanxie353** [comment]
I will close it as every frontend task is not open yet, we can re-open it again once the task is made an open task.
Thanks for your understanding :)

**Comment by soran-ghaderi** [comment]
> I will close it as every frontend task is not open yet, we can re-open it again once the task is made an open task.
> 
> Thanks for your understanding :)

The task has been opened now!
Would you please re-open the pull request?

**Pull request closed without merging**
