### PR TITLE
feat: Add `fftn` to ivy functional API

### LINKED ISSUE #19200: fftn

### PR DESCRIPTION
**Pull request by akshatvishu**
Close #19200

### CODE REVIEW

**Comment by akshatvishu** [comment]
Sorry, Felix! @hirwa-nshuti  was busy helping folks solve their bugs on Discord. I couldn't respond as quickly as I wanted to, but I've resolved the merge conflicts. Also, I was thinking of adding a `TODO` note for TensorFlow backend because I want to thoroughly check it with other backend regarding the `axis` and `norm` functionality that we've added compositionally.  Additionally , we should track this  `issue` raised at `TensorFlow` which will add `Pocket_FFT`  successor to tensorflow and with that these additional parameters: <https://github.com/tensorflow/tensorflow/issues/56685>

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey most of the implementation looks great😂
However some assertion errors are still present can you try to increase the tol values🤞

And resolve the merge conflicts issues with array API tests submodule😊
Thanks

**Comment by NripeshN** [comment]
Hey @akshatvishu,
Could you please solve the merge conficts

**Comment by akshatvishu** [comment]
> Hey @akshatvishu, Could you please solve the merge conficts

Sure; will do it later today

**Pull request closed without merging**
