### PR TITLE
solve to conform to array API standard

### PR DESCRIPTION
**Pull request by Aarsh2001**

### CODE REVIEW

**Comment by Aarsh2001** [comment]
although a partial solution, I had some doubts with the tests -:

Torch error -: RuntimeError: Boolean value of Tensor with no values is ambiguous https://github.com/unifyai/ivy/issues/628
TensorFlow error - : AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'setitem'
jax error : FailedHealthCheck

Requesting Review @ivy-seed @djl11 @saeedashrraf @mattbarrett98

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @Aarsh2001 , thank you for your effort! You should not be raising exceptions in the function. Instead, you should handle the input properly to avoid those exceptions getting triggered. Can you please remove those?

**Comment by Aarsh2001** [comment]
> Hello @Aarsh2001 , thank you for your effort! You should not be raising exceptions in the function. Instead, you should handle the input properly to avoid those exceptions getting triggered. Can you please remove those?

Alright, will do that

**Comment by Aarsh2001** [comment]
will make new pull request

**Pull request closed without merging**
