### PR TITLE
Added torch.norm in the functional frontend

### LINKED ISSUE #11936: norm

### PR DESCRIPTION
**Pull request by AmgadHasan**
- Implemented the `torch.norm` function in `ivy/functional/frontends/torch/linalg.py`

- Implemented a test for it named `test_torch_norm` in `ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py`

Close #11936

### CODE REVIEW

**Comment by danielmunioz** [comment]
Hey @AmgadHasan! Thanks for contributing! I left a quick review on line 107 of `ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py` could you please fix that and then run the tests? It looks like the testing functions may generate an invalid combination of arguments such as:
 
```
x = torch_front.tensor([[[-1.]]], dtype=torch_front.float32)
ord = 1
keepdim = False
``` 

Could you please fix those issues as well and make sure the tests are passing?
Other than that the PR seems to be in good shape!

Feel free to ask any questions!
Thanks! :)

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by AmgadHasan** [comment]
> Hey @AmgadHasan! Thanks for contributing! I left a quick review on line 107 of `ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py` could you please fix that and then run the tests? It looks like the testing functions may generate an invalid combination of arguments such as:
> 
> ```
> x = array([[[-1.]]], dtype=float32)
> ord = 1
> keepdim = False
> ```
> 
> Could you please fix those issues as well and make sure the tests are passing? Other than that the PR seems to be in good shape!
> 
> Feel free to ask any questions! Thanks! :)

Hello Daniel

Thank you for reviewing my PR. However, I can't find your review of line 107 in the test module. I can't find any comments on that file.

**Comment by danielmunioz** [comment]
Hey @AmgadHasan! You can find the review by going to the 'Files Changed' tab here on Github, I'll ping you there as well

**Comment by AmgadHasan** [comment]
> Hey @AmgadHasan! You can find the review by going to the 'Files Changed' tab here on Github, I'll ping you there as well

Hello @danielmunioz I checked and still can't find it.

Here's what it looks like to me 
image

**Comment by danielmunioz** [comment]
That's so weird 🤔, I can see it on my end, guess it's just a github bug then
Anyways, for line 107 of `ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py` the name of the input argument there should be 'A' instead of 'tensor', those testing arguments should match the function ones so that the test suite is able to properly recognize them

After that could you please run the test and make sure it's passing for your function?

If you have any questions please feel free to reach out! :)
Thanks!

**Comment by Daniel4078** [comment]
I found that this pull request https://github.com/unifyai/ivy/pull/16729 is also dealing with this task. It seems like there are some misunderstanding here.

**Comment by AmgadHasan** [comment]
@danielmunioz Looks like my PR finally passed all test! 
Do you have any more changes or feedback?

**Comment by danielmunioz** [comment]
Hey @AmgadHasan, sorry but the tests are not passing yet, could you please run them locally and make sure they're passing? The github are random across the repo and examples so they sometimes miss some important cases, that's why we always try to get the test passing locally first, if you have any 

Also, we should add more parameters to the testing values of `ord` such as `-1` and `-2`, as the [original implementation](https://pytorch.org/docs/stable/generated/torch.linalg.norm.html) seems to be able to handle those!

If there you have any questions feel free to reach out!
Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
