### PR TITLE
Added inverse_mdct

### PR DESCRIPTION
**Pull request by YahyaRamzy**
inverse_mdct #21185

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Hi, You might need to add the tests for this PR

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by YahyaRamzy** [comment]
> Hi, You might need to add the tests for this PR

I added the test , but i have a problem passing the test beacuse inverse_mcdt doesnt exist in the backend? Is this true or is my code bugged ?

**Comment by a0m0rajab** [comment]
Thnak you for that, I am not sure about the tests,would love to have an input from a core contributor or Ivy worker, I am new like you :)  

One more thing, is that: you can change the `inverse_mdct` in the body of the PR to close #ISSUE_NUMBER 
this will help to auto close the issue. 

See [Ivy Docs](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues), and [GitHub docs ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for reference.

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey! Thanks for the hard work! The `inverse_mdct` is not yet available in the ivy API, you should either implement this frontend function compositionally or propose the `inverse_mcdt` to be included into the ivy API. The tests also shouldn't include anything of the native imports, thanks!

**Comment by juliagsy** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
