### PR TITLE
Reformatted stable_divide

### LINKED ISSUE #2157: stable_divide

### PR DESCRIPTION
**Pull request by JamieLine**
Fixes #2157

### CODE REVIEW

**Comment by Oxbeefbabe** [comment]
Hi @JamieLine sorry for keeping you waiting,

Can you please ensure that all of the checks passing in the master branch are also passing for your PR? I'd recommend that you've pulled the most recent commits, or merged upstream if you are working on a fork. I'd also go over your docstrings and make sure they are passing. You can check the Github checks to find the checks relating to docstring tests and make sure they are passing or if not, you can open the details and have a closer look.

Mention me when you are ready to have another look :)

Thank you

**Comment by JamieLine** [comment]
Hi @Oxbeefbabe no worries about the wait, I've added some more changes to make it pass more of the tests. It now passes the docstring tests but for some reason fails test-fn-statistical-numpy when master isn't and I'm not sure why, I've asked in the discord and I'll see if I can fix it.

**Comment by JamieLine** [comment]
Hi @Oxbeefbabe, as far as I can tell this branch now matches the tests with master up to some tests only being run on master such as `github-release/release-if-tagged-commit`. Certainly all of the docstring tests either pass or fail on code which is not included in this commit.

**Comment by Oxbeefbabe** [comment]
Ok, that seems all fine to me, the last thing is to make sure that the lint / check-formatting tests are passing. These should be pretty easy to fix. Once that is done I'll go ahead and accept the PR and merge your changes :)

**Comment by JamieLine** [comment]
@Oxbeefbabe I've checked the error message from lint / check-formatting and it only shows errors in files not touched by this commit, specifically `ivy_tests/test_ivy/helpers.py` and `ivy_tests/test_ivy/conftest.py` which is the same as the master branch (the actual text of the error message is identical to the master branch error), should I still go and edit them to work? It just seems strange to edit the tests as part of a reformatting operation.

**Comment by Oxbeefbabe** [comment]
I've had a look and that does seem to be the case. Everything looks good to me, merging your PR now :)

**Pull request merged**
