### PR TITLE
Cummax

### LINKED ISSUE #12998: cummax

### PR DESCRIPTION
**Pull request by AkshayC2001**
Close #12998

### CODE REVIEW

**Comment by chanpreet007** [comment]
Did you implemented this function?

**Comment by AkshayC2001** [comment]
> Did you implement this function?

yes?

**Comment by chanpreet007** [comment]
I see you have taken this function as subtask in the past. Were you able to implement  and add this through pull request?

**Comment by AkshayC2001** [comment]
> I see you have taken this function as subtask in the past. Were you able to implement and add this through pull request?

i am implementing this function for first time

**Comment by chanpreet007** [comment]
Are you sure, This function should be here? location wise and not in miscellaneous_ops?

**Comment by AkshayC2001** [comment]
> 

yes

**Comment by AkshayC2001** [comment]
> Are you sure, This function should be here? location wise and not in miscellaneous_ops?

sorry for the late reply but i am implementing instance of that function. real function is already there in codebase

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
