### PR TITLE
Added tril_indices_from to numpy frontend. Issue:

### LINKED ISSUE #19676: tril_indices_from
implement numpy.tril_indices_from

### PR DESCRIPTION
**Pull request by Muradmustafayev-03**
Close #19676

### CODE REVIEW

**Comment by Muradmustafayev-03** [comment]
Btw is arr asserted to be 2-dimensional or should I assert it inside the fuction itself?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Muradmustafayev-03** [comment]
@ivy-leaves description is changed. Anything else? Why are those 2 hecks failing?

**Comment by Muradmustafayev-03** [comment]
Hello, @RickSanchezStoic . Please review and merge if sufficient

**Comment by RickSanchezStoic** [comment]
@Muradmustafayev-03 Why have you defined the same function twice in two different files?

**Comment by Muradmustafayev-03** [comment]
@RickSanchezStoic I noticed that some other functions are duplicated in these 2 files, so I thought it's also necessary for this function. If needed I can remove it from one of the files, just tell me in which of those files to keep it. (probably in indexing-like operations, but still i'm waiting for you to tell)

**Comment by Muradmustafayev-03** [comment]
@RickSanchezStoic and also should I write the test for that function as well?

**Comment by Muradmustafayev-03** [comment]
Dear @RickSanchezStoic , please read answer my previous comments, so that i can update my PR.

**Comment by Muradmustafayev-03** [comment]
Dear @RickSanchezStoic , please read answer my previous comments, so that i can update my PR.

**Comment by Muradmustafayev-03** [comment]
@RickSanchezStoic updated :)

**Comment by RickSanchezStoic** [comment]
@Muradmustafayev-03 Can you go through the `intelligent-tests-pr / run_tests (1) (pull_request)` and try fixing the errors?

**Pull request closed without merging**
