### PR TITLE
can_cast adhering to Array API Standard

### PR DESCRIPTION
**Pull request by sohil-hub**

### CODE REVIEW

**Comment by sohil-hub** [comment]
Hey @mattbarrett98 ,
Please have a look.
And there is no open task in Array API, Is there anything else for me? Please let me know.

**Comment by mattbarrett98** [comment]
There shouldn't be any `/` in the function arguments. Also you need to uncomment the function in data_type_functions.txt so that the tests run.

**Comment by mattbarrett98** [comment]
All of the tests are failing

**Comment by sohil-hub** [comment]
> All of the tests are failing

yeah, will try to fix it.

**Comment by sohil-hub** [comment]
Hey @mattbarrett98, 
 for from_ = bool and to=int, all framework methods returns True.
 image

But While running the tests I got this error. Can you assist me please. 
image
image

**Comment by mattbarrett98** [comment]
So you would need to add something like `if from_ == bool and to == int: return False` to each backend function to get the desired behaviour

**Comment by sohil-hub** [comment]
Failed again. 🙂

**Comment by mattbarrett98** [comment]
So you will need to continue editing the functions to fix whatever errors you are getting 🙂

**Comment by sohil-hub** [comment]
> So you will need to continue editing the functions to fix whatever errors you are getting 🙂

Sure, Can you please check the return statement of the can_cast function from ivy/functional/ivy/data_type.py?
Because I don't know how can we set the backend framework from dtype?

**Pull request merged**
