### PR TITLE
Added Sum to raw_ops

### LINKED ISSUE #5316: Sum

### PR DESCRIPTION
**Pull request by KareemMAX**
Close #5316

### CODE REVIEW

**Comment by KareemMAX** [comment]
- [ ] #5316

**Comment by RickSanchezStoic** [comment]
Hi @KareemMAX can you try resolving the merge conflicts? Also, the test that you have implemented seems to be failing. Can you try looking into it? Let me know if you need help with any of this.

**Comment by KareemMAX** [comment]
Hey @RickSanchezStoic, I have resolved the conflicts and tried to rerun the tests, I'm running them with `--backend=all --num-examples=50` and rerun them couple of times to make sure they don't fail and they didn't. Could you please provide me with the failed falsifying example?

Also, here is a screenshot of my test:
image

**Comment by RickSanchezStoic** [comment]
also I would suggest to not specify the `num-examples` as it might lead to some corner cases getting missed on your end

**Comment by KareemMAX** [comment]
Hey @RickSanchezStoic I tried removing `num-examples` and still didn't have any problems running the code. Actually I run `test-frontend-tensorflow` myself locally and found out that it is not related to my specific function. And there was about 180 failed test over 668.

This is something I'm actually interested in fixing as it is annoying seeing a failed test that isn't your fault, but I think this failed test is not related to my function.

**Comment by RickSanchezStoic** [comment]
Hi @KareemMAX, yeah the errors don't seem to be from your function. Just fix the conflicts and then it should be good to go ig.

**Comment by KareemMAX** [comment]
@RickSanchezStoic conflicts are now resolved, feel free to merge

**Pull request merged**
