### PR TITLE
Added neg method to tensor class of frontend.paddle.tensor.tensor

### LINKED ISSUE #16747: neg

### PR DESCRIPTION
**Pull request by nikita-jare**
Close #16747

### CODE REVIEW

**Comment by rishabgit** [comment]
Hi @nikita-jare, thanks for looking into this :)
Could you please resolve the conflicts? Apart from that, everything looks good to me

**Comment by nikita-jare** [comment]
Thank you @rishabgit. I have resolved the conflicts. Please check.

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi @nikita-jare, you seem to be accidentally editing the unrelated ivy_tests/array_api_testing/test_array_api submodule. Could you please undo the changes?
It looks like some tests are failing, which might be due to above edits, but in case they aren't, could you please fix those too?
Feel free to request a review afterwards. Thanks! :)

**Comment by rishabgit** [comment]
lgtm! thanks for adding this! :)

**Pull request merged**
