### PR TITLE
added numpy vander frontend function + frontend test

### LINKED ISSUE #9753: vander

### PR DESCRIPTION
**Pull request by Giac3**
Close #9753

### CODE REVIEW

**Comment by Giac3** [comment]
- #9753

**Comment by Giac3** [comment]
Hey @V-G-spec , I am getting the following error I am not sure what it is pointing at.
[ exit 1
 shell: /usr/bin/bash -e {0} ]
The lint errors are appearing from files unrelated to my changes, and all four pytest tests are passing in my local env.

**Comment by Giac3** [comment]
Hey @V-G-spec , I am getting the following error I am not sure what it is pointing at.
[ exit 1
 shell: /usr/bin/bash -e {0} ]
The lint errors are appearing from files unrelated to my changes, and all four pytest tests are passing in my local env.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Giac3** [comment]
still working

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by V-G-spec** [comment]
Hey @Giac3, apologies for the late reply. I don't think any of the errors are caused by the changes in your files, though I would request you to double check the same.

**Comment by Giac3** [comment]
Hello @V-G-spec , apologies I have been very busy as of late, no worries I will go over everything tomorrow morning.

**Comment by V-G-spec** [comment]
Sure thing

**Comment by Giac3** [comment]
Hello @V-G-spec, could you let me know why the tests are failing please, so I can fix anything that is happening on my end this weekend.

**Pull request closed without merging**
