### PR TITLE
add solve to tensorflow

### PR DESCRIPTION
**Pull request by PatricYan**
- [ ] #3322

### CODE REVIEW

**Comment by PatricYan** [comment]
Hi @VedPatwardhan , I have resolved the conflict, would you like to make a review for the PR?

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hi @PatricYan, thanks for contributing! The changes seem good to me. But even if the frontend tests are currently passing for your function, they are bound to fail at some point in the future, because singular matrices should not be generated for this function and the handling for the same needs to be added during data generation. Please refer [`test_solve`](https://github.com/unifyai/ivy/blob/3867b8933e076906e576feeee4ad00838d72074d/ivy_tests/test_ivy/test_functional/test_core/test_linalg.py#L643) which is used to test the `ivy.solve` function to see the way it's handled there and replicate the same for your function. 
Feel free to re-request my review once you're done with the changes.
Let me know if you have any questions. Thanks 🙂

**Comment by PatricYan** [comment]
> Hi @PatricYan, thanks for contributing! The changes seem good to me. But even if the frontend tests are currently passing for your function, they are bound to fail at some point in the future, because singular matrices should not be generated for this function and the handling for the same needs to be added during data generation. Please refer [`test_solve`](https://github.com/unifyai/ivy/blob/3867b8933e076906e576feeee4ad00838d72074d/ivy_tests/test_ivy/test_functional/test_core/test_linalg.py#L643) which is used to test the `ivy.solve` function to see the way it's handled there and replicate the same for your function. Feel free to re-request my review once you're done with the changes. Let me know if you have any questions. Thanks 🙂

Hi @VedPatwardhan , I have added a filter in the generated matrices as you mentioned above

**Review by VedPatwardhan — APPROVED** [review]
lgtm! Thanks for contributing 🙂

**Pull request merged**
