### PR TITLE
Added divide method in the PyTorch frontend

### PR DESCRIPTION
**Pull request by he11owthere**
closes https://github.com/unifyai/ivy/issues/21752

image

### CODE REVIEW

**Comment by he11owthere** [comment]
@AlexandraPosta Please add 'bfloat16' in the `with_unsupported_dtypes` decorator before running the tests until the issue with `ivy.Array.repr` method has been fixed as mentioned by Ved in https://github.com/unifyai/ivy/pull/21447. Thank you! 🙂

**Comment by AlexandraPosta** [comment]
Hello! Please have another look at the parameters for the test function.

**Comment by he11owthere** [comment]
> Hello! Please have another look at the parameters for the test function.

Hello @AlexandraPosta! Thank you for your input. I've reviewed the parameters for the test function once more, and everything appears to be in order with my code. If you have any further suggestions or concerns, please let me know. 😊

**Comment by AlexandraPosta** [comment]
Apologies about that. I must have read something wrong. Thank you for your contribution!

**Pull request merged**
