### PR TITLE
Atan2

### LINKED ISSUE #12012: atan2

### PR DESCRIPTION
**Pull request by shreyjain26**
Close #12012

### CODE REVIEW

**Comment by shreyjain26** [comment]
Hi @Infrared1029 , could you please review this? 
All tests are passing, I think the pr could be merged.

**Comment by edith007** [comment]
Hi @shreyjain26 👋
I think atan2 is already implemented in this PR. https://github.com/unifyai/ivy/pull/13924

**Comment by shreyjain26** [comment]
> Hi @shreyjain26 👋
> I think atan2 is already implemented in this PR. https://github.com/unifyai/ivy/pull/13924

Hi @edith007 , the implementation you have done is in math.py, mine is for raw_ops.py.

**Comment by edith007** [comment]
Thanks for clarifying, Shrey! I didn't realize that you were working on a different implementation of atan2 in raw_ops.py.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
