### PR TITLE
Scan function's test

### PR DESCRIPTION
**Pull request by TimothyElems**
https://github.com/unifyai/ivy/issues/17449

### CODE REVIEW

**Comment by TimothyElems** [comment]
[Add Control flow operators to Jax Frontend #1579](https://github.com/unifyai/ivy/issues/1579)

**Comment by TimothyElems** [comment]
https://github.com/TimothyElems/ivy/commit/cf28c67431783a6eef59c78adcd13af71b3f22cc

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Sam-Armstrong** [comment]
Duplicate of https://github.com/unifyai/ivy/pull/17396

**Pull request closed without merging**
