### PR TITLE
issue18991. Added the tensorflow general function of make_ndarray

### LINKED ISSUE #18991: make_ndarray

### PR DESCRIPTION
**Pull request by janchilling**
closes #18991

### CODE REVIEW

**Comment by janchilling** [comment]
For the made_ndarray #18991, which is to implement general tensorflow frontend functions

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by janchilling** [comment]
I updated the PR description with the link to the issue, but according to the documentation I have to link the issue using the Development setting, but it does not allow me to edit.

**Comment by Daniel4078** [comment]
> I updated the PR description with the link to the issue, but according to the documentation I have to link the issue using the Development setting, but it does not allow me to edit.

Well, you are supposed to edit the initial discription of the pull request, not the comments or the title you know. But I have done that for you.

**Comment by Daniel4078** [comment]
add_frontend_checklist

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
You are not supposed to push changes to the content of .idea and runConfigurations folders you know. And you should also add a test for the function you add.

**Pull request closed without merging**
