### PR TITLE
Reformat einops rearrange in general

### LINKED ISSUE #9214: einops_rearrange
Reformat einops_rearrange in general

### PR DESCRIPTION
**Pull request by Alikerin**
Close #9214

### CODE REVIEW

**Comment by Pchatain** [comment]
Hey there! I'm not sure how this happened, but I submitted a PR with this same issue a week ago: https://github.com/unifyai/ivy/issues/8981

**Comment by Alikerin** [comment]
Hi @Pchatain The issue you created is not linked to the sub-task you worked on. At the time I chose the task, it was unassigned and currently, it is only assigned to me even after you got your PR merged.
@V-G-spec can you help reconcile this?

**Comment by V-G-spec** [comment]
Looping in @kurshakuz

**Comment by kurshakuz** [comment]
Hey @Alikerin! The original issue was created two weeks ago and was already merged. I did not notice your PR, so sorry for the confusion!

I would suggest you to undo the changes where you change (i.e. delete) already implemented parts and keep the `With varying pattern:` part as I think it can still be useful. Then we can merge your PR as well. If this PR is a part of our application challenge, we will get you passed, so no worries on that side. Hope it makes sense to you as well!

**Comment by Alikerin** [comment]
Yes @kurshakuz, that makes sense to me, thank you :)
I have an example that uses the `out` argument and another that uses `ivy.Container`, do you think it's a good idea to add them as well?

**Comment by Alikerin** [comment]
@kurshakuz I will appreciate if you can review the changes I have made

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Alikerin** [comment]
@V-G-spec @kurshakuz Please kindly take a look at this PR

**Comment by V-G-spec** [comment]
Hi @Alikerin! Sorry about the delay; this PR somehow slipped under the radar 😅
May I ask why you have made many changes to the imports? If it's all the same, can you revert those changes? Everything else looks good to go!

**Comment by Alikerin** [comment]
Hi @V-G-spec 
Thank you for taking a look. The changes in import were due to isort which I have in my VSCode; if you look closely it didn't change anything it only rearranged them

**Comment by Alikerin** [comment]
Hi @V-G-spec 
I have reverted the changes to imports as you suggested

**Comment by V-G-spec** [comment]
Thanks!

**Pull request merged**
