### PR TITLE
dev containers json

### PR DESCRIPTION
**Pull request by smruthi49**

### CODE REVIEW

**Comment by smruthi49** [comment]
Hi @aditya-hari ! Can you check this and help me through this?

**Comment by smruthi49** [comment]
@VedPatwardhan , why are there 10000 commits under my name?
What happened here?

**Comment by VedPatwardhan** [comment]
> @VedPatwardhan , why are there 10000 commits under my name? What happened here?

Hey @smruthi49, this was the last one of a series of `push --force` we did on master to remove unwanted files from the commit history, please follow the steps suggested in Dan's public announcement on discord a few weeks ago to get your branch up to date with the latest commit history. I'll also remove the automated review request from myself and @CatB1t, @aditya-hari is the reviewer assigned to your PR. Thanks 🙂

**Comment by hirwa-nshuti** [comment]
Hey this PR got heavily conflicted I am going to close it for now feel free to open another one

**Pull request closed without merging**
