### PR TITLE
Suwilanji Chisanga 

### PR DESCRIPTION
**Pull request by suwilanjichisanga**
Frontend  Pull request

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by suwilanjichisanga** [comment]
Front End PR

**Comment by RickSanchezStoic** [comment]
hi, @suwilanjichisanga can you please elaborate on the changes that you have made here?

**Comment by suwilanjichisanga** [comment]
> hi, @suwilanjichisanga can you please elaborate on the changes that you have made here?

@RickSanchezStoic I made some changes on the file(s) trignometric_functions.py 
I omitted argument "subok" as I read that it doesn't affect the result and should be omitted.  

In the file math.py I omitted the argument "name".... same reason as stated above.  

In the file ivy/functional/frontends/tensorflow/math.py 
 I added these lines of codes from line 94:   

"ret =" ivy.cumprod(x, axis=axis, exclusive=exclusive, reverse=reverse), x.dtype
        if reverse:
        return ivy.flip(ret, axis)
    return ret
    )

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by RickSanchezStoic** [comment]
@suwilanjichisanga I recommend creating an issue first and then trying contributing, check out the guide to know more https://lets-unify.ai/ivy/contributing.html . I will be closing this pr for now as we will be making some changes soon. Thanks!

**Pull request closed without merging**
