### PR TITLE
add diag function frontend Numpy

### PR DESCRIPTION
**Pull request by m7mdmosa27**
diag #6149

### CODE REVIEW

**Comment by m7mdmosa27** [comment]
Close #6149

**Comment by V-G-spec** [comment]
Hey, thanks for the submission. Can you please take a look at the merge conflict and mitigate the failing test case?

**Comment by m7mdmosa27** [comment]
Hey @V-G-spec, Thanks for the review. I solved the conflict, but don't know what you mean by mitigating the failing test case.
Can you explain more, please?

**Comment by V-G-spec** [comment]
Thank you for resolving the conflicts. There are failing tests in this merge request, and the formatting is inconsistent with the contributor's guide. Secondly, the changes should all be relevant to the function being worked on (You have changed 11 files, with differences of newline in most of them. Please rectify those)

**Comment by m7mdmosa27** [comment]
> Thank you for resolving the conflicts. There are failing tests in this merge request, and the formatting is inconsistent with the contributor's guide. Secondly, the changes should all be relevant to the function being worked on (You have changed 11 files, with differences of newline in most of them. Please rectify those)

Thank you for reviewing, I dropped all the commits and add new ones for two files only but the pull request is closed and I opened a new one.

**Comment by V-G-spec** [comment]
👍

**Pull request closed without merging**
