### PR TITLE
Added exp_ to torch frontend

### PR DESCRIPTION
**Pull request by fahad12398**
#14655

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
@RashulChutani the `run_tests_1` doesn't seem to be picking up the test for this, can you please look into this once ?

**Comment by RashulChutani** [comment]
Hi, I have rerun the Mapping Recalibration Algorithm, which will complete soon, after which the Workflow should work correctly.

**Comment by fahad12398** [comment]
@RickSanchezStoic The `lint / Check formatting / check-formatting` is failing. Can you guide me on this? Thanks.

**Comment by fahad12398** [comment]
@RickSanchezStoic ?

**Comment by fahad12398** [comment]
@RashulChutani, I have intentionally made the tests to fail and they were identified, but after reverting back it says 0 tests.

**Comment by RashulChutani** [comment]
Actually, Since the issue with intelligent testing was resolved after this PR was created, you will have to create a new PR.

**Comment by fahad12398** [comment]
> Actually, Since the issue with intelligent testing was resolved after this PR was created, you will have to create a new PR.

ok, I was thinking of trying to create a new PR. Thank you for your guidance and assistance.

**Comment by fahad12398** [comment]
Closing this PR because of the tests not being identified due to issue with intelligent testing. To solve the issue, Created a new PR #14947.

**Pull request closed without merging**
