### PR TITLE
lu

### PR DESCRIPTION
**Pull request by 29riyasaxena**
#1582

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Ookamice** [comment]
@29riyasaxena 
Thank you for your contributions, please could you check the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing.html); namely the section on writing tests.

**Comment by 29riyasaxena** [comment]
Thank you @Ookamice. I forgot to install pre-commit; hence "black" check was failing. I have fixed it now.

**Comment by 29riyasaxena** [comment]
Hi @Ookamice, could you please tell me if I need to make any other changes to the PR? Thank you!

**Comment by Ookamice** [comment]
@29riyasaxena 
Hiya, please could you read the contributor's guide I have linked in a previous message regarding writing tests. Every frontend function should be added with a corresponding testcase. You can see examples of testcases for jax.lax.linalg functions in ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_linalg.py.

**Comment by 29riyasaxena** [comment]
Thank you @Ookamice. I have updated the test cases. Please confirm if it's correct, or do I need to make some changes?

**Comment by 29riyasaxena** [comment]
Hello @Ookamice, I recently came across a couple of unsuccessful tests on my PR, which were mentioned in the GitHub Actions comments as potentially ignorable (run_tests (n)). Could you please tell me if this is something I need to address or if the PR is acceptable in its current condition?

**Comment by Ookamice** [comment]
@29riyasaxena
Sorry for the late review, for testing, it is advised to ignore the intelligent-test-pr as from my experience, it often leads to false negatives and sometimes the test you have written wouldn't be picked up. Rather, it is better to just run the pytest from command-line with: `python -m pytest -v ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_linalg.py::test_jax_lu`. Let me know if it passes locally for you and I'll test it on my end too

**Comment by 29riyasaxena** [comment]
> @29riyasaxena Sorry for the late review, for testing, it is advised to ignore the intelligent-test-pr as from my experience, it often leads to false negatives and sometimes the test you have written wouldn't be picked up. Rather, it is better to just run the pytest from command-line with: `python -m pytest -v ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_linalg.py::test_jax_lu`. Let me know if it passes locally for you and I'll test it on my end too.

Thank you, @Ookamice, for your quick response. I have verified that all the test cases have passed locally for me. Please check if it's the same for you.

**Comment by 29riyasaxena** [comment]
Hi there @Ookamice, I have already verified the thing you have asked for, that is, running the code with pytest on the command line is running successfully. Please let me know if I need to make any other changes.

**Review by Ookamice — CHANGES_REQUESTED** [review]

**Comment by Ookamice** [comment]
@29riyasaxena 
Ah sorry about that, looks like my comments were pending. I have just requested those changes, let me know if you have any questions and I'll be glad to help. 👍

**Comment by 29riyasaxena** [comment]
Hi @Ookamice, I noticed that the backend of jax.lu still needs to be implemented. The issue of test cases being skipped is must be because of this. Please advise me on how to proceed further.

**Comment by 29riyasaxena** [comment]
Yes, I am looking at the backend. I am new to ivy and I think I'll take some time to do it.

**Comment by Ookamice** [comment]
@29riyasaxena 
No pressure! Adding support to the backend is completely optional so don't feel like you have to do it when you're using an ivy function with some missing implementations. As long as your code works cleanly on the ones with back-end support, it would be good 💯

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @29riyasaxena 
Is this still under works?
Currently the test is very limited as the arrays generated is forced to have a square shape of only two dims (using lamba map). It should be an array of any shape (..., m, n) as in jax docs.

**Comment by 29riyasaxena** [comment]
Hi @Ishticode, sorry, I'm not actively working on this due to some academic commitments.

**Comment by Ishticode** [comment]
Thanks for the message. I will close it for now then @29riyasaxena 
Please feel free to reopen whenever you like. Thank you very much :)

**Pull request closed without merging**
