### PR TITLE
Reformat element-wise function isnan()

### PR DESCRIPTION
**Pull request by abekek**
#2217

### CODE REVIEW

**Comment by sreegandh804** [comment]
Hey @abekek , i would suggest you try and get the numpy docstrings passing , after which you could let me know.

**Comment by abekek** [comment]
@sreegandh804 , thanks for the review. I think numpy-docstrings is passing for this function, but it fails on other functions like `reshape` and `array_and_indicies`. Is this an expected behavior?

**Comment by sreegandh804** [comment]
Hi @abekek , 
As long as the tests failing are not caused due to the changes you made(which doesn't seem to be the case here) it's fine.
I'll get this PR merged right away

**Comment by abekek** [comment]
@sreegandh804, great, thank you for your help!

**Pull request merged**
