### PR TITLE
Added docstrings for bitwise_and

### LINKED ISSUE #1768: bitwise_and

### PR DESCRIPTION
**Pull request by sampreet-arthi**
Resolves #1768

### CODE REVIEW

**Comment by sampreet-arthi** [comment]
Should I also add docstrings to the backend files?

**Review by RashulChutani — COMMENTED** [review]
Can you try passing the docstring tests?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
