### PR TITLE
Add arange for PaddlePaddle backend

### LINKED ISSUE #11046: arange

### PR DESCRIPTION
**Pull request by xingyu-long**
Close #11046

### CODE REVIEW

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hi @xingyu-long and thanks for the contribution, 
1. in ivy, the return dtype of a function must be the same as input dtype so cast to the input dtype
2. you need to handle the case where the start and step have different signs, for example:
```
if (step > 0 and start > stop) or (step < 0 and start < stop):
        if isinstance(stop, float):
            stop = float(start)
        else:
            stop = start
```

once these are fixed, we are good to merge

**Comment by xingyu-long** [comment]
Hi @MahmoudAshraf97, Thanks for the suggestion! Please check the latest code.

**Review by MahmoudAshraf97 — APPROVED** [review]
Hi, I just fixed some casting rules to ensure consistency with other backends

**Comment by xingyu-long** [comment]
> Hi, I just fixed some casting rules to ensure consistency with other backends

Thanks for the help! I will be more careful for other tasks.

**Pull request merged**
