### PR TITLE
sampled_softmax_loss in Tensorflow frontends

### PR DESCRIPTION
**Pull request by rohitsalla**
ref : https://github.com/unifyai/ivy/issues/1548
Upon the list of functions of to be added on tensorflow frontends
Implemented sampled_softmax_loss

### CODE REVIEW

**Comment by Sarvesh-Kesharwani** [comment]
Hi @rohitsalla,
Thanks for the contribution, In addition to the frontend function, kindly ensure the implementation of its unit test in the corresponding Python script. Feel free to refer to other merged PRs for guidance on this.

**Comment by rohitsalla** [comment]
@Sarvesh-Kesharwani hey I have written the test function for it , can u please check

**Comment by Sarvesh-Kesharwani** [comment]
Hi @rohitsalla,
it seems you missed committing the added test function, please add it and let me know.

**Comment by rohitsalla** [comment]
https://github.com/unifyai/ivy/pull/28192
Can u check this @Sarvesh-Kesharwani

**Comment by Sarvesh-Kesharwani** [comment]
Hi @rohitsalla,
please check other merged prs for refrence, the unit test is still missing.

**Pull request closed without merging**
