### PR TITLE
Add complex conjugate function to Jax frontend

### LINKED ISSUE #14487: conj

### PR DESCRIPTION
**Pull request by adityagandhamal**
Close #14487
Implemented and tested the complex conjugate operator function `conj` from the `jax.lax` namespace in Jax frontend.

### CODE REVIEW

**Comment by adityagandhamal** [comment]
Hey @V-G-spec, I've looked into the failing tests, these are not caused due to my changes

**Comment by V-G-spec** [comment]
@adityagandhamal can you please resolve the merge conflicts?

**Comment by adityagandhamal** [comment]
Hey @V-G-spec, I've resolved the merged conflicts. I don't think the existing lint failures are due to my changes.

**Comment by V-G-spec** [comment]
Yep, looks good. Just revert some inadvertent changes in the files (space in some newlines outside your function definition etc.) and ping me
Keep up the great work!

**Comment by adityagandhamal** [comment]
Hey @V-G-spec, I think all seems good now

**Comment by V-G-spec** [comment]
Yep, awesome

**Pull request merged**
