### PR TITLE
Fix : paddle_solve bug

### LINKED ISSUE #21319: solve
### Bug Explanation

The `paddle.linalg.solve` tests are failing. The tests and the front-end function are not implemented properly.
The test should generate two matrices of shape [ *, M, M ] and [ *, M, K ] but the written test just generates two matrices of the same shape, and function arguments are mismatched returning 
`TypeError: solve() got an unexpected keyword argument 'x'`

### Steps to Reproduce Bug

Run : `pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_linalg.py::test_paddle_solve`

### Environment

MacOs : 13.5

### Ivy Version

 0.0.0.0.0

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

Mac M1

### PR DESCRIPTION
**Pull request by dhanush-2501**
# PR Description 
Fixes the paddle_solve bug

## Related Issue 

Close #21319

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials: 
https://twitter.com/coder_dhanush

### CODE REVIEW

**Comment by ReneFabricius** [comment]
Thank you for your contribution.
I am afraid the test does not include the cases of multi-column matrix on the right hand side or solving for batches of systems as per paddle docs [solve](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/linalg/solve_en.html). Could you please add those cases?

**Comment by dhanush-2501** [comment]
@ReneFabricius But, This is the approach used for all other solve() as well as the approach used in helpers functions also.
Can you pls confirm this?

**Comment by ReneFabricius** [comment]
@dhanush-2501 It is, however it is incomplete. API array standard for [solve](https://data-apis.org/array-api/latest/extensions/generated/array_api.linalg.solve.html?highlight=solve) also mentions that the right hand side can have multiple columns and that multiple equation systems can be passed together. You can wait for opinion of the assigned reviewer, since as you correctly point out, it is a problem with all frontend solve implementations and perhaps may be addressed in a separate issue.

**Review by hirwa-nshuti — APPROVED** [review]
Hey @dhanush-2501 

This seems to have slipped under our radar. I'm going to write down a task to check for this extended behaviour🙂
Meanwhile, I am going to merge this PR and thank you for contributing.

Thanks

**Comment by dhanush-2501** [comment]
@hirwa-nshuti , thats nice. As I have worked on functions related to solve and cholesky_solve. can you assign that to me?

**Pull request merged**
