### PR TITLE
adding tile to torch_tensor_instance

### PR DESCRIPTION
**Pull request by rohithGoudM**
Close https://github.com/unifyai/ivy/issues/14568

### CODE REVIEW

**Comment by rohithGoudM** [comment]
Code Review #14568

**Comment by rohithGoudM** [comment]
Close #14568

**Comment by kurshakuz** [comment]
ivy-gardener

**Comment by rohithGoudM** [comment]
Hi @kurshakuz, thank you for the feedback.
I have resolved the conflicts.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
