### PR TITLE
Add max pool1d to torch frontend

### PR DESCRIPTION
**Pull request by heitorcfelix**
Issue: https://github.com/unifyai/ivy/issues/6013
Based on https://github.com/unifyai/ivy/pull/12459

### CODE REVIEW

**Comment by Ookamice** [comment]
@heitorcfelix 
Thank you for the contributions.

However, I'm not sure about the use of `ivy.handle_padding` as there aren't any backend implementations for it for any of the frameworks. This is also the reason why the intelligent-tests are failing.  I see it also used in #12459 which is very odd. Please could you look into this.

**Comment by heitorcfelix** [comment]
> However, I'm not sure about the use of `ivy.handle_padding` as there aren't any backend implementations for it for any of the frameworks. This is also the reason why the intelligent-tests are failing. I see it also used in #12459 which is very odd. Please could you look into this.

While testing, I replaced this function with ivy.functional.layers._handle_padding, which passed the tests. However, I returned to the previous version to leave it in the same pattern as the reference PR. Can I keep "ivy.functional.layers?_handle_padding"?

**Comment by Ookamice** [comment]
@heitorcfelix 
Thanks for the quick fix!
However, there is still a failing test for the jax backend: `AssertionError: returned shape = (1, 1, 2), ground-truth returned shape = (1, 1, 1)` Let me know if you have any thoughts on what might be causing this. 😃

**Comment by heitorcfelix** [comment]
> I wrote a simple code to show the problem:

When I do not change the data_format, the result of Jax is the same as the other fronts
```
INPUT:
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
TORCH
ivy.array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])
NUMPY
ivy.array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])
JAX
ivy.array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])
```

**Comment by heitorcfelix** [comment]
@Ookamice  
> Could you please resolve the conflicts and I'll get it merged 🚀

Done! 🚀

**Comment by Ookamice** [comment]
@heitorcfelix 
Thank you for your contributions 🚀 💪

**Pull request merged**
