### PR TITLE
Quantile Method - Extend Ivy Functional API (New Branch)

### PR DESCRIPTION
**Pull request by Aaa2275**
#6934

### CODE REVIEW

**Comment by Aaa2275** [comment]
Hi @Ishticode 

I made a new pull request on a new branch and made sure that changes were made on only required files. Also, I did some changes on Torch backend that mimic the behaviour of other backends (tensorflow, numpy, and jax). Beforehand, it wasn't capturing the same behaviour of other backends and for some reason it was passing the tests.

I think now should be all good.
Thanks

**Review by Ishticode — APPROVED** [review]
The CI seems to have gone a bit haywire. But this time It was possible for me to check locally and everythings running good. I just pushed a minor docstyle fix push which would've been tedious to communicate here without the CI showing.

@Aaa2275 Looking great. I will get this merged. Thanks for your contribution and patience.  🙂

**Comment by Aaa2275** [comment]
Hi @Ishticode 

That's great news. Thanks a lot for comments and help.

**Comment by Daniel4078** [comment]
> The CI seems to have gone a bit haywire. But this time It was possible for me to check locally and everythings running good. I just pushed a minor docstyle fix push which would've been tedious to communicate here without the CI showing.
> 
> @Aaa2275 Looking great. I will get this merged. Thanks for your contribution and patience. 🙂

@Aaa2275 @Ishticode Just found out, the implementation of quantile for the torch backend is not fully correct as its test(https://github.com/unifyai/ivy/actions/runs/4187133030/jobs/7256571129#step:7:3093) fails. Please have a look and fix it.

**Pull request merged**
