### PR TITLE
Implementing greater equal function

### PR DESCRIPTION
**Pull request by AW786WA**
# PR Description

## Related Issue

Close #

## Checklist

- [Yes ] Did you add a function?
- [No ] Did you add the tests?
- [Yes, performed the tests multiple times but tests are not passing. ] Did you run your tests and are your tests passing?
- [No ] Did pre-commit not fail on any check?
- [Yes, I have read the IVY documentation and watched tutorial videos] Did you follow the steps we provided?
-[Pull Request Type -Draft] Please provide your valuable guidance in order to progress further. I have attached a snapshot of a function for your examination.
Replica of greater_equal_function

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by AW786WA** [comment]
Hello Ved,

Thank you, for your feedback.

The irony is that I haven't touched or manipulated the conflicting files as they were not pertinent to the task. I have carefully reviewed the situation and the git repository to ensure there are no unintended changes. However, the conflict persists. I'd greatly appreciate any further guidance or advice on how to fix this issue.

Best
Waqas (AW786WA)

**Comment by vedpatwardhan** [comment]
> Hello Ved,
> 
> Thank you, for your feedback.
> 
> The irony is that I haven't touched or manipulated the conflicting files as they were not pertinent to the task. I have carefully reviewed the situation and the git repository to ensure there are no unintended changes. However, the conflict persists. I'd greatly appreciate any further guidance or advice on how to fix this issue.
> 
> Best Waqas (AW786WA)

@hmahmood24 should be able to help you out (as he's assigned to the PR) 😄

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @AW786WA, thanks a lot for the PR. Can you please revert all of your previous commits and then freshly add your function and its corresponding test in a new commit afterwards? We need to clean up the PR. Thanks :)

**Comment by hmahmood24** [comment]
Closing this PR as it has been stale for more than 2 weeks now.

**Pull request closed without merging**
