### PR TITLE
Reformatted bitwise_right_shift

### PR DESCRIPTION
**Pull request by LucasPilla**
Issue: 
- #2252 

Changes: 
Updated docstring for `bitwise_right_shift` according to Deep Dive.

Doubts:
How should I add doctrings for the array operators methods, as `__rshift__` and `__rrshift__`? I just added the "Examples" section.

### CODE REVIEW

**Comment by abdrahmandiab** [comment]
Hi Lucas! For the __function__ methods you can follow the example of [__add__](https://github.com/unifyai/ivy/blob/6297e0d5de7a4b869f4facd984539a04c2192a13/ivy/array/array.py#L310). 

Let me know if you have any more questions. :)

**Comment by LucasPilla** [comment]
@abdrahmandiab Hi, I just updated the `__function__` docstrings

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab Hi, I just updated the `__function__` docstrings Could you review my pull request, please?

Hi Lucas, sorry for making you wait so long 😅 I'll start the review process now and will let you know if I find any changes that need to be applied. :)

**Comment by abdrahmandiab** [comment]
Hi @LucasPilla! 🙋🏻‍♂️

Thank you so much for your patience, and thank you for your amazing work! I've checked most of your changes and they seem to be correct! 🚀

There are however a few tiny changes that I'd like you to make and then we can proceed to merge this PR soon hopefully :)

The changes are:

1. In the `ivy/functional/ivy/elementwise.py` file, I think the sizes of the arrays can be varied a bit more, currently they are all 3x1 and don't show a large sample of possible values. If you can try introducing some harder examples of using the function as the examples go on that would be awesome!

2. There seems to be no implementations for `__rshift__` or `__rrshift__` inside [ivy/container/container.py](https://github.com/unifyai/ivy/blob/master/ivy/container/container.py). These functions should be implemented here as well, and again you can follow the examples of [`__add__`](https://github.com/unifyai/ivy/blob/67aa14bfb83beb6d6962614d276c47932536057e/ivy/container/container.py#L108) and [`__radd__`](https://github.com/unifyai/ivy/blob/67aa14bfb83beb6d6962614d276c47932536057e/ivy/container/container.py#L173) for this. And of course refer to the [Docstring Examples](https://lets-unify.ai/ivy/deep_dive/13_docstring_examples.html#docstring-examples) section for how to add examples on this.

Otherwise I think all the other changes are very good! 
Thanks so much! 😊

**Comment by LucasPilla** [comment]
@abdrahmandiab 

- I updated the examples from `ivy/functional/ivy/elementwise.py`. I used more varied array shapes and broadcasting.
- I implemented `__rshift__` and `__rrshift__` methods for containers with docstrings and examples.

I believe everything is OK now :+1:. Let me know if there are other changes I shoud make.
Thanks :smile:!

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab
> 
> * I updated the examples from `ivy/functional/ivy/elementwise.py`. I used more varied array shapes and broadcasting.
> * I implemented `__rshift__` and `__rrshift__` methods for containers with docstrings and examples.
> 
> I believe everything is OK now 👍. Let me know if there are other changes I shoud make. Thanks 😄!

Hi @LucasPilla, unfortunately there seems to be a few docstrings tests that are failing now so we can't merge just yet😅 Could you please try to have a go at fixing them, and of course if you are struggling with that just contact me and we can work it out together. 😄 

You can check these failures by clicking on the Details button here:
image

Then you can search for failures specific to `bitwise_right_shift` by using the Search bar at the top right corner of the logs. 😃 
image

**Comment by LucasPilla** [comment]
@abdrahmandiab I forgot to initialize the output variable, when using `out` argument.
I fixed other small errors as well, it should be correct now 🙏. Can you check?

**Comment by LucasPilla** [comment]
@abdrahmandiab Are there anything I should fix?

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab Are there anything I should fix?

Oh! I sincerely apologize @LucasPilla I thought I had merged your PR earlier since I had confirmed your implementation was correct. This somehow slipped under the radar as I was quite busy this week. 🙃 

Again, I sincerely apologize! Thanks for all the hard work!

**Pull request merged**
