### PR TITLE
feat(paddle.tensor.logic): add logical bitwise_or and test

### PR DESCRIPTION
**Pull request by iamwahid**
Closes https://github.com/unifyai/ivy/issues/16204

### CODE REVIEW

**Comment by iamwahid** [comment]
Hi @AnnaTz could you please review this PR?

**Comment by AnnaTz** [comment]
> 

Hi @iamwahid, @Ishticode has been assigned to your PR and will review it at their earliest convenience. In the meantime, kindly resolve the conflicts between your PR and our master.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Thanks @AnnaTz 
Hi @iamwahid. Thank you very much for the PR. Mostly looking good. 
Just that I checked and `paddle.bitwise_or` does support `int32` and I am assuming it perhaps supports other int types. Why are these specified as unsupported? As our frontends simulate the native framework,  we should be able to support all dtypes as the native and allow the testing. Does that make sense? please feel free to follow up with updates, questions or a review request when you make relevant changes. Thank you very much 🙂

**Comment by iamwahid** [comment]
> Thanks @AnnaTz Hi @iamwahid. Thank you very much for the PR. Mostly looking good. Just that I checked and `paddle.bitwise_or` does support `int32` and I am assuming it perhaps supports other int types. Why are these specified as unsupported? As our frontends simulate the native framework, we should be able to support all dtypes as the native and allow the testing. Does that make sense? please feel free to follow up with updates, questions or a review request when you make relevant changes. Thank you very much 🙂

Hi @Ishticode , thanks for the review. 

I will double check with native if it does support most of number types, and will update accordingly

**Comment by iamwahid** [comment]
Hi @Ishticode , as [on documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/bitwise_or_en.html) the supported data types are `bool, uint8, int8, int16, int32, int64`. Hence, I removed float types from code

**Review by Ishticode — APPROVED** [review]
I made a small update. All looking Good. Thank you very much for your contribution @iamwahid. I will get this merged. All the best 🙂

**Comment by iamwahid** [comment]
Great, thank you so much @Ishticode. 

I may add another contributions to this great repository in  the future.

**Comment by Ishticode** [comment]
You are welcome and we appreciate your contributions @iamwahid 😄

**Pull request merged**
