### PR TITLE
Added experimental backend for is_storage function

### PR DESCRIPTION
**Pull request by TahaTasleem**

### CODE REVIEW

**Comment by TahaTasleem** [comment]
- [] #6695

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by aryans1204** [comment]
Hi, the PR looks good, however the lint tests are failing. The lint tests are mostly failing because of trivial aspects like no newline character at the ned of line and other formatting issues. I'd recommend you to take a look at the lint test details, and fix the minor formatting issues. Afterwards, the PR looks godd to merge.

**Comment by guillesanbri** [comment]
Closing as stale

**Pull request closed without merging**
