### PR TITLE
asarray

### PR DESCRIPTION
**Pull request by tamukagate**

### CODE REVIEW

**Comment by tamukagate** [comment]
add_reformatting_checklist_creation

**Comment by tamukagate** [comment]
Close #7187

**Comment by tamukagate** [comment]
Close #7187

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by tamukagate** [comment]
Hi @agniiyer, please may you review my pull request.

**Comment by agniiyer** [comment]
Hey you still need to add docstring examples :) Can you take a look at the docs to see how this is done?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
