### PR TITLE
Add numpy.linalg.slogdet to JAX frontend

### PR DESCRIPTION
**Pull request by Ajay6601**
slogdet #6724

### CODE REVIEW

**Comment by Nightcrab** [comment]
Will review once frontend test is added.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ajay6601** [comment]
I am working with this PR

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by hirwa-nshuti** [comment]
Hey @Ajay6601 
This function was implemented in this pull request https://github.com/unifyai/ivy/pull/5060
And was merged, which means I am going to close this PR.
Feel free to allocate another task to you
Thanks🙂

**Pull request closed without merging**
