### PR TITLE
Addded missing single quote in line 8 on test-frontend-numpy

### PR DESCRIPTION
**Pull request by memorybase**
# PR Description

## Related Issue

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by memorybase** [comment]
Hello, Please kindly review.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by hirwa-nshuti** [comment]
Hey @memorybase 

Thanks for contributing to Ivy 🙂
However, the changes you added aren't supposed to be there as the double quotes are only for the `Numpy Frontend` part and `Exhaustive CI` only.

Meanwhile, you can explore our [contribution guide](https://unify.ai/docs/ivy/overview/contributing.html) to check out the open tasks to work on🤞
I'm going to close this item!
Thanks

**Comment by memorybase** [comment]
Alright, thanks!

**Pull request closed without merging**
