### PR TITLE
Paddle Frontend tensor.min implementation

### LINKED ISSUE #22519: min

### PR DESCRIPTION
**Pull request by kashifqau**
Close #22519

### CODE REVIEW

**Comment by Mr-Niraj-Kulkarni** [comment]
@kashifqau  Can you please resolve the lint errors please. Apart from that everything looks good.

**Comment by kashifqau** [comment]
@Mr-Niraj-Kulkarni Thank you for your initial review.

Lint errors are not related to ivy code rather they are related to the python files. I am pasting the error below. 
Please suggest about how can we fix them?

ivy-lint.................................................................Failed
- hook id: ivy-lint
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/reporp0ywty_/py_env-python3.8/bin/ivy-lint", line 5, in <module>
    from ivy_lint.__main__ import main
  File "/home/runner/.cache/pre-commit/reporp0ywty_/py_env-python3.8/lib/python3.8/site-packages/ivy_lint/__init__.py", line 3, in <module>
    from .formatters import *
  File "/home/runner/.cache/pre-commit/reporp0ywty_/py_env-python3.8/lib/python3.8/site-packages/ivy_lint/formatters/__init__.py", line 6, in <module>
    from .function_ordering import FunctionOrderingFormatter
  File "/home/runner/.cache/pre-commit/reporp0ywty_/py_env-python3.8/lib/python3.8/site-packages/ivy_lint/formatters/function_ordering.py", line 13, in <module>
    FILE_PATTERN = re.compile(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/sre_parse.py", line 836, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 0

**Comment by kashifqau** [comment]
@Mr-Niraj-Kulkarni Thank you so much for your initial review and feedback.

Lint errors are resolved. You are requested to please have a look.

**Review by Mr-Niraj-Kulkarni — APPROVED** [review]

**Comment by Mr-Niraj-Kulkarni** [comment]
Looks good to me. Thanks

**Pull request merged**
