### PR TITLE
implemented tensnorflow xdivy frontend

### LINKED ISSUE #13286: xdivy

### PR DESCRIPTION
**Pull request by ajithpious**
closes #13286

### CODE REVIEW

**Comment by ajithpious** [comment]
@agniiyer Could you please review my PR.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @ajithpious 
Thanks for the PR😊
All looks good to me, just fix the merge conflicts and it will be good to go😀

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @ajithpious 
All looks good😊
But you'll have to remove the changes made to `.idea` files before we merge this PR.
Thanks

**Comment by ajithpious** [comment]
Hi @hirwa-nshuti , made the changes. could you please review my request.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @ajithpious 

Thanks for the updates, however tests are failing from my end.
Would you look into this🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
