### PR TITLE
geometric random function for numpy frontend

### LINKED ISSUE #9733: geometric
- [] #9481

### PR DESCRIPTION
**Pull request by AbhirKarande**
close #9733

### CODE REVIEW

**Comment by AbhirKarande** [comment]
So one check that is failing is the 'test-frontend-numpy' check. When I go I see that 
'python3 -m pytest --backend all ivy_tests/test_ivy/test_frontends/test_numpy' is run. 

I try running that myself to see which tests are failing and I get 44 failed tests, 202 passed, and 4 errors. The failures seem to be in the test_mathematical_functions, test_matrix, test_ndarray, etc. 

I have not previously modified any of the frontend functions or anything related. Any advice on how to address these?

**Comment by AbhirKarande** [comment]
@ahmedo42 Do you have any guidance on fixing the failed checks. Please refer to my above comment. Thanks!

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @AbhirKarande 
Thanks for contributing to ivy😊
You don't have to worry about the other failing tests and as your implementation tests are passing we can go ahead and merge the PR.
Here are the changes that are needed:

- [ ] Remove the changes that you made on `.idea` files here is a good guide to help you out
[Managing your fork](https://lets-unify.ai/ivy/contributing/the_basics.html#managing-your-fork)
- [ ] Also create an issue for the function you're implementing and comment with the issue number to this PR for it to be linked with it. You can follow the contribution guide to understand the workflow🙂 [ToDo List Issues](https://lets-unify.ai/ivy/contributing/the_basics.html#todo-list-issues)

After these are solved your PR will be merged
Thanks😊

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
There are still changes in `.idea` files you need to remove them I'll merge the PR then.

Also, comment on this PR with the issue for this function to be linked
Thank😊

**Comment by AbhirKarande** [comment]
- [] #9733

**Review by hirwa-nshuti — APPROVED** [review]
Looks good now😊
Thanks for contributing🙂

**Pull request merged**
