### PR TITLE
tensordot adhering to Array API standard

### PR DESCRIPTION
**Pull request by martinoywa**
This currently contains base tensordot implementation for the following backend frameworks:

- [x] Numpy 
- [x] PyTorch
- [x] TensorFlow
- [x] JAX

Related Issue:
- [x] https://github.com/unifyai/ivy/issues/346

### CODE REVIEW

**Comment by martinoywa** [comment]
Hi @djl11, both TensorFlow and PyTorch don't seem to able to work with uint8 for their tensordot implementation. What would you suggest for me to do?

**Review by HotzingTone — CHANGES_REQUESTED** [review]
Please add docstring to ivy.tensordot. Thanks!

**Review by HotzingTone — COMMENTED** [review]
We're now updating our test module, once it's done we'll be able to review. Thanks!

**Comment by martinoywa** [comment]
Awesome! Still working on the TF implementation.

**Review by HotzingTone — CHANGES_REQUESTED** [review]
Hi, thanks for your work.
Please go to ivy/ivy_test/array_api_methods_to_test/linear_algebra.txt, uncomment #tensordot to get tensordot included in the test.
Also, I see no JAX implementation has been made?

**Comment by martinoywa** [comment]
> Hi, thanks for your work. Please go to ivy/ivy_test/array_api_methods_to_test/linear_algebra.txt, uncomment #tensordot to get tensordot included in the test. Also, I see no JAX implementation has been made?

No problem, I'll do just that. 
Adding JAX implementation in a few.

**Review by HotzingTone — COMMENTED** [review]
Looks good! Passing review to @djl11.
Thanks for your work!

**Review by djl11 — CHANGES_REQUESTED** [review]
Please get the unit tests passing. For example, you have not imported the List type in one file.

**Review by HotzingTone — APPROVED** [review]
Sorry it was me not merging the upstream properly.
Now resolved, and all test passed.
 @djl11 please review again :)

**Comment by martinoywa** [comment]
Hi @HotzingTone, I resolved some conflicts which were coming from the upstream, and it lead to these tests failing. Please advice. Thanks.

**Pull request merged**
