### PR TITLE
Used device memory

### PR DESCRIPTION
**Pull request by Boldcodes**
- [x] #1777

### CODE REVIEW

**Comment by Darshan-H-E** [comment]
Hi @Boldcodes,
Apologies for the delay. It would be helpful if you could look into the [contributor guide](https://lets-unify.ai/ivy/deep_dive/7_devices.html#devices) and add outputs to the examples which you have added.

**Comment by Boldcodes** [comment]
Hi @Darshan-H-E , I'll do just that

**Comment by Boldcodes** [comment]
Hi @Darshan-H-E, How do I request for a code review

**Comment by Darshan-H-E** [comment]
Hi @Boldcodes, kindly reflect on the changes requested. Otherwise this PR will be closed due to inactivity.

**Pull request closed without merging**
