### PR TITLE
add swapaxes frontends.torch

### PR DESCRIPTION
**Pull request by PatternFinder**
link to issue: #2704

### CODE REVIEW

**Comment by bicycleman15** [comment]
Hey, the PR looks good to me. Could you please resolve merge conflicts ? 🙂

**Comment by PatternFinder** [comment]
> Hey, the PR looks good to me. Could you please resolve merge conflicts ? 🙂

done :)

**Review by bicycleman15 — APPROVED** [review]
LGTM! Please resolve the conflicts and I will merge the PR 🙂 
Sorry for making you do this again. I have approved the changes so that you yourself can merge the PR if I don't respond 😅

**Comment by PatternFinder** [comment]
> LGTM! Please resolve the conflicts and I will merge the PR 🙂 Sorry for making you do this again. I have approved the changes so that you yourself can merge the PR if I don't respond 😅

no problem :) I've resolved the merge conflict again; please have a look.

doesn't the `approved` give me `write access` to merge this PR myself? I couldn't figure it out 😅

**Pull request merged**
