### PR TITLE
Updated clip_vector_norm Issue #2238

### PR DESCRIPTION
**Pull request by AwkNinja**

### CODE REVIEW

**Comment by AwkNinja** [comment]
When running the tests for docstrings I was getting `linalg.vector_norm:Expectedafloatingpointorcomplextensorasinput.GotInttorchy` this was causing the test to fail but in the function arguments a float was clearly being passed instead of an Int. I'm not sure if its an issue on my side or its from vector_norm. Please let me know.

**Comment by Oxbeefbabe** [comment]
Hi @AwkNinja,

These seem to be happening due to your changes. Have a look and see if you can fix them. Also, make sure that your lint tests are passing.

Mention me when you are ready for me to have another look.  :)

**Comment by AwkNinja** [comment]
Hi @Oxbeefbabe I have fixed the lint errors and the error with doc_strings, Please take a look and let me know if there is any other actions needed from my side.

**Comment by Oxbeefbabe** [comment]
Hi AwkNinja, everything looks good to me. Could you do me a favour before I merge? There is a lint check that is failing only because there is not a newline at the end of `ivy_tests/test_ivy/test_functional/test_core/test_linalg.py` Do you mind just quickly adding a new line and committing it to the PR. After that, I'll go ahead and merge. Cheers!

**Comment by AwkNinja** [comment]
Yea sure I'll add that. Thanks for your help. 😊

**Comment by AwkNinja** [comment]
I just checked there was already a new line at the end of `ivy_tests/test_ivy/test_functional/test_core/test_linalg.py` for me and github doesn't detect this change when comparing to `unifyai:master`, I'm not sure if someone already added the line or something but clearly there isn't an empty line when I check the repository on the github desktop.

**Comment by Oxbeefbabe** [comment]
Ok, it seems that someone has already done that. Since you are working on a fork you will be a a few commits behind. This is a non-issue then, thank you for checking! Merging now :)

**Pull request merged**
