### PR TITLE
poisson_nll_loss

### PR DESCRIPTION
**Pull request by Tatiats7**

### CODE REVIEW

**Comment by Tatiats7** [comment]
[#5741]

**Comment by Tatiats7** [comment]
This PR is for #5741

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi. Apologies for the late reply and Thank you very much for the PR.  Could you please also include the test for the function you implemented as detailed in the [frontend tests section](https://lets-unify.ai/ivy/deep_dive/ivy_frontends_tests.html) on the deep dive. Let me know if something is unclear.

**Comment by Ishticode** [comment]
Hi @Tatiats7 
I've marked the PR as stale because there has been no response in over a month. Please feel free to work on the requested changes and request a review if possible. Otherwise, this PR will be closed in 7 days. Thank you.

**Pull request closed without merging**
