### PR TITLE
refactor: Refactoring for efficiency and readability

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
Reformatted and Refactored files for better readability and according to latest Python standards. Used `f-strings` wherever possible, Replaced unneeded comprehensions with generator (Functions like `any`, `all` and `sum` allow us to pass in a generator rather than a collection. Doing so removes a pair of brackets, making the intent slightly clearer). Also, Simplified `finding` if substrings are present in strings by using `in` operator, merged nested `if` conditions, and few more small changes to make the code better and clean.

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:
https://twitter.com/Sai_Suraj_27

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by vedpatwardhan — COMMENTED** [review]
I'll request @KareemMAX's review on the PR, thanks @Sai-Suraj-27 😄

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hey @Sai-Suraj-27, 

As there are some conflicts, can you fix those to simplify the review process?

**Comment by Sai-Suraj-27** [comment]
@KareemMAX sir, I have resolved the conflicts. Please check now, Thank you.

**Pull request merged**
