### PR TITLE
Broadcast shape

### LINKED ISSUE #26195: broadcast_shape

### PR DESCRIPTION
**Pull request by Ivanseven**
# PR Description

## Related Issue

Close #26195, depends on pending broadcast_shape PRs: #23574 or alternative #22977

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided? ( To the best I can understand, the docs are a bit overwhelming )

### CODE REVIEW

**Comment by Ivanseven** [comment]
I am having some trouble understanding & writing the testing for this PR, could you help?

I am using the following to describe arrays with integers:
`
dtype_and_x=helpers.dtype_and_values(
        available_dtypes=["int32", "int64"], num_arrays=2
),
`

I think the testcase is failing because of receiving an Ivy array: `ivy.array(0)`, however the other testcases do not seem to be converting their arrays, so I don't understand why my test is receiving Ivy arrays.

Hypothesis Errors:
```
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_broadcast_shape[cpu-numpy-False-False] - ivy.utils.exceptions.IvyBackendException: numpy: broadcast_shapes: expected a sequence of integers or a single integer, got 'ivy.array(0)'
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_broadcast_shape[cpu-jax-False-False] - ivy.utils.exceptions.IvyBackendException: jax: broadcast_shapes: Shapes must be 1D sequences of concrete values of integer type, got (ivy.array(0),).
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_broadcast_shape[cpu-tensorflow-False-False] - ivy.utils.exceptions.IvyBackendException: tensorflow: broadcast_shapes: {{function_node __wrapped__BroadcastArgs_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] must be a vector.[] [Op:Broa...
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_broadcast_shape[cpu-torch-False-False] - ivy.utils.exceptions.IvyBackendException: torch: broadcast_shapes: ('Input shapes should be of type ints, a tuple of ints, or a list of ints, got ', ivy.array(0))
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_broadcast_shape[cpu-paddle-False-False] - exceptiongroup.ExceptionGroup: Hypothesis found 6 distinct failures. (6 sub-exceptions)

```

**Comment by Sarvesh-Kesharwani** [comment]
Hi @Ivanseven,
you can refer to this page [how to implement unit tests for frontend functions](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html) for a head start, or you can also check other pages.

Spend some time with the doc I shared and also go through the functions and their unit tests already implemented.
Let me know once the implementation is done with some of the test cases passing, if not all.
Thanks

**Comment by Sarvesh-Kesharwani** [comment]
Also please resolve the merge conflicts.

**Comment by Ivanseven** [comment]
Hi @Sarvesh-Kesharwani, it's been 3 months so I have stopped looking into this issue, but thanks anyway!

**Pull request closed without merging**
