### PR TITLE
fix implementation for paddle backend

### LINKED ISSUE #14301: fix

### PR DESCRIPTION
**Pull request by rogn02**
close #14301

- [x] #14301

### CODE REVIEW

**Comment by rogn02** [comment]
@MahmoudAshraf97 @Ishticode , please review my PR and tell me if there needs to be any changes. Thank you

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
AttributeError: module 'paddle' has no attribute 'fix'

**Comment by rogn02** [comment]
I have made changes, please review the changes. Thank you

**Comment by MahmoudAshraf97** [comment]
Hi @rogn02 , another contributor implemented the function already, sorry for the inconvenience

**Comment by rogn02** [comment]
@MahmoudAshraf97 , it's okay, thank you for your time :)

**Pull request closed without merging**
