### PR TITLE
poisson

### PR DESCRIPTION
**Pull request by Om-Doiphode**
- [ ] #1557 
- [ ] #13371

### CODE REVIEW

**Comment by Infrared1029** [comment]
Hello @Om-Doiphode, the test appears to be failing, can you make sure the test is passing so I can take a close look? Thanks!

**Comment by Om-Doiphode** [comment]
Hello @Infrared1029, I have checked the logs, the test is failing because of issues in other files which I haven't changed. Kindly look into this.

**Comment by Infrared1029** [comment]
Hello @Om-Doiphode, the failing test I am mentioning is `ERROR ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_tensorflow_poisson[cpu-ivy.functional.backends.tensorflow-False-False]`  the reason appears to be `E      fixture 'lam' not found`, looking at the test implementation, it is indeed the case the `Iam` is not being generated yet passed to the test handling function. Always make sure to run the tests on your machine and that everything passes.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
