### PR TITLE
feat(loss-functions): add poisson_nll_loss function

### LINKED ISSUE #21727: poisson_nll_loss

### PR DESCRIPTION
**Pull request by akshatvishu**
Close #21727

### CODE REVIEW

**Comment by akshatvishu** [comment]
This below is one of the failing test for my implementation:
```py
______________ test_poisson_nll_loss[cpu-tensorflow-False-False] _______________
ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py:158: in test_poisson_nll_loss
    fn_tree="functional.ivy.experimental.poisson_nll_loss",
ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py:187: in test_poisson_nll_loss
    helpers.test_function(
ivy_tests/test_ivy/helpers/function_testing.py:459: in test_function
    gradient_test(
ivy_tests/test_ivy/helpers/function_testing.py:1015: in gradient_test
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:169: in value_test
    assert_all_close(
ivy_tests/test_ivy/helpers/assertions.py:62: in assert_all_close
    assert np.allclose(
E   AssertionError:  the results from backend tensorflow and ground truth framework torch do not match
E    [0.]!=[-0.69314719] 
E   
E   
E   Falsifying example: test_poisson_nll_loss(
E       backend_fw='tensorflow',
E       on_device='cpu',
E       dtype_input_target=(['float64', 'float64'], [array([2.]), array([2.])]),
E       log_input=False,
E       full=False,
E       epsilon=1e-08,
E       reduction='none',
E       fn_name='poisson_nll_loss',
E       test_flags=FunctionTestFlags(
E           ground_truth_backend='torch',
E           num_positional_args=0,
E           with_out=False,
E           instance_method=False,
E           test_gradients=True,
E           test_compile=False,
E           as_variable=[False],
E           native_arrays=[False],
E           container=[False],
E       ),
E   )
```

But when I run it on a python file:
```py
import torch
import ivy

ivy.set_backend("tensorflow")
x = ivy.array([2.], dtype=ivy.float64)
y = ivy.array([2.], dtype=ivy.float64)
z = ivy.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(z)
print(z.dtype)
print("TORCH OUTPUT")
x = torch.tensor([2.], dtype=torch.float64)
y = torch.tensor([2.], dtype=torch.float64)
z = torch.nn.functional.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(z)
print(z.dtype)

"""
ivy.array([0.61370563])
float64
TORCH OUTPUT
tensor([0.6137], dtype=torch.float64)
torch.float64
"""
```

**Comment by akshatvishu** [comment]
same with this test failure for `tensorflow backend`:
```py
E       AssertionError:  the results from backend tensorflow and ground truth framework torch do not match
E        [0. 0. 0. 0. 0. 0. 0. 0. 0.]!=[-0.07701635 -0.07701635 -0.07701635 -0.07701635 -0.07701635 -0.07701635
E        -0.07701635 -0.07701635 -0.07701635] 
E       
E       
E       Falsifying example: test_poisson_nll_loss(
E           backend_fw='tensorflow',
E           on_device='cpu',
E           dtype_input_target=(['float32', 'float32'],
E            [array([2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32),
E             array([2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32)]),
E           log_input=False,
E           full=False,
E           epsilon=1e-08,
E           reduction='none',
E           fn_name='poisson_nll_loss',
E           test_flags=FunctionTestFlags(
E               ground_truth_backend='torch',
E               num_positional_args=0,
E               with_out=False,
E               instance_method=False,
E               test_gradients=True,
E               test_compile=False,
E               as_variable=[False],
E               native_arrays=[False],
E               container=[False],
E           ),
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.6', b'AXicY2Bk4GBAAKahz2QEYgAXHQAv') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:62: AssertionError
```
But when I call my implementation then it gives different result:
```py
import torch
import ivy


ivy.set_backend("tensorflow")
x = ivy.array([2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=ivy.float32)
y = ivy.array([2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=ivy.float32)
z = ivy.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(z)
print(z.dtype)

x = torch.tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float32)
y = torch.tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float32)
z = torch.nn.functional.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(z)
print(z.dtype)
"""
ivy.array([0.61370564, 0.61370564, 0.61370564, 0.61370564, 0.61370564,
       0.61370564, 0.61370564, 0.61370564, 0.61370564])
float32
tensor([0.6137, 0.6137, 0.6137, 0.6137, 0.6137, 0.6137, 0.6137, 0.6137, 0.6137])
torch.float32
"'"

```

**Comment by akshatvishu** [comment]
@kurshakuz  Can you please provide any feedback on this ?
Because when I call my implementation to check for inputs which are giving failures, I am getting different results:

**Example:**

```py
E       AssertionError:  the results from backend paddle and ground truth framework torch do not match
E        [0.]!=[-0.6931472] 
E       
E       
E       Falsifying example: test_poisson_nll_loss(
E           backend_fw='paddle',
E           on_device='cpu',
E           dtype_input_target=(['float32', 'float32'],
E            [array([2.], dtype=float32), array([2.], dtype=float32)]),
E           log_input=False,
E           full=False,
E           epsilon=1e-08,
E           reduction='none',
E           test_flags=FunctionTestFlags(
E               ground_truth_backend='torch',
E               num_positional_args=0,
E               with_out=False,
E               instance_method=False,
E               test_gradients=True,
E               test_compile=False,
E               as_variable=[False],
E               native_arrays=[False],
E               container=[False],
E               precision_mode=False,
E           ),
E           fn_name='poisson_nll_loss',
E       )
```
But when I call my function with the same inputs for which it is showing failures, I get same results across all frameworks.
```py
ivy.set_backend("tensorflow")
ivy.set_inplace_mode('strict') 
x = ivy.array([2.], dtype=ivy.float32)
y = ivy.array([2.], dtype=ivy.float32)
z = ivy.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(f"TF backend:{z}")#TF backend:ivy.array([0.61370564])

ivy.set_backend("torch")
ivy.set_inplace_mode('strict') 
x = ivy.array([2.], dtype=ivy.float32)
y = ivy.array([2.], dtype=ivy.float32)
z = ivy.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(f"torch_backend{z}")#torch_backendivy.array([0.61370564])

ivy.set_backend("paddle")
ivy.set_inplace_mode('strict') 
x = ivy.array([2.], dtype=ivy.float32)
y = ivy.array([2.], dtype=ivy.float32)
z = ivy.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(f"paddle_backend{z}") #paddle_backendivy.array([0.61370564])

print("TORCH NATIVE API")
x = torch.tensor([2.], dtype=torch.float32)
y = torch.tensor([2.], dtype=torch.float32)
z = torch.nn.functional.poisson_nll_loss(x, y, log_input=False, reduction="none")
print(f"TORCH NATIVE: {z}") #TORCH NATIVE: tensor([0.6137])
```

**Comment by akshatvishu** [comment]
Update: So, setting ` testing_gradient=False` , lowering the value generation test range and adding `rtol` and `atol` have made the test pass for all backends @kurshakuz

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! I am very sorry for such delay this PR somehow slipped under the radar. Would you mind removing all changes that are unrelated to the function you are adding?

**Comment by akshatvishu** [comment]
> Hey! I am very sorry for such delay this PR somehow slipped under the radar. Would you mind removing all changes that are unrelated to the function you are adding?

sure!

**Comment by akshatvishu** [comment]
Hey @kurshakuz . I removed the out of scope functionality as discussed with Ved and Haider at discord.(refs:[LINK](https://discord.com/channels/799879767196958751/1000044049333485648/1154461407199383693))

**Review by kurshakuz — APPROVED** [review]
LGTM! Thanks for your contribution!

**Comment by akshatvishu** [comment]
> LGTM! Thanks for your contribution!

Thanks for the review @kurshakuz !

**Pull request merged**
