### PR TITLE
Adding eigh function in linalg.py in tensorflow frontend

### PR DESCRIPTION
**Pull request by Ammar-Shah**

### CODE REVIEW

**Comment by Ammar-Shah** [comment]
#5476

**Comment by DragosStoican** [comment]
Hey @Ammar-Shah  🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

**Comment by Ammar-Shah** [comment]
> Hey @Ammar-Shah 🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

My bad. Thank you! Will be careful in future

**Comment by DragosStoican** [comment]
The test `test_tensorflow_eigh` is failing. It needs to be passed before merging this PR

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
