### PR TITLE
Add rot90 function to Jax frontend

### LINKED ISSUE #6795: rot90

### PR DESCRIPTION
**Pull request by Change-m**
Close #6795

### CODE REVIEW

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi, just a few changes before-hand.

1. It shows that you have removed the `vstack()` from the file to implement `rot90()` in the `files changed` tab, kindly fix that.
2. Also, kindly resolve the conflicts too.

Thanks! 🙂

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi!
Kindly resolve the conflicts and you also have to refactor this according to the new tests.
Thanks! 🙂
https://lets-unify.ai/ivy/deep_dive/ivy_tests.html#ivy-tests

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
