### PR TITLE
feat: implements gradients function

### PR DESCRIPTION
**Pull request by esther-bello**
# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by vedpatwardhan — COMMENTED** [review]
I think we already have `execute_with_gradients` which computes the gradients, but I'll leave this with @Ookamice to review as this was an auto-requested review. Thanks @esther-bello 😄

**Comment by esther-bello** [comment]
> I think we already have `execute_with_gradients` which computes the gradients, but I'll leave this with @Ookamice to review as this was an auto-requested review. Thanks @esther-bello 😄

oh it wasn't ticked as taken that why I worked on it. shall I work on a different task then?

**Comment by esther-bello** [comment]
@Ookamice please let me know if the execute_with_gradients is the same as the gradients and if I should work on some other function/task. Thank you.

**Comment by esther-bello** [comment]
hi @vedpatwardhan could you kindly review this for me? Thanks.

**Comment by vedpatwardhan** [comment]
> hi @vedpatwardhan could you kindly review this for me? Thanks.

Hey @esther-bello, @ZoeCD will review this PR soon. Thanks for your patience 😄

**Comment by ZoeCD** [comment]
Hello @esther-bello!

Are you working on any of the open sub tasks? Can you share the link?
Because, as Ved mentioned, we already have  `execute_with_gradients` so you could implement the frontend calling `ivy.execute_with_gradients` or create a new issue and PR to add something that `execute_with_gradients` is missing.

**Comment by esther-bello** [comment]
> Hello @esther-bello!
> 
> Are you working on any of the open sub tasks? Can you share the link? Because, as Ved mentioned, we already have `execute_with_gradients` so you could implement the frontend calling `ivy.execute_with_gradients` or create a new issue and PR to add something that `execute_with_gradients` is missing.

Oh I thought the "execute_with_gradients" was different from the "gradients" function because it was open when I started working on it. Okay. I'll work on something else then, thanks.

**Comment by Ishticode** [comment]
I will close this PR for now as we already have gradient executing functions plus it calls current_ backend(..).gradients whereas gradients (with an s) doesnt exist in our backends which shows this implementation is incorrect. Lastly it has no test accompanying. Please feel free to reopen if you feel so while following our [contributing guidelines](https://unify.ai/docs/ivy/overview/contributing.html). Thanks

**Pull request closed without merging**
