### PR TITLE
inplace_decrement #3791

### PR DESCRIPTION
**Pull request by aryans1204**
add_reformatting_checklist_general

### CODE REVIEW

**Comment by aryans1204** [comment]
added_reformatting_checklist_general

**Comment by aryans1204** [comment]
Hi, it seems the checklist reformatting bot isn't working?

**Comment by aryans1204** [comment]
add_reformatting_checklist_elementwise

**Comment by aryans1204** [comment]
Hi, the bot works for the elementwise category, not the general category under which the inplace_decrement function belongs. Any ways around this?

**Comment by aryans1204** [comment]
add_reformatting_checklist_general

**Comment by aryans1204** [comment]
add_reformatting_checklist_general

**Comment by aryans1204** [comment]
waiting for review from @zaeemansari70

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hey! First of all thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Whether there is one problem, you have implemented different tasks in one PR.
You have to make separate pull requests for separate tasks respectively.
This won't take long as you have the changes, we have to follow a standard here at ivy🙂!
For more details you can refer to the docs https://lets-unify.ai/ivy/contributing.html
Thanks for understanding  🙂!

**Comment by aryans1204** [comment]
Hi,

As such, I'll close this pull request and issue a new pull request with only the inplace_decrement commits.

Thanks

**Pull request closed without merging**
