### PR TITLE
feat: Implementation of inv function in Paddle frontend.

### LINKED ISSUE #26522: inverse

### PR DESCRIPTION
**Pull request by HPatto**
# PR Description
Implementation of the inv function in Paddle frontend. Tests pass locally, although I believe namespace choice in the initial ToDo List should be changed. Current version of Paddle puts the inv function in the "paddle.linalg" namespace.

## Related Issue

Closes #26522 

## Checklist

- [y] Did you add a function?
- [y] Did you add the tests?
- [y] Did you run your tests and are your tests passing?
- [y] Did pre-commit not fail on any check?
- [y] Did you follow the steps we provided?

### CODE REVIEW

**Comment by HPatto** [comment]
I have some general thoughts/questions on the submission.

1. The namespace of the implemented function (paddle.linalg.inv) is different to the suggestion inside the ToDo List Issue (paddle.math.inv). This was done for two reasons: (1), it matches the current Paddle [documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/linalg/inv_en.html) and (2), the tests would throw a "Key Error" if the frontend function was not in the linalg namespace - I think it couldn't determine the ground truth.

2. The control of acceptable data-types is partially handled within the function decorator, and partially within the test definition. This mimics the implementation of jax.numpy.inv, but I'm not sure if it's best practice.

**Comment by KevinUnadkat** [comment]
hy @HPatto 
Everything seems to be fine , ill give it a final check soon and then merge it ,
thanks for contributing

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
The linked issue is for adding `paddle.inverse` (https://github.com/PaddlePaddle/Paddle/blob/release/2.2/python/paddle/tensor/math.py#L1167) and not `paddle.linalg.inv` even though both functions have the same functionality. Can you please move your function and the test to the correct files? Thanks :)

**Comment by HPatto** [comment]
Hey @hmahmood24,

Let me know if there's anything else to fix, and I'll get on it.

**Review by hmahmood24 — APPROVED** [review]
Changes look good to me. Thanks so much for the contribution! @HPatto 🚀

**Pull request merged**
