### PR TITLE
nanmedian

### PR DESCRIPTION
**Pull request by shireenchand**
added frontend and test for jax nanmedian function

### CODE REVIEW

**Comment by shireenchand** [comment]
#14214

**Comment by zhumakhan** [comment]
Hi @shireenchand, thanks for you PR! Test is failing due to torch backend implementation of nanmedian (torch does not have overwrite_input argument). Feel free to add fixes for it in this PR. Also, please use *available_dtypes=helpers.get_dtypes("valid")* in the tests.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by zhumakhan** [comment]
> Hi @shireenchand, thanks for you PR! Test is failing due to torch backend implementation of nanmedian (torch does not have overwrite_input argument). Feel free to add fixes for it in this PR. Also, please use _available_dtypes=helpers.get_dtypes("valid")_ in the tests.

Hi, issues mentioned above still exist, could you please make sure tests are passing on you local machine!
Thanks

**Pull request closed without merging**
