### PR TITLE
array_helpers.py/Fix sums_products_differences.test_numpy_nancumprod  #9886

### PR DESCRIPTION
**Pull request by moriisaac**
Fixed the subnormal  argument conflict that resulted in the float function returning a keyword argument error
close https://github.com/unifyai/ivy/issues/9886

### CODE REVIEW

**Comment by hirwa-nshuti** [comment]
Hey @moriisaac 
This looks like a newly introduced strategy 😊,
Would you clearly specify where it should be used and add it there for the tests to be run

Thanks

**Comment by moriisaac** [comment]
Hey @hirwa-nshuti 
It's a strategy I came up with to modify the 'array_values()' function so  as to handle the case where 'floats()' doesn't allow the "allow_subnormal"
The code should be implemented on from line 758 in array_helpers.py file.
The tests were successful☺

**Comment by moriisaac** [comment]
I'm unable to link the pr  to the issue #9886

**Comment by moriisaac** [comment]
@hirwa-nshuti 
The above commit is for the whole file array_helpers.py and my solution to the keyword argument.
the test fixed is 
#9886 test_numpy_nancumprod

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Would you add the changes to the corresponding file https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
This will help me to review them for now it seems like you introduced a new file🙂

**Comment by moriisaac** [comment]
I have made the necessary changes☺️

**Comment by hirwa-nshuti** [comment]
> I have made the necessary changes☺️

Check the file because I am getting a large number of lines of code added🤣

https://github.com/unifyai/ivy/pull/9908/files

**Comment by moriisaac** [comment]
The only lines changed are from 758 to 800.

**Comment by moriisaac** [comment]
I have made the necessary corrections🙃sorry for the confusion

**Comment by hirwa-nshuti** [comment]
Well the issue is that with the file changed on the PR it is indicating 952 lines added 
Try to have a look at your PR changes here https://github.com/unifyai/ivy/pull/9908/files
Better if you can go to the actual file in which you need to make changes and add the changes there.

**Comment by moriisaac** [comment]
I opened another pull request the one mentioned above and I have the necessary changes there, do help out with the merging.

**Comment by hirwa-nshuti** [comment]
As you opened another PR I'm closing this one. The one opened will get reviewed by the person assigned🙂

**Pull request closed without merging**
