### PR TITLE
implemented jax lax erf in the jax frontend and tested.

### PR DESCRIPTION
**Pull request by vaatsalya123**
#1578

### CODE REVIEW

**Comment by kimbring2** [comment]
@vaatsalya123 Hello, your code passes the test. However, you need to resolve the conflict for merging (: Please mention me after that.

**Comment by vaatsalya123** [comment]
Hello I am rather confused because two days ago when I committed the code it said that my merge was stable and it can be merged.Though today it says it cannot be merged could you explain why this could be.

**Comment by kimbring2** [comment]
@vaatsalya123 That is why there is a code change to the original repository. You need to resolve it or make another PR.

**Comment by vaatsalya123** [comment]
I think now we are now all good to go for merge thanks!

**Comment by bicycleman15** [comment]
Hey @vaatsalya123, the PR looks good however could you remove your changes on the following files from the commit:
1. `.idea/ivy.iml`
2. `.idea/misc.iml`

**Comment by vaatsalya123** [comment]
I removed .idea changes let me know if it is good for merge

**Comment by bicycleman15** [comment]
LGTM !

**Pull request merged**
