### PR TITLE
feat: Updated `TensorFlow` version mapping from `2.14.0` to `2.15.0`

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
New version of [TensorFlow 2.15.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.15.0) is released. So, I updated the version from `2.14.0` to `2.15.0`.

## Related Issue
Closes #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials
https://twitter.com/Sai_Suraj_27

### CODE REVIEW

**Comment by Sai-Suraj-27** [comment]
@vedpatwardhan please look into this when you are free, thank you.

**Comment by vedpatwardhan** [comment]
lgtm! could you please fix the merge conflicts so that we could merge the PR? Thanks @Sai-Suraj-27 😄

**Comment by Sai-Suraj-27** [comment]
> lgtm! could you please fix the merge conflicts so that we could merge the PR? Thanks @Sai-Suraj-27 😄

Done @vedpatwardhan 👍🏻, Please check now.

**Comment by vedpatwardhan** [comment]
Great, I'll merge the PR now, thanks @Sai-Suraj-27 😄

**Pull request merged**
