### PR TITLE
ifft

### LINKED ISSUE #17528: ifft

### PR DESCRIPTION
**Pull request by jakubbober**
Close #17528

### CODE REVIEW

**Comment by jakubbober** [comment]
I keep getting this error:
`NameError: free variable 'method_name' referenced before assignment in enclosing scope`

I am not sure why this pops up just in the test that I created, I would be grateful if the future assignee or someone else could explain to me what goes wrong and how this testing framework works exactly, because for now I was just writing analogous code to the one already existing.

**Comment by jakubbober** [comment]
Managed to solve it, but I still can't figure out which fixtures and parameters I can add to the test cases.

**Comment by jakubbober** [comment]
I would appreciate some help from anyone, or I could just close the PR and delete the issue to let someone else handle it who is more knowledgeable in this particular area.

**Comment by V-G-spec** [comment]
Hi @jakubbober! Apologies for the delay. The person who was previously asked to review your PR went on leave, and hence it is now re-assigned to me. Can you start by merging the conflict issues first? For fixtures/parameters, it's best to go through the testing deep dive series on YT. Let me know if you have any other doubts

Thanks!

**Pull request closed without merging**
