### PR TITLE
Implementation of Sigmoid for Ivy Experimental  

### LINKED ISSUE #23190: sigmoid

### PR DESCRIPTION
**Pull request by samthakur587**
# Implemented the sigmoid function for the ivy experimental.

## Implemented the sigmoid function for the ivy experimental with all the backend support jax, numpy , tensorflow , paddle , torch , with the ivy container and ivy array class. passing all the test heres the local results.

image

Close #23190

## Checklist

- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you add the tests?
- [x] Did you add a function?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by samthakur587** [comment]
hii @ndurumo254 can please review the PR. i am waiting for your review.

**Comment by samthakur587** [comment]
Hi! @KareemMAX can you please review and merge this PR. i tested in local it's passing all the test and please let me if any changes required here. 

thanks

**Comment by KareemMAX** [comment]
> Hi! @KareemMAX can you please review and merge this PR. i tested in local it's passing all the test and please let me if any changes required here.
> 
> thanks

Hey @samthakur587, sorry for the inconvenience. I'll take over the PR along with @ndurumo254 and look into it once I can.

**Comment by KareemMAX** [comment]
Hey @samthakur587, sadly I think this function is actually a [duplicate](https://unify.ai/docs/ivy/docs/functional/ivy/activations/ivy.functional.ivy.activations.sigmoid.html#sigmoid), let me check internally and get back to you

**Comment by samthakur587** [comment]
> Hey @samthakur587, sadly I think this function is actually a [duplicate](https://unify.ai/docs/ivy/docs/functional/ivy/activations/ivy.functional.ivy.activations.sigmoid.html#sigmoid), let me check internally and get back to you

it's in the core activation function i have implemented for the experimental and it is not present in here [experimental](https://unify.ai/docs/ivy/docs/functional/ivy/experimental/ivy.functional.ivy.experimental.activations.html). if i am not wrong.

**Comment by KareemMAX** [comment]
Hi @samthakur587,

I've corresponded with the team internally, sadly yes this ToDo entry is a duplicate, therefore we will close your PR. It's entirely our fault that we have listed this function as an open task, so your contribution is still considered if you are an applicant (but beware that our [hiring is now on pause](https://discord.com/channels/799879767196958751/939838320547090482/1162487857005477939)).

We are really sorry for the inconvenience we caused. Looking forward to your future contributions.

**Comment by samthakur587** [comment]
Hii @KareemMAX  if the sigmoid is present in the ivy.experimental api then why it's not there in any file that that we required to change for any api in experimental activation.

image

this is the tf backend but same for all backend as well for the ivy.experimental.activation and both the classes array and container.

can you please look into this.

**Comment by samthakur587** [comment]
i am not getting where is the actual problem.

**Comment by samthakur587** [comment]
okk @KareemMAX  now i understand the problem.

thanks

**Pull request closed without merging**
