### PR TITLE
adding take 

### LINKED ISSUE #11835: take

### PR DESCRIPTION
**Pull request by bhavyanarang**
Close #11835

### CODE REVIEW

**Comment by bhavyanarang** [comment]
Can you please guide me further, take was implemented in jax.numpy frontend and its implementation would be same to that for numpy so I have implemented that.

**Review by zaeemansari70 — COMMENTED** [review]
Hi @bhavyanarang !

Thanks for contributing to Ivy!

You are not handling these `arguments mode`,`unique_indices`,`indices_are_sorted`,`fill_value` in the function. These have to be added in the backend implementation as a superset first then called here.

Also, the one which is already implemented is an incorrect implementation it also has to be fixed. :slightly_smiling_face: 

Do let me know if you have any other questions!
Thanks! :slightly_smiling_face:

**Comment by bhavyanarang** [comment]
@zaeemansari70 Thanks for the explanation. I am working on the issue and will add commits most probably tomorrow.

**Comment by bhavyanarang** [comment]
@zaeemansari70 for some reason my ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py/take() function is not calling /workspaces/ivy/ivy/functional/ivy/experimental/manipulation.py/take() and calling some other take. Can you please let me know how to resolve this?

**Review by zaeemansari70 — COMMENTED** [review]
Do not continue implementing anything in this PR, as their is a design decision being made regarding this function that if it should exist in the functional API or not.
I will keep you updated regarding this :slightly_smiling_face: 
Thanks! :slightly_smiling_face:

**Pull request closed without merging**
