### PR TITLE
Percentile function for numpy frontend Ivy API

### PR DESCRIPTION
**Pull request by Tiago-B-C-Reis**
Add percentile to function frontend and respective unitest.
percentile https://github.com/unifyai/ivy/issues/8952

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

The PR looks good, a few changes are required:
1. You can remove `@from_zero_dim_arrays_to_float` decorator and instead use `@from_zero_dim_arrays_to_scalar` decorator.
2. Can you fix the lint errors caused by your PR.

Let me know if you need help with anything.
Thanks

**Comment by Tiago-B-C-Reis** [comment]
Hello @sherry30,
I need your help here, please.

I have two errors:

intelligent-tests-pr / run_tests_1 (pull_request) - this one I don't think is related to the function:
`"AssertionError: the return with a numpy backend produced data type of float64, while the return with a torch backend returned a data type of float32."`
The Numpy backend is returning a different type that the torch backend, and I don´t know why.

lint / check-formatting (pull_request) - this one is pointing formatting error in files that I haven´t changed:
`ivy/functional/frontends/torch/indexing_slicing_joining_mutating_ops.py:6:1: F401 'math' imported but unused`
`ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py:6:5: F401 'exceptions' imported but unused`

I would really appreciate your help and thank you in advance for your time.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

There are a few problems I noticed with the function implemented. 

You have to make the frontend function exactly like it is in that specific framework's documentation.
You can check out the documentation [here](https://numpy.org/doc/1.23/reference/generated/numpy.percentile.html). The function definition is a bit different from what you implemented (placement of `*` and `/` in the definition). There are a bunch of methods which can be set (e.g. `inverted_cdf`, `averaged_inverted_cdf`) in this function using the `method` argument, you will have to implement these compositionally if they are not present in ivy api.
(most of these are not in `ivy.quantile`).


As for the errors you are facing:
1. This error is related to the function you implemented, you can see it at the bottom of the error summary. `np.percentile` returns `float64` if the dtype of the input is lower than `float64`, you can check this out in the link i provided above of the documentation.
2. You can ignore the lint errors in this case 😃 .

Sorry I didn't notice the methods earlier, this function seems like a lot of work 😅  but I'd be happy to help you along the way

Thanks

**Comment by Tiago-B-C-Reis** [comment]
Hey @sherry30 , thanks for the reply! 
 
There are indeed some `method` variations that are not currently implemented. However, even if I wanted to implement them compositionally, it does not seem to exist any function within ivy (like suggested in the [Ivy do](https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html#compositions)) to replicate the behavior of such methods (e.g. `inverted_cdf`, `averaged_inverted_cdf`). 
As suggested in the documentation for cases like this, should we just document this in the code and wait for the respective future implementations in 'ivy.'?
Also, the `quantile` function on  [the ivy functional ivy experimental statistical ](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/experimental/statistical.py) makes relation to the already deprecated version of numpy.precentile before version 1.22.0 that does not have the argument "method" and its functions.
  
 About the error, the doc says it returns float64 when the input is smaller than float64. This seems like something we can't control. 

Nevertheless, I have committed again, so please also give it a check.

I'm giving a lot of effort to complete this task in order to have an accepted PR, but I'm reaching a dead end, do you have any tips or help that can give me?
 
 Many thanks

**Comment by sherry30** [comment]
After going through the function, I  somewhat agree that it should be added to the ivy API, since it is also present in tensorflow and jax. You should mention this in the issue you created for adding this function so it gets accepted soon and gets added in the todo list issues.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Tiago-B-C-Reis** [comment]
Hello [ivy-seed](https://github.com/ivy-seed),

This PR is waiting for the missing update on the [Ivy API Quantile function](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/experimental/statistical.py). Without it won't be possible to complete this PR like [sherry30](https://github.com/sherry30) mention on the comment above.

I had opened an issue to solve this, #8954 but was closed without the function being updated, yet.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
