### PR TITLE
added numpy array function and it's test

### LINKED ISSUE #6983: array

### PR DESCRIPTION
**Pull request by skydowx**
Close #6983

### CODE REVIEW

**Comment by jkeane508** [comment]
Hi,

It seems that tests didn't run the first time properly, will leave a review once they have run.

**Comment by skydowx** [comment]
Hi @jkeane508, is there something pending from my side? Doesn't look like the tests are failing from my code.

**Comment by jkeane508** [comment]
> Hi @jkeane508, is there something pending from my side? Doesn't look like the tests are failing from my code.

No nothing on your end, just a hectic week, apologies for not getting back sooner!

**Review by jkeane508 — APPROVED** [review]
LGTM!

**Pull request merged**
