### PR TITLE
First ever contribution

### LINKED ISSUE #21323: igamma

### PR DESCRIPTION
**Pull request by shakirriyaz**
Implemented igamma function in jax lax frontend 
Close #21323

### CODE REVIEW

**Comment by shakirriyaz** [comment]
Close #21323

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by shakirriyaz** [comment]
@D0m-inic I have linked the issue
Can you please check

**Comment by D0m-inic** [comment]
Hi, good work, just a few things.
Could you change the name of the test to remove the double underscore for consistency.
Could you also change the `available_dtypes` to use the `helpers.get_dtypes` method - the types for this function should be `valid`.
Could you also take a look at the parameters you're passing into `helpers.dtype_and_values` to get your testing data - try not to restrict any parameters (e.g. setting min's or max's) where you don't need to, so that all the valid types of data are tested 😄

**Comment by shakirriyaz** [comment]
@D0m-inic 
Changed the fn name
However , for the datatypes and min values, that is something the function demands of because of its domain
I checked the ivy.igamma function code and that takes float only as datatype 
Also its implementation in other libraries has the same code almost and that is already merged

**Comment by D0m-inic** [comment]
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.igamma.html

Taking a look at the docs, you can see that the function can take in more data types than just float 👍 .
The function can take in Arrays as well as individual values, so you should reflect this in the min and max dims of the `dtype_and_values` function.

Also, could you change the code so that x and xs are drawn from the same `dtype_and_x` call 😃

**Comment by D0m-inic** [comment]
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.igamma.html
Taking a look at the docs, you can see that the function can take in more data types than just float 👍 .

Could you take a look at the failling tests?

**Comment by danielmunioz** [comment]
Closing due to inactivity.
Sorry for any inconveniencies!

**Pull request closed without merging**
