### PR TITLE
Positive #426

### PR DESCRIPTION
**Pull request by chie2727**
PR for issue "positive #426" in "Update Element-wise Functions to Conform to Array API Standard #63".

### CODE REVIEW

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @chie2727 , thank you for your efforts! Can you uncomment "positive" in ivy_tests/array_api_methods_to_test/elementwise_functions.txt ?

**Comment by chie2727** [comment]
Hello @saeedashrraf , I have uncommented "positive" in the txt file.

**Comment by saeedashrraf** [comment]
Hello @chie2727, I need to rebase to the latest master branch. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR ?

**Comment by saeedashrraf** [comment]
Thank you for your contribution @chie2727 :)

**Pull request merged**
