### PR TITLE
refactor: Upgraded python code according to the latest standards using `pyupgrade`.

### LINKED ISSUE #23999: [Feature Request]: Upgrade Python code according to the latest standards at few places.
**Is your feature request related to a problem? Please describe.**
At many places in the codebase the Python code can be upgraded according to the latest standards, like the following:

image

image

**Describe the solution you'd like**
The solution for this is to use the [pyupgrade](https://github.com/asottile/pyupgrade) tool and modify all the files accordingly to follow the current latest standards of Python. This increases the readability and maintainability of the codebase.

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
I see that some code at many places in the codebase can be upgraded according to the latest standards of Python to increase the readability. I used the [pyupgrade](https://github.com/asottile/pyupgrade) tool for making these changes. This can also be added as a `pre-commit` hook but I just made the changes which I think will be very useful as of now.

## Related Issue
Close #23999 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:
https://twitter.com/Sai_Suraj_27

### CODE REVIEW

**Review by vedpatwardhan — COMMENTED** [review]
As always, I'll leave the formatting decisions with @KareemMAX, thanks @Sai-Suraj-27 😄

**Comment by hmahmood24** [comment]
> As always, I'll leave the formatting decisions with @KareemMAX, thanks @Sai-Suraj-27 😄

Agreed. @KareemMAX is the best person to review this. Sorry for putting this on your shoulders Kareem. Hope that's alright?

**Comment by KareemMAX** [comment]
Hey @Sai-Suraj-27,
LGTM but wanted to confirm somethings, can you confirm which python version this hook is working on? And @vedpatwardhan can you confirm what is the earliest python version we are supporting? I presume 3.8 if I remember correctly

**Review by KareemMAX — APPROVED** [review]

**Comment by Sai-Suraj-27** [comment]
> Hey @Sai-Suraj-27, LGTM but wanted to confirm somethings, can you confirm which python version this hook is working on? And @vedpatwardhan can you confirm what is the earliest python version we are supporting? I presume 3.8 if I remember correctly

Sir, I see that it requires python version >=3.8.1, (https://pypi.org/project/pyupgrade)

**Comment by vedpatwardhan** [comment]
> Hey @Sai-Suraj-27, LGTM but wanted to confirm somethings, can you confirm which python version this hook is working on? And @vedpatwardhan can you confirm what is the earliest python version we are supporting? I presume 3.8 if I remember correctly

exactly, the earliest python version we aim to support is 3.8 😄

**Review by KareemMAX — CHANGES_REQUESTED** [review]
LGTM overall. There are some conflicts that you need to fix. Also can you add it as a pre-commit hook? You may use `--py38-plus` argument for better results in our case.

**Comment by Sai-Suraj-27** [comment]
@KareemMAX sir, I have resolved the conflicts and regarding adding it as a pre-commit hook. Sure, I will create a PR for it immediately.

**Comment by KareemMAX** [comment]
> @KareemMAX sir, I have resolved the conflicts and regarding adding it as a pre-commit hook. Sure, I will create a PR for it immediately.
> 
> Edit: I have made the following PR (#26305) adding the `pyupgrade` pre-commit hook. All the changes in this PR are in that PR also, as this PR is almost like a subset of the new PR, So I request you to merge this first, so that the new PR can be updated and the other new changes made by `pyupgrade` can be reviewed more easily, Thank you.

I guess the best course of action now is to close this PR and merge #26305

**Pull request closed without merging**
