### PR TITLE
Added tan function and test in paddle.tensor.math for paddlepaddle frontend

### LINKED ISSUE #15915: tan

### PR DESCRIPTION
**Pull request by sachelsout**
Close #15915

### CODE REVIEW

**Comment by sachelsout** [comment]
Hello @suvadityamuk , could you please review my PR. :)

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey would you resolve the merge conflicts

**Review by hirwa-nshuti — APPROVED** [review]
Looks good to me😊

Thanks for contributing

**Comment by sachelsout** [comment]
> Looks good to me😊
> 
> Thanks for contributing

Thank you for reviewing and merging ❤️

**Pull request merged**
