### PR TITLE
Added fmax instance function to pytorch frontend

### LINKED ISSUE #13167: fmax

### PR DESCRIPTION
**Pull request by DebadityaPal**
Resolves #13167

### CODE REVIEW

**Comment by suvadityamuk** [comment]
Hi, @DebadityaPal!

Thank you for your contribution to Ivy! :grin: 

It seems there is a [small linting error in your Test](https://github.com/unifyai/ivy/actions/runs/4520697600/jobs/7961976882?pr=13169#step:5:31). Do you mind using the [Pre-commit hook](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit) in order to properly lint everything? 

Otherwise, more or less, LGTM!

Thanks again!

**Comment by DebadityaPal** [comment]
@suvadityamuk when I run the pre-commit about 50 files get changed with the black and flake8 hooks. I fixed the 2 files that I changed, would you like me to fix all the others as well?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by DebadityaPal** [comment]
@suvadityamuk can you review it once more?

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
