### PR TITLE
random distributions

### PR DESCRIPTION
**Pull request by DanielWit**
#3584 
#3585 
#3586 
#3587
#3588

### CODE REVIEW

**Comment by sreegandh804** [comment]
Hey @DanielWit , I would suggest you work on only 3 issues at the same time, once your PR for issues you assigned yourself gets merged you can assign yourself 3 more, this is so that we have issues free for the other contributors to work on. 🙂 
Feel free to take a look at the contributors guide for more information here : https://lets-unify.ai/ivy/contributing/1_the_basics.html#the-basics

**Comment by sreegandh804** [comment]
Hey @DanielWit , it also looks like you haven't added the test function to the relevant functions, could you look into that 😅

**Comment by DanielWit** [comment]
> Hey @DanielWit , it also looks like you haven't added the test function to the relevant functions, could you look into that 😅

hello sir, I just added a test for uniform() could you please check if is it done correctly before I add next ones thank you

**Comment by sreegandh804** [comment]
Hi @DanielWit , It looks good, but as I said would you only work on 3 issues at a time also I would suggest you make individual  comments on the main issue for each of the functions you selected with the issue number so that the issue gets assigned to you 🙂 https://lets-unify.ai/ivy/contributing.html

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
