### PR TITLE
greater_equal

### PR DESCRIPTION
**Pull request by LikhithaSadavala**
Added "greater_equal"

### CODE REVIEW

**Review by LikhithaSadavala — COMMENTED** [review]
Add greater_equal

**Comment by LikhithaSadavala** [comment]
fixes #4234

**Comment by Oxbeefbabe** [comment]
Hi @LikhithaSadavala , can you please find your function on one of the Todo Lists and make a reference to it in this PR.

Also, as part of the frontend function tasks, you need to implement the test for this function. Can you please get on that as well?

Finally, you seem to have a couple of lint errors in your code. If you fix them up that should unlock the rest of the workflow. If you check the Setting Up section in the docs you can find a pre-commit hook that will fix most lint errors and stop you from pushing any other changes that introduce lint errors in the future. I'd recommend setting up the pre-commit hook as it is a huge time saver :)

**Comment by LikhithaSadavala** [comment]
Close #4234

**Comment by LikhithaSadavala** [comment]
torch.Tensor.reciprocal #12946

**Pull request closed without merging**
