### PR TITLE
Eigh

### PR DESCRIPTION
**Pull request by arv0804**
#615

### CODE REVIEW

**Comment by arv0804** [comment]
#697  please check

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @arv0804 ,You still need to add the eigh implementation to the file ivy/functional/ivy/linear_algebra.py. You also need to uncomment the eigh from the file ivy_tests/array_api_methods_to_test/linear_algebra.txt

**Comment by arv0804** [comment]
#697 check please @saeedashrraf

**Comment by saeedashrraf** [comment]
Thank you for your contributions!

**Pull request merged**
