### PR TITLE
Add zipf function to Numpy Frontend

### PR DESCRIPTION
**Pull request by yaneholanda**

### CODE REVIEW

**Comment by yaneholanda** [comment]
Close #1530 zipf

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,
There's no `ivy.zipf` function, in this case you can either implement it compositionally using multiple ivy functions, or if you think its not that simple to implement this then you can create an issue for adding this in the experimental API
[docs](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) for reference

Thanks

**Comment by yaneholanda** [comment]
Hi @sherry30,
I implemented at ivy/functional/frontends/numpy/random/functions.py
Is my implementation incorrect?

**Comment by sherry30** [comment]
The implementation is incorrect because it uses `ivy.zipf` which does not exist in the ivy's functional API.
For that reason you can follow the steps I mentioned in my previous comment

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
