### PR TITLE
EHN: ACOSH added in paddle.tensor.tensor.Tensor class  from acosh #16007form list of function  #15115

### LINKED ISSUE #16007: acosh

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
I have added acosh in Tensor class. Closed #16007

### CODE REVIEW

**Comment by MuhammadNizamani** [comment]
@RickSanchezStoic I manually resolved the merge conflicts on GitHub, which is why the pre-commit check failed.

**Comment by RickSanchezStoic** [comment]
@RashulChutani The tests don't seem to be picking up, can you confirm once?

**Comment by RickSanchezStoic** [comment]
@RashulChutani It's still not picking up tests, even after resolving merge conflicts, please have a look. Thanks!

**Comment by MuhammadNizamani** [comment]
@RickSanchezStoic which tests you are talking about?

**Comment by RickSanchezStoic** [comment]
> @RickSanchezStoic which tests you are talking about?

`intelligent-tests-pr / run_tests (1) (pull_request) ` this is where you test is supposed to be executed.

**Comment by RashulChutani** [comment]
Hi @RickSanchezStoic Actually there is an issue with respect to the Memory Limit of GitHub Actions containers, which I am trying to fix. I will let you know as soon as it's done.

**Comment by MuhammadNizamani** [comment]
I locally run test for this function and It all passed.

**Comment by MuhammadNizamani** [comment]
@RashulChutani when 

> Hi @RickSanchezStoic Actually there is an issue with respect to the Memory Limit of GitHub Actions containers, which I am trying to fix. I will let you know as soon as it's done.

@RashulChutani when this issue will get solved . If you need some help I would to tag along.

**Comment by RashulChutani** [comment]
Hi @MuhammadNizamani I am working on the same. Actually the issue is due to a memory limit issue of GitHub actions. Thanks for offering help. I will let you know in case I need any

**Comment by MuhammadNizamani** [comment]
@RashulChutani I would love work with you

**Comment by MuhammadNizamani** [comment]
@RickSanchezStoic  when you are going to merge this ?

**Comment by RickSanchezStoic** [comment]
@RashulChutani the right tests are not being picked up here, could check this once please? Thanks

**Comment by MuhammadNizamani** [comment]
@RickSanchezStoic  it's been mounth could please review this

**Comment by MuhammadNizamani** [comment]
@RickSanchezStoic  review this please

**Comment by RickSanchezStoic** [comment]
@RashulChutani will they need to create a new pr because the tests still don't seem to be picking up ?

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @MuhammadNizamani 
Would you resolve the merge conflicts for CI run

**Comment by MuhammadNizamani** [comment]
@hirwa-nshuti I have resolve the merge conflict

**Review by hirwa-nshuti — APPROVED** [review]
Looks good to me😊
Going to merge

**Pull request merged**
