### PR TITLE
Test frontend methods refactor

### PR DESCRIPTION
**Pull request by mosesdaudu001**
# Refactored `test_frontend_method` to return frontend arrays before flattening to numpy

### CODE REVIEW

**Comment by AnnaTz** [comment]
Hey @sherry30, I'll leave this to you for reviewing since it's basically a testing issue. 
As far as the frontends are concerned, the PR seems to satisfy its purpose.

**Review by sherry30 — CHANGES_REQUESTED** [review]
We don't really need `test_compile` and `precision_mode` in the init flags right.
I guess we can remove those.
The rest looks good imo.
Feel free to merge it after running a few tests and making sure its working fine.
👍

**Comment by mosesdaudu001** [comment]
> We don't really need `test_compile` and `precision_mode` in the init flags right. I guess we can remove those. The rest looks good imo. Feel free to merge it after running a few tests and making sure its working fine. 👍

Done, and the tests are passing as well.

**Comment by AnnaTz** [comment]
> > We don't really need `test_compile` and `precision_mode` in the init flags right. I guess we can remove those. The rest looks good imo. Feel free to merge it after running a few tests and making sure its working fine. 👍
> 
> Done, and the tests are passing as well.

I think you merge it now as Sherry said 👍

**Pull request merged**
