### PR TITLE
Reformatting correlate #4101

### PR DESCRIPTION
**Pull request by nassimberrada**
Pull request for issue #4101

### CODE REVIEW

**Comment by nassimberrada** [comment]
add_reformatting_checklist_statistical

**Comment by nassimberrada** [comment]
Hello @modanesh !  Seeing that you have been assigned to this issue by the Ivy team i'd like to ask a question. 

In following the guidelines with regards to the formatting checklist i tried to run the Comment-to-Checklist process (see the comment above) but it seems to have failed due to an API limit.

Could you please provide me with guidance on how to proceed ? 

Thanks

**Comment by modanesh** [comment]
Sure. But before proceeding any further, I have a question. I can't find where `correlate` is mentioned in the original issue #812 . Am I missing something?

**Comment by nassimberrada** [comment]
I don't believe it is mentionned yet in the #812 issue. 
I was initially working on the implementation of the frontend correlate method as mentionned in the Add Statistical Functions to Numpy Frontend #1529 issue. At some point i had to make reference to the backend counterpart, but seeing that it had yet to be implemented i figured i would create an issue and suggest a pull request to implement it first before resuming work on the frontend side.
Is that maybe the origin of the problem ?

**Comment by modanesh** [comment]
So you basically need to implement the correlate function as a composition of existing ivy functions. I recommend you to check the [open tasks section in the contributor guide](https://lets-unify.ai/ivy/contributing/4_open_tasks.html). So I'll close this PR. Thanks 🙂

**Pull request closed without merging**
