### PR TITLE
Added bitwise_xor to Jax frontend

### PR DESCRIPTION
**Pull request by Pranjal-bisht**
Close https://github.com/unifyai/ivy/issues/6235

### CODE REVIEW

**Comment by Pranjal-bisht** [comment]
Local Test case passed
image

Issue no. :
- [] #6235

**Comment by guillesanbri** [comment]
Hi! Thanks a lot for contributing to Ivy, some things to review:
- Looks like there are two functions being added in this PR, could you please remove the one that is not in the issue? We are managing functions one at a time to keep things organized 😁
- Also looks like the formatting of the files has been modified (probably due to some auto-formatting tool) with 8 spaces in the args lines, this should be fixed by using the [pre-commit hook](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit)

Thanks once again!

**Comment by Pranjal-bisht** [comment]
Hi @guillesanbri , 
I have corrected the formatting and also removed the unnecessary functions ( Actually , I by mistakenly commit my previous branch code as well :), sorry for that. ) . Hope, everything is fine now.
Thanks for reviewing.
Close #6235

**Comment by Pranjal-bisht** [comment]
`Close #6235 `

**Comment by guillesanbri** [comment]
Thanks for the changes! I am looking into why the PR is not linking to the issue but the rest looks good to me, will merge it as soon as I find out why it isn't linking correctly 🙂​

**Comment by guillesanbri** [comment]
Problem solved, thanks once again for the contribution!

**Pull request merged**
