### PR TITLE
fix: Function Reformatting of is_int_dtype function

### LINKED ISSUE #23534: is_int_dtype

### PR DESCRIPTION
**Pull request by pavan999999999**
Replacing lambda function with function defined with def in is_int_dtype function of data_type.py submodule

# PR Description

## Related Issue

Close #23534 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by pavan999999999** [comment]
Hi @bipinKrishnan, can you tell me whether I have to work on the failing testcases or not?

**Comment by bipinKrishnan** [comment]
Hey @pavan999999999 , your issue is not correctly linked to the main to-do list. You should follow the instructions mentioned [here](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) to correctly link issues. For now I'll link the issue manually🙂.

**Comment by pavan999999999** [comment]
Thanks @bipinKrishnan for guiding me, will do it correctly next time onwards

**Comment by bipinKrishnan** [comment]
LGTM! Thanks for the contribution @pavan999999999 🚀.

**Pull request merged**
