### PR TITLE
add diagonal to all 5 frameworks + ivy core

### PR DESCRIPTION
**Pull request by Abdelrhman-Hosny**
Add diagonal to the 5 frameworks, solves issue #118 

- [x] torch
- [x] mxnet
- [x] jax
- [x] tf
- [x] np

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

For resolving conflicts with upstream, I have created this [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG) on the entire process of making a PR, including how best to keep this aligned with upstream.

**Comment by djl11** [comment]
Seems as though the array API tests for diagonal are not passing. I just checked the CI logs for JAX and it's failing, I presume the same is true for other backends. Are the tests passing for you locally?

**Comment by djl11** [comment]
accidentally closed

**Comment by Abdelrhman-Hosny** [comment]
It fails in jax and tensorflow locally, it fails at the `@given` decorator that belongs to the `hypothesis` library in array API tests,
The error is `TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment`.

works locally using `numpy` and `torch`

**Review by djl11 — CHANGES_REQUESTED** [review]
The diagonal methods are in the wrong place. Can you please move from ivy.functional.backends.some_backend.core to ivy.functional.backends.some_backend.array_api

The correct file is either linear_algebra_functions or linear_algebra_extensions, you will have to check the standard online.

**Comment by Abdelrhman-Hosny** [comment]
I've moved the functions to the correct locations, however I'm still failing the tensorflow and jax tests locally, both of them failing because a function called `do_draw` in `hypothesis` library is trying to assign a variable in a tensor.

The two errors are `TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment` and 
`TypeError: '<class 'jaxlib.xla_extension.DeviceArray'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method:....`

Tests pass numpy and torch tests

**Review by djl11 — CHANGES_REQUESTED** [review]
I seem to be unable to push to your repo. Could you please give me write access so I can merge with upstream?

**Comment by Abdelrhman-Hosny** [comment]
> I seem to be unable to push to your repo. Could you please give me write access so I can merge with upstream?

The allow edits by maintainers was already checked, I rechecked it again just in case

I've also added the check for the `_wrapped_function.reduce` as discussed in #165

**Review by djl11 — CHANGES_REQUESTED** [review]
Please fix type hint for jax. We should use the Union JaxArray as is done for other backends. This makes it explicit that many different array types may pass into the method, depending on whether jax is performing tracing or not.

**Pull request merged**
