### PR TITLE
Zamokuhle23 patch 1

### LINKED ISSUE #19853: adaptive_avg_pool3d

### PR DESCRIPTION
**Pull request by Zamokuhle23**
Close #19853

### CODE REVIEW

**Review by Dsantra92 — COMMENTED** [review]
Hi @Zamokuhle23, thank you for taking the time for contributing to ivy. It would be very helpful if you could reformat your pr according the [contributor guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Zamokuhle23** [comment]
Ok Thanks, I have added Close + issue_number and re-requested

**Comment by Aarsh2001** [comment]
Hey @Zamokuhle23, my apologies for the delayed response. This PR looks like a good merge, thank you for you contribution 🙂

**Pull request merged**
