### PR TITLE
copy_array

### PR DESCRIPTION
**Pull request by davidlee1102**
Nice to see you again 😺 
Hope that you can check the code for me and give some feedbacks for this 
Thank you
David

### CODE REVIEW

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hi @davidlee1102, nice to see you again! Please make the following changes to the docstring before we merge your PR:
1. Please add the `Functional Examples` heading before the functional examples as suggested [here](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html).
2. Please update the `ivy.Container` examples by passing multiple arrays to the container with different keywords, because that's the advantage with `ivy.Container` over `ivy.Array`.
3. Please also add `Instance Method Examples` to the docstring as specified on the same page.
Feel free to ask any questions. Thanks 🙂

**Comment by davidlee1102** [comment]
Hi @VedPatwardhan ,
About your request,
1. I have fixed, could you check it for me again?
2. I also added more multiple arrays to the container with different keywords, , could you check it for me again?
3. I also fixed, could you check it for me again?
Thank you, hope you have a nice weekend 😺 
David

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Great work! One last update, we don't need mixed input examples for instance methods, please remove those. Thanks 🙂

**Comment by davidlee1102** [comment]
Hi @VedPatwardhan,
I have fixed, let check :D 
David

**Review by VedPatwardhan — APPROVED** [review]
lgtm!

**Pull request merged**
