### PR TITLE
round_ implemented for torch frontend

### LINKED ISSUE #17513: round_

### PR DESCRIPTION
**Pull request by DebadityaPal**
Closes #17513

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@DebadityaPal Please resolve the conflicts!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by nathzi1505** [comment]
Hey @DebadityaPal it looks there are some merge conflicts. Would you mind looking at those and resolving them?

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
