### PR TITLE
added flatten (tensorflow)

### PR DESCRIPTION
**Pull request by jgyfutub**
#19158

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by mobley-trent** [comment]
Hey there @jgyfutub its good practice to create another branch to work on your feature instead of working on the `master` branch

**Comment by jgyfutub** [comment]
@mobley-trent okk..thanks for your advice, can you please help in reviewing my pr?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by mobley-trent** [comment]
Hi @jgyfutub your PR looks great ✨ 
The test strategy is not set up correctly. Follow the guidelines on the [docs](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#introduction) for more info 🙂

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
