### PR TITLE
feat: implement average_max_pool3d in torch frontend

### LINKED ISSUE #26132: adaptive_max_pool3d

### PR DESCRIPTION
**Pull request by Amit0617**
# PR Description

## Related Issue

Close #26132 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Amit0617** [comment]
Regarding Protected Branch, I read and re-read the contributing guidelines. I can't see any instructions regarding branch.
Also can't find any file called `display_test_results`

**Comment by AlexandraPosta** [comment]
Hello @Amit0617, thank you for your contribution! :zap:

To answer your questions, you currently have a PR open for the main, so you are all set up from a branch point of view. "display_test_results" is a job that is automatically run by our CI Pipeline, please find more information [in our documentation](https://unify.ai/docs/ivy/overview/deep_dive/continuous_integration.html). The main take is that you should check the log to see the failing tests.

In terms of your function implementation, please make sure to test the function locally. Please revisit the (un)supported_dtypes.   Additionally, you need to take into consideration that quite a few backends (numpy, jax, tensorflow, torch, paddle) do not have an implementation for adaptive_max_pool3d.

**Comment by Amit0617** [comment]
> quite a few backends (numpy, jax, tensorflow, torch, paddle) do not have an implementation for adaptive_max_pool3d.

I guess that means there isn't any of the backend implementation existing and that's why testing goes empty.

**Comment by AlexandraPosta** [comment]
Hello @Amit0617, did you explore any other solutions?

**Comment by Amit0617** [comment]
Looks like it is dependent on https://github.com/unifyai/ivy/pull/22631

**Comment by Ishticode** [comment]
although this is draft I am closing it due to the fact that this already exists in torch frontend.

**Pull request closed without merging**
