### PR TITLE
add multiplication function

### PR DESCRIPTION
**Pull request by utkarshraj779**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Aarsh2001 — CHANGES_REQUESTED** [review]
Hey @utkarshraj779, kindly add the #issue_number as well as a test for this function, thanks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Aarsh2001** [comment]
Closing this PR because of no activity

**Pull request closed without merging**
