### PR TITLE
feat: Add tensorflow GatherNd raw_ops

### LINKED ISSUE #27443: GatherNd

### PR DESCRIPTION
**Pull request by TalhaKhalil**
# PR Description

## Related Issue

Closes #27443

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by TalhaKhalil** [comment]
Hi @he11owthere, 

Hope you are doing well, 

So, I had implemented GatherNd in raw ops for tensorflow. But the issue I am currently facing is that out of 5 tests sometimes 4 or 3 are passing.
I am not quite sure what the problem is exactly and why they are not passing 100%.

Would really appreciate if you could help me out with this.

**Review by he11owthere — COMMENTED** [review]
Hello @TalhaKhalil, correct me if I am wrong but I think indices must have at least as many dimensions as the input tensor.
Try using these values:
```
min_num_dims=1,
max_num_dims=5,
min_dim_size=1,
max_dim_size=10,
indices_same_dims=True,
```

**Comment by TalhaKhalil** [comment]
@he11owthere I changed these parameters in the test function but as of now none of the tests are passing

**Comment by he11owthere** [comment]
> @he11owthere I changed these parameters in the test function but as of now none of the tests are passing

For me, all the tests are passing with these values:
```
min_num_dims=3,
max_num_dims=3,
min_dim_size=1,
max_dim_size=3,
axis_zero=True,
disable_random_axis=True,
indices_same_dims=True,
```

After making these changes, you will have to include a `with_supported_dtypes` decorator and add appropriate data types after running the tests.

**Comment by TalhaKhalil** [comment]
@he11owthere Can you tell me the the data types to be included along with the decorator `with_supported_dtypes `.

**Comment by he11owthere** [comment]
> @he11owthere Can you tell me the the data types to be included along with the decorator `with_supported_dtypes `.

You will have to run the tests and will face errors regarding unsupported data types like `int16` is not supported by some backend so you will get to know which data types are supported and which are not.

**Review by NripeshN — APPROVED** [review]

**Pull request merged**
