### PR TITLE
dice loss Paddle Frontend nn functions 

### LINKED ISSUE #18231: dice_loss

### PR DESCRIPTION
**Pull request by ligia26**
Close #18231

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by abdulasiraj** [comment]
Hi @ligia26 
Thanks for your great work. There's somethings you're missing. 

1. Add the test functions for dice lose in this file `ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_loss.py` and make sure all tests are passed.
2. Kindly remove the `.patteric` file.

Thanks Again!

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
Hi @ligia26 
Thanks for your great work. There're somethings you've missed. 

1. Add the test functions for dice lose in this file `ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_loss.py` and make sure all tests are passed.
2. Kindly remove the `.patteric` file.

Thanks Again!

**Comment by ligia26** [comment]
I cannot fix this conflict myself, could you please have a look?

**Review by ligia26 — COMMENTED** [review]
tests added

**Comment by abdulasiraj** [comment]
Hi @ligia26 
Your branch contains some illegal characters which shouldn't be there. So please try to remove those, If you can't as they are hidden. Please create a new branch and copy paste only your code lines. Also, when you're trying to commit, only add your files only. This'll help in unnecessary files created by OS.
Thanks!

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
Hi @ligia26 
Your branch contains some illegal characters which shouldn't be there. So please try to remove those, If you can't as they are hidden. Please create a new branch and copy paste only your code lines. Also, when you're trying to commit, only add your files only. This'll help to avoid in unnecessary files created by OS.
Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
