### PR TITLE
tensorflow_sinh

### PR DESCRIPTION
**Pull request by AmroGFarghali**

### CODE REVIEW

**Comment by AmroGFarghali** [comment]
Close #12917

**Comment by Infrared1029** [comment]
hello @AmroGFarghali! Thanks a lot for your contribution! your PR includes the `.ivy` folder by mistake, it should not be there, can you remove it?

**Comment by AmroGFarghali** [comment]
> hello @AmroGFarghali! Thanks a lot for your contribution! your PR includes the `.ivy` folder by mistake, it should not be there, can you remove it?

I removed the folder as mentioned, thank you for the review

**Comment by Infrared1029** [comment]
everything looks good to me, just change the default value of `name` to `None` (not super critical but just to make everything consistent with tensorflow's docs) also make sure you are testing `complex` values in the tests alongside `floats`, will merge after that, thanks a lot for your contribution!

**Comment by AmroGFarghali** [comment]
> everything looks good to me, just change the default value of `name` to `None` (not super critical but just to make everything consistent with tensorflow's docs) also make sure you are testing `complex` values in the tests alongside `floats`, will merge after that, thanks a lot for your contribution!

Updated with the mentioned changes, thanks so much for the reviews!

**Comment by Infrared1029** [comment]
lgtm, merging!

**Pull request merged**
