### PR TITLE
added trunc function to frontend.paddle.tensor.math

### LINKED ISSUE #17563: trunc

### PR DESCRIPTION
**Pull request by nikita-jare**
Close #17563

### CODE REVIEW

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi @nikita-jare, thanks for looking into this :)
Could you please resolve the conflicts? Apart from that, everything looks good to me

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi @nikita-jare, you seem to be accidentally editing the unrelated ivy_tests/array_api_testing/test_array_api submodule. Could you please undo the changes?
It looks like some tests are failing, which might be due to above edits, but in case they aren't, could you please fix those too?
Feel free to request a review afterwards. Thanks! :)

**Comment by rishabgit** [comment]
Hi @nikita-jare there was a slight issue with the decorator used. It should be `supported` instead of `unsupported` - https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/trunc_en.html
Updated the code and everything lgtm! 
Thanks a ton for adding this! :)

**Comment by nikita-jare** [comment]
Thank you so much for correcting the mistake @rishabgit.

**Pull request merged**
