### PR TITLE
Torch.vander Frontend

### PR DESCRIPTION
**Pull request by nassimberrada**

### CODE REVIEW

**Comment by nassimberrada** [comment]
**Error**: Field elements must be 2- or 3-tuples
>           x=np.asarray(x, dtype=input_dtype),

**Review by Ishticode — CHANGES_REQUESTED** [review]
Depending on [this issue](https://github.com/unifyai/ivy/issues/4908), when the vander function is added to the Ivy API, we should be able to change the frontend to direct call to the `ivy.vander`.

**Review by Ishticode — CHANGES_REQUESTED** [review]
I think this can move forward now and should be simple although there are some conflict. See if you can fix the easily. Let me know how it goes. Thnx.🙂

**Comment by nassimberrada** [comment]
I pushed the implementation using a version that doesn't yet include ivy.vander because it is a bit lagging behind the master, would that make the tests on your side automatically fail ?

**Comment by Ishticode** [comment]
> I pushed the implementation using a version that doesn't yet include ivy.vander because the branch i worked on is a bit lagging behind the master, would that make the tests on your side automatically fail ?

It would lag behind as I run your tests on your branch so its exactly the same as yours.    
I think if you sync your master fork it should able to update your branch by `git fetch and merge` then the new implementation should come in. Let me know if it doesn't work. If it causes any trouble, you can just create new branch from the synced in master and copy over the two updates and create a new pr.

**Comment by nassimberrada** [comment]
Done, Should be ready to merge i think

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi Nassim. Yh about ready to merge. 
But I tried test and it fails for numpy but when I change `N` min_value to 1 in the `@given` parametrisation of the test it passes.

Could you change the test OR see if/why N=0 might cause any issues. if it does we can handle N=0 as a special case. It's not a big deal.

Besides that just a reminder to fix the lints and then i will get this merged. Great work on this. Come a far way 🙂.

**Comment by nassimberrada** [comment]
I tried to handle N=0 as a special case but somehow it started giving inconsistencies in data types, i figured i would just up the min value of N to 1 in the tests as you said, given that there's no much use in the function for a value of N=0 i guess.
I don't think there's any lint error left too, so unless you'd rather i try to crack down that special case then we could move forward with this.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hmmm from the commit for handling N=0 case, I see that it has code

```python
def vander(x, N=None, increasing=False):
    if N == 0:
        return ivy.array([], dtype=input.dtype)
    else:
...
```

I guess you mistakenly put `input.dtype` instead of the `x.dtype`. Could you try that?

**Comment by nassimberrada** [comment]
Commit name says it all, my bad

**Review by Ishticode — APPROVED** [review]
😂 it can happen. I will get this merged. Thank you very much @nassimberrada

**Pull request merged**
