### PR TITLE
greater_equal

### PR DESCRIPTION
**Pull request by Mohamed-dewidar**

### CODE REVIEW

**Comment by Mohamed-dewidar** [comment]
Close #13651

**Comment by hirwa-nshuti** [comment]
Hey @Mohamed-dewidar 

Would you check if you have added proper content to the PR for us to start the review process

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Mohamed-dewidar 
Thank you for the PR. As @hirwa-nshuti pointed out, Could you kindly update and add appropriate content and exclude .idea files. Feel free to explore [the deep dive section](https://lets-unify.ai/docs/ivy/overview/deep_dive.html) if you are unsure about anything or ask a question.
Thanks 🙂.

**Comment by Mohamed-dewidar** [comment]
I will work on it
but I did not know where is the problem
Thanks for help.

**Pull request closed without merging**
