### PR TITLE
Update arctan2 numpy frontend

### PR DESCRIPTION
**Pull request by Nouran6Gamal**

### CODE REVIEW

**Comment by Nouran6Gamal** [comment]
@sreegandh804 any changes I can do ? , only lint check passed , checks that didn't passed don't show any error to solve except for docstrings errors

**Review by Nouran6Gamal — COMMENTED** [review]
any changes I can do ? , only lint check passed , checks that didn't pass don't show any error to solve except for docstrings errors
(my old pull request with many changes https://github.com/unifyai/ivy/pull/3834 , here with only 2 commits)

**Comment by sreegandh804** [comment]
Hi @Nouran6Gamal , could you make a comment mentioning the Issue number of the function which was assigned to you, and also just to clarify, if you already have a PR that resolves the same issue, I would suggest you close this PR and continue fixing the errors in your old Pr which can be looked into by the assignee of the PR. 🙂

**Comment by Nouran6Gamal** [comment]
@sreegandh804 I 'll close it , thanks

**Comment by Nouran6Gamal** [comment]
@sreegandh804  I apologize I deleted the related fork to the old pr and I can't shift the new fork to the old pr , can you assign here @sherry30  and I 'll close the old pr ?

**Comment by sreegandh804** [comment]
Sure, will do it right away 👍

**Comment by Nouran6Gamal** [comment]
@sreegandh804 thanks , I'll close the old one

**Comment by Nouran6Gamal** [comment]
That pr is to complete that pr https://github.com/unifyai/ivy/pull/3834  @sherry30 
what should I edit for this error 

2022-09-05T08:57:09.5877399Z E AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
2022-09-05T08:57:09.5877469Z E
2022-09-05T08:57:09.5877544Z E ret_np_flat:
2022-09-05T08:57:09.5877612Z E
2022-09-05T08:57:09.5877678Z E []
2022-09-05T08:57:09.5877748Z E
2022-09-05T08:57:09.5877832Z E ret_np_from_gt_flat:
2022-09-05T08:57:09.5877884Z E
2022-09-05T08:57:09.5877973Z E [array(0., dtype=float16)]

**Comment by Nouran6Gamal** [comment]
ivy/ivy_tests/test_ivy/helpers.py:3250: in new_fn
2022-09-05T08:57:09.5872162Z return test_fn(*args, **kwargs)
2022-09-05T08:57:09.5872387Z ivy/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py:318: in test_numpy_arctan2
2022-09-05T08:57:09.5872455Z @given(
2022-09-05T08:57:09.5872677Z ivy/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py:348: in test_numpy_arctan2
2022-09-05T08:57:09.5872797Z np_frontend_helpers.test_frontend_function(
2022-09-05T08:57:09.5872960Z ivy/ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py:49: in test_frontend_function
2022-09-05T08:57:09.5873095Z _test_frontend_function_ignoring_unitialized(*args, **kwargs)
2022-09-05T08:57:09.5873292Z ivy/ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py:39: in _test_frontend_function_ignoring_unitialized
2022-09-05T08:57:09.5873451Z helpers.value_test(ret_np_flat=ret_flat, ret_np_from_gt_flat=frontend_ret_flat)
2022-09-05T08:57:09.5873544Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2022-09-05T08:57:09.5873549Z
2022-09-05T08:57:09.5873621Z def value_test(
2022-09-05T08:57:09.5873687Z *,
2022-09-05T08:57:09.5873760Z ret_np_flat,
2022-09-05T08:57:09.5873841Z ret_np_from_gt_flat,
2022-09-05T08:57:09.5873911Z rtol=None,
2022-09-05T08:57:09.5874018Z atol=1e-6,
2022-09-05T08:57:09.5874116Z ground_truth_backend="TensorFlow",
2022-09-05T08:57:09.5874180Z ):
2022-09-05T08:57:09.5874323Z """Performs a value test for matching the arrays in ret_np_flat and
2022-09-05T08:57:09.5874402Z ret_from_np_flat.
2022-09-05T08:57:09.5874464Z
2022-09-05T08:57:09.5874536Z Parameters
2022-09-05T08:57:09.5874628Z ----------
2022-09-05T08:57:09.5874750Z ret_np_flat
2022-09-05T08:57:09.5874889Z A list (flattened) containing Numpy arrays. Return from the
2022-09-05T08:57:09.5874975Z framework to test.
2022-09-05T08:57:09.5875052Z ret_from_np_flat
2022-09-05T08:57:09.5875197Z A list (flattened) containing Numpy arrays. Return from the ground
2022-09-05T08:57:09.5875279Z truth framework.
2022-09-05T08:57:09.5875334Z rtol
2022-09-05T08:57:09.5875426Z Relative Tolerance Value.
2022-09-05T08:57:09.5875494Z atol
2022-09-05T08:57:09.5875585Z Absolute Tolerance Value.
2022-09-05T08:57:09.5875666Z ground_truth_backend
2022-09-05T08:57:09.5875769Z Ground Truth Backend Framework.
2022-09-05T08:57:09.5875834Z
2022-09-05T08:57:09.5875890Z Returns
2022-09-05T08:57:09.5875992Z -------
2022-09-05T08:57:09.5876126Z None if the value test passes, else marks the test as failed.
2022-09-05T08:57:09.5876196Z """
2022-09-05T08:57:09.5876351Z if type(ret_np_flat) != list:
2022-09-05T08:57:09.5876445Z ret_np_flat = [ret_np_flat]
2022-09-05T08:57:09.5876549Z if type(ret_np_from_gt_flat) != list:
2022-09-05T08:57:09.5876650Z ret_np_from_gt_flat = [ret_np_from_gt_flat]
2022-09-05T08:57:09.5876777Z > assert len(ret_np_flat) == len(ret_np_from_gt_flat), (
2022-09-05T08:57:09.5876898Z "len(ret_np_flat) != len(ret_np_from_gt_flat):\n\n"
2022-09-05T08:57:09.5877035Z "ret_np_flat:\n\n{}\n\nret_np_from_gt_flat:\n\n{}".format(
2022-09-05T08:57:09.5877138Z ret_np_flat, ret_np_from_gt_flat
2022-09-05T08:57:09.5877207Z )
2022-09-05T08:57:09.5877272Z )
2022-09-05T08:57:09.5877399Z E AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
2022-09-05T08:57:09.5877469Z E
2022-09-05T08:57:09.5877544Z E ret_np_flat:
2022-09-05T08:57:09.5877612Z E
2022-09-05T08:57:09.5877678Z E []
2022-09-05T08:57:09.5877748Z E
2022-09-05T08:57:09.5877832Z E ret_np_from_gt_flat:
2022-09-05T08:57:09.5877884Z E
2022-09-05T08:57:09.5877973Z E [array(0., dtype=float16)]
2022-09-05T08:57:09.5877979Z
2022-09-05T08:57:09.5878103Z ivy/ivy_tests/test_ivy/helpers.py:759: AssertionError
2022-09-05T08:57:09.5878356Z ----------------------------- Captured stderr call -----------------------------
2022-09-05T08:57:09.5878697Z WARNING:root:NumPy does not support autograd, declaring a 'variable' is identical to declaring an 'array' when using numpy backend.
2022-09-05T08:57:09.5879031Z WARNING:root:NumPy does not support autograd, declaring a 'variable' is identical to declaring an 'array' when using numpy backend.
2022-09-05T08:57:09.5879276Z ------------------------------ Captured log call -------------------------------
2022-09-05T08:57:09.5879637Z WARNING root:gradients.py:9 NumPy does not support autograd, declaring a 'variable' is identical to declaring an 'array' when using numpy backend.
2022-09-05T08:57:09.5879990Z WARNING root:gradients.py:9 NumPy does not support autograd, declaring a 'variable' is identical to declaring an 'array' when using numpy backend.
2022-09-05T08:57:09.5880234Z ---------------------------------- Hypothesis ----------------------------------
2022-09-05T08:57:09.5880341Z Falsifying example: test_numpy_arctan2(
2022-09-05T08:57:09.5880498Z dtype_and_x=(['float16', 'float16'],
2022-09-05T08:57:09.5880653Z [-0.9090909090909091, -0.9090909090909091]),
2022-09-05T08:57:09.5880768Z dtype='float16',
2022-09-05T08:57:09.5880841Z where=False,
2022-09-05T08:57:09.5880933Z as_variable=[False, False],
2022-09-05T08:57:09.5880997Z with_out=False,
2022-09-05T08:57:09.5881082Z num_positional_args=2,
2022-09-05T08:57:09.5881174Z native_array=[False, False],
2022-09-05T08:57:09.5881277Z fw='numpy',
2022-09-05T08:57:09.5881343Z )
2022-09-05T08:57:09.5881433Z Falsifying example: new_fn(
2022-09-05T08:57:09.5881496Z data=data(...),
2022-09-05T08:57:09.5881727Z get_command_line_flags={'as_variable': None,
2022-09-05T08:57:09.5881855Z 'native_array': None,
2022-09-05T08:57:09.5881970Z 'with_out': None,
2022-09-05T08:57:09.5882087Z 'container': None,
2022-09-05T08:57:09.5882215Z 'instance_method': None,
2022-09-05T08:57:09.5882343Z 'test_gradients': None},
2022-09-05T08:57:09.5882439Z device='cpu',
2022-09-05T08:57:09.5882725Z f=<module 'ivy.functional.backends.numpy' from '/ivy/ivy/functional/backends/numpy/init.py'>,
2022-09-05T08:57:09.5882828Z fw='numpy',
2022-09-05T08:57:09.5882892Z )
2022-09-05T08:57:09.5882995Z Falsifying example: test_numpy_arctan2(
2022-09-05T08:57:09.5883149Z dtype_and_x=(['float16', 'float16'],
2022-09-05T08:57:09.5883303Z [-0.9090909090909091, -0.9090909090909091]),
2022-09-05T08:57:09.5883403Z dtype='float16',
2022-09-05T08:57:09.5883474Z where=False,
2022-09-05T08:57:09.5883561Z as_variable=[False, False],
2022-09-05T08:57:09.5883633Z with_out=False,
2022-09-05T08:57:09.5883763Z num_positional_args=2,
2022-09-05T08:57:09.5883854Z native_array=[False, False],
2022-09-05T08:57:09.5883955Z fw='numpy',
2022-09-05T08:57:09.5884007Z )
2022-09-05T08:57:09.5884292Z ____ test_numpy_deg2rad[cpu-ivy.functional.backends.numpy-True-False-numpy] ____
2022-09-05T08:57:09.5884298Z
2022-09-05T08:57:09.5884595Z get_command_line_flags = {'as_variable': None, 'container': None, 'instance_method': None, 'native_array': None, ...}
2022-09-05T08:57:09.5884698Z device = 'cpu'
2022-09-05T08:57:09.5884982Z f = <module 'ivy.functional.backends.numpy' from '/ivy/ivy/functional/backends/numpy/init.py'>
2022-09-05T08:57:09.5885123Z fw = 'numpy', args = (), kwargs = {}
2022-09-05T08:57:09.5885128Z
2022-09-05T08:57:09.5885208Z @given(data=st.data())
2022-09-05T08:57:09.5885284Z > @settings(max_examples=1)
2022-09-05T08:57:09.5885300Z
2022-09-05T08:57:09.5885393Z ivy/ivy_tests/test_ivy/helpers.py:3222:

**Review by Nouran6Gamal — COMMENTED** [review]
what should I edit for this error  @sherry30 

2022-09-05T08:57:09.5877399Z E AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):
2022-09-05T08:57:09.5877469Z E
2022-09-05T08:57:09.5877544Z E ret_np_flat:
2022-09-05T08:57:09.5877612Z E
2022-09-05T08:57:09.5877678Z E []
2022-09-05T08:57:09.5877748Z E
2022-09-05T08:57:09.5877832Z E ret_np_from_gt_flat:
2022-09-05T08:57:09.5877884Z E
2022-09-05T08:57:09.5877973Z E [array(0., dtype=float16)]

I added min_num_dims=1 & i solved the conflict of my branch then I found my function arctan2 and function deg2rad merged so I copied the original code files from ivy repo and added my code in these 2 files
https://github.com/Nouran6Gamal/ivy/blob/patch-1/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
and https://github.com/Nouran6Gamal/ivy/blob/patch-1/ivy/functional/frontends/numpy/mathematical_functions/trigonometric_functions.py

in test- frontend-numpy I didn't find any error related to my function but related to another functions
and lint showed me error not in my 2 edited file
these are lint errors
ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py:55:45: E12[8](https://github.com/unifyai/ivy/runs/8236938657?check_suite_focus=true#step:5:9) continuation line under-indented for visual indent
ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py:56:45: E128 continuation line under-indented for visual indent
ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py:57:45: E128 continuation line under-indented for visual indent
ivy_tests/test_ivy/test_functional/test_extensions.py:1:1: W3[9](https://github.com/unifyai/ivy/runs/8236938657?check_suite_focus=true#step:5:10)1 blank line at end of file

any thing I should edit in both files ?

**Comment by Nouran6Gamal** [comment]
@sherry30 , someone added a function in both files & caused a confilct in the branch , should I add his function  ?

**Comment by Nouran6Gamal** [comment]
@sherry30 I fixed matters in #4170, is there anything that I can edit?

**Review by sherry30 — APPROVED** [review]
Looks good 👍 
Thanks for the contribution

**Pull request merged**
