### PR TITLE
EHN : Adding searchsorted n jax devicearray.py

### LINKED ISSUE #18979: searchsorted

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
Closed  #18979

### CODE REVIEW

**Comment by danielmunioz** [comment]
Hey @MuhammadNizamani! Thanks for contributing!

The tests seem to be passing locally, however could you please update the name of the test function so that it references jax like the others? this for consistency's sake, also there has been some updates to the file paths recently, could you please fix the merge conflicts?

Other than that the PR looks healthy!

Thanks! :)

**Comment by MuhammadNizamani** [comment]
@danielmunioz  on it

**Comment by MuhammadNizamani** [comment]
@danielmunioz  please review this

**Comment by danielmunioz** [comment]
Hey @MuhammadNizamani! Yeah, as stated previously the tests seem to be passing locally, but could you please fix the merge errors and add "_array_" to the to the test name like the others? 

Other than that it looks good to me! :)

**Comment by MuhammadNizamani** [comment]
@danielmunioz on it

**Comment by MuhammadNizamani** [comment]
@danielmunioz  I am done with the changes that you asked for please review my PR.

**Comment by danielmunioz** [comment]
Hey @MuhammadNizamani! All tests seem to be passing locally!

LGTM, Merging now!

Thanks! :)

**Pull request merged**
