### PR TITLE
paddle.tensor.creation.arange

### LINKED ISSUE #15634: arange

### PR DESCRIPTION
**Pull request by manavshah-boop**
close #15634

### CODE REVIEW

**Comment by manavshah-boop** [comment]
Close #15634

**Comment by soma2000-lang** [comment]
Hi @manavshah-boop Can you please look into the failing test?

**Comment by manavshah-boop** [comment]
Hi @soma2000-lang, I looked into the failing tests and it seems like it might be unrelated to this PR. I tried to run other functions (that have already been approved) from the same file and they all give the same error: 

FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_full_like[cpu-ivy.functional.backends.numpy-False-False] - AttributeError: 'NoneType' object has no attribute 'backend'
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_full_like[cpu-ivy.functional.backends.torch-False-False] - AttributeError: 'NoneType' object has no attribute 'backend'

Can you explain to me whether this error is being caused by my PR or from somewhere else?

**Comment by manavshah-boop** [comment]
Hi @soma2000-lang When testing locally, I get the error:

FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_arange[cpu-ivy.functional.backends.numpy-False-False] - AttributeError: 'NoneType' object has no attribute 'valid_int_dtypes'
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_arange[cpu-ivy.functional.backends.torch-False-False] - AttributeError: 'NoneType' object has no attribute 'valid_int_dtypes'

I can't figure out how to resolve this error. Do you have any suggestions on how to go about resolving this error?

**Comment by manavshah-boop** [comment]
Hi @soma2000-lang The tests are now passing locally, however intelligent-tests-pr- / run_tests (1) is failing on the pr. Do you know why it is failing?

**Comment by soma2000-lang** [comment]
Hi @manavshah-boop  let me find out and get me back to you

**Comment by manavshah-boop** [comment]
@soma2000-lang I talked to someone in the discord about the error and they said "The error was not related to your piece of code but with the ivy itself. The ivy folks updated the @unsupported_dtypes_decorator  : which I linked to you in the  earlier message; Now, if you update your branch with the latest changes from upstream then the error will elevate."
So if my test is passing locally and he said the error didn't have anything to do with my code, is my code approved?

**Comment by soma2000-lang** [comment]
@manavshah-boop Please resolve the conflicts.

**Comment by manavshah-boop** [comment]
@soma2000-lang i'm a little confused on what the conflicts are. can you please guide me towards fixing these conflicts?

**Comment by soma2000-lang** [comment]
Update your branch with the master

**Pull request closed without merging**
