### PR TITLE
Updated TIle Function

### PR DESCRIPTION
**Pull request by faseehahmed26**
https://github.com/unifyai/ivy/issues/5335

### CODE REVIEW

**Comment by faseehahmed26** [comment]
Hi @simonetgordon  while writing my unit test function I am getting a weird error of  
**ValueError: operands could not be broadcast together with shapes (2,1) (0,1)** could you please help me with it as I think it's not concerned with the function I am implementing

**Comment by faseehahmed26** [comment]
Hi @simonetgordon  I don't understand why the test functions which  I haven't edited are failing, unit test for the tile() function ran successfully on my computer for all backends  would you please help me understand  whether I have made and mistake or not

**Comment by faseehahmed26** [comment]
https://github.com/unifyai/ivy/issues/5335

**Review by simonetgordon — CHANGES_REQUESTED** [review]
Hi there, thanks for the contribution :) 

Can you pull the latest updates from master? The PR diff looks odd, as though you've deleted and added a bunch of functions.

**Comment by simonetgordon** [comment]
Additionally, `test_tile` seems to be passing the frontend torch tests. You need not worry about other frontend test failures, they are currently failing on master also.

**Comment by simonetgordon** [comment]
Hi there, yes, as I said, you should pull from the master branch of Ivy to merge the latest changes into this PR. Then we will see if that fixes the odd PR diff.

**Comment by faseehahmed26** [comment]
Done

**Comment by faseehahmed26** [comment]
@simonetgordon  I think the test ran but it is still facing issues from remaining unit tests

**Comment by faseehahmed26** [comment]
@simonetgordon Do you have any next steps that you want me to work on to merge my pull request

**Comment by faseehahmed26** [comment]
Hi @simonetgordon is my PR ready to get merged or do you want me to make further changes

**Comment by faseehahmed26** [comment]
Do you want me to update my forked master branch by removing the file and adding them again

**Comment by faseehahmed26** [comment]
Is this okay

**Comment by simonetgordon** [comment]
Hi, sorry it's still not working. You will know it has worked when only your additions are highlighted in the 'Files Changed', not the entire files. Try the copy+pasting the content of the files on the unify-ai master branch, but do not delete the files. The idea is to have them exactly the same as the master with only your additions on the 'Files Changed' diff.

**Comment by faseehahmed26** [comment]
Hi I think now it will work

**Comment by simonetgordon** [comment]
Hi there, it hasn't worked - are you able to see the 'Files Changed' option at the top of this PR? You can check each time you push a commit whether or not it has made a difference. 

If nothing seems to be working, I recommend closing this PR and opening a new one from a different branch on your fork. Th new branch should just be pulled from master and not contain any of these edits. Then you can copy and paste the tile and test_tile function in the correct files and make a new PR. You can then request a review from me, even if i haven't been assigned to the PR.

**Comment by faseehahmed26** [comment]
Could you confirm once again or do you suggest I close this pull request and open a new one from another branch from my master branch

**Pull request closed without merging**
