### PR TITLE
add reduce_mean to tensorflow frontend

### PR DESCRIPTION
**Pull request by Selozhd**
Related issue: [reduce_mean]( https://github.com/unifyai/ivy/issues/2678)

### CODE REVIEW

**Comment by modanesh** [comment]
Thanks for your contribution. Before merging into the master, it requires a few changes:

1- Please check the output of lint checks. There are some indentation that need to be updated.
2- Also please check the output of "test-frontend-tensorflow / run-nightly-tests". From the test logs, it throws this error: `E       hypothesis.errors.InvalidArgument: test_tensorflow_reduce_mean() got an unexpected keyword argument 'x_n_input_dtypes_n_unique_idx_n_bool', from x_n_input_dtypes_n_unique_idx_n_bool=_array_idx_n_dtype_n_bool() in @given` . You should be able to get some ideas on how to resolve it by looking at similar functions in the `test_tf_functions.py`.

**Comment by Selozhd** [comment]
- @modanesh Thanks for the feedback. I couldn't find the time to look into it during the week.
I opened a new PR. Here is the [link](https://github.com/unifyai/ivy/pull/2922)

**Comment by Selozhd** [comment]
Finally managed to get back to this! @modanesh I am reopening this PR instead of opening a new one.

**Comment by modanesh** [comment]
Thanks. Looking into the lint tests you can find error messages on why it's failing. For example, from the test logs, `scalar_mul` and `log_sigmoid` already exist in the `math.py` file, so you don't need to add them.

**Comment by Selozhd** [comment]
@modanesh I removed all the duplicate code and rerun all the test, it should be all good now!

**Comment by modanesh** [comment]
Looks good to me. Thanks for your contribution :)

**Pull request merged**
