### PR TITLE
Implementation of mean_squared_error metric for tensorflow frontend

### PR DESCRIPTION
**Pull request by ztsv-av**
Fully tested. All 4 tests are passed.

#2978

### CODE REVIEW

**Comment by ztsv-av** [comment]
Commenting so that this PR does not close.

**Comment by ztsv-av** [comment]
@chie2727 @djl11 kindly raising attention to avoid the bot closing the PR due to inactivity.

**Comment by Aarsh2001** [comment]
Hi @ztsv-av, apologies for the late reply. The test directory has been refactored a bit, can you please pull the latest changes and put the test function inside `test_frontends/test_tensorflow/test_metrics.py`. Thanks🙂

**Review by Aarsh2001 — COMMENTED** [review]
Put test in the right file

**Comment by ztsv-av** [comment]
Rebased the PR and recommitted again as per your comment. I tested individually for each backend. All 4 tests passed. Please have a look.

**Review by Aarsh2001 — COMMENTED** [review]
lgtm! Can you please fix the merge conflicts, and then we can have this PR merged into master. Thanks

**Comment by ztsv-av** [comment]
resolved conflicts -- a PR was merged before this one with poisson functionality.

**Pull request merged**
