### PR TITLE
feat: added lcm method to paddle tensor class

### LINKED ISSUE #26272: lcm

### PR DESCRIPTION
**Pull request by arshPratap**
# PR Description
Added lcm method to paddle tensor class

## Related Issue

Close #26272

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by arshPratap** [comment]
Have resolved the merge conflicts
@bipinKrishnan  could you take a look ?
Thanks

**Comment by arshPratap** [comment]
Hi @bipinKrishnan .. could you take a look ?

**Comment by bipinKrishnan** [comment]
LGTM! Let's wait for the tests to complete.

**Comment by arshPratap** [comment]
@bipinKrishnan no failing tests !

**Comment by arshPratap** [comment]
@bipinKrishnan no failing tests !

**Comment by arshPratap** [comment]
Hi @bipinKrishnan could you take a look ! Thanks

**Comment by bipinKrishnan** [comment]
Looks like the CI didn't pickup the tests, can you please rebase on top of the main branch?

**Comment by arshPratap** [comment]
> Looks like the CI didn't pickup the tests, can you please rebase on top of the main branch?

Hey @bipinKrishnan .. have rebased the code..but the CI is not picking up the test

**Comment by Ishticode** [comment]
i've resolved conflicts. lets wait on ci.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
