### PR TITLE
feat(frontends): Creates a `__version__` variable when setting a frontend

### PR DESCRIPTION
**Pull request by AnnaTz**

### CODE REVIEW

**Comment by umairjavaid** [comment]
looks good!

**Review by umairjavaid — APPROVED** [review]
looks good!

**Comment by umairjavaid** [comment]
Since we're returning the frontend version, we can have this in all the frontends, even for ones whose backend isn't implemented?

**Comment by AnnaTz** [comment]
> looks good!

Did you try it out in practice? I don't have any handy way to test this.

**Comment by AnnaTz** [comment]
> Since we're returning the frontend version, we can have this in all the frontends, even for ones whose backend isn't implemented?

Yes, but I'm not sure we have multi-version support for those new frontends yet.

**Pull request merged**
