### PR TITLE
Removing MXNet from backend options

### PR DESCRIPTION
**Pull request by rohini-ranjanR**
Adding 'MXNet' in code line 80 of README.rst if IVY supports this framework.
                                                                           OR
Removing the MXNet option from the backend option (https://github.com/rohini-ranjanR/ivy/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) as this framework is not mentioned in README.rst (https://github.com/rohini-ranjanR/ivy/blob/master/README.rst) means the IVY ML framework doesn't support the MXNet framework.

### CODE REVIEW

**Comment by rohini-ranjanR** [comment]
If IVY supports MXNet can I add it to README.rst? I commit for both.

**Comment by YushaArif99** [comment]
Hey @rohini-ranjanR
Ivy currently does not support MXNet. But this is a deliberate decision on our part so that we can first focus on getting a stable version of Ivy out as soon as possible.  Expect breaking changes and sharp edges until we release version 1.2.0 in the next few weeks! Until then, I think it's better to leave the documentation as it is since some refactoring will be required later anyways. Thanks! 😊

**Comment by rohini-ranjanR** [comment]
I try to make a change in README.rst in my copied repository by including the 'MXNet' framework as it was missing for this I got an answer that Ivy doesn't support MXNet for now. I again found https://github.com/unifyai/ivy/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml have an 'MXNet' option can I remove it from there? I created 2 PR for these 2 issues.

**Comment by YushaArif99** [comment]
> Author

I think it's okay to remove the MXNET option from the `bug_report.yaml` file but its better to leave the README.rst file unmodified for the abovementioned reason.

**Comment by rohini-ranjanR** [comment]
Should I remove MXNet from the YAML file and create a new pull request?

**Review by YushaArif99 — APPROVED** [review]
Hi @rohini-ranjanR 
The change seems good to me. I will now merge this PR. Thanks a lot for flagging the issue!

**Comment by rohini-ranjanR** [comment]
Thanks

**Pull request merged**
