### PR TITLE
jax.numpy.fft.fft2 implementation

### PR DESCRIPTION
**Pull request by airpods69**
#6699

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by airpods69** [comment]
I will start working on this again today or by tomorrow morning

**Comment by airpods69** [comment]
Trying to work on it but I am getting a module does not exist error whenever I run the tests in docker
Which is very weird because I believe it should work

**Comment by ogbanugot** [comment]
Hmm, can you share the exact error here with the traceback?

**Comment by airpods69** [comment]
```
Command ran -> ./run_tests_CLI/test_jax_frontend.sh jax test_jax_numpy_fft2

Use Database in ReadOnly Mode with local caching !
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /ivy
plugins: typeguard-2.13.3, json-report-1.5.0, hypothesis-6.55.0, metadata-2.0.4
collected 1 item

ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft2.py F      [100%]

=================================== FAILURES ===================================
_____ test_jax_numpy_fft2[cpu-ivy.functional.backends.jax-False-False-jax] _____
ivy_tests/test_ivy/helpers/testing_helpers.py:184: in new_fn
    @settings(max_examples=1)
ivy_tests/test_ivy/helpers/testing_helpers.py:226: in new_fn
    return test_fn(*args, **kwargs)
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft2.py:8: in test_jax_numpy_fft2
    @given(
ivy_tests/test_ivy/helpers/testing_helpers.py:112: in num_positional_args
    for param in inspect.signature(fn).parameters.values():
/usr/lib/python3.8/inspect.py:3105: in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
/usr/lib/python3.8/inspect.py:2854: in from_callable
    return _signature_from_callable(obj, sigcls=cls,
/usr/lib/python3.8/inspect.py:2228: in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
E   TypeError: <module 'ivy.functional.frontends.jax.numpy.fft2' from '/ivy/ivy/functional/frontends/jax/numpy/fft2.py'> is not a callable object
E
E   You can reproduce this example by temporarily adding @reproduce_failure('6.55.0', b'AAcAAAA=') as a decorator on your test case
E   Falsifying example: new_fn(
E       data=data(...),
E       get_command_line_flags={'as_variable': None,
E        'native_array': None,
E        'with_out': None,
E        'container': None,
E        'instance_method': None,
E        'test_gradients': None},
E       device='cpu',
E       f=<module 'ivy.functional.backends.jax' from '/ivy/ivy/functional/backends/jax/__init__.py'>,
E       fw='jax',
E       fixt_frontend_str='jax',
E   )
E   Draw 1: False
E   Draw 2: False
E
E   You can reproduce this example by temporarily adding @reproduce_failure('6.55.0', b'AAAA') as a decorator on your test case
=============================== warnings summary ===============================
../usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19
  /usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft2.py::test_jax_numpy_fft2[cpu-ivy.functional.backends.jax-False-False-jax]
======================== 1 failed, 1 warning in 10.00s =========================
```

**Comment by ogbanugot** [comment]
Hey @airpods69 so, I'm not sure why it's not working but I asked a colleague and she says you should try changing  `fn_name="ivy.functional.frontends.jax.numpy.fft2"` to `fn_name="ivy.functional.frontends.jax.numpy.fft.fft2"` in the test function's num_positional_args. Let me know if that works.

**Comment by airpods69** [comment]
Seems like I wrote the test case wrong
Can you tell me about the dtype would be? 

```
Use Database in ReadOnly Mode with local caching !
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /ivy
plugins: typeguard-2.13.3, json-report-1.5.0, hypothesis-6.55.0, metadata-2.0.4
collected 1 item

ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft2.py F      [100%]

=================================== FAILURES ===================================
_____ test_jax_numpy_fft2[cpu-ivy.functional.backends.jax-False-False-jax] _____
ivy_tests/test_ivy/helpers/testing_helpers.py:184: in new_fn
    @settings(max_examples=1)
ivy_tests/test_ivy/helpers/testing_helpers.py:226: in new_fn
    return test_fn(*args, **kwargs)
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft2.py:8: in test_jax_numpy_fft2
    @given(
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft2.py:24: in test_jax_numpy_fft2
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:739: in test_frontend_function
    _test_frontend_function(test_unsupported, args, kwargs, args_ivy, kwargs_ivy)
ivy_tests/test_ivy/helpers/function_testing.py:585: in _test_frontend_function
    ret = frontend_fn.__wrapped__(*args, **kwargs)
ivy/functional/frontends/jax/func_wrapper.py:57: in new_fn
    return fn(*new_args, **new_kwargs)
ivy/functional/frontends/jax/numpy/fft.py:7: in fft2
    return ivy.fft2(a, s, axes, norm)
E   AttributeError: module 'ivy.functional.backends.jax' has no attribute 'fft2'
E   Falsifying example: test_jax_numpy_fft2(
E       dtype_and_x=(['float16', 'float16', 'float16', 'float16'],
E        [array(-1., dtype=float16),
E         array(-1., dtype=float16),
E         array(-1., dtype=float16),
E         array(-1., dtype=float16)]),
E       num_positional_args=0,
E       as_variable=[False],
E       native_array=[False],
E   )
E
E   You can reproduce this example by temporarily adding @reproduce_failure('6.55.0', b'AXicY2AAAkYGCGAkjg0AAPwACQ==') as a decorator on your test case
E   Falsifying example: new_fn(
E       data=data(...),
E       get_command_line_flags={'as_variable': None,
E        'native_array': None,
E        'with_out': None,
E        'container': None,
E        'instance_method': None,
E        'test_gradients': None},
E       device='cpu',
E       f=<module 'ivy.functional.backends.jax' from '/ivy/ivy/functional/backends/jax/__init__.py'>,
E       fw='jax',
E       fixt_frontend_str='jax',
E   )
E   Draw 1: False
E   Draw 2: False
E
E   You can reproduce this example by temporarily adding @reproduce_failure('6.55.0', b'AAAA') as a decorator on your test case
=============================== warnings summary ===============================
../usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19
  /usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft2.py::test_jax_numpy_fft2[cpu-ivy.functional.backends.jax-False-False-jax]
======================== 1 failed, 1 warning in 18.80s =========================
```

**Comment by airpods69** [comment]
@ogbanugot do you have any idea why the code is not working? I cannot figure out how the attribute error is coming

**Comment by ogbanugot** [comment]
Hey @airpods69, can you try to use the updated helper function for frontend tests, see an example here https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_linalg.py#L18. Then set `fn_tree="ivy.functional.frontends.jax.numpy.fft.fft2"`.

**Comment by airpods69** [comment]
Awesome @ogbanugot I am getting a different error now, which is good i suppose? I went through the docs but I cant find how to generate different dtypes in the same `dtype_and_x`

```
Use Database in ReadOnly Mode with local caching !
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /ivy
plugins: typeguard-2.13.3, json-report-1.5.0, hypothesis-6.55.0, metadata-2.0.4
collected 1 item

ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft.py F       [100%]

=================================== FAILURES ===================================
_______ test_jax_numpy_fft2[cpu-ivy.functional.backends.jax-False-False] _______
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft.py:13: in test_jax_numpy_fft2
    fn_tree="jax.numpy.fft.fft2",
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft.py:27: in test_jax_numpy_fft2
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:661: in test_frontend_function
    ret, frontend_ret = _test_frontend_function(args, kwargs, args_ivy, kwargs_ivy)
ivy_tests/test_ivy/helpers/function_testing.py:513: in _test_frontend_function
    ret = get_frontend_ret(frontend_fn, *args_ivy, **kwargs_ivy)
ivy_tests/test_ivy/helpers/function_testing.py:1557: in get_frontend_ret
    ret = fn(*args, **kwargs)
E   TypeError: fft2() missing 3 required positional arguments: 's', 'axes', and 'norm'
E   Falsifying example: test_jax_numpy_fft2(
E       dtype_and_x=(['bfloat16'], array([[[2, 2],
E                [2, 2]]], dtype=bfloat16)),
E       num_positional_args=0,
E       as_variable=[False],
E       native_array=[False],
E       on_device='cpu',
E       fn_tree='ivy.functional.frontends.jax.numpy.fft.fft2',
E       frontend='jax',
E   )
E
E   You can reproduce this example by temporarily adding @reproduce_failure('6.55.0', b'AXicY2BgYGRABkxEMQEBFwAK') as a decorator on your test case
=============================== warnings summary ===============================
../usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19
  /usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft.py::test_jax_numpy_fft2[cpu-ivy.functional.backends.jax-False-False]
========================= 1 failed, 1 warning in 5.17s =========================

```

**Comment by airpods69** [comment]
ahh it gets interesting
I hardcoded the values just to see what happens since I couldn't figure out how the positional arguments work and now I have no clue how to handle the Jax type

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by airpods69** [comment]
will do after 15th 
sorry for the delay
I have my exams

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by airpods69** [comment]
will start working on this again

**Pull request closed without merging**
