### PR TITLE
Add the step for installing array API testing dependencies to the "Using miniconda" subsection in the "Setting Up" docs page

### PR DESCRIPTION
**Pull request by fabriziocacicia**

### CODE REVIEW

**Comment by fabriziocacicia** [comment]
@zaeemansari70 I had previously merged other changes to the Setting Up page steps, prior to your [discord message](https://discord.com/channels/799879767196958751/1043104326186455071/1126134070083067997) in which you told me to ask you for a review to test them.

Feel free to test the entire setup process if you want and let me know if any step is causing issues.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by zaeemansari70 — APPROVED** [review]
lgtm!

**Comment by zaeemansari70** [comment]
Co-authored-by: zaeemansari70 <zaeemansari70@gmail.com>

**Pull request merged**
