### PR TITLE
EHN: adding function repeat in jax devicearray

### LINKED ISSUE #19359: repeat

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
Closed #19359

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
Hi @MuhammadNizamani  Seems like there is some issue with the CI runners. @RashulChutani can you please take a look at `run_tests (1) (pull_request) `

**Comment by MuhammadNizamani** [comment]
@RickSanchezStoic I think these tests are unrelated to my PR

**Comment by RickSanchezStoic** [comment]
@MuhammadNizamani Kindly go through the logs in `intelligent-tests-pr / run_tests (1) (pull_request) ` in determine and run tests and search for `test_jax_repeat` you will find the relevant failures for this test. Try resolving it once and let me know how it goes.

**Comment by MuhammadNizamani** [comment]
@RickSanchezStoic  I have resolve the issue that cause by my PR , now other issue are `test_jax___add__`

**Comment by RickSanchezStoic** [comment]
Hey @MuhammadNizamani can you update your branch and resolve the conflicts, thanks!

**Pull request merged**
