### PR TITLE
iscomplexobj

### PR DESCRIPTION
**Pull request by shireenchand**
Added jax iscomplexobj frontend and test

### CODE REVIEW

**Comment by shireenchand** [comment]
#11222

**Comment by aditya-hari** [comment]
Hey, sorry for the delay. Can you please copy over the changes to a new PR?

**Comment by aditya-hari** [comment]
Hey! This looks good and the tests are passing. Can you just link it to the ToDo list?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
