### PR TITLE
affine_grid_Pytorch #20922

### PR DESCRIPTION
**Pull request by tbeetech**
updated affine grid and implemented the functions it depends on

### CODE REVIEW

**Review by tbeetech — COMMENTED** [review]
indentation fix

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by tbeetech — COMMENTED** [review]
added missing parentheses

**Review by tbeetech — COMMENTED** [review]
formatted ivy.zero function invocation to single line

**Review by tbeetech — COMMENTED** [review]
syntaxerror fix

**Comment by tbeetech** [comment]
i'm getting this error on failure Run exit 1
  exit 1
  shell: /usr/bin/bash -e {0}
Error: Process completed with exit code 1.
please assist

**Review by tbeetech — COMMENTED** [review]
corrected formatting for lint

**Review by tbeetech — COMMENTED** [review]
corrected formatting for lint

**Review by tbeetech — COMMENTED** [review]
correcting linting

**Review by tbeetech — COMMENTED** [review]
corrected lint

**Comment by tbeetech** [comment]
please come in @zaeemansari70

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi @tbeetech 

This is the failure I am having while testing locally:
```
E       AssertionError: The length of results from backend jax and ground truthframework torch does not match
E       
E       len(ret_np_flat) != len(ret_np_from_gt_flat):
E       
E       ret_np_flat:
E       
E       []
E       
E       ret_np_from_gt_flat:
E       
E       [array([[[[0., 0.],
E                [0., 0.]],
E       
E               [[0., 0.],
E                [0., 0.]]]])]
E       Falsifying example: test_torch_affine_grid(
E           on_device='cpu',
E           backend_fw='jax',
E           frontend='torch',
E           dtype_and_input_and_other=(['float64'], array([[[0., 0., 0.],
E                    [0., 0., 0.]]]), (1, 1, 2, 2), False),
E           fn_tree='ivy.functional.frontends.torch.nn.functional.affine_grid',
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=0,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.82.0', b'AXicY2CgKgAAAE8AAQ==') as a decorator on your test case
```
All the frameworks are failing for the same falsifying example, I've provided the minimal example to make it easy for you.

Kindly fix this and request a review from me.

Thanks! :slightly_smiling_face:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
