### PR TITLE
added tests for new zeros

### PR DESCRIPTION
**Pull request by Praneet9**

### CODE REVIEW

**Comment by Praneet9** [comment]
Close #7558

**Comment by Praneet9** [comment]
@nathzi1505 The tests fail due to Hypothesis not being found which doesn't look like it is related to my changes. How do I proceed with this?

**Comment by nathzi1505** [comment]
@CatB1t would you like to look at this?

**Comment by Praneet9** [comment]
@nathzi1505 @CatB1t This was merged with the other PR #7795 I had. This can be closed now. Please confirm and close this.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
