### PR TITLE
Argsort Add Array Instance methods for Numpy Frontend

### PR DESCRIPTION
**Pull request by Taciturny**

### CODE REVIEW

**Comment by Aarsh2001** [comment]
Hi @Taciturny, can you please link the issue you're working on?

**Comment by Taciturny** [comment]
Please how can I do that? I thought I did. Thanks

**Comment by Aarsh2001** [comment]
Please refer to this [guide](https://lets-unify.ai/ivy/contributing/open_tasks.html#open-tasks), assign yourself an issue from the issue tasks, and link to the PR

**Comment by Taciturny** [comment]
Thanks. I have already assigned an issue ----argsort #6790. But I'm yet to
create a PR until I'm done. Or should I create a PR now?

**Comment by Aarsh2001** [comment]
Please make all the changes in one PR. I'll close this for now, thanks🙂

**Pull request closed without merging**
