### PR TITLE
Numpy Frontend Random Binomial Implementation

### PR DESCRIPTION
**Pull request by RavinderPal408**
Kindly Review my changes

### CODE REVIEW

**Review by RavinderPal408 — COMMENTED** [review]
kindly review my changes

**Review by RavinderPal408 — COMMENTED** [review]
Kindly review

**Comment by RavinderPal408** [comment]
@danielmunioz kindly review . I only implements binomial function

**Comment by RavinderPal408** [comment]
@ivy-seed @danielmunioz  Kindly review ,If any change required please let me know

**Comment by RavinderPal408** [comment]
Dear Assignee @danielmunioz  From my end test is passed . Is there any change which is required

**Comment by RavinderPal408** [comment]
binomial #13793

**Comment by danielmunioz** [comment]
Hi @RavinderPal408, sorry for running late to your review, I've been feeling a bit sick for the past few days, hence the delay, but anyways, I left a couple of comments around the code, could you please fix those and get the tests running again?

Also it looks like you missed the steps to engage with a ToDo list, hence why it took a bit to get someone assigned to your PR, as described in the [contributing guide](https://lets-unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues), you need to comment your issue in the ToDo list with this format `- [ ] #Issue_number`, as well as commenting your PR in the issue like this: `Close #Issue_number`, this is necessary so that the PRs get linked to their respective issues and get closed once the job is done!, I linked them manually for this PR but for other tasks/issues that you may planning on working on please check out the steps outlined in the contributing guide!

If you have any questions please feel free to reach out! :)

**Comment by RavinderPal408** [comment]
Thanks @danielmunioz for your constructive reply. As you mention about Comments ,From where I have to find those comments
Because I try to find it but not found yet

**Comment by danielmunioz** [comment]
Hey @RavinderPal408! You can find the comments just scrolling a little bit up in the conversation, you can also find them by clicking on the `Files Changed` tab that's in the same section as `conversation`

**Comment by danielmunioz** [comment]
Hey! I just checked and the binomial function still has one of the issues unresolved, could you please fix that?, Also it looks like you deleted the `chisquare` function and test? could you add them back again please? Your PR should only modify code related to your issue!
Thanks! :)

**Comment by RavinderPal408** [comment]
Hi @danielmunioz . I used min_value and max_value because they are probabilities values . Its value is between 0 and 1 . Yes They are for mathematical reason

**Comment by danielmunioz** [comment]
Line 102 of `ivy/functional/frontends/numpy/random/functions.py`, you can check the comment I left there by going to the `Files changed` tab of the PR :), 
About the min and max, would it work if we just use 0 and 1?, as far as I understand you are allowed to do that in [Numpy](https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html#:~:text=pfloat%20or,0%20and%20%3C%3D1.), so theoretically we should we able to use those values here as well

Also I noticed that `p` seems to be generated just a single number, when it can also be an array, we should test for that as well

**Comment by RavinderPal408** [comment]
@danielmunioz 0 and 1 values are okay . test is passed

**Comment by RavinderPal408** [comment]
@danielmunioz  WHY checks are failed for chisquare function . I not implement this function

**Comment by danielmunioz** [comment]
Hey! @RavinderPal408, the CI runs tests all over the repo, not just this one function, that's why you are seeing errors regarding the chi-square function even though you didn't implement implement it, but don't worry!, any failure that is not related to the function you are working on does not affect the review of your PR!

**Comment by RavinderPal408** [comment]
@danielmunioz Thanks for this information. Can you please help me in finding out which issues are unresolved ?

**Comment by danielmunioz** [comment]
Line 103 of `ivy/functional/frontends/numpy/random/functions.py` size default value should be None, the frontend implementation should resemble the [original function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html) as much as possible

**Comment by RavinderPal408** [comment]
Hey! @danielmunioz Default value of size is changed to None .Please check

**Comment by RavinderPal408** [comment]
Hi @danielmunioz Kindly give some feedback

**Comment by danielmunioz** [comment]
Hey @RavinderPal408! Yeah the tests seem to be passing now, However it seems that this example is failing
```
import ivy.functional.frontends.numpy as front_np

sum(front_np.random.binomial(9, 0.1, 20000) == 0)/20000.
```
Could you please take a look at it?
The function should be able to accept n as ints or int array, p as float or float array and size as int or int tuple, as per the [numpy function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html), the frontend implementation should be able to resemble the original function as much as possible, also the tests need to probably be updated to check for this behavior as well

**Comment by RavinderPal408** [comment]
@danielmunioz  Can you please check and highlight errors ?

**Comment by danielmunioz** [comment]
Hey @RavinderPal408! Yeah, it seems that the errors shown are not related to your PR and the test cases seem to be working locally! :)
I'll merge your PR now! Thanks for the contribution!! 🚀

**Comment by danielmunioz** [comment]
ivy-gardener

**Pull request merged**
