### PR TITLE
 Added torch.deg2rad() function on pointwise_ops.py

### PR DESCRIPTION
**Pull request by sirajissalekeen16**
Added torch.deg2rad() function

### CODE REVIEW

**Comment by sirajissalekeen16** [comment]
Close #6077

**Comment by sherry30** [comment]
Hi,
PR looks good, Can you resolve the lint errors,
I'll merge it as soon as you fix these.

Thanks

**Comment by sirajissalekeen16** [comment]
I have tried to fix the lint errors, but I can't understand **Indentation is not a multiple of four (E111)** and  **Missing whitespace after keyword(E275)**, Can you please fix these errors on my behalf and tell me what's causing these errors?

**Comment by zaeemansari70** [comment]
Your changes looks good to be merged!
I hope you enjoyed contributing to Ivy, looking forward to your contributions for Ivy in the future too 🙂
Thanks!

**Pull request merged**
