### PR TITLE
Add bilinear to torch frontend

### LINKED ISSUE #4286: bilinear

### PR DESCRIPTION
**Pull request by Nielsencu**
Close #4286

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
No need for type hints in the frontend functions. Also, can you take a look at the lint in CI, you have caused a few failures here.

**Comment by Nielsencu** [comment]
Changed as per requested. However, now I am facing failed tests for my frontend function. May I know how can I see the debug output for the failed test?

**Review by mattbarrett98 — COMMENTED** [review]
You can click on `details` and then `Run frontend tests`. Then search in the logs for `bilinear` and you should be able to skip to the failures of your test

**Comment by Nielsencu** [comment]
Followed Pytorch's legacy Bilinear implementation :
https://github.com/pytorch/pytorch/blob/79f5bf84e54d57a4c81912aeedb0b8a27f97c27e/torch/legacy/nn/Bilinear.py

Is there an array creation API that allows creation of zeroes-filled ivy array by just supplying the shape? I had to use ivy.zeros_like function and pass in a standard python array with the correct shape. 

Also I tried finding function similar to Pytorch.narrow or aten::narrow, but I decided to just use a standard for loop. Is there a current implementation of ivy.narrow()?

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
`ivy.zeros` is what you're looking for. Unfortunately `narrow` isn't in our API yet. There is no need for all the shape checking/error raising in the frontend function you have written. Instead the test you write you should only generate inputs which are valid 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
