### PR TITLE
feat: adding instance method for Bitwise or

### PR DESCRIPTION
**Pull request by nishantb06**

### CODE REVIEW

**Comment by nishantb06** [comment]
Close #7182

**Comment by nishantb06** [comment]
Hi @atakanoc 
Can you help me figure out why the tests are failing? (There's no problem on my local system) . A couple of other recent PR's also have the same test failing so I think this is not an issue in my PR

**Comment by atakanoc** [comment]
Hi, @nishantb06! Sorry for not updating you sooner.

It appears that the `handle_frontend_method` decorator is going through a change at the moment and therefore unable to assist with the testing of your method. Once it is fixed, I'll take another look! ☺️

**Comment by nishantb06** [comment]
hey @atakanoc any updates on this? how can I run the tests for this PR again to see if the checks are passing or not?

**Comment by atakanoc** [comment]
Hi @nishantb06! It looks like the decorator has now been updated. To continue with your contribution, you can: 
1. Pull the master branch to your fork's branch by running `./merge_with_upstream.sh <YOUR_BRANCH>`. You have to open a terminal in the root of your repository to run the command as described.
2. Update your test implementation based on the changes made to the decorator.
3. Push to GitHub.

Here is a summary of the changes made to the decorator [in this commit](https://github.com/unifyai/ivy/commit/11b328b20c07b6ace50a9c3c6244b012a5269085):
- Added class_tree 
- Updated init_name to init_tree
- Updated method_tree to method_name
- Some of the parameters that are passed to test_frontend_function are now passed in an object to make things cleaner.
- test_frontend_function is more efficient now as it doesn't search/parse or import the module at each run.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
