### PR TITLE
tanh #1643

### PR DESCRIPTION
**Pull request by soran-ghaderi**
Update

tanh #1643 - Added to the PyTorch frontend - pointwise_ops.py --reopening (https://github.com/unifyai/ivy/pull/1667)!

### CODE REVIEW

**Comment by soran-ghaderi** [comment]
Hi, @RitujaPawas 

could you please review this pull request?
It has been created for **more than a month** (I have mentioned the original one which was closed since frontend tasks were not open).

**Comment by MarShaikh** [comment]
> Hi, @RitujaPawas
> 
> could you please review this pull request? It has been created for **more than a month** (I have mentioned the original one which was closed since frontend tasks were not open).

Hi, I haven't your PR in detail, but just to save you time, the frontend task also require you to write the test for the said backend. You can find more information here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis. Thanks!

**Comment by soran-ghaderi** [comment]
> > Hi, @RitujaPawas
> > could you please review this pull request? It has been created for **more than a month** (I have mentioned the original one which was closed since frontend tasks were not open).
> 
> Hi, I haven't seen your PR in detail, but just to save you time, the frontend task also require you to write the test for the said backend. You can find more information here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis. Thanks!

Hi @MarShaikh , I have added the test as well. It is ready to be reviewed. Thanks.

**Review by RitujaPawas — APPROVED** [review]
Hey @soran-ghaderi the changes look good. Thank you for your contribution!.

**Pull request merged**
