### PR TITLE
feat: experimental layer_norm functions

### LINKED ISSUE #26362: layer_norm

### PR DESCRIPTION
**Pull request by uuzall**
# PR Description
This PR adds the experimental layer_norm functions. The layer_norm functions have been added to the ivy experimental, and the torch experimental files. The tests have also been added.

## Related Issue
Close #26362

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by uuzall** [comment]
@MahmoudAshraf97 Hello, could you please review this PR.

**Comment by MahmoudAshraf97** [comment]
Hello and thanks for your contribution, since `layer_norm` already exists in our functional API I'll have to close this PR unfortunately

**Comment by uuzall** [comment]
Hello @MahmoudAshraf97, this PR is for the **experimental** functional API as listed in Issue #3856. I double-checked, and the experimental API does not have `layer_norm` added yet.

**Comment by MahmoudAshraf97** [comment]
It exists in the stable API, not the experimental

**Pull request closed without merging**
