### PR TITLE
rint

### LINKED ISSUE #9985: rint

### PR DESCRIPTION
**Pull request by norman135**
close #9985

### CODE REVIEW

**Comment by Nightcrab** [comment]
``casting`` default should be ``same_kind``.
``order`` default should be ``K`` not ``k``.

Logic here
```
ret = ivy.where(where, ret, ivy.default(out, ivy.zeros_like(ret)), out=out)
```
is incorrect, as the 3 argument of ``where`` should be ``x``, not a zeroes array. (according to https://numpy.org/doc/stable/reference/generated/numpy.rint.html)

**Comment by norman135** [comment]
Thanks for the clarification🙏

**Comment by norman135** [comment]
All requested changes applied

**Comment by Nightcrab** [comment]
Looks good. Merging.

**Pull request merged**
