### PR TITLE
feat: implemented tensorflow backend for lstm on cpu and gpu, and updated torch frontend lstm to use ivy.lstm_update

### PR DESCRIPTION
**Pull request by mattbarrett98**
Hey @vedpatwardhan, not so fluent in the ivy testing, could you verify whether my changes have broken either the torch frontend lstm or the backend `ivy.lstm_update`.

### CODE REVIEW

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
Hey @mattbarrett98, thanks for creating the PR. Seems like both the [frontend](https://github.com/unifyai/ivy/actions/runs/7224816809/job/19688202681?pr=27762#step:4:3162) and [backend](https://github.com/unifyai/ivy/actions/runs/7224816809/job/19688202681?pr=27762#step:4:26) ones are failing 😅
Ofc except for [`test_lstm_update,paddle`](https://github.com/unifyai/ivy/actions/runs/7224816809/job/19688202681?pr=27762#step:6:26) all the others are failing on `main` as well, but would be great to get the existing tests to pass before merging 😄

**Comment by mattbarrett98** [comment]
> Hey @mattbarrett98, thanks for creating the PR. Seems like both the [frontend](https://github.com/unifyai/ivy/actions/runs/7224816809/job/19688202681?pr=27762#step:4:3162) and [backend](https://github.com/unifyai/ivy/actions/runs/7224816809/job/19688202681?pr=27762#step:4:26) ones are failing 😅
> Ofc except for [`test_lstm_update,paddle`](https://github.com/unifyai/ivy/actions/runs/7224816809/job/19688202681?pr=27762#step:6:26) all the others are failing on `main` as well, but would be great to get the existing tests to pass before merging 😄

Given the urgency of the lstm demo, I don't know that it makes sense for me to also be fixing tests that were already failing, and potentially waste time on fixing a wrongly written test or something

**Comment by vedpatwardhan** [comment]
> Given the urgency of the lstm demo, I don't know that it makes sense for me to also be fixing tests that were already failing, and potentially waste time on fixing a wrongly written test or something

Yeah that makes sense tbh, let's get the PR merged with a ToDo about the test failure. Thanks @mattbarrett98 😄

**Comment by mattbarrett98** [comment]
> Yeah that sounds good, let's get the PR merged with a ToDo about the test failure. Thanks @mattbarrett98 😄

Sure, do the changes look okay to you? also in the tf backend I'm converting ivy arrays to manually to native arrays, as opposed to handling it with a decorator. is there a way we handle this for mixed functions, where the compositional part requires inputs to ivy arrays, and the backend specific part requires inputs to native?

**Comment by vedpatwardhan** [comment]
> Sure, do the changes look okay to you? also in the tf backend I'm converting ivy arrays manually to native arrays, as opposed to handling it with a decorator. is there a way we handle this for mixed functions, where the compositional part requires inputs to ivy arrays, and the backend specific part requires inputs to native?

Yeah the changes look good to me overall (ofc can't be fully sure on the cases we were testing with but as long as it works well in the demo). About applying different wrappers for the compositional and mixed functions, you could define the [`mixed_backend_wrappers`](https://github.com/unifyai/ivy/blob/9ba0c21147cdd7bdc2f65d714046c368b1690ecf/ivy/functional/ivy/experimental/norms.py#L516) where the `ivy` function would by default contain all the wrappers for the compositional implementation and this attribute would specify which ones of those should we skip and which new ones should we add to the list of wrappers applied to the backend implementation. Thanks @mattbarrett98 😄

**Pull request merged**
