### PR TITLE
Add igammac

### PR DESCRIPTION
**Pull request by AmeenUrRehman**
# PR Description

## Related Issue

Close [#](https://github.com/unifyai/ivy/issues/26461)

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by AmeenUrRehman** [comment]
- [ ] #26462 Solving this issue

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by AmeenUrRehman** [comment]
@nathzi1505 hey could plz review the pr

**Comment by NripeshN** [comment]
Hi @AmeenUrRehman,
Your tests are failing https://github.com/unifyai/ivy/actions/runs/6381436285/job/17319090927?pr=26462#step:4:15

**Comment by Sarvesh-Kesharwani** [comment]
Closing the PR for the time being since there has been no activity for more than 2 weeks.

**Pull request closed without merging**
