### PR TITLE
EHN: adding logical_not funct in paddle tensor.py

### LINKED ISSUE #17455: logical_not
adding  logical_not in paddle.tensor.tesnor.Tensor form this todo list  #15115

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
logical_not from issue Closed #17455

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MuhammadNizamani** [comment]
@ZoeCD  waiting for review

**Comment by ZoeCD** [comment]
Hello, sorry for the late response! There are some branch conflicts to resolve. But other than that, lgtm!

**Comment by MuhammadNizamani** [comment]
@ZoeCD this PR is ready to merge

**Comment by MuhammadNizamani** [comment]
@ZoeCD this PR is ready to merge

**Comment by MuhammadNizamani** [comment]
@ZoeCD  could please merge this PR

**Pull request merged**
