### PR TITLE
svd

### LINKED ISSUE #4425: svd

### PR DESCRIPTION
**Pull request by karalleyna**
Closes #4425

### CODE REVIEW

**Comment by abdrahmandiab** [comment]
Hi @karalleyna,

**Comment by abdrahmandiab** [comment]
Hi @karalleyna,
You can check out for Failing tests in our Github CI by first clicking on `Details` next to the "test-frontend-jax / run-nightly-tests (pull_request)" check action.

**Comment by karalleyna** [comment]
@abdrahmandiab  Ah, I see :) I appreciate your help. I was stuck in the `Check on failures` section.  I think it is now okay because no failure message is related to `svd`.

**Comment by karalleyna** [comment]
Hi @abdrahmandiab, I think it is done right now. Could you please check it out? :)

**Comment by abdrahmandiab** [comment]
> Hi @abdrahmandiab, I think it is done right now. Could you please check it out? :)

Hi @karalleyna, everything looks good to me! Will be merging soon.

Thanks for your hard work! 😊

**Pull request merged**
