### PR TITLE
added remainder numpy frontend

### PR DESCRIPTION
**Pull request by lumi232**
Hi, I am new to this repo's codebase so isn't sure of the solution. I started open sourcing due to hacktoberfest and I really love this repo and would like to make the rest of my contributions here.  Please give me the hacktoberfest point so that I can clear the event.

### CODE REVIEW

**Comment by aryans1204** [comment]
Hi, before I can merge this, since this is a Frontend task, please also write the tests for your frontend and get them passing. Thanks for contributing!

**Comment by lumi232** [comment]
done

**Comment by aryans1204** [comment]
I also find that the issue that you linked to this pull request had already been opened by someone else. In the future, please do not work on issues that are opened by someone else unless they are placed back into the open pool.

Also, could you please get the test passing as well for jax and numpy frontend? Thanks

**Comment by aryans1204** [comment]
I see that you've also made a commit for the divide function under jax/numpy. I don't see how it is related to the Remainder implementation for the NumPy frontend, so you could please rever that commit, or create a separate pull request that pertains to the Jax NumPy divide issue

**Comment by aryans1204** [comment]
Hi, since there's been no activity on this pull request for the past 9 days, I'm closing it. if you wish to continue working on this in the future, you can either reopen this PR or create a new one.

**Pull request closed without merging**
