### PR TITLE
Add numpy frontend swapaxes function

### LINKED ISSUE #4546: swapaxes

### PR DESCRIPTION
**Pull request by pdpino**
Closes #4546

### CODE REVIEW

**Comment by MrZilinXiao** [comment]
Hi @pdpino. Sorry for the late reply. I noticed there is an unknown error causing the numpy frontend test to fail. It is not your fault and I will look into it if the rerun does not work either.

**Comment by MrZilinXiao** [comment]
Hi @pdpino. I am back! It turns out that the unit test failed due to a mistake made by one of our engineers. Now the problem solves! See https://github.com/unifyai/ivy/actions/runs/3128268922/jobs/5075893952#step:6:14817 to know why your code is failing...

**Comment by pdpino** [comment]
Hi @MrZilinXiao , I fix the issue in `test_transpose_like_operations.py` :slightly_smiling_face:

**Review by MrZilinXiao — APPROVED** [review]
Congrats! Your PR is free to go!

**Pull request merged**
