### PR TITLE
Add `any()` to torch frontend

### LINKED ISSUE #9438: any
Implement the `torch.Tensor.any()` frontend function.

### PR DESCRIPTION
**Pull request by jaketae**
Close #9438

### CODE REVIEW

**Comment by jaketae** [comment]
Hello @simonetgordon, the test seems to be failing due to

* `AttributeError: module 'ivy_tests.test_ivy.helpers' has no attribute 'array_or_none'`
* `IndentationError: unexpected indent`

[Link](https://github.com/unifyai/ivy/actions/runs/3853660784/jobs/6566851736) to the CI job.

I've addressed the first error in #9442, but it's unclear to me where the second `IndentationError` is occurring. I'd appreciate any pointers!

**Comment by simonetgordon** [comment]
> Hello @simonetgordon, the test seems to be failing due to
> 
> * `AttributeError: module 'ivy_tests.test_ivy.helpers' has no attribute 'array_or_none'`
> * `IndentationError: unexpected indent`
> 
> [Link](https://github.com/unifyai/ivy/actions/runs/3853660784/jobs/6566851736) to the CI job. I'm able to locally reproduce the error, both on my branch _and master_, via
> 
> ```
> pytest ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py -k 'test_torch_instance_any'
> ```
> 
> I've addressed the first error in #9442, but it's unclear to me where the second `IndentationError` is occurring. I'd appreciate any pointers!

Thanks so much for raising an issue on the first issue. Your solution looks good but it's best that @CatB1t approves it before merging. The indentation error looks like it's in `frontends/torch/tensor.py` but upon inspecting it I'm not sure why an indentation error would be raised, it looks aligned. Perhaps it is related to other torch frontend errors.

**Comment by jaketae** [comment]
Hello @simonetgordon, thanks for the comment.

It appears that `test_torch_instance_sqrt` was the culprit. As you said, I'm not sure why the run was being affected by other tests even with the `-k` flag. In any case, I commented out that particular test and was able to run and pass the test case successfully.

```
collected 236 items / 234 deselected / 2 selected                                                                          

ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py ..                                                       [100%]

===================================================== warnings summary =====================================================
ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py: 50 warnings
  /data/lily/jt856/documents/ivy/ivy_tests/test_ivy/helpers/function_testing.py:1457: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
    ins_gt = frontend_creation_fn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================== 2 passed, 234 deselected, 50 warnings in 6.76s ======================================
```

Let me know if anything seems off. Thanks!

**Comment by simonetgordon** [comment]
lgtm!

**Pull request merged**
