### PR TITLE
Close #16023

### LINKED ISSUE #16023: corrcoef

### PR DESCRIPTION
**Pull request by jyjoshi**

### CODE REVIEW

**Comment by jyjoshi** [comment]
Hi @MahmoudAshraf97, I have been working on implementing the corrcoeff function for the paddle backend. 

I used the same logic used for implementing the function with the torch backend using similar apis for paddle. 

It seems like there are some discrepancies in the outputs and I am trying to debug the code. 


Error that occurred while running unit test on the paddle backend function ->

E           AssertionError:  the results from backend paddle and ground truth framework tensorflow do not match
E            [[nan nan nan nan nan nan]
E            [nan nan nan nan nan nan]
E            [nan nan nan nan nan nan]
E            [nan nan nan nan nan nan]
E            [nan nan nan nan nan nan]
E            [-1. -1. -1. -1. -1.  1.]]!=[[      nan       nan       nan       nan       nan       nan]
E            [      nan       nan       nan       nan       nan       nan]
E            [      nan       nan       nan       nan       nan       nan]
E            [      nan       nan       nan       nan       nan       nan]
E            [      nan       nan       nan       nan       nan       nan]
E            [      nan       nan       nan       nan       nan 1.0000001]] 
E           
E           
E           Falsifying example: test_corrcoef(
E               backend_fw=<module 'ivy.functional.backends.paddle' from '/Users/jayjoshi/ivy/ivy/functional/backends/paddle/__init__.py'>,
E               on_device='cpu',
E               dtype_and_x=(['float32', 'float32'], [array([[-1., -1., -1.],
E                        [-1., -1., -1.],
E                        [-1., -1., -1.]], dtype=float32), array([[-1., -1., -1.],
E                        [-1., -1., -1.],
E                        [-1., -1., -2.]], dtype=float32)]),
E               rowvar=False,
E               fn_name='corrcoef',
E               ground_truth_backend='tensorflow',
E               test_flags=FunctionTestFlags(
E                   num_positional_args=1,
E                   with_out=False,
E                   instance_method=False,
E                   test_gradients=False,
E                   test_compile=None,
E                   as_variable=[False],
E                   native_arrays=[False],
E                   container=[False],
E               ),
E           )
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.75.3', b'AXicY2CAAEYkeriwmRhgAAARQAAm') as a decorator on your test case



Can I get the exact inputs to the function that resulted in this error?

**Comment by jyjoshi** [comment]
Hi @MahmoudAshraf97, just an update, I figured the data_type_and_x field provides the values for the input and did a little bit of debugging. 

The problem arises due to some internal implementation of the corrcoef function in paddle. Provided the processed arrays as input to the corrcoef paddle function; it gives inaccurate outputs in some cases. 

How should I proceed ahead?

Given the native paddle implementation is inconsistent; I am going to try to implement the function without the native paddle implementation. 
Am I in the right direction?

**Comment by MahmoudAshraf97** [comment]
Check if the paddle implementation is a single kernel or compositional, also make sure that your implementation of preprocessing has the same results, maybe the problem is there

**Comment by jyjoshi** [comment]
I had checked with my preprocessing before; it was giving consistent results. I will look into the paddle implementation being single kernel or compositional. Can you guide me where I could find this info?

Also, I tried creating the function without native paddle function and in some results the margin of error is about 0.01, leading to test fails, can this be acceptable? I will look into this as well if needed. 

Thanks

**Comment by jyjoshi** [comment]
Hi @MahmoudAshraf97, just checked the paddle source code for the implementation and it seems to be compositional. It internally uses other functions like cov(), diag() and sqrt() 

`def corrcoef(x, rowvar=True, name=None):
            if len(x.shape) > 2 or len(x.shape) < 1:
                raise ValueError(
                    "Input(x) only support N-D (1<=N<=2) tensor in corrcoef, but received "
                    "length of Input(input) is %s." % len(x.shape)
                )
            check_variable_and_dtype(x, 'dtype', ['float32', 'float64'], 'corrcoef')
        
            c = cov(x, rowvar)
            if c.ndim == 0:
                # scalar covariance
                # nan if incorrect value (nan, inf, 0), 1 otherwise
                return c / c
        
            d = paddle.diag(c)
        
            if paddle.is_complex(d):
                d = d.real()
            stddev = paddle.sqrt(d)
            c /= stddev[:, None]
            c /= stddev[None, :]
        
            # Clip to [-1, 1].  This does not guarantee
            if paddle.is_complex(c):
                return paddle.complex(
                    paddle.clip(c.real(), -1, 1), paddle.clip(c.imag(), -1, 1)
                )
            else:
                c = paddle.clip(c, -1, 1)
        
            return c`

**Comment by jyjoshi** [comment]
Hi @MahmoudAshraf97, I tried testing the internal functions used by paddle in corrcoef implementation and it seems that the covariance calculated is also inconsistent with the covariance calculated by other frameworks for the failing inputs. 

```
Input Matrix [[-1.0, -1.0, -1.0], [-1.0, -1.0, -1.0], [-1.0, -1.0, -2.0]] 
 

Paddle Covariance :  Tensor(shape=[3, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [-0.00000006, -0.00000006,  0.33333325]])
Torch Covariance :  tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3333]])
Numpy Covariance :  [[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.33333333]]



Paddle CorrelationCoeff :  Tensor(shape=[3, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[nan, nan, nan],
        [nan, nan, nan],
        [-1., -1.,  1.]])
Torch CorrelationCoeff :  tensor([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, 1.]])
Numpy CorrelationCoeff :  [[nan nan nan]
 [nan nan nan]
 [nan nan  1.]]
Tensor(shape=[3, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [-0.00000006, -0.00000006,  0.33333325]])
Tensor(shape=[3, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[nan, nan, nan],
        [nan, nan, nan],
        [1. , 1. , 1. ]])
```

How can we move ahead?

**Comment by jyjoshi** [comment]
Hi @MahmoudAshraf97, I am summarising everything I have done on this PR. 

- Tried implementing the corrcoef function using the native paddle.linalg.corrcoef function which did not work. 

- Debugged the code and found that the paddle.linalg.cov() function used internally by paddle was incomplete; so fixed it. 

- Using the modified cov() function I rewrote the ivy paddle backend using paddle functions. This also resulted in some failure in precision due to difference in backend values and ground truth being greater than the tolerance level set. 

- Also tried a different way to implement the same corrcoef using other paddle functions but also arrived at the same failure due to values not being close enough. 

- The difference between values in the failed test case was about 0.01

Please let me know how we can move ahead with this.

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hi @jyjoshi , great work so far and I like your debugging and reasoning skills, since `paddle.corrcoef` is compositional, then you can either use your own compositional implementation inspired by any other backend or use the paddle implementation using the same functions but from the ivy paddle backend, it should give consistent results with other backends

**Comment by jyjoshi** [comment]
Thanks @MahmoudAshraf97, I will try to implement based on some other framework implementations, but due to the accuracy issue creeping up in the cov() function in paddle, it might be a little difficult to fix it unless we manage to implement corrcoef() without internally using cov().

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MahmoudAshraf97** [comment]
Hello, any updates?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
