### PR TITLE
fix: broken link in dashboard_automation/update_db.py

### LINKED ISSUE #27037: [Bug]: Small broken link in dashboard_automation/update_db.py
### Bug Explanation

action_url seems to be broken in [automation_tools/dashboard_automation/update_db.py](https://github.com/unifyai/ivy/blob/main/automation_tools/dashboard_automation/update_db.py). I could be mistaken, but I think a simple fix could be to replace `https://github.com/unifyai/ivy/actions/runs/` with `https://github.com/unifyai/ivy/actions/`

### Steps to Reproduce Bug

Go to the above url, copy paste the given url in action_url in anew tab, it shows a 404 error

### Environment

Chrome Version 118.0.5993.71 (Official Build) (64-bit)

### Ivy Version

0.0.3.0

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

_No response_

### PR DESCRIPTION
**Pull request by Archit-Kohli**
# PR Description
Updated the link given in update_db.py from `https://github.com/unifyai/ivy/actions/runs/` to `https://github.com/unifyai/ivy/actions/`

## Related Issue

Closes #27037 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Archit-Kohli** [comment]
Hey @hmahmood24 please merge this request if it's alright, or let me know any changes I have to make

**Comment by hmahmood24** [comment]
I will let @vedpatwardhan review the change since he's most suited for that. Thanks :)

**Comment by Archit-Kohli** [comment]
@vedpatwardhan please let me know if I have to make any more changes?

**Review by vedpatwardhan — COMMENTED** [review]
I think the current link is actually correct (for the intended purpose in the script), because it's been like that for a [year](https://github.com/unifyai/ivy/commit/226b178bbab91957e4d3cc32a66c43dc2d75fc2d) or so and the database has been updating correctly. Thanks @Archit-Kohli for making your contribution though 😄

**Pull request closed without merging**
