### PR TITLE
Added __divmod__ to Numpy Frontend API

### LINKED ISSUE #22230: __divmod__

### PR DESCRIPTION
**Pull request by mtilerisoy**
Close #22230

### CODE REVIEW

**Comment by Ookamice** [comment]
@mtilerisoy 
Thank you for your contributions, I would advise opening a separate issue and PR for adding float into the typehints of the backend functions for sqrt as it does not directly relate with the issue this PR aims to solve. (This is for the sake of clarity for future references)

Secondly, please refer to the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) regarding writing testcases for your frontend function. 😄

**Comment by mtilerisoy** [comment]
I have a separate issue and PR for sqrt (#22193), however; they seem to have appeared in this PR as well. Is this a problem?

**Comment by Ookamice** [comment]
@mtilerisoy
It would be for the best if you can revert the changes on the sqrt files for this PR as ideally each PR should tackle one issue for the sake of organisation.

**Comment by mtilerisoy** [comment]
Is it possible to simply revert the changes made on the other issue's files?

**Comment by Ookamice** [comment]
@mtilerisoy
I'm not an expert in using git but I would assume there will be a way for you to remove the committed files with changes for sqrt. This would also change your PR that tackles the sqrt issue as it appears that you have opened both PRs on the same branch in your fork.

**Comment by Sam-Armstrong** [comment]
@mtilerisoy I think the easiest way is to manually change all the elementwise.py files back to what they were before and push these changes to this PR in a new commit. Please could you also add the corresponding test for the frontend function you've added? Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
