### PR TITLE
reshape #6643

### PR DESCRIPTION
**Pull request by eswhy28**
reshape

### CODE REVIEW

**Review by eswhy28 — COMMENTED** [review]
reshape #6643

**Comment by eswhy28** [comment]
reshape is working fine on my computer i don't why its giving whitspaces errors

**Comment by eswhy28** [comment]
i dont know why my pull request is closed

**Comment by hirwa-nshuti** [comment]
Hi, it seems like you removed all the changes you had already made on the last commit try to revert the last changes you made.
Thanks:)

**Pull request closed without merging**
