### PR TITLE
diagflat

### PR DESCRIPTION
**Pull request by shireenchand**
added frontend and test for jax diagflat function

### CODE REVIEW

**Comment by shireenchand** [comment]
#14216

**Comment by zhumakhan** [comment]
Hi, thanks for you PR!
It seems tests are failing due to some backend implementation errors. Feel free to creating fixes for them. Also in testing, I would suggest *available_dtypes=helpers.get_dtypes("valid")*, and for dtypes that are not supported by backend framework using  *with_unsupported_dtypes* decorator in the backend implementation.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by zhumakhan** [comment]
> Hi, thanks for you PR! It seems tests are failing due to some backend implementation errors. Feel free to creating fixes for them as commits in this PR. Also in testing, I would suggest _available_dtypes=helpers.get_dtypes("valid")_, and for dtypes that are not supported by backend framework using _with_unsupported_dtypes_ decorator in the backend implementation.


Hi, issues mentioned above still exist, could you please make sure tests are passing on you local machine!
Thanks

**Pull request closed without merging**
