### PR TITLE
Add Discrete Fourier Transform functions to Numpy Frontend #1532

### LINKED ISSUE #14406: rfft

### PR DESCRIPTION
**Pull request by rubada**
Close #14406

### CODE REVIEW

**Comment by rubada** [comment]
Hi I would like when are you going to review my code

**Comment by rubada** [comment]
@karalleyna Hi When are you going to review my files?
Thank you

**Comment by rubada** [comment]
@karalleyna 
Hi it has been more than 2 weeks since I made my commit, please can you review my files.

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hiya 👋

Apologies for taking so long to review your PR. I don't believe `ivy.rfft` exists so the test cases for your code is failing. Please consider checking the documentation for [`ivy.dft`](https://unify.ai/docs/ivy/docs/functional/ivy/experimental/layers/ivy.functional.ivy.experimental.layers.dft.html). Also, I believe [numpy's rfft](https://numpy.org/doc/stable/reference/generated/numpy.fft.rfft.html) operates only on real-valued arrays so the tests should be modified appropriately.

Let me know if you have any more questions and thanks for contributing!

**Comment by rubada** [comment]
@Ookamice
Hi 🙂
Thank you for your review, that correct ivy.rfft doesn't exist in, ivy/functional/ivy/experimental/layers.py, in my first PR, I added the ivy.rfft in layers.py, but there was a conflict. So I removed the layer.py file from my PR. should I create an issue for ivy.rfft?

I changed the ditypes to "numeric", but the reason why I use real_and_complex, because in NumPy docs it is mentioned that "If the input a contains an imaginary part, it is silently discarded."

**Comment by Ookamice** [comment]
@rubada 
> Thank you for your review, that correct ivy.rfft doesn't exist in, ivy/functional/ivy/experimental/layers.py, in my first PR, I added the ivy.rfft in layers.py, but there was a conflict. So I removed the layer.py file from my PR. should I create an issue for ivy.rfft?

I believe it is possible to implement `rfft` as a composite function using ivy's existing [`ivy.dft`](https://unify.ai/docs/v1.1.9/ivy/docs/functional/ivy/experimental/layers/ivy.functional.ivy.experimental.layers.dft.html) (I believe the **onesided** flag will be of use) and other ivy functions. However, if this isn't the case then I would say to follow the [contributer's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) and create a new issue for missing ivy function.

> I changed the ditypes to "numeric", but the reason why I use real_and_complex, because in NumPy docs it is mentioned that "If the input a contains an imaginary part, it is silently discarded."

Good catch! 👍

**Comment by rubada** [comment]
@Ookamice
Hi 😄
Can you please check the code if it is ok
Thank you

**Review by Ookamice — CHANGES_REQUESTED** [review]
@rubada 
Hiya, thanks for the changes!
I just checked the intelligent-tests and it seems your tests are failing due to ' TypeError: dft() takes 1 positional argument but 2 positional arguments (and 5 keyword-only arguments) were given'. I think this is because of `a=x` instead of `a=x[0]` in your test helper. Also, I'd advise `n=n, axis=axis, norm=norm,` as well for a more comprehensive testing. Lastly, please update the default value of norm from `backwards` to `None` in your function declerator as specified in the jax docs.

Let me know if you have any other questions!

**Comment by rubada** [comment]
Hi, 

> @rubada Hiya, thanks for the changes! I just checked the intelligent-tests and it seems your tests are failing due to ' TypeError: dft() takes 1 positional argument but 2 positional arguments (and 5 keyword-only arguments) were given'. I think this is because of `a=x` instead of `a=x[0]` in your test helper. Also, I'd advise `n=n, axis=axis, norm=norm,` as well for a more comprehensive testing. Lastly, please update the default value of norm from `backwards` to `None` in your function declerator as specified in the jax docs.
> 
> Let me know if you have any other questions!

@Ookamice
Hi 🤔
I tried everything to remove the errors, but still I couldn't remove them, I tried many numeric values but still get the same errors.

Thank you

**Comment by Ookamice** [comment]
@rubada 
Hiya, I had a closer look and opened a github codespace to run tests on manually and didn't notice any major issues. Could you let me know what's the concern and we can fix it together?

**Comment by rubada** [comment]
@rubada
Hi, 
The intelligent-tests-pr / run_tests_39 failed is due to "tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128", I used float type but it didn't work, and then I add @integer_arrays_to_float and didn't work, where is my mistake??
The rfft function returns the dft function which is using the fft function to calculate rfft, and the fft function is already merged, so rfft should work properly, why the testing is failing?
As for the intelligent-tests-pr / run_tests_1 (pull_request), it is failed due to the "RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int16) of kernel `slice` is not registered.", I don't know why I got this error?

I don't know where is my mistake in the code I wrote?

Thanks😀

**Comment by Ookamice** [comment]
@rubada

Hiya, just made some small tweaks to your test logic to make it more robust.

Please could you add a condition to cast the results to torch's default dtype if we are using the torch backend? So far the only error is that for torch, we return a complex64 instead of a complex128. This should be a easy fix but let me know if you have any questions!

PS: You can run the tests locally or on github codespace with `python -m pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py::test_numpy_rfft --backend 'all'` which should make testing and troubleshooting easier instead of relying on the intelligent test

Looking forward to merging this! 👍

**Comment by rubada** [comment]
@Ookamice
Hi 😀,
I did the tests locally in the past, but I got a failed test due to allow_subnormal, that's why I didn't see the torch error, today I updated hypothesis to v6.75.3, then the torch failed test appear, I fixed it and the tests passed locally.

Please check my code if it is ok.

Thank you very much for your help and patience! 🙏🏻

**Comment by Ookamice** [comment]
small error with the backend implementation of tensorflow complex casting I think but your frontend implementation looks good!

Thank you for your contributions! ❤️

**Pull request merged**
