### PR TITLE
Reformatting eigh in backend linear_algebra

### PR DESCRIPTION
**Pull request by LourensT**

### CODE REVIEW

**Comment by LourensT** [comment]
Close #10780

**Comment by LourensT** [comment]
very minor reformatting changes, but necessary to progress the ToDo

**Comment by V-G-spec** [comment]
Thank you for your contribution @LourensT 😃 
Can you address the failing tests? Thanks!

**Comment by LourensT** [comment]
Hi @V-G-spec, I'm slightyl confused. Linting errors seem to not be in files I've edited, I suppose I can ignore them? Do you know where I can inspect the failure of the details of the intelligent-tests-pr?

**Pull request closed without merging**
