### PR TITLE
added nanvar to numpy frontend

### PR DESCRIPTION
**Pull request by SaifAshraf70**

### CODE REVIEW

**Comment by SaifAshraf70** [comment]
Could you tell me why my pull request was not accepted, I have passed the 4 tests on my local machine
@RashulChutani

**Comment by RashulChutani** [comment]
Hi @SaifAshraf70 I will review the PR and merge it soon if it seems to be correct. Thanks for your contribution.

**Comment by SaifAshraf70** [comment]
> Hi @SaifAshraf70 I will review the PR and merge it soon if it seems to be correct. Thanks for your contribution.

@RashulChutani

**Comment by RashulChutani** [comment]
Hi @SaifAshraf70 I will have to clone your Branch and run the tests locally. Will do that soon and merge. Thanks.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @SaifAshraf70 I see some lint tests failing for your function. Can you please resolve them? Thanks.

**Comment by SaifAshraf70** [comment]
> Hi @SaifAshraf70 I see some lint tests failing for your function. Can you please resolve them? Thanks.

I have just resolve it @RashulChutani

**Comment by SaifAshraf70** [comment]
Should I make a new PR due to what Dan made yesterday  (push --force), although my PR has no conflicts @RashulChutani ?

**Comment by RashulChutani** [comment]
Yes, Actually the Force Push is taking time to complete, and thus the repo is locked. Please wait sometime before you make a new PR.

**Comment by SaifAshraf70** [comment]
Hi, @RashulChutani could you review my code, I am waiting for you a long time ago!

**Comment by RashulChutani** [comment]
Hi @SaifAshraf70 Actually I am waiting for the force push to complete so that I can merge your PR. As soon as it's done, you can create a new PR and I will merge it ASAP.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @SaifAshraf70 Can you please remove changes from test_docstrings Module, and all other Modules that are not related to your Function? You only need to make sure that the lint tests (and the frontend tests) pass for your added Function. Thanks.

**Comment by SaifAshraf70** [comment]
Hi @RashulChutani I made a new PR and resolve lint test
this is the link of PR: https://github.com/unifyai/ivy/pull/8893

**Pull request closed without merging**
