### PR TITLE
Fix merge conflicts for Paddle Creation Clone frontend

### LINKED ISSUE #19201: clone

### PR DESCRIPTION
**Pull request by Kalachuchis**
Close #19201

### CODE REVIEW

**Comment by Kalachuchis** [comment]
```(base) root ➜ /workspaces/ivy (master) $ pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_clone

Use Database in ReadOnly Mode with local caching !
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.10.0, pytest-7.4.0, pluggy-1.2.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-3.7.1, json-report-1.5.0, hypothesis-6.80.0, metadata-3.0.0
collected 5 items                                                                                                                                                                                                  

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py .....                                                                                                                             [100%]

================================================================================================= warnings summary =================================================================================================
ivy/data_classes/container/base.py:1347
  /workspaces/ivy/ivy/data_classes/container/base.py:1347: DeprecationWarning: invalid escape sequence '\.'
    flat_keys = re.split("/|\.", key_chain)  # noqa

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py: 50 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1035: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================================================================== 5 passed, 51 warnings in 91.68s (0:01:31) =====================================================================================```

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hello! Thank you for your contribution!

Can you please resolve the error?

```
========================================================================== FAILURES ==========================================================================
___________________________________________ test_paddle_clone[cpu-ivy.functional.backends.tensorflow-False-False] ____________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.clone",
        dtype_and_x=helpers.dtype_and_values(available_dtypes=helpers.get_dtypes("valid")),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:496: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:508: in test_paddle_clone
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:805: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:111: in value_test
    assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

values = [[array(-1, dtype=bfloat16)], [array(49024, dtype=uint16)]], this_key_chain = None

    def assert_same_type_and_shape(values, this_key_chain=None):
        x_, y_ = values
        for x, y in zip(x_, y_):
            if isinstance(x, np.ndarray):
                x_d = str(x.dtype).replace("longlong", "int64")
                y_d = str(y.dtype).replace("longlong", "int64")
                assert (
                    x.shape == y.shape
                ), "returned shape = {}, ground-truth returned shape = {}".format(
                    x.shape, y.shape
                )
>               assert (
                    x_d == y_d
                ), "returned dtype = {}, ground-truth returned dtype = {}".format(x_d, y_d)
E               AssertionError: returned dtype = bfloat16, ground-truth returned dtype = uint16
E               Falsifying example: test_paddle_clone(
E                   frontend='paddle',
E                   on_device='cpu',
E                   dtype_and_x=(['bfloat16'], [array(-1, dtype=bfloat16)]),
E                   test_flags=FrontendFunctionTestFlags(
E                       num_positional_args=0,
E                       with_out=False,
E                       inplace=False,
E                       as_variable=[False],
E                       native_arrays=[False],
E                       generate_frontend_arrays=False,
E                   ),
E                   fn_tree='ivy.functional.frontends.paddle.clone',
E               )
E               
E               You can reproduce this example by temporarily adding @reproduce_failure('6.80.0', b'AXicY2UAAkYGCIDSAACOAAg=') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:76: AssertionError
______________________________________________ test_paddle_clone[cpu-ivy.functional.backends.torch-False-False] ______________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.clone",
        dtype_and_x=helpers.dtype_and_values(available_dtypes=helpers.get_dtypes("valid")),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:496: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:508: in test_paddle_clone
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:805: in test_frontend_function
    value_test(
ivy_tests/test_ivy/helpers/assertions.py:111: in value_test
    assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

values = [[array(-1, dtype=bfloat16)], [array(49024, dtype=uint16)]], this_key_chain = None

    def assert_same_type_and_shape(values, this_key_chain=None):
        x_, y_ = values
        for x, y in zip(x_, y_):
            if isinstance(x, np.ndarray):
                x_d = str(x.dtype).replace("longlong", "int64")
                y_d = str(y.dtype).replace("longlong", "int64")
                assert (
                    x.shape == y.shape
                ), "returned shape = {}, ground-truth returned shape = {}".format(
                    x.shape, y.shape
                )
>               assert (
                    x_d == y_d
                ), "returned dtype = {}, ground-truth returned dtype = {}".format(x_d, y_d)
E               AssertionError: returned dtype = bfloat16, ground-truth returned dtype = uint16
E               Falsifying example: test_paddle_clone(
E                   frontend='paddle',
E                   on_device='cpu',
E                   dtype_and_x=(['bfloat16'], [array(-1, dtype=bfloat16)]),
E                   test_flags=FrontendFunctionTestFlags(
E                       num_positional_args=0,
E                       with_out=False,
E                       inplace=False,
E                       as_variable=[False],
E                       native_arrays=[False],
E                       generate_frontend_arrays=False,
E                   ),
E                   fn_tree='ivy.functional.frontends.paddle.clone',
E               )
E               
E               You can reproduce this example by temporarily adding @reproduce_failure('6.80.0', b'AXicY2UAAkYGCIDSAACOAAg=') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:76: AssertionError
_____________________________________________ test_paddle_clone[cpu-ivy.functional.backends.paddle-False-False] ______________________________________________

args = ('uint16',), kwargs = {}

    @functools.wraps(fn)
    def _handle_exceptions(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
>           return fn(*args, **kwargs)

ivy/utils/exceptions.py:335: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dtype_in = 'uint16'

    def as_native_dtype(
        dtype_in: Union[paddle.dtype, str, bool, int, float]
    ) -> paddle.dtype:
        if dtype_in is int:
            return ivy.default_int_dtype(as_native=True)
        if dtype_in is float:
            return ivy.default_float_dtype(as_native=True)
        if dtype_in is complex:
            return ivy.default_complex_dtype(as_native=True)
        if dtype_in is bool:
            return paddle.bool
        if not isinstance(dtype_in, str):
            return dtype_in
        if dtype_in in native_dtype_dict.keys():
            return native_dtype_dict[ivy.Dtype(dtype_in)]
        else:
>           raise ivy.utils.exceptions.IvyException(
                f"Cannot convert to Paddle dtype. {dtype_in} is not supported by Paddle."
            )
E           ivy.utils.exceptions.IvyException: Cannot convert to Paddle dtype. uint16 is not supported by Paddle.

ivy/functional/backends/paddle/data_type.py:241: IvyException

During handling of the above exception, another exception occurred:

args = (array(49024, dtype=uint16), <function test_frontend_function.<locals>.<lambda> at 0x7fc48718d900>, {<class 'tuple'>: False, <class 'list'>: False, <class 'dict'>: False}, (), False, None, ...)
kwargs = {}

    @functools.wraps(fn)
    def _handle_exceptions(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
>           return fn(*args, **kwargs)

ivy/utils/exceptions.py:335: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy/functional/ivy/nest.py:1187: in nested_map
    return fn(x)
ivy_tests/test_ivy/helpers/function_testing.py:737: in <lambda>
    lambda x: ivy.native_array(x) if isinstance(x, np.ndarray) else x,
ivy/func_wrapper.py:400: in _handle_array_like_without_promotion
    return fn(*args, **kwargs)
ivy/functional/ivy/creation.py:1901: in native_array
    return ivy.to_native(ivy.asarray(x, dtype=dtype, device=device))
ivy/func_wrapper.py:400: in _handle_array_like_without_promotion
    return fn(*args, **kwargs)
ivy/func_wrapper.py:868: in _handle_out_argument
    return fn(*args, out=out, **kwargs)
ivy/func_wrapper.py:357: in _handle_array_function
    return fn(*args, **kwargs)
ivy/func_wrapper.py:831: in _handle_device_shifting
    return fn(*args, **kwargs)
ivy/functional/ivy/creation.py:147: in _asarray_to_native_arrays_and_back
    return to_ivy(fn(*new_args, dtype=dtype, **kwargs))
ivy/functional/ivy/creation.py:243: in _asarray_infer_device
    return fn(*args, device=device, **kwargs)
ivy/functional/ivy/creation.py:71: in _asarray_handle_nestable
    return fn(*args, **kwargs)
ivy/functional/ivy/creation.py:254: in _inputs_to_native_shapes
    return fn(*new_args, **kwargs)
ivy/functional/ivy/creation.py:202: in _asarray_infer_dtype
    dtype = ivy.as_native_dtype(dtype)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ('uint16',), kwargs = {}

    @functools.wraps(fn)
    def _handle_exceptions(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
            return fn(*args, **kwargs)
        # Not to rethrow as IvyBackendException
        except IvyNotImplementedException as e:
            _configure_stack_trace(e.__traceback__)
            raise e
        except IvyError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyError(
                fn.__name__, str(e), include_backend=True
            )
        except IvyBroadcastShapeError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyBroadcastShapeError(
                fn.__name__, str(e), include_backend=True
            )
        except IvyDtypePromotionError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyDtypePromotionError(
                fn.__name__, str(e), include_backend=True
            )
        except (IndexError, IvyIndexError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyIndexError(
                fn.__name__, str(e), include_backend=True
            )
        except (AttributeError, IvyAttributeError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyAttributeError(
                fn.__name__, str(e), include_backend=True
            )
        except (ValueError, IvyValueError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyValueError(
                fn.__name__, str(e), include_backend=True
            )
        except (Exception, IvyBackendException) as e:
            _configure_stack_trace(e.__traceback__)
>           raise ivy.utils.exceptions.IvyBackendException(
                fn.__name__, str(e), include_backend=True
            )
E           ivy.utils.exceptions.IvyBackendException: paddle: as_native_dtype: Cannot convert to Paddle dtype. uint16 is not supported by Paddle.

ivy/utils/exceptions.py:372: IvyBackendException

During handling of the above exception, another exception occurred:

args = ({'x': array(49024, dtype=uint16)}, <function test_frontend_function.<locals>.<lambda> at 0x7fc48718d900>), kwargs = {'shallow': False}

    @functools.wraps(fn)
    def _handle_exceptions(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
>           return fn(*args, **kwargs)

ivy/utils/exceptions.py:335: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy/functional/ivy/nest.py:1163: in nested_map
    ret = {
ivy/functional/ivy/nest.py:1164: in <dictcomp>
    k: nested_map(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (array(49024, dtype=uint16), <function test_frontend_function.<locals>.<lambda> at 0x7fc48718d900>, {<class 'tuple'>: False, <class 'list'>: False, <class 'dict'>: False}, (), False, None, ...)
kwargs = {}

    @functools.wraps(fn)
    def _handle_exceptions(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
            return fn(*args, **kwargs)
        # Not to rethrow as IvyBackendException
        except IvyNotImplementedException as e:
            _configure_stack_trace(e.__traceback__)
            raise e
        except IvyError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyError(
                fn.__name__, str(e), include_backend=True
            )
        except IvyBroadcastShapeError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyBroadcastShapeError(
                fn.__name__, str(e), include_backend=True
            )
        except IvyDtypePromotionError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyDtypePromotionError(
                fn.__name__, str(e), include_backend=True
            )
        except (IndexError, IvyIndexError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyIndexError(
                fn.__name__, str(e), include_backend=True
            )
        except (AttributeError, IvyAttributeError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyAttributeError(
                fn.__name__, str(e), include_backend=True
            )
        except (ValueError, IvyValueError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyValueError(
                fn.__name__, str(e), include_backend=True
            )
        except (Exception, IvyBackendException) as e:
            _configure_stack_trace(e.__traceback__)
>           raise ivy.utils.exceptions.IvyBackendException(
                fn.__name__, str(e), include_backend=True
            )
E           ivy.utils.exceptions.IvyBackendException: paddle: nested_map: paddle: as_native_dtype: Cannot convert to Paddle dtype. uint16 is not supported by Paddle.

ivy/utils/exceptions.py:372: IvyBackendException

During handling of the above exception, another exception occurred:

    @handle_frontend_test(
>       fn_tree="paddle.clone",
        dtype_and_x=helpers.dtype_and_values(available_dtypes=helpers.get_dtypes("valid")),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:496: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py:508: in test_paddle_clone
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:784: in test_frontend_function
    raise e
ivy_tests/test_ivy/helpers/function_testing.py:735: in test_frontend_function
    kwargs_frontend = ivy.nested_map(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ({'x': array(49024, dtype=uint16)}, <function test_frontend_function.<locals>.<lambda> at 0x7fc48718d900>), kwargs = {'shallow': False}

    @functools.wraps(fn)
    def _handle_exceptions(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
            return fn(*args, **kwargs)
        # Not to rethrow as IvyBackendException
        except IvyNotImplementedException as e:
            _configure_stack_trace(e.__traceback__)
            raise e
        except IvyError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyError(
                fn.__name__, str(e), include_backend=True
            )
        except IvyBroadcastShapeError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyBroadcastShapeError(
                fn.__name__, str(e), include_backend=True
            )
        except IvyDtypePromotionError as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyDtypePromotionError(
                fn.__name__, str(e), include_backend=True
            )
        except (IndexError, IvyIndexError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyIndexError(
                fn.__name__, str(e), include_backend=True
            )
        except (AttributeError, IvyAttributeError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyAttributeError(
                fn.__name__, str(e), include_backend=True
            )
        except (ValueError, IvyValueError) as e:
            _configure_stack_trace(e.__traceback__)
            raise ivy.utils.exceptions.IvyValueError(
                fn.__name__, str(e), include_backend=True
            )
        except (Exception, IvyBackendException) as e:
            _configure_stack_trace(e.__traceback__)
>           raise ivy.utils.exceptions.IvyBackendException(
                fn.__name__, str(e), include_backend=True
            )
E           ivy.utils.exceptions.IvyBackendException: paddle: nested_map: paddle: nested_map: paddle: as_native_dtype: Cannot convert to Paddle dtype. uint16 is not supported by Paddle.
E           Falsifying example: test_paddle_clone(
E               frontend='paddle',
E               on_device='cpu',
E               dtype_and_x=(['bfloat16'], [array(-1, dtype=bfloat16)]),
E               test_flags=FrontendFunctionTestFlags(
E                   num_positional_args=0,
E                   with_out=False,
E                   inplace=False,
E                   as_variable=[False],
E                   native_arrays=[False],
E                   generate_frontend_arrays=False,
E               ),
E               fn_tree='ivy.functional.frontends.paddle.clone',
E           )
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.80.0', b'AXicY2UAAkYGCIDSAACOAAg=') as a decorator on your test case

ivy/utils/exceptions.py:372: IvyBackendException
====================================================================== warnings summary ======================================================================
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py: 76 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1059: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================================== 40.0% of 5 passed ======================================================================================================================================== short test summary info ===================================================================
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_clone[cpu-ivy.functional.backends.tensorflow-False-False] - AssertionError: returned dtype = bfloat16, ground-truth returned dtype = uint16
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_clone[cpu-ivy.functional.backends.torch-False-False] - AssertionError: returned dtype = bfloat16, ground-truth returned dtype = uint16
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_clone[cpu-ivy.functional.backends.paddle-False-False] - ivy.utils.exceptions.IvyBackendException: paddle: nested_map: paddle: nested_map: paddle: as_native_dtype: Cannot convert to Paddle dtype. uint16 is not ...
========================================================= 3 failed, 2 passed, 76 warnings in 12.01s ==========================================================
```

**Comment by Kalachuchis** [comment]
Pushed some changes. Results of tests: 
```
Use Database in ReadOnly Mode with local caching !
=================================================================================== test session starts ===================================================================================
platform linux -- Python 3.10.0, pytest-7.4.0, pluggy-1.2.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-3.7.1, json-report-1.5.0, metadata-3.0.0, hypothesis-6.82.0
collected 5 items                                                                                                                                                                         

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py .....                                                                                                    [100%]

==================================================================================== warnings summary =====================================================================================
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py: 50 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1035: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================================================================== 100.0% of 5 passed =========================================================================================================================================================== 5 passed, 50 warnings in 92.00s (0:01:32) ========================================================================
```

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! I have tested the implementation locally and it seems to be failing for the TypeError. Can you please resolve it?
```
E       TypeError: test_frontend_function() missing 1 required keyword-only argument: 'backend_to_test'
```

**Comment by Kalachuchis** [comment]
Hi! Sorry for the late updates. Pushed some changes resolving the missing keywords in the test function. here are the results
```
(base) root ➜ /workspaces/ivy (master) $ pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py::test_paddle_clone
Fallback to DirectoryBasedExamples
Database unavailable, local caching only !
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.10.0, pytest-7.4.0, pluggy-1.2.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-3.7.1, json-report-1.5.0, metadata-3.0.0, hypothesis-6.82.3
collected 5 items                                                                                                                                                                 

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py .....                                                                                            [100%]

================================================================================ warnings summary =================================================================================
../../opt/fw/tensorflow/_distutils_hack/__init__.py:18
  /opt/fw/tensorflow/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
    warnings.warn(

../../opt/fw/tensorflow/_distutils_hack/__init__.py:33
  /opt/fw/tensorflow/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")

../../opt/fw/tensorflow/setuptools/sandbox.py:13
  /opt/fw/tensorflow/setuptools/sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../../opt/fw/tensorflow/pkg_resources/__init__.py:2871
  /opt/fw/tensorflow/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py: 50 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1035: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================ 100.0% of 5 passed ======================================================================================================================================================== 5 passed, 54 warnings in 58.94s =========================================================================
```

**Comment by Kalachuchis** [comment]
test results 
```
Use Database in ReadOnly Mode with local caching !
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.10.0, pytest-7.4.0, pluggy-1.2.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-3.7.1, json-report-1.5.0, hypothesis-6.82.4, metadata-3.0.0
collected 5 items                                                                                                                                                                 

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py .....                                                                                            [100%]

================================================================================ warnings summary =================================================================================
ivy/data_classes/container/base.py:1396
  /workspaces/ivy/ivy/data_classes/container/base.py:1396: DeprecationWarning: invalid escape sequence '\.'
    flat_keys = re.split("/|\.", key_chain)  # noqa

../../opt/fw/tensorflow/_distutils_hack/__init__.py:18
  /opt/fw/tensorflow/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
    warnings.warn(

../../opt/fw/tensorflow/_distutils_hack/__init__.py:33
  /opt/fw/tensorflow/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")

../../opt/fw/tensorflow/setuptools/sandbox.py:13
  /opt/fw/tensorflow/setuptools/sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../../opt/fw/tensorflow/pkg_resources/__init__.py:2871
  /opt/fw/tensorflow/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_creation.py: 50 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1035: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================ 100.0% of 5 passed =================================================================================================================================================== 5 passed, 55 warnings in 88.99s (0:01:28) ====================================================================
```

**Comment by Kalachuchis** [comment]
Fixed conflicts. please review @kurshakuz

**Pull request closed without merging**
