### PR TITLE
Feat: Erosion2d Tensorflow Frontend

### LINKED ISSUE #23317: erosion2d
Function to implement Erosion2D

### PR DESCRIPTION
**Pull request by bhavya092**
Close #23317 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by bhavya092** [comment]
@RickSanchezStoic can you help me to understand what's going wrong?

**Comment by RickSanchezStoic** [comment]
Hi @bhavya092 checkout the error logs and you should see this error :
```
 i_h, i_w = ivy.shape(image)
E   ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by bhavya092** [comment]
@RickSanchezStoic Can you mention what is wrong with the code and the indentation? Why is there a lint error?

**Comment by RickSanchezStoic** [comment]
Hi @bhavya092 the first issue that needs attention here is the test for the function fails which you can see in the logs of `intelligent-tests-pr / run_tests (1) (pull_request)`

**Comment by Ishticode** [comment]
closing this as changes requested above remain unresolved. Please feel free to reopen if you would like to keep working, resolve the conflicts and rerequest a review. Thank you very much :)

**Pull request closed without merging**
