### PR TITLE
orthogonal #17774

### LINKED ISSUE #17774: orthogonal

### PR DESCRIPTION
**Pull request by stalemate1**
close #17774

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
hey @stalemate1 

Would you add changes to this PR as it seems like you haven't added anything to this PR😂

**Comment by dash96** [comment]
Sorry there was an issue with an other function that I was working on earlier on the same file. Hence, to avoid infinite loop of conflict I did not add any file here.

**Comment by dash96** [comment]
will add as soon as I merge the other function

**Pull request closed without merging**
