### PR TITLE
fix(torch-frontend): fix failing test for torch.nn.functional.group_norm

### PR DESCRIPTION
**Pull request by yopknopixx**
# PR Description

fix failing test for torch.nn.functional.group_norm

### CODE REVIEW

**Review by vedpatwardhan — APPROVED** [review]
lgtm! For whatever reason the CI isn't able to capture these changes and run relevant tests. Feel free to merge the PR provided you've run the ivy tests and frontend tests for functions dependent on `ivy.group_norm` and they pass. Thanks @yopknopixx 😄

**Review by kurshakuz — COMMENTED** [review]
@yopknopixx can you run the test locally and show the passing results before I merge? Thanks!

**Comment by vedpatwardhan** [comment]
Hey @yopknopixx let me know once you're done with what @kurshakuz suggested (no rush). Thanks 😄

**Comment by yopknopixx** [comment]
image
Apologies for the delay @kurshakuz! I missed your comment.

**Comment by vedpatwardhan** [comment]
awesome, feel free to merge the PR in that case, thanks @yopknopixx 😄

**Pull request merged**
