### PR TITLE
SELU FUNCTION

### PR DESCRIPTION
**Pull request by SaimR036**

### CODE REVIEW

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi @SaimR036 ,

This should be added in the respective frontend file, kindly link your PR to the issue or let me know from which todo list did you choose the function so I can link the issue you created.

Also, please add the test to the function as well in the respective test file.

Thanks! :slightly_smiling_face:

**Comment by SaimR036** [comment]
@zaeemansari70 #19808 This is the task

**Review by zaeemansari70 — COMMENTED** [review]
Hi @SaimR036  
The issue you linked me to is already closed and marked as done :thinking: 
This function already exists in the ivy's functional API, feel free to select something else from the to do list, thanks :slightly_smiling_face:

**Comment by zaeemansari70** [comment]
Closing as discussed above :+1:

**Pull request closed without merging**
