### PR TITLE
Reformatting for Issue #1251

### PR DESCRIPTION
**Pull request by pfdah**
Issue -#1251 some of the back end had already been modified, but I made it similar to the closed Issue function

### CODE REVIEW

**Comment by pfdah** [comment]
#1251

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @pfdah, I apologize for the delay. Can you add more examples to the function's implementation in the /ivy/functional/ivy/creation.py file. Make sure to add the examples as explained [here](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html#docstring-examples). Feel free to ask any questions. Thanks!

**Comment by pfdah** [comment]
Sorry for the delay from my side as well. How many examples should I add and what are the scenarios that I must cover?

**Comment by saeedashrraf** [comment]
Hello @pfdah , I apologize for the delay again. Your pull request slipped under the radar 😅. Regarding the number of examples that you should add, your examples should:

1. cover all possible variants (explained below) for each of the arguments independently, not combinatorily. This means the number of examples should be equal to the maximum number of variations for a single argument, and not the entire grid of variations across all arguments (further explained in the examples below)

2. vary the values and input shapes considerably between examples
 
3. start with the simplest examples first. For example, this means using the default values for all optional arguments in the first example, and using small arrays, with a small number of dimensions, and with simple values for the function in question
 
4. include an example with: (a) out unused, (b) out used to update a new array y, and (c) out used to inplace update the input array x (provided that it shares the same dtype and shape as the return)

Thanks for your effort!

**Pull request closed without merging**
