### PR TITLE
qr

### PR DESCRIPTION
**Pull request by Guru-mp3**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Guru-mp3** [comment]
@agniiyer Please check the PR

**Comment by agniiyer** [comment]
Hey you still have to implement the test for the function! Take a look at some other examples in the code and the docs to understand how to do this :)

**Comment by Guru-mp3** [comment]
Okay sure

**Comment by Guru-mp3** [comment]
@agniiyer I have added the test, can you review my PR again?

**Comment by agniiyer** [comment]
Hey the tests are not passing. Can you merge with upstream and then take another look?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
