### PR TITLE
feat: added the batch_norm function to NN paddle frontend

### LINKED ISSUE #23300: batch_norm

### PR DESCRIPTION
**Pull request by Sanjay8602**
# PR Description
feat: added the norm for NN paddle frontend

## Related Issue
Resolves #23300 

Closes #

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Review by Sanjay8602 — COMMENTED** [review]
--

**Review by Sanjay8602 — COMMENTED** [review]
deleted paddlefrontend in test_norm.py

**Review by Sanjay8602 — COMMENTED** [review]
--

**Comment by Sanjay8602** [comment]
Hi @KareemMAX , 
I am new contributor to IVY 
Sir I need some help 
I have passed nearly 95% test cases but I am getting error in 6 test cases and I don't know what to do next next please help me 
I have update all the files and resolved all those error but in last 6 errors I am getting what to do ?
please reply ASAP

**Comment by KareemMAX** [comment]
> I have passed nearly 95% test cases but I am getting error in 6 test cases and I don't know what to do next next please help me

I'm not really sure which test cases are you talking about, usually a single test function will only add 5 tests.

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Seems like you deleted some unrelated files. Can you revert that change back?

**Comment by Sanjay8602** [comment]
> Seems like you deleted some unrelated files. Can you revert that change back?

Those file were not related this issue so by mistake all those files came along

**Comment by KareemMAX** [comment]
> Those file were not related this issue so by mistake all those files came along

Sadly we can't merge with those removed files appearing in the PR diff. You'll need to remove them

**Pull request closed without merging**
