### PR TITLE
Torch Lcm Frontend

### PR DESCRIPTION
**Pull request by nassimberrada**
PR for issue #4937

### CODE REVIEW

**Comment by nassimberrada** [comment]
**Tests Passed**

**Review by Ishticode — CHANGES_REQUESTED** [review]
Great effor Nassim. As all the backends have a supported version of lcm, we will wait for the Ivy api extension.

**Comment by nassimberrada** [comment]
**Status**: Waiting for ivy.lcm

**Comment by Ishticode** [comment]
> **Status**: Waiting for ivy.lcm

You're welcome to implement it yourself.

**Comment by nassimberrada** [comment]
I raised the issue for the ivy.lcm extension, just waiting for it to be up

**Pull request closed without merging**
