### PR TITLE
paddle diagonal

### LINKED ISSUE #17933: diagonal

### PR DESCRIPTION
**Pull request by elabongaatuo**
Close #17933

### CODE REVIEW

**Comment by paulaehab** [comment]
Hi @elabongaatuo could you please check that function passing tests also I couldn't resolve conflicts

**Comment by paulaehab** [comment]
Also, you need to add   backend_fw, variable in test_paddle_diagonal function and then add  backend_to_test=backend_fw to test_frontend_method function

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
