### PR TITLE
dropout #4475

### PR DESCRIPTION
**Pull request by anaghazachariah**
solving dropout #4475

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by DragosStoican** [comment]
Hey @Ammar-Shah 🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://unify.ai/docs/ivy/overview/contributing/the_basics.html)

**Comment by DragosStoican** [comment]
Hi @anaghazachariah it looks like the dropout function in the tensorflow frontend is already implemented. I apologies for the confusion. Could you please look for another function to implement and open a new PR for that? Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
