### PR TITLE
leaky_relu

### PR DESCRIPTION
**Pull request by wassimchouchen**
This is the PR for the code challenge, actually the new function applies the negative slope to negative values, and returns the input

### CODE REVIEW

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hey @wassimchouchen! 
Thank you so much for contributing to ivy! 🙂

You have added the superset behaviour in the ivy functional only, as this function uses `ivy.current_backend()` which states that this is a primary function and it's functionality in all the backends is to be updated, you have only added it in ivy only 🙂

Also, you have to handle the added arguments in the test files as well.
I'd refer you to the docs as it is explained in detail there :slightly_smiling_face: 
 https://lets-unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html
You also don't need to make any changes to the `array_api` folder :slightly_smiling_face: 

Do let me know if you have any other questions!
Thanks!

**Comment by wassimchouchen** [comment]
hey @zaeemansari70 how are you, 
as you asked i made the necessary changes in all the backend framework that use leaky_relu function(jax, numpy, paddle, tensorflow, torch) and made the necessary changes in "ivy_tests\test_ivy\test_functional\test_nn\test_activations.py" leaky relu unit test
and about the array_api i didn't made anything in it, i reset al the repos and fetch the changes and just changing the LEaky relu as the first commit, and the others i am gonna work on them after completing from this 

thanks a lot man

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
The hypothesis tests are failing, please fix the failures and request another review

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
