### PR TITLE
added resolve_neg

### LINKED ISSUE #19543: resolve_neg

### PR DESCRIPTION
**Pull request by 00umar**
close #19543

### CODE REVIEW

**Comment by Infrared1029** [comment]
Hey @00umar, there are several major issues with the PR such as the writing the function in the wrong file, adding a `if __nam__=="__main__"` section in `tensor.py`, and the test itself , I'd suggest taking a look at the docs and familiarizing yourself with them first, thanks!

**Comment by 00umar** [comment]
Thanks....will do that.

**Comment by 00umar** [comment]
Am I to place it at miscellaneous file?

**Comment by 00umar** [comment]
@Infrared1029 good day, my pycharm professional has expired, I've no get to test the code with VScode, should i still make the PR? i will really appreciate your response

**Comment by 00umar** [comment]
@Infrared1029 good day..can you help and assess this PR? thanks

**Review by 00umar — COMMENTED** [review]
can you review the changes?

**Comment by Sarvesh-Kesharwani** [comment]
Hi @00umar , 
please resolve the merge conflicts so we can proceed with your pull request.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Sarvesh-Kesharwani** [comment]
Hi @00umar,
can you remove the unrelated changes from the commit.
thanks

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
