### PR TITLE
Create set.py

### PR DESCRIPTION
**Pull request by WILHEMS**

### CODE REVIEW

**Comment by aditya-pola** [comment]
Hey, I'm a little unclear about the PR. Can you point me to what task your PR is regarding?

**Comment by WILHEMS** [comment]
> Hey @WILHEMS, I'm a little unclear about the PR. Can you point me to what task your PR is regarding?

Hey @aditya-pola I was trying to reslove an issue posted by one of the engineers concerning creating the new file set.py under tensorflow frontends I went ahead and did that.

**Comment by aditya-pola** [comment]
This must be a mistake. You are adding what seems like a backend function to the frontend. Could you link the original issue here please?

**Comment by WILHEMS** [comment]
Hello, I realised the mistake and please allow me to close the issue so that I can create a new one. Thank you.

**Comment by aditya-pola** [comment]
Hey @WILHEMS, please feel free to create a new issue and an assosciated PR. Following which, request a review from me and I'll take a look!

**Comment by WILHEMS** [comment]
Thank you @aditya-pola  for the kind gesture. I am looking forward to it. Have a nice time.

**Pull request closed without merging**
