### PR TITLE
Developed a storage function

### PR DESCRIPTION
**Pull request by TahaTasleem**

### CODE REVIEW

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hey! 
First of all thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
It just seems to be incomplete, to complete the frontend task you have to do the following:

1. Implement the `test` for `is_storage()` as well to complete the task. For reference I am attaching the link to the guide https://lets-unify.ai/ivy/deep_dive/ivy_frontends_tests.html#frontend-instance-method-test-examples, which will help you in the process.
  
Thanks !🙂

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
The ivy backend of this function `is_storage()` should be implemented in the extensions first. For extension you also have to write a description that why a certain function should be added to the ivy extension, which in this case is `is_storage`.

I've attached the guides below which explains the process in detail, thanks! 🙂

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
The backends are being only implemented in the `extensions` now, you have implemented it in the `ivy/functional/backends/torch/utility.py`.
I also previously highlighted that, In this case the specific function can be added in the extensions of Ivy only first, https://github.com/unifyai/ivy/issues/3856.
I'd also suggest that you make another PR for the extension task as these are two separate tasks you have done in a single PR.

I'll link you to the guidelines again:

1. https://lets-unify.ai/ivy/contributing/open_tasks.html#ivy-api-extensions
2. https://lets-unify.ai/ivy/contributing/the_basics.html#extensions.

Do let me know if you have any other questions. 🙂

**Comment by TahaTasleem** [comment]
- [ ] #6695

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by zaeemansari70 — COMMENTED** [review]
Just submitting a general review as I saw you have another PR opened related to the backend for the same function, https://github.com/unifyai/ivy/pull/6700, once this one get's merged then the frontend implementation in this PR will be useful.
Will surely review once you get the backend merged 🙂
Thanks! 🙂

**Pull request closed without merging**
