### PR TITLE
added round func to ndarray.py in numpy/ndarray

### PR DESCRIPTION
**Pull request by hanafganesa**
#6063 
fixing merging branch conflict on 1st pull request

### CODE REVIEW

**Comment by sharique1006** [comment]
Hi @hanafganesa, you need to write tests for your function as well. You shouldn't be committing changes for `.idea` files. Also, please resolve the lint errors.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
