### PR TITLE
added docstring examples for expand_dims for #1221

### PR DESCRIPTION
**Pull request by sohamtiwari3120**
#1221

### CODE REVIEW

**Comment by sohamtiwari3120** [comment]
Hi @chie2727, can you please review my PR, also there are certain linting errors from Flake8, I have tried to resolve most of them, but would require confirmation on how to resolve the remaining ones.

Thank you

**Comment by sohamtiwari3120** [comment]
@chie2727 @1Doomdie1 @djl11 
Hi, I haven't received any reviews yet for my PR

**Comment by sohamtiwari3120** [comment]
Hi @chie2727 @djl11 @1Doomdie1 can you please review my PR? 
I can't request a PR review directly because of the following note from Github

> Note: Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

**Comment by djl11** [comment]
Hi @sohamtiwari3120, very sorry for the delay. I've just requested for @Darshan-H-E to review this. We will have a review done very soon! Thanks for your patience!

**Comment by Darshan-H-E** [comment]
Hi @sohamtiwari3120, apologies for the delay. One minor fix is required on line 337 for the formatting check to pass. Please try to fix that.

**Comment by sohamtiwari3120** [comment]
Hi @Darshan-H-E, I have added # noqa for line 337 in `ivy\functional\ivy\manipulation.py` which contained the URL for the array API documentation. And I have corrected the URL to point to the expand_dims function
Before:
```
(337)     `docstring <https://data-apis.org/array-api/latest/API_specification/generated/signatures.elementwise_functions.tan.html>`_
```

After:
```
(337)     `docstring <https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.expand_dims.html>`_ # noqa
```

**Comment by sohamtiwari3120** [comment]
Thank you @chie2727 :)

**Comment by Darshan-H-E** [comment]
Hi @chie2727 and @sohamtiwari3120 since the function is already in the functional API, there's no need to mention ivy.Container in the type hints of the function.

**Comment by sohamtiwari3120** [comment]
Oh, so you would like me to remove ivy.Container from the type hints?
Before:
```
def expand_dims(
    x: Union[ivy.Array, ivy.NativeArray, ivy.Container],
    axis: int = 0,
    *,
    out: Optional[Union[ivy.Array, ivy.Container]] = None,
) -> Union[ivy.Array, ivy.Container]:
```

After?:
```
def expand_dims(
    x: Union[ivy.Array, ivy.NativeArray],
    axis: int = 0,
    *,
    out: Optional[ivy.Array] = None,
) -> ivy.Array:
```

**Comment by Darshan-H-E** [comment]
yeah, there was no change required for the type hint. If possible @chie2727 make a revert so that @sohamtiwari3120 can make a new commit

**Comment by sohamtiwari3120** [comment]
@Darshan-H-E should I instead create a new PR?

**Comment by sohamtiwari3120** [comment]
Also, @Darshan-H-E, I did not exactly understand why ivy.Container type should not be present in the type hints since it is already in the functional API?

So when is the ivy.Container applicable to be used in type hints? Can you please help me understand the same?

**Comment by Darshan-H-E** [comment]
@sohamtiwari3120, it depends on the function. If the function is not in the functional API then we add the container to the type hint. If we keep on adding container to the type hint of every function, then it becomes clunky.

**Comment by Darshan-H-E** [comment]
Hope this helps

**Comment by chie2727** [comment]
Hi @sohamtiwari3120 , as expand_dims is a nestable function, we can omit the ivy.Container type hint for this.
You can see a full explanation for this here under the header Nestable Functions:
https://lets-unify.ai/ivy/deep_dive/9_function_arguments.html

Please make a new commit and I'll merge your changes in.

**Comment by Darshan-H-E** [comment]
Thanks for helping out with the PR @chie2727

**Comment by sohamtiwari3120** [comment]
Thanks @chie2727! :) 
I too went ahead and explored the docs yesterday in search for the answer and found the nestable part in functional arguments.

Also, do I need to remove `ivy.Container` examples from the docstring for the function or let it be? @chie2727 @Darshan-H-E

**Comment by sohamtiwari3120** [comment]
Hi @chie2727 and @Darshan-H-E, I have pushed a new commit to my fork. 
1. I have only changed the functional arguments:
Before:
```
def expand_dims(
    x: Union[ivy.Array, ivy.NativeArray, ivy.Container],
    axis: int = 0,
    *,
    out: Optional[Union[ivy.Array, ivy.Container]] = None,
) -> Union[ivy.Array, ivy.Container]:
```

After:
```
def expand_dims(
    x: Union[ivy.Array, ivy.NativeArray],
    axis: int = 0,
    *,
    out: Optional[ivy.Array] = None,
) -> ivy.Array:
```


2. My docstring still includes explanations for ivy Container, do I leave it be or remove it?
3. Do I need to create a new PR?

**Comment by Darshan-H-E** [comment]
Hi @sohamtiwari3120, there's no need to change the examples or explanations about Container. You have done a good job. The only thing is change the function type hints to what it was before you made any commits/changes. And make a commit to this PR itself. Hope it answers all your doubts. If not feel free to ping again.

**Comment by sohamtiwari3120** [comment]
Hi @Darshan-H-E, before I made any changes to the function, the function signature was:
```
def expand_dims(
    x: Union[ivy.Array, ivy.NativeArray],
    axis: int = 0,
    *,
    out: Optional[Union[ivy.Array, ivy.NativeArray]] = None,
) -> ivy.Array:
```

My question was, for the **out** keyword argument, should it include the ivy.NativeArray type? If I understand correctly, it should only have the `Optional[ivy.Array]` type, right?

**Comment by Darshan-H-E** [comment]
yeah since we are returning an ivy array, it makes more sense to change it to `out: Optional[ivy.Array]`.

**Comment by sohamtiwari3120** [comment]
Hi @Darshan-H-E and @chie2727, I have created a new PR #1348

**Comment by Darshan-H-E** [comment]
Thanks @sohamtiwari3120

**Pull request merged**
