### PR TITLE
zeros_initializer

### LINKED ISSUE #20947: <zeros_initializer>

### PR DESCRIPTION
**Pull request by mohansharma077**
closes #20947

### CODE REVIEW

**Comment by mohansharma077** [comment]
#20947 I have this issue created and requested for pull request. I
don''t see any pull request on my profile what happens, does it accept or
reject?

**Review by AryanSharma21 — COMMENTED** [review]
Implementation looks good , I saw the test log , the failing test cases are not related with your code. However, request review from a maintainer so we can understand better

**Comment by mohansharma077** [comment]
Thanks for the feedback!

**Comment by mohansharma077** [comment]
@AryanSharma21 erros are  related to tensorflow

**Comment by mohansharma077** [comment]
@juliagsy any updates

**Comment by AryanSharma21** [comment]
@juliagsy  please review

**Comment by mohansharma077** [comment]
@ivy-leaves review please

**Comment by mohansharma077** [comment]
@juliagsy @ivy-leaves please review

**Comment by juliagsy** [comment]
Hey! Really sorry on the delay, due to the slight difference in the behaviour of this function, I'm double checking with the relevant team internally, I'll try to get back to you soon! Apologies and thanks!

**Comment by mohansharma077** [comment]
I am waiting to hear back from you ,  thanks!

**Comment by mohansharma077** [comment]
> Hey! Really sorry on the delay, due to the slight difference in the behaviour of this function, I'm double checking with the relevant team internally, I'll try to get back to you soon! Apologies and thanks!

@juliagsy  any updates

**Comment by juliagsy** [comment]
Thanks for contributing!

**Pull request merged**
