### PR TITLE
torch linalg.qr frontend

### PR DESCRIPTION
**Pull request by sondertg**

### CODE REVIEW

**Comment by sondertg** [comment]
close #7604

**Comment by sondertg** [comment]
I realized there is another qr function defined in ```C:\Users\tugaygül\PycharmProjects\Ivy\ivy\ivy\functional\frontends\torch\blas_and_lapack_ops.py```
Do I need to remove that?

**Comment by sondertg** [comment]
Only failing qr test related to implemented at here. I can remove that if requested. Thanks.

> I realized there is another qr function defined in `C:\Users\tugaygül\PycharmProjects\Ivy\ivy\ivy\functional\frontends\torch\blas_and_lapack_ops.py` Do I need to remove that?

**Comment by sondertg** [comment]
Hi @ukj02, I checked and asked torch channel at dc about implementation of qr. Failed qr tests related to torch.qr at `blas_and_lapack_ops.py` and linalg.qr is not an alias of that one. All frontend tests are fixed for linalg.qr,  this PR ready to be merged. Can you please review when you have time?

**Comment by ukj02** [comment]
Hi @sondertg! Thank You for you contribution! 😀 

Sorry for the late response, but this looks good to me!

**Pull request merged**
