### PR TITLE
Update the pdist() function for PyTorch frontend pdist #17097

### LINKED ISSUE #17097: pdist

### PR DESCRIPTION
**Pull request by shaimah**
Closes #17097

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by danielmunioz** [comment]
Hey @shaimah! Thanks for contributing!
Just a minor detail, the default value of `p` should be 2 and x should be called `input` in the function arguments I believe, the frontend implementations should resemble their [original counterparts](https://pytorch.org/docs/stable/generated/torch.nn.functional.pdist.html) as closely as possible, the test arguemnts should be updated with the new name accordingly as well.

Other than that the tests seem to be passing locally and in general the PR looks to be in a good shape!

**Comment by theRealBird** [comment]
@danielmunioz Looping you back in here. Not sure why the assignee was changed. Thanks!

**Comment by danielmunioz** [comment]
Hey @shaimah! I just checked your PR again, thanks for the changes! It seems to be working well and the tests are passing locally, the only thing left is to remove the asterisk for in the function definition (in the original function p is both a positional and keyboard argument), but I'll take care of that minuscule detail after merge!

Overall, LGTM! Merging Now

Thanks for contributing! 🚀

**Pull request merged**
