### PR TITLE
Close #10248

### LINKED ISSUE #10248: clip_by_norm

### PR DESCRIPTION
**Pull request by ezgiogulmus**

### CODE REVIEW

**Comment by ezgiogulmus** [comment]
Hello @WilliamHirst,
I really don't know what the problem is. The logs are not very descriptive or I don't get them. I keep checking my code but couldn't find the solution. Can you help me understand why it's failing?
Thanks!

**Comment by WilliamHirst** [comment]
Hi Ezgi,
Thanks for making a contribution! :)

As for the lint-test, all failing test are unrelated to your contribution. In other words, just ignore this.

To check out the errors related to your changes, click "Details" on "intelligent-tests-pr/run_tests_1". Then click "Determine and Run Tests", then use cmd+F and search for "Falsifying example: test_tensorflow_clip_by_norm" to find the errors triggered by your changes.

**Comment by WilliamHirst** [comment]
Hi Ezgi,
There still seems to be some errors related to your PR. When these errors are fixed, let me know! :)

**Comment by ezgiogulmus** [comment]
Still working on it. I'll let you know as soon as it's done. 
Thank you :)
Have a great day!

**Comment by WilliamHirst** [comment]
Hi, these are all errors in files unrelated to your changes. Good job! 👏

**Pull request merged**
