### PR TITLE
put_along_axis

### LINKED ISSUE #21569: put_along_axis

### PR DESCRIPTION
**Pull request by SumantxD**
Close #21569

### CODE REVIEW

**Comment by SumantxD** [comment]
@kurshakuz Could you review my code plz!! :smile:

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! Your implementation seems to be failing currently. You can take a look at the error below:

```
E           ivy.utils.exceptions.IvyBackendException: torch: concat: Tensors must have same number of dimensions: got 1 and 2
```

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
