### PR TITLE
Added ifft function for numpy frontend with local tests passing

### LINKED ISSUE #9949: ifft

### PR DESCRIPTION
**Pull request by CodeMaestro1000**
Close #9949

### CODE REVIEW

**Comment by CodeMaestro1000** [comment]
Lint test failure does not have anything to do with my code...

Black and flake8 tests passed as part of pre-commit.

**Comment by V-G-spec** [comment]
Thanks for your contribution @CodeMaestro1000. If I'm not wrong, the `test-frontend-numpy / run-nightly-tests (pull_request)` shows some errors originating from your file. Can you please address this?

**Comment by CodeMaestro1000** [comment]
Hi @V-G-spec 

I tried reproducing the specific error but it passed locally. I don't know what the issue might be but here's my test case and here's the results:
```
from hypothesis import reproduce_failure
import ivy_tests.test_ivy.helpers as helpers
from ivy_tests.test_ivy.helpers import handle_frontend_test


@handle_frontend_test(
    fn_tree="numpy.fft.ifft",
    dtype_and_x=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("numeric")
    )
    
)
# @reproduce_failure('6.55.0', b'AAIAAACAAAAAAAAAAAA=')
def test_numpy_iftt(
    dtype_and_x,
    frontend,
    test_flags,
    fn_tree,
    on_device
):
    input_dtype, x = dtype_and_x
    helpers.test_frontend_function(
        input_dtypes=input_dtype,
        frontend=frontend,
        test_flags=test_flags,
        fn_tree=fn_tree,
        on_device=on_device,
        test_values=True,
        a=x,
        n=None,
        axis=-1,
        norm=None
    )
```

And here are the results:
```
Use Database in ReadOnly Mode with local caching !
================================================================ test session starts =================================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /workspaces/ivy
plugins: typeguard-2.13.3, hypothesis-6.55.0, metadata-2.0.4, json-report-1.5.0
collected 4 items                                                                                                                                    

ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py ....                                                  [100%]

================================================================== warnings summary ==================================================================
../../usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19
  /usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================ 4 passed, 1 warning in 7.53s ============================================================
```

I'll go ahead and commit again to run the tests. I'll try to reproduce the errors if they don't pass the frontend tests.

**Comment by CodeMaestro1000** [comment]
Hi @V-G-spec The errors from my code in `test-frontend-numpy / run-nightly-tests (pull_request)` have been fixed and the tests passed. Can you please review?

Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by V-G-spec** [comment]
Hey @CodeMaestro1000, apologies for the late reply. Thanks for fixing the errors. Only a couple of lint errors are there now in your primary function file- There should be 2 blank lines after the import statements and there shouldn't be a blank line at the end of the file. I'll merge your PR as soon as you fix those. Everything else looks good
Thanks!

**Comment by CodeMaestro1000** [comment]
Hi @V-G-spec. Thanks for the feedback. The requested lint changes have been made to all the necessary files. Thanks 👍

**Comment by V-G-spec** [comment]
Somehow because of that change, the first intelligent test is not passing anymore

**Comment by CodeMaestro1000** [comment]
I think the issue would probably be that this branch is several commits behind the main branch. I'll try to update my branch and it should pass.
Thanks.

**Comment by V-G-spec** [comment]
Ok

**Comment by CodeMaestro1000** [comment]
The intelligent-tests-pr have all passed. If there's anything else that needs reviewing please let me know.

Thanks 👍

**Comment by V-G-spec** [comment]
Your fix re-added the newline issue 😅. Please take a quick look at that

**Comment by CodeMaestro1000** [comment]
Hi @V-G-spec. I checked my files and there are no newlines. However, the lint tests (Flake8) are failing now because it says there should be a blank line at the end of my `discrete_fourier_transform.py` file. Here's the error:
```
ivy/functional/frontends/numpy/fft/discrete_fourier_transform.py:10:45: W292 no newline at end of file
```

According to PEP8 standard, there should be a newline at the end of each file. I'm confused as to what to follow. Any help would be much appreciated. Thanks.

**Comment by V-G-spec** [comment]
Yes, that is what I meant by my previous comment. For now, we can stick with the flake8 standard

**Comment by CodeMaestro1000** [comment]
Alright. I'll add the newlines to both files then. Thanks.

**Comment by CodeMaestro1000** [comment]
I think the frontend tests might have been refactored hence while the `intelligent-tests-pr` jobs are failing. You can take a look at the respective `run_tests_1` jobs inside each intelligent test and you should see that the test passed for `ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py`.

**Pull request closed without merging**
