### PR TITLE
Reformat lstm_update in layers

### LINKED ISSUE #9320: lstm_update

### PR DESCRIPTION
**Pull request by Saad-Mufti**
Close #9320

### CODE REVIEW

**Review by CatB1t — CHANGES_REQUESTED** [review]
Hello @Saad-Mufti! Thanks for your contribution (: 
I've requested some changes, please have a look and ask for a review when you're done fixing them!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by CatB1t — CHANGES_REQUESTED** [review]
LGTM!

**Review by CatB1t — APPROVED** [review]
LGTM!

**Pull request merged**
