### PR TITLE
add log1p frontend pytorch

### LINKED ISSUE #6676: log1p

### PR DESCRIPTION
**Pull request by MohamedHamdy28**
Close #6676

### CODE REVIEW

**Comment by MohamedHamdy28** [comment]
@Auxia 
Hello! Can you please help me, I don't know why its failing some checks. It passed all the tests when I ran it on my machine.

**Comment by Auxia** [comment]
Hi @MohamedHamdy28, It is actually passing the test. The github workflow actually tests all the functions under the torch frontend (and the same for others as well). Though, can you get the conflicts resolved? I will be happy to merge as soon as you can get those conflicts resolved.

**Comment by MohamedHamdy28** [comment]
@Auxia Hi! is it ok now?

**Comment by Auxia** [comment]
Yep, looks good to me! Thanks for contributing :)

**Pull request merged**
