### PR TITLE
feat: implementation of ctc_loss function

### LINKED ISSUE #24636: ctc_loss

### PR DESCRIPTION
**Pull request by tbeetech**
# PR Description

## Related Issue

Close #24636 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Infrared1029** [comment]
hello @tbeetech, thanks for your contribution, if you add a backend function it should be added to all backend functions, as well as a method for `ivy.Array` and `ivy.Container`, and the test ofc.

**Comment by tbeetech** [comment]
@Infrared1029 please respond

**Comment by Infrared1029** [comment]
> @Infrared1029 please respond

Hello @tbeetech, PRs can take up to three work days to get reviewed as we usually work on other stuff internally besides reviewing PRs, please be patient during weekends!

**Comment by tbeetech** [comment]
> > @Infrared1029 please respond
> 
> Hello @tbeetech, PRs can take up to three work days to get reviewed as we usually work on other stuff internally besides reviewing PRs, please be patient during weekends!

ive completed the task you assigned to me can i get a review now @Infrared1029

**Comment by Infrared1029** [comment]
Hello, @tbeetech, as mentioned previously, `ctc_loss` should be implemented for *all* bacekends we support, there should be an instance method for the Array class, and an instance method for the Container class, and a test written, that passes.

The current PR does not do any of this (correctly) and the torch implementation included is incorrect too, please make sure to go through the docs and choose an easier task/function, adding a backend function is one of the longer and more difficult tasks. ill be closing this PR for now.

**Pull request closed without merging**
