### PR TITLE
feat: add bessel_i0e to tensorflow frontend

### LINKED ISSUE #26241: bessel_i0

### PR DESCRIPTION
**Pull request by TobeTek**
# PR Description
Implement tensorflow frontend for bessel_i0e function

Close #26241 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @TobeTek! Thanks for the PR. However, you'd need to fix the [failing tests](https://github.com/unifyai/ivy/actions/runs/6333803527/job/17202447329?pr=26242) for us to proceed forward. Can you look into fixing the tests? Thanks :)

**Comment by hmahmood24** [comment]
> Hi @hmahmood24 👋🏾, I tried fixing the tests, but the following code:
> 
> ```python
> bessel_i0e = ivy.exp(-ivy.abs(x)) * ivy.i0(ivy.abs(x))
> ```
> 
> is not consistent with the result of other frameworks/backends. I have confirmed that is the right formula for the exponentially scaled Bessel function of the first kind ( I0e(x) )
> 
> I found [SciPy's i0e implementation](https://github.com/scipy/scipy/blob/main/scipy/special/cephes/i0.c#L167), and would like to implement that using `ivy` manipulation methods, without using the `ivy.i0` method. What do you think?
> 
> Thanks!

@TobeTek Sure no worries. Feel free to implement your function using `ivy` functions even though this isn't ideal and we try to keep the frontend implementations as brief as possible. Can you try to implement yours s.t. it is <10 lines of code? Thanks!

**Comment by hmahmood24** [comment]
Closing this PR since it has been stale for more than 2 weeks now.

**Comment by TobeTek** [comment]
Hi @hmahmood24 ,
Apologies for not replying earlier. I was waiting for my earlier PR, https://github.com/unifyai/ivy/pull/26993 to get reviewed and merged, since it was somewhat a foundation for this. I figured if there were any changes that would affect my `bessel_i0` implementation, they would also affect this `bessel_i0e` implementation.
It's been quite a while since I opened #26993 , but it's yet to be reviewed. I was hoping you could review that, and if you think it's good to go, I can jump back in here.

Thanks!

**Pull request closed without merging**
