### PR TITLE
add ivy.erfc to ivy experimental API

### LINKED ISSUE #21130: erfc

### PR DESCRIPTION
**Pull request by akshatvishu**
Close #21130

### CODE REVIEW

**Comment by akshatvishu** [comment]
@YushaArif99  Can you please review it ?

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @akshatvishu 

Extremely sorry for the delay in response. I was away traveling for a few weeks due to which I couldnt respond to a lot of the PRs. Now that I am back, I'll definately be more responsive.

With regards to the PR, your implementation does look good to me at first glance. But since the CI tests are showing, I cant say whether there are any bugs or not. 
Could you kindly resolve the merge conflicts and then re-request a review once that's done? Hopefully, the CI tests will then run 🤞🏼 
Thanks! @akshatvishu 🙂

**Comment by akshatvishu** [comment]
Hey@YushaArif99, can you please review it again!

**Review by YushaArif99 — APPROVED** [review]
Hi @akshatvishu 

Thanks a lot for making the requested changes. The PR looks in a healthy state now and all relevant tests also seem to be passing. I'll be going ahead with the merge. Great work 👏🏼

**Comment by akshatvishu** [comment]
> Hi @akshatvishu
> 
> Thanks a lot for making the requested changes. The PR looks in a healthy state now and all relevant tests also seem to be passing. I'll be going ahead with the merge. Great work 👏🏼

Thanks for the review @YushaArif99   (୨୧•͈∀•͈)⊃━ᵗʱᵃᵑᵏઽ

**Pull request merged**
