### PR TITLE
function sqrt implemented and formatted

### PR DESCRIPTION
**Pull request by ZeynelAbidin91**
The PR includes the implementation of **'sqrt' function** that is formatted to Array API standards. 
All tests passed on all frameworks except mxnet.

### CODE REVIEW

**Review by djl11 — APPROVED** [review]

**Comment by djl11** [comment]
Thanks!

**Comment by djl11** [comment]
Sorry @ZeynelAbidin91, I just realized a couple of tests were failing for TensorFlow. Please create a new PR. I have just also re-opened the issue.

**Comment by ZeynelAbidin91** [comment]
Ok,  working on it. Thanks for informing me @djl11

**Comment by ZeynelAbidin91** [comment]
"unary_assert_against_refimpl" gives error with tensorflow in sqrt_test. tf.sqrt gives a different value in test than it normally gives when I apply it as a single function with the same input value like in terminal.   

in details:

in_ = ivy.array([[0.000000e+00, **8.507059e+37**, 0.000000e+00],
           [0.000000e+00, 0.000000e+00, 0.000000e+00],
           [0.000000e+00, 0.000000e+00, 0.000000e+00]], dtype=float32)
res = ivy.array([[0.000000e+00, **1.383168e+19**, 0.000000e+00],
           [0.000000e+00, 0.000000e+00, 0.000000e+00],
           [0.000000e+00, 0.000000e+00, 0.000000e+00]], dtype=float32)

the output of this input 8.507059e+37 must be 9.223372036854776e+18. instead it gives different value.

E                 AssertionError: out[0, 1]=**1.3831680355561636e+19, but should be roughly sqrt(x[0, 1])=9.223372036854776e+18** [sqrt()]
E                 x[0, 1]=8.507059173023462e+37
E               assert False
E                +  where False = isclose(1.3831680355561636e+19, 9.223372036854776e+18)

On the other hand when I apply tf.sqrt() with same input it returns correct value. 

>>> tf.math.sqrt(8.507059e+37)
<tf.Tensor: shape=(), dtype=float32, numpy=9.223372e+18>


I got stuck here. What approach do you suggest?

**Comment by ZeynelAbidin91** [comment]
https://github.com/unifyai/ivy/pull/375
New PR was sent.

**Pull request merged**
