### PR TITLE
Adding shape_n function 

### LINKED ISSUE #7966: shape_n

### PR DESCRIPTION
**Pull request by adrivg10**
- [ ] Close #7966

### CODE REVIEW

**Comment by WilliamHirst** [comment]
Hi! The commit looks good, there seem to be a couple of failing tests though. Have a look at the failing lint test.

Thanks 😊

**Comment by adrivg10** [comment]
Hi! I was looking at them but they have nothing to be with the code I updated (my code goes from line 671 to 704 in test_general_functions.py and it got the error in line 711,712 and 715). Same with the other 2 errors on numpy/experimental/linear_algebra.py and jax/experimental/linear_algebra.py:103:40

**Comment by adrivg10** [comment]
Also, when I pass the tests to the code on docker, it is passing all the them without any error

**Comment by WilliamHirst** [comment]
Yes you are right! Will give it a last little check and merge if it seems good 👌🏼

**Comment by adrivg10** [comment]
Perfect!, i will wait for your answer 😄

**Pull request merged**
