### PR TITLE
PR for issue #808

### PR DESCRIPTION
**Pull request by Allaye**
fixed issue #808

### CODE REVIEW

**Comment by Allaye** [comment]
@sherry30  and @Ishticode  can you please review my PR

**Review by sherry30 — CHANGES_REQUESTED** [review]
Can you remove all the changes to the .idea folder and .gitignore file from the commit, also you don't have to write docstring in all of the backend functions since it will get repetitive, just in ivy/image.py is fine.
and one last thing, can you write output of the example in the dcostring directly under the print statement as it would appear on a terminal

**Comment by Allaye** [comment]
@sherry30   i have done the necessary update

**Comment by Allaye** [comment]
@sherry30  please do help me with the review, i have made the requested update

**Pull request closed without merging**
