### PR TITLE
Added Tile function

### PR DESCRIPTION
**Pull request by faseehahmed26**

### CODE REVIEW

**Comment by faseehahmed26** [comment]
This pull request will solve this  issue https://github.com/unifyai/ivy/issues/5335

**Comment by faseehahmed26** [comment]
Hi as discussed I have closed my PR and  opened a New Pull Request @simonetgordon  could you please review it

**Comment by simonetgordon** [comment]
Hi there, 

We have the same problem with this PR, as you can see. Perhaps you made a mistake when resolving merge conflicts. Can you check these files for repeated code? i.e. a function being defined twice

**Review by simonetgordon — CHANGES_REQUESTED** [review]
Same issue as before

**Comment by faseehahmed26** [comment]
If possible could you please tell the filename where there are repeating function 

> Hi there,
> 
> We have the same problem with this PR, as you can see. Perhaps you made a mistake when resolving merge conflicts. Can you check these files for repeated code? i.e. a function being defined twice

**Comment by simonetgordon** [comment]
We are always only talking about the files which you have edited, i.e. appear in 'Files Changed'

**Comment by faseehahmed26** [comment]
As I have re forked the repository and I have created a new branch to create a  pull  request  I have only added my  bit of  the functions and haven't edited anything else

**Comment by faseehahmed26** [comment]
I am not seeing any repeated function inside "Files Changed"

**Comment by faseehahmed26** [comment]
If you could share a Screenshot or anything else to explain the error I am facing it would be great

**Comment by simonetgordon** [comment]
Hmm, I have taken a look at your branch an indeed there are no repeated functions in the files you've changed. I'm not sure why the diff looks like that. I will merge this PR as `test_tile` seems to still be passing. I will keep an eye on it and it may need to be reverted.

**Comment by faseehahmed26** [comment]
Thanks a lot

**Comment by faseehahmed26** [comment]
fixed https://github.com/unifyai/ivy/issues/5335

**Pull request merged**
