### PR TITLE
Adding additional arguments in `max_pool1d` and `max_pool3d` similar to how they're implemented in `max_pool2d`

### PR DESCRIPTION
**Pull request by kgmann**
Fixes https://trello.com/c/2JFgzicu

Added `dilation`, `ceil_out` and depth wise pooling to `max_pool1d`

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Please update the tests to include the new arguments and expand the range of example generation for updated old arguments

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by kgmann** [comment]
Hey @MahmoudAshraf97, sure, I was actually not done yet. They are still a few changes to make to the functions as well as updating the tests. I was working on another task, but I'll get this done in a bit.

**Review by sherry30 — APPROVED** [review]
lgtm!
You can go ahead and merge it if there are no failures other than the valid_dtype one

**Pull request merged**
