### PR TITLE
Added cosh instance method in pytorch frontend

### PR DESCRIPTION
**Pull request by usama-baloch**

### CODE REVIEW

**Comment by vaatsalya123** [comment]
Hey @usama-baloch thank you so much for contributing,Though your PR has a merge conflict which need's to be resolved before I can do a review.Though once you have resolved the issue feel free to ask me again to do a review of the PR thanks!

**Comment by usama-baloch** [comment]
Hi @vaatsalya123 thank you for pointing out the problem, I just resolve the conflicts. Now you can review it :)

**Comment by vaatsalya123** [comment]
Hey @usama-baloch sorry for the delayed response! ,Though your PR looks good (:

**Comment by vaatsalya123** [comment]
Hey @usama-baloch sorry for the delayed response! ,Though your PR looks good (:

**Comment by usama-baloch** [comment]
Thanks @vaatsalya123 :)

**Pull request merged**
