### PR TITLE
Added jax.numpy.array_equiv function to JAX frontend.

### LINKED ISSUE #5867: array_equiv

### PR DESCRIPTION
**Pull request by JaithraVarma**
Close #5867

### CODE REVIEW

**Comment by JaithraVarma** [comment]
Hi @CerberusLatrans,
I have added both array_equiv function of JAX frontend and its test. Please see to it and let me know if that is okay.
Thanks.

**Comment by CerberusLatrans** [comment]
Hi Jaithra. Thanks for your PR-- everything looks good. Just before I merge, do you know if the test is passing locally for you? The CI does not seem to be showing the test logs for me right now.

**Comment by JaithraVarma** [comment]
Hi @CerberusLatrans. The test is passing for me.

**Comment by CerberusLatrans** [comment]
Great! I will merge. Thank you for your contribution!

**Pull request merged**
