### PR TITLE
Added alpha_dropout and test_torch_alpha_dropout for pytorch frontend

### PR DESCRIPTION
**Pull request by akkefa**
Added alpha_dropout and test_torch_alpha_dropout for pytorch frontend

#18331

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MuhammadNizamani** [comment]
Closed #18331
@akkefa next time write 'closed' beside your issue name like above so when your PR got merge your issue should closed automatically.

**Comment by akkefa** [comment]
> Closed #18331 @akkefa next time write 'closed' beside your issue name like above so when your PR got merge your issue should closed automatically.

@MuhammadNizamani  Sure.

**Comment by akkefa** [comment]
@MuhammadNizamani Why tests are failing can you help me understand the issue?

**Comment by akkefa** [comment]
Yes. @MuhammadNizamani Should I wait or need to work on backend implementation too?

**Comment by MuhammadNizamani** [comment]
@akkefa  i do not think waiting is an option

**Comment by ZoeCD** [comment]
I cannot provide an estimated timeline for this, as it depends heavily on our community and internal efforts. If you would like to work on the implementation yourself, please let me know. In the meantime, I will close this PR, and we can resume once the function is added to Ivy's API

**Pull request closed without merging**
