### PR TITLE
exp2 extension

### LINKED ISSUE #6196: exp2

### PR DESCRIPTION
**Pull request by nassimberrada**
Close #6196

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
About the tensorflow backend
I am not fully sure of the consequences of `np_config.enable_numpy_behavior()`.... But enabling it file wide could lead to some unforeseen results in other functions. 

**I think its best** if we use 
```python
    return tf.cast(
        tf.math.pow(tf.constant(2, dtype=x.dtype), x), dtype=x.dtype
    )
```
 instead of involving numpy into this at all.

So could you delete the np config import and behaviour setting and updte the implementation in the tesorflow backend. 

edit: maybe just `2` instead of `tf.constant(2, dtype=x.dtype)` **might** work to as the first input for `pow` also I think.

**Comment by nassimberrada** [comment]
I actually got an error that suggested using that when making use of numpy related functions, unless i used it the tests wouldn't pass. Switched for tf.math.pow as you suggested and it works as well, that's definitely better than relying on a file-wide change.

**Review by Ishticode — CHANGES_REQUESTED** [review]
We actually dont need the `tf.cast`. It should be removed.
It should just be `return tf.math.pow(2,x)`. I think it should pass. Lmk when done and hopefully its ready

And the error for numpy related behaviour wast that tf's numpy experimental exp2 called x.astype internally with x being a tf tensor. This required np behaviour to be enabled. Bus fortunately we can steer clear from the whole thing.

**Comment by nassimberrada** [comment]
I see, yeah the error was definitely related to the "astype" element, makes sense. 
Removed tf.cast.

**Review by Ishticode — APPROVED** [review]

**Pull request merged**
