### PR TITLE
Fe numpy cov 7651

### LINKED ISSUE #7651: cov

### PR DESCRIPTION
**Pull request by picqushini**
Close #7651

### CODE REVIEW

**Comment by WilliamHirst** [comment]
Hi,
There seems to be a formatting error. Could you have a look at this?
Thanks

**Comment by WilliamHirst** [comment]
Also you do not seem to have linked your commit to any issue. Please follow the instructions in the docs.

https://lets-unify.ai/ivy/contributing/the_basics.html

**Comment by picqushini** [comment]
Hi :)
For some reason, I cannot add only the relevant changes. I have also tried to commit and push only the two files that I have modified, but it does not work.

The formatting errors (reason why the test don't pass) are for files that i did not touch. I have asked on the Discord server and Anna said that's to be expected because the test checks everything, not just my functions, so I shouldn't concern myself with errors that are not caused by my code. 

I cannot link the issue to the PR because I can't modify the Development section on the right (actually, I can't modify anything from the right side section... ).

Sorry, it's my first time contributing to a big project so, even though I followed the guide, I might have done something wrong or I may be missing some passages 😢 Thank you for your patience

**Comment by WilliamHirst** [comment]
I see!

Yes you are absolutely right, the formatting errors are not related to your change so do not worry about this.

As for the linking to the issue, you can simply modify your first comment in the PR and add "Close #<Issue number>".

And as for all the changes made to the different files, I suggest tracing your commit history and find which commit made this changes then revert back. 

No worries! Good luck 😊

**Comment by picqushini** [comment]
@WilliamHirst , It's the [initialized] commit, but that's automatic, correct?
Could a solution be to add the files manually on GitHub instead of pushing them from my local machine?

**Comment by WilliamHirst** [comment]
I have had a look and I cant really see where you went wrong. I would recommend that you create a new branch, copy only the relevant changes and create a new PR. Please also tag me in this new PR so I can continue helping you. 

If the error still continues, I would possibly try only making changes directly on github as the changes might be made by your  IDE.

**Comment by picqushini** [comment]
Ok, will do!
Thank you again :)

**Pull request closed without merging**
