### PR TITLE
Add tan and tanh to JAX frontend

### LINKED ISSUE #7165: tan

### LINKED ISSUE #7166: tanh

### PR DESCRIPTION
**Pull request by TAUIL-Abd-Elilah**
Close #7165
Close #7166

### CODE REVIEW

**Comment by TAUIL-Abd-Elilah** [comment]
HI @CerberusLatrans 
Can I know what gets wrong, because I don't get any errors on my local machine?

**Comment by CerberusLatrans** [comment]
Hi @TAUIL-Abd-Elilah thanks for the PR!

Nothing about the test looks wrong and it makes sense that it passes locally.
If you are wondering why the test-frontend-jax CI tests are failing, that is for a bunch of other tests that are likely failing due to a recent refactoring in the frontend testing methods.

Let me know if this makes sense or if you have any questions. Otherwise, I think it can be merged.

**Comment by TAUIL-Abd-Elilah** [comment]
Thanks for your reply @CerberusLatrans.
Yes, it makes sense, and I don't have any questions.

**Comment by CerberusLatrans** [comment]
Great; thanks for  the contribution! I have merged it.

**Pull request merged**
