### PR TITLE
Changes in nonzero function

### PR DESCRIPTION
**Pull request by gabrielfgoi**
close https://github.com/unifyai/ivy/issues/12877

### CODE REVIEW

**Review by jkeane508 — CHANGES_REQUESTED** [review]
hey,

Thanks for submitting this PR! 

Could you please link the issue this closes?

Thanks
James

**Comment by gabrielfgoi** [comment]
Hey, sure 

here the issue 

nonzero #12877

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by gabrielfgoi** [comment]
Waiting for the review

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @gabrielfgoi 

Would you explain the purpose of this PR if there is an issue that you were facing would you provide a to reproduce it so we can make sure that this PR solves the issue😊

Also would you remove the `.DS_Store` file that is added to this PR.

Thanks

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
