### PR TITLE
feat: Added unsorted_segment_sqrt_n function 

### LINKED ISSUE #23780: unsorted_segment_sqrt_n

### PR DESCRIPTION
**Pull request by kamlishgoswami**
Close #23780

### CODE REVIEW

**Comment by kamlishgoswami** [comment]
Hi @MahmoudAshraf97  ,

Can u please review the PR and please let me know if any changes are needed? Thanks

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hello and thanks for the contribution, the implementation has several failures that can be discovered by running the tests using this command:
```pytest ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_creation.py::test_unsorted_segment_sqrt_n```

if the test is slow, you can use the following flags to select one backend only and prevent generating minimal examples ` -B=numpy --robust`, this can speed up the initial debugging.
Once all the tests are passing, feel free to request another review

**Comment by kamlishgoswami** [comment]
After making the changes still 27 tests are failing. Could you please help to sort out this issue?

**Comment by NiteshK84** [comment]
Hi @kamlishgoswami , 
please resolve the merge conflicts so we can proceed with your pull request.

**Comment by kamlishgoswami** [comment]
> Hi @kamlishgoswami , please resolve the merge conflicts so we can proceed with your pull request.

Hello @NiteshK84, I have resolved the merge conflicts. Thanks!

**Comment by kamlishgoswami** [comment]
> > Hi @kamlishgoswami , please resolve the merge conflicts so we can proceed with your pull request.
> 
> Hello @NiteshK84, I have resolved the merge conflicts. Thanks!

@NiteshK84, Looking forward to your kind response. Thanks

**Comment by NiteshK84** [comment]
Hi @kamlishgoswami,
Can you work on these failing test cases.
image

image

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by kamlishgoswami** [comment]
Update!!

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @kamlishgoswami 
Thanks for the effort. 
There are 5 dinstinct failures noted by hypothesis for test_unsorted_segment_sqrt_n as seen in logs (under Combined Test Results) here 
https://github.com/unifyai/ivy/actions/runs/7446656031/job/20258066865?pr=27180
you can use the search bar to find it.
Please could you try to fix these and request a review when done. Thank you very much

**Comment by Ishticode** [comment]
Thank you very much for the PR. Closing this due to lack of activity with changes requested remaining unresolved. Please feel free to reopen if you would like to continue working on this. :)

**Pull request closed without merging**
