### PR TITLE
fix: fixed typo's in `ivy_tests\test_ivy\helpers\globals.py`

### LINKED ISSUE #26413: Small Typo in `ivy_tests\test_ivy\helpers\globals.py`
In the file [`ivy_tests\test_ivy\helpers\globals.py`](https://github.com/unifyai/ivy/blob/main/ivy_tests/test_ivy/helpers/globals.py)
In the following lines the word `interrupted` is misspelled (second `t` is missing).
https://github.com/unifyai/ivy/blob/d0e94eecc26b02ac6cb014065bcd40a8e69f3f3c/ivy_tests/test_ivy/helpers/globals.py#L65
https://github.com/unifyai/ivy/blob/d0e94eecc26b02ac6cb014065bcd40a8e69f3f3c/ivy_tests/test_ivy/helpers/globals.py#L66

Also, in the file [`CITATION.cff`](https://github.com/unifyai/ivy/blob/main/CITATION.cff) The last line can be removed and added in the last but one sentence as it is just 1 word in the last line. Changing this will make it look more clean.
https://github.com/unifyai/ivy/blob/d0e94eecc26b02ac6cb014065bcd40a8e69f3f3c/CITATION.cff#L43
(YAML linter spotted this for me when I was looking that file)

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
In the file [`ivy_tests\test_ivy\helpers\globals.py`](https://github.com/unifyai/ivy/blob/main/ivy_tests/test_ivy/helpers/globals.py)
In the following lines the word `interrupted` is misspelled (second `t` is missing).
https://github.com/unifyai/ivy/blob/d0e94eecc26b02ac6cb014065bcd40a8e69f3f3c/ivy_tests/test_ivy/helpers/globals.py#L65
https://github.com/unifyai/ivy/blob/d0e94eecc26b02ac6cb014065bcd40a8e69f3f3c/ivy_tests/test_ivy/helpers/globals.py#L66

Also, in the file [`CITATION.cff`](https://github.com/unifyai/ivy/blob/main/CITATION.cff) The last line can be removed and the 1 word can be added in the last but one sentence as it is just 1 word in the last line. Changing this will make it look more clean.
https://github.com/unifyai/ivy/blob/d0e94eecc26b02ac6cb014065bcd40a8e69f3f3c/CITATION.cff#L43
(YAML linter spotted this for me when I was looking that file)

## Related Issue
Close #26413

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials
https://twitter.com/Sai_Suraj_27

### CODE REVIEW

**Review by sherry30 — APPROVED** [review]
The one in the testing looks good, I'll ask Ved's review for the change in the .cff file since I'm not sure about that.

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Feel free to merge @sherry30, thanks @Sai-Suraj-27 😄

**Review by CatB1t — APPROVED** [review]
lgtm!

**Comment by Sai-Suraj-27** [comment]
@sherry30 sir, the PR got approval, [lease look into this when you are free, Thank you.

**Comment by vedpatwardhan** [comment]
I'll get this merged now, thanks @Sai-Suraj-27 😄

**Pull request merged**
