### PR TITLE
Added tensorflow.math.zeta to Tensorflow Ivy Frontends

### LINKED ISSUE #13313: Zeta
Implementing the  [tf.math.zeta](https://www.tensorflow.org/api_docs/python/tf/math/zeta) for ivy frontend tensorflow

### PR DESCRIPTION
**Pull request by akshatvishu**
Close #13313

### CODE REVIEW

**Comment by akshatvishu** [comment]
Previously made the [PR](https://github.com/unifyai/ivy/pull/13444) for the same issue but had to close it due to encountering an intractable error.

Currently, passing all test-cases except for `Paddle backend` as paddle doesn't have an zeta function implementation!

**Comment by AnnaTz** [comment]
Hi, we can merge this as soon as you resolve the conflicts.

**Comment by akshatvishu** [comment]
> Hi, we can merge this as soon as you resolve the conflicts.

Sure!

**Comment by AnnaTz** [comment]
I think something went wrong with the merge. You didn't resolve some conflicts and now the code is kind of messed up.

**Comment by akshatvishu** [comment]
Let me undo the last commit and see the problem ! @AnnaTz

**Comment by AnnaTz** [comment]
Hi @akshatvishu, I think you have accidentally removed some functions.

**Comment by akshatvishu** [comment]
> Hi @akshatvishu, I think you have accidentally removed some functions.
Yeah @AnnaTz , I think I merged my changes my remote branch and that was causing the issue! But resetting my branch with master and then force pushing the changes worked !

**Comment by AnnaTz** [comment]
Apologies for the revert commit. It was by accident. I was just wondering why the name of the PR appear different in the master after I merge it.

**Comment by akshatvishu** [comment]
> Apologies for the revert commit. It was by accident, you can ignore it. I was just wondering why the name of the PR appears different in the master after I merged it.

No worries! Thank you for your valuable feedback throughout my PR ; I am eager to continue contributing to Ivy open-source and look forward to making even more substantial commitments in the future.

**Pull request merged**
