### PR TITLE
Paddle frontend round

### PR DESCRIPTION
**Pull request by gbit1605**
# PR Description
build: added round function to paddle frontend

## Related Issue

Close #26295

## Checklist

- [ Yes ] Did you add a function?
- [ Yes ] Did you add the tests?
- [ No ] Did you run your tests and are your tests passing?
- [ No ] Did pre-commit not fail on any check?
- [ Yes ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by umairjavaid — CHANGES_REQUESTED** [review]
There are merge conflicts. Please resolve those :)

**Comment by gbit1605** [comment]
> There are merge conflicts. Please resolve those :)

Hi, I have resolved the merge conflicts. Please let me know if anything else needs to be done.

**Comment by Ishticode** [comment]
I am closing this PR for several reasons. The PR adds unrelated methods like sum. It adds round but modifies its already existing test to be for round_. It links the issue to the very PR itself which means no external issues are linked along with few other issues I have noticed. If you feel right you can reopen or make another PR which is more than welcome. Please check out our contributors guideline at https://unify.ai/docs/ivy/overview/contributing.html

**Pull request closed without merging**
