### PR TITLE
Stateful activations submodule fixup

### PR DESCRIPTION
**Pull request by Oxbeefbabe**
Still WIP, waiting for changes on how unsupported data types are handled

### CODE REVIEW

**Comment by Oxbeefbabe** [comment]
Here's the stateful/activations submodule fixup is ready for review. Included as well is changes to the `test_method` function to detect unsupported dtypes/devices for constructors and methods in classes, and then testing that they do indeed fail, like the other testing helpers in helpers.py.

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hi @Oxbeefbabe, I think the tests are failing when run with a large number of examples (I tried with 100). I think the reason could be related to testing for unsupported_dtypes for backends where the `__init__` method is being used in `helpers.py` while for e.g. `unsupported_dtypes` is assigned to the `_forward` method for `GELU`. Apart from that, there are a few more failures related to the tolerance used for the value tests, please check that out.
Thanks 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by VedPatwardhan** [comment]
<Commit to keep the pr open>

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
