### PR TITLE
added Torch Instance Method "bitwise_right_shift_"

### LINKED ISSUE #22379: bitwise_right_shift_

### PR DESCRIPTION
**Pull request by AaizaKhan**
Close #22379

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by AaizaKhan** [comment]
@DecFox

**Comment by DecFox** [comment]
Hey @AaizaKhan thanks for the PR. Sorry for the late review. The diff here seems to span ~14k lines which I don't think was intended. Do you mind taking a look and only include changes specific to the `bitwise_right_shift_` function.
Thanks!

**Comment by AaizaKhan** [comment]
> Hey @AaizaKhan thanks for the PR. Sorry for the late review. The diff here seems to span ~14k lines which I don't think was intended. Do you mind taking a look and only include changes specific to the `bitwise_right_shift_` function. 

Hi, I was working on it. But somehow my PR closed?? I'm confused

**Comment by AaizaKhan** [comment]
I'll ping you once its done. @DecFox

**Pull request closed without merging**
