### PR TITLE
Updated nan_to_num

### PR DESCRIPTION
**Pull request by umer200**

### CODE REVIEW

**Comment by umer200** [comment]
closes #12752

**Comment by umer200** [comment]
please review my PR @MahmoudAshraf97

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hello, Paddle doesn't have a function called `nan_to_num`, you'll have to implement a solution using other functions

**Comment by umer200** [comment]
> Hello, Paddle doesn't have a function called `nan_to_num`, you'll have to implement a solution using other functions

Ok sir I'll check into that and update the function.
Meanwhile I just wanted to know that will this issue remain assigned to me since tomorrow is the last day for me to have this issue assigned to me or I'll have to reopen the issue?

**Pull request closed without merging**
