### PR TITLE
reptile_step #14980

### PR DESCRIPTION
**Pull request by cullenoc**
Reformat reptile_step: fixed typo in docstring and added docstring examples

### CODE REVIEW

**Comment by Sam-Armstrong** [comment]
Close https://github.com/unifyai/ivy/issues/14980

**Comment by Sam-Armstrong** [comment]
Hey @cullenoc, I've linked this to the corresponding issue - but in future please could you do this yourself by adding a comment ‘Close #Issue_number’, as explained here: https://unify.ai/docs/ivy/overview/contributing/the_basics.html

Thanks :) will review shortly

**Review by Sam-Armstrong — CHANGES_REQUESTED** [review]
I've suggested a couple of minor changes, but otherwise looks good

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Sam-Armstrong** [comment]
Has been resolved by https://github.com/unifyai/ivy/pull/16440

**Pull request closed without merging**
