### PR TITLE
#3603

### PR DESCRIPTION
**Pull request by aryans1204**
Added svd linear algebra operator under JAX frontend

### CODE REVIEW

**Comment by sreegandh804** [comment]
Hey @aryans1204 , could you change the issue title to the function name 🙂

**Comment by aryans1204** [comment]
Hi I edited it to (svd)#3603

**Comment by Oxbeefbabe** [comment]
Good start! Remember that for the front-end tasks you also need to implement the test for the front end. You can find more information on how to do so here: https://lets-unify.ai/ivy/deep_dive/17_ivy_frontends_tests.html

**Comment by aryans1204** [comment]
Hi I added the tests for the JAX operators

**Comment by Oxbeefbabe** [comment]
It seems the test you wrote is failing. Can you please get it passing? You should check `test-frontend-jax / run-nightly-tests (pull_request)` for more information

**Comment by aryans1204** [comment]
Hi I noticed that there aren't any tests for any of the functions under JAX linalg. Do I need to write those too for the svd function, or just the tests for the operators.py svd function?

**Comment by aryans1204** [comment]
Could you help me understand why the test are failing? I can't find a particular cause, even after commenting my test code out, the tests are still failing.

**Pull request closed without merging**
