### PR TITLE
Feature/add frontend function pytorch eigh

### LINKED ISSUE #22636: eigh
- [ ] #7479

### PR DESCRIPTION
**Pull request by AliTarekk**
# Add linear algebra `eigh` function to PyTorch frontend

Close #22636

### CODE REVIEW

**Comment by AliTarekk** [comment]
Close #22636

**Comment by AliTarekk** [comment]
@nathzi1505 Kindly review my PR. Thanks!

**Comment by nathzi1505** [comment]
Hi @AliTarekk can you check the lint issues for me?
Everything else looks good.

**Comment by AliTarekk** [comment]
> Hi @AliTarekk can you check the lint issues for me? Everything else looks good.

Hello @nathzi1505 I fixed the linting issue. I am not sure what I should do about the persisting linting error. Would be amazing if you take a look at it and get back to me. Thanks!

**Pull request merged**
