### PR TITLE
Implemented `erfinv` math functionality for TensorFlow frontend

### PR DESCRIPTION
**Pull request by edith007**
Close https://github.com/unifyai/ivy/issues/14171

### CODE REVIEW

**Comment by edith007** [comment]
@valeriocost Let me know if there are any suggestions or changes required ? 🙇🏻

**Comment by valeriocost** [comment]
@edith007 LGTM but there is a merging conflict, I think you removed `test_tensorflow_zeta`. Could you fix that? Thanks 😄

**Comment by edith007** [comment]
Resolved it! @valeriocost

**Comment by edith007** [comment]
@valeriocost We are getting `AttributeError: module 'ivy.functional.backends.torch' has no attribute 'erfinv'` Is there is no backend implementation for erfinv??

**Comment by valeriocost** [comment]
@edith007 looks like it! We do have the `erf` function in our functional API (https://github.com/unifyai/ivy/blob/7cb2d6de3dd15d1d7e335e46282f9830e9168e33/ivy/functional/ivy/elementwise.py#L5054), I think you should add the inverse yourself (take a look here https://lets-unify.ai/docs/ivy/overview/deep_dive/function_types.html, in particular "Compositional" and "Mixed" functions) 😄

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
