### PR TITLE
Update logic.py

### PR DESCRIPTION
**Pull request by Saumyadeepm**
_Functions added are as follows:_

- [x] #16411
- [x] #16412 
- [x] #16413 
- [x] #16414 
- [x] #16415 
- [x] #16416 
- [x] #16417

### CODE REVIEW

**Comment by theRealBird** [comment]
Hi @Saumyadeepm,
Thank you so much for your contribution and patience with the code review process. Are there any open issues related to the implementation of these functions, if so could you please link those issues in the PR? This helps us close the issues and keep track of what has been implemented. 
Thanks!

**Comment by Saumyadeepm** [comment]
Can you please help me how to and where to Start and write PR, i know it must be very silly to ask but still , I would be glad if you could help me out

**Comment by theRealBird** [comment]
No silly questions @Saumyadeepm! I would be happy to help. 

In accordance with our [contributing guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#the-basics), we need to:-

First open a new issue with the title being just the name of the sub-task you would like to work on. 

Comment on the ToDo list issue with a reference to this issue like so:
 #Issue_number
Your issue will then automatically be added to the ToDo list.

You then need to link the issue you created in your PR, so that we can keep track of it.  Feel free to reach out to me/visit our docs for more details.

**Comment by Saumyadeepm** [comment]
#16409

**Comment by Saumyadeepm** [comment]
Is is correct what is did above if not can you please guide me once again

**Comment by theRealBird** [comment]
Hey @Saumyadeepm , apologies for the delayed response, but as Anna explained this is not the correct way. 
I will try and explain it here once more :-
First go to the ToDo list issue where the list of all the functions that need to be implemented is present.
Choose one function that is open and that is present in that list, and create a issue for that function.
Then link the newly created issue with the ToDo list by commenting it there.
Then make a PR and link it to close the issue you created.

I would suggest going through the contributing guide once more as that explains it in a bit more detail and asking any specific questions if you have any.

Thanks a lot! :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Pull request closed without merging**
