### PR TITLE
PR for bitwise_invert

### PR DESCRIPTION
**Pull request by ebyau**
Jax,Numpy and Torch; some  tests are passing locally
Tensorflow; all tests are failing locally

### CODE REVIEW

**Comment by ebyau** [comment]
I was not able to verify bool and int data types for input array as required by the ```bitwise_invert``` function

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Please can you remove any changes you've made unrelated to your function. You should only make changes related to `bitwise_invert`. Thanks 🙂

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
It looks like you have made lots of small edits (like adding in space before `\`.  You've made so many changes I think it might just be easier to start over and make another PR only editing things related to `bitwise_invert`. Thanks 🙂

**Comment by ebyau** [comment]
Alright i will close this PR and create new one then ask you you to review

**Pull request closed without merging**
