### PR TITLE
sqrt in tensorflow updated

### PR DESCRIPTION
**Pull request by ZeynelAbidin91**
tf.sqrt doesn't generate the correct result with float32. I resolve it by casting to float64 then changed back to float32 after finding the correct solution. 
Now all tests passed in addition to all special case tests.
there should be a more efficient way. continue to examine. any help would be appreciated. Thanks

### CODE REVIEW

**Review by 1Doomdie1 — APPROVED** [review]
Looks good, thank you!

**Comment by ZeynelAbidin91** [comment]
> Looks good, thank you!

Thanks for the review!

**Review by djl11 — CHANGES_REQUESTED** [review]
Please uncomment sqrt method in `ivy_tests/array_api_methods_to_test`, and then `sqrt` will be included in the unit tests :)

Also I noticed an unused tensorflow import. Once these are fixed and the tests are passing, I can go ahead and merge!

**Comment by ZeynelAbidin91** [comment]
> Please uncomment sqrt method in `ivy_tests/array_api_methods_to_test`, and then `sqrt` will be included in the unit tests :)
> 
> Also I noticed an unused tensorflow import. Once these are fixed and the tests are passing, I can go ahead and merge!

I fixed all changes you requested @djl11. All tests for sqrt passed. Thanks!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
