### PR TITLE
Add is_tensor method to the paddle frontend tensor class

### LINKED ISSUE #17963: is_tensor

### PR DESCRIPTION
**Pull request by arshPratap**
Close #17963

### CODE REVIEW

**Comment by arshPratap** [comment]
@hmahmood24 would like to know your thoughts on this . Thanks !

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Daniel4078** [comment]
can you please comment this for a list of stuff you should care for:`add_frontend_checklist`. Thanks!

**Comment by arshPratap** [comment]
> can you please comment this for a list of stuff you should care for:`add_frontend_checklist`. Thanks!

@Daniel4078 my apologies but could you please elaborate on this a bit...

**Comment by Daniel4078** [comment]
> > can you please comment this for a list of stuff you should care for:`add_frontend_checklist`. Thanks!
> 
> @Daniel4078 thanks for the reply..my apologies but could you please elaborate on this a bit...

 That string is a keyword that when commented on its own will trigger one of the Ivy bots to put up a checklist of things to do for frontend impementaiton tasks.

**Comment by arshPratap** [comment]
add_frontend_checklist

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Can you resolve the conflict and mark your current progress on the Todo list? thanks

**Comment by arshPratap** [comment]
@Daniel4078 thanks for the suggestions..I have filed up the task list to the best of my knowledge and have also tested the `is_tensor` method. Please take another look . Thanks again !

**Review by Daniel4078 — APPROVED** [review]
Looks good to me, Thanks!

**Pull request merged**
