### PR TITLE
Added new_zeros instance method to PyTorch frontend #5733

### PR DESCRIPTION
**Pull request by afif-malghani**
The change is untested on local system as of now, having issues with shell scripts for testing.

Referance issue: #5733

### CODE REVIEW

**Comment by johanjino** [comment]
Hi @afif-malghani , could I know what was the issue you faced with the shell scripts for testing?

**Comment by afif-malghani** [comment]
ivy/run_tests_CLI/run_tests.sh: 
`ERROR: file or directory not found: ivy_tests/`

/ivy/run_tests_CLI/test_torch_frontend.sh: (no arguments given)
`ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --backend
  inifile: None
  rootdir: /ivy`

**Comment by johanjino** [comment]
> On PR checks I am getting assertion error on functions that I did not modify, like torch.addmv, torch.bmm, torch.matrix_rank, etc

this is alright, only functions of lines of code you have modified needs to be correct

**Comment by johanjino** [comment]
Seems good to me. Thank you for your contribution 😄

**Pull request merged**
