### PR TITLE
Refactor matrix_rank

### PR DESCRIPTION
**Pull request by karalleyna**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by simonetgordon — COMMENTED** [review]
Hi @karalleyna, looks good! But the ultimate test is for the Array-API tests to past. When you were refactoring, did you run these tests locally? I have just added the Array-API label so the tests should run on this PR now. When they have ran, could you check that matrix_rank passes on all the backends? If you find that it fails and are not sure how to fix it, please feel free to send me a message and we can work on it together :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by simonetgordon — CHANGES_REQUESTED** [review]
Hi @karalleyna, this all looks good! Could you pull from master to get the latest updates pertaining to the array-API tests? Then it's ready to be merged :)

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
