### PR TITLE
Add numpy frontend cbrt

### LINKED ISSUE #3397: Numpy Frontend cbrt
Implement Numpy's cbrt mathematical function. One of the tasks present in https://github.com/unifyai/ivy/issues/1525

### PR DESCRIPTION
**Pull request by aryanxk02**
Fixes #3397

### CODE REVIEW

**Comment by roboFiddle** [comment]
Hi @aryanxk02,

Thanks for your pull request. Can you please make sure that the formatting on your files is correct so that the lint/check-formatting check passes. It seems that test_np_arithmetic_operations.py is missing a newline at  the end of the file, but there may be other necessary changes too. Other than that, the PR looks good.

**Comment by aryanxk02** [comment]
Hello @roboFiddle 

I have added a new line at the end of test_np_arithmetic_operations.py Also, how do I fix the lint/check-formatting passes? Do I have to use a code formatter for that?

Thanks!

**Comment by roboFiddle** [comment]
Thanks, this looks good. I'll merge it now.

**Comment by aryanxk02** [comment]
Thank you! @roboFiddle

**Pull request merged**
