### PR TITLE
log10

### LINKED ISSUE #14275: log10

### PR DESCRIPTION
**Pull request by Dhruv2012**
Close #14275

### CODE REVIEW

**Comment by Dhruv2012** [comment]
Hii @Fayad-Alman, relevant tests are passing. Hopefully can be merged!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Fayad-Alman — CHANGES_REQUESTED** [review]
Hi Dhruv,

Sorry for the late response. All the changes look good, you just need to resolve the current conflicts with your branch compared to the Ivy repository.

Thanks for your patience and contributions,
Fayad

**Comment by Dhruv2012** [comment]
Hii @Fayad-Alman,
Resolved the merge conflicts.

**Review by Fayad-Alman — APPROVED** [review]
LGTM!

**Pull request merged**
