### PR TITLE
reformation task any

### PR DESCRIPTION
**Pull request by Paulyn01**

### CODE REVIEW

**Comment by Paulyn01** [comment]
Hi,
I am running the example using the master branch. as well as testing the examples on my Mac using the import ivy format and its running successfully.

**Comment by simonetgordon** [comment]
Hi Pauline, 

I think if you just fix the indentation as indicated above, all tests should pass! The docstrings test needs correct formatting to parse the output.

Simone

**Comment by simonetgordon** [comment]
Hi Pauline,

The numpy-style docstrings issue has been fixed, but there is still an error parsing the examples due to a line missing between the container examples (indicated in review comment above). You can see the issue in the following output in the docstrings test details:
```
output for  any  on run:  ivy.array(True)ivy.array([[True]])ivy.array(True)ivy.array(True)ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)}ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)} 

output in docs : ivy.array(True)ivy.array([[True]])ivy.array(True)ivy.array(True)ivy.array(True){a:ivy.array(True),b:ivy.array(True)}>>>x=ivy.Container(a=ivy.native_array([0,1,2]),b=ivy.array([3,4,5]))>>>y=x.any()>>>print(y)ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)}
```

**Comment by Paulyn01** [comment]
I try to fix the error but its still failing. What specific modification should I make please.

thank you

**Comment by simonetgordon** [comment]
Hi Pauline, 

If you just press leave an empty/blank line between the two docstring examples indicated previously - i.e., line 260 should be empty - then the test should pass 😊

**Comment by simonetgordon** [comment]
Hi Pauline,

Nice, that's fixed! However, now the test-docstrings is failing for a new reason 😅 This is the test output:
```
output for  any  on run:  ivy.array(True)ivy.array([[True]])ivy.array(True)ivy.array(True)ivy.array(True){a:ivy.array(True),b:ivy.array(True)}Dimensionoutofrange(expectedtobeinrangeof[-1,0],butgot-2)torchy=x.any(x){a:ivy.array(True),b:ivy.array(True)}ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)} 

output in docs : ivy.array(True)ivy.array([[True]])ivy.array(True)ivy.array(True)ivy.array(True){a:ivy.array(True),b:ivy.array(True)}ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)}
```

So for one of the examples, the dimension is out of range (at least for the torch backend): `Dimension out of range(expected to be in range of [ -1, 0 ], but got -2) torch`. Why don't you try running each of the examples in a python script to with `ivy.set_backend('torch')` to see if you can reproduce this error?

**Comment by simonetgordon** [comment]
Hi Pauline,

Almost there I think, but still some discrepancies. Looks like there is extra output when the code is run vs what you have written in the docs:

```
output for  any  on run:  
ivy.array(True)ivy.array([[True]])ivy.array(True)ivy.array(True)ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)}ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)} 
output in docs : 
ivy.array(True)ivy.array([[True]])ivy.array(True)ivy.array(True)ivy.array(True{a:ivy.array(True),b:ivy.array(True)}
ivy.array(True){a:ivy.array(True),b:ivy.array(True)}{a:ivy.array(True),b:ivy.array(True)}
```

**Comment by simonetgordon** [comment]
Perhaps try testing the examples one by one on to isolate which one is causing the issue?

**Comment by Paulyn01** [comment]
have done that and all are responding properly

**Comment by simonetgordon** [comment]
Hi Pauline,

Sorry I was on holidays last week. I can see it's passing the docstrings test now, so it's ready to merge!

**Pull request merged**
