### PR TITLE
feat(paddle): Add mean method to Paddle Frontend

### LINKED ISSUE #25943: mean

### PR DESCRIPTION
**Pull request by Boghdady9**
# PR Description

## Related Issue

Close #25943 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Boghdady9** [comment]
@hmahmood24

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @Boghdady9, thanks a lot for the PR. The tests seem to be passing when running locally so it looks good to me. Can you just fix some of the [lint issues](https://github.com/unifyai/ivy/actions/runs/6284449722/job/17065828426?pr=25950) with this PR? I recommend using `pre-commit`. Thanks!

**Comment by Boghdady9** [comment]
image

@hmahmood24

**Review by hmahmood24 — APPROVED** [review]
Looks good to merge! @Boghdady9 🚀

**Pull request merged**
