### PR TITLE
Update math.py --> reduce_mean( )

### LINKED ISSUE #20948: reduce_mean

### PR DESCRIPTION
**Pull request by kashi476074**
Close #20948

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by kashi476074** [comment]
I have the implementation of the function should I apply that or just use ivy.reduce_mean.

**Review by kashi476074 — COMMENTED** [review]
Added Astype function for datatype

**Comment by AlexandraPosta** [comment]
Hello! Unfortunately, I need to close this PR because of an error on our side. There is already an implementation for reduce_mean (please check the unifyai/ivy code). We really appreciate your interest in ivy, so I would strongly suggest to work on another task from the ToDo list. 

In the future, make sure to include testing for the function that you work on. Good luck! :)

**Pull request closed without merging**
