### PR TITLE
numpy instance method __itruediv__

### LINKED ISSUE #9007: __itruediv__

### PR DESCRIPTION
**Pull request by Chaitanya134**
Closes #9007

### CODE REVIEW

**Comment by Chaitanya134** [comment]
Hey @DragosStoican,
are these failing tests something to be worried about? If so, then how can I fix it?

**Comment by DragosStoican** [comment]
Hi @Chaitanya134, sorry for the wait, I was away for the holiday season :). 

You should only be concerned with the test for the function you implemented. Right now the test is failing due to the error : `fixture 'as_variable' not found`. You can look at some of the similar tests in the same file since the error is a test setup error. If you want to test locally if the tests are passing, check out the [setting up](https://lets-unify.ai/ivy/contributing/setting_up.html) tutorial. But you can also look at the logs here in github. I personally like to look at the raw logs and search for the name of the test that is being implemented. Try it out on your logs [herer](https://pipelines.actions.githubusercontent.com/serviceHosts/65e6b2a0-b7ba-4104-8cd3-f0c8d4a53050/_apis/pipelines/1/runs/516951/signedlogcontent/2?urlExpires=2022-12-27T15%3A16%3A51.6273274Z&urlSigningMethod=HMACV1&urlSignature=TbBzR7W6XLMr%2BgK2z1%2FS1sGS1PhOD1jBh8URHdH%2F0rs%3D)

**Comment by Chaitanya134** [comment]
Hey @DragosStoican,
Can you help me with this error
```
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('uint16') with casting rule 'same_kind'
E       Falsifying example: test_numpy_instance_itruediv__(
E           dtype_and_x=(['uint16', 'uint16'],
E            [array(0, dtype=uint16), array(0, dtype=uint16)]),
E           as_variable=[False],
E           native_array=[False],
E           init_num_positional_args=0,
E           method_num_positional_args=1,
E           frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.numpy' from '/ivy/ivy/functional/frontends/numpy/__init__.py'>, framework_init_module=<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>, init_name='array', method_name='__itruediv__'),
E           frontend='numpy',
E       )
```

One possible solution I found was to replace 
```
available_dtypes=helpers.get_dtypes("numeric"),
```

with 
```
available_dtypes=helpers.get_dtypes("float"),
```

But it doesn't seem like a good approach

**Comment by Chaitanya134** [comment]
I think that this error could be because of the handle_numpy_casting decorator. It has casting="same kind" by default. How can I change it and with what value should I change it?

**Comment by DragosStoican** [comment]
Hi @Chaitanya134 , the best place to ask for advice would be the discord channel. There's a higher chance someone has ran into a similar issue and they can provide you with some tips. You can join the discord [here](https://discord.gg/aptp6w6XkR).

I had a look at the logs and it looks like you're getting a `TypeError` in the test. It looks like this `TypeError: array() got an unexpected keyword argument 'data'`.

However, I looked into the `numpy.mathematical_functions.arithmetic_operations.divide` function you are using in the implementation of __itruediv__ . Unfortunately, the test for this function is failing itself, this could mean that the `divide` function is broken somehow, or that the test for that function is broken. If the function `divide` is not working correctly we cannot expect __itruediv__ to work either, even if you fix the other issues I mentioned. 

You could keep working on `__itruediv__`, but you might have to fix `divide` as well. Alternatively you could pick up another task to work on and come back to this when the `divide` function has been fixed by an ivy team member. Ultimately, I cannot merge this PR until the tests for `__itruediv__` are passing.

**Comment by Chaitanya134** [comment]
Oh ok I got it. I actually fixed the ```TypeError```. The error I mentioned is coming after fixing it. I too had a look into the divide function under arithmetic operations. I even tried to reimplement it but it gives me another error while testing the function.
```
ivy.exceptions.IvyBackendException: numpy: as_ivy_dtype: get_dtypes(kind='numeric', full=False, none=True)
E           Falsifying example: test_numpy_true_divide(
E               dtype_and_x=(['int8', 'int8'],
E                [array(0, dtype=int8), array(0, dtype=int8)]),
E               where=[array(False)],
E               as_variable=[False],
E               native_array=[False],
E               num_positional_args=2,
E               with_out=False,
E               frontend='numpy',
E               fn_tree='ivy.functional.frontends.numpy.true_divide',
E               on_device='cpu',
E           )
```

I checked some more functions like test_numpy_add, test_numpy_multiply, etc. in the test_arithmentic_operations file and they all raise this same error.

**Comment by DragosStoican** [comment]
Yeah, it's a common error accross the numpy frontend. You can definitely find out more details if you start a conversation about it on discord.

**Comment by DragosStoican** [comment]
Hi @Chaitanya134, I discussed the issue with the team and I think we can merge your PR as long as the only thing causing the test to fail is the casting error in numpy. We understand it is unfair to ask you to complete another task since this was a task we opened ourselves.

So I think I'd be happy to merge this if you push your fix for the TypeError. Thanks for your contribution!

**Comment by Chaitanya134** [comment]
Thanks for your incredible support @DragosStoican

**Pull request merged**
