### PR TITLE
Std torch frontend

### PR DESCRIPTION
**Pull request by artykov1511**

### CODE REVIEW

**Comment by kurshakuz** [comment]
Hey @artykov1511! Can you please link the original issue to that PR? It is also not clear for me what do you want to implement here. Are you adding std or sqrt functions? The title says std, but you have only added the test for the sqrt function.

**Comment by artykov1511** [comment]
Hey @kurshakuz, I was implementing std, but I guess this task was already given to someone else  before I allocated it.

**Comment by artykov1511** [comment]
Closed #8841

**Comment by artykov1511** [comment]
Hey @kurshakuz, when I committed and pushed from my local branch, all other previous commits from other branches were pushed as well. I dont why this happened. Can you help delete these commits?

**Pull request closed without merging**
