### PR TITLE
amin- Mathematical functions to Numpy Frontend #3808

### PR DESCRIPTION
**Pull request by Saivarunt**

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Here is the docs for this function: https://numpy.org/doc/stable/reference/generated/numpy.matrix.min.html. As you can see your function doesn't have the same signature as `numpy.matrix.min` and doesn't even have the same name (should be `min` not `matrix_min`).

You can also see in test-frontend-numpy that your test is failing which you will need to get passing 🙂

**Comment by Saivarunt** [comment]
Greetings @mattbarrett98! I looked into the things you pointed out and have made a few changes. Kindly take a look and let me know what you think. It would be great if you could help me out with the test functions, since this is my first time handling testing.

**Review by mattbarrett98 — COMMENTED** [review]
This function is a bit unique from most other frontend functions, since it's actually an instance method. We are currently working on adding some examples on how to add instance methods and I will direct you towards these when they are ready 🙂

**Comment by Saivarunt** [comment]
Alright, will put this on hold till then. I'd be glad to help out if needed, let me know if something pops up. 
:)

**Review by mattbarrett98 — COMMENTED** [review]
Thanks for your patience 🙂 You can pick another issue if you like, that is a regular function rather than an instance method.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
