### PR TITLE
added_support_for_Conv2D_with_unit_test 

### PR DESCRIPTION
**Pull request by kaushal07wick**

### CODE REVIEW

**Comment by kaushal07wick** [comment]
@kurshakuz , I have made all the changes from my side, the lint/check formatiing shows error in other files not mine,
kinldy chek once

**Comment by kaushal07wick** [comment]
> @kurshakuz , I have made all the changes from my side, the lint/check formatiing shows error in other files not mine, kinldy chek once

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @kaushal07wick !

Please remove all of the unrelated changes from that PR and only leave the implementations from those files:
`ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py`
`ivy/functional/frontends/tensorflow/raw_ops.py`

Thanks!

**Comment by kaushal07wick** [comment]
sure

**Comment by kaushal07wick** [comment]
i made a new pr, kindly check on that #10529

**Comment by kurshakuz** [comment]
Thanks, closing that PR then

**Pull request closed without merging**
