### PR TITLE
Wrapping up Complex Dtype Checking

### PR DESCRIPTION
**Pull request by soma2000-lang**
Resolves https://trello.com/c/8sO8VMW7 opened by @VedPatwardhan

### CODE REVIEW

**Review by VedPatwardhan — APPROVED** [review]
Hey @soma2000-lang, thanks for making the changes, could you please also comment on the trello card with this PR link about the submodules that are done in this PR? I'll get the PR merged shortly, thanks 🙂

**Comment by soma2000-lang** [comment]
@VedPatwardhan  I have linked  the PR link in the outcome section and written about the submodules tested in the comment section! Thanks!

**Comment by VedPatwardhan** [comment]
Sounds great, feel free to merge the PR. Thanks @soma2000-lang 🙂

**Comment by soma2000-lang** [comment]
@VedPatwardhan I donot have any option to merge this PR

**Comment by VedPatwardhan** [comment]
I'm not sure why you're not able to merge the PR as you've been added to the github organization. Anyway, I'll merge this PR now 🙂

**Pull request merged**
