### PR TITLE
Implemented grid_sample function:

### LINKED ISSUE #21957: grid_sample

### PR DESCRIPTION
**Pull request by JustinValentin954**
- Support for nearest neighbor sampling added.
- Modes include 'nearest' with padding options 'zeros' and 'border'.
- 'bilinear' mode marked as not implemented for future work.

Close #21957.

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by KevinUnadkat** [comment]
hy @JustinValentin954 
can pls add issue link to this pr

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
