### PR TITLE
Reformatted the random.randint function

### PR DESCRIPTION
**Pull request by Ahmed-Yahia-cs**
- [ ]  #1061

- Reformatted the random.randint function docstring to inherit the NumPy style.
- Reformatted the randint function docstring for the backends:[numpy, jax, tensorflow, torch] to inherit the NumPy style.
- Reformatted the lambda expression used on the numpy backend.

### CODE REVIEW

**Review by 1Doomdie1 — COMMENTED** [review]
LGTM!
I'll have Dan confirm this before merging!

**Review by djl11 — COMMENTED** [review]
Thanks for making the changes, I've just requested a review from @saeedashrraf :)

**Review by djl11 — CHANGES_REQUESTED** [review]
Looks great! Very last thing, could you please add a few more examples to the docstring? We recently updated the instructions, which can be found both in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) and on this [YouTube video](https://www.youtube.com/watch?v=fTifKx8GJrg&list=PLwNuX3xB_tv9A9fVtIqgh2mH6ZPxJ2eB6&index=2). Once the new examples are added, I'll go ahead and get it merged! Thanks!

**Comment by Ahmed-Yahia-cs** [comment]
the randint function can't be called from an instance and its arguments have only a few variances so I was able to add only a few examples.

**Review by djl11 — CHANGES_REQUESTED** [review]
lgtm! Could you just remove the changes to `.idea` and I'll get it merged, thanks! :)

**Comment by saeedashrraf** [comment]
Hello @Ahmed-Yahia-cs , thank you for your effort!

**Pull request merged**
