### PR TITLE
torch frontend cos_ method

### LINKED ISSUE #6068: cos_

### PR DESCRIPTION
**Pull request by lovesahaj**
Close #6068

### CODE REVIEW

**Comment by lovesahaj** [comment]
@Daniel4078 torch frontend test only fails when testing on the 'bfloat16' type arguments, that's because numpy doesn't support that

**Comment by Daniel4078** [comment]
> @Daniel4078 torch frontend test only fails when testing on the 'bfloat16' type arguments, that's because numpy doesn't support that

Then please check out this deep dive document (https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html#supported-data-types-and-devices) about what to do in this case and maybe update your test to skip this unsupported datatype. Thank you!

**Comment by lovesahaj** [comment]
I did that already, `cos_` doesn't fail any test cases.

**Review by Daniel4078 — APPROVED** [review]
Well done! I think it is all fine now. Thank you!

**Pull request merged**
