### PR TITLE
Add torch norm frontend.

### PR DESCRIPTION
**Pull request by Chandu-4444**
#11936

### CODE REVIEW

**Comment by Chandu-4444** [comment]
@fspyridakos  I've created a new PR on this.

**Comment by vayuusaee** [comment]
in analysising the code in flask8

E501 - Line too long: This error occurs when a line of code exceeds the maximum line length specified in the configuration file. You can fix this by breaking up the line into multiple lines or adjusting the maximum line length in your configuration file.

E302 - Expected 2 blank lines, found 1: This error occurs when there is only one blank line between two blocks of code, and two blank lines are expected. To fix this error, simply add another blank line.

E231 - Missing whitespace after ',': This error occurs when there is no whitespace after a comma in a list or tuple. To fix this, add a space after the comma.

E261 - At least two spaces before inline comment: This error occurs when an inline comment is not preceded by at least two spaces. To fix this error, add the necessary spaces before the inline comment.

E402 - Module level import not at top of file: This error occurs when an import statement is not at the top of the file. To fix this error, move the import statement to the top of the file.

**Comment by zhumakhan** [comment]
Hi, thanks for your contribution!
Too many tests seem to fail, though your changes did not touch most of them.
Could you please try making one more commit to re-run the tests?

**Comment by zhumakhan** [comment]
Hi again, could you resolve the conflicts?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Chandu-4444** [comment]
@zhumakhan I resolved the conflicts.

**Comment by zhumakhan** [comment]
Still a lot of test fails, they should be passing

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
