### PR TITLE
Ivy.<func name> mm

### PR DESCRIPTION
**Pull request by program-20**
name: test-experimental-core-ivy
on:
  workflow_dispatch:
  push:
    pull_request:
      types: [labeled, opened, synchronize, reopened, review_requested]
permissions:
  actions: read
jobs:
  run-nightly-tests:
    if: ${{(github.event_name == 'push') || contains(github.event.pull_request.labels..name, 'Exhaustive CI') || contains(github.event.pull_request.labels..name, 'Ivy API Experimental')}}
    strategy:
      matrix:
        backends: [ numpy, torch, jax, tensorflow ]
        submodules: [ creation, device, dtype, elementwise, general, gradients, linalg, manipulation, meta, nest, random, searching, set, sorting, sparse_array, statistical, utility ]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2

      - name: Check Files Changed
        shell: pwsh
        id: check_file_changed
        run: |
          cd ivy
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { `
            $_ -match 'ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_${{ matrix.submodules }}.py' `
          }
          $HasDiff = $SourceDiff.Length -gt 0
          Write-Host "::set-output name=changed::$HasDiff"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        if: github.event_name == 'pull_request' && steps.check_file_changed.outputs.changed == 'True'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: test-ivy-experimental.yml
          workflow_conclusion: ""
          search_artifacts: true
          name: hypothesis_${{ matrix.backends }}_test_experimental_zip
          path: |
            ivy/.hypothesis/
        continue-on-error: true

      - name: Unzip Hypothesis Examples
        id: unzip
        if: github.event_name == 'pull_request'
        run: |
          cd ivy/.hypothesis
          unzip examples.zip
          rm examples.zip
        continue-on-error: true

      - name: Create Hypothesis Directory
        if: github.event_name == 'pull_request' && steps.check_file_changed.outputs.changed == 'True'
        run: |
          cd ivy
          mkdir -p .hypothesis
          cd .hypothesis
          mkdir -p examples
        continue-on-error: true

      - name: Run Experimental Test
        if: steps.check_file_changed.outputs.changed == 'True'
        id: tests
        run: |
          cd ivy
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          ./run_tests_CLI/test_experimental_core.sh ${{ matrix.backends }} test_${{ matrix.submodules }} ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD}}
        continue-on-error: true

      - name: Zip Hypothesis Examples
        if: github.event_name == 'pull_request' && steps.check_file_changed.outputs.changed == 'True'
        run: |

### CODE REVIEW

**Comment by program-20** [comment]
fixing the error in the YAML syntax on line 20, you need to properly indent the runs-on: ubuntu-latest line.

**Comment by program-20** [comment]
name: test-experimental-core-ivy
on:
  workflow_dispatch:
  push:
    pull_request:
      types: [labeled, opened, synchronize, reopened, review_requested]
permissions:
  actions: read
jobs:
  run-nightly-tests:
    if: ${{(github.event_name == 'push') || contains(github.event.pull_request.labels..name, 'Exhaustive CI') || contains(github.event.pull_request.labels..name, 'Ivy API Experimental')}}
    strategy:
      matrix:
        backends: [ numpy, torch, jax, tensorflow ]
        submodules: [ creation, device, dtype, elementwise, general, gradients, linalg, manipulation, meta, nest, random, searching, set, sorting, sparse_array, statistical, utility ]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2

      - name: Check Files Changed
        shell: pwsh
        id: check_file_changed
        run: |
          cd ivy
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { `
            $_ -match 'ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_${{ matrix.submodules }}.py' `
          }
          $HasDiff = $SourceDiff.Length -gt 0
          Write-Host "::set-output name=changed::$HasDiff"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        if: github.event_name == 'pull_request' && steps.check_file_changed.outputs.changed == 'True'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: test-ivy-experimental.yml
          workflow_conclusion: ""
          search_artifacts: true
          name: hypothesis_${{ matrix.backends }}_test_experimental_zip
          path: |
            ivy/.hypothesis/
        continue-on-error: true

      - name: Unzip Hypothesis Examples
        id: unzip
        if: github.event_name == 'pull_request'
        run: |
          cd ivy/.hypothesis
          unzip examples.zip
          rm examples.zip
        continue-on-error: true

      - name: Create Hypothesis Directory
        if: github.event_name == 'pull_request' && steps.check_file_changed.outputs.changed == 'True'
        run: |
          cd ivy
          mkdir -p .hypothesis
          cd .hypothesis
          mkdir -p examples
        continue-on-error: true

      - name: Run Experimental Test
        if: steps.check_file_changed.outputs.changed == 'True'
        id: tests
        run: |
          cd ivy
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          ./run_tests_CLI/test_experimental_core.sh ${{ matrix.backends }} test_${{ matrix.submodules }} ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD}}
        continue-on-error: true

      - name: Zip Hypothesis Examples
        if: github.event_name == 'pull_request' && steps.check_file_changed.outputs.changed == 'True'
        run: |
          cd ivy/.hypothesis
          zip -r examples.zip examples

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by KareemMAX** [comment]
Hi @program-20,

Thanks for the PR!

However, looking more closely, it’s unclear how this PR would meaningfully contribute towards the project, because I can't find out what are you trying to do.

Therefore, I’ve simply closed it for now 🙂

Please feel free to submit other PRs based on our [Open Tasks](https://lets-unify.ai/ivy/overview/contributing/open_tasks.html).

Thanks!

**Pull request closed without merging**
