### PR TITLE
bitwise_or

### LINKED ISSUE #9848: bitwise_or
Pytorch Frontend

### PR DESCRIPTION
**Pull request by ahmedqazi123**
Close #9848

### CODE REVIEW

**Comment by ahmedqazi123** [comment]
Not sure why it's failing the lint and run_tests_1 tests. I did install and use the pre commit hook.

**Comment by ahmedqazi123** [comment]
Can someone tell me why exactly is this test not passing?

**Comment by vaatsalya123** [comment]
@ahmedqazi123 Hey sorry for the late response to the Pr , Regarding the failing lint test it seems to be fixed now is passing.Though you said you have failing test does that mean your implementation is falling tests or were you just referencing the lint failure?

**Comment by ahmedqazi123** [comment]
I was just referring to the PR test failure

**Comment by ahmedqazi123** [comment]
@vaatsalya123 currently it's only failing the "check on failures" test from the run nightly tests pytorch frontend. Again I'm not sure why it's doing that.

**Comment by vaatsalya123** [comment]
that's alright no worries for that , rest of the implementation lgtm!

**Pull request merged**
