### PR TITLE
unique_all implementation

### PR DESCRIPTION
**Pull request by Maria-98-ui**
This is the full code, but do let me know if I need to add or delete anything.

### CODE REVIEW

**Comment by MahmoudAshraf97** [comment]
Hi and thanks for the contribution, the output is missing some required values, please check the other backends implementations for reference, also dont forget to use hypothesis tests to verify your code using
`pytest -B paddle ivy_tests/test_ivy/test_functional/test_core/test_set.py::test_unique_all`

**Comment by Maria-98-ui** [comment]
Okay, got it. Thanks.

**Comment by Maria-98-ui** [comment]
I made the required changes, please check. And I have an issue while performing hypothesis test for unique_all. I am getting an error of directory not found and such. I did some debugging but still its not resolving. would you suggest anything? Thanks!

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hi @Maria-98-ui , the tests run fine locally and this is the result
`AssertionError: The length of results from backend paddle and ground truth framework torch does not match`
please let me know which error are you facing with the tests, are you sure you are in ivy directory?

**Comment by Maria-98-ui** [comment]
Yes I am running the test in ivy directory.. the error specifies that my ivy test path directory is not found. I will keep trying to debug it. And as for the results you got on your side, I will see to it too.

**Comment by MahmoudAshraf97** [comment]
that means you're in `ivy/ivy` directory, go up one folder and run the tests there

**Comment by MahmoudAshraf97** [comment]
then navigate to the directory yourself and run `pytest -B paddle test_set.py::test_unique_all`

**Comment by Maria-98-ui** [comment]
@MahmoudAshraf97 after much debugging the error of no directory is gone. Although as i am running the test, this error occurs 

> E       hypothesis.errors.InvalidArgument: Missing required kwargs: 'backend_fw', 'on_device'  

which I believe corresponds to the handle_test decorator. What do you suggest?

**Comment by MahmoudAshraf97** [comment]
@Maria-98-ui , I can run the test with no problems, I use this command

```
pytest -B paddle ivy_tests/test_ivy/test_functional/test_core/test_set.py::test_unique_all

E       AssertionError: The length of results from backend paddle and ground truth framework torch does not match
E
E       len(ret_np_flat) != len(ret_np_from_gt_flat):
E
E       ret_np_flat:
E
E       [array([-1.], dtype=float32), array([1]), array([], shape=(0, 1), dtype=int64)]
E
E       ret_np_from_gt_flat:
E
E       [array([-1.], dtype=float32), array([0]), array([0]), array([1])]

ivy_tests/test_ivy/helpers/assertions.py:107: AssertionError
=============================================== short test summary info ================================================
FAILED ivy_tests/test_ivy/test_functional/test_core/test_set.py::test_unique_all[cpu-ivy.functional.backends.paddle-False-False] - AssertionError: The length of results from backend paddle and ground truth framework torch does not match
```

**Comment by Maria-98-ui** [comment]
@MahmoudAshraf97 I have changed the code as requested.. can you check if the test error still persists ?

> AssertionError: The length of results from backend paddle and ground truth framework torch does not match 

I cant run the test on my end, I am getting system memory issue when i try to test run..

**Review by MahmoudAshraf97 — APPROVED** [review]
I used paddle.unique function to ease the implementation, and since it doesn't support nan, I added some logic to match ivy.unique behavior, the function is now passing the tests

**Comment by Maria-98-ui** [comment]
@MahmoudAshraf97 Okay much thanks for the help!

**Pull request merged**
