### PR TITLE
Add Random sampling pareto to Numpy Frontend

### LINKED ISSUE #21170: pareto

### PR DESCRIPTION
**Pull request by Ellenella**
Implement the numpy.random.pareto function with a test function to the Numpy Frontend 
Close #21170 

The numpy.random.pareto function generates a random sample from the Pareto distribution. The Pareto distribution is a continuous distribution that is often used to model the distribution of wealth or income.

The test function tests the numpy.random.pareto function by generating a random sample from the distribution and comparing the results to the theoretical distribution.

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by Ishticode — COMMENTED** [review]
Hi @Ellenella 
Thank you for the PR and the comment. The reason for delay is the PR not being linked to an issue as pointed out by the comment by ivy-leaves above. Your tests are seems fine. So its almost ready to merge when you get yourself assigned using the details above. Let me know if something is unclear. Thank you 😄

**Comment by Ishticode** [comment]
needs to say "close #21170" in the first comment to get the issue linked.

**Comment by Ellenella** [comment]
I have revised the ToDo list issues guidelines. Thank you for pointing out that was the issue. I appreciate your guidance. Based on that, I believe the pull request is ready to be merged now. Thank you!

**Review by Ishticode — APPROVED** [review]
Great @Ellenella 
Merging now.
Thank you for you contribution 😀

**Pull request merged**
