### PR TITLE
close #17587

### LINKED ISSUE #17587: remainder

### PR DESCRIPTION
**Pull request by Vishal3639**
close #17587

### CODE REVIEW

**Comment by Vishal3639** [comment]
@Aarsh2001 @zaeemansari70 
Dear Aarsh and Zaeem, Could you please review my PR, let me know how to fix this issue? Thank you.

**Review by Aarsh2001 — CHANGES_REQUESTED** [review]
Kindly revert the `.idea` file changes, thanks

**Comment by Vishal3639** [comment]
.idea file changes reverted, kindly review my PR. Thanks.

**Review by Aarsh2001 — COMMENTED** [review]
Let's wait for the tests to pass !

**Comment by Aarsh2001** [comment]
Can you please fix the conflicts, thanks 🙂

**Review by Aarsh2001 — COMMENTED** [review]
Let's wait for the tests to pass

**Review by Aarsh2001 — APPROVED** [review]

**Comment by Aarsh2001** [comment]
The tests are failing for `torch` and `tensorflow`, can you please look into that ?

**Review by Aarsh2001 — CHANGES_REQUESTED** [review]
Tests failing for `torch` and `tensorflow`

**Comment by Vishal3639** [comment]
Hello Aarsh, 
I have resolved the conflicts.
Kindly help me to solve the test, i am not getting how to resolve.

**Pull request merged**
