### PR TITLE
Added is_meta to torch frontends tensor 

### LINKED ISSUE #19590: is_meta

### PR DESCRIPTION
**Pull request by tejeshbhalla**
Close #19590

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by tejeshbhalla** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗



> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

Done

**Comment by tejeshbhalla** [comment]
hey @sagewhocodes kindly review and suggest the changes

**Comment by tejeshbhalla** [comment]
@sagewhocodes  review this

**Comment by tejeshbhalla** [comment]
@ivy-leaves  check it plz

**Comment by sagewhocodes** [comment]
LGTM!

**Pull request merged**
