### PR TITLE
Reformating and docstring examples of tanh() in activations.py #1574 

### PR DESCRIPTION
**Pull request by owaisorakzai**

### CODE REVIEW

**Comment by owaisorakzai** [comment]
Heyy... Can you please review my pull request
Thanks

**Comment by ishishruti** [comment]
Please mention the issue this is resolving.

**Comment by owaisorakzai** [comment]
#1574 
Link: https://github.com/unifyai/ivy/issues/1574

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Could you resolve merge conflicts? Otherwise, everything else looks good!

**Comment by owaisorakzai** [comment]
Heyyy... I have made changes... This branch does not have any conflicts now

**Comment by owaisorakzai** [comment]
Hello... Any update on my PR request?

**Review by MarShaikh — CHANGES_REQUESTED** [review]
I noticed you removed a number of functions. Why is that so?

**Comment by owaisorakzai** [comment]
I haven't removed any functions..There were some conflicts in activations.py file...so what I did was that i copied updated file from ivy base repository and paste all contents of it in my repo

**Review by MarShaikh — CHANGES_REQUESTED** [review]
So sorry but it becomes quite difficult to review this PR as you copy pasted to resolve merge conflicts which can cause problems if I merge this PR. Your examples look good though. I would highly recommend that you create another PR but resolve any merge conflicts properly! Will be closing this for now. If you think, you can fix the issues in the PR, let me know, I will reopen it. Thanks!

**Review by DevanteCaprice — COMMENTED** [review]
I believe there may have been an error somewhere

**Pull request closed without merging**
