### PR TITLE
Added selu activation function to tensorflow and torch

### PR DESCRIPTION
**Pull request by youssef893**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by kurshakuz — CHANGES_REQUESTED** [review]
There seems to be too much unncessary changes. Please make sure that you branch is in sync with master. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Your implementation does not contain selu activation function. Please add it and let me know once you are done. Thanks!

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
