### PR TITLE
#25679-nansum_torch_frontend

### LINKED ISSUE #25679: nansum

### PR DESCRIPTION
**Pull request by OriginCoding**
feat: nansum method added in pytorch frontend

Close #25679 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by NripeshN** [comment]
Hi @OriginCoding,
Please resolve the merge conflicts

**Comment by OriginCoding** [comment]
@NripeshN it has been resolved you can merge this now 
Thanks a lot

**Review by OriginCoding — COMMENTED** [review]
changes

**Comment by OriginCoding** [comment]
@NripeshN you can merge this now 
thanks

**Review by NripeshN — APPROVED** [review]

**Comment by NripeshN** [comment]
LGTM!!

**Pull request merged**
