### PR TITLE
feat: add cpu function

### LINKED ISSUE #21086: cpu

### PR DESCRIPTION
**Pull request by Prajyot70**
close #21086

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Hi Thank you for your effort, since this is a frontend function, you need to implement it in the frontend folder and add the related tests, to do that you need to read the documentation or check other examples, 

The related docs:  
https://unify.ai/docs/ivy/overview/contributing.html
https://unify.ai/docs/ivy/overview/contributing.html

**Comment by Prajyot70** [comment]
> Hi Thank you for your effort, since this is a frontend function, you need to implement it in the frontend folder and add the related tests, to do that you need to read the documentation or check other examples, 
> 
> The related docs:  
> https://unify.ai/docs/ivy/overview/contributing.html
> https://unify.ai/docs/ivy/overview/contributing.html
> 

Hello,
Thank you for your review!
I have made the required changes as stated by you. please have a look at them and if there are any mistakes or corrections needed please let me know.
Thank You!

**Review by a0m0rajab — COMMENTED** [review]
Thanks for adding the tests, but can you check the implementation of the function again? the location is not correct and you need to follow the examples in the guide it will direct you.

**Comment by Prajyot70** [comment]
> Thanks for adding the tests, but can you check the implementation of the function again? the location is not correct and you need to follow the examples in the guide it will direct you. 

Hello,
Thank you for your review!
I figured out the correct location for both the function and the test this time but when i try to make changes in the place it shows the following error, even though I'm trying to make changes in my forked repository.
 **_There was a error commiting your changes: A file with the same name already exists. Please choose a different name and try again._**
If i change the name then the location gets changed automatically. Do you have any potential suggestions for this issue.
Thank You!

**Comment by JPGoodale** [comment]
Hi @Prajyot70 I believe that this function should be added to the `tensor` file in the torch frontend and the test to the corresponding `test_tensor` one. Also the `@to_ivy_arrays_and_back` decorator is currently at the top of the file rather than just above the function which it is decorating and you still have a call of your function and print statement of its result at the bottom of the file which should be removed before pushing.

**Comment by Prajyot70** [comment]
> Hi @Prajyot70 I believe that this function should be added to the `tensor` file in the torch frontend and the test to the corresponding `test_tensor` one. Also the `@to_ivy_arrays_and_back` decorator is currently at the top of the file rather than just above the function which it is decorating and you still have a call of your function and print statement of its result at the bottom of the file which should be removed before pushing.

Hello,
Thank you for your review and suggestions it helped a lot!
I have made the required changes as stated by you. please have a look at them 
Thank You!

**Comment by JPGoodale** [comment]
Hi @Prajyot70, glad I could help. It looks like the `to_cpu` method which you are trying to call has yet to have been implemented, maybe try using `ivy.to_device`. Also there a few spelling issues and missing fields in your test function, please take a look at these as they will of course cause your tests to fail even if the function itself is correct.

**Comment by Prajyot70** [comment]
> Hi @Prajyot70, glad I could help. It looks like the `to_cpu` method which you are trying to call has yet to have been implemented, maybe try using `ivy.to_device`. Also there a few spelling issues and missing fields in your test function, please take a look at these as they will of course cause your tests to fail even if the function itself is correct. 

Hello,
I've made the following changes in the pull request,

- > Changed method from 'to_cpu' to 'ivy.to_device'
- > Made changes in test according to function
- > Corrected the spelling issues and missing feilds in the tests

Please have a look at them and let me know your insights.
Thank You!

**Comment by Prajyot70** [comment]
> > Hi @Prajyot70, glad I could help. It looks like the `to_cpu` method which you are trying to call has yet to have been implemented, maybe try using `ivy.to_device`. Also there a few spelling issues and missing fields in your test function, please take a look at these as they will of course cause your tests to fail even if the function itself is correct. 
> 
> Hello,
> I've made the following changes in the pull request,
> 
> -  Changed method from 'to_cpu' to 'ivy.to_device'
> -  Made changes in test according to function
> -  Corrected the spelling issues and missing feilds in the tests
> 
> Please have a look at them and let me know your insights.
> Thank You!

Hello @JPGoodale ,
This is just a kind reminder to bring your attention to the quoted message which explains the changes made in the PR according to your suggestions and ivy's contribution guidelines.
Please have a look at it and let me know your insights.
Thank You!

**Comment by NripeshN** [comment]
Hey @Prajyot70,
Could you please solve the merge conflicts.

**Comment by Prajyot70** [comment]
Hello @NripeshN ,
I've done everything possible on my end regarding the function and tests, still 2 tests are failing. Can you please review the function and tests and let me know your insights.
Thank You!

**Comment by Prajyot70** [comment]
Hello @NripeshN ,
At last only one test was failing, that is because of the inappropriate PR title. Now i have updated the PR title as specified by conventional commits organization.
Please have a look.
Thank You!

**Comment by Prajyot70** [comment]
Hello @NripeshN ,
This is a kind reminder to please review the PR. Github actions bot has commented as checks passed.
Thank You!

**Comment by Sarvesh-Kesharwani** [comment]
Hi @Prajyot70
Please work on the changes suggested and let me know afterwords.
Thanks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Sarvesh-Kesharwani — CHANGES_REQUESTED** [review]

**Comment by Prajyot70** [comment]
Hello @Sarvesh-Kesharwani ,
Thank you for your review & apologies for the delay.
I'll work on the changes and will inform you soon.
Thank You !

**Comment by Ishticode** [comment]
I am closing this as there are many issues still there pointed out by @a0m0rajab @JPGoodale @Sarvesh-Kesharwani above. The requested changes are not made, the implementation has a different name the torch method and the tests are chosen to be implemented differently than other examples. Please follow our [Contributing page](https://unify.ai/docs/ivy/overview/contributing.html) for further details. Thanks for the efforts all

**Pull request closed without merging**
