### PR TITLE
tf.linalg.diag func frontend add

### PR DESCRIPTION
**Pull request by Sindhuinti**

### CODE REVIEW

**Comment by Sindhuinti** [comment]
Close #11750

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by hirwa-nshuti** [comment]
Hey @Sindhuinti 
There have been major updates in the repository which made your changes conflict with the current repository status.
Would you copy the changes from this PR and open a new one adding them there😊

Feel free to ask for help if you need any🙂

**Comment by Sindhuinti** [comment]
Ok i will work on new PR @hirwa-nshuti

**Pull request closed without merging**
