### PR TITLE
Reformatting Eigvalsh

### PR DESCRIPTION
**Pull request by Damjan-Dimovski**
Implemented Docstrings and Docstring Examples where needed
Implemented static and instance method for eigvalsh in ivy/container/linear_algebra.py

### CODE REVIEW

**Comment by Aarsh2001** [comment]
Hi @Damjan-Dimovski; please add the formatting checklist in the PR. Here is the link to the [guide](https://lets-unify.ai/ivy/contributing/open_tasks.html#formatting-checklistl) for doing so, thanks🙂

**Comment by Damjan-Dimovski** [comment]
add_reformatting_checklist_linear_algebra

**Comment by Damjan-Dimovski** [comment]
Hi @Aarsh2001, sorry about that, I forgot to add the checklist. I think everything should be fine now, can you review my commits when you have the time?

**Review by Aarsh2001 — APPROVED** [review]
LGTM

**Pull request merged**
