### PR TITLE
Bitwise left shift

### PR DESCRIPTION
**Pull request by sreegandh804**
Please review my PR and let me know if there is an issue with my code(i have written the code for the bitwise_left_shift function)

### CODE REVIEW

**Comment by sreegandh804** [comment]
I will work on fixing the failed test cases, any suggestions/ advice  would be helpful.
image

**Comment by Ishticode** [comment]
were your tests passing locally?

**Comment by sreegandh804** [comment]
No they were not I only had 1/5 test passing in the PyTorch framework, so I am looking at how to deal with .__lshift__, .__ilshift__ functions. Is there anything that you would advise me to do?

**Comment by Ishticode** [comment]
> No they were not I only had 1/5 test passing in the PyTorch framework, so I am looking at how to deal with .**lshift**, .**ilshift** functions. Is there anything that you would advise me to do? But at the same time, some of the closed issues were failing locally too, so I am not sure if it's still my function's fault.

Hi @sreegandh804 I will have a look soon : )

**Pull request closed without merging**
