### PR TITLE
added backend_fw and backend_to_test to relevant torch frontend test

### PR DESCRIPTION
**Pull request by mosesdaudu001**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by mosesdaudu001** [comment]
Pls do not merge yet. There are conflicts that i need to resolve. I think someone just added new tests to tensorflow frontend

**Comment by mosesdaudu001** [comment]
all conflicts have been fixed.

I noticed that test_jax_cos was duplicated as can be seen in:

[https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_mathematical_functions.py#L3234](url)

The pre-commit package did not allow any commit due to the duplicate, so I had to remove the duplicate

**Review by sherry30 — APPROVED** [review]
lgtm!

**Pull request closed without merging**
