### PR TITLE
Vayuusaee patch 1

### PR DESCRIPTION
**Pull request by vayuusaee**

### CODE REVIEW

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @vayuusaee
Thanks for contributing to ivy😊
It seems like your changes involves your newly introduced shell file.
Which is not being reflected on this PR.
Also would you try to explain in details what type of problem your PR is fixing.

Thanks

**Comment by vayuusaee** [comment]
the above line we have modified the postCreateCommand property to execute a shell script located

**Comment by hirwa-nshuti** [comment]
> the above line we have modified the postCreateCommand property to execute a shell script located

Would you tell the reason why you need to create another script if there was an issue that you might be facing?

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
