### PR TITLE
feat: Added ifftshift function to JAX frontend

### LINKED ISSUE #26672: ifftshift

### PR DESCRIPTION
**Pull request by zerodoxxx**
# PR Description
Added ifftshift fft function to JAX frontend and added tests for it

## Related Issue
Close #26672

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by zerodoxxx** [comment]
Hi @Infrared1029 can you please have a look at the PR?

**Comment by zerodoxxx** [comment]
@Infrared1029 can you please review my PR, my upwork contract ends in the first week of November.

**Comment by Ishticode** [comment]
waiting on ci

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @zerodoxxx 
Thanks for the PR. The CI seem to have caught some failures for test_jax_ifftshift. Could you please check out the logs at https://github.com/unifyai/ivy/actions/runs/8129770869/job/22217299881?pr=26673 and see if you can fix the issues and request and review when done. Thanks :)

**Comment by Ishticode** [comment]
Closing this due to inactivity. Please feel free to reopen if you would like to continue working on this. Thanks :)

**Pull request closed without merging**
