### PR TITLE
Add fliplr frontends.torch

### PR DESCRIPTION
**Pull request by PatternFinder**
link to issue: #2714

### CODE REVIEW

**Comment by johanjino** [comment]
Hi, it would be great if you could fix the conflicts. Thank you!

**Comment by johanjino** [comment]
I think the `roll` function got added recently. Just make sure that this is still present along with your function `fliplr` 😀

**Comment by PatternFinder** [comment]
merge conflict resolved

**Comment by johanjino** [comment]
Thank you @PatternFinder for your contribution 😄.

The PR looks good to me and will be merged soon!

**Review by johanjino — APPROVED** [review]

**Pull request merged**
