### PR TITLE
fftshift, tanh

### LINKED ISSUE #14727: fftshift

### PR DESCRIPTION
**Pull request by roudik**
Close #14727 and #14660

### CODE REVIEW

**Comment by theRealBird** [comment]
Hi @roudik,
Thank you for your contribution. Could you please explain what changes have you made to the ```tanh``` function?

**Comment by roudik** [comment]
Hey,I have not made any changes, just retyped the function because the issue was mine and was marked as undone. You can disregard that issue, my main task was to implement fftshift, which I have done. Sincerely, Rudik Grigoryan
-------- Original message --------From: theRealBird ***@***.***> Date: 08/05/2023  07:47  (GMT+04:00) To: unifyai/ivy ***@***.***> Cc: roudik ***@***.***>, Mention ***@***.***> Subject: Re: [unifyai/ivy] fftshift, tanh (PR #14803) 
Hi @roudik,
Thank you for your contribution. Could you please explain what changes have you made to the tanh function?

**Comment by roudik** [comment]
Dear @theRealBird, I have added another commit removing tanh changes.
Sincerely,
Rudik Grigoryan

**Comment by theRealBird** [comment]
Hi @roudik,
This should be the last change which I request. There are some merge conflicts in the PR. The simplest way to get rid of them without cherry-picking would be to add your new ```fftshift``` changes at the end of the ```ivy/functional/frontends/numpy/fft/discrete_fourier_transform.py``` and ```ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py``` files in a new commit, but feel free to resolve them in any way you see fit.

Thank you!

**Comment by roudik** [comment]
Dear @theRealBird,
Could you check if it merges properly now?
Sincerely,
Rudik Grigoryan

**Comment by theRealBird** [comment]
Thank you for your contribution!

**Pull request merged**
