### PR TITLE
Fix raw_ops.test_tensorflow_AddN

### PR DESCRIPTION
**Pull request by mohamedehab0999**

### CODE REVIEW

**Comment by mohamedehab0999** [comment]
Closes #9079

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by mohamedehab0999** [comment]
reopen

**Pull request closed without merging**
