### PR TITLE
max_pool3d

### LINKED ISSUE #19144: max_pool3d

### PR DESCRIPTION
**Pull request by Sar-thak-3**
Closes #19144

### CODE REVIEW

**Comment by Sar-thak-3** [comment]
Hi @zhumakhan this PR is for the paddle max_pool3d frontend function, Kindly review it and let me know the changes required!
* All the test cases are passing locally

**Comment by zhumakhan** [comment]
Hey, thanks for your PR!
Test is failing for jax backend, could you please have a closer look into that:
```
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_pooling.py::test_paddle_max_pool3d[cpu-ivy.functional.backends.jax-False-False] - AssertionError: returned shape = (1, 1, 1, 2, 1), ground-truth returned shape = (1, 1, 1, 1, 1)
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_pooling.py::test_paddle_max_pool3d[cpu-ivy.functional.backends.paddle-False-False] - ValueError: (InvalidArgument) the output size must be greater than 0. But received: output_size = 0 due to the settings of input_size(1), padding(0,0), k_size(2) and stride(1). Please check again!
```

**Comment by Sar-thak-3** [comment]
Hi @zhumakhan , there were some errors in the backend files of JAX and Paddle I corrected them, you can have a look. I think now the pr is good to go, if any other change is required do let me know!

**Review by zhumakhan — CHANGES_REQUESTED** [review]

**Comment by zhumakhan** [comment]
Also, tests are not passing yet, could you please check them?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
