### PR TITLE
Update ndarray.py

### PR DESCRIPTION
**Pull request by PushpamJha14**
std #16333

### CODE REVIEW

**Comment by PushpamJha14** [comment]
pull request for issue - std #16333

**Comment by PushpamJha14** [comment]
#16333

**Comment by PushpamJha14** [comment]
fix #16333

**Comment by theRealBird** [comment]
Hi @PushpamJha14, 
Thank you for your contribution to Ivy. It seems you have missed out on the corresponding test for the function you have implemented. Is this PR a work in progress?

**Pull request closed without merging**
