### PR TITLE
Update raw_ops.py adding Nextafter

### LINKED ISSUE #21331: NextAfter

### PR DESCRIPTION
**Pull request by Lancelot03**
close #21331

### CODE REVIEW

**Comment by Lancelot03** [comment]
#21331

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by a0m0rajab** [comment]
Thank you for that, can you add `close #Issue_number` in the body of the PR to automatically close the related issue? 
Here is the [related GitHub docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by Lancelot03** [comment]
close #21331

**Comment by a0m0rajab** [comment]
Thanks for the comment, but can you add the close comment to the body of the PR? you can edit this by clicking on the three dots on top of the PR.

**Comment by a0m0rajab** [comment]
Thank you for adding the close tag to the body, just for extra information, doing this connected this PR to the issue, and you can find it in the sidebar: 
image

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Lancelot03** [comment]
.

**Pull request closed without merging**
