### PR TITLE
Updated the nanvar numpy frontend code by shortening it

### PR DESCRIPTION
**Pull request by danushkhanna**
I have shortened and updated the nanvar numpy frontend code.

My version of the nanvar numpy frontend code eliminates the duplicate code and simplifies the logic, while still preserving the same functionality.

### CODE REVIEW

**Comment by danushkhanna** [comment]
Screenshot 2023-05-09 at 7 28 06 PM

I've passed all the test cases locally. The only test failing here is of the pre-commit. 

@AnnaTz Please check, thank you.

**Comment by AnnaTz** [comment]
Hi @danushkhanna, the assignee of your PR will review it at their earliest convenience.

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey there! Thanks for your hard work! The changes look good to me but there are failing tests in the CI (run_test_16), please fix them first such that all related tests are passing, thanks!

**Comment by danushkhanna** [comment]
I'll be making a new clean PR since the commit history here is a bit ugly. Thanks for reviewing, I'll be commenting the new PR link soon.

**Pull request closed without merging**
