### PR TITLE
add frontend torch rand function

### LINKED ISSUE #9686: rand

### PR DESCRIPTION
**Pull request by jonnyroutley**
Close #9686

This is a copy of my [last PR](https://github.com/unifyai/ivy/pull/9693) but with the right commits cherry-picked (I managed to do something bad when rebasing). Local tests still passing.

FAO @fspyridakos - thanks again

### CODE REVIEW

**Comment by jonnyroutley** [comment]
hey @nathzi1505 please could you have a look at this when you have the chance? I'm not quite sure why one of the github tests is failing

**Comment by nathzi1505** [comment]
Things look fine to me. @AnnaTz would you mind having a look over them?

**Comment by AnnaTz** [comment]
> hey @nathzi1505 please could you have a look at this when you have the chance? I'm not quite sure why one of the github tests is failing

The failure is not related to your commits. The test of the function you added is passing.

**Comment by AnnaTz** [comment]
> Things look fine to me. @AnnaTz would you mind having a look over them?

Lgtm too!

**Comment by jonnyroutley** [comment]
Thank you both for having a look @nathzi1505 @AnnaTz ! If one of you could merge soon that would be great :)

**Pull request merged**
