### PR TITLE
Reformatting DefaultDevice.__enter__

### PR DESCRIPTION
**Pull request by kimbring2**
For the issue #1362

### CODE REVIEW

**Comment by kimbring2** [comment]
@mattbarrett98 Can you please take a look at this PR for me?

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
`__enter__` is called when a `with` block is used, so perhaps an example using a `with` block and an explanation would be more appropriate here 🙂

**Comment by kimbring2** [comment]
@mattbarrett98 Thank you for reviewing. I modify the code according to your advice +1:

**Review by mattbarrett98 — COMMENTED** [review]
Thanks 🙂

**Comment by kimbring2** [comment]
@mattbarrett98 Thank you for merging. I check we can use 'from typing import Self'. 

I just find it from 'https://peps.python.org/pep-0673/'. However, it seems like it is just a proposal.

I try to use the same class as the return value to the DefaultDtype class. 

`
class DefaultDtype:
    """"""

    # noinspection PyShadowingNames
    def __init__(
            self,
            dtype: Union[ivy.Dtype, ivy.NativeDtype],
    ) -> None:
        self._dtype = dtype

    def __enter__(self) -> DefaultDtype:
        set_default_dtype(self._dtype)
        return self
`

And it gives the error say 'E   NameError: name 'DefaultDtype' is not defined'. Is there any proper way to return the class itself in Python?

Thank you.

**Pull request merged**
