### PR TITLE
Fix Frontend Failing Test: jax, numpy, torch - math.tensorflow.math.reduce_prod

### PR DESCRIPTION
**Pull request by ZJay07**
# PR Description
Test was failing because of small floating point rounding difference and too small/large values causing the results to be `inf` in some frameworks.
Fixed by adding tolerance and min max x values.

## Related Issue

Close https://github.com/unifyai/ivy/issues/28541
Close https://github.com/unifyai/ivy/issues/28540
Close https://github.com/unifyai/ivy/issues/28539

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @ZJay07
Thank you very much for the PR. 
Maybe we should use safety factors instead of specifying min max values

**Comment by ZJay07** [comment]
Oh, what do you mean by a safety factor, do you mind giving me an example?

**Review by Ishticode — COMMENTED** [review]
safety factor ensures values are bounded based on dtype instead of just hardcoded min or max. You can see it used with `test_tensorflow_reduce_std` in the same file.

**Comment by ZJay07** [comment]
Updated with safety factors similar to `reduce_std`. Let me know if this is correct.

**Review by Ishticode — APPROVED** [review]
Thanks @ZJay07 for the fix :)

**Pull request merged**
