### PR TITLE
min #4418

### PR DESCRIPTION
**Pull request by aplatyps**
from issue Reformat statistical #812
reformatted min with docstring added

### CODE REVIEW

**Comment by MrZilinXiao** [comment]
Hi @aplatyps. Thanks for your contribution. But I believe you have some additional modifications besides `min`. Would you mind move unnecessary modifications out of this PR?

**Comment by aplatyps** [comment]
> Hi @aplatyps. Thanks for your contribution. But I believe you have some additional modifications besides `min`. Would you mind moving unnecessary modifications out of this PR?

Hi @MrZilinXiao, thanks for the comment. I've checked again and I'm sure I did not modify anything apart from `min` function in all `statistical.py` files. The diff shown on github is a bit strange because I moved all `min` function to above `max`. Previously some of them are randomly positioned.

**Comment by MrZilinXiao** [comment]
Hi @aplatyps. Yeah, I understand that there are some irrelevant unit test failures. I am just curious about the strange git diff result...
Let me check further why this diff shows you altered some irrelevant parts. Will get back to you soon.

**Comment by aplatyps** [comment]
Hi @MrZilinXiao, because most of the functions in `statistical.py` are very similar, just 1 or 2 lines of difference. This is why if you move an entire code block to a different position it will mess up the diff a little. You may open the file in full view at Files changed > ... > View file then you will understand better.

**Comment by MrZilinXiao** [comment]
Got it. Code LGTM except for the strange diff :)

**Review by MrZilinXiao — APPROVED** [review]
Got it. Code LGTM except for the strange diff :)

**Pull request merged**
