### PR TITLE
Add torch.unique

### LINKED ISSUE #7862: unique

### PR DESCRIPTION
**Pull request by jegork**
Hey, I was trying to implement torch.unique, however, I have stumbled on a couple of issues. 
First of all, it is challenging to implement the `dim` parameter. None of the `ivy.unique_` methods implements the axis/dim parameter, and I couldn't mimic the numpy implementation, as it uses structured arrays. How can I tackle this?

Additionally, I have trouble writing tests. Is there a way that I can cancel some checks? 
E.g. the test fails when the output of original and implemented functions are [0, 1] and [1, 0], however, AFAIK there is no explicit ordering for `torch.unique` when sorted=False, so it is hard (impossible?) to predict/imitate the ordering there.

Thanks!

Closes  #7862

### CODE REVIEW

**Comment by ogbanugot** [comment]
Hi @jegork, good job so far! 
Regarding the issues you raised, first, I would suggest that you leave the `dim` parameter in the function signature but don't test for it for now. Ultimately, that`dim` parameter will be added to the ivy functional API for `unique_` as a `superset` behavior, but until then we can get your PR merged for now and refactor it when the update has been made to the functional API. 

Secondly, there is no way to skip some tests. What you can do is get the returned values and then manually handle the assertion yourself. That way if `sorted=false` you can check that the values are the same irrespective of the order. See an example of manually handling the assertion [here](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_numpy/test_manipulation_routines/test_basic_operations.py#L24).

**Comment by jegork** [comment]
Hey @ogbanugot, thanks for your reply and the provided info! 
I have left the dim parameter unimplemented. 
Additionally, I have fixed how the function works when `sorted=True`. 

Would be great if you could check my tests, cuz they look a bit cumbersome to me, so might require some refactoring. 
I decided to sort both outputs when `sorted=False` and then compare them, which seems to me as the best approach.
Open to any new ideas!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by jegork** [comment]
hello @ogbanugot, do you think it is ready to be merged?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by jegork** [comment]
waiting for a review

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Sorry for the late review, 
Your PR looks good, I've requested a few changes on specific lines.

Other than these, just fix the merge conflicts and your PR will be good to merge if the test passes 😄 

Thanks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by jegork** [comment]
hey @sherry30, thanks for your feedback! 

Should i then use numpy functions and not ivy functions in my test code? i.e. lines 736-755? 
Because if I cast `ret` and `ret_gt` to numpy arrays, then applying `ivy.argsort` to them leads to errors with torch backend (although works perfectly fine with numpy backend) as it expects torch tensors, not numpy arrays

My tests with torch backend fails with 
```
>           raise ivy.exceptions.IvyBackendException(fn.__name__, str(e))
E           ivy.exceptions.IvyBackendException: torch: argsort: sort() received an invalid combination of arguments - got (numpy.ndarray, out=NoneType, stable=bool, descending=bool, dim=int), but expected one of:
E            * (Tensor input, *, bool stable, int dim, bool descending, tuple of Tensors out)
E            * (Tensor input, int dim, bool descending, *, tuple of Tensors out)
E                 didn't match because some of the keywords were incorrect: stable
E            * (Tensor input, *, bool stable, name dim, bool descending, tuple of Tensors out)
E            * (Tensor input, name dim, bool descending, *, tuple of Tensors out)
E                 didn't match because some of the keywords were incorrect: stable
E
```

**Comment by sherry30** [comment]
Hey,

Sorry for the late reply.
You're right, in this case you can set backend to numpy, I think that should work since ivy functions accept native arrays.
Let me know if it doesn't, I'd be happy to help you out.

Thanks

**Comment by jegork** [comment]
Hey @sherry30! thanks for your suggestion, i've implemented what you described

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Everything looks good implementation wise.
Can you fix merge conflicts, I'll merge your PR after that.
1 more thing, in the changed files tab it shows the whole file is changed for some reason 🤔, can you fix that somehow so that it only detects your changes, but its also fine as long as you haven't made any other change in that file.

Thanks

**Pull request closed without merging**
