### PR TITLE
added the threshold activation to ivy experimental api

### LINKED ISSUE #26093: threshold

### PR DESCRIPTION
**Pull request by samthakur587**
# added the threshold activation to ivy experimental api

## implemented the threshold activation function to the all  backend numpy jax torch tensorflow paddle. in the both ivy array and ivy container data classes. the test result.

image

Close #26093

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by KareemMAX** [comment]
Hi @samthakur587 , seems like you have changed `docs/demos` which you might have done by mistake. Can you revert that change because we can't merge with that change in place?

**Comment by samthakur587** [comment]
Hey @KareemMAX I made all the changes that required and you suggested me in my PR softshrink. I hope this PR is now good to merge .

thanks

**Comment by samthakur587** [comment]
Hi! @saeedashrraf  can you please review this is there there any modification required.

**Comment by samthakur587** [comment]
Hi! @KareemMAX @saeedashrraf  can you please check is the any duplicate there or not . bcz it's failing duplicate test 🤔

**Comment by KareemMAX** [comment]
> Hi! @KareemMAX @saeedashrraf can you please check is the any duplicate there or not . bcz it's failing duplicate test 🤔

You are not making a duplicate, no worries

**Comment by samthakur587** [comment]
Hii @KareemMAX @saeedashrraf  waiting for the review.

**Comment by samthakur587** [comment]
hii @KareemMAX @saeedashrraf  still waiting for your review 😞

**Review by KareemMAX — APPROVED** [review]
LGTM! Merging now

**Pull request merged**
