### PR TITLE
add triu creation and test function

### PR DESCRIPTION
**Pull request by maciejbalawejder**
Everything seems to be working fine, all four tests passed.

### CODE REVIEW

**Review by AnnaTz — CHANGES_REQUESTED** [review]
All is good but you need to remove changes in the .idea folder in order to merge your PR.

**Comment by maciejbalawejder** [comment]
Cool, I revert those files to their original form but still it shows that I changed something.

**Comment by AnnaTz** [comment]
> Cool, I revert those files to their original form but still it shows that I changed something.

Yes removing this can be tricky. You could try reverting back to the commit before those changes and then re-pasting the code of your function.

**Comment by AnnaTz** [comment]
Alternatively you could create a new branch and then a new PR to be sure that you don't change the idea folder this time.

**Comment by maciejbalawejder** [comment]
Yes exactly that's what I was thinking about haha

**Pull request closed without merging**
