### PR TITLE
Add allclose, any and astype instance method to paddle.tensor.tensor.Tensor

### LINKED ISSUE #17082: allclose

### LINKED ISSUE #17173: any

### LINKED ISSUE #17423: astype

### PR DESCRIPTION
**Pull request by HaiderSultanArc**
Close #17082 
Close #17173 
Close #17423

### CODE REVIEW

**Comment by HaiderSultanArc** [comment]
Close #17173

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by HaiderSultanArc** [comment]
Yes, I have linked both issues. 
Like this:
Close #17082 
Close #17173

**Comment by Aarsh2001** [comment]
LGTM !

**Pull request merged**
