### PR TITLE
Added conjugate instance method to NumPy ndarray

### LINKED ISSUE #22583: conjugate

### PR DESCRIPTION
**Pull request by vincenzofanizza**
Close #22583

### CODE REVIEW

**Comment by DragosStoican** [comment]
Hi @vincenzofanizza . It appears `conjugate` was already implemented... If you take a look at `ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py`, there is a function `conj`. Conj is an alias for `conjugate`. This should have been reflected #3607 . I will reach out to have that updated, but in the meantime, do you mind working on implementing a different function? Thanks!

**Comment by vincenzofanizza** [comment]
Hi @DragosStoican, thanks for the feedback. I will update the PR ASAP.

**Comment by vincenzofanizza** [comment]
@DragosStoican could you please review the changes when possible?

**Comment by DragosStoican** [comment]
Hi @vincenzofanizza , please have another look [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#alias-functions) and make sure you've added `conj` as an alias to `conjugate`. You will also need to mention this alias in the test, like mentioned in the docs

**Comment by DragosStoican** [comment]
Hi @vincenzofanizza, looks great! I think you are missing the `aliases` keyword in `handle_frontend_test`. Have another look [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#alias-functions) for a quick example of what I am referring to.

Other than that, it looks all good. Your PR is marked as a draft thought and I cannot get it merged until you request a review from me.

**Comment by vincenzofanizza** [comment]
Hi @DragosStoican, I did not include the `aliases` argument because the `handle_frontend_method` function does not seem to accept it. Please have a look [here](https://github.com/unifyai/ivy/blob/6c3a181b1b03fe1aea7430dc89cde92cae0c3e7f/ivy_tests/test_ivy/helpers/testing_helpers.py#L715). 

Am I missing something in how the function handles the input arguments?

**Pull request merged**
