### PR TITLE
Add maximum to paddle frontend

### LINKED ISSUE #17846: maximum

### PR DESCRIPTION
**Pull request by melch-inno**
close #17846

### CODE REVIEW

**Review by Fayad-Alman — CHANGES_REQUESTED** [review]
Hi @melch-inno, please fix the conflicts with your branch with the ivy repository, and I'll come back to this PR.

**Comment by melch-inno** [comment]
> Hi @melch-inno, please fix the conflicts with your branch with the ivy repository, and I'll come back to this PR.

I belive I saw someone merged "maximum" function to paddle after I pushed my PR but now I can't find their changes anymore...

**Comment by melch-inno** [comment]
> Hi @melch-inno, please fix the conflicts with your branch with the ivy repository, and I'll come back to this PR.

I belive I saw someone merged "maximum" function to paddle after I pushed my PR but now I can't find their changes anymore...

**Review by Fayad-Alman — APPROVED** [review]
LGTM!

**Pull request merged**
