### PR TITLE
No changes needed for "get_min_denominator" function.

### PR DESCRIPTION
**Pull request by Girgis98**
I believe there is no need for reformatting.

### CODE REVIEW

**Comment by jiahanxie353** [comment]
could you refer to the link of the task that you are trying to accomplish?

**Comment by Girgis98** [comment]
https://github.com/unifyai/ivy/issues/2575

**Comment by CatB1t** [comment]
Hello @Girgis98, as this function semes to be completed, could you pick another function to work on? Thanks!

**Comment by Girgis98** [comment]
yes sure

**Pull request closed without merging**
