### PR TITLE
Initial implementation of unique_counts (Issue #145)

### PR DESCRIPTION
**Pull request by RKuipers**
Only Numpy passes unit tests, the rest get stuck because of issues with the bool datatype not being properly implemented yet.

Please let me know if making those datatypes work is something I should do, and furthermore if you want me to change anything else.

### CODE REVIEW

**Comment by djl11** [comment]
Hi @RKuipers, thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by RKuipers** [comment]
Hi @djl11, that box is already checked so you should be able to make commits here.
If rebasing is giving issues I'm happy to try it myself or make a new PR based on the updated master branch?

**Comment by djl11** [comment]
> Hi @djl11, that box is already checked so you should be able to make commits here. If rebasing is giving issues I'm happy to try it myself or make a new PR based on the updated master branch?

No that's all good! Thanks!

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Review by djl11 — CHANGES_REQUESTED** [review]
Please remove all changes to .idea and conftest.py, and fix the type hints which are currently incorrect. Please reformat the code as describe in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/), and also as explained in this [YouTube series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl).

**Pull request closed without merging**
