### PR TITLE
Added Multi Dot

### LINKED ISSUE #19403: multi_dot

### PR DESCRIPTION
**Pull request by avi-thakur-0812**
Closes #19403

### CODE REVIEW

**Comment by avi-thakur-0812** [comment]
@KareemMAX  Hey! Could you please look at why I seem to be getting a conflict. Thanks!

**Comment by avi-thakur-0812** [comment]
@nathzi1505 Hey! Could you please look at why I seem to be getting a conflict. Thanks!

**Comment by nathzi1505** [comment]
Hi @Daniel4078, @KareemMAX  and @zaeemansari70 - would you mind looking at the conflict coming through?

**Comment by Daniel4078** [comment]
> 

I think the author of the pull request should try to update his branch to the main branch and resolve the conflict manually on their side usnig git command line prompts (or similair IDE features). Also I think maybe it is better for you to try resolve the problem yourself as the assigned reviewer of this pull request instead of just asking those who are recommended by github. Thanks!

**Comment by avi-thakur-0812** [comment]
Hey, thanks for the information. I will resolve the conflict manually.

**Pull request closed without merging**
