### PR TITLE
added erf fuction to tensorflow math

### PR DESCRIPTION
**Pull request by ShoaibMajidDar**

### CODE REVIEW

**Comment by ShoaibMajidDar** [comment]
Close #19786

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @ShoaibMajidDar 

The tests for `test_tensorflow_erf` are failing in the CI with the error:
```python
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py:2869: in test_tensorflow_erf
    helpers.test_frontend_function(
E   TypeError: test_frontend_function() missing 1 required keyword-only argument: 'backend_to_test'
...
```

You can checkout other examples to see how to properly write the frontend test. 
Could you kindly fix this and re-request a review once all tests are passing. Thanks! 🙂

**Comment by ShoaibMajidDar** [comment]
Hi @YushaArif99  can you please review this PR

**Comment by ShoaibMajidDar** [comment]
Hi @YushaArif99 can you please review this PR

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @ShoaibMajidDar 

Thanks alot for making the requested changes. Just one final thing before we merge this PR, there are a couple of linting errors that have arose as a result of resolving the merge conflicts. I have resolved the changes locally but am unable to push them to this PR branch as its denying me access. 

Can you kindly fix the linting errors and then re-request a review once again. Thanks in advance! 🙂

**Comment by ShoaibMajidDar** [comment]
Hi @YushaArif99 I have resolved the conflicts.

**Comment by ShoaibMajidDar** [comment]
Hi @YushaArif99 I have resolved the conflicts.

**Review by YushaArif99 — APPROVED** [review]
Hi @ShoaibMajidDar 

Apologies for the delay in response. I was away for a couple of weeks due I couldnt respond to the PRs in time. Now that I am back, I'll definitely be alot more responsive. 

Thanks a lot for fixing the previous linting errors. I feel bad having to ask this again, but could you kindly just resolve the conflicts one last time and then re-request a review once that's done? 
Feel free to DM me if I don't respond in time. Really sorry for causing this trouble 🙏🏼.

**Comment by YushaArif99** [comment]
Hi @ShoaibMajidDar. Are you still working on this PR? Could you kindly resolve the conflicts asap so that I can merge the PR 😄.

**Comment by ShoaibMajidDar** [comment]
I will resolve the conflict by tomorrow.

**Comment by YushaArif99** [comment]
> I will resolve the conflict by tomorrow.

Thanks alot @ShoaibMajidDar. Kindly re-request a review once that's done so that I can get notified 🙂

**Comment by YushaArif99** [comment]
@ShoaibMajidDar any updates on this 🙂

**Comment by YushaArif99** [comment]
Hi @ShoaibMajidDar 

There's another contributor who is interested in working on this PR (https://github.com/unifyai/ivy/pull/26731). However, I've asked them to hold off since you had already reserved it. 

To ensure the progress of the project and to respect the time of all contributors, I kindly request you respond to the PR so that it can be merged. 

If there is no response in the next few days, I'll have to close this PR. This is to ensure that we don't keep other contributors waiting.

Thanks! 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
