### PR TITLE
paddle.nn.functional.activation.glu and test

### PR DESCRIPTION
**Pull request by Adeola23**

### CODE REVIEW

**Comment by Adeola23** [comment]
Close #16299

**Comment by Adeola23** [comment]
@MuhammadSaeedBatikh

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Adeola23** [comment]
@MuhammadSaeedBatikh pls review. Thanks

**Comment by Adeola23** [comment]
@MuhammadSaeedBatikh

**Comment by Adeola23** [comment]
@MuhammadSaeedBatikh pls review

**Comment by MuhammadSaeedBatikh** [comment]
Hi @Adeola23, thanks for your PR.
The implementation seems both accurate and efficient. However, you only seem to be testing for very limited tensor shapes.
Could you please change it to this:
```
min_num_dims=1,
max_num_dims=4,
min_dim_size=1,
max_dim_size=4,
```
if tests pass, no further modifications are required.

**Comment by Adeola23** [comment]
> Hi @Adeola23, thanks for your PR. The implementation seems both accurate and efficient. However, you only seem to be testing for very limited tensor shapes. Could you please change it to this:
> 
> ```
> min_num_dims=1,
> max_num_dims=4,
> min_dim_size=1,
> max_dim_size=4,
> ```
> 
> if tests pass, no further modifications are required.

HI @MuhammadSaeedBatikh, The reason why I the limited size of tensor is because I was getting the error `array split does not result in an equal division`. How can I solve this from the implementation?

**Comment by MuhammadSaeedBatikh** [comment]
This makes sense. The reason why this happens is that GLU halves the dimension/axis of interest; therefore, it must be even.
For example, given an input x with shape [3, 6, 8]; the shape of `glu(x, axis=2)`  should be [3,6,4], and for the case of   `glu(x, axis=1)`, it should be [3,3,8]. However, for `glu(x, axis=0)` should raise an exception because 3 is odd.
So, I suggest you add another check to the function. That's for the actual implementation.
As for the tests, we prefer if tests fail loudly than passing and then failing silently. 
In this case, you may want to write a custom helper_test function that makes sure the corresponding number of elements on for the `axis` argument is even. 
 P.S. 
Please reference the issue on your first comment for proper referencing and closing.

**Pull request closed without merging**
