### PR TITLE
Quantile function for numpy frontend Ivy API

### PR DESCRIPTION
**Pull request by Tiago-B-C-Reis**
Add quantile to function frontend and respective unitest.
quantile https://github.com/unifyai/ivy/issues/9137

### CODE REVIEW

**Comment by Tiago-B-C-Reis** [comment]
Hello, @ivy-seed please take a look at this PR.

**Comment by Nightcrab** [comment]
I got this import error while running tests:

```
../../../../../ivy/functional/frontends/numpy/statistics/order_statistics.py:2: in <module>
    from numpy import function_base as fb
E   ImportError: cannot import name 'function_base' from 'numpy'
```
I looked under numpy's submodules and couldn't find ``function_base``. Perhaps there is a path mistake or version mismatch>

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Tiago-B-C-Reis** [comment]
Hello [ivy-seed](https://github.com/ivy-seed),

For this PR, that answer is the same that in #9176, since both share the same Ivy API function, the quantile:

This PR is waiting for the missing update on the [Ivy API Quantile function](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/experimental/statistical.py). Without it won't be possible to complete this PR like [sherry30](https://github.com/sherry30) mention on the comment above.

I had opened an issue to solve this, #8954 but was closed without the function being updated, yet.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
