### PR TITLE
Add max instance method to Jax frontend

### LINKED ISSUE #13758: max

### PR DESCRIPTION
**Pull request by Sheila-nk**
Reference #13758

### CODE REVIEW

**Comment by Sheila-nk** [comment]
Hey @Fayad-Alman 
Some of the tests are failing and I wonder if they are relevant to the `max` instance method I just added since all tests are passing locally.
Apart from that the `max` method takes an additional keyword argument `initial=None` as shown [here](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.max.html) but when I add it, I encounter the error:
```
TypeError: max() got an unexpected keyword argument 'initial
```
Is there a special way to handle the `initial` argument that I might have missed?
Thank you!

**Review by Fayad-Alman — CHANGES_REQUESTED** [review]
Hi @Sheila-nk,
Would you mind adding the initial argument so I can see where the error is coming from?
Thanks for your contributions!

**Comment by Sheila-nk** [comment]
@Fayad-Alman I have made the requested change. The workflow tests fail with the error:
 ```
TypeError: max() got an unexpected keyword argument 'initial'
```

**Comment by Fayad-Alman** [comment]
Hi @Sheila-nk 
I've found the source of this error; the original max function located in ivy/functional/frontends/jax/numpy/statistical.py does not have an initial parameter. In addition, the ivy function max located in ivy/functional/ivy/statistical.py also has no initial parameter. Would you mind adding these parameters and requesting another review?
Thanks again for your continued efforts!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Sheila-nk** [comment]
I have been having some technical issues. Still working on this PR.

**Comment by Sheila-nk** [comment]
I am unable to finish working on this PR due to some unresolved technical issues. I will therefore close it.

**Pull request closed without merging**
