### PR TITLE
add extract method to sorting_searching_counting

### PR DESCRIPTION
**Pull request by AntoniosMalak**

### CODE REVIEW

**Comment by AntoniosMalak** [comment]
Hi @johanjino may u review the task PR:)

**Comment by johanjino** [comment]
Hey @AntoniosMalak, Please mention which issue this is resolving. Thank you!

**Comment by AntoniosMalak** [comment]
Hi @johanjino, This is an issue I created `extract #7716`.
This is an issue in ToDo list `Add Sorting searching, and counting functions to Numpy Frontend #1531`

**Comment by AntoniosMalak** [comment]
Hi, @johanjino  may u review it, please!

**Comment by AntoniosMalak** [comment]
Hi, @johanjino can you review this PR to merge it if everything is ok?

**Comment by AntoniosMalak** [comment]
Hi @CatB1t, in other PR :) May u check it?

**Comment by AntoniosMalak** [comment]
@CatB1t you may check it know.

**Pull request closed without merging**
