### PR TITLE
added kron to torch misc

### LINKED ISSUE #21838: kron

### PR DESCRIPTION
**Pull request by charchit7**
Close #21838

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by charchit7** [comment]
`ivy/utils/exceptions.py:390: IvyBackendException
========================================================================================== 20.0% of 5 passed ================================================================================================================================================================================== short test summary info ========================================================================================
FAILED ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py::test_torch_kron[cpu-jax-False-False] - ivy.utils.exceptions.IvyBackendException: numpy: nested_map: numpy: nested_map: can't convert np.ndarray of type bfloat16. The only supported types are: float64, float32, float16, complex64, comp...
FAILED ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py::test_torch_kron[cpu-tensorflow-False-False] - ivy.utils.exceptions.IvyBackendException: tensorflow: kron: The DType <class 'numpy.dtypes.Float16DType'> could not be promoted by <class 'numpy.dtype[bfloat16]'>. This means that no common DType...
FAILED ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py::test_torch_kron[cpu-torch-False-False] - ivy.utils.exceptions.IvyBackendException: numpy: nested_map: numpy: nested_map: can't convert np.ndarray of type bfloat16. The only supported types are: float64, float32, float16, complex64, comp...
FAILED ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py::test_torch_kron[cpu-paddle-False-False] - ivy.utils.exceptions.IvyValueError: paddle: kron: (InvalidArgument) The type of data we are trying to retrieve (float16) does not match the type of data (float32) currently contained in the conta...
============================================================================== 4 failed, 1 passed, 114 warnings in 58.82s ==============================================================================`


Testing 1

**Comment by charchit7** [comment]
Hey @jkeane508 need guidance here.

**Comment by jkeane508** [comment]
ivy-gardener

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hi,

Just looking at the test logs. The issue was a problem with our testing framework which has since been resolved. Can you please pull the latest version on the repo to get the latest fixes. Thanks!

**Comment by charchit7** [comment]
Hello,

Thank you for your review. I have updated the code. Could you please review the changes? (All 5 tests have passed in the local repository).

**Comment by charchit7** [comment]
Hey @jkeane508 could you please check one again.

**Review by jkeane508 — APPROVED** [review]
LGTM!

**Comment by charchit7** [comment]
Thanks, @jkeane508!

**Pull request merged**
