### PR TITLE
Added initial_seed function to torch

### LINKED ISSUE #14642: initial_seed

### PR DESCRIPTION
**Pull request by Patric-Ramz**
close #14642

### CODE REVIEW

**Comment by Patric-Ramz** [comment]
Do I need to use the ivy.randint function instead of the torch.randint function?

**Comment by Sam-Armstrong** [comment]
Hi @Patric-Ramz,

Yes the frontend function needs to be made up of ivy functions rather than torch functions. In addition, please can you write the tests for this function and ensure that they pass? Here are some links to our documentation for writing frontend functions and their tests, hopefully this will help :)

https://lets-unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#writing-frontend-functions
https://lets-unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#ivy-frontend-tests

You might also find it useful to read the 'Frontend APIs' section of our Open Tasks page:
https://lets-unify.ai/docs/ivy/overview/contributing/open_tasks.html

Thanks!

**Comment by Patric-Ramz** [comment]
Hi @Sam-Armstrong 

Thank you for the review. I will make the changes and write the tests for the function.

Kind regards,

**Comment by Patric-Ramz** [comment]
Hi @Sam-Armstrong 

You didn't request any changes so I am unable to request a code review even though I made changes. 

Under reviewers it still says no reviews. 

Please help me!

Kind regards,
Rele

**Comment by Sam-Armstrong** [comment]
@Patric-Ramz
Hi Rele, don't worry - you don't need to request a review or anything, I can already see your updated changes :)

Please can you make sure that the tests you added pass - all 5 cases are failing for me. You can run your tests with this command:
pytest ivy_tests/test_ivy/test_frontends/test_torch/test_random_sampling.py::test_torch_initial_seed

You will also need to include the @to_ivy_arrays_and_back decorator above your function declaration.

There are some unnecessary changes here also:
- Any changes to .iml/.xml files need to be removed
- You've added extra whitespaces to ivy/functional/frontends/numpy/random/functions.py

Finally, please can you make sure to include a line of whitespace and the end of the file, and include two lines of whitespace between the previous function and the start of yours (rather than one).

Thanks!

**Comment by Patric-Ramz** [comment]
Thank you for the feedback, I will make the changes : )

**Comment by Patric-Ramz** [comment]
Hi Sam,

When I run the test the _get_fn_dtypes(framework, kind="valid") returns "None" for framework. do you have any advice on how I can fix this issue?

here is a snippet of the error I am getting.


ivy_tests\test_ivy\helpers\hypothesis_helpers\dtype_helpers.py:186: in get_dtypes
    frontend_dtypes = retrieval_fn(test_globals.CURRENT_FRONTEND(), kind)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

framework = None, kind = 'numeric'

    def _get_fn_dtypes(framework, kind="valid"):
>       return test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[framework.backend][
            test_globals.CURRENT_DEVICE_STRIPPED
        ][kind]
E       AttributeError: 'NoneType' object has no attribute 'backend'

**Comment by Sam-Armstrong** [comment]
@Patric-Ramz Please could you give me some context on how to reproduce this error? When I run your test, the error is something like "fixture 'num_positional_args' not found".

**Comment by Patric-Ramz** [comment]
Hi Sam, 

Sorry for the late response.

I changed num_positional_args to num_positional_args=0 in my test function

if you run the test now it will reproduce the 'NoneType' object has no attribute 'backend' error.

for some reason the helper function _get_fn_dtypes in ivy_tests\test_ivy\helpers\hypothesis_helpers\dtype_helpers.py is making the framework variable = 'none' 

Please help me with it.

**Comment by Sam-Armstrong** [comment]
@Patric-Ramz The error now seems to be "TypeError: test_frontend_function() missing 1 required keyword-only argument: 'test_flags'", rather than the one you said. Are you running this test using the pytest command? It seems like we're having some disparity in the results we're getting

**Comment by Patric-Ramz** [comment]
Yes I am running the test using this function in the terminal

pytest ivy_tests/test_ivy/test_frontends/test_torch/test_random_sampling.py::test_torch_initial_seed

**Comment by Patric-Ramz** [comment]
I am going to add the test_flags argument. please let me know what error you are getting afterwards.

**Comment by Patric-Ramz** [comment]
I think there error is on my side because when I try to run previously added tests I get the exact same error.

**Comment by Sam-Armstrong** [comment]
Hi @Patric-Ramz,

I've had a look at what this torch function is actually doing, and I realised that we don't actually have all we need for it in the ivy functional api right now. This function basically just gets the current seed that has been set in torch, so to implement this we would need to call a method like 'get_seed' in the ivy functional api. Unfortunately this does not exist yet, so we will have to wait until this is implemented before we can look to add this torch function to the frontend api. You can see the open issue for 'get_seed' here https://github.com/unifyai/ivy/issues/3856, if this was something you were interested in working on.

Sorry to bring this bad news, and also apologies that it took me a while to check this - I needed to confirm the problem with the team.

Sam

**Comment by Patric-Ramz** [comment]
Okay thank you. I will look for a new issue to work on.

Kind regards,

**Comment by Patric-Ramz** [comment]
I will try that.

Thank you : )

**Comment by Sam-Armstrong** [comment]
No worries :)

**Pull request closed without merging**
