### PR TITLE
added stateless_gamma to tensorflow frontened and tested.

### PR DESCRIPTION
**Pull request by Ashu8900**
# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ashu8900** [comment]
I will do it again and resubmit

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Ashu8900 
Thanks for the PR.
After removing the double ivy.ivy in you function call, there are still failures that you can see at https://github.com/unifyai/ivy/actions/runs/8129172276/job/22216135032?pr=26395
under Combined Tests Results for `stateless_gamma`
Could you pls fix and request a review when done.Thanks :)

**Comment by Ishticode** [comment]
closing this due to lack of activity with changes requested remaining unresolved. Please feel free to reopen if you would like to continue working on this.

**Pull request closed without merging**
