### PR TITLE
changed the docstring and parameter description in print_all_arrays_on…

### PR DESCRIPTION
**Pull request by Preeti2095**
#1082

### CODE REVIEW

**Comment by bicycleman15** [comment]
Hey @Preeti2095, its a good start, could you also please add an example showing the working of `print_all_arrays_on_dev` in it's docstring.
You can refer to the contribution guide [here](https://lets-unify.ai/ivy/contributing/7_docstring_examples.html) for more clarity. But I think for this function, a single example is enough. 
Feel free to reach me if there is any confusion 🙂

**Comment by Preeti2095** [comment]
I am really sorry for late update....and i have got a doubt. When i run the print_all_arrays_on_dev() function, it internally calls the get_call_arrays_on_dev() function. So, what this function actually does?
The output i get from get_call_arrays_on_dev() is:
```
x=ivy.array([1,2,3])
y=ivy.dev(x)
print(ivy.get_all_arrays_on_dev(y))
out-->
[masked_array(data=--,
                         mask=True,
                         fill_value=1e+20,
                         dtype=float64), masked]
```
what this means?

**Comment by bicycleman15** [comment]
I am not sure but it seems `get_all_arrays_on_dev` is not working as intended. Perhaps @Ishticode can have a look ?
In the mean time, you are very much welcome to work on any other issue @Preeti2095 🙂

**Comment by Preeti2095** [comment]
Sure and thank you for the response. Let me know if I need to any changes on it.
Thank you @bicycleman15.

**Review by Ishticode — COMMENTED** [review]
@bicycleman15 I have brought this into discussion under [this page](https://github.com/unifyai/ivy/discussions/1317).

**Comment by bicycleman15** [comment]
closing this due to inactivity

**Pull request closed without merging**
