### PR TITLE
Update stat.py

### LINKED ISSUE #20867: var
Adding var which is a Statistical Function to PaddlePaddle Frontend

### PR DESCRIPTION
**Pull request by praveen8ae**
Close #20867 
- [x]  #20867

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by AryanSharma21 — COMMENTED** [review]
Hry @praveen8ae , you should edit the Description and write the closing tag as 
`close #issue_number` to properly link the issue with the pull request. 

The `- [ ] #issue_number` tag should go under the to do list comments from where you have selected this issue to work. 

Also,  while implementing an API function you should also be writing test function to make sure the function behaves properly. 
Thanks 😊

**Comment by AryanSharma21** [comment]
You can read about contribution basics in the ivy docs as well

**Comment by praveen8ae** [comment]
> Hry @praveen8ae , you should edit the Description and write the closing tag as `close #issue_number` to properly link the issue with the pull request.
> 
> The `- [ ] #issue_number` tag should go under the to do list comments from where you have selected this issue to work.
> 
> Also, while implementing an API function you should also be writing test function to make sure the function behaves properly. Thanks 😊

can you please show me an example(template or anything), I'm a bit confused 😅

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
