### PR TITLE
feat: Added adaptive max pooling 1D to Ivy backend

### LINKED ISSUE #22317: adaptive_max_pool1d

### PR DESCRIPTION
**Pull request by arshPratap**
# PR Description 

Added adaptive max pooling 1D function to ivy backend.
Currently utilized by Torch and Paddle Frameworks
This PR will be followed by another PRs that enables the said function into the designated framework frontends
## Related Issue 

Close #22317

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by bipinKrishnan** [comment]
Hey @arshPratap , can you fix the failing tests for jax, tf and paddle backends?

**Comment by bipinKrishnan** [comment]
@arshPratap The tests in "run_test (1)" are failing due to generated output not matching the ground truth. Can you look into this, fix the conflicts and push again?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by arshPratap** [comment]
Rebased !

**Comment by Sarvesh-Kesharwani** [comment]
Hi @arshPratap , 
please resolve the merge conflicts so we can proceed with your pull request.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi
The logs show failures for the added tests
```
ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_adaptive_max_pool1d,numpy
ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_adaptive_max_pool1d,torch
ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_adaptive_max_pool1d,paddle
ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_adaptive_max_pool1d,jax
ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py::test_adaptive_max_pool1d,tensorflow
```
That you may see at https://github.com/unifyai/ivy/actions/runs/8003861982/job/21860150431?pr=22542
Are you able to fix these? Please let me know if something is unclear.

**Comment by Ishticode** [comment]
closing due to inactivity for over two weeks after requested changes. Please feel free reopen if you would like to continue working on this. Thanks :)

**Pull request closed without merging**
