### PR TITLE
Reformat cos

### PR DESCRIPTION
**Pull request by mohanadtalat91**
Issue #5927

### CODE REVIEW

**Comment by mohanadtalat91** [comment]
Hello, 
Could you @ankitdsi2010  please review my pr  ??

**Comment by mohanadtalat91** [comment]
Hello @Ishticode, 
Could you please review my PR ??

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @mohanadtalat91 Thanks for this PR 🙂.

Could you keep the args `key_chains` and others as keyword only and `x` the positional only as it was previously done in `static_cos` and keep the call to static_cos in contianer's `cos` method as it was before (with key word args).

Please feel free to ask anything if the above didn't make sense or something and when changes are made, request my review. Thanks

**Comment by mohanadtalat91** [comment]
> Hi @mohanadtalat91 Thanks for this PR 🙂.
> 
> Could you keep the args `key_chains` and others as keyword only and `x` the positional only as it was previously done in `static_cos` and keep the call to static_cos in contianer's `cos` method as it was before (with key word args).
> 
> Please feel free to ask anything if the above didn't make sense or something and when changes are made, request my review. Thanks

Hi @Ishticode, thanks for your review.
Could you please review it agian after my update. And feel free if you need any change or update. Thanks in advanced.

**Comment by MarShaikh** [comment]
> Hi @mohanadtalat91 Thanks for the review request 🙂. We shouldn't be needing to remove the docstrings containing parameter details. It seems as if this function is already formatted in PR#1935 and some others afterwards. I am not sure but if you were wrongfully assigned an already completed task then we apologise. If this is a PR made for the application then please go ahead and submit it as and I will tag @MarShaikh

Following up on @Ishticode, @mohanadtalat91 if you do submit this PR, please send your email and this PR link to the IvyTeam acc. Thanks!

**Comment by mohanadtalat91** [comment]
> Hi @mohanadtalat91 Thanks for the review request 🙂. We shouldn't be needing to remove the docstrings containing parameter details. It seems as if this function is already formatted in PR#1935 and some others afterwards. I am not sure but if you were wrongfully assigned an already completed task then we apologise. If this is a PR made for the application then please go ahead and submit it as and I will tag @MarShaikh

Okay, I see. But I saw that didn't completed, so I took this issue. 😊

**Review by Ishticode — COMMENTED** [review]
Hi. Yh. But I have a way to merge this. May I point out that if you can exclude all your changes in the array and container folders.... and then remove the examples for **Container** and **NativeArray** from the functional/ivy/elementwise... then request my review... 🙂
Sorry for the inconvenience.

**Comment by mohanadtalat91** [comment]
> Hi. Yh. But I have a way to merge this. May I point out that if you can exclude all your changes in the array and container folders.... and then remove the examples for **Container** and **NativeArray** from the functional/ivy/elementwise... then request my review... 🙂 Sorry for the inconvenience.

So. Should I work on this issue or what should I do ?? 🙂

**Comment by Ishticode** [comment]
> > Hi. Yh. But I have a way to merge this. May I point out that if you can exclude all your changes in the array and container folders.... and then remove the examples for **Container** and **NativeArray** from the functional/ivy/elementwise... then request my review... 🙂 Sorry for the inconvenience.
> 
> So. Should I work on this issue or what should I do ?? 🙂

Hey. You can continue work yes but ... you will have to exclude changes in the `Array` and `Container` submodules. So there should be no changes there. As for functional/ivy submodule, the only change should be the removal of `Container` and `NativeArray` example. Please let me know if this is unclear and I will try my best to help out. Sorry for any confusion @mohanadtalat91 . 🙂

**Comment by mohanadtalat91** [comment]
> > > Hi. Yh. But I have a way to merge this. May I point out that if you can exclude all your changes in the array and container folders.... and then remove the examples for **Container** and **NativeArray** from the functional/ivy/elementwise... then request my review... 🙂 Sorry for the inconvenience.
> > 
> > 
> > So. Should I work on this issue or what should I do ?? 🙂
> 
> Hey. You can continue work yes but ... you will have to exclude changes in the `Array` and `Container` submodules. So there should be no changes there. As for functional/ivy submodule, the only change should be the removal of `Container` and `NativeArray` example. Please let me know if this is unclear and I will try my best to help out. Sorry for any confusion @mohanadtalat91 . 🙂

Okay, But I've one question, should I remove (`Native array` & `Container`) examples from `Functional` and replace another example or just remove ?? 
If you mention what should to be done in a specific line of code, it'll be nice 😊

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi. Yes we should remove the Native array examples and move the container examples over to the relevant container method.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Actually could you just delete the Native Array example and make the changes above and then request my review.

So in summary. Exclude any changes to the container and array directories and then remove the Native Array example from functional ivy.

**Review by Ishticode — APPROVED** [review]
Hi @mohanadtalat91 
I have decided to fix up some of the issues and go ahead and merge your PR. Thanks for your patience. We apologize that this issue got reassigned and but I have tried to keep some of your import parts for the refactor such as removing the Native Array example and an elaborate example for in array/elementwise. The lint is caused by external commits. Thanks a lot for your patience and struggle. Please feel free to move forward with @MarShaikh if you like. 🙂

**Pull request merged**
