### PR TITLE
dev_util #1800

### PR DESCRIPTION
**Pull request by so-dipe**

### CODE REVIEW

**Review by ZoeCD — CHANGES_REQUESTED** [review]
Hi! Are you applying for the internship? Could you please add more examples of how to use this function?

**Comment by so-dipe** [comment]
Yes, I'm applying for the internship.
I have added more examples to the function.

**Comment by ZoeCD** [comment]
Hi! Thank you for your contribution. One more thing before merging. There are some lint issues with these new commits, you can review them under the details of the check. Do you have the lint pre-commit hook installed? You can learn about it [here](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit)

**Comment by so-dipe** [comment]
Hi, I fixed the lint issues with the commit. Thanks for your time.

**Pull request merged**
