### PR TITLE
fix the failing unit test of jax.lax.reshape

### LINKED ISSUE #8746: Fix jax_lax_operators.test_jax_lax_reshape
|   |   |
|---|---|
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/5374196432/jobs/9749300759"></a>
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/5374196432/jobs/9749300759"></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/5374196432/jobs/9749300759"></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/5374196432/jobs/9749300759"></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/5374196432/jobs/9749300759"></a>

### PR DESCRIPTION
**Pull request by hello-fri-end**
close #8746

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hey, thank you for your contribution! Besides the lint error, which I believe can be fixed by removing the commented-out bit of code, can you please explain your reasoning for the solution? I know it's not a requirement, but just for my own understanding

**Comment by hello-fri-end** [comment]
> Hey, thank you for your contribution! Besides the lint error, which I believe can be fixed by removing the commented-out bit of code, can you please explain your reasoning for the solution? I know it's not a requirement, but just for my own understanding

Basically, this function is supposed a generate a valid `reshape` tuple given the original shape. It works by first calculating the `size` ( total no. of elements = product of all the dimensions) and then generating a tuple of integers whose product is equal to `size`. The code I deleted basically makes one of the values in the tuple equal to 1, rendering it an invalid reshape tuple.

**Comment by hello-fri-end** [comment]
Hi @V-G-spec, can we merge this?

**Comment by V-G-spec** [comment]
I see, thanks a lot for the explanation. I can see some conflicts that need to be resolved first. Can you check this out?
If you believe a delay in my respons caused the issuee, let me know and don't worry about it.
Thanks!

**Comment by hello-fri-end** [comment]
> I see, thanks a lot for the explanation. I can see some conflicts that need to be resolved first. Can you check this out? If you believe a delay in my respons caused the issuee, let me know and don't worry about it. Thanks!

Fixed the merge conflict.

**Comment by V-G-spec** [comment]
Great! I fixed your first comment to follow the contribution guide. Merging your PR now. Thanks again!

**Pull request merged**
