### PR TITLE
added mish activation

### PR DESCRIPTION
**Pull request by aryankhatana01**

### CODE REVIEW

**Comment by aditya-pola** [comment]
Hey @aryankhatana01 🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

**Comment by aditya-pola** [comment]
Hey this looks good but there's a few changes required before I can merge.
- Add examples to the ivy functional method docstrings
- Write the frontend test. More instructions can be found via following the links [here](https://lets-unify.ai/ivy/contributing/open_tasks.html#frontend-apis)

**Comment by aditya-pola** [comment]
Sure, just take a look at docstrings of other functions in ivy/functional/ivy/activations.py for how examples are implemented.
- For the frontend test follow the link I provided, You will find more instructions about how to implement the test if you follow the link in point 3 in the [link](https://lets-unify.ai/ivy/contributing/open_tasks.html#frontend-apis) I provided.

If you are having trouble with tests please look at how tests are implemented for other functions, that should give you a good idea.

**Comment by aryankhatana01** [comment]
@aditya-pola Is this commit okay?

**Comment by aryankhatana01** [comment]
@aditya-pola I've made the necessary changes and also installed pre-commit. How does It look now?

**Comment by aryankhatana01** [comment]
@aditya-pola Is this PR ready to be merged?

**Comment by aryankhatana01** [comment]
@aditya-pola Is this PR good to be merged?

**Comment by aditya-pola** [comment]
Hey @aryankhatana01, apologies for the delay, I had to confer with my colleagues about the PR. There are a few changes that need to be made before merging. 
- Since the task was to implement the torch frontend, we can't have the backend implementation. The frontend needs to be implemented compositionally using ivy functions (tanh and softplus) in ivy/functional/frontends/torch/nn/functional/non_linear_activation_functions.py
- The test has to be placed in ivy_tests/test_ivy/test_frontends/test_torch/test_non_linear_activation_functions.py. Please ensure the test is passing.
- Please remove the backend implementation and the changes to ivy/functional/ivy/activations.py.

An example of a torch fronted implementation can be found here for [celu](https://github.com/unifyai/ivy/pull/4160)

**Comment by aryankhatana01** [comment]
@aditya-pola No problem, got it!

**Comment by aryankhatana01** [comment]
@aditya-pola Is it okay now?

**Comment by aditya-pola** [comment]
Looks great! Thank you for the contribution :)

**Pull request merged**
