### PR TITLE
Add MAX function to Paddle's math

### LINKED ISSUE #15983: max

### PR DESCRIPTION
**Pull request by Nordiniv**
closes #15983

### CODE REVIEW

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hi @Nordiniv,
Seems like you are missing tests to your frontend function, I'll provide the complete checklist that you will need to follow. Please request a review from me once you have this list completed

**Comment by KareemMAX** [comment]
add_frontend_checklist

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
