### PR TITLE
add neg instance method to PyTorch frontend

### PR DESCRIPTION
**Pull request by Y-T-G**
Close https://github.com/unifyai/ivy/issues/7509

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by aditya-pola** [comment]
This somehow slipped under my radar, my apologies! I will be reviewing this ASAP and get back to you.

**Comment by aditya-pola** [comment]
This looks good to me! Merging...

**Comment by Y-T-G** [comment]
@aditya-pola Thanks

**Pull request merged**
