### PR TITLE
Pairwise distance

### LINKED ISSUE #3757: pairwise_distance

### PR DESCRIPTION
**Pull request by JamieLine**
Fixes #3757. Moved distance_functions.py to match Torch's function signatures, which is needed for all functions in distance_functions.py. Local tests pass on my PC.

### CODE REVIEW

**Comment by JamieLine** [comment]
Is the change in file structure correct? It makes Ivy's version of the Torch API match the official Torch API for this function.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
File structure looks good 🙂 Can you use `helpers.get_dtypes` to draw data types. And you should be able to remove `as_variable` and `native_array` from the `@given`, they are handled by the command line decorator

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
