### PR TITLE
Added trace method

### LINKED ISSUE #22555: trace

### PR DESCRIPTION
**Pull request by Aaryan562**
Close #22555

### CODE REVIEW

**Comment by Aaryan562** [comment]
@bipinKrishnan could you pls review my PR.

**Comment by Aaryan562** [comment]
@bipinKrishnan could you pls review my PR. It has been 2 days. I have passed all the local test cases and there are no lint errors as well. Pls review and merge as long as there are no merge conflicts with it.

**Comment by Aaryan562** [comment]
@sherry30 hello, sorry to disturb you. But Ig @bipinKrishnan is inactive and my PR is getting merge conflicts. I request you to pls review it and merge since my local test cases are passing successfully. Thank you

**Comment by bipinKrishnan** [comment]
LGTM! Thanks for the contribution @Aaryan562 🚀 .

**Pull request merged**
