### PR TITLE
Added from_numpy Ops to Pytorch Frontend #5912

### PR DESCRIPTION
**Pull request by marolAI**

### CODE REVIEW

**Comment by JamieLine** [comment]
Hi! Thanks for the PR!

Most of this code looks quite good, there are just 3 issues I have seen so far, 2 of which are very minor. 
1) There are some linting failures, have a look in the test log that can be found by clicking on `Details` next to the linting check on this page, and if they are related to your code please fix them. When you push new code, the tests will automatically be run again, or you can run `flake8` and `black` locally to check them.
2) When you defined a test for this function (which is absolutely correct, the function does need a test), you didn't define a function body. You added the `@given` decorator, and `def test...(...)` but nothing afterwards. Have a look at the other tests in that file, fill out the function body, and run the test locally using `pytest` to make sure that it passes. 
3) You've made some slight formatting changes to `test_torch_as_tensor`, these will need to be undone, the previous formatting was correct.

The rest of the PR looks good though, and once these changes have been made and the tests pass, this should be good to be merged!

Any questions or comments please let me know!

**Comment by marolAI** [comment]
Hi!
I am not sure if I understand point 2., I defined it as others did and the local test with `pytest` passes. Otherwise the other changes have been made. 
Can you check them and let me know if something has to change?

**Comment by JamieLine** [comment]
Hi! As far as I can tell I just misread the original code, it's all good now!

**Comment by marolAI** [comment]
Close #5912

**Pull request merged**
