### PR TITLE
NumPy Frontend - mathematical_functions - trigonometric functions

### PR DESCRIPTION
**Pull request by roboFiddle**

### CODE REVIEW

**Comment by bicycleman15** [comment]
Hey @roboFiddle , you have made changes to a lot of frontend functions. Could you let me know which function you are working and just implement frontend and test for that function only. ?

Maybe linking the issue you are working on in the PR helps streamline the process a lot.

Maybe you could raise a new PR and just work on the function that you are interested in ? Let me know whatever suits you 🙂

**Review by bicycleman15 — CHANGES_REQUESTED** [review]
Let me know if you are working on the same PR, or will be raising a new one. I would personally however suggest to open a new one and work from there afresh 🙂 .

**Comment by roboFiddle** [comment]
I'll separate each function into a different PR. Closing.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
