### PR TITLE
Reformatted the einsum function

### PR DESCRIPTION
**Pull request by ctoanadu**

### CODE REVIEW

**Comment by VedPatwardhan** [comment]
Hi @ctoanadu, thanks for contributing! Could you please mention the issue you've created in [this](https://github.com/unifyai/ivy/issues/812) ToDo list so that it would get linked there? Thanks 🙂

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
There are a few changes to be made to your PR before we get it merged:
1. `out: Optional[Union[ivy.Array, ivy.NativeArray]]` needs to be replaced with `out: Optional[ivy.Array]`. This is because Ivy is designed in a way that every function accepts an Ivy array and returns an Ivy array, so the out argument needs to be an `ivy.Array`. Feel free to read more about this [here](https://lets-unify.ai/ivy/deep_dive/8_inplace_updates.html#inplace-updates).
2. The docstring of this function also needs to be updated according to the format specified [here](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html).
Feel free to ask any questions 🙂

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hi @ctoanadu, seems like the docstrings are still not in the required format, please refer [this](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html) page for updating them, in particular, the docstring need not have description of examples like lines 460, 467, 473 and many other lines so please remove them too. We just need to have a line informing what input it is, e.g. `With :code: 'ivy.Array' input:` followed by few examples covering all possible variants for each of the arguments independently as described on the page mentioned above. Along with `ivy.Array` and `ivy.NativeArray`, please also add examples for:
1. a mix of `ivy.Array` and `ivy.NativeArray`
2. `ivy.Container`
3. a mix of `ivy.Array` and `ivy.Container`
4. multiple `ivy.Container` arguments
5. instance method of the `ivy.Array` class
6. instance method of the `ivy.Container` class

You'd be able to find all necessary details about the same on the page mentioned, although please feel free to ask any questions.  Also, the files changed show that you might've accidentally added a submodule, please remove it too. Thanks 🙂

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
There seem to be a few more changes to be made:
1. Please add the `Functional Examples` and `Instance Method Examples` before the functional examples and instance method examples respectively as specified [here](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html). And of course, please remove the `Examples` header present currently.
2. Every example is currently followed by 2 blank lines, please update that to one blank line after every example.
3. `...` seems to be added for multiline inputs, please remove them too, because it'll cause the docstring tests to fail.
4. Line 572 seems to be too long, please update it so that it doesn't exceed the maximum character limit per line. To do so, you can have parameter `b` on a new line instead of it being on the same line.
5. The indentation on line 560 and 561 needs to be changed, please add a tab space there.
6. Some examples seem to have values separated with one space after a comma, some with two and some with none. Please update that to ensure uniformity with one space after a comma for every value in the arrays.
Thanks 🙂

**Comment by ctoanadu** [comment]
I can't seem to figure out the conflict with my master and that of ivy.

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hi @ctoanadu, The docstring looks good to me, but the `ivy/functional/ivy/ivy` submodule still seems to exist in the code, please remove it. 
Let me know if you need my help with that, I'll be happy to do so.
Thanks 🙂

**Comment by ctoanadu** [comment]
> Hi @ctoanadu, The docstring looks good to me, but the `ivy/functional/ivy/ivy` submodule still seems to exist in the code, please remove it. Let me know if you need my help with that, I'll be happy to do so. Thanks 🙂

I do need help. I have deleted it on my local repo but cant seem to effect the changes on gitub. Thanks a lot for your help

**Comment by VedPatwardhan** [comment]
Let's wait till the docstring tests are completed, we can merge your PR right after that.

**Comment by VedPatwardhan** [comment]
The docstring tests are failing for this function currently, I'll take another look tomorrow and let you know if anything needs to be changed. Thanks 🙂

**Review by VedPatwardhan — APPROVED** [review]
lgtm! Thanks for contributing. I'll merge your PR now

**Comment by ctoanadu** [comment]
> lgtm! Thanks for contributing. I'll merge your PR now

Thanks a lot mate

**Pull request merged**
