### PR TITLE
percentile #19260

### LINKED ISSUE #19260: Percentile experimental implementation

### PR DESCRIPTION
**Pull request by alrizkipascar**
Close #19260

=====Notes=====
since paddle and torch does not have percentile function, I am just using quantile from each framework since they have same purpose.

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi @alrizkipascar! Thanks a lot for working on this 😄 It looks like the tests are failing, and it's throwing `fixture 'ground_truth_backend' not found`, could you please look into it?

Here's a quick way to run the tests on local before pushing the changes - 
```
pytest /workspaces/ivy/ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_statistical.py::test_percentile
```
Feel free to re-request review after making these changes, thanks! 😄

**Comment by alrizkipascar** [comment]
> Hi @alrizkipascar! Thanks a lot for working on this 😄 It looks like the tests are failing, and it's throwing `fixture 'ground_truth_backend' not found`, could you please look into it?
> 
> Here's a quick way to run the tests on local before pushing the changes -
> 
> ```
> pytest /workspaces/ivy/ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_statistical.py::test_percentile
> ```
> 
> Feel free to re-request review after making these changes, thanks! 😄

Okay I will try find the issues

**Comment by rishabgit** [comment]
> > Hi @alrizkipascar! Thanks a lot for working on this 😄 It looks like the tests are failing, and it's throwing `fixture 'ground_truth_backend' not found`, could you please look into it?
> > Here's a quick way to run the tests on local before pushing the changes -
> > ```
> > pytest /workspaces/ivy/ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_statistical.py::test_percentile
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Feel free to re-request review after making these changes, thanks! 😄
> 
> Okay I will try find the issues

Thanks! I'll suggest starting with pulling the latest updates from ivy. There have been tons of changes in the testing pipeline recently. Good luck! 😄

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
