### PR TITLE
added frontend,test for numpy sort

### PR DESCRIPTION
**Pull request by fkhjoy**
without executing test

### CODE REVIEW

**Comment by fkhjoy** [comment]
#3545

**Comment by abdrahmandiab** [comment]
Hi @fkhjoy , are you still working on this PR?
If so, there is no rush, and please feel free to request a review once the tests are passing or if you need help.
If not you can let me know as well. :)

Thanks! :)

**Comment by fkhjoy** [comment]
@abdrahmandiab hi. Yeah. I was working. I am confused about the way of testing.

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab hi. Yeah. I was working. I am confused about the way of testing.

hi!
In that case I would recommend checking the [frontend tasks YouTube playlist](https://www.youtube.com/playlist?list=PLwNuX3xB_tv-wTpVDMSJr7XW6IP_qZH0t) and making sure you go through [the frontend tests docs](https://lets-unify.ai/ivy/deep_dive/17_ivy_frontends_tests.html) in order to get a better understanding of how we implement our tests.

**Comment by abdrahmandiab** [comment]
Hi @fkhjoy,
Unfortunately I have to close this PR as it has been active for quite a long time!
Feel free to re-claim this function or any other one should you want to continue your application process at any time! 😅

Thanks!

**Pull request closed without merging**
