### PR TITLE
added the gaussion_nll_loss

### LINKED ISSUE #22141: gaussian_nll_loss

### PR DESCRIPTION
**Pull request by sushmanthreddy**
close #22141

### CODE REVIEW

**Comment by sushmanthreddy** [comment]
@Infrared1029 can u
 pls review the pull request the test casses are failing for only paddle , that is bfloat16 issue ,where ivy people are working on
here is below screenshot 

Screenshot from 2023-08-18 22-26-10

**Comment by sushmanthreddy** [comment]
Screenshot from 2023-08-20 02-24-52
supporting datatypes are selected from here

**Comment by Infrared1029** [comment]
Hi @sushmanthreddy, few changes
- remove any updates to the array_api files
- make sure all arguments are included in the docstrings

for the bfloat issues with paddle @MahmoudAshraf97 any ideas what is causing that?

**Comment by sushmanthreddy** [comment]
@Infrared1029 there is a problem of converting bfloat16 to int16 or vice versa..
The paddle doesn't support the bfloat16 as input...
so that is the reason it is causing fail for paddle test.

**Comment by sushmanthreddy** [comment]
@Infrared1029 i have removed the array_api files..
And for bfloat16 is not only for implementation but also failing for other implemented code in ivy_functional folder..
I think work is going on for bfloat16 for paddle .But logic and implementation is correct ..

Hopefull..if u want any changes pls let me knew.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @sushmanthreddy 
Thanks for the PR and sorry for the delays on our end. Not sure why this was not merged earlier. If you can clear up the conflicts I should be able to merge this soon.

**Comment by Ishticode** [comment]
Let me know if you have any questions

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
