### PR TITLE
bitwise_right_shift adhering to Array API standard

### PR DESCRIPTION
**Pull request by VedPatwardhan**

### CODE REVIEW

**Comment by VedPatwardhan** [comment]
@mattbarrett98, please review.

**Review by mattbarrett98 — COMMENTED** [review]
Hi, thanks for making the changes. I made some small changes also and now all the tests are passing 🙂

**Comment by VedPatwardhan** [comment]
> Hi, thanks for making the changes. I made some small changes also and now all the tests are passing 🙂

@mattbarrett98 thanks a lot!

**Comment by mattbarrett98** [comment]
Thanks for contributing!

**Comment by VedPatwardhan** [comment]
Thank you for your continued guidance throughout!

**Pull request merged**
