### PR TITLE
feat: add is_tensor to tensorflow frontend general functions

### LINKED ISSUE #7584: is_tensor

### PR DESCRIPTION
**Pull request by chtnnh**
Close #7584
Need help with PyTest, I am unable to wrap my head around the testing helpers yet.

Essentially, when I run these tests, I get the same error, despite trying various combinations of the parameters passed to the `test_frontend_function`

### CODE REVIEW

**Comment by chtnnh** [comment]
Close #7584

**Comment by WilliamHirst** [comment]
Hi, 
Thank you for making a contribution! Before I look into the test issues, could you please fix the merge conflict?

And also, to closer study what is going wrong, have a look at the test-log. Specifically the test-frontend. Simply click the "check details", then go into the "Run Frontend Tests", and search for the function you are working on (is_tensor). 

Let me know when there are no conflicts😊

**Comment by chtnnh** [comment]
Hey @WilliamHirst, I have resolved the merge conflicts, the pace at which Ivy is developing, it's hard to avoid merge conflicts!

I'm on VSCode on an Ubuntu VM. Where can I find "check details" you mentioned previously?

**Comment by WilliamHirst** [comment]
Great job!

You can find the test log in the PR. You will find it right under the comment-section.

**Comment by chtnnh** [comment]
> You can find the test log in the PR. You will find it right under the comment-section.

My bad, I thought you were talking about an IDE feature.

I went through the details like you said, but am having a hard time placing it in context. Should I try for longer?

**Comment by chtnnh** [comment]
@WilliamHirst @Ishticode I have gone through test logs, a few observations:
1. Most of the failing tests are not related to my function, should I be concerned with fixing these?
2. I went through the documentation on the testing helpers, but might've missed something important because I am not able to figure out what exactly is going on when the test runs.

Could you point me in the right direction?

**Comment by chtnnh** [comment]
@Ishticode just a ping on this! would love to get this merged before the breaking changes are introduced!

**Comment by WilliamHirst** [comment]
First of do not have to worry about the failing tests that are not related to your function. 

You should can find the relevant error by going into "Run Frontend Tests", then cmd+F and search for "Falsifying example: test_tensorflow_<FUNCTION NAME>.

In you case it simply seems that the test is failing, i.e that the function does not return the same result when calling different backend. 

Have a little dive into what exactly you are sending the test as well as making sure that all parameters make sense.

**Comment by chtnnh** [comment]
> Have a little dive into what exactly you are sending the test as well as making sure that all parameters make sense.

Gotcha, working on that!

Thank you for the response @WilliamHirst

**Comment by WilliamHirst** [comment]
No problem!😊

**Comment by chtnnh** [comment]
Hey @WilliamHirst 

I have tried various combinations of input parameters to both my testing function and my implementation of `is_tensor`

I am unsure what the issue is so far, if you could point me in the right direction with that, I might be able to wrap this up today!

Thank you

**Comment by WilliamHirst** [comment]
Without diving deeply into the changes, it is hard to say. My only thought is to try to put the as_variable_flags to False, as I remember reading that this caused some failing tests in a similar function. It was done in this commit: https://github.com/unifyai/ivy/commit/5214a772915b2b6a898dc681d5d5edecf2343ca5

**Comment by chtnnh** [comment]
Hey @WilliamHirst sorry for the delay, I will get back to you on this in 24 hours!

**Comment by WilliamHirst** [comment]
No problem, dont stress!😊

**Comment by chtnnh** [comment]
Hey @WilliamHirst

I tried what you suggested by setting `as_variable` to False, that didn't seem to work. I'm really confused as to what I can try now. I tried setting values for the other variables as well, in many different permutations 😖 to no help

Sorry for stretching this out so long

**Comment by WilliamHirst** [comment]
No problem, sometimes one can get stuck!😊

Quick question, is there a reason why you are calling the ivy.is_native_array? In the torch implementation of the function, we are using ivy.is_array?

**Comment by chtnnh** [comment]
> No problem, sometimes one can get stuck!😊
> 
> Quick question, is there a reason why you are calling the ivy.is_native_array? In the torch implementation of the function, we are using ivy.is_array?

Hey @WilliamHirst, that was the issue I think, the tests are now passing!

My bad, I didn't find `ivy.is_array`, this could've been a much simpler experience

Nevertheless, thank you so much!

**Pull request merged**
