### PR TITLE
reformat lars_update

### LINKED ISSUE #25688: lars_update

### PR DESCRIPTION
**Pull request by Abhinav-CHD**
# Added functional examples to the lars_update function resolves #25688

##  Reformat gradients #776 

Close  #25688 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Abhinav-CHD** [comment]
Hey I believe some of the test cases are not passing. Could you please help me with that?

**Review by vedpatwardhan — COMMENTED** [review]
The changes look good to me, but I'll leave this with @RickSanchezStoic to review as he's assigned to the PR (the automation auto-requested my review due to changes to the gradients files). Thanks @Abhinav-CHD 😄

**Comment by Abhinav-CHD** [comment]
@vedpatwardhan Thank you. It was an honor to contribute to Ivy.

**Comment by RickSanchezStoic** [comment]
lgtm!

**Pull request merged**
