### PR TITLE
update API standardization for "qr" in tf, torch, np, and jax

### PR DESCRIPTION
**Pull request by matthewclso**
"qr" has been implemented, however, there are still errors, because "triu" has not been implemented for any framework (or maybe there's some other issue I'm not catching).  Submitting PR for feedback.

### CODE REVIEW

**Comment by matthewclso** [comment]
Attaching the error for reference:

`./ivy_tests/test_array_api/array_api_tests/test_linalg.py::test_qr Failed: [undefined]AssertionError: triu is not defined in ivy.functional.backends.tensorflow
@pytest.mark.xp_extension('linalg')
>   @given(
        x=xps.arrays(dtype=xps.floating_dtypes(), shape=matrix_shapes()),
        kw=kwargs(mode=sampled_from(['reduced', 'complete']))
    )

ivy_tests/test_array_api/array_api_tests/test_linalg.py:418: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy_tests/test_array_api/array_api_tests/test_linalg.py:451: in test_qr
    assert_exactly_equal(R, _array_module.triu(R))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <undefined stub for 'triu'>
args = (<tf.Tensor: shape=(0, 1, 1), dtype=float32, numpy=array([], shape=(0, 1, 1), dtype=float32)>,)
kwargs = {}

    def _raise(self, *args, **kwargs):
>       raise AssertionError(f"{self.name} is not defined in {mod_name}")
E       AssertionError: triu is not defined in ivy.functional.backends.tensorflow

ivy_tests/test_array_api/array_api_tests/_array_module.py:52: AssertionError`

**Comment by matthewclso** [comment]
This PR address issue #455

**Comment by matthewclso** [comment]
I have also implemented the triu function in Array API Standard such that the qr function no longer comes across that error (triu is tracked in #60 ).
The test_qr test now passes locally, but CI is still failing since the remainder function is not implemented.  I noticed someone else has already opened an issue for that so I'm leaving it.

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @matthewclso , thanks for the pull request. Can you uncomment the tests for qr and triu? You can do that by uncommenting the names of the functions in the corresponding files in the array_api_methods_to_test folder which you can find in the ivy_tests folder.

**Review by saeedashrraf — COMMENTED** [review]
There are 327 changed files in the commit. Unfortunately, rebasing the branch did not fix this issue. To be able to approve the pull request, you need to create a new pull request and make sure to add and commit only the exact changes that you made. Make sure that no other changes are added along with your commit.  Thank you for your efforts.

**Comment by matthewclso** [comment]
@saeedashrraf Apologies, apparently my IDE was making some changes to files I wasn't working on due to formatting or something.  Have submitted new PR #545 for review.

**Pull request closed without merging**
