### PR TITLE
added instance method for torch frontend logaddexp function

### LINKED ISSUE #19620: logaddexp

### PR DESCRIPTION
**Pull request by Amritds**
Close #19620

### CODE REVIEW

**Comment by Amritds** [comment]
ivy-gardener

**Comment by Amritds** [comment]
@D0m-inic Could you please review this?

**Comment by Amritds** [comment]
ivy-gardener

**Comment by D0m-inic** [comment]
Looks good to me. If you could just add the `backend_to_test` parameter to `test_frontend_method`.

**Comment by Amritds** [comment]
Hi @D0m-inic Thanks! I have added the backend_to_test parameter. Could you please check now?

**Comment by D0m-inic** [comment]
ivy-gardener

**Comment by D0m-inic** [comment]
Looks good 👍

**Pull request merged**
