### PR TITLE
chore: add contributors map

### PR DESCRIPTION
**Pull request by a0m0rajab**
This PR is using the [contributor map action](https://github.com/tunaitis/contributor-map) to build a map and update the one in the repo every Monday:

### CODE REVIEW

**Comment by YushaArif99** [comment]
Hi @a0m0rajab 

Apologies for getting back so late. Was quite busy with some ongoing tasks and so reviewing this PR totally slipped under my radar 😅. 

Thanks for this contribution. I think it's a pretty cool feature to add to our repo 👌🏼. But before I merge this PR, let me take a second opinion on this since I am not an expert when it comes to CI workflows

**Comment by YushaArif99** [comment]
@RashulChutani, could you kindly take a look at this PR since you're more familiar with GitHub actions 🙂

**Comment by RashulChutani** [comment]
Hi @YushaArif99, Sure, I will have a look.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by a0m0rajab** [comment]
@RashulChutani @YushaArif99 is there anything I need to do for this?

**Pull request closed without merging**
