### PR TITLE
Add paddle.nn.functional.vision.channel_shuffle to Paddle Frontend

### LINKED ISSUE #20119: channel_shuffle

### PR DESCRIPTION
**Pull request by zawyar**
close #20119

### CODE REVIEW

**Comment by Infrared1029** [comment]
Hey @zawyar, looks good to the most part, lets get the linting errors fixed before merging

**Comment by zawyar** [comment]
Hey @Infrared1029, The linting is done. We're good to go.

**Comment by zawyar** [comment]
@Infrared1029 gentle reminder.

**Comment by Infrared1029** [comment]
The tests seem to fail, did you run the tests locally and confirm that the tests are all green? I'd be happy to take a closer look when you confirm this (or when you get stuck completely)

**Comment by zawyar** [comment]
@Infrared1029 the tests are all green for my local. It's just that my branch had gone out of sync. I've merged with the upstream ivy repo and the tests should be all green now.

**Comment by a0m0rajab** [comment]
@zawyar could you rebase the branch to the one we have? this way you would solve the conflict,

**Comment by zawyar** [comment]
Sure, I'll do it right away

**Comment by zawyar** [comment]
Done.

**Comment by zawyar** [comment]
@a0m0rajab

**Comment by a0m0rajab** [comment]
Thanks, for that! if you do a rebase the conflict would be resolved, can you  ensure that they are resolved? 
And if it's resolved we can wait for yasser, he will get back to your PR as long as he finishes his queue work.

**Comment by Ishticode** [comment]
Already implemented in https://github.com/unifyai/ivy/pull/22393

**Pull request closed without merging**
