### PR TITLE
Pending changes exported from your codespace

### PR DESCRIPTION
**Pull request by Akashsingh310**

### CODE REVIEW

**Comment by nathzi1505** [comment]
Hi @CatB1t, would you mind reviewing this?

**Review by CatB1t — COMMENTED** [review]
Hello @Akashsingh310, can you write more details about the rationale of having this change? these flags are used in strategies generation, I don't think we should have them being passed to function `setup_frontend_test`

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
