### PR TITLE
bitwise right shift

### PR DESCRIPTION
**Pull request by VedPatwardhan**

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
The majority of the tests are still failing, please could you amend the functions such that all the tests pass. It seems you haven't implemented the functions `__rshift__` and `__irshift__` which is responsible for some of the failures. Thanks 🙂

**Comment by VedPatwardhan** [comment]
@mattbarrett98 Sure, I'll implement those functions, thank you for responding.

**Comment by VedPatwardhan** [comment]
@mattbarrett98 I implemented the `__rshift__`, `__irshift__`, and `__rrshift__` functions, but the tests are still failing, please have a look and guide me about where I'm going wrong here.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hi, before we look any further into the double underscore methods, could you make sure the `bitwise_right_shift` tests pass. It looks like some of them are failing because the datatype of the output is incorrect. Please could you alter the functions such that the outputs are of the correct datatype https://data-apis.org/array-api/latest/API_specification/generated/signatures.elementwise_functions.bitwise_right_shift.html?highlight=bitwise#signatures.elementwise_functions.bitwise_right_shift.

**Comment by VedPatwardhan** [comment]
@mattbarrett98 I've added code for getting few tests passing, what should I do next to get all tests passing?

**Comment by VedPatwardhan** [comment]
@mattbarrett98 I've updated the code so that all the tests are passing and have also resolved the conflicts, please have a look.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hi, it looks like things haven't gone very smoothly when merging changes from the master, and it's showing a large number of edits under 'files changed'. I think the easiest thing to do now is for you to re-fork the repo, re-add your changes associated with `bitwise_right_shift` and make another pull request (and request my review). Thanks 🙂

**Comment by VedPatwardhan** [comment]
Sure, I'll create a new PR and request your review there.

**Pull request closed without merging**
