### PR TITLE
feat: add eigval function to ivy api

### PR DESCRIPTION
**Pull request by sounritesh**

### CODE REVIEW

**Comment by sounritesh** [comment]
resolves #5438

**Comment by kimbring2** [comment]
@sounritesh Hello, thank you for your contribution. I check several errors in your code.

The first thing is to add the eigvals function to the extension.py file under the array, container folder of Ivy.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by sounritesh** [comment]
Still trying to figure out the issue

**Comment by JamieLine** [comment]
Hi!

Because I've just been assigned, I'm not up to speed on how this PR is going, is there anything you'd like help with?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
