### PR TITLE
Update nest.py

### LINKED ISSUE #22589: <insert_into_nest_at_index>

### PR DESCRIPTION
**Pull request by MahadShahid8**
Implemented doc strings for better understanding of the code

# PR Description 
Implemented some doc strings for better understanding of the code

## Related Issue 

Close #22589 

## Checklist 

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ]Yes Did you follow the steps we provided?

### CODE REVIEW

**Comment by MahadShahid8** [comment]
@DecFox kindly review my pr

**Comment by MahadShahid8** [comment]
@DecFox

**Comment by DecFox** [comment]
Hey @MahadShahid8 thanks for the PR. Sorry for the delay in the review. Left some comments to take care of before we can merge. 
Thanks!

**Comment by MahadShahid8** [comment]
@DecFox I see that you are saying that you have left some changes to take care of, but there aren't any comments related to changes. Kindly reply as soon as you can :)

**Review by DecFox — CHANGES_REQUESTED** [review]

**Comment by MahadShahid8** [comment]
@DecFox the issue has been resolved. Kindly review the changes as soon as you can :)

**Comment by DecFox** [comment]
LGTM!

**Pull request merged**
