### PR TITLE
Vishwasg217/max unpool ivy api

### LINKED ISSUE #22111: <max_unpool1d>#22110

### PR DESCRIPTION
**Pull request by vishwasg217**
Close #22111
added max_unpool ivy API functions along with it's PyTorch frontend functions

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by vishwasg217** [comment]
@Infrared1029 @ivy-leaves what am I supposed to do next?

**Comment by vishwasg217** [comment]
@Infrared1029 , @ivy-leaves ?? please help me out

**Comment by Infrared1029** [comment]
Hi @vishwasg217, reviewing PRs can take up to ~4 work days (so weekends are excluded), sometimes might take even more as team members work on other tasks internally besides the reviews

Looking at the PR, you will have to properly add the `unpool` function to the backends before calling it in the frontends, i'd suggest creating separate PRs for both tasks, one PR that involves adding the `unpool` function to the backends (either doing it compositionally or as primary functions to all backends), and another PR where you implement the torch frontend one. Adding `return current_backend().unpool` does not add the function to the backend, you need to write the logic.

**Comment by vishwasg217** [comment]
Hey, 
thank you for responding. Okay, I think I understand the issue., I didn't realize the `unpool` functions didn't exist in the backend itself. Can I work on only the Pytorch backend `unpool` functions for now? 

Also, I apologize if seemed a bit pushy. Thank you for your time.

**Comment by Ishticode** [comment]
Thaks for the PR @vishwasg217 
It seems like we will have to close the PR as the calls ivy.max_unpool2d are invalid as they currently don't exist as rightly pointed out by @Infrared1029 who made some recommendations above but no change has been made. 
Please feel free to reopen, update or open another PR if you feel like that the right way. Thanks

**Pull request closed without merging**
