### PR TITLE
Revert "Implemented precision_score function in _classification.py and Added …"

### PR DESCRIPTION
**Pull request by zeus2x7**
Reverts unifyai/ivy#23277

### CODE REVIEW

**Comment by zeus2x7** [comment]
hi @hello-fri-end  can you please revert the pr merged as it is not complete and accurate implementation of precision_score as in sklearn

**Comment by zeus2x7** [comment]
hi @hello-fri-end  can you please look into the pr it would be a lot helpful

**Comment by hello-fri-end** [comment]
Hey @nathzi1505, could you please take a look at this? It seems you were assigned to the `precision_score` PR and you would have a lot more context about this than I do. Thanks.

**Comment by zeus2x7** [comment]
hi @nathzi1505  can you please revert it as it is not complete and accurate implementation of precision_score as in sklearn

**Comment by zeus2x7** [comment]
@nathzi1505  it would be great if you could review the pr.

**Pull request merged**
