### PR TITLE
Reformat Function Elementwise Log10

### LINKED ISSUE #1984: log10

### PR DESCRIPTION
**Pull request by utsavk28**
fixes #1984

### CODE REVIEW

**Comment by utsavk28** [comment]
@RashulChutani @djl11 Can you please review this PR?

**Comment by utsavk28** [comment]
Hey @Auxia, can you please review my PR

**Comment by Auxia** [comment]
Hi! I had a look through your changes and I amm not sure why you deleted the parameters and returns from the docstrings. Was this by accident? I'd request you to reset those two paragraphs.

**Comment by utsavk28** [comment]
Hey @Auxia, I have added the Parameters & Returns back in Docstrings.
Are there any more changes?

**Comment by Auxia** [comment]
Yeah it looks good, docstring tests are passing as well. Thanks for contributing to Ivy :)

**Pull request merged**
