### PR TITLE
Update linalg.py

### PR DESCRIPTION
**Pull request by 11Kclarke**
#5972

### CODE REVIEW

**Comment by JoelPendleton** [comment]
@11Kclarke Could you please add a test for the code you have written to the [test_jax_lax_linalg.py] file(https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_linalg.py)?

**Comment by 11Kclarke** [comment]
Hi, 
I've added a test function, is this ok?

**Comment by 11Kclarke** [comment]
Hi @JoelPendleton, can I have some guidance on what more needs to be done to complete this?

**Comment by JoelPendleton** [comment]
Hi @11Kclarke you need to modify your code so that you're implementing ```jax.numpy.linalg.matrix_power``` not ```jax.lax.linalg.matrix_power```.  In other words, you're implementing on the wrong namespace and need to move your code to a different file, i.e. _ivy/functional/frontends/jax/numpy/linalg.py_.

**Comment by 11Kclarke** [comment]
Hey, 
Like this?

**Comment by JoelPendleton** [comment]
Hi, you were almost there with your implementation. The mistakes you made were:

- You forgot to change the name space of your function from jax.lax to jax.numpy throughout, e.g. I corrected `fn_name="ivy.functional.frontends.jax.lax.linalg.matrix_power"` to `fn_name="ivy.functional.frontends.jax.numpy.linalg.matrix_power"`.
- I also changed the function's parameter `x` to `a` to reflect the [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.matrix_power.html).
- I added a `filter` method to the `helpers.dtype_and_values` method.
- Finally, I added some tolerances when testing the function. 

Thanks for contributing to Ivy :) We really appreciate your help!

**Pull request merged**
