### PR TITLE
Better run_tests.sh

### PR DESCRIPTION
**Pull request by gjvnq**
I modified the `./run_tests.sh` script to include a help message as well as the possibility of running specific tests and of passing arguments to pytest.

The new interface is compatible with the previous one. That is, calling the script without passing any parameters runs all tests under `ivy_tests/`.

### CODE REVIEW

**Comment by bicycleman15** [comment]
Hey @gjvnq , thanks a lot for taking the time to improve our testing suite. 

This looks great !
We were actually planning to do this, however it got lost somewhere in the endless task list 😅 

I am looping in @djl11.
What do you think about this Dan ?

**Comment by bicycleman15** [comment]
Also @gjvnq, could you give some example usage of your changes to the `run_tests.sh` if possible 🙂  ?

**Comment by gjvnq** [comment]
Just run the script with `-h` and it will print a few usage examples.

**Review by djl11 — APPROVED** [review]
lgtm!

**Pull request closed without merging**
