### PR TITLE
feat: added arguments and docstrings to the functions for superset behavior

### PR DESCRIPTION
**Pull request by Aaryan562**
This PR is for the trello card https://trello.com/c/71MXGtPF.

### CODE REVIEW

**Review by HaiderSultanArc — CHANGES_REQUESTED** [review]
Looks like a lot of tests are failing!

**Comment by vedpatwardhan** [comment]
The test failures I think are because of the new `tensorflow` release (as all the `with_[un]supported_[device_and_]dtypes` decorators need to be updated to `2.14.0` instead of `2.13.0`. Let's wait for that to be fixed on `main` (should be done by eod)

**Review by HaiderSultanArc — COMMENTED** [review]
Looks good to me! Let's wait till tests run 😄

**Comment by Aaryan562** [comment]
> Looks good to me! Let's wait till tests run 😄

Which tests are you talking about? CI tests?

**Comment by vedpatwardhan** [comment]
Also, just a side note, it would be good to also update the container methods (`data_classes/container/statistical.py`), the `ivy` function (`ivy/functional/ivy/statistical.py`), all the backends (`ivy/functional/backends/<backend>/statistical.py`) and the tests (`ivy_tests/test_ivy/test_functional/test_core/test_statistcal.py`) to also accomodate the new arguments for these functions. Thanks @Aaryan562  😄

**Review by HaiderSultanArc — COMMENTED** [review]
@vedpatwardhan CI is not picking up tests for this PR still.

**Comment by Aaryan562** [comment]
@vedpatwardhan @HaiderSultanArc In the latest commit tho there are many changes in `data_classes/container/statistical.py` and `ivy/functional/ivy/statistical.py` lets focus on min function. In that I am getting the below error when container flag is set to true:
image
I tried to test it manually and I have added that file also in the commit for your reference I got following homogenous output:
image
What could be the reason for the following error?

**Comment by vedpatwardhan** [comment]
The above example uses the container instance method as `container=[True]` and `instance_method=True`

**Comment by Aaryan562** [comment]
@vedpatwardhan @HaiderSultanArc I will close this PR as there is so much mess. In the next PR I will create we will go function by function adding the arguments and making it pass through the backends.

**Comment by Aaryan562** [comment]
> `container=[True]` and `instance_method=True`

Does that mean I have to add static method for `min`?

**Review by vedpatwardhan — COMMENTED** [review]
> Does that mean I have to add static method for `min`? Also, every function has static method in the folder except min,max,mean so is it mandatory to have static method for the function or are there any certain conditions?

Yep we need to add container instance and static methods for these functions as well 😄

**Pull request closed without merging**
