### PR TITLE
Add jax.numpy.nanpercentile with tests

### LINKED ISSUE #17054: nanpercentile

### PR DESCRIPTION
**Pull request by sashank17**
Close #17054

### CODE REVIEW

**Comment by sashank17** [comment]
Close #17054

**Comment by sashank17** [comment]
I'm not sure why the tests are failing. It would be great if someone could help. Thanks!

**Comment by Ookamice** [comment]
@sashank17 
I'm running a few tests in a codespace manually as it doesn't seem like the intelligent-tests-pr has picked up on your test functions. However, I am not quite sure what the issue is as the error logs aren't too conclusive. There are some instances where the error has arised from ` IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)` due to `swapaxes` so it may be wise to start resolving it from there.

I would recommend making a small python file that tries to the function you have writte, `nanpercentile`, and start with some simple cases first to give a quick sanity check that the underlying logic is correct. Then, it would be a good idea to start exploring more complex edge cases to identify what the issue is.

Let me know if you have any thoughts about this matter and I'll try my best to aid you! 😄

**Comment by sashank17** [comment]
okay thank you! I will try to do that and get back to you asap @Ookamice

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by sashank17** [comment]
@Ookamice I made some changes but the test still fail. I think the error is due to the fact that I don't account for axis greater than 1 in the code. The easiest way to fix this I feel is if someone implements the apply_along_axis function in ivy API. It would also make it a lot easier if percentile/nanquantile was implemented in ivy API

**Comment by Ookamice** [comment]
@sashank17 
It's true that some composite functions require more work than others due to missing functionality in the Ivy API. If you believe Ivy's API is lacking in functionality that will help you and other future coders, feel free to follow the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#creating-an-issue-on-ivy-s-github-using-a-template) on opening an issue regarding "missing function suggestion"

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
