### PR TITLE
squeeze adhering to Array API Standard.

### PR DESCRIPTION
**Pull request by HadIhab**

### CODE REVIEW

**Comment by HadIhab** [comment]
The test for the PyTorch backend passed successfully on my local machine, but it fails here in Github actions is it a problem with the env ?

**Review by Ishticode — APPROVED** [review]
Good to go. Thnx for the contribution : )

**Comment by Ishticode** [comment]
> The test for the PyTorch backend passed successfully on my local machine, but it fails here in Github actions is it a problem with the env ?

That was not a problem with your code.

**Comment by HadIhab** [comment]
> Good to go. Thnx for the contribution : )

All right, you're welcome I'm very happy to contribute in such great projects.

**Pull request merged**
