### PR TITLE
Updated argmin function from searching functions (#216)

### PR DESCRIPTION
**Pull request by shantam-8**
Please review the following updates to the argmin function. The tests are currently failing, as seen by the following error:
image
Hence, could you please help me as to how should I go about this? Thanks in advance!

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @shantam-8 . Great work : )
Could you update with the following changes:
1. Merge your fork upstream
2. Uncomment your function in `ivy_tests/array_api_methods_to_test`
3. Update the docstring in ivy/array_api/searching_functions.py

Could you also provide some details about the error you have posted in your first comment. 
Please request a review from me when you have made the changes : )
Thanks.

**Comment by shantam-8** [comment]
Hello @Ishticode, I hope you are doing well. I have merged the fork and have uncommented my function in array_api_methods_to_test.txt. However, I was not able to find the "ivy/array_api/searching_functions.py" file.  Could you please help me with that? I will update that as soon as possible. Thanks in advance!

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @shantam-8
I am gonna change few things and let u know further

**Review by Ishticode — APPROVED** [review]
lgtm. Thanks for the contribution : )

**Pull request merged**
