### PR TITLE
Vecdot adhering to Array API Standard

### PR DESCRIPTION
**Pull request by odehDanOps**

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Please could you update your fork so it is up to date with the ivy master branch (there were a lot of failing tests at the time you made the PR)

**Comment by odehDanOps** [comment]
> Please could you update your fork so it is up to date with the ivy master branch (there were a lot of failing tests at the time you made the PR)

The fork is updated now

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hi, you haven't implemented `vecdot` for the backends: torch, tensorflow or jax. Also, the test is failing for NumPy so can you try to amend the function such that the test passes. Thanks 🙂

**Comment by odehDanOps** [comment]
> Hi, you haven't implemented `vecdot` for the backends: torch, tensorflow or jax. Also, the test is failing for NumPy so can you try to amend the function such that the test passes. Thanks 🙂

Okay

**Comment by odehDanOps** [comment]
@mattbarrett98 I don't know why the test for Numpy is failing can you check what I am doing wrong before I continue with the implementation of Torch, TensorFlow, and Jax.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
I updated the NumPy function and the test is passing. Hopefully this gives you some inspiration on how to proceed with the other backends 🙂

**Comment by odehDanOps** [comment]
> I updated the NumPy function and the test is passing. Hopefully this gives you some inspiration on how to proceed with the other backends 🙂

Yes, thank you!!

**Pull request merged**
