### PR TITLE
conjugate #13039

### PR DESCRIPTION
**Pull request by AdamBures**
Added a conjugate function to ndarray.py

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hey, thanks a lot for your contribution. Can you check out the contributing guide for formatting the first comment? Meanwhile, I'll take a look at your commits :D

**Comment by V-G-spec** [comment]
I noticed that you haven't written the tests for your function, is there any specific reason for that?

**Comment by AdamBures** [comment]
I forgot, I'll change it ASAP.

**Comment by V-G-spec** [comment]
There are quite a few failing tests. Kindly take a look at these

**Comment by AdamBures** [comment]
I'm kinda stuck with the error. 
It says: : fatal: No url found for submodule path 'models' in .gitmodules
I would really appreciate your help.

**Comment by AdamBures** [comment]
I fixed the submodel error but there are some more errors. I'll try and fix them all.

**Comment by V-G-spec** [comment]
Awesome! Keep up the great work

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by AdamBures** [comment]
I'm gonna take a look on it as soon as possible.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by V-G-spec** [comment]
👍🏼

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
