### PR TITLE
eye

### PR DESCRIPTION
**Pull request by HotzingTone**

### CODE REVIEW

**Review by djl11 — CHANGES_REQUESTED** [review]
The tests for TensorFlow and PyTorch are failing. Once these are passing I'll then merge :)

**Comment by HotzingTone** [comment]
Thanks Dan!
Tests on my computer never work probably, but I'll try.

**Review by djl11 — CHANGES_REQUESTED** [review]
Why has matrix power been added as well? Also could you please uncomment  the eye method from the .txt files so that it's included in the tests? :)

**Comment by HotzingTone** [comment]
Sorry! matrix_power was accidentally added, now removed.
Also eye is included in the tests now.

**Review by djl11 — CHANGES_REQUESTED** [review]
It seems as though the NumPy tests are the only ones passing. Could you make any updates so the other framework tests also pass?

**Review by djl11 — CHANGES_REQUESTED** [review]
JAX test seems to be failing, could you try and get this passing? :)

**Comment by HotzingTone** [comment]
> 

It's weird that JAX used to pass when I request the review, but now it doesn't.

**Comment by HotzingTone** [comment]
@djl11 So now all tests passed. But what I did was just rerun the test, no code changed :)

**Pull request merged**
