### PR TITLE
Added function "select_scatter"

### LINKED ISSUE #18167: select_scatter

### PR DESCRIPTION
**Pull request by sanju4725**
Close #18167

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by sanju4725** [comment]
#18167

**Review by theRealBird — CHANGES_REQUESTED** [review]
Hi @sanju4725,

Thank you so much for contributing to Ivy. To make sure Ivy is accurate and works the way it is meant to, we implement test functions for every frontend function we implement.

Could you please add the corresponding test function for `select_scatter`? Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
