### PR TITLE
Added another function characteristic_equation_solver

### PR DESCRIPTION
**Pull request by Sarath2206**
kronecker_product
Add support for calculating the Kronecker product of two matrices, which creates a block matrix with entries from both matrices.

characteristic_equation_solver
Implement a function that finds the coefficients of the characteristic polynomial of a matrix, enabling you to solve for eigenvalues.

### CODE REVIEW

**Comment by Sarath2206** [comment]
- [kronecker_product] #7479
- [characteristic_equation_solver] #7479 
 
https://github.com/unifyai/ivy/issues/7479

**Comment by jkeane508** [comment]
> * [kronecker_product] [Add Linear Algebra operations to PyTorch frontend #7479](https://github.com/unifyai/ivy/issues/7479)
> * [characteristic_equation_solver] [Add Linear Algebra operations to PyTorch frontend #7479](https://github.com/unifyai/ivy/issues/7479)
> 
> #7479

Hey, 

For these issues to be closed on the list, you need to open new issues so I can link them to this PR. You can check out the docs here to see - https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues

Thanks,
James

**Comment by Sarath2206** [comment]
I've added the issue. COuld you check it please.

**Comment by jkeane508** [comment]
> I've added the issue. COuld you check it please.

Could you please link it?

**Comment by Sarath2206** [comment]
fixes unifyai/ivy#16094

**Comment by Sarath2206** [comment]
I have linked the PR to the issue.
https://github.com/unifyai/ivy/issues/16094

Please have a look at it

**Comment by Sarath2206** [comment]
image


@jkeane508  Can you please check the image and the error? It is due to the other function, ```multi_dot```. Also, can you confirm if my commit regarding the ```characteristic_equation_solver``` is fine and if the code is working?

**Comment by jkeane508** [comment]
> I have linked the PR to the issue. #16094
> 
> Please have a look at it

I don't believe this is the correct way to open an issue for PRs. I would refer to guides here on the youtube channel - https://www.youtube.com/playlist?list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG

**Comment by Sarath2206** [comment]
#16175

**Comment by Sarath2206** [comment]
Sorry for the inconvenience caused. COuld you please check it now? If there is still any further discrepancy, can you please guide me through that.

**Review by jkeane508 — CHANGES_REQUESTED** [review]
For this PR, you would also need to implement a test in the relevant section of the testing suite and have it pass before we can merge :)

I would refer to the docs and the youtube if you get stuck :)

Thanks!

**Comment by Sarath2206** [comment]
Thanks for the update! I would work on that.

**Comment by Sarath2206** [comment]
@jkeane508  Can you please guide me on where to submit the test suite? And should we be using the helper functions from https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html

**Comment by Sarath2206** [comment]
@jkeane508 I have added the respective hypothesis testing in the test_torch/test_linalg.py

Can you please check it and re-verify the pull request?

**Review by jkeane508 — COMMENTED** [review]
Hey,

Could you please resolve the merge conflicts on your branch?

Thanks,
James

**Comment by jkeane508** [comment]
> 

Yea you can just separate them out so that one isn't overwriting the other :)

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey, it appears that you have deleted solve_ex and the test for it. Could you please add these back in?

Thanks!

**Comment by Sarath2206** [comment]
I have added them back!!

Thanks.

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey,

Starting to look good, no failing tests which is a good sign.

There are a few formatting changes needed, but should be good to merge after!

Thanks!

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey,

It looks like lint tests still aren't passing, I would recomend installing a pre-commit hook as outlined in the docs [here](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit)

Thanks!

**Comment by Sarath2206** [comment]
@jkeane508 I have made the necessary changes and also passed all the pre-commit hooks. Please check it once!
image

Thanks! 👍

**Comment by Sarath2206** [comment]
Thanks @jkeane508!!

**Pull request merged**
