### PR TITLE
EHN: adding isfinite inpaddle.tesnor.tensor.tesnor

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
adding isfinite inpaddle.tesnor.tensor.tesnor from this issue #17052

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MuhammadNizamani** [comment]
Sir issue is asdedt

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MuhammadNizamani** [comment]
@khushi-411  can you review this PR please because MahmoudAshraf97  no longer review fronted PR

**Review by khushi-411 — APPROVED** [review]
Great! All tests are passed now. Thanks for the nice work @MuhammadNizamani!

**Pull request merged**
