### PR TITLE
Implemented sigmoid for mindspore frontend

### PR DESCRIPTION
**Pull request by rishabh0098**
#17800

### CODE REVIEW

**Comment by rishabh0098** [comment]
@V-G-spec please review.

**Comment by V-G-spec** [comment]
Hey @rishabh0098 thanks for your contribution!
Can you check out the failing tests once? Also, without going into your changes, there should be changes in 2 files- the function and its test function

Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
