### PR TITLE
Implemented jax numpy gradient in the jax frontend

### LINKED ISSUE #18237: gradient

### PR DESCRIPTION
**Pull request by umilic16**
Close #18237

### CODE REVIEW

**Comment by umilic16** [comment]
Hi @juliagsy can you review this PR, and help me figure out how to fix the test?

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey there! Apologies for the delayed review and thanks for contributing! Please sample all arguments to be tested in the tests, then please make sure they are all passing, thanks!

**Comment by umilic16** [comment]
For some reason occasionally it throws:
E           TypeError: gradient() got an unexpected keyword argument 'varargs'
Sometimes it says its an unexpected argument sometimes its fine and I cant manage to figure out why is that happening. It wasn't throwing that error for a while, I was trying to fix some other errors and then suddenly it started throwing it again but I didn't change anything related to varargs so I don't know how.

**Comment by umilic16** [comment]
when edge_order is none it throws
           File "/opt/fw/mxnet/numpy/lib/function_base.py", line 1188, in gradient
               if edge_order > 2:
           During the handling of the above exception, another exception occurred:
            '>' not supported between instances of 'NoneType' and 'int'

when edge order is not none it throws
      if edge_order is not None:
>       raise NotImplementedError("The 'edge_order' argument to jnp.gradient is not supported.")
/opt/fw/jax/jax/_src/numpy/lax_numpy.py:720: UnfilteredStackTrace

**Comment by umilic16** [comment]
Can you help me out, let me know what I'm missing? @juliagsy

**Comment by juliagsy** [comment]
Hey! Apologies for the delayed response, the notifications slipped through somehow. I'll test it out myself and see what's the issue there, will get back to you soonest possible! Thanks!

**Review by juliagsy — CHANGES_REQUESTED** [review]

**Comment by umilic16** [comment]
@juliagsy I had that signature too but it was giving me the same error, but I tried again anyway and I'm still getting the same error:
TypeError: gradient() got an unexpected keyword argument 'varargs'

Even when I use some example from the function definition as test values like:
>>> f = np.array([1, 2, 4, 7, 11, 16], dtype=float)
>>> varargs = 2

**Comment by juliagsy** [comment]
Hey! So because that's a positional variable argument, here's an example of a test with similar behaviour, please refactor the test similar to the behaviour, thanks!
https://github.com/unifyai/ivy/blob/251355d972119c132add944148c3e63925cf5e10/ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py#L409
the ref frontend function is tf einsum, `varargs` is not a valid argument in this case is expected, thanks!

**Comment by juliagsy** [comment]
Hey! Would you mind to resolve the conflicts in the pr first? I'll review soon after, thanks!

**Pull request merged**
