### PR TITLE
add max_pool3d to pytorch frontend

### LINKED ISSUE #22024: max_pool3d

### PR DESCRIPTION
**Pull request by progs2002**
close #22024

### CODE REVIEW

**Comment by paulaehab** [comment]
HI @progs2002  Thanks for contributing could please add the tests for your frontend function please follow this guide: (https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html )

**Comment by progs2002** [comment]
@paulaehab I have implemented a test for the function. Could you please take a look at this?

**Comment by paulaehab** [comment]
Hi @progs2002 Great work 👍 but you have to run the tests and make it successful run I tested the function, and it fails in all backends 
image
as you can see, the error is because the output and input size

**Comment by progs2002** [comment]
Had some issues with the merge, I'll make the necessary changes.

**Comment by progs2002** [comment]
@paulaehab The tests are passing now except for the paddle backend (as max pooling with dilation is not currently supported). Can you please take a look?

**Comment by paulaehab** [comment]
> @paulaehab The tests are passing now except for the paddle backend (as max pooling with dilation is not currently supported). Can you please take a look?

yeah nice work I just need you to keep the file changes only of this function please un commit the changes in (devcontainer and torch comparison_ops.py) and I will merge it.

**Comment by progs2002** [comment]
@paulaehab Yep, it's done.

**Comment by paulaehab** [comment]
Hi @progs2002  lgt thanks for contributing 😄

**Pull request merged**
