### PR TITLE
Added relu function to PyTorch frontend

### PR DESCRIPTION
**Pull request by AymenSe**
I have added the relu function to PyTorch frontend.

### CODE REVIEW

**Comment by AymenSe** [comment]
@MarShaikh could you review the added code please, for further improvement?

**Comment by kimbring2** [comment]
@AymenSe I do not meet any errors during the test. Looks fine!

**Comment by AymenSe** [comment]
@ivy-seed @1Doomdie1 @djl11 
Please someone review my PR! it's been 6 days since my first commit. I think @MarShaikh is offline these days.

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Could you just remove the `.idea` files? Could you also fix the lint errors as well? You can just use `pre-commit` to simplify your task! You can find more info. in our docs. Thanks!

**Comment by AymenSe** [comment]
@MarShaikh I have deleted the folder.

**Comment by AymenSe** [comment]
@MarShaikh could you please review my changes?

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Looks good! Could you just resolve the merge conflicts so I can merge this PR as well? Thanks!

**Comment by AymenSe** [comment]
@MarShaikh i don't have access to resolve them!
image

**Comment by AymenSe** [comment]
Sorry i accidentally deleted this pull repo, the new repo here: #3179

**Pull request merged**
