### PR TITLE
feat: added paddle chunk method with test

### LINKED ISSUE #24169: chunk

### PR DESCRIPTION
**Pull request by olaoluwaidowu**
# PR Description

Added chunk method

## Related Issue

Close #24169

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by olaoluwaidowu** [comment]
I am new, please let me know if there is something I need to do.
My frontend method tests all passed locally. I had failed pre-commit on some files which I am not sure are associated with my code.

**Comment by olaoluwaidowu** [comment]
I have fixed the pre-commit issues on my files. Thanks

**Comment by danielmunioz** [comment]
@olaoluwaidowu Thanks for the changes!

So sorry for the delay, this one slipped through the cracks!

All tests seem to be passing and arguments seem to be correct! 

LGTM! Merging now! 🚀

**Comment by olaoluwaidowu** [comment]
@danielmunioz , thank you.

**Pull request merged**
