### PR TITLE
Updated unset_with_grads #2354

### PR DESCRIPTION
**Pull request by DrashtySoni**

### CODE REVIEW

**Comment by Daniel4078** [comment]
Some changes is needed. Firstly, the code lack proper formatting as exposed by flake8 tests. Secondly, the docstrings also have formatting issues as described in the tests. Thanks!

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Some changes is needed. Firstly, the code lack proper formatting as exposed by flake8 tests. Secondly, the docstrings also have formatting issues and do not have the correct examples required in the contributers guide. Thanks!

**Comment by DrashtySoni** [comment]
@Daniel4078 Fixed the changes in [https://github.com/unifyai/ivy/pull/2593/commits/f925eb438ca67a1ccac471d9d03effb468f23e33](url)

**Comment by Daniel4078** [comment]
just a small tip, you can request a fresh review from a reviewer by click the refresh icon in the Reviewers section of the sidebar of the Conversation tab. Now I will wait till all the checks on the pull request are done and then decide if there is any more problem.

**Review by Daniel4078 — APPROVED** [review]
I found nothing wrong here and I think it is good for merge. Thank you.

**Pull request merged**
