### PR TITLE
#19185

### PR DESCRIPTION
**Pull request by Obony**
#ToDo: Fixes func_wrapper.py_ivy.nested_nth_index_where

-[x] Closes an updated version of the _get_first_array function that addresses the ToDo comment in func_wrapper.py file and improves efficiency using the ivy.nested_nth_index_where function.

### CODE REVIEW

**Comment by Obony** [comment]
#19185

I am done with my To Do list.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Obony** [comment]
Done ivy-gardener

**Comment by Obony** [comment]
ivy-gardener

**Review by vedpatwardhan — COMMENTED** [review]
Hey @MahmoudAshraf97, could you please see if the changes to `_get_first_array` in this PR are required? @Obony there's some changes made to the `.idea` folder and some lint failures in the tests, could you please fix those in the meantime? Thanks 🙂

**Comment by MahmoudAshraf97** [comment]
Hi @Obony, seems that the `ivy.nested_nth_index_where` function that you used is still not implemented, feel free to implement it in a new PR if you still want to continue working on this issue, if not, please feel free to contribute to other issues that has `ToDo` label

**Pull request closed without merging**
