### PR TITLE
PR_full_like_implementation

### PR DESCRIPTION
**Pull request by RitujaPawas**
[opened discussion about the errors received locally](https://github.com/unifyai/ivy/discussions/452)

### CODE REVIEW

**Comment by RitujaPawas** [comment]
All tests are passing locally. I have not implemented `mxnet`

**Comment by RitujaPawas** [comment]
Hi @saeedashrraf can you elaborate if any changes are due from my side?

**Comment by saeedashrraf** [comment]
Hello @RitujaPawas , Can you just go through the files changed and remove any unnecessary imports, comments, or indentations? This is probably the result of your repo being a little out of sync with the main one.

**Comment by RitujaPawas** [comment]
Ok @saeedashrraf I will remove the unnecessary imports/indents and update asap!

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hi @RitujaPawas , the failure seems to be cause by the diagonal function which we can ignore for now. However, can you please remove the unnecessary white spaces added to "ivy/functional/ivy/core/general.py" and also, make sure that the only changes in "ivy_tests/array_api_methods_to_test/creation_functions.txt" is the uncommenting of full_like ?

**Comment by RitujaPawas** [comment]
Sure @saeedashrraf I will update asap!

**Comment by RitujaPawas** [comment]
Hi @saeedashrraf , are changes alright now?

**Comment by RitujaPawas** [comment]
@saeedashrraf  any update?

**Review by saeedashrraf — COMMENTED** [review]
Hello @RitujaPawas, This looks ready for merging . Thanks for your efforts. We will just wait for Dan's final confirmation.

**Comment by RitujaPawas** [comment]
Hey @saeedashrraf thankyou so much for your guidance.

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Comment by RitujaPawas** [comment]
Thanks @djl11 and @saeedashrraf!

**Pull request merged**
