### PR TITLE
fix: Reformatted gather to use torch backend for its backend-specific implementation. Updated docstrings.

### PR DESCRIPTION
**Pull request by Kacper-W-Kozdon**
# PR Description

Fixes https://github.com/unifyai/ivy/issues/26498 Updated docstrings with examples in array methods.

## Related Issue

Closes https://github.com/unifyai/ivy/issues/26498

## Checklist

- [ ] ⏩ Did you add a function?
- [ ] ⏩ Did you add the tests?
- [ ] ❌ Did you run your tests and are your tests passing?
- [ ] ✅ Did pre-commit not fail on any check?
- [ ] ✅ Did you follow the steps we provided?

### CODE REVIEW

**Comment by Kacper-W-Kozdon** [comment]
add_reformatting_checklist_general

**Comment by juliagsy** [comment]
Hey @vedpatwardhan, given this is framework implementation related and to make sure the changes doesn't break anything, will the changes in this PR affect any use of `gather`? Thanks!

**Comment by Kacper-W-Kozdon** [comment]
The SOS checks from the checklist are for the docstrings from ivy.Container, more specifically: I'm not sure what the extra arguments of the gather method there (as compared to the general backend implementation's arguments) are supposed to do, so I have not added any examples there. 

On a sidenote: Should all variants of the "result" variable returned by functions be renamed to the "res" suggested in Deep Dive?

**Comment by vedpatwardhan** [comment]
> Hey @vedpatwardhan, given this is framework implementation related and to make sure the changes doesn't break anything, will the changes in this PR affect any use of `gather`? Thanks!

I don't think they should, but I think @AnnaTz should take a look just in case. Also, seems like the `demos` submodule has been updated, @Kacper-W-Kozdon could you please revert changes to it? Thanks 😄

**Comment by Kacper-W-Kozdon** [comment]
> > Hey @vedpatwardhan, given this is framework implementation related and to make sure the changes doesn't break anything, will the changes in this PR affect any use of `gather`? Thanks!
> 
> I don't think they should, but I think @AnnaTz should take a look just in case. Also, seems like the `demos` submodule has been updated, @Kacper-W-Kozdon could you please revert changes to it? Thanks 😄

Hey, @vedpatwardhan - could you double check if it's ok now?

**Comment by AnnaTz** [comment]
> > Hey @vedpatwardhan, given this is framework implementation related and to make sure the changes doesn't break anything, will the changes in this PR affect any use of `gather`? Thanks!
> 
> I don't think they should, but I think @AnnaTz should take a look just in case. Also, seems like the `demos` submodule has been updated, @Kacper-W-Kozdon could you please revert changes to it? Thanks 😄

Hey @vedpatwardhan @Kacper-W-Kozdon, since the PR updates only the torch backend, if the ivy test (`test_gather`) is passing, then the dependent frontend functions should be okay as well.

**Comment by vedpatwardhan** [comment]
> Hey @vedpatwardhan @Kacper-W-Kozdon, since the PR updates only the torch backend, if the ivy test (`test_gather`) is passing, then the dependent frontend functions should be okay as well.

Sounds good, feel free to merge the PR if `test_gather` passes @juliagsy, thanks @Kacper-W-Kozdon @juliagsy @AnnaTz 😄

**Comment by Kacper-W-Kozdon** [comment]
> > Hey @vedpatwardhan @Kacper-W-Kozdon, since the PR updates only the torch backend, if the ivy test (`test_gather`) is passing, then the dependent frontend functions should be okay as well.
> 
> Sounds good, feel free to merge the PR if `test_gather` passes @juliagsy, thanks @Kacper-W-Kozdon @juliagsy @AnnaTz 😄

$ pytest ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather
Fallback to DirectoryBasedExamples
Database unavailable, local caching only !
======================================================= test session starts =======================================================
platform linux -- Python 3.10.12, pytest-8.0.0.dev309+g70f03dbc, pluggy-1.3.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /home/bubble/ivy
plugins: hypothesis-6.88.1
collected 1 item

ivy_tests/test_ivy/test_functional/test_core/test_general.py F                                                              [100%]

============================================================ FAILURES =============================================================
_______________________________________________ test_gather[cpu-numpy-False-False] ________________________________________________

backend_fw = 'numpy', on_device = 'cpu'

    @handle_test(
>       fn_tree="functional.ivy.gather",
        params_indices_others=helpers.array_indices_axis(
            array_dtypes=helpers.get_dtypes("numeric"),
            indices_dtypes=["int32", "int64"],
            min_num_dims=1,
            max_num_dims=5,
            min_dim_size=1,
            max_dim_size=10,
        ),
    )

ivy_tests/test_ivy/test_functional/test_core/test_general.py:1002:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:960: in array_indices_axis
    x_dtype, x, x_shape = draw(
ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw
    return strategy.do_draw(self)
ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py:160: in do_draw
    return data.draw(self.wrapped_strategy)
ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw
    return strategy.do_draw(self)
ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:496: in dtype_and_values
    available_dtypes = draw(available_dtypes)
ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw
    return strategy.do_draw(self)
ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:208: in get_dtypes
    retrieval_fn(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

framework = 'numpy', kind = 'numeric', mixed_fn_dtypes = 'compositional'

    def _get_fn_dtypes(framework: str, kind="valid", mixed_fn_dtypes="compositional"):
        all_devices_dtypes = test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[
            framework
        ]
        if mixed_fn_dtypes in all_devices_dtypes:
            all_devices_dtypes = all_devices_dtypes[mixed_fn_dtypes]
>       return all_devices_dtypes[test_globals.CURRENT_DEVICE_STRIPPED][kind]
E       KeyError: 'cpu'
E
E       You can reproduce this example by temporarily adding @reproduce_failure('6.88.1', b'AA==') as a decorator on your test case

ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:38: KeyError
========================================================= 0.0% of 1 passed ============================================================================================================= short test summary info =====================================================
FAILED ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather[cpu-numpy-False-False] - KeyError: 'cpu'
======================================================== 1 failed in 3.66s ========================================================

The failure does not seem to be related to the changes, I'm not sure yet why "cpu" key would cause a problem, especially because test_gather starts from numpy. Is there an easy way to check just the torch backend?

**Comment by AnnaTz** [comment]
> > > Hey @vedpatwardhan @Kacper-W-Kozdon, since the PR updates only the torch backend, if the ivy test (`test_gather`) is passing, then the dependent frontend functions should be okay as well.
> > 
> > 
> > Sounds good, feel free to merge the PR if `test_gather` passes @juliagsy, thanks @Kacper-W-Kozdon @juliagsy @AnnaTz 😄
> 
> $ pytest ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather Fallback to DirectoryBasedExamples Database unavailable, local caching only ! ======================================================= test session starts ======================================================= platform linux -- Python 3.10.12, pytest-8.0.0.dev309+g70f03dbc, pluggy-1.3.0 backend(s): all device: cpu number of Hypothesis examples: 25 rootdir: /home/bubble/ivy plugins: hypothesis-6.88.1 collected 1 item
> 
> ivy_tests/test_ivy/test_functional/test_core/test_general.py F [100%]
> 
> ============================================================ FAILURES ============================================================= _______________________________________________ test_gather[cpu-numpy-False-False] ________________________________________________
> 
> backend_fw = 'numpy', on_device = 'cpu'
> 
> ```
> @handle_test(
> ```
> 
> > ```
> >   fn_tree="functional.ivy.gather",
> > ```
> 
> ```
>     params_indices_others=helpers.array_indices_axis(
>         array_dtypes=helpers.get_dtypes("numeric"),
>         indices_dtypes=["int32", "int64"],
>         min_num_dims=1,
>         max_num_dims=5,
>         min_dim_size=1,
>         max_dim_size=10,
>     ),
> )
> ```
> 
> ivy_tests/test_ivy/test_functional/test_core/test_general.py:1002:
> 
> ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:960: in array_indices_axis x_dtype, x, x_shape = draw( ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py:160: in do_draw return data.draw(self.wrapped_strategy) ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw return self.definition(data.draw, *self.args, **self.kwargs) ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:496: in dtype_and_values available_dtypes = draw(available_dtypes) ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw return self.definition(data.draw, *self.args, **self.kwargs) ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:208: in get_dtypes retrieval_fn(
> 
> framework = 'numpy', kind = 'numeric', mixed_fn_dtypes = 'compositional'
> 
> ```
> def _get_fn_dtypes(framework: str, kind="valid", mixed_fn_dtypes="compositional"):
>     all_devices_dtypes = test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[
>         framework
>     ]
>     if mixed_fn_dtypes in all_devices_dtypes:
>         all_devices_dtypes = all_devices_dtypes[mixed_fn_dtypes]
> ```
> 
> > ```
> >   return all_devices_dtypes[test_globals.CURRENT_DEVICE_STRIPPED][kind]
> > ```
> 
> E KeyError: 'cpu' E E You can reproduce this example by temporarily adding @reproduce_failure('6.88.1', b'AA==') as a decorator on your test case
> 
> ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:38: KeyError ========================================================= 0.0% of 1 passed ============================================================================================================= short test summary info ===================================================== FAILED ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather[cpu-numpy-False-False] - KeyError: 'cpu' ======================================================== 1 failed in 3.66s ========================================================
> 
> The failure does not seem to be related to the changes, I'm not sure yet why "cpu" key would cause a problem, especially because test_gather starts from numpy. Is there an easy way to check just the torch backend?

Hi @Kacper-W-Kozdon, were you in sync with our latest `main` branch when you ran the test? I tried running it on my side and and didn't get that `KeyError`. The test is however failing in the torch backend where your changes are at.

**Comment by Kacper-W-Kozdon** [comment]
> > > > Hey @vedpatwardhan @Kacper-W-Kozdon, since the PR updates only the torch backend, if the ivy test (`test_gather`) is passing, then the dependent frontend functions should be okay as well.
> > > 
> > > 
> > > Sounds good, feel free to merge the PR if `test_gather` passes @juliagsy, thanks @Kacper-W-Kozdon @juliagsy @AnnaTz 😄
> > 
> > 
> > $ pytest ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather Fallback to DirectoryBasedExamples Database unavailable, local caching only ! ======================================================= test session starts ======================================================= platform linux -- Python 3.10.12, pytest-8.0.0.dev309+g70f03dbc, pluggy-1.3.0 backend(s): all device: cpu number of Hypothesis examples: 25 rootdir: /home/bubble/ivy plugins: hypothesis-6.88.1 collected 1 item
> > ivy_tests/test_ivy/test_functional/test_core/test_general.py F [100%]
> > ============================================================ FAILURES ============================================================= _______________________________________________ test_gather[cpu-numpy-False-False] ________________________________________________
> > backend_fw = 'numpy', on_device = 'cpu'
> > ```
> > @handle_test(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > ```
> > >   fn_tree="functional.ivy.gather",
> > > ```
> > 
> > 
> > ```
> >     params_indices_others=helpers.array_indices_axis(
> >         array_dtypes=helpers.get_dtypes("numeric"),
> >         indices_dtypes=["int32", "int64"],
> >         min_num_dims=1,
> >         max_num_dims=5,
> >         min_dim_size=1,
> >         max_dim_size=10,
> >     ),
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ivy_tests/test_ivy/test_functional/test_core/test_general.py:1002:
> > ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:960: in array_indices_axis x_dtype, x, x_shape = draw( ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py:160: in do_draw return data.draw(self.wrapped_strategy) ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw return self.definition(data.draw, *self.args, **self.kwargs) ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:496: in dtype_and_values available_dtypes = draw(available_dtypes) ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw return self.definition(data.draw, *self.args, **self.kwargs) ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:208: in get_dtypes retrieval_fn(
> > framework = 'numpy', kind = 'numeric', mixed_fn_dtypes = 'compositional'
> > ```
> > def _get_fn_dtypes(framework: str, kind="valid", mixed_fn_dtypes="compositional"):
> >     all_devices_dtypes = test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[
> >         framework
> >     ]
> >     if mixed_fn_dtypes in all_devices_dtypes:
> >         all_devices_dtypes = all_devices_dtypes[mixed_fn_dtypes]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > ```
> > >   return all_devices_dtypes[test_globals.CURRENT_DEVICE_STRIPPED][kind]
> > > ```
> > 
> > 
> > E KeyError: 'cpu' E E You can reproduce this example by temporarily adding @reproduce_failure('6.88.1', b'AA==') as a decorator on your test case
> > ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:38: KeyError ========================================================= 0.0% of 1 passed ============================================================================================================= short test summary info ===================================================== FAILED ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather[cpu-numpy-False-False] - KeyError: 'cpu' ======================================================== 1 failed in 3.66s ========================================================
> > The failure does not seem to be related to the changes, I'm not sure yet why "cpu" key would cause a problem, especially because test_gather starts from numpy. Is there an easy way to check just the torch backend?
> 
> Hi @Kacper-W-Kozdon, were you in sync with our latest `main` branch when you ran the test? I tried running it on my side and and didn't get that `KeyError`. The test is however failing in the torch backend where your changes are at.

Hey, @AnnaTz - it seems that the dependancies for the venv were not fully installed on my pc (docker is too heavy for my laptop, so I use WSL). Once it's fixed, I'll check where's the problem with the changes and try to do something about it or eventually ask for some suggestions on what to look for (my guess: before the change, the code in use was a copy of the implementation from the tensorflow's documentation, so it's either about dimensions or types that work with tensorflow but are not supported by torch; or i just made some simple coding mistake in the few lines i changed).

**Comment by Kacper-W-Kozdon** [comment]
> > > > Hey @vedpatwardhan @Kacper-W-Kozdon, since the PR updates only the torch backend, if the ivy test (`test_gather`) is passing, then the dependent frontend functions should be okay as well.
> > > 
> > > 
> > > Sounds good, feel free to merge the PR if `test_gather` passes @juliagsy, thanks @Kacper-W-Kozdon @juliagsy @AnnaTz 😄
> > 
> > 
> > $ pytest ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather Fallback to DirectoryBasedExamples Database unavailable, local caching only ! ======================================================= test session starts ======================================================= platform linux -- Python 3.10.12, pytest-8.0.0.dev309+g70f03dbc, pluggy-1.3.0 backend(s): all device: cpu number of Hypothesis examples: 25 rootdir: /home/bubble/ivy plugins: hypothesis-6.88.1 collected 1 item
> > ivy_tests/test_ivy/test_functional/test_core/test_general.py F [100%]
> > ============================================================ FAILURES ============================================================= _______________________________________________ test_gather[cpu-numpy-False-False] ________________________________________________
> > backend_fw = 'numpy', on_device = 'cpu'
> > ```
> > @handle_test(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > ```
> > >   fn_tree="functional.ivy.gather",
> > > ```
> > 
> > 
> > ```
> >     params_indices_others=helpers.array_indices_axis(
> >         array_dtypes=helpers.get_dtypes("numeric"),
> >         indices_dtypes=["int32", "int64"],
> >         min_num_dims=1,
> >         max_num_dims=5,
> >         min_dim_size=1,
> >         max_dim_size=10,
> >     ),
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ivy_tests/test_ivy/test_functional/test_core/test_general.py:1002:
> > ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:960: in array_indices_axis x_dtype, x, x_shape = draw( ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py:160: in do_draw return data.draw(self.wrapped_strategy) ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw return self.definition(data.draw, *self.args, **self.kwargs) ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:496: in dtype_and_values available_dtypes = draw(available_dtypes) ivy_dev/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw return strategy.do_draw(self) ivy_dev/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1730: in do_draw return self.definition(data.draw, *self.args, **self.kwargs) ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:208: in get_dtypes retrieval_fn(
> > framework = 'numpy', kind = 'numeric', mixed_fn_dtypes = 'compositional'
> > ```
> > def _get_fn_dtypes(framework: str, kind="valid", mixed_fn_dtypes="compositional"):
> >     all_devices_dtypes = test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[
> >         framework
> >     ]
> >     if mixed_fn_dtypes in all_devices_dtypes:
> >         all_devices_dtypes = all_devices_dtypes[mixed_fn_dtypes]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > ```
> > >   return all_devices_dtypes[test_globals.CURRENT_DEVICE_STRIPPED][kind]
> > > ```
> > 
> > 
> > E KeyError: 'cpu' E E You can reproduce this example by temporarily adding @reproduce_failure('6.88.1', b'AA==') as a decorator on your test case
> > ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:38: KeyError ========================================================= 0.0% of 1 passed ============================================================================================================= short test summary info ===================================================== FAILED ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather[cpu-numpy-False-False] - KeyError: 'cpu' ======================================================== 1 failed in 3.66s ========================================================
> > The failure does not seem to be related to the changes, I'm not sure yet why "cpu" key would cause a problem, especially because test_gather starts from numpy. Is there an easy way to check just the torch backend?
> 
> Hi @Kacper-W-Kozdon, were you in sync with our latest `main` branch when you ran the test? I tried running it on my side and and didn't get that `KeyError`. The test is however failing in the torch backend where your changes are at.

Hey, @AnnaTz - after fixing my dependancies, the results of the test show only some warnings, but no errors anymore. I don't know much about pytest, so I'm still looking into how to get it to list the details of all the warnings.

(ivy_dev) bubble@DESKTOP-R198GD9:~/ivy$ pytest ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather -r a
Use Database in ReadOnly Mode with local caching !
============================================================ test session starts ============================================================
platform linux -- Python 3.10.12, pytest-8.0.0.dev309+g70f03dbc, pluggy-1.3.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /home/bubble/ivy
plugins: hypothesis-6.88.1
collected 1 item

ivy_tests/test_ivy/test_functional/test_core/test_general.py .                                                                        [100%]

============================================================= warnings summary ==============================================================
ivy/utils/exceptions.py:390
  /home/bubble/ivy/ivy/utils/exceptions.py:390: UserWarning: The current backend: 'tensorflow' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
    warnings.warn(

ivy_tests/test_ivy/test_functional/test_core/test_general.py: 45 warnings
  /home/bubble/ivy/ivy_dev/lib/python3.10/site-packages/tensorflow/python/framework/ops.py:293: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(self._numpy())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================= 100.0% of 1 passed ================================================================================================================== 1 passed, 46 warnings in 7.29s =======================================================

**Comment by Kacper-W-Kozdon** [comment]
Hi, @AnnaTz - an update on pytest results: I ran pytest on the branch from PR (i double-checked it contained the correct files) the following command: 

`$ pytest -v --full-trace --debug=pytestdebug.log ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather`

There were no errors reported in the output (test passed 100%) but a lot of warnings. Terminal displays the warnings in a very limited way, so that's why I searched for "warning" inside the pytestdebug.log. All of them were in the tensorflow backend (the number of warnings varied between pytest runs from about 20 to about 60). 

What this PR still needs is the update to examples in docstrings from gather in class methods, I saw some of them had arguments like "key" and some other which are not present in functional gather. It was not clear to me from descriptions, how to properly use these arguments, unless it's like with standard python functions which allow to set your own conditions for ordering. I could use some clarification on that.

**Comment by AnnaTz** [comment]
> Hi, @AnnaTz - an update on pytest results: I ran pytest on the branch from PR (i double-checked it contained the correct files) the following command:
> 
> `$ pytest -v --full-trace --debug=pytestdebug.log ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather`
> 
> There were no errors reported in the output (test passed 100%) but a lot of warnings. Terminal displays the warnings in a very limited way, so that's why I searched for "warning" inside the pytestdebug.log. All of them were in the tensorflow backend (the number of warnings varied between pytest runs from about 20 to about 60).
> 
> What this PR still needs is the update to examples in docstrings from gather in class methods, I saw some of them had arguments like "key" and some other which are not present in functional gather. It was not clear to me from descriptions, how to properly use these arguments, unless it's like with standard python functions which allow to set your own conditions for ordering. I could use some clarification on that.

Do you mean the `key_chains`. `to_apply`, etc in the container methods? You don't need to update those.

**Comment by Kacper-W-Kozdon** [comment]
> > Hi, @AnnaTz - an update on pytest results: I ran pytest on the branch from PR (i double-checked it contained the correct files) the following command:
> > `$ pytest -v --full-trace --debug=pytestdebug.log ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather`
> > There were no errors reported in the output (test passed 100%) but a lot of warnings. Terminal displays the warnings in a very limited way, so that's why I searched for "warning" inside the pytestdebug.log. All of them were in the tensorflow backend (the number of warnings varied between pytest runs from about 20 to about 60).
> > What this PR still needs is the update to examples in docstrings from gather in class methods, I saw some of them had arguments like "key" and some other which are not present in functional gather. It was not clear to me from descriptions, how to properly use these arguments, unless it's like with standard python functions which allow to set your own conditions for ordering. I could use some clarification on that.
> 
> Do you mean the `key_chains`. `to_apply`, etc in the container methods? You don't need to update those.

I mean the examples with these arguments being used. There are none for that. Is that ok? 

Other than that, I think I have not seen anything more to add to this PR. Other backends used their own functions/methods; one of them had some fairly lengthy nested function, but seemed ok otherwise- it was not a lambda and I did not see an obvious way to simplify it while I was reading through it.

**Comment by AnnaTz** [comment]
> > > Hi, @AnnaTz - an update on pytest results: I ran pytest on the branch from PR (i double-checked it contained the correct files) the following command:
> > > `$ pytest -v --full-trace --debug=pytestdebug.log ivy_tests/test_ivy/test_functional/test_core/test_general.py::test_gather`
> > > There were no errors reported in the output (test passed 100%) but a lot of warnings. Terminal displays the warnings in a very limited way, so that's why I searched for "warning" inside the pytestdebug.log. All of them were in the tensorflow backend (the number of warnings varied between pytest runs from about 20 to about 60).
> > > What this PR still needs is the update to examples in docstrings from gather in class methods, I saw some of them had arguments like "key" and some other which are not present in functional gather. It was not clear to me from descriptions, how to properly use these arguments, unless it's like with standard python functions which allow to set your own conditions for ordering. I could use some clarification on that.
> > 
> > 
> > Do you mean the `key_chains`. `to_apply`, etc in the container methods? You don't need to update those.
> 
> I mean the examples with these arguments being used. There are none for that. Is that ok?
> 
> Other than that, I think I have not seen anything more to add to this PR. Other backends used their own functions/methods; one of them had some fairly lengthy nested function, but seemed ok otherwise- it was not a lambda and I did not see an obvious way to simplify it while I was reading through it.

 Ah, you don't need to add such examples.

**Review by AnnaTz — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
