### PR TITLE
Adding real Instance Method to JAX Frontend

### LINKED ISSUE #19710: Real

### PR DESCRIPTION
**Pull request by shakikk**
Close #19710

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hello! Please remove file changes to the .idea folder and add the test implementation. Thanks!

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! I have tested the implementation locally and it seems to be failing for the TypeError. Can you please resolve it?

```
E       TypeError: test_frontend_method() missing 1 required keyword-only argument: 'backend_to_test'
```

**Comment by shakikk** [comment]
Hey, I hope you are well! I have made changes to the test_devicearray.py file to pass all tests. Please let me know if there are any other changes that need to be made :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
