### PR TITLE
experimental/average

### PR DESCRIPTION
**Pull request by hodanik**
Close https://github.com/unifyai/ivy/issues/10185

### CODE REVIEW

**Comment by hodanik** [comment]
Hi @fspyridakos, the Development section in the right column of this page is not active for me. So I can not link this pull request to my reserved issue, as was explained in the ivy video tutorial. Could you help on this? Thanks a lot.

**Comment by fspyridakos** [comment]
> Hi @fspyridakos, the Development section in the right column of this page is not active for me. So I can not link this pull request to my reserved issue, as was explained in the ivy video tutorial. Could you help on this? Thanks a lot.

It just needs to be in the first comment of the PR, I've done it for you :)

**Comment by hodanik** [comment]
> @fspyridakos, Thanks a lot :)

**Comment by hodanik** [comment]
Dear @fspyridakos sorry to bother you. I created this pull request on the 8th of Feb and got no reviews yet. Today, I sent a message to IvyTeam, but no reply yet. I was wondering if I made a mistake or missed something in the contributing process that caused this delay?

**Comment by fspyridakos** [comment]
Sorry for that, I think the person who's assigned to review this is not around atm, I could take a look

**Comment by hodanik** [comment]
> Sorry for that, I think the person who's assigned to review this is not around atm, I could take a look

It is nice of you :)

**Comment by fspyridakos** [comment]
From what I can tell, you somewhat replaced nanmean with average, could you correct this and make it a new separate function? Also please fix the conflicts. Thanks!

**Comment by hodanik** [comment]
Hi @fspyridakos . I modified the average function. Although the changes are insignificant, the average is a separate function now. I also added some more examples to check the input args.
Should I create a new pull request to apply the modifications? Or would you please reopen the "experimental/average #10420" pull request for me to apply the changes? Unfortunately, I accidentally closed it while syncing my master branch.

**Comment by fspyridakos** [comment]
I cannot re-open the PR either unfortunately so I would reccommend you try to open a new PR

**Comment by hodanik** [comment]
> I cannot re-open the PR either unfortunately so I would reccommend you try to open a new PR

Thanks for such a quick reply :) I will open a new PR now.

**Comment by hodanik** [comment]
@fspyridakos, please find the new PR link in as follows: https://github.com/unifyai/ivy/pull/10651
Thanks for your help. Have a nice evening.

**Pull request closed without merging**
