### PR TITLE
Added tanh to Math functions for numpy frontend

### PR DESCRIPTION
**Pull request by steve-mir**
# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by steve-mir** [comment]
Added tanh

**Comment by steve-mir** [comment]
Added test

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @steve-mir
Thank you very much for the PR.
Two requests. Firstly the issue for the task should be mentioned. Your first comment misses the issue number.
Secondly, is  the underscore in `_tanh` added by a mistake?

**Comment by steve-mir** [comment]
First I didn't know was meant to add the issue number to the commit
message. Also I named it _tahn just following the convention. Others were
named with an underscore

**Comment by Ishticode** [comment]
I am closing this for two reasons. Firstly, no issue is linked which the PR compliance check has requested above. Secondly, this functions is already implemented much before this pr as seen within refactor here https://github.com/unifyai/ivy/commit/f339a054892a33ce7ffb196883d40b5a5756bceb#diff-ff1d511638a9a12c743e93907b0a1a3451bb51db333f8e101fad1bd71df5e674R47
Please feel free to check our [contributing guideline](https://unify.ai/docs/ivy/overview/contributing.html) to make further contributions. Thank yo very much.

**Pull request closed without merging**
