### PR TITLE
setxor1d and test_setxor1d Implemented

### LINKED ISSUE #11989: setxor1d
Working on (#8431-> #17791)

### PR DESCRIPTION
**Pull request by Sarvesh-Kesharwani**
Closes #11989

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Sarvesh-Kesharwani Thank you very much for the PR.
Could you update the dtyp to all `valid` dtypes in the test as we are trying to be as comprehensive with the tests as possible. If you encounter any problems let me know. Secondly the argument `assume_unique` should also be generated as `st.booleans()` and pass it to the `test_frontend_function`. If I didn't make sense then please feel free to tag me and ask about it and you may ask for a review if you think its fixed. Thanks @Sarvesh-Kesharwani 😃

**Comment by Sarvesh-Kesharwani** [comment]
> Hi @Sarvesh-Kesharwani Thank you very much for the PR. Could you update the dtyp to all `valid` dtypes in the test as we are trying to be as comprehensive with the tests as possible. If you encounter any problems let me know. Secondly the argument `assume_unique` should also be generated as `st.booleans()` and pass it to the `test_frontend_function`. If I didn't make sense then please feel free to tag me and ask about it and you may ask for a review if you think its fixed. Thanks @Sarvesh-Kesharwani 😃

Absolutely, I'll take care of it.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Sorry for the delay @Sarvesh-Kesharwani 
I will keep this PR on high priority.


Although the function is names 1d, the `np.setxor1d` function can take inputs of higher dimensions but the output will be given as 1d. So, using the python built-in `set` function on input array will fail for array of dimension higher than 1 with `TypeError: unhashable type: 'numpy.ndarray'`.  Could you perhaps find a way around it. Perhaps flatten the input array first as then the builtin `set` function would work for 1d input.

Also please could you try to run the test as it should clearly be failing because the parameters passed to test_ frontend_function as `x1` and `x2` don't even exist in function signature.
Please feel free to follow up on this. I will try to respond quickly. Thank you very much for the patience  🙂

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
