### PR TITLE
Adding MXNet in backend

### PR DESCRIPTION
**Pull request by rohini-ranjanR**
I add MNNet in backend option as IVY ML framework. I remove it earlier but after getting error I put it again.

### CODE REVIEW

**Comment by atakanoc** [comment]
Hi @rohini-ranjanR!

I'm a little confused about what you mean by "I remove it earlier but after getting error I put it again" because you haven't made any changes to Ivy that have been merged yet. I see that there is another pull request you were working on - #6865. 

If this pull request is related to that one, which it seems to be, could you close one of them and continue your work on the other? It's better to keep related work on the same pull request so that it doesn't get disconnected like this. ☺️

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by rohini-ranjanR** [comment]
Screenshot 2022-11-22 184345
These checks are not successful 
Screenshot 2022-11-22 184541
This is the error I was getting in Code

**Comment by rohini-ranjanR** [comment]
Hey, 
This issue has now been solved and a similar pull request has now been merged (https://github.com/unifyai/ivy/pull/6865#event-7879592216). Thanks.

**Comment by atakanoc** [comment]
Alright, thanks for your contribution @rohini-ranjanR!

**Pull request closed without merging**
