### PR TITLE
feat: Add instance method to NumPy

### LINKED ISSUE #23150: take

### PR DESCRIPTION
**Pull request by paulmbuitu**
# PR Description
Added ".take() fn" to NumPy frontend, implementing it via using composition as there were no ivy.take() fn

## Related Issue

Close #23150 

## Checklist

- [x] Did you add a function? Yes
- [x] Did you add the tests? No
- [x] Did you follow the steps we provided? Yes

### Socials:
@Mbuitu_m

### CODE REVIEW

**Comment by paulmbuitu** [comment]
The related issue was 23150, you can close it

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey! thanks for the great work! Could you please add a test for the instance method in its corresponding folder within `ivy_tests`? thanks!

**Comment by paulmbuitu** [comment]
On it. Thanks

**Comment by juliagsy** [comment]
Hey! Thanks for the great work! The tests are not passing unfortunately, would you please check the tests locally and make sure they pass with `python3 -m pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py::test_numpy_take` thanks!
ps: please also update your branch to the latest commit if possible, thanks!

**Comment by juliagsy** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
