### PR TITLE
Add frontend numpy nanmedian

### PR DESCRIPTION
**Pull request by yizhouyang999**
- [ ] #6703

### CODE REVIEW

**Comment by yizhouyang999** [comment]
Close #6703 
Hi, I want to re-request review.

And I also have problem when run test in my laptop,
ERROR: file or directory not found: /home/yizhou/projects/lvy/ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py::test_numpy_nanmedian

but I have this file or directory there, could you give any idea about it?

**Comment by CerberusLatrans** [comment]
Hi @yizhouyang999
Regarding your test not being found, can you give me a few more details like more of the console output (if any)? Also, what testing environment (Docker, venv, codespaces) and IDE are you using?

Thanks for reformatting the arguments. Is the first if statement (line 78) necessary since the else branch should also be able to handle it if none are Nan? 

Also, on line 84 do you mean to have `is_nan[i]` instead of `ivy.isnan(i)`? I would say either method is fine, but only keep one to avoid unused computation/redundancy.

Finally, the overwrite_input feature is not supposed to just wrap it in an ivy array-- the docs have it modifying the input in place. See if you can use some array instance methods to achieve this behavior.

Let me know if you have any other questions or problems.

**Comment by yizhouyang999** [comment]
Hi @CerberusLatrans ,

1 for the overwrite_input problem:
I check the source code of numpy.median, overwrite_input parameter affect the logic of implementation very deeply. I can not extract it out if I want to use ivy.median. Since currently ivy.median does not support this parameter, may I wrap it in an ivy array as a temporary solution?

2 for the test problem:
I use docker, and here is the output:
/usr/bin/python3 /opt/.pycharm_helpers/pycharm/_jb_pytest_runner.py --target /home/yizhou/projects/lvy/ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py::test_numpy_nanmedian 
Testing started at 12:11 PM ...
Launching pytest with arguments /home/yizhou/projects/lvy/ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py::test_numpy_nanmedian --no-header --no-summary -q in /ivy

ERROR: file or directory not found: /home/yizhou/projects/lvy/ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py::test_numpy_nanmedian

============================= test session starts ==============================
collecting ... collected 0 items

============================ no tests ran in 0.00s =============================

Process finished with exit code 4

Empty suite

**Comment by CerberusLatrans** [comment]
1) That is understandable, so I don't think it is necessary to actually conserve memory allocation. However, I think it is still important that we modify the array in-place. Try calling instance methods (array.nan_median()) if it exists.

2) Could it be that Ivy is capitalized in your path? Not sure why this would be, but it has always been lowercase for me.
Also, you should make sure to have pytest show header and summary when the test does run for easier debugging
Screen Shot 2022-11-12 at 2 55 32 PM

If either of those things doesn't do anything, try asking in the discord pycharm channel. I use VSCode Codespaces to run my environment so unfortunately I am not too familiar with this environment.

**Comment by yizhouyang999** [comment]
Hi @CerberusLatrans,
Thank you for these suggestions. It is still not working, I posted this issue in the discord Pycharm channel. Hopefully it will work out.
But could we merge this branch if test is working in Github?(I do not know how to check this actually, because I saw some merged branched also failed in the "test-frontend-numpy / run-nightly-tests (pull_request)" )

**Comment by CerberusLatrans** [comment]
I am looking into the numpy frontend tests too and I cannot see it being run. Unfortunately I am not going to merge it if the test is not even being registered. It would cause an error regardless because (I think) the array instance method of nanmedian is not implemented. Until your environment issue gets resolved, feel free to work on that in the meantime if it interests you (just reserve that task for yourself). Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
