### PR TITLE
Added torch hinge_embedding_loss

### PR DESCRIPTION
**Pull request by ZiadAmerr**
Added hinge_embedding_loss
- #7673

### CODE REVIEW

**Comment by ZiadAmerr** [comment]
Hi, @ZoeCD, I am still working on it, I will update you as soon as I see my pull request ready to be merged, also please note that `check-formatting` is not working well as my files are formatted but it is raising that error in a different file in the fork that I didn't even change

Also regarding the `nightly-tests`, torch's `hinge_embedding_loss` gets an input and a target to calculate the loss. But there is this constraint, the target should only contain values either -1 or 1.

> Measures the loss given an input tensor xx and a labels tensor yy (containing 1 or -1).

And the loss is calculated as follows

Screenshot 2022-12-08 at 6 35 48 PM

I can't modify the `test_torch_hinge_embedding_loss` decorator to only generate an array of (-1, 1) values. How can I do that?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ZiadAmerr** [comment]
.

**Comment by ZoeCD** [comment]
Hi! Sorry for the late response

"I can't modify the test_torch_hinge_embedding_loss decorator to only generate an array of (-1, 1) values. How can I do that?"
-> The helper function `dtype_and_values()` has the optional arguments `min_value` and `max_value`, maybe you can use them to set up this constraint

"also please note that check-formatting is not working well as my files are formatted but it is raising that error in a different file in the fork that I didn't even change"
-> Yeah, don't worry about lint errors that are not related to your PR

Hope that helps! 😊

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ZoeCD** [comment]
Hi, are you still interested in working on this PR? 🙂

**Comment by ZiadAmerr** [comment]
Hi @ZoeCD I am interested yes but I am a bit busy going through some college examinations, if it is okay to wait then yes I would like to work on it. If it is not okay for you to wait for me to finish, then you can mark this as unfinished and I work on other tasks later on when I finish. But yes I do have interest in working on it

**Comment by ZoeCD** [comment]
Good luck with your college exams! 🤓 I think the best thing to do, then, is to convert this PR into a draft. Because if we close it, the function would become free for others to work on. You can ask for a review once you resume your contribution  😊

**Comment by ZiadAmerr** [comment]
Thank you, will start working asap

**Pull request closed without merging**
