### PR TITLE
feat: Implemented Jax/numpy/savez function

### LINKED ISSUE #27106: savez

### PR DESCRIPTION
**Pull request by rohitkg83**
# Implemented Jax/numpy/savez function

#27106 

Closes #27106 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

@rkg830926

### CODE REVIEW

**Comment by soma2000-lang** [comment]
Hi @rohitkg83 Can you  kindly look into the failing tests..

**Comment by rohitkg83** [comment]
Hi @soma2000-lang - Thanks a lot for looking into this. I believe these errors aren't specific to the changes that were implemented. These errors were already there for other jax frontend functions also when I set-up the environment 3 weeks back. I was seeing these errors for any jax frontend function tests I was trying to run. I earlier thought that this might be a local environment issue but given it is failing here as well I believe there might be some issue with docker / environment set-up files. Can you please check with fellow ML engineers if any jax specific environment issues have been reported elsewhere.

**Comment by rohitkg83** [comment]
Hi @soma2000-lang  - Did you get chance to look further into this? Many thanks

**Comment by soma2000-lang** [comment]
Yes @rohitkg83 currently going through this.

**Comment by Ishticode** [comment]
Closing this due to inactivity for over 5 months. Please reopen if you would like to continue work on this.

**Pull request closed without merging**
