### PR TITLE
Made the Requested Changes

### PR DESCRIPTION
**Pull request by KarimIbrahim11**
1-PR only changes in the scope of the assigned function
2-Changed the code to adapt to the complex numbers which resulted in failing one test out of the four. After keen inspection of the errors, It shows that the backend function result doesn't match with the jax sign results. Knowing that the results match if I changed the dtype back to "float", I am anticipating the backend function doesn't handle complex. I have attached a screenshot of the error shown on the failiing test.

backend

### CODE REVIEW

**Review by AnnaTz — CHANGES_REQUESTED** [review]

**Review by KarimIbrahim11 — COMMENTED** [review]
Kindly review my code after making the requested changes. :)

**Comment by KarimIbrahim11** [comment]
> > Kindly review my code after making the requested changes. :)
> 
> Please sync with our current master. There is an error in the CI tests that we have now fixed.

Successfully synced the repo with upstream.
image

**Comment by AnnaTz** [comment]
Please have a look at `intelligent-tests-pr / run_tests_1 (pull_request)`. There is an error related to complex numbers that needs to be resolved.

**Comment by KarimIbrahim11** [comment]
> 

This error is related to the backend of the function please read the very first comment on this PR: https://github.com/unifyai/ivy/pull/14025#issue-1663180979 . Whoever implemented the backend ivy,sign function didn't handle complex numbers, if you change the dtype to float it will work.

**Comment by KarimIbrahim11** [comment]
> Please have a look at `intelligent-tests-pr / run_tests_1 (pull_request)`. There is an error related to complex numbers that needs to be resolved.

In PR #13700 the previous reviewer asked me to support Complex numbers so I did and that's what raised the aforementioned error related to backend so Should or Should not it support complex ?

**Comment by AnnaTz** [comment]
> 

The test should include all valid dtypes, but if the original function does not support a dtype you can handle it using the unsupported_dtypes decorator. You can read about this [here](https://lets-unify.ai/docs/ivy/overview/deep_dive/data_types.html#supported-and-unsupported-data-types).

**Comment by KarimIbrahim11** [comment]
> > 
> 
> The test should include all valid dtypes, but if the original function does not support a dtype you can handle it using the unsupported_dtypes decorator. You can read about this [here](https://lets-unify.ai/docs/ivy/overview/deep_dive/data_types.html#supported-and-unsupported-data-types).

Kindly review my changes. I've updated elementwise.py in the backend with the decorator. The test you referred to passed now.

**Review by AnnaTz — APPROVED** [review]
Great! Ready to be merged.

**Pull request merged**
