### PR TITLE
Reformat multi_index_nest

### LINKED ISSUE #7242: multi_index_nest

### PR DESCRIPTION
**Pull request by archbung**
Close #7242

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by archbung** [comment]
@abdrahmandiab could you take a look?

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab could you take a look?

Hi @archbung , sorry for the late reply, been quite swamped lately :)
Will be reviewing this PR soon, so please be on the lookout! 

Thanks!

**Comment by abdrahmandiab** [comment]
Hi @archbung ,
apologies for taking a long time to review this PR 😅 
I've only added examples for the `ivy.Container` class since it is also supported. But otherwise you did a great job, and I've merged the PR so you can proceed with your application now!
Thanks!

**Comment by archbung** [comment]
Hi @abdrahmandiab, no worries and thanks for the review!

**Pull request merged**
