### PR TITLE
added batch_norm

### PR DESCRIPTION
**Pull request by humzakt**
close https://github.com/unifyai/ivy/issues/15814

### CODE REVIEW

**Comment by humzakt** [comment]
Added batch_norm in torch frontend framework

**Comment by aparajith21** [comment]
ivy-gardener

**Comment by aparajith21** [comment]
Hi! Thank you so much for contributing, but unfortunately batch_norm already exists in torch in the frontends/torch/nn/functional/norms.py file. The norm functions already exist and it appears to have been added by mistake to the list here https://github.com/unifyai/ivy/issues/21 . Apologies for the misuse of your time.

**Comment by humzakt** [comment]
> Hi! Thank you so much for contributing, but unfortunately batch_norm already exists in torch in the frontends/torch/nn/functional/norms.py file. The norm functions already exist and it appears to have been added by mistake to the list here #21 . Apologies for the misuse of your time.

Alright no worries. I will get started with any other function. Also a small request, can you refer me good resources for setting up on macbook m1. The tutorial in the guides is using an intel mac and i am having trouble setting up tests using docker. Thanks

**Comment by aparajith21** [comment]
The guide here (https://unify.ai/docs/ivy/overview/contributing/setting_up.html) has some additional details for setting up on M1, however if you're still facing issues, please join the discord channel here https://discord.com/invite/sXyFF8tDtm and we can help you better

**Comment by humzakt** [comment]
Alright thanks alot. I will get started on another task.

**Pull request closed without merging**
