### PR TITLE
atan adhering to Array API Standard.

### PR DESCRIPTION
**Pull request by Darshan-H-E**

### CODE REVIEW

**Comment by mattbarrett98** [comment]
Thanks for contributing!

**Comment by Darshan-H-E** [comment]
Thank you

**Comment by Darshan-H-E** [comment]
> Thanks for contributing!

Hi matt, One minor issue. I had submitted the link to this PR in the questionnaire (breezy) even before it was merged into the master branch of the main repo. Will it cause any problems in the process?

**Comment by mattbarrett98** [comment]
If the link still works and brings you to this merged PR then I don't think there will be any problems 🙂

**Pull request merged**
