### PR TITLE
added torch matrix_exp function (linalg)  and tested

### LINKED ISSUE #17885: matrix_exp

### PR DESCRIPTION
**Pull request by juliommen**
Close #17885

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by DragosStoican** [comment]
Hi @juliommen , first of all thank you for your contribution! However, it seems your test is failing on the Jax, Tensorflow and Paddle backends. Can you please make sure all the tests are passing and then I will take another look!

**Comment by juliommen** [comment]
> Hi @juliommen , first of all thank you for your contribution! However, it seems your test is failing on the Jax, Tensorflow and Paddle backends. Can you please make sure all the tests are passing and then I will take another look!

The tests fail on these frameworks because their backend implementations are wrong.  

Here they are, just for clarification:

**Jax**
`
def matrix_exp(
    x: JaxArray,
    /,
    *,
    out: Optional[JaxArray] = None,
) -> JaxArray:
    return jla.expm(x)
`

**Paddle**
`


def matrix_exp(
    x: paddle.Tensor,
    /,
    *,
    out: Optional[paddle.Tensor] = None,
) -> paddle.Tensor:
    # TODO: this is elementwise exp, should be changed to matrix exp ASAP
    return paddle.exp(x)
`
**Tensorflow**
`
def matrix_exp(
    x: Union[tf.Tensor, tf.Variable],
    /,
    *,
    out: Optional[Union[tf.Tensor, tf.Variable]] = None,
) -> Union[tf.Tensor, tf.Variable]:
    return tf.linalg.expm(x)
`

**Comment by juliommen** [comment]
> Hi @juliommen , first of all thank you for your contribution! However, it seems your test is failing on the Jax, Tensorflow and Paddle backends. Can you please make sure all the tests are passing and then I will take another look!

Hello! I've made the changes, but the tests will continue to fail on Paddle backend function, because its implementation is wrong, see:

´´´
def matrix_exp(
    x: paddle.Tensor,
    /,
    *,
    out: Optional[paddle.Tensor] = None,
) -> paddle.Tensor:
    # TODO: this is elementwise exp, should be changed to matrix exp ASAP
    return paddle.exp(x)
```

**Comment by DragosStoican** [comment]
That is fine @juliommen , thank you for your contribution!! 😁

**Pull request merged**
