### PR TITLE
inverse hyperbolic tangent function added

### PR DESCRIPTION
**Pull request by adityarajsahu**

### CODE REVIEW

**Comment by adityarajsahu** [comment]
@kurshakuz can you please tell me how to fix these failing tests? I am not able to figure out what is wrong.

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! Your implementation does not contain a testing funciton. Please implement it, so that I can help further. Please take a look at our documentation. Thanks!

**Comment by adityarajsahu** [comment]
@kurshakuz I have implemented the testing function, but one test is failing, can you please help?

**Comment by adityarajsahu** [comment]
@kurshakuz can you please have a look?

**Comment by adityarajsahu** [comment]
@ivy-seed please help with merging this pr. it's been two weeks since I created this pr.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Pull request closed without merging**
