### PR TITLE
eigh function for TensorFlow Frontend 

### PR DESCRIPTION
**Pull request by rannynayyar67**
affiliated with #4238 issue

### CODE REVIEW

**Comment by ZoeCD** [comment]
Hi! There are some test and lint errors. Could you please check them out? You can learn more about these problems by clicking the details section alongside the failing test. Thanks!

**Comment by rannynayyar67** [comment]
okay @ZoeCD 
will check them

**Comment by rannynayyar67** [comment]
Hi @ZoeCD, I am not able to identify the reason of the test-frontend-tensorflow error 
the detail section is not quit detailed in this test

**Comment by rannynayyar67** [comment]
@ZoeCD can you please review the commit associated with this PR

**Comment by rannynayyar67** [comment]
hi @johanjino 
can you review this PR.
This PR is associated with an early PR #4245 you reviewed and suggested me to fork the responsitory and add my work to it again.

**Pull request closed without merging**
