### PR TITLE
added xlog1py

### LINKED ISSUE #14210: xlog1py

### PR DESCRIPTION
**Pull request by piyushgit011**
closes #14210

### CODE REVIEW

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hey @piyushgit011 

Apologies for the late response. Was quite swamped with work recently and so reviewing this PR totally slipped under my radar 😅 

With regards to the PR, could you kindly look into the failing tests for `xlog1py` and re-request a review once all relevant tests are passing? Thanks!


**Update:** It seems that the `xlog1py` function does not currently exist in Ivy. In that case, you cant directly implement the frontend function. You'll need to first implement this function in Ivy along with the implementation for all backends and only then can you write the frontend function. 
Since this task has now transitioned into the `Extend Ivy API` task, its up to you if you want to continue working on it in this PR or if you want to close this PR and work on a new task.

**Comment by piyushgit011** [comment]
Okay , i will try to implement in the backend too

**Comment by YushaArif99** [comment]
@piyushgit011 are you still working on this PR? It's been 2 weeks and there have been no commits made. If you're no longer working on the PR, we can close this one 🙂

**Comment by piyushgit011** [comment]
i will be working on this in next two to three days

**Comment by YushaArif99** [comment]
Sure no worries 🙂

**Comment by YushaArif99** [comment]
Hi @piyushgit011 

Are you still working on this PR? there has been no activity for quite a while now. If you're not working on this anymore, we can close this PR 🙂

**Comment by YushaArif99** [comment]
I have closed this PR for now. If you're still working, let me know and i'll reopen the PR 😄

**Pull request closed without merging**
