### PR TITLE
Add global_norm to tensorflow backend

### LINKED ISSUE #16504: global_norm

### PR DESCRIPTION
**Pull request by maxDeCoder**
close #16504

### CODE REVIEW

**Comment by theRealBird** [comment]
Hello @maxDeCoder, 
Thank you so much for your contribution to Ivy and for your patience with the code review process. I believe the issue you have linked is for the implementation of the "frontend function" and not the backend. Could you have look?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @maxDeCoder 

The implementation of this function should be done in the Tensorflow frontend, in this file https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/tensorflow/linalg.py

Along with its unit test

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
