### PR TITLE
Reformatted depthwise_conv2d

### PR DESCRIPTION
**Pull request by luis-guerraf**
#1108

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @luis-guerraf. Great work here. Could you kindly add few more examples based on the instructions provided at [Docstring examples page](https://lets-unify.ai/ivy/contributing/5_docstring_examples.html). If anything is unclear pls let me know or check the [video](https://www.youtube.com/watch?v=fTifKx8GJrg) explaining this.
When done could u ask for my review. Thanks :)

**Comment by luis-guerraf** [comment]
Hi @Ishticode, I added a couple of extra examples, however I couldn't get the case of ivy.Container on both inputs to work. Can you help me with this? Also what are those github checks that are not passing? I noticed I was quick a few commits behind and the test_array_api file was added into my merge-commit when I tried to merge my branch with upstream, can this be an issue?

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi, @luis-guerraf all is good except some file in the submodule test_array_api got a change. Could you check, undo that locally and push. Hopefully, that makes sense. Ask for my review when done. : )

**Comment by luis-guerraf** [comment]
Hi @Ishticode, I think it's fixed now.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @luis-guerraf. Mostly Done. Could you take care of test-numpy-style-docstrings. Let me know for any issues. Other failures are not based on your work so don't worry about them for now. Thnx

**Review by Ishticode — APPROVED** [review]
Looking great @luis-guerraf. I will get it merged now. Thanks for your contribution : )

**Pull request merged**
