### PR TITLE
Added Categorical to jax frontend

### LINKED ISSUE #21785: categorical

### PR DESCRIPTION
**Pull request by VaishnaviMudaliar**
Closes #21785

### CODE REVIEW

**Comment by VaishnaviMudaliar** [comment]
hey @saeedashrraf ! please do review this pr and let me know about the changes required :)

**Comment by VaishnaviMudaliar** [comment]
Hey! @saeedashrraf , please have a look at the PR and let me know if any changes are required 😊
Thanks!

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @VaishnaviMudaliar, I hope you are doing well! I apologize for the delay. Can you please remove the duplicate multivariate_normal? Thanks!

**Comment by VaishnaviMudaliar** [comment]
Hey @saeedashrraf 👋 thanks for the review, I have deleted the extra multivariate normal function. Please have a look and let me know if more changes are needed😊
Thanks!

**Comment by saeedashrraf** [comment]
Hello @VaishnaviMudaliar , just edit the helper function you created to be private and additionally, removed the incorrect decorator handling the `dtype` input to the function. Thank you for your contribution!

**Comment by VaishnaviMudaliar** [comment]
Thanks alot! @saeedashrraf I'll do that right away ☺️

**Pull request merged**
