### PR TITLE
added ndarray as alias

### PR DESCRIPTION
**Pull request by VictorOdede**
Close https://github.com/unifyai/ivy/issues/14770

### CODE REVIEW

**Comment by VictorOdede** [comment]
Close #14770

**Comment by vaatsalya123** [comment]
Could you explain why do we need this?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by VictorOdede** [comment]
Waiting for review

**Review by hirwa-nshuti — APPROVED** [review]
Looks great to me😊

**Pull request merged**
