### PR TITLE
reformat: gpu_is_available

### PR DESCRIPTION
**Pull request by yugaljain1999**
fixes https://github.com/unifyai/ivy/issues/1230
Added logic for gpu_is_available in the device module

### CODE REVIEW

**Comment by yugaljain1999** [comment]
Hey @Darshan-H-E , Can you please review this and lemme know how can I add gputil in requirements.txt? As I added that module in requirments.txt of branch named  'yugaljain1999:#1230_gpu_is_available' but it didn't pick that requirments.txt file to install pip modules..
Can you pls lemme know how we can add new module in requirements.txt?
Thanks

**Comment by kinshukdua** [comment]
@yugaljain1999 I don't think GPUtils is a good choice as it only works for Nvidia GPUs. Plus, all the functionalities are already implemented in the existing backend.

**Comment by yugaljain1999** [comment]
@kinshukdua So should I use nvidia_smi gpu device only to check if gpu is available or not?

**Comment by yugaljain1999** [comment]
@Darshan-H-E can you please review PR and lemme know what changes we need to do in code?
Thanks

**Comment by Darshan-H-E** [comment]
Hi @yugaljain1999, Can you reformat the function ( add a new line after the function) to pass the lint/check-formatting test?

**Comment by Darshan-H-E** [comment]
Hi @yugaljain1999, Can you reformat the function ( add a new line after the function) to pass the lint/check-formatting test?

**Comment by Darshan-H-E** [comment]
@yugaljain1999 Can nvidia_smi.nvmlDeviceGetCount() detect non-nvidia GPU as well?

**Comment by yugaljain03** [comment]
@Darshan-H-E I just fixed linting issue.
As per detecting non nvidia GPU I didn't test that on non nvidia GPU but I hope it will work there as well if cuda can be configure in non nvidia GPU.

**Comment by kinshukdua** [comment]
Hi @yugaljain1999, this is supposed to be a reformating task, the implementation of the function itself has already been done. You just need to add type hints, docstrings and example as mentioned in the task document.

**Comment by yugaljain03** [comment]
@kinshukdua Got that so I will add those and then update the PR.
Thanks for letting me know

**Comment by yugaljain1999** [comment]
@kinshukdua , I just checked out, implementation of function isn't done yet as it's showing `return _cur_backend().gpu_is_available()` in return but it should have been replaced by some functions from libraries imported.
As you can see in other functions this wasn't written that's why there was just need to add docstrings,type hints and examples like your PR but in `gpu_is_available` and `num_gpus` case there wasn't any function used so how can we take it as already implemented?
Are you getting me?
Thanks

**Comment by Darshan-H-E** [comment]
@yugaljain1999 _cur_backend().gpu_is_available() is called, it infers to the back-end specific method which is already implemented. In case of numpy it always returns False as it doesn't make use of gpu. @kinshukdua is right about this. This was a reformatting task where you are required to reformat the implemented methods to conform to the standards.

**Comment by Darshan-H-E** [comment]
If you have already submitted the PR link in breezy, it's totally fine. I've raised the matter with Dan. You'll be progressed to the next stage.

**Comment by yugaljain1999** [comment]
@Darshan-H-E So should I now update docstrings and add examples and then commit in this PR?
As I can see `gpu_is_available` issue is unmarked in #814.

And I didn't get breezy form to submit PR so I did submit that on upwork milestone. Is that fine?
Looking forward to hear back soon.
Thanks

**Comment by Darshan-H-E** [comment]
Hi @yugaljain1999, if you have submitted on upwork then you will soon receive an update from Dan. If you would like to work on this task again, you are welcome to do so. But make sure to follow the process and contributor guide. Thank you

**Pull request merged**
