### PR TITLE
Close #6634

### LINKED ISSUE #6634: var

### PR DESCRIPTION
**Pull request by khadija267**

### CODE REVIEW

**Comment by JerryGCDing** [comment]
Hi @khadija267, thank you for contributing to Ivy 😃! Can you fix the failing `lint` and `test-frontend-numpy` checks associated with this PR? (FYI: details about failing frontend tests can be accessed by clicking on `Details -> Run Frontend Tests`)

**Comment by khadija267** [comment]
> Hi @khadija267, thank you for contributing to Ivy smiley! Can you fix the failing `lint` and `test-frontend-numpy` checks associated with this PR? (FYI: details about failing frontend tests can be accessed by clicking on `Details -> Run Frontend Tests`)

I don't understand what to fix, especially with the test-frontend-numpy, could please help?

**Comment by JerryGCDing** [comment]
So `lint` checks basically point out some formatting errors on certain lines within the files that you have changed. And for `test-frontend-numpy` you can search for the keyword `test_numpy_var` in the logs of `Run Frontend Tests` which will return some falsifying examples about the test. Hope this information is helpful 😃.

**Comment by khadija267** [comment]
Sorry?
Is that issue closed, means that I'm unable to work on it?

**Pull request closed without merging**
