### PR TITLE
frontend.numpy.ndarray: add support for all instance method

### LINKED ISSUE #4886: all

### PR DESCRIPTION
**Pull request by hmahmood24**
Close #4886

### CODE REVIEW

**Comment by hmahmood24** [comment]
Hey @modanesh,

I'm waiting on a response on this PR so we can close it as soon as possible since I can only have 3 active tasks at a time. Hoping to hear a response from you. Thanks!

**Comment by modanesh** [comment]
Thanks for your contribution. LGTM. The only question is that were the changes made to the `helpers.py` necessary?

**Comment by hmahmood24** [comment]
Hi @modanesh,

Not for this specific test case but it is for coherency and ease of usage down the road since someone might want to have control over the `allow_none` argument of the `get_shape` function.

**Comment by modanesh** [comment]
Thanks! Could you also resolve the conflicts?

**Comment by hmahmood24** [comment]
Sure. I have resolved the conflicts now 😊

**Pull request merged**
