### PR TITLE
numpy insert

### PR DESCRIPTION
**Pull request by luizgubarichello**
Close https://github.com/unifyai/ivy/issues/15954

### CODE REVIEW

**Comment by luizgubarichello** [comment]
Close #15954

**Review by zaeemansari70 — COMMENTED** [review]
Hi @luizgubarichello 

Kindly do let me know when you are done with your implementation.
You can request a review from me by commenting in your PR :slightly_smiling_face: 

Thanks! :slightly_smiling_face:

**Comment by luizgubarichello** [comment]
> Hi @luizgubarichello
> 
> Kindly do let me know when you are done with your implementation. You can request a review from me by commenting in your PR 🙂
> 
> Thanks! 🙂

Hello!

I'm done, you can review my PR ;)

Thanks

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi @luizgubarichello 

You also have to add the test in the respective test file too!
Kindly refer to the frontend section in the deep dive in our docs.https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html

Thanks! :slightly_smiling_face:

**Comment by luizgubarichello** [comment]
I updated and created the test file, but couldnt find a way to test the test in my machine. Anyway, I think my logic is correct and it should work.

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
The intelligent tests on the CI are failing for your implementation, you have to do a setup to test things properly, as we use `hypothesis` for rigorous testing, it tests on multiple possible examples which finds a failure if there is even a slight issue in the logic :slightly_smiling_face:  
Do let me know if you have any questions!
Thanks! :slightly_smiling_face:

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
