### PR TITLE
Added nll_loss to paddle frontend

### LINKED ISSUE #21312: nll_loss

### PR DESCRIPTION
**Pull request by aks1204**
Close #21312

### CODE REVIEW

**Comment by aks1204** [comment]
@nathzi1505 could you please review my PR.

**Comment by nathzi1505** [comment]
Hi @aks1204, I see there is a lint error with the commit. 
Would you mind looking at it for me?
Else looks fine.

**Comment by aks1204** [comment]
> Hi @aks1204, I see there is a lint error with the commit. Would you mind looking at it for me? Else looks fine.

@nathzi1505 I'd initially looked for the formatting error when I made the PR but wasn't able to figure out what exactly was the error in my code format. Could you please look and specify. Thanks.

**Comment by nathzi1505** [comment]
> > Hi @aks1204, I see there is a lint error with the commit. Would you mind looking at it for me? Else looks fine.
> 
> @nathzi1505 I'd initially looked for the formatting error when I made the PR but wasn't able to figure out what exactly was the error in my code format. Could you please look and specify. Thanks.

It's alright. Not a big issue, let me just go ahead and merge.

**Comment by aks1204** [comment]
> > Hi @aks1204, I see there is a lint error with the commit. Would you mind looking at it for me? Else looks fine.
> 
> @nathzi1505 I'd initially looked for the formatting error when I made the PR but wasn't able to figure out what exactly was the error in my code format. Could you please look and specify. Thanks.

Screenshot 2023-08-09 173107

**Pull request merged**
