### PR TITLE
EHN: adding cond in paddle tensor.py

### LINKED ISSUE #18180: cond
adding cond method in paddle tensor.py

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
Closed  #18180

### CODE REVIEW

**Comment by danielmunioz** [comment]
Hey @MuhammadNizamani Thanks for contributing!

There seems to be a couple of issues with the PR, first you forgot to add `._ivy_array` to the `self` call, it also looks like the testing function is not testing for the `p` argument, you mind adding that and then run the test for your function and make it's passing please?

If you have any questions please don't hesitate to reach out!
Thanks! :)

**Comment by MuhammadNizamani** [comment]
> Hey @MuhammadNizamani Thanks for contributing!
> 
> There seems to be a couple of issues with the PR, first you forgot to add `._ivy_array` to the `self` call, it also looks like the testing function is not testing for the `p` argument, you mind adding that and then run the test for your function and make sure it's passing please?
> 
> If you have any questions please don't hesitate to reach out! Thanks! :)

Sir I am calling function using paddle_frontend so some function from function will call @to_ivy_arrays_and_back so I don;t need to .`_ivy_array to the self`

**Comment by MuhammadNizamani** [comment]
@danielmunioz  done with require chnages

**Comment by danielmunioz** [comment]
Hey @MuhammadNizamani! Yep, you are right, I missed that you're using paddle_front directly!

And yeah, the PR looks in good shape overall!
Merging now! 🚀 

Thanks!

**Pull request merged**
