### PR TITLE
Implemented precision_score function in _classification.py

### PR DESCRIPTION
**Pull request by muzakkirhussain011**
The precision_score function calculates the precision score for classification tasks, which is a measure of the accuracy of positive predictions.

The precision_score function takes as input the true labels y_true and predicted labels y_pred. It also allows for optional parameters such as normalize for controlling whether the result should be normalized and sample_weight for handling sample weights.

The function first determines the type of target variable, checking if it is a multilabel classification problem. If it is, it computes the difference between y_true and y_pred and counts the number of non-zero elements along the specified axis, corresponding to the number of different labels predicted. It then checks if this count is equal to zero for each sample and converts the result to an integer.

For binary or multiclass classification problems, the code simply compares y_true and y_pred for equality, again converting the result to integers.

The function sums up the integer values, which represent the number of correct positive predictions, and optionally normalizes the result by dividing it by the total number of samples. The final result is cast as a float if normalization is enabled.

# PR Description 

## Related Issue 

Close #

## Checklist 

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by muzakkirhussain011** [comment]
Hi @jieunboy0516 ,

I've added a new function, precision_score, to the _classification.py module. This function is tailored to classification tasks and is designed to work seamlessly with Ivy. 

The precision_score function calculates precision, an essential metric for classification tasks, and contributes to Ivy's compatibility in machine learning projects.

I'd greatly appreciate it if you could review and provide your feedback on this addition.

Thank you

**Comment by muzakkirhussain011** [comment]
> Hi @muzakkirhussain011, you will also need to add a test for the function to make sure it works as expected.



> Hi @muzakkirhussain011, you will also need to add a test for the function to make sure it works as expected.

Hi @AnnaTz ,

Thank you for your feedback! I'm pleased to let you know that a test for the `precision_score` function has been added to ensure it works as expected.

You can check out the details in the pull request 
https://github.com/unifyai/ivy/pull/23264

If you have any more suggestions or questions, please feel free to let me know.

Best regards

**Comment by AnnaTz** [comment]
> > Hi @muzakkirhussain011, you will also need to add a test for the function to make sure it works as expected.
> 
> > Hi @muzakkirhussain011, you will also need to add a test for the function to make sure it works as expected.
> 
> Hi @AnnaTz ,
> 
> Thank you for your feedback! I'm pleased to let you know that a test for the `precision_score` function has been added to ensure it works as expected.
> 
> You can check out the details in the pull request #23264
> 
> If you have any more suggestions or questions, please feel free to let me know.
> 
> Best regards

Thanks! However, we prefer to merge a single PR containing a new function and its test. Please combine your 2 PRs to review them together.

**Comment by muzakkirhussain011** [comment]
> Thanks! However, we prefer to merge a single PR containing a new function and its test. Please combine your 2 PRs to review them together.

Hi @AnnaTz ,

Thank you for your feedback. I've now combined the two PRs into a single one for review.

You can find the updated PR with both the new function and its corresponding test at the following link: 
https://github.com/unifyai/ivy/pull/23277

Please review it, and let me know if you have any further suggestions or feedback.

Thanks again for your guidance.

Best regards

**Comment by zeus2x7** [comment]
Hi @muzakkirhussain011  the test function needs to be written in the ivy_tests/test_ivy/test_frontends/test_sklearn/test_metrics/test_classification.py file 
You can go through these sections of docs for much greater understanding 
[Ivy Tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html)
[Ivy Frontend Tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html)

**Review by zeus2x7 — COMMENTED** [review]
Hi @muzakkirhussain011 the test function needs to be written in the ivy_tests/test_ivy/test_frontends/test_sklearn/test_metrics/test_classification.py file
You can go through these sections of docs for much greater understanding
[Ivy Tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html)
[Ivy Frontend Tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html)

**Comment by muzakkirhussain011** [comment]
> Hi @muzakkirhussain011 the test function needs to be written in the ivy_tests/test_ivy/test_frontends/test_sklearn/test_metrics/test_classification.py file
> You can go through these sections of docs for much greater understanding
> [Ivy Tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html)
> [Ivy Frontend Tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html)

Hi @zeus2x7 ,

Thank you for your guidance. I've written the test function and placed it in the `ivy_tests/test_ivy/test_frontends/test_sklearn/test_metrics/test_classification.py` file.

You can find the updated PR with both the new function and its corresponding test at the following link:
https://github.com/unifyai/ivy/pull/23277

If you have any specific details or requirements for the test function, please let me know, and I'll make any necessary adjustments. Additionally, I'll review the provided sections of the documentation for a deeper understanding.

Thanks again for your assistance.

Best regards

**Comment by zeus2x7** [comment]
@muzakkirhussain011 can you close this PR which doesn't have the test function implemented as it would be better.

**Comment by muzakkirhussain011** [comment]
> @muzakkirhussain011 can you close this PR which doesn't have the test function implemented as it would be better.

Hi @zeus2x7 ,

Thank you for bringing this to my attention. I wanted to clarify that the PR containing the code and test function hasn't been assigned any reviewers yet. However, I've added the test function to the other PR that was lacking it and doesn't have any reviewers.

I appreciate your attention to detail, and please feel free to let me know if you have any further suggestions or requirements.

Best regards

**Comment by zeus2x7** [comment]
Hi, @muzakkirhussain011 another pr created by you #23277 has been assigned a reviewer and I have commented out a change on that pr, you can look into it.

**Pull request closed without merging**
