### PR TITLE
Torch frontend one hot

### PR DESCRIPTION
**Pull request by qAp**
https://github.com/unifyai/ivy/issues/3684

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
hi @qAp can you please fix the lint errors? Thanks!

**Comment by qAp** [comment]
@RickSanchezStoic Are the latest changes what you're after?

**Comment by RickSanchezStoic** [comment]
hi @qAp can you try resolving the merge conflicts? Thanks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
