### PR TITLE
Add bitwise_not instance method from torch tensor

### PR DESCRIPTION
**Pull request by JFMatos**

### CODE REVIEW

**Comment by JFMatos** [comment]
I need some help with these errors because the log from "intelligent-tests-pr / run_tests_1 (pull_request)" does not specify any information about what is causing the error, and the "lint / check-formatting (pull_request)" mentions files that I did not change.

**Comment by JFMatos** [comment]
Close #10190

**Comment by JFMatos** [comment]
Close #10190

**Comment by JFMatos** [comment]
I need some help with these errors because the log from "intelligent-tests-pr / run_tests_1 (pull_request)" does not specify any information about what is causing the error, and the "lint / check-formatting (pull_request)" mentions files that I did not change.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by nathzi1505** [comment]
Hey @JFMatos, apologies for the delay. 
Thank you so much for the commits :D.
I see that there are some tests failing as well as some lint issues.
Would you mind reviewing them and asking for a recheck again?

**Comment by JFMatos** [comment]
Hey @nathzi1505, the thing is that the errors are from other files and tests that I did not interact with. So, I don't know what to do.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request merged**
