### PR TITLE
reformatted shape

### PR DESCRIPTION
**Pull request by akarshitkverma**
- [ ] #1091 .

### CODE REVIEW

**Comment by akarshitkverma** [comment]
Hey @VedPatwardhan , I cannot figure out why the check is failing. Can you please help?

**Comment by VedPatwardhan** [comment]
Hi, @akarshitkverma, thanks for contributing, I'll go through the issue and get back to you by tomorrow!

**Comment by VedPatwardhan** [comment]
Hey, @akarshitkverma, the tests that are failing in your PR are a result of a previously existing issue, so we can merge your PR. Thanks a lot for contributing!

**Comment by akarshitkverma** [comment]
Thanks :)

**Pull request merged**
