### PR TITLE
Add Matmul function for Torch Frontend 

### LINKED ISSUE #10204: matmul

### PR DESCRIPTION
**Pull request by MuhammedAshraf2020**
close #10204

### CODE REVIEW

**Comment by MuhammedAshraf2020** [comment]
@suvadityamuk can you please have a look here ?

**Comment by suvadityamuk** [comment]
Hi @MuhammedAshraf2020 , 

it seems that the linting tests are failing. Please use the [pre-commit hook](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit) to repair the same. Thanks! :slightly_smiling_face:

**Comment by MuhammedAshraf2020** [comment]
> Hi @MuhammedAshraf2020 ,
> 
> It seems that the linting tests are failing. Please use the [pre-commit hook](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit) to repair the same. Thanks! slightly_smiling_face

all lint errors which is mine, i have solve it by pre-commit, the rest is not because of my code, can you check by yourself please?

**Comment by MuhammedAshraf2020** [comment]
hello, SuvAditya
i did pre-commit hock as you asked me to do , but there is no response from
you from that day to now , is everything ok?
all tests are passed on my device, and all lint errors that exist are not
mine "all of these lint errors also apperese to the rest of PR of other
people , you can check by yourself"
i want to know if there is any problem in my PR ? or at least when you will
check it by yourself.
Thank you for your time.

‫في الأربعاء، 8 فبراير 2023 في 4:15 م تمت كتابة ما يلي بواسطة ‪Suvaditya
Mukherjee‬‏ ***@***.***‬‏>:‬

**Pull request closed without merging**
