### PR TITLE
Update device.py

### PR DESCRIPTION
**Pull request by rsun0013**
for issue 1239

### CODE REVIEW

**Comment by Darshan-H-E** [comment]
Hi @rsun0013 please refer to https://lets-unify.ai/ivy/contributing/9_devices.html#devices. Please make changes in the argument type hint by making use of available ivy data types. And update the docstring as per the contributor guide.

**Comment by rsun0013** [comment]
hi, ive changed the type hint, but what else do i need to do for the docstrings, i followed the contributor guide for that

**Comment by Darshan-H-E** [comment]
Hi @rsun0013, both ivy.Device and ivy.NativeDevice can be passed to the argument device. So update the type hint accordingly. Remove the "Returns none" statement in the docstring as it's self evident because we are working with a constructor. Remove the print statement as it just shows the Default Device object instance and it's memory address. Add another example where "tpu" is the parameter. Reformat the function

**Comment by Darshan-H-E** [comment]
If you have any doubts, feel free to reach out. Thanks!

**Comment by rsun0013** [comment]
hi @Darshan-H-E ive made the requested changes

**Comment by Darshan-H-E** [comment]
Good job @rsun0013

**Comment by djl11** [comment]
@Darshan-H-E could you please squash and merge in future? :) Makes the commit history a bit cleaner. Thanks!

**Pull request merged**
