### PR TITLE
Add eigvals to NumPy Frontend

### LINKED ISSUE #22266: eigvals

### PR DESCRIPTION
**Pull request by abdllahdev**
Close #22266

### CODE REVIEW

**Comment by abdllahdev** [comment]
This PR for implementing the eigvals #22266 function to NumPy frontend

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by bipinKrishnan** [comment]
Hey @abdllahdev , the issue referred to in this PR is not correctly linked to the respective to-do list here https://github.com/unifyai/ivy/issues/1526. Can you please follow the steps mentioned [here](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) and do the required steps. Basically you would have to comment `- [] #<issue_number>` in the to-do list to link your issue. Thanks!

**Comment by abdllahdev** [comment]
Hi @bipinKrishnan, I updated my comment on #1526 to follow the instructions described in the docs but the issue is still not added to the ToDo list there seem to be problem with bot recognising the comments.

**Pull request closed without merging**
