### PR TITLE
ivy coding challenge final submisssion

### PR DESCRIPTION
**Pull request by keveaux**

### CODE REVIEW

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @keveaux , Can you make sure to add the type hint for the variable "as_str" as well ? It is a bool variable. Can you also make sure to add an example output of the function in ivy/functional/ivy/device.py ? 
Thank you for your effort.

**Comment by saeedashrraf** [comment]
Hello @keveaux , this looks better . One last comment, it is not necessary to make a call to the docstring_examples_run method as done [here](https://github.com/unifyai/ivy/pull/1023/files#diff-0e8ba5b04a942384961c29725afef8395744ddf88893d80cf924a3e6da5ad1aaR40). The test is run automatically for any methods with valid examples in the docstring

**Comment by keveaux** [comment]
Hello @saeedashrraf I have made the change ready for review

**Comment by saeedashrraf** [comment]
Hello @keveaux , thank you for your effort!

**Pull request merged**
