### PR TITLE
added exp instance method to paddle.tensor.tensor.Tensor. class

### PR DESCRIPTION
**Pull request by Br-Al**
#16171

### CODE REVIEW

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hello,

Looks like this PR makes changes to some .idea/ files. Can you please undo these changes as they are not relevant to the PR

Thanks :)

**Comment by Br-Al** [comment]
> 

Noted @jkeane508 ,
 
but I didn't manually update those files. But everything under the `.idea` folder should be ignored if I'm right.

**Comment by Br-Al** [comment]
Hello @jkeane508 ,
I'm done with the requested changes.

**Review by jkeane508 — APPROVED** [review]
LGTM!

**Pull request merged**
