### PR TITLE
Added docstrings and examples for logical_or

### PR DESCRIPTION
**Pull request by rensortino**
Solves #2249

### CODE REVIEW

**Comment by simonetgordon** [comment]
Hi there,

Thanks for the contribution! 😊

Your PR is currently failing the test-numpy-style docstrings test. Have a look at the 'Details' of the check to see what the exact issues are. Also, the lint test is now passing on master, so if update this branch with a pull from master, the lint test should hopefully pass. If it doesn't, it means there are some issues with this PR.

Simone

**Comment by rensortino** [comment]
Hi, @simonetgordon, thank you for your feedback, I updated the docs and there shouldn't be any more errors related to my function. Let me know if there are any more changes I need to do.

Also, I can't request a review as no reviewer shows up in the sidebar.

**Comment by simonetgordon** [comment]
Hi,

Thanks for the update! There are currently two failing tests which do not appear on the CI: lint and test-docstrings. Perhaps you only need to pull from master for these to be fixed. If they are still not passing after a pull, check the 'Details' of the tests and search for `logical_or` to see if it's causing the failures.

Kind Regards, 

Simone

**Comment by simonetgordon** [comment]
Hi there,

`logical_or` is failing the docstrings test. Here's the output:

```
E           AssertionError: 
E             The following methods had failing docstrings:
E             
E             Array.logical_or
E             logical_or
E             
E           assert False

ivy/ivy_tests/test_docstrings.py:107: AssertionError
----------------------------- Captured stdout call -----------------------------
output for  logical_or  on run:  ivy.array([True,True,False]) 
output in docs : vy.array([True,True,False]) 
 True  !=  vy.arrayTrue 

output for  logical_or  on run:  ivy.array([True,True,True]),ivy.array([[False,True,True],[True,True,True]]),ivy.array([1,1,0]),ivy.array([True,True,False]),{a:ivy.array([False,True,True]),b:ivy.array([True,True,True])},ivy.array([True,True,False]),{a:ivy.array([False,True,True]),b:ivy.array([True,True,True])},nocontainersfoundinargumentstorchz=ivy.Container.static_logical_or(x,y),{a:ivy.array([False,True,True]),b:ivy.array([True,True,True])} 

output in docs : ivy.array([True,True,True]),ivy.array([[False,True,True],[True,True,True]]),ivy.array([True,True,False]),ivy.array([True,True,False]),{a:ivy.array([False,True,True]),b:ivy.array([True,True,True])},ivy.array([True,True,False]),{a:ivy.array([False,True,True]),b:ivy.array([True,True,True])},ivy.array([True,True,True]) 
 1  !=  True 
 ```
 
 Try to push some fixes and let me know if you have any questions 😊

**Comment by rensortino** [comment]
@simonetgordon thank you for your feedback and your patience 😅. I checked the logs of the tests and now there shouldn't be any more related to the logical_or function. Let me know if I need to do anything else.

**Review by simonetgordon — APPROVED** [review]
looks good!

**Pull request merged**
