### PR TITLE
Refactored paddle avg_pooling frontend functions and thier tests

### PR DESCRIPTION
**Pull request by mohame54**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by AnnaTz — CHANGES_REQUESTED** [review]
Seems alright, similar to the changes you made to the torch frontend. However, the tests are failing. Were they failing before?

**Comment by mohame54** [comment]
Failing !! It worked fine with me.  I will check them again.

**Comment by mohame54** [comment]
could you show the failing tests @AnnaTz

**Comment by AnnaTz** [comment]
> could you show the failing tests @AnnaTz

seems it was a CI bug

**Pull request merged**
