### PR TITLE
hardswish

### PR DESCRIPTION
**Pull request by AlexandraPosta**
Hardswish PaddlePaddel

### CODE REVIEW

**Comment by AlexandraPosta** [comment]
Close #16017

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hi,

Looks like this implementation is failing tests here - https://github.com/unifyai/ivy/actions/runs/5114044325/jobs/9193890890?pr=16022

We need to get all tests passing before merging :)

**Comment by AlexandraPosta** [comment]
Hello! I believe the only issue is a lint error from other files. Is this correct?

**Comment by MahmoudAshraf97** [comment]
Hi, please open a new PR with only the relevant changes as this PR contains a lot of unrelated changes

**Pull request closed without merging**
