### PR TITLE
dropout 3d mindspore

### LINKED ISSUE #21050: dropout 3d mindspore
- [dropout3d] #21020

### PR DESCRIPTION
**Pull request by sushmanthreddy**
close #21050

### CODE REVIEW

**Comment by sushmanthreddy** [comment]
@paulaehab can u plss review the pull request pls?

**Comment by sushmanthreddy** [comment]
@paulaehab can u plss review th pull request?

**Comment by paulaehab** [comment]
Hi @sushmanthreddy sorry for late reply, Nice work just solve conflicts and I will merge it 😄

**Comment by sushmanthreddy** [comment]
@paulaehab can u plss merge it , I have made the changes
?

**Comment by paulaehab** [comment]
Co-authored-by: paulaehab<eng.paulaehab@gmail.com>

**Pull request merged**
