### PR TITLE
added cholesky_solve to paddle frontend

### LINKED ISSUE #18322: cholesky_solve

### PR DESCRIPTION
**Pull request by owais8**
Closes #18322

### CODE REVIEW

**Comment by owais8** [comment]
Kindly check my PR locally as all tests are passing locally. Issue seems to be with Github CI. Feel free to clone my repo locally to verify

**Comment by owais8** [comment]
@Ishticode formatting seems to be correct. Don't know why lint is failing
Kindly do let me know if any changes are required.
Thanks 🙂

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @owais8 
Thankyou for the PR and sorry for delay on my end. I will keep your PR on priority and give follow up reviews asap.

I have ran the `test_paddle_cholesky_solve` locally and it fails. This is due to the signature mismatch between your implementatin of `cholesky_solve` with `chol` and `rhs` and that of the paddles cholesky_solve which has `x` and `y` params as seen at [here]( https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/linalg/cholesky_solve_en.html). 

Are you sure when you ran `test_paddle_cholesky_solve` on ur system it passes? I can't see how it gets past the `test_frontend_function` calling the actual native paddle function with the wrong parameters!

Please check [our guide for frontend implementations](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html) or ask any follow up questions. Then you can make relevant updates and request a review when done. Thank you 🙂

**Comment by owais8** [comment]
Closing this as the resolve conflicts button is not available for me. Also I made this PR from my master branch which isn't good practice at all. Sorry for inconvenience

**Pull request closed without merging**
