### PR TITLE
at #7499

### PR DESCRIPTION
**Pull request by norman135**
I might need help.
The method is currently taking in the ufunc as an argument and working as it should. It was the only way I could get the function to be dynamic that way I wouldn't have to define all ufuncs. The tests are printing nothing. I'd appreciate any form of help to optimize this like how it should be, because I think this way might not be optimal, or even considerable.
Thank you.🙏

### CODE REVIEW

**Comment by norman135** [comment]
#7499

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @norman135 You will actually have to create a ufunc class (as given here, https://numpy.org/doc/stable/reference/generated/numpy.ufunc.html), and then add the "at" method for the same. Hope that helps!

**Comment by norman135** [comment]
> Hi @norman135 You will actually have to create a ufunc class (as given here, https://numpy.org/doc/stable/reference/generated/numpy.ufunc.html), and then add the "at" method for the same. Hope that helps!

That should help. I'll get to it.
Appreciate.

**Comment by norman135** [comment]
#8821

**Pull request closed without merging**
