### PR TITLE
Reformat outer

### PR DESCRIPTION
**Pull request by whatcoloris**
Thanks to @mattbarrett98 for pointing out I had misunderstood the Reformatting task. Here's another attempt using the already completed SVD and Diagonal methods as guides for what needs to be done.
1.) added return value and line breaks to backend code
2.) added examples to docstrings, and fixed perceived error in docstring
Thank you again to the Ivy team.

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @whatcoloris. Many Thanks for the PR. Could you kindly reformat the outer function in the other backends too.

**Comment by juliagsy** [comment]
Hey there! As this PR is inactive for more than 7 days, it will be closed in 24 hours if there are no further response. If you have made changes and need the next review, please request a new review so that we are notified and aware of it! Thank you!

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @whatcoloris. Could you kindly remove the conflicts... If you need help or you find it difficult please let me know and I will help. **Once done, please don't forget to request my review.**

**Review by Ishticode — CHANGES_REQUESTED** [review]
There were some tests being added/fixed. Could you update your fork branch? (Pls don't force push). If its passes I will merge it right away. I think your PR looks good otherwise. thnx

**Review by Ishticode — APPROVED** [review]
I have gone ahead and ran the tests locally on your branch. All is fine. I will go ahead and merge this now. Thank you for your contribution. 😊

**Pull request merged**
