### PR TITLE
setxor1d

### PR DESCRIPTION
**Pull request by Sarvesh-Kesharwani**
image

ar1: ivy.array([0, 0])
ar2: ivy.array([1, 1])

Closed https://github.com/unifyai/ivy/issues/11989

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by hmahmood24** [comment]
> image
> 
> ar1: ivy.array([0, 0]) ar2: ivy.array([1, 1])
> 
> Closed #11989

Hey @Sarvesh-Kesharwani. Can you provide me more details as to which backend is failing ?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Sarvesh-Kesharwani** [comment]
waiting for review.

**Review by abdulasiraj — CHANGES_REQUESTED** [review]
you're using the data types that are not available in paddlepaddle. please have a look.
```
E   RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), bfloat16) of kernel `argsort` is not registered. Selected wrong DataType `bfloat16`. Paddle support following DataTypes: int32, int64, float64, float32.
```

**Comment by Sarvesh-Kesharwani** [comment]
Issue resolved.

**Comment by Sarvesh-Kesharwani** [comment]
> you're using the data types that are not available in paddlepaddle. please have a look.
> 
> ```
> E   RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), bfloat16) of kernel `argsort` is not registered. Selected wrong DataType `bfloat16`. Paddle support following DataTypes: int32, int64, float64, float32.
> ```
Issue resolved!

**Pull request merged**
