### PR TITLE
Added more examples in the docstring for function

### LINKED ISSUE #1167: einsum

### PR DESCRIPTION
**Pull request by RohitRathore1**
Fixes #1167 

- Reformat the docstring of einsum in statistical.py to NumPy style
- Added more examples for the function `einsum`

### CODE REVIEW

**Comment by RohitRathore1** [comment]
@1Doomdie1 can you please tell me why other test cases have failed? As I have made changes only for the doctsctrings.

**Comment by simonetgordon** [comment]
Hi Rohit,

Thanks for making a contribution!

Make sure you are only making changes in the relevant docstring file (ivy/functional/ivy/statistical.py). Please undo changes in the other files as we cannot merge to the master branch otherwise. 

In order for the docstring tests to pass, a slight reformatting of the arrays needs to be done:
>>> B = ivy.array([[ 0,  1,  2,  3],
    ...               [ 4,  5,  6,  7],
    ...               [ 8,  9, 10, 11]])

Should be 

Were you intending to just making changes for `einsum`? As that is the only function which has changes in this PR. I'm just verifying this as In your PR description you said "Reformat the docstring of `sum` in statistical.py to NumPy style", but perhaps you meant `einsum` here?

Also, there are some formatting errors detected by lint in ivy/functional/ivy/statistical.py. You can see a description of these issues by clicking 'details' on the right of the lint check.

As for the other failing checks, I wouldn't worry too much about these as they are also failing on the master branch. But please do remove changes in all files exc

**Comment by simonetgordon** [comment]
Hi Rohit,

Thanks for making a contribution!

Make sure you are only making changes in the relevant file (ivy/functional/ivy/statistical.py). Please undo changes in the other files as we cannot merge to the master branch otherwise.

In order for the docstring tests to pass, a slight reformatting of the arrays in the examples needs to be done:

B = ivy.array([[ 0, 1, 2, 3],
... [ 4, 5, 6, 7],
... [ 8, 9, 10, 11]])

Should be

B = ivy.array([[ 0, 1, 2, 3],\
                       [ 4, 5, 6, 7],\
                      [ 8, 9, 10, 11]])


Were you intending to just making changes for einsum? As that is the only function which has changes in this PR. I'm just verifying this as In your PR description you said "Reformat the docstring of sum in statistical.py to NumPy style", but perhaps you meant `einsum` here?

Also, there are some formatting errors detected by lint in ivy/functional/ivy/statistical.py. You can see a description of these issues by clicking 'details' on the right of the lint check. 

As for the other failing checks, I wouldn't worry too much about these as they are also failing on the master branch. 

Thanks again!

Simone

**Comment by RohitRathore1** [comment]
> Hi Rohit,
> 
> Thanks for making a contribution!
> 
> Make sure you are only making changes in the relevant file (ivy/functional/ivy/statistical.py). Please undo changes in the other files as we cannot merge to the master branch otherwise.
> 
> In order for the docstring tests to pass, a slight reformatting of the arrays in the examples needs to be done:
> 
> ```
> >>> A = ivy.array([0, 1, 2])
> >>> B = ivy.array([[ 0,  1,  2,  3],
> ...               [ 4,  5,  6,  7],
> ...               [ 8,  9, 10, 11]])
> ```
> 
> Should be
> 
> ```
> >>> A = ivy.array([0, 1, 2])
> >>> B = ivy.array([[ 0,  1,  2,  3],\
>                   [ 4,  5,  6,  7],\
>                   [ 8,  9, 10, 11]])
> ```
> 
> Were you intending to just making changes for einsum? As that is the only function which has changes in this PR. I'm just verifying this as In your PR description you said "Reformat the docstring of sum in statistical.py to NumPy style", but perhaps you meant `einsum` here?
> 
> Also, there are some formatting errors detected by lint in ivy/functional/ivy/statistical.py. You can see a description of these issues by clicking 'details' on the right of the lint check.
> 
> As for the other failing checks, I wouldn't worry too much about these as they are also failing on the master branch.
> 
> Thanks again!
> 
> Simone

Hi @simonetgordon Thanks for your review. I have made the following changes which you had asked. 

> Were you intending to just making changes for einsum? As that is the only function which has changes in this PR. I'm just verifying this as In your PR description you said "Reformat the docstring of sum in statistical.py to NumPy style", but perhaps you meant einsum here?
here I have fixed that. 

Now you can review my PR. I am looking forward to it.
Thanks!

**Comment by simonetgordon** [comment]
Hi Rohit, 

Thanks for amending the files such that only ivy/functional/ivy/statistical.py is the only one with changes :)

However, there are still some formatting issues with this file, this time detected by flake8. The errors are:
```
ivy/functional/ivy/statistical.py:75:89: E501 line too long (89 > 88 characters)
ivy/functional/ivy/statistical.py:211:[8](https://github.com/unifyai/ivy/runs/6633931411?check_suite_focus=true#step:5:9)9: E501 line too long (89 > 88 characters)
```

Also, the '\' needs to be add to all example arrays, including the big one.

Thanks again!

Simone

**Comment by RohitRathore1** [comment]
> ivy/functional/ivy/statistical.py:75:89: E501 line too long (89 > 88 characters)

Hey @simonetgordon thanks for your feedback again.

If you will check this line:
```
ivy/functional/ivy/statistical.py:75:89: E501 line too long (89 > 88 characters)
```

then it is pointing to line number 75 in the code which is the docstring of another function that's why I was not touching but now I have fixed please have a look.
Thanks!

**Comment by simonetgordon** [comment]
Hi Rohit,

Thanks for pointing that out, and thanks for making the changes. Just one small thing to fix. The output of docstring example does not need to have '\' at the end of an array line, i.e.
```
    >>> ivy.einsum('ij,jk->ik', A, B)
    ivy.array([[ 2,  3,  1],\
                [ 4,  6,  2],\
                [10, 15,  5]])
```
can have the '\' removed. Only input arrays (begin with `>>>`) need to have this. The contributer guide has been updated to reflect this: https://lets-unify.ai/ivy/contributing/13_docstring_examples.html#docstring-examples

Thanks!

Simone

**Comment by RohitRathore1** [comment]
> Hi Rohit,
> 
> Thanks for pointing that out, and thanks for making the changes. Just one small thing to fix. The output of docstring example does not need to have '' at the end of an array line, i.e.
> 
> ```
>     >>> ivy.einsum('ij,jk->ik', A, B)
>     ivy.array([[ 2,  3,  1],\
>                 [ 4,  6,  2],\
>                 [10, 15,  5]])
> ```
> 
> can have the \ removed. Only input arrays (begin with `>>>`) need to have this. The contributer guide has been updated to reflect this: https://lets-unify.ai/ivy/contributing/13_docstring_examples.html#docstring-examples
> 
> Thanks!
> 
> Simone

hi @simonetgordon done! pease can you check once?
Thank you!

**Pull request merged**
