### PR TITLE
mdct #23604

### LINKED ISSUE #23604: mdct

### PR DESCRIPTION
**Pull request by vicentescardoso**
PR Description
This PR introduces the MDCT (Modified Discrete Cosine Transform) functionality to the Ivy framework. The new mdct function has been added, providing developers with more tools for audio and signal processing within the framework.

Related Issue
Close #23604

Checklist
 Did you add a function?
Yes, the mdct function has been added.
 Did you add the tests?
Tests have been added and can be found in the respective test file for the mdct function.
 Did you run your tests and are your tests passing?
Tests were executed successfully.
 Did pre-commit not fail on any check?
Pre-commit checks were executed successfully.
 Did you follow the steps we provided?
Yes, I adhered to the contribution guidelines and coding standards of the Ivy framework. Additional linting was performed using flake8 and pylint.

### CODE REVIEW

**Comment by vicentescardoso** [comment]
Hey @kurshakuz I think all relevant tests passed. Let me know if you need anything!

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hello!

Seems like there are some attribute discover issues:
```
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py::test_tensorflow_mdct[cpu-numpy-False-False] - AttributeError: module 'ivy.functional.backends.numpy' has no attribute 'mdct'
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py::test_tensorflow_mdct[cpu-jax-False-False] - AttributeError: module 'ivy.functional.backends.jax' has no attribute 'mdct'
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py::test_tensorflow_mdct[cpu-tensorflow-False-False] - AttributeError: module 'ivy.functional.backends.tensorflow' has no attribute 'mdct'
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py::test_tensorflow_mdct[cpu-torch-False-False] - AttributeError: module 'ivy.functional.backends.torch' has no attribute 'mdct'
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py::test_tensorflow_mdct[cpu-paddle-False-False] - AttributeError: module 'ivy.functional.backends.paddle' has no attribute 'mdct'
```
Can you please take a look and resolve them?

**Comment by vicentescardoso** [comment]
Hey @kurshakuz. Thank you for bringing this to my attention. The test failures are expected at this stage because the mdct function has not yet been implemented in the backend. This is similar to the situation with some other functions in this file.If you're comfortable with it, I would suggest merging this PR as is. I plan to work on the backend implementation in a separate PR to follow.

**Comment by vicentescardoso** [comment]
Hey @kurshakuz , can you take a look? Thanks. This is expected, no backend for this function

**Comment by vicentescardoso** [comment]
@kurshakuz hey, can you answer so we can close this one? Thanks!

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! It can not be merge as you have to either implement the backend function or use a compositional solution.

Please open a new PR addressing those changes. Thanks!

**Pull request closed without merging**
