### PR TITLE
Create Input

### PR DESCRIPTION
**Pull request by hrak99**
#4215

### CODE REVIEW

**Comment by hrak99** [comment]
My apologies! I just tried to send you a PR. Maybe the format is not the right one as there is an error too. Please advise me in this regard.

**Comment by hrak99** [comment]
why is giving "ivy_tests/test_ivy/test_frontends/test_torch/test_non_linear_activation_functions.py:73:5: E999 SyntaxError: invalid syntax".

**Comment by hrak99** [comment]
I'm also trying to run the same code on PyCharm, but every time it gives the error "jax requires jaxlib to be installed".
I'm using Windows.

**Comment by hrak99** [comment]
I tried to run .py files  (math.py, and test_math.py) located in TensorFlow in different folders on Pycharm but every time Jax module error is generated. I'm using windows. Please also tell me if the new code is generated in mentioned two files, then how I link with the pull request (PR).

**Comment by hrak99** [comment]
A lot of questions are coming as I'm trying to explore, :). How to deal with parameters or variables like **kwargs. In cases like tensorflow input, this parameter is supporting batch_shape and batch_input_shape.

**Comment by Oxbeefbabe** [comment]
Hi, apologies for the slow response, I am currently away and have minimal access to the internet! I'll comment when possible, and I should be back to my regular schedule from next week.

The `**kwargs` argument is a catch-all argument that collects any keyword arguments that were not specified in the function definition and makes them accessible through a dictionary under the `kwargs` variable within the function definition. 

Another issue I'm seeing is that you are writing the code in the wrong file. There should be a file under `ivy\frontends\tensorflow` called `layers.py`. According to the task list it should be empty right now. You should check the other frontend files for tensorflow to see how to properly make imports. Then your test should go in the corresponding test file in `test_ivy`. You should look at the Deep Dive blogs for the Frontend API and Frontend API Tests for more information on how to do these.

**Comment by Oxbeefbabe** [comment]
Forgot to mention that the Deep Dives I mentioned are accessible from the Ivy Documentation :)

**Comment by hrak99** [comment]
> Hi, apologies for the slow response, I am currently away and have minimal access to the internet! I'll comment when possible, and I should be back to my regular schedule from next week.
> 
> The `**kwargs` argument is a catch-all argument that collects any keyword arguments that were not specified in the function definition and makes them accessible through a dictionary under the `kwargs` variable within the function definition.
> 
> Another issue I'm seeing is that you are writing the code in the wrong file. There should be a file under `ivy\frontends\tensorflow` called `layers.py`. According to the task list it should be empty right now. You should check the other frontend files for tensorflow to see how to properly make imports. Then your test should go in the corresponding test file in `test_ivy`. You should look at the Deep Dive blogs for the Frontend API and Frontend API Tests for more information on how to do these.

thanks for your comprehensive response.

**Comment by hrak99** [comment]
I'm still a little bit confused about where to write the code. Layers.py is the file to use for coding.

**Comment by hrak99** [comment]
> I'm still a little bit confused about where to write the code. Layers.py is the file to use for coding.

There is another file test_layers.py in the ivy_test directory. I think i have to use these two files

**Comment by hrak99** [comment]
test_results
How to create test result folders. Because I'm facing empty suit problem as well. Please guide me in this regard. Because the real work starts after that configuration.

**Comment by hrak99** [comment]
waiting for your reply, :).  I'm trying to find solution but still finding a way to in.

**Comment by Oxbeefbabe** [comment]
The code for the `input` function should go in the file: `ivy/functional/frontends/tensorflow/layers.py`. You should check the other files in `ivy/ivy/functional/frontends/tensorflow` to see what imports you should be calling. 

The test function for the `input` function should go in `ivy_tests/test_ivy/test_frontends/test_tensorflow/test_layers.py`. Again, check the other files in `ivy_tests/test_ivy/test_frontends/test_tensorflow` to see what imports you should call and how your test should be structured. 

You should then be able to run the `test_layers.py` file as a pytest function (pyCharm should automatically give you the option if you have a function with the word `test` in its name, e.g. `test_input`). You will need to add into the additional arguments in the configuration generated: `--backend all`. This way the frontend is tested with all of the backends. 

Again, apologies for the slow response, my internet connection is currently limited and I'm on a reduced schedule. I should be more accessible from next week.

**Comment by hrak99** [comment]
> The code for the `input` function should go in the file: `ivy/functional/frontends/tensorflow/layers.py`. You should check the other files in `ivy/ivy/functional/frontends/tensorflow` to see what imports you should be calling.
> 
> The test function for the `input` function should go in `ivy_tests/test_ivy/test_frontends/test_tensorflow/test_layers.py`. Again, check the other files in `ivy_tests/test_ivy/test_frontends/test_tensorflow` to see what imports you should call and how your test should be structured.
> 
> You should then be able to run the `test_layers.py` file as a pytest function (pyCharm should automatically give you the option if you have a function with the word `test` in its name, e.g. `test_input`). You will need to add into the additional arguments in the configuration generated: `--backend all`. This way the frontend is tested with all of the backends.
> 
> Again, apologies for the slow response, my internet connection is currently limited and I'm on a reduced schedule. I should be more accessible from next week.

thanks for the response. Now I'm close to writing the code but PyCharm is giving jaxlib error (windows) constantly. Can we avoid or ignore this error through settings, or I have to install docker as there is no other option for windows?

**Comment by Oxbeefbabe** [comment]
Sorry for the delay.

I'm not sure what error you are speaking about. Docker is definitely an excellent way to go. If you have a student email, you can sign up to get the PyCharm Professional edition for free, allowing you to use Docker interpreters. I personally use Docker myself when working on Ivy.

**Comment by hrak99** [comment]
> Sorry for the delay.
> 
> I'm not sure what error you are speaking about. Docker is definitely an excellent way to go. If you have a student email, you can sign up to get the PyCharm Professional edition for free, allowing you to use Docker interpreters. I personally use Docker myself when working on Ivy.

I don't have that access (student email). That's why I'm using the Community edition but the options are not available according to any youtube tutorial or the documentation regarding remote docker python interpreter settings.  Now I'm turned to VS and trying to connect with docker (it's taking a lot of time at the moment). I will try one more time with Pycharm professional (trial version). Let see ...

**Comment by Oxbeefbabe** [comment]
Yeah, unfortunately, JetBrains has only included the ability to use a remote Docker Interpreter in PyCharm Professional Edition. You cannot do it with the Community Version. I see you are already doing but I would suggest using a different IDE, or if you want to stick with PyCharm, you can follow this guide on the docs which should hopefully set everything up properly. (https://lets-unify.ai/ivy/contributing/0_setting_up.html#virtual-environments-no-docker)

**Review by hrak99 — COMMENTED** [review]
I have just used a previously solved function to establish a pipeline. Is it now fine? So that i can start on the given query.

**Comment by hrak99** [comment]
> I have just used a previously solved function to establish a pipeline. Is it now fine? So that I can start on the given query.

There is also showing a problem "This branch has conflicts that must be resolved".

**Comment by hrak99** [comment]
I connected Pycharm successfully with Docker. Now I'm facing this issues;-

ImportError while loading conftest '/opt/project/ivy_tests/test_array_api/conftest.py'.
test_array_api/conftest.py:7: in <module>
    from array_api_tests import _array_module as xp
test_array_api/array_api_tests/__init__.py:6: in <module>
    from ._array_module import mod as _xp
test_array_api/array_api_tests/_array_module.py:27: in <module>
    raise RuntimeError("No array module specified. Either edit _array_module.py or set the ARRAY_API_TESTS_MODULE environment variable")
E   RuntimeError: No array module specified. Either edit _array_module.py or set the ARRAY_API_TESTS_MODULE environment variable

Kindly assist me in this regard so that i can start on the problem now, :)

**Comment by hrak99** [comment]
> I connected Pycharm successfully with Docker. Now I'm facing these issues;-
> 
> ImportError while loading conftest '/opt/project/ivy_tests/test_array_api/conftest.py'. test_array_api/conftest.py:7: in from array_api_tests import _array_module as xp test_array_api/array_api_tests/**init**.py:6: in from ._array_module import mod as _xp test_array_api/array_api_tests/_array_module.py:27: in raise RuntimeError("No array module specified. Either edit _array_module.py or set the ARRAY_API_TESTS_MODULE environment variable") E RuntimeError: No array module specified. Either edit _array_module.py or set the ARRAY_API_TESTS_MODULE environment variable
> 
> Kindly assist me in this regard so that i can start on the problem now, :)

Update Question:-
After editing the attached _array_module.py,
changes_in_array_module

got this error
2022-09-24 23:07:18.196441: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
ImportError while loading conftest '/opt/project/ivy_tests/test_array_api/conftest.py'.
test_array_api/conftest.py:7: in <module>
    from array_api_tests import _array_module as xp
test_array_api/array_api_tests/__init__.py:6: in <module>
    from ._array_module import mod as _xp
test_array_api/array_api_tests/_array_module.py:9: in <module>
    ivy.set_framework('tensorflow')
E   AttributeError: module 'ivy' has no attribute 'set_framework'

Process finished with exit code 4

Empty suite

**Comment by hrak99** [comment]
if I changed ivy.set_framework('tensorflow') to ivy.backend('tensorflow')
then, ERROR: file or directory not found: C:/Users/shahzaib laptops/PycharmProjects/ivy/ivy_tests/test_ivy. 
Though I have changed the directory too like the attached file.
dir
but don't know exactly what to do.

**Comment by hrak99** [comment]
Now it's working to some extent as I disabled the option "python.use.targets.api". Still facing
array_module_changes
[Error.pdf](https://github.com/unifyai/ivy/files/9649747/Error.pdf)
 different errors. I have attached the screenshot and errors report for your perusal.

**Comment by hrak99** [comment]
Waiting :)

**Review by hrak99 — COMMENTED** [review]
Plz check

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey there! Thanks for contributing! I'm your new assignee, since I'm only taking over your PR recently, I have a few confusion

1) May I know what is the current issue which you're facing now? Just to check as I saw a few but not sure which are persisting or resolved. 

2) For the function you're working on, I see that the PR states `input`, the same for your issue and the linked issue to the ToDo list. However, I see that your changes are the `add` function instead, may I know what function are you working on now?

3) Please keep your PyCharm `.idea` configurations locally, without pushing them to this PR. The PR should only consist of changes related to your selected function and its test.

Thanks a lot!

**Comment by hrak99** [comment]
> Hey there! Thanks for contributing! I'm your new assignee, since I'm only taking over your PR recently, I have a few confusion
> 
> 1. May I know what is the current issue which you're facing now? Just to check as I saw a few but not sure which are persisting or resolved.
> 2. For the function you're working on, I see that the PR states `input`, the same for your issue and the linked issue to the ToDo list. However, I see that your changes are the `add` function instead, may I know what function are you working on now?
> 3. Please keep your PyCharm `.idea` configurations locally, without pushing them to this PR. The PR should only consist of changes related to your selected function and its test.
> 
> Thanks a lot!

Many thanks for your response.
[Error.pdf](https://github.com/unifyai/ivy/files/9668819/Error.pdf)
Basically, I'm working on the TensorFlow input function. Due to configuration problems, I just used the previously solved functions like TensorFlow add function to just check the test results and commit option. 
Please elaborate further about "PyCharm `.idea` configurations".  Do you mean "don't push" the solved functions to PR?
One more thing I would like to ask about my coding files layers.py & test_layers.py files. Whether these files will create no hurdle regarding PR if I write only the new code according to the "todo list issue" and commit.

**Comment by juliagsy** [comment]
@hrak99 Thanks for your reply!

I see, noted.

As for the `idea` configurations, if you see in the "file changes" tab of this PR, the configurations made on your side are being saved in this PR, which should not be the case as the `idea` folder should not have changes. All changes should only be related to the function implementation and testing (which are `input` in tensorflow frontend, and `test_tensorflow_input` in tensorflow frontend tests).

Thanks!

**Comment by juliagsy** [comment]
btw, since your PR is a lot behind on our master (where there are a lot of new changes and commits on the ivy master branch now), would you like to maybe update your fork and create a new PR so that your fork is up to date and changes maybe a bit more tidy :)

thanks again!

**Pull request closed without merging**
