### PR TITLE
add atan to jax

### PR DESCRIPTION
**Pull request by PatricYan**
- [ ] #3090 
- add atan to jax

### CODE REVIEW

**Comment by PatricYan** [comment]
I have resolved the conflict, would you like to make a review?

**Comment by sreegandh804** [comment]
Sure thing @PatricYan , It looks good, I'll review it and merge it once I have a look at the tests as well 🙂

**Comment by sreegandh804** [comment]
@PatricYan , the test related to your atan function seems to be failing, do you mind taking a look at it?😅

**Comment by PatricYan** [comment]
> @PatricYan , the test related to your atan function seems to be failing, do you mind taking a look at it?😅

@sreegandh804 ok, I will take a look at it, and fix all the problems

**Comment by PatricYan** [comment]
@sreegandh804 I have fixed the test cases, it is caused by the new test condition **handle_cmd_line_args**

**Comment by PatricYan** [comment]
I have fixed all the test cases in test_jax by adding **@handle_cmd_line_args**

**Comment by sreegandh804** [comment]
@PatricYan I would suggest you make changes only to the function that has been assigned to you, i.e atan to get your tests passing, as long as the test relevant only to your function is passing, I'll get it merged

**Comment by PatricYan** [comment]
> @PatricYan I would suggest you make changes only to the function that has been assigned to you, i.e atan to get your tests passing, as long as the test relevant only to your function is passing, I'll get it merged

Hi @sreegandh804 , in my localhost, all test are well.

**Comment by PatricYan** [comment]
Hi @sreegandh804 , I have removed other code, and just fix my test case atan by adding **@handle_cmd_line_args**

**Comment by PatricYan** [comment]
in localhost 
```
Launching pytest with arguments --backend jax test_jax_lax_operators.py::test_jax_lax_atan --no-header --no-summary -q in /Users/yanpengfei/yanllearnn/GitHub/ivy/ivy_tests/test_ivy/test_frontends/test_jax

============================= test session starts ==============================
collecting ... collected 1 item

test_jax_lax_operators.py::test_jax_lax_atan[cpu-ivy.functional.backends.jax-True-False-jnp_call-jax] <- ivy_tests/test_ivy/helpers.py 

============================== 1 passed in 0.22s ===============================

Process finished with exit code 0
PASSED [100%]
```

**Comment by sreegandh804** [comment]
Yeah sorry about that,  the failures don't seem to be a problem caused by your code, I will get it merged as soon as you resolve the conflicts 😅 .

**Comment by PatricYan** [comment]
done, @sreegandh804

**Comment by sreegandh804** [comment]
Thanks a lot, @PatricYan  for contributing. 😄

**Pull request merged**
