### PR TITLE
Update tree_generation.py

### PR DESCRIPTION
**Pull request by Aryan4884**
Fixed a typo

### CODE REVIEW

**Comment by Aryan4884** [comment]
It is a typo error. Plz review it and merge it.

**Review by he11owthere — CHANGES_REQUESTED** [review]
Hello! Thank you for catching those small mistakes. You'll need to rename the same variable at line number 124 as well:
https://github.com/unifyai/ivy/blob/2eb070c034196498366b6899dda8b3631ad82550/scripts/backend_generation/tree_generation.py#L124

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
