### PR TITLE
Reformatted the is_native_array function (#1382)

### PR DESCRIPTION
**Pull request by nbalcarc**
#1382

### CODE REVIEW

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi, can you update the type hints in ivy as well as all the other back ends? Thanks.

**Comment by nbalcarc** [comment]
I've fixed the failing check, all checks should be passing now.

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi, can you update the type hints for input x? From your example, x takes inputs both ivy arrays and native arrays. Also, could you add an example of using exclusive as one of the parameters? Thanks.

**Review by MarShaikh — APPROVED** [review]
Great, looks good!

**Pull request merged**
