### PR TITLE
Adding jax lax is_finite operator and tests

### PR DESCRIPTION
**Pull request by Sjsingh101**
For the `is_finite` operator (addressed in the issue https://github.com/unifyai/ivy/issues/13916):

- Implements Ivy Frontend API.
- Includes Ivy Frontend Tests.

There was a typo in https://github.com/unifyai/ivy/issues/1578 as the list of operators doesn't have `is_dinite`.

Ref: [Operator functions](https://jax.readthedocs.io/en/latest/jax.lax.html#operators)

### CODE REVIEW

**Comment by Sjsingh101** [comment]
Hi @V-G-spec , I have gone through the Pull Requests section of this [doc](https://lets-unify.ai/docs/ivy/overview/contributing/the_basics.html#pull-requests) and have addressed all the failing tests except one (run_tests_30). 

The `jax.lax .real` function always return the result with float32 datatype but it should be following relation mentioned below: 
- Input datatype: complex128 => Output datatype: float64
- Input datatype: complex64 => Output datatype: float32

As `ivy.dtype` is not working on complex object then how can we fetch the exact datatype of the input? Could you please help me with this?

**Comment by Sjsingh101** [comment]
Hi @CatB1t and @VedPatwardhan, I have updated the branch with a merge commit and fixed rest of the linting errors. I ran `flake8 $(git ls-files '*.py')` locally but it is not replicating this particular linting error. Apart from that, The `jax.lax.real` function is still causing problem in all backends (test in some backends passed due to favourable nature of input). I need some guidance as mentioned in above comment to sort this function.

P.S: All the tests directly related to is_finite function passed properly.

**Comment by CatB1t** [comment]
Hello @Sjsingh101, GitHub automatically requests a review when a file flagged in the CODEOWNER file is changed, as it seems the changes aren't intentional, I'll remove me and @VedPatwardhan from the reviewers. In the meanwhile @MahmoudAshraf97 should be able to help you further with the PR. Thanks! 😄

**Comment by V-G-spec** [comment]
Apologies for the delay @Sjsingh101, I was on an off for the past 2 weeks

**Comment by V-G-spec** [comment]
Can you start with resolving the merge conflicts? We will then take it from there to solve the remaining test failures
Thanks!

**Comment by Sjsingh101** [comment]
Hello @V-G-spec, Welcome back! I have closed this PR while syncing the fork by mistake. I have raised a new PR and all the failing test are unrelated to the files I have added. Please take a look. Link to new PR: https://github.com/unifyai/ivy/pull/15476

**Pull request closed without merging**
