### PR TITLE
feat: implement complex operator in jax.lax

### LINKED ISSUE #21788: complex

### PR DESCRIPTION
**Pull request by Tonycrux**
# PR Description

## Related Issue

Close #21788

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials
https://twitter.com/istonycrux

### CODE REVIEW

**Comment by mohame54** [comment]
Hi @Tonycrux thanks for contribution, I think your frontend  implementation is not compatible with jax.lax.complex

**Comment by Tonycrux** [comment]
Hi @mohame54 I have fixed that. Please check it now.

**Comment by mohame54** [comment]
looks good to me @Tonycrux and thanks for contribution.

**Comment by Tonycrux** [comment]
Thank you @mohame54

**Pull request merged**
