### PR TITLE
added diag to torch frontend

### LINKED ISSUE #4137: diag

### PR DESCRIPTION
**Pull request by L-Hinkle**
Close #4137

### CODE REVIEW

**Comment by L-Hinkle** [comment]
Currently fails paddle test because there is a flaw in the paddle backend. The function `diag` calls itself recursively and never terminates.

**Comment by Daniel4078** [comment]
> Currently fails paddle test because there is a flaw in the paddle backend. The function `diag` calls itself recursively and never terminates.

I will look into this problem and try to inform other Ivy members to fix the ivy.diag for paddle backend. What about the other frameworks?

**Comment by L-Hinkle** [comment]
> > Currently fails paddle test because there is a flaw in the paddle backend. The function `diag` calls itself recursively and never terminates.
> 
> I will look into this problem and try to inform other Ivy members to fix the ivy.diag for paddle backend. What about the other frameworks?

The

> > Currently fails paddle test because there is a flaw in the paddle backend. The function `diag` calls itself recursively and never terminates.
> 
> I will look into this problem and try to inform other Ivy members to fix the ivy.diag for paddle backend. What about the other frameworks?

It passes for the other frameworks

**Review by Daniel4078 — APPROVED** [review]
I have asked someone to try fix the diag for the paddlepaddle backend and for now, I can just merge your code as it works well for all other backends and passes the current CI checks.

**Pull request merged**
