### PR TITLE
#16510 mean

### PR DESCRIPTION
**Pull request by inthedepthsofitall**
# PR Description 

## Related Issue 

Close #

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Infrared1029** [comment]
hello @inthedepthsofitall, thanks for taking the time to contribute to ivy, however, you should make sure to contribute with one and only one function in a PR, it is also important to note that we handle tests in their specific test frontend files, using hypothesis, i highly recommend reading the docs + watching some of our youtube videos to get a better idea, thanks!

**Comment by inthedepthsofitall** [comment]
These are from past pulls, there is only function, the mean function with its own file on the NN of paddle

**Comment by inthedepthsofitall** [comment]
@Infrared1029  please check, had to rebase initial commits

**Comment by Infrared1029** [comment]
> @Infrared1029 please check, had to rebase initial commits

Sorry for the late reply, But again, this is not how frontend functions or tests are added in ivy, as advised previously, please take the time to properly read the documentation and figure out how adding frontend functions and their test is done in ivy, i'll be closing the PR as rewriting this properly will most likely require a new PR.

**Pull request closed without merging**
