### PR TITLE
add instance Methods to Numpy Frontend sort

### PR DESCRIPTION
**Pull request by Hellenn07**

### CODE REVIEW

**Comment by Hellenn07** [comment]
#5238

**Comment by Hellenn07** [comment]
#5240

**Comment by Hellenn07** [comment]
Hey there! I created a new PR branch as @ogbanugot had earlier suggested. Can you review it for me. Any suggestions or recommendations are welcome.

**Comment by ogbanugot** [comment]
Hey @Hellenn07 , thanks for the effort so far but you haven't committed any files yet. Kindly confirm thanks!

**Comment by Hellenn07** [comment]
> Hey @Hellenn07 , thanks for the effort so far but you haven't committed any files yet. Kindly confirm thanks!

Hello, I did commit some files and all checks passed. Will this be approved for merge! Thanks.

**Comment by Hellenn07** [comment]
Close #5650

**Comment by Auxia** [comment]
Hi @Hellenn07, it seems you have committed changes to files within the `test_array_api` submodule which is not in our scope as this a separate git repository for the array api standard. I suggest going through the relevant docs again and referring to the youtube [videos](https://www.youtube.com/channel/UCGlkr-YCs3TjMVeOhbbULsw).

**Pull request closed without merging**
