### PR TITLE
Added log2 to torch frontend

### PR DESCRIPTION
**Pull request by ahmedelmogtaba**
#3183

### CODE REVIEW

**Comment by ahmedelmogtaba** [comment]
hi @abdrahmandiab , I added log2 to torch frontend, kindly review my request.

**Comment by ahmedelmogtaba** [comment]
@abdrahmandiab

**Comment by abdrahmandiab** [comment]
Hi @ahmedelmogtaba, 
sorry it took me a while to review your PR, I was just a tiny bit busy! 😅 

Everything seems good now, thanks for your effort! 🥰

**Comment by ahmedelmogtaba** [comment]
Hi @abdrahmandiab, no worries, thank you so much :+1:

**Pull request merged**
