### PR TITLE
feat: added tanh_

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
#15115

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by jaskiratsingh2000** [comment]
I have tried a lot but I have no way clue and implementation approach on why these test cases are failing.

**Comment by jaskiratsingh2000** [comment]
@RickSanchezStoic Can you please help review this PR?

**Comment by Ookamice** [comment]
@jaskiratsingh2000 
Refer to https://github.com/unifyai/ivy/issues/22481
Thank you

**Pull request closed without merging**
