### PR TITLE
Add Statistical functions mean numpy frontend #2546

### PR DESCRIPTION
**Pull request by Emperor-WS**
Greetings
i think i did everything
i did the frontend
the tests as well
and changed the init files
i did the mean function according to the numpy documentation
waiting for your reply.
Best regards.

### CODE REVIEW

**Comment by Emperor-WS** [comment]
@abdrahmandiab Greetings sir,
Is it normal that some checks failed? i mean is it a problem with my code or a problem with github?
waiting for your reply.
Best regards.

**Comment by Emperor-WS** [comment]
@abdrahmandiab hello,
so im having couple of issues 
regarding ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py in lint formating and i didnt even change anything in manipulation so i dont really know why im getting error there
and im having errors in docstrings as well which doesnt seem to have anything to do with my code
and as well as the run-nightly-tests got some Errors that has nothing with my code as well
can you help me with it because i have no idea how to solve those errors?

**Comment by kimbring2** [comment]
@Emperor-WS Hello, the code looks fine. However, It looks like you need to write code for only Numpy ToDo(https://github.com/unifyai/ivy/issues/2546) which you mentioned before.

**Comment by Emperor-WS** [comment]
> @Emperor-WS Hello, the code looks fine. However, It looks like you need to write code for only Numpy ToDo(#2546) which you mentioned before.

Hello Eng. @kimbring2, i did all 4 of them because someone told me to do so, so what should i do now remove everything and just add the numpy mean test front end and test? and then my code will be merged and done?

**Comment by kimbring2** [comment]
@Emperor-WS Yes, move to the next one when you finish one. Your code can be merged in that way.

**Comment by Emperor-WS** [comment]
> @Emperor-WS Yes, move to the next one when you finish one. I will test your code after you do that! Checking every framework is not easy.

Okay i will discard all commits and reupload only the numpy

**Comment by Emperor-WS** [comment]
Hello Eng. @kimbring2 , that should do it
there are couple of issues that has nothing to do with my code or folders though why does that usually happens? are those bugs in the frame work it self?

**Comment by kimbring2** [comment]
@Emperor-WS Yes, it seems like. Your current commit looks better than before. I can tell you the test result soon.

**Comment by Emperor-WS** [comment]
> @Emperor-WS Yes, it seems like. Your current commit looks better than before. I can tell you the test result soon.

@kimbring2 Hello, so whats the test result is all good?

**Comment by kimbring2** [comment]
@Emperor-WS No, it seems like I need more time. Please try to do another simple task if you need the accepted commit result.

**Comment by Emperor-WS** [comment]
> @Emperor-WS No, it seems like I need more time. Please try to do another simple task if you need the accepted commit result.

I solved a small issue which was i had the function name wrong so you can start the testing again maybe it will be easier this time
Waiting for your reply and thanks for your time.

**Comment by Emperor-WS** [comment]
@kimbring2 Hello,
So i checked the tests and it seems that everything is alright with them all the errors are coming for different functions that i didnt implement and the errors for my function seem to be the same for other functions as well which i assume is a problem with the framework it self (im not sure though) and i think my code is ready to be merged so if its ready to be merged can you merge it to me? 
Thanks in advance.

**Comment by kimbring2** [comment]
@Emperor-WS I encounter the same error(**hypothesis.errors.InvalidArgument: Missing required kwarg: 'fw'**) again using the latest Ivy repository.

How did you run the test? Try to run 'def test_numpy_cos()' of another folder. I can run it well. Please tell me the result after running that.

**Comment by Emperor-WS** [comment]
> @Emperor-WS I encounter the same error(**hypothesis.errors.InvalidArgument: Missing required kwarg: 'fw'**) again using the latest Ivy repository.
> 
> How did you run the test? Try to run '[test_numpy_cos()](https://github.com/unifyai/ivy/blob/9c42473dc819f6550a84ff0e1a4e7e9afbb6943a/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py#L23)' of another folder. I can run it well. Please tell me the result after running that.

i had the same error for few days but it was in other functions as well until the ivy framework got updated and found out it was caused by the * in the test_numpy_mean function so i removed the * and now its good to go, there is a specific error now that im trying to resolve i will try to solve it and when its done i think my code will be good to get merged.

**Comment by kimbring2** [comment]
@Emperor-WS Another error(E   hypothesis.errors.MultipleFailures: Hypothesis found 3 distinct failures.) occurs from your latest code.

**Comment by Emperor-WS** [comment]
> @Emperor-WS Another error(E hypothesis.errors.MultipleFailures: Hypothesis found 3 distinct failures.) occurs from your latest code. It means code has multiple errors.

but every single function i tried testing are giving the same error
the error i know that is happening and i dont know how to solve it

AssertionError: Found 1 arrays in the input arguments, but 2 dtypes and as_variable_flags. Make sure to pass in a sequence of bools for all associated boolean flag inputs to test_function, with the sequence length being equal to the number of arrays in the arguments.

i know its related to as_variable_flags but im not sure what to change

**Comment by Emperor-WS** [comment]
> > @Emperor-WS Another error(E hypothesis.errors.MultipleFailures: Hypothesis found 3 distinct failures.) occurs from your latest code. It means code has multiple errors.
> 
> but every single function i tried testing are giving the same error the error i know that is happening and i dont know how to solve it
> 
> AssertionError: Found 1 arrays in the input arguments, but 2 dtypes and as_variable_flags. Make sure to pass in a sequence of bools for all associated boolean flag inputs to test_function, with the sequence length being equal to the number of arrays in the arguments.
> 
> i know its related to as_variable_flags but im not sure what to change

@kimbring2 i fixed that and it should be working now, tell me if there is any error left that is related to my code

**Comment by kimbring2** [comment]
@Emperor-WS Hello,

After commenting out the 'value_test' part of [helpers.py#L1703](https://github.com/unifyai/ivy/blob/3f57f3e9aaf82db2f0cf04cf0fd8214e53e66239/ivy_tests/test_ivy/helpers.py#L1703)' line, your current code gives error saying "E   TypeError: _mean_dispatcher() got an unexpected keyword argument 'x'"

That error is triggered at 
[helpers.py#L1899](https://github.com/unifyai/ivy/blob/3f57f3e9aaf82db2f0cf04cf0fd8214e53e66239/ivy_tests/test_ivy/helpers.py#L1899).

**Comment by Emperor-WS** [comment]
> @Emperor-WS Hello,
> 
> After commenting out the 'value_test' part of [helpers.py#L1703](https://github.com/unifyai/ivy/blob/3f57f3e9aaf82db2f0cf04cf0fd8214e53e66239/ivy_tests/test_ivy/helpers.py#L1703)' file, your current code gives error saying "E TypeError: _mean_dispatcher() got an unexpected keyword argument 'x'"
> 
> That error is triggered at [helpers.py#L1899](https://github.com/unifyai/ivy/blob/3f57f3e9aaf82db2f0cf04cf0fd8214e53e66239/ivy_tests/test_ivy/helpers.py#L1899).

I saw that error few hours ago but Im not really sure why is it throwing that error but i think i know the solution i will give it a try and tell you

**Comment by kimbring2** [comment]
@Emperor-WS I just watch below error from your code. It seems like you need to see the [mean function document of Numpy](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) to arrange the parameter for the test function. 

FAILED [ 50%]
ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py:11 (test_numpy_mean[cpu-ivy.functional.backends.numpy-True-False-np_call-numpy])
fw = 'numpy'

    @given(
>       dtype_and_x=helpers.dtype_and_values(
            available_dtypes=ivy_np.valid_float_dtypes
        ),
        dtype=st.sampled_from(ivy_np.valid_float_dtypes + (None,)),
        where=np_frontend_helpers.where(),
        as_variable=helpers.array_bools(num_arrays=1),
        with_out=st.booleans(),
        num_positional_args=helpers.num_positional_args(
            fn_name="ivy.functional.frontends.numpy.mean"
        ),
        native_array=helpers.array_bools(num_arrays=1),
    )

ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py:42: in test_numpy_mean
    np_frontend_helpers.test_frontend_function(
ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py:40: in test_frontend_function
    _test_frontend_function_ignoring_unitialized(*args, **kwargs)
ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py:19: in _test_frontend_function_ignoring_unitialized
    values = helpers.test_frontend_function(*args, **kwargs)
ivy_tests/test_ivy/helpers.py:1845: in test_frontend_function
    ret = frontend_fn(*args, **kwargs)
ivy/functional/frontends/numpy/statistics/averages_and_variances.py:16: in mean
    ret = ivy.mean(x, out=out)
ivy/func_wrapper.py:421: in new_fn
    return fn(*args, **kwargs)
ivy/func_wrapper.py:372: in new_fn
    ret = fn(*args, out=native_out, **kwargs)
ivy/func_wrapper.py:98: in new_fn
    return fn(*new_args, **new_kwargs)
ivy/func_wrapper.py:160: in new_fn
    ret = fn(*args, **kwargs)
ivy/functional/backends/numpy/statistical.py:35: in mean
    return np.asarray(np.mean(x, axis=axis, keepdims=keepdims, out=out))
<__array_function__ internals>:180: in mean
    ???
/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3474: in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([-0.], dtype=float16), axis = None, dtype = dtype('float32')
out = array([0.], dtype=float16), keepdims = False

    def _mean(a, axis=None, dtype=None, out=None, keepdims=False, *, where=True):
        arr = asanyarray(a)
    
        is_float16_result = False
    
        rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
        if rcount == 0 if where is True else umr_any(rcount == 0, axis=None):
            warnings.warn("Mean of empty slice.", RuntimeWarning, stacklevel=2)
    
        # Cast bool, unsigned int, and int to float64 by default
        if dtype is None:
            if issubclass(arr.dtype.type, (nt.integer, nt.bool_)):
                dtype = mu.dtype('f8')
            elif issubclass(arr.dtype.type, nt.float16):
                dtype = mu.dtype('f4')
                is_float16_result = True
    
>       ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
E       ValueError: output parameter for reduction operation add has the wrong number of dimensions: Found 1 but expected 0

/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:179: ValueError

**Comment by Emperor-WS** [comment]
> @Emperor-WS I just watch the below error from your code. It seems like you need to see the [mean function document of Numpy](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) to arrange the parameter for the test function.
> 
> > FAILED [ 50%]
> > ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py:11 (test_numpy_mean[cpu-ivy.functional.backends.numpy-True-False-np_call-numpy])
> > fw = 'numpy'
> > ```
> > @given(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > ```
> > >   dtype_and_x=helpers.dtype_and_values(
> > > ```
> > 
> > 
> > ```
> >         available_dtypes=ivy_np.valid_float_dtypes
> >     ),
> >     dtype=st.sampled_from(ivy_np.valid_float_dtypes + (None,)),
> >     where=np_frontend_helpers.where(),
> >     as_variable=helpers.array_bools(num_arrays=1),
> >     with_out=st.booleans(),
> >     num_positional_args=helpers.num_positional_args(
> >         fn_name="ivy.functional.frontends.numpy.mean"
> >     ),
> >     native_array=helpers.array_bools(num_arrays=1),
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py:13:
> > 
> > ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py:42: in test_numpy_mean
> > np_frontend_helpers.test_frontend_function(
> > ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py:40: in test_frontend_function
> > _test_frontend_function_ignoring_unitialized(*args, **kwargs)
> > ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py:19: in _test_frontend_function_ignoring_unitialized
> > values = helpers.test_frontend_function(*args, **kwargs)
> > ivy_tests/test_ivy/helpers.py:1845: in test_frontend_function
> > ret = frontend_fn(*args, **kwargs)
> > ivy/functional/frontends/numpy/statistics/averages_and_variances.py:16: in mean
> > ret = ivy.mean(x, out=out)
> > ivy/func_wrapper.py:421: in new_fn
> > return fn(*args, **kwargs)
> > ivy/func_wrapper.py:372: in new_fn
> > ret = fn(*args, out=native_out, **kwargs)
> > ivy/func_wrapper.py:98: in new_fn
> > return fn(*new_args, **new_kwargs)
> > ivy/func_wrapper.py:160: in new_fn
> > ret = fn(*args, **kwargs)
> > ivy/functional/backends/numpy/statistical.py:35: in mean
> > return np.asarray(np.mean(x, axis=axis, keepdims=keepdims, out=out))
> > <**array_function** internals>:180: in mean
> > ???
> > /usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3474: in mean
> > return _methods._mean(a, axis=axis, dtype=dtype,
> > 
> > a = array([-0.], dtype=float16), axis = None, dtype = dtype('float32')
> > out = array([0.], dtype=float16), keepdims = False
> > ```
> > def _mean(a, axis=None, dtype=None, out=None, keepdims=False, *, where=True):
> >     arr = asanyarray(a)
> > 
> >     is_float16_result = False
> > 
> >     rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
> >     if rcount == 0 if where is True else umr_any(rcount == 0, axis=None):
> >         warnings.warn("Mean of empty slice.", RuntimeWarning, stacklevel=2)
> > 
> >     # Cast bool, unsigned int, and int to float64 by default
> >     if dtype is None:
> >         if issubclass(arr.dtype.type, (nt.integer, nt.bool_)):
> >             dtype = mu.dtype('f8')
> >         elif issubclass(arr.dtype.type, nt.float16):
> >             dtype = mu.dtype('f4')
> >             is_float16_result = True
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > ```
> > >   ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
> > > ```
> > 
> > 
> > E       ValueError: output parameter for reduction operation add has the wrong number of dimensions: Found 1 but expected 0
> > /usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:179: ValueError

@kimbring2 do i need to arrange the paramteres for test_numpy_mean?
i mean this part in the code
        x=np.asarray(x, dtype=input_dtype[0]),
        axis=None,
        dtype=dtype,
        out=None,
        keepdims=False,
        where=where,
is arranged according to the numpy.mean documentation
if i arrange the test function it should be something like this i guess?

def test_numpy_mean(
    dtype_and_x,
    dtype,
    with_out,
    where,
    as_variable,
    num_positional_args,
    native_array,
    fw,
):

or am i wrong?

**Comment by kimbring2** [comment]
@Emperor-WS Not that parameters, I mean parameter of '**mean**' function under '**averages_and_variances**.py' and '**np_frontend_helpers.test_frontend_function'** function.

**Comment by Emperor-WS** [comment]
> @Emperor-WS Not that parameters, I mean parameter of '**mean**' function under '**averages_and_variances**.py' and '**np_frontend_helpers.test_frontend_function'** function.

@kimbring2  i compared it and it was the same parameters as the mean documentation the only difference is that i wrote x rather than a so thats the only thing that seemed i can change for me kindly tell me if im wrong

**Comment by kimbring2** [comment]
@Emperor-WS Hello, you do not need to import the np_frontend_helpers module directly in this file.

I assume this problem is too difficult with your current understanding of Ivy. 

Do you have another accepted commit? There are more [easy task](https://github.com/unifyai/ivy/commit/86b46280557f6a6f4709238415e46dffd825f5ed)s with just a few modifications.

I will just commit my own code for the Numpy mean frontend and close this request soon.

Sorry. We can not spend too much time on only one commit.

**Comment by Emperor-WS** [comment]
> @Emperor-WS Hello, you do not need to import the np_frontend_helpers module directly in this file.
> 
> I assume this problem is too difficult with your current understanding of Ivy.
> 
> Do you have another accepted commit? There are more [easy task](https://github.com/unifyai/ivy/commit/86b46280557f6a6f4709238415e46dffd825f5ed)s with just a few modifications.
> 
> I will just commit my own code for the Numpy mean rontend and close this request soon.
> 
> We can not spend too much time on only one commit. Sorry ):

Hello, yes i do have another accepted commit and the second one should get accepted soon if you want to close this PR its okay.

**Comment by kimbring2** [comment]
@Emperor-WS Sounds relief. Close now!

**Pull request closed without merging**
