### PR TITLE
Implemented sinc in the backend

### PR DESCRIPTION
**Pull request by pj-mathematician**
Can you review and please list the additions/deletions I should incorporate?
And I will also need help with the doc string for ivy/elementwise.py

Thanks

### CODE REVIEW

**Comment by Unevilicorn** [comment]
Hi, 

Could you also link the issue this relates to. This is so that it's easier for us to track what's being done.
The test is failing for sinc, you can see by going through the `checks` near the bottom of this page, click on detail on the row for `test-core-ivy / run-nightly-tests ({backend}, elementwise)` then click on `Run Functional-Core Test`

Thanks

**Comment by pj-mathematician** [comment]
@Unevilicorn thank you for the review, I will fix the tests by EOD. 

sinc is a part of the functional API and is referenced in the Frontend TODO lists #12 , #1525 and #3612 
But when I started the Frontend sinc I noticed that it isn't present in the backend at all. Hence I wrote the backend implementations. I believe it should be added to the list here #3856 . I have opened a separate issue to track this here #4447

**Comment by Unevilicorn** [comment]
I would actually recommend doing this compositionally then, since this function isn't too complex to compose, you can see it's behaviour from [pytorch docs](https://pytorch.org/docs/stable/special.html#torch.special.sinc).

I'll take another look, and check if this should be added to the list :+1:

**Comment by pj-mathematician** [comment]
I understand. So instead of adding any backend functions, I should implement sinc compositionally to only the frontend files of Numpy and Torch, as mentioned in the frontend todo tasks, right?

**Comment by Unevilicorn** [comment]
Yeah, that's the simplest way to go about it, just implementing them compositionally in the frontend for your framework. However it does feel like it could be added as an extension, I'll let you know when I find out if this should be added or not.

**Comment by pj-mathematician** [comment]
Alright then! Closing this PR for now, and will work on the frontend as you suggested. Let me know if there is a need for it in the backend, I'd love to get back on it 🙌🏻

**Comment by pj-mathematician** [comment]
@Unevilicorn , I have opened #4462 to work on this. Thank you for the clarification

**Pull request closed without merging**
