### PR TITLE
Added examples for arange

### PR DESCRIPTION
**Pull request by iamravi1**
- [ ] #7629

### CODE REVIEW

**Comment by iamravi1** [comment]
Please check this PR as I have added examples for arange function

**Comment by RashulChutani** [comment]
Hi @iamravi1 Can you please mention the issue number? Thanks.

**Comment by iamravi1** [comment]
- [ ] #7629

**Comment by iamravi1** [comment]
#7629 is the issue number

**Comment by RashulChutani** [comment]
Sure. I will check in detail soon. Thanks.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @iamravi1, In the issue #7629, Can you add a reference to the Task you have picked the arange function from? Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by iamravi1** [comment]
Please do check this PR

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @iamravi1 Can you add your issue # under the issue #790, so that it gets marked completed when I merge your PR.

**Comment by iamravi1** [comment]
Added issue under #729

**Comment by iamravi1** [comment]
I have added this under #729 please check and try to merge

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
