### PR TITLE
fft #5794

### PR DESCRIPTION
**Pull request by steelhitman**

### CODE REVIEW

**Comment by JamieLine** [comment]
Hi! Thanks for the PR!

Just a few quick points for now:
1. Which function is this a frontend implementation for? From the Numpy Docs I could find `numpy.fft.fft` but not `FFT`, and `numpy.fft.fft` has a different set of arguments. Our frontend implementations should match the exact name and argument list of the function they are replicating.
2. The frontend function will need to have a test written for it, `ivy_tests/test_ivy/test_frontends` has all of the frontend tests, it should be clear roughly what the test should look like based on those examples, and then if anything needs tweaking I can have a look through it afterwards.

Any questions or comments please let me know!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
