### PR TITLE
add paddle sort

### LINKED ISSUE #18310: Sort

### PR DESCRIPTION
**Pull request by ogbanugot**
Close #18310

### CODE REVIEW

**Comment by ogbanugot** [comment]
Hey, @kurshakuz can I get a review, please?

**Review by kurshakuz — APPROVED** [review]
LGTM! Thanks @ogbanugot

**Comment by ogbanugot** [comment]
Hi @kurshakuz I've resolved the conflict now, thanks!

**Comment by kurshakuz** [comment]
LGTM!

**Pull request merged**
