### PR TITLE
pull request for bincount frontend wrapper and testing

### PR DESCRIPTION
**Pull request by harshxtanwar**
bincount #13643

Hii, 
I am a new contributor to Ivy.
I am getting a small error while testing, which I am not able to understand how to resolve.

### CODE REVIEW

**Comment by valeriocost** [comment]
Hi @harshxtanwar 😄 please comment "close #13643" to let the issue be linked with the PR, thanks!

**Comment by valeriocost** [comment]
and about the error itself, I think the function is implemented for all integers types while you set `int64` as not supported 😄 either flag all integer types as supported or all other types as unsupported

**Comment by harshxtanwar** [comment]
close #13643

**Comment by harshxtanwar** [comment]
Hi @valeriocost, 
I guess all the test cases passed for torch.

**Comment by valeriocost** [comment]
@harshxtanwar I think the decorator still defines the unsupported types rather than the supported 😅

**Comment by harshxtanwar** [comment]
Hi @valeriocost I am sorry, I thought I had an option to either specify all unsuppported dtypes, or just the supported ones. 
I have mentioned the supported dtype instead, and the test cases are also passing for torch.

**Comment by valeriocost** [comment]
the tests are still failing as you can see on the reports here I'm afraid

**Comment by harshxtanwar** [comment]
I am actually a new contributor to Ivy, it'll be great if you could help me out in understanding. Does the error message below occure because there are missing frontend wrappers and test functions for tensorflow and paddle ? because there we can mention their supported dtypes as well.

the error message says 
```
=================================================== short test summary info ===================================================
FAILED ivy_tests/test_ivy/test_frontends/test_torch/test_utilities.py::test_torch_utilities_bincount[cpu-ivy.functional.backends.tensorflow-False-False] - ivy.utils.exceptions.IvyError: tensorflow: bincount: arr: Tensor conversion requested dtype int32 for Tensor with dtype in...
FAILED ivy_tests/test_ivy/test_frontends/test_torch/test_utilities.py::test_torch_utilities_bincount[cpu-ivy.functional.backends.paddle-False-False] - ivy.utils.exceptions.IvyBackendException: paddle: bincount: paddle: bincount: paddle: bincount: paddle: bincount: paddle: ...
================================================ 2 failed, 3 passed in 52.72s =================================================
```

**Comment by harshxtanwar** [comment]
Hi @valeriocost, kindly let me know whenever you get free :))

**Comment by valeriocost** [comment]
Hi @harshxtanwar sorry for the late reply! 😅 can you try to rebase your branch with master? In order to check if the tests are passing here on the CI pipeline. Thanks!

**Comment by harshxtanwar** [comment]
Hi @valeriocost, are you asking me to sync my branch for bincount with the master branch of Ivy as shown in the picture below ?
image

Because I have one more PR going on in a separate branch, so I don't know if I should rebase or not. Although, I checked the test and all of the test cases are passing except for the paddle and tensor-flow error, which I strongly feel exist because there are no frontend wrappers for these specific backends.

image
image

**Comment by valeriocost** [comment]
yes, you should update your fork and then integrate new changes into you branch (something like in this guide https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html).
Yes, I think the error is raised because there aren't the backend implementations 😅

**Comment by harshxtanwar** [comment]
Hi @valeriocost, are you asking me to sync my branch for bincount with the master branch of Ivy as shown in the picture below ?
image

Because I have one more PR going on in a separate branch, so I don't know if I should rebase or not. Although, I checked the test and all of the test cases are passing except for the paddle and tensor-flow error, which I strongly feel exist because there are no frontend wrappers for these specific backends.

As you can see below, my branch is not that many commits behind, it is pretty much up to date:
image

I am using the following command for testing and the local tests are passing as well:
```
pytest ivy_tests/test_ivy/test_frontends/test_torch/test_utilities.py::test_torch_utilities_bincount
```

**Comment by harshxtanwar** [comment]
wow @valeriocost ,
I synced and pulled the changes in the branch and now the tests are passing here !!

**Pull request merged**
