### PR TITLE
Paddle max_pool2d

### LINKED ISSUE #19063: max_pool2d
[]- #15055

### PR DESCRIPTION
**Pull request by Sar-thak-3**
Close #19063

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @Sar-thak-3 
Thanks for the PR🙂
I haven't gone much through your code but there first changes needed😂
You can remove these new added files and add the changes to respective submodules

**Comment by Sar-thak-3** [comment]
Hi @hirwa-nshuti , thank you for replying, should I remove the changes I made in backend submodules?

**Comment by Sar-thak-3** [comment]
@hirwa-nshuti I am new to Ivy, and it would be really helpful if you can guide me through this process.

**Comment by Sar-thak-3** [comment]
Hi @hirwa-nshuti , all the test cases are working fine locally, kindly review the pr and let me know the changes required.

Thanks for your cooperation!

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @Sar-thak-3 

Would you resolve the merge conflicts here for me to be able to run the tests locally

**Pull request closed without merging**
