### PR TITLE
added tensorflow frontend linalg.eigvals

### LINKED ISSUE #12405: eigvals

### PR DESCRIPTION
**Pull request by mustafa1adel**
close #12405

### CODE REVIEW

**Comment by mustafa1adel** [comment]
I tried to run pytest. But It keeps failing all tests, not just `tensorflow.linalg.eigvals`. please check it and let me know if there's an error or sth to be edited.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey @mustafa1adel! Did you try running:
```
pytest ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py::test_tensorflow_eigvals
```

The other tests seems to be fine, for example: test_tensorflow_eigvalsh. There seems to be an error with your implementation. Can you take a look?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
