### PR TITLE
Added rsqrt() for Paddle as well as test file

### LINKED ISSUE #17771: rsqrt
Reciprocal of the square root of a number

### PR DESCRIPTION
**Pull request by samdemarinis**
Close #17771

### CODE REVIEW

**Comment by danielmunioz** [comment]
Hey @samdemarinis!

Thanks for contributing to ivy!

It seems however that your PR is not following the [Frontends ToDo guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis), could you please adapt your PR to them?

Thanks! :)

**Comment by samdemarinis** [comment]
Hi @danielmunioz thanks for reviewing! I am trying to follow the Frontends ToDo guide the best that I can. Is the issue that I did not implement the function in the correct file? I'm thinking I could place it in ivy/functional/frontends/paddle/linalg.py

**Comment by danielmunioz** [comment]
Yes, that's the main problem, but there is also an issue with the docstrings, frontend functions usually don't make use of any
Again all of that is included in the guides 

About the specifics of the location, this is really not a linalg operation so probably some place where math operators are stored would be a better pick

Thanks!, And feel free to ask away! :)

**Comment by samdemarinis** [comment]
Hey @danielmunioz I placed the function rsqrt() in ivy/functional/frontends/paddle/tensor/math.py and the test function in ivy/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py. However, it's saying that this branch has conflicts that must be resolved and I am a bit confused. Am I not able to edit these files?

**Comment by danielmunioz** [comment]
Hey @samdemarinis, yes you are allowed to edit this files, what's probably happening is that your branch is not up to date with the main repo, updating your branch and then adding the code to those files should fix the merge conflicts! You can also check the [GitHub guidelines](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) on fixing merge conflicts :)

Feel free to ask any questions!

**Comment by samdemarinis** [comment]
Hi @danielmunioz I tried to synch the forked repository, and it made me discard the changes I made. So now the pull request is closed and I don't know how to reopen it :( Can you please help me with this when you get a chance?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by samdemarinis** [comment]
Hey @danielmunioz I re-synched my copy of the repository and made edits to the files I described above. However, I am getting an error on multiple tests that says "Error: Process completed with exit code 1." I'm not sure what's wrong because it won't give me any more information; I assume it's an error in the code but I don't quite know what it is. I'm sorry for the confusion!

**Comment by danielmunioz** [comment]
Hey @samdemarinis, you may be seeing the errors on github, you can try running the test locally with the command: `pytests <test_path>::<test>` for example for your case it'd be something like: `pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py::test_paddle_rsqrt`

There it is should show you the errors of your function only!

**Comment by samdemarinis** [comment]
Hi @danielmunioz I am a bit confused where to run the provided command; is there a place on Github where I can do so?

**Comment by samdemarinis** [comment]
@danielmunioz I have downloaded the repository and am trying to run the provided command in my terminal, but I keep getting errors for modules that are being imported in other files, like conftest.py. There are many different imports; do I need to install all of these (like redis, numpy, termcolor, etc.) before I can run the command?

**Comment by danielmunioz** [comment]
Yeah, you need to install the packages listed in `requirements.txt`, you can also try running the docker enviroment which comes with everything necessary for development, you can check the [setting up guide](https://unify.ai/docs/ivy/overview/contributing/setting_up.html) for more details, but by far the easiest way is to create a Codespace instance and work there, you can create one directly in your branch and go on from there! Again you can check the Codespaces section on the setting up guide for mode details!

Feel free to ask away!
Thanks!

**Comment by samdemarinis** [comment]
Hi @danielmunioz thank you for that info! I have created a Codespace instance and I am running the tests through there. I have 3/5 of them passing right now but I am struggling to pass the final two. They are both failing due to a KeyError that states: `KeyError: 'cpu'`. The location of the error seems to be in /workspaces/ivy/ivy/functional/backends/tensorflow/__init__.py in the function _get_fn_dtypes(framework, kind="valid"). Do you have an idea of what might be causing these two failed tests?

**Comment by samdemarinis** [comment]
`===================================================================================================== FAILURES ======================================================================================================
_________________________________________________________________________ test_paddle_rsqrt[cpu-ivy.functional.backends.numpy-False-False] __________________________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.rsqrt",
        dtype_and_x=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
        ),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py:1356: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:493: in dtype_and_values
    available_dtypes = draw(available_dtypes)
/opt/miniconda/envs/multienv/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw
    return strategy.do_draw(self)
/opt/miniconda/envs/multienv/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1539: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:173: in get_dtypes
    valid_dtypes = set(retrieval_fn(test_globals.CURRENT_BACKEND(), kind))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

framework = <module 'ivy.functional.backends.numpy' from '/workspaces/ivy/ivy/functional/backends/numpy/__init__.py'>, kind = 'valid'

    def _get_fn_dtypes(framework, kind="valid"):
>       return test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[framework.backend][
            test_globals.CURRENT_DEVICE_STRIPPED
        ][kind]
E       KeyError: 'cpu'
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.81.1', b'AA==') as a decorator on your test case

ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:35: KeyError
_______________________________________________________________________ test_paddle_rsqrt[cpu-ivy.functional.backends.tensorflow-False-False] _______________________________________________________________________

    @handle_frontend_test(
>       fn_tree="paddle.rsqrt",
        dtype_and_x=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
        ),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py:1356: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py:493: in dtype_and_values
    available_dtypes = draw(available_dtypes)
/opt/miniconda/envs/multienv/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py:951: in draw
    return strategy.do_draw(self)
/opt/miniconda/envs/multienv/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1539: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:173: in get_dtypes
    valid_dtypes = set(retrieval_fn(test_globals.CURRENT_BACKEND(), kind))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

framework = <module 'ivy.functional.backends.tensorflow' from '/workspaces/ivy/ivy/functional/backends/tensorflow/__init__.py'>, kind = 'valid'

    def _get_fn_dtypes(framework, kind="valid"):
>       return test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[framework.backend][
            test_globals.CURRENT_DEVICE_STRIPPED
        ][kind]
E       KeyError: 'cpu'
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.81.1', b'AA==') as a decorator on your test case

ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py:35: KeyError
============================================================================================== short test summary info ==============================================================================================
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py::test_paddle_rsqrt[cpu-ivy.functional.backends.numpy-False-False] - KeyError: 'cpu'
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py::test_paddle_rsqrt[cpu-ivy.functional.backends.tensorflow-False-False] - KeyError: 'cpu'
=========================================================================================== 2 failed, 3 passed in 10.75s ============================================================================================`

**Comment by danielmunioz** [comment]
Hey @samdemarinis, not sure honestly, maybe something in the backends, I'll take a look, in the meantime could you please sync your branch with master and fix the merge errors?

**Comment by samdemarinis** [comment]
Absolutely @danielmunioz thank you so much.

**Comment by samdemarinis** [comment]
@danielmunioz All checks have passed! Hooray!!!

**Comment by danielmunioz** [comment]
Hey @samdemarinis! Yeah, all tests look to be passing locally as well! 🚀 

LGTM! Merging now!
Thanks for contributing! :)

**Comment by samdemarinis** [comment]
@danielmunioz Thank you so much for all of your help. I am so appreciative!

**Pull request merged**
