### PR TITLE
smooth_l1_loss

### LINKED ISSUE #21165: smooth_l1_loss
- [smooth_1_loss] #22378

### PR DESCRIPTION
**Pull request by sushmanthreddy**
close #21165

### CODE REVIEW

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Hello, I suppose you need to implement the backend of your function for every framework available to allow your function to pass tests, not just paddle and torch.

**Comment by Daniel4078** [comment]
by the way, you should have a look at the new guide line of how we should write commit messages: https://www.conventionalcommits.org/en/v1.0.0/. Thanks.

**Comment by sushmanthreddy** [comment]
@Daniel4078 The problem here is smooth_l1_loss is and mixed function due to that only some backends have the implementation of smooth_l1_loss,oneis torch and paddle ,so that is the reason have implemented in this way.
[link](https://unify.ai/docs/ivy/overview/deep_dive/function_types.html#mixed-functions)

**Review by Daniel4078 — COMMENTED** [review]
I would say that you should still try to implement this function compositionally in other backend by recreating its intended behavior using combinations of other functions in the target backend framework.

**Comment by sushmanthreddy** [comment]
i will work on it

**Comment by sushmanthreddy** [comment]
@Daniel4078 I have implemented the backend support manually in respective frameworks of jax,numpy and tensorflow...can u pls review that,it might have some mistakes over them,pls review it once and let me knew any changes are needed?

**Review by Daniel4078 — COMMENTED** [review]
Please update your branch with the main one as I found that your tests are failing due to an old problem: E   ModuleNotFoundError: No module named 'dill'. Which has been patched out in recent commits on the ivy main branch.

**Comment by sushmanthreddy** [comment]
@Daniel4078 i have updated it and pushed the code..Now tests are passing as u mentiioned
Screenshot from 2023-08-23 14-41-18

screenshot of it is

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
I think that it will be good for you slightly expand your docstring examples for your function like guided here(https://unify.ai/docs/ivy/overview/deep_dive/docstring_examples.html#docstring-examples). For example, some example requarding the use of reduction and out argument will be appreciated.

**Comment by sushmanthreddy** [comment]
@Daniel4078 i have changed the doc strings any new changes are needed??

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Found a failing test of your function, please have a look: 
```
E   ivy.utils.exceptions.IvyBackendException: paddle: execute_with_gradients: paddle: nested_map: paddle: nested_map: (Fatal) There is no grad op for inputs:[0] or it'sstop_gradient=True.
E     [Hint: target_node should not be null.] (at /paddle/paddle/fluid/eager/general_grad.h:72)
E   
E   Falsifying example: test_smooth_l1_loss(
E       backend_fw='paddle',
E       on_device='cpu',
E       dtype_and_input=(['float64'], [array([-1., -1., -1.])]),
E       dtype_and_target=(['float64'], [array([-1., -1., -1.])]),
E       beta=0.5,
E       reduction='none',
E       test_flags=FunctionTestFlags(
E           ground_truth_backend='tensorflow',
E           num_positional_args=2,
E           with_out=False,
E           instance_method=False,
E           test_gradients=True,
E           test_compile=False,
E           as_variable=[False],
E           native_arrays=[False],
E           container=[False],
E       ),
E       fn_name='smooth_l1_loss',
E   )
```

**Comment by sushmanthreddy** [comment]
@Daniel4078 it has been failing for all of the loss function that is paddle bfloat16 issue or some backend issue.
If u check the for other loss functions ,which are implemented u can see that they will also fail for paddle only

**Comment by sushmanthreddy** [comment]
@Daniel4078 here is the screenshot of it.
Screenshot from 2023-08-24 09-31-30

**Comment by Daniel4078** [comment]
Maybe you can leave a comment in the relevent code saying this problem, then I can merge and let other ivy members to deal with this global problem.

**Comment by sushmanthreddy** [comment]
@Daniel4078 i have added in the doc string mentioning the error..can u pls review it ?

**Review by Daniel4078 — APPROVED** [review]
Looks good for me!

**Pull request merged**
