### PR TITLE
divide adhering to Array API standard

### PR DESCRIPTION
**Pull request by PatChizzy**
Deleted Jax folder created in #394 

Some tests are still failing
@djl11 @1Doomdie1 please review

### CODE REVIEW

**Review by PatChizzy — COMMENTED** [review]
Conflicts Resolved

**Review by 1Doomdie1 — CHANGES_REQUESTED** [review]
Hey! Thank you for contributing to Ivy!
Looks like you have to pass in the same data type into divide, see:
image

Please remove everything from .idea

Thank you!

**Comment by PatChizzy** [comment]
@1Doomdie1 not sure i follow, kindly help clarify.

when you say remove everything form `.idea`, do you mean all files and folders in that directory?
if yes, would removing everything solve the datatype issue?

**Review by djl11 — CHANGES_REQUESTED** [review]
Could you please fix the import errors as a result of the conflict fixes and also remove all .idea files @HotzingTone?

**Review by djl11 — CHANGES_REQUESTED** [review]
Hey @HotzingTone, sorry I meant could you remove all .idea file **changes**, not the files themselves? :)

**Comment by HotzingTone** [comment]
> Hey @HotzingTone, sorry I meant could you remove all .idea file **changes**, not the files themselves? :)

Ok, now all historic changes to the .idea folder have been reverted.

**Comment by mattbarrett98** [comment]
Thanks for contributing!

**Pull request merged**
