### PR TITLE
reformat: reformatted `exists` in general submodule

### PR DESCRIPTION
**Pull request by Abdelrahman0W**
- Modified docstrings in  function in general submodule
- Add more docstring examples

### CODE REVIEW

**Comment by Abdelrahman0W** [comment]
add_reformatting_checklist_general

**Comment by Abdelrahman0W** [comment]
Close #5287

**Comment by Abdelrahman0W** [comment]
Hi @RashulChutani,
I am sorry for bothering you but is there anything I should do with 'Reformatting Task Checklist' comment. Also, there are some errors that are not related to this reformatting task, I think.

**Comment by Abdelrahman0W** [comment]
Hi @RashulChutani,
I am sorry for bothering you but is there any other thing I should do with 'Reformatting Task Checklist' comment or the PR in general. Also, there are some errors that are not related to this reformatting task, I think. Is this okay?
Kindly review it if everything is okay.

**Comment by Abdelrahman0W** [comment]
Hi @RashulChutani,

I am sorry for bothering you but I have some questions.
- Is there any other thing I should do with 'Reformatting Task Checklist' comment or the PR in general?
- There are some errors that are not related to this reformatting task, I think. Is this okay?
- Should I add the `@handle_nestable` decorator?

Thanks in advance.

Kindly review it if everything is okay.

**Comment by Abdelrahman0W** [comment]
@abdrahmandiab 
Hello Abdelrahman, I am so sorry for bothering you. I know this is not assigned to you but can you please review it for me? It is a part of an application process and it's been opened for 4 days now.
Thanks in advance.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @Abdelrahman0W Thanks for your contribution! I see some error with the "exists" function in the run-docstring-tests Check. Can you please resolve that? Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
