### PR TITLE
added jax.numpy.logical_not frontend and test

### PR DESCRIPTION
**Pull request by MustafaDahshory**

### CODE REVIEW

**Comment by MustafaDahshory** [comment]
issue #10081

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Hi @MustafaDahshory 

Can you kindly resolve the merge conflicts? Also, I have noticed that the CI tests are failing for `test_jax_numpy_logical_not` (https://github.com/unifyai/ivy/actions/runs/4019612938/jobs/6906661940). Could you kindly fix all failing tests? Thanks!

**Comment by MustafaDahshory** [comment]
I fixed the failing tests related to the functions I implemented. the merge conflicts appear as the repo gets updated in the time my pull request is reviewed. I hope this is acceptable.

**Review by YushaArif99 — APPROVED** [review]
Hi @MustafaDahshory 

Thanks, a lot for making the changes requested. All CI tests are passing now. I will now be merging this PR. Thanks again for your contribution! 😃

**Pull request merged**
