### PR TITLE
Update for NN tensorflow method ctc_unique_labels #17626

### PR DESCRIPTION
**Pull request by alrizkipascar**
Close https://github.com/unifyai/ivy/issues/17626

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by theRealBird** [comment]
Hi @alrizkipascar,
Thank you so much for your contribution to Ivy. The PR looks good to me just one request, could you please resolve the merge conflicts? Thanks!

**Comment by alrizkipascar** [comment]
Hey @theRealBird I already fixed the conflict but it seems I still have some fail at run test, is it ok or any clue to fix that?

**Comment by theRealBird** [comment]
It is unlikely that they are being caused by your changes @alrizkipascar! Thanks for making the fix.

**Comment by alrizkipascar** [comment]
@theRealBird Thank you for reviewing my PR!

**Pull request merged**
