### PR TITLE
#12744

### PR DESCRIPTION
**Pull request by adhamebr**
added out and dtype to nonzero() in searching

### CODE REVIEW

**Comment by VedPatwardhan** [comment]
Hey @adhamebr, this was the last one of a series of `push --force` we did on master to remove unwanted files from the commit history, please follow the steps suggested in Dan's public announcement on discord a few weeks ago to get your branch up to date with the latest commit history. I'll also remove the automated review request from myself and @CatB1t, @fspyridakos is the reviewer assigned to your PR. Thanks 🙂

**Comment by adhamebr** [comment]
> Hey @adhamebr, this was the last one of a series of `push --force` we did on master to remove unwanted files from the commit history, please follow the steps suggested in Dan's public announcement on discord a few weeks ago to get your branch up to date with the latest commit history. I'll also remove the automated review request from myself and @CatB1t, @fspyridakos is the reviewer assigned to your PR. Thanks 🙂

I did

**Comment by krishna1111111** [comment]
ok

**Review by krishna1111111 — COMMENTED** [review]
good

**Comment by adhamebr** [comment]
What should I do now?

**Pull request closed without merging**
