### PR TITLE
unique_consecutive

### LINKED ISSUE #22828: unique_consecutive
<-- #3612

### PR DESCRIPTION
**Pull request by NiteshK84**
# PR Description 
Adds unique_consecutive func to torch frontend

## Related Issue 

Close #22828

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by NiteshK84** [comment]
Hey reviewer,
i fixed all the errors but couldn't fix this one, could you please help here?
image

**Comment by KevinUnadkat** [comment]
hy @NiteshK84 , everything seems good , but have you tested the function locally .

**Comment by NiteshK84** [comment]
Hi @KevinUnadkat i did test locally and all the test cases passed for all backend.
thanks

**Comment by NiteshK84** [comment]
okay, actually i just checked the CI test failure, and i updated the test, sorry for the Inconvenience.

**Comment by KevinUnadkat** [comment]
hy @NiteshK84 
Everything seems to be ok now,
Thanks for Contributing.

**Pull request merged**
