### PR TITLE
numpy dirichlet

### LINKED ISSUE #4369: dirichlet

### PR DESCRIPTION
**Pull request by nassimberrada**
Close #4369

### CODE REVIEW

**Review by Ishticode — COMMENTED** [review]
Looking good mostly. May I ask as to why is `test_values=False` in the `test_frontend_function` call?

**Comment by nassimberrada** [comment]
I think that's a necessary argument to pass given the nature of the function itself which draws random samples at each draw. You can't test for the exactitude of values between two back-ends because they will necessarily output different value. Setting test_values = False seems to be a standard procedure when dealing with random functions apparently, that's what we did for ivy.dirichlet and it's the same for other front-end functions as well (see "random" function just above dirichlet in the numpy frontends).

**Review by Ishticode — APPROVED** [review]
Sorry my bad. This is pretty obvious. Thanks for explaining. I am absent minded sometimes 🙂. lgtm as long as the tests pass...

**Comment by nassimberrada** [comment]
Took me a while to catch that one, but ivy.dirichlet threw enough errors at me to drill that inside my head for good 😃

**Comment by Ishticode** [comment]
> Took me a while to catch that one, but ivy.dirichlet threw enough errors at me to drill that inside my head for good 😃

😂 Thats why debugging is perhaps the most active learning experience. Anyways good work @nassimberrada

**Pull request merged**
