### PR TITLE
Adding torch.argsort function

### PR DESCRIPTION
**Pull request by otmanealami**
torch.argsort

### CODE REVIEW

**Comment by otmanealami** [comment]
Close ##6978

**Comment by nathzi1505** [comment]
@jkeane508  - This seems to be an extension of #6978. 
Mind having a look?

**Comment by nathzi1505** [comment]
@otmanealami Can you take a pull of the recent changes and then add your commits. 
I just want to ensure that your torch frontend and the lint checks should pass succesfully.😃

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by nathzi1505** [comment]
The frontend part looks good to me. @CatB1t can you check the test part?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
