### PR TITLE
updated multiply #7176

### PR DESCRIPTION
**Pull request by titoausten**

### CODE REVIEW

**Comment by titoausten** [comment]
Made some changes to the docstring and docstring examples for the multiply function.

**Comment by titoausten** [comment]
Updated container/elementwise.py #7176

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @titoausten, It seems that the docstring checks are failing for the container multiply function. Can you please resolve the same?

**Comment by titoausten** [comment]
@RashulChutani I already did that with the second commit. Kindly check again. Thanks

**Review by titoausten — COMMENTED** [review]
@RashulChutani  I already did that with the second commit. Kindly check again. It's the statistical function that needs review not the multipy function. Thanks

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @titoausten Your changes are still being shown for the multiply function only. Can you please recheck that? Thanks.

**Comment by titoausten** [comment]
> Hi @titoausten Your changes are still being shown for the multiply function only. Can you please recheck that? Thanks.

@RashulChutani can you share a screenshot or something because I don't understand what you're requesting I do.

**Comment by RashulChutani** [comment]
Yeah Sure. This is what I see in Files Changed! [Screenshot_2022-11-24-14-28-45-43_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/41239718/203738215-c7defb4d-af94-4f7f-a9c5-a8b81892565e.jpg)

**Comment by titoausten** [comment]
> Yeah Sure. This is what I see in Files Changed! [Screenshot_2022-11-24-14-28-45-43_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/41239718/203738215-c7defb4d-af94-4f7f-a9c5-a8b81892565e.jpg)

Kindly check again.

**Comment by titoausten** [comment]
@RashulChutani I am yet to get a response from you.

**Comment by RashulChutani** [comment]
Hi @titoausten Sure. I will review it soon.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @titoausten I still see the changes with Multiply function which result in a lint error. Can you please check again?

**Comment by titoausten** [comment]
> Hi @titoausten I still see the changes with Multiply function which result in a lint error. Can you please check again?

@RashulChutani , can you please let me know for which exactly? Array, container or functional?

**Comment by RashulChutani** [comment]
It's for all 3 actually. Can you see the "Files Changed" section?

**Comment by titoausten** [comment]
@RashulChutani kindly review the code again

**Comment by RashulChutani** [comment]
Sure. I will do that soon.

**Comment by titoausten** [comment]
@RashulChutani , I'm still waiting for your feedback.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @titoausten I still see your changes for the multiply function only, actually.

**Comment by titoausten** [comment]
> Hi @titoausten I still see your changes for the multiply function only, actually.

I chose to work on the multiply function alone. I dont understand anymore. What am I supposed to do?.

What changes? Are they causing an error? Of course not. What should I do?.

**Comment by titoausten** [comment]
> Hi @titoausten I still see your changes for the multiply function only, actually.

The Contributor guide stated to pick out a function and work on it and that is what I did. I don't know what you expect me to do anymore.

**Comment by hirwa-nshuti** [comment]
Hey, we are sorry that this task was still open for contribution and that it caused you a lot of confusion
The task was completed via https://github.com/unifyai/ivy/pull/1617
This means that I am going to close this PR and feel free to take another issue open for contribution🙂

**Pull request closed without merging**
