### PR TITLE
matrix_exp

### PR DESCRIPTION
**Pull request by abhigya-sodani**

### CODE REVIEW

**Comment by abhigya-sodani** [comment]
I know its failing some of the tests, I just don't know how to find why they are failing. Also am not sure if I wrote the test correctly.

**Comment by X3nOph0N** [comment]
You can find the error logs here, just click the Details and you can find that you got multiple failures in the Run API test sequence. What's more, you can also use local pytest to reproduce the error. Hope this will help you.
image

**Comment by X3nOph0N** [comment]
Additionally, this is the summary of the failures.
image

**Comment by abhigya-sodani** [comment]
Fixed my test written for matrix_exp and that helped me pass some tests. However, still getting failures on functionality I did not work with at all. I have pasted all the failures below:


`FAILED ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py::test_remainder[remainder(x1, x2)]
FAILED ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py::test_remainder[__mod__(x1, x2)]
FAILED ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py::test_remainder[__imod__(x1, x2)]

FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_binary[remainder(x1_i is +0 and x2_i > 0) -> +0]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_binary[remainder(isfinite(x1_i) and x1_i > 0 and x2_i is +infinity) -> x1_i]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_binary[remainder(isfinite(x1_i) and x1_i < 0 and x2_i is -infinity) -> x1_i]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_binary[__mod__(x1_i is +0 and x2_i > 0) -> +0]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_binary[__mod__(isfinite(x1_i) and x1_i > 0 and x2_i is +infinity) -> x1_i]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_binary[__mod__(isfinite(x1_i) and x1_i < 0 and x2_i is -infinity) -> x1_i]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_iop[__imod__(x1_i is +0 and x2_i > 0) -> +0]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_iop[__imod__(isfinite(x1_i) and x1_i > 0 and x2_i is +infinity) -> x1_i]
FAILED ivy_tests/test_array_api/array_api_tests/test_special_cases.py::test_iop[__imod__(isfinite(x1_i) and x1_i < 0 and x2_i is -infinity) -> x1_i]

FAILED ivy_tests/test_array_api/array_api_tests/test_linalg.py::test_matrix_rank
`


the failures in test_matrix_rank and test_remainder are examples of this. I would really appreciate it if it would be possible to review the changes I made and see if there are any extremely obvious breaking changes I am making to the ivy.array type.

**Comment by JerryGCDing** [comment]
Hi @abhigya-sodani, thank you for contributing to Ivy 😄. As for backend submodule function implementations, the functions being used need to be backend specific (e.g. `numpy.ceil` within `numpy` backend instead of `math.ceil`), and the argument array types also need to be associated with the native array types. Also, seems like you missed the function implementation in `ivy/container/experimental/linear_algebra.py`, for more detailed guides, please refer to our doc section (https://lets-unify.ai/ivy/contributing/open_tasks.html) about `Ivy Experimental API`.
For the tests, `lint` is about potential formatting errors within your function implementations (or it can be from others' implementations, so pay close attention 😃), and you don't need to worry about failing tests that are not associated with your functions.

**Pull request closed without merging**
