### PR TITLE
Jax devicearray any

### LINKED ISSUE #14889: any

### PR DESCRIPTION
**Pull request by VictorOdede**
Close #14889

### CODE REVIEW

**Comment by VictorOdede** [comment]
@hirwa-nshuti I've fixed the merge conflicts for this branch.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Would you solve these merge conflicts as well

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Would you resolve these merge conflicts

**Review by hirwa-nshuti — APPROVED** [review]
Looks great to me!
Going to merge😊

**Pull request merged**
