### PR TITLE
Adding Linear Algebra function (Cholesky) for Tensor Flow Frontend

### LINKED ISSUE #4533: cholesky
#1140

### PR DESCRIPTION
**Pull request by 14Emanuel**
Close #4533

### CODE REVIEW

**Comment by 14Emanuel** [comment]
@zaeemansari70 hello, can you review my code please? Thanks in advance

**Comment by 14Emanuel** [comment]
@juliagsy hey, I saw you reviewed the Jax.lax.linalg.Cholesky function frontend. Can you help me with mine too? Thanks in advance

**Comment by juliagsy** [comment]
Hello! Thanks for contributing! Each PR gets an assignee from the team and they're responsible for the PR review, I'm most likely the reviewer for the jax cholesky function. I've helped to request a review from your assignee, but in rare cases, if your assignee is not responding (probably for more than 3 days from review request), I'll only step in by then, apologies for the delays due to holiday season and thanks for your understanding and patience!

**Comment by 14Emanuel** [comment]
@zaeemansari70 hey, are you there!! and free to assist in reviewing my code

**Comment by 14Emanuel** [comment]
@juliagsy hey, good morning, can you chip in for @zaeemansari70 for me please, this is the 3rd unresponsive day. I have my test running already, so it's just about you checking and merging the PR not so much to do; plus I want to continue with my internship application after merging the PR, can you assist me please, thanks in advance.

**Comment by juliagsy** [comment]
Hey! Apologies for the delayed review, I'll be able to step in if the PR is still ongoing! I'll review it if the PR is reopened! Sorry once again and thanks a lot!

**Comment by 14Emanuel** [comment]
Hey, I closed the PR and got assigned a new person

**Comment by 14Emanuel** [comment]
Hey, I can reopen it so that we can work on it together, IS THAT OKAY

**Comment by 14Emanuel** [comment]
@juliagsy the PR is reopened, I appreciate your coming in,

**Comment by 14Emanuel** [comment]
@juliagsy are you there?

**Review by juliagsy — APPROVED** [review]
Thanks for contributing! I'll merge in soon!

**Pull request merged**
