### PR TITLE
feat: add static function corrcoef to paddle backend

### LINKED ISSUE #23384: corrcoef

### PR DESCRIPTION
**Pull request by researchstarter**
close #23384

### CODE REVIEW

**Comment by researchstarter** [comment]
ivy-gardener

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Daniel4078** [comment]
I change your PR title and link this PR to the correct issue for you. Please remember what to do next time.

**Comment by researchstarter** [comment]
Hi @Daniel4078. I appreciate your help. I think that the "Trigger lint format" is failing because of other code parts. What do you think? Is it okay?

**Comment by Daniel4078** [comment]
currently, some tests are failing due to a ModuleNotFoundError: No module named 'dill' happening in another file of the code base, so you will need to wait for a bit till that problem is fixed. But it looks good to me.

**Comment by researchstarter** [comment]
Hi @Daniel4078. How can I know whether the issue with lint is fixed?

**Review by Daniel4078 — APPROVED** [review]
Looks good to me. But you can remove the unused name argument all together as the frontend and ivy version do not have it.

**Comment by researchstarter** [comment]
@Daniel4078, thank you for your comment. I removed the unused argument. Now, everything seems fine.

**Pull request merged**
