### PR TITLE
Implement numpy.ptp

### LINKED ISSUE #13820: ptp

### PR DESCRIPTION
**Pull request by P0trak**
Close #13820

### CODE REVIEW

**Comment by Sam-Armstrong** [comment]
Hi @P0trak, thanks for the PR!

When I run the tests you wrote at the moment (with the command 'pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py::test_numpy_ptp') all the cases result in failures. These all need to be passing for me to be able to merge. Also, please could you add a line of whitespace to the end of your function and test to follow standard convention.

Finally, is there a reason why you've set out=out for ivy.max, but out=None for ivy.min? Shouldn't they both be set =None (or just not specified as a param)?

Thanks

**Comment by P0trak** [comment]
Hi Sam,

I'll work on the tests and reformatting. I used the out parameters as I did because that's how they're used in the underlying NumPy implementation of the ptp function:

`def _ptp(a, axis=None, out=None, keepdims=False):
    return um.subtract(
        umr_maximum(a, axis, None, out, keepdims),
        umr_minimum(a, axis, None, None, keepdims),
        out`

**Comment by Sam-Armstrong** [comment]
@P0trak Thanks for the clarification, that makes sense

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
