### PR TITLE
Dtype

### PR DESCRIPTION
**Pull request by davidlee1102**

### CODE REVIEW

**Comment by davidlee1102** [comment]
@bicycleman15 ,
please check on my PR please, thank you

**Comment by bicycleman15** [comment]
@jkeane508 do you mind reviewing this ? Got a little too much on my plate right now 😅

**Comment by davidlee1102** [comment]
@bicycleman15 show me which food got on your plate :))), I will eat it by fixing this problems :)))

**Comment by jkeane508** [comment]
> @jkeane508 do you mind reviewing this ? Got a little too much on my plate right now 😅

Yea sure @bicycleman15 😀

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hi @davidlee1102,

Can you please remove the `.gitingore` file from this PR 😀

**Comment by davidlee1102** [comment]
Hi @jkeane508 ,
I have fixed error, let check again

**Comment by jkeane508** [comment]
So I've taken a quick look through your examples.

`ivy.dtype` also has an instance method implementation so you need to include that in your examples.

Its explained here - https://lets-unify.ai/ivy/deep_dive/12_docstring_examples.html

Please request a review when you have added these examples 😄

**Comment by davidlee1102** [comment]
Hi @jkeane508 ,
You should check dtype again because of it still not have instance examples for this
```
    x1 = ivy.array([1, 0, 1, -1, 0])
    y = x1.dtype()
    print(y)
````
Thank you, 
David

**Comment by davidlee1102** [comment]
Hi @jkeane508 ,
Could you please check my PR again, thank you 😄 
David

**Comment by jkeane508** [comment]
Hi David,

Your examples look good to me, however there have been changes made to the `test_array_api` files in your commit. If you could remove these that would be great. There should only be changes made to the `data_type.py` file in your commit.

Thanks!

**Comment by davidlee1102** [comment]
Hi @jkeane508 ,
Let check again for this
Thank you 
David

**Comment by jkeane508** [comment]
Thanks😄

**Pull request merged**
