### PR TITLE
close #16543

### LINKED ISSUE #16543: concat

### PR DESCRIPTION
**Pull request by huzi6181**
Close #16543

### CODE REVIEW

**Comment by huzi6181** [comment]
@khushi-411 im sorry if im bothering you but ive created a new pull request, i would appreciate it if you could review, for now it is a partial solution, note that i havent made any format changes at all this time around

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by huzi6181** [comment]
Hi, i have received no feedback yet

**Comment by sondertg** [comment]
Hi, there is currently a merge conflict and please kindly check docs.
https://unify.ai/docs/ivy/overview/contributing.html

**Comment by huzi6181** [comment]
@sondertg i have resolved merge conflicts, i would really really appreciate it if you could help me with the failing checks (I only added the concat method in tensor.py, i didnt touch anything else)

**Pull request closed without merging**
