### PR TITLE
pixel_unshuffle function added for Paddle Frontend

### LINKED ISSUE #21596: pixel_unshuffle

### PR DESCRIPTION
**Pull request by Sameerk22**
Close #21596

### CODE REVIEW

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Kindly un-commit the changes in the `.idea` folder.
Thanks!

**Comment by Sameerk22** [comment]
> Kindly un-commit the changes in the `.idea` folder. Thanks!
Done

**Comment by Sameerk22** [comment]
The changes requested by the reviewer i.e. Zaeem Ansari are done and I have reponed the pull request.

**Comment by paulaehab** [comment]
Hello @Sameerk22 first sorry for late reply, thanks for your contributing first to review this PR the edits must be the 2 files related to the function vision.py and test_vision.py so I can review the function and merge the PR.please remove all edits and changes in the other file so the file changes be these two files only.

**Comment by Sameerk22** [comment]
Hi! @paulaehab 
Thanks for reaching out. 
By deleting the files from this pull request will solve it? Like I did for 2 files?

**Comment by Sameerk22** [comment]
Kindly check.
Now I have only 2 files (the required ones) with changes.

**Comment by paulaehab** [comment]
Hi @Sameerk22  again I am very sorry for late reply, I mean you should have the File changed contain only the needed file so if may be you can  un commit your commit because the changes files may affect our repo.
Also, I have test the function, and it works fine great work, and thanks for your contributing 👍it just failing for paddle and torch backend just take a llok at them both but totally great work 😄

**Comment by Sameerk22** [comment]
Hi @paulaehab .
So i reseted those commits but from where I did that these 2 files (i.e. tensor.py & test_tensor.py )were also present so I though this should come along. There is no conflict or change in it. But those unnecessary files are now gone.
Kindly check.

**Comment by paulaehab** [comment]
> Hi @paulaehab . So i reseted those commits but from where I did that these 2 files (i.e. tensor.py & test_tensor.py )were also present so I though this should come along. There is no conflict or change in it. But those unnecessary files are now gone. Kindly check.

Yeah that is working fine right now but there is 2 different files added of torch (tensor.py and test_tensor.py) could you check that and remove them and I will merge the PR, thanks for your contributing 👍

**Comment by Sameerk22** [comment]
> > Hi @paulaehab . So i reseted those commits but from where I did that these 2 files (i.e. tensor.py & test_tensor.py )were also present so I though this should come along. There is no conflict or change in it. But those unnecessary files are now gone. Kindly check.
> 
> Yeah that is working fine right now but there is 2 different files added of torch (tensor.py and test_tensor.py) could you check that and remove them and I will merge the PR, thanks for your contributing 👍

Hi! @paulaehab 
So finally, I have made all the changes as required.
Now waiting for you to merge it.
And Thank You! It was great interacting.

**Comment by Sameerk22** [comment]
@paulaehab

**Comment by paulaehab** [comment]
Hey @Sameerk22  lgt thanks for contributing 😄

**Pull request merged**
