### PR TITLE
Map

### PR DESCRIPTION
**Pull request by Psychofun**
Pull request for issue #2094

### CODE REVIEW

**Comment by Psychofun** [comment]
#2094

**Comment by RickSanchezStoic** [comment]
Hi @Psychofun the changes you made were not needed. The `lambda`s are only to be replaced for backends. You just need to add the docstring examples for the `map` function following the docstring examples guide. Please feel free to ask any more queries you might have.

**Comment by Psychofun** [comment]
Hi there! @RickSanchezStoic 
I've added some examples for map. 
I'll be waiting for your review and comments.
Thanks.

**Comment by RickSanchezStoic** [comment]
@Psychofun kindly fix the lint errors for the file you made changes to. Also, once you make the changes, do `bash ./merge_with_upstream` to update your fork with unifyai:master. Thanks

**Comment by Psychofun** [comment]
@RickSanchezStoic I made the corrections. 
  One question. Using  `./merge_with_upstream ` is equivalent to use the `Update branch` button?
  Thank you!

**Comment by RickSanchezStoic** [comment]
> @RickSanchezStoic I made the corrections. One question. Using `./merge_with_upstream ` is equivalent to use the `Update branch` button? Thank you!

Yes, in the end you should just make sure that your fork is not behind the master

**Comment by RickSanchezStoic** [comment]
@Psychofun you need to fix the docstring errors for your specific functions. Kindly check the contributor guide and update. Feel free to ask any queries. Thanks!

**Comment by Psychofun** [comment]
@RickSanchezStoic 
I have corrected the errors, I think there aren't anymore. 
Let me know what else is needed to carry out the PR.
Thanks for your time.

**Comment by RickSanchezStoic** [comment]
@Psychofun Check the docstring log and you will find `map` is still there in the list of failing functions.

**Comment by Psychofun** [comment]
@RickSanchezStoic  I checked  and fixed it. I hope now  all is working well.
I'm waiting your review.
Thanks for your feedback.

**Comment by RickSanchezStoic** [comment]
Looks good to me!

**Pull request merged**
