### PR TITLE
feat: Added adaptive max pooling 3D to Ivy backend

### LINKED ISSUE #22318: adaptive_max_pool3d

### PR DESCRIPTION
**Pull request by arshPratap**
Added adaptive max pooling 3D function to ivy backend.
Currently utilized by Torch and Paddle Frameworks
This PR will be followed by another PRs that enables the said function into the designated framework frontends

## Related Issue 

Close #22318 

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by bipinKrishnan** [comment]
ivy-gardener

**Comment by bipinKrishnan** [comment]
Hey @arshPratap, can you please resolve the conflicts?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by arshPratap** [comment]
Rebased !

**Comment by Ishticode** [comment]
conflicted as this already exists.

**Pull request closed without merging**
