### PR TITLE
add: make_ndarray : function + test

### PR DESCRIPTION
**Pull request by Khushiyant**
Completed sub task in #6931

Added ```make_ndarray``` in ```general_function.py``` with following tasks:

- [x] Written test for ```make_ndarray``` in ```test_general_function.py``` 
- [x] Written function for ```make_ndarray```

Added function properties:
- Parameter : x -> ```Any```, name -> ```None```
- Return Type: ```ivy.Array```
- Function tree:  ```tensorflow.make_ndarray```

### CODE REVIEW

**Comment by ukj02** [comment]
Hi @Khushiyant ! Thank You for your contribution!
I am getting the error `TypeError: make_ndarray() got an unexpected keyword argument 't'`. Can you check it out and see what the problem is.

Thanks! 😄

**Comment by Khushiyant** [comment]
I have solved all the errors on my side but I feel there is a problem in core implementation of ```tensor_util.py``` and ```tensor.py``` due to usage of undefined properties such as ```tensor_shape``` and ```tensor_contents``` 

```
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py:139: in test_tensorflow_make_ndarray
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:731: in test_frontend_function
    ret, frontend_ret = _test_frontend_function(args, kwargs, args_ivy, kwargs_ivy)
ivy_tests/test_ivy/helpers/function_testing.py:702: in _test_frontend_function
    raise e
ivy_tests/test_ivy/helpers/function_testing.py:675: in _test_frontend_function
    frontend_ret = frontend_fw.__dict__[fn_name](
/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/tensor_util.py:592: in MakeNdarray
    shape = [d.size for d in tensor.tensor_shape.dim]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tf.Tensor: shape=(2,), dtype=float16, numpy=array([-1., -1.], dtype=float16)>, name = 'tensor_shape'

    def __getattr__(self, name):
      if name in {"T", "astype", "ravel", "transpose", "reshape", "clip", "size",
                  "tolist", "data"}:
        # TODO(wangpeng): Export the enable_numpy_behavior knob
        raise AttributeError(
            f"{type(self).__name__} object has no attribute '{name}'. " + """
          If you are looking for numpy-related methods, please run the following:
          from tensorflow.python.ops.numpy_ops import np_config
          np_config.enable_numpy_behavior()
        """)
>     self.__getattribute__(name)
E     AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'tensor_shape'
E     Falsifying example: test_tensorflow_make_ndarray(
E         dtype_and_x=(['float16'], [array([-1., -1.], dtype=float16)]),
E         as_variable=[False],
E         num_positional_args=0,
E         native_array=[False],
E         fn_tree='ivy.functional.frontends.tensorflow.make_ndarray',
E         on_device='cpu',
E         frontend='tensorflow',
E     )
E     
E     You can reproduce this example by temporarily adding @reproduce_failure('6.55.0', b'AXicY2SAAEYkGpnNAAAAfgAG') as a decorator on your test case

/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py:446: AttributeError
```

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ZoeCD** [comment]
Hi! Sorry for the late reply. Are you still interested in working in this PR? Do you have any updates on the problem you faced?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
