### PR TITLE
Implemented `__matmul__`

### PR DESCRIPTION
**Pull request by TudorAndrei**
Solves #119

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by TudorAndrei** [comment]
Edits are allowed :smile:

**Comment by djl11** [comment]
> Edits are allowed 😄

Thank you!

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Review by djl11 — CHANGES_REQUESTED** [review]
Please reformat the code as describe in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/), and also as explained in this [YouTube series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl).

**Review by djl11 — APPROVED** [review]

**Review by djl11 — CHANGES_REQUESTED** [review]
The NumPy tests seems to be failing. I didn't try any other tests. Can you get these tests passing and then I'm happy to merge :)

**Comment by TudorAndrei** [comment]
I will check on the NumPy erros

**Review by djl11 — CHANGES_REQUESTED** [review]
There are no changes since my last review. Please request a new review once changes have been made and the tests are passing :)

**Comment by TudorAndrei** [comment]
Apparently the @ operation is not tested in [Array api](https://github.com/data-apis/array-api-tests/blob/511929cebea939f137f910b4a68ddbce42f69611/array_api_tests/test_linalg.py#L282). How should I proceed @djl11

**Comment by djl11** [comment]
Unfortunately operator methods do not have dedicated unit tests in the Array API test suite, and so these issues are being closed. Please choose another method to work on. Very sorry for the confusion.

**Review by djl11 — COMMENTED** [review]
Unfortunately operator methods do not have dedicated unit tests in the Array API test suite, and so these issues are being closed. Please choose another method to work on. Apologies for the confusion.

**Pull request closed without merging**
