### PR TITLE
Trace function

### PR DESCRIPTION
**Pull request by JudeDavis1**

### CODE REVIEW

**Comment by JudeDavis1** [comment]
Please review the pull request, thanks.

**Comment by JudeDavis1** [comment]
Still awaiting a review...

**Comment by Ishticode** [comment]
@JudeDavis1 looks like your PR is about ready : ) . I will request final review from Daniel before merge.

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
