### PR TITLE
tensor_scatter_nd_max

### LINKED ISSUE #10890: tensor_scatter_nd_max

### PR DESCRIPTION
**Pull request by Husienvora**
Close #10890

### CODE REVIEW

**Comment by Husienvora** [comment]
Hey it's my first pr I might need some feedback if I am doing something wrong

**Comment by aditya-hari** [comment]
Hey, sorry for the delay. Can you please copy over the changes to a new PR? The commit histories are messed up since the restructuring

**Comment by Husienvora** [comment]
sure

**Comment by Husienvora** [comment]
hey #11843 is the new pr

**Pull request closed without merging**
