### PR TITLE
mean_absolute_error frontend function added

### PR DESCRIPTION
**Pull request by yash-garg274**
#9966 

**Overview**
Can take the input in all 4 framework types and converts the output into the required framework types. The function takes y_true and y_pred as parameters and finds the mean of their absolute difference. 

I have added the mean_absolute_error function and have written the test function for it.

### CODE REVIEW

**Comment by suvadityamuk** [comment]
Hi, Yash!

I can only see the test in the final PR's `files changed` set. May I suggest you take a look once again to see if you have committed all the required files?

Also, it seems that the linting check and a few of the tests are failing. Please do make sure you can clear them

**Comment by yash-garg274** [comment]
Hi @suvadityamuk, please check my updated code, all the test cases related to mean_absolute_error are passing but for a few other functions it's failing. I am not getting why I am getting an error for the lining part, let me know if I can make changes in my code for it. Thanks

**Comment by suvadityamuk** [comment]
Hi, @yash-garg274 

Please use the [pre-commit hook](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit) to try and fix the linting errors.

**Comment by suvadityamuk** [comment]
Hi, there!

Do you mind merging the current main branch? We should mostly then be good to go. :slightly_smiling_face: 
Thanks!

**Comment by yash-garg274** [comment]
> Hi, there!
> 
> Do you mind merging the current main branch? We should mostly then be good to go. 🙂 Thanks!

Hi, I have taken the pull from the main branch into my pull request. Could you please check it and let me know if it's ready to merge with the main branch?
Thanks

**Comment by suvadityamuk** [comment]
LGTM, thank you for your contribution!

**Comment by yash-garg274** [comment]
> LGTM, thank you for your contribution!

Thanks @suvadityamuk for helping me out. Could you please tell me the next step?

**Comment by suvadityamuk** [comment]
Sure thing, @yash-garg274!

 Feel free to submit the PR link on the link given in your email to go ahead with the next-steps. If you have any other questions, reach out on our Discord for more info! Good luck! :grin:

**Pull request merged**
