### PR TITLE
general functions gradients

### PR DESCRIPTION
**Pull request by KartikeyDubeyKD**

### CODE REVIEW

**Comment by KartikeyDubeyKD** [comment]
#14818

**Comment by valeriocost** [comment]
Hi @KartikeyDubeyKD, LGTM 👍🏼 did you ask for a review from @CatB1t ?

**Comment by KartikeyDubeyKD** [comment]
No, sir not yet

**Comment by KartikeyDubeyKD** [comment]
do I have to ping him on Discord?

**Comment by KartikeyDubeyKD** [comment]
@CatB1t Hello kindly review this PR

**Comment by valeriocost** [comment]
Hi @KartikeyDubeyKD can you try to rebase with master in order to check if the tests are passing here? Thanks 🙏🏼

**Comment by KartikeyDubeyKD** [comment]
Sorry sir, I did something wrong while trying to rebase it with Master, can I uncommit this recent commit?

**Comment by valeriocost** [comment]
you should be able to revert the last commit "Merge branch 'unifyai:master' into grad" 😄

**Pull request closed without merging**
