### PR TITLE
Changes to jax/numpy/fft.py

### PR DESCRIPTION
**Pull request by KaiGarcia**

### CODE REVIEW

**Comment by modanesh** [comment]
Hey @KaiGarcia  🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

**Comment by modanesh** [comment]
Since it's not required, could you help me understand why is there a new `requirements.txt` file? 
Also, could you please write a test for the implemented function according to [this doc](https://lets-unify.ai/ivy/deep_dive/ivy_tests.html)? Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
