### PR TITLE
Added fmax function

### PR DESCRIPTION
**Pull request by progrmoiz**
fmax #4808

### CODE REVIEW

**Comment by Auxia** [comment]
Hi @progrmoiz, are you still working on this PR? We noticed this PR has been inactive for the past 3 weeks. Please let me know if you need help with anything or if you have stopped working on this PR. Otherwise, we will label this PR as stale and promptly close it.

Thanks!

**Comment by progrmoiz** [comment]
Yes, I was working on it and waiting for it to be reviewed. But didn't get reviewed last time by the team.

I'll work on resolving the new code conflicts now.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Auxia** [comment]
Hi @progrmoiz, I have noticed that the code conflicts haven't been resolved yet. Are you still working on this PR?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
