### PR TITLE
min function 0.1

### PR DESCRIPTION
**Pull request by skipper-com**
Base commit for min function adhere to standard

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hi, please could you move the functions to the correct files. For example, the min function currently in ivy/functional/ivy/core/general.py needs to be moved to ivy/functional/ivy/array-api/statistical_functions.py. All the backend functions also need to be moved to the correct files. 

Could you go to the file ivy_tests/array_api_methods_to_test/statistical_functions.txt and uncomment your function min, so that the tests run. Thanks 🙂

**Comment by skipper-com** [comment]
> Hi, please could you move the functions to the correct files. For example, the min function currently in ivy/functional/ivy/core/general.py needs to be moved to ivy/functional/ivy/array-api/statistical_functions.py. All the backend functions also need to be moved to the correct files.
> 
> Could you go to the file ivy_tests/array_api_methods_to_test/statistical_functions.txt and uncomment your function min, so that the tests run. Thanks 🙂

Hi Matt,
I've done everything you mentioned. But 1 test failed for all frameworks (test_ceil_special_cases_one_arg_equal_1). Probably, this is out of my task scope. Or not?

**Comment by skipper-com** [comment]
> Yes this failure is unrelated to your changes don't worry about it. All tests for min are passing, we'll just wait for final confirmation from @djl11 before merging your changes. Thanks 🙂

Thanks! I'll wait.

**Review by djl11 — CHANGES_REQUESTED** [review]
Looks good! No need to add the commented out old methods though, you should just delete these :) Once they have been removed, I'll get it merged! Thanks!

**Comment by skipper-com** [comment]
> Looks good! No need to add the commented out old methods though, you should just delete these :) Once they have been removed, I'll get it merged! Thanks!

I'm too new in developing process, so I choose comment unnecessary code out. Now I deleted it and push a new commit. Hope for the quick merge:)

**Review by mattbarrett98 — APPROVED** [review]

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
