### PR TITLE
added std to numpy fronted and tested

### PR DESCRIPTION
**Pull request by philipilono**
- [x] #6696

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by philipilono** [comment]
This PR is still awaiting review

**Comment by philipilono** [comment]
Hi, is this PR going to be reviewed?

**Review by MarShaikh — COMMENTED** [review]
Hi, the code looks great, but unfortunately, it seems like there was some confusion regarding the issue allotment. I noticed that you had opened the issue first, but we didn't realise that someone else also tagged your issue in their PR. No worries though, please send a message to IvyTeam acc with your email and this PR link so we can proceed to further steps if this was a part of the application process. Otherwise, sorry we have to close this!

**Pull request closed without merging**
