### PR TITLE
ArgMax  (Add RawOps Operations for TensorFlow)

### PR DESCRIPTION
**Pull request by Lancelot03**

### CODE REVIEW

**Comment by Lancelot03** [comment]
Should I close this PR or do some changes in this only

**Comment by ZoeCD** [comment]
Hello! Thank you for your contribution! Sadly, frontend tasks are not open yet. Can you close this PR, please? You can open it again when we open the frontend tasks. Meanwhile, if you are applying for the internship, you can read our guide about how you can contribute [here](https://lets-unify.ai/ivy/contributing.html) 😊

**Comment by Lancelot03** [comment]
Thanks for let me know 😊

**Comment by Lancelot03** [comment]
> Hello! Thank you for your contribution! Sadly, frontend tasks are not open yet. Can you close this PR, please? You can open it again when we open the frontend tasks. Meanwhile, if you are applying for the internship, you can read our guide about how you can contribute [here](https://lets-unify.ai/ivy/contributing.html) 😊

And Please let me know more about the internship.

**Pull request closed without merging**
