### PR TITLE
feat(jax frontend): add histogram function

### LINKED ISSUE #26450: histogram

### PR DESCRIPTION
**Pull request by bangaradi**
# PR Description

## Related Issue

Close #26450

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by bangaradi** [comment]
To the reviewer,

The failing test cases as shown in the results aren't related to the function that I've made or the testcases that I've written.
Can you please look into it.

Thanks.

**Review by HaiderSultanArc — COMMENTED** [review]
Hey @bangaradi . CI is not picking up tests so I have to wait till that is fixed before merging this PR 😄

**Comment by bangaradi** [comment]
Are you talking about the one failed test? 
Or is it something on your side?

Because if you are talking about that one failed check, it is unrelated to my PR and seems to be common even among some other PRs and also doesn't introduce any new errors, as given by the CI bot.

Thank you for the review!

**Comment by bangaradi** [comment]
> Hey @bangaradi . CI is not picking up tests so I have to wait till that is fixed before merging this PR 😄 

Are you talking about the one failed test? 
Or is it something on your side?

Because if you are talking about that one failed check, it is unrelated to my PR and seems to be common even among some other PRs and also doesn't introduce any new errors, as given by the CI bot.

Thank you for the review!

**Comment by HaiderSultanArc** [comment]
@bangaradi I mean the CI didn't pick up the test you wrote. Can you merge upstream/main with your branch to see if that helps?

**Comment by bangaradi** [comment]
> @bangaradi I mean the CI didn't pick up the test you wrote. Can you merge upstream/main with your branch to see if that helps?

@HaiderSultanArc I've merged with the upstream, can you check now and let me know? Thank you.

**Comment by bangaradi** [comment]
@HaiderSultanArc Can you explain any way in which I can checkout why the CI pipeline isn't picking up the testcase that I've written? 

Thanks!

**Comment by bangaradi** [comment]
Hey @HaiderSultanArc ,
Can you check this out and suggest any changes?

**Comment by NiteshK84** [comment]
Hi @bangaradi , 
please resolve the merge conflicts so we can proceed with your pull request.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ishticode** [comment]
Closing this due to inactivity for over 3 months. Please feel free to reopen if you would like to continue working on this. Thank you :)

**Pull request closed without merging**
