### PR TITLE
changes and fixes

### PR DESCRIPTION
**Pull request by RickSanchezStoic**
fixes and changes for more dtype promotion

### CODE REVIEW

**Comment by mattbarrett98** [comment]
Just curious, what makes these type promotions necessary- are any tests failing?

**Comment by RickSanchezStoic** [comment]
Yeah, so this was part of the individual task that was assigned to me, while I had implemented the type promotions for the functions previously but it later turned out that some functions were missed or were not discovered yet. Also, it was proposed that many functions were not being tested for this either. So I looked for the functions mainly those that perform operations on two or more inputs and did the type promotion to stay on the safer side.

**Review by mattbarrett98 — COMMENTED** [review]
Ah okay. Recently the tests for type promotion were fixed and are now all running. You can have a look in the `type_promotions` array API tests. I think the only ones still with errors are some of the bitwise functions. Hence we shouldn't bother with the casting in these functions, as it will only slow them down.

**Comment by RickSanchezStoic** [comment]
alright then, will close this for now.

**Pull request merged**
