### PR TITLE
test(backend handler): added tests for inplace update warnings.

### PR DESCRIPTION
**Pull request by Madjid-CH**
# PR Description
when we introduced a warning when a backend does not support inplace update in `previous_backend `function [here](https://github.com/unifyai/ivy/blob/1c14ca4a627e415700bda678141108ef7ccf1c6c/ivy/utils/backend/handler.py#L546) that made the warning being throwed multiple times when setting a backend because we are iterating the `backend_stack `and calling `previous_backend` [here](https://github.com/unifyai/ivy/blob/1c14ca4a627e415700bda678141108ef7ccf1c6c/ivy/utils/backend/handler.py#L402C46-L402C46) so I added a flag to avoid this behavior. 
```python
ivy.set_tensorflow_backend()
 UserWarning: The current backend: 'tensorflow' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
  warnings.warn(
ivy.set_jax_backend()
UserWarning: The current backend: '' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
  warnings.warn(
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
UserWarning: The current backend: 'jax' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
  warnings.warn(
```

### CODE REVIEW

**Comment by Madjid-CH** [comment]
@vedpatwardhan I noticed you have provided a solution before I had a chance create a PR.
at least we can add the tests I added, also using the `_inplace_update_cache` will make the warning of a given backend appear once:
```python
ivy.set_tensorflow_backend()
UserWarning: The current backend: 'tensorflow' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
  warnings.warn(
ivy.set_tensorflow_backend()

```
so the second time we call `ivy.set_tensorflow_backend()` no warning is raised. Do we want this behavior ?

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
> @vedpatwardhan I noticed you have provided a solution before I had a chance create a PR. at least we can add the tests I added, also using the `_inplace_update_cache` will make the warning of a given backend appear only once even when setting the backend for a second time:
> 
> ```python
> ivy.set_tensorflow_backend()
> UserWarning: The current backend: 'tensorflow' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
>   warnings.warn(
> ivy.set_tensorflow_backend()
> ```
> 
> so the second time we call `ivy.set_tensorflow_backend()` no warning is raised. Do we want this behavior ?

Yep exactly, given that the user has already seen the warning once, throwing the warning a second time could be annoying. Could you please revert the changes except for the tests? Thanks @Madjid-CH 😄

**Comment by Madjid-CH** [comment]
> > @vedpatwardhan I noticed you have provided a solution before I had a chance create a PR. at least we can add the tests I added, also using the `_inplace_update_cache` will make the warning of a given backend appear only once even when setting the backend for a second time:
> > ```python
> > ivy.set_tensorflow_backend()
> > UserWarning: The current backend: 'tensorflow' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
> >   warnings.warn(
> > ivy.set_tensorflow_backend()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so the second time we call `ivy.set_tensorflow_backend()` no warning is raised. Do we want this behavior ?
> 
> Yep exactly, given that the user has already seen the warning once, throwing the warning a second time could be annoying. Could you please revert the changes except for the tests? Thanks @Madjid-CH 😄

sure

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Feel free to merge, thanks @Madjid-CH 😄
(Given that the tests aren't running in the CI due to a docker issue, I'd suggest running these tests and ensuring that they're passing before you merge)

**Comment by Madjid-CH** [comment]
> lgtm! Feel free to merge, thanks @Madjid-CH 😄 (Given that the tests aren't running in the CI due to a docker issue, I'd suggest running these tests and ensuring that they're passing before you merge)

you don't have to ask 🙌

**Pull request merged**
