### PR TITLE
ENH: equal_all is added in paddle tesnor.py

### LINKED ISSUE #17949: equal_all
adding equal_all in paddle  tensor.py

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
Closed #17949

### CODE REVIEW

**Comment by KareemMAX** [comment]
Hey @MuhammadNizamani 

To streamline the review process a little bit. Do you mind adding a comment and in it "add_frontend_checklist" (without double quotes nor newlines)? Our automation will convert your comment into a checklist where you can fill which points you have completed, then I'll start our review process

**Comment by MuhammadNizamani** [comment]
add_frontend_checklist

**Comment by MuhammadNizamani** [comment]
@KareemMAX  check list added

**Comment by MuhammadNizamani** [comment]
> Hey @MuhammadNizamani,
> 
> Great work, but seems like tests are failing on all backends. Can you look into that?

@KareemMAX  can you tell me more about tests which are failing?
becasue local test are passing take a look the pic
equall_all

**Comment by KareemMAX** [comment]
@MuhammadNizamani weird, I guess I'll provide you with my whole log. I'm testing on codespaces.
<details>
  <summary>Error output</summary>

  ```
  @KareemMAX ➜ /workspaces/ivy (equal_all) $ pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py::test_paddle_equal_all
  Use Database in ReadOnly Mode with local caching !
  ================================================================================= test session starts =================================================================================
  platform linux -- Python 3.10.0, pytest-7.3.2, pluggy-1.2.0
  backend(s): all
  device: cpu
  number of Hypothesis examples: 25
  rootdir: /workspaces/ivy
  plugins: typeguard-2.13.3, anyio-3.7.0, hypothesis-6.79.2, metadata-3.0.0, json-report-1.5.0
  collected 5 items                                                                                                                                                                     

  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py FFFFF                                                                                           [100%]

  ====================================================================================== FAILURES =======================================================================================
  ________________________________________________________ test_paddle_equal_all[cpu-ivy.functional.backends.numpy-False-False] _________________________________________________________

  frontend = 'paddle', on_device = 'cpu'

      @handle_frontend_method(
  >       class_tree=CLASS_TREE,
          init_tree="paddle.to_tensor",
          method_name="equal_all",
          dtypes_and_x=helpers.dtype_and_values(
              available_dtypes=helpers.get_dtypes("valid"),
              num_arrays=2,
              min_value=-np.inf,
              max_value=np.inf,
              shared_dtype=True,
              safety_factor_scale="log",
              small_abs_safety_factor=32,
          ),
      )

  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1856: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1878: in test_paddle_equal_all
      helpers.test_frontend_method(
  ivy_tests/test_ivy/helpers/function_testing.py:1542: in test_frontend_method
      value_test(
  ivy_tests/test_ivy/helpers/assertions.py:111: in value_test
      assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  values = [[array([ True])], [array(True)]], this_key_chain = None

      def assert_same_type_and_shape(values, this_key_chain=None):
          x_, y_ = values
          for x, y in zip(x_, y_):
              if isinstance(x, np.ndarray):
                  x_d = str(x.dtype).replace("longlong", "int64")
                  y_d = str(y.dtype).replace("longlong", "int64")
  >               assert (
                      x.shape == y.shape
                  ), "returned shape = {}, ground-truth returned shape = {}".format(
                      x.shape, y.shape
                  )
  E               AssertionError: returned shape = (1,), ground-truth returned shape = ()
  E               Falsifying example: test_paddle_equal_all(
  E                   frontend='paddle',
  E                   on_device='cpu',
  E                   dtypes_and_x=(['bool', 'bool'], [array(False), array(False)]),
  E                   method_flags=FrontendMethodTestFlags(
  E                       num_positional_args=0,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E                   frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.paddle' from '/workspaces/ivy/ivy/functional/frontends/paddle/__init__.py'>, framework_init_module=<module 'paddle' from '/opt/fw/paddle/paddle/__init__.py'>, init_name='to_tensor', method_name='equal_all'),
  E                   init_flags=FrontendMethodTestFlags(
  E                       num_positional_args=1,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E               )
  E               
  E               You can reproduce this example by temporarily adding @reproduce_failure('6.79.2', b'AAEAAAAAAAAAAAA=') as a decorator on your test case

  ivy_tests/test_ivy/helpers/assertions.py:71: AssertionError
  _________________________________________________________ test_paddle_equal_all[cpu-ivy.functional.backends.jax-False-False] __________________________________________________________

  frontend = 'paddle', on_device = 'cpu'

      @handle_frontend_method(
  >       class_tree=CLASS_TREE,
          init_tree="paddle.to_tensor",
          method_name="equal_all",
          dtypes_and_x=helpers.dtype_and_values(
              available_dtypes=helpers.get_dtypes("valid"),
              num_arrays=2,
              min_value=-np.inf,
              max_value=np.inf,
              shared_dtype=True,
              safety_factor_scale="log",
              small_abs_safety_factor=32,
          ),
      )

  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1856: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1878: in test_paddle_equal_all
      helpers.test_frontend_method(
  ivy_tests/test_ivy/helpers/function_testing.py:1542: in test_frontend_method
      value_test(
  ivy_tests/test_ivy/helpers/assertions.py:111: in value_test
      assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  values = [[array([ True])], [array(True)]], this_key_chain = None

      def assert_same_type_and_shape(values, this_key_chain=None):
          x_, y_ = values
          for x, y in zip(x_, y_):
              if isinstance(x, np.ndarray):
                  x_d = str(x.dtype).replace("longlong", "int64")
                  y_d = str(y.dtype).replace("longlong", "int64")
  >               assert (
                      x.shape == y.shape
                  ), "returned shape = {}, ground-truth returned shape = {}".format(
                      x.shape, y.shape
                  )
  E               AssertionError: returned shape = (1,), ground-truth returned shape = ()
  E               Falsifying example: test_paddle_equal_all(
  E                   frontend='paddle',
  E                   on_device='cpu',
  E                   dtypes_and_x=(['bool', 'bool'], [array(False), array(False)]),
  E                   method_flags=FrontendMethodTestFlags(
  E                       num_positional_args=0,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E                   frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.paddle' from '/workspaces/ivy/ivy/functional/frontends/paddle/__init__.py'>, framework_init_module=<module 'paddle' from '/opt/fw/paddle/paddle/__init__.py'>, init_name='to_tensor', method_name='equal_all'),
  E                   init_flags=FrontendMethodTestFlags(
  E                       num_positional_args=1,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E               )
  E               
  E               You can reproduce this example by temporarily adding @reproduce_failure('6.79.2', b'AXicY2RAAAAAGAAC') as a decorator on your test case

  ivy_tests/test_ivy/helpers/assertions.py:71: AssertionError
  ______________________________________________________ test_paddle_equal_all[cpu-ivy.functional.backends.tensorflow-False-False] ______________________________________________________

  frontend = 'paddle', on_device = 'cpu'

      @handle_frontend_method(
  >       class_tree=CLASS_TREE,
          init_tree="paddle.to_tensor",
          method_name="equal_all",
          dtypes_and_x=helpers.dtype_and_values(
              available_dtypes=helpers.get_dtypes("valid"),
              num_arrays=2,
              min_value=-np.inf,
              max_value=np.inf,
              shared_dtype=True,
              safety_factor_scale="log",
              small_abs_safety_factor=32,
          ),
      )

  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1856: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1878: in test_paddle_equal_all
      helpers.test_frontend_method(
  ivy_tests/test_ivy/helpers/function_testing.py:1542: in test_frontend_method
      value_test(
  ivy_tests/test_ivy/helpers/assertions.py:111: in value_test
      assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  values = [[array([ True])], [array(True)]], this_key_chain = None

      def assert_same_type_and_shape(values, this_key_chain=None):
          x_, y_ = values
          for x, y in zip(x_, y_):
              if isinstance(x, np.ndarray):
                  x_d = str(x.dtype).replace("longlong", "int64")
                  y_d = str(y.dtype).replace("longlong", "int64")
  >               assert (
                      x.shape == y.shape
                  ), "returned shape = {}, ground-truth returned shape = {}".format(
                      x.shape, y.shape
                  )
  E               AssertionError: returned shape = (1,), ground-truth returned shape = ()
  E               Falsifying example: test_paddle_equal_all(
  E                   frontend='paddle',
  E                   on_device='cpu',
  E                   dtypes_and_x=(['bool', 'bool'], [array(False), array(False)]),
  E                   method_flags=FrontendMethodTestFlags(
  E                       num_positional_args=0,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E                   frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.paddle' from '/workspaces/ivy/ivy/functional/frontends/paddle/__init__.py'>, framework_init_module=<module 'paddle' from '/opt/fw/paddle/paddle/__init__.py'>, init_name='to_tensor', method_name='equal_all'),
  E                   init_flags=FrontendMethodTestFlags(
  E                       num_positional_args=1,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E               )
  E               
  E               You can reproduce this example by temporarily adding @reproduce_failure('6.79.2', b'AXicY2RAAAAAGAAC') as a decorator on your test case

  ivy_tests/test_ivy/helpers/assertions.py:71: AssertionError
  ________________________________________________________ test_paddle_equal_all[cpu-ivy.functional.backends.torch-False-False] _________________________________________________________

  frontend = 'paddle', on_device = 'cpu'

      @handle_frontend_method(
  >       class_tree=CLASS_TREE,
          init_tree="paddle.to_tensor",
          method_name="equal_all",
          dtypes_and_x=helpers.dtype_and_values(
              available_dtypes=helpers.get_dtypes("valid"),
              num_arrays=2,
              min_value=-np.inf,
              max_value=np.inf,
              shared_dtype=True,
              safety_factor_scale="log",
              small_abs_safety_factor=32,
          ),
      )

  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1856: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1878: in test_paddle_equal_all
      helpers.test_frontend_method(
  ivy_tests/test_ivy/helpers/function_testing.py:1542: in test_frontend_method
      value_test(
  ivy_tests/test_ivy/helpers/assertions.py:111: in value_test
      assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  values = [[array([ True])], [array(True)]], this_key_chain = None

      def assert_same_type_and_shape(values, this_key_chain=None):
          x_, y_ = values
          for x, y in zip(x_, y_):
              if isinstance(x, np.ndarray):
                  x_d = str(x.dtype).replace("longlong", "int64")
                  y_d = str(y.dtype).replace("longlong", "int64")
  >               assert (
                      x.shape == y.shape
                  ), "returned shape = {}, ground-truth returned shape = {}".format(
                      x.shape, y.shape
                  )
  E               AssertionError: returned shape = (1,), ground-truth returned shape = ()
  E               Falsifying example: test_paddle_equal_all(
  E                   frontend='paddle',
  E                   on_device='cpu',
  E                   dtypes_and_x=(['bool', 'bool'], [array(False), array(False)]),
  E                   method_flags=FrontendMethodTestFlags(
  E                       num_positional_args=0,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E                   frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.paddle' from '/workspaces/ivy/ivy/functional/frontends/paddle/__init__.py'>, framework_init_module=<module 'paddle' from '/opt/fw/paddle/paddle/__init__.py'>, init_name='to_tensor', method_name='equal_all'),
  E                   init_flags=FrontendMethodTestFlags(
  E                       num_positional_args=1,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E               )
  E               
  E               You can reproduce this example by temporarily adding @reproduce_failure('6.79.2', b'AXicY2RAAAAAGAAC') as a decorator on your test case

  ivy_tests/test_ivy/helpers/assertions.py:71: AssertionError
  ________________________________________________________ test_paddle_equal_all[cpu-ivy.functional.backends.paddle-False-False] ________________________________________________________

  frontend = 'paddle', on_device = 'cpu'

      @handle_frontend_method(
  >       class_tree=CLASS_TREE,
          init_tree="paddle.to_tensor",
          method_name="equal_all",
          dtypes_and_x=helpers.dtype_and_values(
              available_dtypes=helpers.get_dtypes("valid"),
              num_arrays=2,
              min_value=-np.inf,
              max_value=np.inf,
              shared_dtype=True,
              safety_factor_scale="log",
              small_abs_safety_factor=32,
          ),
      )

  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1856: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py:1878: in test_paddle_equal_all
      helpers.test_frontend_method(
  ivy_tests/test_ivy/helpers/function_testing.py:1542: in test_frontend_method
      value_test(
  ivy_tests/test_ivy/helpers/assertions.py:111: in value_test
      assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  values = [[array([ True])], [array(True)]], this_key_chain = None

      def assert_same_type_and_shape(values, this_key_chain=None):
          x_, y_ = values
          for x, y in zip(x_, y_):
              if isinstance(x, np.ndarray):
                  x_d = str(x.dtype).replace("longlong", "int64")
                  y_d = str(y.dtype).replace("longlong", "int64")
  >               assert (
                      x.shape == y.shape
                  ), "returned shape = {}, ground-truth returned shape = {}".format(
                      x.shape, y.shape
                  )
  E               AssertionError: returned shape = (1,), ground-truth returned shape = ()
  E               Falsifying example: test_paddle_equal_all(
  E                   frontend='paddle',
  E                   on_device='cpu',
  E                   dtypes_and_x=(['bool', 'bool'], [array(False), array(False)]),
  E                   method_flags=FrontendMethodTestFlags(
  E                       num_positional_args=0,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E                   frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.paddle' from '/workspaces/ivy/ivy/functional/frontends/paddle/__init__.py'>, framework_init_module=<module 'paddle' from '/opt/fw/paddle/paddle/__init__.py'>, init_name='to_tensor', method_name='equal_all'),
  E                   init_flags=FrontendMethodTestFlags(
  E                       num_positional_args=1,
  E                       as_variable=[False],
  E                       native_arrays=[False],
  E                   ),
  E               )
  E               
  E               You can reproduce this example by temporarily adding @reproduce_failure('6.79.2', b'AXicY2RAAAAAGAAC') as a decorator on your test case

  ivy_tests/test_ivy/helpers/assertions.py:71: AssertionError
  ================================================================================== warnings summary ===================================================================================
  ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py: 15 warnings
  /opt/fw/tensorflow/tensorflow/python/framework/ops.py:1059: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
      return int(self._numpy())

  -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
  =============================================================================== short test summary info ===============================================================================
  FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py::test_paddle_equal_all[cpu-ivy.functional.backends.numpy-False-False] - AssertionError: returned shape = (1,), ground-truth returned shape = ()
  FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py::test_paddle_equal_all[cpu-ivy.functional.backends.jax-False-False] - AssertionError: returned shape = (1,), ground-truth returned shape = ()
  FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py::test_paddle_equal_all[cpu-ivy.functional.backends.tensorflow-False-False] - AssertionError: returned shape = (1,), ground-truth returned shape = ()
  FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py::test_paddle_equal_all[cpu-ivy.functional.backends.torch-False-False] - AssertionError: returned shape = (1,), ground-truth returned shape = ()
  FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py::test_paddle_equal_all[cpu-ivy.functional.backends.paddle-False-False] - AssertionError: returned shape = (1,), ground-truth returned shape = ()
  =========================================================================== 5 failed, 15 warnings in 11.94s ===========================================================================
  ```
</details>

**Comment by MuhammadNizamani** [comment]
@KareemMAX  thanks for your log I will take a look under the hood.

**Comment by MuhammadNizamani** [comment]
@KareemMAX  Now I am getting same error, could you please test equal_all function in codespace here is command for it copy and paste it 
`python3 -m pytest -v -x ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_logic.py::test_paddle_equal_all`

if it failed tests than I will contact haris and I will ask him how should processed.

**Review by KareemMAX — APPROVED** [review]
Awesome work @MuhammadNizamani, to speed up the process I'll resolve my comment and merge right away.

**Pull request merged**
