### PR TITLE
logdet tensor.py

### PR DESCRIPTION
**Pull request by profgandhi**
close https://github.com/unifyai/ivy/issues/14666

### CODE REVIEW

**Comment by profgandhi** [comment]
close #14666

**Comment by Daniel4078** [comment]
I do not think that logdet(x) is the same as log(det(x)), please check this doc of torch:https://pytorch.org/docs/stable/generated/torch.logdet.html

**Comment by profgandhi** [comment]
In the example section we can see that they are performing A.det().log(), shouldn't it be same as log(det(x))?

**Comment by Daniel4078** [comment]
> In the example section we can see that they are performing A.det().log(), shouldn't it be same as log(det(x))?

>>> A = torch.randn(3, 3)
>>> torch.logdet(A)
tensor(-1.3430)
>>> A.det().log()
tensor([ 0.1815, -0.8917, -0.3031])

so torch.logdet(A) != A.det().log()

**Comment by profgandhi** [comment]
Both the A's are different, torch.randn(3,3) produces a 3x3 square matrix which then give a single result, but the A used in the second part is:
tensor([[[ 0.9254, -0.6213],
         [-0.5787,  1.6843]],

        [[ 0.3242, -0.9665],
         [ 0.4539, -0.0887]],

        [[ 1.1336, -0.4025],
         [-0.7089,  0.9032]]])

which is a array of 3 2x2 matrices which give 3 logdets for 3 different square matrices

**Comment by profgandhi** [comment]
so torch.logdet(A) == A.det().log() should be true only?

**Comment by ZiadAmerr** [comment]
Hey @profgandhi, thanks a lot for your contribution, are the tests passing? :)

**Comment by profgandhi** [comment]
Yea on github it shows tests as passing except the lint test,

The frontend tests also showed to be passing. I ran the test function 3 times, tests were passing 2 times but on the 3rd, 1 of the 2 test did not pass.

**Comment by ZiadAmerr** [comment]
Did you keep track of that error that didn't pass? If so, can you show it?

**Comment by profgandhi** [comment]
ret_np = array(-100.50634, dtype=float32), ret_from_gt_np = array(-100.48407, dtype=float32), rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'torch'
AssertionError:  the results from backend numpy and ground truth framework torch do not match
E            -100.50634002685547!=-100.48406982421875
Any suggestions on how I can fix this
The values are close but not equal
@ZiadAmerr

**Comment by ZiadAmerr** [comment]
> ret_np = array(-100.50634, dtype=float32), ret_from_gt_np = array(-100.48407, dtype=float32), rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'torch' AssertionError: the results from backend numpy and ground truth framework torch do not match E -100.50634002685547!=-100.48406982421875 Any suggestions on how I can fix this The values are close but not equal @ZiadAmerr

Yeah, just increase the values of `rtol` (relative tolerance) and `atol` (absolute tolerance, and it will work. But point is, it seems strange, 0.02 is not a small difference, looks like something underneath is being rounded when it shouldn't. Can you provide the whole test values? (i.e. the square matrix generated by `_get_dtype_and_square_matrix()` that raised that error) Maybe we can investigate that further, otherwise, LGTM, amazing work!

**Comment by profgandhi** [comment]
ret_np = array(-103.27893, dtype=float32), ret_from_gt_np = array(-103.97208, dtype=float32), rtol = 1e-05, atol = 1e-06, ground_truth_backend = 'torch'

dtype_and_x=(['float32'], array([[4.4452289e-16, 2.7105054e-20],
                       [2.6469780e-23, 1.6155871e-27]], dtype=float32)),

How to I set the rtol and atol values? @ZiadAmerr

**Comment by profgandhi** [comment]
@ZiadAmerr I have added atol and rtol, can we merge?

**Review by ZiadAmerr — CHANGES_REQUESTED** [review]
There is a problem with the tests, they are failing due to a syntax error related to a problem in the code you haven't edited, as you can see the previous function that tests `div_` is not actually complete, raising a syntax error in your first line of code. This problem should be resolved. I don't know whether you should be the one reviewing this or not, but I will get back to you as soon as possible. In the meantime, if you can resolve it yourself, feel free to do so and request another review from me :)

**Comment by profgandhi** [comment]
More tests are after I resolving conflict? I don't think they are related to my code? @ZiadAmerr

**Comment by ZiadAmerr** [comment]
> More tests are after I resolving conflict? I don't think they are related to my code? @ZiadAmerr

I think it is working fine now, but if there are merge conflicts, please resolve them and request a review and we will merge after that :)

**Comment by profgandhi** [comment]
@ZiadAmerr I have resolved the merge conflicts, please do a review

**Comment by ZiadAmerr** [comment]
Are the tests passing locally?

**Comment by profgandhi** [comment]
Yes, they are passing locally.

**Comment by ZiadAmerr** [comment]
I think I understand why the error is arising, looks like during he resolving of the merge conflicts, some parts of your code were deleted, but they still look the same although they were taken from the previous function, merging that will cause an error, can you please modify your function so that the Files Changed tab can have your whole implementation marked as additions (the plus sign) and not just parts of it? That's what's causing the problems.

**Comment by profgandhi** [comment]
I see what you are saying. I think I have fixed it now. @ZiadAmerr

**Comment by ZiadAmerr** [comment]
Looks like the tests are not passing, check out the error [here](https://github.com/unifyai/ivy/actions/runs/4901656572/jobs/8753058455?pr=14835#step:3:159)

```
E   AssertionError:  the results from backend tensorflow and ground truth framework torch do not match
E    -inf!=nan 
E   
E   
E   Falsifying example: test_torch_instance_logdet(
E       frontend='torch',
E       on_device='cpu',
E       dtype_and_x=(['float32'], array([[1.0000000e+00, 1.0000000e+00],
E               [4.7019774e-38, 3.5264831e-38]], dtype=float32)),
E       method_flags=FrontendMethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E       ),
E       init_flags=FrontendMethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E       ),
E       frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.torch' from '/ivy/ivy/functional/frontends/torch/__init__.py'>, framework_init_module=<module 'torch' from '/usr/local/lib/python3.8/dist-packages/torch/__init__.py'>, init_name='tensor', method_name='logdet'),
E   )
```

**Comment by profgandhi** [comment]
@ZiadAmerr All tests are passing now. Can we merge?

**Comment by ZiadAmerr** [comment]
The tests are not passing, I think you removed the tolerance keyword args in one of the last commits, can you revert back these changes?

**Comment by profgandhi** [comment]
But adding them back would lead to error -inf != number/nan  i think?

**Comment by ZiadAmerr** [comment]
Well, can you dive deeper into that and find out how each backend behaves? This could be a superset behavior problem we can tackle. I can talk about it with the team if we have a solid understanding of when each one happens.

**Comment by profgandhi** [comment]
@ZiadAmerr Are all the tests passing now?

**Comment by profgandhi** [comment]
@ZiadAmerr I think all tests are running now? Do tests rerun as they were are green before and then they were not?

**Comment by ZiadAmerr** [comment]
I just do a couple reruns before merging just to make sure that the tests are passing

**Comment by profgandhi** [comment]
@ZiadAmerr Can you please help me with these errors? These are not related to my function, why are they occuring?

**Comment by ZiadAmerr** [comment]
It's fine, as long as they are not related to your implementation. Since the tests are passing locally then we're set to go :)

**Comment by profgandhi** [comment]
Yea, the tests are passing locally, I am using this command to run tests locally pytest ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py::test_torch_instance_logdet

**Comment by ZiadAmerr** [comment]
LGTM, thanks a lot @profgandhi! :)

**Review by ZiadAmerr — APPROVED** [review]

**Pull request merged**
