### PR TITLE
Add single for jax frontend and test

### LINKED ISSUE #11524: single

### PR DESCRIPTION
**Pull request by xingyu-long**
Close #11524

### CODE REVIEW

**Comment by xingyu-long** [comment]
Hi @agniiyer, can you take a look for this PR? thanks a lot!

**Comment by xingyu-long** [comment]
Hi @agniiyer, can you take a look for this PR? I'd like to check-in as soon as possible. thanks!

**Comment by agniiyer** [comment]
Nicely done! :)

**Comment by agniiyer** [comment]
Co-authored-by: agniiyer <agni.iyer14@alumni.imperial.ac.uk>

**Pull request merged**
