### PR TITLE
stft

### LINKED ISSUE #26989: <stft>

### PR DESCRIPTION
**Pull request by muhammadhammad-tech**
Fixes #26989

# PR Description
Need help with the test function

## Related Issue

Closes #26989

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

Twitter: https://twitter.com/hammad98007

### CODE REVIEW

**Comment by aparajith21** [comment]
Hey, thanks for contributing! As mentioned by the bot in an earlier comment, please ensure that the PR title adheres to conventional commit standards. Further, fully populate the checklist (i.e. run the tests and confirm that they pass) so i know it is ready for review!

**Comment by muhammadhammad-tech** [comment]
@aparajith21 would be able to help me in tests cause i think i am doing but unable to point, do i need to implement stft layers.py according to paddle cause at the moment there some parameters that it do not accept. would appreciate your feedback thank you.

**Comment by Sarvesh-Kesharwani** [comment]
This issue belongs to this IssueBoard: #15049

**Comment by Sarvesh-Kesharwani** [comment]
> @aparajith21 would be able to help me in tests cases i think i am doing something wrong but unable to point, do i need to implement stft layers.py according to paddle cause at the moment there some parameters that it do not accept. would appreciate your feedback thank you.

Please try to fix this error:
image


and right now all the test cases are failing.
image

**Comment by Ishticode** [comment]
Closing this due to inactivity for over 2 months after changes were requested. Please feel free to reopen if you would like to continue work on this. Thank you  :)

**Pull request closed without merging**
