### PR TITLE
Reformat general inplace_increment #2813

### PR DESCRIPTION
**Pull request by edaehn**
Minor formatting fixes in  inplace_increment(), +examples. Thanks!

### CODE REVIEW

**Comment by ZoeCD** [comment]
Looks good! Thanks!

**Comment by edaehn** [comment]
Thanks, Zoe! Best regards, Elena

**Comment by edaehn** [comment]
Hi Zoe, it seems that some jobs are failing, for instance, lint and nightly tests. These are not related to the inplace_increment(). I find that also all the tests (in other PRs) run too slowly and some checks are not successful. Should we do any fixes? Please let me know. Thank you very much.
Best regards, Elena.

**Comment by edaehn** [comment]
Hi Zoe, The PR is not linked to the issue inplace_increment #2813, and the issue is not closed after the merge. Please advice. Thank you very much. Best regards, Elena

**Comment by edaehn** [comment]
closes #2813

**Pull request merged**
