### PR TITLE
frontend tensorflow.nn avgpool_2d

### PR DESCRIPTION
**Pull request by Steven-Foo**

### CODE REVIEW

**Comment by DragosStoican** [comment]
Hi @Steven-Foo 😀, could you add a link to the associated issue? Thanks! Then I can have a look as quick as possible 😁

**Comment by Steven-Foo** [comment]
Hi @DragosStoican I believe these two issues caused the test to fail in test_activation and test_liange in test_tensorflow. https://github.com/unifyai/ivy/issues/3153

**Comment by DragosStoican** [comment]
Sorry, I meant the issue you are looking to fix with this PR 😅I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

**Comment by DragosStoican** [comment]
It seems the CI pipeline encountered some errors and your test was executed :) If you update your fork you should be able to see the test result in the github action logs now 😁

**Comment by Steven-Foo** [comment]
Thanks a bunch, will check on it asap.

**Comment by DragosStoican** [comment]
Looking forward to it :) Best of luck!

**Comment by Steven-Foo** [comment]
@DragosStoican Hello there, I hope you're having a wonderful day. Could you please review my implementation of the Frontend API function? Thanks!

**Comment by DragosStoican** [comment]
Hi @Steven-Foo, unfortunately the tests are still failing. The test `test_tensorflow_avg_pool2d` needs to be passed before I can merge this PR

**Comment by Steven-Foo** [comment]
@DragosStoican Hi sir, I hope you are having a good day. Regarding the failing tests, I have corrected a few of them, however, one test is still failing, which is under the NumPy backend, whereas the trigger occurs at the Numpy experimental backend. So I'd like to know what I can do to move forward. Thanks in advance for the guidance.

**Comment by Steven-Foo** [comment]
@DragosStoican Hello, Could you please review my implementation of the Frontend API function again? Thanks!

**Comment by DragosStoican** [comment]
Hi @Steven-Foo , I am really sorry for the late reply as I haven't been notified of changes on your PR. It seems that test_tensorflow_avg_pool2d is still failing on all backends. I suggest you look at the logs [here](https://pipelines.actions.githubusercontent.com/serviceHosts/65e6b2a0-b7ba-4104-8cd3-f0c8d4a53050/_apis/pipelines/1/runs/492377/signedlogcontent/2?urlExpires=2022-12-12T07%3A23%3A27.8607606Z&urlSigningMethod=HMACV1&urlSignature=QXx8PmZuxob%2BmZjMQKMkFrFFoDSjU5OoB%2BTdbqe7SqU%3D) to understand what is going wrong with your implementation.

Right now it seems there is a "reference before assignment" error occurring in your _x_and_ksize. 
`2022-12-10T16:05:41.8930893Z >       return dtype, x, kernel, strides, padding, data_format`
`2022-12-10T16:05:41.8931132Z E       UnboundLocalError: local variable 'kernel' referenced before assignment`

Are you sure you need this function? Why are you not using _x_and_filters instead?

You can make sure the test passes and debug any errors locally, if you need help setting up your environment to run the test this link can help [setting up](https://lets-unify.ai/ivy/contributing/setting_up.html)

**Comment by Steven-Foo** [comment]
@DragosStoican  Hi, the reason I set up my own _x_and_ksize instead of _x_and_filter is that it causes arguments unmatched errors. For the testing, Ill take a look into it, thanks!

**Comment by Steven-Foo** [comment]
@DragosStoican Hi, I have **passed the test cases in my local environment for avg_pool2d**. However, this particular commit has a  “hypothesis.errors.FailedHealthCheck: Examples routinely exceeded the max allowable sizes” issue. May I have some insight on this particular issue? Thanks in advance. Would be extra grateful if this error can be fixed before the [git-push force]

**Comment by DragosStoican** [comment]
Hi @Steven-Foo, sorry but your test is still failing for me (due to an assertion error), and it should be passing in the CI before I can merge this branch. In addition, it seems that some of the changes you made to `_x_and_filters` is now causing other tests to fail. Please make sure your changes do not cause other tests to fail.

Regarding the error `hypothesis.errors.FailedHealthCheck`, I'd recommend asking about it in the discord channel, as that is the best place to get help.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
