### PR TITLE
added logictic function

### PR DESCRIPTION
**Pull request by Abrar-Mustakim**

### CODE REVIEW

**Comment by Oxbeefbabe** [comment]
Hi there @Abrar-Mustakim, are you an applicant for the Ivy Internship?

**Comment by Abrar-Mustakim** [comment]
> applicant

Yes. I am an application for ML engineer internship

**Comment by Oxbeefbabe** [comment]
Alright. We appreciate your enthusiasm for creating new tools for Ivy! however, for the time being, can you please choose a function to complete the function formatting task (as described here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#open-tasks) with. Please create a new PR with your changes when you are ready.

Thank you!

**Comment by djl11** [comment]
Will open again once we have our PR extension pipeline well defined, thanks a lot for the contribution!

**Pull request closed without merging**
