### PR TITLE
Frombufferlatest

### PR DESCRIPTION
**Pull request by Nanda198**
closes https://github.com/unifyai/ivy/issues/17643

### CODE REVIEW

**Comment by Nanda198** [comment]
i have mistakenly raised the pr from master branch and closed that pr when rebase the master branch. hence raised this new pr. it is aalready reviewed in  PR #17817

**Comment by hello-fri-end** [comment]
Hey @Nanda198 ! Thanks for opening this PR :) Since `frombuffer`  is a creation function it should go under `ivy/functional/frontends/jax/numpy/creation.py` and similarly, the test should be implemented in `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_creation.py`. Would you please update the PR with these changes? Feel free to request another review when you're done :)

**Comment by Nanda198** [comment]
hi @hello-fri-end Thanks for guiding me on this. hope i can push the changes in this PR . do i need to close this and create new PR?

**Comment by hello-fri-end** [comment]
> hi @hello-fri-end Thanks for guiding me on this. hope i can push the changes in this PR . do i need to close this and create new PR?

No need to close this PR - you can push the changes here itself 😊

**Comment by hello-fri-end** [comment]
> hi @hello-fri-end Thanks for guiding me on this. hope i can push the changes in this PR . do i need to close this and create new PR?

No need to close this PR - you can push the changes here itself 😊

**Comment by Nanda198** [comment]
@hello-fri-end  Thanks for your immediate response. i have moved from manipulation to creation file. let me know any other changes are needed.

**Comment by hello-fri-end** [comment]
> @hello-fri-end Thanks for your immediate response. i have moved from manipulation to creation file. let me know any other changes are needed.

LGTM! :rocket:

**Pull request merged**
