### PR TITLE
Issue #18991.Added tensorflow frontend general function make_ndArray

### LINKED ISSUE #18991: make_ndarray

### PR DESCRIPTION
**Pull request by janchilling**
close #18991

### CODE REVIEW

**Comment by janchilling** [comment]
@D0m-inic Would appreciate if I can get a reply. Thank you.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by janchilling** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

Already added.

**Comment by D0m-inic** [comment]
If you could also add a test for the raw_ops implementation you added in `test_raw_ops.py` 😃

**Comment by janchilling** [comment]
> If you could also add a test for the raw_ops implementation you added in `test_raw_ops.py` 😃

will do!

**Comment by D0m-inic** [comment]
😄

**Comment by janchilling** [comment]
@D0m-inic, mate can you give me a review for the last commit, and what are all these failing test?

**Comment by D0m-inic** [comment]
Hi, you should be using the `dtype_and_values` function in your test instead of the `dtype_values_axis` helper function as you dont need to draw an axis. As well as this, you need to adjust the parameters into dtype_and_values to make sure that only valid values are being passed into the function for the test (in this case, only arrays, not constants, should be taken in).

You should also add the `backend_to_test` parameter to your test.

**Pull request closed without merging**
