### PR TITLE
Added Cumsum Instance method to Jax NumPy Frontend

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Close #14953

**Comment by RakshitKumar04** [comment]
Hey, @Dsantra92 Please review my PR.

**Comment by Dsantra92** [comment]
Hi @RakshitKumar04, good work overall. But looks like some of the tests are failing, we can merge after the tests are passing. Don't mind the tests if they are failing because of other functions.

**Comment by RakshitKumar04** [comment]
Hey, @nathzi1505 I am facing this `Assertion error` in my implementation. Can you please guide me on how to resolve this.

```
E       AssertionError: the ground truth framework jax returned a int64 datatype while the backend paddle returned a uint8 datatype
E       Falsifying example: test_jax_devicearray_cumsum(
E           dtype_and_x=(['int64'], [array([0])], 0),
E           init_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           frontend_method_data=FrontendMethodData(ivy_init_module=<module 'ivy.functional.frontends.jax.numpy' from '/ivy/ivy/functional/frontends/jax/numpy/__init__.py'>, framework_init_module=<module 'jax.numpy' from '/usr/local/lib/python3.8/dist-packages/jax/numpy/__init__.py'>, init_name='array', method_name='cumsum'),
E           method_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           on_device='cpu',
E           frontend='jax',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.70.2', b'AXicY2BkQAUAACEAAg==') as a decorator on your test case
```

**Comment by RakshitKumar04** [comment]
Hey, @nathzi1505 I checked the frontend function `jax.numpy.cumsum` it too is showing the same error as above.
Please review the PR.

**Comment by RakshitKumar04** [comment]
Hey, @nathzi1505 please review my PR.

**Comment by RakshitKumar04** [comment]
Hey, @nathzi1505 please review my PR.

**Comment by nathzi1505** [comment]
Hi @ahmedo42, would you mind doing a review of this?

**Comment by RakshitKumar04** [comment]
Hey, @ahmedo42 please review my PR.

**Comment by RakshitKumar04** [comment]
.

**Pull request closed without merging**
