### PR TITLE
Implemented Extended Ivy Function API - AMAX

### LINKED ISSUE #20268: amax

### PR DESCRIPTION
**Pull request by RakshitKumar04**
Close #20268

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Hey, @Mr-Niraj-Kulkarni Please review my PR.

**Comment by Kibet-g** [comment]
import ivy

def amax(x):
  """Returns the maximum value in the input tensor."""
  if not isinstance(x, ivy.Array):
    raise TypeError("Input must be an Ivy Array.")
  if x.ndim == 0:
    return x[0]
  else:
    return ivy.amax(ivy.max(x, axis=-1))

if __name__ == "__main__":
  x = ivy.array([1, 2, 3, 4, 5])
  print(amax(x))

  y = ivy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  print(amax(y))

**Comment by RakshitKumar04** [comment]
> import ivy
> 
> def amax(x): """Returns the maximum value in the input tensor.""" if not isinstance(x, ivy.Array): raise TypeError("Input must be an Ivy Array.") if x.ndim == 0: return x[0] else: return ivy.amax(ivy.max(x, axis=-1))
> 
> if **name** == "**main**": x = ivy.array([1, 2, 3, 4, 5]) print(amax(x))
> 
> y = ivy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) print(amax(y))



Hii, @Kibet-g can you please offer more details regarding the code you're referring to?

**Comment by Mr-Niraj-Kulkarni** [comment]
Hey @RakshitKumar04, can you please resolve the lint errors?

**Comment by RakshitKumar04** [comment]
> Hey @RakshitKumar04, can you please resolve the lint errors?

Hey, @Mr-Niraj-Kulkarni  done with the lint error, please take a look.

**Comment by Mr-Niraj-Kulkarni** [comment]
Hey @RakshitKumar04 , I tried to test locally the tests are failing. Can you please look into that. Thanks

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
