### PR TITLE
added tf.zeros front end

### LINKED ISSUE #6951: zeros

### PR DESCRIPTION
**Pull request by AhmedMousa-ag**
This PR closes #6951

### CODE REVIEW

**Comment by AhmedMousa-ag** [comment]
@Aarsh2001 Hi, I was wondering about your review?

**Comment by Aarsh2001** [comment]
LGTM! Please fix the merge conflicts 🙂

**Comment by AhmedMousa-ag** [comment]
Hi @Aarsh2001, Thank you, it's fixed now, there's an error format to ivy core which I didn't touch, I think it's in the master branch

**Comment by AhmedMousa-ag** [comment]
Hi @Aarsh2001, is everything ok?

**Comment by Aarsh2001** [comment]
Apologies for the delayed response; looks good now. Thank you for your contribution!

**Pull request merged**
