### PR TITLE
Added array function and docstrings in creation.py

### PR DESCRIPTION
**Pull request by Ajay6601**
Close https://github.com/unifyai/ivy/issues/12315

### CODE REVIEW

**Comment by Ajay6601** [comment]
Is the PR ready to be merged

**Comment by kurshakuz** [comment]
Thank you for your contribution ! Could you create an issue for your PR, comment it to the corresponding To-Do list and link the issue to the PR as outlined in the Frontend APIs part of the [Open Tasks section](https://lets-unify.ai/ivy/contributing/open_tasks.html#open-tasks) in the docs ?

**Comment by Ajay6601** [comment]
> Thank you for your contribution ! Could you create an issue for your PR, comment it to the corresponding To-Do list and link the issue to the PR as outlined in the Frontend APIs part of the [Open Tasks section](https://lets-unify.ai/ivy/contributing/open_tasks.html#open-tasks) in the docs ?


Reformat array #12315

**Comment by Ajay6601** [comment]
Close #12315

**Review by kurshakuz — CHANGES_REQUESTED** [review]
There seems to be too much unnecessary changes. Please resolve that and let me know once you are done. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
