### PR TITLE
add jax.numpy.cov to jax frontend

### LINKED ISSUE #17025: cov

### PR DESCRIPTION
**Pull request by mohame54**
close #17025

### CODE REVIEW

**Comment by mohame54** [comment]
close  #17025

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by mohame54** [comment]
@MuhammadSaeedBatikh  I am ready for the review

**Comment by MuhammadSaeedBatikh** [comment]
Hi @mohame54, 
Done reviewing, lgtm. Thanks for the PR.

**Pull request merged**
