### PR TITLE
Reformat searching #757: argmax #1745 open task

### PR DESCRIPTION
**Pull request by tariqsu**
Reformat searching #757: argmax #1745 open task

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @tariqsu Thanks for the PR.
Could you kindly only reformat the specified function in the already created files. We will not be needing new files for it. Please follow the [contributors](https://lets-unify.ai/ivy/contributing.html) guide and feel free to ask anything. Once you think you have reformatted correctly please request a review from me 😊

**Comment by tariqsu** [comment]
> Hi @tariqsu Thanks for the PR. Could you kindly only reformat the specified function in the already created files. We will not be needing new files for it. Please follow the [contributors](https://lets-unify.ai/ivy/contributing.html) guide and feel free to ask anything. Once you think you have reformatted correctly please request a review from me 😊

Just fixed that issue regarding the files. Thanks!

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @tariqsu 
There are several things to note. 
There should be no new files created. There is still ivy/searching.py created with functions copied over from functional/ivy where they should remain.
No functions besides argmax should be reformatted.
Please implement the static or instance methods inside the container and array classes accurately with the correct arguments and decorators. The details can be found on the [deep dive page](https://lets-unify.ai/ivy/deep_dive.html) under Array and Container subheadings.
Please kindly take a look and feel free to ask any questions based on that. When the corrections are made  please ask for my review. Thank you very much 😊

**Comment by Ishticode** [comment]
This PR will be closed in 24 hours due to inactivity. Please refer to the changes requested above, update and clarify if you would like to continue working. Thankyou.

**Pull request closed without merging**
