### PR TITLE
Add count_nonzero extension

### LINKED ISSUE #6284: count_nonzero

### PR DESCRIPTION
**Pull request by raghuveerbhat**
Close #6284

### CODE REVIEW

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi, could you fix the merge conflicts first? With that I will be able to see whether tests are failing in the CI or not. Thanks!

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi, I just made the CI run on the functions you wrote. Meanwhile can you resolve the merge conflicts? I will keep your PR in the top of my list so I can review this quicker and this doesn't happen again. Thanks!

**Comment by raghuveerbhat** [comment]
Hi @MarShaikh , thank you for keeping my PR on priority :). I've resolved merge conflicts now. Please let me know if any other changes are required.

**Review by MarShaikh — APPROVED** [review]
LGTM! Thanks for contributing! 🌟

**Pull request merged**
