### PR TITLE
Partially Completed prod, help needed

### PR DESCRIPTION
**Pull request by Volthai7us**
Jax

Test Passed: 27, Ignored 69 of 96 tests

Torch

Test Failed: 12, passed: 42, Ignored 42 of 96 tests

Tensorflow

Test Failed: 36, passed: 36, Ignored 24 of 96 tests

the Error message in all of the failed tests:
>       return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
E       AttributeError: 'function' object has no attribute 'reduce'

Numpy

Test Failed: 33, passed: 33, Ignored 30 of 96 tests

the Error message in all of the failed tests:
>       return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
E       AttributeError: 'function' object has no attribute 'reduce'

Mxnet

Test Failed: 42, Ignored 54 of 96 tests

What can I do for 'reduce' error?

### CODE REVIEW

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by Volthai7us** [comment]
> Thanks a lot for the PR!
> 
> I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

I directly added you as contributer on my fork.

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

For resolving conflicts with upstream, I have created this [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG) on the entire process of making a PR, including how best to keep this aligned with upstream.

**Review by djl11 — CHANGES_REQUESTED** [review]
Please reformat the code as describe in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/), and also as explained in this [YouTube series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl).

**Comment by 1Doomdie1** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
