### PR TITLE
added fill_diagonal to ivy experimental api

### LINKED ISSUE #12174: fill_diagonal

### PR DESCRIPTION
**Pull request by Giac3**
Close #12174

### CODE REVIEW

**Comment by Infrared1029** [comment]
Thanks for the contribution @Giac3! can you resolve the conflicts so I can take a look? thanks!

**Comment by Infrared1029** [comment]
hey @Giac3, the `.idea` folder changes should not be committed, can we get that fixed?

**Comment by Giac3** [comment]
@Infrared1029 hmmm strange I don't see why they are included I will fix that today thank you.

**Comment by Infrared1029** [comment]
Hey @Giac3, the test seems to be failing, can you make sure the tests are passing so i can take a closer look?

**Pull request closed without merging**
