### PR TITLE
Resize

### PR DESCRIPTION
**Pull request by shireenchand**
Numpy frontend and test for resize

### CODE REVIEW

**Comment by shireenchand** [comment]
Hi @V-G-spec can you please review this PR. Thanks!

**Comment by V-G-spec** [comment]
Hi @shireenchand. Can you look at contributing guide once for the "close" comment and the failing tests? It is quite likely that the issue is the same as your last PR, but I'd rather you be double sure
Thanks!

**Comment by shireenchand** [comment]
Close #10679

**Comment by shireenchand** [comment]
Closing this as someone already made this frontend function due to the delay in merging this pr

**Pull request closed without merging**
