### PR TITLE
sqrt torch front end was implemented

### LINKED ISSUE #7269: sqrt

### PR DESCRIPTION
**Pull request by artykov1511**
Close #7269

### CODE REVIEW

**Comment by ogbanugot** [comment]
Hey @artykov1511 great job on the contribution! However, can you please add a test for the method, you can check how tests were written for the other existing methods, thanks.

**Comment by ogbanugot** [comment]
Also, can you modify the comment with the issue number to `Close <issue_number>`, so that the issue is closed once we get the PR merged? Thanks.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
