### PR TITLE
First PR for element-wise array (divide func)

### PR DESCRIPTION
**Pull request by PatChizzy**
I'm pretty sure everything is fine, but i need code reveiw for the following;

1. unit test for abs passes for numpy and torch. However, i get some interesing errors for jax and tensorflow.

for jax == RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.

for tensorflow == Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

2. unit test for my own function (elementwise array for divide) fails for numpy with the error below.

for numpy == TypeError: array() got an unexpected keyword argument 'copy'

for torch == 4 out of 5 test fail and i cant make out the error messages yet. Excited that one passed!

for tensorflow == same as above for abs func

for jax ==  same as above for abs func

### CODE REVIEW

**Comment by 1Doomdie1** [comment]
Hey thank you for contributing.
Are you using the docker container to run the tests or locally on your machine? If you are running the tests locally make sure you have the right versions of each module. You have them in the main ivy folder requirements.txt and optional.txt

**Review by 1Doomdie1 — COMMENTED** [review]
Hey thank you for contributing.
Are you using the docker container to run the tests or locally on your machine? If you are running the tests locally make sure you have the right versions of each module. You have them in the main ivy folder requirements.txt and optional.txt.

Also could you uncomment divide in this file please?
https://github.com/PatChizzy/ivy/blob/master/ivy_tests/array_api_methods_to_test/elementwise_functions.txt
This will add it to the tests.

And please resolve the conflicts in your branch :)

**Comment by PatChizzy** [comment]
Yes, i'm using the latest docker container to run tests.
At this point, i dont know what else to do.

**Review by djl11 — CHANGES_REQUESTED** [review]
First of all, it will be easier for me to give support if the diffs were cleaned up a bit. Could you please remove the changes inside .idea folder, remove all the re-formatting changes, and also remove the new jax submodule you've added? Once the diff is purely changes related to the divide method, I can dive into these issues a bit more :)

**Comment by PatChizzy** [comment]
Hi Dan, this branch has some issue and i think its because of the Jax module i was trying to build from source, due to the errors i got during run. However, i've created a new PR in a new branch. #480

**Pull request closed without merging**
