### PR TITLE
fixed the " ModuleNotFoundError" and also the refactored the test_elu for the ELU class, to show the tests now run

### LINKED ISSUE #28136: Getting the stateful tests up and running
Trying to run the stateful tests throws an error, e.g. running the tests for `ivy_tests/test_ivy/test_stateful/test_activations.py::test_elu` throws an error 
```
E           ModuleNotFoundError: No module named ‘ELU'
```
This is the same across all other stateful tests. The goal of this task is to fix this error so that all stateful tests run successfully without error unless there’s a genuine test failure

### PR DESCRIPTION
**Pull request by mosesdaudu001**
# PR Description

The purpose of the PR is to get the stateful test up and running. I was able to do that but I noticed that for ELU, the alpha was passed as a keyword argument was not positioned correctly, which was why I changed the position. I do not think we need to pass in the `method_num_positional_args` for each test, as it is already generated correctly in the `handle_method` function. Except there is another reason I may not know. I do not think we should be adding it for every test case.

## Related Issue

close #28136

### CODE REVIEW

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
Hey @mosesdaudu001, thanks for making the changes to `test_elu`, could you please do the same changes for the other stateful tests as well? Seems like quite a lot of them are [failing](https://github.com/unifyai/ivy/actions/runs/7846294202/job/21414190094?pr=28162#step:4:45) due to the same reason. Thanks 😄

**Comment by NripeshN** [comment]
Hey @mosesdaudu001,
Is this PR being worked upon?

**Comment by mosesdaudu001** [comment]
Really sorry about the hold up. Recently circumstances have made me unavailable. I should have completed the task, but I’ve not really had the time. My bad 😥 @vedpatwardhan 

if @soma2000-lang still wants it. I’m happy to drop it for him. Sorry about the hold up mate 😅

**Comment by soma2000-lang** [comment]
> Really sorry about the hold up. Recently circumstances have made me unavailable. I should have completed the task, but I’ve not really had the time. My bad 😥 @vedpatwardhan
> 
> if @soma2000-lang still wants it. I’m happy to drop it for him. Sorry about the hold up mate 😅

I can take it up

**Pull request closed without merging**
