### PR TITLE
dirichlet extension

### PR DESCRIPTION
**Pull request by nassimberrada**

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
I guess this should be in  ivy's `random` submodule. What do you think?
`NativeArray` examples are to be omitted. `Container` examples to be moved to container methods and array instance examples to be moved to the equivalent array instance method. Please feel free to tag me if this does not make sense. Thanks 🙂

**Comment by nassimberrada** [comment]
**Error** Same issue than torch.cross

**Comment by nassimberrada** [comment]
@Ishticode I got a question for this function, which i guess is valid for all distribution functions. Given that the function is intended to randomly draw values given the underlying distribution, doesn't that mean that you will necessarily get different values when the test runs the same inputs on two back-ends, even if the function is correctly implemented in both ?

**Review by Ishticode — COMMENTED** [review]
I don't think so that should be an issue... Maybe taking a look at the tests for random generating functions would be englightening.

If you get it fixed feel free to migrate and merge.

**Pull request closed without merging**
