### PR TITLE
unsorted_segment_sum

### LINKED ISSUE #14576: unsorted_segment_sum
Math functions for TensorFlow frontend

### PR DESCRIPTION
**Pull request by a00ayad00**
Close #14576

### CODE REVIEW

**Comment by a00ayad00** [comment]
Is there any review, please ??

**Comment by zaeemansari70** [comment]
Hi @a00ayad00!
Thanks for contributing to Ivy! :slightly_smiling_face: 

I was about to review your PR, is there a specific reason because of which you closed it? :slightly_smiling_face: 

I also cannot see any implementation in the test files.

**Comment by a00ayad00** [comment]
Hi zaeem,
I waited you a lot of time and I thought you won't reviwe it, and the contract on Upwork will expire soon.
For the test function, I didn't know what is that, but now I know 😄.

**Comment by zaeemansari70** [comment]
Actually the time to expect a review a for a PR varies between 1-5 days at max :slightly_smiling_face: 
I unfortunately cannot reopen your PR as the reopen option is unavailable now due to some reason, feel free to make a new PR.

Thanks! :slightly_smiling_face:

**Pull request closed without merging**
