### PR TITLE
feat: Fmax updated

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
#20123

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by jaskiratsingh2000** [comment]
@KareemMAX Can you please review it once?

**Comment by jaskiratsingh2000** [comment]
@KareemMAX would appreciate your response

**Comment by jaskiratsingh2000** [comment]
@KareemMAX Please look into and help me review this PR as all the test cases passes for it.

**Review by NripeshN — APPROVED** [review]

**Comment by NripeshN** [comment]
LGTM!

**Pull request merged**
