### PR TITLE
added paddle.nanmean and tests for it

### LINKED ISSUE #22885: nanmean

### PR DESCRIPTION
**Pull request by sabre-code**
# PR Description 

Added paddle.nanmean function and test for it. Passed all tests for all backends.

## Related Issue 

Close  #22885

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by sabre-code** [comment]
@AlexandraPosta Hello can you please review the code and let me know if there are any changes required. Passed all backend tests.

**Comment by AlexandraPosta** [comment]
Hello @sabre-code! Your contribution is very much appreciated :). 

The first thing would be to reference the issue properly. Please check [our documentation](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) and change the comment that you left [here](https://github.com/unifyai/ivy/issues/15039). Currently, in the task list, your function is not referenced as open, so a different contributor can take it over.

Then, can you resolve your conflicts?

**Comment by sabre-code** [comment]
> Hello @sabre-code! Your contribution is very much appreciated :). 
> 
> The first thing would be to reference the issue properly. Please check [our documentation](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) and change the comment that you left [here](https://github.com/unifyai/ivy/issues/15039). Currently, in the task list, your function is not referenced as open, so a different contributor can take it over.
> 
> Then, can you resolve your conflicts?  

Thanks for referencing this PR on the issue list. I will work on resolving conflicts. :)

**Comment by sabre-code** [comment]
@AlexandraPosta I have resolved the conflicts. :)

**Pull request closed without merging**
