### PR TITLE
8391 - eig in torch linalg frontend

### PR DESCRIPTION
**Pull request by giannisginis**

### CODE REVIEW

**Comment by giannisginis** [comment]
Close #8391

**Comment by giannisginis** [comment]
Failed tests dont seem to be related to this PR! So, it is ready for review :) .

**Comment by aditya-pola** [comment]
Hi @giannisginis, this looks great! I just have to find out whether tests are allowed to have useful comments. I'll let you know once I find out and I can then merge the PR!

**Comment by aditya-pola** [comment]
I think it would be best to remove the comments in the test. Let me know once you've done that. I can merge the PR then :)

**Comment by giannisginis** [comment]
Hi @aditya-pola ! thanks for the suggestion! I removed the comments in test and resolved the conflicts with master :)

**Comment by aditya-pola** [comment]
The changes don't seem to be reflected in the PR. Could you make sure that you pushed the changes?

**Comment by giannisginis** [comment]
> The changes don't seem to be reflected in the PR. Could you make sure that you pushed the changes?

@aditya-pola i removed the comments in this commit https://github.com/unifyai/ivy/pull/8524/commits/9a1d51c1ddc636051aa9b44bc969382a20338b45#.  You dont see the changes?

**Comment by aditya-pola** [comment]
That's odd. I didn't see the changes earlier. I do see them now. Merging!

**Comment by giannisginis** [comment]
Thanks for the review @aditya-pola :)!

**Pull request merged**
