### PR TITLE
Added 'scan' to tensorflow frontend

### LINKED ISSUE #14675: scan

### PR DESCRIPTION
**Pull request by AbdullahSabry**
Closes #14675 

Hello, 

I'm trying to create the frontend for the function 'scan' tensorflow. The test keeps on failing and I'm not sure what's the probelm. Check this out and tell me what to change. 

Thanks!

### CODE REVIEW

**Comment by AbdullahSabry** [comment]
Hey @CatB1t 

In the file "function_testing.py" I had a conflict with the keyword argument 'fn' with the 'fn' in 'tf.scan'. Is it okay to rename the argument to '_fn' instead of 'fn'?

This change seems to not break any other use of the function since it's a positional argument, and it makes tests compatible to run since conflicting keywork arguments seem to be causing issues in testing. Please review this and tell me what you think.

Thanks!

**Review by CatB1t — COMMENTED** [review]
Hello @AbdullahSabry, thanks for flagging the issue with `get_frontend_ret`, I've pushed a fix to master for this one, sync your branch with Ivy's master branch and everything should be working fine! Thanks.

**Comment by AbdullahSabry** [comment]
Hey @theRealBird @ivy-leaves @ivy-seed 

PR is ready for merge; it passed all the tests after the last commit! 

Please check it out and thank you

**Comment by AbdullahSabry** [comment]
Hey @CatB1t 

Sorry to bring you into this again but can you review this PR? The pull request hasn't gotten much activity in days, but I believe it's ready to merge

Thank you for your time

**Comment by AbdullahSabry** [comment]
Hey @theRealBird, Sorry for causing a havoc over here :D 

As for the linter tests, checking out the log file revealed that it failed on the formatting of parameters in `helpers.dtype_and_values` which it wants to just flatten the input parameters. Even fixing that and flattening it, it seems to be failing on other files outside the scope of the PR. However I removed the extra new line in 1868 as you requested. 

Is it expected that I reformat the code for the other files failing the test? Let me know if I need to do that.

Apologies for everything and thank you for your understanding

**Comment by theRealBird** [comment]
Hey @AbdullahSabry,

Thanks for making the requested changes. Don't worry, you need not worry about code which you did not write.
Are you sure ``` ivy.associative_scan(elems, fn, reverse=reverse)``` has been implemented already in Ivy's functional API and exists?

**Comment by AbdullahSabry** [comment]
Hey @theRealBird 

Yes, it is fully implemented in the experimental API. I tried a couple of dummy runs with the examples in tensorflow docs to verify that it outputs clean results and it does.

The full implimentation can be found in `ivy/functional/ivy/experimental/manipulation.py` from line 1793.

**Comment by theRealBird** [comment]
Hey @AbdullahSabry,

Ah I see, it was implemented recently. Everything looks good to me! Great work and thank you for your patience. 😃

**Pull request merged**
