### PR TITLE
fix clip_vector_norm

### LINKED ISSUE #10255: clip_vector_norm

### PR DESCRIPTION
**Pull request by sudarshbuxyyes**
Close #10255

### CODE REVIEW

**Comment by guillesanbri** [comment]
Hi! Thank you for the contribution! As this is a formatting task, please, follow the steps here https://lets-unify.ai/ivy/contributing/open_tasks.html#formatting-checklist :slightly_smiling_face: Thanks!

**Comment by sudarshbuxyyes** [comment]
add_reformatting_checklist_general

**Comment by guillesanbri** [comment]
now that the comment is there, you should go over each item, modifying the comment accordingly and completing the checklist. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
