### PR TITLE
Add frontends.torch flip, fliplr, flipud

### PR DESCRIPTION
**Pull request by PatternFinder**
* Add flip, fliplr, flipud to frontends.torch.other_operations

* Add fliplr, flipud to backends.torch.manipulation

* Add test_flip, test_fliplr, test_flipud to test_ivy.frontends.torch.test_other_operations

link to issue: #2647

### CODE REVIEW

**Comment by PatternFinder** [comment]
@saeedashrraf Hi, could you take a look at this PR and let me know if this is the correct way going forward? Thanks.

**Comment by saeedashrraf** [comment]
Hello @PatternFinder, thank you for your effort! you need to create a separate issue for each of the functions you are working on instead of one issue for all 3 functions to get assigned the functions correctly. So, instead of only one issue #2647, there should be 3 issues, one for each function.

In addition to that, can you implement fliplr and flipud in the rest of the backends just like you did for torch?

**Comment by PatternFinder** [comment]
> Hello @PatternFinder, thank you for your effort! you need to create a separate issue for each of the functions you are working on instead of one issue for all 3 functions to get assigned the functions correctly. So, instead of only one issue #2647, there should be 3 issues, one for each function.
> 
> In addition to that, can you implement fliplr and flipud in the rest of the backends just like you did for torch?

got it, first I'll close these group by alias PRs, file them separately, then look at implementing the other backends

**Comment by PatternFinder** [comment]
closing to file each function separately

**Pull request closed without merging**
