### PR TITLE
Fixed Einops_Rearrange in general.py

### LINKED ISSUE #3842: einops_rearrange

### PR DESCRIPTION
**Pull request by hrasul**
resolves #3842 

- Changed doctrings.
- Added examples for einops rearrange using ivy

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
If you look at the `test-docstrings` and scroll up, you can see the list of failing docstring examples, one of which is `einops_rearrange`. So at least one of your examples must be failing, can you fix this 🙂

**Comment by hrasul** [comment]
> If you look at the `test-docstrings` and scroll up, you can see the list of failing docstring examples, one of which is `einops_rearrange`. So at least one of your examples must be failing, can you fix this 🙂
I just fixed it can you take a look again!! Cheers!!

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
this function is still appearing in the list of failing `test-docstrings`

**Comment by hrasul** [comment]
> this function is still appearing in the list of failing `test-docstrings`

I just made some more changes, I took a look it isn't there anymore.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Great thanks 🙂 Part of the task is to also add examples to the container and array instance methods for `einops_rearrange`. Also you have added 5 examples here, but they're all basically doing the same thing, so maybe 2 would suffice. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
