### PR TITLE
Added Resolve_neg.py

### LINKED ISSUE #19543: resolve_neg

### PR DESCRIPTION
**Pull request by 00umar**
Close #19543

### CODE REVIEW

**Comment by MuhammadSaeedBatikh** [comment]
Hi @00umar, please make sure that your first comment reference the issue this PR closes. [See the guideline ](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#pull-requests).

**Comment by 00umar** [comment]
close #19873

**Comment by 00umar** [comment]
Close #19873

**Comment by 00umar** [comment]
Closed.

**Comment by MuhammadSaeedBatikh** [comment]
Hi @00umar, please make it your first comment. This way your issue will be closed automatically after a successful merge.

**Comment by 00umar** [comment]
Ok, I will do that.

**Comment by 00umar** [comment]
Done, I will be waiting for your feedback.

**Comment by MuhammadSaeedBatikh** [comment]
Hi @00umar, sorry for the late response.
This PR deviates a great deal from what it should look like. Here are some tips:
1. `resolve_neg` is a torch frontend function. It should be placed in `ivy/functional/frontends/torch/tensor.py`.
2. You shouldn't create new files. 
3. all frontend functions must be implemented as backend-agnostic Ivy functions. This line is wrong `if not isinstance(tensor, torch.Tensor):`
4. All frontend functions must follow the signature of the [original function](https://pytorch.org/docs/stable/generated/torch.resolve_neg.html#torch.resolve_neg). This includes variables names.
5. You have to implement corresponding test function for `resolve_neg`. This function should be placed in `ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py` and named `test_torch_tensor_property_resolve_neg`.
Due to all of the aforementioned missing checks, this PR will be closed. Please read the following guides carefully before starting a new one. [Frontend API](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis), [Frontend guide](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#ivy-frontends), [Ivy Frontend tests](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#ivy-frontend-tests).

**Comment by 00umar** [comment]
Thanks, i will start it over again.

**Comment by 00umar** [comment]
can i make another PR after the corrections?

**Comment by MuhammadSaeedBatikh** [comment]
yes

**Pull request closed without merging**
