### PR TITLE
Reformat general

### PR DESCRIPTION
**Pull request by viktoriadorjan1**

### CODE REVIEW

**Comment by aditya-hari** [comment]
Hey, thanks for the contribution. Can you please link the issue that this is for?

**Comment by viktoriadorjan1** [comment]
> Hey, thanks for the contribution. Can you please link the issue that this is for?

This is for "Reformat general / "get_all_arrays_in_memory"
and "Reformat general / num_arrays_in_memory"

**Comment by aditya-hari** [comment]
You need to create an issue for the subtask you're addressing first, and then link this PR with that. Please refer to the [contributing guide](https://lets-unify.ai/ivy/contributing/the_basics.html#the-basics) for the process.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
