### PR TITLE
Add reciprocal function and test to numpy frontend

### PR DESCRIPTION
**Pull request by PavanNeerudu**
This is the associated [issue](https://github.com/unifyai/ivy/issues/6778 )

### CODE REVIEW

**Comment by aditya-pola** [comment]
Hey @PavanNeerudu 🙂, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

**Comment by PavanNeerudu** [comment]
Hey @aditya-pola Can you take a look at this? The tests for the function reciprocal were running fine in my machine. I even changed the function related to floor_divide as its test was failing.

**Comment by aditya-pola** [comment]
Run the pre-commit hooks to fix the linting issues. You may have to manually fix some of the errors flagged. Find more information [here](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit).
The failing numpy frontend tests are for different functions and you can disregard them. I've also run the test on my machine and they seem to pass.
Thank you for fixing floor_divide, those were required changes!

**Comment by PavanNeerudu** [comment]
I am not able to install brew which is needed to install pre-commit in my linux system. Is there any workaround to fix the lint issues?

**Comment by aditya-pola** [comment]
Brew is the package manager for macOS. Please follow the instructions specified in the Pre-commit section, the other sections are for setting up a work environment. I am assuming you are using a virtual environment in linux. You can just use pip to get pre-commit as explained in the link.

**Comment by PavanNeerudu** [comment]
Thanks @aditya-pola for the help. Is the PR now good?

**Comment by aditya-pola** [comment]
This looks good to me! Merging

**Pull request merged**
