### PR TITLE
feat: added fromstring function #26661

### LINKED ISSUE #26661: fromstring

### PR DESCRIPTION
**Pull request by Coleman97**
Fixes #26661

# PR Description

Implemented the fromstring function to Jax frontend.

## Related Issue 

Close 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Coleman97** [comment]
@ivy-leaves @aparajith21 is everything okay with the pull request and can it be merged?

**Comment by aparajith21** [comment]
Hey, thanks for contributing! Please add tests for every function you add, you will find a detailed explanation for how to do this in the contributors guide. Once that's done, please request review again!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ishticode** [comment]
Closing this due to inactivity for over 6 months after addition of tests were requested for over 6 months. Please feel free to reopen if you would like to continue working on this. Thank you :)

**Pull request closed without merging**
