### PR TITLE
greater_equal adhering to Array API standard

### PR DESCRIPTION
**Pull request by thecoder12**

### CODE REVIEW

**Review by djl11 — CHANGES_REQUESTED** [review]
Please replace args x, y with x1, x2 as per the names used in the standard :)

**Comment by 1Doomdie1** [comment]
Hey thecoder12, thank you for contributing!
Next time after you made the changes requested by a ivy team member please request a "Code Review".
I've requested one for you now but please keep this in mind!
If you fail to do so the PR will remain unchecked and will be closed automatically!

**Review by djl11 — APPROVED** [review]
Looks good to me, just pending the tests passing.

**Comment by thecoder12** [comment]
@djl11 - Would I need to rebase the master, resolve conflicts and then again create PR?

**Comment by mattbarrett98** [comment]
Thanks for contributing!

**Pull request merged**
