### PR TITLE
Trace in instance methods ndarray as well as tests

### LINKED ISSUE #15751: Trace
front end numpy for trace.

### PR DESCRIPTION
**Pull request by bahbah94**
Close #15751

### CODE REVIEW

**Comment by bahbah94** [comment]
@MuhammadSaeedBatikh Please check my PR. Thanks

**Comment by MuhammadSaeedBatikh** [comment]
Hi @bahbah94, thanks for the PR.
looks good, however, the tests seem to be quite limited: 
```
   ...
    offset=st.integers(min_value=0, max_value=0),
    axis1=st.integers(min_value=0, max_value=0),
    axis2=st.integers(min_value=1, max_value=1),
   ...
``` 
`axis1` and `axis2` are restricted to 0 and 1 and `offset` is set to 0.
You may try with more appropriate helpers functions such as `dtype_values_and_axes` instead of `dtype_and_values`, which returns appropriate  `dtype`, `x`, `axis1`, `axis2`.

**Comment by bahbah94** [comment]
@MuhammadSaeedBatikh Thank you for the review. I have made some updates based on your review.

**Comment by MuhammadSaeedBatikh** [comment]
Hi @bahbah94, please notice that the `abs(offset)` should be less than or equal to `x.shape[axis2]`. Notice that `offset` indicates whether the diagonal is in the direction of the lower or upper triangular portion of the matrix.
Additionally, there are still some failing cases. There's an assertion error for torch and Jax backends:
`AssertionError: returned dtype = int64, ground-truth returned dtype = uint64`
You can ignore the paddle exception.
You should also remove all unnecessary comments such as unused code.

**Comment by bahbah94** [comment]
@MuhammadSaeedBatikh Thanks for the feedback. Im still working on fixing this. If the test for dtype works for numpy and ternsorflow, then it would be an issue of the backend implementation of jax and torch? for the dtype assertion error?

Also, im not sure for offset, what should be added should i extract the dtype,x and axis from the arguments directly. For example: 
@handle_frontend_method(
    class_tree=CLASS_TREE,
    init_tree="numpy.array",
    method_name="trace",
    dtype_x_and_axes=dtype_values_and_axes(),
    dtype, x , axis1 , axi2 = dtype_x_and_axes,
    offset=st.integers(min_value=0, max_value=x.shape[axis2]),

or should i write :

@handle_frontend_method(
    class_tree=CLASS_TREE,
    init_tree="numpy.array",
    method_name="trace",
    dtype_x_and_axes=dtype_values_and_axes(),
    offset=st.integers(min_value=0, max_value=dtype_x_and_axes[1].shape[dtype_x_and_axes[3]]),

May you please help with these questions? 

)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
