### PR TITLE
added add_n function

### LINKED ISSUE #11548: add_n
Implementing add_n functionality for TensorFlow frontend.

### PR DESCRIPTION
**Pull request by SethiAbhinav**
Closes #11548

### CODE REVIEW

**Comment by SethiAbhinav** [comment]
@Aarsh2001 please review the PR. Thanks!

**Comment by SethiAbhinav** [comment]
@WilliamHirst could you please take a look at this PR.

**Comment by WilliamHirst** [comment]
Hi,
Thanks for making a contribution!

It seems like the function you have added is just an alias of AddN in the raw_ops file. If so, it should instead be implemented as described here:

https://github.com/unifyai/ivy/issues/1545

**Comment by SethiAbhinav** [comment]
Right @WilliamHirst , I had done that earlier and @Aarsh2001 closed that PR and I completely forgot while remaking the PR. Thanks for letting me know! 

The changes are made. Please review it. Thanks!

**Pull request merged**
