### PR TITLE
adjoint_function

### PR DESCRIPTION
**Pull request by rannynayyar67**

### CODE REVIEW

**Comment by abdrahmandiab** [comment]
Hi @rannynayyar67 , could you please indicate what issue this PR is addressing?

**Comment by rannynayyar67** [comment]
hi @abdrahmandiab ,
This is to-do list issue - [Add Linear Algebra functions for TensorFlow frontend #1546](https://github.com/unifyai/ivy/issues/1546)
adjoint function of Tensorflow frontend

**Comment by abdrahmandiab** [comment]
> hi @abdrahmandiab , This is to-do list issue - [Add Linear Algebra functions for TensorFlow frontend #1546](https://github.com/unifyai/ivy/issues/1546) adjoint function of Tensorflow frontend

ah, I see! In that case, I'd recommend going through [the frontend tasks docs](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis) for better instructions on how to implement this functionality such that it follows our guidelines and formatting, as well where within the file structure this function should be implemented, since we don't use python notebooks.😅

Thanks!

**Comment by rannynayyar67** [comment]
@abdrahmandiab 
Ok 
will make the changes accordingly before tomorrow. 
thanks for the feedback.

**Comment by rannynayyar67** [comment]
#3981

**Comment by rannynayyar67** [comment]
#3983

**Comment by rannynayyar67** [comment]
@abdrahmandiab 
Made the changes in the new PR
#3983
Please Do let me know the reviews

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab Made the changes in the new PR #3983 Please Do let me know the reviews

Hi @rannynayyar67 , it seems there's been someone else assigned to that other PR and they're in the process of reviewing it with you so I'll leave you guys to it. Please do let me know if you need any extra assistance, but for now I'll be closing this PR. :)

Thanks!

**Pull request closed without merging**
