### PR TITLE
fix: Fixed passing of `ceil_mode` key-word argument in `ivy.avg_pool2d()` function call

### LINKED ISSUE #27851: Unexpected keyword argument `pad_mode` in function call `ivy.avg_pool2d()`
In the following function call, the key-word argument `pad_mode` is used,
https://github.com/unifyai/ivy/blob/207dec0cee120a5898749d7b3f7b984341fff313/ivy/functional/frontends/mindspore/ops/function/nn_func.py#L146-L155
From the actual definition of the `ivy.avg_pool2d()`, the key-word argument should be `ceil_mode`
https://github.com/unifyai/ivy/blob/207dec0cee120a5898749d7b3f7b984341fff313/ivy/functional/ivy/experimental/layers.py#L375-L387

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
In the following function call, the key-word argument `pad_mode` is used,
https://github.com/unifyai/ivy/blob/207dec0cee120a5898749d7b3f7b984341fff313/ivy/functional/frontends/mindspore/ops/function/nn_func.py#L146-L155
From the actual definition of the `ivy.avg_pool2d()`, the key-word argument should be `ceil_mode`
https://github.com/unifyai/ivy/blob/207dec0cee120a5898749d7b3f7b984341fff313/ivy/functional/ivy/experimental/layers.py#L375-L387

## Related Issue
Closes #27851 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by KareemMAX** [comment]
This function seems to be incorrectly defined, it should follow [`mindspore.ops.avg_pool2d` signature](https://www.mindspore.cn/docs/en/r2.2/api_python/ops/mindspore.ops.avg_pool2d.html#mindspore.ops.avg_pool2d)

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Make sure you follow this signature https://www.mindspore.cn/docs/en/r2.2/api_python/ops/mindspore.ops.avg_pool2d.html#mindspore.ops.avg_pool2d

**Comment by Sai-Suraj-27** [comment]
> This function seems to be incorrectly defined, it should follow [`mindspore.ops.avg_pool2d` signature](https://www.mindspore.cn/docs/en/r2.2/api_python/ops/mindspore.ops.avg_pool2d.html#mindspore.ops.avg_pool2d)

Hey, @KareemMAX I corrected the function def, it's arguments and default values. 👍🏻

**Review by KareemMAX — APPROVED** [review]

**Comment by Sai-Suraj-27** [comment]
Hey, @vedpatwardhan can you once look into this PR. Also, the frontend tests for mindspore are implemented yet or not? because I see the following. (Me and Kareem discussed about it but we are unsure). Thank you.
https://github.com/unifyai/ivy/blob/b024de17148728f658c30db8116547ed8d4daa58/ivy_tests/test_ivy/test_frontends/test_mindspore/test_ops/test_function/test_mindspore_nn_func.py#L203-L204

**Comment by vedpatwardhan** [comment]
> Hey, @vedpatwardhan can you once look into this PR. Also, the frontend tests for mindspore are implemented yet or not? because I see the following. (Me and Kareem discussed about it but we are unsure). Thank you.
> 
> https://github.com/unifyai/ivy/blob/b024de17148728f658c30db8116547ed8d4daa58/ivy_tests/test_ivy/test_frontends/test_mindspore/test_ops/test_function/test_mindspore_nn_func.py#L203-L204

The changes look good to me, feel free to merge. Yeah the tests aren't working for the mindspore frontend at the moment 😄

**Pull request merged**
