### PR TITLE
Fix Frontend Failing Test: paddle - math.paddle.diff

### PR DESCRIPTION
**Pull request by ZJay07**
# PR Description
2 errors:
1. dtype error, append, prepend and x are different dtypes hence causing an error, fix by casting append and preppend to the same dtype as x
2. dim error x, append and prepend should be the same dim, fixed by making max_dim of x to be the same as the other 2

## Related Issue

Close https://github.com/unifyai/ivy/issues/28495
Close https://github.com/unifyai/ivy/issues/28527
Close https://github.com/unifyai/ivy/issues/28526
Close https://github.com/unifyai/ivy/issues/28525
Close https://github.com/unifyai/ivy/issues/28524

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @ZJay07 
Thank you very much for the PR.
I think restriciting max number of dims to be also 1 like min num of dims means that we are testing for only 1d arrays while paddles diff function should also be able to run multidimensional arrays. So can we put a higher limit on if it helps maybe 5 or 6?

**Comment by ZJay07** [comment]
@Ishticode it should worked now for multi dimensions :)

**Review by Ishticode — COMMENTED** [review]
We should not be needing to do so much to get dim and dtype right for append and prepend after they are generated. Can you see if you can instead generate them right to begin with? like in the helpers used. There is a shared strategy used here but that doesn't seem to get the same dtype? maybe use a single array generate with num_arrays equal to two or something.
Let me know if something is not clear

**Comment by ZJay07** [comment]
Just fixed it to generate an array, let me know if this is the right fix!

**Review by Ishticode — APPROVED** [review]
That looks good. Thank you very much :) @ZJay07

**Pull request merged**
