### PR TITLE
feat: Added  ldl_factor function to torch frontend in linalg.py file.

### LINKED ISSUE #26396: ldl_factor

### PR DESCRIPTION
**Pull request by Dheeraj-Bal**
# PR Description

Added  ldl_factor function to torch frontend in linalg.py file.

Close #26396

## Checklist

- [x] Added a function

### CODE REVIEW

**Comment by Dheeraj-Bal** [comment]
@jieunboy0516 Can you please help with the one failing check?

**Comment by jieunboy0516** [comment]
Hi @Dheeraj-Bal , thanks for your contribution to Ivy. Could you please add a unit test function as well?
you could reference some other merged functions at [https://github.com/unifyai/ivy/issues/7479](https://github.com/unifyai/ivy/issues/7479)

**Comment by Dheeraj-Bal** [comment]
Hi @jieunboy0516, it seems like ldl_factor method is not implemented in torch backend and ivy API, hence it cannot be directly  implemented in frontend. Would you like me to edit the torch backend and ivy API files as well.

**Comment by jieunboy0516** [comment]
> Hi @jieunboy0516, it seems like ldl_factor method is not implemented in torch backend and ivy API, hence it cannot be directly implemented in frontend. Would you like me to edit the torch backend and ivy API files as well.

@Dheeraj-Bal i think you are right. i dont see other ivy backends that can do the job of LDL factorization. I will have an ask and get back to you soon. Thanks a lot

**Comment by jieunboy0516** [comment]
Sorry @Dheeraj-Bal , after digging further into the situation, seems that you might have to implement `ivy.ldl_factor` backend first or implement the frontend without the ldl_factor backend. 
please take a look at  [https://github.com/unifyai/ivy/pull/19897](this PR)
```
ivy.ldl_factor needs to be fully implemented (added to all backends and tested) before it can be used in the frontends.
I have added it to our https://github.com/unifyai/ivy/issues/3856. Feel free to either open a new PR for that issue, or wait until that is added by someone else. You could alternatively try to implement the frontend functions without ivy.ldl_factor but I think that would be too complex.```

**Comment by Dheeraj-Bal** [comment]
@jieunboy0516 , how will the unit test function will be written in this case? If you can guide, it would be helpful.

**Comment by Dheeraj-Bal** [comment]
@jieunboy0516, can you guide on how to add unit test function in this scenario and in general too. I felt difficulty in understanding how to write unit test function.

**Comment by jieunboy0516** [comment]
> @jieunboy0516, can you guide on how to add unit test function in this scenario and in general too. I felt difficulty in understanding how to write unit test function. I have made changes in the backend as well. Can you guide on why my tests are failing now?

You would have to implement `ldl_factor` for different backend frameworks. Thanks for your hard work on it.

**Pull request closed without merging**
