### PR TITLE
Add diagflat function to Jax Frontend

### LINKED ISSUE #6893: diagflat

### PR DESCRIPTION
**Pull request by Change-m**
Close #6893

### CODE REVIEW

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi,

1. Kindly resolve the conflicts.
2. It shows that you've edited or removed a function while editing the files, kindly do not remove the previous one, you have to add it.

Thanks! 🙂

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi!
Kindly resolve the conflicts and you also have to refactor this according to the new tests.
Thanks! 🙂
https://lets-unify.ai/ivy/deep_dive/ivy_tests.html#ivy-tests

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
