### PR TITLE
refactor: Reformatted and Refactored some files to make the code better and more readable. 

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
Reformatted and Refactored files for better readability and according to latest Python standards. Used `f-strings` wherever possible, Replaced unneeded comprehensions with generator (Functions like `any`, `all` and `sum` allow us to pass in a generator rather than a collection. Doing so removes a pair of brackets, making the intent slightly clearer). Also, removed unnecessary calls to `.keys()` when iterating over a dictionary as the default behaviour when iterating over a dictionary is to iterate over the keys, merged nested `if` conditions, and few more small changes to make the code better and clean.

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:
https://twitter.com/Sai_Suraj_27

### CODE REVIEW

**Review by vedpatwardhan — COMMENTED** [review]
Just requested @KareemMAX's review on the PR, thanks @Sai-Suraj-27 😄

**Comment by vedpatwardhan** [comment]
I'm not sure if that label works anymore tbh, but even if it did, all the `ivy` tests are failing anyway due to the `KeyError` with `tensorflow` because of its recent release, so we wouldn't be able to test these changes with the `Exhaustive Tests` label 😅

**Comment by KareemMAX** [comment]
> I'm not sure if that label works anymore tbh, but even if it did, all the `ivy` tests are failing anyway due to the `KeyError` with `tensorflow` because of its recent release, so we wouldn't be able to test these changes with the `Exhaustive Tests` label 😅

Oh, so what do you suggest? I'm a bit hesitant to repeat the last mistake of breaking ivy again tbh 😅

**Comment by vedpatwardhan** [comment]
> Oh, so what do you suggest? I'm a bit hesitant to repeat the last mistake of breaking ivy again tbh 😅 @vedpatwardhan

Actually the `KeyError` thing is fixed now, so the CI results can be considered reliable. I'd suggest checking through the `display-test-results` workflow to see if any test failures or warnings can be attributed to the changes and get the PR merged if everything looks good. We can always keep an eye on `main` as well if there's further issues like we did the last time. Thanks @KareemMAX 😄

**Comment by KareemMAX** [comment]
Cool, I'll merge the PR now. Thanks both @Sai-Suraj-27 @vedpatwardhan

**Pull request merged**
