### PR TITLE
Match kwargs

### PR DESCRIPTION
**Pull request by atakanoc**
- [] #2732

### CODE REVIEW

**Comment by ZoeCD** [comment]
Hi! It seems there are some docstring errors in the examples. Could you please review them? You can see the errors under test-docstrings / run-docstring-tests (pull_request) -> details 😊

**Comment by atakanoc** [comment]
At line 703 I saw the following:
`/ivy/ivy/__init__.py:650: UserWarning: Output is unequal to the docstrings output: match_kwargs`

After noticing that the output for the docstring example was incorrect, I fixed it by modifying the example lines of code that produce the output and then to be sure, I ran those same lines on a test file and copy/pasted the output. However, the error persists and I'm not sure about what to do from here onwards.

When searching for 'match_kwargs' in the test output I also see this exact set of lines repeated 4 times:
```
output for  match_kwargs  on run:  module'ivy.functional.backends.torch.layers'hasnoattribute'linear'torchx=ivy.match_kwargs(kwargs,ivy.elementwise.add,ivy.layers.linear),name'x'isnotdefinedtorchprint(x),module'ivy.functional.backends.torch.layers'hasnoattribute'linear'torchx=ivy.match_kwargs(kwargs,ivy.layers.linear,ivy.elementwise.add),name'x'isnotdefinedtorchprint(x) 
output in docs : [{'out':ivy.array([0,0,0])},{'bias':ivy.array([0,1,2])}],[{'out':ivy.array([0,0,0]),'bias':ivy.array([0,1,2])},{}] 
 module'ivy.functional.backends.torch.layers'hasnoattribute'linear'torchx=ivy.match_kwargskwargs  !=  'out':0 
```

I haven't been able to figure out what this means either.

**Comment by atakanoc** [comment]
I'd appreciate a little help so I know where to continue from :)

**Comment by ZoeCD** [comment]
Could you please try with `ivy.add` and `ivy.linear` instead of `ivy.elementwise.add` and `ivy.layers.linear`?

**Comment by atakanoc** [comment]
@ZoeCD Looks like it's fixed now. No mention of `match_kwargs` in the logs anymore.

**Comment by ZoeCD** [comment]
Great, thank you for your contribution!

**Pull request merged**
