### PR TITLE
Update meta.py

### LINKED ISSUE #22591: <_compute_cost_and_update_grads>
Meta.py

### PR DESCRIPTION
**Pull request by MahadShahid8**
Removed lambda backend binded and added doc strings for better understanding of the code

# PR Description 
Reformatted the _compute_cost_and_update_grads function from meta.py. Removed the lambda backend binding and added helpful docstrings

## Related Issue 

Close #22591 

## Checklist 

- [ ]Yes Did you add a function?
- [ ] Did you add the tests?
- [ ]Yes Did you follow the steps we provided?

### CODE REVIEW

**Comment by MahadShahid8** [comment]
@RickSanchezStoic kindly review my pull request

**Comment by MahadShahid8** [comment]
@RickSanchezStoic kindly review my pr as soon as you can so I can proceed with my application with ivy. I shall be really obliged

**Comment by MahadShahid8** [comment]
@RickSanchezStoic

**Comment by MahadShahid8** [comment]
@RickSanchezStoic

**Comment by RickSanchezStoic** [comment]
lgtm!

**Pull request merged**
