### PR TITLE
added clip_ frontend method

### LINKED ISSUE #22491: clip_

### PR DESCRIPTION
**Pull request by Aaryan562**
Close #22491

### CODE REVIEW

**Comment by Aaryan562** [comment]
@umairjavaid Pls review my PR.

**Comment by umairjavaid** [comment]
Amazing work!

**Review by umairjavaid — CHANGES_REQUESTED** [review]
Amazing work! There are merge conflicts, other than that everything seems alright. Could you please fix those? So that I can merge it

**Comment by Aaryan562** [comment]
@umairjavaid I resolved the merge conflicts. Pls merge them before another conflicts arises. Thank you.

**Review by Aaryan562 — COMMENTED** [review]
Resolved the conflicts.

**Pull request merged**
