### PR TITLE
Add Squeeze function to Tensorflow frontend

### PR DESCRIPTION
**Pull request by hamehrabi**
Please assign it to @V-G-spec 
Thanks

### CODE REVIEW

**Comment by hamehrabi** [comment]
Close #7162

**Comment by hamehrabi** [comment]
Hi @V-G-spec,

I'd be thankful if you check and merge my function. 😊

**Comment by V-G-spec** [comment]
👍

**Comment by hamehrabi** [comment]
> 👍

Thanks

**Pull request merged**
