### PR TITLE
tostring

### LINKED ISSUE #14000: tostring

### PR DESCRIPTION
**Pull request by piyushgit011**
closes #14000

### CODE REVIEW

**Comment by nathzi1505** [comment]
Hi @piyushgit011, thanks for contributing.
Would you mind looking at the failing tests?

**Comment by piyushgit011** [comment]
Hey @nathzi1505  i added tostring but using .tobytes in the function but the tests are failing for tobytes can u help me with this??

**Comment by nathzi1505** [comment]
Would you mind giving me a screenshot of just the test for tostring on your machine?

**Comment by piyushgit011** [comment]
hey @nathzi1505  can you check it? my docker container is not working

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by nathzi1505** [comment]
@piyushgit011 I see there happen to have arose one merge conflict. 
Would you mind looking at them?

**Comment by piyushgit011** [comment]
I will look into it

**Comment by devika-02** [comment]
Hey since this PR is stale can I work on it?

**Comment by piyushgit011** [comment]
Hey @nathzi1505 i think this can be merge now

**Pull request merged**
