### PR TITLE
docs: update the documentation info

### LINKED ISSUE #23658: update the documentation guide

### PR DESCRIPTION
**Pull request by a0m0rajab**
# PR Description

This PR is using a stacked PR logic to make it easier to read and review, to start reviewing it we need to merge them in this order: 
- https://github.com/unifyai/ivy/pull/23654
- https://github.com/unifyai/ivy/pull/23653
- https://github.com/unifyai/ivy/pull/23652

## Related Issue

Close #23658

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by jaskiratsingh2000** [comment]
@a0m0rajab is this complete yet? Can you please let me know?

**Comment by guillesanbri** [comment]
what's the purpose of the guides.md file exactly?

**Comment by a0m0rajab** [comment]
@guillesanbri kept it as a placeholder right now for previous text, I was thinking to move them directly to our demos but just decided to revisit/rethink about it again when we got the first iteration done.

**Comment by guillesanbri** [comment]
> @guillesanbri kept it as a placeholder right now for previous text, I was thinking to move them directly to our demos but just decided to revisit/rethink about it again when we got the first iteration done.

the changes are going to be in the commit history anyway, no need to have another file with the text we have removed :) although I don't fully follow still, this PR only affects that file so it will be changing a file that is not rendered anywhere right?

**Comment by a0m0rajab** [comment]
Merged this since there is no input here about the docs, will continue on the other PR>

**Pull request merged**
