### PR TITLE
add sinc to numpy frontend

### LINKED ISSUE #22090: sinc

### PR DESCRIPTION
**Pull request by HoshiNoRandii**
Close #22090

### CODE REVIEW

**Comment by HoshiNoRandii** [comment]
I found [this issue with numpy](https://github.com/numpy/numpy/issues/11204) that my code does not replicate (and thus does not pass tests). Would it be better to match this behavior instead?

**Comment by lucasalavapena** [comment]
Thanks for your PR Randy :smile:.

Regarding your question, if I understand it correctly, that would be a concern for the person implementing the sinc numpy backend, so that is not a concern in this PR (at least I think). Also I think you could simplify your implementation of the frontend using [`ivy.sinc`](https://unify.ai/docs/ivy/docs/functional/ivy/experimental/elementwise/ivy.functional.ivy.experimental.elementwise.sinc.html#sinc ) . Please let me know if that does not make sense!

There are some failing tests relating to dtypes, check the `display_test_results` run, it lists the tests that failed due to this PR.

I also ran them on my codespace, you could do something similar for debugging purposes (note I used --pdb to launch the python debugger into the failure):
```
(multienv) @lucasalavapena ➜ .../test_ivy/test_frontends/test_numpy/test_mathematical_functions (numpy-sinc) $ pytest --pdb test_other_special_functions.py 
Use Database in ReadOnly Mode with local caching !
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.10.0, pytest-7.4.0, pluggy-1.2.0
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-3.7.1, hypothesis-6.82.4, json-report-1.5.0, metadata-3.0.0
collected 5 items                                                                                                                                                                 

test_other_special_functions.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

frontend = 'numpy', backend_fw = 'numpy', on_device = 'cpu'

    @handle_frontend_test(
>       fn_tree="numpy.sinc",
        dtype_and_x=helpers.dtype_and_values(available_dtypes=helpers.get_dtypes("float")),
        test_with_out=st.just(False),
    )

test_other_special_functions.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_other_special_functions.py:24: in test_numpy_sinc
    helpers.test_frontend_function(
../../../helpers/function_testing.py:881: in test_frontend_function
    value_test(
../../../helpers/assertions.py:118: in value_test
    assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

values = [[array(-2.7827534e-08, dtype=float32)], [3.8981718325193755e-17]], this_key_chain = None

    def assert_same_type_and_shape(values, this_key_chain=None):
        x_, y_ = values
        for x, y in zip(x_, y_):
            if isinstance(x, np.ndarray):
                x_d = str(x.dtype).replace("longlong", "int64")
                y_d = str(y.dtype).replace("longlong", "int64")
                assert (
                    x.shape == y.shape
                ), "returned shape = {}, ground-truth returned shape = {}".format(
                    x.shape, y.shape
                )
>               assert (
                    x_d == y_d
                ), "returned dtype = {}, ground-truth returned dtype = {}".format(x_d, y_d)
E               AssertionError: returned dtype = float32, ground-truth returned dtype = float64
E               Falsifying example: test_numpy_sinc(
E                   frontend='numpy',
E                   backend_fw='numpy',
E                   on_device='cpu',
E                   dtype_and_x=(['float32'], [array(-1., dtype=float32)]),
E                   test_flags=FrontendFunctionTestFlags(
E                       num_positional_args=0,
E                       with_out=False,
E                       inplace=False,
E                       as_variable=[False],
E                       native_arrays=[False],
E                       test_compile=False,
E                       generate_frontend_arrays=False,
E                   ),
E                   fn_tree='ivy.functional.frontends.numpy.sinc',
E               )
E               
E               You can reproduce this example by temporarily adding @reproduce_failure('6.82.4', b'AXicY2AAAkYGCADTAAAkAAM=') as a decorator on your test case

../../../helpers/assertions.py:82: AssertionError
```

**Comment by lucasalavapena** [comment]
I asked others in the team regarding using `sinc` and they said it was prefer so that is fine. You are right that the change is relevant here. Your float solution is good!

Sorry for not mentioning it earlier but could you please uncommit your submodule (test_array_api) changes, I think they are unrelated to this specific PR. Otherwise I think we can merge it.

**Comment by HoshiNoRandii** [comment]
I couldn't figure out how to uncommit just the test_array_api changes, since they were originally in the same commit as my first attempt at writing the sinc function. I've just used `git submodule update --remote` to make sure they match with what is currently on ivy's main branch. If that's not sufficient, could you help me figure out how to uncommit the changes properly?

**Comment by lucasalavapena** [comment]
I think that solution is fine since we squash it, if we rebased your commits then you probably have to use an interactive rebase and edit your old commit.  

I will check back with the testing team because I tested your PR on codespaces and it passes your new tests but it is still failing in the CI.

**Comment by lucasalavapena** [comment]
@HoshiNoRandii Sorry for the long wait. Thank you for your patience :smile: .  

I did not get proper response from the team, however, I spent more time testing it thoroughly in codespaces (running pytest multiple times and redoing some of failed CI tests in codespaces using `hypothesis.reproduce_failure`) and I believe the CI is just wrong and your code is just fine, so LGTM!

**Pull request merged**
