### PR TITLE
added cos to NumPy frontend

### PR DESCRIPTION
**Pull request by gurkankilicaslan**

### CODE REVIEW

**Comment by ZoeCD** [comment]
Hi! It looks good to me! Thank you for your contribution 😊 However, there is already a `test_cos` function in `test_elementwise` in master. Could you please revert those changes and update the project? We can merge your PR after that. Thanks!

**Comment by gurkankilicaslan** [comment]
> Hi! It looks good to me! Thank you for your contribution 😊 However, there is already a `test_cos` function in `test_elementwise` in master. Could you please revert those changes and update the project? We can merge your PR after that. Thanks!



> Hi! It looks good to me! Thank you for your contribution 😊 However, there is already a `test_cos` function in `test_elementwise` in master. Could you please revert those changes and update the project? We can merge your PR after that. Thanks!

**Comment by gurkankilicaslan** [comment]
> Hi! It looks good to me! Thank you for your contribution 😊 However, there is already a `test_cos` function in `test_elementwise` in master. Could you please revert those changes and update the project? We can merge your PR after that. Thanks!

Hi, Thank you for your feedback. I reverted the related function. Could you check and give me new feedback🙂?

**Comment by gurkankilicaslan** [comment]
> > Hi! It looks good to me! Thank you for your contribution 😊 However, there is already a `test_cos` function in `test_elementwise` in master. Could you please revert those changes and update the project? We can merge your PR after that. Thanks!
> 
> Hi, Thank you for your feedback. I reverted the related function. Could you check and give me new feedback🙂?

I mistakenly closed the PR. I reverted the related function. Could you check and give me new feedback?

**Comment by ZoeCD** [comment]
Hello! Just one more thing. There are some merge conflicts. Git is taking `sin` and `cos` as a name change and not as two separate functions. Could you please update your branch with upstream master locally to solve this? Thanks! 😊

**Comment by gurkankilicaslan** [comment]
> Hello! Just one more thing. There are some merge conflicts. Git is taking `sin` and `cos` as a name change and not as two separate functions. Could you please update your branch with upstream master locally to solve this? Thanks! 😊

Hello @ZoeCD, I resolved it. Can you check it, please?

**Comment by ZoeCD** [comment]
Looks good! Thanks!

**Pull request merged**
