### PR TITLE
sparse_categorical_accuracy

### PR DESCRIPTION
**Pull request by shunleili**
sparse_categorical_accuracy #3751

### CODE REVIEW

**Review by ankitdsi2010 — CHANGES_REQUESTED** [review]
Could you please write the frontend test for this function.

**Comment by shunleili** [comment]
Hi @ankitdsi2010 .
Thanks for your help! May I enter the PR link into the questionnaire?

**Review by ankitdsi2010 — CHANGES_REQUESTED** [review]
Fix the test failing [here](https://github.com/unifyai/ivy/runs/8178009234?check_suite_focus=true#step:6:1558)

**Comment by shunleili** [comment]
> Fix the test failing [here](https://github.com/unifyai/ivy/runs/8178009234?check_suite_focus=true#step:6:1558)

Hi @ankitdsi2010 
I'm not familiar with `ivy test`. Is the problem about no max of y_pred or dtype? Could you pls give me some hint?

**Pull request closed without merging**
