### PR TITLE
cos function without idea file

### LINKED ISSUE #9477: cos

### PR DESCRIPTION
**Pull request by aymuos15**
Close #9477

### CODE REVIEW

**Comment by aymuos15** [comment]
Hi @V-G-spec

Could you please check my PR?

**Comment by V-G-spec** [comment]
Hi @aymuos15, sorry for the delay. Thank you for your contribution! Can you please take a look at the lint errors once?

**Comment by aymuos15** [comment]
Hi @V-G-spec, 

I am a bit confused about interpreting the lint errors. For example:

ivy/functional/backends/jax/experimental/elementwise.py:234:89: E501 line too long (94 > 88 characters)
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_math.py:2101:2: E121 continuation line under-indented for hanging indent

Could you possibly point out which line thsee 2 are referring to? I will be able to solve the rest then. Thanks!

**Comment by aymuos15** [comment]
@V-G-spec Hi, on checking the errors, it seems that the cos function had already been implemented but the issue was still open?

Could you let me know what I should do next?

**Comment by V-G-spec** [comment]
Hey, so the first lint error is not of a file you have changed, so you need not worry about it. The second is an indentation error for the parenthesis in one of the lines of your test function. I would recommend taking a read through the documentation. A simple google search should also be useful in rectifying the same.
Thanks!

**Comment by aymuos15** [comment]
Hi @V-G-spec 

I am closing this issue as the cos function is already present. Thank you for the support.

**Pull request closed without merging**
