### PR TITLE
qr

### PR DESCRIPTION
**Pull request by 29riyasaxena**
#1582

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by a0m0rajab** [comment]
Hi @29riyasaxena thank you for your PR, could we just change the PR title and add a reference to the issue you worked at? This would help us with tracking your work. When you get the things correct the GitHub Bot will show a pass message. 

If you had time to resolve conflict as well it would be great, this would save time for the engineer who is responsible for reviewing.

**Comment by 29riyasaxena** [comment]
Hi @a0m0rajab, Thank you for your reply. Yes, I was resolving the conflicts. I'll update it as soon as possible.

**Comment by a0m0rajab** [comment]
@29riyasaxena thank you for that, can you follow the instructions in the "PR Compliance Checks", 
adding a a keyword for the PR body can help the connection between the issue and the PR. 
and the title name would help to have a clear changelog history

**Comment by Sam-Armstrong** [comment]
@29riyasaxena I think this issue is already being worked on by @amk16, who opened this issue on the todo list https://github.com/unifyai/ivy/issues/23151.

**Comment by 29riyasaxena** [comment]
Oh, okay. Thank you, I'll close this PR.

**Pull request closed without merging**
