### PR TITLE
bitwise_and Close  #17637

### LINKED ISSUE #17637: bitwise_and
implementing the bitwise and for paddle frontend

### PR DESCRIPTION
**Pull request by samthakur587**
bitwise_and Close #17637

### CODE REVIEW

**Comment by samthakur587** [comment]
bitwise_and Close #17637

**Comment by samthakur587** [comment]
hey @Ishticode i am facing error in formatting of the files can you please look into it. i am looking for  some suggestion

thank you

**Comment by samthakur587** [comment]
hey @Ishticode can you please review the PR. because its very hard to solve the merge conflict again and again also the some else merged PR will overlap with my code and deficult to solve.

thank you

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @samthakur587, thanks for the PR. I am stepping in for Ishtiaq here. Can you please revert the changes made to the `array_api_testing` folder so I can proceed to merge the PR? Everything else looks good to me. Thanks :)

**Comment by samthakur587** [comment]
hey @hmahmood24 the changes in ivy_test folder are not made by me the changes came when i pull the branch in local there is not any commit made. i am trying but i am not finding any way to remove these changes. can you please help me to remove these changes. 

thank you

**Comment by hmahmood24** [comment]
> hey @hmahmood24 the changes in ivy_test folder are not made by me the changes came when i pull the branch in local there is not any commit made. i am trying but i am not finding any way to remove these changes. can you please help me to remove these changes.
> 
> thank you

[This](https://github.com/unifyai/ivy/pull/17647/commits/4038bc97ecdc8e8a9cb18395339d18795d201991) is the commit where you've accidently pushed changes to the `array_api_testing` folder. You can revert this commit and then manually add your function and its test afterwards. Note that reverting this commit will remove any changes you made after it so copy and keep your function and the test somewhere safe and then add it back once you've reverted this commit.

**Comment by samthakur587** [comment]
hey @hmahmood24 i solved the problem of ivy_test_array . i found that the ivy_test_array folder has modified automatically due to running the pre-commit locally. i think the files are in ivy_test_array are not formated according to the pre-commit config. 
this the reason i am not able to run able to reformat my file with pre-commit.

so now PR is ready to merge but it has only the issue with formatting can you please check and let me know where is the problem in formatting.

thank you

**Comment by samthakur587** [comment]
hey @hmahmood24  all changes has done now the PR ready to merge

thank you

**Comment by Ishticode** [comment]
@hmahmood24 Thanks for taking this Mahmood.

**Comment by hmahmood24** [comment]
Looks good to merge now. Thanks for the PR! @samthakur587 🚀

**Pull request merged**
