### PR TITLE
Adds index_put_() to Tensor and tests

### PR DESCRIPTION
**Pull request by raeudigerRaeffi**
Adds index_put_() to pytorch tensor. Tests are currently failing due to the Pytorch function being incorrectly called. I suspect the reason is that the Tensor is incorrectly initalized and does not have the same dtype as the generated array

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by raeudigerRaeffi** [comment]
Outlined in #9561

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hey! Could you please link the issue you've created for this so that your work gets linked properly? Check out the docs hyperlink by ivy-leaves in earlier comment. Thanks! :smile:

**Comment by raeudigerRaeffi** [comment]
Relates to issue #20936

**Comment by raeudigerRaeffi** [comment]
I however noticed that i accidentally worked on an internal todo and not an open to externals one

**Comment by AnnaTz** [comment]
> Hey @AnnaTz sorry about tagging you here, but could you please help in reviewing this PR?
> 
> Frontend implementation of `torch.Tensor.index_put` is part of the [internal To-Do board](https://github.com/unifyai/ivy/issues/9561) as @raeudigerRaeffi noticed, and I'm not sure of the SOP here but considering that this frontend is important for compiling popular models, I think we should accept the PR if it's correct.

Hi @raeudigerRaeffi @rishabgit, I have linked the PR to the private subtask. Even though it references an internal ToDo list, it should be find to merge the PR as soon as the tests pass. 

Just one note, the function in the ToDo is `index_put`, not `index_put_`, so @raeudigerRaeffi please add that one here as well. It should be fairly simple since you have already implemented the rest. Also, please make sure you add tests for all the functions you are implementing. Thanks!

**Comment by raeudigerRaeffi** [comment]
@AnnaTz thanks for your reply. I implemented the tests as requested and modified the function name too.

**Comment by AnnaTz** [comment]
Hi @raeudigerRaeffi, you will need to resolve the conflicts so that the CI checks can run properly. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
