### PR TITLE
Ivy histogram branch

### PR DESCRIPTION
**Pull request by Tristan1649**
Close #12450

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by WilliamHirst** [comment]
Hi,
Please link the issue the PR is trying to solve. Follow the instructions in the docs: https://lets-unify.ai/ivy/contributing/the_basics.html#the-basics

**Comment by Tristan1649** [comment]
> Hi, Please link the issue the PR is trying to solve. Follow the instructions in the docs: https://lets-unify.ai/ivy/contributing/the_basics.html#the-basics

Hi @WilliamHirst  Hystogram #4  Ivy histogram branch #12450

**Comment by WilliamHirst** [comment]
Hi, 
Due to the force push made a couple of days ago there is a merge conflict with your PR. Please follow the instructions made by Dan in the announcement channel on Discord a couple of weeks ago.
Let me know when this is done 😊

**Pull request closed without merging**
