### PR TITLE
UnsortedSegmentSum

### PR DESCRIPTION
**Pull request by jwyatt09**
# PR Description

- [ ] #22874

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Sam-Armstrong** [comment]
@jwyatt09 Isn't this already being worked on by @usayrimrehman? Or is that issue stale?

**Comment by usayrimrehman** [comment]
Yes, I am working on this

**Comment by Sam-Armstrong** [comment]
@usayrimrehman thanks for letting us know, in that case I'll close this PR for the time being as you started working on this first.

**Pull request closed without merging**
