### PR TITLE
Add Matmul function for Torch Frontend

### LINKED ISSUE #10204: matmul

### PR DESCRIPTION
**Pull request by MuhammedAshraf2020**
closes #10204

### CODE REVIEW

**Comment by MuhammedAshraf2020** [comment]
hi @Aarsh2001 can you have a look here.

**Review by Aarsh2001 — CHANGES_REQUESTED** [review]
So there's a `blfoat16` error in the tests. Please have a look at the `test-frontend-torch` check in the check suite. I think you can probably resolve it by adding the decorator `with_unsupported_dtypes` and pass `bfloat16` as an argument.

**Comment by MuhammedAshraf2020** [comment]
> So there's a `blfoat16` error in the tests. Please have a look at the `test-frontend-torch` check in the check suite. I think you can probably resolve it by adding the decorator `with_unsupported_dtypes` and pass `bfloat16` as an argument.

okay , i will do it now

**Comment by MuhammedAshraf2020** [comment]
@Aarsh2001 
Screenshot from 2023-02-16 07-23-24
it locally passes the tests as shown here

**Comment by MuhammedAshraf2020** [comment]
@Aarsh2001 
Can you have a look here now ?

**Comment by MahmoudAshraf97** [comment]
> @Aarsh2001 Screenshot from 2023-02-16 07-23-24 it locally passes the tests as shown here

Hello Muhammed, this doesn't mean that the tests passed, the following screenshot is an example of successful tests:
image

You need to fix the arguments to the test function because the dtype is wrong

**Comment by MuhammedAshraf2020** [comment]
@MahmoudAshraf97 
oh, thank you for you notice, i hope the next commit solve this problem.

**Review by MahmoudAshraf97 — APPROVED** [review]

**Comment by MahmoudAshraf97** [comment]
I Added tolerance parameters because the results differed slightly due to different backend implementations, all the test are now passing and going to merge, Great work!

**Pull request merged**
