### PR TITLE
Adding support for random dtype generation for out arg during testing

### PR DESCRIPTION
**Pull request by danielmunioz**

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by CatB1t — COMMENTED** [review]
Hello Daniel, is this still an active PR?

**Comment by danielmunioz** [comment]
Hey Mustafa, Yeah, these changes are still needed AFAIK, however this PR needs to be updated to account for the recent changes in the testing suite, I'll look into it and I'll ping you back!

**Comment by CatB1t** [comment]
> Hey Mustafa, Yeah, these changes are still needed AFAIK, however this PR needs to be updated to account for the recent changes in the testing suite, I'll look into it and I'll ping you back!

Awesome, thansk Daniel

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
