### PR TITLE
Added log function and test to pytorch frontend

### PR DESCRIPTION
**Pull request by usama-baloch**
Added log function (pointwise_ops) and its test to PyTorch frontend.

### CODE REVIEW

**Comment by CerberusLatrans** [comment]
Hi @usama-baloch thanks for the PR! Everything looks good.
Before I merge, just two things:

Can you comment "Close #<corresponding issue num you created>" in its own comment like in the docs here?
Screen Shot 2022-11-25 at 12 00 43 AM

Can you confirm that the torch log test you implemented is passing locally? It doesn't seem to be showing any errors in the CI frontend check, but I think it failed to collect tests in the first place. Thanks!

**Comment by usama-baloch** [comment]
Hi @CerberusLatrans, I just updated the pointwise_ops.py file again, now it is ready for merge I think. You can now check it from your side. It is completely fine from my side 🌝, Here is the confirmation that it works well locally:

png

**Comment by CerberusLatrans** [comment]
Close #7300

**Comment by CerberusLatrans** [comment]
Hi @usama-baloch looks good; I will merge. Thanks for the contribution!

**Comment by usama-baloch** [comment]
Hi @CerberusLatrans, Yes I just added the unsupported dtypes using the decorator. You can now check it.

**Comment by CerberusLatrans** [comment]
Hi @usama-baloch, great! Thanks for your contribution.

**Pull request merged**
