### PR TITLE
added onnx trilu function and test

### LINKED ISSUE #21358: Trilu

### PR DESCRIPTION
**Pull request by ShreyanshBardia**
closes #21358

### CODE REVIEW

**Comment by ShreyanshBardia** [comment]
Hi @AlexandraPosta, could you please review this PR

**Comment by AlexandraPosta** [comment]
Hello @ShreyanshBardia, apologies for the late reply. It would be ideal to start by solving the merge conflicts. Thank you!

**Comment by ShreyanshBardia** [comment]
Hey @AlexandraPosta, can you check now

**Comment by AlexandraPosta** [comment]
Hello @ShreyanshBardia I have just had a look at the file. Great work, thank you for your contribution! :)

**Pull request merged**
