### PR TITLE
Add numpy frontend tanh #3005

### LINKED ISSUE #3005: Numpy Frontend tanh
PR: https://github.com/unifyai/ivy/pull/3289

### PR DESCRIPTION
**Pull request by aryanxk02**
Fixes #3005

### CODE REVIEW

**Comment by aryanxk02** [comment]
Hello @JLU-Neal and @LINBOTANG123 Please review the PR :)

**Comment by Oxbeefbabe** [comment]
Hi there, good start, have a few things I'd like for you to fix:

Your test seems to be failing. You should check `test-frontend-numpy / run-nightly-tests (pull_request)` for more information and fix it so it is passing.

There are lint errors in your code. You should check `lint / check-formatting (pull_request)` to see what is wrong and fix them.

Finally, there are conflicts between your changes and the master branch. Before you are ready to have your changes committed, please make sure there are no merge conflicts. Thank you!

**Comment by CerberusLatrans** [comment]
Hello,
Please fix the lint errors and arg typos before proceeding. if possible, try to get the numpy frontend tests passing. Thanks!

**Comment by ivy-seed** [comment]
This PR has been marked as stale because it has been inactive for more than 7 days. Please comment or this will be closed in 7 days

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
