### PR TITLE
Added example to linear_algebra.svd()

### PR DESCRIPTION
**Pull request by VictorCanLima**
Completed #1078

### CODE REVIEW

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hey @VictorCanLima, thanks for contributing, could you please resolve the issues in the files caused by merge conflicts?

**Comment by VictorCanLima** [comment]
Merge conflicts resolved @VedPatwardhan 😃

**Comment by VedPatwardhan** [comment]
Hey @VictorCanLima, the nightly tests are failing for divide and prod, could you please try to get them to pass? Thank you!

**Review by VedPatwardhan — COMMENTED** [review]
Hey @VictorCanLima, the nightly tests are failing for divide and prod, could you please try to get them to pass? Thank you!

**Comment by VedPatwardhan** [comment]
Hey @VictorCanLima, I came to know that you had some confusion regarding the task. Really sorry about the confusion!

**Comment by VedPatwardhan** [comment]
I have resolved the conflicts, the failed tests are related to non-deterministic behaviour. I'll be merging your PR now. Thank you for contributing!

**Pull request merged**
