### PR TITLE
degrees

### PR DESCRIPTION
**Pull request by ndurumo254**
added degree function 
#7477

### CODE REVIEW

**Comment by ndurumo254** [comment]
@fspyridakos . 
hope this find you well. i have just backdated our issue and I left the branch where we were following the changes.  any changes needed to the PR?

**Comment by ndurumo254** [comment]
#7477

**Comment by ndurumo254** [comment]
@aditya-pola hello are you there to help.  i get conflicts after days when I solve them

**Comment by aditya-pola** [comment]
Close #7477

**Comment by aditya-pola** [comment]
Hello @ndurumo254, I am looking into this now. I have made the necessary changes, but in the furture you should follow the instructions at [ToDoList Issues](https://lets-unify.ai/ivy/contributing/the_basics.html#todo-list-issues) (specifically point c and d) to ensure a smooth workflow and avoid someone else working on the same issue.

**Comment by ndurumo254** [comment]
> Hello @ndurumo254, I am looking into this now. I have made the necessary changes, but in the furture you should follow the instructions at [ToDoList Issues](https://lets-unify.ai/ivy/contributing/the_basics.html#todo-list-issues) (specifically point c and d) to ensure a smooth workflow and avoid someone else working on the same issue.

ok. will be waiting for reviews

**Comment by aditya-pola** [comment]
@ndurumo254 sorry to keep you waiting. My machinewas giving me unexpected issues. I notice that you've added a diagonal function which seems out of the scope of the PR. Please remove that.
There are also a lot of formatiing changes which I am not sure are required. Please run lint checks by following the instructions here: [pre-commit hooks](https://lets-unify.ai/ivy/contributing/setting_up.html?highlight=pre+commit#pre-commit)

**Comment by ndurumo254** [comment]
@aditya-pola hello there. i have tried to solve lints and the conflicts . i would appreciate if you can check the changes before we start getting conflicting errors from other implementations. 
thanks 
regards

**Comment by aditya-pola** [comment]
@ndurumo254 Please do not make any changes that are not relevant to the degrees function. If you have, I would request you to remove them. You can safely run the test for your function using `pytest test_jax_numpy_namespace_functions.py::test_jax_numpy_degree` without having to deal with issues from the rest of the file. Most of the lint errors should be automatically fixed by running the pre-coommit hooks. Please let me know if that is not working.

**Comment by ndurumo254** [comment]
> pytest test_jax_numpy_namespace_functions.py::test_jax_numpy_degree

from my side 11 check passed

**Comment by aditya-pola** [comment]
Your lint checks are still failing. Did you run the pre-commit hooks?

You can see where it's failing. The first one is at line 742, column 89 for example
```ivy/functional/experimental/manipulation.py:742:89: E501 line too long (91 > 88 characters)
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_namespace_functions.py:774:21: E126 continuation line over-indented for hanging indent
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_namespace_functions.py:77[8](https://github.com/unifyai/ivy/actions/runs/3651238613/jobs/6168218038#step:5:9):21: E126 continuation line over-indented for hanging indent
ivy_tests/test_ivy/test_frontends/test_numpy/test_matrix/test_methods.py:81:66: W504 line break after binary operator```

**Comment by aditya-pola** [comment]
Hold on, these lint errors may not actually be relevant to you. Have you run the pre-commit hooks? That's all I need to know to merge this at this point

**Comment by ndurumo254** [comment]
> Your lint checks are still failing. Did you run the pre-commit hooks?
> 
> You can see where it's failing. The first one is at line 774, column 21 for example
> 
> ```
> ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_namespace_functions.py:774:21: E126 continuation line over-indented for hanging indent
> ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_namespace_functions.py:77[8](https://github.com/unifyai/ivy/actions/runs/3651238613/jobs/6168218038#step:5:9):21: E126 continuation line over-indented for hanging indent
> ```

this why I was asking you wether I should make changes to other peoples implementation. for  example 
> ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_namespace_functions.py:774:21: E126 continuation line over-indented for hanging indent  is related to  einsum

**Comment by aditya-pola** [comment]
You don't have to make those changes. I just need to know that you've run the pre-commit hooks @ndurumo254

**Comment by ndurumo254** [comment]
> You don't have to make those changes. I just need to know that you've run the pre-commit hooks @ndurumo254

yes and black passed

**Comment by aditya-pola** [comment]
That means I can merge this! Merging now

**Comment by ndurumo254** [comment]
> That means I can merge this! Merging now

ok. thanks for your guidance all through.

**Pull request merged**
