### PR TITLE
Adding multiple Raw Ops to TensorFlow frontend

### LINKED ISSUE #11629: CumulativeLogsumexp

### LINKED ISSUE #11633: Complex

### LINKED ISSUE #11635: AccumulateNV2

### LINKED ISSUE #12548: DebugGradientIdentity

### LINKED ISSUE #12555: Real

### PR DESCRIPTION
**Pull request by KevinUnadkat**
Closes #11629
Closes #11633
Closes #11635
Closes #12548
Closes #12555

### CODE REVIEW

**Comment by KevinUnadkat** [comment]
@WilliamHirst can u pls check the error I'm getting in 

>  ivy/functional/frontends/tensorflow/raw_ops.py

 file from line 622 to line 625
I can understand what does it mean

**Comment by WilliamHirst** [comment]
Hi Kevin,
There is a formatting error. Your functions have breached the maximum line limit (88).

**Comment by KevinUnadkat** [comment]
> Hi Kevin, There is a formatting error. Your functions have breached the maximum line limit (88).

ivy/functional/frontends/tensorflow/raw_ops.py:622:1: E302 expected 2 blank lines, found 0
ivy/functional/frontends/tensorflow/raw_ops.py:623:89: E501 line too long (93 > 88 characters) 

Both  622 and 623 are blank lines

**Comment by WilliamHirst** [comment]
Hi Kevin,
Two of your lines (628 and 630) are still breaching the maximum number of characters. They are 93 and 92 characters respectively, and should be less that 88. For some reason the error log says this error is on lines 665 and 667, but this is wrong. It is on 628 and 630. 

Let me know when this is fixed! 👍

**Comment by KevinUnadkat** [comment]
> Hi Kevin, Two of your lines (628 and 630) are still breaching the maximum number of characters. They are 93 and 92 characters respectively, and should be less that 88. For some reason the error log says this error is on lines 665 and 667, but this is wrong. It is on 628 and 630.
> 
> Let me know when this is fixed! 👍

hy @WilliamHirst , i fix the error

**Pull request merged**
