### PR TITLE
Add type hints execute_with_gradients

### PR DESCRIPTION
**Pull request by Psychofun**

### CODE REVIEW

**Comment by Psychofun** [comment]
Pull request for issue #1725

**Review by RashulChutani — CHANGES_REQUESTED** [review]
@Psychofun The added docstring looks good. Can you also make the required changes for the corresponding Ivy container and Array Functions as mentioned here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#function-formatting. Thanks

**Comment by Psychofun** [comment]
@RashulChutani I added docstrings for ivy.Array and ivy.Container and add ivy.Container static and instance method.
 I look forward to your answer and review.
Thanks.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi, I see the docstring tests fail for some of your functions. Can you please resolve those?

**Comment by Psychofun** [comment]
@RashulChutani  Changes made.
Waiting for your review.
Thanks.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @Psychofun, there are still some issues with the docstring tests. Please resolve:
ivy/array/gradients.py:304 in public method `execute_with_gradients`:
        D412: No blank lines allowed between a section header and its content ('Examples')

**Comment by Psychofun** [comment]
@RashulChutani It's resolved.
Waiting for review. Thanks.

**Comment by Psychofun** [comment]
@RashulChutani Changes made. Waiting for review.

**Pull request closed without merging**
