### PR TITLE
update setting_up.rst

### PR DESCRIPTION
**Pull request by Satarupa22-SD**
# PR Description
Updates the path for requirements.txt file present in the requirements directory

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Satarupa22-SD** [comment]
@Sam-Armstrong please look into it. Thanks :)

**Comment by Sam-Armstrong** [comment]
@Satarupa22-SD did we establish in the discord discussion that this doc was actually correct because it was referring to the requirements in the `ivy/ivy_tests/array_api_testing/test_array_api` folder?

**Comment by Satarupa22-SD** [comment]
@Sam-Armstrong we were referring to separate sections in the documentation which is why there was confusion, someone pointed that out later 😅. However, please feel free to look into it again. 🙂

**Comment by Sam-Armstrong** [comment]
@Satarupa22-SD I think this is correct for `Installing array API testing dependencies`, as there is a requirements.txt file under the `ivy/ivy_tests/array_api_testing/test_array_api` directory, and this section of the docs is specifically referring to the dependencies for array api testing.

**Comment by Ishticode** [comment]
Based on the comments from @Sam-Armstrong it seems like its best to close this PR. Please feel free to suggest otherwise @Satarupa22-SD

**Pull request closed without merging**
