### PR TITLE
Formatted unset_default_int_dtype function

### PR DESCRIPTION
**Pull request by janetwamaitha**
#7731

### CODE REVIEW

**Comment by nassimberrada** [comment]
Hi @janetwamaitha, thank you for your contribution !
This looks good to me, could you solve the merge conflicts ? I'll then proceed to merge your PR, thanks !

**Comment by janetwamaitha** [comment]
Hey Naseem, yes I could.
Let me have a look at it.

**Comment by janetwamaitha** [comment]
Hey @nassimberrada I have resolved the conflicts.

**Comment by nassimberrada** [comment]
Hi @janetwamaitha, this looks good to me so i'll be merging at once, thank you for your contribution !

**Pull request merged**
