### PR TITLE
nextafter

### PR DESCRIPTION
**Pull request by ojask12**

### CODE REVIEW

**Comment by MahmoudAshraf97** [comment]
Hi, there seems to be two nextafter functions in your file, can you recheck? and make sure you modify the existing function, dont create a new one

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hi, please do not change anything outside the function body as it's unified in all backends

**Comment by ojask12** [comment]
Only the empty line was removed. No other changes were made in the file apart from the function nextafter.

**Comment by ojask12** [comment]
nextafter is neither available in paddlepaddle api nor on array api standards. Thus, referring to numpy's nextafter.
image

**Comment by MahmoudAshraf97** [comment]
hi @ojask12, ivy.nextafter only accepts x1 and x2 as arguments
image
image

**Comment by MahmoudAshraf97** [comment]
Hi, your branch is out of sync due to a recent `push --force`, please fork from the Paddle branch again and submit a new PR

**Pull request closed without merging**
