### PR TITLE
Reformat creation docs examples added

### PR DESCRIPTION
**Pull request by iamravi1**

### CODE REVIEW

**Comment by iamravi1** [comment]
- [ ] #6942

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by iamravi1** [comment]
Added examples for linspace

**Comment by aryans1204** [comment]
Hi, please get the docstrings tests passed

**Comment by iamravi1** [comment]
Please check, those errors are not from my code.

**Comment by iamravi1** [comment]
In this only examples are added

**Comment by atakanoc** [comment]
Hi @iamravi1!

If you head over to the [docstring tests of this PR](https://github.com/unifyai/ivy/actions/runs/3506801811/jobs/5874078492) and search for linspace using `CTRL/CMD + F` you can see that there are issues with the docstring examples. To continue with your contributions, you can use this as your starting point. Thanks! ☺️

**Comment by iamravi1** [comment]
I have updated the PR

**Pull request closed without merging**
