### PR TITLE
Add tests for `assertions`

### PR DESCRIPTION
**Pull request by adityagandhamal**
Working on https://trello.com/c/t3vbd50Y/2037-adding-tests-for-assertions

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hi @adityagandhamal can you add the link to this to the trello card? And ping me once this is no longer a work in progress

**Comment by adityagandhamal** [comment]
Sure!

**Comment by adityagandhamal** [comment]
Yet to implement the test for `check_shape`. Waiting for an approval on https://github.com/unifyai/ivy/pull/20996

**Comment by V-G-spec** [comment]
Can you mark this as ready for review when done?

**Comment by V-G-spec** [comment]
👍🏼

**Pull request merged**
