### PR TITLE
Initial attempt at NumPy trapz() function - Issue #17939

### PR DESCRIPTION
**Pull request by Harrison-O**
For issue #17939

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Harrison-O** [comment]
This is my first PR for Ivy. @zhumakhan Can you please let me know how to check the details of the failed tests? I have no idea what these tests are or how to find out.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Harrison-O** [comment]
@zhumakhan can you let me know if this PR passes? I have checked the failing tests and they all appear to be code that isn't mine.

**Comment by zhumakhan** [comment]
LGTM!

**Pull request merged**
