### PR TITLE
Update linear_algebra.py

### PR DESCRIPTION
**Pull request by yluoc**
update info and -info form float to string in ivy/data_classes/array/linear_algebra.py/vector_norm.

### CODE REVIEW

**Comment by yluoc** [comment]
Type arguments for "Literal" must be None, a literal value (int, bool, str, or bytes), or an enum value. So I simply change the red lighted info and -info form float to String

**Review by vedpatwardhan — COMMENTED** [review]
Hey @Ishticode, thanks for requesting the review abd @yluoc thanks for making the changes! I think the reason we've added the type-hint in this way is because the same is followed in the [Array API Standard](https://data-apis.org/array-api/latest/extensions/generated/array_api.linalg.vector_norm.html#extensions-generated-array-api-linalg-vector-norm--page-root). So I think we should first create an issue on their [repository](https://github.com/data-apis/array-api-tests) (if not done already) and based on their response, we can move forward with making the change to the type-hint here. Thanks 😄

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
