### PR TITLE
Update the sum function type hints, docstrings and docstring examples

### PR DESCRIPTION
**Pull request by topefolorunso**

### CODE REVIEW

**Comment by topefolorunso** [comment]
#1739

**Comment by Auxia** [comment]
The examples have been tested to work and the type hints have been satisfactorily changed. I will now merge this PR.

**Comment by topefolorunso** [comment]
Thanks a lot @Auxia . It's a pleasure having my first merged PR with you.
I look forward to contributing more to the project. Cheers.

**Comment by Auxia** [comment]
The pleasure is mine :)

**Pull request merged**
