### PR TITLE
adding more example on zeros_like function doc.

### PR DESCRIPTION
**Pull request by MHamidA**

### CODE REVIEW

**Comment by MHamidA** [comment]
#1862

**Comment by MHamidA** [comment]
Hii @Oxbeefbabe,
I haven't assigned to the #790 issues yet, but I already did this pull request (idk if this is allowed or not), and about this pull request, I don't think there is a lot of reformatting that needs to be done. I just added more examples (and am still not quite sure if I should specify the input type or not). It'd be great if there are any suggestions or corrections. TIA!

**Comment by Oxbeefbabe** [comment]
Hello @MHamidA ,

This is a good start! You should include examples showing how each of the arguments affects the output; using the function with ivy.Containers; and using the function as an instance method.

**Comment by Oxbeefbabe** [comment]
I see that you are using the ivy.set_framework(). This function is outdated and we now use ivy.set_backend() (e.g. ivy.set_backend('numpy') ) If you are working in a fork then it is likely that you need to merge with upstream to get the most up-to-date version of Ivy, so you can use this new function. Using zeros_like() with NumPy as an instance method works fine for me.

I can't find the example where Daniel mentioned not to add instance method examples. It is still shown in the Docstings Examples page in the wiki. I think to be safe its better to add it :)

**Comment by MHamidA** [comment]
I see.. thanks for the confirmation. I'll try to start work on it by tonight.🙌😁

**Comment by MHamidA** [comment]
Hello @Oxbeefbabe :))

I've added more examples with some variations. Please review it thankuu.

**Comment by MHamidA** [comment]
Sorry, I forgot to replace the output and forgot to check some input formats; please see the most recent commit thanku! 🙌

**Comment by Oxbeefbabe** [comment]
Good stuff! You still should add an example making use of the device and out parameters. The device parameter is a bit of a tricky one. I'd recommend using the string 'cpu' and then adding a comment under the example output explaining that the array is now stored on the string.

**Comment by MHamidA** [comment]
Hii @Oxbeefbabe, please review it once again (esp. the example of the device argument is the way to use that argument and the comment given is appropriate) Thankuuu 😅

**Review by Oxbeefbabe — COMMENTED** [review]
That looks great! I'll accept and merge this shortly :)

**Comment by MHamidA** [comment]
Thankuu! One more thing regarding the issue that I opened. Am I the one that needs to close the issue or is the Ivy team the one that will close it?

**Pull request merged**
