### PR TITLE
added tensordot to PyTorch frontend

### LINKED ISSUE #9611: tensordot

### PR DESCRIPTION
**Pull request by kgmann**
Close #9611

### CODE REVIEW

**Comment by V-G-spec** [comment]
Hey @kgmann! Thank you for your contribution
I see some errors being flagged with your changes. Can you address those?
Thanks!

**Comment by kgmann** [comment]
Hey @V-G-spec, I already went through the failing tests before and just did again. None of them are related to my changes, if I'm not mistaken. Could you pinpoint which errors you're referring to so that I can look into them ?

**Comment by V-G-spec** [comment]
Let me check the logs and get back to you

**Comment by V-G-spec** [comment]
Looks great. Merging your PR. Thanks for your contribution!

**Pull request merged**
