### PR TITLE
close #19092

### LINKED ISSUE #19092: softmax

### PR DESCRIPTION
**Pull request by huzi6181**
close #19092

### CODE REVIEW

**Comment by tomatillos** [comment]
Hi, thanks! It's probably better if you only do the dtype conversion at the end, I don't think we need to do it twice

**Comment by huzi6181** [comment]
@tomatillos Ive removed the first dtype conversion, all tests are passing on pycharm. please review

**Comment by tomatillos** [comment]
If you can resolve the merge conflicts we can get this merged, should be able to do it by `command line instructions`

**Comment by huzi6181** [comment]
@tomatillos third times the charm! please review

**Comment by tomatillos** [comment]
Woah, we don't want all of these other past commits, you should only change the code in the two relevant files. Maybe open a new PR and just add the function + tests?

**Pull request closed without merging**
