### PR TITLE
Solved_Descriptions_Problems

### PR DESCRIPTION
**Pull request by krishna1111111**

### CODE REVIEW

**Review by VedPatwardhan — COMMENTED** [review]
Hey @krishna1111111, I don't think we should add descriptions this manner, as docstrings and other comments dividing into should be sufficient to explain the code. In case you're interested in docstrings and stuff, feel free to check out the open tasks for [Function Reformatting](https://lets-unify.ai/ivy/contributing/open_tasks.html#function-formatting). Thanks 🙂

**Comment by krishna1111111** [comment]
should i now change to its ok for now ?

**Comment by VedPatwardhan** [comment]
Yeah it may help in the short term, but these comments would be difficult to maintain, which is why we've instead added a [`Deep Dive`](https://lets-unify.ai/ivy/deep_dive.html) to the docs as an alternative, where we've tried to explain the purpose and functionality of all aspects of Ivy. Feel free to contribute to it if there are any improvements! Thanks @krishna1111111 🙂

**Comment by krishna1111111** [comment]
In my point of you i can say if these are used in short term than these are also for benefits only but I got your point.... please recommend me what else is better...? Apart from this because I have seen many people using this things and are very useful for them and are very beneficial for big organisation also ...all we need is benefits , and those benefits from where we get is best 🙂. Thanks

**Comment by VedPatwardhan** [comment]
> In my point of you i can say if these are used in short term than these are also for benefits only but I got your point.... please recommend me what else is better...? Apart from this because I have seen many people using this things and are very useful for them and are very beneficial for big organisation also ...all we need is benefits , and those benefits from where we get is best 🙂. Thanks

Hey @krishna1111111, in case your interested in contributing to docstrings and other documentation related stuff, feel free to contribute to the [Deep Dive](https://lets-unify.ai/ivy/deep_dive.html) or [Function Reformatting](https://lets-unify.ai/ivy/contributing/open_tasks.html#function-formatting) based on the tasks open . Thanks 🙂

**Comment by krishna1111111** [comment]
Can you please help me in this case ?

**Comment by krishna1111111** [comment]
Should I only look into the function reformatting?

**Comment by VedPatwardhan** [comment]
Not necessarily, you could look into any of the [open tasks](https://lets-unify.ai/ivy/contributing/open_tasks.html). Of course, any fix to the docs would also be appreciated 🙂

**Comment by krishna1111111** [comment]
Please check the once is this ok for the description like has mentioned in docs. I think this description manner ok. So please merge this and proceed the process

**Review by VedPatwardhan — COMMENTED** [review]
Hey @krishna1111111, as I mentioned before, we shouldn't be adding these types of description comments to files as they'll be hard to maintain, but feel free to work on the open tasks. Thanks 🙂

**Comment by VedPatwardhan** [comment]
Just removed my review request as @jkeane508 is assigned to this PR, thanks 🙂

**Pull request closed without merging**
