### PR TITLE
triu

### LINKED ISSUE #21607: triu
todo list: #3612

### PR DESCRIPTION
**Pull request by NiteshK84**
# PR Description 
adds triu function in torch frontend

## Related Issue 

Close #21607

## Checklist 

- [ x] Did you add a function?
- [x ] Did you add the tests?
- [ x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by umairjavaid** [comment]
The tests are not passing. Kindly fix these 
```
E   ivy.utils.exceptions.IvyBackendException: numpy: nested_map: numpy: nested_map: torch: nested_map: torch: nested_map: torch: as_ivy_dtype: Cannot convert to ivy dtype. uint32 is not supported by PyTorch backend.
E   Falsifying example: test_torch_triu(
E       frontend='torch',
E       on_device='cpu',
E       backend_fw='tensorflow',
E       dtype_x=(['uint32'], [array([[0]], dtype=uint32)]),
E       diagonal=0,
E       frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.torch', framework_init_module='torch', init_name='tensor', method_name='triu'),
E       method_flags=FrontendMethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E           precision_mode=False,
E           test_compile=False,
E       ),
E       init_flags=FrontendMethodTestFlags(
E           num_positional_args=0,
E           as_variable=[False],
E           native_arrays=[False],
E           precision_mode=False,
E           test_compile=False,
E       ),
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.7', b'AXicY2RkYAAiKIEEAABvAAU=') as a decorator on your test case
```

**Review by umairjavaid — CHANGES_REQUESTED** [review]
The test is not passing. Kindly add uint32 in the unsupported dtypes decorater for the triu function in the torch backend

**Comment by umairjavaid** [comment]
please fix the merge conflicts

**Review by umairjavaid — CHANGES_REQUESTED** [review]
The test is not passing. Kindly add uint32 in the unsupported dtypes decorater for the triu function in the torch backend

**Comment by NiteshK84** [comment]
@umairjavaid 
fixed dtype issue and resolved conflicts.
Thanks

**Comment by NiteshK84** [comment]
Hi @umairjavaid, i am ready for the review,
Thanks

**Comment by umairjavaid** [comment]
Great work! It seems alright, I'm merging it =)

**Pull request merged**
