### PR TITLE
add torch pairwise_distance

### PR DESCRIPTION
**Pull request by jonaspptawat**
Add Distance functions to PyTorch Frontend https://github.com/unifyai/ivy/issues/25

### CODE REVIEW

**Comment by jonaspptawat** [comment]
https://github.com/unifyai/ivy/issues/6995

**Comment by jonaspptawat** [comment]
@DragosStoican I have recently fixed some floating point accuracy error. I have locally tested on my  PC and all tests were passed! Thank you so much for your time, Have a good day.

**Comment by jonaspptawat** [comment]
Looking forward for your review🥺

**Comment by jonaspptawat** [comment]
I'm looking forward for your review 🥺 @DragosStoican

**Comment by DragosStoican** [comment]
Hi @jonaspptawat, I'm having a look today, sorry for the wait, and thanks for your contribution!

**Comment by jonaspptawat** [comment]
It's okay. Thank you for your reply and take ur time to review my code. Have a good day sir😁

**Comment by DragosStoican** [comment]
Hi @jonaspptawat the frontend tests should cover all the function arguments. Your test is missing the `eps` argument. Could you add that in and see if the test is still passing? 😄

**Comment by DragosStoican** [comment]
Also🙂 , I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

**Comment by DragosStoican** [comment]
> 

Oh, it's not affecting the computation, I see it now 😅 My bad

**Comment by jonaspptawat** [comment]
Thank you so much @DragosStoican ! I will read through the link that you gave me.

**Pull request merged**
