### PR TITLE
feat: added paddle chunk instance method

### LINKED ISSUE #24169: chunk

### PR DESCRIPTION
**Pull request by olaoluwaidowu**
# PR Description
implemented paddle Tensor instance chunk method

#24169

## Related Issue

Close #24169

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Daniel4078** [comment]
ivy-gardener

**Review by Daniel4078 — APPROVED** [review]
Looks good to me.

**Comment by Daniel4078** [comment]
I forget to remind you to add a test(here https://github.com/unifyai/ivy/blob/main/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py) for the instance method you added, my bad.

**Comment by olaoluwaidowu** [comment]
> I forget to remind you to add a test(here https://github.com/unifyai/ivy/blob/main/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py) for the instance method you added, my bad.

Sure, I'll do it. Should I create a separate pull request for this?

**Comment by Daniel4078** [comment]
> > I forget to remind you to add a test(here https://github.com/unifyai/ivy/blob/main/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py) for the instance method you added, my bad.
> 
> Sure, I'll do it. Should I create a separate pull request for this?

You should. Thank you for your understanding.

**Comment by olaoluwaidowu** [comment]
What issue should I reference?

**Comment by Daniel4078** [comment]
> What issue should I reference?

same as this one.

**Comment by olaoluwaidowu** [comment]
Okay, I will do. Thanks

**Pull request merged**
