### PR TITLE
[torch frontend] Add torch frontend function `median`

### LINKED ISSUE #13211: median
Implement median reduction operation for the PyTorch frontend.

### PR DESCRIPTION
**Pull request by JasirZaeem**
closes #13211 

Added median function to the torch frontend with accompanying test
https://pytorch.org/docs/stable/generated/torch.median.html

Note: Default value for the `dim` argument is `-1`

### CODE REVIEW

**Comment by MuhammadSaeedBatikh** [comment]
lgtm. Thanks @JasirZaeem for your PR.

**Comment by mohamedehab0999** [comment]
@JasirZaeem , @MuhammadSaeedBatikh I think the output should contain 2 Arrayes. The first tensor will be populated with the median values and the second tensor, which must have dtype long, with their indices in the dimension dim of input.
https://pytorch.org/docs/stable/generated/torch.median.html

**Comment by JasirZaeem** [comment]
@mohamedehab0999 You are right, when reducing across an axis indices are returned as well in a named tuple, this will have to be done using ivy's kthvalue instead of median I missed that. Should I create a new PR directly with the correct behaviour that references the existing issue #13211 , or make an issue for this first ?

**Comment by MuhammadSaeedBatikh** [comment]
Thanks a lot @mohamedehab0999 for pointing this out. 
Yes @JasirZaeem, please create a new PR and a new tracking issue.

**Pull request merged**
