### PR TITLE
math.py and raw.ops changes

### LINKED ISSUE #13138: acosh

### PR DESCRIPTION
**Pull request by DICEYCorpo**
Close #13138

### CODE REVIEW

**Comment by DICEYCorpo** [comment]
- [ ] #13138

**Comment by valeriocost** [comment]
Hello @DICEYCorpo, you should add a comprehensive test. Take a look here https://lets-unify.ai/ivy/overview/deep_dive/ivy_frontends_tests.html 😄

**Comment by DICEYCorpo** [comment]
@valeriocost I updated as you asked for. Kindly check :D

**Comment by valeriocost** [comment]
I think that the range of `[-1, 1]` is a bit narrow. Take a look at both the Ivy and tf documentation https://lets-unify.ai/ivy/docs/functional/ivy/ivy.functional.ivy.elementwise.html#ivy.functional.ivy.elementwise.acosh https://www.tensorflow.org/api_docs/python/tf/math/acosh. The range should be at least `[-1, +inf]`. Also, the type should numeric because this function is not limited to floats 😄

**Comment by DICEYCorpo** [comment]
Hey @valeriocost kindly check the latest update. :D Changed the type to numeric and the range is also widened.

**Comment by valeriocost** [comment]
As you can see, a test is failing. I think it might be due to `math.inf`. Maybe you can just avoid defining a minimum and a maximum value, I think the test won't fail in that case. Just check how other tests are implemented 😄

**Comment by valeriocost** [comment]
LGTM 👍🏼 ready to be merged!

**Pull request merged**
