### PR TITLE
Added dot function

### PR DESCRIPTION
**Pull request by Lucky-Mahlangu**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Lucky-Mahlangu** [comment]
Hi can you assist in reviewing the code. I am only making a pull request of the dot function. Excluding the tests. I seek guidance with regards to the failing tests.

**Comment by Lucky-Mahlangu** [comment]
Hi @nathzi1505 can you assist with reviewing the above checks ? I need guidance with regards to the failing tests. Thanks.

**Comment by nathzi1505** [comment]
> Hi @nathzi1505 can you assist with reviewing the PR checks ? I need guidance with regards to the failing tests. Thanks.

Just follow the guide mentioned. 
Don't have to worry about other failing checks.

**Comment by nathzi1505** [comment]
Also, please add the link to the issue you created.

**Comment by Lucky-Mahlangu** [comment]
Closes #21459

**Comment by Ishticode** [comment]
The dot function implementation is not accopmpanying the test here? ☺️

**Pull request merged**
