### PR TITLE
Formatted code and added doc strings

### PR DESCRIPTION
**Pull request by Siddhesh-Agarwal**
- formatted the entire repository with `isort` followed by `black`
- added examples in docstrings in fww places

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by simonetgordon — CHANGES_REQUESTED** [review]
Hi there,

Apologies for the delay in the review, this PR must have slipped through the cracks somehow 😅 

Please pull changes from master so the proper diff can be shown in 'Files Changed'.

Also, could you please link the issue you are fixing by commenting 'Closes #<Issue num>'.

Thanks!

Simone

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
