### PR TITLE
updated _compute_cost_and_update_grads function to specifications (Close  #18275)

### LINKED ISSUE #18275: cost_fn_with_variables

### PR DESCRIPTION
**Pull request by rereversed**
- followed the 4 steps including referring back to the deep dive page
- replaced lambda with a nested function 'cost_fn_with_variables' (parameter v)inside the main function 
- added doctoring with example based off the sections provided in deep dive.

not sure if I should have put any decorators, also this is my first time using GitHub, the whole repo is so intuitive!

Close #18275

### CODE REVIEW

**Comment by aparajith21** [comment]
Hey @rereversed 🙂, thanks for contributing! But could you edit the description with `Close #Issue_number`, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues) so everything's properly linked and we know what's being changed and for what purpose.

**Comment by rereversed** [comment]
close #18004

**Comment by rereversed** [comment]
> Hey @rereversed 🙂, thanks for contributing! But could you edit the description with `Close #Issue_number`, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues) so everything's properly linked and we know what's being changed and for what purpose.

Thanks for reminding me, totally missed it ! What should I do now?

**Comment by rereversed** [comment]
open #18004

**Comment by rereversed** [comment]
Closes #756

**Comment by rereversed** [comment]
Close #18275

**Comment by rereversed** [comment]
add_reformatting_checklist_meta

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
