### PR TITLE
added unravel_index

### LINKED ISSUE #10421: unravel_index
unravel_index

### PR DESCRIPTION
**Pull request by rajshukla1102**
Close #10421

### CODE REVIEW

**Comment by rajshukla1102** [comment]
@aditya-hari can you please review my pr!

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @rajshukla1102 

Would you resolve the merge conflicts so I can be able to run tests.

Thanks

**Comment by rajshukla1102** [comment]
@hirwa-nshuti I have resolved the merge conflicts. can you look it once!

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey would you check your unit tests
They're still failing for other backends except the numpy one😊

**Comment by rajshukla1102** [comment]
@hirwa-nshuti hey I am trying to resolve unit test but for every backend test I am getting the error 
`AssertionError: The length of results from backend jax and ground truthframework numpy does not match` can you help me in this?

**Comment by hirwa-nshuti** [comment]
Hey @rajshukla1102 
Would you close this PR and copy your changes to a new one the last changes made to the repo, introduced a lot of conflicts which can't be fixed from this PR. Tag me in the next PR you'll open I'll then have a look at your tests and help out

Thanks😊

**Pull request closed without merging**
