### PR TITLE
Reformat elementwise minimum

### LINKED ISSUE #1751: minimum

### PR DESCRIPTION
**Pull request by SaadHasib**
Closes #1751

### CODE REVIEW

**Comment by simonetgordon** [comment]
Hi Saad, 

I believe your proper PR addressing this issue has been merged: https://github.com/unifyai/ivy/pull/1750.

Can this PR be closed?

Simone

**Comment by simonetgordon** [comment]
Ah, indeed you're right. My apologies! @Ishticode can review this now.

**Comment by SaadHasib** [comment]
No worries, apologies for causing any confusion.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @SaadHasib 
Thank you for the PR 😊 and sorry for the confusion above.
As I understand you are adding examples with `ivy.Container` input. Could you kindly leave the examples previously added unchanged **unless** there was a reason to change then. In that case a brief explanation will be much appreciated. Please let me know in any case and any other questoin you might have. Thanks a lot : )

**Comment by SaadHasib** [comment]
The previous examples had inputs for `ivy.Array`, `ivy.NativeArray` and `Number` inputs, which is covered by the `Union` of these types. So only the examples of `ivy.Array` are kept and `ivy.Container` is added.

This is pointed out in [Docstring examples](https://lets-unify.ai/ivy/deep_dive/12_docstring_examples.html#ivy-add) for the `ivy.add` method, _"Ignoring the union over `ivy.Array` and `ivy.NativeArray` which is covered by points 6 and 7"_

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @SaadHasib Thanks for clarifying 😊
Could you also reformat the function `minimum` in the backends (such as adding type hints).
When I checked minimum in the `numpy` backend it didn't seem formatted.
Please feel free to ask anything else and request a review when changes are made. Thank you 😊

**Comment by SaadHasib** [comment]
I've added type hints, consistent with other types in the files for numpy, tensorflow, and pytorch.
Type hints for jax are already present and mxnet uses a lambda function.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @SaadHasib 
Great. just two small requests. Could you put all arguments for backend functions on newlines the way it is done in ivy and also make sure the lint tests are passing... Dw about the other tests unless I specify. 
I think after that I can merge your PR. Thank you 😊

**Comment by SaadHasib** [comment]
I've added arguments on new lines for numpy, tensorflow, pytorch and jax, and used union types as are being used in the other functions of the files.
Lint tests are passing

**Review by Ishticode — APPROVED** [review]
Perfectly done. 
Will get it merged now. Thank you very much for your contribution😊

**Pull request merged**
