### PR TITLE
set_min_denominator

### PR DESCRIPTION
**Pull request by DragosStoican**
#2840

### CODE REVIEW

**Comment by ZoeCD** [comment]
Hi! To make reviewing easier, we make a checklist of the things that need to be done in the reformatting task. Could you please follow the steps that are [here](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#formatting-checklist)? We would really appreciate it 😊

**Comment by DragosStoican** [comment]
add_reformatting_checklist_general

**Comment by DragosStoican** [comment]
I hope this is alright 😄 Can you have a look at reviewing it? Thanks!!

**Comment by ZoeCD** [comment]
Thank you for your contribution! 😊

**Pull request merged**
