### PR TITLE
Added code for one_hot #9011

### LINKED ISSUE #9011: one_hot

### PR DESCRIPTION
**Pull request by jaygala223**
Fixes #9011

### CODE REVIEW

**Comment by jaygala223** [comment]
Hi @ukj02 I am working on this issue. Are you working on it too?

**Comment by ukj02** [comment]
Hi @jaygala223 , thank you for your contribution!

Some of the TensorFlow tests for one_hot are still failing, can you check what tests are failing and fix them accordingly.

Thank! 😄

**Comment by jaygala223** [comment]
Yes. I am working on it and will submit a fix by tomorrow

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
