### PR TITLE
feat: Implemented Logcumsumexp on the paddle frontend

### LINKED ISSUE #23525: logcumsumexp

### PR DESCRIPTION
**Pull request by Ashkewww**
# Implemented logcumsumexp on the paddle frontend

## Related Issue

Implemented logcumsumexp function on the paddle frontend and wrote the tests for it. Having some trouble with making the tests run for other frameworks as this function is not available in any other framework. 

close #23525 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials:

X -> https://twitter.com/AYUSHCHANDAN201?t=asetQReurkFZ24PVTO9HKQ&s=09

### CODE REVIEW

**Comment by saeedashrraf** [comment]
ivy-gardener

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @Ashkewww , thank you for your contribution. It seems like the tests are still not passing for the implemented function. Can you take a look and try to fix this? Let me know if you face any issues. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
