### PR TITLE
isreal #8892

### LINKED ISSUE #8892: isreal

### PR DESCRIPTION
**Pull request by dmegkos**
Close #8892

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by dmegkos** [comment]
Hi, any updates on this PR? Thanks!

**Comment by abdrahmandiab** [comment]
Hi @dmegkos , apologies for the late reply on this PR!
Will be leaving a review by today or tomorrow hopefully so please stay tuned! :)

**Review by abdrahmandiab — CHANGES_REQUESTED** [review]
Hi @dmegkos , it seems you have not implemented the implementation for the function itself? 
You should implement the function `isreal` [here](https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/numpy/logic/array_type_testing.py). 😅

**Comment by dmegkos** [comment]
> Hi @dmegkos , it seems you have not implemented the implementation for the function itself? You should implement the function `isreal` [here](https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/numpy/logic/array_type_testing.py). sweat_smile
> 
> The function should behave exactly like [`numpy.isreal`](https://numpy.org/doc/stable/reference/generated/numpy.isreal.html#numpy.isreal) but should be implmented using ivy functions.
> 
> Hope that clears things up a bit blush

Hi @abdrahmandiab, perhaps I implemented the function in the wrong python file, apologies as I'm quite new to the open source approach, Ivy is my first contribution :D Let me try few changes, thank you!

**Comment by dmegkos** [comment]
Hi @abdrahmandiab, it seems that the code was placed in the right file. I implemented the function using ivy.isreal(). I also added @handle_numpy_casting_special. Is there something I'm missing? When I test the new function using the examples found in [numpy.isreal](https://numpy.org/doc/stable/reference/generated/numpy.isreal.html#numpy.isreal), I get the same results.

**Comment by abdrahmandiab** [comment]
> Hi @abdrahmandiab, it seems that the code was placed in the right file. I implemented the function using ivy.isreal(). I also added @handle_numpy_casting_special. Is there something I'm missing? When I test the new function using the examples found in [numpy.isreal](https://numpy.org/doc/stable/reference/generated/numpy.isreal.html#numpy.isreal), I get the same results.

Hi @dmegkos 
Could you check to see if you have committed and pushed the function implementation itself? As you can see from the [files changed](https://github.com/unifyai/ivy/pull/8895/files) tab, you have only pushed the changes where you implemented the tests, as well as a few changes to the Array api submodule (which should be reverted but that's a different problem 😅 ). The changes where you implemented the function themselves don't seem to have been pushed yet 😅 

Thanks!
Diab

**Comment by dmegkos** [comment]
> > Hi @abdrahmandiab, it seems that the code was placed in the right file. I implemented the function using ivy.isreal(). I also added @handle_numpy_casting_special. Is there something I'm missing? When I test the new function using the examples found in [numpy.isreal](https://numpy.org/doc/stable/reference/generated/numpy.isreal.html#numpy.isreal), I get the same results.
> 
> Hi @dmegkos Could you check to see if you have committed and pushed the function implementation itself? As you can see from the [files changed](https://github.com/unifyai/ivy/pull/8895/files) tab, you have only pushed the changes where you implemented the tests, as well as a few changes to the Array api submodule (which should be reverted but that's a different problem 😅 ). The changes where you implemented the function themselves don't seem to have been pushed yet 😅
> 
> Thanks! Diab

You are right, I think I understand my mistake! Also, for some reason the last commit pulled changes from others, I don't know what went wrong 😅 This whole thing is a mess, I'll try to clean things up. Apologies for this, as I said I'm new to git and open source contribution 😅

**Pull request closed without merging**
