### PR TITLE
close #18160

### LINKED ISSUE #18160: case

### PR DESCRIPTION
**Pull request by norman135**
Would appreciate if I can get help on how we can implement the strict functionality or other improvements that can be made.

close #18160

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by danielmunioz** [comment]
Hi @norman135! Thanks for contributing!

The tests for your function seem to be failing, you mind running those locally and get those passing please?

Also it seems that you are calling `func()` at the end of your function, however the output of `ivy.where` is expected to be an `array`, you can check the [main function implementation](https://github.com/unifyai/ivy/blob/5c763687844db90c6786e8ef203697e14410848f/ivy/functional/ivy/searching.py#L378-L457) for more info on the function, not sure if `where` is the best tool for the job here 🤔 

it looks like you are not testing for the `exclusive` argument here could you add that please?, we should aim to thoroughly test all arguments that are relevant for the function, I also see that you are trying to generate `x` as integers? however the dtype you are generating may not be integer everytime, you can tweak the parameters of the [dtype_and_values](https://github.com/unifyai/ivy/blob/9d0b8e0c5d716f95885572cad27297ffb5670f9e/ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py#L288-L488) helper to generate exactly what you need with a uniform dtype

For more info on Frontend tests check out the [Guide](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#ivy-frontend-tests)!

If you have any questions please feel free to reach out!
Thanks! :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
