### PR TITLE
`paddle.tensor.linalg.cross` frontend

### LINKED ISSUE #16059: cross

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #16059

### CODE REVIEW

**Comment by mobley-trent** [comment]
Hello @MahmoudAshraf97 do you mind reviewing this PR for the Paddle frontend ?

**Comment by mobley-trent** [comment]
Hey @hmahmood24 @hirwa-nshuti 🙂
Do you mind reviewing this PR ?

**Comment by mobley-trent** [comment]
@AnnaTz

**Comment by hmahmood24** [comment]
Everything looks good to merge @mobley-trent 👍🏼 Thanks!

**Pull request merged**
