### PR TITLE
Adding multi_dot function and test in torch frontend

### LINKED ISSUE #11952: multi_dot

### PR DESCRIPTION
**Pull request by abdulasiraj**
close #11952

### CODE REVIEW

**Comment by abdulasiraj** [comment]
Locally, all test cases passed but here they are failing. Can you please point that out?

**Comment by abdulasiraj** [comment]
Hi @vaatsalya123,
Can you please have a look?

**Comment by vaatsalya123** [comment]
Hey @abdulasiraj first of all thanks for contributing to ivy  ,I just went through your PR but noticed that you have accidentally committed the .idea folder which ideally you should not. So could you please revert your changes to the .ivy folder thanks!

**Comment by abdulasiraj** [comment]
Thanks @vaatsalya123.
I'll do that now

**Comment by abdulasiraj** [comment]
Hi, @vaatsalya123 
Can you please have a look now?

**Pull request closed without merging**
