### PR TITLE
Added 'cond' function to tensorflow frontend with testing

### LINKED ISSUE #14575: cond

### PR DESCRIPTION
**Pull request by AbdullahSabry**
Closes #14575 

Hello, 

I closed the pull request #14603 due to stale behaviour and needing to merge from a branch instead of master. This PR is an implimentation of #14575 'cond' function for the tensorflow frontend.

The tests that seem to be failing have to do with other functions. Could this be due to a conflict between 'cond' in tensorflow frontend with 'cond' in "ivy.experimental.linear_algebra" which has completely different characteristics? 

Thanks!

### CODE REVIEW

**Comment by soma2000-lang** [comment]
Hi @AbdullahSabry Can you please run the tests locally and see if they are passing.Also look into the intelligent pr tests which are failing .You can see the error log.

**Comment by AbdullahSabry** [comment]
Hey @soma2000-lang , Sorry for the delayed response I've been a little busy with school. I have tested the PR locally and the tests for `cond` passes, however the tests behave exactly as they do remotely; some fail and they're the exact same ones that do remotely. As I said I believe this is due to the fact that the function name is in conflict with `ivy.cond` in `ivy/experimental/linear_algebra.py`. 

Please let me know what you think, and sorry again for the delay. 

Thanks!

**Comment by AbdullahSabry** [comment]
Hey @soma2000-lang I just did so. It seems like the same issue is still happening :( 

I cannot figure out why a function like `constant` would fail in `test_general_functions.py` in test 15 with the addition of the function `cond`. It doesn't make sense how there is a conflict occuring

**Comment by soma2000-lang** [comment]
@AbdullahSabry Sorry for the delay.Merging this.!

**Pull request merged**
