### PR TITLE
tensorflow frontend - eigvalsh

### PR DESCRIPTION
**Pull request by OmondiVincent**
eigvalsh #3169

### CODE REVIEW

**Comment by sreegandh804** [comment]
Hey @OmondiVincent , could you try and fix the cause of lint errors that are only relevant to the code you added. 🙂

**Comment by OmondiVincent** [comment]
@sreegandh804 Thank you, I'm working on it

**Comment by sreegandh804** [comment]
Hey @OmondiVincent , could you resolve the conflicts?

**Comment by OmondiVincent** [comment]
Hello @sreegandh804, kindly review

**Comment by sreegandh804** [comment]
Hey @OmondiVincent , there don't seem to be any files that have any changes, could you look into that? 😅

**Comment by OmondiVincent** [comment]
Hey @sreegandh804 my issue seems to be solved from another PR, I don't understand why he opened the same issue as mine because I was the first to open the issue. So should I close this PR and open another issue. Kindly give me a way forward.

**Comment by sreegandh804** [comment]
Hi @OmondiVincent , It does look like an issue that was created after you made a PR which has been merged, But since this wasn't your fault, you wouldn't have to make another PR or select another Issue, We will proceed you to the next stage of the application process

**Comment by OmondiVincent** [comment]
Hello @sreegandh804  how should I proceed to the next stage

**Comment by OmondiVincent** [comment]
@ as per the instruction given I should enter the PR link in the questionnaire....how should I proceed

**Comment by OmondiVincent** [comment]
@sreegandh804  as per the instruction given I should enter the PR link in the questionnaire....

**Comment by sreegandh804** [comment]
Hey @OmondiVincent , sorry for the late response, Yes Enter this PR Link, and if you face any issues please do not hesitate to reach out to the ivy team's discord account. 🙂

**Comment by OmondiVincent** [comment]
Hi @sreegandh804 Thank you so much

**Pull request closed without merging**
