### PR TITLE
sqrt

### PR DESCRIPTION
**Pull request by aryanxk02**
The following pull request adds sqrt function for Numpy Frontend. This fixes one of the tasks present in https://github.com/unifyai/ivy/issues/1525

### CODE REVIEW

**Comment by sreegandh804** [comment]
Hey @aryanxk02 , could you get the tests related to the function you selected passing? 🙂

**Comment by aryanxk02** [comment]
Alright @sreegandh804 I will work on it! 🙂

**Comment by sreegandh804** [comment]
@aryanxk02 , sure thing 👍 🙂

**Comment by aryanxk02** [comment]
Hey @sreegandh804 I think someone has previously made a PR for sqrt function.

**Comment by aryanxk02** [comment]
I think I should close this PR!

**Comment by sreegandh804** [comment]
that's true, could you select another function if that's alright with you 🙂

**Pull request closed without merging**
