### PR TITLE
add frontend jax numpy atleast_1d function

### LINKED ISSUE #9302: atleast_1d

### PR DESCRIPTION
**Pull request by Nunyapa**
Close #9302

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Mostly looks good. Can we just change the flags. instead of as_variable and native_array, the test should be passed `test_flags` and `test_flags=test_flags` to `test_frontend_function`.
this should replace the as_variable, num pos, native array and without flags. If you want without to be false you should pass `test_without=st.just(False)!`. 

This is not in docs yet and needs to added. so sorry for the confusion.
you can take a look at this test for an example.

**Comment by Nunyapa** [comment]
@Ishticode Thank you:) I've changed the flags in the test function. Should be fine now

**Comment by Nunyapa** [comment]
Hello, @Nightcrab! May you check PR, pls?

**Comment by Nightcrab** [comment]
Merged.

**Pull request merged**
