### PR TITLE
Experimental quantize #13648

### PR DESCRIPTION
**Pull request by evixedor**
added partial solutions for quantize

### CODE REVIEW

**Comment by valeriocost** [comment]
Hello @evixedor, you should implement the function in all supported backends and make sure that all test pass with exhaustive data generation 😄 thanks!

**Comment by evixedor** [comment]
Hello, I just wanted to indicate that I am in a part Canada (Les Coteaux) that just experienced an Icey Rain that has disrupted electricity for over 3 days now. I have had difficulty making progress with this task. It is my hope that things be restored back as soon as possible. At the moment, I can only have access to electricity by taking 30mins trips to locations slightly affected in order to charge my devices and make research progress. In any case, I'll continue to work on this issue until it is done. I thought I should make this post if there was any concern with my inactivity recently.

**Comment by valeriocost** [comment]
@evixedor if you prefer I can close this PR and you can pick another open task whenever it is more convenient for you 😄 thanks!

**Comment by evixedor** [comment]
@valeriocost  Oh no. No need to close it. The situation should be resolved sometime this week. In the mean time, I'll continue making the little trips to get as much as I can done. Thank you.

**Comment by valeriocost** [comment]
Great 😄

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by evixedor** [comment]
I would like to continue working on this. Thank you.

**Comment by valeriocost** [comment]
take your time, thanks 😄

**Comment by evixedor** [comment]
I would like to continue working on this

**Pull request closed without merging**
