### PR TITLE
Add isin torch frontend

### PR DESCRIPTION
**Pull request by simoneVU**

### CODE REVIEW

**Comment by simoneVU** [comment]
Resolves #3917

**Review by MarShaikh — CHANGES_REQUESTED** [review]
could you resolve the merge conflicts and rerequest for a review? Thanks!

**Review by MarShaikh — CHANGES_REQUESTED** [review]
Hi! There seems to be some linting errors that need fixing, and the `test_comparison` function has a syntax error at `L:604`. You can fix the first linting errors by just using `pre-commit`, for more info, check out the `pre-commit` section of the docs!

**Comment by simoneVU** [comment]
I was trying to update my branch with the current changes but I am not sure whether it worked. The tests suite on my laptop works, weirdly it seems that it does no pass the tests here. Could you please help me?

**Review by MarShaikh — CHANGES_REQUESTED** [review]
It seems like the update affected a number of files. Can you please only push the changes that you made. I think the merge from upsteam wasn't done properly? In any case, please update and re-request for a review. Thanks!

**Comment by simoneVU** [comment]
I think that now it should be fixed. Just out of curiosity, how am I supposed to do the upstream with the main branch without pushing all the changes the other people did in my pull request?  Remotely it passed all the test for the _comparison_ops.py_

**Review by MarShaikh — APPROVED** [review]
LGTM!

**Pull request merged**
