### PR TITLE
feat: add rfft for JAX frontend

### LINKED ISSUE #23800: rfft

### PR DESCRIPTION
**Pull request by SenayGe**
# PR Description

Implemented rfft for JAX frontend

## Related Issue

Close #23800

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by KevinUli** [comment]
Hi @SenayGe , the PR looks good. One small thing, could you discard the changes made on the demo_conf.py file? After that I can merge the PR. Thanks!

**Comment by SenayGe** [comment]
> Hi @SenayGe , the PR looks good. One small thing, could you discard the changes made on the demo_conf.py file? After that I can merge the PR. Thanks!

Hi @KevinUli, thanks for reviewing the PR. The original submodule file was modified after I opened the PR. I have updated it now to sync the changes. Thanks!

**Comment by SenayGe** [comment]
Hi @KevinUli, can you have a look? I have addressed what you pointed out and I think it looks good.
Thanks!

**Comment by KevinUli** [comment]
LGTM! Thanks for the PR 😃

**Pull request merged**
