### PR TITLE
Reformatted array_equal

### PR DESCRIPTION
**Pull request by realgjl**

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @realgjl looks good so far : )
You need to reformat the functions for backends. That won't take much time. All is clarified in [Ivy - Reformatting - Coding Tutorial 01: relu](https://www.youtube.com/watch?v=fHTJEpkkAqY) on Youtube. Hope that is clear! 
Kindly make the changes and request my review and lmk for any issues... : )

**Comment by realgjl** [comment]
Hi @Ishticode : Thank you for your kind notes! I have updated the backend code. Please kindly review.

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi. Could you kindly add a few more cases in the examples, such as when a True value is returned, as well as when its false due to different shape. You can take a look at [numpy's array_equal page](https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html) to see some of these : ).
 
Once done could you explicitly request a review from the side panel? Asking it through the comments doesn't get me notified sometimes. 

Your PR should be ready to merge after the examples hopefully. lmk if any of the above don't make sense. thnx

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hmmm I meant for you to only add examples under ivy/general.py where u added the first example in the docstring for array_equal.  The examples are good, just need to be under ivy only. Sorry if I lead to any confusion. thnx and lmk for any questions. : )

**Comment by realgjl** [comment]
@Ishticode My bad in fact. No worries. I have modified the files. Please kindly check them.

**Review by Ishticode — APPROVED** [review]
Looking good. Thanks a lot for your contribution.... Merging it now. : )

**Pull request merged**
