### PR TITLE
trace #1147

### PR DESCRIPTION
**Pull request by Kirow789**
trace #1147

### CODE REVIEW

**Review by chie2727 — CHANGES_REQUESTED** [review]
Hi @Kirow789 ,
Apologies for the wait in having your PR reviewed.

Just a few changes I have for you to make:

- [ ] 1. Please update function argument by including the `out` variable and also include descriptions for the `Parameters` and `Returns`.
Have a look at lines 2194 to 2216 of this example:
https://github.com/unifyai/ivy/blob/7d510b6cbc71350c6fa22d8273ba5326424eb655/ivy/functional/ivy/elementwise.py#L2194

- [ ] 2. You need to include another functional example under `ivy.Array inputs` that makes use of both `x` and `offset` variables.

- [ ] 3. Please include an `ivy.Container` functional example.

- [ ] 4. For the instance method examples, please change the `ivy.NativeArray instance method` example with a `ivy.Container instance method` example.

- [ ] 5. There's no need to include the lines such as `offset = 0: (default) trace of an array` so you can delete the lines 672, 691 and 699.

**Comment by chie2727** [comment]
Hi @Kirow789 , please leave a comment if you are still working on this task.

**Comment by Kirow789** [comment]
Hi @chie2727, thanks for getting back to me and apologies for the delay in my response. 
Right now I have the following problem with `ivy.Container` functional example:
`ivy.Container(a=ivy.array([[5., 0., 0.], [1., 2., 3.]]), b=ivy.array([[0., 0., 2.], [1., 2., 3.]]))
ivy.trace(x)`

Screen Shot 2022-07-08 at 12 21 50

**Comment by chie2727** [comment]
@Kirow789 , I just tried on my local system and it didn't seem to have any problem.
Could you show me exactly how you have executed the code?

clip_3

**Comment by Kirow789** [comment]
@chie2727, here's the screenshot of my commands in IPython

Screen Shot 2022-07-08 at 12 49 18

**Comment by chie2727** [comment]
@Kirow789 , are you importing ivy from a cloned ivy repository? Or did you install ivy using `pip` (which I don't recommend actually)

**Comment by Kirow789** [comment]
@chie2727, Actually I installed using `pip`. I had some problems installing docker. I think my Mac is too old. Shall I just go ahead and add the functional example output as it is supposed to be?

**Review by chie2727 — CHANGES_REQUESTED** [review]
@Kirow789 I see. Okay for now go ahead and add the correct output.
Also please take a look at the `test-docstrings` check and see why the check is failing and what changes you might need to make!

**Comment by chie2727** [comment]
Hi @Kirow789  , let me know if you are still working on this reformatting task, otherwise I will need to close this PR because of inactivity.

**Pull request closed without merging**
