### PR TITLE
reformatting set_min_base

### PR DESCRIPTION
**Pull request by darius-1234**

### CODE REVIEW

**Comment by darius-1234** [comment]
add_reformatting_checklist_general

**Comment by darius-1234** [comment]
Hi, I am unsure why some tests are failing, I have just edited the relevant docstring

**Comment by darius-1234** [comment]
This PR addresses #3045 set_min_base issue

**Comment by ankitdsi2010** [comment]
The tests are failing for other functions, you don't need to worry about it.

**Comment by ankitdsi2010** [comment]
Thank you for your contribution

**Pull request merged**
