### PR TITLE
eq_ 

### PR DESCRIPTION
**Pull request by mustafaa7med**
eq_ #16246

### CODE REVIEW

**Comment by mustafaa7med** [comment]
Hello @theRealBird, I appreciate your review to this PR.

Thanks in advance.
Moustafa

**Comment by mustafaa7med** [comment]
Any updates please @theRealBird

**Comment by theRealBird** [comment]
Hello @mustafaa7med, thank you so much for contributing to Ivy. I will have a closer look at your PR very soon. Thank you for your patience.

**Comment by theRealBird** [comment]
Thank you for contributing to Ivy! Merging this PR now.

**Pull request merged**
