### PR TITLE
torch linalg cond function

### LINKED ISSUE #10131: cond
Implementation of frontend api for torch.linalg.cond

### PR DESCRIPTION
**Pull request by shubham303**
Close #10131

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by nathzi1505** [comment]
Hey @shubham303, apologies for the delay.
Thank you so much for the commits :D.
I see that there are some merge conflicts that needs to be resolved.
Would you mind taking a pull of the current version of the repository them and rechecking again?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
