### PR TITLE
feat: add inverse_stft tensorflow frontend

### LINKED ISSUE #21761: inverse_stft

### PR DESCRIPTION
**Pull request by Dharshannan**
Close #21761

### CODE REVIEW

**Comment by Dharshannan** [comment]
This PR is for the inverse_stft implementation.

**Comment by Dharshannan** [comment]
Issue #21761, still working on implementing stft into functional API, will do the same with inverse_stft and then update this PR.

**Comment by joaozenobio** [comment]
Hi @Dharshannan ! Thanks for the PR :smile: It seems you still working on the solution. Please pin me if you need a review

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
