### PR TITLE
arccosh

### LINKED ISSUE #3260: arccosh

### PR DESCRIPTION
**Pull request by saenznicolass**
Fixes #3260

### CODE REVIEW

**Review by RashulChutani — COMMENTED** [review]
Hi @saenznicolass, Can you mention the issue#, which tracks the PR? Thanks.

**Comment by saenznicolass** [comment]
Hi @RashulChutani. It is done, thank you.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @saenznicolass, Good Work. I see a waning related to your function (arccosh) in the Numpy Frontend Tests. Can you try resolving it?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
