### PR TITLE
adding asarray_chkfinite method and test

### LINKED ISSUE #13857: asarray_chkfinite

### PR DESCRIPTION
**Pull request by abdulasiraj**
closes #13857

### CODE REVIEW

**Review by ndurumo254 — CHANGES_REQUESTED** [review]
Hello @abdulasiraj, Thanks for your contribution. Your implementation looks good, but the unit tests are failing. If you fix them, then I will go ahead and merge your PR. Thanks

**Comment by abdulasiraj** [comment]
Sure. I'll fix them

**Comment by abdulasiraj** [comment]
Hi @ndurumo254,
Tests were failed due to some other reasons. I just re-run tests and they all (PR related) are passing. Can you please have a look?

Thanks

**Comment by abdulasiraj** [comment]
Hi @ndurumo254,
Can you please have a look now?

Thanks!

**Comment by ndurumo254** [comment]
> Hi @ndurumo254, Can you please have a look now?
> 
> Thanks!

@abdulasiraj  hi am reviewing your PR, sorry for the delay

**Comment by ndurumo254** [comment]
looks good to me. Am going to merge

**Pull request merged**
