### PR TITLE
Added tanh function

### PR DESCRIPTION
**Pull request by kanakmi**
- Added tanh function
- Reordered the functions so that they appear in alphabetical order
- Removed unnecessary spaces

This PR addresses the issue #2600

### CODE REVIEW

**Comment by VedPatwardhan** [comment]
hi @kanakmi, please specify the open task you're completing to the concerned ToDo list, so that it can be linked accordingly. Refer the [docs](https://lets-unify.ai/ivy/contributing.html) to understand how that's done. Thanks 🙂

**Comment by VedPatwardhan** [comment]
Hi @kanakmi, please let me know if you're still working on the PR, because otherwise I'll have to close it in a few days due to inactivity. Thanks 🙂

**Comment by kanakmi** [comment]
Hi @VedPatwardhan 
Although adding non-linear activation functions like tanh wasn't mentioned in issue #1569 but I believed it should be and that's why I picked it up. I think I should have asked to do that before adding the pull request. So if you allow me, I would like to take up this issue and also add a frontend test for it.
Thanks
Kanak

**Comment by VedPatwardhan** [comment]
Hi @kanakmi, no problem at all! I'd suggest you pick a function from the ToDo lists and get it assigned to you. If you're okay with it, I'll then close this PR. Let me know what you think. Thanks 🙂

**Comment by VedPatwardhan** [comment]
Hi @kanakmi, no problem at all! We do invite contributions that extend Ivy's functionality, but then I'll suggest you add the Extension label to it and we'll then take a call as to whether or not to merge it based on the workflow mentioned in the [docs](https://lets-unify.ai/ivy/contributing/1_the_basics.html#extensions). For now, I'd suggest you pick a function from the ToDo lists and get it assigned to you. Let me know what you think. Thanks 🙂

**Comment by kanakmi** [comment]
Understood @VedPatwardhan 
I have opened a new issue #2712 and this time I took it from the ToDo list. Do let me know if I can work on it and I am closing this PR.
Thanks
Kanak

**Comment by VedPatwardhan** [comment]
Sure @kanakmi, you can work on that issue provided you get it assigned to you by commenting accordingly on the ToDo list based on the contributor guide. I'll close this PR now. Thanks 🙂

**Pull request closed without merging**
