### PR TITLE
added docstring examples for ones() in creation.py

### LINKED ISSUE #7726: ones

### PR DESCRIPTION
**Pull request by martinvuyk**
closes #7726

### CODE REVIEW

**Comment by martinvuyk** [comment]
Hi @sherry30  could you please review my PR? tx

**Comment by martinvuyk** [comment]
Hi @Daniel4078  could you please review my PR? tx

**Comment by Daniel4078** [comment]
> Hi @Daniel4078 could you please review my PR? tx

Sorry for the wait, I will quickly contact sherry30 about this and in the meantime give you a review.

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Please fix this small error, thank you!
ivy/functional/ivy/creation.py:351 in public function `ones`:
        D412: No blank lines allowed between a section header and its content ('Examples')

**Comment by martinvuyk** [comment]
I tried reading the test-docstrings test logs, but I don't understand what the problem is. Maybe the syntax for the examples I wrote is wrong?

**Review by sherry30 — APPROVED** [review]
The examples look good.
test docstrings are failing for a few other functions, `ones` seem to be passing 👍 
Thanks for the contribution.

**Pull request merged**
