### PR TITLE
Added 3 examples for einops_rearrange function

### LINKED ISSUE #8981: einops_rearrange

### PR DESCRIPTION
**Pull request by Pchatain**
Close #8981

### CODE REVIEW

**Comment by Pchatain** [comment]
add_reformatting_checklist_general

**Comment by Pchatain** [comment]
I'm not sure whether I need to worry about lint errors on files that I didn't edit, and I can't tell if there are lint errors on my code due to lint errors on other code.

Also, I'm not sure why the test-docstrings githtub action is being skipped, so I don't know whether the examples I added to the docstring are passing or not. I'd appreciate any advice or pointers on the above two checklist items! Happy holidays!

**Comment by kurshakuz** [comment]
Hey @Pchatain! You don't have to worry about the errors in files or lines you did not edit! Just make sure your own contribution works and don't produce any errors. 

To check your implementation please check the instructions here https://lets-unify.ai/ivy/deep_dive/docstring_examples.html in the Docstring Tests chapter. This will help you get started. If you have any questions feel free to ask here or in our Discord (probably you can get a response faster there)

**Comment by Pchatain** [comment]
Thanks @kurshakuz! I'm not sure whether the github action itself is getting run. I asked on discord in the todo-list channel, and also asking here. I was able to verify that the docstring tests all pass when I call test_docstrings.py locally in docker. However, the test-docstrings test gets skipped in github actions, which is not the expected behavior according to https://lets-unify.ai/ivy/deep_dive/docstring_examples.html where it says this test should get run on every push. Locally my PR is now ready to be reviewed, and of the actions that actually run it my changes don't cause any github actions to fail.

**Review by kurshakuz — APPROVED** [review]
Hey @Pchatain! I have tested it locally as well and it is passing all tests. I will go ahead and merge your PR. Thank you for your contribution!

**Pull request merged**
