### PR TITLE
added tf.math.bincount to tensorflow frontend, Issue #19712

### LINKED ISSUE #19712: bincount

### PR DESCRIPTION
**Pull request by JyotishnaBaishya**
close #19712

### CODE REVIEW

**Review by AryanSharma21 — COMMENTED** [review]
Implementation looks good, have you run the added the test case in local env ? If yes, please do give a screenshot of running test result

**Comment by JyotishnaBaishya** [comment]
@AryanSharma21 Hi, thanks for the review. I have run the added tensorflow_bincount test locally and ran it using the pytest command from terminal. I am attaching the screenshot for that. Further, I see that tests for tf.math.atanh() has failed here which is not part of my changes.
Bincount_test_ss

**Comment by JyotishnaBaishya** [comment]
@AryanSharma21 Hi, thanks for the review. I have run my added test case tensorflow_bincount using the pytest command from terminal. Further, I see that tests for tf.math.atanh() has failed here.
Bincount_test_ss(1)

**Comment by AryanSharma21** [comment]
That looks good to me as the failure of atanh has nothing to do with your implementation , Its a different function. You can request review from any maintainers of the repo and hence close the issue. Thanks

**Review by AryanSharma21 — COMMENTED** [review]
Hello @vedpatwardhan , Please review and merge if sufficient

**Comment by JyotishnaBaishya** [comment]
Hi @vedpatwardhan , please review the PR.

**Pull request merged**
