### PR TITLE
style: reformat qr

### LINKED ISSUE #23793: qr
Work on 'qr' subtask under 'Reformat linear_algebra'

### PR DESCRIPTION
**Pull request by Bilaerl**
Reformatted the qr function in the linear algebra submodule

## Related Issue

Close #23793

### Socials: 

@bilaerl

### CODE REVIEW

**Comment by Bilaerl** [comment]
add_reformatting_checklist_linear_algebra

**Comment by Bilaerl** [comment]
Github actions seem to be skipping the test-docstring task. And I don't know know what to do about that

**Comment by Bilaerl** [comment]
@JPGoodale Please review this pull request

**Review by HaiderSultanArc — APPROVED** [review]
Looks good to me! Thanks 😄

**Comment by Bilaerl** [comment]
Thank you @HaiderSultanArc 🙂

**Pull request merged**
