### PR TITLE
Added paddle.nn.functional.avgpool1d

### LINKED ISSUE #15055: Add `paddle.nn.functional.pooling` NN Pooling Functions to PaddlePaddle Frontend
Add [NN Pooling Functions](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html) to PaddlePaddle Frontend

> Please keep in mind that the proper way to link an issue to this list is to comment "- [ ] #issue_number" while the issue's title only includes the name of the function you've chosen.

- [ ] avg_pool1d
- [ ] avg_pool2d
- [ ] avg_pool3d
- [ ] max_pool1d
- [ ] max_pool2d
- [ ] max_pool3d
- [ ] adaptive_max_pool1d
- [ ] adaptive_max_pool2d
- [ ] adaptive_max_pool3d
- [ ] adaptive_avg_pool1d
- [ ] adaptive_avg_pool2d
- [ ] adaptive_avg_pool3d
- [ ] max_unpool1d
- [ ] max_unpool2d
- [ ] max_unpool3d

### PR DESCRIPTION
**Pull request by Sar-thak-3**
Closes #15055 

I have added AvgPool1d layer in "ivy/functional/frontends/paddle/nn/functional/Avgpool1d.py" If you require the file to be stored anywhere else, let me know. Also, do let me know if the code is correct, if it is not suggest me the appropriate changes, after that I will also add a test file for the same in test_frontends.
 
And mentors I can't understand the role of [https://github.com/unifyai/ivy/blob/e86a4b36080437040f94e2222a60b8e28ef7428a/ivy/functional/backends/numpy/experimental/layers.py#L357C5-L357C5](url) this condition here. Before this condition, the avg pool matrix obtained is working as needed. 
I request to kindly help me in merging this request.

### CODE REVIEW

**Comment by Sar-thak-3** [comment]
Hi @danielmunio, I am new to Ivy and I don't exactly know the process of pr's for Ivy. Are you assigned as a reviewer for this pr?

**Comment by danielmunioz** [comment]
Hey @Sar-thak-3!

Thanks for contributing to ivy! 🚀 

Yes, I'm your reviewer :), first, it seems that you haven't properly linked this PR with an open task, you need to create an issue referencing the task you wanna work on and then link the PR to the issue, please follow the [ToDo list issues](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) guide and format your PR with those rules!

Also it looks like you wanna work on a frontend task, please take a look at the [Frontend task guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) where you can find the general workflow for a task like this as well as how to properly write and place the functions!

Please feel free to ask any question you may have!
Thanks :)

**Comment by Sar-thak-3** [comment]
Hi @danielmunioz I made the changes you said.
* Changes in backend folders are reverted
* Testing file added in ivy_tests 
* avg_pool1d function is put in its appropriate place

Kindly review now and let me know the changes required!

**Comment by danielmunioz** [comment]
Hey @Sar-thak-3! Thanks for the changes

The tests doesn't seem to be passing however, could you please run them locally and make sure they're passing? The easiest way to run them is by executing the command: `pytest <test_file_path>::<name_of_your_testing_funtion>`

If you have any questions please don't hesitate to let me know!
Thanks! :)

**Comment by Sar-thak-3** [comment]
Hi @danielmunioz , I corrected some mistakes in the code, and now it is working for every test case. Kindly have a look and let me know the changes required.

Thanks a lot for helping!

**Comment by Sar-thak-3** [comment]
@danielmunioz , thanks for your help, this function was already merged by someone else, so I might close this pr.

My other Pr's for frontend functions like max_pool3d and avg_pool2d are still to be reviewed, kindly review them and help me merge them!

**Pull request closed without merging**
