### PR TITLE
Added 'add',  'subtract', 'multiply' to paddle frontend Math

### LINKED ISSUE #15995: multiply

### PR DESCRIPTION
**Pull request by NripeshN**
Close #15995 https://github.com/unifyai/ivy/issues/16000 https://github.com/unifyai/ivy/issues/16001

### CODE REVIEW

**Comment by NripeshN** [comment]
Close #16000

**Comment by NripeshN** [comment]
Close #16001

**Comment by Daniel4078** [comment]
add_frontend_checklist

**Comment by NripeshN** [comment]
Hello, this is my first time here @Daniel4078 . How do I edit the checklist. I am not sure what I should do next.

**Comment by NripeshN** [comment]
add_reformatting_checklist_ Frontend

**Comment by NripeshN** [comment]
add_frontend_tasklist_paddlepaddle

**Comment by NripeshN** [comment]
add_frontend_checklist

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Can you try resolve the merge conflicts in the test_paddle_math file? Thanks.

**Comment by NripeshN** [comment]
> Can you try resolve the merge conflicts in the test_paddle_math file? Everything else is pretty good now, Thanks.

Merge conflicts resolved now

**Review by Daniel4078 — APPROVED** [review]
looks good to me, thanks!

**Pull request merged**
