### PR TITLE
Added abs function for paddlepaddle frontend

### LINKED ISSUE #15976: abs

### PR DESCRIPTION
**Pull request by yashsandansing**
close #15976

### CODE REVIEW

**Comment by yashsandansing** [comment]
Hi @Ishticode could you please review this PR? 
There seems to be just 1 fail which ig is common to all paddlepaddle tasks

**Comment by Ishticode** [comment]
@yashsandansing Thank you very much for the PR. I think this looks good. Should be able to merge when I run the tests. But could u resolve conflicts and tag me. Let me know if you need any help or have any questions. Thank you very much. 🙂

**Comment by yashsandansing** [comment]
Hey @Ishticode I have resolved the conflicts and the PR is ready to be reviewed again

**Review by Ishticode — APPROVED** [review]
Ready to merge. We should be careful not to remove decorators from other functions. Ive added back the decorators for the function `multiply`.
Thank you very much for the contribution @yashsandansing 
🙂

**Comment by yashsandansing** [comment]
Thanks for the merge @Ishticode 
I did try to make sure that I did not remove anything while committing but I guess I must have overlooked it.
Thanks for pointing it out. I'll make sure it won't happen again. :)

**Pull request merged**
