### PR TITLE
atleast 3d extension

### LINKED ISSUE #6886: atleast_3d

### PR DESCRIPTION
**Pull request by raghuveerbhat**
Close #6886
And also fix for test failing for #6883

### CODE REVIEW

**Comment by atakanoc** [comment]
Hey @raghuveerbhat!

This pull request looks great! Just a couple of notes, though. ☺️

1. The typehints for the parameters don't seem to be quite right. Alongside Arrays, a user is able to pass ints, floats and so on directly.
2. There seem to be some changes made to the `test_atleast_2d` even though that function is out of scope for this task. Please revert that.

Once you're done making these changes, feel free to run `merge_with_upstream.sh` on your branch and then push the changes. Thanks! ☺️

**Comment by raghuveerbhat** [comment]
Hi @atakanoc , sorry for the delay in reply.. got caught up in some work. Thank you for your review. I agree with all our comment and have made changes. Let me know if any other changes are required :)

**Comment by atakanoc** [comment]
No worries at all! Thank you again, I'm giving this a check now.

**Comment by atakanoc** [comment]
Looks great, thanks a lot! I think you missed the PyTorch typehints but I've handled that part myself, so no worries.

Have a good one! ☺️

**Pull request merged**
