### PR TITLE
Code Formatting - arrays_equal

### PR DESCRIPTION
**Pull request by KBendo98**
Issue #1105

### CODE REVIEW

**Comment by bicycleman15** [comment]
Hey @KBendo98, the examples are good, but I think they just need a little more editing according to the contributor guidelines [here](https://lets-unify.ai/ivy/contributing/7_docstring_examples.html) and [here](https://lets-unify.ai/ivy/contributing/6_docstrings.html).

Also you do not need to implement `arrays_equal` for all backends since `ivy.arrays_equal` is made up of composition of `ivy.array_equal`. So you can remove those changes 🙂

**Comment by KBendo98** [comment]
> Hey @KBendo98, the examples are good, but I think they just need a little more editing according to the contributor guidelines [here](https://lets-unify.ai/ivy/contributing/7_docstring_examples.html) and [here](https://lets-unify.ai/ivy/contributing/6_docstrings.html).
> 
> Also you do not need to implement `arrays_equal` for all backends since `ivy.arrays_equal` is made up of composition of `ivy.array_equal`. So you can remove those changes 🙂

Thanks for the feedback! I removed the changes and added some additional examples.

**Comment by bicycleman15** [comment]
Hey @KBendo98, the examples are good. Could you please just format them exactly in the way as mentioned in this guide [here](https://lets-unify.ai/ivy/contributing/13_docstring_examples.html)

So that would including heading like:
```
Functional Examples
-------------------

With :code:`ivy.Array` input:
```

I think you get the idea.
Feel free to ask if there's any confusion 🙂

**Comment by KBendo98** [comment]
> Hey @KBendo98, the examples are good. Could you please just format them exactly in the way as mentioned in this guide [here](https://lets-unify.ai/ivy/contributing/13_docstring_examples.html)
> 
> So that would be including heading like this below according to the examples in your docstring:
> 
> ```
> Functional Examples
> -------------------
> 
> With :code:`ivy.Array` input:
> ```
> 
> I think you get the idea. Feel free to ask if there's any confusion 🙂

Hi @bicycleman15, please review my PR when you have time. Thanks!

**Review by bicycleman15 — APPROVED** [review]
LGTM! Thanks for your contribution @KBendo98 🙂

**Pull request merged**
