### PR TITLE
Complex

### LINKED ISSUE #16974: complex

### PR DESCRIPTION
**Pull request by ken-kay**
Adding PyTorch Creation Ops "torch.complex" to Ivy.

This is a partial solution that needs further testing.

Close #16974

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ken-kay** [comment]
Hi, I already have the link to my issue, I used this format:

Close #Issue_number
And in my PR's description, it says:

Close #16974

<https://github.com/unifyai/ivy/issues/16974>

Which links to this issue:

https://github.com/unifyai/ivy/issues/16974

If I linked it incorrectly, could I get more clarification on how to
correct it?

Thanks,

Kenani

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ken-kay** [comment]
Still fixing the failing tests.

**Comment by zhumakhan** [comment]
This fails all the test since `ivy.complex` does not have backend implementations. Another way to implement this frontend function is by composing existing ivy functions so that we won't need backend implementations.
I would suggest creating a complex tensor `ret` of the same shape as `a` and `b`. Then assign real values of `ret` to `a` and imaginary values into `b`

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
