### PR TITLE
added mean to paddle.tensor.stat

### LINKED ISSUE #15426: mean

### PR DESCRIPTION
**Pull request by KSANTHOSH200**
Close #15426

### CODE REVIEW

**Comment by KSANTHOSH200** [comment]
close #15463

**Comment by KSANTHOSH200** [comment]
Hi @theRealBird ,

Can you please review the PR? Would love to get some feedback on this.

Thanks.

**Comment by theRealBird** [comment]
Hi @KSANTHOSH200, thank you for your contribution! Functionality-wise everything looks good to me.😃
However, there are some merge conflicts in this PR. It would be great if you could resolve those and then I would be able to make the merge.

Thanks a lot for your patience and work :)

**Comment by KSANTHOSH200** [comment]
.

**Comment by KSANTHOSH200** [comment]
Hi @theRealBird,

Can you merge this pr?

Thanks.

**Pull request merged**
