### PR TITLE
added torch sub instance method and tests

### PR DESCRIPTION
**Pull request by Nerdward**
#4888

### CODE REVIEW

**Comment by Nerdward** [comment]
Close #4888 

Should all the tests pass before a merge can be made?

**Comment by Nerdward** [comment]
@ankitdsi2010 Should all the tests pass before a merge can happen?
Are there any changes you recommend?

**Review by ankitdsi2010 — CHANGES_REQUESTED** [review]
Fix linting tests add import ivy_np, ivy_torch and Tensor

**Comment by Nerdward** [comment]
@ankitdsi2010 I used the bash script to pull changes from the main branch to my fork. I have made the changes with the lint and tests but it doesn't seem to work.

**Pull request closed without merging**
