### PR TITLE
feat(math): add unique_with_counts_and_squared This commit adds a new function called unique_with_counts_and_squared to the math module. This function computes unique values, their indices, and counts from an input list and and also returns their squared values.  - Added unique_with_counts_and_squared. - Included unit tests for the new function.  Closes #26181

### LINKED ISSUE #26181: reverse_sequence

### PR DESCRIPTION
**Pull request by RichieOrito**
# Add General Functions to TensorFlow frontend

I created a new function that calculates the unique values with counts and also returns their squared values:

## Related Issue
There was a function already created and I had to expound on it adding the squaring of unique counts

Close #26181

## Checklist

- [*] Did you add a function?
- [*] Did you add the tests?
- [* ] Did you run your tests and are your tests passing?
- [* ] Did pre-commit not fail on any check?
- [*] Did you follow the steps we provided?

### CODE REVIEW

**Comment by AnnaTz** [comment]
Hi @RichieOrito, there seems to be some misunderstanding.
The function `unique_with_counts` already exists in our tensorflow frontend [link](https://github.com/unifyai/ivy/blob/02a6b67b1aad8c5f6f36583d8702c48f99652b9f/ivy/functional/frontends/tensorflow/general_functions.py#L630).
The issue you have referenced (#26181) is to add `reverse_sequence`.

**Comment by RichieOrito** [comment]
Hey @AnnaTz 

> Hi @RichieOrito, there seems to be some misunderstanding. The function `unique_with_counts` already exists in our tensorflow frontend [link](https://github.com/unifyai/ivy/blob/02a6b67b1aad8c5f6f36583d8702c48f99652b9f/ivy/functional/frontends/tensorflow/general_functions.py#L630). The issue you have referenced (#26181) is to add `reverse_sequence`.

Hey sorry @AnnaTz what I did is update the `unique_with_counts` with a `unique_with_counts_and_squared`

**Comment by AnnaTz** [comment]
> Hey @AnnaTz
> 
> > Hi @RichieOrito, there seems to be some misunderstanding. The function `unique_with_counts` already exists in our tensorflow frontend [link](https://github.com/unifyai/ivy/blob/02a6b67b1aad8c5f6f36583d8702c48f99652b9f/ivy/functional/frontends/tensorflow/general_functions.py#L630). The issue you have referenced (#26181) is to add `reverse_sequence`.
> 
> Hey sorry @AnnaTz what I did is update the `unique_with_counts` with a `unique_with_counts_and_squared` which returns their squared values

@RichieOrito you need to follow the ToDo lists we have opened for public contributors. `unique_with_counts_and_squared` is not a function in the original tensorflow framework and thus we do not have plans to add it to our frontend.

**Comment by RichieOrito** [comment]
> > Hey @AnnaTz
> > > Hi @RichieOrito, there seems to be some misunderstanding. The function `unique_with_counts` already exists in our tensorflow frontend [link](https://github.com/unifyai/ivy/blob/02a6b67b1aad8c5f6f36583d8702c48f99652b9f/ivy/functional/frontends/tensorflow/general_functions.py#L630). The issue you have referenced (#26181) is to add `reverse_sequence`.
> > 
> > 
> > Hey sorry @AnnaTz what I did is update the `unique_with_counts` with a `unique_with_counts_and_squared` which returns their squared values
> 
> @RichieOrito you need to follow the ToDo lists we have opened for public contributors. `unique_with_counts_and_squared` is not a function in the original tensorflow framework and thus we do not have plans to add it to our frontend.

Hello @AnnaTz I will follow the ToDo lists..its seems i'm a little bit lost. Can you guide me on exactly what I sould be working on ?

**Comment by AnnaTz** [comment]
> > > Hey @AnnaTz
> > > > Hi @RichieOrito, there seems to be some misunderstanding. The function `unique_with_counts` already exists in our tensorflow frontend [link](https://github.com/unifyai/ivy/blob/02a6b67b1aad8c5f6f36583d8702c48f99652b9f/ivy/functional/frontends/tensorflow/general_functions.py#L630). The issue you have referenced (#26181) is to add `reverse_sequence`.
> > > 
> > > 
> > > Hey sorry @AnnaTz what I did is update the `unique_with_counts` with a `unique_with_counts_and_squared` which returns their squared values
> > 
> > 
> > @RichieOrito you need to follow the ToDo lists we have opened for public contributors. `unique_with_counts_and_squared` is not a function in the original tensorflow framework and thus we do not have plans to add it to our frontend.
> 
> Hello @AnnaTz I will follow the ToDo lists..its seems i'm a little bit lost. Can you guide me on exactly what I sould be working on ?

[This](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html) page explains all you need to know about contributing.

**Pull request closed without merging**
