### PR TITLE
Reformated meta submodule function name fomaml_step

### LINKED ISSUE #8890: fomaml_step

### PR DESCRIPTION
**Pull request by saifurrehman4114**
Close #8890

### CODE REVIEW

**Comment by saifurrehman4114** [comment]
add_reformatting_checklist_Reformat meta

**Comment by saifurrehman4114** [comment]
I am struggling to add in the example section in docstring what would be the output of this function and how to calculate it or how it would be computed. These function inputs are very vague and I have read the documentation of this function but was unable to compute it.

Thank you!

**Comment by guillesanbri** [comment]
Hi 🙂 thank you for the contribution and sorry for the late reply! I'll review this now

**Comment by guillesanbri** [comment]
Close #8890

**Comment by guillesanbri** [comment]
Given that this function is for meta learning (https://arxiv.org/abs/1703.03400) it's probably best to define two appropiate cost functions to use in the `inner_cost_fn` and `outer_cost_fn` params. To understand the rest of the parameters, I'd recommend to read through the `_train_tasks` function, hope this helps a bit 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by saifurrehman4114** [comment]
Sure, I will read it and get back to you!

**Comment by saifurrehman4114** [comment]
> 

@guillesanbri Just wanted to ask that inner_cost_fn and outer_cost_fn are included in the params in the docstring I have included. Can you please review that and let me know what things are left and do those and merge the PR. Thanks

**Comment by guillesanbri** [comment]
Hi, seems like the docstring don't have valid functions, just the `Callable` type. The docstring should run fine if executed as an isolated command so probably worth doing that and debugging :slightly_smiling_face:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
