### PR TITLE
Omarragi9 patch 3

### PR DESCRIPTION
**Pull request by omarragi9**
@Aarsh2001

### CODE REVIEW

**Comment by WilliamHirst** [comment]
Hi,
Thanks for making a contribution! 

It seems like you haven’t implemented a test for your function. Please do this.

Also you need to link the PR to the appropriate issue as described in the docs:
https://lets-unify.ai/ivy/contributing/the_basics.html#the-basics

Let me know when this is done 😊

**Comment by omarragi9** [comment]
Close #11502

**Comment by omarragi9** [comment]
@WilliamHirst I have just implemented the test function you are free to review it and suggest any changes.😊

**Comment by WilliamHirst** [comment]
Hi, 
Great thanks! 🙏 

There seems to be some formatting issues. Check them out in the <lint> log.

**Comment by omarragi9** [comment]
@WilliamHirst Hi, Thanks for the fast response. I reviewed the formatting issues and solved them so, you can take a look again on my code.

**Comment by WilliamHirst** [comment]
Great!

There are still some formatting errors. It seems like you are missing some whitespaces. There should be two between each test. Check the log for more details 😊

**Comment by omarragi9** [comment]
@WilliamHirst Hi again, sorry for the inconvenience but i didn't write much test functions , Hope i get it right this time.

**Comment by WilliamHirst** [comment]
Hi again,
Sorry for the delay, I have been very busy lately! Everything looks good and all of your tests are passing. Good job 👏

**Comment by omarragi9** [comment]
@WilliamHirst Thanks a lot for your help and your time.

**Pull request merged**
