### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by ANIRUDH-333**

### CODE REVIEW

**Comment by satakshigarg** [comment]
Thanks @ANIRUDH-333 for your contributions !! Everything looks good to me.
Could you please resolve the conflicts with the branch, then I'll merge the changes successfully.

Thanks !!

**Comment by ANIRUDH-333** [comment]
I am finding it difficult to resolve conflicts and I suspect this is due to the change of branch name from main to master. Can I close this PR and open it again?

**Comment by ANIRUDH-333** [comment]
I have resolved the conflicts. @satakshigarg

**Comment by satakshigarg** [comment]
Apologies @ANIRUDH-333, but I can still see a conflict. Could you please resolve it ?

**Comment by ANIRUDH-333** [comment]
Sorry. Now I see it resolved. @satakshigarg can you merge it now.

**Comment by satakshigarg** [comment]
Done !!
Thank you @ANIRUDH-333

**Pull request merged**
