### PR TITLE
global_norm #7294

### PR DESCRIPTION
**Pull request by Canberkg**

### CODE REVIEW

**Comment by nassimberrada** [comment]
Hi @Canberkg, your implementation looks good to me but i noticed that your PR makes changes to the .idea folder, specifically the ivy.iml and misc.xml files. Could you revert those changes ? Then your PR will be good to merge.
Thanks !

**Comment by Canberkg** [comment]
Sorry about that. I hope everything is okay now.

**Comment by nassimberrada** [comment]
One very last thing before merging, could you correct the lint errors related to your commit ?

**Comment by Canberkg** [comment]
Done. I corrected every lint error caused by my implementation.

**Comment by nassimberrada** [comment]
Perfect, merging then, thank you for your contribution !

**Pull request merged**
