### PR TITLE
Paddle qr

### LINKED ISSUE #20785: qr
Adding the qr function to paddle.tensor.linalg as per the todo issue

### PR DESCRIPTION
**Pull request by yashj8**
Close #20785
qr frontend function and test for the  paddlepaddle linear algebra module
Closes the todolist subtask #20785 
(Previous PR was closed due to merge conflict)

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by yashj8** [comment]
Resolved merge conflicts

**Comment by rishabgit** [comment]
Hi! Thanks for working on this 😄 Could you please take care of the [lint](https://github.com/unifyai/ivy/actions/runs/5715690046/job/15485584960?pr=20893) issues? Looks great otherwise! 

Hope this helps - [pre-commit](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit)

**Comment by yashj8** [comment]
Hi @rishabgit! Thanks a lot for the review! 
I have fixed the formatting with pre-commit and now there are no errors.
Please let me know if something needs further work.

**Comment by yashj8** [comment]
PR was accidentally closed. Restored and reopened.

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hey, I'm getting an odd error on local testing - `ERROR ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_linalg.py - ivy.utils.exceptions.IvyAttributeError: paddle: function_supported_devices_and_dtypes: paddle: function_supported_devices_and_dtypes: 'tuple' object has no attribute 'values'` 

Looks like it was due to a bug on the testing pipeline which was recently fixed, could you please sync your branch with the latest updates?

**Comment by yashj8** [comment]
Thanks for letting me know!
I have synced the branch with the ivy/master branch.

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi, I resolved the issue with incorrect fixtures in testing, but it throws error on qr implementation now. Could you please look into it? Thanks!

**Comment by yashj8** [comment]
Thanks a lot for the changes!
Reg the implementation I cant find anything wrong as of now

I have referred the [Paddle documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/linalg/qr_en.html) and the corresponding [ivy code](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/linear_algebra.py#L1735) for it.

**Comment by rishabgit** [comment]
Hi, your testing fn was off, fixed it now but getting `AssertionError:  the results from backend torch and ground truth framework paddle do not match` which I'm not sure how to fix exactly

@hirwa-nshuti saw your changes [here](https://github.com/unifyai/ivy/commit/03555915ecf02e2ec1c9c94805e575b238a0598a) which I believe deals with similar "issue" with numpy testing? 

Do you have any idea on what could be the ideal workaround here? Already set `rtol=1e-01`

image

**Comment by yashj8** [comment]
Hello @rishabgit 
How should we proceed with it?

Are there some changes I should be trying?

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi! Fixed the issue with testing pipeline, could you please take care of merge conflicts? LGTM to merge otherwise. Thanks! 😄

**Comment by rishabgit** [comment]
Needed slight updates, but LGTM otherwise! Thanks for adding this @yashj8 😄

**Comment by yashj8** [comment]
Thanks for everything @rishabgit! This was my first PR at ivy! 
Sorry for the delay and mess up in the merge conflict. 
Can you please shed some light on what might be going wrong initially (which you fixed with the matrix_is_stable?) Would be helpful later on.

**Comment by rishabgit** [comment]
> Thanks for everything @rishabgit! This was my first PR at ivy! Sorry for the delay and mess up in the merge conflict. Can you please shed some light on what might be going wrong initially (which you fixed with the matrix_is_stable?) Would be helpful later on.

Hey @yashj8, I'll suggest diving into the code of `matrix_is_stable` (especially its docstring) and googling from there if you're unclear about any key word - would explain things much better + exhaustively than I could imo 😄

**Pull request merged**
