### PR TITLE
add asfarray implementation and test

### PR DESCRIPTION
**Pull request by srijamk**
Close #16302

### CODE REVIEW

**Comment by srijamk** [comment]
Hi @satakshigarg! My PR is ready for review if you could take a look at it

**Comment by satakshigarg** [comment]
add_frontend_checklist

**Comment by satakshigarg** [comment]
> Hi @satakshigarg! My PR is ready for review if you could take a look at it

Thank you @srijamk for your PR. However there are few checks which aren't passing for the PR. A comment regarding the same can be found above. Please take a look, and let me know when your PR is ready for review. I would be glad to help.

**Comment by satakshigarg** [comment]
> Hi @satakshigarg! My PR is ready for review if you could take a look at it

Thank you @srijamk for your PR. It looks good to me. 
Looking forward to more such valuable contributions. Best luck !!

**Pull request merged**
