### PR TITLE
feat: Add eigh_tridiagonal to TensorFlow frontend #23634

### LINKED ISSUE #23634: eigh_tridiagonal

### PR DESCRIPTION
**Pull request by NickyGuants**
# PR Description

## Related Issue

Close #23634

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by NickyGuants** [comment]
Hi @Infrared1029  have you had a chance to look at this?

**Comment by Infrared1029** [comment]
Hi @NickyGuants,  i assumed from the checklist you haven't tested the function yet (as it is not checked), looking at the CI logs, it seems the function is failing, can you make sure the tests pass? ill then take a closer look

**Comment by Sarvesh-Kesharwani** [comment]
Please work on fixing the failing test cases 
image
for ex
the returned values from some backends don't match the gt backend, i.e., TensorFlow
image

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
