### PR TITLE
Modify Gradient Descent update function

### PR DESCRIPTION
**Pull request by Accumulated**

### CODE REVIEW

**Comment by Accumulated** [comment]
#2143

**Comment by sherry30** [comment]
Hi,

The test docstrings for `gradient_descent_update` seems to be failing. Can you look into those and try to fix them.

If you have any trouble, I'd be happy to help you out.

Thanks.

**Comment by Accumulated** [comment]
The test docstrings for gradient_descent_update now runs correctly.

**Review by sherry30 — APPROVED** [review]
looks good 

Thanks a lot for the contribution 😄

**Pull request merged**
