### PR TITLE
fix: edited split function and test function 

### LINKED ISSUE #23602: split

### PR DESCRIPTION
**Pull request by mcnugets**
# PR Description
added split function and test function 

## Related Issue

Closes #23602

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?

### CODE REVIEW

**Comment by mcnugets** [comment]
Hi @zaeemansari70 , can you please have a look at my code, especially the test function for split(), i am having a bit of a problem with passing the tests locally. Thank you

**Review by zaeemansari70 — COMMENTED** [review]
Hey, can you specify where are you having trouble while implementing it :slightly_smiling_face:

**Comment by mcnugets** [comment]
Hello, @zaeemansari70 just had trouble passing all the run tests, and I was unsure what issues I had in my code. Do you think my code is ready to merge?

**Comment by zaeemansari70** [comment]
All the tests should be passing, I'd suggest go through our docs https://unify.ai/docs/ivy/overview/deep_dive.html

**Comment by mcnugets** [comment]
Hello @zaeemansari70, can you please help me to identify this error:


```
>       frontend_ret = ins_gt.__getattribute__(frontend_method_data.method_name)(
            *args_method_frontend, **kwargs_method_frontend
        )
E       AttributeError: 'ArrayImpl' object has no attribute 'split'
E       Falsifying example: test_jax_split(
E           frontend='jax',
E           on_device='cpu',
E           backend_fw='numpy',
E           dtype_value=(['int32'], [array([0], dtype=int32)]),
E           indices_or_sections=[1],
E           axis=0,
E           frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.jax.numpy', framework_init_module='jax.numpy', init_name='array', method_name='split'),
E           init_flags=FrontendInitTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           method_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E               precision_mode=False,
E               inplace=False,
E               test_trace=False,
E               generate_frontend_arrays=False,
E           ),
E       )
E       
```

**Comment by mcnugets** [comment]
Hello @zaeemansari70 , can you please help me to identify this error:


```
>       frontend_ret = ins_gt.__getattribute__(frontend_method_data.method_name)(
            *args_method_frontend, **kwargs_method_frontend
        )
E       AttributeError: 'ArrayImpl' object has no attribute 'split'
E       Falsifying example: test_jax_split(
E           frontend='jax',
E           on_device='cpu',
E           backend_fw='numpy',
E           dtype_value=(['int32'], [array([0], dtype=int32)]),
E           indices_or_sections=[1],
E           axis=0,
E           frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.jax.numpy', framework_init_module='jax.numpy', init_name='array', method_name='split'),
E           init_flags=FrontendInitTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           method_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E               precision_mode=False,
E               inplace=False,
E               test_trace=False,
E               generate_frontend_arrays=False,
E           ),
E       )
E       
```

**Comment by Daniel4078** [comment]
> Hello @zaeemansari70 , can you please help me to identify this error:
> 
> ```
> >       frontend_ret = ins_gt.__getattribute__(frontend_method_data.method_name)(
>             *args_method_frontend, **kwargs_method_frontend
>         )
> E       AttributeError: 'ArrayImpl' object has no attribute 'split'
> E       Falsifying example: test_jax_split(
> E           frontend='jax',
> E           on_device='cpu',
> E           backend_fw='numpy',
> E           dtype_value=(['int32'], [array([0], dtype=int32)]),
> E           indices_or_sections=[1],
> E           axis=0,
> E           frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.jax.numpy', framework_init_module='jax.numpy', init_name='array', method_name='split'),
> E           init_flags=FrontendInitTestFlags(
> E               num_positional_args=0,
> E               as_variable=[False],
> E               native_arrays=[False],
> E           ),
> E           method_flags=FrontendMethodTestFlags(
> E               num_positional_args=0,
> E               as_variable=[False],
> E               native_arrays=[False],
> E               precision_mode=False,
> E               inplace=False,
> E               test_trace=False,
> E               generate_frontend_arrays=False,
> E           ),
> E       )
> E       
> ```

I think the correct frontend function you should call is "array_split"(https://github.com/unifyai/ivy/blob/13f2779b7440ca16a82dd7b3c80685f882b32485/ivy/functional/frontends/jax/numpy/manipulations.py#L19) instead of just "split"

**Comment by mcnugets** [comment]
@Daniel4078 Thank you for your message. I changed the frontend functions from 'split()' to 'array_split()', however, the problem still occurs. However, I would like to point out that some of the failed run tests are unrelated to my function implementations:

run test(15):
```
FAILED ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_logic.py::test_jax_isin[cpu-paddle-False-False]
=================== 1 failed, 3 warnings in 75.24s (0:01:15) ===================
Error: Process completed with exit code 1.
```


run test(30)

```
FAILED ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_operators.py::test_jax_exp[cpu-paddle-False-False]
=================== 1 failed, 3 warnings in 69.66s (0:01:09) ===================
Error: Process completed with exit code 1.
```

**Comment by mcnugets** [comment]
Hello @zaeemansari70 @Daniel4078 ,  I would like to ask if I should continue with the task, as I found out that split() 
function is nonexistent in the [jax.array](https://jax.readthedocs.io/en/latest/_autosummary/jax.Array.html)

**Comment by mcnugets** [comment]
> Hello @zaeemansari70 @Daniel4078 , I would like to ask if I should continue with the task, as I found out that split() function is nonexistent in the [jax.array](https://jax.readthedocs.io/en/latest/_autosummary/jax.Array.html)

Im closing this issue due to this reason i commented above

**Pull request closed without merging**
