### PR TITLE
refactor `inv` adjoint=True to work for `N-D` input.

### PR DESCRIPTION
**Pull request by akshatvishu**
- Refactor the `adjoint=True` in `inv`  to work with `N-D` inputs for `NumPy`, `Jax` and `Torch`.
- Added `inv` to TensorFlow frontend and write test.
 
Ran test locally for both changes (test are passing for all backends)

@zaeemansari70  @DragosStoican

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by akshatvishu** [comment]
Found that  the test for `torch.linalg.inv` are failing for `NumPy` backend; on further evaluation I think its due to floating point rounding errors.

Example:
```py
n_p = np.array([[-4.8828125e-04, -7.3242188e-04,  5.6385994e-04],
                [-3.1250000e-02, -1.0000000e+00, -3.5047298e-05],
                [-1.0000000e+00, -2.8000000e+01, -9.7656250e-04]], dtype="float32")

t_a = torch.tensor(n_p, dtype=torch.float32)

a = np.linalg.inv(n_p)
b = torch.linalg.inv(t_a)
print(a)
print(b)
"""
[[ 6.7559831e-02  2.2400699e+02 -8.0002518e+00]
 [-6.4266406e-02 -8.0066528e+00  2.5023928e-01]
 [ 1.7734651e+03  1.8358134e+02 -6.6028666e+00]]
 
 
tensor([[ 9.3754e-02,  2.2401e+02, -8.0004e+00],
        [-6.5066e-02, -8.0068e+00,  2.5024e-01],
        [ 1.7735e+03,  1.8358e+02, -6.6030e+00]])
"""

# Changing the `dtype` to `float64` for same input
"""
[[ 6.75597127e-02  2.24006993e+02 -8.00025153e+00]
 [-6.42664004e-02 -8.00665258e+00  2.50239273e-01]
 [ 1.77346509e+03  1.83581347e+02 -6.60286684e+00]]
 
tensor([[ 6.7560e-02,  2.2401e+02, -8.0003e+00],
        [-6.4266e-02, -8.0067e+00,  2.5024e-01],
        [ 1.7735e+03,  1.8358e+02, -6.6029e+00]], dtype=torch.float64)
""" 
```

**Comment by akshatvishu** [comment]
Hey @Ookamice  if you want some added context on this  `PR` then feel free to check the [linear-algebra](https://discord.com/channels/799879767196958751/1000044022942933112/1126549769897123871) channel at `discord` . Couldn't find your username on `discord` otherwise would've tagged you in-there!

**Comment by Ookamice** [comment]
@akshatvishu 
Digging through torch's repo and [issues](https://github.com/pytorch/pytorch/issues/65557), it looks like it is an issue that was identified but torch chose for more transparent functions over numerical stability. I think your PR is good to be merged now and if later on, this becomes a problem, a quick fix of upcasting and downcasting can be added. 👍

**Comment by akshatvishu** [comment]
Thank you for the review! I too had the same idea as `upcasting` everything to `float64` and then casting the results back to `input_dtype`.

**Comment by akshatvishu** [comment]
Thank you so much @sherry30  for linking the issue !

**Pull request merged**
