### PR TITLE
reformat general inplace_increment #2813

### PR DESCRIPTION
**Pull request by edaehn**
fixed type

### CODE REVIEW

**Comment by edaehn** [comment]
Hi @juliagsy, I have fixed the lint formatting issues. 
Could you please review the changes? 
Thank you very much. 

Best regards, Elena.

**Comment by juliagsy** [comment]
Hey Elena! 

Thanks for the changes and lint fix! Will review and merge in soon if it's ready!

**Review by juliagsy — APPROVED** [review]
Thanks for contributing!

**Comment by edaehn** [comment]
Hi @juliagsy, thanks for the review and merge. 
Have a great day, Elena

**Pull request merged**
