### PR TITLE
Reformatted, function "maximum"

### PR DESCRIPTION
**Pull request by SaadHasib**
Added docstring examples (functional, instance).
Added "Array API Standard" conform string.
Renamed variables in docstring to match argument names.

### CODE REVIEW

**Comment by SaadHasib** [comment]
Reformatted, function "minimum".

**Comment by simonetgordon** [comment]
Hi Saad,

I noticed you have made changes for both max and min functions. Please try to make a PR for only one issue at a time. I am linking both issues with this PR for now, so you don't have to make any changes to fix this for now.

Also, you have examples for both Number and ivy.Array types, but you are missing ivy.NativeArray examples. Please refer to [this](https://lets-unify.ai/ivy/contributing/13_docstring_examples.html#docstring-examples) for further guidance.

Thanks again!

Simone

**Comment by SaadHasib** [comment]
Apologies for mixing multiple issues in this PR. I'll change that in the future.

I'll add examples for `ivy.NativeArray` and comment once done.

Regards.

**Comment by SaadHasib** [comment]
I've added the examples for `ivy.NativeArray` argument types.

Please let me know if any further changes are required.

**Comment by simonetgordon** [comment]
Hi Saad,

Looks good! Thanks 😊 

Kind Regards, 

Simone

**Comment by SaadHasib** [comment]
My pleasure!

**Pull request merged**
