### PR TITLE
Sort method 

### PR DESCRIPTION
**Pull request by bethelhall**

### CODE REVIEW

**Comment by bethelhall** [comment]
@1Doomdie1 Can you please review this PR?

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
Hello @bethelhall , thanks for your efforts. Can you please remove the changes to the .idea folder ?

**Comment by bethelhall** [comment]
> @saeedashrraf, thanks for your review. But I am not sure if I get what you mean. You mean remove the changes from the .idea folder?

**Comment by saeedashrraf** [comment]
It seems like you are trying to commit changes to ivy.iml file. Can you undo these changes only ?

**Comment by saeedashrraf** [comment]
Please, remove the .idea folder from the git ignore list of the project.

**Comment by bethelhall** [comment]
@saeedashrraf I am on it.

**Comment by bethelhall** [comment]
@saeedashrraf I have removed it, but there is also "**/.idea/shelf/" in .gitignore. Should I also remove it?

**Comment by saeedashrraf** [comment]
No, that is fine. Please do not remove anything else from the gitignore. So, only this line is removed 
https://github.com/unifyai/ivy/pull/635/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R24

**Comment by bethelhall** [comment]
@saeedashrraf How about now?

**Comment by bethelhall** [comment]
@saeedashrraf anything else?

**Review by saeedashrraf — CHANGES_REQUESTED** [review]
There seems to be an issue with the tensorflow implementation . Can you try and get that fixed ?

**Comment by bethelhall** [comment]
@saeedashrraf Absolutely. Just wanted to make sure everything else is fixed. Thanks

**Comment by bethelhall** [comment]
@saeedashrraf Can you please help me debug what's going on with the Tenosrflow implementation? I have tried several ways to get around the error but not a chance.

**Comment by saeedashrraf** [comment]
@bethelhall you seem to casting the dtype bool into an array of dtype int32. Is there a reason for that? Also, you are converting the array to a numpy array which you should not be doing. Can you try undoing these two things and see if it fixes the issue ?

**Comment by bethelhall** [comment]
@saeedashrraf 
Somehow the argument passed to the method turns out to be a boolean value and I was checking the dtype and casting it to int32. When I reverted back to the initial state, where I avoid checking the dtype, I get the error below.

And yes, I shouldn't have converted the output to a NumPy array. I did that to help me debug the problem.

Screen Shot 2022-03-23 at 9 06 25 PM

**Comment by saeedashrraf** [comment]
@bethelhall 
The method tf.sort accepts numeric Tensors only as input. So, the input must be cast to a numeric dtype first using tf.cast. But, as mentioned in the [Array API Standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.sorting_functions.sort.html#signatures.sorting_functions.sort), the returned array must have the same data type and shape as x. So, we need to cast the resulting Tensor from tf.sort back to a bool using tf.cast. Feel free to ask again if you are still facing any issues :)

**Comment by bethelhall** [comment]
You mean like this? 
telegram-cloud-photo-size-4-5899936239270869353-y

**Comment by saeedashrraf** [comment]
@bethelhall , Thanks for your effort! It looks good now as the test_sort tests pass successfully.

**Comment by bethelhall** [comment]
@saeedashrraf Awesome. Thanks for the help.

**Comment by bethelhall** [comment]
@saeedashrraf Do I have to close the issue and check this task as completed?

**Comment by saeedashrraf** [comment]
Anytime!
No worries, it's now closed.

**Pull request merged**
