### PR TITLE
Manipulation routines

### PR DESCRIPTION
**Pull request by MelatKebedeAbraham**

### CODE REVIEW

**Review by jkeane508 — COMMENTED** [review]
Hello,

Can you please reference the issue that this PR tackles?

Thanks!
James

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MelatKebedeAbraham** [comment]
Hello, @ jkeane508 
i attempted to create a new PR, but the system notified me that I already have an open one?

**Comment by jkeane508** [comment]
> Hello, @jkeane508 i attempted to create a new PR, but the system notified me that I already have an open one?

Why you are attempting to open a new PR?

**Comment by MelatKebedeAbraham** [comment]
> > Hello, @jkeane508 i attempted to create a new PR, but the system notified me that I already have an open one?
> 
> Why you are attempting to open a new PR?

I need to clarify that the previously created PR was intended for a different ToDo. As a result, I had to suggest an experimental implementation of Ivy.argpartation. This was necessary because the frontend APIs are required to be short, and this particular method requires a longer implementation

**Comment by jkeane508** [comment]
> > > Hello, @jkeane508 i attempted to create a new PR, but the system notified me that I already have an open one?
> > 
> > 
> > Why you are attempting to open a new PR?
> 
> I need to clarify that the previously created PR was intended for a different ToDo. As a result, I had to suggest an experimental implementation of Ivy.argpartation. This was necessary because the frontend APIs are required to be short, and this particular method requires a longer implementation

In this case you should finish with the first PR before attempting to start a new one :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
