### PR TITLE
prod (#12385)

### PR DESCRIPTION
**Pull request by Moamen-Elsayed**

### CODE REVIEW

**Comment by Moamen-Elsayed** [comment]
What is the issue with this PR?

**Comment by Moamen-Elsayed** [comment]
prod #12385

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Your implementation looks good, but you also have to add a test for this function in the `test_frontends` folder to make sure that the implementation is correct.
You can refer to the docs to see how that is done.

Thanks

**Comment by Moamen-Elsayed** [comment]
I have added the test function for Jax.numpy.prod function

**Comment by zaeemansari70** [comment]
Hi, your PR shows changes in files which shouldn't be committed in this PR, as there was a force-push recently, take a look at this announcement, I hope this resolves it :slightly_smiling_face: 
https://discordapp.com/channels/799879767196958751/983684937712558080/1080080255387189318

**Pull request closed without merging**
