### PR TITLE
changes to pooling.py

### LINKED ISSUE #21141: adaptive_max_pool2d

### LINKED ISSUE #21145: adaptive_max_pool3d

### PR DESCRIPTION
**Pull request by MohamedEzzatIsmail**
Close #21141
Close #21145

### CODE REVIEW

**Comment by MohamedEzzatIsmail** [comment]
a

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by a0m0rajab — COMMENTED** [review]
@MohamedEzzatIsmail Hi, thank you for the PR, but the tests should be in a different file. 
Feel free to check the deep dive or previous tasks to see where to add them, 

You can do this changes in this PR without closing it, 
Plus, can you follow the close #ISSUE_NUMBER style in the PR description? 

this will help to automatically close the issues and mark them as done.

**Comment by MohamedEzzatIsmail** [comment]
@a0m0rajab sorry I didn't get it can explain me more

**Comment by a0m0rajab** [comment]
Feel free to check this: [ToDo List Issues](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) and [GitHub Linking issues docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for further details.

**Pull request closed without merging**
