### PR TITLE
Added Interpolate layer Stateful API

### LINKED ISSUE #17945: interpolate

### PR DESCRIPTION
**Pull request by shubham1206agra**
Close #17945

### CODE REVIEW

**Comment by shubham1206agra** [comment]
@juliagsy Can you please review this PR?

**Comment by juliagsy** [comment]
Hey! Apologies for the delayed review, I was checking the tests locally and it was running quite slow on my side. The tests seem to be failing, could you please recheck all the tests and their implementation and make sure that they are passing? Thanks a lot!

**Comment by shubham1206agra** [comment]
> Hey! Apologies for the delayed review, I was checking the tests locally and it was running quite slow on my side. The tests seem to be failing, could you please recheck all the tests and their implementation and make sure that they are passing? Thanks a lot!

The tests failing are related to `ivy.interpolate` implementation (not stateful class implementation) which has quite a few bugs rn. So after this PR merge, I will work on fixing `ivy.interpolate` on another PR

**Comment by juliagsy** [comment]
Ahh I see, thanks for the clarification! Since they're related, would you mind to fix them here instead so that we can make sure both are passing before merging. Thanks!

**Comment by shubham1206agra** [comment]
> Ahh I see, thanks for the clarification! Since they're related, would you mind to fix them here instead so that we can make sure both are passing before merging. Thanks!

Can't do it right now.
As fix requires another PR to be merged to fix area interpolation (#18146 )

See this 
image

**Comment by juliagsy** [comment]
I see, got it now. Since it's already a wip on your side, it's better to do it step by step, I'll keep an eye as well on the referenced PR, but I'll come back once that's merged and we can look into the interpolate refactor. Hope this makes sense! and please feel free to ping me here when the other pr is merged and ready in case I overlooked anything, thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
