### PR TITLE
depthwise_conv2d_backprop_input 

### LINKED ISSUE #1548: Add Neural Network functions for TensorFlow frontend
Add [Neural Network functions](https://www.tensorflow.org/api_docs/python/tf/nn#functions) for TensorFlow frontend:
- [ ] atrous_conv2d
- [ ] atrous_conv2d_transpose
- [ ] avg_pool1d
- [ ] avg_pool2d
- [ ] batch_normalization
- [ ] collapse_repeated
- [ ] compute_average_loss
- [ ] conv1d
- [ ] conv1d_transpose
- [ ] conv2d_transpose
- [ ] conv3d_transpose
- [ ] conv_transpose
- [ ] convolution
- [ ] crelu
- [ ] ctc_unique_labels
- [ ] depthwise_conv2d
- [ ] depthwise_conv2d_backprop_filter
- [ ] depthwise_conv2d_backprop_input
- [ ] dropout
- [ ] embedding_lookup
- [ ] embedding_lookup_sparse
- [ ] erosion2d
- [ ] gelu
- [ ] l2_normalize
- [ ] local_response_normalization
- [ ] log_poisson_loss
- [ ] max_pool1d
- [ ] max_pool2d
- [ ] moments
- [ ] nce_loss
- [ ] normalize_moments
- [ ] pool
- [ ] safe_embedding_lookup_sparse
- [ ] sampled_softmax_loss
- [ ] scale_regularization_loss
- [ ] separable_conv2d
- [ ] sigmoid_cross_entropy_with_logits
- [ ] silu
- [ ] sufficient_statistics
- [ ] swish
- [ ] weighted_cross_entropy_with_logits
- [ ] weighted_moments
- [ ] with_space_to_batch
- [ ] zero_fraction

### PR DESCRIPTION
**Pull request by Bhavit03**
close #1548

### CODE REVIEW

**Comment by Bhavit03** [comment]
Hey @nassimberrada,
My code's failing few of the PR tests,
Can you suggest  me ways to rectify this issue?

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Bhavit03** [comment]
Hey @nassimberrada ,
I've updated the code as per your suggestions and reformatted it, Still some of the cases are failing.
Can you review it again so that it can be merged soon?

**Comment by Bhavit03** [comment]
hey @nassimberrada ,
All the errors are rectified including formatting, except this one:
Failed test case: 27,46,73,128

ivy/utils/exceptions.py:345: in _handle_exceptions
    return fn(*args, **kwargs)
ivy/functional/ivy/nest.py:1260: in nested_map
    return fn(x)
ivy_tests/test_ivy/helpers/function_testing.py:1626: in <lambda>
    lambda x: frontend_config.native_array(x) if isinstance(x, np.ndarray) else x,
ivy_tests/test_ivy/test_frontends/config/torch.py:106: in native_array
    return torch.tensor(x)
E   TypeError: can't convert np.ndarray of type bfloat16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by Bhavit03** [comment]
I've updated the test function, still unable to figure out source of error. Can you give it a check finally?

**Comment by Bhavit03** [comment]
@nassimberrada It's all done I guess!

**Comment by Bhavit03** [comment]
Hey,
Couldn't run the tests locally due to some issue in docker.
I did removed the input_dtype but was still getting errors, can't figure out what's going wrong now.

**Comment by Bhavit03** [comment]
Yeah I've tried that also,
Can't figure out origin of error

**Comment by Bhavit03** [comment]
Thanks for your support!

**Pull request closed without merging**
