### PR TITLE
added empty function torch

### PR DESCRIPTION
**Pull request by elhusseinn**
- [ ] #4301

### CODE REVIEW

**Comment by Oxbeefbabe** [comment]
Hi, apologies for the slow response, I am currently away and have minimal access to the internet! I'll comment when possible, and I should be back to my regular schedule from next week.

This is a good start. Can you please make sure to implement the functionality for all of the optional parameters in the torch.empty function? Also, can you please make sure that testing for these variables is included in your tests?

**Comment by elhusseinn** [comment]
Thanks for you reply, which params haven't I tested for, I think i tested for all params, can I get more clarification please?
thanks.

**Comment by Oxbeefbabe** [comment]
You should implement the parameters for all of the parameters described in the pytorch docs for empty: https://pytorch.org/docs/stable/generated/torch.empty.html. The only two you do not need to implement are pin_memory and memory_format, as these do not change the input/output of the function.

**Comment by elhusseinn** [comment]
The only parameter I didn't implement is the layout parameter, which is related to the memory , every other parameter is implemented and included in the tests.

**Comment by Oxbeefbabe** [comment]
Ok, I've had a closer look and this seems all good to me then. Good job, merging your PR now!

**Pull request merged**
