### PR TITLE
feat: Adds tf.math.mod alias

### LINKED ISSUE #23792: mod

### PR DESCRIPTION
**Pull request by MaxFrax**
Close #23792

### CODE REVIEW

**Comment by MaxFrax** [comment]
As per [tensorflow documentation](https://www.tensorflow.org/api_docs/python/tf/math/floormod) tf.math.mod is an alias for tf.math.floormod. Luckily, someone already implemented floormod in Ivy.
This PR just adds the alias.

I have two concerns:
1. Floormod has two implementations, one in [raw_ops](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/tensorflow/raw_ops.py#L573) and one in [math.py](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/tensorflow/math.py#L282).
[As per instructions](https://github.com/unifyai/ivy/issues/1545) I think the raw_ops one should be dropped.
2. Running the floor_mod test in test_math has a failing test case. The command I used to run the test is 
```pytest -x ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py::test_tensorflow_floormod```
[floor_mod_test.txt](https://github.com/unifyai/ivy/files/12646262/floor_mod_test.txt)

Any feedback is highly appreciated.

**Comment by MaxFrax** [comment]
It seems that [Gesoti](https://github.com/Gesoti) has already a [PR](https://github.com/unifyai/ivy/pull/23536/) introducing the same functionality. He seems to better handle types in the frontend tests.

**Comment by umairjavaid** [comment]
Hi @MaxFrax, the tests are not passing. You have to make sure all the tests pass
```
| Traceback (most recent call last):
    |   File "/ivy/ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py", line 2934, in test_tensorflow_Mod
    |     helpers.test_frontend_function(
    |   File "/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 1005, in test_frontend_function
    |     value_test(
    |   File "/ivy/ivy_tests/test_ivy/helpers/assertions.py", line 175, in value_test
    |     assert_all_close(
    |   File "/ivy/ivy_tests/test_ivy/helpers/assertions.py", line 56, in assert_all_close
    |     assert np.allclose(
    | AssertionError:  the results from backend tensorflow and ground truth framework tensorflow do not match
    |  1.0!=-1.0 
    | 
    | 
    | Falsifying example: test_tensorflow_Mod(
    |     frontend='tensorflow',
    |     backend_fw='tensorflow',
    |     on_device='cpu',
    |     dtype_and_x=(['float64', 'float64'], [array(-1.), array(2.)]),
    |     test_flags=FrontendFunctionTestFlags(
    |         num_positional_args=0,
    |         with_out=False,
    |         inplace=False,
    |         as_variable=[False],
    |         native_arrays=[False],
    |         test_compile=False,
    |         generate_frontend_arrays=False,
    |         transpile=False,
    |         precision_mode=False,
    |     ),  # or any other generated value
    |     fn_tree='ivy.functional.frontends.tensorflow.raw_ops.Mod',
    | )
    | Explanation:
    |     These lines were always and only run by failing examples:
    |         /ivy/ivy_tests/test_ivy/helpers/assertions.py:59
    |         /ivy/ivy_tests/test_ivy/helpers/assertions.py:61
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.86.2', b'AXicY2AAAkYGCGCEMYCACUIBAABuAAY=') as a decorator on your test case
```

**Review by umairjavaid — CHANGES_REQUESTED** [review]
Hi @MaxFrax, the tests are not passing. You have to make sure all the tests pass

**Comment by MaxFrax** [comment]
@umairjavaid Thanks for your review!
Now `pytest -x ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py::test_tensorflow_mod` gives me 5/5.

**Comment by umairjavaid** [comment]
Great work :)

**Pull request merged**
