### PR TITLE
Fixes #11566 Size

### LINKED ISSUE #11566: size

### PR DESCRIPTION
**Pull request by jaygala223**
Fixes #11566 size

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by vaatsalya123** [comment]
Hey @jaygala223,

I would like to begin by thanking you for your contribution, and I apologize for the delay in my response/review. Regarding your pull request, I would like to bring to your attention a minor issue that is unrelated to your implementation.

To resolve this issue, I suggest that you create a new pull request and close the current one. Recently, we performed a Git history clean-up that required a force push. Unfortunately, it appears that your pull request still contains information from before the force push.

Therefore, I recommend that you move your changes to a new, fresh pull request. This will help ensure that your changes can be reviewed and merged successfully.

Thank you again for your contribution.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
