### PR TITLE
Made Log_softmax Function support complex dtype

### PR DESCRIPTION
**Pull request by mohame54**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by jshepherd01** [comment]
I'm seeing this test failure:
```
E   AssertionError:  the results from backend paddle and ground truth framework tensorflow do not match
E    [[ 0.29893983-6.58843719e+00j -0.70106017+1.00000000e+10j]]!=[[ 0.29893983-3.05251886e-01j -0.70106017+1.00000000e+10j]] 
```
It seems like it might be an issue with one of the backend frameworks itself, could you look into it? If it is an issue with them, the best thing to do is raise an issue on their repository and then link it here

**Comment by mohame54** [comment]
could you provide me with test examples to test them locally.

**Comment by jshepherd01** [comment]
It comes from this test case (actually a slightly different one, the tests re-ran from the merge commit)
```
E   AssertionError:  the results from backend jax and ground truth framework tensorflow do not match
E    [[0.+0.j]
E    [0.+0.j]]!=[[-0.6931472+0.j]
E    [-0.6931472+0.j]] 
E   
E   
E   Falsifying example: test_log_softmax(
E       backend_fw='jax',
E       on_device='cpu',
E       dtype_and_x=(['complex64'], [array([[-1.-1.j],
E                [-1.-1.j]], dtype=complex64)]),
E       axis=None,
E       fn_name='log_softmax',
E       test_flags=FunctionTestFlags(
E           ground_truth_backend='tensorflow',
E           num_positional_args=1,
E           with_out=False,
E           instance_method=False,
E           test_gradients=False,
E           test_compile=False,
E           as_variable=[False],
E           native_arrays=[False],
E           container=[False],
E           precision_mode=False,
E       ),
E   )
```

**Comment by mohame54** [comment]
Yeah, I managed to solve it by making axis=-1 following as a default attr instead of axis=None @vedpatwardhan advice and about the error it appeared cuz I forgot to handle the axis in **tensorflow backend** correctly.

**Review by jshepherd01 — CHANGES_REQUESTED** [review]
That makes sense. You might also want to change the tensorflow frontend, since that seems to be failing with the exact opposite problem

**Pull request merged**
