### PR TITLE
Graph Compiler different framework example

### PR DESCRIPTION
**Pull request by CheezBallzPi**
Continuation of #5352. Here are the images that will eventually fill the spaces:

compiled_graph_tf
compiled_graph_jax
compiled_graph_numpy

### CODE REVIEW

**Comment by CheezBallzPi** [comment]
It seems that there are some changes in master that didn't carry over to my branch for some reason. I'll try to get those fixed.

**Comment by CheezBallzPi** [comment]
Alright should be ok now.

**Comment by CheezBallzPi** [comment]
Reversed all the arrows. New photos attached:
compiled_graph_numpy
compiled_graph_tf
compiled_graph_jax

**Review by djl11 — APPROVED** [review]
looks good to me! I was wondering whether we should also put green boxes around the singular functions as well, to show that these are also the ivy functions but just with one function, but this might clutter things and so I think your approach is actually perhaps better. I'll leave this decision with you anyway, the graphs and the text are both great!

**Comment by CheezBallzPi** [comment]
I also think it will look a bit cluttered. I'll leave it as is.

**Pull request merged**
