### PR TITLE
Add Random_Normal functions for TensorFlow frontend

### LINKED ISSUE #9557: normal

### PR DESCRIPTION
**Pull request by ream-kh**
resolves #9557

### CODE REVIEW

**Comment by ukj02** [comment]
Hi @ream-kh ! Thanks for your contribution!

The code is giving the error `fixture 'mean' not found`. Can you look into it and see what the problem is?

Thanks! 😄

**Comment by ream-kh** [comment]
Hi @ukj02, 
Thank you for the review.
Kindly check the updated files.

**Comment by ukj02** [comment]
It still gives the error ` ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.` Can you try to see what is wrong?

**Comment by ream-kh** [comment]
@ukj02 Can you check now?

**Comment by ream-kh** [comment]
Hi @ukj02, can you check now?

**Comment by ukj02** [comment]
Its giving me a new error ` AssertionError: 1.764052391052246 != 0.06751875579357147`. You can run the tests on your computer before pushing so that we do not have to do this back and forth.

**Pull request closed without merging**
