### PR TITLE
bitwise_invert adhering to Array API Standard

### PR DESCRIPTION
**Pull request by ebyau**
All tests passing locally except for Tensorflow one test fails

### CODE REVIEW

**Comment by ebyau** [comment]
@mattbarrett98 this is new PR for  bitwise_invert

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Thanks! Tensorflow is failing because `tf.bitwise.invert` doesn't take allow bool input types. I think then if you add some logic to the tf function so that when the datatype of `x` is bool, then you first cast `x` to an integer type (using `tf.cast`) and then call `tf.bitwise.invert`. I think this will fix the failure 🙂

**Comment by ebyau** [comment]
I have done the  casting but the tensorflow tests still fail; but i tested the logic with tensorflow code by creating boolean tensor trying `tf.bitwise.invert()` it fails then when i cast the tensor to an i`nt32 dtype` it works well

**Comment by ebyau** [comment]
Why do think the Tensor flow tests could be still failing?

**Comment by mattbarrett98** [comment]
> Why do you think the Tensor flow tests could be still failing?

Looking into it I've noticed that `bitwise.invert` is a different function in Tensorflow, and doesn't do what we want here. I've tried something using `logical_not` instead, I'll see if the tests pass.

**Comment by mattbarrett98** [comment]
Got there in the end 🙂 The problem was `tf.bitwise.invert` doesn't allow bool inputs, so in this case we just use `tf.logical_not`. Thanks for contributing!

**Comment by ebyau** [comment]
You welcome
Will the `tf.logical_not` be able to handle float tensors?

**Comment by mattbarrett98** [comment]
bitwise_invert only needs to handle int and bool dtype https://data-apis.org/array-api/latest/API_specification/generated/signatures.elementwise_functions.bitwise_invert.html 🙂

**Pull request merged**
