### PR TITLE
Added docstring examples to default (#2799)

### PR DESCRIPTION
**Pull request by ShauryaMohan**
Addresses issue #2799 default.

### CODE REVIEW

**Comment by ShauryaMohan** [comment]
hi @abdrahmandiab even though tests are failing but none of them are related to my changes, not even in the docstrings they are not my changes (it's argsort function that is giving these errors). Can you check this once?

**Comment by ShauryaMohan** [comment]
@abdrahmandiab can you please check this pull request, it has been marked as stale, I'll be happy to change my request if there's problem.

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab can you please check this pull request, it has been marked as stale, I'll be happy to change my request if there's problem.

Hi @ShauryaMohan, I didn't know whether you were done working or not as you hadn't requested a review yet nor commented anything. 😅 

I will get to it soon if you think it's ready then, thank you! :)

**Comment by ShauryaMohan** [comment]
@abdrahmandiab , I am working on open source for the first time, I realise I should have asked you to review.

**Comment by abdrahmandiab** [comment]
> @abdrahmandiab , I am working on open source for the first time, I realise I should have asked you to review.

That's completely fine friend, no worries! :)

**Comment by abdrahmandiab** [comment]
Hi @ShauryaMohan!
To make reviewing formatting PRs easier, we have a checklist now. Could you please follow the steps that are [here](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#formatting-checklist)? 

Would be a great help, thanks!

**Comment by ShauryaMohan** [comment]
add_reformatting_checklist_general

**Comment by ShauryaMohan** [comment]
Hi @abdrahmandiab can you review it now, I have added the checklist. Some lint checks were failing I corrected them.

**Review by abdrahmandiab — APPROVED** [review]
Everything looks good! 🚀

Thank you for your work! 😃

**Comment by ShauryaMohan** [comment]
Thank you!

**Pull request merged**
