### PR TITLE
Added frexp function in numpy frontend - frexp #11626

### PR DESCRIPTION
**Pull request by RakshitKumar04**

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
> Hey, sorry for the delay. Can you please copy over the changes to a new PR? The commit histories are messed up due to the restructuring

Hey, @aditya-hari I have fixed the PR. Can you please help me in passing the checks

**Comment by RakshitKumar04** [comment]
Hey, @aditya-hari I have updated the code, can you please review the PR.

**Comment by aditya-hari** [comment]
Hey, this function is already being worked on by someone else in  #11626. I'll be able to merge this only if they don't proceed with it.

**Comment by RakshitKumar04** [comment]
> Hey, this function is already being worked on by someone else in #11626. I'll be able to merge this only if they don't proceed with it.

Hey, I don't think this is being worked on. I don't see any PR for it and also no one has been assigned for that issue.

**Comment by aditya-hari** [comment]
The issue I have linked to indicates that it is being worked on. However, they seem to have closed the issue, so we're clear. I'll review this ASAP

**Comment by aditya-hari** [comment]
Additionally, please go through the contribution guideline to appropriately format this PR by linked this to an issue, which is subsequently linked to the ToDo issue

**Comment by RakshitKumar04** [comment]
> Additionally, please go through the contribution guideline to appropriately format this PR by linked this to an issue, which is subsequently linked to the ToDo issue

Hey, I have raised the issue and mentioned the PR to in it. Please review it.

**Comment by RakshitKumar04** [comment]
Close #12334

**Comment by RakshitKumar04** [comment]
Hey, @aditya-hari I followed the contribution guide and did what was asked, but I am unable to mention the PR under the development option.

**Comment by aditya-hari** [comment]
The tests are still incorrect. Please look at the review I have opened

**Comment by RakshitKumar04** [comment]
hey, @aditya-hari I did some changes and tried to resolve the conflicts, can you please review it.

**Comment by aditya-hari** [comment]
Hey, fine on the conflicts front but the tests are still failing due to the dtypes. The input is similar to exp, so whatever works for that should also work for this.

**Comment by RakshitKumar04** [comment]
hey @aditya-hari, I tried to resolve the dtypes conflict, PLease review if and if it fails please guide how to make it correct.

**Comment by RakshitKumar04** [comment]
Hey, @aditya-hari I got some issues with this PR, maybe because I did some changes with the test API submodule while setting up GitHub codespace to run the test and pushed them with this PR. Should make a new PR and tag u there?

**Comment by RakshitKumar04** [comment]
Hey, @aditya-hari here is the reference to new PR #13244

**Comment by RakshitKumar04** [comment]
Hey, @aditya-hari here is the reference to new PR #13244

**Comment by RakshitKumar04** [comment]
Hey, @aditya-hari please review the PR.

**Comment by aditya-hari** [comment]
Still failing :\ 

You can run the tests locally, how you can do that is described in the development guide - https://lets-unify.ai/ivy/overview/deep_dive/ivy_tests.html

**Comment by RakshitKumar04** [comment]
Hey @MuhammadSaeedBatikh can you please guide me on how do I resolve this error
**E   AttributeError: 'tuple' object has no attribute 'data'**
E   Falsifying example: test_numpy_frexp(
E       dtype_and_x=(['float32'], [array([-1.], dtype=float32)]),
E       fn_tree='ivy.functional.frontends.numpy.frexp',
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=1,
E           with_out=True,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=False,
E       ),
E       on_device='cpu',
E       frontend='numpy',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.71.0', b'AXicY2BkAAMoBaSBLAAAPgAF') as a decorator on your test case

**Comment by MuhammadSaeedBatikh** [comment]
Hi @RakshitKumar04, thanks for the PR. 
I think this particular exception is raised because the test handler expects the returned values to be array-like and tries to access ret.data property to compare it with ground truth. In your case, `frexp` returns both the mantissa and exponent which is probably why it says `'tuple' object has no attribute 'data'`.

**Comment by RakshitKumar04** [comment]
Thanks, Sir @MuhammadSaeedBatikh 
Sir the issue is to be **'Close as Completed'** by me or the ivy seed
Link to issue: https://github.com/unifyai/ivy/issues/12334

**Comment by MuhammadSaeedBatikh** [comment]
Done.
I apologize. This used to be done automatically after merging a PR.

**Pull request merged**
