### PR TITLE
Typo in building blocks

### PR DESCRIPTION
**Pull request by Ambro19**
The sentence is correct in terms of its meaning, but there is a minor issue with the use of the apostrophe in "it’s." The correct form should be "its" without an apostrophe. 

Here's the corrected version:
"The first important point to make is that Ivy does not implement its own C++ or CUDA backend."

Close #22641

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by theRealBird** [comment]
Hello @Ambro19, thank you for contributing to Ivy. Just a question, did you mean to push changes unrelated to the doc-string change on this branch? It seems you are also working on a frontend method.

Could you please link the original issue tracking the implementation of `instance_norm` as explained in our contributing guide in our docs? Thanks!


The change related to the docs looks good to me. Great spot, thanks for the fix!

**Comment by Ambro19** [comment]
Hi @theRealBird, you're very welcome! Yes, you're right, I was also working on the implementation of instance_norm() too. I may be wrong, but it looked to me that someone else has already fixed, merged and closed it (I've the function and its test ready). I am going to check and do as you suggest. Thank you.

**Comment by Ambro19** [comment]
> Hello @Ambro19, thank you for contributing to Ivy. Just a question, did you mean to push changes unrelated to the doc-string change on this branch? It seems you are also working on a frontend method.
> 
> Could you please link the original issue tracking the implementation of `instance_norm` as explained in our contributing guide in our docs? Thanks!
> 
> The change related to the docs looks good to me. Great spot, thanks for the fix!

**Comment by Ambro19** [comment]
@theRealBird, can you please check this link: https://github.com/unifyai/ivy/pull/22140
This is the link you're referring to.  So, you can see that @saeedashrraf asked to edit some minor changes. 

I hope this is what you meant by "linking the original issue tracking?"

**Comment by theRealBird** [comment]
Hi @Ambro19,
I see that the PR for `instance_norm` is being worked upon seperately.
If you will see, if I merge this PR, I will also merge the changes for `instance_norm` which can be problematic as this PR is not for `instance_norm`.
To merge the fix for typos, we should remove the commits for `instance_norm` from this PR (and this only) so that only commits remaining are the ones related to the typos.
Hope this clears it up. Thanks!

**Comment by Ambro19** [comment]
Hi @theRealBird, thanks for your comment. Yes, this clears it up. If I fo understand, i need to remove this instance- notm PR? Sorry for the confusion.

**Comment by theRealBird** [comment]
Hi @Ambro19,
Thank you for your patience. You don't have to necessarily remove that PR. You just need to remove the commits not related to the typo from this PR.
We can see the changes due to `instance_norm` implementation because the commits are pushed onto the same branch.
Hope that clears it up! Thanks!

**Comment by Ambro19** [comment]
pic1

**Comment by Ambro19** [comment]
pic1



Hi @theRealBird, no problem at all. Thanks for your comment. From the picture I provided above I saw the commit in question (highlighted). I am fixing it now. Thanks!

**Comment by Ambro19** [comment]
@theRealBird, I just fixed the issues that prevented merging. I hope this solves the issues. Thank you!

**Pull request closed without merging**
