### PR TITLE
reformat expand_dims

### PR DESCRIPTION
**Pull request by banditelol**
#973 
- update `expand_dims` docstring
- add examples
- conform exception to `array-api`'s [`expand_dims`](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.expand_dims.html)
  - mxnet: `MXNetError` to `IndexError`
  - numpy: `AxisError` to `IndexError`

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
You shouldn't edit any of the actual code, please remove these changes. The docstring looks good but just a few small changes required. Please have a look at this docstring https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/elementwise.py#L40 which is formatted correctly and ensure yours looks like this. 

One thing for example is there shouldn't be a `:` after the parameter names, thanks 🙂

**Comment by banditelol** [comment]
> You shouldn't edit any of the actual code, please remove these changes. The docstring looks good but just a few small changes required. Please have a look at this docstring https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/elementwise.py#L40 which is formatted correctly and ensure yours looks like this.
> 
> One thing for example is there shouldn't be a `:` after the parameter names, thanks 🙂

Noted, I'll work on it.
Oh and I just want to make sure, is the space behind `ret` intentional?
https://github.com/unifyai/ivy/blob/63a8d8ce8ccdc5a3751ba7f6318748bdda2e57b1/ivy/functional/ivy/elementwise.py#L77-L79

**Comment by mattbarrett98** [comment]
Good spot! no this isn’t intentional and shouldn’t be there 🙂

**Review by mattbarrett98 — COMMENTED** [review]
great, thanks!

**Pull request merged**
