### PR TITLE
Reformating Elementwise @logical_and

### PR DESCRIPTION
**Pull request by muhamadnickysalim**
Hello this PR resolves issue https://github.com/unifyai/ivy/issues/2179

I have added some examples in docstring and reformatting parameters

Thank you

### CODE REVIEW

**Comment by Unevilicorn** [comment]
Hi @muhamadnickysalim,
There is a few problems with the doc-strings:
- the parameters doc-string seems to have been removed by accident
- styling error which you can find in the `test-numpy-style-docstrings` check
- an error caused by the examples within the doc-string, you can see in it `test-fn-elementwise-numpy` check

**Comment by muhamadnickysalim** [comment]
Dear @Unevilicorn,
I've restoring the params doc-string, but I have no clue about styling error you've mentioned before.
Also, I'm still wandering which examples made an error.

Could you give me more hint to fix them? Thank you

**Comment by Unevilicorn** [comment]
You should be able to find the list of checks near the bottom of this page alternatively you can look at the checks tab at the top of this page or click [here](https://github.com/unifyai/ivy/pull/2256/checks). To get the specific details, you will need to click into the specific checks I've mentioned.

**Comment by muhamadnickysalim** [comment]
Alright, I've fixed the problems. That was silly mistakes.
There you go, you can review them and merge if there are no problem yet.

Thank you :)

**Comment by Unevilicorn** [comment]
Everything looks good and I have gone ahead and merged this PR :slightly_smiling_face:

**Pull request merged**
