### PR TITLE
refactor: remove bfloat16 from decorators

### PR DESCRIPTION
**Pull request by Sjsingh101**
# PR Description

This PR will remove bfloat16 from some `with_unsupported_dtypes` decorators.

## Related Issue

This PR is related to the Trello task: https://trello.com/c/mWrhZsRl/2816-remove-bfloat16-from-a-few-decorators

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [X] Did you run your tests and are your tests passing?
- [X] Did pre-commit not fail on any check?
- [X] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by hello-fri-end — COMMENTED** [review]
Hey @Sjsingh101 ! Thanks for creating this PR. I'm not sure If follow why we should be removing `bfloat16` from the decorators. Could you please explain this?

**Comment by Sjsingh101** [comment]
> Hey @Sjsingh101 ! Thanks for creating this PR. I'm not sure If follow why we should be removing `bfloat16` from the decorators. Could you please explain this?

There were a few PRs which added bfloat16 to unsupported dtypes before ivy team fixed the `__repr__`. Therefore, The changes to the decorators need to be reverted. Please refer to the trello card mentioned [here](https://trello.com/c/mWrhZsRl/2816-remove-bfloat16-from-a-few-decorators).

**Review by hello-fri-end — APPROVED** [review]
Thanks for the explanation @Sjsingh101 . Feel free to merge this PR :)

**Pull request merged**
