### PR TITLE
Add count_nonzero to paddle/tensor/math with associated tests

### LINKED ISSUE #23118: count_nonzero

### PR DESCRIPTION
**Pull request by maxxies**
# PR Description

The mathematical count_nonzero function was added to the Paddle Frontend. 

## Related Issue

Close #23118

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials:

https://twitter.com/maxwell_mawube

### CODE REVIEW

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
You should check your commited changes as it included some not relevent changes that should not be included. like docs and deep_dive stuffs

**Comment by maxxies** [comment]
> 



> 

Could you help me out with the specific docs? I merged my working branch with the main branch and it seems they came with the merge. What about the count-nonzero function implementation? @Daniel4078

**Comment by Daniel4078** [comment]
> > 
> 
> > 
> 
> Could you help me out with the specific docs? I merged my working branch with the main branch and it seems they came with the merge. What about the count-nonzero function implementation? @Daniel4078

My advice is to copy your new code somewhere first, then create a new branch in your repo from the current master branch so that all the other files are up to date, then you can copy back your code and commit them in one commit (it will be on a new PR due to the new branch).

**Comment by AryanSharma21** [comment]
Hello, @maxxies , @Daniel4078 , Just wanted to let you know that this issue was already opened by me last week and I have also already opened a PR for it. Can you please close this one ?

@Daniel4078 you can review the PR #23282 please ?

**Comment by Daniel4078** [comment]
> Hello, @maxxies , @Daniel4078 , Just wanted to let you know that this issue was already opened by me last week and I have also already opened a PR for it. Can you please close this one ?
> 
> @Daniel4078 you can review the PR #23282 please ?

@AryanSharma21 Done, but I suppose the people assigned to your PR should be merging it in most cases

**Pull request closed without merging**
