### PR TITLE
Fix torch.as_strided for non-contiguous tensors

### PR DESCRIPTION
**Pull request by AnnaTz**
So that this is True:
```
ivy.set_torch_backend()
size = [12, 1, 512, 64]
stride = [64, 196608, 768, 1]
x = torch.rand((12, 1, 64, 512)).transpose(-1, -2)
orig = torch.as_strided(x, size, stride).detach().numpy()
front = torch_frontend.as_strided(x, size, stride).ivy_array.data.detach().numpy()
print(np.allclose(orig, front))
```

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by vedpatwardhan — COMMENTED** [review]
Hey @AnnaTz, looking through the current view implementation in the framework, I'm not sure if we can consistently deal with the case when the input `ivy.NativeArray` itself has a view, because it's not just about the `_base` attribute for the `ivy.Array`, we also need to populate the `_manipulation_stack` of the operations that were performed on that `ivy.NativeArray` before this view was created. This is because we don't deal with the memory layout of arrays on the framework level and this seems to be an inherent limitation of that constraint.
So I think unless we can populate the `_manipulation_stack`, `_view_refs` and stuff correctly, we can't support the behaviour in the framework where an input `ivy.NativeArray` was already a view 😅

**Comment by AnnaTz** [comment]
ivy-gardener

**Comment by AnnaTz** [comment]
> 

Thanks Ved! For now I will limit the changes to `torch.as_strided` just to make it work correctly for the demo. Hope that's fine 😅
I will have to dive into view handling in the frontends as well soon enough.

**Comment by AnnaTz** [comment]
> Hey @AnnaTz, looking through the current view implementation in the framework, I'm not sure if we can consistently deal with the case when the input `ivy.NativeArray` itself has a view, because it's not just about the `_base` attribute for the `ivy.Array`, we also need to populate the `_manipulation_stack` of the operations that were performed on that `ivy.NativeArray` before this view was created, which is then useful to ensure that all views are updated when an inplace update is performed. This is because we don't deal with the memory layout of arrays on the framework level and this seems to be an inherent limitation of that constraint. So I think unless we can populate the `_manipulation_stack`, `_view_refs` and stuff correctly by retrieving an equivalent from `torch.Tensor` and `np.ndarray` (which is unlikely), I can't really think of a way to support the behaviour in the framework where an input `ivy.NativeArray` was already a view 😅 But happy to hear suggestions if you think there's a way to get this to work, I'll also dive a bit into this soon. Thanks 😄

Thanks Ved! For now I will limit the changes to torch.as_strided just to make it work correctly for the demo. Hope that's fine 😅
I will have to dive into view handling in the frontends as well soon enough.

**Comment by AnnaTz** [comment]
> Hey @AnnaTz, looking through the current view implementation in the framework, I'm not sure if we can consistently deal with the case when the input `ivy.NativeArray` itself has a view, because it's not just about the `_base` attribute for the `ivy.Array`, we also need to populate the `_manipulation_stack` of the operations that were performed on that `ivy.NativeArray` before this view was created, which is then useful to ensure that all views are updated when an inplace update is performed. This is because we don't deal with the memory layout of arrays on the framework level and this seems to be an inherent limitation of that constraint. So I think unless we can populate the `_manipulation_stack`, `_view_refs` and stuff correctly by retrieving an equivalent from `torch.Tensor` and `np.ndarray` (which is unlikely), I can't really think of a way to support the behaviour in the framework where an input `ivy.NativeArray` was already a view 😅 But happy to hear suggestions if you think there's a way to get this to work, I'll also dive a bit into this soon. Thanks 😄

Thanks Ved! For now I will limit the changes to `torch.as_strided` just to make it work correctly for the demo. Hope that's fine 😅
I will have to dive into view handling in the frontends as well soon enough.

**Comment by AnnaTz** [comment]
@Sam-Armstrong Could you let me know if the current changes work for you? Thanks!

**Pull request merged**
