### PR TITLE
feat: one_hot function of paddlepaddle

### LINKED ISSUE #24151: one_hot

### PR DESCRIPTION
**Pull request by SamruddhiNavale**
# PR Description
feat: one_hot function of paddlepaddle

## Related Issue
Close #24151

##Checklist
 * [x]  Did you add a function?
 * [x]  Did you add the tests?
 * [x]  Did you run your tests and are your tests passing?
 * [x]  Did pre-commit not fail on any check?
 * [x]  Did you follow the steps we provided?

Socials:

### CODE REVIEW

**Comment by SamruddhiNavale** [comment]
Hey there
Let me know if any changes are required.

**Comment by SamruddhiNavale** [comment]
hello @danielmunioz 

Let me know if any changes are required.
100.0% of 5 passed in local
few PR checks are failing tho.

**Comment by danielmunioz** [comment]
Hey @SamruddhiNavale! Thanks for contributing!

There is a small issue, the arguments of your function don't match the [original function](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/one_hot_en.html) ones, they should be the same for the PR to pass, would you please fix that? and update the test accordingly?

If you have any questions please feel free to reach out!
Thanks!!

**Comment by SamruddhiNavale** [comment]
Thank you for your response!
I have made the required changes. Do I raise a new PR now?

**Comment by SamruddhiNavale** [comment]
100% of 5 passed.
Kindly accept my PR. Let me know if any further changes are required
Thank you.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by SamruddhiNavale — COMMENTED** [review]
Reviewed Changes. Thanks.

**Review by Ishticode — APPROVED** [review]
lgtm. Thanks for your patience. I will merge this soon. Thank you very much for the efforts here

**Pull request merged**
