### PR TITLE
Torch FE tensorsolve feature added

### LINKED ISSUE #9889: tensorsolve

### PR DESCRIPTION
**Pull request by ra9hur**
Close #9889

### CODE REVIEW

**Comment by ra9hur** [comment]
Here are the test results:

root@4b5f0995dbc1:/ivy# pytest -v --num-examples 50 ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py::test_torch_tensorsolve
Use Database in ReadOnly Mode with local caching !
=================================================== test session starts ===================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'ivy_profile' -> max_examples=50, print_blob=True, deadline=timedelta(milliseconds=500000), suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much, HealthCheck.data_too_large], database=MultiplexedDatabase(DirectoryBasedExampleDatabase('/ivy/.hypothesis/examples/'), ReadOnlyDatabase(RedisExampleDatabase(Redis<ConnectionPool<Connection<host=redis-17011.c259.us-central1-2.gce.cloud.redislabs.com,port=17011,db=0>>>, expire_after=datetime.timedelta(days=8))))
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.15.0-58-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '7.1.2', 'pluggy': '1.0.0'}, 'Plugins': {'hypothesis': '6.55.0', 'json-report': '1.5.0', 'metadata': '2.0.4', 'typeguard': '2.13.3'}}
rootdir: /ivy
plugins: hypothesis-6.55.0, json-report-1.5.0, metadata-2.0.4, typeguard-2.13.3
collected 4 items

ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py::test_torch_tensorsolve[cpu-ivy.functional.backends.numpy-False-False] PASSED [ 25%]
ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py::test_torch_tensorsolve[cpu-ivy.functional.backends.jax-False-False] PASSED [ 50%]
ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py::test_torch_tensorsolve[cpu-ivy.functional.backends.tensorflow-False-False] PASSED [ 75%]
ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py::test_torch_tensorsolve[cpu-ivy.functional.backends.torch-False-False] PASSED [100%]

==================================================== warnings summary =====================================================
../usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19
  /usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================== 4 passed, 1 warning in 40.30s ==============================================

**Comment by ra9hur** [comment]
Haven't tested for dims(axes) parameter.

Referred to tensorsolve implementation in ivy framework and jax_numpy_fe framework.
1. Could not find corresponding test for ivy/array/linear_algebra/tesnorsolve
2. test_jax_numpy_tensorsolve haven't tested for axes parameter either.

Finding this a bit tricky. Should this parameter be tested? 
If yes, can you please share some hints OR reference implementation.

**Comment by ra9hur** [comment]
@karalleyna , request you to please review the PR.

**Comment by karalleyna** [comment]
Hi @ra9hur,

Thanks for your contribution! 🙃

**Pull request merged**
