### PR TITLE
Added diff to jax.numpy frontend

### LINKED ISSUE #9922: diff

### PR DESCRIPTION
**Pull request by AhmedHashish123**
Close #9922

### CODE REVIEW

**Comment by AhmedHashish123** [comment]
Hello @Nightcrab , I passed all test cases. Could you please review my work?

**Comment by Nightcrab** [comment]
Could you reverse the changes made to ``./idea`` in the commit?

The hypothesis tests should also be relaxed to allow for different dimensions and shapes of the input, which are currently restricted (2 dims and shape (2,6)).

**Comment by AhmedHashish123** [comment]
@Nightcrab I have restored the text in ./idea and allowed for different dimensions and shapes of the input.
Could you review my PR again?

**Comment by Nightcrab** [comment]
Looks good now, merging.

**Pull request merged**
