### PR TITLE
bitwise_right_shift

### PR DESCRIPTION
**Pull request by Om-Doiphode**
- [ ] #3612

### CODE REVIEW

**Comment by karalleyna** [comment]
The files that you have changed don't pass the formatting test. Unfortunately, your test is also failing. Can you make the necessary changes? Then, I can merge it :)

**Comment by Om-Doiphode** [comment]
Hi @karalleyna, I have made the necessary changes pertaining to the files I have changed, can you please review it? Thanks!

**Comment by karalleyna** [comment]
Could you reformat all files that you have made changes on?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
