### PR TITLE
all

### PR DESCRIPTION
**Pull request by KevinUnadkat**
Adding all from utility to paddle backend

### CODE REVIEW

**Comment by KevinUnadkat** [comment]
@MahmoudAshraf97 
i made a little mistake just give me some time ill fix it

**Comment by KevinUnadkat** [comment]
issue - all #10737

**Comment by KevinUnadkat** [comment]
hy @MahmoudAshraf97 
do i need to delete this "  KevinUnadkat:PaddlePaddle " now and open a new branch for new pull request

**Comment by MahmoudAshraf97** [comment]
Either sync your branch with the main PaddlePaddle branch or delete it and create a new branch

**Pull request merged**
