### PR TITLE
feat: paddle scatter (test case problem)

### LINKED ISSUE #23106: scatter

### PR DESCRIPTION
**Pull request by hritikakolkar**
## Related Issue

Close #23106
The test cases is not passing having minor errors

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by hritikakolkar** [comment]
Hi @danielmunioz please see this merge. I am having some issues with backends

**Comment by danielmunioz** [comment]
Hey @hritikakolkar! Thanks for contributing!

Yeah there seems to be an error in your helper, specifically on:
```
input_dtypes = [dtype_x[0], dtype_index[0], dtype_updates[0], dtype_overwrite[0]]
```
Seems to be an index out of range issue, I do believe `dtype_overwrite` can be empty, which causes issues when indexing

Other than that the PR seems to be in good shape!

If there are any questions feel free to reach out! :)
Thanks

**Comment by hritikakolkar** [comment]
okay will look into it, one more question do I have to update the paddle_scatter branch with the current version of ivy

**Comment by hritikakolkar** [comment]
dtype_overwrite cannot be empty I think in[ frontend ](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/scatter_en.html) as it is default value. Or I am not getting your point.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
