### PR TITLE
Reformat Device dev_dist

### PR DESCRIPTION
**Pull request by TryinCoding**
modified:   ivy/functional/ivy/device.py

### CODE REVIEW

**Comment by Unevilicorn** [comment]
Hi, can you link the issue or the todo list that this PR relates to. Thanks!

**Comment by TryinCoding** [comment]
> Hi, can you link the issue or the todo list that this PR relates to. Thanks!
this is under
reformat device #814 

the issue i made is 
dev_dist #3221

**Comment by Unevilicorn** [comment]
Hi there, this function

**Comment by Unevilicorn** [comment]
Hi there,
It seems that we've made a mistake, we're not longer supporting this function for the next release and we should have removed this function from the todo-list beforehand. Sorry about this oversight. The best way to proceed for now would be picking another function from the todo-list to work from.
Thanks

**Pull request closed without merging**
