### PR TITLE
feat: Update set.py

### LINKED ISSUE #23539: unique_inverse

### PR DESCRIPTION
**Pull request by adlub**
Updated set.py, in particular the unique_inverse function

Close #23539

### CODE REVIEW

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hi, seems like you have changed `docs/demos` which you might have done by mistake. Can you revert that change because we can't merge with that change in place?

**Comment by adlub** [comment]
> Hi, seems like you have changed `docs/demos` which you might have done by mistake. Can you revert that change because we can't merge with that change in place?

@KareemMAX I seem to be having trouble using "git checkout/revert" to revert these changes, I am trying to do it by using a codespace but it does not seem to work. Could i also create a new commit that includes the up to date version of those files that are on the repository (not inlcluding my changes)?

**Comment by KareemMAX** [comment]
> > Hi, seems like you have changed `docs/demos` which you might have done by mistake. Can you revert that change because we can't merge with that change in place?
> 
> @KareemMAX I seem to be having trouble using "git checkout/revert" to revert these changes, I am trying to do it by using a codespace but it does not seem to work. Could i also create a new commit that includes the up to date version of those files that are on the repository (not including my changes)?

I guess that should work, also try merging

**Comment by adlub** [comment]
> > > Hi, seems like you have changed `docs/demos` which you might have done by mistake. Can you revert that change because we can't merge with that change in place?
> > 
> > 
> > @KareemMAX I seem to be having trouble using "git checkout/revert" to revert these changes, I am trying to do it by using a codespace but it does not seem to work. Could i also create a new commit that includes the up to date version of those files that are on the repository (not including my changes)?
> 
> I guess that should work, also try merging

I ended up being able to remove the "docs" changes, is my work ready to merge now? Also, during this process, i accidentally requested 3 other reviewers. @RickSanchezStoic, @sherry30, @CatB1t, sorry about that, are you able to remove yourselves from this?

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Hi, you have to handle this in the respective test_function in the test file aswell and add the functionality there in the hypothesis too.
Thanks!

**Comment by adlub** [comment]
> Hi, you have to handle this in the respective `test_function` in the `test file` aswell and add the functionality there in the hypothesis too. Thanks!

Hi @zaeemansari70, I have applied these changes now, thanks

**Pull request merged**
