### PR TITLE
Add asinh paddle math frontend

### LINKED ISSUE #19224: asinh

### PR DESCRIPTION
**Pull request by NripeshN**
Close #19224

### CODE REVIEW

**Comment by selvaraj-sembulingam** [comment]
Hey, Thanks for contributing. Please comment `add_frontend_checklist` and edit and confirm with the checklist please, thanks!

**Comment by NripeshN** [comment]
add_frontend_checklist

**Comment by selvaraj-sembulingam** [comment]
LGTM! Thanks for contributing. 

Kindly resolve the conflicts to go for merge.

**Comment by NripeshN** [comment]
> LGTM! Thanks for contributing.
> 
> Kindly resolve the conflicts to go for merge.

I have sorted out the merge conflicts

**Pull request merged**
