### PR TITLE
added column_stack frontend function

### PR DESCRIPTION
**Pull request by Aditya062003**

### CODE REVIEW

**Comment by Aditya062003** [comment]
Close #11196

**Comment by agniiyer** [comment]
Hey can you resolve the conflicts and check if the tests are passing? Thanks :)

**Comment by agniiyer** [comment]
Hey @Aditya062003 just another reminder to resolve the conflicts and check if the tests are passing. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
