### PR TITLE
Added `around` function to functional api

### LINKED ISSUE #21321: `around`

### PR DESCRIPTION
**Pull request by joshiayush**
* [x] Resolves #21321
* [test_rouding.py](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_rounding.py#L226-L254) already includes test for `ivy.around()` function.

### CODE REVIEW

**Review by AryanSharma21 — COMMENTED** [review]
Hey, @joshiayush . I looked at the test log , I see there is an error in the function implementation.

`E   RecursionError: maximum recursion depth exceeded in comparison`

Recursion error is pretty self explanatory , it happens when we do not terminate the recursion using the  `tail condition` or `base condition` properly.
Please look into it and try running the function tests locally as well. Thanks

**Comment by joshiayush** [comment]
@sladyn98

**Comment by AnnaTz** [comment]
> @AnnaTz When I run the tests locally it passes for `numpy` and for the other backends that provides a compositional implementation like `jax`, it just gets stuck...
> 
> What am I doing wrong? Could you please help, it's been 2 weeks and there's no review on this PR that's why I mentioned you 👀

Hi @joshiayush, the reviewer asked you to fix some error and you haven't asked for another review since then, so that explains why you haven't heard back from him. You could try re-requesting a review, or asking on our public channels on discord about the specific error you are facing. Thanks!

**Comment by joshiayush** [comment]
@AryanSharma21 Tests are passing locally for `jax` and `numpy` backend and now I just need to add an implementation for the rest of the backends.

> Hey, @joshiayush . I looked at the test log , I see there is an error in the function implementation.
>
> E   RecursionError: maximum recursion depth exceeded in comparison
>
> Recursion error is pretty self explanatory , it happens when we do not terminate the recursion using the tail condition or base condition properly.
> Please look into it and try running the function tests locally as well. Thanks

Regarding your previous review, that's happening because there's no implementation for `tensorflow` and `torch` backend

**Comment by AryanSharma21** [comment]
Hey, @joshiayush. I am trying to spot the problem here, Generally, tf.tensor or eager tensor should be working with astype but I did find a recommendation to try using `tf.cast` instead of astype. 
Try using tf.cast in the tensorflow implementation. Besides, please try backtracking the issue, you can try that by setting the backend explicitly to TensorFlow

**Comment by joshiayush** [comment]
> Hey, @joshiayush. I am trying to spot the problem here, Generally, tf.tensor or eager tensor should be working with astype but I did find a recommendation to try using `tf.cast` instead of astype. Try using tf.cast in the tensorflow implementation. Besides, please try backtracking the issue, you can try that by setting the backend explicitly to TensorFlow

If you could please carefully look at the implementation of [`tf.around`](https://github.com/unifyai/ivy/pull/21320/files#diff-92e7519f18f3bb1fe6c223b07941ae3e0aa3ab8635dafe862c12a74c8988586fR521-R539), you'll find that for casting `tf.cast` has been used, there isn't a point of using `astype` for `tf` and still the problem persists...

**Comment by joshiayush** [comment]
@AryanSharma21 Sorry to ask but are you an ivy member? Your reviews aren't helping at all.

Could you please elaborate where did I use astype in tf backend so I would get the error?

You could try removing yourself from reviewers so the  one assigned as reviewer will get on it. Please try to do it 🙏

**Comment by AryanSharma21** [comment]
With respect sir @joshiayush , No I am not an ivy member. Sorry if it bothers you by any means but I pointed out a mistake in a friendly helping manner. Also, I am not sure how can I completely remove myself from the review completely. However it is not necessary as the assigned user is always an ivy member and can make a review / merge anytime. 
So, I am requesting @YushaArif99  on your behalf as well to manage this pull request from now on. 😇

**Comment by YushaArif99** [comment]
Hi @joshiayush. Apologies for the delay in the review. Have been swamped with work recently and so haven't had the time to review any PRs 😓 
Thanks a lot for stepping in and giving your feedback as well @AryanSharma21 🙂 

With regards to the PR, although I haven't looked into the code in much detail, I do notice a couple of discrepancies in what this PR intends to add as opposed to the issue it is referring to. 
- The issue # for this PR is not linked to the SubTask Todo list [here](https://github.com/unifyai/ivy/issues/1525). In fact, I have noticed that `numpy.around` was actually already reserved by another contributor (https://github.com/unifyai/ivy/issues/20180)
- The Subtask this PR is a part of falls under the broader category of Frontend API. It is clearly mentioned in the docs [here](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) as to what this task entails. It might be the case that `ivy.around` is yet not implemented, but the guidelines to deal with such cases are also clearly mentioned in the [docs](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis:~:text=In%20the%20case%20where%20your%20chosen%20function%20exists%20in%20all%20frameworks%20by%20default%2C%20but%20is%20not%20implemented%20in%20Ivy%E2%80%99s%20functional%20API%2C%20please%20convert%20your%20existing%20GitHub%20issue%20to%20request%20for%20the%20function%20to%20be%20added%20to%20Ivy.%20Meanwhile%2C%20you%20can%20select%20another%20frontend%20function%20to%20work%20on%20from%20the%20ToDo%20list!). 

Could you kindly address the abovementioned points first @joshiayush. I'll then start with the code review. Happy to answer any questions you have 🙂

**Comment by joshiayush** [comment]
> * The issue # for this PR is not linked to the SubTask Todo list https://github.com/unifyai/ivy/issues/1525. In fact, I have noticed that numpy.around was actually already reserved by another contributor (https://github.com/unifyai/ivy/issues/20180)

That is true because there's another github user who made it reserved for itself unless ivy marked it stale, but you reopened it. That issue was reserved but there wasn't any PR linked to it so I just decided to make one. To link this PR to the Subtask ToDo list I suppose you've to manually make the change over the ToDo list because I don't have the right.

> * The Subtask this PR is a part of falls under the broader category of Frontend API. It is clearly mentioned in the docs [here](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) as to what this task entails. It might be the case that ivy.around is yet not implemented, but the guidelines to deal with such cases are also clearly mentioned in the [docs](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis:~:text=In%20the%20case%20where%20your%20chosen%20function%20exists%20in%20all%20frameworks%20by%20default%2C%20but%20is%20not%20implemented%20in%20Ivy%E2%80%99s%20functional%20API%2C%20please%20convert%20your%20existing%20GitHub%20issue%20to%20request%20for%20the%20function%20to%20be%20added%20to%20Ivy.%20Meanwhile%2C%20you%20can%20select%20another%20frontend%20function%20to%20work%20on%20from%20the%20ToDo%20list!).

Alright, I'll make a issue for it. I saw that `round` function was used to support this behaviour of `around` function without implementing it. Is it going to be fine if I just use `ivy.round` right now?

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Yes you can use the `round` function in the meantime, as long as the behavior of the function is preserved. 
Also, could you kindly resolve the merge conflicts as well. Once that's done, feel free to re-request a review from me @joshiayush. Thanks! 🙂

**Comment by joshiayush** [comment]
> Yes you can use the `round` function in the meantime, as long as the behavior of the function is preserved. Also, could you kindly resolve the merge conflicts as well. Once that's done, feel free to re-request a review from me @joshiayush. Thanks! 🙂

Currently, I'm a bit busy but I'll resolve all the conflicts by the next week and yes you're right I should use `round` function.

**Comment by YushaArif99** [comment]
Hi @joshiayush

Any updates on the PR 🙂?

**Comment by YushaArif99** [comment]
Hi @joshiayush 

There is still no updates on this PR. Are you still working on it? If not, I might then have to close this PR so that other contributors have the chance to work on it. Thanks 🙂

**Comment by joshiayush** [comment]
> Hi @joshiayush
> 
> There are still no updates on this PR. Are you still working on it? If not, I might then have to close this PR so that other contributors have the chance to work on it. Thanks 🙂

I'm sorry for being so careless about the request I pulled here. I believe it's about time when I should close this PR and let others work on it. :+1:

**Pull request closed without merging**
