### PR TITLE
implement mse_loss Pytorch frontend

### PR DESCRIPTION
**Pull request by jfrausto7**
PR for #6443 
- implement 'mse_loss'
- implement 'test_torch_mse_loss'

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by aditya-pola** [comment]
“Hey @jfrausto7 🙂, sorry about the delay, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)”

**Comment by aditya-pola** [comment]
@jfrausto7, in the frontend test, you have sampled from all possible reduction methods. For mse_loss mean should suffice, otherwise this looks great to me. Please change the test.

**Comment by thirstyturtle125** [comment]
@aditya-pola Thanks for the note, I'll keep that in mind. Change requested has been made!

**Comment by aditya-pola** [comment]
This looks good to me! Merging

**Pull request merged**
