### PR TITLE
Update tensorflow frontend hard_sigmoid and related tests

### PR DESCRIPTION
**Pull request by FrankShi9**
From old PR hard_sigmoid https://github.com/unifyai/ivy/issues/2511 https://github.com/unifyai/ivy/pull/2580 #2860

### CODE REVIEW

**Comment by Aarsh2001** [comment]
Hi please implement the the function in the frontend module as well, thanks🙂.

**Comment by FrankShi9** [comment]
> Hi please implement the the function in the frontend module as well, thanks🙂.

[Update hard_sigmoid activations.py #2859](https://github.com/unifyai/ivy/pull/2859)

**Comment by Aarsh2001** [comment]
Kindly do everything in one PR, we need to check the CI for each function. Since the implementation is not in master, the test is failing for your function. Add it in this PR and close that one, thanks🙂

**Comment by FrankShi9** [comment]
> Kindly do everything in one PR, we need to check the CI for each function. Since the implementation is not in master, the test is failing for your function. Add it in this PR and close that one, thanks🙂

Please have a look, it has been a while and test functions seem pretty different from my early commits:)

**Comment by Aarsh2001** [comment]
There is no function called `ivy.hard_sigmoid` in the functional API, you'll have to implement this using a composition of ivy functions. If you aren't able to come up with a solution, you can allot some other issue to yourself, thanks🙂.

**Comment by FrankShi9** [comment]
> There is no function called `ivy.hard_sigmoid` in the functional API, you'll have to implement this using a composition of ivy functions. If you aren't able to come up with a solution, you can allot some other issue to yourself, thanks🙂.

Updated

**Comment by Aarsh2001** [comment]
Hi @FrankShi9, please open another PR for exponential, and pass `fn_tree` argument in `test_frontend_function`, with value being equal to the function name. `fn_tree = "hard_sigmoid"`

**Comment by FrankShi9** [comment]
> Hi @FrankShi9, please open another PR for exponential, and pass `fn_tree` argument in `test_frontend_function`, with value being equal to the function name. `fn_tree = "hard_sigmoid"`

Updated, not intended to add exponential implementation which is not my work.

**Pull request merged**
