### PR TITLE
ndarray.max

### LINKED ISSUE #5641: max

### PR DESCRIPTION
**Pull request by geeythree**
Close #5641

### CODE REVIEW

**Comment by ankitdsi2010** [comment]
Yeah you can use the numpy NoValue object and see if it works

**Review by ankitdsi2010 — CHANGES_REQUESTED** [review]
Fix the linting tests which failed relevant to your function and also check why test-frontend-numpy test is failing and fix it

**Comment by modanesh** [comment]
Hi @geeythree :)
I'll be reviewing this PR moving forward. Could you ping me when you're done with changes, or simply want a review?

**Comment by geeythree** [comment]
@modanesh Thanks for letting me know! :) 
I'm having some trouble figuring out how to write test for the function that I implemented

**Comment by modanesh** [comment]
Here we describe in detail how tests work and how to write one: https://lets-unify.ai/ivy/deep_dive/ivy_tests.html
I highly recommend take a look at it. Don't hesitate to ask any questions :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by geeythree** [comment]
I'm still working on this PR.

**Comment by modanesh** [comment]
Could you point out to where those implementations are?

**Comment by geeythree** [comment]
`ivy/ivy/functional/frontends/numpy/ndarray/ndarray.py` at **line 65** already contains an implementation of max(). I am not sure if this happened when I accidentally force pushed my commits onto the ivy repo or if somebody else had written it. 

`ivy/ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py` at **line 495** already has test implemented for max() which was not written by me.

**Comment by modanesh** [comment]
I will look into it and will let you know.

**Comment by modanesh** [comment]
I'm going to close this PR as the function is already implemented. This shouldn't have happened since we have a clear protocol on how to reserve a subtask and work on it, so this is an error on our end. Since @geeythree started working on it, you may proceed to the next stage of the application process :)

**Comment by geeythree** [comment]
Thank you for the clarification, @modanesh!
Just for confirmation, is it ok if I work on another subtask?

**Comment by modanesh** [comment]
Of course it's fine. We would appreciate your contribution 🙂

**Pull request closed without merging**
