### PR TITLE
mean function (PR #16323)

### PR DESCRIPTION
**Pull request by Nelson-ku**
I created this pull request to resolve the conflicts with the main branch

### CODE REVIEW

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @Nelson-ku, thanks for the PR. I have a couple of points that you need to address:

1. Can you please link the sub-task issue you are working on by commenting `Close #<issue_number>` on this PR?
2. There are some [lint/formatting](https://github.com/unifyai/ivy/actions/runs/5236532693/jobs/9454138732?pr=16284) errors associated with this PR. Can you resolve them? I suggest using `pre-commit` to auto-format the commits according to the set standards. Details on how to use `pre-commit` are provided in the documentation/website.
3. The CI doesn't seem to run your test for some reason. Can you run your test locally using `pytest` and attached screenshots of the test logs/results here?
4. There are merge conflicts with upstream. Can you kindly resolve those as well?

Kindly re-request a review once done. Thanks! 😃

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by hmahmood24** [comment]
> Hey @Nelson-ku, thanks for the PR. I have a couple of points that you need to address:
> 
> 1. Can you please link the sub-task issue you are working on by commenting `Close #<issue_number>` on this PR?
> 2. There are some [lint/formatting](https://github.com/unifyai/ivy/actions/runs/5236532693/jobs/9454138732?pr=16284) errors associated with this PR. Can you resolve them? I suggest using `pre-commit` to auto-format the commits according to the set standards. Details on how to use `pre-commit` are provided in the documentation/website.
> 3. The CI doesn't seem to run your test for some reason. Can you run your test locally using `pytest` and attached screenshots of the test logs/results here?
> 4. There are merge conflicts with upstream. Can you kindly resolve those as well?
> 
> Kindly re-request a review once done. Thanks! 😃

Hey @Nelson-ku, have you gone through the points above? What's the approximate ETA on your work? Please update accordingly. Thanks :)

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
