### PR TITLE
Add isin to jax.numpy logic functions to Jax frontend 

### PR DESCRIPTION
**Pull request by AntoniosMalak**

### CODE REVIEW

**Comment by AntoniosMalak** [comment]
Hi @kurshakuz, may you check the code, please?

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! My local test is showing the following error. Can you please fix it? Thanks!

```
========================================================================= ERRORS ==========================================================================
___________________________________ ERROR collecting ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_logic.py ___________________________________
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_logic.py:636: in <module>
    dtype_and_args=helpers.args_and_dtypes(
E   AttributeError: module 'ivy_tests.test_ivy.helpers' has no attribute 'args_and_dtypes'
```

**Comment by AntoniosMalak** [comment]
@kurshakuz may u check it?

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! This is looking good! Can you please finally run the test locally and show the passing test for your implementation? Thanks!

**Comment by AntoniosMalak** [comment]
Hi @kurshakuz , I found I forgot in `jax` in fn_tree="numpy.isin", so I added it I think everything is ok now and I tried it on my local machine. may u check it again.

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Please resolve the conflicts and then I will take a look, thanks!

**Comment by AntoniosMalak** [comment]
Hi @kurshakuz,  all these conflicts were not from me, it was other commits, and I don't know where it comes from.

**Pull request closed without merging**
