### PR TITLE
Added Exp_ function to Paddle Frontend

### LINKED ISSUE #22472: exp_

### PR DESCRIPTION
**Pull request by Aaryan562**
Close #22472 
passed

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Aaryan562** [comment]
> 

I edited the PR description.

**Comment by Aaryan562** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

Done

**Comment by Aaryan562** [comment]
Hey @sherry30, I have created the PR. Could you pls review it. Thanks!

**Review by sherry30 — APPROVED** [review]
lgtm!

**Pull request merged**
