### PR TITLE
Eigh Function - Tensorflow Frontend function 

### PR DESCRIPTION
**Pull request by rannynayyar67**
issue #4238

### CODE REVIEW

**Comment by rannynayyar67** [comment]
eigh function commit for this PR [https://github.com/unifyai/ivy/pull/4245/commits/4cc21aa8074ca71e08ae34bc11b5c6f103a3605a](url)

**Comment by rannynayyar67** [comment]
@johanjino can you review the PR

**Comment by johanjino** [comment]
Hey @rannynayyar67 , not sure why the `linalg` file is deleted . Please refer the [Open Tasks](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#open-tasks) on how to be doing this

**Comment by johanjino** [comment]
Also, theres been lots of conflicting files, if it seems hard for you to resolve it, you can fork the repo to add your works to it again

**Comment by rannynayyar67** [comment]
okay
am going to resolve the issues.

**Pull request closed without merging**
