### PR TITLE
tanh implementation

### PR DESCRIPTION
**Pull request by simonetgordon**
All array-api tests pass, Docker tests fail. Need to investigate further. Should have write access.
------------------------------------------------------------------------------------------------------------------------
### Summary of Changes:

**Declaring function**: ivy/functional/ivy/array_api/elementwise_functions.py

**Torch**
- Removing core definition: ivy/functional/backends/torch/core/math.py
- Adding elementwise_functions definition: ivy/functional/backends/torch/array_api/elementwise_functions.py

**Tensorflow**
- Removing core definition: ivy/functional/backends/tensorflow/core/math.py
- Adding elementwise_functions definition: ivy/functional/backends/tensorflow/array_api/elementwise_functions.py

**Numpy**
- Removing core definition: ivy/functional/backends/numpy/core/math.py
- Adding elementwise_functions definition: ivy/functional/backends/numpy/array_api/elementwise_functions.py

**MXNet**
- Removing core definition: ivy/functional/backends/mxnet/core/math.py
- Adding elementwise_functions definition: ivy/functional/backends/mxnet/array_api/elementwise_functions.py

**Jax**
- Removing core definition: ivy/functional/backends/jax/core/math.py
- Adding elementwise_functions definition: ivy/functional/backends/jax/array_api/elementwise_functions.py

**Changes Requested+ Implemented:**
- Fixing the typing information in the ivy/functional/ivy/array_api/elementwise_functions.py file. Type of x should be Union[ivy.Array, ivy.NativeArray].
- Uncomment function tanh in ivy_tests/array_api_methods_to_test/elementwise_functions.txt.

### CODE REVIEW

**Comment by simonetgordon** [comment]
Hi Matt, thanks fo this. Regarding 

> Could you fix the typing information in the ivy/functional/ivy/array_api/elementwise_functions.py file. Type of x should be Union[ivy.Array, ivy.NativeArray].

at around 5:40 of this tutorial video (implementing isfinite) https://www.youtube.com/watch?v=PW_4yWzPGVc&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl&index=3, Dan deletes the Union[] and replaces it with `ivy.Array`. Is this still the correct thing to do?

**Comment by mattbarrett98** [comment]
If you look at the description of that youtube video, Dan made a correction and we do accept native arrays as input. So the Union[] term is what we’re looking for. Apologies for any confusion 🙂

**Comment by mattbarrett98** [comment]
Your changes look okay so I'm not sure why all the tests are failing. Maybe create a new PR and see if that helps. Also you don't need to worry about the failure related to ceil, this is a separate issue 🙂

**Comment by simonetgordon** [comment]
@mattbarrett98 Hi Matt, I've just merged with master and the tests are still failing. For the array-api tests, it seems to be related to the ceil function so I won't worry about that. But as for the Docker tests, surely pulling upstream has updated the Docker files too, so I'm still unsure of what's going on there. Could it be related to my docker configuration? I can't access the details of the docker failure as I don't have an account.

**Comment by simonetgordon** [comment]
@mattbarrett98 Hi Matt, as you can see the array-api tests are passing fine now that the ceil func has been removed from testing. Are you able to see the 'details' of the dockercloud tests?

**Comment by simonetgordon** [comment]
@mattbarrett98 Hi Matt, as you can see the array-api tests are now all passing with the ceil function removed from testing. I have rebuilt the dockerfiles using the shell script in ivy/ivy, but the tests are still not passing. Any other insights you may have would be much appreciated, I'm keen to move to the next stage of the process :)

**Review by mattbarrett98 — APPROVED** [review]

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
