### PR TITLE
Reformat conv2d_transpose (and other layers)

### PR DESCRIPTION
**Pull request by xoiga123**

### CODE REVIEW

**Comment by xoiga123** [comment]
Close #9635

**Comment by xoiga123** [comment]
add_reformatting_checklist_layers

**Comment by xoiga123** [comment]
I think `dropout1d` is failing because it's experimental right now?

**Comment by xoiga123** [comment]
@aditya-hari please help me. It's failing at `tf.linalg` too and I didn't touch it at all. And I only reformatted docstrings and typehints but `dropout1d` still throws up errors.

**Comment by aditya-hari** [comment]
Hey! Thanks for the contributions.  
 
 Can you please restrict this PR to only the subtask at hand? Appreciate that you've made other fixes, but subsuming unrelated changes into a single PR makes tracking changes more difficult for us. Doing that will also make life easier for you with the failing tests.   
  
 You can open a different PR for the changes to other layer functions.

**Pull request merged**
