### PR TITLE
Activation to tensorflow

### PR DESCRIPTION
**Pull request by DawoodTahir**
Add activation for tensorflow frontend https://github.com/unifyai/ivy/issues/1664

### CODE REVIEW

**Comment by chie2727** [comment]
Hi @DawoodTahir , which task are you working on?

**Comment by DawoodTahir** [comment]
Adding linear, exponential and hard sigmoid activation to tensorflow
front-end

**Comment by chie2727** [comment]
@DawoodTahir 
Could you please include a link to your task issue in the first comment of this PR?

**Comment by DawoodTahir** [comment]
Issue: Add activation for tensorflow frontend #1664

**Comment by chie2727** [comment]
@DawoodTahir The frontend tasks have not yet officially been launched so I can't review your PR just yet. The tasks may become available in about a week or two, so in the meantime you are welcome to tackle one of the reformatting tasks instead!

https://github.com/unifyai/ivy/issues?q=is%3Aopen+label%3A%22Function+Reformatting%22+label%3A%22ToDo%22

**Comment by chie2727** [comment]
Hi @DawoodTahir , let me know if you'd prefer to close this PR and start on a new task

**Comment by chie2727** [comment]
Hi @DawoodTahir , I'll be closing this PR because of inactivity. Thanks!

**Pull request closed without merging**
