### PR TITLE
fix: Fixed spelling mistakes (used `codespell` hook to find the mistakes).

### LINKED ISSUE #26668: Fix spelling mistakes across the repo.
There are quite a few spelling mistakes present in the repo, use [codespell](https://github.com/codespell-project/codespell) pre-commit hook to identify misspellings across the entire repo, and fix them.
**Examples of misspellings:**
**(Altough instead of Although)**
https://github.com/unifyai/ivy/blob/dccba61947e7b4c632deb0c7b81c14f7aa1d8e9d/README.md?plain=1#L1340
**(conatiner instead of container)**
https://github.com/unifyai/ivy/blob/dccba61947e7b4c632deb0c7b81c14f7aa1d8e9d/docs/overview/contributing/setting_up.rst?plain=1#L765

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
I used [codespell](https://github.com/codespell-project/codespell) pre-commit hook to identify misspellings across the entire repo. I fixed almost all of the spelling mistakes currently present in the repo. 

## Related Issue
Close #26668 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials
https://twitter.com/Sai_Suraj_27

### CODE REVIEW

**Comment by Sai-Suraj-27** [comment]
@KareemMAX sir, Please look into this when you are free, Thank you.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Let's see what @KareemMAX thinks, thanks @Sai-Suraj-27 😄

**Review by KareemMAX — APPROVED** [review]
LGTM! merging it now

**Pull request merged**
