### PR TITLE
[torch] add `var_mean`

### PR DESCRIPTION
**Pull request by khushi-411**
Ref: #8942

### CODE REVIEW

**Review by Ishticode — APPROVED** [review]
Hi @khushi-411
 
Your PR looks great. Just a minor update I made to return the tuple as its a frontend funtion and hence follows the return statement for [torch.var_mean](https://pytorch.org/docs/stable/generated/torch.var_mean.html)

Otherwise the PR is perfect. Merging it now. Thaks for your contribution 😊.

**Comment by khushi-411** [comment]
Hi, @Ishticode!

That's a great catch! Ugh, I missed it. Thanks for pointing that out and reviewing the PR! I'm looking forward to contributing.😊

**Comment by Ishticode** [comment]
@khushi-411 You're welcome to contribute. May I ask if you are planning to join Ivy at all?
You seem to have strong and pretty relevant skills.

**Comment by khushi-411** [comment]
Indeed @Ishticode. I tried to reach out to the team in the "IvyTeam" discord channel for further rounds. Could you please check it out there? I was hoping to join in January if that suits you all :)

I'm glad that you found my skills relevant. Thanks!

**Pull request merged**
