### PR TITLE
feat: add paddle randperm

### LINKED ISSUE #17687: randperm

### PR DESCRIPTION
**Pull request by Unicorncosmos**
randperm Close #17687

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Unicorncosmos** [comment]
> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

ok

**Comment by MuhammedAshraf2020** [comment]
@Unicorncosmos 
Thank you for your contribution and sorry for the lateness, I'm going to review it soon 🙂

**Comment by Unicorncosmos** [comment]
> @Unicorncosmos Thank you for your contribution and sorry for the lateness, I'm going to review it soon 🙂

ok

**Comment by Unicorncosmos** [comment]
hi what is the progress of the review

**Comment by Unicorncosmos** [comment]
@MuhammedAshraf2020 
what is the progress of the review?

**Comment by satakshigarg** [comment]
@Unicorncosmos thanks for your PR. However, I can see that there are few [errors](https://github.com/unifyai/ivy/actions/runs/5424798842/jobs/9864679087?pr=17777#step:3:207) being raised by your code. 
Could you please rectify them, and kindly try testing the code on local using PyTest if you aren't doing it already.
Looking forward to the resolved code, and feel free to ping me once the code is ready for review.

**Comment by Unicorncosmos** [comment]
> @Unicorncosmos thanks for your PR. However, I can see that there are few [errors](https://github.com/unifyai/ivy/actions/runs/5424798842/jobs/9864679087?pr=17777#step:3:207) being raised by your code. 
> Could you please rectify them, and kindly try testing the code on local using PyTest if you aren't doing it already.
> Looking forward to the resolved code, and feel free to ping me once the code is ready for review.

Ok

**Comment by Unicorncosmos** [comment]
why the resolve conflicts button is disabled

**Comment by Unicorncosmos** [comment]
image

**Comment by Unicorncosmos** [comment]
Hi is there any update regarding above

**Comment by satakshigarg** [comment]
> why the resolve conflicts button is disabled

The button has been disabled for everyone, and it says you need to resolve conflicts using CLI. So please try resolving conflicts on your local system using CLI.
Hope that helps !!

**Comment by Unicorncosmos** [comment]
> > why the resolve conflicts button is disabled
> 
> The button has been disabled for everyone, and it says you need to resolve conflicts using CLI. So please try resolving conflicts on your local system using CLI.
> Hope that helps !!

Ok

**Comment by satakshigarg** [comment]
@Unicorncosmos Could you please share any updates, if there's any ? Let me know if you are facing any difficulties.
Unfortunately, the resolve conflicts can be resolved only on your local system for this PR. Apologies for the inconvenience.
Thanks & Keep contributing 😃

**Comment by joaozenobio** [comment]
Hi @Unicorncosmos! Thanks for your contribution :smile: I see that you need help with your code and sorry for the delay on an answer. 
First I would advise you to solve the conflicts of your fork updating with the master branch. It can be done by saving the modifications you made in another folder, solving the conflicts of your fork, cloning again the fork and inserting the modification in the new copy of your fork.

Then, I would like to warn you about the files you modified. According to the ToDo list of issues the issue you are trying to solve came from, only two files must be modified: 

* ivy/functional/frontends/paddle/random.py
* ivy\_tests/test\_ivy/test\_frontends/test\_paddle/test\_random.py

Please do not modify other files than these.

The second problem I can see in your code is the git merging comments that are left in your code. They should not be there for your code to run properly. you can see them in the comments I left in the files.

Please check for these errors and then make sure the frontend function is written accordingly with the contributor guides that can be found on the [Ivy Documentation](https://unify.ai/docs/ivy/) and the test are not just following the same required patterns but also pass.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
