### PR TITLE
implemented cummax function to PyTorch Frontend

### LINKED ISSUE #16082: cummax

### PR DESCRIPTION
**Pull request by Dherya27**
Close #16082

### CODE REVIEW

**Comment by Dherya27** [comment]
Close #16082

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi. Could you exclude your changes to .idea directory configuration.
Then I will hopefully get this merged right away. It looks good. This a a test for torch frontend cummax as the function was already implemented with a missing test for some reason.
Let me know if you need any help.

**Comment by Dherya27** [comment]
Hi,

I have implemented the requested changes. Please review the updated files.

Regards,

**Review by Ishticode — APPROVED** [review]
Looking great. Thanks @Dherya27 for your contribution. I will get this test merged. Thanks 🙂

**Comment by Dherya27** [comment]
Thanks. @Ishticode

**Pull request merged**
