### PR TITLE
fix: Fixed `paddle.math.floor` for jax, torch, and tensorflow backends

### LINKED ISSUE #28417: Fix Frontend Failing Test: tensorflow - math.paddle.floor
To-do List: https://github.com/unifyai/ivy/issues/27499

### LINKED ISSUE #28418: Fix Frontend Failing Test: jax - math.paddle.floor
To-do List: https://github.com/unifyai/ivy/issues/27496

### LINKED ISSUE #28419: Fix Frontend Failing Test: torch - math.paddle.floor
To-do List: https://github.com/unifyai/ivy/issues/27498

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# PR Description
Fixed `paddle.math.floor` for jax, torch, and tensorflow backends

image

## Related Issue
Closes #28417
Closes #28418
Closes #28419

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Sai-Suraj-27** [comment]
Even though the [documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/floor_en.html) of paddle paddle says that the supported dtypes are `float32, float64 or float16`. When we test the function using `float16`, it gives error and say's that it supports only `float32, float64`
image

**Comment by MuhammadNizamani** [comment]
> Even though the [documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/floor_en.html) of paddle paddle says that the supported dtypes are `float32, float64 or float16`. When we test the function using `float16` dtype, it gives error and say's that it supports only `float32, float64`. So, I removed it as a supported dtype.
> 
> Paddle Paddle version: **2.6.0 (Latest)**
> 
> image

@Sai-Suraj-27  I am facing the same issue paddlepaddle docs says something and paddle backed does not support.

**Comment by Ishticode** [comment]
> > Even though the [documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/floor_en.html) of paddle paddle says that the supported dtypes are `float32, float64 or float16`. When we test the function using `float16` dtype, it gives error and say's that it supports only `float32, float64`. So, I removed it as a supported dtype.
> > Paddle Paddle version: **2.6.0 (Latest)**
> > image
> 
> @Sai-Suraj-27 I am facing the same issue paddlepaddle docs says something and paddle backed does not support.

Yh paddle's docs are sometimes incorrect in this regard. One might have to check manually. or you can write a loop with all dtypes and try except block that you can run for any function and it would clearly show which dtypes are actually supported.

**Review by Ishticode — APPROVED** [review]
looks good. Your are right about paddle docs. Thanks for the efforts. :)

**Pull request merged**
