### PR TITLE
isreal at Torch

### LINKED ISSUE #21267: isreal

### PR DESCRIPTION
**Pull request by kashi476074**
Added isreal at torch frontend
close #21267

### CODE REVIEW

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hello! thanks for the great work so far! please only add the function at the torch frontend and not the paddle frontend. Please also add the corresponding tests in the respective folders in `ivy_tests/...` thanks!

**Comment by kashi476074** [comment]
I just wanna know that is it common to fail this much tests or
We have to make all tests successful?

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey! Thanks for adding the tests! Please remove the paddle changes as it is not related to your issue, also, did you have an issue related to the torch `isreal` functional version as well? Cuz your issue is related to the instance method version. Please make sure that no one else is working on the functional version and create an issue on that as well then link it here to avoid conflicts, thanks a lot!

PS: I've just saw your follow up message in the discord channel, all comments or PR approval will be based on the conversation in the PR instead of the channel, thanks!

**Comment by juliagsy** [comment]
You'll only need to make sure that the tests for your selection function is passing, other tests failure which exists in master itself but is not related to your function may be ignored, thanks!

**Comment by kashi476074** [comment]
Thanks.
I have already removed the changes from Paddle

**Comment by juliagsy** [comment]
Ah yes, thanks a lot! Do you also have an issue related to the torch `isreal` functional version as well? Cuz your issue is related to the `instance` method version. Please make sure that no one else is working on the functional version and create an issue on that as well then link it here to avoid conflicts, thanks a lot!

**Comment by kashi476074** [comment]
The issue is created at  
https://github.com/unifyai/ivy/issues/21267

and I also attach it to instance method issue where it says 
unifyai deleted a comment from kashi476074.

I suppose this means I am already been assigned this issue

**Comment by kashi476074** [comment]
I am not getting any issue related to the torch isreal functional durinh run

**Comment by juliagsy** [comment]
Yeah, this is already attached. Never mind, just gone through the issues and I don't think there's another person working on the functional version :D The reason I asked is because they're usually listed as 2 different functions in 2 different ToDo lists due to their nature and there's a chance that there's another person who's claimed the functional version there. No worries now :D

**Comment by kashi476074** [comment]
Thanks.
So are these changes good to merge or need some more attention.

**Comment by juliagsy** [comment]
Hey! I was running the tests and I think there are some failure persisting, I'll need to run it another time tmr to give review comments, but could you please run it locally and try to fix the failures meanwhile? Thanks!

**Comment by kashi476074** [comment]
I have run it on local but is says 
"(no files to check) Skipped" for all Tests

**Pull request merged**
