### PR TITLE
Numpy Around function correction

### LINKED ISSUE #15484: rounding.test_numpy_around

### PR DESCRIPTION
**Pull request by NicholusMagak**
This tries to fix #15484 which is related to #15292

### CODE REVIEW

**Comment by NicholusMagak** [comment]
@Infrared1029 Please review my PR. Thank you.

**Comment by NicholusMagak** [comment]
@Infrared1029 In the event you have some time, please review this PR.

**Comment by Infrared1029** [comment]
Hey @NicholusMagak, the tests appear to be failing according the the CI, can you make sure they are passing so i can have a closer look? sorry for the late reply!

**Comment by Infrared1029** [comment]
Sorry for the late reply, probably setting the test to only generate integers and floats should work.
`helpers.dtypes("float_and_integer")`, some backends do not support bools for the around function.

**Comment by NicholusMagak** [comment]
@Infrared1029 Thank you for the reply. I assume you're busy hence I'm not usually worried about late replies. I made the changes you recommender and ended up having new errors. Reverted back to the way the file were and I could not get the errors to go down. Any other possible solution?

**Comment by NicholusMagak** [comment]
Is it potentially because I am using a docker python image 3.8.10?

**Pull request closed without merging**
