### PR TITLE
Added def tolist() method to ndarray.py

### PR DESCRIPTION
**Pull request by westrany**

### CODE REVIEW

**Comment by guillesanbri** [comment]
Hi! I will be reviewing this PR from now on, could you please give me some info of what Issue/Task is this related to? Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
