### PR TITLE
qdwh 

### LINKED ISSUE #13731: qdwh

### PR DESCRIPTION
**Pull request by Burhankhalid**
Close #13731

### CODE REVIEW

**Comment by Burhankhalid** [comment]
@karalleyna can you please review this code?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Burhankhalid** [comment]
Hi can anyone please take a look at this review?@CatB1t

**Comment by Burhankhalid** [comment]
Hey @karalleyna still waiting for a review on this.

**Comment by Burhankhalid** [comment]
Hi, still waiting on this.

**Review by Ookamice — CHANGES_REQUESTED** [review]
HIya 👋

Thank you for contributing and I am so sorry this has slipped past our PR approval process.

Please could you write the test case for the function you've added and also remove the pycharm ide configuration folder. You can consult the [contributer's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) for more info.

Feel free to ask me any questions!

**Comment by Burhankhalid** [comment]
Ok thank you I will get on it right away.

**Comment by Burhankhalid** [comment]
add_reformatting_checklist_qdwh

**Comment by Burhankhalid** [comment]
Hi, I've written the test case. Kindly review this PR again @Ookamice .

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hiya, could you quickly change `fn_tree="jax.lax.linalg"` to `fn_tree="jax.lax.linalg.qdwh"` please?

I'll give it a closer look after the change has been made and tests have been ran!

**Comment by Burhankhalid** [comment]
Yeah sorry, just added qdwh.

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hiya, thanks for the quick fix

Not sure why but the CI testing pipeline isn't running your tests so I have opened a codespace and configured it for testing your PR. Currently your tests are failing due to `TypeError: qdwh() got an unexpected keyword argument 'lower'`. I believe this is because qdwh() doesn't take the lower flag but you have incluided them in your testing decorator.

Feel free to use the codespace yourself to aid in your troubleshooting. Running the command `python3 -m pytest ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_linalg.py::test_jax_lax_qdwh  --backend 'all' -rxXs ` should run all the necessary test.

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hi, thanks for the changes.

There is still a lower=lower in your tests that are throwing a `NameError` in the test you've written. Please could you rectify this :)

Also, feel free to use the codespace to run your tests (Remember to go to the git tab and sync the changes before running so you can run your latest PR)

**Comment by Burhankhalid** [comment]
Hi, thanks for your quick review. I've removed the lower flag. Can you kindly review this PR again? 

Much appreciated!

**Review by Ookamice — CHANGES_REQUESTED** [review]
@Burhankhalid 👋 
Hiya, here's a rundown of the very basics on using the intelligent PR test:
- Look at `display_test_results`
-  Expand the `New failures introduced` to see if an error relating to your PR exists (in this case qdwh)
-  Expand  `Combined Test Result` 
-  Use github's built-in search bar to search through the log (eg: search 'qdwh')

(Alternatively you can run `python3 -m pytest ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_linalg.py::test_jax_lax_qdwh  --backend 'all'` in the codespace which wil lbe faster as it means not running a lot of superfluous tests)

In this case, the error is with `TypeError: qdwh() got an unexpected keyword argument 'symmetrize_input'` which I believe is due to your test case declaration as well as in `helpers.test_frontend_function` declaration within your test function.

PS: Please also remove your .idea folder ide configuration files from this PR

**Comment by Burhankhalid** [comment]
Hi, I've removed the ".idea" folder and some changes to the test function. Please review this again and guide me to any more changes necessary.

**Comment by Ookamice** [comment]
Hiya, I still see some odd changes in the `file changed` tab

Could you please make sure that only the relevant files are changed. It only should include `ivy/functional/frontends/jax/lax/linalg.py` and `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_linalg.py`

**Comment by Burhankhalid** [comment]
Yeah, I'm just figuring out a way to exclude those files. If I delete them from the "files changed" tab will that be sufficient?

**Comment by Ookamice** [comment]
@Burhankhalid

I believe deleting them from the files changed tab would add a change that means the file gets deleted rather than untouched. I'm not 100% sure though as I usually use git through the command line

**Comment by Burhankhalid** [comment]
I have been researching and I think the  ".gitignore"  will need to be present for the .idea folder to be removed. Shall I do just that.

**Comment by Burhankhalid** [comment]
Hi, if you look at the last commit, there are only 2 files changed. Is there a way you can just merge the files from the latest commit?

**Comment by Ookamice** [comment]
@Burhankhalid 
I'm sorry but github only allows me to merge all the commits in a PR at once. You can try closing this PR and opening another one if you can't get the files changed to play nicely. 😸

**Pull request closed without merging**
