### PR TITLE
while_loop

### LINKED ISSUE #7170: while_loop

### PR DESCRIPTION
**Pull request by ahmedwael216**
Closes #7170

### CODE REVIEW

**Comment by ahmedwael216** [comment]
Still not ready.
I have A problem with the data types that fails the Tests.

**Comment by ahmedwael216** [comment]
Close #1579

**Comment by Daniel4078** [comment]
#7170

**Comment by Daniel4078** [comment]
I do not think you should commit your changes to the .idea folder at all.

**Review by kurshakuz — COMMENTED** [review]
+1 to previous comment. Please remove the updates to the .idea folder. Can you please also clarify why do you use those specific numbers in the `_test_condition_fn` and `_test_body_fn`?

Thanks :)

**Comment by ahmedwael216** [comment]
- Will remove them in a minute.
- no special values just wanted to test if my test were right. And they are clearly not written right.

**Comment by kurshakuz** [comment]
Feel free to request a new review when you feel ready!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
