### PR TITLE
lstsq

### LINKED ISSUE #22530: lstsq

### PR DESCRIPTION
**Pull request by TomiMalamud**
Close #22530

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi, 
The frontend implementation should be composed of ivy functions. You can read more about it in our docs.
You will also have to implement a test function for this frontend function and get it to pass.

All of these things are well documented in the docs so make sure to go through those first and then feel free to ask any questions.

Thanks

**Review by TomiMalamud — COMMENTED** [review]
Added new tests

**Comment by TomiMalamud** [comment]
Close #22532

**Comment by sherry30** [comment]
Hey,

I just noticed that someone has already opened PR for this function before you, they commented it first [here](https://github.com/unifyai/ivy/issues/7479#issuecomment-1689487669).
So I would suggest that you pick a different function, a one which is not already picked and no one has commented.

Sorry for realizing a lot later. 😅 

Thanks

**Pull request closed without merging**
