### PR TITLE
Reformat clear_mem_on_dev

### PR DESCRIPTION
**Pull request by yusufraji**
Add examples to clear_mem_on_dev

### CODE REVIEW

**Comment by yusufraji** [comment]
#6291

**Comment by Daniel4078** [comment]
Hello, please do not forget to add a comment for the Reformatting Task Checklist. Thank you! Here is the deep dive document for it(https://lets-unify.ai/ivy/contributing/open_tasks.html#formatting-checklist)

**Comment by yusufraji** [comment]
add_reformatting_checklist_device

**Review by Daniel4078 — APPROVED** [review]
Well done, I think there is nothing wrong to fix. Thank you.

**Pull request merged**
