### PR TITLE
Tensorflow frontend tensor __rmod__, __rdiv__, __abs__

### LINKED ISSUE #5577: __abs__

### LINKED ISSUE #5578: __rdiv__

### LINKED ISSUE #5579: __rmod__

### PR DESCRIPTION
**Pull request by khimraj**
close #5577 
close #5578
close #5579

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
hi, @khimraj can you try resolving the conflicts? Also, can you check for the failing tests?

**Comment by khimraj** [comment]
@RickSanchezStoic, I have resolved conflicts now, you can check.

**Comment by RickSanchezStoic** [comment]
Hi, @khimraj can you try fixing the failures?

**Comment by khimraj** [comment]
@RickSanchezStoic fixed test failures, check now.

**Comment by khimraj** [comment]
@RickSanchezStoic fixed test failures, please check now.

**Comment by RickSanchezStoic** [comment]
Hi @khimraj , can you try resolving the conflicts ? also the failures still seem to be there.

**Comment by khimraj** [comment]
Hi @RickSanchezStoic, I have resolved conflicts and test failures. Can you please review now?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by RickSanchezStoic** [comment]
@khimraj just try resolving the conflicts, otherwise looks good to me

**Comment by khimraj** [comment]
@RickSanchezStoic, resolved the conflicts

**Pull request merged**
