### PR TITLE
Task - Created the Slogdet function

### PR DESCRIPTION
**Pull request by AnimeshGurjar**
Implemented the slogdet function for Torch, Tensorflow, numpy and mxnet

### CODE REVIEW

**Review by 1Doomdie1 — CHANGES_REQUESTED** [review]
Hey, thank you for contributing. Please remove all contents from the commit which is not related to slogdet (for example everything in .idea).
In addition you are missing one folder in your branch https://github.com/unifyai/ivy/tree/master/ivy_tests. Update your fork and then go inside that folder in linear_algebra.txt and uncomment slogdet to add it to the test.

**Comment by AnimeshGurjar** [comment]
Hi. I did what you asked. 

- I deleted the .name file.
-  I uncommented slodget from linear_algebra.txt, 

But when I updated the fork, my branch had no changes.
Also now the tests are failing. Previously, the attribute "slodget" was called from the `ivy/functional/backends/numpy/core/linalg.py`
 but now for some reason its calling from 
`ivy/functional/backends/numpy/array_api/linear_algebra.py` 
and same for torch, tensorflow and mxnet.

**Comment by AnimeshGurjar** [comment]
Hi. I have made the changes as you asked. 
- Deleted the .name file.
- Updated the fork.
- Uncommented slodget
- Also moved all functions to correct files.

**Review by 1Doomdie1 — CHANGES_REQUESTED** [review]
Hey, thank you for contributing!

Please refer to: ivy/functional/ivy/array_api/linear_algebra.py line 101 and modify this to the standard notation shown here: https://lets-unify.ai/ivy/contributing.html#ivy-api

After you make the changes please request another code review! :)

**Review by 1Doomdie1 — APPROVED** [review]
This looks great.
I will request Dan to take a look himself as well and get this merged.

Again, thank you for contributing! :)

**Comment by AnimeshGurjar** [comment]
Great! Thank you for all your help and for giving me this opportunity.

**Review by djl11 — CHANGES_REQUESTED** [review]
Two points:

1. Could you please remove `ivy_tests/test_ivy/conftest.py`
2. Why is the det method also added? Was it needed for the slogdet method?

Thanks!

**Comment by AnimeshGurjar** [comment]
Hi Dan. 
As you asked, I've removed the `ivy_tests/test_ivy/confest.py`. 
I previously also added the det() method, because it was needed in `ivy_tests.test_array_api.array_api_tests.test_linalg.test_slogdet` in the earlier version of fork, but in the updated one, those lines of code were commented out, so now the methods were not needed. So I've removed those det() functions too.

**Review by djl11 — APPROVED** [review]
lgtm

**Review by djl11 — CHANGES_REQUESTED** [review]
Looks like your JAX test is failing, could you investigate?

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Comment by AnimeshGurjar** [comment]
Great! Thank you.

**Pull request merged**
