### PR TITLE
Fixing ndarray reshape

### PR DESCRIPTION
**Pull request by danielmunioz**

### CODE REVIEW

**Comment by danielmunioz** [comment]
Close #6944

**Comment by danielmunioz** [comment]
OK, so I took the liberty of updating the arguments and the test function, now the test is passing without issue!!, Please LMK if my assessment of the issue was correct!

**Comment by guillesanbri** [comment]
Hi! Thanks a lot for the contribution! I'm afraid we have released a refactor of the test decorators and `handle_cmd_line_args` is deprecated. I believe a public announcement is coming shortly so I will let you know what should be changed asap :slightly_smiling_face:

**Comment by danielmunioz** [comment]
Cool!, sorry any updates on the `handle_cmd_line_args` update @guillesanbri?

**Comment by guillesanbri** [comment]
Hi! sorry for the late response, although the tests are currently disabled we are already incorporating the new method test handler, so if you want you can change the test of the PR to use the new handler we can merge it once it has been modified. You can use [these tests](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py) as reference and obviously the testing frontends docs, thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
