### PR TITLE
close#9964

### PR DESCRIPTION
**Pull request by revenge47**

### CODE REVIEW

**Comment by revenge47** [comment]
hey something wrong with my PR. please let me know. thanks

**Comment by revenge47** [comment]
Hi there, something wrong with my PR please let me know thanks :smile:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by revenge47** [comment]
hi there please let me know if there is something I can change about my PR. thanks 😄

**Comment by agniiyer** [comment]
Hey can you remove the changes to split and just keep the changes to reverse? :)

**Comment by revenge47** [comment]
Done! 👍 however my commits are the reverse function.

**Comment by revenge47** [comment]
hey anything else I can do on my end?

**Pull request closed without merging**
