### PR TITLE
added test and function for choice in numpy frontend

### LINKED ISSUE #11071: choice

### PR DESCRIPTION
**Pull request by avinoam-simon**
closes #11071

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by RickSanchezStoic** [comment]
Hi @avinoam-simon can you try getting rid of the merge conflicts? The best way would be to copy and save your changes somewhere else, update you repo to the latest master, re-add your changes and push again

**Comment by hirwa-nshuti** [comment]
Hey @avinoam-simon 
To get rid of merge conflicts use `./merge_with_upstream.sh master` and fix the conflicts locally then push.
For more info feel free to explore the fork management section of the docs https://lets-unify.ai/docs/ivy/overview/contributing/the_basics.html#managing-your-fork

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
