### PR TITLE
refactor multi_head_attention

### PR DESCRIPTION
**Pull request by Infrared1029**
(WIP), What is left is:
- [ ] use `scaled_dot_product_attention` when possible
- [x] Add Docs
- [x] Add a few more assertions
- [x] Use Ivy exceptions
- [x] If provided input is not batched, batchify it first, and unbatchify before returning
- [ ] Add out support
- [x] Add bias support
- [x] Take a look at extra arguments like torch's `add_zero_attn` and `add_bias_kv` to support superset behavior
- [x] Modify Stateful layer
- [x] Update the tests
- [x] Remove old multi_head_attention

### CODE REVIEW

**Comment by Infrared1029** [comment]
Mentioning @MahmoudAshraf97 because we are doing this together.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Infrared1029** [comment]
Wanted to point out that there are probably some tweaks to be done in the docsstring, the unchecked todos as well, but since the applied team needs this asap decided to merge now and continue them in a separate PR, the stateful layer (and the functional one tbh) are very similiar to torch's, if any suggestions need to be made that prevents immediate merge, let me or @MahmoudAshraf97  know so we get it done asap. Cc @juliagsy

**Review by vedpatwardhan — APPROVED** [review]
lgtm! Probably you know this already, but we'd also need to update the [stateful test](https://github.com/Infrared1029/ivy/blob/300d999435ec7ff37604332b9dcef70bcf499902/ivy_tests/test_ivy/test_stateful/test_layers.py#L255) for multi-head attention. 
I'll also request @juliagsy's review just to confirm that the function now allows what they need. Thanks @Infrared1029 @MahmoudAshraf97 @kgmann 🙂

**Review by juliagsy — COMMENTED** [review]
lgtm too! thanks all!

**Pull request merged**
