### PR TITLE
feat: Added `pad` to paddle frontend 

### LINKED ISSUE #22759: pad

### PR DESCRIPTION
**Pull request by AbdullahSabry**
Close #22759

### CODE REVIEW

**Comment by AbdullahSabry** [comment]
Hey @abdulasiraj 

A couple of comments on the PR; 
1. The mode `symmetric` was not implemented yet so it needed to be excluded from testing.
2. In the original paddle function the input `fill` could receive a size 3 tuple with RGB. However this isn't supported in `ivy.fill`. Let me know if there's anything to be done to resolve this

Review this and let me know. Thanks!

**Comment by abdulasiraj** [comment]
Hi @AbdullahSabry,
`symmetric` mode exists in Ivy functional api as you can see here https://github.com/unifyai/ivy/blob/1da6f0f3580a1e5672fccc1cb7c8e67e65c77b98/ivy/functional/ivy/experimental/manipulation.py#L1035

**Comment by AbdullahSabry** [comment]
@abdulasiraj 

Unfortunately when I run tests I get the error

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by abdulasiraj — APPROVED** [review]
yes. you're right there's problem with symmetric mode.

**Pull request merged**
