### PR TITLE
feat: added quantile function

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
#10704

### CODE REVIEW

**Comment by jaskiratsingh2000** [comment]
@ivy-leaves @lucasalavapena Can you please review it now

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by jaskiratsingh2000** [comment]
@ivy-leaves Thanks for the mention but I have already mentioned it.

**Comment by jaskiratsingh2000** [comment]
@ivy-leaves Can you assign someone to this please?

**Comment by jaskiratsingh2000** [comment]
Hi @kurshakuz I think this is good to go now.

**Comment by lucasalavapena** [comment]
FYI @jaskiratsingh2000, @ivy-leaves is a bot!

**Comment by jaskiratsingh2000** [comment]
Oh I didn't notice that. Bots seems real though. Anyways, can you review it now?

**Comment by jaskiratsingh2000** [comment]
Oh I didn't notice that. Bots seems real though. Anyways, can you review it now @lucasalavapena ?

**Review by lucasalavapena — CHANGES_REQUESTED** [review]
Thanks for the updating the PR :) ! Unfortunately your tests are still failing  :/ , see [the CI](https://github.com/unifyai/ivy/actions/runs/6176908736/job/16767053328?pr=23558) specifically the New Failures Introduced section (The Combined Tests Results section has more detailed logs)! 

The easiest way to test it would be to setup codespaces per https://unify.ai/docs/ivy/overview/contributing/setting_up.html#github-codespaces and then checkout your branch! Then do `pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_stat.py::test_paddle_quantile`. If you need help running tests, you can ask on the discord!

**Comment by jaskiratsingh2000** [comment]
@lucasalavapena I actually did that but I'mnot sure what the cause of issue was or how to approach that

**Comment by jaskiratsingh2000** [comment]
I sent but there seems to be no response regarding test cases.

**Comment by lucasalavapena** [comment]
@jaskiratsingh2000 I would do breakpoints and debug it a bit, I think one of the problem you have, having debugged it myself is that `axis` should be an int or list not a tuple, because in the paddle implementation, at least the one I have in codespaces which is probably based on their develop branch, they have something like this, which does type checking via `isinstance`:

```
    if axis is None:
        x = paddle.flatten(x)
        axis = 0
        out_shape = [1] * dims
    else:
        if isinstance(axis, list):
            axis_src, axis_dst = [], []
            for axis_single in axis:
                if not isinstance(axis_single, int) or not (
                    axis_single < dims and axis_single >= -dims
                ):
                    raise ValueError(
                        "Axis should be None, int, or a list, element should in range [-rank(x), rank(x))."
                    )
                if axis_single < 0:
                    axis_single = axis_single + dims
                axis_src.append(axis_single)
                out_shape[axis_single] = 1

            axis_dst = list(range(-len(axis), 0))
            x = paddle.moveaxis(x, axis_src, axis_dst)
            if len(axis_dst) == 0:
                x = paddle.flatten(x)
                axis = 0
            else:
                x = paddle.flatten(x, axis_dst[0], axis_dst[-1])
                axis = axis_dst[0]
        else:
            if not isinstance(axis, int) or not (axis < dims and axis >= -dims):
                breakpoint()
                raise ValueError(
                    "Axis should be None, int, or a list, element should in range [-rank(x), rank(x))."
                )
            if axis < 0:
                axis += dims
            out_shape[axis] = 1
```



And then I got `AssertionError: returned dtype = float32, ground-truth returned dtype = float64` which is a common error, see https://github.com/search?q=repo%3Aunifyai%2Fivy+returned+dtype+%3D+float32%2C+ground-truth+returned+dtype+%3D+float64&type=pullrequests to get some help!

**Comment by jaskiratsingh2000** [comment]
@lucasalavapena So does it mean that I should write this whole in the test_stat file?

**Comment by jaskiratsingh2000** [comment]
@lucasalavapena So I'm confused now could you please tell me where the changes are required and what change I should do so that it could be breaked as you mentioned? I actually tried the same way what other functions have been implemented.

**Comment by jaskiratsingh2000** [comment]
@lucasalavapena Will you be able to commit those test case changes from your end. I think after that it is good to go since I'm unable to do that from my end.

**Comment by jaskiratsingh2000** [comment]
@lucasalavapena For some reason, my branch got deleted and as a result the changes as well.Please refer to teh new PR I opened here - https://github.com/unifyai/ivy/pull/23580

**Comment by lucasalavapena** [comment]
> @lucasalavapena So does it mean that I should write this whole in the test_stat file?

No. In your test file you are creating an axis variable that you are using for testing it, you have to make sure that it is valid for the paddle function. A tuple is not in the list of accepted types for axis in https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/quantile_en.html

**Comment by jaskiratsingh2000** [comment]
@lucasalavapena So how should I mention that?

**Pull request closed without merging**
