### PR TITLE
added the soft_margin loss

### LINKED ISSUE #21072: soft_margin_loss
- [soft_margin_loss] #22717

### PR DESCRIPTION
**Pull request by sushmanthreddy**
close #21072

### CODE REVIEW

**Comment by sushmanthreddy** [comment]
@kgmann can u plss review the pull request ?

**Comment by sushmanthreddy** [comment]
> @kgmann can u plss review the pull request ?

@kgmann can u pls review the pull request?

**Comment by kgmann** [comment]
Hey @sushmanthreddy, thanks for your contribution, and sorry for my late reply. 
Can you please fix the issues in the code (one has to do with the `handle_array_like_without_promotion` decorator) and make sure the test is passing ? 
You can run the tests locally with  `pytest ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py::test_soft_margin_loss`. 
Feel free to let me know when you encounter any issue. Thanks.

**Comment by kgmann** [comment]
Hey @sushmanthreddy, thanks for your contribution, and sorry for my late reply.
Can you please make sure the test is passing ? It's currently failing.
You can run it locally with `pytest ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py::test_soft_margin_loss`.
Feel free to let me know when you encounter any issue. Thanks.

**Comment by kgmann** [comment]
ivy-gardener

**Comment by sushmanthreddy** [comment]
@kgmann the tests are now passing if paddle doesn't pass thats due to paddle bfloat16 issue.,where ivy people are working on .other than that ,i have implemented the loss function according to paper.

now testcases are passing and backend implementation is also there over here.Soft_margin_loss is only present in paddle and torch.so i have added in them.
Screenshot from 2023-08-18 16-05-23

here sc of testspassing

**Comment by sushmanthreddy** [comment]
@kgmann unsupported datatypes are checked this way and added to it and crossverified with doc also

**Pull request closed without merging**
