### PR TITLE
svdvals

### PR DESCRIPTION
**Pull request by Tyred**
I believe it's done. Let me know if I did anything wrong!

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Tyred. Excellent work here 
You have implemented the function in all backends, just requires you to add the function in `functional/ivy/array_api/linear_algebra.py` with the docstring formatted as in the [contributing guide](https://lets-unify.ai/ivy/contributing.html).
will be ready to merge soon. Thanks : )

**Comment by Tyred** [comment]
On it!

**Comment by Tyred** [comment]
> Hi @Tyred. Excellent work here You have implemented the function in all backends, just requires you to add the function in `functional/ivy/array_api/linear_algebra.py` with the docstring formatted as in the [contributing guide](https://lets-unify.ai/ivy/contributing.html). will be ready to merge soon. Thanks : )

Done! I also resolved the conflicts with the master branch as there was some changes in the repository structure.

**Review by Ishticode — APPROVED** [review]
I think its ready to merge and the two tests failed for other reasons. Excellent : )

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
