### PR TITLE
Implemented gradient for jax.numpy frontend

### PR DESCRIPTION
**Pull request by Supremolink81**
#Close 10838

### CODE REVIEW

**Comment by Supremolink81** [comment]
Partial solution; there is an error with my setup where the imports pass through fine, but when I run the code, I get a ModuleNotFoundError, like so:

Traceback (most recent call last):
  File "c:/Users/arioz/OneDrive/Documents/Programming/Python/ivy/ivy/functional/frontends/jax/numpy/mathematical_functions.py", line 11, in <module>
    from ivy.functional.frontends.jax.func_wrapper import (
ModuleNotFoundError: No module named 'ivy.functional'

I tried adding the path to the ivy repo into sys.path, but the result is the same.

Another issue was the indentation of the yml file, but that was easily fixable.

**Comment by Supremolink81** [comment]
To add to the last comment, I tried the following:

-cloning the repo from GitHub
-downloading zip file
-cloning the repo using Ivy's command

I did this all while using a venv set to Python 3.8. I tried both installing from the requirements.txt file and from ivy-core, neither fixed the issue.

Unsure if this helps, but here is the result of dir(ivy):

['ACTIVATION_FUNCTIONS', 'Adam', 'Any', 'Array', 'Callable', 'ComplexDtype', 'Constant', 'Container', 'ContainerBase', 'Conv1D', 'Conv1DTranspose', 'Conv2D', 'Conv2DTranspose', 'Conv3D', 'Conv3DTranspose', 'DefaultComplexDtype', 'DefaultDevice', 'DefaultDtype', 'DefaultFloatDtype', 'DefaultIntDtype', 'DefaultUintDtype', 'DepthwiseConv2D', 'Device', 'Dict', 'Dropout', 'Dtype', 'DynamicBackendContext', 'FN_CACHE', 'FN_DECORATORS', 'Finfo', 'FirstLayerSiren', 'FloatDtype', 'Framework', 'FrameworkStr', 'FunctionType', 'GEGLU', 'GELU', 'Generator', 'GlobalsDict', 'GlorotUniform', 'GradientTracking', 'INF', 'IfElse', 'Iinfo', 'Initializer', 'IntDtype', 'Iterable', 'KaimingNormal', 'LAMB', 'LARS', 'LSTM', 'LayerNorm', 'Linear', 'List', 'Literal', 'Module', 'ModuleConverters', 'ModuleHelpers', 'MultiHeadAttention', 'NativeArray', 'NativeDevice', 'NativeDtype', 'NativeShape', 'NativeSparseArray', 'NativeVariable', 'NestedArray', 'NestedSequence', 'Node', 'Number', 'Ones', 'Optimizer', 'Optional', 'OrderedDict', 'Profiler', 'Protocol', 'SGD', 'Sequence', 'Sequential', 'Shape', 'Siren', 'SparseArray', 'SupportsBufferProtocol', 'TMP_DIR', 'Tuple', 'TypeVar', 'UintDtype', 'Uniform', 'Union', 'UserDict', 'WhileLoop', 'Zeros', '_MIN_BASE', '_MIN_DENOMINATOR', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_all_ivy_dtypes_str', '_assert_array_decimal_values_formatting', '_assert_array_significant_figures_formatting', '_default_globals', '_sf', '_version', 'abc', 'abs', 'acos', 'acosh', 'activations', 'adam_step', 'adam_update', 'add', 'add_array_specs', 'add_ivy_array_instance_methods', 'add_ivy_container_instance_methods', 'adjoint', 'all', 'all_complex_dtypes', 'all_devices', 'all_dtypes', 'all_equal', 'all_float_dtypes', 'all_int_dtypes', 'all_nested_indices', 'all_numeric_dtypes', 'all_uint_dtypes', 'allclose', 'angle', 'annotations', 'any', 'arange', 'arg_info', 'arg_names', 'argmax', 'argmin', 'args_to_ivy', 'args_to_native', 'argsort', 'argwhere', 'arr_conversions', 'array', 'array_api_promotion_table', 'array_decimal_values', 'array_decimal_values_stack', 'array_equal', 'array_mode_stack', 'array_significant_figures', 'array_significant_figures_stack', 'as_ivy_dev', 'as_ivy_dtype', 'as_native_dev', 'as_native_dtype', 'asarray', 'asarray_handle_nestable', 'asarray_infer_device', 'asarray_to_native_arrays_and_back', 'asin', 'asinh', 'assert_supports_inplace', 'assertions', 'ast', 'astype', 'atan', 'atan2', 'atanh', 'atleast_1d', 'atleast_2d', 'atleast_3d', 'avg_pool1d', 'avg_pool2d', 'avg_pool3d', 'backend', 'backend_stack', 'backend_version', 'bernoulli', 'beta', 'bfloat16', 'binarizer', 'binary_cross_entropy', 'binary_cross_entropy_with_logits', 'bind_custom_gradient_function', 'bitwise_and', 'bitwise_invert', 'bitwise_left_shift', 'bitwise_or', 'bitwise_right_shift', 'bitwise_xor', 'bool', 'broadcast_arrays', 'broadcast_shapes', 'broadcast_to', 'builtins', 'cache_fn', 'can_cast', 'ceil', 'check_float', 'cholesky', 'choose_random_backend', 'clear_backend_stack', 'clear_mem_on_dev', 'clip', 'clip_matrix_norm', 'clip_vector_norm', 'closest_valid_dtype', 'compiled_backends', 'complex128', 'complex64', 'compute_weight_mat', 'concat', 'constant_pad', 'constants', 'cont_conversions', 'container', 'container_types', 'control_flow_ops', 'conv', 'conv1d', 'conv1d_transpose', 'conv2d', 'conv2d_transpose', 'conv3d', 'conv3d_transpose', 'conv_general_dilated', 'conv_general_transpose', 'converters', 'copy', 'copy_array', 'copy_nest', 'copysign', 'corrcoef', 'cos', 'cosh', 'count_nonzero', 'creation', 'cross', 'cross_entropy', 'cumprod', 'cumsum', 'current_backend', 'current_backend_str', 'data_type', 'dct', 'default', 'default_complex_dtype', 'default_complex_dtype_stack', 'default_device', 'default_device_stack', 'default_dtype', 'default_dtype_stack', 'default_float_dtype', 'default_float_dtype_stack', 'default_int_dtype', 'default_int_dtype_stack', 'default_uint_dtype', 'default_uint_dtype_stack', 'deg2rad', 'del_global_attr', 'depthwise_conv2d', 'deserialize', 'det', 'dev', 'dev_handles', 'dev_util', 'device', 'dft', 'diag', 'diagflat', 'diagonal', 'diff', 'dirichlet', 'divide', 'double', 'dropout', 'dropout1d', 'dropout3d', 'dsplit', 'dstack', 'dtype', 'dtype_bits', 'duplicate_array_index_chains', 'dynamic_backend_as', 'dynamic_backend_stack', 'e', 'eig', 'eigh', 'eigh_tridiagonal', 'eigvals', 'eigvalsh', 'einops', 'einops_rearrange', 'einops_reduce', 'einops_repeat', 'einsum', 'elementwise', 'embedding', 'empty', 'empty_like', 'equal', 'erf', 'exception_trace_mode_stack', 'exceptions', 'execute_with_gradients', 'exists', 'exp', 'exp2', 'expand', 'expand_dims', 'experimental', 'expm1', 'extra_promotion_table', 'eye', 'eye_like', 'fft', 'finfo', 'fix', 'flatten', 'flip', 'fliplr', 'flipud', 'float16', 'float32', 'float64', 'float_power', 'floor', 'floor_divide', 'fmax', 'fmin', 'fmod', 'fn_array_spec', 'fomaml_step', 'fourier_encode', 'from_dlpack', 'full', 'full_like', 'func_wrapper', 'function_supported_devices', 'function_supported_devices_and_dtypes', 'function_supported_dtypes', 'function_unsupported_devices', 'function_unsupported_devices_and_dtypes', 'function_unsupported_dtypes', 'functional', 'functools', 'gamma', 'gather', 'gather_nd', 'gc', 'gcd', 'gelu', 'general', 'get', 'get_all_arrays_in_memory', 'get_all_ivy_arrays_on_dev', 'get_array_mode', 'get_backend', 'get_dynamic_backend', 'get_exception_trace_mode', 'get_item', 'get_min_base', 'get_min_denominator', 'get_nan_policy', 'get_nestable_mode', 'get_num_dims', 'get_queue_timeout', 'get_referrers_recursive', 'get_show_func_wrapper_trace_mode', 'get_tmp_dir', 'globals_vars', 'gpu_is_available', 'grad', 'gradient', 'gradient_descent_update', 'gradients', 'greater', 'greater_equal', 'hamming_window', 'handle_array_function', 'handle_array_like_without_promotion', 'handle_exceptions', 'handle_nans', 'handle_nestable', 'handle_out_argument', 'handle_view', 'handle_view_indexing', 'handler', 'hann_window', 'has_nans', 'heaviside', 'helpers', 'hsplit', 'hstack', 'hypot', 'i0', 'if_else', 'ifft', 'iinfo', 'imag', 'import_module_path', 'importlib', 'index_nest', 'inf', 'infer_default_dtype', 'infer_device', 'infer_dtype', 'initializers', 'inner', 'inplace_arrays_supported', 'inplace_decrement', 'inplace_increment', 'inplace_update', 'inplace_variables_supported', 'inputs_to_ivy_arrays', 'inputs_to_native_arrays', 'insert_into_nest_at_index', 'insert_into_nest_at_indices', 'inspect', 'instance_norm', 'int16', 'int32', 'int64', 'int8', 'integer_arrays_to_float', 'interp', 'interpolate', 'inv', 'invalid_complex_dtypes', 'invalid_devices', 'invalid_dtype', 'invalid_dtypes', 'invalid_float_dtypes', 'invalid_int_dtypes', 'invalid_numeric_dtypes', 'invalid_uint_dtypes', 'is_array', 'is_bool_dtype', 'is_complex_dtype', 'is_float_dtype', 'is_int_dtype', 'is_ivy_array', 'is_ivy_container', 'is_ivy_sparse_array', 'is_local', 'is_native_array', 'is_native_dtype', 'is_native_sparse_array', 'is_uint_dtype', 'isclose', 'isfinite', 'isin', 'isinf', 'isnan', 'isreal', 'isscalar', 'itertools', 'ivy', 'jac', 'kaiser_bessel_derived_window', 'kaiser_window', 'kron', 'l2_normalize', 'lamb_update', 'lars_update', 'layer_norm', 'layers', 'lcm', 'leaky_relu', 'less', 'less_equal', 'lexsort', 'linalg', 'linear', 'linear_algebra', 'linspace', 'locks', 'log', 'log10', 'log1p', 'log2', 'log_softmax', 'logaddexp', 'logaddexp2', 'logging', 'logical_and', 'logical_not', 'logical_or', 'logical_xor', 'logit', 'logspace', 'losses', 'lp_normalize', 'lstm_update', 'maml_step', 'manipulation', 'map', 'map_nest_at_index', 'map_nest_at_indices', 'match_kwargs', 'math', 'matmul', 'matrix_exp', 'matrix_norm', 'matrix_power', 'matrix_rank', 'matrix_transpose', 'max', 'max_chunk_sizes', 'max_pool1d', 'max_pool2d', 'max_pool3d', 'maximum', 'mean', 'median', 'meshgrid', 'meta', 'min', 'minimum', 'mish', 'module', 'moveaxis', 'msort', 'multi_head_attention', 'multi_index_nest', 'multinomial', 'multiply', 'multiprocessing', 'nan', 'nan_policy_stack', 'nan_to_num', 'nanmean', 'nanmedian', 'nansum', 'native_array', 'native_bfloat16', 'native_bool', 'native_complex128', 'native_complex64', 'native_double', 'native_float16', 'native_float32', 'native_float64', 'native_inplace_support', 'native_int16', 'native_int32', 'native_int64', 'native_int8', 'native_sparse_array', 'native_sparse_array_to_indices_values_and_shape', 'native_uint16', 'native_uint32', 'native_uint64', 'native_uint8', 'ndenumerate', 'ndindex', 'negative', 'nest', 'nestable_mode_stack', 'nested_any', 'nested_argwhere', 'nested_array', 'nested_map', 'nested_multi_map', 'newaxis', 'nextafter', 'nonzero', 'normalize_axis_tuple', 'norms', 'not_equal', 'np', 'num_arrays_in_memory', 'num_cpu_cores', 'num_gpus', 'num_ivy_arrays_on_dev', 'one_hot', 'ones', 'ones_like', 'optimizer_update', 'optimizers', 'os', 'outer', 'output_to_native_arrays', 'outputs_to_ivy_arrays', 'pad', 'padding_ceil_mode', 'percent_used_mem_on_dev', 'permute_dims', 'pi', 'pinv', 'poisson', 'positive', 'pow', 'prelu', 'print_all_arrays_in_memory', 'print_all_ivy_arrays_on_dev', 'prod', 'promote_types', 'promote_types_of_inputs', 'promotion_table', 'prune_empty', 'prune_nest_at_index', 'prune_nest_at_indices', 'psutil', 'pynvml', 'python_copy', 'qr', 'quantile', 'queue_timeout_stack', 'rad2deg', 'randint', 'random', 'random_normal', 'random_uniform', 're', 'real', 'reciprocal', 'relu', 'remainder', 'repeat', 'reptile_step', 'reset_globals', 'reshape', 'result_type', 'roll', 'rot90', 'round', 'scaled_dot_product_attention', 'scatter_flat', 'scatter_nd', 'searching', 'searchsorted', 'seed', 'sequential', 'set', 'set_array_decimal_values', 'set_array_mode', 'set_array_significant_figures', 'set_backend', 'set_default_complex_dtype', 'set_default_device', 'set_default_dtype', 'set_default_float_dtype', 'set_default_int_dtype', 'set_default_uint_dtype', 'set_dynamic_backend', 'set_exception_trace_mode', 'set_global_attr', 'set_jax_backend', 'set_min_base', 'set_min_denominator', 'set_nan_policy', 'set_nest_at_index', 'set_nest_at_indices', 'set_nestable_mode', 'set_numpy_backend', 'set_queue_timeout', 'set_shape_array_mode', 'set_show_func_wrapper_trace_mode', 'set_split_factor', 'set_tensorflow_backend', 'set_tmp_dir', 'set_torch_backend', 'set_warning_level', 'set_with_grads', 'shape', 'shape_array_mode', 'shape_array_mode_stack', 'show_func_wrapper_trace_mode_stack', 'shuffle', 'sigmoid', 'sign', 'signbit', 'sin', 'sinc', 'sinh', 'slogdet', 'softmax', 'softplus', 'solve', 'sort', 'sorting', 'sparse_array', 'sparse_cross_entropy', 'split', 'split_factor', 'split_factors', 'split_func_call', 'sqrt', 'square', 'squeeze', 'stable_divide', 'stable_pow', 'stack', 'stateful', 'statistical', 'std', 'stop_gradient', 'subtract', 'sum', 'supports_gradients', 'supports_inplace_updates', 'svd', 'svdvals', 'swapaxes', 'sys', 'take_along_axis', 'tan', 'tanh', 'tensordot', 'tensorsolve', 'threading', 'thresholded_relu', 'tile', 'to_device', 'to_ivy', 'to_ivy_arrays_and_back', 'to_ivy_module', 'to_ivy_shape', 'to_list', 'to_native', 'to_native_arrays_and_back', 'to_native_shape', 'to_numpy', 'to_scalar', 'top_k', 'total_mem_on_dev', 'tpu_is_available', 'trace', 'trace_mode_dict', 'trapz', 'tril', 'tril_indices', 'triu', 'triu_indices', 'trunc', 'trunc_divide', 'try_array_function_override', 'try_else_none', 'type_promote_arrays', 'uint16', 'uint32', 'uint64', 'uint8', 'unique_all', 'unique_counts', 'unique_inverse', 'unique_values', 'unravel_index', 'unset_array_decimal_values', 'unset_array_mode', 'unset_array_significant_figures', 'unset_backend', 'unset_default_complex_dtype', 'unset_default_device', 'unset_default_dtype', 'unset_default_float_dtype', 'unset_default_int_dtype', 'unset_default_uint_dtype', 'unset_dynamic_backend', 'unset_exception_trace_mode', 'unset_nan_policy', 'unset_nestable_mode', 'unset_queue_timeout', 'unset_shape_array_mode', 'unset_show_func_wrapper_trace_mode', 'unset_warning_level', 'unset_with_grads', 'unstack', 'used_mem_on_dev', 'utility', 'utils', 'valid_complex_dtypes', 'valid_devices', 'valid_dtype', 'valid_dtypes', 'valid_float_dtypes', 'valid_int_dtypes', 'valid_numeric_dtypes', 'valid_uint_dtypes', 'value_and_grad', 'value_is_nan', 'vander', 'var', 'vec_sig_fig', 'vecdot', 'vector_norm', 'vector_to_skew_symmetric_matrix', 'verbosity', 'vmap', 'vorbis_window', 'vsplit', 'vstack', 'warn', 'warn_to_regex', 'warning_level', 'warning_level_stack', 'warnings', 'weakref', 'where', 'while_loop', 'with_backend', 'with_grads', 'with_grads_stack', 'with_supported_device_and_dtypes', 'with_supported_devices', 'with_supported_dtypes', 'with_unsupported_device_and_dtypes', 'with_unsupported_devices', 'with_unsupported_dtypes', 'wraps', 'xlogy', 'zero_pad', 'zeros', 'zeros_like', 'zeta']

**Comment by jkeane508** [comment]
> Partial solution; there is an error with my setup where the imports pass through fine, but when I run the code, I get a ModuleNotFoundError, like so:
> 
> Traceback (most recent call last): File "c:/Users/arioz/OneDrive/Documents/Programming/Python/ivy/ivy/functional/frontends/jax/numpy/mathematical_functions.py", line 11, in from ivy.functional.frontends.jax.func_wrapper import ( ModuleNotFoundError: No module named 'ivy.functional'
> 
> I tried adding the path to the ivy repo into sys.path, but the result is the same.
> 
> Another issue was the indentation of the yml file, but that was easily fixable.

Not sure I follow when you say run code, do you mean run tests or import Ivy into python?

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Noticed that this is still just a draft but just as a heads up, we can't merge any PRs that make changes outside of the files specific to the function implementation and the test.

Happy coding!

**Comment by Supremolink81** [comment]
> > Partial solution; there is an error with my setup where the imports pass through fine, but when I run the code, I get a ModuleNotFoundError, like so:
> > Traceback (most recent call last): File "c:/Users/arioz/OneDrive/Documents/Programming/Python/ivy/ivy/functional/frontends/jax/numpy/mathematical_functions.py", line 11, in from ivy.functional.frontends.jax.func_wrapper import ( ModuleNotFoundError: No module named 'ivy.functional'
> > I tried adding the path to the ivy repo into sys.path, but the result is the same.
> > Another issue was the indentation of the yml file, but that was easily fixable.
> 
> Not sure I follow when you say run code, do you mean run tests or import Ivy into python?

I cloned the repo onto my local machine, then tried to run the mathematical_functions.py file in VS Code. The file imported ivy, which worked without issue, but when it tried to import things from ivy.functional, it raised a ModuleNotFoundError. 

> To add to the last comment, I tried the following:
> 
> -cloning the repo from GitHub -downloading zip file -cloning the repo using Ivy's command
> 
> I did this all while using a venv set to Python 3.8. I tried both installing from the requirements.txt file and from ivy-core, neither fixed the issue.
> 
> Unsure if this helps, but here is the result of dir(ivy):
> 
> ['ACTIVATION_FUNCTIONS', 'Adam', 'Any', 'Array', 'Callable', 'ComplexDtype', 'Constant', 'Container', 'ContainerBase', 'Conv1D', 'Conv1DTranspose', 'Conv2D', 'Conv2DTranspose', 'Conv3D', 'Conv3DTranspose', 'DefaultComplexDtype', 'DefaultDevice', 'DefaultDtype', 'DefaultFloatDtype', 'DefaultIntDtype', 'DefaultUintDtype', 'DepthwiseConv2D', 'Device', 'Dict', 'Dropout', 'Dtype', 'DynamicBackendContext', 'FN_CACHE', 'FN_DECORATORS', 'Finfo', 'FirstLayerSiren', 'FloatDtype', 'Framework', 'FrameworkStr', 'FunctionType', 'GEGLU', 'GELU', 'Generator', 'GlobalsDict', 'GlorotUniform', 'GradientTracking', 'INF', 'IfElse', 'Iinfo', 'Initializer', 'IntDtype', 'Iterable', 'KaimingNormal', 'LAMB', 'LARS', 'LSTM', 'LayerNorm', 'Linear', 'List', 'Literal', 'Module', 'ModuleConverters', 'ModuleHelpers', 'MultiHeadAttention', 'NativeArray', 'NativeDevice', 'NativeDtype', 'NativeShape', 'NativeSparseArray', 'NativeVariable', 'NestedArray', 'NestedSequence', 'Node', 'Number', 'Ones', 'Optimizer', 'Optional', 'OrderedDict', 'Profiler', 'Protocol', 'SGD', 'Sequence', 'Sequential', 'Shape', 'Siren', 'SparseArray', 'SupportsBufferProtocol', 'TMP_DIR', 'Tuple', 'TypeVar', 'UintDtype', 'Uniform', 'Union', 'UserDict', 'WhileLoop', 'Zeros', '_MIN_BASE', '_MIN_DENOMINATOR', '**builtins**', '**cached**', '**doc**', '**file**', '**loader**', '**name**', '**package**', '**path**', '**spec**', '**version**', '_all_ivy_dtypes_str', '_assert_array_decimal_values_formatting', '_assert_array_significant_figures_formatting', '_default_globals', '_sf', '_version', 'abc', 'abs', 'acos', 'acosh', 'activations', 'adam_step', 'adam_update', 'add', 'add_array_specs', 'add_ivy_array_instance_methods', 'add_ivy_container_instance_methods', 'adjoint', 'all', 'all_complex_dtypes', 'all_devices', 'all_dtypes', 'all_equal', 'all_float_dtypes', 'all_int_dtypes', 'all_nested_indices', 'all_numeric_dtypes', 'all_uint_dtypes', 'allclose', 'angle', 'annotations', 'any', 'arange', 'arg_info', 'arg_names', 'argmax', 'argmin', 'args_to_ivy', 'args_to_native', 'argsort', 'argwhere', 'arr_conversions', 'array', 'array_api_promotion_table', 'array_decimal_values', 'array_decimal_values_stack', 'array_equal', 'array_mode_stack', 'array_significant_figures', 'array_significant_figures_stack', 'as_ivy_dev', 'as_ivy_dtype', 'as_native_dev', 'as_native_dtype', 'asarray', 'asarray_handle_nestable', 'asarray_infer_device', 'asarray_to_native_arrays_and_back', 'asin', 'asinh', 'assert_supports_inplace', 'assertions', 'ast', 'astype', 'atan', 'atan2', 'atanh', 'atleast_1d', 'atleast_2d', 'atleast_3d', 'avg_pool1d', 'avg_pool2d', 'avg_pool3d', 'backend', 'backend_stack', 'backend_version', 'bernoulli', 'beta', 'bfloat16', 'binarizer', 'binary_cross_entropy', 'binary_cross_entropy_with_logits', 'bind_custom_gradient_function', 'bitwise_and', 'bitwise_invert', 'bitwise_left_shift', 'bitwise_or', 'bitwise_right_shift', 'bitwise_xor', 'bool', 'broadcast_arrays', 'broadcast_shapes', 'broadcast_to', 'builtins', 'cache_fn', 'can_cast', 'ceil', 'check_float', 'cholesky', 'choose_random_backend', 'clear_backend_stack', 'clear_mem_on_dev', 'clip', 'clip_matrix_norm', 'clip_vector_norm', 'closest_valid_dtype', 'compiled_backends', 'complex128', 'complex64', 'compute_weight_mat', 'concat', 'constant_pad', 'constants', 'cont_conversions', 'container', 'container_types', 'control_flow_ops', 'conv', 'conv1d', 'conv1d_transpose', 'conv2d', 'conv2d_transpose', 'conv3d', 'conv3d_transpose', 'conv_general_dilated', 'conv_general_transpose', 'converters', 'copy', 'copy_array', 'copy_nest', 'copysign', 'corrcoef', 'cos', 'cosh', 'count_nonzero', 'creation', 'cross', 'cross_entropy', 'cumprod', 'cumsum', 'current_backend', 'current_backend_str', 'data_type', 'dct', 'default', 'default_complex_dtype', 'default_complex_dtype_stack', 'default_device', 'default_device_stack', 'default_dtype', 'default_dtype_stack', 'default_float_dtype', 'default_float_dtype_stack', 'default_int_dtype', 'default_int_dtype_stack', 'default_uint_dtype', 'default_uint_dtype_stack', 'deg2rad', 'del_global_attr', 'depthwise_conv2d', 'deserialize', 'det', 'dev', 'dev_handles', 'dev_util', 'device', 'dft', 'diag', 'diagflat', 'diagonal', 'diff', 'dirichlet', 'divide', 'double', 'dropout', 'dropout1d', 'dropout3d', 'dsplit', 'dstack', 'dtype', 'dtype_bits', 'duplicate_array_index_chains', 'dynamic_backend_as', 'dynamic_backend_stack', 'e', 'eig', 'eigh', 'eigh_tridiagonal', 'eigvals', 'eigvalsh', 'einops', 'einops_rearrange', 'einops_reduce', 'einops_repeat', 'einsum', 'elementwise', 'embedding', 'empty', 'empty_like', 'equal', 'erf', 'exception_trace_mode_stack', 'exceptions', 'execute_with_gradients', 'exists', 'exp', 'exp2', 'expand', 'expand_dims', 'experimental', 'expm1', 'extra_promotion_table', 'eye', 'eye_like', 'fft', 'finfo', 'fix', 'flatten', 'flip', 'fliplr', 'flipud', 'float16', 'float32', 'float64', 'float_power', 'floor', 'floor_divide', 'fmax', 'fmin', 'fmod', 'fn_array_spec', 'fomaml_step', 'fourier_encode', 'from_dlpack', 'full', 'full_like', 'func_wrapper', 'function_supported_devices', 'function_supported_devices_and_dtypes', 'function_supported_dtypes', 'function_unsupported_devices', 'function_unsupported_devices_and_dtypes', 'function_unsupported_dtypes', 'functional', 'functools', 'gamma', 'gather', 'gather_nd', 'gc', 'gcd', 'gelu', 'general', 'get', 'get_all_arrays_in_memory', 'get_all_ivy_arrays_on_dev', 'get_array_mode', 'get_backend', 'get_dynamic_backend', 'get_exception_trace_mode', 'get_item', 'get_min_base', 'get_min_denominator', 'get_nan_policy', 'get_nestable_mode', 'get_num_dims', 'get_queue_timeout', 'get_referrers_recursive', 'get_show_func_wrapper_trace_mode', 'get_tmp_dir', 'globals_vars', 'gpu_is_available', 'grad', 'gradient', 'gradient_descent_update', 'gradients', 'greater', 'greater_equal', 'hamming_window', 'handle_array_function', 'handle_array_like_without_promotion', 'handle_exceptions', 'handle_nans', 'handle_nestable', 'handle_out_argument', 'handle_view', 'handle_view_indexing', 'handler', 'hann_window', 'has_nans', 'heaviside', 'helpers', 'hsplit', 'hstack', 'hypot', 'i0', 'if_else', 'ifft', 'iinfo', 'imag', 'import_module_path', 'importlib', 'index_nest', 'inf', 'infer_default_dtype', 'infer_device', 'infer_dtype', 'initializers', 'inner', 'inplace_arrays_supported', 'inplace_decrement', 'inplace_increment', 'inplace_update', 'inplace_variables_supported', 'inputs_to_ivy_arrays', 'inputs_to_native_arrays', 'insert_into_nest_at_index', 'insert_into_nest_at_indices', 'inspect', 'instance_norm', 'int16', 'int32', 'int64', 'int8', 'integer_arrays_to_float', 'interp', 'interpolate', 'inv', 'invalid_complex_dtypes', 'invalid_devices', 'invalid_dtype', 'invalid_dtypes', 'invalid_float_dtypes', 'invalid_int_dtypes', 'invalid_numeric_dtypes', 'invalid_uint_dtypes', 'is_array', 'is_bool_dtype', 'is_complex_dtype', 'is_float_dtype', 'is_int_dtype', 'is_ivy_array', 'is_ivy_container', 'is_ivy_sparse_array', 'is_local', 'is_native_array', 'is_native_dtype', 'is_native_sparse_array', 'is_uint_dtype', 'isclose', 'isfinite', 'isin', 'isinf', 'isnan', 'isreal', 'isscalar', 'itertools', 'ivy', 'jac', 'kaiser_bessel_derived_window', 'kaiser_window', 'kron', 'l2_normalize', 'lamb_update', 'lars_update', 'layer_norm', 'layers', 'lcm', 'leaky_relu', 'less', 'less_equal', 'lexsort', 'linalg', 'linear', 'linear_algebra', 'linspace', 'locks', 'log', 'log10', 'log1p', 'log2', 'log_softmax', 'logaddexp', 'logaddexp2', 'logging', 'logical_and', 'logical_not', 'logical_or', 'logical_xor', 'logit', 'logspace', 'losses', 'lp_normalize', 'lstm_update', 'maml_step', 'manipulation', 'map', 'map_nest_at_index', 'map_nest_at_indices', 'match_kwargs', 'math', 'matmul', 'matrix_exp', 'matrix_norm', 'matrix_power', 'matrix_rank', 'matrix_transpose', 'max', 'max_chunk_sizes', 'max_pool1d', 'max_pool2d', 'max_pool3d', 'maximum', 'mean', 'median', 'meshgrid', 'meta', 'min', 'minimum', 'mish', 'module', 'moveaxis', 'msort', 'multi_head_attention', 'multi_index_nest', 'multinomial', 'multiply', 'multiprocessing', 'nan', 'nan_policy_stack', 'nan_to_num', 'nanmean', 'nanmedian', 'nansum', 'native_array', 'native_bfloat16', 'native_bool', 'native_complex128', 'native_complex64', 'native_double', 'native_float16', 'native_float32', 'native_float64', 'native_inplace_support', 'native_int16', 'native_int32', 'native_int64', 'native_int8', 'native_sparse_array', 'native_sparse_array_to_indices_values_and_shape', 'native_uint16', 'native_uint32', 'native_uint64', 'native_uint8', 'ndenumerate', 'ndindex', 'negative', 'nest', 'nestable_mode_stack', 'nested_any', 'nested_argwhere', 'nested_array', 'nested_map', 'nested_multi_map', 'newaxis', 'nextafter', 'nonzero', 'normalize_axis_tuple', 'norms', 'not_equal', 'np', 'num_arrays_in_memory', 'num_cpu_cores', 'num_gpus', 'num_ivy_arrays_on_dev', 'one_hot', 'ones', 'ones_like', 'optimizer_update', 'optimizers', 'os', 'outer', 'output_to_native_arrays', 'outputs_to_ivy_arrays', 'pad', 'padding_ceil_mode', 'percent_used_mem_on_dev', 'permute_dims', 'pi', 'pinv', 'poisson', 'positive', 'pow', 'prelu', 'print_all_arrays_in_memory', 'print_all_ivy_arrays_on_dev', 'prod', 'promote_types', 'promote_types_of_inputs', 'promotion_table', 'prune_empty', 'prune_nest_at_index', 'prune_nest_at_indices', 'psutil', 'pynvml', 'python_copy', 'qr', 'quantile', 'queue_timeout_stack', 'rad2deg', 'randint', 'random', 'random_normal', 'random_uniform', 're', 'real', 'reciprocal', 'relu', 'remainder', 'repeat', 'reptile_step', 'reset_globals', 'reshape', 'result_type', 'roll', 'rot90', 'round', 'scaled_dot_product_attention', 'scatter_flat', 'scatter_nd', 'searching', 'searchsorted', 'seed', 'sequential', 'set', 'set_array_decimal_values', 'set_array_mode', 'set_array_significant_figures', 'set_backend', 'set_default_complex_dtype', 'set_default_device', 'set_default_dtype', 'set_default_float_dtype', 'set_default_int_dtype', 'set_default_uint_dtype', 'set_dynamic_backend', 'set_exception_trace_mode', 'set_global_attr', 'set_jax_backend', 'set_min_base', 'set_min_denominator', 'set_nan_policy', 'set_nest_at_index', 'set_nest_at_indices', 'set_nestable_mode', 'set_numpy_backend', 'set_queue_timeout', 'set_shape_array_mode', 'set_show_func_wrapper_trace_mode', 'set_split_factor', 'set_tensorflow_backend', 'set_tmp_dir', 'set_torch_backend', 'set_warning_level', 'set_with_grads', 'shape', 'shape_array_mode', 'shape_array_mode_stack', 'show_func_wrapper_trace_mode_stack', 'shuffle', 'sigmoid', 'sign', 'signbit', 'sin', 'sinc', 'sinh', 'slogdet', 'softmax', 'softplus', 'solve', 'sort', 'sorting', 'sparse_array', 'sparse_cross_entropy', 'split', 'split_factor', 'split_factors', 'split_func_call', 'sqrt', 'square', 'squeeze', 'stable_divide', 'stable_pow', 'stack', 'stateful', 'statistical', 'std', 'stop_gradient', 'subtract', 'sum', 'supports_gradients', 'supports_inplace_updates', 'svd', 'svdvals', 'swapaxes', 'sys', 'take_along_axis', 'tan', 'tanh', 'tensordot', 'tensorsolve', 'threading', 'thresholded_relu', 'tile', 'to_device', 'to_ivy', 'to_ivy_arrays_and_back', 'to_ivy_module', 'to_ivy_shape', 'to_list', 'to_native', 'to_native_arrays_and_back', 'to_native_shape', 'to_numpy', 'to_scalar', 'top_k', 'total_mem_on_dev', 'tpu_is_available', 'trace', 'trace_mode_dict', 'trapz', 'tril', 'tril_indices', 'triu', 'triu_indices', 'trunc', 'trunc_divide', 'try_array_function_override', 'try_else_none', 'type_promote_arrays', 'uint16', 'uint32', 'uint64', 'uint8', 'unique_all', 'unique_counts', 'unique_inverse', 'unique_values', 'unravel_index', 'unset_array_decimal_values', 'unset_array_mode', 'unset_array_significant_figures', 'unset_backend', 'unset_default_complex_dtype', 'unset_default_device', 'unset_default_dtype', 'unset_default_float_dtype', 'unset_default_int_dtype', 'unset_default_uint_dtype', 'unset_dynamic_backend', 'unset_exception_trace_mode', 'unset_nan_policy', 'unset_nestable_mode', 'unset_queue_timeout', 'unset_shape_array_mode', 'unset_show_func_wrapper_trace_mode', 'unset_warning_level', 'unset_with_grads', 'unstack', 'used_mem_on_dev', 'utility', 'utils', 'valid_complex_dtypes', 'valid_devices', 'valid_dtype', 'valid_dtypes', 'valid_float_dtypes', 'valid_int_dtypes', 'valid_numeric_dtypes', 'valid_uint_dtypes', 'value_and_grad', 'value_is_nan', 'vander', 'var', 'vec_sig_fig', 'vecdot', 'vector_norm', 'vector_to_skew_symmetric_matrix', 'verbosity', 'vmap', 'vorbis_window', 'vsplit', 'vstack', 'warn', 'warn_to_regex', 'warning_level', 'warning_level_stack', 'warnings', 'weakref', 'where', 'while_loop', 'with_backend', 'with_grads', 'with_grads_stack', 'with_supported_device_and_dtypes', 'with_supported_devices', 'with_supported_dtypes', 'with_unsupported_device_and_dtypes', 'with_unsupported_devices', 'with_unsupported_dtypes', 'wraps', 'xlogy', 'zero_pad', 'zeros', 'zeros_like', 'zeta']

**Pull request closed without merging**
