### PR TITLE
Paddle frontend clip

### LINKED ISSUE #17913: clip

### PR DESCRIPTION
**Pull request by BBBenG23**
Close #17913 

Please let me know if there are any issues or if you have any questions. Thank you!

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by BBBenG23** [comment]
Do I need to worry about the failed checks? I tried some of the failing tests on my machine without my changes, and they still fail.

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi! Thanks for working on this 😄 It looks like most of the failing tests are unrelated, but could you take care of the lint [error](https://github.com/unifyai/ivy/actions/runs/5460237660/jobs/9937021948?pr=18022)? Hope this helps - https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit

**Comment by BBBenG23** [comment]
@rishabgit Thank you for taking a look at my pull request! I ran pre-commit and passed the lint test.

**Comment by rishabgit** [comment]
Thanks a ton for adding this! :))

**Pull request merged**
