### PR TITLE
Added argmin instance method to paddle.Tensor frontend

### LINKED ISSUE #16280: argmin

### PR DESCRIPTION
**Pull request by AbdelrhmanNile**
Close #16280

### CODE REVIEW

**Comment by RickSanchezStoic** [comment]
@AbdelrhmanNile Can you try resolving the merge conflicts, thanks!

**Comment by AbdelrhmanNile** [comment]
@RickSanchezStoic  done!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
