### PR TITLE
add: test quantile fronend jax numpy statistical

### LINKED ISSUE #14091: quantile

### PR DESCRIPTION
**Pull request by trantuantdt**
Close #14091

### CODE REVIEW

**Comment by trantuantdt** [comment]
Hi @V-G-spec . There is an error "The results from backend torch and ground truth framework jax do not match".  I believe that we should fix it in another backend issue.

**Comment by V-G-spec** [comment]
Just ensure intelligent test 1 is passing for now and that any error is not caused by your file changes. Ivy team is constantly working on the other issues

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
