### PR TITLE
feat: add increment method to paddle frontend

### LINKED ISSUE #26215: increment

### PR DESCRIPTION
**Pull request by muhammadhammad-tech**
Fixes https://github.com/unifyai/ivy/issues/26215

PR Description
Implemented the increment method in both math.py, test_math.py, tensor.py, and test_tensor.py.

Related Issue
Close https://github.com/unifyai/ivy/issues/26215

Checklist
 

- [x] Did you add a function?

 

- [x] Did you add the tests?

 

- [x] Did you run your tests and are your tests passing?

 

- [x] Did pre-commit not fail on any check?

 

- [x] Did you follow the steps we provided?

Socials

### CODE REVIEW

**Comment by muhammadhammad-tech** [comment]
really sorry for the mess i will be careful in my other PRs this one is just terrible, i am unable to resolve docs/demos conflict. will be looking forward for your response and guidance thank you @KareemMAX

**Comment by muhammadhammad-tech** [comment]
@juliagsy

**Comment by KareemMAX** [comment]
> really sorry for the mess i will be careful in my other PRs this one is just terrible, i am unable to resolve docs/demos conflict. will be looking forward for your response and guidance thank you @KareemMAX

No worries at all, you may revert the commits that involved the `doc/demos` conflict. Then you may use your IDE's GUI to not commit that change instead of always commiting all files

**Comment by muhammadhammad-tech** [comment]
@KareemMAX  is it good ? thank you.

**Comment by muhammadhammad-tech** [comment]
hey @KareemMAX  kindly can you check it.. thank you

**Comment by KareemMAX** [comment]
> hey @KareemMAX kindly can you check it.. thank you

Hey @muhammadhammad-tech, I'll leave it with @MuhammedAshraf2020 as he is your primary assignee.

**Comment by muhammadhammad-tech** [comment]
@MuhammedAshraf2020 kindly can you review it thank you

**Comment by MuhammedAshraf2020** [comment]
Hey @muhammadhammad-tech, thank you for your contribution 🙏🏻 we  appreciate it too much ☺️ will review it soon. Thanks

**Comment by Sarvesh-Kesharwani** [comment]
Hi @muhammadhammad-tech 
please resolve the merge conflicts.

**Comment by muhammadhammad-tech** [comment]
@Sarvesh-Kesharwani  could you check

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @muhammadhammad-tech 
Thanks for the PR.
Mostly good. Could you untangle the tensor method and its test from other methods and the tests. It seems to take on part from other functions and perhaps is the reason of so many new failures at https://github.com/unifyai/ivy/actions/runs/7604484114/job/20707480593?pr=27063. Let me know if unclear. Should be ready to merge. Pleaser request a review when made the update and let me know if something is unclear. Thanks a lot :)

**Comment by Ishticode** [comment]
Thank you very much for the PR. Closing this due to lack of activity with changes requested remaining unresolved for over a month. Please feel free to reopen if you would like to continue working on this. :)

**Pull request closed without merging**
