### PR TITLE
paddle.nn.functional.activation.glu and test

### PR DESCRIPTION
**Pull request by Adeola23**

### CODE REVIEW

**Comment by Adeola23** [comment]
@RickSanchezStoic

**Comment by Adeola23** [comment]
@RickSanchezStoic pls can you review

**Comment by RickSanchezStoic** [comment]
Hi @Adeola23 Can you undo the changes to the .idea files, and resolve the merge conflicts?
Thanks!

**Comment by Adeola23** [comment]
> Hi @Adeola23 Can you undo the changes to the .idea files, and resolve the merge conflicts?
> Thanks!

@RickSanchezStoic Done. Pls review

**Comment by Adeola23** [comment]
@RickSanchezStoic

**Comment by RickSanchezStoic** [comment]
@Adeola23 check `intelligent-tests-pr / run_tests (1) (pull_request)` for failures and fix them.

**Comment by Adeola23** [comment]
@RickSanchezStoic intelligent-tests-pr / run_tests (1) (pull_request) because it's running test for test_paddle_log_softmax instead of test_paddle_glu, how do I resolve it.

**Comment by RickSanchezStoic** [comment]
@RashulChutani It seems to be picking up the wrong test here, can you check this once?

**Comment by RashulChutani** [comment]
Hi @RickSanchezStoic, Sure.

**Comment by Adeola23** [comment]
@RickSanchezStoic

**Comment by Adeola23** [comment]
@RickSanchezStoic

**Pull request closed without merging**
