### PR TITLE
greater function-1st PR

### PR DESCRIPTION
**Pull request by Volthai7us**

### CODE REVIEW

**Review by HotzingTone — CHANGES_REQUESTED** [review]
Thanks! Once all tests pass we will review the code :)

**Comment by dmarinere** [comment]
@Volthai7us you have to fetch upstream on your GitHub first and resolve conflict before this can work.

**Comment by Volthai7us** [comment]
Tests past in my local computer. I don't know what is wrong

**Comment by mattbarrett98** [comment]
I have made a new PR #726, since Ivy has had so many changes since this PR was made its just easier to start a new one. (You will still be credited for the commit 🙂 )

**Pull request closed without merging**
