### PR TITLE
"Added nanmedian function and testing"

### PR DESCRIPTION
**Pull request by hopedonn**
Close https://github.com/unifyai/ivy/issues/19330

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by hopedonn** [comment]
@vedpatwardhan

**Comment by DragosStoican** [comment]
Hi @hopedonn . Great PR, thank you very much! Can you just make sure the formatting test passes and then I am happy to get this merged! You can find the errors [here] (https://github.com/unifyai/ivy/actions/runs/5548026318/jobs/10130470232?pr=19338) . Please only worry about the errors caused by the changes you've made. Looking forward to getting this merged soon!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by hopedonn** [comment]
Active

**Comment by hopedonn** [comment]
Fixed formatting issues @DragosStoican

**Pull request merged**
