### PR TITLE
Reformat logical_not

### LINKED ISSUE #2231: logical_not

### PR DESCRIPTION
**Pull request by vamsivallepu**
Reformatted logical_not function 
resolves #2231

### CODE REVIEW

**Comment by Unevilicorn** [comment]
Hi @vamsivallepu,
The example you have provided does not cover all the variation of the input, you can read more about it [here](https://lets-unify.ai/ivy/deep_dive/12_docstring_examples.html).

**Comment by vamsivallepu** [comment]
Hi @Unevilicorn 
Thanks for reviewing. I have gone through the link you have provided, and I think the only variation I have missed is ivy.Container. But as per the function arguments, it only accepts either ivy.Array or ivy.NativeArray. So does that mean I need to alter the function arguments too?

**Comment by Unevilicorn** [comment]
You don't need to alter the argument type, since this is all handled by the `@handle_nestable` decorator, you can read more about it [here](https://lets-unify.ai/ivy/deep_dive/5_containers.html#nestable-functions).

**Comment by vamsivallepu** [comment]
While working on examples of instance methods, I noticed that logical_not() is not working with ivy.NativeArray type as an instance method. Is it a bug, or do I have to mention, "this function doesn't work with the NativeArray type as an instance method"?

**Comment by vamsivallepu** [comment]
@Unevilicorn, I hope I have made the necessary changes. Can you please review my latest commit?

**Comment by Unevilicorn** [comment]
Looks good and I've merged this PR :slightly_smiling_face:

**Pull request merged**
