### PR TITLE
passing postitional args as kw for `paddle.Tensor.astype` at paddle frontend

### PR DESCRIPTION
**Pull request by akshatvishu**
Currently  the implementation for `paddle.Tensor.astype` is passing positional argument `dtype` as keyword argument which is throwing an error.

Implementation: [code](https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/paddle/tensor/tensor.py#L258)

Also, fixed the `decorator` to specify `bfloat16`  as the only unsupportive dtype as `ivy` doesn't support it at paddle backend yet, other than that all dtypes should be supported by `astype`

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ZoeCD** [comment]
Hello! Sorry for the late response. Good catch! Could you please resolve the merge conflicts? I'll merge your pull request after that

**Comment by akshatvishu** [comment]
> Hello! Sorry for the late response. Good catch! Could you please resolve the merge conflicts? I'll merge your pull request after that

Done!

**Comment by akshatvishu** [comment]
Thanks @ZoeCD  for the review!

**Pull request merged**
