### PR TITLE
index_add_

### LINKED ISSUE #26393: index_add_
index_add_ function

### PR DESCRIPTION
**Pull request by imsoumya18**
# PR Description
index_add_ method in Paddla FrontEnd

## Related Issue
index_add_ #26393 

Close #26393

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials
[Twitter](https://twitter.com/imsoumya184)

### CODE REVIEW

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey  @imsoumya18 ! Thanks for taking the time to work on this. Actually, we have a policy for keeping the [frontend implementations short](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#short-frontend-implementations) and this implementation is 25 lines long and there are 3 nested while loops in the code. Ideally, the frontend implementations should only contain a few lines. Therefore, I would advice you to first create an issue in our repo for adding the `index_add` function to ivy's functional API using this [template](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#creating-an-issue-on-ivy-s-github-using-a-template) guide. A memeber of our team will team review the request and add it to an open task. Then it's your choice, if you want to take it up yourself and wait for someelse else to pick it up. Otherwise, if you feel there's a way of making the frontend implementation short without adding this function to our functional API, I'd be happy to discuss the approach with you as well. Thanks !

**Comment by imsoumya18** [comment]
@NiteshK84 can u please have a look at it? Same as #26394 but, in place version.

**Comment by NiteshK84** [comment]
> @NiteshK84 can u please have a look at it? Same as #26394 but, in place version.

Hi @imsoumya18,
Could you kindly start by initiating the creation of a new issue for incorporating the index_add function into the IvyFunctional API?

**Comment by NiteshK84** [comment]
> > @NiteshK84 can u please have a look at it? Same as #26394 but, in place version.
> 
> Hi @imsoumya18, Could you kindly start by initiating the creation of a new issue for incorporating the index_add function into the IvyFunctional API?

as per the policy, we will have to update your previous function implementation as well.

**Comment by imsoumya18** [comment]
> > @NiteshK84 can u please have a look at it? Same as #26394 but, in place version.
> 
> Hi @imsoumya18, Could you kindly start by initiating the creation of a new issue for incorporating the index_add function into the IvyFunctional API as suggested by @hello-fri-end ?

I tried that. But, other devs didn't merge that saying a new functional API is unnecessary for such small reason and gave a green signal to go forward with this approach. That's why this is stuck for a long time. I'll try to pass the tests and let u know.

**Comment by NiteshK84** [comment]
> > > @NiteshK84 can u please have a look at it? Same as #26394 but, in place version.
> > 
> > 
> > Hi @imsoumya18, Could you kindly start by initiating the creation of a new issue for incorporating the index_add function into the IvyFunctional API as suggested by @hello-fri-end ?
> 
> I tried that. But, other devs didn't merge that saying a new functional API is unnecessary for such small reason and gave a green signal to go forward with this approach. That's why this is stuck for a long time. I'll try to pass the tests and let u know.

If that is the case, then you can sure go forward and work on fixing the remaining failing test cases.

**Comment by imsoumya18** [comment]
@NiteshK84 check once

**Comment by imsoumya18** [comment]
@NiteshK84 all tests passed !!

**Comment by imsoumya18** [comment]
@NiteshK84 all tests are passing now. Have a look at it...

**Comment by NiteshK84** [comment]
LGTM!
image

**Pull request merged**
