### PR TITLE
increment #17727

### LINKED ISSUE #17727: increment
https://github.com/unifyai/ivy/issues/15039

### PR DESCRIPTION
**Pull request by afarinizadi**
close #17727

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by afarinizadi** [comment]
Okay I have done that.

> If you are working on an open task, please **edit** the PR description to link to the issue you've created.
> 
> For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).
> 
> Thank you 🤗

**Comment by afarinizadi** [comment]
I don't seem to be able to connect the issue under development for some reason it's not allowing me. Do you know why?

**Review by YushaArif99 — COMMENTED** [review]
Hi @afarinizadi 

Apologies for the late review. Have been extremely busy with work recently and so haven't had the time to review PRs 😓 
The changes look good overall. However, the tests aren't showing up in the CI for some reason. I'll try running the tests locally just to confirm. For that, could you kindly sync your repo with the master branch just to iron out any erroneous bugs that have already been fixed in the branch from showing up? Thanks! 🙂

**Review by YushaArif99 — CHANGES_REQUESTED** [review]
Can you kindly re-request a review once you've synced your repo with the master branch. Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
