### PR TITLE
tanh_ added

### PR DESCRIPTION
**Pull request by shivam-151197**

### CODE REVIEW

**Comment by shivam-151197** [comment]
please review my code

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! Your implementation is currently failing and throwing the following error. Can you resolve it? Thanks!


```
x = ivy.array(-1.)

    @with_supported_dtypes({"2.4.2 and below": ("float32", "float64")}, "paddle")
    @to_ivy_arrays_and_back
    def tanh_(
        x,
        /,
        *,
        name=None,
    ):
        ret = ivy.tanh(x)
>       x.dtype = ret.dtype
E       AttributeError: can't set attribute
E       Falsifying example: test_paddle_tanh_(
E           dtype_and_x=(['float32'], [array(-1., dtype=float32)]),
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E               generate_frontend_arrays=False,
E           ),
E           fn_tree='ivy.functional.frontends.paddle.nn.functional.tanh_',
E           on_device='cpu',
E           frontend='paddle',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2AAAkYGCIDSAAAqAAM=') as a decorator on your test case

ivy/functional/frontends/paddle/nn/functional/activation.py:137: AttributeError
```

**Comment by shivam-151197** [comment]
@kurshakuz I have tried to solve the error. The problem I have figured is that,  while useing ivy.inplace_update() function response from backend changes which is not correct value for tanh(x) and if I don't use ivy.inplace_update() then value is exactly what it should be. 
Any suggestion will be a great help, Thanks.

**Comment by shivam-151197** [comment]
@kurshakuz I have fixed the issue please have a look again

**Pull request closed without merging**
