### PR TITLE
Added loss function in Distance_function.py

### LINKED ISSUE #12176: triplet_margin_with_distance_loss

### PR DESCRIPTION
**Pull request by Shivam7-1**
closes #12176

### CODE REVIEW

**Comment by Daniel4078** [comment]
hello, can you post a link to the issue this pull request is dealing with here? Thank you.

**Comment by Shivam7-1** [comment]
https://github.com/unifyai/ivy/issues/12176 
Issue: #12176

**Comment by Daniel4078** [comment]
You did not put your function in the correct place and you are supposed to add a test for your function as well, please refer to this merged pull request as an example for what is expected as it added another loss function correctly.

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
I repeat, you did not put your function in the correct place and you are supposed to add a test for your function as well, please refer to this merged pull request(https://github.com/unifyai/ivy/pull/2870/files) as an example for what is expected as it added another loss function correctly.

**Pull request closed without merging**
