### PR TITLE
Implement torch.Tensor.apply_

### LINKED ISSUE #18185: apply_
Implement torch.Tensor.apply_

### PR DESCRIPTION
**Pull request by yopknopixx**
This PR implements `torch.Tensor.apply_` and closes #18185

### CODE REVIEW

**Comment by V-G-spec** [comment]
Can you please resolve the conflicts?
Thanks!

**Comment by V-G-spec** [comment]
Hey, can you run these tests locally once and share the screenshot of whether they are passing or not? Include relevant information in the SS, so I can map each result to your PR
(Copying this to all your recent PRs)

**Comment by yopknopixx** [comment]
Hey @V-G-spec please have a look at the following test report:
[implement_torch_tensor_apply_.csv](https://github.com/unifyai/ivy/files/12013763/implement_torch_tensor_apply_.csv)

**Comment by V-G-spec** [comment]
Didn't see any errors in the logs, but it would be great if you could share the screenshots from your local machine test passing, as I asked earlier
Thanks!

**Comment by yopknopixx** [comment]
test_torch_instance_apply_

**Comment by V-G-spec** [comment]
Thanks!

**Pull request merged**
