### PR TITLE
Cov

### LINKED ISSUE #22490: cov

### PR DESCRIPTION
**Pull request by samthakur587**
# added the cov method to paddle frontend Tensor.

## In this PR I have added the cov method to paddle frontend. which is use to calculate the covariance matrix.

# Close #22490

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by samthakur587** [comment]
hii , i have try my best to implement this function by reding all the docs and source code from paddle and other framework. but i stuck in a error and now getting any way to come out from this can you please help me to solve this error.

image

even i have implemented this cov method to paddle linalg frontend. there my all the cases are passing. i don't why not here they are passing.

thank you

**Comment by Sarvesh-Kesharwani** [comment]
Hello @samthakur587, please resolve the merge conflicts and let me know, I'll review your PR.
Thanks

**Comment by Sarvesh-Kesharwani** [comment]
Hi @samthakur587, 
please work on the changes suggested, and also remove all the changes unrelated to the target function implementation.

**Comment by samthakur587** [comment]
Hii! @Sarvesh-Kesharwani Thinks for Review i made the changes. actually there is small mistake in composite decoretor i fixed this and now it's passing all the test cases.  

image

please let me know is there any other changes required. otherwise it's ready to merge 🚀 

Thanks  
samthakur

**Pull request merged**
