### PR TITLE
Added Torch select

### PR DESCRIPTION
**Pull request by VictorOdede**
Close https://github.com/unifyai/ivy/issues/14388

### CODE REVIEW

**Comment by VictorOdede** [comment]
Close #14388

**Comment by VictorOdede** [comment]
@vaatsalya123 Kindly review this PR

**Comment by VictorOdede** [comment]
Hey @vaatsalya123 , I fixed the merge conflict on this branch

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by VictorOdede** [comment]
Waiting for review

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @VictorOdede 

I tried to run the tests locally but they're failing due to this branch hasn't been updated.
Would you update with the latest changes😊

Thanks

**Review by hirwa-nshuti — APPROVED** [review]
Looks good to me!

Going to merge😊

**Pull request merged**
