### PR TITLE
reformatted activations.py for sigmoid 

### PR DESCRIPTION
**Pull request by shoryak**
sigmoid_reformatting_checklist_activations

WIP ,
1.) Function arguments reformatted 

Please comment and advice as I will be adding more commits to complete the subtask. 
#5153  #754

### CODE REVIEW

**Comment by Daniel4078** [comment]
Can you leave a link to the issue this pull request is dealing with?

**Comment by Daniel4078** [comment]
Please refer to this guide(https://docs.google.com/document/d/1DGY3x5VwIpYIV-7Ko-sCdTD1sTAtlhWLNAy70BXGqw8) and add the automatic checklist for reformatting task. Thank you!

**Comment by shoryak** [comment]
> (https://docs.google.com/document/d/1DGY3x5VwIpYIV-7Ko-sCdTD1sTAtlhWLNAy70BXGqw8) 

I am unable to access this document , I have requested for permissions though , Thankyou

**Comment by Daniel4078** [comment]
> > (https://docs.google.com/document/d/1DGY3x5VwIpYIV-7Ko-sCdTD1sTAtlhWLNAy70BXGqw8)
> 
> I am unable to access this document , I have requested for permissions though , Thankyou

Well, in short:
To add the reformatting checklist to a PR:
The PR author should add a comment on their PR with the format: 

add_reformatting_checklist_<category_name>

Where <category_name> is the category name of the function addressed in the PR.
E.g. for the function ‘add’ under the category elementwise, the applicant will comment “add_reformatting_checklist_elementwise”
This comment will then automatically be edited with the reformatting checklist including links to the relevant files for the category.

**Comment by Daniel4078** [comment]
And I think you can look at this instead https://lets-unify.ai/ivy/contributing/4_open_tasks.html#formatting-checklist

**Comment by shoryak** [comment]
sigmoid_reformatting_checklist_activations

**Comment by shoryak** [comment]
> > > (https://docs.google.com/document/d/1DGY3x5VwIpYIV-7Ko-sCdTD1sTAtlhWLNAy70BXGqw8)
> > 
> > 
> > I am unable to access this document , I have requested for permissions though , Thankyou
> 
> Well, in short: To add the reformatting checklist to a PR: The PR author should add a comment on their PR with the format:
> 
> add_reformatting_checklist_<category_name>
> 
> Where <category_name> is the category name of the function addressed in the PR. E.g. for the function ‘add’ under the category elementwise, the applicant will comment “add_reformatting_checklist_elementwise” This comment will then automatically be edited with the reformatting checklist including links to the relevant files for the category.

Got it  , I will do that right away

**Comment by shoryak** [comment]
add_reformatting_checklist_activations

**Comment by shoryak** [comment]
@Daniel4078  am I doing something wrong with my comments to add the checklist as it hasn't worked as of yet

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
