### PR TITLE
sigmoid_focal_loss function creation for frontend NN paddle

### LINKED ISSUE #19759: sigmoid_focal_loss

### PR DESCRIPTION
**Pull request by Davidch4r**
Close #19759

### CODE REVIEW

**Comment by Davidch4r** [comment]
Hey to whoever reads this, I'm still quite new to PR's in GitHub so I accidentally added a new commit of me deleting a file as a part of a new commit. I meant to just remove it from my commit but it seems to not have worked. Sorry

**Review by zaeemansari70 — CHANGES_REQUESTED** [review]
Kindly un-commit your changes from the `.idea` folder thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @Davidch4r, thanks for the PR. However you would need to also add a test for your implementation as it is for all the frontend functions in your file (for reference). Furthermore, your PR doesn't replicate the full function signature of the native paddle function: https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/sigmoid_focal_loss_en.html. You have also made changes to the `.idea` folder which I'll need you to uncommit. Thanks!

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
