### PR TITLE
Paddle scale

### LINKED ISSUE #22158: scale

### PR DESCRIPTION
**Pull request by Gauravpadam**
Closes #22158

### CODE REVIEW

**Review by AryanSharma21 — COMMENTED** [review]
Hey, @Gauravpadam , Going through the test log here. The function is not passing for paddle and numpy backend 

For Paddle , 
`E   AssertionError:  the results from backend paddle and ground truth framework paddle do not match
E    -1.4873869585846142e-06!=0.0 `

For numpy

`E   AssertionError:  the results from backend numpy and ground truth framework paddle do not match
E    -0.019593140068901116!=-0.01959433601226124 `

I guess, for Numpy backend, setting a tolerance level might help. 
Also, I would like to be a part of this discussion. Am willing to learn , Thanks

**Comment by Gauravpadam** [comment]
Hey @AryanSharma21, Thanks for the feedback, Always appreciated!
Yes perhaps we should manage the threshold at the backend, Thanks for pointing that out.

**Comment by YushaArif99** [comment]
Hi @Gauravpadam 

Really sorry for not reviewing the PR in time. Dont know how this totally slipped under the radar somehow 🙏🏼 😅. However, a suggestion I'd like to make is to kindly DM me on Discord as well if I don't respond in time since I'm mostly active on Discord and sometimes overlook the email notifications (since there are a bunch of them I get on a daily basis aha). 

Anyways, with regards to the PR, could you kindly first resolve the merge conflicts and re-request a review once that's done. I'll then start the review. Thanks for the patience @Gauravpadam 🙂

**Comment by Gauravpadam** [comment]
@YushaArif99 I think I should be starting a new branch rather than rebasing this one, Since the histories differ a lot now that It has been this long 😅. No worries, I'll make a new PR for this

**Pull request closed without merging**
