### PR TITLE
feat(jax frontend): implement extract function #26581

### LINKED ISSUE #26581: extract

### PR DESCRIPTION
**Pull request by mikekwabs**
**PR Description**

Added extract function for jax frontend API in ivy/functional/frontends/jax/numpy/searching_sorting.py file

__Related Issue__
#26581 

Close #26581

### CODE REVIEW

**Comment by mikekwabs** [comment]
@rishabgit

**Comment by mikekwabs** [comment]
@rishabgit

**Comment by mikekwabs** [comment]
hi @Aarsh2001. Could you please review my PR. thank you.

**Comment by mikekwabs** [comment]
@vedpatwardhan

**Review by rishabgit — CHANGES_REQUESTED** [review]
Hi, thanks for adding this! 😄 I fixed a slight typo in the import, but the tests seem to be still failing, could you please look into it? Thanks!

`pytest /workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_searching_sorting.py::test_jax_extract`

**Comment by vedpatwardhan** [comment]
> @vedpatwardhan

@rishabgit would be reviewing this PR, thanks @mikekwabs 😄

**Pull request closed without merging**
