### PR TITLE
add test_dot experimental linalg

### PR DESCRIPTION
**Pull request by TugayGul**
# PR Description 
add test_dot to ivy.functional.experimental

### CODE REVIEW

**Comment by sondertg** [comment]
Hi, below `dtypes` are not working, investigating the reason. There is no supported/unsupported dtype decorator on there so I can filter those but not sure this is right thing to do.
`INT64, INT32, INT16, DOUBLE, FLOAT, BFLOAT16, HALF, COMPLEX128, COMPLEX64`

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by Ishticode — CHANGES_REQUESTED** [review]
The test is still failing. Please figure out the unsupported dtypes and add a decorator accordingly. This should hopefully fix the issue. Thanks 🙂️

**Comment by sondertg** [comment]
There is no such decorator used in there. Moreover, When I run test_linalg.py to see which tests are passing, can't see much to check why my test function fails.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Sarvesh-Kesharwani** [comment]
Hi @TugayGul,
You haven't linked this pull request to any open issues. Please refer to the contribution guide in the Ivy docs for guidance. Additionally, it appears that you initially implemented the target function, but in subsequent commits, it was removed. Kindly address this issue and inform me once resolved. Thank you for your contribution.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
