### PR TITLE
Update linear_algebra.py

### PR DESCRIPTION
**Pull request by yluoc**
update inf and -inf from float to string in ivy/data_classes/array/linear_algebra.py/matrix_norm.

### CODE REVIEW

**Comment by yluoc** [comment]
A red line when I open the file I mentioned above and I fix it, please check it if you think it is not correct or you can improve if you have better solution.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by V-G-spec** [comment]
Hey @yluoc thanks a lot for your contribution! I see some failing tests with your changes. Do you mind taking a look at them? You can easily track them by searching for your function/file in combined logs. It is possible that these are due to other files. Confirm the same, and do share a screenshot of the tests passing in your local machine while updating

Thanks!

**Comment by V-G-spec** [comment]
Seeing no updates in a month, I'm closing this

**Comment by V-G-spec** [comment]
Seeing no updates in a month, I'm closing this

**Pull request closed without merging**
