### PR TITLE
reformat adam_step

### LINKED ISSUE #1640: adam_step

### PR DESCRIPTION
**Pull request by hirwa-nshuti**
Added functional examples to the adam_step function resolves #1640

### CODE REVIEW

**Comment by hirwa-nshuti** [comment]
> The container instance methods can be found here: https://github.com/unifyai/ivy/blob/master/ivy/container/gradients.py#L161. I don't believe the array instance method exists yet so could you please add this (you should be able to basically copy the way it's done in other array instance methods)

As you can see here I think the issue I was working on is the method of adam_step()  as shown here https://github.com/unifyai/ivy/issues/776 and in the container instance, it is not there. The one you referenced is adam_update and I think I can work on it after this PR is merged so I can open a new Issue of the adam_update() method.

Thanks.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hi, yes you're right `adam_update` is another function my bad.

If you look under test_docstrings action it shows the list of functions/methods whose docstrings examples aren't working properly. It seems most of yours are currently listed in here, please could you fix the examples 🙂

**Comment by hirwa-nshuti** [comment]
Hi, I worked on the changes you asked for and all the tests are passing now.
Thanks

**Comment by hirwa-nshuti** [comment]
Hi, I hardly finally finished my examples and now the warnings am receiving are common to all other PRs I came across, I don't know if there is something I can do about it.

Thanks.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Hey, in the type hints we don't include `ivy.Container` as you have in the functional `adam_step` (this is just for brevity). Also in your container example you have explicitly set the backend to torch which you shouldn't do, were you having issues with the other backends?

**Comment by hirwa-nshuti** [comment]
Hello @mattbarrett98,

Actually, I had a slight problem using the backends but I found it was due to my mistakes in passing arguments to the functions. Here are the changes, I removed explicitly set backends and also removed the `ivy.Container` type hint in the functional `adam_step` method. But for the container method, I included them in there. 

Thanks

**Review by mattbarrett98 — COMMENTED** [review]
Looks good, thank you!

**Pull request merged**
