### PR TITLE
Adds `paddle.tensor.logic.bitwise_not` function to PaddlePaddle Frontend

### LINKED ISSUE #16515: bitwise_not

### PR DESCRIPTION
**Pull request by DubeySandeep**
Close #16515

### CODE REVIEW

**Comment by DubeySandeep** [comment]
One of the tests failed on this PR: https://github.com/unifyai/ivy/actions/runs/5232837663/jobs/9447856652?pr=16516#step:3:116

Looks like it failed during setup and I see multiple PRs failing around the same lines. Can someone restart the test in case it's a flaky/unexpected error?

**Comment by AnnaTz** [comment]
> One of the tests failed on this PR: https://github.com/unifyai/ivy/actions/runs/5232837663/jobs/9447856652?pr=16516#step:3:116
> 
> Looks like it failed during setup and I see multiple PRs failing around the same lines. Can someone restart the test in case it's a flaky/unexpected error?

Hi @DubeySandeep, I have restarted all CI checks. Other than that, your implementation looks good to me!

**Comment by DubeySandeep** [comment]
Hi @AnnaTz, Thanks for reviewing the PR and restarting the builds. It looks like the build got canceled and failed unexpectedly (or because of an unknown reason), would you mind restarting [the only failed check](https://github.com/unifyai/ivy/actions/runs/5232837663/jobs/9469871597?pr=16516)?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
