### PR TITLE
 Paddle Frontend Convolution

### LINKED ISSUE #15834: conv2d

### LINKED ISSUE #21078: conv1d

### LINKED ISSUE #21079: conv3d

### LINKED ISSUE #21107: conv1d_transpose

### LINKED ISSUE #21108: conv2d_transpose

### LINKED ISSUE #21109: conv3d_transpose

### PR DESCRIPTION
**Pull request by NouranYoussef**
close #21078
closes #15834 
closes #21079 
closes #21108 
closes #21109
closes #21107

### CODE REVIEW

**Comment by Daniel4078** [comment]
ivy-gardener

**Comment by NouranYoussef** [comment]
@Daniel4078 could u pls review the functions. i've reused other functions defined for pytorch's frontend , as both frameworks' functions are almost the same except that paddle functions accept data_format input which is handled

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Found some failures for the tensorflow backend in the test log for you to fix:
E   ivy.utils.exceptions.IvyBackendException: tensorflow: conv: tensorflow: conv_general_dilated: {{function_node __wrapped__Conv3D_device_/job:localhost/replica:0/task:0/device:CPU:0}} CPU implementation of Conv3D currently only supports dilated rates of 1. [Op:Conv3D] name: 
E   Falsifying example: test_paddle_conv3d(
E       on_device='cpu',
E       frontend='paddle',
E       backend_fw='tensorflow',
E       dtype_vals=(['float64'],
E        array([[[[[0.5]]]]]),
E        array([[[[[0.5]]]]]),
E        array([0.5]),
E        2,
E        2,
E        'valid',
E        1),
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=0,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=False,
E       ),
E       fn_tree='ivy.functional.frontends.paddle.nn.functional.conv3d',
E   )

**Review by Daniel4078 — CHANGES_REQUESTED** [review]
Here I found another small problem maybe related to the different behavior of the same function in different frameworks, please have a look:
```
E   AssertionError:  the results from backend numpy and ground truth framework paddle do not match
E    [[[[[0.75]]
E   
E      [[1.  ]]
E   
E      [[0.75]]]]]!=[[[[[1.  ]]
E   
E      [[1.  ]]
E   
E      [[0.75]]]]] 
E   
E   
E   Falsifying example: test_paddle_conv3d(
E       on_device='cpu',
E       frontend='paddle',
E       backend_fw='numpy',
E       dtype_vals=(['float32'], array([[[[[0.5]],
E        
E                 [[0.5]],
E        
E                 [[0.5]]]]], dtype=float32), array([[[[[0.5]],
E        
E                 [[0.5]]]]], dtype=float32), array([0.5], dtype=float32), [2,
E         1,
E         1], 1, 'same', 1),
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=0,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=False,
E       ),
E       fn_tree='ivy.functional.frontends.paddle.nn.functional.conv3d',
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.2', b'AXicY2QAAUYGKIAzDjAwUMhkYAAAt5sEhA==') as a decorator on your test case
```

**Comment by NouranYoussef** [comment]
> Here I found another small problem maybe related to the different behavior of the same function in different frameworks, please have a look:
> 
> ```
> E   AssertionError:  the results from backend numpy and ground truth framework paddle do not match
> E    [[[[[0.75]]
> E   
> E      [[1.  ]]
> E   
> E      [[0.75]]]]]!=[[[[[1.  ]]
> E   
> E      [[1.  ]]
> E   
> E      [[0.75]]]]] 
> E   
> E   
> E   Falsifying example: test_paddle_conv3d(
> E       on_device='cpu',
> E       frontend='paddle',
> E       backend_fw='numpy',
> E       dtype_vals=(['float32'], array([[[[[0.5]],
> E        
> E                 [[0.5]],
> E        
> E                 [[0.5]]]]], dtype=float32), array([[[[[0.5]],
> E        
> E                 [[0.5]]]]], dtype=float32), array([0.5], dtype=float32), [2,
> E         1,
> E         1], 1, 'same', 1),
> E       test_flags=FrontendFunctionTestFlags(
> E           num_positional_args=0,
> E           with_out=False,
> E           inplace=False,
> E           as_variable=[False],
> E           native_arrays=[False],
> E           generate_frontend_arrays=False,
> E       ),
> E       fn_tree='ivy.functional.frontends.paddle.nn.functional.conv3d',
> E   )
> E   
> E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.2', b'AXicY2QAAUYGKIAzDjAwUMhkYAAAt5sEhA==') as a decorator on your test case
> ```



> Here I found another small problem maybe related to the different behavior of the same function in different frameworks, please have a look:
> 
> ```
> E   AssertionError:  the results from backend numpy and ground truth framework paddle do not match
> E    [[[[[0.75]]
> E   
> E      [[1.  ]]
> E   
> E      [[0.75]]]]]!=[[[[[1.  ]]
> E   
> E      [[1.  ]]
> E   
> E      [[0.75]]]]] 
> E   
> E   
> E   Falsifying example: test_paddle_conv3d(
> E       on_device='cpu',
> E       frontend='paddle',
> E       backend_fw='numpy',
> E       dtype_vals=(['float32'], array([[[[[0.5]],
> E        
> E                 [[0.5]],
> E        
> E                 [[0.5]]]]], dtype=float32), array([[[[[0.5]],
> E        
> E                 [[0.5]]]]], dtype=float32), array([0.5], dtype=float32), [2,
> E         1,
> E         1], 1, 'same', 1),
> E       test_flags=FrontendFunctionTestFlags(
> E           num_positional_args=0,
> E           with_out=False,
> E           inplace=False,
> E           as_variable=[False],
> E           native_arrays=[False],
> E           generate_frontend_arrays=False,
> E       ),
> E       fn_tree='ivy.functional.frontends.paddle.nn.functional.conv3d',
> E   )
> E   
> E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.2', b'AXicY2QAAUYGKIAzDjAwUMhkYAAAt5sEhA==') as a decorator on your test case
> ```

Thanks for pointing that out, I've found that the inconsistency arises from the difference in how PaddlePaddle handles padding and dilation in comparison to other frameworks. Specifically, in PaddlePaddle, when the padding is 'same', the dilation is overwritten to 1. 
see: https://github.com/PaddlePaddle/Paddle/blob/8bdb336d92800112f9ced17a70a6faf26d3b2006/paddle/phi/kernels/cpu/conv_util.h#L21

so to align the behavior of the frontend function, i've updated the implementation to match that of PaddlePaddle:
so the dilation is now overwritten to 1 when the padding is same

**Review by Daniel4078 — APPROVED** [review]
Looks good to me! Thanks

**Pull request merged**
