### PR TITLE
Cross

### PR DESCRIPTION
**Pull request by shireenchand**
Added tensorflow cross frontend and test

### CODE REVIEW

**Comment by shireenchand** [comment]
Close #10858

**Comment by shireenchand** [comment]
@aditya-hari this pr is in the correct format and doesn't use tf. Please review this

**Comment by aditya-hari** [comment]
The "closes #" is supposed to link to an issue, while it links to itself here.

**Comment by shireenchand** [comment]
Close #11055

**Comment by shireenchand** [comment]
> The "closes #" is supposed to link to an issue, while it links to itself here (and in the other 2 PRs as well).

Got it! Sorry for the confusion. I have done the required

**Comment by aditya-hari** [comment]
Great! Can you just link that to the ToDo list issue now? You need to comment the following in the ToDo list 
``` 
- [ ] #number  
````

**Comment by shireenchand** [comment]
> Great! Can you just link that to the ToDo list issue now? You need to comment the following in the ToDo list
> 
> ```
> - [ ] #number  
> ```

Done for all!

**Comment by aditya-hari** [comment]
Great! The tests look good for this but for the sake of thoroughness, can you implement tests similar to that in [Torch's cross](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py#L405)? Right now your test only accounts for 3-element vectors, but cross can have  vectors of greater size as well as long as the innermost dimension is 3.

**Comment by shireenchand** [comment]
Made the required changes. Thanks for pointing out that necessary check!

**Comment by aditya-hari** [comment]
Looks good to me!

**Pull request merged**
