### PR TITLE
added the numpy trace function frontend

### LINKED ISSUE #18013: trace

### PR DESCRIPTION
**Pull request by Maxzeno**
Close #18013

### CODE REVIEW

**Comment by Maxzeno** [comment]
#18013

**Comment by theRealBird** [comment]
Hi @Maxzeno,

Thank you so much for contributing to Ivy. To make sure Ivy is accurate and works the way it is meant to, we implement test functions for every frontend function we implement.

Could you please add the corresponding test function for `trace`? Thanks!

**Comment by Maxzeno** [comment]
@theRealBird Okay

**Comment by Maxzeno** [comment]
@theRealBird please review the changes I added a test function for trace as requested by you

Thanks

**Comment by Maxzeno** [comment]
@theRealBird @ivy-leaves @thecoder12 @edaehn @

Please review and merge my pull request

**Comment by theRealBird** [comment]
Hi @Maxzeno,
Thank you for your patience and adding the test function. However, it seems that the function is failing the tests. Could you please confirm and fix the errors?

**Comment by Maxzeno** [comment]
@theRealBird correct me if am wrong but the run_test 1, 14 and some other run test don't pass (I checked a lot of pull requests and noticed the same thing) 

**But I ran my own tests and they passed**
if you have the time check my latest commit to this pull request 
thank you for your time

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Maxzeno** [comment]
@theRealBird please review again

**Comment by juliagsy** [comment]
Hey! Many apologies for the delayed review of the previous assignee, I've just very recently been assigned to the pr and was about to check the test, but could you please update your branch to the latest master commit so that everything is up to date? I'll try to check back soonest possible on a working day, thanks!

**Comment by juliagsy** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
