### PR TITLE
Added unsorted_segment_sum

### LINKED ISSUE #19711: unsorted_segment_sum

### PR DESCRIPTION
**Pull request by adnanlabib1509**
Close #19711

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by adnanlabib1509** [comment]
Hi @sagewhocodes can u please review the PR and let me knew if any changes are needed. Thanks

**Comment by sagewhocodes** [comment]
Hi @adnanlabib1509 , Apologies for the delay. I'll go through your PR now!

**Comment by sagewhocodes** [comment]
LGTM!

**Pull request merged**
