### PR TITLE
reformat: floor - added relevant docstrings and docstring examples

### LINKED ISSUE #1278: floor

### PR DESCRIPTION
**Pull request by bhattbhuwan13**
fixes #1278

### CODE REVIEW

**Comment by bhattbhuwan13** [comment]
Hey @Ishticode, thanks for the review. 

Regarding formatting the `floor()` method in the backends, here is what the [instructions](https://lets-unify.ai/ivy/deep_dive/10_docstrings.html) say:

> All functions in the Ivy API at `ivy/functional/ivy/category_name.py` should have full and thorough docstrings. In contrast, all backend implementations at `ivy/functional/backends/backend_name/category_name.py` should not have any docstrings, on account that these are effectively just different instantiations of the functions at `ivy/functional/ivy/category_name.py`.


Ignoring the docstrings, the `floor()` method in the backends have the required type hints. 

```python
./ivy/functional/backends/mxnet/elementwise.py:def floor(x: mx.nd.NDArray, out: Optional[mx.nd.NDArray] = None) -> mx.nd.NDArray:
./ivy/functional/backends/torch/elementwise.py:def floor(x: torch.Tensor, *, out: Optional[torch.Tensor] = None) -> torch.Tensor:
./ivy/functional/backends/numpy/elementwise.py:def floor(x: np.ndarray, *, out: Optional[np.ndarray] = None) -> np.ndarray:
./ivy/functional/backends/tensorflow/elementwise.py:def floor(x: Tensor) -> Tensor:
./ivy/functional/backends/jax/elementwise.py:def floor(x: JaxArray) -> JaxArray:
```

Also, the issue I raised has some context. Specially this comment: https://github.com/unifyai/ivy/issues/1278#issuecomment-1146731999

**Review by Ishticode — CHANGES_REQUESTED** [review]
@bhattbhuwan13 Thnks for the referencing. Yes, I am aware that there is no need for a docstring in the backend. If you can kindly take a look at the [floor function in torch backend](https://github.com/unifyai/ivy/blob/96ffe3f5e2393639ff5b45375630e26c3893e2c8/ivy/functional/backends/torch/elementwise.py#L84), you will see that it needs slight adjustment such as every argument and return type-hint to be moved to on newline. It does have type hints so there is no need for that. For an example, check the format of the function on [this link](https://lets-unify.ai/ivy/deep_dive/0_navigating_the_code.html#backend-api). This is not a big change so perhaps won't require much effort. Sry if this was not clear beforehand.

**Comment by bhattbhuwan13** [comment]
@Ishticode, Thanks for the clarification. I will work on it. Thanks.

**Comment by bhattbhuwan13** [comment]
@Ishticode, I set my editor to auto format my code according to the numpy style(which is the one followed by this repo). Here is a snapshot of what I get after running it. Let me know if it is ok. After your confirmation I will change the code in other files too. 

```python
@_handle_flat_arrays_in_out
def floor(
    x: mx.nd.NDArray, out: Optional[mx.nd.NDArray] = None
) -> mx.nd.NDArray:
    ret = mx.nd.floor(x)
    if ivy.exists(out):
        return ivy.inplace_update(out, ret)
    return ret

```

**Comment by Ishticode** [comment]
> @Ishticode, I set my editor to auto format my code according to the numpy style(which is the one followed by this repo). Here is a snapshot of what I get after running it. Let me know if it is ok. After your confirmation I will change the code in other files too.
> 
> ```python
> @_handle_flat_arrays_in_out
> def floor(
>     x: mx.nd.NDArray, out: Optional[mx.nd.NDArray] = None
> ) -> mx.nd.NDArray:
>     ret = mx.nd.floor(x)
>     if ivy.exists(out):
>         return ivy.inplace_update(out, ret)
>     return ret
> ```

Hi. That seems perfect. Could you just make sure the editor doesn't automatically change all functions in a file or something... Otherwise, it seems good. Thanks.

**Comment by bhattbhuwan13** [comment]
@Ishticode, done :) .

**Comment by bhattbhuwan13** [comment]
Got some linting error. Will fix them

**Comment by bhattbhuwan13** [comment]
@Ishticode, got some linting errors in `setup.py` file which is unrelated to the files I made changes to. Everything else is as expected. Please review.

**Review by Ishticode — APPROVED** [review]
@bhattbhuwan13 great work and examples. Had to make a slight mod in jax and tf backend to put return part on next line.
I will go ahead and merge it now. Thank you for your contribution : )

**Comment by bhattbhuwan13** [comment]
@Ishticode, Thanks for your help :).

**Pull request merged**
