### PR TITLE
Torch frontend square

### PR DESCRIPTION
**Pull request by artykov1511**

### CODE REVIEW

**Comment by artykov1511** [comment]
Close #7804

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by V-G-spec** [comment]
Hi @artykov1511, thanks for your contribution!
Can you please resolve the merge conflicts?

**Comment by artykov1511** [comment]
@V-G-spec, Ive done it. Pleae, take a look and let me know if there is any other mistakes

**Comment by V-G-spec** [comment]
Thanks. There are still some tests that your code is failing on. Kindly look into those once

**Comment by artykov1511** [comment]
Hey @V-G-spec, I've fixed the lint error. Other errors seem to be caused not by my code. I guess everything is correct with my code. Best regards.

**Comment by V-G-spec** [comment]
Not sure if that is the case. Check the logs for `intelligent-tests-pr / run_tests_1`

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
