### PR TITLE
Add angle function to NumPy Frontend

### PR DESCRIPTION
**Pull request by mattcrewe**

### CODE REVIEW

**Comment by mattcrewe** [comment]
Close #12541

**Comment by MuhammadSaeedBatikh** [comment]
Hi @mattcrewe, thanks for the PR. 
`np.angle` computes the angle of a complex input, so I am not entirely sure of reason behind the TODO you added. Could you please elaborate on this?  
Otherwise, lgtm.

**Comment by mattcrewe** [comment]
Hi @MuhammadSaeedBatikh.
While the angle function is intended to take complex numbers as input the `np.angle` function will accept integer and float numbers as input; the other backends also mirror this behaviour. I am currently not testing for cases outside complex numbers as the current frontend implementation is only suitable to handle complex inputs. I left it at this point as it matches the current solutions for the other backends.

**Comment by MuhammadSaeedBatikh** [comment]
Makes sense. 
But no need to worry about that as these dtype conversions (if supported) are handled by the backend functions anyway. I', gonna remove the comments/TODOs and merge the PR. Thanks.

**Comment by aryanxk02** [comment]
Hello @mattcrewe and @MuhammadSaeedBatikh, I happened to spend some time working on this function because it was not marked 'completed' here: https://github.com/unifyai/ivy/issues/1525. Later while going through the codebase, I realised that the code for angle() has already been pushed. Please do the needful. Thank you.

**Pull request merged**
