### PR TITLE
add lognormal to numpy frontend

### LINKED ISSUE #14586: lognormal

### PR DESCRIPTION
**Pull request by ratulMahjabin**
Close #14586

### CODE REVIEW

**Comment by ratulMahjabin** [comment]
Hello @zhumakhan, 
can you please review the code and provide suggestions if needed.

note: I created test for `lognormal` and run locally. It passed the test successfully. I added ss for the reference
image
[venv]
image [docker]

**Comment by zhumakhan** [comment]
Hi, thanks a lot for you PR!
Please fix lint issues mentioned above. Rest seems good to me!

**Comment by ratulMahjabin** [comment]
> 



> Hi, thanks a lot for you PR! Please fix lint issues mentioned above. Rest seems good to me!

@zhumakhan can you please tell me how to solve it? or any reference regarding this?

**Comment by ratulMahjabin** [comment]
@zhumakhan when I run `pre-commit run -all-files` it shows that black, autoflake, flake8,pydocstyle passed but when I push commit in the remote `black`  `flake8` fails.  I don't think it's an issue from my end. can you please close the PR?

**Comment by zhumakhan** [comment]
Hi, there are too many failing tests, in order to accept this PR they should be passing. Also please do not modify files that are not related to the issue your solving. Could you please undo your changes on those files?

**Pull request closed without merging**
