### PR TITLE
Numpy Mean Instance

### PR DESCRIPTION
**Pull request by Hassan-Ik**

### CODE REVIEW

**Comment by CerberusLatrans** [comment]
Hi @Hassan-Ik, thanks for the PR. Is this a todo list task? If so, can you follow the instructions here (https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues) to properly link the corresponding issue? Thanks!

**Comment by Hassan-Ik** [comment]
Close Mean #6268

**Comment by CerberusLatrans** [comment]
Thanks for linking it here. On the original to-do list, can you comment "- [ ] #Issue_number" as in the contributing guide so that it can correctly reserve this task for you?

**Comment by CerberusLatrans** [comment]
@Hassan-Ik can you fix the test so that it passes and has correct dimension arguments passed in? One of the errors is "Dimension out of range (expected to be in range of [-1, 0], but got 1)". Let me know if you have any questions. Thanks!

**Comment by Hassan-Ik** [comment]
> Thanks for linking it here. On the original to-do list, can you comment "- [ ] #Issue_number" as in the contributing guide so that it can correctly reserve this task for you?

I have already did it.

**Comment by CerberusLatrans** [comment]
Thanks for fixing the attribute testing error. Have you tried debugging the float assertion error? Let me know.

I saw that you commented on the original to-do list, but please double check that it is in that exact format. If it is, then the comment should get automatically deleted by the bot. Thanks!

**Comment by CerberusLatrans** [comment]
You would think that haha! However, when passed through functional ivy or the backends sometimes the dtypes can get changed for whatever reason. I think similar things are happening on some other tests, even ones that I am trying to debug now. When we find a general fix for this it will probably pass, so I think this is fine and will merge it. Thank you for the contribution @Hassan-Ik !

**Pull request merged**
