### PR TITLE
Added associative scan JAX Frontend Control Flow #17442 

### LINKED ISSUE #17442: associative_scan

### PR DESCRIPTION
**Pull request by Panderio**
Close #17442

### CODE REVIEW

**Comment by JPGoodale** [comment]
Hi @Panderio, there is an ivy implementation of associative scan here: https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/experimental/manipulation.py#L1958. Please use this in your frontend implementation. Thank you :)

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
