### PR TITLE
Fixes typo error

### PR DESCRIPTION
**Pull request by Sarvesh-Kesharwani**
chrome_5rHC0tiVbf
https://lets-unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html

it think correct version should be " it would not be possible"

### CODE REVIEW

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @Sarvesh-Kesharwani 
Thanks for the PR🤗

Spotting errors in documentation is a good things and thanks for taking the initiative😊
However I saw that you have opened several PRs that might be related to this issue which makes it spammy to the team as it is an issue to be reviewed once🙂
Would you add all those changes to this one PR so it can make sense to be reviewed.

Thanks and happy coding🤞

**Comment by Sarvesh-Kesharwani** [comment]
> Hey @Sarvesh-Kesharwani Thanks for the PR🤗
> 
> Spotting errors in documentation is a good things and thanks for taking the initiative😊 However I saw that you have opened several PRs that might be related to this issue which makes it spammy to the team as it is an issue to be reviewed once🙂 Would you add all those changes to this one PR so it can make sense to be reviewed.
> 
> Thanks and happy coding🤞

Hello @hirwa-nshuti,
My goal was to maintain the distinctness of independent modifications by submitting separate PRs. However, if you believe it would be more appropriate to consolidate them, kindly let me know.

**Comment by hirwa-nshuti** [comment]
> > Hey @Sarvesh-Kesharwani Thanks for the PR🤗
> > Spotting errors in documentation is a good things and thanks for taking the initiative😊 However I saw that you have opened several PRs that might be related to this issue which makes it spammy to the team as it is an issue to be reviewed once🙂 Would you add all those changes to this one PR so it can make sense to be reviewed.
> > Thanks and happy coding🤞
> 
> Hello @hirwa-nshuti, My goal was to maintain the distinctness of independent modifications by submitting separate PRs. However, if you believe it would be more appropriate to consolidate them, kindly let me know.

Yeah I understand that but it can be reviewed under documentation fix up no need to open multiple PRs it can be reviewed by one person

**Comment by ZiadAmerr** [comment]
@hirwa-nshuti Should we merge this PR or close it and combine all edits to a single PR?

**Comment by hirwa-nshuti** [comment]
We can merge for now and keep it in mind for the future

**Comment by ZiadAmerr** [comment]
Okay, thanks @Sarvesh-Kesharwani for your contribution :)

**Pull request merged**
