### PR TITLE
Docs Glossary

### PR DESCRIPTION
**Pull request by jkeane508**
Creating a Glossary for Ivy Docs using sphinx glossary directive

### CODE REVIEW

**Comment by jkeane508** [comment]
Hi,

Currently cannot get the Glossary directive to work perhaps you could weigh in?

Thanks!

**Review by VedPatwardhan — CHANGES_REQUESTED** [review]
Hii @jkeane508, you just need to add the path to this file at the end of the `index_append.rst` file, then it would be visible in the table of contents. Thanks 🙂

**Comment by jkeane508** [comment]
Thanks! @VedPatwardhan 

I was wondering if you could figure out why the glossary directive wasn't being processed? It just ignores it when viewing it on GitHub.

**Review by VedPatwardhan — COMMENTED** [review]
But the PR hasn't been merged yet so I don't think we can know if the glossary directive works with GitHub or not. Let's see if it works after merging, and if there's an issue we'd work together on fixing it if that's okay?
Thanks 🙂

**Comment by jkeane508** [comment]
@VedPatwardhan,

Sounds good!
 
I'll get @djl11 to skim over before pushing to master.

**Review by djl11 — APPROVED** [review]
looks great! Thanks James :)

**Pull request merged**
