### PR TITLE
sum #6246

### PR DESCRIPTION
**Pull request by EvanMarie**

### CODE REVIEW

**Comment by ZoeCD** [comment]
Hi! Could you please comment on the PR, the issues related to the functions you implemented? That will help us link them to the PR and automatically close them once the PR is merged. Thanks!

**Comment by EvanMarie** [comment]
Sure! To my knowledge, the only issues I had here were caused by the conflicts my Max M1 processor had with the Ivy test functions, and I was unable to run them locally. If I remember correctly I had a small formatting issue in my test code that was very quick and easy to fix. Again, if I had been able to get my processor to work with the local tests, I would have done so. But I had already spent a great deal of time on this project due to a function I initially chose to implement that had already been implemented 9 weeks prior but had had no documentation to that effect. I did not find that out until I had already implemented and committed my version, which ended up being a duplicate. And so I had to choose a second function and figured I would implement this one and hope I didn't have any issues when committing, rather than wrangle with my processor and the testing. Unfortunately, I had missed that one issue.

**Comment by EvanMarie** [comment]
Is there a way I can get more information about what is failing?

**Comment by ZoeCD** [comment]
Hi! I'm sorry to hear you duplicated a function :( You can see the errors and failures in the "details" section of the CI tests. According to the logs, the test function raises an error. I noticed you didn't add any of the data generation decorators. That should fix it! Other than that, your PR looks good to me. Let me know if you have any questions 🙂

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
