### PR TITLE
Paddle rfft2

### PR DESCRIPTION
**Pull request by catplotlib**
solves #22002

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Pchatain** [comment]
Hi, it looks like this is marked as a draft. Nice job getting the PR connected with the TODO list issue properly! Let me know when you want me to look at it again but looks like good progress so far.

**Comment by catplotlib** [comment]
Hi Peter! Thanks for the feedback. I've made sure everything's polished up. Feel free to take another look when you have a moment. Appreciate your guidance! 😊

**Comment by Pchatain** [comment]
Hi @catplotlib , apologies for the delay. The code as written looks correct, based on pytorch implementation at https://pytorch.org/docs/stable/generated/torch.fft.rfft2.html. However, several tests fail when I run locally, outlined below.
```
====================================== short test summary info =======================================
FAILED test_fft.py::test_paddle_rfft2[cpu-numpy-False-False] - ivy.utils.exceptions.IvyBackendException: numpy: rfftn: 'NoneType' object is not iterable
FAILED test_fft.py::test_paddle_rfft2[cpu-jax-False-False] - ivy.utils.exceptions.IvyBackendException: jax: rfftn: 'NoneType' object is not iterable
FAILED test_fft.py::test_paddle_rfft2[cpu-tensorflow-False-False] - ivy.utils.exceptions.IvyBackendException: tensorflow: rfftn: `x` and `y` must have the same dtype...
FAILED test_fft.py::test_paddle_rfft2[cpu-torch-False-False] - ivy.utils.exceptions.IvyBackendException: torch: rfftn: 'NoneType' object is not iterable
FAILED test_fft.py::test_paddle_rfft2[cpu-paddle-False-False] - ivy.utils.exceptions.IvyValueError: paddle: rfftn: Invaid FFT argument s({}), it should be a sequ...
================================== 5 failed, 60 warnings in 55.89s ===
```

Also linking in https://github.com/unifyai/ivy/issues/22169 #22169 because this was opened and seems to be a duplicate issue.

Some minor style: Pre-commit says a newline should be added at the end of the file. And fix the spacing in the testing function.

**Comment by Pchatain** [comment]
Furthermore there's a chance that you get complex128 dtype related errors due to https://github.com/unifyai/ivy/issues/21100. Try to skip these dtype tests for now?

**Comment by catplotlib** [comment]
Thanks! Seems to be an issue with how I’m handling types, could you tell me how to run paddle frontend tests locally please?

**Comment by Pchatain** [comment]
> Thanks! Seems to be an issue with how I’m handling types, could you tell me how to run paddle frontend tests locally please?

Definitely! Follow the setting up guide here - https://unify.ai/docs/ivy/compiler/setting_up.html. Personally I simply call pytest on the specific function I want to test.

**Comment by Ishticode** [comment]
Calling this due to lack of activity. Normally ivy-seed would label it as stale and auto close but seems to have not detected. Anyways please feel free to reopen if you have any updates @catplotlib

**Pull request closed without merging**
