### PR TITLE
Updated Reformat Activation #754

### PR DESCRIPTION
**Pull request by DrashtySoni**
I have added  #1225, #1267, #784, #1574, #1173, #1467, #1741 under #754 issue.

### CODE REVIEW

**Comment by sherry30** [comment]
Hi,

I'm not sure why you added examples to all the functions in the activation submodule.
You're only supposed to do 1, you have to get assigned that function first in the issue.
Were you assigned any function? if yes can you link the issue number here

Thanks

**Comment by DrashtySoni** [comment]
> Hi,
> 
> I'm not sure why you added examples to all the functions in the activation submodule. You're only supposed to do 1, you have to get assigned that function first in the issue. Were you assigned any particular function? if yes can you link the issue number here?
> 
> Thanks

So, basically, I was told the below lines in the task:
(i) Check out the issues on the Ivy repo, filtering to only search for issues with both the
labels “Function Reformatting” and “ToDo”, returning [these](https://github.com/unifyai/ivy/issues?q=is%3Aopen+is%3Aissue+label%3AToDo+label%3A%22Function+Reformatting%22). Each of these issues is a
ToDo list refers to this function reformatting task.
(ii) Pick a function to work on from one of these ToDo lists which are not already ticked, have
not got an issue opened next to the checkbox, and are not present in the comments.

So I was asked to pick any issue under "Function Reformatting" that satisfies point (ii) is the reason I picked up [Reformat Activation](https://github.com/unifyai/ivy/issues/754) task since it satisfies point (ii).

**Comment by sherry30** [comment]
I think you're a little confused about the task.
`Activation` is a submodule which contains multiple functions like, `tanh`, `gelu` etc. So you were supposed to pick 1 function from these. however it seems like all of the functions under activation submodule issue are already assigned to someone, you can tell that since they are all blue and have an issue linking to them.

**Comment by DrashtySoni** [comment]
Then, what to do about the issue I committed for?

**Comment by sherry30** [comment]
Those issues are created by other applicants for the function they were assigned, you're supposed to do the same, create an issue for a function which has not been selected yet. then you're supposed to comment on the main submodule issue with the issue number of your newly created issue then it will be automatically assigned to you.

I'll close this PR, you can create a new one when a function gets assigned to you

**Comment by DrashtySoni** [comment]
So, what should I do?
Whatever commit I did isn't considered?
Is that PR to master ivy repo isn't considered under me?

How to ask for the issue to be assigned to me?

**Pull request closed without merging**
