### PR TITLE
frontends.tf.raw_ops: add support for Conv3D

### LINKED ISSUE #9466: Conv3D

### PR DESCRIPTION
**Pull request by hmahmood24**
Close #9466

### CODE REVIEW

**Review by kurshakuz — CHANGES_REQUESTED** [review]
Hey! Can you please resolve the merge conflict and show me the result of your local test run?

**Comment by hmahmood24** [comment]
Resolved @kurshakuz.
Sure. Here you go:

(1/2)
image

(2/2)
image

**Review by kurshakuz — APPROVED** [review]
LGTM! Can you please resolve the conflict and then I will merge your PR.

**Comment by hmahmood24** [comment]
Conflicts resolved! 🙂

**Pull request merged**
