### PR TITLE
updateProd

### PR DESCRIPTION
**Pull request by patcasrares**

### CODE REVIEW

**Comment by modanesh** [comment]
Hi,

Thanks for your contribution. There are a few things that need to be modified:

1- In `torch.statistical` and `ivy.statistical`, `keepdims: bool = False,` needs to be changed to `keepdims: Optional[bool] = False,`. Feel free to read more about this [here](https://lets-unify.ai/ivy/deep_dive/8_inplace_updates.html). Also, please consider updating other relative backend functions in mxnet, tensorflow, numpy, and jax.
2- Please remove the `prod()`'s docstring from `torch.statistical` since we have that docstring in `ivy.statistical`. 
3- In the PR, there're changes applied to the `var()` in `torch.statistical`. Were they necessary?

Don't hesitate to ask any further questions if you have any,. I'd be happy to help.

**Comment by patcasrares** [comment]
1. done
2. done
3. it seems there was some changes on the master branch between the time I cloned the repo and the time I made the PR

**Comment by modanesh** [comment]
In the change log I see that you've made changes to the `min()` function in `ivy/functional/ivy/statistical.py` and `var()` function in `ivy/functional/backends/torch/statistical.py` which are not required for this task. Please revert those changes since they are to be considered for another PR. You should focus on the `prod()` function instead. In addition, please consider updating other relative backend functions in mxnet, tensorflow, numpy, and jax with correct function arguments orders and type hints.

**Comment by patcasrares** [comment]
I updated the arguments

**Comment by patcasrares** [comment]
I changed dtype and the order

**Pull request merged**
