### PR TITLE
matmul frontend in pytorch

### PR DESCRIPTION
**Pull request by jiisa-k**
#7513

### CODE REVIEW

**Comment by jiisa-k** [comment]
@RashulChutani please look into my PR and let me know if I need to make any changes!

**Comment by RashulChutani** [comment]
Hi @jiisa-k Sure, I will let you know ASAP. Thanks.

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @jiisa-k Actually you need implement the frontend method in terms of the ivy methods and not using the torch frontend methods. Please refer to the Deep dive in Ivy Docs for details. Thanks.

**Comment by jiisa-k** [comment]
Hi @RashulChutani, the issue states that if the Linear Algebra function to be implemented has identical behaviour to another PyTorch function, then I should keep an alias in the linalg.py file rather than create a duplicate implementation. Since pytorch.linalg.matmul is an alias of pytorch.matmul, I have used the torch frontend method. Let me know if I should implement the frontend using ivy methods regardless. Thanks!

**Comment by RashulChutani** [comment]
Sure. That sounds good. I will go in some more detail and let you know. Thanks for pointing it out.

**Comment by RashulChutani** [comment]
Hi @jiisa-k I will check soon and get back to you. Looks good to me briefly.

**Comment by jiisa-k** [comment]
Hello @RashulChutani, any updates?

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @jiisa-k, Looks good to me. Can you please resolve the merge conflicts? Thanks

**Comment by jiisa-k** [comment]
@RashulChutani the conflicts have been resolved. Thanks!

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @jiisa-k Can you still add the test for the matmul function, so that I can confirm that it works correctly? Also, can you resolve the lint errors? Thanks.

**Pull request closed without merging**
