### PR TITLE
 frontends.torch.linalg: add support for vander

### PR DESCRIPTION
**Pull request by yw14218**

### CODE REVIEW

**Comment by yw14218** [comment]
Ref #10389

**Comment by agniiyer** [comment]
Hey the tests are still not passing. Can you take another look? :)

**Comment by yw14218** [comment]
screenshot

Hello, upon investigation it seems that the [torch.linalg.vander](https://pytorch.org/docs/1.12/generated/torch.linalg.vander.html?highlight=vander) function is only available after PyTorch 1.12, and therefore a key error would occur for now as the Ivy image was staged for PyTorch 1.10.

Also, I noted that in my implementation of the function, the last line should change from 
``
return ivy.stack([input ** i for i in range(column_number)], dim=len(input_shape))
``
to
``
return ivy.stack([input ** i for i in range(column_number)], axis=len(input_shape))
``

I think I will not submit a new PR as the tests are going to fail anyways due to aforementioned problems. Please advice me the next step if possible? Do I need to pick another function to implement? Thanks! @agniiyer

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
