### PR TITLE
added jax.random.cauchy to jax frontend

### LINKED ISSUE #14407: cauchy

### PR DESCRIPTION
**Pull request by hnehme99**
Close #14407

### CODE REVIEW

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hiya, thank you for contributing 😊

However, there are some bugs in your code that still need to be resolved before I can merge this. Please check the runtests for more details.

**Comment by hnehme99** [comment]
> Hiya, thank you for contributing 😊
> 
> However, there are some bugs in your code that still need to be resolved before I can merge this. Please check the runtests for more details.

Hello! After running tests again, I realized that I made a mistake and did not recognize that cauchy has no backend implementation. Any idea on how I should proceed?
Thanks in advance.

**Comment by Ookamice** [comment]
HIya,
I recommend reading this section of the [contributer's guide](https://lets-unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) where it details what you should do if an `ivy.<func_name>' is missing.

Let me know if you need any more help 😄

**Review by Ookamice — CHANGES_REQUESTED** [review]
Hiya, please don't import the math module in the frontend files. I think you're only using it for the constant pi, in which case please refer here about [ivy.pi](https://lets-unify.ai/docs/ivy/docs/functional/ivy/ivy.functional.ivy.constants.html#ivy.pil)

I think because of this some tests aren't being run properly so I'll give your PR a closer look after this has been fixed 😊

**Review by Ookamice — CHANGES_REQUESTED** [review]
Thanks for the prompt changes made but as I have said, please do not use the math library and rather look at ivy's implementation of pi. Thank you 👋

**Comment by hnehme99** [comment]
Hello! 

I fixed that issue but tests are failing for torch and paddle backends.

`ivy.utils.exceptions.IvyException: Cannot convert to ivy dtype. uint32 is not supported by Paddle backend.`

`ivy.utils.exceptions.IvyBackendException: torch: _handle_nestable_dtype_info_wrapper: torch: as_native_dtype: Cannot convert to PyTorch dtype. uint32 is not supported by PyTorch.`

**Comment by Ookamice** [comment]
> Hello!
> 
> I fixed that issue but tests are failing for torch and paddle backends.
> 
> `ivy.utils.exceptions.IvyException: Cannot convert to ivy dtype. uint32 is not supported by Paddle backend.`
> 
> `ivy.utils.exceptions.IvyBackendException: torch: _handle_nestable_dtype_info_wrapper: torch: as_native_dtype: Cannot convert to PyTorch dtype. uint32 is not supported by PyTorch.`

Let me check with my colleagues and I'll get back to you. I believe that the torch will always fail for jax.random functions and is being fixed by an upcoming refactor. This might be an edgecase with paddlepaddle's tests so I'll get this double checked for you. 😊

**Comment by Ookamice** [comment]
It looks like jax.random.gamma has the same issue and that was approved so I will merge your's too.

Thank you for your contirbution 😊

**Pull request merged**
