### PR TITLE
unique_counts #1748 Function Reformatting

### PR DESCRIPTION
**Pull request by CSheets53**
Reformatted set.unique_counts per #794 and #1748

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

You don't have to add `out` argument to `unique_counts` since it returns multiple arrays.
So you can remove that from the container and array function as well.
One more thing, you should test static_method like, `y = ivy.static_unique_counts(x)`

Thanks

**Comment by CSheets53** [comment]
> Hi,
> 
> You don't have to add `out` argument to `unique_counts` since it returns multiple arrays. So you can remove that from the container and array function as well. One more thing, you should test static_method like, `y = ivy.static_unique_counts(x)`
> 
> Thanks

Ok, thank you! I interpreted the docs to mean `out` goes on every function - would I only use `out` when a method returns a single array then?

**Comment by sherry30** [comment]
Yes, that's correct. Since `unique_counts` returns 2 arrays, we wont be using `out` argument for it.

**Review by sherry30 — APPROVED** [review]
Looks perfect, 
Thanks for the contribution 😃

**Pull request merged**
