### PR TITLE
Bring round function to array api standard

### PR DESCRIPTION
**Pull request by Neel-Renavikar**
PR for issue #226

### CODE REVIEW

**Review by djl11 — CHANGES_REQUESTED** [review]
Please uncomment the det method in the correct file in ivy_tests/array_api_methods_to_test (by removing the #), and then we can see if the tests are passsing :)

**Comment by Neel-Renavikar** [comment]
@djl11 , @1Doomdie1 the failing test cases have same exceptions like:
"AssertionError: remainder is not defined in ivy"
"AssertionError: not_equal is not defined in ivy"

Can you help me with issues? I think that the round method is dependent on the remainder and not_equal method which are not yet implemented. Any pointers would be helpful.

**Comment by Neel-Renavikar** [comment]
@djl11 requesting a review primarily on my last comment as I think the methods are failing because the function is dependent on other functions that have not been implemented yet. Please refer to the comment above.

**Review by djl11 — CHANGES_REQUESTED** [review]
Hi @Neel-Renavikar, apologies for the late reply. Could you please run `merge_with_upstream.sh` locally and then fix any resulting conflicts manually? Following that, you can leave the tests out, but please add a comment `# depends on remainder, not_equal`, similar to as is done in this [line](https://github.com/unifyai/ivy/blob/f4b78d354c7eef469600ad3f9bb69e4400a86aa6/ivy_tests/array_api_methods_to_test/elementwise_functions.txt#L16). I'll then get it merged. Thanks!

**Comment by Neel-Renavikar** [comment]
@djl11 I have rebased the branch and squashed all the commits. I think the PR is ready to be merged with your approval.

**Review by djl11 — APPROVED** [review]
lgtm!

**Comment by djl11** [comment]
Thanks!

**Pull request merged**
