### PR TITLE
feat(paddle frontend): add index_sample function

### LINKED ISSUE #26495: index_sample

### PR DESCRIPTION
**Pull request by ksbharaj**
# PR Description

Added Index_sample for Paddle

## Related Issue

Close #26495

## Checklist

- [X] Did you add a function?
- [X] Did you add the tests?
- [X] Did you run your tests and are your tests passing?
- [X] Did pre-commit not fail on any check?
- [X] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ksbharaj** [comment]
Hi @Sam-Armstrong and @KareemMAX. I raised this PR to address the requested change. Kindly let me know if you require any additional info to help merge this to the main branch. Thank you

**Comment by Sam-Armstrong** [comment]
@ksbharaj please could you add the corresponding frontend test? 
https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#ivy-frontend-tests

**Comment by ksbharaj** [comment]
Hi @Sam-Armstrong. I believe this is already there from a previous PR. Please check:

ivy/ivy_tests/test_ivy/test_frontends/test_paddle
/test_search.py

and the function test_paddle_index_sample()

Let me know if that's the correct test, and if anything else is needed.

**Comment by ksbharaj** [comment]
> Hi @Sam-Armstrong. I believe this is already there from a previous PR. Please check:
> 
> ivy/ivy_tests/test_ivy/test_frontends/test_paddle /test_search.py
> 
> and the function test_paddle_index_sample()
> 
> Let me know if that's the correct test, and if anything else is needed.

Hi @Sam-Armstrong. Have you had a chance to review this? Kindly let me know if you need any more information from me

**Comment by Sam-Armstrong** [comment]
@ksbharaj we also need a test in ivy/ivy_tests/test_ivy/test_frontends/test_paddle
/test_tensor.py, as you've implemented a tensor method here.

**Comment by ksbharaj** [comment]
Hey @Sam-Armstrong 
I've added the test to test_paddle/test_tensor/test_tensor.py as requested. Kindly let me know if there's anything else required.

**Comment by ksbharaj** [comment]
Hi @Sam-Armstrong. I added the tests, but I think this still needs some rectifications. I think I am facing some issues getting the tests to work locally, so I can't debug effectively.
If you have the chance, please review my code and kindly let me know how I can improve it (I'm eager to learn and improve here)

**Comment by ksbharaj** [comment]
Hi @Sam-Armstrong. Please do let me know. I would like to continue contributing but just need some help on how to do it correctly. Thank you

**Comment by Sam-Armstrong** [comment]
Hi @ksbharaj, sorry for the slow reply. I'm not exactly sure what's going wrong with the test unfortunately, the other tests in the file seem to be failing for me also. I'll continue looking into it, but maybe for the time being could you resolve the merge conflicts with main? Thanks!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Ishticode** [comment]
Closing this due to inactivity for over 6 months. Please feel free to reopen if you would like to continue working on this. Thank you :)

**Pull request closed without merging**
