### PR TITLE
Var() - issue number 14969 ( updating numpy frontend from To Do List for OpenSource Challenge)

### PR DESCRIPTION
**Pull request by Sj0605-DataSci**
Hi there, here i have updated two code files in whch firstly : 
1. I have shorten the var() function 
2.  have created test_numpy_var for the tesing of the frontend

### CODE REVIEW

**Comment by Sj0605-DataSci** [comment]
Screenshot 2023-05-08 at 11 58 52 PM
See locally i m not getting any error, please merge it such that i will be able to pass open source challenge stage 1, I legit wanna contribute and be a part of Ivy

**Comment by Sj0605-DataSci** [comment]
Hey ivy team please add ToDo list label also

**Comment by Sj0605-DataSci** [comment]
Hey Nassim if you are seeing this comment, please take AnnaTz in loop also this is regarding ToDO list and Numpy frontend for OS Challenge to get into Ivy as ML Engineer intern

**Comment by Sj0605-DataSci** [comment]
@AnnaTz this in reference to issue number 14969, please review this

**Review by AnnaTz — APPROVED** [review]
Looks good to me!

**Comment by Sj0605-DataSci** [comment]
Hey Anna, so now should I gave this link right for OS challenge completion?

**Comment by AnnaTz** [comment]
> and do add ( ToDo list labels whatever might be necessary such that its applicable for open source challenge

We don't add a ToDo label to PRs. I linked the PR to the issue you created (you should do this on your own from now on) and that issue is a subtask of the numpy shortening ToDo list.

**Pull request merged**
