### PR TITLE
Add paddle.tensor.tensor.Tensor.squeeze function

### LINKED ISSUE #22451: squeeze
To-do list: https://github.com/unifyai/ivy/issues/15115

### PR DESCRIPTION
**Pull request by AliTarekk**
Add the paddle.Tensor instance method squeeze for the paddle frontend

Close #22451

### CODE REVIEW

**Comment by AliTarekk** [comment]
close #22451

**Comment by AliTarekk** [comment]
@Sam-Armstrong kindly review my PR

**Review by Sam-Armstrong — CHANGES_REQUESTED** [review]
@AliTarekk please could you make the frontend implementation and test part of the same PR? You can just update this PR to add the test. Thanks!

**Comment by AliTarekk** [comment]
> @AliTarekk please could you make the frontend implementation and test part of the same PR? You can just update this PR to add the test. Thanks!

@Sam-Armstrong I merged the branch with the test part to this branch. Let me know if it needs further modification. Thank you!

**Review by Sam-Armstrong — APPROVED** [review]
I've made a couple of minor changes, but otherwise looks good to me. Thanks for the contribution @AliTarekk!

**Comment by Sam-Armstrong** [comment]
ivy-gardener

**Comment by Sam-Armstrong** [comment]
@AliTarekk Oh wait sorry, the issue you've linked to this PR was opened and is being worked on by someone else. For that reason I'll have to close this PR. Feel free to open your own issue from one of our todo list items!

**Pull request closed without merging**
