### PR TITLE
Reformatted copy_array #1708

### PR DESCRIPTION
**Pull request by 11Nick26**
Reformat general #791

Not sure if backend formatting was implemented correctly but i can revert them back if they are incorrect so please let me know.

Thank you!

### CODE REVIEW

**Comment by simonetgordon** [comment]
Hi Nick,

Thanks for the contribution!

This looks good for the ivy function. Did you intend to update the backends also? Only 1 file has been altered.

Simone

**Comment by 11Nick26** [comment]
I was going to update the backend functions but i realized i don't think i have to. But if that is necessary just let me know and I'll make the proper changes!

**Review by chie2727 — CHANGES_REQUESTED** [review]
Hi @11Nick26 , please include the following additional examples:

- [x] 1. A `With :code:`ivy.Array` input:` example that makes use of the `out` parameter.

- [x] 2. A Container Static Method Example

Have a look at the docstring guide for reference:
https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html

**Review by chie2727 — CHANGES_REQUESTED** [review]
Hi @11Nick26 ,

Thanks for making all the changes.
One last thing: please include an ivy.Container instance method example as there isn't an example for this yet.

**Comment by chie2727** [comment]
Hi @11Nick26 , thanks for all your patience. I removed some duplicated examples and native_array examples which were added by a previous contributor as those aren't required anymore.
Everything is looking good so I'll merge in your changes now.

**Review by chie2727 — APPROVED** [review]

**Pull request merged**
