### PR TITLE
matrix_exp

### PR DESCRIPTION
**Pull request by abhigya-sodani**

### CODE REVIEW

**Review by CheezBallzPi — CHANGES_REQUESTED** [review]
Your lint tests are not passing. Have a look at the logs.

**Comment by abhigya-sodani** [comment]
Fixed lint, and some testing issues, looks through the failures none seem to be due to matrix_exp. Let me know if something more is needed!

**Review by CheezBallzPi — CHANGES_REQUESTED** [review]
Check again, the tests for the backends are still not passing. You want to click the "Run Experimental Test" section when you are checking the failing tests to actually see what is breaking. LMK if you need any help finding the tests still.

**Comment by abhigya-sodani** [comment]
> Check again, the tests for the backends are still not passing. You want to click the "Run Experimental Test" section when you are checking the failing tests to actually see what is breaking. LMK if you need any help finding the tests still.

The errors seem to be in the test_matrix_rank (numpy, linalg) , test_linspace (torch, creation_functions), test_inv (tensorflow, linalg), and test_matrix_rank (tensorflow, linalg) 

I found these when looking at the "Run Array API tests" section. I am confused how these errors relate to the functionality that I worked on.

**Comment by CheezBallzPi** [comment]
You are looking at the non-experimental tests. I believe the ones that are failing are in the test-experimental-core-ivy suites. Here's a link to one: https://github.com/unifyai/ivy/actions/runs/3502702160/jobs/5867271540

**Comment by RickSanchezStoic** [comment]
Hi @abhigya-sodani are you still making changes ? If not I will have to go ahead and close this pr because of inactivity. Thanks!

**Pull request closed without merging**
