### PR TITLE
Update generating_index_arrays.py

### LINKED ISSUE #13040: tril_indices_from

### PR DESCRIPTION
**Pull request by billumillu**
Copied diag_indices( ) and  tril_indices( ) from [indexing_like_operations.py](https://github.com/billumillu/ivy/blob/master/ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py)
Added tril_indices_from( )
Also, modified tril_indices( )

Issue: resolve #13040

### CODE REVIEW

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey,

If you are just copying these over without making any changes, it might be worthwhile just importing the functions.

**Comment by billumillu** [comment]
Hey @jkeane508 

I actually believe those two functions should be in this file (generating_index_arrays.py) rather than in indexing_like_operations.py [based on [this](https://numpy.org/doc/stable/reference/arrays.indexing.html#)]

I'm not sure though, of course. I asked on Discord (backend settings). Maybe you could look into it, please?

And I also have a doubt about the tril_indices( ) function. It takes (n, k, m) as arguments, but returns (n, m, k). Is this okay?
This is in the indexing_like_operations.py file. I modified it in my file to (n, k, m)

Thanks for the review :)

**Comment by billumillu** [comment]
@jkeane508 Hey, man. I'm assuming you're super busy. Would be grateful if you could please quickly review my PR.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Review by hirwa-nshuti — CHANGES_REQUESTED** [review]
Hey @billumillu 

Thanks for the PR😊
Sorry for reviewing this late, would you add the unit tests of the above implemented functions🙂

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
