### PR TITLE
Added arrcos, arrcosh, arcsin, arcsinh to jax.numpy frontend namespace functions

### PR DESCRIPTION
**Pull request by Torus403**

### CODE REVIEW

**Comment by modanesh** [comment]
Thanks for your contribution. Could you link the issue this PR is trying to solve?

**Comment by Torus403** [comment]
> Thanks for your contribution. Could you link the issue this PR is trying to solve?

Hey, sure thing: 
https://github.com/unifyai/ivy/issues/4612
and the specific ones are these: 
- https://github.com/unifyai/ivy/issues/5248
- https://github.com/unifyai/ivy/issues/5249
- https://github.com/unifyai/ivy/issues/5250
- https://github.com/unifyai/ivy/issues/5251

**Comment by modanesh** [comment]
As the `test-frontend-jax` reports, all added functions fail with this error: `got an unexpected keyword argument 'x'`. Could you take a look at it?

**Comment by Torus403** [comment]
@modanesh Hey apologies for the back and forth, I think i have fixed it now. Any way to get the tests to rerun? Many thanks for all your help.

**Comment by modanesh** [comment]
No worries. Resolving conflicts should do the trick.

**Comment by Torus403** [comment]
Hey @modanesh just wanted to thank you for all your help!!! this was my first commit so hopefully it will go smoother next time. Thanks again :)

**Comment by modanesh** [comment]
No problem :) You did a good job for your first PR. Thanks for your contribution!

**Pull request merged**
