### PR TITLE
added relu_ activation function and test for PaddlePaddle frontend

### LINKED ISSUE #16343: relu_

### PR DESCRIPTION
**Pull request by sachelsout**
Close #16343

### CODE REVIEW

**Comment by sachelsout** [comment]
Hello @khushi-411 , could you please review my PR ?

**Review by khushi-411 — CHANGES_REQUESTED** [review]
Hey, @sachelsout! Thanks for the PR and ping. So far looks good to me. Could you please update the branch?
I see there's a failure that looks flaky to me—just wanted to make CI green before merging. Thanks!

**Comment by sachelsout** [comment]
Hi @khushi-411 , I updated the branch as you mentioned, but unknowingly a lot of test cases started failing. The test cases are passing locally.

**Comment by khushi-411** [comment]
Yeah, these are unrelatable. Could you please resolve the conflicts? Thanks Also, I'm sorry, I thought I responded you earlier.

**Comment by sachelsout** [comment]
> Yeah, these are unrelatable. Could you please resolve the conflicts? Thanks! Also, I'm sorry, I thought I responded you earlier.

No worries, I'll resolve the conflicts right away !! 😄

**Comment by sachelsout** [comment]
Hi @khushi-411 , during resolving the conflicts, I noticed someone who has implemented rrelu() function has written code for testing the function incorrectly. The person has just defined the function test_paddle_rrelu() but hasn't written anything in that code, which is creating errors. 

image

That's why I've removed his/her broken test code. I'll ping the person in his/her related issue/PR by commenting this.

**Comment by khushi-411** [comment]
Good catch, @sachelsout! 🎉 I see the test cases were incorrectly added in #16466. `rrelu` with paddle backend is already available here: https://github.com/unifyai/ivy/blob/37a63e8305f47e6355b14af04a106b24840d65b8/ivy/functional/frontends/paddle/nn/functional/activation.py#L138-L174. 

Rohan, if you are interested in further contributing, please add a test for rrelu in this PR or a new one, whichever way you are interested. Thanks!

**Review by khushi-411 — COMMENTED** [review]
Good catch, @sachelsout! 🎉 I see the test cases were incorrectly added in #16466. `rrelu` with paddle backend is already available here: https://github.com/unifyai/ivy/blob/37a63e8305f47e6355b14af04a106b24840d65b8/ivy/functional/frontends/paddle/nn/functional/activation.py#L138-L174. 

Rohan, if you are interested in further contributing, please add a test for rrelu in this PR or a new one, whichever way you are interested. Thanks!

**Comment by sachelsout** [comment]
> Good catch, @sachelsout! 🎉 I see the test cases were incorrectly added in #16466. `rrelu` with paddle backend is already available here:
> 
> https://github.com/unifyai/ivy/blob/37a63e8305f47e6355b14af04a106b24840d65b8/ivy/functional/frontends/paddle/nn/functional/activation.py#L138-L174
> 
> .
> Rohan, if you are interested in further contributing, please add a test for rrelu in this PR or a new one, whichever way you are interested. Thanks!

Hi @khushi-411 , I would love to work on resolving rrelu issue but @Adeola23 is going to raise a PR to resolve the issue, as seen from his latest comment on the issue.

image

**Comment by sachelsout** [comment]
Hi @khushi-411 , are there any changes remaining from my side ?

**Comment by khushi-411** [comment]
Hi, @sachelsout! Thanks for your patience! Overall looks good to me. Let's wait for #17184 to merge, update this PR, and land into the master branch.

I hope to land this PR today.

**Comment by sachelsout** [comment]
> Hi, @sachelsout! Thanks for your patience! Overall looks good to me. Let's wait for #17184 to merge, update this PR, and land into the master branch.
> 
> I hope to land this PR today.

Sounds good 😊

**Review by khushi-411 — APPROVED** [review]
LGTM! The failures are unrelated.
Thanks for the PR!

**Comment by sachelsout** [comment]
> LGTM! The failures are unrelated.
> Thanks for the PR!

Thank you @khushi-411 for reviewing and merging the PR 😊

**Pull request merged**
