### PR TITLE
Add Squeeze function to Tensorflow frontend

### PR DESCRIPTION
**Pull request by hamehrabi**

### CODE REVIEW

**Comment by hamehrabi** [comment]
#7162

**Comment by hamehrabi** [comment]
Hi @V-G-spec,

I hope you're doing well.

The tests based on codespace had been passed successfully before PR, so I am just wondering what the issue could be. I'd appreciate it if you guided me in this regard.

Thanks🙂

**Comment by hamehrabi** [comment]
Close #7162

**Comment by hamehrabi** [comment]
Hey @V-G-spec,

Thank you very much for the response and guidance 🙂. I just need help with regard to the function. It passed the test using codespace+vscode, but here shows the errors. Does it mean my fork has a problem? I updated my repo frequently. I just wondering what might cause this conflict here. 
Thanks 
Hamed

**Comment by V-G-spec** [comment]
Based on my understanding, it's possible that the error is due to some other file (as is the case with lint error). Can you go through the logs once and confirm this? Would be great if you could also attach a screenshot of tests passing in your local machine.
Thanks!

**Comment by hamehrabi** [comment]
> Based on my understanding, it's possible that the error is due to some other file (as is the case with lint error). Can you go through the logs once and confirm this? Would be great if you could also attach a screenshot of tests passing in your local machine. Thanks!

Hey @V-G-spec,

Thanks for the reply. Agree with you; I think it might be due to other files' problems. I would appreciate it if you implement my function with your system to check whether it works properly with your local system. I have tested it multiple times, and it successfully passed all the tests.

hamed

**Comment by V-G-spec** [comment]
I see. Can you remove your changes from misc.xml file? Rest looks good

**Comment by hamehrabi** [comment]
> I see. Can you remove your changes from misc.xml file? Rest looks good

Dear @V-G-spec,

I have changed the misc.xml codes. In fact, I have copied the codes from the ivy master branch and replaced them with that mine. Unfortunately, again it couldn't pass the tests here. May I ask you to run my codes with your system and see whether it works? Very appreciate it. 

Best,

**Comment by V-G-spec** [comment]
@hamehrabi, I did not want you to do that for the test cases to pass but to adhere to the contributing guidelines. There should not be changes in other files. Right now, there still are. 
Secondly, please refer to [this link](https://lets-unify.ai/ivy/deep_dive/continuous_integration.html) for passing tests to confirm from the logs if your functions are producing the errors. 
Once both of these are addressed, I will accept the pull request.

Thanks!

**Comment by hamehrabi** [comment]
> 
Hi @V-G-spec 
I have checked the errors in the frontend test and found that some merged functions cannot pass the tests in the repo, and due to their failure in tests, my function also cannot pass the tests.
For example, `"test_tensorflow_eigh"` and `"test_tensorflow_normalize"` are the name of a few. Based on the issues with these functions, what's your suggestion? 

Thanks



or

**Comment by V-G-spec** [comment]
Thanks for doing that. I also found something similar, just wanted you to check as well. There is no problem with your function and it is therefore acceptable to merge. I am sorry for reiterating this but you are not supposed to have changes in more files than necessary- the misc.xml does not have a newline in the end in your pull request. I am only waiting for that to merge your commits

**Comment by hamehrabi** [comment]
> Thanks for doing that. I also found something similar, just wanted you to check as well. There is no problem with your function and it is therefore acceptable to merge. I am sorry for reiterating this but you are not supposed to have changes in more files than necessary- the misc.xml does not have a newline in the end in your pull request. I am only waiting for that to merge your commits

Dear @V-G-spec,
Thank you for your reply. You're right, I deleted the space line at the end of misc.xml. Please let me know if I need to do any further changes. Thanks for the merging in advance. 😊

**Comment by hamehrabi** [comment]
> The number of files changed is still 3. Your IDE seems to be removing the newline. Try to make the changes using some other editor

@V-G-spec 
Would really appreciate it if you could tell me more about the problem. You said that three files were changed. Could you tell me how many files need to be changed and what they are? Do you mean only the code and test files need to be changed not anymore? To do this, do I remove my changes from the misc.xml file? I would appreciate it if you could explain a little more.

**Comment by V-G-spec** [comment]
Yes, you may close this request, create a new fork and PR, and choose me as the reviewer.
Thanks

**Pull request closed without merging**
