### PR TITLE
feat: implement paddle crop

### LINKED ISSUE #21345: crop

### PR DESCRIPTION
**Pull request by Praneet9**
Close #21345

### CODE REVIEW

**Comment by Praneet9** [comment]
@Ishticode I have made the changes but the tests are failing for some other functions unrelated to my commit. Is there a glitch or is there something wrong with my implementation? Can you help me close this?

**Review by Ishticode — CHANGES_REQUESTED** [review]
Although there are other failurees, `test_paddle_crop` is also failing with the error `AssertionError: returned shape = (3, 0, 0), ground-truth returned shape = (3, 0, 3)`.
Please check the error logs [here](https://github.com/unifyai/ivy/actions/runs/6058067696/job/16439944879?pr=21588) under `combined test results`.
Please could you try to fix the issue and rerequest a review. 🙂️

**Comment by Praneet9** [comment]
@Ishticode This PR looks ready for review now. It still fails one test on `test_exponents_and_logarithms` which seems to be unrelated to my commit.

**Comment by Sarvesh-Kesharwani** [comment]
Hi @Praneet9,
Please update your branch with latest changes from upstream and then test your implementation again, and let me know.
image

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
