### PR TITLE
log2 #1912

### PR DESCRIPTION
**Pull request by shashankgarg93**

### CODE REVIEW

**Comment by shashankgarg93** [comment]
@RashulChutani Hi Rachel, could you please review this PR for issue #1912 ? Thanks.

**Comment by shashankgarg93** [comment]
Changes:

Added/updated docstrings in log2(), +examples
Added ivy.Container static of ivy.log2()
Removed lambda in return
Thanks!

**Comment by RashulChutani** [comment]
> @RashulChutani Hi Rashul, could you please review this PR for issue #1912 ? Thanks.

Sure. I will do that ASAP.

**Comment by shashankgarg93** [comment]
> > @RashulChutani Hi Rashul, could you please review this PR for issue #1912 ? Thanks.
> 
> Sure. I will do that ASAP.

Thanks

**Comment by shashankgarg93** [comment]
> > @RashulChutani Hi Rashul, could you please review this PR for issue #1912 ? Thanks.
> 
> Sure. I will do that ASAP.

@RashulChutani Hi, can you help me with the PR review so I can quickly move forward with the interview process? 😄

**Comment by RashulChutani** [comment]
Hi, @shashankgarg93 Can you reformat the examples in the docstring such that they have the correct formatting? For ex. [0., 2.0,float('nan')] should be [0., 2.0, float('nan')]

**Comment by shashankgarg93** [comment]
> Hi, @shashankgarg93 Can you reformat the examples in the docstring such that they have the correct formatting? For ex. [0., 2.0,float('nan')] should be [0., 2.0, float('nan')]

Hi @RashulChutani, I edited it. Thanks :)

**Comment by RashulChutani** [comment]
Sure. I will have a look again ASAP. It may take some time as we have multiple PRs to review.

**Comment by shashankgarg93** [comment]
> Sure. I will have a look again ASAP. It may take some time as we have multiple PRs to review.

Okay :)

**Comment by shashankgarg93** [comment]
Hi, are the doctoring examples in correct format now?

**Comment by shashankgarg93** [comment]
Hi @RashulChutani, are the docstring examples in correct format now?

**Comment by shashankgarg93** [comment]
Hi @RashulChutani, please help with the PR

**Comment by shashankgarg93** [comment]
Hi @RashulChutani, please help with the PR

**Comment by shashankgarg93** [comment]
I put the intern start date as july so i need to complete the whole interview process within july. Please help with the PR so i can move  forward with the interview process. It is a bit urgent, thanks 😄

**Comment by shashankgarg93** [comment]
@RashulChutani Hi Rashul, Are the examples fine now?

**Comment by shashankgarg93** [comment]
Hi @RashulChutani , please verify the code changes.

**Comment by shashankgarg93** [comment]
@RashulChutani Hi, can you help me with the PR review so I can quickly move forward with the interview process? :D

**Comment by RashulChutani** [comment]
Hi @shashankgarg93 It seems to be ok. I will have a detailed look soon and merge it if everything seems ok.

**Comment by shashankgarg93** [comment]
Hi @RashulChutani, i’ve been waiting to move to the next round. Thanks, i’ll be active in case there’s any edit needed

**Review by RashulChutani — COMMENTED** [review]
Hi, The examples seem to be ok. Can you please resolve conflicts with the master.

**Comment by shashankgarg93** [comment]
Hi @RashulChutani , it is ready to be merged.

**Comment by RashulChutani** [comment]
@shashankgarg93 Please resolve the lint errors.

**Comment by shashankgarg93** [comment]
> @shashankgarg93 Please resolve the lint errors.

Done

**Comment by shashankgarg93** [comment]
The tests were running fine but now they are failing. Please help with the merge

**Comment by shashankgarg93** [comment]
are you there @RashulChutani ?

**Comment by shashankgarg93** [comment]
@RashulChutani, the doctstring test is failing, it was working fine earlier. Is there an error with the merge?

**Comment by RashulChutani** [comment]
Please check if the changes you have made pass the docstring tests.

**Comment by shashankgarg93** [comment]
I have made no changes, just merged the master branch with me. The rest code remains same and the tests were being passed earlier.

**Comment by RashulChutani** [comment]
Sure. Just make sure that the docstring tests pass for the functions you have written.

**Comment by shashankgarg93** [comment]
Yes, passing for my function

**Comment by RashulChutani** [comment]
Sure. Let me check the issues with the master and will let you know.

**Comment by shashankgarg93** [comment]
> Sure. Let me check the issues with the master and will let you know.

Please do.

**Comment by shashankgarg93** [comment]
The test which failed shows error in the log for a test case in the def negative() method

**Comment by shashankgarg93** [comment]
> The test which failed shows error in the log for a test case in the def negative() method

Can I rollback my code to the one which was passing all tests or it is not required?

**Comment by shashankgarg93** [comment]
Any update @RashulChutani ?

**Comment by shashankgarg93** [comment]
HI @RashulChutani , is it fine now?

**Comment by shashankgarg93** [comment]
@RashulChutani , HI

**Review by RashulChutani — CHANGES_REQUESTED** [review]
There are still some instances with no space such as: x = ivy.array([0., 2.0,float('nan')]). Can you please check once?

**Comment by shashankgarg93** [comment]
done!

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Please add a space here ["ivy.array([[nan, 0.],[-inf, 2.]])" should be changed to "ivy.array([[nan, 0.], [-inf, 2.]])"]

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
