### PR TITLE
reformat  DefaultDevice.__exit__

### PR DESCRIPTION
**Pull request by ahembal**
- [ ] #1764

### CODE REVIEW

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @ahembal.
I think you need an example of what would happen after a `with` statement is **exited** from which is when `__exit__` is called. It should print the device set before it. The examples added are merely using the `unset_default_device` function directly, unless I missed something. Please request my review when you make the changes.

**Review by Ishticode — CHANGES_REQUESTED** [review]
The examples are currently inaccurate. As clarified above in previous review `__exit__` statement isn't called inside `with` but rather is the method executed when `with` statement is finished and **exited** from. This is in contrast to `__enter__` which is called when `with` is initiated for example. You can check the docstring for `__enter__` for more context.  This is one usecase.  Please search  `__exit__` on google to read more on if this does not make sense. Let me know for any clarifications 😊.

**Comment by ahembal** [comment]
:) Let me check it again, this is the context manager usage, and I need to show 'with block' in the example, right? 
So, maybe I just need to move the print statement outside of the with block, 
at the end of the block __exit__ code is run in background. 
Then, print statement outside of the block, can show the default device.
Do I understand correctly?

**Comment by ahembal** [comment]
Hi @Ishticode, could you review it again? 
I changed the comment and put print statement after with block, so 'print' will be run after __exit__() function.
Thanks.

**Review by Ishticode — APPROVED** [review]
lgtm! Thanks for your contribution here. I will get it merged.

**Pull request merged**
