### PR TITLE
cosh and cosh_ added to torch frontend and tested

### PR DESCRIPTION
**Pull request by rgrupesh**
close: #6685 
close: #6686 

Signed-off-by: Rupesh <rupeshgelal9@gmail.com>

### CODE REVIEW

**Comment by rgrupesh** [comment]
@agniiyer

**Comment by agniiyer** [comment]
Hi have you tried testing with all backends? There's still a bfloat16 data type error. Take a look and let me know when it's sorted out! :)

**Comment by rgrupesh** [comment]
> Hi have you tried testing with all backends? There's still a bfloat16 data type error. Take a look and let me know when it's sorted out! :)

Can you please elaborate? Because the test passes on those implemented functions.
Screenshot from 2022-11-09 13-26-46

**Comment by agniiyer** [comment]
Sure if you run the test with the flag `--backend all` you'll see the error. You can also see it in the test logs here on Github. However, I think this is an issue that needs to be fixed on our end, so I will go ahead and merge this! Nice work :)

**Pull request merged**
