### PR TITLE
Add tensorflow frontend function 'unique'.

### LINKED ISSUE #11774: unique

### PR DESCRIPTION
**Pull request by AsakusaRinne**
Close #11774

### CODE REVIEW

**Comment by AsakusaRinne** [comment]
The output order of `tf.unique` is different from `ivy.unique`. Tensorflow keeps the order of values of original tensor. That's the reason for line 344-348 of `general_functions.py`.

**Comment by aditya-hari** [comment]
Hey! Looks good and the tests are passing, but any reason why the tests only use specific dtypes?

**Comment by AsakusaRinne** [comment]
> Hey! Looks good and the tests are passing, but any reason why the tests only use specific dtypes?

Hi! Specific dtypes are used because the test uses different backends, which may not support the dtype. For example, if I add `uint32` to the dtype list of the test, I'll get the following error:

```
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_unique[cpu-ivy.functional.backends.torch-False-False] - ivy.utils.exceptions.IvyBackendException: torch: new_fn: torch: as_native_dtype: Cannot convert to PyTorch dtype. uint32 is not supported by PyTorch.
```

**Comment by aditya-hari** [comment]
You can use the get_dtypes("valid") helper for getting the appropriate dtypes for a frontend test

**Comment by AsakusaRinne** [comment]
> You can use the get_dtypes("valid") helper for getting the appropriate dtypes for a frontend test

Thank you, however it does not work and will throw the following exception:

```
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py::test_tensorflow_unique[cpu-ivy.functional.backends.tensorflow-False-False] - ivy.utils.exceptions.IvyBackendException: tensorflow: unique_all: Value for attr 'T' of bool is not in the list of allowed values: bfloat16, half, float, double, int8, int16, int32, int64, complex64, complex128
```

**Comment by aditya-hari** [comment]
Hey, sorry for the delay. Can you reopen a new PR with the same changes? There was some reorganization lately because of which the commit history is a bit messed

**Comment by AsakusaRinne** [comment]
> Hey, sorry for the delay. Makes sense. Can you reopen a new PR with the same changes? There was some reorganization lately because of which the commit history is a bit messed

Of cource, I'll open a new PR.

**Pull request closed without merging**
