### PR TITLE
Done Tensorsolve numpy

### PR DESCRIPTION
**Pull request by JonathanGhaly**
it gives me an error in the test due to output formatting 
Expected :1.305903857309865e+18
Actual   :1305903857309865025

### CODE REVIEW

**Review by abdrahmandiab — CHANGES_REQUESTED** [review]
Hi @JonathanGhaly,
great work so far! I've pushed a fix for the tests that were failing that slightly restructures the array generation.

Just one thing left however 😅 We should recreate the exact behavior of the function being implemented in the frontend using a composition of ivy functions, and it seems that your implementation is missing logic to handle the `axes` parameter, which unfortunately is not currently part of the `ivy.solve` function!  I have included comments on the specific part of the code where this logic should be added.

As such, please feel free to implement this behavior in the frontend function, or going even deeper with this and adding that parameter to `ivy.solve` itself, and then passing the axes parameter to it. Regardless of your choice, as long as the behavior matches, we would accept the PR! 😄

Thanks and please re-request a review once these changes have been addressed!

**Comment by abdrahmandiab** [comment]
Hi @JonathanGhaly , it seems you have requested a review but the changes requested have not yet been implemented nor are there any comments, is this intentional? 😅

**Review by abdrahmandiab — CHANGES_REQUESTED** [review]
Please implement the changes addressed in the previous review in order for us to continue the process 😅

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by abdrahmandiab** [comment]
Seeing as this PR has been stale for a while, we will be closing it along with the associated issue for now, feel free to continue your application process at any time by opening another issue (for this function or another one). 

Thanks! 😅

**Pull request closed without merging**
