### PR TITLE
Fixed subract fn

### PR DESCRIPTION
**Pull request by nathzi1505**
Reformatted subtract function - #4067

### CODE REVIEW

**Comment by nathzi1505** [comment]
Hi, any suggestions you would like for me to add?

**Comment by abdrahmandiab** [comment]
hi @nathzi1505 , could you please add the reformatting task's checklist as per the instructions [here](https://lets-unify.ai/ivy/contributing/4_open_tasks.html?highlight=add_reformatting#formatting-checklist). 😅

This should hopefully take you only a few moments, but it is very important to ensure we don't miss anything, and it decreases the review time. 😋 

Thanks!

**Comment by nathzi1505** [comment]
Sure @abdrahmandiab .

**Comment by nathzi1505** [comment]
add_reformatting_checklist_elementwise

**Comment by nathzi1505** [comment]
@abdrahmandiab I am getting this error - Error: API rate limit exceeded for installation ID 14158673 in my GitHub workflow notifications. Can you help?

**Comment by nathzi1505** [comment]
add_reformatting_checklist_elementwise

**Comment by nathzi1505** [comment]
Hi @abdrahmandiab, I have added the checklist for your reference. Feel free to share any suggestions.

**Comment by nathzi1505** [comment]
Hi @abdrahmandiab, I have added the checklist for your reference. Feel free to share any suggestions.

**Comment by abdrahmandiab** [comment]
Hi @nathzi1505,
It seems that there are a lot of items in the checklist that have been marked as ⏩(skip), when they are applicable to the subtract function.

There should actually be pretty much no skipped items for this function, since it has implementations for the array and container classes, as well as the special operator function `__sub__` and the reverse special operator function `__rsub__`. 

Docstrings should be added to all of these functions according to the task description in the [docs](https://lets-unify.ai/ivy/contributing/4_open_tasks.html?highlight=open+tasks#function-formatting). And, you can use the checklist beside for an extra bit of guidance. :)

Feel free to re-request a review once the reformatting has been completed for all files. 😅

Good job so far though! The changes you have made thus look good to me. :)

**Review by abdrahmandiab — CHANGES_REQUESTED** [review]
Hi @nathzi1505,
It seems that there are a lot of items in the checklist that have been marked as ⏩(skip), when they are applicable to the subtract function.

There should actually be pretty much no skipped items for this function, since it has implementations for the array and container classes, as well as the special operator function `__sub__` and the reverse special operator function `__rsub__`. 

Docstrings should be added to all of these functions according to the task description in the [docs](https://lets-unify.ai/ivy/contributing/4_open_tasks.html?highlight=open+tasks#function-formatting). And, you can use the checklist beside for an extra bit of guidance. :)

Feel free to re-request a review once the reformatting has been completed for all files. 😅

Good job so far though! The changes you have made thus look good to me. :)

**Comment by nathzi1505** [comment]
Hi @abdrahmandiab, I have followed the checklist and have made changes as you suggested. Feel free to review them and suggest new ones if required. Thanks.

**Comment by abdrahmandiab** [comment]
> Hi @abdrahmandiab, I have followed the checklist and have made changes as you suggested. Feel free to review them and suggest new ones if required. Thanks.

Hi @nathzi1505, sorry it took me a bit to get to this, I saw your review request a few days ago and completely forgot to do it! 😅 

I am going to review this today hopefully, so be on the lookout for that soon! :)
Sorry for the inconvenience and thanks!

**Comment by abdrahmandiab** [comment]
Hey @nathzi1505 ,
Just finished reviewing and merging your PR, everything looks perfect to me! 😇

Thank you so much for your hard work, and I apologize once again for the late review! 😅
Well done!

**Pull request merged**
