### PR TITLE
isfortran

### PR DESCRIPTION
**Pull request by shireenchand**
Frontend and test for numpy isfortran

### CODE REVIEW

**Comment by shireenchand** [comment]
Hey @suvadityamuk,

The reason why I chose ```a.flags.fnc``` is because we get an extra check here on the fact that is it just``` F_Contiguous``` and not ```C_Contiguous``` as well

**Comment by suvadityamuk** [comment]
> Hey @suvadityamuk,
> The reason why I chose a.flags.fnc is because we get an extra check here on the fact that is it just F_Contiguous and not C_Contiguous as well

Right, understood. Thanks for the explanation!

Could you possibly re-check the linting errors? Might I suggest making use of the [pre-commit hook](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit) to help?

**Comment by shireenchand** [comment]
Hi @suvadityamuk, is there a reason why these tests are failing? Like something related to the frontend or do they fail usually?

**Comment by V-G-spec** [comment]
Hi, can you revert the changes other than the ones for the function you worked on in the test file?

**Comment by shireenchand** [comment]
@V-G-spec I corrected those. Can you check them?

**Comment by shireenchand** [comment]
Hi @V-G-spec,
Do let me know if there are any other changes that are needed?
Thanks!!

**Comment by V-G-spec** [comment]
Looks good, and I believe @suvadityamuk verified tests were failing due to some other files

**Pull request merged**
