### PR TITLE
added amax feature

### LINKED ISSUE #17138: amax

### LINKED ISSUE #17220: amax

### PR DESCRIPTION
**Pull request by AkshayVenkataraman**
Close #17138 
Close #17220

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by MuhammadSaeedBatikh** [comment]
Hi @AkshayVenkataraman, thanks for the PR. 
There's a conflict in `test_frontends.test_paddl.test_tensor.test_paddle_tensor.py`.
Additionally, The testing functions are not sufficient for the following args:
Axis and num_dims need to be tested further.
`available_dtypes`  needs to test for more datatypes other than floats.

**Comment by AkshayVenkataraman** [comment]
Hello @MuhammadSaeedBatikh , I've made the changes, sorry it didn't catch my eye. Kindly let me know if it solves the problem!

**Comment by AkshayVenkataraman** [comment]
Thanks, @MuhammadSaeedBatikh, resolved them.  You can merge now! :D

**Comment by MuhammadSaeedBatikh** [comment]
lgtm.

**Comment by MuhammadNizamani** [comment]
@AkshayVenkataraman @MuhammadSaeedBatikh 
There is an issue in this pull request (PR) in the file` ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py`. The problem occurs when anyone tries to run a test on any function, and it throws the following error`: TypeError: accept.<locals>.dtype_and_values() got an unexpected keyword argument 'min_axis'.`

**Comment by MuhammadSaeedBatikh** [comment]
Hi @MuhammadNizamani, thanks for pointing out this issue. Ineed, there's a problem with test function that wasn't showing up. I'm reopening this issue and reverting the merge. 
To @AkshayVenkataraman, please change the test function as such:
```
@handle_frontend_test(
    fn_tree="paddle.amax",
    dtype_and_x=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("numeric"),
    ),
)
```
Please make sure that tests pass locally. Thanks.

**Pull request merged**
