### PR TITLE
Added Paddle frontend function and test for hsigmoid_loss

### LINKED ISSUE #23196: hsigmoid_loss

### PR DESCRIPTION
**Pull request by nme998**
# PR Description

## Related Issue

Close #23196

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by he11owthere** [comment]
Hello there! Nice work but tests on CI are failing for all the backends:
https://github.com/unifyai/ivy/actions/runs/7375297990/job/20066805185?pr=23475#step:6:14

**Review by he11owthere — CHANGES_REQUESTED** [review]
Hello there! Nice work but tests on CI are failing for all the backends:
https://github.com/unifyai/ivy/actions/runs/7375297990/job/20066805185?pr=23475#step:6:14

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
