### PR TITLE
Add randint_like function to Pytorch frontend

### LINKED ISSUE #14238: #14019_like
Add `randint_like` function to Pytorch frontend

### PR DESCRIPTION
**Pull request by esh-b**
Close #14238

### CODE REVIEW

**Comment by hmahmood24** [comment]
Hey @esh-b, thanks so much for this contribution! 😃 Can you kindly run your tests locally using `pytest` and ensure that the tests are passing for all backends? I have manually tested your function locally and it seems to fail for all backends currently. Let me know if you have any questions. Thanks!

**Comment by esh-b** [comment]
Hi @hmahmood24 , I am unable to run the tests locally since I get this error shown in the image.
image

But I thought the test was okay since the `run_tests_1` was successful?

**Comment by hmahmood24** [comment]
The `run_tests_1` workflow [could not determine](https://github.com/unifyai/ivy/actions/runs/4717915783/jobs/8366957614?pr=14239#step:3:98) your added test and hence didn't run it. I manually ran your implementation locally and found it to fail for all backends. I think your error indicates that you need to reinstall the packages in `requirements.txt` and `optional.txt` files, in the `requirements` folder, within a fresh new environment to be able to run the tests locally. Let me know if this helps!

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
