### PR TITLE
Reformat Softmax activation function #839

### PR DESCRIPTION
**Pull request by hg19939**
This pull request concerns issue #839. Here is a brief overview of the changes I made:

- The `ivy.softmax` function's docstring is now in NumPy style rather than Sphinx.
- Reformatted the Softmax activation function according to requirements mentioned in this [link](https://www.youtube.com/watch?v=fHTJEpkkAqY&list=PLwNuX3xB_tv9A9fVtIqgh2mH6ZPxJ2eB6&index=2).
- Included a docstring unit test.

### CODE REVIEW

**Comment by bicycleman15** [comment]
`.idea` folder should not be in the commit. Could you please exclude those files. Rest LGTM ! 🙂

**Comment by bicycleman15** [comment]
There are some conflicts as well, please try to resolve those.
If you are not able to, let me know 🙂

**Comment by hg19939** [comment]
Sure, I will give it a try. I first noticed conflicts yesterday; initially when I made the PR there were none. Also what is LGTM? Google suggests it's "Looks Good To Me", but since I am not sure, I have to ask.

**Comment by bicycleman15** [comment]
Yes, LGTM does mean Looks Good to Me :)

**Comment by hg19939** [comment]
Hello @bicycleman15 . First of all, apologies for the slightly messy commit history. I managed to resolve the conflicts fairly easy. I made the following changes:

- Followed [this](https://stackoverflow.com/questions/11124053/accidentally-committed-idea-directory-files-into-git) Stackoverflow thread to remove the `.idea` folder.
- Removed the docstring test because it was causing issues with regards to the run-nightly-tests. The log suggested there was no docstring test and after removing it the problem was gone.

Please, let me know if the approach is acceptable.

**Comment by bicycleman15** [comment]
hey @hg19939. you must not add `.idea` folder to `.gitignore`. 
Helpful tip is just don't stage those files present inside `.idea` folder when you make a commit.

I would suggest you to close this PR and make a fresh one, we will take it from there. Right now it has become very messy 🙂

**Comment by hg19939** [comment]
Hello @bicycleman15 . Thanks for the feedback, I will make sure to open a new PR. The command I am supposed to use to delete the `.idea` folder is still `git rm -r --cached .idea`, right?

**Comment by bicycleman15** [comment]
Basically, you are not supposed to touch the `.idea` folder anywhere in the commit/PR.
That's all.
So, when you create a new PR, make sure you don't touch the `.idea` folder. 🙂

**Pull request closed without merging**
