### PR TITLE
conj

### PR DESCRIPTION
**Pull request by shireenchand**
Added pytorch conj with frontend and tests

### CODE REVIEW

**Comment by shireenchand** [comment]
#11979

**Comment by aditya-hari** [comment]
Hey! The text itself is fine, but why has the indentation of all the function in the test file been changed?

**Comment by shireenchand** [comment]
I think the PEP reformatting did that. I'll get that changed and push it. Thanks!

**Comment by shireenchand** [comment]
fixed the listing error! Please do review it

**Comment by aditya-hari** [comment]
LGTM!

**Pull request merged**
