### PR TITLE
Add: added fmax method for torch frontend

### LINKED ISSUE #20123: fmax

### PR DESCRIPTION
**Pull request by ajay-vishnu**
Close #20123

### CODE REVIEW

**Comment by ajay-vishnu** [comment]
Hey @Infrared1029, I dunno why few tests are failing. Could you help me out on this?

**Comment by ajay-vishnu** [comment]
@Infrared1029, The test case isn't passing because of usage of unsupported datatype, i.e., `bfloat16`. This issue, #9492 is still opened and is being reviewed. Do tell me if there are any changes to be made in the code. :)

**Comment by ajay-vishnu** [comment]
And as for the ones like issue, it is open in #8599.

**Comment by Infrared1029** [comment]
@ajay-vishnu taking a quick look, code looks good to me, will test properly and merge once the ones_like function works

**Comment by ajay-vishnu** [comment]
Alright, that sounds great. :)

**Comment by ajay-vishnu** [comment]
@Infrared1029, all the test are passing now. Do tell me if there needs to be any changes to be made.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
