### PR TITLE
Avg pool3D

### LINKED ISSUE #11776: AvgPool3D

### PR DESCRIPTION
**Pull request by shreyjain26**
Close #11776

### CODE REVIEW

**Comment by shreyjain26** [comment]
Hi @ZoeCD , could you please review this and help me through the task

**Comment by ZoeCD** [comment]
LGTM! Do you have any specific questions?

**Comment by shreyjain26** [comment]
Yeah. Why do I fail the lint test? Can you please help me through it?

**Comment by shreyjain26** [comment]
@ZoeCD Could you please help me understand where is the lint test failing.
image
When I am doing it locally, flask8 in pre-commit passes and shows no error. But after pushing to git, the lint test fails. Please help.

**Comment by ZoeCD** [comment]
Don't worry about the lint errors that appear in CI; they're not related to your PR. There are some branch conflicts to solve, but other than that, I think your PR looks good

**Comment by ZoeCD** [comment]
Hey @shreyjain26  we did a `push --force` on master to remove unwanted files from the commit history, please follow the steps suggested in Dan's public announcement on discord a few weeks ago to get your branch up to date with the latest commit history 😊

**Pull request closed without merging**
