### PR TITLE
feat: adds missing sequence_insert onnx function to ivy Api experimental.

### LINKED ISSUE #26852: SequenceInsert

### PR DESCRIPTION
**Pull request by tbeetech**
# feat: adds missing sequence_insert onnx function to ivy Api experimental

## #26852 

Closes #26852 

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by tbeetech** [comment]
for some reasons the check formatting test error points to line 393 but line 393 is blank can you give me advice on the next step or do you think I'm ready for merge is so please merge thanks
Screenshot (228)

**Comment by tbeetech** [comment]
@MahmoudAshraf97 pls review me thanks

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
Hello, please remove all the changes that are not related to your PR such as formatting

**Comment by tbeetech** [comment]
@MahmoudAshraf97 please can i get a review no

**Comment by MahmoudAshraf97** [comment]
Hello @tbeetech , this function has no native implementations in any of the 5 frameworks so this function does not meet the requirements of adding a new functional function. I will have to close this PR unfortunately but thanks for your contribution.

**Pull request closed without merging**
