### PR TITLE
Added round_ method to the Paddle frontend

### PR DESCRIPTION
**Pull request by he11owthere**
closes https://github.com/unifyai/ivy/issues/22480

### CODE REVIEW

**Comment by he11owthere** [comment]
I'm encountering the following error message across all the backends, indicating that the return value from my `round_` method (specifically, -0.0) doesn't match the returned value from the backend's `round_` method (i.e. -1.0) when testing with input = -0.5.

As per the array API standard, the expected behavior is to return the nearest integer value in such situations. I would greatly appreciate your guidance on this matter. Thank you very much for your assistance!

image

**Comment by ZoeCD** [comment]
Hello, Bhushan! I see what you mean. Paddle paddle does not follow the standard 
[https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/round_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/round_cn.html). I'm tagging @AnnaTz since she is leading the frontends. She'll know what's best to do in this case!

**Comment by AnnaTz** [comment]
> I'm encountering the following error message across all the backends, indicating that the return value from my `round_` method (specifically, -0.0) doesn't match the returned value from the backend's `round_` method (i.e. -1.0) when testing with input = -0.5.
> 
> As per the array API standard, the expected behavior is to return the nearest integer value in such situations. I would greatly appreciate your guidance on this matter. Thank you very much for your assistance!
> 
> image

It seems that `paddle.round` does not follow the array api standard. You can see in the official documentation's [example](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/round_cn.html#round) that paddle indeed round -0.5 to -1.0.
A frontend function should mimic the original function's behavior, so your implementation should return the same results as paddle.

**Comment by he11owthere** [comment]
Thanks, @AnnaTz, for your effort and guidance. I've made the necessary changes. 😊
@ZoeCD, I've resolved the merge conflicts, and the PR is ready for merging. 🙂

**Comment by ZoeCD** [comment]
Thank you for the help @AnnaTz! 
And thank you for your PR @he11owthere!

**Pull request merged**
