### PR TITLE
Binomial Random sampling numpy frontend

### PR DESCRIPTION
**Pull request by RavinderPal408**
I close my previous PR and reopen this

### CODE REVIEW

**Review by RavinderPal408 — COMMENTED** [review]
Kindly review my changes

**Comment by ZiadAmerr** [comment]
Hi @RavinderPal408, thanks for your contribution. Can you revert back to the previous commit? I think the last commit has changes to other irrelevant files.

**Comment by RavinderPal408** [comment]
Hi @ZiadAmerr  in last commit i.e "ivy and test_ivy changed" I accidentally push 4,649 files, it is my mistake but I only changed two files I,e ivy.frontend.numpy (function)and test_ivy (testing). Please consider my "binomial frontend function" commit as actual commit .Kindly ignore other commits

**Comment by RavinderPal408** [comment]
Hi @ZiadAmerr I try to revert back this commit but not able to do this . Can You please help me in reverting back to previous commit
I will be thankful to you.

**Comment by ZiadAmerr** [comment]
Yes, you can use `git revert <commit_hash>`, with the commit hash being the commit hash of the last commit that was valid, you can find it using `git log`.

**Comment by RavinderPal408** [comment]
Hi @ZiadAmerr ,Is this commit ok now to merge

**Comment by ZiadAmerr** [comment]
No, you need to make sure that the files changed are the only files related to your PR. As ypu can see; you have 4000+ files changed

**Comment by ZiadAmerr** [comment]
Hi @RavinderPal408, if you are facing problems, I can suggest closing this PR and opening a clean new one with the changes you want. :)

**Pull request closed without merging**
