### PR TITLE
empty_like adhering to Array API standard

### PR DESCRIPTION
**Pull request by RickSanchezStoic**
empty_like #254 tests for all backends passing locally except mxnet for which I didn't implement the function.

### CODE REVIEW

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
`empty` is a separate function to yours `empty_like` so you shouldn't delete it. Please can you only make changes to your function, Thanks!

**Comment by RickSanchezStoic** [comment]
Ok, I will update you soon with the changes.

**Review by mattbarrett98 — COMMENTED** [review]
I just made a couple of small changes, but everything looks good! We will just get confirmation from @djl11 before merging your changes. Thanks 🙂

**Comment by RickSanchezStoic** [comment]
Thank you Matt a lot for helping me out.

**Comment by mattbarrett98** [comment]
Thanks for contributing!

**Comment by RickSanchezStoic** [comment]
Thank you @mattbarrett98

**Pull request merged**
