### PR TITLE
added adagrad optimizer, adagrad_update and adagrad_step

### LINKED ISSUE #20851: Adagrad

### PR DESCRIPTION
**Pull request by ShreyanshBardia**
closes #20851

### CODE REVIEW

**Comment by ShreyanshBardia** [comment]
Some tests are falling but I'm not sure if they are due to the current PR. Similar tests are failing for other previous optimizers as well. @JPGoodale can you confirm if the issue is due to PR or the test decorators

**Comment by ShreyanshBardia** [comment]
HI @vedpatwardhan, can you take a look at this PR.

**Review by vedpatwardhan — COMMENTED** [review]
Hey @ShreyanshBardia, we should be adding this function to the experimental API rather than the main API. Given that @JPGoodale has been assigned to the PR, he'll take a look soon, thanks 😄

**Comment by ShreyanshBardia** [comment]
Oh yes, correct.  Moved the functions to experimental API. I don't think experimental API exist for stateful module though, so the optimizer still exists in main API.

**Comment by JPGoodale** [comment]
Hi @ShreyanshBardia, thank you for your contribution, most of the `gradients` tests are passing with the exception of Paddle failing on both functions due to use of `bfloat16` which is not available in Paddle. Besides this it looks like there are some issues with the `optimizers` module due to length mismatches such as: `AssertionError: result length mismatch: [array([1.], dtype=float32)] (1) != [] (0)`.

**Comment by ShreyanshBardia** [comment]
Hey @JPGoodale, yes the tests are indeed failing, but I'm not sure if they are due to this PR or due to some bug in test functions because tests for other existing optimizers are failing as well.
```

__________________ test_adam_optimizer[cpu-jax-False-False] ___________________
ivy_tests/test_ivy/test_stateful/test_optimizers.py:124: in test_adam_optimizer
    init_tree="ivy.stateful.optimizers.Adam",
ivy_tests/test_ivy/test_stateful/test_optimizers.py:159: in test_adam_optimizer
    helpers.test_method(
ivy_tests/test_ivy/helpers/function_testing.py:1[319](https://github.com/unifyai/ivy/actions/runs/5792566049/job/15699211351?pr=21261#step:3:320): in test_method
    gradient_test(
ivy_tests/test_ivy/helpers/function_testing.py:947: in gradient_test
    assert len(grads_np_flat) == len(
E   AssertionError: result length mismatch: [array([1.], dtype=float32)] (1) != [] (0)
```
Could you confirm this, please

**Comment by JPGoodale** [comment]
Hey @ShreyanshBardia, I see what you're saying about the other optimizers failing as well, thanks for pointing this out! Let me discuss this with the authors of those functions so we can get this fixed and your PR merged.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ShreyanshBardia** [comment]
Hi @JPGoodale, has there been any update? If not should I keep this PR open

**Pull request closed without merging**
