### PR TITLE
Atan2

### LINKED ISSUE #12012: atan2

### PR DESCRIPTION
**Pull request by shreyjain26**
Close #12012

### CODE REVIEW

**Comment by shreyjain26** [comment]
Hi @sherry30 , could you please review this and help me through the task

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

currently the tests are failing because of a mistake which I pointed out on the specific line.
The tests will pass after that probably.

Thanks

**Comment by shreyjain26** [comment]
Lint test is still failing

**Comment by shreyjain26** [comment]
@sherry30 Locally in pre-commit flask8 lint test passes but for some reason it does not pass here.
image
Please help me understand what I am doing wrong and how do I resolve it.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

The lint errors on the CI are unrelated to your PR, you do not have to worry about those 😃 

Your PR looks good, can you resolve the merge conflict?
I'll merge your PR as soon as you resolve that

Thanks

**Comment by shreyjain26** [comment]
Hi, 
How do I update my branch without discarding commits. When I try to sync to the master, it only shows me option to discard the commits.

**Comment by shreyjain26** [comment]
Merge conflicts have been resolved. This pr can be merged now

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

I think you accidentally pushed changes to the .idea files 😅 
I'll merge once you remove those 

Thanks

**Comment by shreyjain26** [comment]
It's only end of the file difference. There isn't any change in the files.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Your PR shouldn't detect any changes in those files. 
you can remove any changes from those by reverting commits or if there is any other easier to do it you can go ahead and try it

Thanks

**Pull request closed without merging**
