### PR TITLE
feat: added helper function in sklearn.utils.validation

### LINKED ISSUE #23700: helper function _num_samples in sklearn frontend

### PR DESCRIPTION
**Pull request by zeus2x7**
# PR Description

added helper function _num_samples for sklearn frontend

## Related Issue

Close #23700

## Checklist

&#9745; Did you add a function?
&#9745; Did you add the tests?
p.s is there any need to add a test function for a function implemented that does not return anything?
&#9745; Did you run your tests and are your tests passing?
&#9745; Did pre-commit not fail on any check?
&#9745; Did you follow the steps we provided?

### CODE REVIEW

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hey @zeus2x7,

Looks like you PR is not linked to any TODO list, and I'm confused what you are trying to do. Can you link it to a TODO list?

**Comment by zeus2x7** [comment]
> Hey @zeus2x7,
> 
> Looks like you PR is not linked to any TODO list, and I'm confused what you are trying to do. Can you link it to a TODO list?

Yes it's not linked to any todo list i am trying to add these functions as they serve as helpers to the functions which i want to implement at later stage

**Comment by zeus2x7** [comment]
hi @KareemMAX  can you please review it ?
It would be a lot helpful

**Comment by zeus2x7** [comment]
hi @KareemMAX  can you please review the pr it would be helpful.

**Comment by KareemMAX** [comment]
Hey @zeus2x7, extremely sorry for the late reply. I was out of office the past week.

> Yes it's not linked to any todo list i am trying to add these functions as they serve as helpers to the functions which i want to implement at later stage

Can you please elaborate further on what functions are you trying to implement. We generally don't want to bloat our code with unnecessary functions, that's why I need to know exactly why we are adding it. Preferably while linking and issue to it as well.

**Pull request closed without merging**
