### PR TITLE
add nanmax 

### PR DESCRIPTION
**Pull request by AmeenUrRehman**
#8000 solving this issue

### CODE REVIEW

**Comment by AmeenUrRehman** [comment]
@juliagsy plz review my code

**Comment by AmeenUrRehman** [comment]
@juliagsy hey could you plz review my code as the reviewer not responding plz.

**Review by juliagsy — COMMENTED** [review]
Hey! Thanks for the great work! The PR looks good to me! Before I approve it, I'll just have to double check a hypothesis HealthCheck error, will get back soon! Thanks a lot!

**Comment by YushaArif99** [comment]
@juliagsy Thanks a lot for stepping in 🙂 . I have approved the changes on my end. When you're done verifying the hypothesis error, feel free to merge the PR. Thanks!

**Review by juliagsy — APPROVED** [review]
Thanks for contributing! Will merge in soon!

**Pull request merged**
