### PR TITLE
added abs instance method to PyTorch frontend and tested

### PR DESCRIPTION
**Pull request by Intenzo21**
PR for #5804

### CODE REVIEW

**Comment by Intenzo21** [comment]
Close #5804

**Comment by Intenzo21** [comment]
Much appreciated, James!

**Comment by Intenzo21** [comment]
> Looks good to me, seems that tests didn't run properly so I re-ran them. Will get back once they have passed :)

@jkeane508 Any update on this matter?

**Comment by jkeane508** [comment]
> > Looks good to me, seems that tests didn't run properly so I re-ran them. Will get back once they have passed :)
> 
> @jkeane508 Any update on this matter?

Yea looks to be an issue with the testing suite, Im going to merge anyway, it looks fine to me!

**Pull request merged**
