### PR TITLE
fix: use tf numpy api instead for broader superset dtype support

### PR DESCRIPTION
**Pull request by mattbarrett98**
I've changed many of the tf elementwise functions that have been problematic for the integrations (as well as some other similar functions which have the same problem) to use the `experimental.numpy` api instead, which mirrors numpy, and hence has wider dtype support.

The basic problem being that tf has stricter dtype support, and so often when transpiling from any other framework to tf we run into issues. for example, all other backends support integer inputs in `exp` but tf, so if `torch.exp` is used on an integer input in some function, and this is transpiled to tf, it will throw an exception as integers aren't supported in `tf.math.exp`.

I think this is a pretty fundamental hole in our 'superset' behaviour which we claim to strive for. It also required enabling some flag in the tf backend init, which hopefully doesn't have any unintended consequences in the tests @vedpatwardhan

### CODE REVIEW

**Comment by vedpatwardhan** [comment]
ivy-gardener

**Comment by vedpatwardhan** [comment]
Hey @mattbarrett98 could you please try a few examples using `ivy.crosscast_data_types` or `ivy.cast_data_types`?
So for e.g.,
```
import ivy

ivy.set_backend("tensorflow")
# can also use ivy.cast_data_types() instead which enables upcasting, downcasting as well as cross-casting
ivy.crosscast_data_types()  

x = ivy.array([1, 2, 3])
print(ivy.expm1(x))
```
gets `ivy.expm1` working with the `tensorflow` backend. I suppose there was some issue with the unsupported dtypes functions which is why this wasn't working. I had pushed a fix for the unsupported dtypes stuff last week after which this might've started working. Thanks 😄

**Review by vedpatwardhan — COMMENTED** [review]
Hey @mattbarrett98 could you please try a few examples using `ivy.crosscast_data_types` or `ivy.cast_data_types`?
So for e.g.,
```
import ivy

ivy.set_backend("tensorflow")
# can also use ivy.cast_data_types() instead which enables upcasting, downcasting as well as cross-casting
ivy.crosscast_data_types()  

x = ivy.array([1, 2, 3])
print(ivy.expm1(x))
```
gets `ivy.expm1` working with the `tensorflow` backend. I suppose there was some issue with the unsupported dtypes functions which is why this wasn't working. I had pushed a fix for the unsupported dtypes stuff last week after which this might've started working. Thanks 😄

**Comment by mattbarrett98** [comment]
> Hey @mattbarrett98 could you please try a few examples using `ivy.crosscast_data_types` or `ivy.cast_data_types`? So for e.g.,
> 
> ```
> import ivy
> 
> ivy.set_backend("tensorflow")
> # can also use ivy.cast_data_types() instead which enables upcasting, downcasting as well as cross-casting
> ivy.crosscast_data_types()  
> 
> x = ivy.array([1, 2, 3])
> print(ivy.expm1(x))
> ```
> 
> gets `ivy.expm1` working with the `tensorflow` backend. I suppose there was some issue with the unsupported dtypes functions which is why this wasn't working. I had pushed a fix for the unsupported dtypes stuff last week after which this might've started working. Thanks 😄

seems to work yea, could you make the cross casting mode default then if we are going with this approach @vedpatwardhan ?

**Comment by vedpatwardhan** [comment]
> > Hey @mattbarrett98 could you please try a few examples using `ivy.crosscast_data_types` or `ivy.cast_data_types`? So for e.g.,
> > ```
> > import ivy
> > 
> > ivy.set_backend("tensorflow")
> > # can also use ivy.cast_data_types() instead which enables upcasting, downcasting as well as cross-casting
> > ivy.crosscast_data_types()  
> > 
> > x = ivy.array([1, 2, 3])
> > print(ivy.expm1(x))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gets `ivy.expm1` working with the `tensorflow` backend. I suppose there was some issue with the unsupported dtypes functions which is why this wasn't working. I had pushed a fix for the unsupported dtypes stuff last week after which this might've started working. Thanks 😄
> 
> seems to work yea, could you make the cross casting mode default then if we are going with this approach @vedpatwardhan ?

Yep, I'll create a bounty task for this as we also need to enable the casting modes by default in the tests, etc. In the meantime, feel free to enable the casting modes in the tracer so that this doesn't become a blocker on your work. Thanks @mattbarrett98 👍

**Comment by mattbarrett98** [comment]
okay nice, will close this pr then thanks @vedpatwardhan

**Pull request closed without merging**
