### PR TITLE
Fix Ivy Failing Test: numpy - creation.asarray

### PR DESCRIPTION
**Pull request by fleventy-5**
# PR Description
Tested for 200 examples test cases for numpy backend  for ivy
Screenshot from 2024-02-08 14-54-09
Tested for 1000 examples test cases for numpy frontend
Screenshot from 2024-02-07 01-19-46

## Related Issue

Closes https://github.com/unifyai/ivy/issues/28203

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by NiteshK84** [comment]
image
image
 @reproduce_failure('6.98.3', b'AXicY2BkAAIwAQMAADIAAw==') 
 Please test again and try to fix these failures.

**Comment by NiteshK84** [comment]
The other test is fine
image

**Comment by fleventy-5** [comment]
@NiteshK84  I'll do the fix for paddle backend also since this fix was only for the numpy backend

**Comment by fleventy-5** [comment]
@NiteshK84 do you know why I'm getting None Type Value is it some issue with the test handler or something else
Screenshot from 2024-02-13 21-18-38

**Comment by Ishticode** [comment]
Thank you very much for the PR and the effort.
The backend numpy and frontend numpy array creation functions do support complex and bool (as you may see with the script below) so even if this resolves some test we should not be going down with this fix.
```python
import ivy
ivy.set_backend('numpy')
print(ivy.array([True]), print(ivy.array([1.+2j])))
import ivy.functional.frontends.numpy as ivy_np
print(ivy_np.asarray([True]), ivy_np.asarray([1.+2j]))
```
 Please feel free to reopen and explain if I am misunderstanding something.

**Pull request closed without merging**
