### PR TITLE
reformatted cos

### PR DESCRIPTION
**Pull request by jashdalvi**

### CODE REVIEW

**Comment by jashdalvi** [comment]
It would be helpful if someone could review this.

**Review by mattbarrett98 — CHANGES_REQUESTED** [review]
Could you remove the docstring test that you added, it is no longer necessary to add this 🙂

**Comment by jashdalvi** [comment]
Sure, I will do this right away.

**Comment by jashdalvi** [comment]
@mattbarrett98 I have done the necessary changes. Please take a look at this!!

**Pull request merged**
