### PR TITLE
reformat atan function (#2263,#761)

### PR DESCRIPTION
**Pull request by Ahmetf1**

### CODE REVIEW

**Comment by Ahmetf1** [comment]
@Darshan-H-E can you please check the PR ?

**Comment by Darshan-H-E** [comment]
Hi @Ahmetf1, apologies for the delay.
There are a couple of minor fixes that needs to be done before merging this PR into master.
- Make changes such that it passes the lint check on CI.
- Resolve the merge conflicts.
Please feel free to ask if you have any doubts.
Thank you.

**Comment by Ahmetf1** [comment]
Hi @Darshan-H-E,
The atan function seems to be already merged. What to do next ?

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
