### PR TITLE
Function reformat: matrix_transpose (#4229)

### PR DESCRIPTION
**Pull request by Sindhuinti**

### CODE REVIEW

**Comment by Sindhuinti** [comment]
**Issue tag** #792

**Comment by Sindhuinti** [comment]
@djl11 check this PR

**Comment by JerryGCDing** [comment]
Hi @Sindhuinti, sorry about the late check-in. Are you still planning to work on this PR, if so, could you fix the failing `lint` and `test-docstrings` checks associated with this PR?

**Comment by Sindhuinti** [comment]
I will work on it

**Pull request closed without merging**
