### PR TITLE
Added updated digamma function for TensorFlow frontend

### LINKED ISSUE #23001: digamma

### PR DESCRIPTION
**Pull request by Thathsarani-Sandarekha**
# Add Digamma Function and Tests to Ivy TensorFlow frontend Math Library

## Summary:
This pull request introduces the Digamma function to the Ivy math library and adds corresponding unit tests. The Digamma function calculates the digamma (Ψ) function, which is a commonly used special function in mathematical and statistical computations.

Close #23001

## Changes Made

- [x] Did you add a function?

Added the Digamma function to math.py with the following details:

* Added a new function 'digamma(x)' to the 'math.py' module. This function computes the digamma function for input 'x'.

- [x] Did you add the tests?

* Added a test suite for the Digamma function in the 'test_tensorflow_math.py' module. The tests cover various data types and input values to ensure the correctness of the Digamma function in the TensorFlow frontend.

- [x] Did you follow the steps we provided?

Yes

### Reason for Changes:

The addition of the Digamma function is essential for various mathematical and statistical computations.

These changes contribute to Ivy's capabilities and support for mathematical operations, making it a more versatile and reliable library for scientific computing.

Please review and consider merging these changes to enhance Ivy's functionality and maintain its compatibility with TensorFlow and other backends.

### CODE REVIEW

**Comment by Thathsarani-Sandarekha** [comment]
Hi @ZoeCD could you please review?
@ZoeCD any more changes to be made? or is this looking good?
Thank you!

**Comment by Thathsarani-Sandarekha** [comment]
Hi @ZoeCD a kind request to review my PR. Thanks!

**Comment by Thathsarani-Sandarekha** [comment]
Hi @ZoeCD. Another kind request to review my PR. Thanks!

**Review by ZoeCD — CHANGES_REQUESTED** [review]
Hey! Sorry for the late reply. There shouldn't be any changes to the config files. So please revert the changes made to `.idea/runConfigurations/_template__of_py_test.xml`
Thanks!

**Comment by Thathsarani-Sandarekha** [comment]
Hi @ZoeCD Thank you so much for your review. I reverted the changes in .idea/runConfigurations/_template__of_py_test.xml. 
Any more changes to be made? or is this looking good?
Thank you!

**Comment by ZoeCD** [comment]
LGTM! Thanks!

**Comment by Thathsarani-Sandarekha** [comment]
Thank you so much @ZoeCD!

**Pull request merged**
