### PR TITLE
Mean 1890

### PR DESCRIPTION
**Pull request by Paulyn01**

### CODE REVIEW

**Comment by simonetgordon** [comment]
Hi there,

Thanks for your contribution! There are a few issues to address. Similar to your other PR for `any`.

Failing docstring test. You can see further details under Details -> Run Docstring Tests. It seems the output is not matching the docstring test example. Are you running these examples using the master branch of ivy as opposed to the stable version? You can run the master version by opening a .py file within your local ivy repository on the command line/ terminal (if you have a mac) and running the examples here. The import ivy will import the most recent master version as long as you have pulled recently too.

the numpy style docstring test is failing. You can view the details in a similar way to the test-docstrings in order to resolve (it could be the lack indentation causing this, which I have pointed out above).

Feel free to ask any questions!

Simone

**Comment by simonetgordon** [comment]
Also, I noticed that both `mean` and `any` are being edited here. Ideally you would have the title of the PR matching the edits exactly. You can either change the title of the PR to encompass both function changes, or alternatively separate the changes into two PRs.

**Comment by simonetgordon** [comment]
Hi Pauline,

This PR can be worked on now since `any` has been merged. It will need to be updated with a pull from master, and merge conflicts need to be resolved. Let me know if you run into any issues!

**Comment by Paulyn01** [comment]
alright. Thank you

**Pull request closed without merging**
