### PR TITLE
EHN : ptp methos is add in Jax devicearray.py

### LINKED ISSUE #19048: ptp

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
closed #19048

### CODE REVIEW

**Comment by MuhammadNizamani** [comment]
@D0m-inic  review this please

**Comment by D0m-inic** [comment]
Hi Muhammad, looks good to me. It looks to me like the dtype and axis values for the test can be obtained from already existing helper methods, could you explain your reasoning behind creating a new composite?

**Comment by D0m-inic** [comment]
It looks to me like your `st.composite` seems to be quite similar in functionality to `helpers.dtype_values_axis` which you could use?

**Comment by MuhammadNizamani** [comment]
> It looks to me like your `st.composite` seems to be quite similar in functionality to `helpers.dtype_values_axis` which you could use?

@D0m-inic  What should I do ? should I change my test method??

**Comment by D0m-inic** [comment]
From what I see, you can get rid of your created `@st.composite`, as it is similar in functionality to the `helpers.dtype_values_axis` function, and in the `@handle_frontend_method` wrapper, when passing in `dtype_and_x_axis_dtype`, make a call to `helpers.dtype_values_axis`  instead. 

If you have a reason to use your custom composite that i'm overlooking, please let me know 😄

**Comment by MuhammadNizamani** [comment]
@D0m-inic I have make changes that you asked for and all test are passing.

**Comment by D0m-inic** [comment]
Hi Muhammad, just checked your PR and it seems some tests are failing, due to complex values types not being allowed.

I see some merge conflicts too? I know about the clone PR of this function being erroneously merged already, but @juliagsy said she already resolved the conflicts so I'm assuming its just something small :)

**Comment by MuhammadNizamani** [comment]
@D0m-inic I will resolve the issue and then I will mention you server

**Comment by D0m-inic** [comment]
👍

**Comment by MuhammadNizamani** [comment]
All tests passed on 
domnic PR

**Comment by D0m-inic** [comment]
Hey Muhammad, could you remove the `shape` parameter from `dtype_values_axis` for random shapes in testing? (This would also mean adding the `valid_axis=True` and `min_num_dims=1` parameters to prevent illegal inputs).

Also, you can change the value of `helpers.get_dtpyes` to be `"float"` instead of `"numeric"`, and then remove the conditionals for the complex numbers.

After these changes i'm happy to merge 😃

**Comment by MuhammadNizamani** [comment]
Sure thanks

**Comment by MuhammadNizamani** [comment]
@D0m-inic I have made changes that you asked for

**Comment by D0m-inic** [comment]
LGTM 👍

**Pull request merged**
