### PR TITLE
Add Instance Methods PyTorch Frontend

### PR DESCRIPTION
**Pull request by Natan-Coder**

### CODE REVIEW

**Comment by Natan-Coder** [comment]
Close #15844

**Comment by Ookamice** [comment]
@Natan-Coder 
Hiya, sorry for the delay in reviewing your PR 😅 
Please could you refer to the [contributor's guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) regarding writing testcases for the function you have implemented.

Let me know if you have any other concerns or question! 😃

**Comment by Natan-Coder** [comment]
Thanks for reviewing my PR. I'm still getting familiar with proper coding techniques and the social/sharing aspect of GitHub. But I really do want to be part of the contributing team to Ivy

**Comment by Ookamice** [comment]
@Natan-Coder 
Great to hear! Let me know if you have any concerns of questions regarding writing test cases. 😄

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by Natan-Coder** [comment]
@Ookamice 
Can the test case be run using Pycharm community? My trial for Pycharm professional ended and I'm wondering if I'll have to start reconfiguring using a different IDE or if I can continue with the community version.

**Comment by Ookamice** [comment]
@Natan-Coder
I'm not 100% sure if my knowledge about PyCharm is outdated or not but from my memory, only PyCharm Professional allows for the use of a remote docker interpreter.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Pull request closed without merging**
