### PR TITLE
feat(frontends): add bitwise_right_shift_ to PyTorch Frontend

### LINKED ISSUE #23768: bitwise_right_shift_

### PR DESCRIPTION
**Pull request by Louay-Ben-nessir**
# PR Description
Added the bitwise_right_shift_  function to torch tensor front end along with the tests.

## Related Issue

Close #23768

## Checklist

- [x] Added the bitwise_right_shift_ to torch tensor front end.
- [x] added the tests.
- [x] Ran the tests.

### CODE REVIEW

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
Hey @Louay-Ben-nessir, can you look into the [failing tests](https://github.com/unifyai/ivy/actions/runs/6227901593/job/16932833638?pr=24155) on this PR please? Thanks!

**Comment by hmahmood24** [comment]
> hello @hmahmood24 , I will try to fix them ASAP. But other than test 1 all of the other failing tests are due to `E ModuleNotFoundError: No module named 'dill'` I don't think this error is related to my code, should I still try to fix it?

Don't worry about that. You just need to look at the link I shared in the previous comment. Additionally I recommend using `pytest` and running your tests locally first to ensure they pass for all backends and then commit them

**Comment by Louay-Ben-nessir** [comment]
@hmahmood24 should I investigate the last 2 failing tests or is this good?

**Review by hmahmood24 — APPROVED** [review]
Hey @Louay-Ben-nessir, the PR seems good to merge now. Thanks a lot for the contribution! 😃

**Comment by Louay-Ben-nessir** [comment]
hello @hmahmood24, Thanks a lot for your help with my first PR! 🙌

**Pull request merged**
