### PR TITLE
Add bugbear to linter

### PR DESCRIPTION
**Pull request by sladyn98**
This pull request seeks to add the [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) plugin into our current pre-commit hooks configuration. Bugbear is a plugin for flake8, adding some more opinionated checks. It is designed to find likely bugs and design problems in our Python code.

### CODE REVIEW

**Comment by sladyn98** [comment]
CC @vedpatwardhan

**Comment by vedpatwardhan** [comment]
Hey @sladyn98, I think the usage of `flake8-bugbear` should be made as an [`additional dependency`](https://github.com/pallets/flask/blob/15a0d4afd481a7f8f7dcf3b45da7175ed14226c5/.pre-commit-config.yaml#L26) on this [line](https://github.com/unifyai/ivy/pull/17864/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R16). We'd also need to add it in our requirements files similar to [this](https://github.com/facebookresearch/ParlAI/blob/ec2132811f6d51e63fc645df3cf9ff69b9bd3b37/requirements.txt#L8), but I'll leave that with you and @KareemMAX if you guys think it's required. Thanks guys!

**Comment by sladyn98** [comment]
Added as an additional dependency.

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Hey @sladyn98,

Seems like `flake8-bugbear` would be a great addition to help us catch bugs quickly.

I'm expecting we will have lots of lint failures once it is integrated correctly so we might need to do a bit of a sweep 😅. Ideally our linting check should pass on this PR because we only check for changed file, so [this failure](https://github.com/unifyai/ivy/actions/runs/5407828840/jobs/9826262658?pr=17864#step:5:106) means there is a catastrophic failure usually.

I suggest we do a `pre-commit run --all-files` and make sure it passes before we merge as well, I know there are present failures on master so we may just check for flake8-bugbear related errors, but Ideally this command should pass.

But for now lets focus on running `flake8-bugbear` correctly first, then see what we can do afterwards.

**Comment by sladyn98** [comment]
@KareemMAX I suggest we do a pre-commit run --all-files and make sure it passes before we merge as well, I know there are present failures on master so we may just check for flake8-bugbear related errors, but Ideally this command should pass.

Should we do this first ? in a separate PR and then come and fix this

**Comment by KareemMAX** [comment]
@sladyn98 Yup I agree, it would a small PR anyway. Let's do that first then continue on this PR

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by sladyn98** [comment]
Let us see after fixing the linter does this still fail @KareemMAX

**Review by KareemMAX — CHANGES_REQUESTED** [review]
Seems like a review request was made by mistake. Asking for changes again

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by KareemMAX** [comment]
Hey @sladyn98,
I'll close this PR in the meantime as it has been stale for a long time. Feel free to open it again in the future.

**Pull request closed without merging**
