### PR TITLE
Conv2D

### PR DESCRIPTION
**Pull request by shapeetha**

### CODE REVIEW

**Comment by danielmunioz** [comment]
Hey @shapeetha, thanks for contributing!

There is a small issue, it seems that you are implementing a paddle frontend function, for frontend functions it's not allowed to use a function from another one as alias (i.e. using a tf frontend function as alias on the paddle frontend), in this case (if there are no aliases available in the paddle frontend), you can follow the [contributing frontends guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) and implement the frontend function as usual

Also is this for a ToDo list task? if so then you need to create an issue and link it with the to do list and you PR, as described in the [contributing guide](https://lets-unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues), you would need to comment your issue in the ToDo list with this format `- [ ] #Issue_number`, as well as commenting your PR in the issue like this: `Close #Issue_number`, this is necessary so that the PRs get linked to their respective issues and get closed once the job is done!

If you have any questions please don't hesitate to reach out! :)

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by danielmunioz** [comment]
This issue has been stale for more than 2 weeks.
Hence I'm closing it now.
Sorry for any inconveniences.

**Pull request closed without merging**
