### PR TITLE
added erf function to jax lax operators and its tests

### LINKED ISSUE #14200: erf

### PR DESCRIPTION
**Pull request by kundakinte**
close #14200

### CODE REVIEW

**Comment by kundakinte** [comment]
hey @karalleyna, hope you’re doing well, if you’re free kindly review my pull request

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by kundakinte** [comment]
hello, i’m waiting on a review

**Comment by kundakinte** [comment]
hello @karalleyna , waiting for a review :)

**Comment by kundakinte** [comment]
no worries

**Pull request closed without merging**
