### PR TITLE
feat: add heaviside method to paddle frontend 

### LINKED ISSUE #26492: heaviside

### PR DESCRIPTION
**Pull request by muhammadhammad-tech**
Fixes #26492

# PR Description
Implemented heaviside for tensor.py and test for test_tensor.py

## Related Issue

Close #26492

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by muhammadhammad-tech** [comment]
@kgmann hey kindly review it quickly thank  you.

**Comment by muhammadhammad-tech** [comment]
@HaiderSultanArc can you look at this and merge it thank you.

**Comment by muhammadhammad-tech** [comment]
@MahmoudAshraf97 kindly look at it

**Comment by muhammadhammad-tech** [comment]
@ivy-branch

**Review by NripeshN — APPROVED** [review]

**Pull request merged**
