### PR TITLE
Signbit

### LINKED ISSUE #4362: signbit
signbit #1525

### PR DESCRIPTION
**Pull request by devenderbutani21**
close #4362

### CODE REVIEW

**Comment by devenderbutani21** [comment]
@modanesh Is there an issue in the code?

**Comment by modanesh** [comment]
Sorry for the late reply. Have you been able to run tests locally? Asking this because the `test_numpy_signbit` is failing. For example, at `miscellaneous.py:283`, I'm getting this: `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`.

**Comment by devenderbutani21** [comment]
@modanesh I have tried to make the change in the frontend so please check it out. Also, I am getting this error while trying to run docker on my pc. `"Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory."`

**Comment by modanesh** [comment]
For the docker issue, try to update docker image (and restart it just in case). Regarding the commit, there are 2 lint failures. Check the lint logs to see more details. There are also `test-frontend-numpy` failures for the `signbit()`. As I went through them, they're mostly raising the `np not being defined` errors.

**Comment by modanesh** [comment]
Hi, 
There're still failing tests mostly with this error: `NameError: name 'np' is not defined` which is in the changes of the `test_miscellaneous.py` file. There're also changes applied to the `test_array_api` which I'm not sure if necessary or not.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
