### PR TITLE
add swapaxes frontends.torch

### PR DESCRIPTION
**Pull request by PatternFinder**
link to issue: #2704

### CODE REVIEW

**Comment by PatternFinder** [comment]
question: since I've only edited the torch test functions, how come others' edits under the tensorflow test functions' lintting error is showing up on this PR? like so,

```
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tf_functions.py:260:1: W391 blank line at end of file
```

**Comment by Auxia** [comment]
Hi!

Could you please install the [pre-commit](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit) hooks. This should fix the linting errors for you when you stage files for commit.

**Comment by PatternFinder** [comment]
alright, thanks for the tip, for now can you take a look at this PR's code and let me know what I can do to fix them?

**Comment by Auxia** [comment]
The tests are not showing failures on your function. Either way, I would suggest fixing the lint errors with the above suggested solution and creating a new commit on this PR. Some errors can be caused by lint errors.

**Pull request closed without merging**
