### PR TITLE
unset_default_float_dtype #6647

### PR DESCRIPTION
**Pull request by ojumah20**
issue #6647

### CODE REVIEW

**Comment by ojumah20** [comment]
I have commited

**Comment by nathzi1505** [comment]
Hi @ojumah20, would you mind pulling the checklist out as mentioned in the guide [here](https://lets-unify.ai/ivy/contributing/open_tasks.html#formatting-checklist)? This will help in ensuring all requirements are covered successfully. Once you are done feel free to reply here and I will go through your PR once again.

Thanks 😊

**Comment by ojumah20** [comment]
add_reformatting_checklist_data_type

**Comment by ojumah20** [comment]
add_reformatting_checklist_DataTypes

**Review by AnnaTz — CHANGES_REQUESTED** [review]
Please revert the changes you made in code outside your assigned function `unset_default_float_dtype`. They are causing test failures.

**Comment by ojumah20** [comment]
@AnnaTz  alright, I'll do that now

**Pull request closed without merging**
