### PR TITLE
update inf constant to conform to Array API Standard #150

### PR DESCRIPTION
**Pull request by HettyPatel**

### CODE REVIEW

**Comment by HettyPatel** [comment]
@djl11 does this look okay?

**Comment by djl11** [comment]
Thanks a lot for the PR!

I'll need to rebase this to the latest master branch before continuing. Could you please give me [write access](https://stackoverflow.com/questions/35278957/can-i-modify-someone-elses-pull-request-and-push-it-back-in-its-branch/49854013#:~:text=When%20creating%20a%20pull%20request,commit%20changes%20to%20your%20PR.&text=So%20if%20you%20want%20to,to%20give%20you%20this%20permission.) to the PR? 🙂

**Comment by djl11** [comment]
> > 
> 
> Hey @djl11 the "Allow Edits by maintainers" box is checked do I need to do anything else?

No that's all good! Thanks!

**Comment by djl11** [comment]
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

**Review by djl11 — CHANGES_REQUESTED** [review]
Could you remove the modifications to the array_api_tests? These are no longer needed :)

**Comment by HettyPatel** [comment]
> Could you remove the modifications to the array_api_tests? These are no longer needed :)

Hey just reverted the changes in array_api_tests folder

**Comment by HettyPatel** [comment]
@djl11  Just checking if you've had the time to look at this.

**Comment by dmarinere** [comment]
You have worked on only torch, I think you need to work on Tensorflow and Numpy

**Comment by HettyPatel** [comment]
Hey @dmarinere all tests were passing right before I reverted the changes that I made in array_api_tests due to @djl11 's request. 

Should I keep the changes reverted and try to make it work? 

Or since a lot of the code has been rebased should I update my fork to the latest code and start from the beginning?

**Comment by mattbarrett98** [comment]
finished off in PR #719

**Pull request closed without merging**
