### PR TITLE
Updated lu_solve to calculate solution of a batch of matrices

### PR DESCRIPTION
**Pull request by moezAhmad**

### CODE REVIEW

**Comment by moezAhmad** [comment]
#1546

**Comment by moezAhmad** [comment]
lu_solve #15943

**Review by Sam-Armstrong — COMMENTED** [review]
Hi @moezAhmad,

There's a few things that need updating here, first .devcontainer/build/devcontainer.json and .idea/ivy.iml should not be updated, so please can you remove your changes to these?

The function you created needs to be decorated with to_ivy_arrays_and_back. Also please could you write a test for this function in ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py? 
You can find out more about this here:
https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#ivy-frontend-tests

Thanks!

**Comment by moezAhmad** [comment]
Hello, @Sam-Armstrong.
I appreciate your code review. I'm currently encountering an issue and believe that utilizing the function ivy.lu_solve might be necessary to simplify problem. To address this problem, I have created an issue (ivy.lu_solve #16069) as instructed in the documentation. I would appreciate your guidance on whether I should proceed with this pull request or choose an alternative one.

Thanks

**Comment by Sam-Armstrong** [comment]
@moezAhmad Thanks for making that issue, looks like Anna has added it to the list of todo items. It makes sense for it to be implemented in the ivy functional api before we look to implement it in any frontends, so it is probably worth waiting until that is done before we look to complete this pull request. If you were interested in adding lu_solve to the functional api as a separate pull request, that would be greatly appreciated! If you are interested it's on the list here: https://github.com/unifyai/ivy/issues/3856

Thanks for your work on this, and the good suggestion!
Sam

**Comment by moezAhmad** [comment]
@Sam-Armstrong,
Thank you for replying. I am new to contributing to Ivy, and the deep dive section is a bit overwhelming for me. I have created a new PR for another issue, and I thank you for your guidance. I would like to know if I will be notified when the ivy.lu_solve method is implemented.

**Comment by Sam-Armstrong** [comment]
No worries! Unfortunately we can't notify you directly when this is resolved, but if you keep an eye on the list https://github.com/unifyai/ivy/issues/3856 it should get checked off once it has been completed.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
