### PR TITLE
refactor: dev_util

### LINKED ISSUE #26072: dev_util

### PR DESCRIPTION
**Pull request by Anik-et**
Close #26072

### CODE REVIEW

**Comment by Daniel4078** [comment]
ivy-gardener

**Comment by Daniel4078** [comment]
Hello, please do not forget to add a comment for the Reformatting Task Checklist. Thank you! Here is the deep dive document for it(https://lets-unify.ai/ivy/contributing/open_tasks.html#formatting-checklist)

**Comment by Anik-et** [comment]
add_reformatting_checklist_device

**Comment by Anik-et** [comment]
@Daniel4078

**Review by Daniel4078 — COMMENTED** [review]
It looks good for now, are you sure there are no other changes to be done? Like update the docstring of the function?

**Comment by Anik-et** [comment]
Found sufficient examples in the docstring with explanatory comments, It looks good to me but let me know if there are any suggestions.

**Pull request merged**
