### PR TITLE
triplet_margin_loss

### PR DESCRIPTION
**Pull request by Dhruv2012**
Close https://github.com/unifyai/ivy/issues/10609

### CODE REVIEW

**Review by zaeemansari70 — COMMENTED** [review]
Hi @Dhruv2012  ,
Do request a review from me by just commenting on the PR once you are done with the implemetation slightly_smiling_face

**Comment by Dhruv2012** [comment]
> Hi @Dhruv2012 , Do request a review from me by just commenting on the PR once you are done with the implementation 🙂

Hi @zaeemansari70,
Yes, I am already done with the implementation. It can be taken up for review 🙂
Thanks!!

**Review by zaeemansari70 — COMMENTED** [review]
Hi @Dhruv2012 , 
There was a force push to Ivy due to which your branch will have conflicts.
Can you please resolve the conflicts?

I hope you understand!
Thanks :slightly_smiling_face:

**Comment by Dhruv2012** [comment]
hi @zaeemansari70,
I have fixed it. It can be taken up for review 🙂 and hopefully be merged.

Thanks!

**Review by zaeemansari70 — APPROVED** [review]
Lgtm!
I hope you enjoyed contributing to Ivy, looking forward to your contributions in the future too 🙂
Thanks!

**Pull request merged**
