### PR TITLE
FIX! Fix Ivy Failing Test: paddle - elementwise.allclose

### LINKED ISSUE #28165: Fix Ivy Failing Test: paddle - elementwise.allclose

### LINKED ISSUE #28194: Fix Ivy Failing Test: jax - elementwise.allclose

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
# PR Description
On 100 numbers of examples it passing locally

allclose-appde

## Related Issue

Closes #28165
Closes #28194
## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Review by samthakur587 — CHANGES_REQUESTED** [review]
Hii @MuhammadNizamani it  looks like all the backend has not support of bfloat16 you can just at assume("bfloat16" not in input_dtype[0]). see if it's works.

**Comment by samthakur587** [comment]
```python
@with_unsupported_device_and_dtypes(
    {"2.6.0 and below": {"cpu": ("float16",)}},
    backend_version,
)
```
and 

image

**Comment by MuhammadNizamani** [comment]
@samthakur587  new changes are working for all 

paddle_allclose new changes

**Review by samthakur587 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
