### PR TITLE
Silu activate function added to paddle frontends

### PR DESCRIPTION
**Pull request by Lucifer60**
Silu activation

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by Lucifer60** [comment]
The silu function tests are mostly passed, while I have cheked those unpassed ones, either "No files were found with the provided path: ivy/new_failures_31.txt. No artifacts will be uploaded."

Or they would be timed out problem. 
While the code is simple:
def silu(x, name=None):
    return ivy.multiply(x , ivy.sigmoid(x))
    
And I think this shouldn't be something wrong. Could get access.

**Comment by Aarsh2001** [comment]
Hey @Lucifer60, please mention the #issue_number as directed in the guide. Also, you should be writing a test for the same, thanks !

**Comment by Aarsh2001** [comment]
Closing this PR due to inactivity, feel free to reopen once you're ready with the changes, thanks 🙂

**Pull request closed without merging**
