### PR TITLE
WIP: accumulate #3897

### PR DESCRIPTION
**Pull request by ddzhulaii**
accumulate #3897

### CODE REVIEW

**Comment by ddzhulaii** [comment]
Hello 👋  I have a few questions about this issue.
I was thinking about three possible ways to solve it:

1. Use already available NumPy functionality (as it's all already implemented in C): use a native NumPy method as input for `method` and convert the input array `array` to a NumPy array -> I believe this does not fit the whole idea of Frontend API (using only Ivy functions)
2. Take as input an Ivy method, for instance, `ivy.add` or `ivy.multiply`, and then with the bunch of if...else use already implemented `ivy.cumsum` , `ivy.cumprod`, etc. But this does not look future proof for me?

What do you think? Thanks in advance :)

**Comment by kimbring2** [comment]
@ddzhulaii Hello, thank you for your PR. I need some time to answer your question well. 

Additioanlly, you need to write a test code for the Frontend function (:

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
