### PR TITLE
Implemented a frontend for tensorflow.linalg.set_diag function

### PR DESCRIPTION
**Pull request by habedi**
Hi,

I added a frontend implementation for the `tensorflow.linalg.set_diag` function. 

It's related to this issue [Add Linear Algebra functions for TensorFlow frontend #1546 ](https://github.com/unifyai/ivy/issues/1546). Furthermore, I opened a new issue to own the subtask of implementing the frontend for `tensorflow.linalg.set_diag` that is available here: [set_diag #20796](https://github.com/unifyai/ivy/issues/20796).

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Hey,

Thanks for opening this PR and this is a great first implementation.

However, I feel that we should most definitely make use of the diag and diagonal functions already in Ivy's API rather than just looping through the matrix.

What do you think?

**Comment by habedi** [comment]
Hey,

I agree, but I could not find any ivy function that I could use to implement updating diagonals. (I'm very new to Ivy's APIs.)

In addition, `tensorflow.linalg.set_diag` is not a normal function. it copies the input tensor (in the case of Ivy, input array) and applies an update on the diagonals. Most functions don't need updating, they mainly only read, or read and compute some values instead of applying updates.

Anyhow, do you recommend any sets of functions from the `ivy` namespace that you think could be relevant or even useful for implementing a frontend for `tensorflow.linalg.set_diag`? Again, I'm not very familiar with the API at the moment.

**Comment by jkeane508** [comment]
> Hey,
> 
> I agree, but I could not find any ivy function that I could use to implement updating diagonals. (I'm very new to Ivy's APIs.)
> 
> In addition, `tensorflow.linalg.set_diag` is not a normal function. it copies the input tensor (in the case of Ivy, input array) and applies an update on the diagonals. Most functions don't need updating, they mainly only read, or read and compute some values instead of applying updates.
> 
> Anyhow, do you recommend any sets of functions from the `ivy` namespace that you think could be relevant or even useful for implementing a frontend for `tensorflow.linalg.set_diag`? Again, I'm not very familiar with the API at the moment.

Hey,

Yea are absolutely right there is no function that recreates this behaviour exactly but we have [`ivy.diag()`](https://unify.ai/docs/ivy/docs/functional/ivy/linear_algebra/ivy.functional.ivy.linear_algebra.diag.html#diag which allows you to get the diagonal of the matrix. So possibly you could use this to get the diagonal to update (which would add support for k values). Then use like a mask to update the diagonal values in the original matrix.

What do you think?

**Comment by habedi** [comment]
> > Hey,
> > I agree, but I could not find any ivy function that I could use to implement updating diagonals. (I'm very new to Ivy's APIs.)
> > In addition, `tensorflow.linalg.set_diag` is not a normal function. it copies the input tensor (in the case of Ivy, input array) and applies an update on the diagonals. Most functions don't need updating, they mainly only read, or read and compute some values instead of applying updates.
> > Anyhow, do you recommend any sets of functions from the `ivy` namespace that you think could be relevant or even useful for implementing a frontend for `tensorflow.linalg.set_diag`? Again, I'm not very familiar with the API at the moment.
> 
> Hey,
> 
> Yea are absolutely right there is no function that recreates this behaviour exactly but we have [`ivy.diag()`](https://unify.ai/docs/ivy/docs/functional/ivy/linear_algebra/ivy.functional.ivy.linear_algebra.diag.html#diag) which allows you to get the diagonal of the matrix. So possibly you could use this to get the diagonal to update (which would add support for k values). Then use like a mask to update the diagonal values in the original matrix.
> 
> What do you think?

I'll check that. Thanks for the tip.

**Comment by habedi** [comment]
I rewrote the code for updating the diagonals in the frontend function for `tensorflow.linalg.set_diag`. Before, it was using a for loop. Now, it's using IvyArray's indexing API. 

It seems to me that IvyArray has a matrix/array indexing API very similar to NumPy. I'm assuming it is fast. Given that, I think this change resolves the efficiency issue.

**Review by jkeane508 — CHANGES_REQUESTED** [review]
Just need to resolve conflicts here

**Comment by habedi** [comment]
> Just need to resolve conflicts here

I fixed the merge conflicts. Some of the tests failed, but I don't think they are related to my code.

Is there anything left to do?

**Review by jkeane508 — APPROVED** [review]
LGTM!

**Pull request merged**
