### PR TITLE
Added lu_solve to PyTorch Frontend

### LINKED ISSUE #22754: lu_solve

### PR DESCRIPTION
**Pull request by NoahWaltman**
# PR Description 

## Related Issue 
lu_solve #22754

Close #22754 

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Hi thanks for the PR, can you implement the tests of the function?

**Comment by NoahWaltman** [comment]
@a0m0rajab Hi! Could you take a look at the new commit where I implemented the test function?

**Comment by a0m0rajab** [comment]
Thanks, we can wait Rick to check this. Meanwhile, could you check the lint issue? I think the docs is explaining how to do it.

**Comment by NoahWaltman** [comment]
ivy-gardener

**Comment by NoahWaltman** [comment]
@RickSanchezStoic

**Comment by RickSanchezStoic** [comment]
Hi @NoahWaltman can you see the `intelligent-tests-pr / run_tests (1) (pull_request) ` logs and try fixing the errors.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by he11owthere** [comment]
Hello there! Nice work but tests on CI are still failing for all the backends:
https://github.com/unifyai/ivy/actions/runs/7344883998/job/19997453454?pr=22922#step:6:15

**Review by he11owthere — CHANGES_REQUESTED** [review]
Hello there! Nice work but tests on CI are still failing for all the backends:
https://github.com/unifyai/ivy/actions/runs/7344883998/job/19997453454?pr=22922#step:6:15

**Comment by ivy-seed** [comment]
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

**Pull request closed without merging**
