### PR TITLE
paddle.tensor.linalg.dot

### LINKED ISSUE #16133: dot

### PR DESCRIPTION
**Pull request by benkimz**
Close #16133

### CODE REVIEW

**Comment by aparajith21** [comment]
ivy-gardener

**Comment by aparajith21** [comment]
Hi! Thanks for contributing! Please write the name of function in the task name and the issue number in the description so it gets linked appropriately

**Comment by benkimz** [comment]
> Hi! Thanks for contributing! Please write the name of function in the PR name and the task number in the description so it gets linked appropriately

Hi too, 
I have placed the function name in backticks to highlight it.
Thank you!

**Comment by aparajith21** [comment]
Hey, sorry just a minor thing - could you place the function name in PR like paddle.tensor.linalg.dot without the close # and have close # in the description! This is so everything gets linked properly! Thanks again

**Comment by benkimz** [comment]
> Hey, sorry just a minor thing - could you place the function name in PR like paddle.tensor.linalg.dot without the close # and have close # in the description! This is so everything gets linked properly! Thanks again

Close #16133 
Like that?

**Pull request closed without merging**
