### PR TITLE
Added paddle_statistical_nanmedian

### PR DESCRIPTION
**Pull request by Dev-Khant**
Solves #14694

### CODE REVIEW

**Comment by Dev-Khant** [comment]
@theRealBird can you review it and let me know if there are any changes. Thanks!

**Comment by Dev-Khant** [comment]
@MahmoudAshraf97 Can you kindly review it. Thanks

**Comment by theRealBird** [comment]
Hi @Dev-Khant , thank you for your patience. I was on leave for the past week so did not get the chance to review your PR for some days. I will be having a look at it now.

**Comment by Dev-Khant** [comment]
Alright Thanks @theRealBird

**Comment by theRealBird** [comment]
Thank you so much for your contribution @Dev-Khant!

**Comment by Dev-Khant** [comment]
@theRealBird @MahmoudAshraf97 Can anyone of you review it. Thanks

**Comment by theRealBird** [comment]
Hi @Dev-Khant, Thank you so much for your contribution and you patience. Your changes look good to me!

**Pull request merged**
