### PR TITLE
Ivy-tensorflow sort func

### PR DESCRIPTION
**Pull request by Gudini108**

### CODE REVIEW

**Comment by JamieLine** [comment]
Hi! Thanks for the PR!

What you currently have looks good, but for it to be merged it will need a test and that test will need to pass. The docs will have the fine details of how to do that. One thing I will add that isn't in the docs however, is that it is useful to run the tests with the PyTest argument `--backend=all` to ensure it works on all backends.

If you'd like any help with anything, or have any questions or comments, please let me know!

**Comment by Gudini108** [comment]
I did test it and i runned through all 12 checks. Hope everything (or at
least majority of it) is good to go now)

сб, 12 нояб. 2022 г. в 06:02, Jamie Line ***@***.***>:

**Comment by JamieLine** [comment]
Hi!

The test looks good as it is. Normally I would just merge this now, but the test fails in the GitHub Actions CI Page. Try updating your fork to the latest version of Ivy and then changing the `handle_cmd_line_args` decorator to `handle_frontend_function`. There's been an update to how the tests work over the last few days which requires this change.

While you are making edits, I'd recommend changing the `min_value` and `max_value` flags to contain a wider range of values. 

Everything else looks good though! If you have any questions or comments please let me know!

Thanks!

**Comment by Gudini108** [comment]
Okay, gonna change those things today, thanks!

Вт, 15 нояб. 2022 г. в 10:33, Jamie Line ***@***.***>:

**Comment by Gudini108** [comment]
Rewrote function and test. Will make commit and PR soon

вт, 15 нояб. 2022 г. в 09:33, Jamie Line ***@***.***>:

**Comment by Gudini108** [comment]
Alright. I synced all changes to my local "tensorflow-sort-func" branch and
tested changes. Let me know if there is anything else that needs fixing.

чт, 17 нояб. 2022 г. в 19:17, Jamie Line ***@***.***>:

**Pull request closed without merging**
