### PR TITLE
Reformat linear_algebra / cross

### PR DESCRIPTION
**Pull request by virchan**
Issue: https://github.com/unifyai/ivy/issues/1204

Added examples to the cross docstring.

### CODE REVIEW

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

can you add Functional Examples and Instance Method Examples following all the points as indicated in the docstring examples here(https://github.com/unifyai/ivy/blob/master/docs/partial_source/contributing/13_docstring_examples.rst).

**Comment by virchan** [comment]
> Hi,
> 
> can you add Functional Examples and Instance Method Examples following all the points as indicated in the docstring examples here(https://github.com/unifyai/ivy/blob/master/docs/partial_source/contributing/13_docstring_examples.rst).

Hello,

Thank you for reaching out. I have added Functional Examples and Instance Method Examples accordingly.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Thanks for making changes but a few more are required. Can you also add example for ivy.Container() ( you can add ivy.Container in the type hint for inputs in this fucntion) and combination of ivy.Container() and ivy.array() (point 8 and 9 in the docstring respectively).
Also 1 example of instance method is required using Container as well (point 11).

**Comment by virchan** [comment]
Hello,

Thank you for replying. I have:

1.  included ivy.Container() in the type hint.
2. added ivy.Container() examples to functional examples and instance method examples.
3. added an example of  a combination of ivy.Container() and ivy.array()  to the functional examples.

Please let me know if there is anything else I need to do. Thank you for your time.

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Everything looks good. I think you accidentally committed changes to the .idea file. Can you kindly remove that from the commit, I'll merge your changes as soon you do that :)

**Comment by virchan** [comment]
Hello,

I have removed the .idea file. Your feedbacks were really helpful. Thank you!

**Pull request merged**
