### PR TITLE
Add sigmoid activation to Paddle frontend and test

### LINKED ISSUE #18312: sigmoid

### PR DESCRIPTION
**Pull request by peterwisu**
Close #18312

### CODE REVIEW

**Comment by V-G-spec** [comment]
Thanks for your contribution @peterwisu! Do you mind taking a look at the failing tests?

**Comment by V-G-spec** [comment]
Just ping me here when you're done with your final changes

**Comment by D0m-inic** [comment]
PR looks good, but could you change the `@with_supported_types` to be `2.5.1 and below`, and could you add the `backend_to_test` parameter to the test

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by hmahmood24** [comment]
Hey @peterwisu, do you still want to work on this PR? If so, can you please resolve the merge conflicts and look at the failing tests [here](https://github.com/unifyai/ivy/actions/runs/5922519628/job/16056609796?pr=19394)? Thanks

**Comment by hmahmood24** [comment]
Closing this PR since it has been stale from more than a month now.

**Pull request closed without merging**
