### PR TITLE
added broadcast_arrays

### LINKED ISSUE #13561: broadcast_arraus

### PR DESCRIPTION
**Pull request by rajshukla1102**
Close #13561

### CODE REVIEW

**Comment by rajshukla1102** [comment]
@sherry30 can you please review this pr

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi @rajshukla1102 ,

The helper function `dtype_and_values` always produces the same shapes for all the generated arrays so this wouldn't really test the broadcast able shapes.
Instead you can see [here](https://github.com/unifyai/ivy/blob/520c235d46c05335b94fb2ac87b853237c522972/ivy_tests/test_ivy/test_functional/test_core/test_dtype.py#L108) a better way to test this function as it is also being tested in ivy API. you can simply use this function to generate broadcast able shapes.

Let me know if you have any questions 😄 
Thanks

**Review by sherry30 — CHANGES_REQUESTED** [review]
Hi,

Your PR mostly looks good and the tests are passing but the lint formatting tests are failing. 
Can you quickly fix those, they shouldn't be too difficult.
I'll merge your PR as soon as you do 😃 

Thanks

**Review by rajshukla1102 — COMMENTED** [review]
@sherry30  i have fixed the lints

**Pull request merged**
