### PR TITLE
taskdo1

### PR DESCRIPTION
**Pull request by Juligee**
My first pull request for todotask

### CODE REVIEW

**Comment by Juligee** [comment]
I am just starting, but I now about to add some solution to the task. I am working on it right now. 
I would ask questions were I am stuck for too long. Thank you.

**Comment by Juligee** [comment]
Hello,
I just updated my code in github space. I wanted to confirm if you found it. 
image

**Comment by Juligee** [comment]
I have now made update in my pull request.

**Comment by Juligee** [comment]
I unknowingly commit to this tdo1 branch.

**Comment by a0m0rajab** [comment]
It's okay you can commit merge it to your master and do that, or even if you like you can open a new PR.

**Comment by Juligee** [comment]
@a0m0rajab l will like to ask do l need to create a new PR for every commit of new issues solution

**Comment by Juligee** [comment]
Or merge every new commit from issues to an existing branch from master

**Comment by a0m0rajab** [comment]
I did not totally understand your question but for every task (issue) you need to open a PR, 
and if you make a commit for that issue in the same pr it should be one PR. 

for example if you take: 
cos and sin functions, each of them need to have a PR. 
but if you do things related to cos and commit them, they will need to stay in the cos pr.

**Comment by Juligee** [comment]
Good morning, 

It clearer now. I have this understanding. I think I need to get the point why when I create another new PR I get the question: 
1. commit directly to the master file 
2. create new branch for this commit and start a new pull request

**Pull request closed without merging**
