### PR TITLE
floor

### LINKED ISSUE #1525: Add Mathematical functions to Numpy Frontend
Add [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html#) to Numpy frontend:

- [ ] sin
- [ ] cos
- [ ] tan
- [ ] arcsin
- [ ] arccos
- [ ] arctan
- [ ] hypot
- [ ] arctan2
- [ ] degrees
- [ ] radians
- [ ] unwrap
- [ ] deg2rad
- [ ] rad2deg
- [ ] sinh
- [ ] cosh
- [ ] tanh
- [ ] arcsinh
- [ ] arccosh
- [ ] arctanh
- [ ] around
- [ ] round_
- [ ] rint
- [ ] fix
- [ ] floor
- [ ] ceil
- [ ] trunc
- [ ] prod
- [ ] sum
- [ ] nanprod
- [ ] nansum
- [ ] cumprod
- [ ] cumsum
- [ ] nancumprod
- [ ] nancumsum
- [ ] diff
- [ ] ediff1d
- [ ] gradient
- [ ] cross
- [ ] trapz
- [ ] exp
- [ ] expm1
- [ ] exp2
- [ ] log
- [ ] log10
- [ ] logaddexp
- [ ] logaddexp2
- [ ] i0
- [ ] sinc
- [ ] signbit
- [ ] copysign
- [ ] frexp
- [ ] Idexp
- [ ] nextafter
- [ ] spacing
- [ ] lcm
- [ ] gcd
- [ ] add
- [ ] reciprocal
- [ ] positive
- [ ] negative
- [ ] multiply
- [ ] divide
- [ ] power
- [ ] subtract
- [ ] true_divide
- [ ] floor_divide
- [ ] float_power
- [ ] fmod
- [ ] mod
- [ ] modf
- [ ] remainder
- [ ] divmod
- [ ] angle
- [ ] real
- [ ] imag
- [ ] conj
- [ ] conjugate
- [ ] maximum
- [ ] fmax
- [ ] amax
- [ ] nanmax
- [ ] minimum
- [ ] fmin
- [ ] amin
- [ ] nanmin
- [ ] convolve
- [ ] clip
- [ ] sqrt
- [ ] cbrt
- [ ] square
- [ ] absolute
- [ ] fabs
- [ ] sign
- [ ] heaviside
- [ ] nan_to_num
- [ ] real_if_close
- [ ] interp

### LINKED ISSUE #22574: floor

### PR DESCRIPTION
**Pull request by alikara345**
# PR Description

## Related Issue

Close #22574

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@alikara345 kindly link the issue you are working on.

**Comment by alikara345** [comment]
Add Mathematical functions to Numpy Frontend #1525
floor #22574

**Comment by soma2000-lang** [comment]
You need to implement the function and write  test for it just as the other has been done

**Comment by alikara345** [comment]
@soma2000-lang  hi can you look results

**Comment by soma2000-lang** [comment]
You need to write the test foe the following added function.kindly cjeck how the other functions have been added.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Pull request closed without merging**
