### PR TITLE
add cosh to trigonometric_functions.py

### PR DESCRIPTION
**Pull request by Change-m**

### CODE REVIEW

**Comment by Change-m** [comment]
> #2689

**Comment by Change-m** [comment]
Hi [bicycleman15](https://github.com/bicycleman15), 
Can you guide me about the problems?

**Comment by bicycleman15** [comment]
Hey @Change-m , this PR is for cosh frontend function, however, you added some `multiply` function as well. Could you explain this additional function ?
Also there are changes in docstring files too.

As far as I know, this PR should not require touching those files.

**Comment by Change-m** [comment]
Hi [bicycleman15](https://github.com/bicycleman15), I make the required changes also added the test for cosh.

**Comment by Change-m** [comment]
#3636

**Pull request merged**
