### PR TITLE
add log1p to jax

### PR DESCRIPTION
**Pull request by PatricYan**
- [ ] #3560

### CODE REVIEW

**Comment by PatricYan** [comment]
Hi @ankitdsi2010 , would you like to make a review for the PR?

**Review by ankitdsi2010 — CHANGES_REQUESTED** [review]
resolve why the test-frontend-jax tests are failing as given [here](https://github.com/unifyai/ivy/runs/8057785438?check_suite_focus=true#step:6:64)

**Comment by PatricYan** [comment]
> resolve why the test-frontend-jax tests are failing as given [here](https://github.com/unifyai/ivy/runs/8057785438?check_suite_focus=true#step:6:64)

Done

**Review by ankitdsi2010 — APPROVED** [review]

**Comment by ankitdsi2010** [comment]
closes #3560

**Pull request merged**
