### PR TITLE
EHN: gcd added in torch tensor.py

### LINKED ISSUE #20951: gcd

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
Closed #20951
Paddle is showing some issues so i have ignore that and review please help to resolver

### CODE REVIEW

**Comment by selvaraj-sembulingam** [comment]
Hi @MuhammadNizamani 

Its not correct to skip test cases for a specific backend.

Kindly use `with_supported_dtypes` decorator in the frontend function

Thanks

**Comment by MuhammadNizamani** [comment]
@selvaraj-sembulingam  I have corrected it Now I am using all backend. please check my test method.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by MuhammadNizamani** [comment]
@selvaraj-sembulingam  This PR got steal and on one carry these type things in this repo.

**Pull request closed without merging**
