### PR TITLE
feat: Update fft.py

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
#19383

### CODE REVIEW

**Comment by ivy-leaves** [comment]
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

**Comment by jaskiratsingh2000** [comment]
@a0m0rajab this issue is not being done by anyone. This is a sub task of many functions. Could you once please review it again?

**Comment by jaskiratsingh2000** [comment]
@a0m0rajab I by mistakenly added wrong issue

**Comment by a0m0rajab** [comment]
The issue is having open PR and it's been active. If you think you have added the wrong number of the issue please feel free to edit the PR description and let me know. 
image

**Comment by a0m0rajab** [comment]
the link to the open PR though; https://github.com/unifyai/ivy/pull/23647

**Comment by jaskiratsingh2000** [comment]
@a0m0rajab Just a confusion. Yes so this issue has been stale so long and have not been reviewed so that's why I decided to work on this. There are lots of multiple issue similar to this so I was confused if I mentioned the correct one here. Anyways yes so since previous PR was also failing test cases if I'm not wrong so that's why I worked on this

**Pull request closed without merging**
