### PR TITLE
added nan_to_num

### PR DESCRIPTION
**Pull request by vandit98**
nan_to_num #11111
hi @MahmoudAshraf97
As adviced by you. I have used tensorflow implementation of nan_to_num in paddle framework and implemented it.
Please review it.
Thanks

### CODE REVIEW

**Review by MahmoudAshraf97 — CHANGES_REQUESTED** [review]
AssertionError: the ground truth framework torch returned a float32 datatype while the backend paddle returned a float64 datatype

**Comment by vandit98** [comment]
hi @MahmoudAshraf97
Can u help me with this error. I have tried to run test for allclose.
Is there any documents or resources for doing this.
image

**Comment by MahmoudAshraf97** [comment]
did you recheck that test_allclose exists in this file?

**Comment by vandit98** [comment]
hi @MahmoudAshraf97 
Yes it do exist.
Screenshot from 2023-03-08 17-56-02

also when i am trying to pass float32 , i am encountering this issue. Due to which i have to convert the input:x to float64. Because this way it is working for each datatype.

image

**Pull request closed without merging**
