### PR TITLE
num_ivy_arrays_on_dev

### PR DESCRIPTION
**Pull request by davidlee1102**
Please check my PR, if have any errors, feel free to let me know. Thank you

### CODE REVIEW

**Comment by simonetgordon** [comment]
Hi David,

Thanks for making a contribution!

In order for the docstring tests to pass, a slight reformatting of the arrays in the examples needs to be done, and there should be no ellipses:
```
>>> A = ivy.array([0, 1, 2])
>>> B = ivy.array([[ 0,  1,  2,  3],
...               [ 4,  5,  6,  7],
...               [ 8,  9, 10, 11]])
```
Should be
```
>>> A = ivy.array([0, 1, 2])
>>> B = ivy.array([[ 0,  1,  2,  3],\
                  [ 4,  5,  6,  7],\
                  [ 8,  9, 10, 11]])
```

Also, there is a small formatting errors detected by lint in. You can see a description of the issue by clicking 'details' on the right of the lint check.

As for the other failing checks, I wouldn't worry too much about these as they are also failing on the master branch.

Thanks again!

Simone

**Comment by davidlee1102** [comment]
Hi Simone,
1. Thank you, that's great, I have updated the \ liked the idea you have told me
2. I have checked the lint error and have fixed, it's better if you can review my code again 😺 
Thank you again!
David

**Comment by simonetgordon** [comment]
Hi David,

Ah yes I see these were not your edits. In any case, the only file that should be altered in this PR is `ivy/functional/ivy/device.py`. Could you try pulling from upstream master to get the latest changes to your branch?

Thanks!

Simone

**Comment by davidlee1102** [comment]
Hi Simon, 
I have done, could you please check on that
Thank you 🙇 
David Lee

**Comment by simonetgordon** [comment]
Hi David,

There are still changes in general.py. Also, if you notice, the lint check is failing in this PR, but not in the latest commits to [master](https://github.com/unifyai/ivy/commits/master). 

Please check that your upstream branch is indeed the master branch of the unifyai/ivy repository.

Thanks!

Simone

**Comment by davidlee1102** [comment]
Hi Simone,
I have check my upstream branch has been up to date, could you please check again. here I am doing
-> in my master branch | I fetch the upstream and merge it into my master
from my branch git fetch origin |  git merge origin/master | and I put the code to my branch again
If you have any questions, feel free to ask me
Thank you!
David

**Comment by simonetgordon** [comment]
Hi David,

You should try `git pull upstream master` on both your master and development branch. There are different kinds of merges possible, and perhaps the current merge is not updating general.py. Also ensure the upstream repo is correct by doing:

```
>>>> git remote -v
origin  git@github.com:unifyai/ivy.git (fetch) # yours will be different
origin  git@github.com:unifyai/ivy.git (push)
upstream        https://github.com/unifyai/ivy.git (fetch) # this should be the same
upstream        https://github.com/unifyai/ivy.git (push)
```

If you still can't find a solution, my advice is to make a new PR from a new development branch on your fork and copy + paste the changes to this function's docstrings.

Kind Regards, 

Simone

**Comment by davidlee1102** [comment]
Hi Simone, 
I have tried but it told me that 
>>>> git checkout master
>>>> git remote -v
origin  https://github.com/davidlee1102/ivy.git (fetch)
origin  https://github.com/davidlee1102/ivy.git (push)
upstream        https://github.com/unifyai/ivy.git (fetch)
upstream        https://github.com/unifyai/ivy.git (push)
>>>> git pull upstream master
From https://github.com/unifyai/ivy
 * branch                master     -> FETCH_HEAD
Already up to date.
---
Could you please take a look on my code, if it still not changes, please let's me know, I will create other branch in order to write docstring and I will push -f to my PR branch
Thank you!
David Lee

**Comment by simonetgordon** [comment]
Hi David,

You are able to check yourself if it has worked 😊 At the top of this PR, you can see that the 'Files Changed' tab has 2 files in it. You will know the issue has been fixed when there is just one file here. Also, this check: lint / check-formatting (pull_request) should be passing.

Again, I think making a new PR is the best course of action.

Kind Regards, 

Simone

**Comment by davidlee1102** [comment]
Thank you, I will close this PR and open another PR, thank you 🙇

**Pull request closed without merging**
