### PR TITLE
isnat function

### PR DESCRIPTION
**Pull request by ndurumo254**
mistakenly delated some files in the previous pull request and i could not recover the branch🤦‍♀️

### CODE REVIEW

**Comment by ndurumo254** [comment]
Is anyone checking on the PR?

**Comment by johanjino** [comment]
> Is anyone checking on the PR?

Hey Yes, I will be checking through the PR 🙂. Sorry for the delay

**Comment by ndurumo254** [comment]
> > Is anyone checking on the PR?
> 
> Hey Yes, I will be checking through the PR 🙂. Sorry for the delay
cool
waiting for your guidance. experiencing some challenges on the tests

**Comment by johanjino** [comment]
Hey @ndurumo254 , what are the exact problems your facing?

For the lint test to pass, please remove line 154 in ivy_tests/test_ivy/test_frontends/test_numpy/test_logic/test_array_type_testing.py

**Comment by ndurumo254** [comment]
> Hey @ndurumo254 , what are the exact problems your facing?
> 
> For the lint test to pass, please remove line 154 in ivy_tests/test_ivy/test_frontends/test_numpy/test_logic/test_array_type_testing.py

Thanks for your reply.
i was implementing isnat array function that is located in the 
ivy_tests/test_ivy/test_frontends/test_numpy/test_logic/test_array_contents.py
can i still make changes on different file. because the file you have referenced is isnan implementation?

**Comment by ndurumo254** [comment]
> Hey @ndurumo254 , what are the exact problems your facing?
> 
> For the lint test to pass, please remove line 154 in ivy_tests/test_ivy/test_frontends/test_numpy/test_logic/test_array_type_testing.py

it passed 
but am now getting ambiguity in the test core variable. how to go about this

**Comment by johanjino** [comment]
Hey @ndurumo254 , looks good to me now, the errors are not from your implementation! Thank you for your contribution

**Pull request merged**
